### ISSUE TITLE
Crear icono para la Bitcoin Wallet

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#100]
Se desarrollara un icono para identificar la Bitcoin Wallet dentro de la Wallet Store.

**Comment by arnaldos** [comment]
viene del issues #99

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina te comparto los iconos para la Bitcoin Wallet 
Versión 1
![bit coin wallet-04](https://cloud.githubusercontent.com/assets/13594347/9916555/ba228718-5c86-11e5-9ba8-d10ae6285363.jpg)
Versión 2
![bit coin wallet-01](https://cloud.githubusercontent.com/assets/13594347/9916552/b9d5100a-5c86-11e5-89cf-42f63911947c.jpg)
Versión 3
![bit coin wallet-02](https://cloud.githubusercontent.com/assets/13594347/9916553/ba042ef8-5c86-11e5-9b0e-ae6e053c300b.jpg)
Versión 4
![bit coin wallet-03](https://cloud.githubusercontent.com/assets/13594347/9916554/ba1b2f72-5c86-11e5-8c31-6165a79242d9.jpg)

**Comment by Luis-Fernando-Molina** [comment]
@arnaldos Como van a poder haber mas bitcoin wallets, en este caso la tenemos que diferenciar con el autor, que es bitDubai. Asi que el nombre sería bitDubai bitcoin wallet.

Respecto a los iconos, pueden ser, pero me gustaría verlos mas en tamaño real, como quedarían en el desktop de la APP. En alguno de los casos estaba el fondo del desktop, toma esa imagen y poné los iconos ahí por favor. 

Gracias!

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina ok perfecto !! ya realizo los ajustes y los subo

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina  Aquí te comparto los screenshot para poder apreciar el icono 

![sreenshot-bitcoin-wallet](https://cloud.githubusercontent.com/assets/13594347/9919702/64af7e46-5c98-11e5-947b-d470a624f036.png)

![sreenshot-bitcoin-wallet1](https://cloud.githubusercontent.com/assets/13594347/9919703/64b3ac0a-5c98-11e5-816b-bd12f74d8e74.png)

![sreenshot-bitcoin-wallet2](https://cloud.githubusercontent.com/assets/13594347/9919704/64d92cc8-5c98-11e5-9aec-6b322ac22e19.png)

**Comment by arnaldos** [comment]
están muy grandes ya le ajusto el tamaño

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina aquí están mas pequeñas las imágenes para que se vean completas

![sreenshot-bitcoin-wallet3](https://cloud.githubusercontent.com/assets/13594347/9919817/0869fa7a-5c99-11e5-9fbe-e183417d19d8.png)
![sreenshot-bitcoin-wallet4](https://cloud.githubusercontent.com/assets/13594347/9919818/087222ea-5c99-11e5-9f25-5421ba9cdac3.png)
![sreenshot-bitcoin-wallet5](https://cloud.githubusercontent.com/assets/13594347/9919819/08753a34-5c99-11e5-913e-1d8f149e26ea.png)

**Comment by Luis-Fernando-Molina** [comment]
@arnaldos el icono me gusta, los colores tambien, no me convence las iniciales , será porque quizás no se entiendan, o porque pudieran ser algo mas gráfico.

Te envié por email los nuevos iconos de android para que veas que forma tienen. 

Refinemos un poco el tema de lo que dice.

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina  ok perfecto !!! ya reviso el material !!!

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina te comparto una serie nueva de versiones de iconos para la bitcoin wallet

Versión 5
![bit coin wallet-05](https://cloud.githubusercontent.com/assets/13594347/10037715/bf658304-6183-11e5-8ecd-bd2b246e9d6d.jpg)

Versión 6
![bit coin wallet-06](https://cloud.githubusercontent.com/assets/13594347/10037716/bf6e23c4-6183-11e5-81ea-fa13d9a574ed.jpg)

Versión 7
![bit coin wallet-07](https://cloud.githubusercontent.com/assets/13594347/10037717/bf709758-6183-11e5-9b1b-5df2f1db8c92.jpg)

Versión 8
![bit coin wallet-08](https://cloud.githubusercontent.com/assets/13594347/10037718/bf774b16-6183-11e5-8e51-893f7403c073.jpg)

Versión 9
![bit coin wallet-09](https://cloud.githubusercontent.com/assets/13594347/10037719/bf7cce1a-6183-11e5-961f-00d2df343ba7.jpg)

Versión 10
![bit coin wallet-10](https://cloud.githubusercontent.com/assets/13594347/10037720/bf919cb4-6183-11e5-92bb-eb6b0e2e666e.jpg)

Versión 11
![bit coin wallet-11](https://cloud.githubusercontent.com/assets/13594347/10037721/bf9adf54-6183-11e5-8a10-3ba7295a3783.jpg)

Versión 12
![bit coin wallet-12](https://cloud.githubusercontent.com/assets/13594347/10037722/bf9cbaea-6183-11e5-8f0e-bd3b14913fb5.jpg)

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina aquí subo el conjunto de iconos mas pequeños para poder visualizarlos todos juntos recomiendo usar la versión 10.

![bit-coin-wallet_icon](https://cloud.githubusercontent.com/assets/13594347/10037829/741a6c6e-6185-11e5-8675-fa2b0f6a160e.png)

**Comment by arnaldos** [comment]
en esta imagen que están todos juntos seria el nro 6 si lo contamos de izquierda a derecha. :smile_cat:

**Comment by Luis-Fernando-Molina** [comment]
:+1:  nos quedamos con la numero 6 tal como vos proponés. Está muy lindo!
