### ISSUE TITLE
Imagen para representar un ejemplo de IoP (Version Accidentado)

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#1000]
La imagen debe mostrar un accidente en moto de un joven,  sin ser la imagen chocante.  Visto desde media distancia,  desde un punto medianamente elevado. Alrededor del accidentado hay curiosos,  y en las cercanías más gente, caminando o haciendo su vida. Sobre esta foto,  la imagen debe mostrar la foto,  con nombre,  profesión y hobbies del accidentado.  Junto con  los hobbies,  debe haber un icono de familia y otro de amigos.  En esta foto se debe mostrar los perfiles de sus familiares más cercanos asociados al icono de familia,  con el botón de mensaje y llamar como en el caso del auto.  Lo mismo para los 5 amigos más cercanos asociados al icono de amigos. Adicional a todo esto,  la imagen debe mostrar los perfiles de la gente que son médicos de entre toda la gente que hay en la foto.  Con 3 alcanza,  uno puede ser de los que están muy cerca y los otros mucho mas lejos.

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina  te comparto la imagen, no coloque los iconos de mensaje y llamada como en la versión del carro, porque al colocar 5 amistades y 5 familiares esto recargaba la imagen con la cantidad de elementos (iconos de actividades). Por eso tome la decisión de colocar dos fichas una para cada uno de los círculos del motorizado, reuniéndo los contactos en una sola ficha, mostrando los iconos de los hobies y desempeños únicamente al que esta relacionado con la profesión de medicina.

### Versión 1

![image-11](https://cloud.githubusercontent.com/assets/13594347/19138213/85c5541a-8b50-11e6-835a-d5d04219a751.jpg)

**Comment by rosanacoronado** [comment]
@Luis-Fernando-Molina 

## Propuesta_2

![iopaccident_1-01](https://cloud.githubusercontent.com/assets/19508456/19160234/2267b4a4-8bbd-11e6-875b-30217281b2cd.png)

**Comment by Jessicafp** [comment]
Propuesta 3
![propuesta-3](https://cloud.githubusercontent.com/assets/19536846/19171264/d6b97f1a-8be9-11e6-95e1-c0b31eaf621f.png)

@arnaldos @Luis-Fernando-Molina

**Comment by arnaldos** [comment]
chicas integrar mas al tipo de la moto con la imagen

**Comment by karentvillegas** [comment]
### Propuesta 4

![propuesta1](https://cloud.githubusercontent.com/assets/19273211/19190700/005d29ce-8c6d-11e6-8447-5dddc0e482bc.jpg)

@arnaldos @Luis-Fernando-Molina

**Comment by arnaldos** [comment]
@karentvillegas @Jessicafp @rosanacoronado una acotación luis en el comentario sugiere que los médicos no estén tan cerca de la escena del accidente. y al menos 3.

**Comment by arnaldos** [comment]
uno bastante cerca y los otros 2 mas lejos los medicos.

**Comment by Luis-Fernando-Molina** [comment]
Vamos a seguir con la propuesta 4.

Cambios:
1. No debe haber un familiar o amigo favorito. Todos al mismo nivel. 
2. La posiblidad de llamar o mensajear a familiar o amigo debe ser individual para cada uno.
3. El perfil del accidentado no hace falta que tenga casco
4. El icono de la moto esta de mas
5. Para los medicos solo poner el icono de medico, no el de los hobbies. Poner el nombre y apellido en el mismo formato que otros casos.
6. NO entiendo para que esta la hora en la seccion de familia y amigos, sacarla.

**Comment by arnaldos** [comment]
perfecto !

**Comment by karentvillegas** [comment]
### Propuesta 4.1

![propuesta4_1](https://cloud.githubusercontent.com/assets/19273211/19203485/786e8e7a-8ca5-11e6-87d3-e3b077cac69b.jpg)

### Propuesta 4.2

![propuesta4_2](https://cloud.githubusercontent.com/assets/19273211/19203642/5f735be8-8ca6-11e6-9771-ff2910fa930e.jpg)

@arnaldos @Luis-Fernando-Molina

**Comment by karentvillegas** [comment]
### Propuesta 4.3

![propuesta4_3](https://cloud.githubusercontent.com/assets/19273211/19208534/640fdcda-8cc9-11e6-995e-0a2d5fda8bc5.jpg)

@arnaldos @Luis-Fernando-Molina

**Comment by arnaldos** [comment]
@karentvillegas propuesta 4.3 solo faltaría el nombre de los médicos

**Comment by karentvillegas** [comment]
### Propuesta 4.4

![propuesta4_4](https://cloud.githubusercontent.com/assets/19273211/19208981/1119327c-8cd0-11e6-97cd-043a9ecac51c.jpg)

@arnaldos @Luis-Fernando-Molina

**Comment by Luis-Fernando-Molina** [comment]
Solo faltaría ponerle la posibilidad de llamar a los médicos,  o enviarles mensajes.

**Comment by karentvillegas** [comment]
### Propuesta 4.5

![propuesta4_5](https://cloud.githubusercontent.com/assets/19273211/19214375/bb017946-8d4f-11e6-8446-1cc54145a11f.jpg)

@arnaldos @Luis-Fernando-Molina

**Comment by arnaldos** [comment]
listo según el ultimo comentario !

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina cierro el caso ya la imagen esta en el media kit https://github.com/Fermat-ORG/media-kit/blob/master/README.md
