### ISSUE TITLE
Imagen para representar un ejemplo de IoP reputacion

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#1001]
un grupo de jóvenes charlando en una habitación de un hostel visto desde el punto de vista de uno que esta sobre una de las tantas camas de dos niveles. De la foto se debe deducir que es un hostel,  por las mochilas,  los lockers, y el tipo de jóvenes viajeros en la imagen.  De los 3 o 4 en la imagen,  se debe mostrar el perfil con nombre,  profesion (estudiantes de algo)  y hobbies y de cada uno el recuadro con su reputación. Uno de ellos debiera tener una reputación baja.  (igual que en los otros casos los textos de la reputación no deben ser legibles)

**Comment by victoralfonzohd** [comment]
### Propuesta 1

@Luis-Fernando-Molina @arnaldos 

![iop-reputacion](https://cloud.githubusercontent.com/assets/15219855/19098506/9dc9cc7e-8a7b-11e6-83b4-7e7602922d1e.jpg)

**Comment by andiechan** [comment]
**Propuesta 2**

![01](https://cloud.githubusercontent.com/assets/19866300/19099685/be26bc10-8a86-11e6-924e-67a69b221ad0.JPG)

**Comment by andiechan** [comment]
**Propuesta 3**

![02](https://cloud.githubusercontent.com/assets/19866300/19100010/4b020980-8a89-11e6-89b6-5e6de43f6c1f.JPG)

**Comment by victoralfonzohd** [comment]
### Propuesta 4

![iop-reputacion](https://cloud.githubusercontent.com/assets/15219855/19116001/f8ca6b2c-8ae1-11e6-9252-51d28b08cfcb.jpg)

**Comment by arnaldos** [comment]
Recuerden colocar el elemento que identifica la profesión y hobies del usuario de esta manera. 
Falta : 
- El nombre
- Clocar el la profesión de la persona un poco mas grande 

![image](https://cloud.githubusercontent.com/assets/13594347/19120647/ebe4e488-8af9-11e6-8681-73daae307c22.png)

**Comment by victoralfonzohd** [comment]
### Propuesta 5

![iop-reputacion](https://cloud.githubusercontent.com/assets/15219855/19123623/549f81d8-8afd-11e6-8f76-de4eac30762f.jpg)

**Comment by ivonnesantos** [comment]
Propuesta 6
![profile_reputacion-2](https://cloud.githubusercontent.com/assets/15238660/19124981/47432ea8-8b03-11e6-90cb-4cc931c8ab8b.jpg)
@arnaldos

**Comment by proseuz** [comment]
## Propuesta 7

![hostals-01](https://cloud.githubusercontent.com/assets/17308060/19125750/49f3dd3e-8b06-11e6-904b-f51d44a79398.jpg)
@Luis-Fernando-Molina @arnaldos

**Comment by Luis-Fernando-Molina** [comment]
Vamos a seguir solo con la propuesta 5
1. EL ingles esta incorrecto. No se dice student of music, sino music student. Y sabra Dios que otros problemas de lenguaje hay. No lo reviso el traductor o alguien que sepa ingles?

2.Saca lo de FOLLOW
1. Pone los perfiles de las 4 personas y los reviews tambien de los 4.

**Comment by victoralfonzohd** [comment]
### Propuesta 5.1

Esta vez el lenguaje fue revisado por Dave.

![iop-reputacion](https://cloud.githubusercontent.com/assets/15219855/19132350/08d27886-8b21-11e6-9320-253bd342b090.jpg)

**Comment by Luis-Fernando-Molina** [comment]
Para que esta el boton de SELECT PROVIDER????

Sacalo por favor.

**Comment by victoralfonzohd** [comment]
Listo @Luis-Fernando-Molina 

![iop-reputacion](https://cloud.githubusercontent.com/assets/15219855/19158234/fc8939f8-8bb5-11e6-81d2-999f5f608c30.jpg)

**Comment by Luis-Fernando-Molina** [comment]
saca lo de AVAILABLE

**Comment by Luis-Fernando-Molina** [comment]
la estudiante de medicina tambien estudia odontologia? eso no es comun, sacalo y pone otra cosa

**Comment by victoralfonzohd** [comment]
Cambios

![iop-reputacion](https://cloud.githubusercontent.com/assets/15219855/19159412/5baa3078-8bba-11e6-8c0d-375a1c98da51.jpg)

**Comment by Luis-Fernando-Molina** [comment]
Listo cerralo y al media kit
