### ISSUE TITLE
Create a vector image of logo IoP 

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#1002]
https://github.com/Fermat-ORG/iop-blockchain/blob/beta-1.0.0/src/qt/res/icons/IoP.png

**Comment by m471c4** [comment]
@arnaldos this issue is ready. We can close it :)

**Comment by arnaldos** [comment]
el logo esta en el repo en esta dirección

https://github.com/Fermat-ORG/fermat-graphic-design/tree/master/2D%20Design/Fermat/fermat%20logo/internet_of_people_logo
