### ISSUE TITLE
Crear mokups para la web de IoP consortium sección News

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#1003]

**Comment by rosanacoronado** [comment]
@arnaldos 

## Propuesta_1

![web_iop_news_1-02](https://cloud.githubusercontent.com/assets/19508456/19169452/9a2c685c-8be2-11e6-86f9-167833ca1e0a.png)

## Propuesta_2

![web_iop_news_2_2-03](https://cloud.githubusercontent.com/assets/19508456/19170393/39a665ba-8be6-11e6-95e4-b5f95810ccf2.png)

## Propuesta_3

![web_iop_news_3-04](https://cloud.githubusercontent.com/assets/19508456/19169453/9a317482-8be2-11e6-9e23-0a9e55b2f590.png)

## Propuesta_4

![web_iop_news_4-05](https://cloud.githubusercontent.com/assets/19508456/19169454/9a39391a-8be2-11e6-945b-d9e4a024dd88.png)

**Comment by arnaldos** [comment]
propuesta 1 y solo cambia el color de las lineas gris por azul

**Comment by rosanacoronado** [comment]
@arnaldos Ajuste de color 

![web_iopconsortium_newssection1-02](https://cloud.githubusercontent.com/assets/19508456/19199863/319966a2-8c94-11e6-9b58-6829a69077ca.png)
