### ISSUE TITLE
Crear mokups para la web de IoP consortium sección About

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#1004]

**Comment by andiechan** [comment]
**Propuesta 1**

![web-iop_about_01-01](https://cloud.githubusercontent.com/assets/19866300/19172427/cd1b7944-8bef-11e6-9762-ac3adec35874.png)

**Comment by andiechan** [comment]
**Propuesta 2**
![web-iop_about_02](https://cloud.githubusercontent.com/assets/19866300/19173327/ca5dfba0-8bf4-11e6-8368-03254e005a57.png)

**Comment by andiechan** [comment]
**Propuesta 3**

![web-iop_about_03](https://cloud.githubusercontent.com/assets/19866300/19173789/f079aae8-8bf7-11e6-829a-6fde16437009.png)

**Comment by proseuz** [comment]
**Propuesta 4**
![web-iop-10](https://cloud.githubusercontent.com/assets/17308060/19177484/aadb666e-8c17-11e6-8cc2-600c14781437.jpg)
**Propuesta 5**
![web-iop-05](https://cloud.githubusercontent.com/assets/17308060/19177485/aaf2db14-8c17-11e6-83ce-e5f3adfd6971.jpg)
**Propuesta 6**
![web-iop-08](https://cloud.githubusercontent.com/assets/17308060/19177486/ab1003f6-8c17-11e6-8948-cddba4932871.jpg)
**Propuesta 7**
![web-iop-09](https://cloud.githubusercontent.com/assets/17308060/19177487/ab62232a-8c17-11e6-9c86-8a938106dd03.jpg)

@arnaldos

**Comment by arnaldos** [comment]
propuesta 2 
- Donde dice staff de fondo una imagen de varias personas puedes aplicar un blur para que no distingan los rostros de las personas.
- En el parrafo ddonde dice Luis molina puedes replantearlo con alguna imagen de cada persona que senombre en el staff

**Comment by andiechan** [comment]
**Propuesta 2.2**
![02-02](https://cloud.githubusercontent.com/assets/19866300/19208649/cbe75b2a-8cca-11e6-859c-60b9acee50cb.png)

En el texto solo se habla de Luis por eso solo coloque un espacio para colocar su foto, no se si Lucas es el editor del texto o es parte del staff que en tal caso faltaría su descripción y respectivamente su foto también.

**Comment by andiechan** [comment]
**Propuesta 2.3** 

![2 3-02](https://cloud.githubusercontent.com/assets/19866300/19208780/b94a38dc-8ccc-11e6-8c3d-12498a422657.png)

**Comment by arnaldos** [comment]
se ve raro el marco que le pusiste a la foto

**Comment by andiechan** [comment]
**Propuesta 2.4**
![2 4-02](https://cloud.githubusercontent.com/assets/19866300/19209376/07401aa2-8cd7-11e6-8e73-5b415e51df34.png)

**Comment by andiechan** [comment]
**Propuesta 2.5**

![2 5-02](https://cloud.githubusercontent.com/assets/19866300/19209485/231061ae-8cd9-11e6-9a3e-4d3553164e2a.png)

**Propuesta 2.6**
![2 6-02](https://cloud.githubusercontent.com/assets/19866300/19209486/2319ced8-8cd9-11e6-9033-c000c939be3d.png)

**Comment by andiechan** [comment]
**Propuesta 2.7**

![2 7-02](https://cloud.githubusercontent.com/assets/19866300/19209521/d35198bc-8cd9-11e6-850c-296ccba323f6.png)

**Comment by andiechan** [comment]
**Propuesta 8**
![04-02](https://cloud.githubusercontent.com/assets/19866300/19253435/05b818e4-8f19-11e6-8b21-3ecff2388829.png)

**Propuesta 9**
![05-02](https://cloud.githubusercontent.com/assets/19866300/19253436/05c09dc0-8f19-11e6-8224-e6255b5601db.png)

**Comment by ivonnesantos** [comment]
Ok puede ser como la 8 pero invertido el espacio, si no nos pasan contenido de otras personas que componen es staff dejamos la foto con el cargo y el nombre y a la foto de luis si la dejamos con su reseña quedaria algo mas o menos asi
![sin titulo-1-01](https://cloud.githubusercontent.com/assets/15238660/19255510/bae51362-8f2c-11e6-9438-a21d124f6f5b.png) @andiechan 
  Otro detalle no justifiques el texto

**Comment by arnaldos** [comment]
o algo similar a este también 
![image](https://cloud.githubusercontent.com/assets/13594347/19255967/314af75e-8f39-11e6-9941-92aebba72611.png)

**Comment by proseuz** [comment]
Hola, por acá dejo una propuesta

## Proposal 10 (falta poner la imagen que va en el rectángulo del staff)

![web-iop-06](https://cloud.githubusercontent.com/assets/17308060/19271991/dd04a030-8f94-11e6-8b1b-3b1da5a7c8bd.jpg)
@arnaldos

**Comment by ivonnesantos** [comment]
@jhonmarquez92 se ve bien puedes hacer una sin la reseña de lucas y laura en caso tal de que no nos entreguen contenido es para tener ambas opciones, los nombres yo los pondria en bold y el cargo normal. @arnaldos tu que dices

**Comment by proseuz** [comment]
10.1 ¿Alguna sugerencia para las imágenes?
![web-iop-06](https://cloud.githubusercontent.com/assets/17308060/19277091/8af50bb0-8fa6-11e6-9476-ec189e136e33.jpg)
10.2
![web-iop-07](https://cloud.githubusercontent.com/assets/17308060/19277093/8b966974-8fa6-11e6-8a5b-4bcdee34d9ce.jpg)
@arnaldos @ivonnesantos

**Comment by arnaldos** [comment]
comparto tu comentario solo invertiria la posicion del texto del cargo y el nombre

**Comment by arnaldos** [comment]
en caso tal seria un texto de lorem ipsum para los otro members

**Comment by ivonnesantos** [comment]
Si pero si no nos dan el contenido antes de publicarla no podemos ponerle el lorem ipsum tendriamos que resdistribuir o hacerlo asi como el la plantea en la 10.2

**Comment by ivonnesantos** [comment]
Lo que yo pienso es que se puede poner la foto pero no se

**Comment by proseuz** [comment]
Propuestas con las modificaciones sugeridas @arnaldos @ivonnesantos 
10.3
![web-iop1-06](https://cloud.githubusercontent.com/assets/17308060/19284256/29a7655c-8fc3-11e6-87d2-987c8fc090ec.jpg)
10.4
![web-iop1-07](https://cloud.githubusercontent.com/assets/17308060/19284257/29bfbee0-8fc3-11e6-8137-08b3cf141f47.jpg)

**Comment by andiechan** [comment]
**Propuesta 01:  Imagen About** 
![imagen_01](https://cloud.githubusercontent.com/assets/19866300/19292880/65cf2a18-8fed-11e6-99e7-7ac1884ac793.jpg)

**1.1**
![imagen_02](https://cloud.githubusercontent.com/assets/19866300/19292879/65c15050-8fed-11e6-80a4-bd6c3d8e8fa9.jpg)

**Comment by isahq23** [comment]
Pienso que el divisor de STAFF debería tener más espacio, más presencia. 
@jhonmarquez92 ponle de altura 250px

Otra cosa, esas reseñas del staff están demasiado grandes y extensas a mi parecer. Pienso que podríamos mostrar algo corto y añadir un botón de "see more" como para seguir leyendo, los usuarios no leen jajaja

@arnaldos sé que el ejemplo que le pusiste no está mal, pero es una tienda. Las imágenes deben ser así de grandes porque se debe detallar el producto. Pero acá no estamos detallando un producto, estamos mostrando una persona. Además que son estilo diferentes al que estamos diseñando.

**Comment by proseuz** [comment]
Con los cambios sugeridos por @isahq23  @arnaldos  @ivonnesantos 
10.5
![web-iop2-06](https://cloud.githubusercontent.com/assets/17308060/19320427/3ec4290e-907f-11e6-8598-083e765616fd.jpg)

10.6
![web-iop2-07](https://cloud.githubusercontent.com/assets/17308060/19320098/eb60d2f4-907d-11e6-8aae-d59b67dd7455.jpg)

**Comment by andiechan** [comment]
**Propuesta 11**
![web-iop_about-04](https://cloud.githubusercontent.com/assets/19866300/19320438/4fb3ae42-907f-11e6-9e71-b02418675d91.png)

Ok les explico la diagramación brevemente, las imagenes de abajo quedan fijas pero al darles clic sale entonces el contenido como en la parte superior de esa forma nadie se tropieza con nadie y no va a parecer un catalogo, ademas se podrá apreciar mejor la biografía de cada uno independientemente de la cantidad de texto que tenga.

**Comment by andiechan** [comment]
**Propuesta 11.2**
![6 2-04](https://cloud.githubusercontent.com/assets/19866300/19320798/b9e74142-9080-11e6-962f-f25e21025bd2.png)

Anexe las redes personales (opcional)

**Comment by isahq23** [comment]
Me gusta la idea de @andiechan para el staff pero la parte de london y el banner de "staff" de @jhonmarquez92 

Qué dices @arnaldos ?

**Comment by andiechan** [comment]
**Propuesta 12**
![7-04](https://cloud.githubusercontent.com/assets/19866300/19328108/396ca5a0-90a0-11e6-9c15-81e01712a4b0.png)

Tomando en cuenta todos los cambios requeridos.

**Comment by arnaldos** [comment]
este podemos dejarlo asi !

**Comment by ivonnesantos** [comment]
Si haremos un Diseño para movil

**Comment by ivonnesantos** [comment]
O como estan tan apresurados con esto puedes eliminar lo que sea nesesario que siempre que no afecte el contenido

**Comment by ivonnesantos** [comment]
Ya te hago un mockups para movil y te lo paso

**Comment by isahq23** [comment]
@robertggovias eso no es reponsivo, eso es adaptativo.
El responsivo "responde" al espacio, eliminando elementos.
El adaptativo se "adapta", moviendo los elementos sin eliminarlos para que se reorganice el espacio.
