### ISSUE TITLE
Crear mokups para la web de IoP consortium sección Events

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#1005]

**Comment by ivonnesantos** [comment]
Propuesta_1 
![events_p1-03](https://cloud.githubusercontent.com/assets/15238660/19175633/77d56a64-8c06-11e6-91f1-7f5eb21b3eca.png)
Propuesta_2
![events_p2-02](https://cloud.githubusercontent.com/assets/15238660/19175634/77dc6850-8c06-11e6-86a5-0f17e7a23fc3.png)

**Comment by isahq23** [comment]
Propuesta 3
![events_1](https://cloud.githubusercontent.com/assets/15214774/19175804/6fecb06e-8c10-11e6-9907-1e79bd77e193.jpg)

Propuesta 4
![events_2](https://cloud.githubusercontent.com/assets/15214774/19175830/a4dabf96-8c10-11e6-883e-d89dc0fdb072.jpg)

**Comment by arnaldos** [comment]
@isahq23 propuesta 4 pero con un cambio, donde esta el calendario remplazar por los eventos próximos (imagenes con cuadros de colores)
anexo imagen
![image](https://cloud.githubusercontent.com/assets/13594347/19198779/3d505a7a-8c97-11e6-822b-2fd7f7451ef1.png)

**Comment by isahq23** [comment]
@arnaldos la propuesta se compone de ambas vistas, para explicarte.

Dichos cuadros de color con imágenes representan los eventos MÁS importantes, diferente del calendario que, aparte de extenderse al mes completo, te muestra todos los eventos de la semana o el mes.

**Comment by isahq23** [comment]
Propuesta 5
![events_3](https://cloud.githubusercontent.com/assets/15214774/19199617/3f70e028-8c9b-11e6-908a-9f1c138b4070.jpg)

@arnaldos debería sustituir la palabra calendar por events?

**Comment by arnaldos** [comment]
si version 5

**Comment by isahq23** [comment]
Listo @arifernandez 
https://drive.google.com/drive/u/0/folders/0B-ykaWmX3h6UdnFHMUZHZnQ2dG8
Aññí está el editable y los recursos con indicaciones
