### ISSUE TITLE
Crear mokups para la web de IoP consortium sección Membership

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#1006]

**Comment by emmysm** [comment]
Propuesta 1
![sin titulo-1-01](https://cloud.githubusercontent.com/assets/15143489/19175501/194fd7be-8c05-11e6-8526-0f5d731b6173.png)

Propuesta 2
![sin titulo-1-02](https://cloud.githubusercontent.com/assets/15143489/19175502/19532310-8c05-11e6-8966-9bcf9e60ff59.png)

**Comment by emmysm** [comment]
Propuesta 3 
![sin titulo-2](https://cloud.githubusercontent.com/assets/15143489/19177493/b1de1a10-8c17-11e6-908b-65550c576928.png)

Propuesta 4

![propuesta 5-01](https://cloud.githubusercontent.com/assets/15143489/19178248/fce9b508-8c1e-11e6-8cb8-811169276714.png)

@arnaldos @Luis-Fernando-Molina

**Comment by arnaldos** [comment]
los ajustes que conversamos por hangouts :smile:

**Comment by emmysm** [comment]
![propuesta 5-01](https://cloud.githubusercontent.com/assets/15143489/19244262/85e94360-8ee9-11e6-9515-3b823be2ada2.png)

@ivonnesantos @arnaldos

**Comment by emmysm** [comment]
@arnaldos  estuve buscando los logos de las universidades mencionadas, y no encontré ninguna. ¿La universidad metropolitana de qué ciudad? Y las otras dos: Resashers insitutions, INFOTA no estoy muy segura si están bien escritas. Con quién se puede hablar referente a eso?

**Comment by emmysm** [comment]
![propuesta iop web-01](https://cloud.githubusercontent.com/assets/15143489/19254511/46525294-8f22-11e6-97ba-69fcccfc11a7.png)

@arnaldos

**Comment by arnaldos** [comment]
para esta imagen seria mejor todas las personas en 2 plano
![image](https://cloud.githubusercontent.com/assets/13594347/19255658/a6b2ccb8-8f36-11e6-9568-f6c73b084004.png)

**Comment by emmysm** [comment]
Ok. Con respecto al resto de la propuesta hay alguna otra modificación que deba hacer?

**Comment by emmysm** [comment]
![propuesta iop web-01-01](https://cloud.githubusercontent.com/assets/15143489/19335419/1bb4affe-90d1-11e6-8443-972f411b4fcd.png)

@arnaldos

**Comment by arnaldos** [comment]
Version definitiva

![membership](https://cloud.githubusercontent.com/assets/13594347/19628062/ff3c23c6-992b-11e6-930c-f2648c2428cc.jpg)
