### ISSUE TITLE
Crear mokups para la web de IoP consortium sección Join us

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#1007]

**Comment by victoralfonzohd** [comment]
@arnaldos 

### Propuesta 1

![join-us-web](https://cloud.githubusercontent.com/assets/15219855/19166566/f583c842-8bd5-11e6-843a-3a6c914e850f.jpg)

**Comment by arnaldos** [comment]
@victoralfonzohd genera otra propuesta plz

**Comment by victoralfonzohd** [comment]
@arnaldos 

### Propuesta 2

![join-us-web](https://cloud.githubusercontent.com/assets/15219855/19169309/cc90bdda-8be1-11e6-91ea-cb7689797489.jpg)

**Comment by victoralfonzohd** [comment]
@arnaldos 

### Propuesta 3

![join-us-web3](https://cloud.githubusercontent.com/assets/15219855/19169785/d9539b9e-8be3-11e6-92aa-163386b62666.jpg)

**Comment by victoralfonzohd** [comment]
@arnaldos 

### Propuesta 4

![join-us-web4](https://cloud.githubusercontent.com/assets/15219855/19191198/53b10968-8c6f-11e6-80c8-ded10b5628de.jpg)

**Comment by arnaldos** [comment]
las lineas debajo de join us pueden ser azules

**Comment by ivonnesantos** [comment]
mi opinion esa imagen con las pantallas de la app los textos iconos y tantos detalles no te parece que chocan un poco con al recuadro azul y texto principal  se debe analizar eso @arnaldos

**Comment by victoralfonzohd** [comment]
### Propuesta 5

![join-us-web5](https://cloud.githubusercontent.com/assets/15219855/19191894/439fcf20-8c72-11e6-9bf4-3c4b203a9e70.jpg)

### Propuesta 5.1

![join-us-web6](https://cloud.githubusercontent.com/assets/15219855/19193356/c46b8c2a-8c77-11e6-9f72-e7cfe5baa130.jpg)

**Comment by arnaldos** [comment]
propuesta 5

**Comment by victoralfonzohd** [comment]
@arnaldos 

### Propuesta 6

![join-us-6](https://cloud.githubusercontent.com/assets/15219855/19325664/29eca342-9095-11e6-8bf2-839be0095b0e.jpg)

**Comment by victoralfonzohd** [comment]
@arnaldos 

### Propuesta 7

![join-us-9](https://cloud.githubusercontent.com/assets/15219855/19325950/803c7690-9096-11e6-996a-a053063402fe.jpg)

**Comment by arnaldos** [comment]
propuesta 6
