### ISSUE TITLE
photo_mockups_IoP_news

### ISSUE THREAD

**Issue by ivonnesantos** [bitDubai/fermat-graphic-design#1009]
Make or edit images for the area of case # 1003 **NEWS**

**Comment by rosanacoronado** [comment]
@arnaldos @ivonnesantos 

## Propuesta_1

Utilice la misma imagen que la propuesta original, solo cambiando el screenshot de la tablet por una imagen de como se veria la pagina de site.
![web_iop_newssection3-02](https://cloud.githubusercontent.com/assets/19508456/19242306/94768018-8ee0-11e6-983b-19ef8e8c5b09.png)

## Propuesta_2

Hice el mismo cambio en el screen de la tablet
![web_iop_newssection4-02](https://cloud.githubusercontent.com/assets/19508456/19242309/949e2dde-8ee0-11e6-962f-58dbd063a346.png)

## Propuesta_3

![web_iop_newssection5-02](https://cloud.githubusercontent.com/assets/19508456/19242308/949c08a6-8ee0-11e6-907c-02b4898daeac.png)

**Comment by rosanacoronado** [comment]
@arnaldos @ivonnesantos 

## Propuesta_4

![web_iop_newssection6-02](https://cloud.githubusercontent.com/assets/19508456/19245141/862bf972-8eed-11e6-8fbc-0f07966319a6.png)

**Comment by arnaldos** [comment]
propuesta 2
