### ISSUE TITLE
Crear Banner de presentación para la Bitcoin Wallet

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#101]
Se desarrollara un Banner de presentación de la Bitcoin Wallet que se mostrara dentro de la Wallet Store.

**Comment by arnaldos** [comment]
viene del issues #99

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina te comparto los Banners para la Bitcoin Wallet 

Versión 1
![banner bitcoin wallet-01](https://cloud.githubusercontent.com/assets/13594347/9916575/d4e21bae-5c86-11e5-8a51-536236485ddf.jpg)

Versión 2
![banner bitcoin wallet-02](https://cloud.githubusercontent.com/assets/13594347/9916576/d53a9c20-5c86-11e5-9626-e2ca09f5f0c6.jpg)

Versión 3
![banner bitcoin wallet-03](https://cloud.githubusercontent.com/assets/13594347/9916577/d56c5c2e-5c86-11e5-9183-0f7b3f04b929.jpg)

**Comment by Luis-Fernando-Molina** [comment]
Mis comentarios son similares a los del icono respecto al nombre.

**Comment by arnaldos** [comment]
perfecto !!

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina creo que de esta manera puede funcionar sin variar lo que se ha trabajado que te parece ?

Versión 1
![banner bitcoin wallet-01](https://cloud.githubusercontent.com/assets/13594347/9919668/24ed5490-5c98-11e5-9a45-dcc376d0feb5.jpg)

Versión 2
![banner bitcoin wallet-02](https://cloud.githubusercontent.com/assets/13594347/9919669/24f2bf5c-5c98-11e5-928a-d85dcb6c8b53.jpg)

Versión 3
![banner bitcoin wallet-03](https://cloud.githubusercontent.com/assets/13594347/9919670/24fa431c-5c98-11e5-8a6a-3df048692ce0.jpg)

**Comment by Luis-Fernando-Molina** [comment]
@arnaldos Vamos a sacarle la palabra en arabe del logo de bitDubai please.

Respecto al logo, no estoy muy seguro. Quizás pudieramos probar algo mas gráfico que las iniciales.

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina  podría ser usando el mismo icono que se esta trabajando en el otro caso ? o trabajar algo totalmente diferente para que unifique ambos casos ?

**Comment by Luis-Fernando-Molina** [comment]
Mejor si no es el mismo icono que para la aplicación sino algo mas elaborado dado que el espacio lo permite. Tenes todo un banner para jugar.

**Comment by arnaldos** [comment]
ok perfecto !!!

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina te comparto una serie nueva de versiones de Banners para la bitcoin wallet

Versión 4
![banner bitcoin wallet-06](https://cloud.githubusercontent.com/assets/13594347/10037770/99ef545a-6184-11e5-9af1-0453583aa6ba.jpg)

Versión 5
![banner bitcoin wallet-04](https://cloud.githubusercontent.com/assets/13594347/10037771/99f1a692-6184-11e5-9c56-26cbed91d46c.jpg)

Versión 6
![banner bitcoin wallet-05](https://cloud.githubusercontent.com/assets/13594347/10037772/99f87d3c-6184-11e5-8a18-a842a0f87359.jpg)

**Comment by Luis-Fernando-Molina** [comment]
Version 4 :+1:   listo este ttema.

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina perfecto !!!
