### ISSUE TITLE
photo_mockups_IoP_About

### ISSUE THREAD

**Issue by ivonnesantos** [bitDubai/fermat-graphic-design#1010]
Make or edit images for the seccion of case #1004 **ABOUT**

**Comment by andiechan** [comment]
**Propuesta 1**
![imagen_01](https://cloud.githubusercontent.com/assets/19866300/19315784/0e56333c-906d-11e6-906f-d480451d1234.jpg)

![imagen_02](https://cloud.githubusercontent.com/assets/19866300/19315785/0e61df2a-906d-11e6-973b-cb09fc6109f1.jpg)

Esta fue la imagen que yo utilice, ya subo otras propuestas @arnaldos

**Comment by ivonnesantos** [comment]
Propuesta 2
![photo_about-01](https://cloud.githubusercontent.com/assets/15238660/19328426/93050818-90a1-11e6-95aa-3ca41d7c231f.png)
Propuesta 3
![photo_about-02](https://cloud.githubusercontent.com/assets/15238660/19328428/965dea2a-90a1-11e6-8426-3e3771f82e5f.png)
Estuve indagando en otras paginas y note que las fotos utilizadas para esta sección suelen ser personas que ven a la cámara o que dan la sensación de que se dirigen al usuario, en tal caso de que el primer actor se dirija a  un segundo actor se suelen ver los rostros transmitiendo agrado al usuario. Esto son puntos en común que encontré en varias paginas con respecto a esta sección.  

@arnaldos

**Comment by arnaldos** [comment]
cambiemos la foto a ver cual se adapta mas a IoP

**Comment by ivonnesantos** [comment]
osea que te haga una version con la pagina completa?

**Comment by arnaldos** [comment]
presentar otra imagen

**Comment by ivonnesantos** [comment]
Propuesta 4 
![photo_about-01](https://cloud.githubusercontent.com/assets/15238660/19459825/21b426e2-94a4-11e6-90b6-d2b75d32d56b.jpg)
Propuesta 5
![photo_about-02](https://cloud.githubusercontent.com/assets/15238660/19459826/21bc4c8c-94a4-11e6-9372-601e2067958e.jpg)

@arnaldos

**Comment by arnaldos** [comment]
la 5 por el momento
