### ISSUE TITLE
photo_mockups_IoP_Events

### ISSUE THREAD

**Issue by ivonnesantos** [bitDubai/fermat-graphic-design#1011]
Make or edit images for the area of case #1005

**Comment by ivonnesantos** [comment]
![events_picture_mockups-01](https://cloud.githubusercontent.com/assets/15238660/19242340/b2116f0c-8ee0-11e6-8520-1a6141626add.png)
@arnaldos

**Comment by isahq23** [comment]
Cover 1
![events_image_1](https://cloud.githubusercontent.com/assets/15214774/19255017/27b0bc14-8f30-11e6-8bf7-0d4b35ec2175.jpg)

Cover 2
![events_image_2](https://cloud.githubusercontent.com/assets/15214774/19255025/3315b794-8f30-11e6-9018-045375000082.jpg)

Cover 3
![events_image_3](https://cloud.githubusercontent.com/assets/15214774/19255028/390a5664-8f30-11e6-80e6-fd062d017869.jpg)

@arnaldos

**Comment by arnaldos** [comment]
isa es logo no lo uses no es el de IoP en todo caso usa ese. por otro lado replantea as imágenes plz

**Comment by ivonnesantos** [comment]
cover 4
![events_p1_photo-01](https://cloud.githubusercontent.com/assets/15238660/19256548/ff950270-8f35-11e6-824e-d67a7d5845b7.png)
@arnaldos

**Comment by ivonnesantos** [comment]
cover_1_suscribe
![events_p1_photo-02](https://cloud.githubusercontent.com/assets/15238660/19276442/48f04038-8fa4-11e6-904d-dc96bc5987e3.png) @arnaldos

**Comment by arnaldos** [comment]
me gusta el subscribe

**Comment by arnaldos** [comment]
sube la imagen plz

**Comment by ivonnesantos** [comment]
Cover 5
![events_p1_photo-01](https://cloud.githubusercontent.com/assets/15238660/19312486/84170a86-9060-11e6-8825-54029e2a3b5d.png)
@arnaldos

**Comment by arnaldos** [comment]
me gusta la idea y si agregas un evento mas ?

**Comment by isahq23** [comment]
Creo que el cover 4 de @ivonnesantos es el más indicado para la imagen principal de la sección de eventos. 

Sin embargo, acá dejo mis propuestas con el logo de IOP
Cover 6
![events_image_1](https://cloud.githubusercontent.com/assets/15214774/19315373/c898e05e-9073-11e6-817b-f0d4a6ddff76.jpg)

Cover 7
![events_image_2](https://cloud.githubusercontent.com/assets/15214774/19315381/d2026462-9073-11e6-9ce9-664205795ba0.jpg)

**Comment by ivonnesantos** [comment]
cover 8
![events_p1_photo-01](https://cloud.githubusercontent.com/assets/15238660/19318161/89718ee2-9075-11e6-9ccb-c80fedd12c72.png)
@arnaldos

**Comment by ivonnesantos** [comment]
Cover 9
![events_p1_photo-03](https://cloud.githubusercontent.com/assets/15238660/19319251/12bb522e-907a-11e6-9fb2-b55b6e8b72fc.jpg)
@arnaldos

**Comment by ivonnesantos** [comment]
Cambios cover 9 
![events_p1_photo-02](https://cloud.githubusercontent.com/assets/15238660/19351314/40e69d48-9129-11e6-8c4c-0138bcd1710a.png)

@arnaldos

**Comment by arnaldos** [comment]
pon una imagen del lado derecho plz a ver como se comporta

**Comment by ivonnesantos** [comment]
![events_p1_photo-03](https://cloud.githubusercontent.com/assets/15238660/19367015/69015172-9167-11e6-8b9d-dee6138e6bca.png)
@arnaldos

**Comment by arnaldos** [comment]
la ultima pero pone el has que sale del calendario

**Comment by arnaldos** [comment]
y la subes
