### ISSUE TITLE
photo_mockups_IoP_Membership

### ISSUE THREAD

**Issue by ivonnesantos** [bitDubai/fermat-graphic-design#1012]
Make or edit images for the area of case #1006

**Comment by emmysm** [comment]
![sin titulo-1-02](https://cloud.githubusercontent.com/assets/15143489/19245083/4e95b714-8eed-11e6-853f-750502ec468c.png)

**Comment by emmysm** [comment]
@arnaldos

**Comment by karentvillegas** [comment]
Algunas propuestas para esta imagen..

Propuesta2
![4](https://cloud.githubusercontent.com/assets/19273211/19284322/70db4b8c-8fc3-11e6-9ecd-33e42d3bf42f.jpg)

Propuesta3
![6](https://cloud.githubusercontent.com/assets/19273211/19284337/83d0d540-8fc3-11e6-9a47-ab3fa03c5a0c.jpg)

Propuesta4
![1](https://cloud.githubusercontent.com/assets/19273211/19284344/8cb1f05e-8fc3-11e6-807e-5ba190e7a5a3.jpg)

@arnaldos

**Comment by arnaldos** [comment]
@karentvillegas propuesta 3 planteala el mockup completo a ver como se ve el conjunto

**Comment by emmysm** [comment]
![propuesta iop web-01](https://cloud.githubusercontent.com/assets/15143489/19291764/35335d46-8fe5-11e6-9397-064ff06becf0.png)

@arnaldos, con la propuesta de @karentvillegas

**Comment by karentvillegas** [comment]
Acá otras propuestas @arnaldos 

Propuesta 5
![propuesta7](https://cloud.githubusercontent.com/assets/19273211/19331272/e4c960bc-90b1-11e6-8356-b4856e133fc6.jpg)

Propuesta 6
![propuesta8](https://cloud.githubusercontent.com/assets/19273211/19331274/e9d91200-90b1-11e6-922a-36e3516b4ff0.jpg)

Propuesta7
![propuesta9](https://cloud.githubusercontent.com/assets/19273211/19331276/ec30e000-90b1-11e6-952c-4e32d2c6b832.jpg)

Propuesta 8
![propuesta10](https://cloud.githubusercontent.com/assets/19273211/19331279/eef4fe2a-90b1-11e6-9655-a556cb4d423b.jpg)

Propuesta 9
![propuesta11](https://cloud.githubusercontent.com/assets/19273211/19331283/f0bc2922-90b1-11e6-9be7-fd2a0aece8b6.jpg)

**Comment by emmysm** [comment]
![propuesta iop web-01-01](https://cloud.githubusercontent.com/assets/15143489/19353927/f0e728bc-9132-11e6-8c97-0577b08d8bb9.png)

@arnaldos  con la última propuesta de @karentvillegas

**Comment by arnaldos** [comment]
el texto del fondo blanco debe tener el mismo tamaño y mismo interlineado que el que esta en el fondo azul

**Comment by Luis-Fernando-Molina** [comment]
Hay un mal entendido enorme aquí. Los miembros del consorcio no son personas, sino universidades y grandes corporaciones.

Por otro lado, el consorcio mas parecido al que queremos formar es el siguiente: 
https://www.w3.org (No tomar como base su diseño grafico porque es inexistente, pero tener en cuenta lo que se hace y dice y muestra en estas organizaciones).

**Comment by Luis-Fernando-Molina** [comment]
Otro ejemplo para tener en cuenta es este: 
https://www.linuxfoundation.org/

**Comment by Luis-Fernando-Molina** [comment]
De donde salieron los textos que están usando?

**Comment by arnaldos** [comment]
esos textos los suministro Daniel a traves del WP.

**Comment by emmysm** [comment]
![membership-02](https://cloud.githubusercontent.com/assets/15143489/19458797/4fb70a62-949c-11e6-97ff-249f7d6093d4.png)
![membership-01](https://cloud.githubusercontent.com/assets/15143489/19458796/4fb49372-949c-11e6-9818-198b92ff4335.png)

La página que nos proporcionó Luis como ejemplo tiene varias secciones de Membership. No estoy segura qué tanta información deba integrar a la página, y si en esta misma se debería colocar un formulario de registro, @arnaldos

**Comment by emmysm** [comment]
**Propuesta 12**
![propuesta 545 member-01](https://cloud.githubusercontent.com/assets/15143489/19479526/311dfb3c-9515-11e6-8d2b-49458cd0a6cb.png)

**Propuesta 13**
![propuesta 545 member-02](https://cloud.githubusercontent.com/assets/15143489/19479527/311f6774-9515-11e6-8b4a-3f97147d9f41.png)

**Propuesta 14**

![propuesta 545 member-03](https://cloud.githubusercontent.com/assets/15143489/19479528/3121a87c-9515-11e6-8873-536bb022ed4b.png)

**Propuesta 15**
![propuesta 545 member-04](https://cloud.githubusercontent.com/assets/15143489/19479530/313fa534-9515-11e6-88df-f83fa4925734.png)

**Propuesta 16**
![propuesta 545 member-05](https://cloud.githubusercontent.com/assets/15143489/19479529/313fcfb4-9515-11e6-9750-b0b6c54adb98.png)

@arnaldos

**Comment by arnaldos** [comment]
la forma de los botones debe mantenerse estandariza el estilo del boton.

un cambio de diagramación y bloque de texto no lo hagas tan rígido, se es un texto simulado pero puedes suavizarlo mas.

![image](https://cloud.githubusercontent.com/assets/13594347/19483401/95014338-952a-11e6-8eb7-776928dadd5d.png)

**Comment by emmysm** [comment]
*\* Propuesta 17**
![propuesta member-01](https://cloud.githubusercontent.com/assets/15143489/19486190/9eea75e4-952b-11e6-8a9c-f5d8b6f9e602.png)

**Propuesta 18**
![propuesta member-02](https://cloud.githubusercontent.com/assets/15143489/19486189/9ee9d47c-952b-11e6-9fc4-2c8e72d9fa7d.png)

**Propuesta 19**
![propuesta member-03](https://cloud.githubusercontent.com/assets/15143489/19486192/9eeeefac-952b-11e6-9a63-fd546f1d94e5.png)

**Propuesta 20**
![propuesta member-04](https://cloud.githubusercontent.com/assets/15143489/19486191/9eec2614-952b-11e6-9a05-dffa0b2b5228.png)

**Propuesta 21**
![propuesta member-05](https://cloud.githubusercontent.com/assets/15143489/19486286/e466bfe2-952b-11e6-9238-96a8bd60c6e1.png)

@arnaldos

**Comment by arnaldos** [comment]
Esta version https://cloud.githubusercontent.com/assets/15143489/19486191/9eec2614-952b-11e6-9a05-dffa0b2b5228.png

Correcciones: 
- Plantea una cambiando la posicion de la imagen con la del contenido como te comente antes.
- Y otra eliminando la imagen del header y colocando la imagen de abajocomo header y picada en dos una parte se muestra original cn el cuadro azul encimay la otra con el plano negro para el sending line 
- Tipografia Helvetica Neue no myriad pro.

Te dejo referencia de los cambios 
![4](https://cloud.githubusercontent.com/assets/13594347/19490230/bee339e4-9544-11e6-9fa8-1d5fcae14d53.jpg)

**Comment by emmysm** [comment]
Perfecto, @arnaldos  ya hago las correcciones

**Comment by emmysm** [comment]
**Propuesta 22**
![propuesta member-02-01-01-04](https://cloud.githubusercontent.com/assets/15143489/19493331/3286fa7c-9548-11e6-8295-962bfc91db09.png)

**Propuesta 23**
![propuesta member-02-01-01-01](https://cloud.githubusercontent.com/assets/15143489/19493332/32a19ce2-9548-11e6-9093-72509a744641.png)

**Propuesta 24**
![propuesta member-02-01-01-02](https://cloud.githubusercontent.com/assets/15143489/19493333/32acfcae-9548-11e6-9e96-904475902e06.png)

**Propuesta 25**
![propuesta member-02-01-01-03](https://cloud.githubusercontent.com/assets/15143489/19493334/32b7c620-9548-11e6-8832-0a6892d4b072.png)

@arnaldos

**Comment by emmysm** [comment]
**Propuesta 26**
![propuestas-02](https://cloud.githubusercontent.com/assets/15143489/19494056/5a26575a-954b-11e6-90fb-55d0568f3a85.png)

**Propuesta 27**
![propuestas-05](https://cloud.githubusercontent.com/assets/15143489/19494057/5a29b3a0-954b-11e6-97eb-f042d21d8035.png)

**Propuesta 28**
![propuestas-06](https://cloud.githubusercontent.com/assets/15143489/19494058/5a2d12ac-954b-11e6-9d24-f2ced9446955.png)

@arnaldos
