### ISSUE TITLE
photo_mockups_IoP_ Join-us

### ISSUE THREAD

**Issue by ivonnesantos** [bitDubai/fermat-graphic-design#1013]
Make or edit images for the area of case #1007 **JOIN US**

**Comment by victoralfonzohd** [comment]
@ivonnesantos  @arnaldos

Tres propuestas, tres conceptos distintos.

### Propuesta 1

![propuesta-1](https://cloud.githubusercontent.com/assets/15219855/19241105/145c5164-8edb-11e6-8876-339353a3f391.jpg)

### Propuesta 2

![propuesta-2](https://cloud.githubusercontent.com/assets/15219855/19241117/20bd267c-8edb-11e6-887d-c1c4c895519f.jpg)

### Propuesta 3

![propuesta-3](https://cloud.githubusercontent.com/assets/15219855/19241516/0103abd8-8edd-11e6-83d9-8360c13bb33f.jpg)

**Comment by arnaldos** [comment]
Has una mezcla entre la 2y3 pero con el fondo claro

**Comment by victoralfonzohd** [comment]
### Propuesta 4

![propuesta-4](https://cloud.githubusercontent.com/assets/15219855/19242956/822704ca-8ee3-11e6-9026-bdfa3d71d709.jpg)

**Comment by victoralfonzohd** [comment]
@arnaldos 

### Propuesta 5

![propuesta-5](https://cloud.githubusercontent.com/assets/15219855/19270416/f1a0cfca-8f8d-11e6-99f1-a68dbedffefe.jpg)

### Propuesta 6

![propuesta-6](https://cloud.githubusercontent.com/assets/15219855/19270438/0d1a5cb2-8f8e-11e6-817c-018ea57be78c.jpg)

**Comment by arnaldos** [comment]
propuesta 5
