### ISSUE TITLE
Crear ficha para identificar los módulos, en estado de Concepto

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#102]
Estado de Concepto, se refiere a los módulos que pueden existir como lo dice la palabra son un concepto aun no establecido.

Estos módulos se pueden identificar con los colores Grises o colores claros como base.

Viene del #92

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina Ficha de Estado de Concepto

![ficha_descriptiva_fermat_org_concepto_y_produccion2](https://cloud.githubusercontent.com/assets/13594347/9818522/e28cde96-5872-11e5-9877-8b60fb054bc3.jpg)

**Comment by Luis-Fernando-Molina** [comment]
La capa deberia tener menos relevancia que el nombre del plugin. Ademas de acuerdo a lo que dijo Miguel, estima el espacio para la cantidad de lineas que se necesitan en cada caso.

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina ajustes solicitados !! 
![ficha_descriptiva_fermat_org_concepto_y_produccion-02](https://cloud.githubusercontent.com/assets/13594347/9825094/fb34ad7a-589a-11e5-8981-a119638f4701.jpg)
![ficha_descriptiva_fermat_org_concepto_y_produccion-04](https://cloud.githubusercontent.com/assets/13594347/9825095/fb3a3178-589a-11e5-96cb-9d94e4b4da0a.jpg)

**Comment by Luis-Fernando-Molina** [comment]
este pudiera andar asi, una pregunta, porque las biulleteras son del rojo oscuro y no del claro?

**Comment by arnaldos** [comment]
aquí subo con las billeteras en color mas claro, y ajustado el código del plugin 
![fichas_plugins-04](https://cloud.githubusercontent.com/assets/13594347/9826919/8c8746a0-58a7-11e5-9ca8-266d5013dbcc.jpg)

**Comment by Luis-Fernando-Molina** [comment]
proba con el nombre del plugin en blanco y el de la capa en negro plese

**Comment by Luis-Fernando-Molina** [comment]
Agreguemos en este como en las otras fichas, debajo de la foto, el Alias del usuario.

**Comment by arnaldos** [comment]
ok perfecto !!!!

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina

Corrección solicitada 

![ficha_descriptiva_fermat_org_concepto-02](https://cloud.githubusercontent.com/assets/13594347/9856925/6ba918d2-5ae1-11e5-8b29-4460d36616fb.jpg)

Versión LANDSCAPE según las recomendaciones dadas en el issues #103

Siguiendo la propuesta de @m471c4 

![ficha_descriptiva_fermat_org_concepto-01](https://cloud.githubusercontent.com/assets/13594347/9856950/9bac56fc-5ae1-11e5-9430-6780c8cc123e.jpg)

**Comment by Luis-Fernando-Molina** [comment]
hace la misma version de la ultima tuya pero landscape please

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina aquí subo dos versiones mas la diferencia entre ellas, es la parte inferior una de ellas tiene un plano rojo.
versión 1
![ficha_descriptiva_fermat_org_concepto-03](https://cloud.githubusercontent.com/assets/13594347/9858746/2b5e15b0-5aec-11e5-857e-29db2969a0a7.jpg)
versión 2
![ficha_descriptiva_fermat_org_concepto-04](https://cloud.githubusercontent.com/assets/13594347/9858747/2b83ebd2-5aec-11e5-87d5-cf3fdc9a0590.jpg)

**Comment by Luis-Fernando-Molina** [comment]
Version 2 :+1: 

Lo del usuario sobre la foto como lo indiue en otro caso. Acomodá las wallets para que ocupen el lugar que ahora dice usuario.

**Comment by arnaldos** [comment]
ok perfecto !!!

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina  que tal así ?
![ficha_descriptiva_fermat_org_concepto-04](https://cloud.githubusercontent.com/assets/13594347/9860545/9117bf78-5af6-11e5-998e-5696906aba43.jpg)

**Comment by Luis-Fernando-Molina** [comment]
el nombre del usuario ponelo en blanco sobre un overlay negro semi transparente por favor.

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina que tal así ?

![ficha_descriptiva_fermat_org_concepto-05-03-04](https://cloud.githubusercontent.com/assets/13594347/9891724/3ef1e4a8-5bd2-11e5-85b0-3f97da3297b7.jpg)

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina comparto el ajuste que mencionabas en el otro caso

![ficha_descriptiva_fermat_org_concepto-07-04](https://cloud.githubusercontent.com/assets/13594347/9894084/6a8cca9e-5be9-11e5-8633-67cdd39fc7a8.jpg)

**Comment by Luis-Fernando-Molina** [comment]
:+1:  Esta fichita queda terminada :smile:

**Comment by arnaldos** [comment]
perfecto !!! :+1:

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina  ya las subo al repo para que @Miguelcldn pueda hacer uso de las fichas !
