### ISSUE TITLE
Create a Connect page fermat.org new site

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#1020]
Issue Reference #1014

**Comment by victoralfonzohd** [comment]
@arnaldos 

### Propuesta 1

![connectfermatweb1](https://cloud.githubusercontent.com/assets/15219855/19356174/ea2d0dd6-913a-11e6-9326-1bf92d99c7fa.jpg)

### Propuesta 2

![connectfermatweb2](https://cloud.githubusercontent.com/assets/15219855/19356190/fa0ad0c6-913a-11e6-9271-ae75ed0357c6.jpg)

**Comment by arnaldos** [comment]
por ahora propuesta 1 pero esperemos la propuesta de jhon y definimos

**Comment by proseuz** [comment]
## Propuesta 3

![fermat web-cs6-05](https://cloud.githubusercontent.com/assets/17308060/19363235/b7b92eee-9157-11e6-8f64-85f89d9e74cd.jpg) 
@arnaldos

**Comment by arnaldos** [comment]
la propuesta 3 también esta buena pero nos quedamos con la 1

**Comment by ivonnesantos** [comment]
@arnaldos y si utiliza la 1 con la parte mail list de la tres

**Comment by arnaldos** [comment]
lo pence por un momento pero no estaba seguro pero puede ser !! presenten la propuesta

**Comment by victoralfonzohd** [comment]
@arnaldos @ivonnesantos Hmm, para parte del mailing list me gusta mas mi versión.. Si presento otra propuesta, creo que seria con la parte de Eventos, que planteo Jhon esa parte me gusta mas.

**Comment by proseuz** [comment]
De acuerdo con @victoralfonzohd creo que mi propuesta del mailing list esta muy grande. En todo caso podría ser el diseño de la propuesta de Victor sobre el fondo plano que propuse yo. @arnaldos  @ivonnesantos

**Comment by proseuz** [comment]
también me agrada más mi propuesta de events como dice Victor

**Comment by ivonnesantos** [comment]
Bueno a mi lo que no me gusto mucho fue el fondo asi que si puede ser la propuesta de mail que es mas ligera pero con el fondo plano

**Comment by victoralfonzohd** [comment]
@arnaldos @ivonnesantos @jhonmarquez92 

## Propuesta 4, usando la seccion de Eventos planteada por Jhon

### Version 1: El fondo de Mailing List puede variar, simplemente se usa otra imagen

---

![connect1](https://cloud.githubusercontent.com/assets/15219855/19455978/5c246d62-948d-11e6-84a0-48af55528aee.jpg)

### Version 2: Seccion Mailing list con fondo plano

---

![connect2](https://cloud.githubusercontent.com/assets/15219855/19455861/c8c9b324-948c-11e6-8627-8c408383060e.jpg)

**Comment by arnaldos** [comment]
vale nos quedamos con la ultima
