### ISSUE TITLE
Crear logo para IoP Consortium

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#1021]
Define a una entidad de asociados que forman la integridad de IoP.

**Comment by victoralfonzohd** [comment]
@arnaldos 

## Propuesta 1

![iop-consortium-logo](https://cloud.githubusercontent.com/assets/15219855/19491541/5421e536-9541-11e6-9df7-e2f621f0254e.jpg)

**Comment by victoralfonzohd** [comment]
@arnaldos 

### Propuesta 2

![iop-consortium-logo3](https://cloud.githubusercontent.com/assets/15219855/19493092/4dbc2160-9547-11e6-9f8a-45c6259e6dd7.jpg)

**Comment by victoralfonzohd** [comment]
@arnaldos 

### Propuesta 3

![iop-consortium-logo4](https://cloud.githubusercontent.com/assets/15219855/19494286/689b71e8-954c-11e6-87bf-40a1cff7a639.jpg)

### Propuesta 4

![iop-consortium-logo5](https://cloud.githubusercontent.com/assets/15219855/19494290/70ae33c0-954c-11e6-9d7c-d5f046ff5599.jpg)

**Comment by Jessicafp** [comment]
Propuesta 5
![1](https://cloud.githubusercontent.com/assets/19536846/19499273/89648f74-9563-11e6-96b4-3f2997100f23.png)

Propuesta 6
![2](https://cloud.githubusercontent.com/assets/19536846/19499263/877b6980-9563-11e6-937b-ab6dec91dc2e.png)

Propuesta 7
![3](https://cloud.githubusercontent.com/assets/19536846/19499264/877ce972-9563-11e6-970f-91a389e9b7c9.png)

Propuesta 8
![4](https://cloud.githubusercontent.com/assets/19536846/19499267/88201aa2-9563-11e6-807f-0975ab450b4f.png)

Propuesta 9
![5](https://cloud.githubusercontent.com/assets/19536846/19499268/882197e2-9563-11e6-8127-51cf27e9b33b.png)

Propuesta 10
![6](https://cloud.githubusercontent.com/assets/19536846/19499265/878a36fe-9563-11e6-87e4-58711ae3b2b4.png)

Propuesta 11
![7](https://cloud.githubusercontent.com/assets/19536846/19499266/87b0cdb4-9563-11e6-92a2-9a91ed2f08ee.png)

@arnaldos

**Comment by arnaldos** [comment]
### Propuesta 12

---

![fermat-iop-consortium1](https://cloud.githubusercontent.com/assets/13594347/19507287/62212fcc-95a8-11e6-8d3b-7e45900e9f86.jpg)

### Propuesta 13

---

![fermat-iop-consortium2](https://cloud.githubusercontent.com/assets/13594347/19507288/6222fef6-95a8-11e6-94be-a2d25820e0a3.jpg)

### Propuesta 14

---

![fermat-iop-consortium3](https://cloud.githubusercontent.com/assets/13594347/19507289/6225f3cc-95a8-11e6-8a21-02a1f210af0d.jpg)

### Propuesta 15

---

![fermat-iop-consortium4](https://cloud.githubusercontent.com/assets/13594347/19507290/6228b7ec-95a8-11e6-8b53-e71e0a1f5252.jpg)

**Comment by victoralfonzohd** [comment]
### Propuesta 16

![iop4](https://cloud.githubusercontent.com/assets/15219855/19531923/7b1ca02e-9607-11e6-94ae-4722d899640f.jpg)

### Propuesta 17

![iop5](https://cloud.githubusercontent.com/assets/15219855/19531931/8c10e232-9607-11e6-9005-f513b2efafc7.jpg)

**Comment by Jessicafp** [comment]
Propuesta 18
![8](https://cloud.githubusercontent.com/assets/19536846/19536178/da744a70-9618-11e6-8438-3db4cc679136.png)

Propuesta 19
![9](https://cloud.githubusercontent.com/assets/19536846/19536186/dcf57788-9618-11e6-8889-053bd6396535.png)

Propuesta 20
![10](https://cloud.githubusercontent.com/assets/19536846/19536179/da8d1564-9618-11e6-98bb-93e62e382ba7.png)

Propuesta 21
![11](https://cloud.githubusercontent.com/assets/19536846/19536180/da9e16fc-9618-11e6-86ac-6264e1cf3fa0.png)

Propuesta 22
![14](https://cloud.githubusercontent.com/assets/19536846/19536183/dadb3b22-9618-11e6-87f0-b285232e70d7.png)

Propuesta 23
![15](https://cloud.githubusercontent.com/assets/19536846/19536184/dadf82cc-9618-11e6-8c1e-c7f8ca695251.png)

@arnaldos

**Comment by isahq23** [comment]
Propuesta 24
![iop_consortium_logo-prop](https://cloud.githubusercontent.com/assets/15214774/19537201/1bcc412c-961d-11e6-8083-cbf32e6c484c.jpg)

**Comment by rosanacoronado** [comment]
@arnaldos 

## Propuesta_25.1

![iopconsortium logo-03](https://cloud.githubusercontent.com/assets/19508456/19564553/ec636948-96b1-11e6-8deb-7b71c213e6de.png)

## Propuesta_25.2

![iopconsortium logo-02](https://cloud.githubusercontent.com/assets/19508456/19564555/ec741d60-96b1-11e6-8881-752aa92d3182.png)

## Propuesta_26.1

![iopconsortium logo-01](https://cloud.githubusercontent.com/assets/19508456/19564554/ec6c7e8e-96b1-11e6-949f-d44124175255.png)

## Propuesta_26.2

![iopconsortium logo-05](https://cloud.githubusercontent.com/assets/19508456/19565296/5746dc52-96b4-11e6-8a63-45db5ce283fa.png)

## Propuesta_26.3

![iopconsortium-04](https://cloud.githubusercontent.com/assets/19508456/19565297/574dc3d2-96b4-11e6-98cc-75555a28045a.png)

## Propuesta_26.4

![iopconsortium-05](https://cloud.githubusercontent.com/assets/19508456/19575940/fa0c7c88-96de-11e6-9b1f-b494909ffc6c.png)

**Comment by ivonnesantos** [comment]
Propuesta 27 Esta es una sola propuesta con sus diferentes variaciones
![lop_p1-iv-01](https://cloud.githubusercontent.com/assets/15238660/19578675/cf14e892-96ea-11e6-85cf-446164c74034.jpg) @arnaldos

**Comment by emmysm** [comment]
Propuesta 28
![propuesta logo iop-01](https://cloud.githubusercontent.com/assets/15143489/19580571/22e69f88-96f5-11e6-94c2-8dfba6c11405.png)

**Comment by isahq23** [comment]
@arnaldos la de @ivonnesantos me parece la mejor

**Comment by emmysm** [comment]
Concuerdo con @isahq23  :D

**Comment by victoralfonzohd** [comment]
### Propuesta 29.1

![iop-consortium-logo](https://cloud.githubusercontent.com/assets/15219855/19582408/10c21384-9702-11e6-8539-6ed74240f745.jpg)

### Propuesta 29.2

Variación en la paleta de colores.

![iop-consortium-logo30](https://cloud.githubusercontent.com/assets/15219855/19598278/043a7d48-9768-11e6-995e-e435cf904c0e.jpg)

**Comment by ivonnesantos** [comment]
Propuesta 30
![lop_propuesta28-01](https://cloud.githubusercontent.com/assets/15238660/19612515/1158131c-97b5-11e6-9bc1-4d4c28206b4e.jpg)

**Comment by karentvillegas** [comment]
Propuesta 31
![propuesta31](https://cloud.githubusercontent.com/assets/19273211/19614017/e5b93cea-97be-11e6-98f1-9e3fbdde6219.png)

Propuesta 32
![propuesta32](https://cloud.githubusercontent.com/assets/19273211/19614018/e5baa260-97be-11e6-9d8e-466845a3e1d1.png)
