### ISSUE TITLE
Crear mokups para la web de IoP consortium sección Join us Version Mobile

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#1028]
Version Pc issue #1007

**Comment by victoralfonzohd** [comment]
@arnaldos 

### Propuesta 1

![join-us-movil1](https://cloud.githubusercontent.com/assets/15219855/19481897/7467562e-951d-11e6-8d9e-d6333ada8e42.jpg)

### Función

![funcion](https://cloud.githubusercontent.com/assets/15219855/19481993/b9462ea0-951d-11e6-9763-14925ea59f98.jpg)

**Comment by arnaldos** [comment]
propuesta 1

**Comment by victoralfonzohd** [comment]
Cambios en la propuesta 1

### Propuesta 1.1

![join-us-mobile](https://cloud.githubusercontent.com/assets/15219855/19491409/d8286202-9540-11e6-9213-6afa37e5b4b7.jpg)
