### ISSUE TITLE
Crear mokups para la web de IoP consortium sección Events Version Mobile

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#1029]
Version Pc issue #1005

**Comment by isahq23** [comment]
Propuesta 1 
![web_iop_events_mobile1](https://cloud.githubusercontent.com/assets/15214774/19490043/8f62e1dc-953b-11e6-8119-494ff579283c.jpg)

Propuesta 2
![web_iop_events_mobile2](https://cloud.githubusercontent.com/assets/15214774/19490050/955a44fe-953b-11e6-9924-351a6d9d56d7.jpg)

NOTA @arnaldos 
No toqué el header ni el footer porque sé que los tienen definidos.

**Comment by arnaldos** [comment]
igual reflejalos para que no se preste a confusión

**Comment by arnaldos** [comment]
Esta propuesta: 
https://cloud.githubusercontent.com/assets/15214774/19490050/955a44fe-953b-11e6-9924-351a6d9d56d7.jpg
