### ISSUE TITLE
Crear ficha para identificar los módulos, en estado de Desarrollo

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#103]
Estado de Desarrollo, se refiere a los módulos que se están construyendo.

Estos módulos se pueden identificar con los colores Rojos como base.

Viene del #92

**Comment by m471c4** [comment]
@Luis-Fernando-Molina, @arnaldos acá los modelos para las fichas de Desarrollo:

![fichasdes](https://cloud.githubusercontent.com/assets/13468350/9828095/f971af84-58b2-11e5-8f8d-5e6ad6db606c.png)

Versión 1:
![fichades1](https://cloud.githubusercontent.com/assets/13468350/9828100/0308c4c4-58b3-11e5-8255-bb123cc9ac61.png)

Versión 2:
![fichades2](https://cloud.githubusercontent.com/assets/13468350/9828102/032b9ddc-58b3-11e5-855e-bf7a39af2923.png)

Versión 3:
![fichades3](https://cloud.githubusercontent.com/assets/13468350/9828103/032ebf76-58b3-11e5-8d34-3c29bc5d9d72.png)

Versión 4:
![fichades4](https://cloud.githubusercontent.com/assets/13468350/9828104/0340702c-58b3-11e5-9cf4-1ae1d7f4addb.png)

Versión 5:
![fichades5](https://cloud.githubusercontent.com/assets/13468350/9828106/03e625d0-58b3-11e5-85a5-1129658fa950.png)

**Comment by m471c4** [comment]
@Luis-Fernando-Molina en las dos primeras mantuve la misma ubicación de la fotografía y demás elementos que ha estado utilizando @arnaldos. En las 3 últimas los cambié, siguiendo tu sugerencia de poner las billeteras al rededor de la fotografía y eso cambió un poco la ubicación.

**Comment by Luis-Fernando-Molina** [comment]
ok, vamos con la version 4, proba por favor el borde naranja ponerlo en blanco, gracias . Asi puede quedar tambien, no está mal, pero probemos.

**Comment by m471c4** [comment]
@Luis-Fernando-Molina acá con los cambios que me pediste:

![fichadesarrollo](https://cloud.githubusercontent.com/assets/13468350/9832213/9e09b462-593d-11e5-8666-7df4bd143fdb.png)

**Comment by Luis-Fernando-Molina** [comment]
@arnaldos @m471c4 necesito que hagamos una prueba de como quedarían estas fichitas si en vez de estar en orientación PORTRAIT estuvieran en LANDSCAPE, porque se adapta mejor al monitor de una computadora cuando se hace zoom sobre alguna de ellas. Veamos como queda por favor (sin poner ningun elemento rotado a 90 grados). Gracias

**Comment by Luis-Fernando-Molina** [comment]
@m471c4 vamos a dejar el borde naranja por favor.

**Comment by m471c4** [comment]
@Luis-Fernando-Molina a partir del modelo final (con el borde naranja), hice 5 versiones de ficha apaisada.

![fichasdeshor](https://cloud.githubusercontent.com/assets/13468350/9843654/389e9684-5a86-11e5-9d87-b23aa9ba43e5.png)

Versión 1:
![fichadeshor1](https://cloud.githubusercontent.com/assets/13468350/9843658/3fbe5ec2-5a86-11e5-9af5-2728498846cb.png)

Versión 2:
![fichadeshor2](https://cloud.githubusercontent.com/assets/13468350/9843659/3fd400ec-5a86-11e5-814c-15506d7750b0.png)

Versión 3:
![fichadeshor3](https://cloud.githubusercontent.com/assets/13468350/9843660/3fded4cc-5a86-11e5-8bbe-132a1fe96b23.png)

Versión 4:
![fichadeshor4](https://cloud.githubusercontent.com/assets/13468350/9843662/3ff0292a-5a86-11e5-88aa-5cf291791880.png)

Versión 5:
![fichadeshor5](https://cloud.githubusercontent.com/assets/13468350/9843661/3fefcab6-5a86-11e5-93bd-e4ea05f5a692.png)

**Comment by Luis-Fernando-Molina** [comment]
De acá vamos a irnos con la version 1 para desarrollo  y @arnaldos con la version.

@Miguelcldn va a necesitar un iconito para Android, otro para Plugin, y otro para Addon. El de plugin in se puede tomar la wallet de PIP que es una especie de enchufe y ponerla en formato del icono este de Android. Para addon, no se.

Tambien va a necesitar los logos de las plataformas y supercapas sin las frases. Y las billeteritas para ponerlas dinamicamente en función de la dificultad.

La base de la ficha se la tienen que dar en vectores igual que los logos de las plataformas. (Cuando alcancemos la version final de alguna ya se la pueden pasar)

**Comment by Luis-Fernando-Molina** [comment]
Proba a la version 1 que ya elegi dividir la parte blanca entre blanco y gris como hiciste antes que eso me gustaba por favor.

**Comment by Miguelcldn** [comment]
@Luis-Fernando-Molina ¿Y para los Libraries no se les pondría ícono?

**Comment by Luis-Fernando-Molina** [comment]
si, tambien, deben tener uno para esos.

**Comment by m471c4** [comment]
@Luis-Fernando-Molina acá con el área blanca dividida. Haré pruebas para los íconos.

![fichadesarrollofinal](https://cloud.githubusercontent.com/assets/13468350/9880738/b7956c54-5b96-11e5-98a8-a9882c594bc4.png)

**Comment by Luis-Fernando-Molina** [comment]
ok, esta se puede quedar así, coordina con @Miguelcldn para que la suba a Fermat.org. Me imagino que antes debés tener los iconos que tiene que colocar en el lugar donde ahora está lo de Android y el trencito.

**Comment by Miguelcldn** [comment]
Pásame un solo diseño (cualquiera) en svg, para ponerlo en todas las fichas y probar el rendimiento. Usar tanto svg (377 fichas actualmente) afectará al rendimiento

**Comment by m471c4** [comment]
@Luis-Fernando-Molina acá con el nombre de la capa en rojo.

![fichadesarrolloletrasrojas](https://cloud.githubusercontent.com/assets/13468350/9886792/f2901d6c-5bb5-11e5-9bb4-21a1490a5116.png)

**Comment by Luis-Fernando-Molina** [comment]
:+1:  este está listo.
