### ISSUE TITLE
Crear mokups para la web de IoP consortium sección News Version Mobile

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#1030]
Version Pc issue #1003

**Comment by rosanacoronado** [comment]
@arnaldos entre cada propuesta solo varía el espaciado entre el bloque de texto y el titulo de la noticia

## Propuesta_1

![iopconsortium_newssection_mobileversion-01](https://cloud.githubusercontent.com/assets/19508456/19484713/7c08986c-9526-11e6-878f-9cae9da493ed.png)

## Propuesta_2

![iopconsortium_newssection_mobileversion2-01](https://cloud.githubusercontent.com/assets/19508456/19484714/7c178c00-9526-11e6-947d-9d1be38fac8f.png)

**Comment by arnaldos** [comment]
coloca la noticia sin la sombra

**Comment by rosanacoronado** [comment]
@arnaldos 

Propuesta 2.1
![iopconsortium_newssection_mobileversion3-01](https://cloud.githubusercontent.com/assets/19508456/19489170/0f522ae6-9538-11e6-882f-48fa4e4fd8ba.png)

Propuesta 2.2 con un leve stroke para que no quede flotando el texto
![iopconsortium_newssection_mobileversion4-01](https://cloud.githubusercontent.com/assets/19508456/19489169/0f4b241c-9538-11e6-9258-52af2105228b.png)

**Comment by arnaldos** [comment]
propuesta 2.1

**Comment by ivonnesantos** [comment]
aprobado con el head que ya tienen el elaborado.
