### ISSUE TITLE
Crear mokups para la web de IoP consortium sección Membership Version Mobile

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#1031]
Version Pc issue #1006 - #1012

**Comment by emmysm** [comment]
**Propuesta 1**
![version mobile-02](https://cloud.githubusercontent.com/assets/15143489/19543940/16530362-9649-11e6-8316-86ad2d36721d.png)

**Propuesta 2**
![version mobile-01](https://cloud.githubusercontent.com/assets/15143489/19543941/1670fc6e-9649-11e6-9371-b8b1daf9f950.png)

@arnaldos

**Comment by emmysm** [comment]
**Propuesta 3**
![version mobile 3-01-01](https://cloud.githubusercontent.com/assets/15143489/19544161/dcfe9822-964a-11e6-85d9-63e9d2b47c4c.png)

@arnaldos

**Comment by isahq23** [comment]
@emmysm la fuente debe aumentar de tamaño, recuerda que es un telf.

**Comment by arnaldos** [comment]
hubo un cambio de esta sección dejo referencia https://cloud.githubusercontent.com/assets/13594347/19628062/ff3c23c6-992b-11e6-930c-f2648c2428cc.jpg
