### ISSUE TITLE
Crear mokups para la web de IoP consortium sección About Version Mobile

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#1032]
Version Pc issue #1004

**Comment by ivonnesantos** [comment]
![about_movil-iv-01](https://cloud.githubusercontent.com/assets/15238660/19491673/d138c788-9541-11e6-9985-84b6216d550a.jpg)
![about_movil-iv-02](https://cloud.githubusercontent.com/assets/15238660/19491674/d14ad716-9541-11e6-8788-c603fc22d75e.jpg)
