### ISSUE TITLE
Create a country versión to Fermat org logo

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#1033]
The logo must have the pieces of the color of the flag of each country

Countries : 
- Switzerland (dayana)
- Morocco (dayana)
- Argentina (rosana)
- Croatia (rosana)
- Germany (alemania)
- Netherlands (holanda)
- Hungary (jessica)
- Southafrica (jessica)
- Venezuela (emmy)
- Australia (emmy)
- Mexico (arnaldo)
- USA (arnaldo)
- Spain (ivonne)

**Comment by victoralfonzohd** [comment]
### Alemania Versión 1

![fermatalemania](https://cloud.githubusercontent.com/assets/15219855/19654053/e32d71da-99e4-11e6-9821-1eaecd5f0067.jpg)

### Alemania Versión 2

![fermatalemania2](https://cloud.githubusercontent.com/assets/15219855/19654951/514a70b6-99e8-11e6-8cfb-4d2ee1014a09.jpg)

### Alemania Versión 3

![fermatalemania3](https://cloud.githubusercontent.com/assets/15219855/19655565/74954fda-99ea-11e6-97b4-20efa2620f93.jpg)

**Comment by victoralfonzohd** [comment]
### Holanda Versión 1

![fermat-holanda1](https://cloud.githubusercontent.com/assets/15219855/19655398/b94b6bf6-99e9-11e6-945e-548e53ff6a64.jpg)

### Holanda Versión 2

![fermatholanda2](https://cloud.githubusercontent.com/assets/15219855/19655136/f3a9dda6-99e8-11e6-845c-24526a188e16.jpg)

### Holanda Versión 3

![fermatholand3](https://cloud.githubusercontent.com/assets/15219855/19655970/e1cc09a8-99eb-11e6-8a09-43c85a970aa8.jpg)

**Comment by arnaldos** [comment]
## EEUU versión 1

## ![fermat_org_eeuu](https://cloud.githubusercontent.com/assets/13594347/19655774/a465ac24-99f3-11e6-92c1-9953ff595fa0.png)

## Mexico versión 1

![fermat_org_mexico](https://cloud.githubusercontent.com/assets/13594347/19655775/a4686900-99f3-11e6-85fa-643fefbd00c8.png)

**Comment by m471c4** [comment]
Para Suiza y Marrucos dejé los símbolos (la cruz y la estrella, respectivamente) derechas, ya que al inclinarlas la estrella quedaba al revés y la cruz se convierte en X.

Switzerland Version 1
![fermat_org_logo_switzerland](https://cloud.githubusercontent.com/assets/13468350/19655848/6cdb287c-99eb-11e6-809c-51de2def4143.png)

Morocco Version 1
![fermat_org_logo_morocco](https://cloud.githubusercontent.com/assets/13468350/19655860/71acd5bc-99eb-11e6-81e4-c80599ab0a45.png)

**Comment by Jessicafp** [comment]
**Hungary Version 1**
![hungary-versio-1](https://cloud.githubusercontent.com/assets/19536846/19656018/1b4dbb7c-99ec-11e6-8fec-f903c9ce19fe.png)

**Southafrica Version 1**
![southafrica-version-1](https://cloud.githubusercontent.com/assets/19536846/19656017/1b349976-99ec-11e6-948f-b6c5eb3065b5.png)

**Comment by arnaldos** [comment]
## Argentina Version 1

## ![fermat_org_argentina](https://cloud.githubusercontent.com/assets/13594347/19657685/9920ac80-99fb-11e6-9f71-53a7422a0b85.png)

## Croatia Version 1

![fermat_org_croatia](https://cloud.githubusercontent.com/assets/13594347/19657780/e7159464-99fb-11e6-92fa-bd27865afe2d.png)

**Comment by emmysm** [comment]
**Venezuela_versión 1**
![fermat_org_logo_vector-03-03](https://cloud.githubusercontent.com/assets/15143489/19657992/3fded48c-99f4-11e6-9805-a56f1f429217.png)

**Venezuela version 2**
![fermat_org_logo_vector-01](https://cloud.githubusercontent.com/assets/15143489/19657699/449a4066-99f3-11e6-8f00-7eff516299e6.png)

**Venezuela version 3**

![fermat_org_logo_vectr-03](https://cloud.githubusercontent.com/assets/15143489/19660807/4519a264-99ff-11e6-96a9-c5b91ffec472.png)

**Comment by arnaldos** [comment]
## Australia versión 1

![fermat_org_australia](https://cloud.githubusercontent.com/assets/13594347/19658695/42f9df1c-99ff-11e6-8e46-eb40f0434392.png)

**Comment by proseuz** [comment]
## Southafrica  Versión 2

![fermat_org_logo_vector](https://cloud.githubusercontent.com/assets/17308060/19658960/0548d0b2-99f8-11e6-8430-b4396d4e34b5.jpg)

**Comment by ivonnesantos** [comment]
version_1
![spain_v1-01](https://cloud.githubusercontent.com/assets/15238660/19659139/c8c1cdc8-99f8-11e6-8107-3d31bb5b01dd.png)

**Comment by rosanacoronado** [comment]
Versiones frontales

Argentina_Version 2
![fermat_org_logo_vector_argentina-03](https://cloud.githubusercontent.com/assets/19508456/19659333/88843696-99f9-11e6-9bb6-0c14d892ab14.png)

Croatia _Version 2
![fermat_org_logo_vectorcroatia2-03](https://cloud.githubusercontent.com/assets/19508456/19659804/4f44e950-99fb-11e6-80c3-c3ba5e81ceff.png)

**Comment by victoralfonzohd** [comment]
### Sudafrica Version 3

![sudafrica](https://cloud.githubusercontent.com/assets/15219855/19659955/f686af50-99fb-11e6-9857-21ceb64221f4.jpg)

**Comment by Luis-Fernando-Molina** [comment]
En general esta bien,  lo único que no me hicieron caso fue lo siguiente :

Si una bandera tiene color rojo por ejemplo,  el rojo debe descomponerse en rojo claro y oscuro e ir intercalado de la misma manera que el logotipo de Internet of People tiene el mismo color azul con dos tonos de azules,  el amarillo con dos tonos y el rojo con dos tonos. 

Corrijan eso por favor.

**Comment by Luis-Fernando-Molina** [comment]
Alemania seguir con versión 1 porque es el que más se parece al original de IoP

**Comment by Luis-Fernando-Molina** [comment]
Holanda version 2 con más azul

**Comment by Luis-Fernando-Molina** [comment]
Usa y México están OK (falta las 2 tonalidades que expliqué)

**Comment by ivonnesantos** [comment]
Version 2 igual pero con escudo 
![spain_v2-01](https://cloud.githubusercontent.com/assets/15238660/19660886/8fdcf378-99ff-11e6-9ef1-34611b9b0a31.png)

**Comment by Luis-Fernando-Molina** [comment]
Todo el resto la versión 1 es la que va,  con los dos tonos

**Comment by m471c4** [comment]
@Luis-Fernando-Molina con lsa correcciones solicitadas:

Switzerland Version 2
![fermat_org_logo_switzerland](https://cloud.githubusercontent.com/assets/13468350/19661633/76e7c2b4-9a02-11e6-85d3-c43d31d6013a.png)

Morocco Version 2
![fermat_org_logo_morocco](https://cloud.githubusercontent.com/assets/13468350/19661645/813924ce-9a02-11e6-9740-b310d5897c6d.png)

**Comment by emmysm** [comment]
**Venezuela**
![fermat_org_logo_vector--03-03](https://cloud.githubusercontent.com/assets/15143489/19662527/e58ba5ca-9a05-11e6-9496-55748d5ee4f2.png)

**venezuela version 1.1**
![fermat_org_logo_vector 1-01](https://cloud.githubusercontent.com/assets/15143489/19662727/d699b0d8-9a06-11e6-8bd3-0991d828d058.png)

**Comment by Jessicafp** [comment]
Southafrica Version 4
![southafrica-version-4](https://cloud.githubusercontent.com/assets/19536846/19661796/15cbe7a2-9a03-11e6-8919-cac9d74bc1c5.png)

Hungary Version 2 
![hungary-version-2](https://cloud.githubusercontent.com/assets/19536846/19662111/4ad05130-9a04-11e6-99ef-123a206a7f70.png)

**Comment by ivonnesantos** [comment]
Version spain con cambios
![spain_v1-01](https://cloud.githubusercontent.com/assets/15238660/19662360/1b24c5c8-9a05-11e6-9d40-cca47963348d.png)

**Comment by victoralfonzohd** [comment]
### Alemania V1.1 Cambios de Color

![alemania](https://cloud.githubusercontent.com/assets/15219855/19662493/b857b0bc-9a05-11e6-9ae3-a460d9c60ddb.jpg)

### Holanda V2.1 Cambios de Color

![holanda](https://cloud.githubusercontent.com/assets/15219855/19662499/c0a22df6-9a05-11e6-952e-bc49a7ce3547.jpg)

**Comment by arnaldos** [comment]
Argentina
![fermat_org_argentina](https://cloud.githubusercontent.com/assets/13594347/19663508/9fabd7ac-9a12-11e6-96dd-1b8376d8121d.png)

---

Australia

## ![fermat_org_australia](https://cloud.githubusercontent.com/assets/13594347/19663385/1edb059e-9a12-11e6-9f3a-87f031d7dc59.png)

Croatia

## ![fermat_org_croatia](https://cloud.githubusercontent.com/assets/13594347/19663387/1ee081b8-9a12-11e6-8c8a-651fce685785.png)

EEUU

## ![fermat_org_eeuu](https://cloud.githubusercontent.com/assets/13594347/19663386/1edff720-9a12-11e6-8933-db227166520e.png)

Mexico
![fermat_org_mexico](https://cloud.githubusercontent.com/assets/13594347/19663388/1ee31c2a-9a12-11e6-9989-955a6d83da76.png)

**Comment by arnaldos** [comment]
## Ajustes

#### Hungria

## ![fermat_hungary](https://cloud.githubusercontent.com/assets/13594347/19668055/5c9c192c-9a2b-11e6-8d46-0aa42fc7068f.png)

#### Alemania

## ![fermat_org_alemania](https://cloud.githubusercontent.com/assets/13594347/19668054/5c9a6528-9a2b-11e6-89dc-a89ab2c2b304.png)

#### Argentina

## ![fermat_org_argentina](https://cloud.githubusercontent.com/assets/13594347/19668057/5c9ec140-9a2b-11e6-8edc-23362d0f02eb.png)

#### Australia

## ![fermat_org_australia](https://cloud.githubusercontent.com/assets/13594347/19668056/5c9dccae-9a2b-11e6-9b44-a6b5163a7b9b.png)

#### Croatia

## ![fermat_org_croatia](https://cloud.githubusercontent.com/assets/13594347/19668058/5cb3cf5e-9a2b-11e6-9f9f-57499e59bfe2.png)

### EEUU

## ![fermat_org_eeuu](https://cloud.githubusercontent.com/assets/13594347/19668059/5cb7dc66-9a2b-11e6-8589-34e923f5f282.png)

#### Mexico

## ![fermat_org_mexico](https://cloud.githubusercontent.com/assets/13594347/19668061/5cbd57e0-9a2b-11e6-950f-c60079b8bdcc.png)

#### Southafrica

## ![fermat_org_southafrica](https://cloud.githubusercontent.com/assets/13594347/19668062/5cc32cb0-9a2b-11e6-8338-79a27c1937a1.png)

#### España

## ![fermat_org_spain-01](https://cloud.githubusercontent.com/assets/13594347/19668063/5cd22dd2-9a2b-11e6-8add-584726b0f864.png)

#### Venezuela

## ![fermat_org_venezuela](https://cloud.githubusercontent.com/assets/13594347/19668111/c0e35422-9a2b-11e6-8092-0ec41761ca2b.png)

#### Holanda

## ![fermat_org_netherland](https://cloud.githubusercontent.com/assets/13594347/19668112/c0e72976-9a2b-11e6-8859-a4f1b62c88bf.png)

#### Morroco

## ![fermat_org_morocco](https://cloud.githubusercontent.com/assets/13594347/19668201/6636276a-9a2c-11e6-8af7-4743bd304bce.png)

#### Switzerland

![fermat_org_switzerland](https://cloud.githubusercontent.com/assets/13594347/19668660/a5a248f4-9a2f-11e6-98fe-4042bc4b0493.png)
