### ISSUE TITLE
Create a Background to IoP website 

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#1035]
Is a collage image profile 

Image reference

![image](https://cloud.githubusercontent.com/assets/13594347/19856738/85f6633a-9f59-11e6-9e76-3f0408214eaf.png)

Size 1980x1280 px

**Comment by karentvillegas** [comment]
Propuesta 1

![propuesta_1](https://cloud.githubusercontent.com/assets/19273211/19860808/ade2a528-9f60-11e6-8e86-65acc37ca926.png)

@arnaldos

**Comment by victoralfonzohd** [comment]
### Propuesta 2

![sin-titulo-1](https://cloud.githubusercontent.com/assets/15219855/19864386/660159da-9f6e-11e6-82d7-57b7713e8f89.jpg)

**Comment by proseuz** [comment]
**Propuesta 3**
![profile-02-01](https://cloud.githubusercontent.com/assets/17308060/19866877/4afd2894-9f78-11e6-9010-32f7217f102e.jpg)
**Propuesta 4**
![profile-01](https://cloud.githubusercontent.com/assets/17308060/19866878/4b684b74-9f78-11e6-8ddd-a3930968dd74.jpg)

**Comment by ivonnesantos** [comment]
Propuesta 5
![backcgraund_1-01](https://cloud.githubusercontent.com/assets/15238660/19868328/f141c124-9f7d-11e6-9bc5-5b2eb43244ef.png)

**Comment by arnaldos** [comment]
@karentvillegas y @ivonnesantos 
trabajemos la version 1 con la propuesta de los perfiles de la version 5

**Comment by ivonnesantos** [comment]
propuesta 6
![back_2](https://cloud.githubusercontent.com/assets/15238660/19870859/c66e76e4-9f88-11e6-86f5-1fdfcf40ba84.png)

**Comment by Jessicafp** [comment]
Propuesta 7
![propuesta-1](https://cloud.githubusercontent.com/assets/19536846/19871330/d393c20a-9f8a-11e6-90d5-3edd358bbb1f.jpg)

Propuesta 8
![propuesta-2](https://cloud.githubusercontent.com/assets/19536846/19871331/d397be46-9f8a-11e6-912c-47b010083a6d.jpg)

**Comment by arnaldos** [comment]
@karentvillegas y @ivonnesantos 
por ahora propuesta 1 pero trabajemos una opcion con la version 1 con la propuesta de los perfiles de la version 5

**Comment by ivonnesantos** [comment]
@arnaldos si ya se esta haciendo una version combinada yo le pase el archivo a kerent pero subio muy tarde hoy debe postear algo de eso.

**Comment by arnaldos** [comment]
ah perfecto !!!!

**Comment by karentvillegas** [comment]
Propuesta 9
![propuesta_3](https://cloud.githubusercontent.com/assets/19273211/19904532/60434694-a049-11e6-91dc-086d3d79e204.png)

Propuesta10
![propuesta_4](https://cloud.githubusercontent.com/assets/19273211/19904533/604913da-a049-11e6-9e89-e2553a6c5ade.png)

@arnaldos

**Comment by arnaldos** [comment]
propuesta 1 definitiva

**Comment by Luis-Fernando-Molina** [comment]
No salen los nombre ni la ciudad, como en los ejemplos que mande

**Comment by Luis-Fernando-Molina** [comment]
En general no me gusta ninguna. No se ve como una red impresionante de gente de nivel global.

**Comment by arnaldos** [comment]
Luis me mandaste un seriado de varias capturas de la pelicula, y debajo tu comentario

> esa es una escena de la película SNOWDEN me gustaría ver si podemos hacer un background para el sitio inspirado en ese tipo de collage.

En ningún momento solicitas exactamente una idea clara donde describa que quieres texto y demás elementos, si quieres reflejar algo en la imagen describe por favor que es lo que quieres realmente y no nos dejes a la interpretación porque sino seguiremos sin entendernos y perdiendo el tiempo.
