### ISSUE TITLE
Crear ficha para identificar los módulos, en estado de QA

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#104]
Estado de QA, se refiere a los módulos que están en control de calidad, ya están terminados pero aun se están verificando o probando.

Estos módulos se pueden identificar con los colores Amarillos como base.

Viene del #92

**Comment by m471c4** [comment]
@Luis-Fernando-Molina, @arnaldos acá los modelos para las fichas de QA. Usé uno de los colores de la paleta para que no desentone y dejé la esquina superior derecha más curva, para que sea más distintiva la forma. En este caso me inclino por la versión 2:

![fichasqa](https://cloud.githubusercontent.com/assets/13468350/9829269/29b593d6-58c7-11e5-9036-164c053ae918.png)

Versión 1:
![fichaqa1](https://cloud.githubusercontent.com/assets/13468350/9829270/35a7a8f0-58c7-11e5-8894-896b5861f0bb.png)

Versión 2:
![fichaqa2](https://cloud.githubusercontent.com/assets/13468350/9829271/35dfb9e8-58c7-11e5-9983-d0d8b1eafb93.png)

Versión 3:
![fichaqa3](https://cloud.githubusercontent.com/assets/13468350/9829272/360ecc42-58c7-11e5-895d-8caa963e7ea4.png)

Versión 4:
![fichaqa4](https://cloud.githubusercontent.com/assets/13468350/9829274/370de452-58c7-11e5-8dec-aa808208bf47.png)

Versión 5:
![fichaqa5](https://cloud.githubusercontent.com/assets/13468350/9829273/36c89618-58c7-11e5-8dc8-30dd8d5b0601.png)

**Comment by Luis-Fernando-Molina** [comment]
Me gustaron! Vamos con la version 1, con el aro verde de color naranja oscuro, aunque se pierda en una parte (proba con el claro tambine) gracias.

**Comment by m471c4** [comment]
@Luis-Fernando-Molina acá las pruebas que me pediste:

Aro color naranja:
![fichaqafin1](https://cloud.githubusercontent.com/assets/13468350/9832220/fa7c3526-593d-11e5-8b09-f469fe6f1f47.png)

Aro color ocre:
![fichaqafin2](https://cloud.githubusercontent.com/assets/13468350/9832221/fa842fb0-593d-11e5-9d41-5604292ceda5.png)

**Comment by Luis-Fernando-Molina** [comment]
@arnaldos proba por favor que esté solo el medio circulo de abajo, y las billeteras repartilas en ese cuadrante, gracias.

Como dije antes, hacé la version landscape please.

**Comment by m471c4** [comment]
@Luis-Fernando-Molina acá con las billeteras en medio círculo. Subí un poco la foto para darle más equilibrio. En un rato hago las pruebas con el formato apaisado (landscape).

![fichaqafin3](https://cloud.githubusercontent.com/assets/13468350/9840006/e4e9d44a-5a53-11e5-8b50-963c7a7c573e.png)

**Comment by m471c4** [comment]
@Luis-Fernando-Molina a partir de este modelo, hice 5 versiones de ficha apaisada.

![fichasqahor](https://cloud.githubusercontent.com/assets/13468350/9843600/bbfbda56-5a85-11e5-8310-561b2370ad70.png)

Versión 1:
![fichaqahor1](https://cloud.githubusercontent.com/assets/13468350/9843611/c8e3d2b4-5a85-11e5-83d7-9168bcd8279b.png)

Versión 2:
![fichaqahor2](https://cloud.githubusercontent.com/assets/13468350/9843610/c8e392c2-5a85-11e5-99d6-45db72d3fee7.png)

Versión 3:
![fichaqahor3](https://cloud.githubusercontent.com/assets/13468350/9843609/c8e274f0-5a85-11e5-9b8a-28d4279c721b.png)

Versión 4:
![fichaqahor4](https://cloud.githubusercontent.com/assets/13468350/9843612/c8eb8b08-5a85-11e5-9b16-2c0220d1e70d.png)

Versión 5:
![fichaqahor5](https://cloud.githubusercontent.com/assets/13468350/9843613/c8f38024-5a85-11e5-8702-4a8f673431f9.png)

**Comment by Luis-Fernando-Molina** [comment]
@m471c4 estan muy lindas las fichitas asi. yo creo que de acá puenden salir los modelos para los 2 estados. 

1) Para este de QA vamos a usar La version 2. Para contunuarla proba poner el nombre de la capa en amarillo, asi no se destaca tanto y vemos si queda mejor.

2) Para produccion @arnaldos  pudiera ir la version 4 (con ajuste en el color).

3) Tambien fijate de ponerle el tipo de letra de Fermat.

**Comment by m471c4** [comment]
@Luis-Fernando-Molina acá la prueba de poner la capa en un medio círculo, pero no creo que funcione, porque las longitudes de esos textos van a variar (de hecho, tuve que disminuir el tamaño para que entrara completo) y @Miguelcldn debe generar esos textos.

![fichaqafinal](https://cloud.githubusercontent.com/assets/13468350/9881341/4ace0a38-5b99-11e5-91ed-8d96ec0d1fed.png)

**Comment by Luis-Fernando-Molina** [comment]
> @Luis-Fernando-Molina acá la prueba de poner la capa en un medio círculo, pero no creo que funcione, 

No se de donde entendiste eso, pero no me referia a poner el nombre del plugin asi.

Deja el nombre del plugin como siempre por favor y practicamente queda terminado este caso.

**Comment by m471c4** [comment]
@Luis-Fernando-Molina 

![fichaqaletrasamarillas](https://cloud.githubusercontent.com/assets/13468350/9886388/e7b2de22-5bb3-11e5-9289-b9c0ddad4cd4.png)
