### ISSUE TITLE
Create a Banner to IoP Voting App 

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#1047]
Reference issue #1044

Size 1024x500

**Comment by andiechan** [comment]
**Propuesta 01**
![v_01](https://cloud.githubusercontent.com/assets/19866300/20188533/73713278-a74f-11e6-9d39-20ab97f2a50a.jpg)

**Propuesta 1.2** 
![v_02](https://cloud.githubusercontent.com/assets/19866300/20188534/738b4564-a74f-11e6-8cea-84c0194850f6.jpg)

**Comment by andiechan** [comment]
**Propuesta 1.3** 
![v_03](https://cloud.githubusercontent.com/assets/19866300/20189335/1efe5f5a-a753-11e6-8834-9a4004fd1299.jpg)

**Comment by andiechan** [comment]
**Propuesta 1.4**
![v_04](https://cloud.githubusercontent.com/assets/19866300/20189971/e0853304-a755-11e6-8416-5f9dcfccf60f.jpg)

**Comment by andiechan** [comment]
**Propuesta 1.5**
![v_05](https://cloud.githubusercontent.com/assets/19866300/20199011/3a3465dc-a77e-11e6-8e39-2c647ef1cc8e.jpg)

**Comment by ivonnesantos** [comment]
Hazte uno con un fondo claro y coloca una foto de un telefono y tambien puedes hacer una propuesta con foto de fondo @andiechan

**Comment by andiechan** [comment]
**Propuesta 02**
![v_06](https://cloud.githubusercontent.com/assets/19866300/20200847/13eda24c-a78a-11e6-9282-f0a31463d823.jpg)

Propuesta 03
![v_07](https://cloud.githubusercontent.com/assets/19866300/20200957/eaeee49a-a78a-11e6-8146-f7c75982fec0.jpg)

**Comment by andiechan** [comment]
**Propuesta 04**
![v_08](https://cloud.githubusercontent.com/assets/19866300/20201702/6220538c-a790-11e6-8093-db566d1e2b12.JPG)
