### ISSUE TITLE
Create a Icon/logo to IoP Voting App 

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#1048]
reference issue #1044

**Comment by victoralfonzohd** [comment]
@arnaldos 

### Propuesta 1

![iopvonting](https://cloud.githubusercontent.com/assets/15219855/20148013/fa49bc04-a680-11e6-8b8c-1a6b02ea36fe.jpg)

### Propuesta 2

![iopvonting2](https://cloud.githubusercontent.com/assets/15219855/20148512/70d4a9ea-a683-11e6-81c2-8a27027e9b19.jpg)

**Comment by ivonnesantos** [comment]
Esta bien me gusta trata de hacer una version en la que manejes el icono y la tipografia

**Comment by rosanacoronado** [comment]
@arnaldos @ivonnesantos 

Propuesta_3
![vapp4-01](https://cloud.githubusercontent.com/assets/19508456/20148915/330e2602-a685-11e6-9ce0-45afadfb45b7.png)

Propuesta_4
![voting app 1-01](https://cloud.githubusercontent.com/assets/19508456/20148860/e9ee882c-a684-11e6-8a33-b2e7b4d7108c.png)

Propuesta_5
![voting app 2-01](https://cloud.githubusercontent.com/assets/19508456/20148859/e9eaa338-a684-11e6-9ad6-6aafc22a91cd.png)

Propuesta_6
![vapp5-01](https://cloud.githubusercontent.com/assets/19508456/20149333/34229f1c-a687-11e6-9eb6-5a0d2e3f3818.png)

Propuesta_7
![vapp6-01](https://cloud.githubusercontent.com/assets/19508456/20149334/3425a388-a687-11e6-907c-7c9e132b089a.png)

**Comment by ivonnesantos** [comment]
Me gustaria que continuaramos con la propuesta 1 de victor y la 5 de rosana talves hacer otras versiones enfocando otro aspecto si embargo la ultima palabra la tiene @arnaldos

**Comment by ivonnesantos** [comment]
Propuesta 8 
Hice como una representacion del switch que ellos piden para la app en este punto "10. Tendrán un interruptor colocado por defecto en el centro, entre SI y NO. Bajando el interruptor a la izquierda votarán SÍ y al NO derecho"
![icon-01](https://cloud.githubusercontent.com/assets/15238660/20157834/99128510-a6ad-11e6-863f-83f595583453.png)

@arnaldos

**Comment by rosanacoronado** [comment]
@arnaldos @ivonnesantos nuevas propuestas basándome en mis propuestas anteriores, e integrando un poco mas la parte iconica con la tipográfica

Propuesta_9
![logo 1-01](https://cloud.githubusercontent.com/assets/19508456/20162143/6192a2fc-a6c9-11e6-95b9-abc651f228ea.png)

Propuesta_10
![logo 2-01](https://cloud.githubusercontent.com/assets/19508456/20162142/618fb31c-a6c9-11e6-8b87-345e163248c3.png)

Propuesta_11
![logo 3-01](https://cloud.githubusercontent.com/assets/19508456/20162144/619b1ed2-a6c9-11e6-9bb7-5ce92302a4d7.png)

**Comment by ivonnesantos** [comment]
Ah se ve muy bien me gusta bastante

**Comment by andiechan** [comment]
A mi también me gusto bastante estas versiones, sobretodo la propuesta 9

**Comment by ivonnesantos** [comment]
@rosanacoronado de la propuesta 9 podríamos hacer una versión que de alguna manera el usuario cuando vea el icono en móvil sepa que esa es la aplicación relacionada con IoP

**Comment by rosanacoronado** [comment]
@arnaldos @ivonnesantos jugando con los colores del logo IoP y con los elementos graficos del mismo (tuercas y fichas)

Propuesta_9.1
![prueba color 1-01](https://cloud.githubusercontent.com/assets/19508456/20201249/fb0c2d72-a78c-11e6-85e8-ef182d8f0ca8.png)

9.2
![prueba color 2-01](https://cloud.githubusercontent.com/assets/19508456/20201250/fb124964-a78c-11e6-85b3-24cff75d2b42.png)

9.3
![prueba color 3-01](https://cloud.githubusercontent.com/assets/19508456/20201251/fb25258e-a78c-11e6-838d-77c285ae2d87.png)

9.4
![ioplogovotingcolor3-01](https://cloud.githubusercontent.com/assets/19508456/20201277/263c4662-a78d-11e6-8a0b-e0e7185a9ac8.png)

9.5
![ioplogovotingcolor4-01](https://cloud.githubusercontent.com/assets/19508456/20201278/2645e0a0-a78d-11e6-846d-9bca0e9ff9a5.png)

9.6
![ioplogovotingcolor6-01](https://cloud.githubusercontent.com/assets/19508456/20201280/264e8eda-a78d-11e6-95c6-24ef07987c37.png)

9.7
![ioplogovotingcolor7-01](https://cloud.githubusercontent.com/assets/19508456/20201281/265a2d44-a78d-11e6-9108-6429080dde2f.png)

**Comment by arnaldos** [comment]
propuesta escogida nro 10 de @rosanacoronado
