### ISSUE TITLE
Footer to website

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#1049]

**Comment by emmysm** [comment]
Propuesta 1
![footers-01-04](https://cloud.githubusercontent.com/assets/15143489/20111397/6eab6d4a-a5be-11e6-9a7c-263fa26bee67.png)

Propuesta 2
![footers-01-01](https://cloud.githubusercontent.com/assets/15143489/20111398/6eae6e3c-a5be-11e6-8196-61efc90c7852.png)

Propuesta 3
![footers-01-02](https://cloud.githubusercontent.com/assets/15143489/20111400/6eb5ebee-a5be-11e6-94ef-d438a5ea533e.png)

Propuesta 4
![footers-01-03](https://cloud.githubusercontent.com/assets/15143489/20111399/6eb2b1d6-a5be-11e6-8745-1d748a6ee3cf.png)

Propuesta 5

![footer 5-01](https://cloud.githubusercontent.com/assets/15143489/20111954/a985be96-a5c0-11e6-892e-3914372124f9.png)

Propuesta 6
![footer 6-01](https://cloud.githubusercontent.com/assets/15143489/20112015/ef48043e-a5c0-11e6-9693-918ec16bd48f.png)

Propuesta 7

![footer 7-01](https://cloud.githubusercontent.com/assets/15143489/20112298/2c98f428-a5c2-11e6-91cd-74ee00683c01.png)

Propuesta 8

![footer 8-06](https://cloud.githubusercontent.com/assets/15143489/20112662/9c47b4ac-a5c3-11e6-90fd-e1205aed79c2.png)

Propuesta 9

![footer 9-06](https://cloud.githubusercontent.com/assets/15143489/20113000/ef20985a-a5c4-11e6-86d2-169b9d59bc99.png)

Propuesta 10
![fotter 10-07](https://cloud.githubusercontent.com/assets/15143489/20113425/c595cc42-a5c6-11e6-9bb6-2476baefc71d.png)

Propuesta 11
![footer 11-07](https://cloud.githubusercontent.com/assets/15143489/20113482/f798a9c6-a5c6-11e6-9314-34da0b66d983.png)

@arnaldos

**Comment by emmysm** [comment]
Propuesta 11
![propuestas-07](https://cloud.githubusercontent.com/assets/15143489/20114591/44ffdafa-a5cb-11e6-9dc3-86f415074955.png)

Propuesta 12
![propuestas-05](https://cloud.githubusercontent.com/assets/15143489/20114593/45029290-a5cb-11e6-863c-01d56ff39f81.png)

Propuesta 13
![propuestas-06](https://cloud.githubusercontent.com/assets/15143489/20114592/45022bfc-a5cb-11e6-9189-9116932b3e74.png)

Propuesta 14
![propuesta 14-06](https://cloud.githubusercontent.com/assets/15143489/20114742/daeefbfe-a5cb-11e6-89ec-134b832c502e.png)

Propuesta 15

![propuesta 13-06](https://cloud.githubusercontent.com/assets/15143489/20114747/e09d51cc-a5cb-11e6-94e4-3a49ea706402.png)

**Comment by emmysm** [comment]
Propuesta 16
![footer blue-02](https://cloud.githubusercontent.com/assets/15143489/20115409/908672ba-a5ce-11e6-8d57-15de4333ef4c.png)

Propuesta 17
![footer blue-08](https://cloud.githubusercontent.com/assets/15143489/20115411/90ada128-a5ce-11e6-89d3-70ced66c6505.png)

Propuesta 18
![footer blue-07](https://cloud.githubusercontent.com/assets/15143489/20115410/90abbf16-a5ce-11e6-94ae-850fd5a77dab.png)

Propuesta 19
![footer blue-06](https://cloud.githubusercontent.com/assets/15143489/20115412/90bfc920-a5ce-11e6-9388-08fb0762ca95.png)

Propuesta 20
![footer blue-05](https://cloud.githubusercontent.com/assets/15143489/20115413/90c62c0c-a5ce-11e6-9459-95a6e3b7f5ad.png)

Propuesta 21
![footer blue-03](https://cloud.githubusercontent.com/assets/15143489/20115414/90c88f92-a5ce-11e6-84b3-bb2cec06bf2e.png)

Propuesta 22
![footer blue-04](https://cloud.githubusercontent.com/assets/15143489/20115415/90c9d190-a5ce-11e6-977e-7621e4feb93c.png)

@arnaldos

**Comment by arnaldos** [comment]
Propuesta 20 o 22 no se que opines @Luis-Fernando-Molina

**Comment by Luis-Fernando-Molina** [comment]
Ninguno con foto va

Debemos tener un estilo para el sitio, de ahi sale el footer. Cual seria el estilo?

**Comment by Jessicafp** [comment]
Propuesta 23
![propuesta-1](https://cloud.githubusercontent.com/assets/19536846/20116629/636a58be-a5d3-11e6-8902-f2c3ca02e058.png)

Propuesta 24
![propuesta-2](https://cloud.githubusercontent.com/assets/19536846/20116627/6368fdc0-a5d3-11e6-9a7a-bf58af59c872.png)

Propuesta 25
![propuesta-3](https://cloud.githubusercontent.com/assets/19536846/20116628/63694de8-a5d3-11e6-9369-a8ff9065519d.png)

Propuesta 26
![propuesta-4](https://cloud.githubusercontent.com/assets/19536846/20116630/637bbe6a-a5d3-11e6-88d5-415474c3cdcc.png)

@arnaldos

**Comment by Jessicafp** [comment]
Propuesta 27
![propuesta-5](https://cloud.githubusercontent.com/assets/19536846/20116835/3fd772c8-a5d4-11e6-9be1-f91e1e762d41.png)

@arnaldos

**Comment by emmysm** [comment]
Propuesta 28
![footer 22-05](https://cloud.githubusercontent.com/assets/15143489/20117164/b7225568-a5d5-11e6-8640-62aae1775f5e.png)

**Comment by Jessicafp** [comment]
Propuesta 29
![propuesat-7](https://cloud.githubusercontent.com/assets/19536846/20117086/6c5294d0-a5d5-11e6-918c-4e68a80e678e.png)

Propuesta 30
![propuesta-6](https://cloud.githubusercontent.com/assets/19536846/20117234/08ba74dc-a5d6-11e6-99b1-08b4f4931d7d.png)

@arnaldos

**Comment by emmysm** [comment]
Propuesta 29

![footer 23-03](https://cloud.githubusercontent.com/assets/15143489/20117376/aa50bfd6-a5d6-11e6-8a94-3f5847dc76b3.png)

**Comment by Jessicafp** [comment]
Propuesta 32
![propuesta-9](https://cloud.githubusercontent.com/assets/19536846/20117718/28ff71b4-a5d8-11e6-9513-3205eab5b919.png)

@arnaldos

**Comment by Jessicafp** [comment]
Propuesta 33
![propuesta-8](https://cloud.githubusercontent.com/assets/19536846/20117920/fd882f7a-a5d8-11e6-9101-e2bd358c78fc.png)

Propuesta 34
![propuesta-10](https://cloud.githubusercontent.com/assets/19536846/20117917/fc9fb2a4-a5d8-11e6-9723-9a66a7d78155.png)

@arnaldos

**Comment by emmysm** [comment]
Footer 35
![footer 34-03](https://cloud.githubusercontent.com/assets/15143489/20118228/1c50a742-a5da-11e6-8190-48d8ccc5fd2d.png)

**Comment by emmysm** [comment]
Propuesta 36
![footer 35 -05-05](https://cloud.githubusercontent.com/assets/15143489/20119007/296ac946-a5dd-11e6-9a7c-086009420d88.png)

Propuesta 37
![footer 35 -05-04](https://cloud.githubusercontent.com/assets/15143489/20119008/298b15c0-a5dd-11e6-8cf1-85c96988ad33.png)

Propuesta 38

![propuesta 38-04](https://cloud.githubusercontent.com/assets/15143489/20119246/25070436-a5de-11e6-9e73-215b366602f1.png)

Propuesta 39
![propuesta 39-08-03](https://cloud.githubusercontent.com/assets/15143489/20120362/e95ba310-a5e2-11e6-90ec-edb63fcc5bd3.png)

Propuesta 40

![propuesta 39-08-08](https://cloud.githubusercontent.com/assets/15143489/20120359/e7232f8c-a5e2-11e6-92f3-d390353a7782.png)

**Comment by emmysm** [comment]
Propuesta 41
![propuesta 40-01](https://cloud.githubusercontent.com/assets/15143489/20121159/54e4cd16-a5e6-11e6-8b64-c3b0985cff13.png)

Propuesta 42
![propuesta 40-03](https://cloud.githubusercontent.com/assets/15143489/20121160/54e95caa-a5e6-11e6-8d19-d2dcc2986a1d.png)

Propuesta 43
![propuesta 40-08](https://cloud.githubusercontent.com/assets/15143489/20121161/5510ac6a-a5e6-11e6-8639-3c37776caaaf.png)

![propuesta 40-01](https://cloud.githubusercontent.com/assets/15143489/20121265/e12d2714-a5e6-11e6-95d4-af995157eb23.png)

Propuesta 45
![propuesta 40-02](https://cloud.githubusercontent.com/assets/15143489/20121196/7fd8399a-a5e6-11e6-844a-6deec266f9bd.png)

**Comment by emmysm** [comment]
Propuesta 46
![propuesta 45-08](https://cloud.githubusercontent.com/assets/15143489/20121528/8296fca0-a5e8-11e6-8c84-39bed16b4545.png)

Propuesta 47
![propuesta 45-01](https://cloud.githubusercontent.com/assets/15143489/20121529/829bb98e-a5e8-11e6-8ca6-dad71761e02b.png)

Propuesta 48
![propuesta 45-02](https://cloud.githubusercontent.com/assets/15143489/20121530/82a05d86-a5e8-11e6-963e-e0d1b5bfd689.png)

Propuesta 49
![propuesta 45-03](https://cloud.githubusercontent.com/assets/15143489/20121531/82a3e76c-a5e8-11e6-8c9e-cd2f74632234.png)

@Luis-Fernando-Molina

**Comment by Jessicafp** [comment]
Propuesta 50
![propuesta-11](https://cloud.githubusercontent.com/assets/19536846/20121826/edc4ca9c-a5e9-11e6-96b6-bb27f421c1ef.png)

Propuesta 51
![propuesta-12](https://cloud.githubusercontent.com/assets/19536846/20121827/edca79ce-a5e9-11e6-9af9-e8ed0048b688.png)

Propuesta 52
![propuesta-13](https://cloud.githubusercontent.com/assets/19536846/20121828/edcf184e-a5e9-11e6-8aa3-74e7f9807c98.png)

@arnaldos

**Comment by arnaldos** [comment]
Propuesta 53

## ![footer_2](https://cloud.githubusercontent.com/assets/13594347/20125812/d86e948c-a60e-11e6-9003-b6e432927612.jpg)

Propuesta 54

## ![footer_3](https://cloud.githubusercontent.com/assets/13594347/20125813/d8911fca-a60e-11e6-9c2a-b8f2ce744b6d.jpg)

Propuesta 55

## ![footer_4](https://cloud.githubusercontent.com/assets/13594347/20125814/d895aed2-a60e-11e6-9231-71f18ac81776.jpg)

Propuesta 56
![footer_5](https://cloud.githubusercontent.com/assets/13594347/20125815/d8ade146-a60e-11e6-94d4-d0125fa1076e.jpg)

**Comment by Luis-Fernando-Molina** [comment]
vamos con la 56 . gracias

**Comment by arnaldos** [comment]
perfecto
