### ISSUE TITLE
Crear ficha para identificar los módulos, en estado de Producción 

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#105]
Estado de Producción, se refiere a los módulos que están terminados y en funcionamiento 

Estos módulos se pueden identificar con los colores Verdes como base.

Viene del #92

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina Ficha de Estado de Producción

![ficha_descriptiva_fermat_org_concepto_y_produccion1](https://cloud.githubusercontent.com/assets/13594347/9818513/d99cf226-5872-11e5-93a1-f6623f16f9a3.jpg)

**Comment by Luis-Fernando-Molina** [comment]
la forma puede andar, pero habria que ajustar algunas cosas.

El color rojo fijate si puede ser el naranja o amarillo de las wallets chiquitas.

Veamos como queda, please

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina ajustes tomando en cuenta la sugerencia de miguel + el color de las billeteras, le coloque naranja y amarillo.
![ficha_descriptiva_fermat_org_concepto_y_produccion-01](https://cloud.githubusercontent.com/assets/13594347/9825055/d3c00546-589a-11e5-9f7a-7103362adfe8.jpg)
![ficha_descriptiva_fermat_org_concepto_y_produccion-03](https://cloud.githubusercontent.com/assets/13594347/9825056/d3c0f320-589a-11e5-88e3-6609a20a2f17.jpg)

**Comment by Luis-Fernando-Molina** [comment]
1) el codigo no puede tener mas de 4 letras.
2) El nombre del plugin fijate como queda en blanco
3) Cuando yo decia en naranja decia reemplazar el rojo alrededor de la foto.

**Comment by arnaldos** [comment]
Ok ya realizo los cambios

**Comment by arnaldos** [comment]
Versión1

![fichas_plugins-01](https://cloud.githubusercontent.com/assets/13594347/9826922/9082a060-58a7-11e5-9a73-254dcae711fb.jpg)

Versión2
![fichas_plugins-02](https://cloud.githubusercontent.com/assets/13594347/9826923/90a343a6-58a7-11e5-8b3c-9ccf61f5f89d.jpg)

Versión3
![fichas_plugins-03](https://cloud.githubusercontent.com/assets/13594347/9826924/90aeb2c2-58a7-11e5-88f5-308074f0add1.jpg)

Versión4
![fichas_plugins-05](https://cloud.githubusercontent.com/assets/13594347/9826926/9171eb70-58a7-11e5-9058-0f06f7ddc42a.jpg)

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina  yo me inclino por la versión 2 !

**Comment by Luis-Fernando-Molina** [comment]
es muy dificil de ver las diferencias con las imagenes tan grandes :-(

Continuemos la version 3 con las wallets naranjas please (del naranja estandard)

**Comment by arnaldos** [comment]
ok perfecto

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina  

Corrección de la Versión 3

![ficha_descriptiva_fermat_org_produccion-02](https://cloud.githubusercontent.com/assets/13594347/9856732/2a0a4460-5ae0-11e5-8fdd-8c2ae6ac90d4.jpg)

Versión LANDSCAPE según las recomendaciones dadas en el issues #103

Siguiendo la propuesta de @m471c4 
![ficha_descriptiva_fermat_org_produccion-01](https://cloud.githubusercontent.com/assets/13594347/9856810/aa2fb972-5ae0-11e5-98f8-5d01486d877e.jpg)

Propuesta 3 

![ficha_descriptiva_fermat_org_produccion-03](https://cloud.githubusercontent.com/assets/13594347/9856813/b23c952c-5ae0-11e5-81d6-18997ce2d736.jpg)

**Comment by Luis-Fernando-Molina** [comment]
Ok vamos a Usar la propuesta 3 con el nombre de la capa en blanco

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina  así estaría bien ?

![ficha_descriptiva_fermat_org_produccion-04-03](https://cloud.githubusercontent.com/assets/13594347/9858720/0ba6fea8-5aec-11e5-8599-2d15ca08480b.jpg)

**Comment by Luis-Fernando-Molina** [comment]
Si, la podemos dejar asi. @m471c4 por favor agrega vos tambien el usuario a las fichas tuyas. 

El usuario debería estar sobre la foto, en el pecho, sino queda como un titulo del icono de la plataforma. Se puede orcurecer con un overlay semi transparente negro.

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina  que tal así el usuario ? 

![ficha_descriptiva_fermat_org_produccion-05-03](https://cloud.githubusercontent.com/assets/13594347/9860567/bb1a1802-5af6-11e5-9a73-7cdbe2ba24f3.jpg)

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina que tal así ?
![ficha_descriptiva_fermat_org_produccion-06-03-03](https://cloud.githubusercontent.com/assets/13594347/9891750/7f14624a-5bd2-11e5-8051-2b1db7a77b3a.jpg)

**Comment by Luis-Fernando-Molina** [comment]
no me entendiste. El overlay negro debiera ir solo detras del nombre y cubriendo la parte de abajo del circulo, no toda la foto. Es lo que se usa para oscurecer el fondo un poco para que se note el nombre que debe estar con letras blancas, pero con cierta trasparencia para que se siga viendo la foto abajo.

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina comparto los ajustes

![ficha_descriptiva_fermat_org_produccion-07-03-03](https://cloud.githubusercontent.com/assets/13594347/9894080/636ac6c6-5be9-11e5-853f-7f90712f0554.jpg)

**Comment by Luis-Fernando-Molina** [comment]
:+1:
