### ISSUE TITLE
Fiat currency Euro/Fermat Moneda 3d

### ISSUE THREAD

**Issue by jonathanborges3d** [bitDubai/fermat-graphic-design#107]
Concepto inicial:

![fiat_euro_1](https://cloud.githubusercontent.com/assets/13649739/9834398/7e2eb35c-5980-11e5-98a6-6170058c7827.png)

Para ésta moneda pienso que pudiese utilizar el mapa de Europa en relieve, de modo que no se identifique solamente con un país en particular si se coloca un símbolo o bandera.  No tengo claro aún qué podría ir de fondo detrás del logo de Fermat en el reverso. Me gustaría saber tu opinión @Luis-Fernando-Molina

**Comment by jonathanborges3d** [comment]
Primer boceto 3D:

![fiat_euro_2](https://cloud.githubusercontent.com/assets/13649739/9838306/14f532e0-5a24-11e5-91a8-c3a3afe08449.jpg)
![fiat_euro_3](https://cloud.githubusercontent.com/assets/13649739/9838307/1529cea6-5a24-11e5-96d9-827ca11e9fef.jpg)

**Comment by Luis-Fernando-Molina** [comment]
las estrellas coinciden con la cantidad de paises?
No se me ocurre nada por ahora, segui avanzando con esta o con otras.

**Comment by jonathanborges3d** [comment]
@Luis-Fernando-Molina No, el número de estrellas coincide con la bandera de la Unión Europea, en las monedas de 1 y  2 euros que he visto en internet hay 12 estrellas también, aunque en posición y proporción distinta.

Con respecto al fondo detrás del logo de Fermat, pensé que pudiesemos tener versiones diferentes con el mismo anverso pero con un icono arquitectónico de por lo menos 5 o 6 países de los que conforman la Unión, así como la moneda del dollar que estoy haciendo tiene el Golden Gate.

**Comment by Luis-Fernando-Molina** [comment]
> Con respecto al fondo detrás del logo de Fermat, pensé que pudiesemos tener versiones diferentes con el mismo anverso pero con un icono arquitectónico de por lo menos 5 o 6 países de los que conforman la Unión, así como la moneda del dollar que estoy haciendo tiene el Golden Gate.

ok, me parece bien-

**Comment by jonathanborges3d** [comment]
@Luis-Fernando-Molina Para el anverso hice tres versiones:

No sé si se notarán a simple vista las edificaciones

![fiat_euro_4](https://cloud.githubusercontent.com/assets/13649739/10208865/3b4896ba-67a0-11e5-8e4a-061b93bcb3cd.jpg)

![fiat_euro_5](https://cloud.githubusercontent.com/assets/13649739/10208918/a05b941c-67a0-11e5-99dc-be8d8d11df9a.jpg)

![fiat_euro_6](https://cloud.githubusercontent.com/assets/13649739/10208925/b5c68780-67a0-11e5-9833-408db5b076d9.jpg)

![fiat_euro_7](https://cloud.githubusercontent.com/assets/13649739/10208931/c82e0f10-67a0-11e5-8039-b549eda1f2fd.jpg)

![fiat_euro_8](https://cloud.githubusercontent.com/assets/13649739/10208948/df40b5fe-67a0-11e5-9fac-be6405045b3e.jpg)

![fiat_euro_9](https://cloud.githubusercontent.com/assets/13649739/10208964/f3124098-67a0-11e5-8c05-f28c0fd59212.jpg)

**Comment by Luis-Fernando-Molina** [comment]
Pone el logo de fermat un toque mas chico, la posicion esta bien. Y a los edificios ponele una base para que no estén en el aire. Al ultimo edificio no lo reconozco...

**Comment by jonathanborges3d** [comment]
@Luis-Fernando-Molina Ok, pensé que sería ése el primero que reconocerías, es el parlamento de Budapest, tal vez deba colocar otro edificio.

**Comment by Luis-Fernando-Molina** [comment]
No se reconoce por la silueta. Si vas a poner budapest, pone el CHAIN BRIDGE

**Comment by jonathanborges3d** [comment]
@Luis-Fernando-Molina Le coloqué el piso a los dos primeros e hice una primera versión con el Chain Bridge, pero no me convence porque la palabra Fermat lo tapa.

![fiat_euro_10](https://cloud.githubusercontent.com/assets/13649739/10211991/17b19ef4-67c3-11e5-9210-227f5af777cb.jpg)

![fiat_euro_11](https://cloud.githubusercontent.com/assets/13649739/10212003/37404892-67c3-11e5-8cb1-871fe553afb7.jpg)

![fiat_euro_12](https://cloud.githubusercontent.com/assets/13649739/10212019/6faaa27c-67c3-11e5-96a0-08d92f880566.jpg)

![fiat_euro_13](https://cloud.githubusercontent.com/assets/13649739/10212030/a08da57e-67c3-11e5-978f-aef14a9607f0.jpg)

**Comment by Luis-Fernando-Molina** [comment]
fijate hay otra imagen donde se ve menos del puente y mas uno de los pilares. Se debe ver el arco del pilar para poder reconocerlo.

**Comment by jonathanborges3d** [comment]
@Luis-Fernando-Molina Hice una versión con otra silueta del puente:

![fiat_euro_14](https://cloud.githubusercontent.com/assets/13649739/10238227/b68796e6-6886-11e5-9d3b-ef27e0d7a5ad.jpg)

![fiat_euro_15](https://cloud.githubusercontent.com/assets/13649739/10238239/d419677a-6886-11e5-84dc-5a5f0be93623.jpg)

**Comment by Luis-Fernando-Molina** [comment]
esta bien, fijate que la segunda columna no quede en el aire y estaria.

**Comment by jonathanborges3d** [comment]
@Luis-Fernando-Molina Con los cambios requeridos.

![fiat_euro_16](https://cloud.githubusercontent.com/assets/13649739/10258880/1b17f4ca-692c-11e5-9b73-c40a5af2801a.jpg)

![fiat_euro_17](https://cloud.githubusercontent.com/assets/13649739/10258895/3a9824f0-692c-11e5-8ec2-6350c3061762.jpg)

Debería hacer más variaciones de ésta moneda o ya pudiese quedar así?

**Comment by Luis-Fernando-Molina** [comment]
Puede quedarse asi.
