### ISSUE TITLE
Creación de un isologo para Fermat CSH

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#108]
Crear isologo para Fermat Cash Handling Platform

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina primer boceto para Fermat CSH

![fermat_chp](https://cloud.githubusercontent.com/assets/13594347/9891512/9448ec96-5bd0-11e5-804d-5e577f423031.png)

**Comment by Luis-Fernando-Molina** [comment]
Hola @arnaldos el logo esta bien, pero vamos a ponerle Fermat CHS (Cash Platform) gracias.

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina  perfecto !! ya genero los cambios y lo comparto de nuevo

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina listo !! que tal asi ?

![fermat_chp2](https://cloud.githubusercontent.com/assets/13594347/9892304/4a903cd8-5bd7-11e5-9ee7-24d93bb61e4e.png)

**Comment by Luis-Fernando-Molina** [comment]
Ok :+1:  pasaselo a @Miguelcldn

**Comment by arnaldos** [comment]
ok perfecto !!!!

**Comment by arnaldos** [comment]
@Miguelcldn ya subí el logo en svg al repo para que puedas actualizarlo en fermat.org

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina te comparto el ajuste del nombre, ya que miguel se dio cuenta de estaba errado, a continuación la versión con el nombre exacto. También lo estoy sustituyendo en el repo
![fermat_csh3](https://cloud.githubusercontent.com/assets/13594347/9894555/d34f84ae-5bee-11e5-8973-f708c424c58c.png)
