### ISSUE TITLE
Fiat currency Libra Esterlina/Fermat Moneda 3d

### ISSUE THREAD

**Issue by jonathanborges3d** [bitDubai/fermat-graphic-design#109]
@Luis-Fernando-Molina Primer boceto 3D:

![fiat_libra_1](https://cloud.githubusercontent.com/assets/13649739/9891783/ca042966-5bd2-11e5-939d-ca3729afbe30.jpg)

![fiat_libra_2](https://cloud.githubusercontent.com/assets/13649739/9891865/71a19f00-5bd3-11e5-8ce0-0d5fd3e1b2b5.jpg)

**Comment by Luis-Fernando-Molina** [comment]
va  bien, pero el edificio en perspectiva me parece que no queda muy bien, fijate de poner una vista de frente.
Luego en la parte interna del poligono pudiera ponerle un dentado o algo que la decore.

**Comment by jonathanborges3d** [comment]
Ok, te parece si utilizo una silueta que tenga mayor detalle? algo cómo ésto:

![](http://www.cliparthut.com/clip-arts/1795/big-ben-wall-clock-1795153.jpg)

@Luis-Fernando-Molina

**Comment by Luis-Fernando-Molina** [comment]
si, pudiera andar

**Comment by jonathanborges3d** [comment]
@Luis-Fernando-Molina Nueva versión con el edificio en toma frontal. También agregué el dentado en  la parte interna del borde dodecagonal.

![fiat_libra_3](https://cloud.githubusercontent.com/assets/13649739/9939487/3ed0a820-5d34-11e5-9bf9-e391cc0d0afb.jpg)

![fiat_libra_4](https://cloud.githubusercontent.com/assets/13649739/9939543/a88a5126-5d34-11e5-8c20-424a84e645b1.jpg)

**Comment by jonathanborges3d** [comment]
@Luis-Fernando-Molina Me gustaría que me dieras tu opinión acerca de ésta última versión por favor.

**Comment by Luis-Fernando-Molina** [comment]
Va bien, proba ponerle alguna textura repetitiva a la parte plateada.

**Comment by Luis-Fernando-Molina** [comment]
Y quizas algun otro dentado donde la parte dorada hace contacto con la plateada.

**Comment by jonathanborges3d** [comment]
@Luis-Fernando-Molina En ésta versión reduje un poco el grosor del anillo exterior, coloqué uno interno alrededor del núcleo plateado y le apliqué un mapa de relieve.

![fiat_libra_5](https://cloud.githubusercontent.com/assets/13649739/10092921/aed05062-6315-11e5-9198-39a7e6bf7a18.jpg)

![fiat_libra_6](https://cloud.githubusercontent.com/assets/13649739/10092949/1aeb5c92-6316-11e5-8423-80420ac28e7d.jpg)

**Comment by Luis-Fernando-Molina** [comment]
va quedando muy bien. EL fondo, que representa?

**Comment by jonathanborges3d** [comment]
Es la bandera del Reino Unido, pero está parcial, tal vez quedaría mejor si se pone completa y centrada.Algo así:

![fiat_libra_7](https://cloud.githubusercontent.com/assets/13649739/10118120/7b850156-6439-11e5-8397-89221850c138.jpg)

**Comment by Luis-Fernando-Molina** [comment]
quizas mas reducida todavia...., fijate que las lineas coordinen bien con "one pound"

**Comment by jonathanborges3d** [comment]
@Luis-Fernando-Molina Una prueba con otro material en el fonfo:

![fiat_libra_9](https://cloud.githubusercontent.com/assets/13649739/10238580/65399140-688b-11e5-8457-280da78aa92c.jpg)

**Comment by Luis-Fernando-Molina** [comment]
Esta muy fuerte, quizas sirva pero menos bumpy

**Comment by jonathanborges3d** [comment]
@Luis-Fernando-Molina Reduje un poco el efecto del bumpmap:

![fiat_libra_10](https://cloud.githubusercontent.com/assets/13649739/10263505/cde10e8c-69ba-11e5-8e29-d3d4604f722e.jpg)

**Comment by Luis-Fernando-Molina** [comment]
:+1:

**Comment by jonathanborges3d** [comment]
@Luis-Fernando-Molina El reverso:

![fiat_libra_11](https://cloud.githubusercontent.com/assets/13649739/10300104/6aaeb536-6bbc-11e5-8339-7e11eefe5639.jpg)

![fiat_libra_12](https://cloud.githubusercontent.com/assets/13649739/10300122/c0967f88-6bbc-11e5-9432-db47bbc56f23.jpg)

**Comment by Luis-Fernando-Molina** [comment]
y que pasó con el edificio en este caso?

**Comment by jonathanborges3d** [comment]
@Luis-Fernando-Molina Cierto, pero como en el anverso tiene el Big Ben no pensé que fuese necesario. Qué opinas de colocar el London Bridge? o tienes alguna sugerencia?

**Comment by Luis-Fernando-Molina** [comment]
el tower bridge es mas conocido. googlealo.

**Comment by jonathanborges3d** [comment]
@Luis-Fernando-Molina Con los cambios:
![fiat_libra_13](https://cloud.githubusercontent.com/assets/13649739/10356872/5eab5dfe-6d45-11e5-8330-4fa23e62c6f0.jpg)

![fiat_libra_14](https://cloud.githubusercontent.com/assets/13649739/10356886/815bc41a-6d45-11e5-924f-eca58b690b0f.jpg)

**Comment by Luis-Fernando-Molina** [comment]
:+1:

**Comment by Luis-Fernando-Molina** [comment]
Cuando termines con el primer juego de monedas FIAT , create unos casos para escenas donde las combinen please
