### ISSUE TITLE
Crear un ícono para representar los Libraries

### ISSUE THREAD

**Issue by m471c4** [bitDubai/fermat-graphic-design#110]
Crear logo para representar las Libraries. Servirá para indicar los componentes que tiene el cada modulo en las fichas para Fermat.org.

**Comment by m471c4** [comment]
@Luis-Fernando-Molina @arnaldos acá el primero boceto para el ícono de Libraries:

![iconlibrary](https://cloud.githubusercontent.com/assets/13468350/9908860/64f54fa4-5c5f-11e5-8ce9-269292fc7d09.png)

En este imagen se pueden ver todos los íconos en conjunto:

![iconsfermat](https://cloud.githubusercontent.com/assets/13468350/9908878/77b653f4-5c5f-11e5-8537-0cedeff440b2.png)

**Comment by Luis-Fernando-Molina** [comment]
el de la library replantealo por favor, los engranajes ya estan tal cual en otro icono. Pudiera ser un estante con libros o algo asi

**Comment by m471c4** [comment]
@Luis-Fernando-Molina si, el engranaje verde ya se está usando, quise usar los mismos elementos para mantener la línea gráfica, pero haré otra cosa y lo subo acá a ver qué te parece. Probaré con los libros.

**Comment by m471c4** [comment]
@Luis-Fernando-Molina acá hay 3 propuestas, ¿te gusta alguna?

Versión 1:
![iconlib1](https://cloud.githubusercontent.com/assets/13468350/9915717/71b1dd7a-5c82-11e5-95e0-f9560a378760.png)

Versión 2:
![iconlib2](https://cloud.githubusercontent.com/assets/13468350/9915718/71d2daa2-5c82-11e5-94ec-20df59dd9ab1.png)

Versión 3:
![iconlib3](https://cloud.githubusercontent.com/assets/13468350/9915719/71d4d708-5c82-11e5-8236-f271a0536005.png)

**Comment by Luis-Fernando-Molina** [comment]
la version 3 :+1:

**Comment by m471c4** [comment]
Buenísimo, los subiré al repositorio.
