### ISSUE TITLE
Crear una imagen de fondo de pantalla en 3D para las app.

### ISSUE THREAD

**Issue by jonathanborges3d** [bitDubai/fermat-graphic-design#111]
@m471c4 Diseñó éste fondo de pantalla

![wallpaper](https://cloud.githubusercontent.com/assets/13649739/9924226/38ce2c62-5cc7-11e5-99a8-9f7985f00ce9.jpg)

Primer boceto en 3D:

![wallpaper_1](https://cloud.githubusercontent.com/assets/13649739/9924234/47e25d04-5cc7-11e5-8c47-fc305faf71f9.jpg)

El concepto es una serie de capas en un material de vidrio con una leve absorción de la luz en color verde.

No me convence el uso de renderizado fotorealista para éstas imágenes, el "grano" de la imagen se nota mucho con respecto a la imagen plana. Qué te parece @Luis-Fernando-Molina ?

**Comment by Luis-Fernando-Molina** [comment]
pienso que va bien, fijate de que se vea sin el grano, proponé algo mas.

**Comment by jonathanborges3d** [comment]
@Luis-Fernando-Molina Primera propuesta basada en la muestra que me enviaste. Hice el render con mental ray de Softimage,es mucho más limpio el resultado.

![wallpaper_2](https://cloud.githubusercontent.com/assets/13649739/9943725/fc42bd40-5d4c-11e5-80d0-b48abff0ccf2.jpg)

Estoy usando la paleta de colores de Fermat para las luces.

**Comment by Luis-Fernando-Molina** [comment]
Está lindo, probá variar las lucen usando de a dos colores en vez de a tres por favor

**Comment by jonathanborges3d** [comment]
@Luis-Fernando-Molina Ok, aquí están algunas variantes en la iluminación, sólo uso dos colores en diferente posición.

![wallpaper_3](https://cloud.githubusercontent.com/assets/13649739/9944949/41ccb760-5d54-11e5-8dce-e1380e43bd1f.jpg)

![wallpaper_4](https://cloud.githubusercontent.com/assets/13649739/9944974/5dd67694-5d54-11e5-9c91-693d287f7be4.jpg)

![wallpaper_5](https://cloud.githubusercontent.com/assets/13649739/9944986/7aac471c-5d54-11e5-8c50-5adf5205c6e0.jpg)

![wallpaper_6](https://cloud.githubusercontent.com/assets/13649739/9944999/91b0cf28-5d54-11e5-8295-d344ed3c3636.jpg)

![wallpaper_7](https://cloud.githubusercontent.com/assets/13649739/9945017/ac46b67c-5d54-11e5-8812-c09d3589ecd4.jpg)

![wallpaper_8](https://cloud.githubusercontent.com/assets/13649739/9945032/c2e3cd84-5d54-11e5-925c-d96b8d989085.jpg)

![wallpaper_9](https://cloud.githubusercontent.com/assets/13649739/9945058/dc9d3080-5d54-11e5-89c7-fb72fd3dd05c.jpg)

![wallpaper_10](https://cloud.githubusercontent.com/assets/13649739/9945077/f9f4fa3c-5d54-11e5-9dac-7489576d04ed.jpg)

**Comment by Luis-Fernando-Molina** [comment]
Varias pudieran andar, fijate si podes hacer los plieges un poco mas sutil, o que no ocupen toda la pantalla.

Ponele numero para poder nombrarlas please. (y quizas un poco mas chica para poder verlas enteras) gracias.

**Comment by jonathanborges3d** [comment]
Segundo boceto en 3D del fondo hecho por @m471c4 

![wallpaper_1_b](https://cloud.githubusercontent.com/assets/13649739/9947082/383e7352-5d61-11e5-9d0d-1142cd5b7b80.jpg).

**Comment by jonathanborges3d** [comment]
@Luis-Fernando-Molina Lo de los pliegues podría ser algo así?

![wallpaper_11](https://cloud.githubusercontent.com/assets/13649739/9947399/a7edd2cc-5d63-11e5-9849-c1146dc1e80f.jpg)

Encontré la imágen completa de la referencia que me enviaste, tal vez se deban hacer del mismo ancho, así los pliegues ocuparían menos espacio.

![](http://androidayuda.com/app/uploads/2015/03/Galaxy-S6-Wallpaper-B.jpg)

**Comment by jonathanborges3d** [comment]
@Luis-Fernando-Molina Segunda propuesta. Esta vez hice los pliegues un poco más sutiles con respecto a la primera y aumenté el ancho de la imagen.

![wallpaper_2_1](https://cloud.githubusercontent.com/assets/13649739/9981660/bc10b334-5f8c-11e5-93eb-b03a237c9c5c.jpg)

**Comment by Luis-Fernando-Molina** [comment]
@jonathanborges3d tomar las dimensiones de la imagen me parece bien, puede ayudar a que sirva en diferentes dispositivos. 

No se si me gusta mucho la idea de hacer algo tan parecido a esa, con plieges y todo. Por ahí pudieramos inventar algo nuevo, con alguna referencia a las wallets cosas de que no quepa duda que es nuestro diseño.

**Comment by jonathanborges3d** [comment]
@Luis-Fernando-Molina Ok, entiendo el punto. Hice ésta escena pensando en la producción de wallets, Qué opinas?

![wallpaper_3_1](https://cloud.githubusercontent.com/assets/13649739/10025136/86785b16-6124-11e5-9a32-44d064da40b5.jpg)

![wallpaper_3_2](https://cloud.githubusercontent.com/assets/13649739/10025428/fd3344d6-6125-11e5-8ec4-db256c0cf5fd.jpg)

**Comment by Luis-Fernando-Molina** [comment]
esta buena la idea. Habria que ver como se ve con iconos encia. Quizas una version mas simple con solo un gusano pudiera andar.

**Comment by jonathanborges3d** [comment]
@Luis-Fernando-Molina Aquí está la versión con un solo gusano.

Versión 1:
![wallpaper_3_3](https://cloud.githubusercontent.com/assets/13649739/10029560/5d35b808-613c-11e5-907a-17a5961c5de3.jpg)

Versión 2:
![wallpaper_3_4](https://cloud.githubusercontent.com/assets/13649739/10029712/471bd222-613d-11e5-9546-2f491aa45811.jpg)

Otra propuesta:

![wallpaper_4_1](https://cloud.githubusercontent.com/assets/13649739/10029586/88482de6-613c-11e5-81d0-5482f761ddd7.jpg)

**Comment by Luis-Fernando-Molina** [comment]
Ok sigamos con la version 2. Ponela en el tamaño dela imagen que habias encontrado y fijate como queda si tuviera inconos encima por favor.

**Comment by jonathanborges3d** [comment]
@Luis-Fernando-Molina Hice los ajustes en el tamaño de la imágen, pero noté que la wallet no quedaba centrada:

![wallpaper_3_5](https://cloud.githubusercontent.com/assets/13649739/10045482/e1f2512e-61cc-11e5-85c4-890a56aadee4.jpg)

Así que hice una tercera versión con un ángulo distitnto:

![wallpaper_3_6](https://cloud.githubusercontent.com/assets/13649739/10045541/4e906d7a-61cd-11e5-9dcb-702fa5c46c0c.jpg)

Aquí está con íconos encima en tres pantallas:

![wallpaper_3_6_1](https://cloud.githubusercontent.com/assets/13649739/10045456/a672fc8e-61cc-11e5-910a-e41ce928a51d.jpg)

![wallpaper_3_6_2](https://cloud.githubusercontent.com/assets/13649739/10045572/87c32f10-61cd-11e5-8065-950ec4057dfa.jpg)

![wallpaper_3_6_3](https://cloud.githubusercontent.com/assets/13649739/10045586/9b56971a-61cd-11e5-843d-76ec4daa8f05.jpg)

**Comment by Luis-Fernando-Molina** [comment]
Decile a @furszy que la prueba a ver como queda en alguno de lo desktops.

**Comment by furszy** [comment]
@jonathanborges3d hablame por slack o skype así las pruebo y charlamos, ya comienza a ser un requisito que se encuentren las imágenes con un peso y tamaño acorde a una aplicación móvil.

**Comment by jonathanborges3d** [comment]
@furszy Ok ya las convierto y te las paso.

**Comment by furszy** [comment]
@jonathanborges3d @Luis-Fernando-Molina  así queda.
![seleccion_035](https://cloud.githubusercontent.com/assets/5377650/10052968/db017a2e-61ff-11e5-9c1b-ff3b237ab065.png)
![seleccion_034](https://cloud.githubusercontent.com/assets/5377650/10053001/fd8b8b3e-61ff-11e5-8a4e-0617e3ba600e.png)

**Comment by jonathanborges3d** [comment]
@furszy Me parece que la imagen en formato cuadrado no funcionará adecuadamente, se comprime el ancho. También noto que está algo pixelada en algunas zonas, probablemente debamos usar una resolución más alta que 640. Qué opinas @Luis-Fernando-Molina?

(Disculpen, presioné el botón equivocado y cerré el issue, ya está arreglado)

**Comment by Luis-Fernando-Molina** [comment]
pienso que la imagen no se lleva bien con los iconos. Quizas aplicandole un blur violento se pueda usar

**Comment by jonathanborges3d** [comment]
@Luis-Fernando-Molina Podría ser algo así o más difuso?
Ajusté el ancho de la imagen para que no se deforme.

![wallpaper_3_6_5](https://cloud.githubusercontent.com/assets/13649739/10088738/cd7e6438-62e6-11e5-9177-afcd8cfe24f8.jpg)

**Comment by Luis-Fernando-Molina** [comment]
hbria que ver con algunos iconos arriba... mas difuso creo que no se notaria que es.

**Comment by furszy** [comment]
#### El difuso de las imágenes lo hice yo en código, si quieren pueden con un numero agregarle mayor o menor nivel desde su aplicación y ver como va quedando.

![seleccion_041](https://cloud.githubusercontent.com/assets/5377650/10200554/87897404-677d-11e5-9427-fe8064143dd8.png)
![seleccion_040](https://cloud.githubusercontent.com/assets/5377650/10200555/878a406e-677d-11e5-96f6-fc18f600b66b.png)

**Comment by jonathanborges3d** [comment]
@Luis-Fernando-Molina Me parece que debería ir un poco más difuso, algo  como la imágen que publiqué de último. Cual es tu opinión?

**Comment by Luis-Fernando-Molina** [comment]
No me termina de convencer , vancemos por otro lado, con las monedas e imagenes artisticas que las mezcle. Me gustaria ver un buen avance por ese lado.

**Comment by jonathanborges3d** [comment]
@Luis-Fernando-Molina Supongo que si la app de fermat ya no va a utilizar fondos para el desktop entonces no será necesario seguir éste tema, lo cerramos?

**Comment by Luis-Fernando-Molina** [comment]
si, cerralo.
