### ISSUE TITLE
Cambiar las fichas descriptivas para fermat.org a un formato de 16:9

### ISSUE THREAD

**Issue by m471c4** [bitDubai/fermat-graphic-design#112]
Es necesario cambiar la resolución de las fichas descriptivas a un formato de 16:9 (esto serían 214x120px). 

@arnaldos, acá podemos subir los ajustes necesarios para cada caso.

**Comment by arnaldos** [comment]
@m471c4 perfecto !!

**Comment by m471c4** [comment]
@Luis-Fernando-Molina, @arnaldos acá subo las fichas con los cambios finales (formato, cambio del color de las carteras) para desarrollo y qa, respectivamente.

![fichawide_desarrollo](https://cloud.githubusercontent.com/assets/13468350/10026891/f51e620a-612d-11e5-823c-e4784bc729ac.png)

![fichawide_qa](https://cloud.githubusercontent.com/assets/13468350/10026853/c1762640-612d-11e5-99e0-523f99ef6626.png)

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina, @m471c4 les comparto las fichas en el nuevo formato 

![ficha_descriptiva_fermat_org_produccion-03](https://cloud.githubusercontent.com/assets/13594347/10027016/92cb9d4c-612e-11e5-83cc-a753ea3296b9.jpg)

![ficha_descriptiva_fermat_org_concepto-02](https://cloud.githubusercontent.com/assets/13594347/10027037/9c9e78e4-612e-11e5-88f6-c1a98b9cbbc9.jpg)

**Comment by m471c4** [comment]
@arnaldos ¿puedes darme el puntaje que estás usando para los textos de tus fichas? Estandaricemos eso para que a Miguel no se le complique. También recuerda que hay que cambiar los colores de lar carteras.

**Comment by Luis-Fernando-Molina** [comment]
@m471c4 a las tuyas les falta del nombre del usuario.

El resto parece ir bien :+1:

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina @m471c4 comparto los ajustes de las carteras 

![ficha_descriptiva_fermat_org_concepto-02](https://cloud.githubusercontent.com/assets/13594347/10032948/3f741850-6150-11e5-9edc-2f5366e53f8f.jpg)
![ficha_descriptiva_fermat_org_produccion-2-03](https://cloud.githubusercontent.com/assets/13594347/10032949/3f78fe4c-6150-11e5-904d-1582dfd87fb2.jpg)

**Comment by Luis-Fernando-Molina** [comment]
@arnaldos sería al reves, primero las amarillas, ante ultima la verde y ultima la roja, de iz a derecha.

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina comparto estas versiones de las fichas re-diagramadas para el formato 16:9  que nos permite aprovechar un poco mas el espacio.

Concepto Versión 1

![ficha_descriptiva_fermat_org_concepto-01](https://cloud.githubusercontent.com/assets/13594347/10033017/8efdfed6-6150-11e5-81d6-25ccf2f6b515.jpg)

Concepto Versión 2

![ficha_descriptiva_fermat_org_concepto-03](https://cloud.githubusercontent.com/assets/13594347/10033018/8f008e30-6150-11e5-9269-ea13e71234b3.jpg)

Concepto Versión 3

![ficha_descriptiva_fermat_org_concepto-04](https://cloud.githubusercontent.com/assets/13594347/10033019/8f040164-6150-11e5-929f-ee7186a079b6.jpg)

Producción Versión 1

![ficha_descriptiva_fermat_org_produccion-01](https://cloud.githubusercontent.com/assets/13594347/10033056/cb6f3696-6150-11e5-9627-111ec23bfd05.jpg)

Producción Versión 2

![ficha_descriptiva_fermat_org_produccion-02](https://cloud.githubusercontent.com/assets/13594347/10033057/cb7baea8-6150-11e5-8e5a-9322509646ef.jpg)

**Comment by Luis-Fernando-Molina** [comment]
@arnaldos agradezco tu proactividad, pero lo que realmente necesito es que @Miguelcldn tenga las fichas lo antes posible y todos los elementos asociados (billeteras, iconos individuales de cada plataforma, etc) asi puede terminar con esto y seguir con otra cosa que nos urge. 

Ya que hiciste otras diagramaciones voy a volver a elegir, pero la idea aquí era solo ensanchar lo que habia.

Concepto Version 1 :+1: 
Producción Version 1 :+1:

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina hablando de las fichas con @m471c4  se nos crea una inquietud y es referente al texto que esta sobre la foto del usuario, hasta el momento todo pinta verse muy bien pero que pasa si hay un nombre que sobre pase limite del espacio establecido, este se saldría de los bordes lo que nos impide la lectura ya que el texto quedaría sobre los elementos. Sabemos que esto esta definido de esta manera, pero nos puede traer problema de lectura para aquellos nombres que posean muchos caracteres. 

Por esta razón proponemos re-ubicar el texto que identifica al usuario y sacarlo del circulo donde se encuentra la foto. 

No se que opinas al respecto ?

**Comment by arnaldos** [comment]
perfecto luis ya le estoy pasando todo a @Miguelcldn

**Comment by Luis-Fernando-Molina** [comment]
En realidad el nombre iria con una letra mas chica para que eso no suceda. @Miguelcldn ya está al tanto. No problem.

**Comment by arnaldos** [comment]
ok perfecto !!!
