### ISSUE TITLE
Ajustes del icono del usuario para las fichas de Fermat.org

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#113]
@Luis-Fernando-Molina De acuerdo a lo conversado con @m471c4, buscamos estandarizar el icono de usuario para las fichas de fermat, según las recomendaciones de google.

A continuación mostraremos 2 opciones que se trabajaron ya que la síntesis que estuvimos trabajando esta asociada a una imagen masculina. 

Por lo que decidimos colocar algo mas sintetizado para mostrar en el icono de usuario.

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina @m471c4  

Icono con el que se esta trabajando.

![user_ar](https://cloud.githubusercontent.com/assets/13594347/10029555/5a5d4312-613c-11e5-9bfa-7e6950114c6a.jpg)

Icono recomendado por @m471c4 siguiendo a las sugerencias de google (material desing) sobre trabajar sobre imágenes mas sintetizadas

![user_dm](https://cloud.githubusercontent.com/assets/13594347/10029580/810bc2e0-613c-11e5-8a13-8ba3f7355595.jpg)

Icono recomendado por @arnaldos buscando no variar la imagen original, buscando sintetizar  dicho icono siguiendo las recomendaciones y mostrar algo mas simple y no figurativo.

![user_ar_2](https://cloud.githubusercontent.com/assets/13594347/10029693/2af1af72-613d-11e5-9baa-0e5fe08994a3.jpg)

**Comment by Luis-Fernando-Molina** [comment]
Yo prefiero el primero. :+1:

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina cuando te refieres al primero te refieres con el que se esta trabajando actualmente cierto ?

**Comment by Luis-Fernando-Molina** [comment]
correcto

**Comment by arnaldos** [comment]
ok entonces nos mantendremos con ese !!
