### ISSUE TITLE
SUPERISSUE: Diseñar la identidad de la Bitcoin Loss Protected Wallet (BLP)

### ISSUE THREAD

**Issue by m471c4** [bitDubai/fermat-graphic-design#114]
1- Crear icono para la Bitcoin Loss Protected Wallet.
2- Crear banner de presentación para la Bitcoin Loss Protected Wallet.

**Comment by m471c4** [comment]
@Luis-Fernando-Molina primer boceto para la identidad de esta wallet (logotipo que iría en el banner)

![blpwalletlogo](https://cloud.githubusercontent.com/assets/13468350/10067994/aed1d6b8-626a-11e5-972d-f20a72180d40.png)

**Comment by Luis-Fernando-Molina** [comment]
Probemos otras alternativas por favor.

**Comment by m471c4** [comment]
@Luis-Fernando-Molina 

![blpwalletlogo2](https://cloud.githubusercontent.com/assets/13468350/10095117/41a32d2c-6331-11e5-97f3-c4bc2d78c99a.png)

**Comment by m471c4** [comment]
Ya se han subido los editables y las versiones correspondientes en png y svg al repositorio. Cerrado el caso.
