### ISSUE TITLE
Crear icono para la Bitcoin Loss Protected Wallet

### ISSUE THREAD

**Issue by m471c4** [bitDubai/fermat-graphic-design#115]
Viene del #114

**Comment by m471c4** [comment]
@Luis-Fernando-Molina acá los primeros bocetos de íconos para esta wallet.

![blpwallet](https://cloud.githubusercontent.com/assets/13468350/10067037/75fa5868-6262-11e5-9a7d-0e7cef9e6884.png)

Versión 1:
![blpwallet1](https://cloud.githubusercontent.com/assets/13468350/10067663/29d9050a-6268-11e5-8bcb-bcda782ba4e2.png)

Versión 1 con otra paleta de color:
![blpwallet2](https://cloud.githubusercontent.com/assets/13468350/10067667/3106a08a-6268-11e5-8cb3-cba0489fb2bb.png)

Versión 2:
![blpwallet3](https://cloud.githubusercontent.com/assets/13468350/10067672/36676f3c-6268-11e5-9a7f-be5124065654.png)

Versión 2 con otra paleta de color:
![blpwallet4](https://cloud.githubusercontent.com/assets/13468350/10067678/3aa05050-6268-11e5-84df-dadd86370842.png)

**Comment by Luis-Fernando-Molina** [comment]
@m471c4 te explico un poco de que se trata esta wallet, asi te aproximás mejor al concepto con tus diseños.

El bitcoin es muy volatil, sube y baja de precio diariamente. Con lo cual si tenes bitcoins en una wallet normal, cuando lo gastas nunca vas a estar seguro si no estás vendiendolo a un precio inferior al que lo compraste. 

Esta wallet, te proteje ante eso, impidiendote gastar bitcoins si no lo compraste a un precio inferior a lo que vale en el momento en que lo querés gastar.

Espero que esto te ayude.

**Comment by m471c4** [comment]
@Luis-Fernando-Molina perfecto. Sería bueno hacer pequeños briefs como estos para las otras wallets también, ya que hay nombres que no dejan muy claros sus propósitos.

Haré algunas propuestas guiándome por lo que me explicas y lo subo acá.

**Comment by Luis-Fernando-Molina** [comment]
@m471c4 Cuando esten Arnaldo y tu soliciten una reunion de diseño gráfico y pregunten sobre cada elemento uno a uno así despejan sus dudas.

**Comment by m471c4** [comment]
Perfecto. Le diré a @arnaldos y te avisamos para reunirnos.

**Comment by m471c4** [comment]
@Luis-Fernando-Molina acá dos versiones más, explorando el concepto de protección y seguridad.

Versión 1:
![blpwallet5](https://cloud.githubusercontent.com/assets/13468350/10095235/f166d056-6331-11e5-8827-dc2fafd20893.png)

Versión 2:
![blpwallet6](https://cloud.githubusercontent.com/assets/13468350/10095269/4ba5c4a0-6332-11e5-99c8-76556f2ea2ee.png)

**Comment by Luis-Fernando-Molina** [comment]
Prefiero la version del escudo. Sin embargo me gustaria ver mas opciones. Los colores verdes ya lo usamos en la wallet anterior (bitcoin wallet). Proba con una wallet con forma de escudo o algo asi, sin la parte cuadrada.

**Comment by m471c4** [comment]
@Luis-Fernando-Molina muy bien, subiré más versiones el el transcurso del día. Probaré con otra paleta de colores.

**Comment by m471c4** [comment]
@Luis-Fernando-Molina solo con el escudo, en un círculo y como wallet:

![blpwalleticon1](https://cloud.githubusercontent.com/assets/13468350/10205362/9a41e3da-678a-11e5-8fba-5c76aa4e30ca.png)
![blpwalleticon2](https://cloud.githubusercontent.com/assets/13468350/10205363/9a6a063a-678a-11e5-86a0-2d51c6469e25.png)
![blpwalleticon3](https://cloud.githubusercontent.com/assets/13468350/10206480/e23c3374-6790-11e5-90d8-6b79beb18e57.png)

**Comment by Luis-Fernando-Molina** [comment]
El ultimo ponele LP y propone nuevas combinciones de colores please.

**Comment by m471c4** [comment]
@Luis-Fernando-Molina acá algunas propuestas de color:

![blpwalletcolor](https://cloud.githubusercontent.com/assets/13468350/10230218/ca6dc9be-6845-11e5-9aa7-284e4b7dabfb.png)

**Comment by m471c4** [comment]
@Luis-Fernando-Molina dos versiones más:

![blpwalletcolor2](https://cloud.githubusercontent.com/assets/13468350/10231227/6fb469a0-684b-11e5-86a6-487a60120df2.png)

**Comment by Luis-Fernando-Molina** [comment]
de las ultimas dos, la primera :+1:

**Comment by m471c4** [comment]
@Luis-Fernando-Molina perfecto, armaré el banner en función de la misma.
