### ISSUE TITLE
Crear banner de presentación para la Bitcoin Loss Protected Wallet

### ISSUE THREAD

**Issue by m471c4** [bitDubai/fermat-graphic-design#116]
Viene del #114

**Comment by m471c4** [comment]
@Luis-Fernando-Molina primer boceto para el banner (no necesariamente con ese logotipo), solo la composición:

![blpwalletbanner](https://cloud.githubusercontent.com/assets/13468350/10095092/fb4d7e18-6330-11e5-8b6d-bf2c7c47c1fa.png)

**Comment by Luis-Fernando-Molina** [comment]
El banner fuera del texto no dice nada sobre el tipo de wallet. Me gustaria que lo haga de alguna manera. Mira la Play Store los banners de aplicaciones reconocidas y extrae de ahi lo que se hace para estos casos.

**Comment by m471c4** [comment]
@Luis-Fernando-Molina muy bien.

**Comment by m471c4** [comment]
@Luis-Fernando-Molina 

![blpwalletbanner](https://cloud.githubusercontent.com/assets/13468350/10206489/e9a650a4-6790-11e5-9294-cc86d479829d.png)

**Comment by Luis-Fernando-Molina** [comment]
@m471c4 @arnaldos estoy viendo algo que pasa con ambos: no tiene mucho sentido hacer el banner en paralelo al icono, porque una cosa depende de la otra. Hasta que no este definido el icono , no esta definida la paleta de colores ni el estilo, ni nada, con lo cual lo mas eficiente seria llevar el icono a la version final y de ahi derivar el banner cuando todas esas cosas ya se sepan.

**Comment by m471c4** [comment]
@Luis-Fernando-Molina acá algunas versiones para el banner:

Versión 1:
![blpwalletbanner1](https://cloud.githubusercontent.com/assets/13468350/10237923/5c11ec6a-6882-11e5-93e5-b8accc93e5c3.png)

Versión 2:
![blpwalletbanner2](https://cloud.githubusercontent.com/assets/13468350/10237924/5c2df400-6882-11e5-86c2-5804075a09c9.png)

Versión 3:
![blpwalletbanner3](https://cloud.githubusercontent.com/assets/13468350/10237938/8ba1dcba-6882-11e5-9cf0-19724b6d8a5b.png)

**Comment by Luis-Fernando-Molina** [comment]
Podemos seguir a partir del 1. Pregunta: el icono aprobado no es lo que se ve en el logo del banner, o me equivoco?

**Comment by m471c4** [comment]
@Luis-Fernando-Molina Muy bien. Para eso utilicé solo la parte del centro, con la unión de la L y la P y los colores naranja para lograr una asociación. ¿Quisieras que lo quite? ¿O que lo pongo completo?

**Comment by Luis-Fernando-Molina** [comment]
Proba poniendo todo

**Comment by m471c4** [comment]
@Luis-Fernando-Molina acá con el ícono completo, le puse ese borde blanco para que no se ierda entre todo ese azul, creo que funciona:

![blpwalletbannerfinal](https://cloud.githubusercontent.com/assets/13468350/10251808/469ffb8a-68fd-11e5-8939-18ee7ae48e5d.png)

Otra cosa, ¿quisieras que agregara la palabra "wallet" al final del texto? Tengo esa duda pues en fermat.org solo aparece como BLP, pero el usuario final no sabrá que es una wallet.

**Comment by Luis-Fernando-Molina** [comment]
si , agrega wallet. En fermat org no aparece porque esta en la capa "wallet" por lo tanto es una wallet.

El banner puede quedar asi :+1:

**Comment by m471c4** [comment]
@Luis-Fernando-Molina excelente, con la palabra wallet:

![blpwalletbannerfinal](https://cloud.githubusercontent.com/assets/13468350/10253987/a54704be-690a-11e5-9016-5140a7f77ade.png)
