### ISSUE TITLE
Crear icono para la Discount Wallet 

### ISSUE THREAD

**Issue by m471c4** [bitDubai/fermat-graphic-design#118]
Viene del #117

**Comment by m471c4** [comment]
@Luis-Fernando-Molina acá primeros bocetos para el icono de la Discount Wallet:

Versión 1:
![dwallet3](https://cloud.githubusercontent.com/assets/13468350/10498189/22977c2c-7294-11e5-9937-56def33f2fa6.png)

Versión 2:
![dwallet4](https://cloud.githubusercontent.com/assets/13468350/10498190/22aa7bb0-7294-11e5-91fb-367940b610c1.png)

Versión 3:
![dwallet5](https://cloud.githubusercontent.com/assets/13468350/10498191/23147e34-7294-11e5-9e6f-5cd908e53928.png)

Versión 4:
![dwallet6](https://cloud.githubusercontent.com/assets/13468350/10498192/23369898-7294-11e5-9449-9b9b5e317a66.png)

**Comment by Luis-Fernando-Molina** [comment]
@m471c4 necesitamos que a partir del icono se pueda identificar que es una discount wallet. Veamos otras opciones que pudieran cumplir con esas características por favor.

**Comment by m471c4** [comment]
@Luis-Fernando-Molina acá otras opciones partiendo del logo:

![dwalletlogo](https://cloud.githubusercontent.com/assets/13468350/10550350/4cb08530-7410-11e5-92fd-ed70f2c623dd.png)

Versión 1:
![dwallet9](https://cloud.githubusercontent.com/assets/13468350/10550354/52c22e38-7410-11e5-822e-0acf86f43c4e.png)

Versión 2:
![dwallet7](https://cloud.githubusercontent.com/assets/13468350/10550361/59bbc8ac-7410-11e5-9739-0c0d468da606.png)

Versión 3:
![dwallet8](https://cloud.githubusercontent.com/assets/13468350/10550366/6163fa48-7410-11e5-8d2c-fa3be11af3ea.png)

**Comment by Luis-Fernando-Molina** [comment]
el concepto del tag me parece bien
el concepto del % me parece bien
quitale la w o cualquier otra cosa
proba transformar el tag en una wallet, poniendole las costuras
la combinacion de colores no me gusta

**Comment by m471c4** [comment]
@Luis-Fernando-Molina muy bien, aplicaré las mejoras y lo subo. Algo que me preocupa de quitar la w es que se vuelva muy genérico (como cualquier tag de descuento). Haré varias propuestas de color.

**Comment by m471c4** [comment]
@Luis-Fernando-Molina acá algunas pruebas de color. Cree dos versiones con las correcciones (una con monedas y la otra sin ellas):

![dwalletcolor](https://cloud.githubusercontent.com/assets/13468350/10563457/b18afd9c-7554-11e5-9e09-10142366ceec.png)

Versión 1:
![dwallet10a](https://cloud.githubusercontent.com/assets/13468350/10563458/bca383d4-7554-11e5-8be6-98a57f12f2d9.png)
![dwallet10b](https://cloud.githubusercontent.com/assets/13468350/10563459/bcadc812-7554-11e5-8b8b-ba068f620fbd.png)

Versión 2:
![dwallet13a](https://cloud.githubusercontent.com/assets/13468350/10563460/c53a095a-7554-11e5-8376-408b51fe5846.png)
![dwallet13b](https://cloud.githubusercontent.com/assets/13468350/10563461/c5f2fcd0-7554-11e5-8a41-e595fff723d1.png)

Versión 3:
![dwallet12a](https://cloud.githubusercontent.com/assets/13468350/10563462/cf8cc186-7554-11e5-9b4e-fdc437d09c5e.png)
![dwallet12b](https://cloud.githubusercontent.com/assets/13468350/10563463/d013017e-7554-11e5-9747-8f951de2bacf.png)

Versión 4:
![dwallet11a](https://cloud.githubusercontent.com/assets/13468350/10563464/d9af14a2-7554-11e5-92f2-8efe3480f0e8.png)
![dwallet11b](https://cloud.githubusercontent.com/assets/13468350/10563465/d9b9631c-7554-11e5-94c3-a9613c03784b.png)

**Comment by Luis-Fernando-Molina** [comment]
Ok, continuemos por favor la version 1 sin las monedas crypto ni el circulo. Proba por favor enderezar el tag y tambien poner monedas fiat en vez de cripto.

**Comment by m471c4** [comment]
@Luis-Fernando-Molina acá con las mejoras:

![dwalletdef1](https://cloud.githubusercontent.com/assets/13468350/10592851/b612651e-7688-11e5-86bb-d875beda0950.png)

Tengo algunas dudas con respecto al formato. Estaba usando el círculo para lograr dimensiones cuadradas exactas, ya que el tag es apaisado, no se si alguno de los chicos de UX (@vnesita, @Neoperol) me pueden responder si esto de dejar el ícono de estas dimensiones  (y centrarlo) es considerada una "buena práctica". Gracias :)

**Comment by vnesita** [comment]
hola @m471c4 pues si, se verá un poco más pequeño que el resto de los iconos en el mercado, ya que, se reduciría hasta llegar al espacio que tienen todos, no sé si me explico?. Lo otro que te aconsejo es que sea mucho mas simples, que no tenga tantos pequeños detalles que cuando lo lleves a su tamaño más pequeño estos se vayan a perder. Algo que puedes hacer es colocarlos al lado de estos que te estoy pasando del mismo tamaño que los otros a ver si tiene suficiente peso visual y si llama la atención tanto o más que el resto.
![unnamed](https://cloud.githubusercontent.com/assets/6201065/10595014/e8b4cbd2-76b1-11e5-95db-c37aa54827c5.png)

**Comment by m471c4** [comment]
@vnesita ¡muchas gracias! Voy a compararlos como me dices y veré cómo los puedo simplificar.

**Comment by m471c4** [comment]
@Luis-Fernando-Molina acá un poco más simple de acuerdo a las sugerencias de Vanessa. Monté 3 versiones en la imagen que me pasó para que veas la comparación y decidas cuál se ajusta mejor o qué cambios adicionales se deben realizar.

![dwallet14](https://cloud.githubusercontent.com/assets/13468350/10629319/927e9220-7797-11e5-922d-e21d41801c37.png)

![dwallet_compararicon](https://cloud.githubusercontent.com/assets/13468350/10629320/940be444-7797-11e5-8bf6-d24441810593.png)

**Comment by Luis-Fernando-Molina** [comment]
la de la segunda fila. Proba dejar solo una moneda de $ y un poquito mas afuera del bolsillo asi se llega a ver cuando esta en tamaño pequeño please.

**Comment by m471c4** [comment]
@Luis-Fernando-Molina probé dejando una sola moneda pero se veía muy desequilibrado, así que dejé las dos de los lados pero las escondí más detrás del "bolsillo", e hice la del cenror más grande, así que el signo de dolar se hace más visible. También cambié el color del centro de la moneda al magenta más claro ya que en la reducción el más oscuro se perdía.

Acá con una sola moneda:
![dwallet16](https://cloud.githubusercontent.com/assets/13468350/10645299/dd48080e-77f6-11e5-96f4-a0da781237f3.png)

Acá mi propuesta final:
![dwallet15](https://cloud.githubusercontent.com/assets/13468350/10645236/8b302ad8-77f6-11e5-8dec-071f2bb427c4.png)

Y acá podemos verla comparada con los demás iconos:
![dwalletcomp](https://cloud.githubusercontent.com/assets/13468350/10645274/bfb49b40-77f6-11e5-93e8-e2ca99aa4f8a.png)

**Comment by m471c4** [comment]
@Luis-Fernando-Molina si te sigue pareciendo muy chica la moneda, se me ocurre reducir el tamaño del "bolsillo" para que la moneda pueda ocupar más espacio. Espero tu opinión.

**Comment by Luis-Fernando-Molina** [comment]
Ok, sigamos con la version de 1 sola moneda y achica un poquito el bolsillo y agranda un poquito la moneda.

**Comment by m471c4** [comment]
@Luis-Fernando-Molina acá con el bolsillo ligeramente más pequeño y la moneda más grande:

![dwallet17](https://cloud.githubusercontent.com/assets/13468350/10676537/cc40f25c-78d0-11e5-9bc6-ae8ffbaf7cde.png)

Acá cómo se ve pequeño:
![dwalletcomp2](https://cloud.githubusercontent.com/assets/13468350/10676541/d5535088-78d0-11e5-85bc-dbd329e746be.png)

**Comment by Luis-Fernando-Molina** [comment]
Prefiero un poquito mas chica pero mas salida del bolsillo. Así la S se ve entera.

**Comment by m471c4** [comment]
@Luis-Fernando-Molina ¿qué tal así? El signo de $ se ve completo.

![dwallet18](https://cloud.githubusercontent.com/assets/13468350/10681987/b28a1f86-78f9-11e5-94c9-570865a25b91.png)

**Comment by Luis-Fernando-Molina** [comment]
:+1:  Listo lo dejamos asi.

**Comment by m471c4** [comment]
@Luis-Fernando-Molina muy bien, subiré las fuentes al repositorio :)
