### ISSUE TITLE
Crear banner de presentación para la Discount Wallet

### ISSUE THREAD

**Issue by m471c4** [bitDubai/fermat-graphic-design#119]
Viene del #117

El Banner de presentación o gráfico de funciones es una potente herramienta que permite mostrar tus recursos creativos y atraer a los usuarios. Este sera publicado en la Wallet Store.

Requisitos

Archivo JPEG o PNG de 24 bits (no alpha)
Tamaño: 1024x500 píxeles

**Comment by m471c4** [comment]
@Luis-Fernando-Molina primeras versiones para el banner.

Versión 1:
![dwalletbanner1](https://cloud.githubusercontent.com/assets/13468350/10630209/f2fdb0f2-779e-11e5-9ad1-1358f8964624.png)

Versión 2:
![dwalletbanner2](https://cloud.githubusercontent.com/assets/13468350/10630210/f32032ee-779e-11e5-9177-3938a60f009b.png)

**Comment by Luis-Fernando-Molina** [comment]
sigamos con el de abajo, no me concence la mezcla del % con wallet, probamos de otra forma please?

**Comment by m471c4** [comment]
@Luis-Fernando-Molina acá con los cambios que me pediste. Hice una versión con el fondo más oscuro y creo que resalta más. Espero tus comentarios.

![dwalletbanner3](https://cloud.githubusercontent.com/assets/13468350/10646252/1099ac62-77fc-11e5-87c0-7401e1018e02.png)
![dwalletbanner4](https://cloud.githubusercontent.com/assets/13468350/10646253/10b13116-77fc-11e5-84fc-80df80b8465b.png)

**Comment by Luis-Fernando-Molina** [comment]
vamos con la primera, el borde blanco de las letras debiera ser del mismo ancho que el borde blanco de la wallet.

**Comment by m471c4** [comment]
@Luis-Fernando-Molina acá con las mejoras que solicitaste. Agrandé un poco el ícono y engrosé la palagra Discount para que se leyera mejor.

![dwalletbanner5](https://cloud.githubusercontent.com/assets/13468350/10676839/a9991fb6-78d2-11e5-9257-98fae8af83e6.png)

**Comment by Luis-Fernando-Molina** [comment]
Proba por favor con un poco de sobra difusa del icono y las palabras también. Gracias

**Comment by m471c4** [comment]
@Luis-Fernando-Molina acá con la sombra difusa:

![dwalletbanner](https://cloud.githubusercontent.com/assets/13468350/10723092/7302f698-7b89-11e5-953d-6b8bf87cac7d.png)

**Comment by Luis-Fernando-Molina** [comment]
Porque la sobre afeca la parte blanca? Me imaginaba que solo caiga sobre el fondo.

**Comment by m471c4** [comment]
@Luis-Fernando-Molina acá con la modificación de la sombra:

![dwalletbanner_2](https://cloud.githubusercontent.com/assets/13468350/10750412/29c18ab2-7c47-11e5-981a-94fa2522c260.png)

**Comment by m471c4** [comment]
@Luis-Fernando-Molina cuando puedas por favor revisa el último comentario de este caso, que ya tiene las mejoras que habías sugerido.

**Comment by Luis-Fernando-Molina** [comment]
:+1:  lo dejemos así

**Comment by m471c4** [comment]
@Luis-Fernando-Molina excelente, lo subiré al repositorio entonces.
