### ISSUE TITLE
SUPER ISSUE: Mejorar BitDubai Deck Prezi

### ISSUE THREAD

**Issue by Luis-Fernando-Molina** [bitDubai/fermat-graphic-design#12]
@arnaldos, en el siguiente enlace se encuentra la presentación de negocios de BitDubai: http://prezi.com/fjxylzpymmn9/?utm_campaign=share&utm_medium=copy

Es necesario revisarla bien y proponer mejoras en caso de ser necesarias.

**Comment by arnaldos** [comment]
Revisando la presentación bitDubai Deck he notado que hay laminas que se ven sobre saturadas esto genera dificultad en la lectura, haciendo difícil entender ciertas estructuras, creo que es necesario tener conocimiento de la ubicación de las laminas para poder realizar los ajustes. y también para analizarlas con mayor detalle.

**Comment by Luis-Fernando-Molina** [comment]
@arnaldos te animas a crear un Issue con lo que encontraste? Le ponés de título lo que habría que hacer y si hace falta una descripción en el detalle.

**Comment by m471c4** [comment]
Me parece que la digramación de la presentación en general puede mejorar con el uso de una retícula que nos permita organizar los elementos y darles dinamismo. Crearé un issue para eso.
