### ISSUE TITLE
Crear icono para la Crypto Commodity Money Wallet

### ISSUE THREAD

**Issue by m471c4** [bitDubai/fermat-graphic-design#122]
Viene del #120

**Comment by emmysm** [comment]
@Luis-Fernando-Molina  , aca planteo dos propuestas para el ícono

![commodity wallet](https://cloud.githubusercontent.com/assets/15143489/10585376/c5f38cec-7660-11e5-957c-75717390669b.jpg)

![icono commdity 2](https://cloud.githubusercontent.com/assets/15143489/10585492/428cec1c-7661-11e5-949d-8718fbb0179c.jpg)

**Comment by Luis-Fernando-Molina** [comment]
@bitDubai/graphic-design-team estimados, desde ahora, como ya somos varios, no alcanza para un issue con poner un titulo como hasta ahora. Debe tambien venir en el cuerpo del issue una descripción de lo que hay que diseñar con todos los detalles a tener en cuenta.

@emmysm parece que hubo un error en fermat.org y esta wallet quedó como en construcción cuando en realidad no está en los planes realizarse. Proseguí por favor con otros issues.
