### ISSUE TITLE
Crear icono para la Crypto Broker Wallet

### ISSUE THREAD

**Issue by m471c4** [bitDubai/fermat-graphic-design#124]
Viene del #123

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina propuestas de icono

Versión 1
![icono1](https://cloud.githubusercontent.com/assets/13594347/10195638/72effae2-6758-11e5-8625-798a4a748c29.jpg)

Versión 2
![icono2](https://cloud.githubusercontent.com/assets/13594347/10195639/72f4d9ae-6758-11e5-8179-558cf365f4e0.jpg)

**Comment by Luis-Fernando-Molina** [comment]
por favor ponelo mas chico y sobre algun desktop como hacíamos antes

**Comment by Luis-Fernando-Molina** [comment]
ok, ya lo vi en otro issue. El icono blanco me gusta mas.
