### ISSUE TITLE
Crear banner de presentación para la Crypto Broker Wallet

### ISSUE THREAD

**Issue by m471c4** [bitDubai/fermat-graphic-design#125]
Viene del #123

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina Primer boceto de banner para la crypto broker wallet
![banner](https://cloud.githubusercontent.com/assets/13594347/10167592/f796cd50-6692-11e5-9132-6928d46e0344.jpg)

**Comment by Luis-Fernando-Molina** [comment]
El logo esta bueno, puede que sirva para otra cosa. Para esta debería ser algo que te refiera al crypto broker.

Fijate si podes encontrar la manera de que sin leer la imagen te transmita eso.

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina 
ok perfecto voy a investigar un poco mas para ver como conceptualizo esta !!! :+1:

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina  adjunto otras versiones

Versión 1
![banner2](https://cloud.githubusercontent.com/assets/13594347/10177503/4fbe9d2e-66c4-11e5-9d47-81d24d08073b.jpg)

Versión 2
![banner3](https://cloud.githubusercontent.com/assets/13594347/10177504/4fe482c8-66c4-11e5-98d0-bdee9ac891b7.jpg)

Versión 3
![banner4](https://cloud.githubusercontent.com/assets/13594347/10177505/4feb1430-66c4-11e5-9684-8a54b545c982.jpg)

Versión 4
![banner5](https://cloud.githubusercontent.com/assets/13594347/10177506/5000d34c-66c4-11e5-8d98-fb1d5992acea.jpg)

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina nuevas versiones de banner

Versión 5
![banner6](https://cloud.githubusercontent.com/assets/13594347/10223918/4f44a5e8-6825-11e5-9db2-07e347e3a7a1.jpg)

Versión 6
![banner7](https://cloud.githubusercontent.com/assets/13594347/10223919/4f4a8f9e-6825-11e5-9587-64e1d4a6b0a3.jpg)

Versión 7
![banner8](https://cloud.githubusercontent.com/assets/13594347/10223920/4f4e1ef2-6825-11e5-9d22-cda694eddc00.jpg)

**Comment by Luis-Fernando-Molina** [comment]
Buenisimo! Version 6 :+1:

**Comment by Luis-Fernando-Molina** [comment]
@Neoperol @vnesita @nelsonalfo Fijense por favor que ahora que se aprobó el banner de la wallet y el icono corresponiente, queda automáticamente definido los colores y en cierta manera el estilo para esta wallet. Me imagino @Neoperol que te pueden servir para el trabajo que estas haciendo.
