### ISSUE TITLE
SUPERISSUE: Diseñar la identidad de la Crypto Customer Wallet (CrCu)

### ISSUE THREAD

**Issue by m471c4** [bitDubai/fermat-graphic-design#126]
1- Crear icono para la Crypto Customer Wallet.
2- Crear banner de presentación para la Crypto Customer Wallet.

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina comparto unos sreenshot para visualizar todos los elementos en conjunto 

![sreenshot-bitcoin-wallet](https://cloud.githubusercontent.com/assets/13594347/10195727/e4eae7ec-6758-11e5-9661-760c4b56ad86.png)
![sreenshot-bitcoin-wallet2](https://cloud.githubusercontent.com/assets/13594347/10195728/e4efda36-6758-11e5-8b6d-e2f1c919bc89.png)
![sreenshot-bitcoin-wallet3](https://cloud.githubusercontent.com/assets/13594347/10195729/e4f70dc4-6758-11e5-8dbf-74354a187dfa.png)
![sreenshot-bitcoin-wallet4](https://cloud.githubusercontent.com/assets/13594347/10195730/e4f974e2-6758-11e5-82a6-0cfc0e120bc9.jpg)
![sreenshot-bitcoin-wallet5](https://cloud.githubusercontent.com/assets/13594347/10195731/e4fdeafe-6758-11e5-9d26-3f9f1748d3d0.jpg)

**Comment by arnaldos** [comment]
medidas ajustadas
![sreenshot-bitcoin-wallet6](https://cloud.githubusercontent.com/assets/13594347/10195769/1c631316-6759-11e5-9aef-186e8370ab89.jpg)

**Comment by Luis-Fernando-Molina** [comment]
ok, el juego de fondo blanco :+1: 

Pero el banner no me termina de convencer. Fijate de usar como background algun tipo de grafico como los que se usan en las cotizaciones de las acciones (candle sticks ) o algo asi.

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina  ya le realizo los ajustes para el banner !!!

**Comment by Luis-Fernando-Molina** [comment]
no entiendo, que ajuste?

**Comment by arnaldos** [comment]
me dice que el banner no estas convencido del todo por eso voy a realizar otra propuesta !!! realmente no seria un ajuste sino una nueva propuesta a lo que me referia !! :smile:

**Comment by Luis-Fernando-Molina** [comment]
ok, el logo y lo que dice no esta mal, solo el fondo me referia yo que puede mejorarse.

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina si de esa manera lo entendí, fui yo quien no se dio a entender :disappointed: ,pero ya estoy mejorando el banner !!
