### ISSUE TITLE
Crear icono para la Crypto Customer Wallet

### ISSUE THREAD

**Issue by m471c4** [bitDubai/fermat-graphic-design#127]
Viene del #126

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina icono para la crypto customer wallet

Versión 2
![icono-wallet-factory3](https://cloud.githubusercontent.com/assets/13594347/10300872/2f297e74-6bc6-11e5-8909-87b42316971a.jpg)
![icono-wallet-factory4](https://cloud.githubusercontent.com/assets/13594347/10300873/2f30cfbc-6bc6-11e5-87de-d65bbb4f48fa.jpg)

Versión 3
![icono-wallet-factory6](https://cloud.githubusercontent.com/assets/13594347/10300896/6d95fbb0-6bc6-11e5-9f43-fde53939e028.jpg)
![icono-wallet-factory5](https://cloud.githubusercontent.com/assets/13594347/10300897/6d9a800e-6bc6-11e5-8306-2033787e3fdc.jpg)

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina disculpa esta es la wallet factory ya la ubico el caso correspondiente

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina esta si es la nueva versión que trabaje para la crypto customer wallet

![icono-crypto-customer3](https://cloud.githubusercontent.com/assets/13594347/10300975/74f63c2a-6bc7-11e5-9ccf-a3f1540cfa9d.jpg)
![icono-crypto-customer4](https://cloud.githubusercontent.com/assets/13594347/10300974/74f5e86a-6bc7-11e5-9e04-a6d64fbaf13b.jpg)

**Comment by Luis-Fernando-Molina** [comment]
ponele por favor una costura para que se vea mas que es una wallet. Como quedaria sobre un fondo no blanco?

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina ya genero la versión con un fondo diferente al blanco y la costura que solicitas

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina Versión del icono con la costura

versión 1

![icono-crypto-customer5](https://cloud.githubusercontent.com/assets/13594347/10314924/219b45de-6c21-11e5-8cd7-1f54b2c3a832.jpg)

![icono-crypto-customer6](https://cloud.githubusercontent.com/assets/13594347/10314925/21a1f0c8-6c21-11e5-964f-aa44c444697a.jpg)

versión 2

![icono-crypto-customer7](https://cloud.githubusercontent.com/assets/13594347/10314956/418baca8-6c21-11e5-9890-2dd9a97c0326.jpg)

![icono-crypto-customer8](https://cloud.githubusercontent.com/assets/13594347/10314957/41906874-6c21-11e5-929c-4622981e5a91.jpg)

versión 3

![icono-crypto-customer9](https://cloud.githubusercontent.com/assets/13594347/10314962/4ba1bc00-6c21-11e5-80f3-fdf47380c634.jpg)

![icono-crypto-customer10](https://cloud.githubusercontent.com/assets/13594347/10314963/4ba42dc8-6c21-11e5-8a02-274119a6e27a.jpg)

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina así se veria con un fondo mas colorido
![icono-crypto-customer11](https://cloud.githubusercontent.com/assets/13594347/10315272/1404b9f8-6c23-11e5-9a9f-a2348ca08111.jpg)

**Comment by arnaldos** [comment]
me inclino mas por la versión que no tiene el marco blanco

**Comment by Luis-Fernando-Molina** [comment]
ok, el circulo azul lo veo como muy vacio, lo podes mejorar?

**Comment by Luis-Fernando-Molina** [comment]
la versionde fondo transparente :+1:  fijate en lo del circulo azul

**Comment by arnaldos** [comment]
dale perfecto !!! ya veo que solución le doy para que no se vea tan simple :smiley:

**Comment by arnaldos** [comment]
el circulo

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina aqui las versiones con el ajuste del circulo

Versión 4
![icono-crypto-customer12](https://cloud.githubusercontent.com/assets/13594347/10322875/9fb66d04-6c49-11e5-84e6-a2a9a1d275cd.jpg)
![icono-crypto-customer13](https://cloud.githubusercontent.com/assets/13594347/10322876/9fbc7582-6c49-11e5-8fc9-810947966363.jpg)

Versión 5

![icono-crypto-customer14](https://cloud.githubusercontent.com/assets/13594347/10322915/d12f5792-6c49-11e5-8376-8477413e5a4a.jpg)
![icono-crypto-customer15](https://cloud.githubusercontent.com/assets/13594347/10322916/d133e6ea-6c49-11e5-9525-e4c3d6b8d00e.jpg)

**Comment by Luis-Fernando-Molina** [comment]
Version 4 :+1:  Vamos a dejarlo así.

**Comment by arnaldos** [comment]
perfecto !!!! ya me enfoco con le banner de esta wallet
