### ISSUE TITLE
Crear banner de presentación para la Crypto Customer Wallet

### ISSUE THREAD

**Issue by m471c4** [bitDubai/fermat-graphic-design#128]
Viene del #126

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina Versión 1 icono Crypto Customer

![icono-crypto-customer](https://cloud.githubusercontent.com/assets/13594347/10227746/ec163eaa-6838-11e5-8aa1-e1eb7ff7abef.jpg)
![icono-crypto-customer2](https://cloud.githubusercontent.com/assets/13594347/10227747/ec16b4ac-6838-11e5-9c16-222502ff7441.jpg)

**Comment by Luis-Fernando-Molina** [comment]
El texto esta bien, me gusta. Pero como explique en otros casos, vamos a hacer las cosas en orden. Primero aprobemos el icono, luego el baner.

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina si aun no he realizado nada para el caso del banner, aqui muestro el icono solo y el icono con el texto, para poder visualizar como se comporta con o sin texto. una ves se apruebe el icono procedo a trabajar en el caso del banner !!! :smile:

**Comment by Luis-Fernando-Molina** [comment]
ah yo pense que era l banner. Ok busca que el icono sea representativo de esa wallet.

**Comment by arnaldos** [comment]
aquí buscaba representar al cliente, con un icono donde se vea un personaje que se caracterice con una persona!! pero ya le voy la vuelta a este concepto y le doy otro enfoque !!!

**Comment by emmysm** [comment]
![banner crypto customer](https://cloud.githubusercontent.com/assets/15143489/10677535/d5121874-78d6-11e5-9439-25241566faeb.png)

@Luis-Fernando-Molina banner para la crypto customer wallet

**Comment by emmysm** [comment]
![banner crypto customer2](https://cloud.githubusercontent.com/assets/15143489/10680543/7aef3da4-78ea-11e5-9777-c1a54ed26c83.png)

@Luis-Fernando-Molina

**Comment by Luis-Fernando-Molina** [comment]
:+1: me encantó  :smile:

**Comment by emmysm** [comment]
Me alegra mucho! :dancers: . Ya lo subo al repositorio, @Luis-Fernando-Molina
