### ISSUE TITLE
Crear icono para la Asset Issuer Wallet

### ISSUE THREAD

**Issue by m471c4** [bitDubai/fermat-graphic-design#130]
Viene del #129 

**Asset Issuer Wallet**

Es la billetera que permite guardar los **Asset** enviados por los **Issuers**

**Issuer** son una entidad juridica (corporaciones, sociedad de inversión, empresas) autorizados para generar oferta  de sus propios valores. 

Los tipos más comunes de los valores emitidos son, acciones, bonos, pagarés  y derivados.

Los **Asset** Se usa como un concepto genérico.Son activos digitales, que pueden ser representados de diferentes maneras, Ejemplo: Baucher, cupones, acciones de empresas, servicios, elementos de marketing o productos, entre otros. que puede ser intercambiable.

**Requisitos**

Archivo PNG de 32 bits (alpha)
Tamaño: 512 x 512 píxeles
Tamaño máximo del archivo: 1024 KB

Una vez elegido el icono, es necesario generar los tamaños, en **.PNG** para aplicarlos en lo siguientes:

**IC launcher**:

48 × 48 px (mdpi)
72 × 72 px (hdpi)
96 × 96 px (xhdpi)
144 × 144 px (xxhdpi)
192 × 192 px (xxxhdpi)
512 × 512 px (Wallet store)

**Comment by mariavictoriapp** [comment]
![icono_asserissuerwallet-01](https://cloud.githubusercontent.com/assets/15197279/10861327/7ed8a784-7f4d-11e5-94c6-d621b3dfd441.png)

Buenas noches @Luis-Fernando-Molina @arnaldos quisiera conocer sus opiniones respecto a este boceto. La propuesta consiste en una billetera abierta donde se contienen una serie de vales y bonos.

**Comment by Luis-Fernando-Molina** [comment]
hola @mariavictoriapp los diseños de iconos solo los reviso en su tamaño target desde ahora, para evitar aprobar cosas que muy chiquitas no se verian. Preguntale a @arnaldos cual es el target y como mostrarlos. Gracias

**Comment by jurene22** [comment]
@Luis-Fernando-Molina @arnaldos Boceto para el Icon Asset_Issuer_Wallet
![icon_asset_issuer_wallet_issue130](https://cloud.githubusercontent.com/assets/15174317/10888065/48559f8a-815c-11e5-9dbf-08407816b5e8.png)
![asset_issuer_wallet vista](https://cloud.githubusercontent.com/assets/15174317/10888069/4c784338-815c-11e5-8b51-1ce4e5e5788b.png)

**Comment by jurene22** [comment]
![icon_asset_issuer_wallet_issue130 medium](https://cloud.githubusercontent.com/assets/15174317/10888104/7cfe5074-815c-11e5-9f04-c49f3efa9572.png)
Version 1

**Comment by Luis-Fernando-Molina** [comment]
@jurene22 no te excediste del tamaño estandard?

**Comment by arnaldos** [comment]
@jurene22 la billetera que estas usando no es la correcta fíjate en la carpeta de fermat ahí encontraras la versión final de esta billetera !!! :smile:

**Comment by m471c4** [comment]
@Luis-Fernando-Molina @arnaldos primer boceto para la Asset Issuer Wallet:

![aiwallet1](https://cloud.githubusercontent.com/assets/13468350/10933400/71c0cd5a-82aa-11e5-9047-c9c5340c78eb.png)

![aiwalletmu1](https://cloud.githubusercontent.com/assets/13468350/10933401/71c2373a-82aa-11e5-9082-c044ec68e278.png)

**Comment by Luis-Fernando-Molina** [comment]
Me gusta la idea de @m471c4 , exploremosla un poco mas.

**Comment by m471c4** [comment]
@Luis-Fernando-Molina muy bien, haré algunas variaciones y las subo.

**Comment by m471c4** [comment]
@Luis-Fernando-Molina varié el color y busqué resaltar más las formas geométricas. Me inclino por la versión 3 ya que gana más tridimensionalidad.

Versión 1:
![aiwallet2](https://cloud.githubusercontent.com/assets/13468350/10960344/76a79a2c-8356-11e5-8a87-bb8a4c42f097.png)
![aiwalletmu2](https://cloud.githubusercontent.com/assets/13468350/10960353/885f46ca-8356-11e5-9ea7-f4a72fb8f112.png)

Versión 2:
![aiwallet3](https://cloud.githubusercontent.com/assets/13468350/10960345/76a9531c-8356-11e5-9c51-1814ece7c555.png)
![aiwalletmu3](https://cloud.githubusercontent.com/assets/13468350/10960355/8d95f530-8356-11e5-9273-063470f3e0f8.png)

Versión 3:
![aiwallet4](https://cloud.githubusercontent.com/assets/13468350/10960346/76b16656-8356-11e5-9e41-ecac75595eae.png)
![aiwalletmu4](https://cloud.githubusercontent.com/assets/13468350/10960358/93010cda-8356-11e5-9d13-bb8a328a05ef.png)

**Comment by Luis-Fernando-Molina** [comment]
el primero color estaba bien, proba sacarle las letras asse y deja el resto. Los bordes claron en la figuras geometricas estan ok.

**Comment by m471c4** [comment]
@Luis-Fernando-Molina te comparto tres versiones con ligeras variaciones y el color anterior:

Versión 1:
![aiwallet5](https://cloud.githubusercontent.com/assets/13468350/10990236/3e72ca6e-8423-11e5-87eb-2fbb8a392362.png)
![aiwalletmu5](https://cloud.githubusercontent.com/assets/13468350/10990248/54477ac4-8423-11e5-8bc7-07cbbb787e38.png)

Versión 2:
![aiwallet8](https://cloud.githubusercontent.com/assets/13468350/10990237/3e770458-8423-11e5-9fe4-19561352494d.png)
![aiwalletmu6](https://cloud.githubusercontent.com/assets/13468350/10990252/595a16de-8423-11e5-9fb2-a42d4cd6d696.png)

Versión3
![aiwallet9](https://cloud.githubusercontent.com/assets/13468350/10990238/3e79efb0-8423-11e5-820d-46db3fcbe719.png)
![aiwalletmu7](https://cloud.githubusercontent.com/assets/13468350/10990257/6108f832-8423-11e5-8ff1-ef5ca748bacf.png)

**Comment by Luis-Fernando-Molina** [comment]
Volvamos a la version 3 donde decis

> varié el color y busqué resaltar más las formas geométricas. Me inclino por la versión 3 ya que gana más tridimensionalidad.

Usemos esa :+1:

**Comment by m471c4** [comment]
@Luis-Fernando-Molina excelente. ya está en el repositorio. Comenzaré a trabajar en el banner.
