### ISSUE TITLE
Crear banner de presentación para la Asset Issuer Wallet

### ISSUE THREAD

**Issue by m471c4** [bitDubai/fermat-graphic-design#131]
Viene del #129

El Banner de presentación o gráfico de funciones es una potente herramienta que permite mostrar tus recursos creativos y atraer a los usuarios. Este sera publicado en la Wallet Store.

Requisitos

Archivo JPEG o PNG de 24 bits (no alpha)
Tamaño: 1024x500 píxeles

**Comment by m471c4** [comment]
@Luis-Fernando-Molina acá las primeras propuestas para el banner, partiendo del icono previamente escogido:

Versión 1:
![aiwallet-banner1](https://cloud.githubusercontent.com/assets/13468350/11054572/15b73dba-8740-11e5-9ed5-fcc073579461.png)

Versión 2:
![aiwallet-banner2](https://cloud.githubusercontent.com/assets/13468350/11054573/15cb88f6-8740-11e5-9976-dbff1c2b258d.png)

Versión 3:
![aiwallet-banner3](https://cloud.githubusercontent.com/assets/13468350/11054574/15e220ca-8740-11e5-9ddd-297fe88317b6.png)

**Comment by Luis-Fernando-Molina** [comment]
Debiera ser a color, segui presentando opciones.

**Comment by m471c4** [comment]
@Luis-Fernando-Molina acá algunas propuestas más:

Versión 4:
![aiwallet-banner4](https://cloud.githubusercontent.com/assets/13468350/11080606/bdac5b16-87e7-11e5-8cc1-e3a76395804c.png)

Versión 5:
![aiwallet-banner5](https://cloud.githubusercontent.com/assets/13468350/11080607/bde45516-87e7-11e5-9125-7c4eaaed7a80.png)

Versión 6:
![aiwallet-banner6](https://cloud.githubusercontent.com/assets/13468350/11080608/bdef6762-87e7-11e5-9c9c-321095fc2a5d.png)
