### ISSUE TITLE
Crear icono para la Asset User Wallet

### ISSUE THREAD

**Issue by m471c4** [bitDubai/fermat-graphic-design#133]
Viene del #132 

**Asset User Wallet**
Es la billetara que permite almacenar o guardar, **Asset** enviado por los usuario.

Los **Asset** Se usa como un concepto genérico. Son activos digitales, que pueden ser representados de diferentes maneras, Ejemplo: Baucher, cupones, acciones de empresas, servicios, elementos de marketing o productos, entre otros. que puede ser intercambiable.

**Requisitos**

Archivo PNG de 32 bits (alpha)
Tamaño: 512 x 512 píxeles
Tamaño máximo del archivo: 1024 KB

Una vez elegido el icono, es necesario generar los tamaños, en **.PNG** para aplicarlos en lo siguientes:

**IC launcher**:

48 × 48 px (mdpi)
72 × 72 px (hdpi)
96 × 96 px (xhdpi)
144 × 144 px (xxhdpi)
192 × 192 px (xxxhdpi)
512 × 512 px (Wallet store)

**Comment by isahq23** [comment]
@arnaldos @Luis-Fernando-Molina 
Aporte para el Asset User Wallet

Propuesta 1-1
![asset_user_wallet_icon_1-1](https://cloud.githubusercontent.com/assets/15214774/10912423/a23fcb50-821b-11e5-86a8-525ac303433a.png)

Propuesta 1-2
![asset_user_wallet_icon_1-2](https://cloud.githubusercontent.com/assets/15214774/10912427/a748deac-821b-11e5-885e-e348041f850d.png)

Nexus
![asset_user_wallet_icon_nexus](https://cloud.githubusercontent.com/assets/15214774/10912434/ac976fa4-821b-11e5-8813-3b9a3212ef6f.png)

**Comment by mariavictoriapp** [comment]
![icono_asset_user_wallet mockup](https://cloud.githubusercontent.com/assets/15197279/10914043/c937a35c-8222-11e5-837e-245de4c1929a.png)
![icono_asset_user_wallet-01-01-01](https://cloud.githubusercontent.com/assets/15197279/10914044/c93c60d6-8222-11e5-9888-ab840373c704.png)

@Luis-Fernando-Molina @arnaldos

**Comment by Luis-Fernando-Molina** [comment]
hola, recordemos como representamos de manera standard algunas cosas aqui:

wallets: con costuras.
assets: con figuras geometricas basicas

**Comment by mariavictoriapp** [comment]
Hola Luis, perfecto haré los ajustes necesarios y vuelvo a enviar

**Comment by mariavictoriapp** [comment]
![icono_asset_user_wallet mockup](https://cloud.githubusercontent.com/assets/15197279/11024246/e59a240e-865d-11e5-855a-d8d2cd6479fc.png)
![icono_asset_user_wallet-01 copia1-01](https://cloud.githubusercontent.com/assets/15197279/11024245/e55a479e-865d-11e5-8834-320c671e1056.png)

Hola, buenas noches, acá adjunto las modificaciones al icono

**Comment by jurene22** [comment]
![icon_ asset_user_wallet_issue133](https://cloud.githubusercontent.com/assets/15174317/11064817/b741ba42-8791-11e5-9be6-8391d685ddec.png)
![vista target](https://cloud.githubusercontent.com/assets/15174317/11064818/b7485f8c-8791-11e5-931b-8299f3261798.png)
@Luis-Fernando-Molina Boceto 1 para Issue 133 en prioridad

**Comment by Luis-Fernando-Molina** [comment]
@jurene22 me gusto tu approach. Fijate si lo podes refinar un poco. Quitale las monedas de bitcoins y los assets ponele un borde blanco a cada figura geometrica, quizas se puedan acomodar mejor tambinén.

**Comment by jurene22** [comment]
![icon_ asset_user_wallet_issue133_refinado 1_1](https://cloud.githubusercontent.com/assets/15174317/11067281/0601a8ca-879e-11e5-943f-1edeb9ee42d6.png)
@Luis-Fernando-Molina Refinando 1

**Comment by jurene22** [comment]
![vista target](https://cloud.githubusercontent.com/assets/15174317/11067386/6f604182-879e-11e5-9f36-2cd6e8a98b87.png)
Vista target

**Comment by arnaldos** [comment]
@jurene22  de acuerdo con @Luis-Fernando-Molina  me gusta tu propuesta para el icono, una observación, y es a nivel de vectores cuida la construcción de los mismos, has que esas lineas sean uniformes y limpias acá se pueden apreciar los nodos en cada punto en que los colocaste. plz si usas curvas en las esquinas has que se aprecie esa curva. busca estandarizar esos puntos ya que veo que tienes una esquina curva y otra recta. también cuida las perspectiva de los elementos has te mantengan la misma, porque sino se pueden apreciar como si cada elemento va por su lado. ya veras como te va a alzar tu propuesta y se va a ver excelente !! :smile:

**Comment by jurene22** [comment]
Chevere muchas gracias por las acotaciones, me pondre a trabajar en esos detalles y mes envio de nuevo a ver que les parece

**Comment by arnaldos** [comment]
vale perfecto !!! :smile:

**Comment by jurene22** [comment]
![icon_ asset_user_wallet_issue133_refinados 2](https://cloud.githubusercontent.com/assets/15174317/11070264/eef02b98-87ac-11e5-9d19-21c749debee1.png)

**Comment by isahq23** [comment]
@arnaldos @Luis-Fernando-Molina 

Propuesta 1-1
![asset_user_wallet_ir_1-1](https://cloud.githubusercontent.com/assets/15214774/11073593/8568e7d0-87bd-11e5-81b7-52ca8f8f8490.png)

Propuesta 1-2
![asset_user_wallet_ir_1-2](https://cloud.githubusercontent.com/assets/15214774/11073596/8a2a0bd2-87bd-11e5-9e09-853a8aaacb63.png)

Propuesta 1-3
![asset_user_wallet_ir_1-3](https://cloud.githubusercontent.com/assets/15214774/11073600/8e9a4f06-87bd-11e5-8e46-c75b50e95990.png)

NExus1
![asset_user_wallet_ir_nexus1](https://cloud.githubusercontent.com/assets/15214774/11073603/94fa9de2-87bd-11e5-9a19-7c1c3cf2f48d.png)

**Comment by jurene22** [comment]
![icon_ asset_user_wallet_issue133_refinado 3](https://cloud.githubusercontent.com/assets/15174317/11135512/e126830a-8977-11e5-9bda-396593552885.png)
@Luis-Fernando-Molina @arnaldos Refinado 3
agregando un poco de perpectiva a las figuras geometricas y refinando bordes

**Comment by Luis-Fernando-Molina** [comment]
proba quitar el cuadradito y que queden solo las otras dos y un poquito mas separadas..

**Comment by jurene22** [comment]
![icon_ asset_user_wallet_issue133_refinado 4](https://cloud.githubusercontent.com/assets/15174317/11187725/b8ed8a5c-8c59-11e5-93a4-f66dbaf00e45.png)
@Luis-Fernando-Molina aqui aporte con cambios sugeridos

**Comment by jurene22** [comment]
![vista target](https://cloud.githubusercontent.com/assets/15174317/11212924/3b1ae658-8d0b-11e5-87dd-f3f21454e451.png)
@Luis-Fernando-Molina Vista target

**Comment by Luis-Fernando-Molina** [comment]
:+1:

**Comment by jurene22** [comment]
listo! ya estan los editables y en diferentes formatos el icono en 2D Desing... gracias
