### ISSUE TITLE
Crear banner de presentación para la Asset User Wallet

### ISSUE THREAD

**Issue by m471c4** [bitDubai/fermat-graphic-design#134]
Viene del #132 

El Banner de presentación o gráfico de funciones es una potente herramienta que permite mostrar tus recursos creativos y atraer a los usuarios. Este sera publicado en la Wallet Store.

Requisitos

Archivo JPEG o PNG de 24 bits (no alpha)
Tamaño: 1024x500 píxeles

Una vez el icono se encuentre aprobado,  procedemos a diseñar el banner (que debe seguir los mismos lineamientos gráficos del icono).

**Comment by ivonnesantos** [comment]
@m471c4 @arnaldos donde puedo encontrar la info de esta app para saber que contenido voy a colocar en el banner?

**Comment by arnaldos** [comment]
@ivonnesantos  fíjate si entras en el caso #132 que es la base o el issue #133 tambien esta relacionado y puedes tener mas info.  :smile:

**Comment by m471c4** [comment]
@ivonnesantos en este caso, la metodología de trabajo sugerida por parte de @Luis-Fernando-Molina y @arnaldos ha sido realizar primero el icono, y una vez este se encuentre aprobado, diseñar el banner (que debe seguir los mismos lineamientos gráficos del icono).

**Comment by m471c4** [comment]
@arnaldos tal vez sería bueno indicar esa información el el superissue del cual se desprende cada uno de estos casos, ¿qué te parece?

**Comment by arnaldos** [comment]
@m471c4 ya lo coloco para evitar confusiones :+1:
