### ISSUE TITLE
Crear icono para la Redeem Point Wallet

### ISSUE THREAD

**Issue by m471c4** [bitDubai/fermat-graphic-design#136]
Viene del #135 

Es la billetara que permite almacenar o guardar, los puntos de intercambio de Asset.

Los **Asset** Se usa como un concepto genérico. Son activos digitales, que pueden ser representados de diferentes maneras, Ejemplo: Baucher, cupones, acciones de empresas, servicios, elementos de marketing o productos, entre otros. que puede ser intercambiable.

**Requisitos**

Archivo PNG de 32 bits (alpha)
Tamaño: 512 x 512 píxeles
Tamaño máximo del archivo: 1024 KB

Una vez elegido el icono, es necesario generar los tamaños, en **.PNG** para aplicarlos en lo siguientes:

**IC launcher**:

48 × 48 px (mdpi)
72 × 72 px (hdpi)
96 × 96 px (xhdpi)
144 × 144 px (xxhdpi)
192 × 192 px (xxxhdpi)
512 × 512 px (Wallet store)

**Comment by m471c4** [comment]
@Luis-Fernando-Molina @arnaldos primeros bocetos para el ícono de Redeem Point Wallet.

![rpwallet1](https://cloud.githubusercontent.com/assets/13468350/10792639/aa1897f0-7d5f-11e5-9d55-37fb56cf5d71.png)

![rpwallet2](https://cloud.githubusercontent.com/assets/13468350/10792686/eabc0436-7d5f-11e5-8742-5757a0a3d937.png)

**Comment by Luis-Fernando-Molina** [comment]
1. Me gusta el concepto del ticket ese
2. No me gusta que este dentro de un circulo

Una wallet de reedem point es la que recibe un digital asset en el momento en que se entrega la mercaderia final. Fijate si podes reflejar eso en otras variantes por favor.

**Comment by m471c4** [comment]
@Luis-Fernando-Molina acá algunas versiones:

![rpwallet4](https://cloud.githubusercontent.com/assets/13468350/10876004/c7ba7b9e-810a-11e5-9deb-5e83cca51c35.png)

![rpwallet5](https://cloud.githubusercontent.com/assets/13468350/10876005/ca785252-810a-11e5-8817-8a80270b48c0.png)

**Comment by Luis-Fernando-Molina** [comment]
@m471c4 los iconos directamente en tamaño final para su revision, gracias

**Comment by m471c4** [comment]
@Luis-Fernando-Molina acá puedes ver las propuestas anteriores:

Versión 1:
![rpwalletmu3](https://cloud.githubusercontent.com/assets/13468350/10902141/c8faac7e-81cb-11e5-8f38-10332e400ca4.png)

Versión 2:
![rpwalletmu4](https://cloud.githubusercontent.com/assets/13468350/10902139/c41356ca-81cb-11e5-941f-8a2b2f3561f0.png)

**Comment by Luis-Fernando-Molina** [comment]
ok, vamos con la version 1.

Las letras que se ven espejadas , debiera ser una R y una P y nos dos R

**Comment by m471c4** [comment]
@Luis-Fernando-Molina muy bien, acá con la corrección. 

![rpwallet6](https://cloud.githubusercontent.com/assets/13468350/10932465/2f79e4ba-82a3-11e5-81db-99edfb212a71.png)
![rpwalletmu5](https://cloud.githubusercontent.com/assets/13468350/10932466/2f92309c-82a3-11e5-8bd4-da6024cbef5b.png)

Cree una versión donde el ángulo del ticket del fondo es mayor, a ver qué te parece (se ajusta mejor al grid cuadrado).

![rpwallet7](https://cloud.githubusercontent.com/assets/13468350/10932470/35c9619c-82a3-11e5-8d59-cd1e0f9d5963.png)
![rpwalletmu6](https://cloud.githubusercontent.com/assets/13468350/10932471/35de47c4-82a3-11e5-9832-1b7501fa09fc.png)

Por otro lado, ¿los colores te parecen bien?

**Comment by Luis-Fernando-Molina** [comment]
Fijate si podes simular un acordion de tickets.

**Comment by m471c4** [comment]
@Luis-Fernando-Molina ¿con acordeón te refieres a una especie de abanico como este?

![rpwallet8](https://cloud.githubusercontent.com/assets/13468350/10962250/03d88a7a-8369-11e5-835a-b942ec4c386f.png)
![rpwalletmu7](https://cloud.githubusercontent.com/assets/13468350/10962251/03e048dc-8369-11e5-8b5f-fb07b0eecf7c.png)

**Comment by Luis-Fernando-Molina** [comment]
no, me refiero a que si estuviesen unidas como tickets reales pudieran plegarse una atras de la otra.
