### ISSUE TITLE
Crear banner de presentación para la Redeem Point Wallet

### ISSUE THREAD

**Issue by m471c4** [bitDubai/fermat-graphic-design#137]
Viene del #135

El Banner de presentación o gráfico de funciones es una potente herramienta que permite mostrar tus recursos creativos y atraer a los usuarios. Este sera publicado en la Wallet Store.

Requisitos

Archivo JPEG o PNG de 24 bits (no alpha)
Tamaño: 1024x500 píxeles

**Comment by ivonnesantos** [comment]
@arnaldos @Luis-Fernando-Molina 
![banner_01](https://cloud.githubusercontent.com/assets/15238660/12374123/7be8a598-bc64-11e5-85b6-c3b6c8bbde63.png)
![banner_02](https://cloud.githubusercontent.com/assets/15238660/12374124/7c01708c-bc64-11e5-8629-e50f5f241e36.png)
![banner_03](https://cloud.githubusercontent.com/assets/15238660/12374125/7c181026-bc64-11e5-9014-8710617813c3.png)

**Comment by ivonnesantos** [comment]
![banner_04](https://cloud.githubusercontent.com/assets/15238660/12400666/a7236af0-bdf3-11e5-9ca3-195377421d71.png)
![banner_05](https://cloud.githubusercontent.com/assets/15238660/12400667/a74718ce-bdf3-11e5-963c-e6ef9b48cff1.png)

@arnaldos @Luis-Fernando-Molina propuestas partiendo de las 2

**Comment by ivonnesantos** [comment]
otra propuesta de color 
![banner_06](https://cloud.githubusercontent.com/assets/15238660/12400784/5b18eba2-bdf4-11e5-83e1-30f1e1d4bff1.png)
@arnaldos

**Comment by arnaldos** [comment]
la versión 5, solo cambia el icono de bitcoins por alguna otra cosa que represente los asset

**Comment by arnaldos** [comment]
juega con los colores, que identifican a la redeem point. si no busca una gama de colores mas amigable para el logo y proponla aqui para ver como funciona

**Comment by ivonnesantos** [comment]
![banner_07](https://cloud.githubusercontent.com/assets/15238660/12406411/e77df108-be1e-11e5-9a1d-4ea5e28cb317.png)
![banner_08](https://cloud.githubusercontent.com/assets/15238660/12406412/e78bbeb4-be1e-11e5-859c-d0c0f029a22a.png)

@arnaldos

**Comment by ivonnesantos** [comment]
![banner](https://cloud.githubusercontent.com/assets/15238660/12566817/dff2ca66-c38d-11e5-96ad-0a25d44e8c87.png)
@arnaldos

**Comment by arnaldos** [comment]
:+1: propuesta 9
