### ISSUE TITLE
Listado de subApplicaciones 

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#138]
Verificar el listado de subApplicaciones en el que se realizaran los diseño correspondientes a cada caso.

A continuación dejo el listado:

[ ] - Intra user 
- Shell
- Developer
- Techical support
-  Feed Back
- Sub App manager
- Sub App Runtime
- Designer
- Developer
- System Monitor
- Fleviews
- Intra user Community
- Extra user
- Asset Issuer Community
- Redeeem Point Community
- Asset Factory
- Crypto Broker Identity
- Customers
- Crypto Distribution
- Device Privet

@Luis-Fernando-Molina @m471c4  Este listado no es definitivo por lo que debemos verificar que todo este en orden antes de desplegar los casos de cada subApp.

**Comment by Luis-Fernando-Molina** [comment]
- [x]  Intra user 
- [ ]  Shell
- [x]  Developer
- [ ]  Techical support
- [ ]   Feed Back
- [ ]  Sub App manager
- [ ]  Sub App Runtime
- [ ]  Designer
- [x]  Developer
- [ ]  System Monitor
- [ ]  Fleviews
- [x]  Intra user Community
- [ ]  Extra user
- [x]  Asset Issuer Community
- [x]  Redeeem Point Community
- [x]  Asset Factory
- [x]  Crypto Broker Identity
- [x]  Customers
- [ ]  Crypto Distribution
- [ ]  Device Privet

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina perfecto !!!

**Comment by jorgeejgonzalez** [comment]
La plataforma **CBP** actualmente tiene 4 sub apps:
1. **Crypto Broker Identity**
2. **Crypto Broker Community**
3. **Crypto Customer Identity**
4. **Crypto Customer Community**

La subapp **Customers** desaparecio al considerarse innecesaria en los ultimos analisis

**Comment by furszy** [comment]
La plataforma CCP actualmente tiene 2 sub apps:
1. **Intra user Identity**
2. **Intra user Community**

**Comment by arnaldos** [comment]
Para la plataforma DAP actualmente tiene 4 sub apps:
1. **Asset Factory**
2. **Asset issuer community**
3. **Reddem point community**
4. **Asset user comunity**

**Comment by arnaldos** [comment]
Un listado de sub App que también se deben definir sus identidades

1-Customer
2-Developer
3-Asset User
4-Redeem Point 
5-Asset Identity User
6-Asset Identity Issuer
7-Asset Redeem Point Identity
