### ISSUE TITLE
SUPERISSUE: Crear los elementos de 3d.fermat.org y sus versiones

### ISSUE THREAD

**Issue by jonathanborges3d** [bitDubai/fermat-graphic-design#139]
Tomando como referencia el esquema de fermat.org se realizarán los siguientes modelos para la versión tridimensional en 3d.fermat.org

Logos de las plataformas de Fermat:

1) COR #96 
2) PIP #97 
3) WPD #140 
4) CCP #141 
5) CCM #142 
6) BNP #143 
7) SHP #144 
8) DAP #145 
9) MKT #146 
10) CSH #147 
11) BNK #148 
12) CBP #149 
13) CDN #150 
14) DPN #151 

Super Capas:

1) P2P #184
2) BCH #185
3) OSA  #186

Fichas Descriptivas:

1) Concepto
2) Desarrollo
3) Producción
4) QA

**Comment by jonathanborges3d** [comment]
@Luis-Fernando-Molina Vamos a organizar el trabajo en los modelos de 3d.fermat.org desde aquí, de modo que se lleve un orden y control de los avances, ¿Qué te parece?

**Comment by Luis-Fernando-Molina** [comment]
Me parece muy bien

**Comment by jonathanborges3d** [comment]
Será necesario crear dos versiones de baja resolución de cada logo, una para vista a distancia larga y otra a distancia media de modo que se visualicen en forma dinámica aplicando Level Of Detail.
