### ISSUE TITLE
SUPER ISSUE: Manual de Imagen para BitDubai

### ISSUE THREAD

**Issue by Luis-Fernando-Molina** [bitDubai/fermat-graphic-design#14]
DAYANA SAID:

Es necesario comenzar a desarrollar un manual de Imagen Corporativa para BitDubai con la finalidad de estandarizar la línea gráfica sobre la que se estará trabajando. Será necesario definir:

```
Paleta de colores
Paleta tipográfica (fuentes empresariales)
Demás elementos gráficos necesarios
```

También se deben realizar mejoras al diseño del isologo para lograr una imagen más profesional y pulida, ya que el actual presenta problemas de reductibilidad y lectura.

Sería recomendable crear un documento digital con toda esta información. @arnaldos y yo estaremos trabajando directamente en esta asignación.

LUIS SAID:

Tengo algunas preguntas @m471c4 relacionado a este Issue.

1-Cuanto tiempo requiere esto?
2-Que impacto tiene esto sobre las cosas que ya están hechas? web site / presentaciones / APP / etc?

Antes de comenzar, tenemos como objetivo del equipo de diseño definir el conjunto de cosas que se van a realizar para estar bien organizados.

**Comment by m471c4** [comment]
Hola @Luis-Fernando-Molina. Esto se puede hacer relativamente rápido, estimo que en 3 días podría estar listo. 

El impacto si sería importante, ya que sería necesario replantear varias cosas (sustituir los logos, las tipografías, los tonos). Aunque llevaría trabajo, yo recomiendo hacerlo ahorita, ya que estamos en una etapa temprana, a hacerlo más adelante donde tengamos más elementos que modificar. También nos ayudará a optimizar el trabajo que se haya de aquí en adelante.

Ya lo separé por issues.

**Comment by Luis-Fernando-Molina** [comment]
@m471c4 de acuerdo, lo vamos a hacer sin lugar a duda. Estás segura de que están ya todos los issues relacionados a esto? 

Comoquiera antes de arrancar, acordamos en nuestra reunión profundizar el  inventario de issues de los distintos temas que hay dando vueltas.
