### ISSUE TITLE
Versión 3D del logo de Fermat WPD

### ISSUE THREAD

**Issue by jonathanborges3d** [bitDubai/fermat-graphic-design#140]
Viene del #139 

Version plana actual:

![wpd](https://cloud.githubusercontent.com/assets/13649739/10120897/604c77da-649c-11e5-8e1b-561a9e337b0e.jpg)

**Comment by jonathanborges3d** [comment]
@Luis-Fernando-Molina Primera versión 3D:

En el editor:

![f_wpd_8](https://cloud.githubusercontent.com/assets/13649739/10263430/d0f5bdae-69b8-11e5-9b44-190214fd9c86.jpg)

Versión en moneda:

![f_wpd_1](https://cloud.githubusercontent.com/assets/13649739/10263456/763a0bf8-69b9-11e5-8508-a0ac65ab6bc0.jpg)

![f_wpd_2](https://cloud.githubusercontent.com/assets/13649739/10263465/a9c4fe38-69b9-11e5-9ed6-266489ffbbff.jpg)

Version .json para 3d.fermat.org:

![f_wpd_5](https://cloud.githubusercontent.com/assets/13649739/10263470/c904817e-69b9-11e5-810c-7e685d6cef42.jpg)

![f_wpd_3](https://cloud.githubusercontent.com/assets/13649739/10263471/d4097f0c-69b9-11e5-8376-648a2a865bef.jpg)

![f_wpd_6](https://cloud.githubusercontent.com/assets/13649739/10263473/dca7fd1e-69b9-11e5-873f-f2337a921942.jpg)

**Comment by Luis-Fernando-Molina** [comment]
Excelente! :+1:

**Comment by jonathanborges3d** [comment]
@Luis-Fernando-Molina Versión actualizada de la moneda:
![f_wpd_9](https://cloud.githubusercontent.com/assets/13649739/10408755/0bff726a-6ed1-11e5-9bf3-ad1d830d5ed5.jpg)

![f_wpd_10](https://cloud.githubusercontent.com/assets/13649739/10408760/2a8c1fd0-6ed1-11e5-9660-653fca5c73d2.jpg)

**Comment by Luis-Fernando-Molina** [comment]
:+1:
