### ISSUE TITLE
Versión 3D del logo de Fermat CCP

### ISSUE THREAD

**Issue by jonathanborges3d** [bitDubai/fermat-graphic-design#141]
Viene del #139 

Versión plana actual:

![ccp](https://cloud.githubusercontent.com/assets/13649739/10120901/9a2bfaf2-649c-11e5-988c-7566f51254f1.jpg)

**Comment by jonathanborges3d** [comment]
@Luis-Fernando-Molina Primera Versión 3D:

En el editor:

![f_ccp_4](https://cloud.githubusercontent.com/assets/13649739/10265620/c3826ec6-6a01-11e5-9ab8-9d122333c002.jpg)

Versión en moneda:

![f_ccp_5](https://cloud.githubusercontent.com/assets/13649739/10265628/209e154c-6a02-11e5-87f8-925c9be6a4c2.jpg)

![f_ccp_6](https://cloud.githubusercontent.com/assets/13649739/10265630/3e2946e0-6a02-11e5-8f35-e659b0e7d0c9.jpg)

Versión .json para 3d.fermat.org:

![f_ccp_1](https://cloud.githubusercontent.com/assets/13649739/10265805/01e9975a-6a09-11e5-8fc7-a2ad8cda2749.jpg)

![f_ccp_2](https://cloud.githubusercontent.com/assets/13649739/10265809/3fb6187e-6a09-11e5-9d19-8ae7e2aa49f9.jpg)

![f_ccp_3](https://cloud.githubusercontent.com/assets/13649739/10265814/760380ec-6a09-11e5-965d-79ba63030645.jpg)

**Comment by Luis-Fernando-Molina** [comment]
:+1:

**Comment by Rart3001** [comment]
Vamos a tener que comprar una impresora 3D para hacer esas monedas están quedando geniales.

**Comment by Luis-Fernando-Molina** [comment]
yeah baby!

**Comment by jonathanborges3d** [comment]
@Rart3001 Gracias Roberto! Si, sería genial tenerlas en físico.

**Comment by jonathanborges3d** [comment]
@Luis-Fernando-Molina Versión actualizada de la moneda:

![f_ccp_7](https://cloud.githubusercontent.com/assets/13649739/10408764/5e1e9a6c-6ed1-11e5-8ba4-73294de0895c.jpg)

![f_ccp_8](https://cloud.githubusercontent.com/assets/13649739/10408770/7e3fbf2e-6ed1-11e5-9003-adfbc2f825cc.jpg)

**Comment by Luis-Fernando-Molina** [comment]
:+1:
