### ISSUE TITLE
Versión 3D del logo de Fermat CCM

### ISSUE THREAD

**Issue by jonathanborges3d** [bitDubai/fermat-graphic-design#142]
Viene del #139

Versión plana actual:

![ccm](https://cloud.githubusercontent.com/assets/13649739/10120903/ce53546a-649c-11e5-8549-61089d52d2a3.jpg)

**Comment by jonathanborges3d** [comment]
@Luis-Fernando-Molina Primera Versión 3D:

En el editor:

![f_ccm_1](https://cloud.githubusercontent.com/assets/13649739/10356102/4e844358-6d3d-11e5-9d36-4710117d13c3.jpg)

La versión en moneda está sujeta a los cambios que se aprueben en el #97 para todos los logos, por eso aún no la posteo.

Versión .json para 3d.fermat.org

![f_ccm_2](https://cloud.githubusercontent.com/assets/13649739/10356133/9f9063da-6d3d-11e5-9a62-585932c2a899.jpg)

![f_ccm_3](https://cloud.githubusercontent.com/assets/13649739/10356166/ef37149c-6d3d-11e5-97f1-68febd866ccd.jpg)

![f_ccm_4](https://cloud.githubusercontent.com/assets/13649739/10356173/0bfb1f1a-6d3e-11e5-8b8f-57c8a0ea4aea.jpg)

**Comment by Luis-Fernando-Molina** [comment]
:+1:

**Comment by jonathanborges3d** [comment]
@Luis-Fernando-Molina Versión en moneda:

![f_ccm_5](https://cloud.githubusercontent.com/assets/13649739/10408775/a52e2eea-6ed1-11e5-961d-f2d2cfa9f43d.jpg)

![f_ccm_6](https://cloud.githubusercontent.com/assets/13649739/10408779/da3bf16c-6ed1-11e5-90d3-fd76ca03b9d1.jpg)

**Comment by Luis-Fernando-Molina** [comment]
:+1:

**Comment by jonathanborges3d** [comment]
Actualización del render de la moneda para los covers de hangouts

![cover_ccm](https://cloud.githubusercontent.com/assets/13649739/10566541/c98595ec-75b3-11e5-8620-d9131c6a1fa3.jpg)
