### ISSUE TITLE
Versión 3D del logo de Fermat BNP

### ISSUE THREAD

**Issue by jonathanborges3d** [bitDubai/fermat-graphic-design#143]
Viene del #139 

Versión plana actual:

![bnp](https://cloud.githubusercontent.com/assets/13649739/10120906/0ca722dc-649d-11e5-8b56-7c66bac26be5.jpg)

**Comment by jonathanborges3d** [comment]
@Luis-Fernando-Molina Versión en 3D:

En el editor:

![f_bnp_1](https://cloud.githubusercontent.com/assets/13649739/10470044/0c7dbaac-71d4-11e5-878a-993f79820ec3.jpg)

Versión en moneda:

![f_bnp_2](https://cloud.githubusercontent.com/assets/13649739/10470075/2bfbd260-71d4-11e5-966c-548f1f0afabf.jpg)

![f_bnp_3](https://cloud.githubusercontent.com/assets/13649739/10470092/43df3b6a-71d4-11e5-865b-53e682732b60.jpg)

Versión .json para 3d.fermat.org:

![f_bnp_4](https://cloud.githubusercontent.com/assets/13649739/10470106/5f337f3e-71d4-11e5-9efa-38e8a95be2cf.jpg)

![f_bnp_5](https://cloud.githubusercontent.com/assets/13649739/10470126/7a6eca10-71d4-11e5-8718-0750c9da9e22.jpg)

![f_bnp_6](https://cloud.githubusercontent.com/assets/13649739/10470168/bbcc536a-71d4-11e5-96c4-380a064663ed.jpg)

**Comment by Luis-Fernando-Molina** [comment]
:+1:  aprobado

**Comment by jonathanborges3d** [comment]
Actualización del render de la moneda para los covers de hangouts

![cover_bnp](https://cloud.githubusercontent.com/assets/13649739/10566484/e0ee5072-75b1-11e5-8789-7f69072b22e1.jpg)
