### ISSUE TITLE
Versión 3D del logo de Fermat SHP

### ISSUE THREAD

**Issue by jonathanborges3d** [bitDubai/fermat-graphic-design#144]
Viene del #139 

Versión plana actual:

![shp](https://cloud.githubusercontent.com/assets/13649739/10120907/2e9aa378-649d-11e5-8519-5a8288dc06e1.jpg)

**Comment by jonathanborges3d** [comment]
@Luis-Fernando-Molina Versión 3d:

En el editor:

![f_shp_1](https://cloud.githubusercontent.com/assets/13649739/10470417/d43ba55c-71d6-11e5-8c77-8028ccd30f76.jpg)

Versión en moneda:

![f_shp_2](https://cloud.githubusercontent.com/assets/13649739/10470431/059be1c0-71d7-11e5-9f09-36d10393c160.jpg)

![f_shp_3](https://cloud.githubusercontent.com/assets/13649739/10470441/212070d2-71d7-11e5-992c-9f1def233ea6.jpg)

Versión .json para 3d.fermat.org:

![f_shp_4](https://cloud.githubusercontent.com/assets/13649739/10470566/f574f1dc-71d7-11e5-9e12-8a90adea4c58.jpg)

![f_shp_5](https://cloud.githubusercontent.com/assets/13649739/10470576/0f3ddb10-71d8-11e5-8c17-ed881f1efd0e.jpg)

![f_shp_6](https://cloud.githubusercontent.com/assets/13649739/10470588/23f79370-71d8-11e5-9eca-3cd6c25c0892.jpg)

**Comment by Luis-Fernando-Molina** [comment]
:+1:

**Comment by jonathanborges3d** [comment]
Actualización del render de la moneda para los covers de hangouts

![cover_shp](https://cloud.githubusercontent.com/assets/13649739/10567197/7100917a-75c6-11e5-96f3-68eb86232e42.jpg)
