### ISSUE TITLE
Versión 3D del logo de Fermat DAP

### ISSUE THREAD

**Issue by jonathanborges3d** [bitDubai/fermat-graphic-design#145]
Viene del #139 

Versión plana actual:

![dap](https://cloud.githubusercontent.com/assets/13649739/10120911/647d7574-649d-11e5-97ce-85906c1567ea.jpg)

**Comment by jonathanborges3d** [comment]
@Luis-Fernando-Molina Versión 3d:

En el editor:

![f_dap_1](https://cloud.githubusercontent.com/assets/13649739/10473256/35ca1594-71f3-11e5-9d6a-dae05b5ae838.jpg)

Versión en moneda:

![f_dap_2](https://cloud.githubusercontent.com/assets/13649739/10473262/57407c22-71f3-11e5-9106-f538ccfcc4c0.jpg)

![f_dap_3](https://cloud.githubusercontent.com/assets/13649739/10473277/7b9871c4-71f3-11e5-8dc6-46ed2f4b7015.jpg)

Versión .json para 3d.fermat.org:

![f_dap_4](https://cloud.githubusercontent.com/assets/13649739/10473290/a6297aaa-71f3-11e5-8a56-3ae2ea17e202.jpg)

![f_dap_5](https://cloud.githubusercontent.com/assets/13649739/10473299/bc3a454a-71f3-11e5-9400-8f005e4d2172.jpg)

![f_dap_6](https://cloud.githubusercontent.com/assets/13649739/10473311/d5b2745c-71f3-11e5-8760-de69243b2e74.jpg)

**Comment by Luis-Fernando-Molina** [comment]
:+1:

**Comment by jonathanborges3d** [comment]
Actualización del render de la moneda para los covers de hangouts

![cover_dap](https://cloud.githubusercontent.com/assets/13649739/10566882/87abd4ac-75bc-11e5-8500-13abee547e9c.jpg)

**Comment by Luis-Fernando-Molina** [comment]
:+1:
