### ISSUE TITLE
Versión 3D del logo de Fermat MKT

### ISSUE THREAD

**Issue by jonathanborges3d** [bitDubai/fermat-graphic-design#146]
Viene del #139 

Versión plana actual:

![mkt](https://cloud.githubusercontent.com/assets/13649739/10120912/7551adc0-649d-11e5-9993-18ce0760da8a.jpg)

**Comment by jonathanborges3d** [comment]
@Luis-Fernando-Molina Versión en 3d:

En el editor:

![f_mkt_1](https://cloud.githubusercontent.com/assets/13649739/10499848/2c9ef174-729d-11e5-94f9-2720ef548a80.jpg)

Versión en moneda:

![f_mkt_2](https://cloud.githubusercontent.com/assets/13649739/10499892/89ebf7be-729d-11e5-8bd9-21f7243dc110.jpg)

![f_mkt_3](https://cloud.githubusercontent.com/assets/13649739/10499941/fefd229e-729d-11e5-8ac1-a409329394c4.jpg)

Versión en .json para 3d.fermat.org:

![f_mkt_4](https://cloud.githubusercontent.com/assets/13649739/10499906/a4ea19ba-729d-11e5-85b6-dcb2c565a1a1.jpg)

![f_mkt_5](https://cloud.githubusercontent.com/assets/13649739/10499914/b90c594e-729d-11e5-85be-0920264d0049.jpg)

![f_mkt_6](https://cloud.githubusercontent.com/assets/13649739/10499919/c22c034e-729d-11e5-99af-49ce26e7c576.jpg)

**Comment by jonathanborges3d** [comment]
Actualización del render de la moneda para los covers de hangouts

![cover_mkt](https://cloud.githubusercontent.com/assets/13649739/10567069/70038db2-75c2-11e5-8dd7-5c8b06bdc94c.jpg)

**Comment by jonathanborges3d** [comment]
@Luis-Fernando-Molina Alguna sugerencia para éste modelo o ya puede quedar así?

**Comment by Luis-Fernando-Molina** [comment]
:+1:
