### ISSUE TITLE
Versión 3D del logo de Fermat CSH

### ISSUE THREAD

**Issue by jonathanborges3d** [bitDubai/fermat-graphic-design#147]
Viene del #139 

Versión plana actual:

![csh](https://cloud.githubusercontent.com/assets/13649739/10120919/c83867fe-649d-11e5-9ed8-256766f02df9.jpg)

**Comment by jonathanborges3d** [comment]
@Luis-Fernando-Molina Versión 3d:

En el editor:

![f_csh_1](https://cloud.githubusercontent.com/assets/13649739/10561684/1f623124-74ff-11e5-9c23-89cda6fcc60b.jpg)

Versión en moneda (Próxima a actualizarse con el fondo que se decida en el #187 )

![f_csh_2](https://cloud.githubusercontent.com/assets/13649739/10561688/4d26f5cc-74ff-11e5-8491-e7837d2ba80b.jpg)

![f_csh_3](https://cloud.githubusercontent.com/assets/13649739/10561690/63bdcd9c-74ff-11e5-85b5-7a1553178b79.jpg)

Versión .json para 3d.fermat.org:

![f_csh_4](https://cloud.githubusercontent.com/assets/13649739/10561692/8b4a0b64-74ff-11e5-9a8a-bf65742e34c8.jpg)

![f_csh_5](https://cloud.githubusercontent.com/assets/13649739/10561695/992e5258-74ff-11e5-95ee-60ef254cf20e.jpg)

![f_csh_6](https://cloud.githubusercontent.com/assets/13649739/10561698/a9683bd4-74ff-11e5-8303-49b7c704e4ca.jpg)

**Comment by Luis-Fernando-Molina** [comment]
:+1:

**Comment by jonathanborges3d** [comment]
Actualización del render de la moneda para los covers de hangouts

![cover_csh](https://cloud.githubusercontent.com/assets/13649739/10566715/9c34047a-75b8-11e5-8d31-e775a393fb52.jpg)
