### ISSUE TITLE
Versión 3D del logo de Fermat BNK

### ISSUE THREAD

**Issue by jonathanborges3d** [bitDubai/fermat-graphic-design#148]
Viene del #139 

Versión plana actual:

![bnk](https://cloud.githubusercontent.com/assets/13649739/10120920/cc865a46-649d-11e5-9a68-174627851637.jpg)

**Comment by jonathanborges3d** [comment]
@Luis-Fernando-Molina Versión 3d:

En el editor:

![f_bnk_1](https://cloud.githubusercontent.com/assets/13649739/10598279/60396096-76c1-11e5-9139-6860f1a2c4f0.jpg)

Versión en moneda (Covers de Hangouts):

![f_bnk_2](https://cloud.githubusercontent.com/assets/13649739/10598288/76134e9a-76c1-11e5-8ec3-81a6a59b29bc.jpg)

Versión en .json para 3d.fermat.org:

![f_bnk_3](https://cloud.githubusercontent.com/assets/13649739/10598334/c610cca6-76c1-11e5-9c21-d43ffb1c8ab3.jpg)

![f_bnk_4](https://cloud.githubusercontent.com/assets/13649739/10598374/261f0806-76c2-11e5-904e-993dd8f5f538.jpg)

![f_bnk_5](https://cloud.githubusercontent.com/assets/13649739/10598401/66f951f6-76c2-11e5-9f2c-1e03add7989f.jpg)

**Comment by Luis-Fernando-Molina** [comment]
:+1:
