### ISSUE TITLE
Versión 3D del logo de Fermat CBP

### ISSUE THREAD

**Issue by jonathanborges3d** [bitDubai/fermat-graphic-design#149]
Viene del #139 

Versión plana actual:

![cbp](https://cloud.githubusercontent.com/assets/13649739/10120925/1bac2362-649e-11e5-883a-ba29ca66c0ef.jpg)

**Comment by jonathanborges3d** [comment]
@Luis-Fernando-Molina Versión 3d:

En el editor:

![f_cbp_1](https://cloud.githubusercontent.com/assets/13649739/10616525/5154dcae-772f-11e5-84a0-fd1047ae68f2.jpg)

Versión en moneda (Covers de Hangouts):

![f_cbp_2](https://cloud.githubusercontent.com/assets/13649739/10616537/5ed8914a-772f-11e5-81c2-eed116ed1265.jpg)

Versión .json para 3d.fermat.org:

![f_cbp_3](https://cloud.githubusercontent.com/assets/13649739/10616628/d48b34ec-772f-11e5-8f21-d854fb7b5b79.jpg)

![f_cbp_4](https://cloud.githubusercontent.com/assets/13649739/10616706/532476f6-7730-11e5-8e44-0d7799967cfd.jpg)

![f_cbp_5](https://cloud.githubusercontent.com/assets/13649739/10616710/5c5af286-7730-11e5-9049-9b33f5b95fe6.jpg)

**Comment by Luis-Fernando-Molina** [comment]
:+1:
