### ISSUE TITLE
Versión 3D del logo de Fermat CDN

### ISSUE THREAD

**Issue by jonathanborges3d** [bitDubai/fermat-graphic-design#150]
Viene del #139 

Versión plana actual:

![cdn](https://cloud.githubusercontent.com/assets/13649739/10120931/4e031b18-649e-11e5-8bcc-6d0436797600.jpg)

**Comment by jonathanborges3d** [comment]
@Luis-Fernando-Molina Versión 3d

En el editor:

![f_cdn_1](https://cloud.githubusercontent.com/assets/13649739/10623740/90c2f37c-775b-11e5-9200-408b0ae8efcb.jpg)

Versión en moneda (Covers de Hangouts):

![f_cdn_2](https://cloud.githubusercontent.com/assets/13649739/10623801/210bca9e-775c-11e5-8aa0-ecbccc996ce5.jpg)

Versión .json para 3d.fermat.org:

![f_cdn_3](https://cloud.githubusercontent.com/assets/13649739/10623892/fe42b7b0-775c-11e5-9690-a6d2a8761400.jpg)

![f_cdn_4](https://cloud.githubusercontent.com/assets/13649739/10623896/05c417b8-775d-11e5-9e60-28a55dc816de.jpg)

![f_cdn_5](https://cloud.githubusercontent.com/assets/13649739/10623901/14547318-775d-11e5-9e2e-45e5b1abc4f4.jpg)

**Comment by Luis-Fernando-Molina** [comment]
:+1:
