### ISSUE TITLE
Versión 3D del logo de Fermat DPN

### ISSUE THREAD

**Issue by jonathanborges3d** [bitDubai/fermat-graphic-design#151]
Viene del #139 

Versión plana actual:

![dpn](https://cloud.githubusercontent.com/assets/13649739/10120933/7937e6ba-649e-11e5-8717-3b1528c67735.jpg)

**Comment by jonathanborges3d** [comment]
@Luis-Fernando-Molina Versión 3d:

En el editor:

![f_dpn_1](https://cloud.githubusercontent.com/assets/13649739/10652940/62533172-7824-11e5-9fba-ca427388fb67.jpg)

Versión en moneda (Covers de Hangouts):

![f_dpn_2](https://cloud.githubusercontent.com/assets/13649739/10653125/4f300c9e-7826-11e5-895e-679ce72f32b3.jpg)

Versión .json para 3d.fermat.org

![f_dpn_3](https://cloud.githubusercontent.com/assets/13649739/10653776/9be45d78-782c-11e5-9f8d-32e1348987e4.jpg)

![f_dpn_4](https://cloud.githubusercontent.com/assets/13649739/10653787/ae8732f2-782c-11e5-827a-6e990329e033.jpg)

![f_dpn_5](https://cloud.githubusercontent.com/assets/13649739/10653792/b8b1f492-782c-11e5-90ae-747503a44d09.jpg)

Con éste modelo termino los logos de las plataformas de Fermat, me faltan por modelar los de las super capas, me gustaría saber si usaremos el mismo modelo de moneda o variaremos para las 3 restantes, por los covers de hangouts.

**Comment by Luis-Fernando-Molina** [comment]
:+1:

**Comment by jonathanborges3d** [comment]
@Luis-Fernando-Molina Y qué opinas sobre lo que te pregunté al final del post?

**Comment by Luis-Fernando-Molina** [comment]
el mismo modelo.
