### ISSUE TITLE
Crear icono para la Wallet Factory

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#156]
Viene de #155 

**Wallet Factory** 

se refiere a una fabrica de billeteras.

**Requisitos**

Archivo PNG de 32 bits (alpha)
Tamaño: 512 x 512 píxeles
Tamaño máximo del archivo: 1024 KB

Una vez elegido el icono, es necesario generar los tamaños, en **.PNG** para aplicarlos en lo siguientes:

**IC launcher**:

48 × 48 px (mdpi)
72 × 72 px (hdpi)
96 × 96 px (xhdpi)
144 × 144 px (xxhdpi)
192 × 192 px (xxxhdpi)
512 × 512 px (Wallet store)

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina Versión 1 icono Wallet Factory

![icono-wallet-factory](https://cloud.githubusercontent.com/assets/13594347/10227712/c108e2da-6838-11e5-85ec-efb214f540a9.jpg)
![icono-wallet-factory2](https://cloud.githubusercontent.com/assets/13594347/10227713/c10af386-6838-11e5-9464-a33ec3ffcdf2.jpg)

**Comment by Luis-Fernando-Molina** [comment]
El icono debe poder interpretarse sin palabras para que sea apropiado.

**Comment by arnaldos** [comment]
perfecto !!! ya trabajo en otra versión !!!

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina icono para la crypto customer wallet

Versión 2

![icono-wallet-factory5](https://cloud.githubusercontent.com/assets/13594347/10300943/f4fd8e60-6bc6-11e5-99cd-5140e62f5219.jpg)
![icono-wallet-factory6](https://cloud.githubusercontent.com/assets/13594347/10300944/f501e14a-6bc6-11e5-9b0e-666d4b28df88.jpg)

Versión 3

![icono-wallet-factory3](https://cloud.githubusercontent.com/assets/13594347/10300964/33d515b8-6bc7-11e5-867a-2e4058fac789.jpg)
![icono-wallet-factory4](https://cloud.githubusercontent.com/assets/13594347/10300965/33dc0d28-6bc7-11e5-8bd2-4e946a9e726f.jpg)

**Comment by Luis-Fernando-Molina** [comment]
Hasta ahora la version 3, aunque sigue estando poco claro que se trata de una fabrica. Estoy viendo que todos los iconos estan saliendo bastante abstractos. Deberiamos tener iconos mas concretos tambien.

Mira en este ejemplo el Image Editor, como con un icono explícito sabes exactamente de que se trata la aplicación. Cuando digo que tengamos una identidad propia en cada wallet o sub app, me refiero tambien a que los iconos debieran abarcar todo el rango, entre concretos y abstractos si queremos dar una imagen de diversidad. @m471c4 fijate en esto vos también por favor. 

![editor](https://cloud.githubusercontent.com/assets/9479367/10308804/b6216d7c-6c0e-11e5-9969-f6a01ff4d70c.jpg)

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina comparto nueva versión de la factory 

Vresión 4
![icono-wallet-factory7](https://cloud.githubusercontent.com/assets/13594347/10441201/15f7da46-7110-11e5-95f7-e52e6ac2e899.jpg)
![icono-wallet-factory8](https://cloud.githubusercontent.com/assets/13594347/10441202/15fb7f3e-7110-11e5-828e-864a52408021.jpg)

**Comment by Luis-Fernando-Molina** [comment]
Arnaldo , el icono esta muy lindo, pero no hay manera de deducir a partir de el que es de una fabrica de wallets. Busca el icono original del wallet factory, el que existia antes de que entraras vos a bitDubai y fijate como dentro de todo te muestra que es una fabrica de wallets. Tomalo como base.

**Comment by arnaldos** [comment]
perfecto luis !!! ya voy a revisar el icono que me comentas,  para replantearlo en esta wallet !

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina en esta versión me enfoque en fusionar una fabrica con una wallet para hacer énfasis al concepto. usando lineas simples que nos permiten identificar de forma rápida el producto.

versión 5

![icono-wallet-factory9](https://cloud.githubusercontent.com/assets/13594347/10444490/0d75dafa-7131-11e5-82b7-a07e0478e09f.jpg)
![icono-wallet-factory10](https://cloud.githubusercontent.com/assets/13594347/10444491/0d783494-7131-11e5-9f22-c30bc54f6d18.jpg)

**Comment by Luis-Fernando-Molina** [comment]
Probemos con algo mas parecido al "Image Editor" que está en la imagen de mas arriba. Me refiero a un dibujo no tan abstracto, sino algo explícito como los pinceles que están ahi. Me gustan los abstractos pero no podemos tener solo de ese tipo.

**Comment by arnaldos** [comment]
Perfecto!!! voy a probar como enlazar todos los elementos, para el estilo gráfico que me sugieres!!! :+1:

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina nueva versión basados en la repesentacion de una factory que lleva en la parte posterior una wallet para indicar, que la aplicación nos permite crear o fabricar una wallet 

Versión 6

![icono-wallet-factory](https://cloud.githubusercontent.com/assets/13594347/11048566/d7584594-870a-11e5-92ba-388224a5fef8.jpg)

![sreenshot-factory](https://cloud.githubusercontent.com/assets/13594347/11048590/04b6e07c-870b-11e5-96a4-2490928e52a4.png)

**Comment by Luis-Fernando-Molina** [comment]
Version 6 de @arnaldos :+1:

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina Perfecto !!! ya genero el banner para esta wallet y así cerramos el caso !!
