### ISSUE TITLE
Crear banner de presentación para la Wallet Factory

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#157]
Viene de #155

El Banner de presentación o gráfico de funciones es una potente herramienta que permite mostrar tus recursos creativos y atraer a los usuarios. Este sera publicado en la Wallet Store.

Requisitos

Archivo JPEG o PNG de 24 bits (no alpha)
Tamaño: 1024x500 píxeles

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina Banner de Graficos de la Wallet Factory

Versión 1 

![sreenshot--wallet-factory](https://cloud.githubusercontent.com/assets/13594347/11155597/a989da9a-8a18-11e5-9127-25160ae74f5b.jpg)

![banner-wallet-factory](https://cloud.githubusercontent.com/assets/13594347/11155598/a992d960-8a18-11e5-9570-df1131548f3a.jpg)

Versión 2

![sreenshot--wallet-factory-2](https://cloud.githubusercontent.com/assets/13594347/11155602/b44bc088-8a18-11e5-847c-f8f62685984a.jpg)

![banner-wallet-factory 2](https://cloud.githubusercontent.com/assets/13594347/11155603/b476f1ea-8a18-11e5-9f06-1693eecb01a6.jpg)

**Comment by Luis-Fernando-Molina** [comment]
@arnaldos el banner esta excelente, pero aca sucede lo miso que te habia dicho antes. Por mas que esté la palabra wallet , no es una wallet sino una sub app (mira en fermat.org) con lo cual no se instala desde la wallet store. Me imagino que el banner puede servir para darle una onda específica a la applicacion, y hasta lo pudiéramos poner en el home de la misma para que le levante el nivel. Vamos a hacer eso para aprovechar que ya lo hiciste.

**Comment by Luis-Fernando-Molina** [comment]
:+1:

**Comment by arnaldos** [comment]
vale perfecto luis !
