### ISSUE TITLE
Crear icono para la Wallet Publisher

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#158]
Viene del #155 

**Wallet Publisher**

es la aplicación que permite publicar una wallet.

**Requisitos**

Archivo PNG de 32 bits (alpha)
Tamaño: 512 x 512 píxeles
Tamaño máximo del archivo: 1024 KB

Una vez elegido el icono, es necesario generar los tamaños, en **.PNG** para aplicarlos en lo siguientes:

**IC launcher**:

48 × 48 px (mdpi)
72 × 72 px (hdpi)
96 × 96 px (xhdpi)
144 × 144 px (xxhdpi)
192 × 192 px (xxxhdpi)
512 × 512 px (Wallet store)

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina primera versión del icono de la wallet publisher

![icono-wallet-publisher1](https://cloud.githubusercontent.com/assets/13594347/10382260/e0a2014a-6deb-11e5-8eaa-21b673ce3073.jpg)
![icono-wallet-publisher2](https://cloud.githubusercontent.com/assets/13594347/10382261/e0b533fa-6deb-11e5-8e20-51d1a7626e98.jpg)

**Comment by Luis-Fernando-Molina** [comment]
segunda?

**Comment by arnaldos** [comment]
Aun estoy trabajando en ello, apenas la termine la subo !!! quería ir mostrándote los avances sobre esta wallet

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina  te comparto 2 versiones mas de la publisher 

Versión 2

![icono-wallet-publisher3](https://cloud.githubusercontent.com/assets/13594347/10441126/5f87c6b8-710f-11e5-9a25-9b96f2e81dc8.jpg)
![icono-wallet-publisher4](https://cloud.githubusercontent.com/assets/13594347/10441127/5f8d0cea-710f-11e5-8d29-adb8368b0b43.jpg)

Versión 3

![icono-wallet-publisher6](https://cloud.githubusercontent.com/assets/13594347/10441139/79360a52-710f-11e5-9b9b-9f0b698dc6bf.jpg)
![icono-wallet-publisher5](https://cloud.githubusercontent.com/assets/13594347/10441140/793aa710-710f-11e5-8566-60c488bce2eb.jpg)

**Comment by Luis-Fernando-Molina** [comment]
La publisher es lo que lleva una wallet de la factory a la store. Fijate si eso te sirve. La version 2 es la que mas me gusta hasta ahora. Acordate que no solo tenemos que hacer iconos abstractos, creo que te mostré en otro caso ejemplos de iconos como objetos reales.

**Comment by jurene22** [comment]
![icono para la asset user wallet 133](https://cloud.githubusercontent.com/assets/15174317/10942378/14182044-82e2-11e5-87c3-a2968b939a1b.png)
@Luis-Fernando-Molina aporte para Icon wallet publisher
![vista target](https://cloud.githubusercontent.com/assets/15174317/10942423/44a14542-82e2-11e5-90bb-3788d19e1b9d.png)

**Comment by Luis-Fernando-Molina** [comment]
No logro deducir de que se trata a partir del icono

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina comparto 2 versiones que parten del mismo concepto la variante entre si es el color. El enfoque que se le da al icono es partiendo de una flecha que envuelve a varias billeteras, en dirección hacia arriba para dar la sensación que se están publicando en algún sitio.

Versión 1

![icono-wallet-publisher7](https://cloud.githubusercontent.com/assets/13594347/11044823/555c1b6a-86f6-11e5-8eb6-7160b26dfd75.jpg)

![sreenshot-editable1](https://cloud.githubusercontent.com/assets/13594347/11044822/552135b8-86f6-11e5-92e7-849f5c8aa359.png)

Versión 2

![icono-wallet-publisher8](https://cloud.githubusercontent.com/assets/13594347/11045017/391f1f14-86f7-11e5-8e89-749bf1ca7bca.jpg)

![sreenshot-editable2](https://cloud.githubusercontent.com/assets/13594347/11044926/d4b18620-86f6-11e5-87bc-1378a9549ef7.png)

**Comment by Luis-Fernando-Molina** [comment]
Version 1 de @arnaldos :+1:

**Comment by jurene22** [comment]
![icon_wallet_publisher_issue158_version 2 y 3](https://cloud.githubusercontent.com/assets/15174317/11066259/a4028e18-8799-11e5-9b43-6ce5558ec708.png)
![vista target](https://cloud.githubusercontent.com/assets/15174317/11066258/a401fa84-8799-11e5-8164-b00479b6b3e7.png)
@Luis-Fernando-Molina bocetos

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina listo !! genero el banner y cerramos el caso !!
