### ISSUE TITLE
Crear banner de presentación para la Wallet Publisher

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#159]
Viene del #155

El Banner de presentación o gráfico de funciones es una potente herramienta que permite mostrar tus recursos creativos y atraer a los usuarios. Este sera publicado en la Wallet Store.

Requisitos

Archivo JPEG o PNG de 24 bits (no alpha)
Tamaño: 1024x500 píxeles

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina banner de gráficos Wallet Publisher

![sreenshot--wallet-publisher](https://cloud.githubusercontent.com/assets/13594347/11161639/938b1bdc-8a54-11e5-91f7-408bd35188ae.jpg)

![banner-wallet-publisher](https://cloud.githubusercontent.com/assets/13594347/11161640/9391da08-8a54-11e5-83a1-9798ccc8dea9.jpg)

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina Ajuste de la tipografía, se elimino la sombra de la misma le da mayor limpieza a la pieza.

![banner-wallet-publisher2](https://cloud.githubusercontent.com/assets/13594347/11161718/f6336760-8a56-11e5-83ae-8ada57f18a5b.jpg)

**Comment by Luis-Fernando-Molina** [comment]
Te digo lo mismo que para el caso https://github.com/bitDubai/fermat-graphic-design/issues/157#issuecomment-156538224

:+1:

**Comment by arnaldos** [comment]
ok de igual forma subo los fuentes por si alguien los necesita usar

**Comment by arnaldos** [comment]
cierro los casos relacionados ?
