### ISSUE TITLE
Mejora y refinamiento del isologo de BitDubai

### ISSUE THREAD

**Issue by m471c4** [bitDubai/fermat-graphic-design#16]
Viene del #14 

Es necesario hacer algunas mejoras en el isologo de BitDubai para evitar algunos problemas de ruido, tal como se muestra en la imagen (está resaltado en rojo).

![isologo_correc](https://cloud.githubusercontent.com/assets/13468350/9077758/af19ee08-3afb-11e5-83bd-6ef81c50926b.png)

En la medida que se resuelvan estos detalles, será necesario reticular el isologo y determinar el tamaño mínimo permitido.

**Comment by Luis-Fernando-Molina** [comment]
@m471c4 @arnaldos  les dí permisos para que ustedes mismos puedan :+1: 

1.Etiquetar los Issues con un label
2.Asignarlos a un Milestone
3.Asignarlos a un recurso.

No hace falta que lo asignen a un recurso todavía, primero veamos cuales son todos los issues y luego lo repartimos.

**Comment by m471c4** [comment]
Buenos días, a continuación el primer boceto del isologo de BitDubai con las mejoras planteadas.

Se mejoró el tamaño de la tipografía, para lograr que resaltara más. La palabra árabe se integró a la raíz "bit", fundiendo el punto (que la hace "bitcoin", en lugar de "inception") con el punto de la i. También se modificó ligeramente la paleta de colores. La fuente empleada fue la Century Gothic, que es muy similar a la anterior para mantener la misma línea gráfica.

![new_logo](https://cloud.githubusercontent.com/assets/13468350/9219134/816e1b62-40a2-11e5-9d5b-8bd2b0d6ee3c.png)

También se hizo una ligera modificación tipográfica en la t de bit, para darle más personalidad. Espero comentarios, sugerencias y críticas.

**Comment by m471c4** [comment]
@Luis-Fernando-Molina ¿tenemos alguna razón social? De ser así, quisiera incluirla en una acepción del isologo.

**Comment by Luis-Fernando-Molina** [comment]
@m471c4 no tenemos, pero debiera ser "bitDubai".

La parte bit me gusta, la de Dubai me parece muy gruesa. Aunque puede ser porque esté acostumbrado a la anterior. Igual me parece muy gruesa.

Probá poner la palabra en árabe un poco mas chica, manteniendo el eje en el punto de la i, a ver como queda please.

**Comment by m471c4** [comment]
@Luis-Fernando-Molina ¡seguro! probaré y lo subo acá.

**Comment by m471c4** [comment]
@Luis-Fernando-Molina, acá el isologo con la palabra árabe más chica.

![new_logo_v3](https://cloud.githubusercontent.com/assets/13468350/9220451/7dc19a98-40ac-11e5-8b97-4dde9bacbc2c.png)

No quisiera disminuirla más ya que será un problema a la hora de hacer reducciones.

**Comment by Luis-Fernando-Molina** [comment]
@m471c4 bien, probamos con Dubai sin negritas?

**Comment by arnaldos** [comment]
Hola @m471c4 leyendo los comentarios, creo que para mantener el texto de la palabra Dubai sin que se vea un bloque muy fuerte, rebajando el tono de color un 10% o 20% menos, se puede llegar a que la palabra sea un poco mas ligera, sin cambiar la tipografía.

**Comment by m471c4** [comment]
Buenos días, adjunto 4 versiones. La primera no tiene mayores cambios que la palabra árabe más grande. En la segunda aclaré la palabra Dubai, siguiendo la recomendación de @arnaldos. En la tercera disminuí el grosor de la palabra Dubai, pero sin que quedara tan delgado como "bit" y en la 4ta cambié la tipografía de la palabra Dubai por la Caviar Dreams pero con algunas modificaciones para estilizarla. 

Finalmente me parece que la mejor es la última versión (con la tipografía Caviar Dreams modificada). Espero sus comentarios

![bitdubailogo1](https://cloud.githubusercontent.com/assets/13468350/9241044/f508c7b2-4137-11e5-90b4-287451048a1c.png)
![bitdubailogo2](https://cloud.githubusercontent.com/assets/13468350/9241046/f8c7a81e-4137-11e5-885f-617ccb97501b.png)
![bitdubailogo3](https://cloud.githubusercontent.com/assets/13468350/9241049/fd4c667c-4137-11e5-8c69-8110e1dde936.png)
![bitdubailogo4](https://cloud.githubusercontent.com/assets/13468350/9241052/030489aa-4138-11e5-9168-87c66c50c604.png)

**Comment by Luis-Fernando-Molina** [comment]
la 4ta es la que me gusta mas :+1:

**Comment by arnaldos** [comment]
totalmente de acuerdo !!! apuesto por la cuarta versión !!

**Comment by m471c4** [comment]
Bien, en ese caso nos quedamos con esa. Se da por cerrado este Issue.
