### ISSUE TITLE
Crear icono para la Wallet Store

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#160]
Viene del #155

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina  primeros bocetos para la wallet store

Versión 1
![icono wallet store-05](https://cloud.githubusercontent.com/assets/13594347/10227304/5b7fe118-6836-11e5-8e76-b28ddf347d73.jpg)
![icono wallet store-06](https://cloud.githubusercontent.com/assets/13594347/10227305/5bf81ea8-6836-11e5-855a-1f4856c06840.jpg)

Versión 2
![icono wallet store-03](https://cloud.githubusercontent.com/assets/13594347/10227319/71206772-6836-11e5-8b95-a152db209ddc.jpg)
![icono wallet store-04](https://cloud.githubusercontent.com/assets/13594347/10227320/714d0606-6836-11e5-80f1-948de0397bea.jpg)

Versión 3
![icono wallet store-07](https://cloud.githubusercontent.com/assets/13594347/10227326/7ef16298-6836-11e5-895a-801af1ea4315.jpg)
![icono wallet store-08](https://cloud.githubusercontent.com/assets/13594347/10227327/7ef19362-6836-11e5-91e9-7cb31760a76f.jpg)

**Comment by arnaldos** [comment]
Versión 4
![icono wallet store-01](https://cloud.githubusercontent.com/assets/13594347/10227349/a056e660-6836-11e5-9c5b-ed476df1ca0f.jpg)
![Uploading icono wallet store-02.jpg…]()

**Comment by Luis-Fernando-Molina** [comment]
Primero vamos a trabajar solo el icono. De ver el icono se debe deducir que es una wallet store, ninguno de esos cumple con esa caracteristica. La conbinacion de colores de la version 4 me gusta.

**Comment by arnaldos** [comment]
perfecto !!! voy a replantear el icono !!

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina icono para la wallet store

![icono-wallet-store-10](https://cloud.githubusercontent.com/assets/13594347/10300843/cd5de144-6bc5-11e5-8731-7bebb0c1b76d.jpg)
![icono-wallet-store-09](https://cloud.githubusercontent.com/assets/13594347/10300844/cd651ef0-6bc5-11e5-8338-48fdaa6c0b6b.jpg)

**Comment by Luis-Fernando-Molina** [comment]
no se ve mal, pero no se deduce que es el icono de una wallet store

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina voy a buscar otro enfoque para esta wallet. tratando de mantener los mismos elementos

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina te comparto el icono de la store 

![icono-wallet-store-11](https://cloud.githubusercontent.com/assets/13594347/10382210/7023f5f4-6deb-11e5-860a-4ac9d6bf9215.jpg)

fondo blanco y texto
![icono-wallet-store-12](https://cloud.githubusercontent.com/assets/13594347/10382211/7027f10e-6deb-11e5-8314-96bebf463c7c.jpg)

con fondo de color
![icono-wallet-store-13](https://cloud.githubusercontent.com/assets/13594347/10382212/702d500e-6deb-11e5-917d-af574d5bc3f0.jpg)

**Comment by Luis-Fernando-Molina** [comment]
Muy bueno! :+1: aprobado!
