### ISSUE TITLE
Crear banner de presentación para la Wallet Store

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#161]
Viene del #155

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina aquí coloco los banners para la store 

Versión 1
![banner-wallet-store](https://cloud.githubusercontent.com/assets/13594347/10475187/6ef29cda-720a-11e5-912b-4a8184f86206.jpg)

Versión 2
![banner-wallet-store2](https://cloud.githubusercontent.com/assets/13594347/10475188/6ef72502-720a-11e5-995c-2a2432bba708.jpg)

También te comparto como se verían aplicadas en una store y el icono en un desktop

![sreenshot-wallet-store2](https://cloud.githubusercontent.com/assets/13594347/10475207/91bc06de-720a-11e5-91a7-c0ca132de029.png)
![sreenshot-wallet-store3](https://cloud.githubusercontent.com/assets/13594347/10475208/91c396c4-720a-11e5-8728-2543e63cdbe1.png)
![sreenshot-wallet-store1](https://cloud.githubusercontent.com/assets/13594347/10475209/91c7ae08-720a-11e5-92fc-f24e67ad1800.png)

**Comment by Luis-Fernando-Molina** [comment]
Arnaldo me gustó la version 2. Sin embargo la wallet store no es una wallet, sino una sub app. Tampoco puede estar para bajarse desde la wallet store porque esta es la wallet store !!! jajaja.

Sin embargo podemos usar el banner dentro de la APP de alguna manera seguramente., en el Action bar por ejemplo (title bar)

**Comment by Luis-Fernando-Molina** [comment]
@nelsonalfo @Neoperol  ya tenemos los colores de la wallet store, hay que ponerla linda ahora! 

> Sin embargo podemos usar el banner dentro de la APP de alguna manera seguramente., en el Action bar por ejemplo (title bar)

**Comment by nelsonalfo** [comment]
fino!

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina  perfecto luis yo la coloque asi porque pence que esta estaria dentro del store de googleplay. pero tomando en cuenta esto procedo a subir el icono al repo y doy este caso como cerrado !!
