### ISSUE TITLE
Crear icono para la Wallet Manager

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#162]
Viene del #155

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina  te comparto esta versión para la wallet manager 

![icono-wallet-manager](https://cloud.githubusercontent.com/assets/13594347/10441291/07121a72-7111-11e5-8e2f-f954403efb90.jpg)
![icono-wallet-manager2](https://cloud.githubusercontent.com/assets/13594347/10441292/073e8abc-7111-11e5-8341-f21ca49c6581.jpg)

**Comment by Luis-Fernando-Molina** [comment]
el wallet manager es un desktop no una subapp, con lo cual en teoria no tiene iconos, pero esta bastante bueno igual. Lo dejemos aca por si algun dia nos hace falta.

**Comment by arnaldos** [comment]
ah ok perfecto !!! Luis y que piezas gráficas necesitamos para la wallet manager ? porque hasta el momento había entendido era una subapp. y estaba trabajando para icono y banner ahora sabiendo esto como debo enfocarlo ?

**Comment by Luis-Fernando-Molina** [comment]
por ahora nada, si necesitamos un icono usaremos este, pero en un principio ni eso hace falta. :+1:
