### ISSUE TITLE
Definir la forma en que se visualizarán las fotos del staff en la sitio de bitDubai

### ISSUE THREAD

**Issue by m471c4** [bitDubai/fermat-graphic-design#164]
Por ahora se visualiza de esta manera:

![foto pag](https://cloud.githubusercontent.com/assets/13468350/10250582/74ef188e-68f5-11e5-921c-917de470dad7.png)

Es necesario hacer nuevas propuestas para lograr una mejor integración con el site.

**Comment by m471c4** [comment]
@Luis-Fernando-Molina primeras propuestas para el display de la foto. Tengo una pregunta en cuanto a la paleta de colores. La paleta de Fermat cambió, entonces ¿sería necesario cambiar también la de bitDubai? Porque en ese caso, sería necesario modificar todo lo que está en la página web.

![fotosh](https://cloud.githubusercontent.com/assets/13468350/10256128/d0d67b1a-6918-11e5-8a94-bcaac74f3174.png)

@arnaldos en cuanto tengas tiempo me gustaría tener tu opinión, o si tienes alguna otra propuesta sería bueno conocerla.

**Comment by Luis-Fernando-Molina** [comment]
la primera, pero con la sombra interna y externa que tenia la original.

No vamos a usar la paleta de Fermat, nos quedamos con la de bitDubai asi como esta.

**Comment by m471c4** [comment]
@Luis-Fernando-Molina con la sombra interna:

![fotoshfinal](https://cloud.githubusercontent.com/assets/13468350/10257537/de74732c-6921-11e5-837a-cc32dfe87ecf.png)

**Comment by Luis-Fernando-Molina** [comment]
la sobre es al revez, sobre la foto, no de la foto sobre el marco. La externa esta ok.

**Comment by m471c4** [comment]
@Luis-Fernando-Molina versión final, con la corrección en la sombra:

![fotoshfinalshad](https://cloud.githubusercontent.com/assets/13468350/10258669/e750b368-6929-11e5-8754-d98d310e56b3.png)

**Comment by Luis-Fernando-Molina** [comment]
:+1:
