### ISSUE TITLE
Sustituir las fotos de "portrait team" en el sitio de bitDubai.com

### ISSUE THREAD

**Issue by m471c4** [bitDubai/fermat-graphic-design#166]
Se sustituirán las fotos del equipo en el sitio web de bitDubai.com, que ahora cuentan con un formato redondo y un marco nuevo.

El issue será cerrado una vez que todas las fotos se hayan sustituido y se haya agregado a los nuevos miembros del equipo.

**Comment by m471c4** [comment]
Ya han sido actualizadas todas las fotos con su nuevo formato ( https://bitdubai.com/wp/#TEAM ); se da por cerrado el caso.

**Comment by Luis-Fernando-Molina** [comment]
@m471c4 @arnaldos , por favor intercambien la posicion de Luis Fuenmayor por la de Guillermo Gutierrez asi se ve mas uniforme.  Ademas faltan Yordin, Vanessa, Gustavo, Hendry, Yorma y Emmanuel. Que pasó que estos se quedaron afuera?

**Comment by m471c4** [comment]
@Luis-Fernando-Molina haré el cambio. Tanto @arnaldos como yo hemos escrito varias veces por los grupos y no hemos tenido respuesta, pensé que no faltaba nadie.

@yalayn @vnesita @gustl-arg @hendry19901990 @Namroy @emmanuelcolina por favor, hacerme llegar a mi correo dayana.matos@gmail.com la foto que desean que aparezca en el sitio de bitDubai, así como el resumen (opcional, en inglés) y las redes sociales que quieran incluir.

Saludos a todos.

**Comment by Luis-Fernando-Molina** [comment]
Mas que resumen es un texto cualquiera que quieran que aparezca abajo.

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina ya las fotos se reemplazaron !! cerramos este caso ?

**Comment by gustl-arg** [comment]
perdon Arnaldo, te la mando en unos minutos..busco tu mail en la pagina ...

**Comment by arnaldos** [comment]
@gustl-arg vale perfecto !!
