### ISSUE TITLE
SUPERISSUE: Crear covers para los hangouts de meetings

### ISSUE THREAD

**Issue by m471c4** [bitDubai/fermat-graphic-design#167]
Es necesario crear covers para cada uno de los tipos de meetings que se realizan a través de hagouts, cada una debe tener el logo de bitDubai y características que los identifiquen. La lista de meetings que se tiene hasta ahora son:

Regular Meeting
Core Team Meeting
Android Meeting
Multiplataforma
Fermat.org Meeting
Fermat Book Meeting
Graphic Design Meeting
UX Meeting
CBP Meeting
    CBP UX Meeting
    CBP GUI Meeting
CCP Meeting
P2P Meeting
DAP Meeting
    DAP UX Meeting
    DAP GUI Meeting
WPD Meeting
    WPD UX Meeting
    WPD GUI Meeting
MKT Meeting

Adicionalmente, se crearán covers para las reuniones de los equipos: 

MALO Team (Matias y León)
ThunderCoin Team (Rodrigo)
George Team (Jorge)
Disruptors Team (Roberto)

Si falta alguno o debe hacerse alguna corrección, favor escribir por acá. Se desprenderán issues para tratar cada uno de los covers, este trabajo será repartido entre @arnaldos y mi persona.

**Comment by Luis-Fernando-Molina** [comment]
Observaciones:

1) ThunderCoin se llama en realidad Thunder
2) George es Yorch
3) Falta Fermat.Org Team
4)Regular Meeting   NO VA
5) Multiplataforma  NO VA

en el caso de GUI , UX es algo que le agrega a la caratula de la plataforma. Un icono o algo grafico, mas un cambio en el título.

**Comment by Luis-Fernando-Molina** [comment]
Hacer primero 1 sola caratula, cuando esté lista el resto lo tomamos de ahi.

**Comment by Luis-Fernando-Molina** [comment]
lo podemos discutir en este mismo caso.

**Comment by jorgeejgonzalez** [comment]
@Luis-Fernando-Molina dayana se coimunico conmigo por Whatsapp parta informarme que esta sin conexion desde el dia domingo en la tarde por lo que me pidio que montara los avances sobre los que ha venido trabajando para este issue. 

Son 5 bocetos que adjunto

![img-20151013-wa0004](https://cloud.githubusercontent.com/assets/2023125/10458418/8367fafa-7194-11e5-9269-bb51455e006a.jpg)

![img-20151013-wa0005](https://cloud.githubusercontent.com/assets/2023125/10458419/8368af36-7194-11e5-8f9d-434e30641314.jpg)

![img-20151013-wa0006](https://cloud.githubusercontent.com/assets/2023125/10458420/836dafa4-7194-11e5-9416-580a2c0e14a3.jpg)

![img-20151013-wa0007](https://cloud.githubusercontent.com/assets/2023125/10458421/83705b32-7194-11e5-9b93-ec1fbf403d0b.jpg)

![img-20151013-wa0008](https://cloud.githubusercontent.com/assets/2023125/10458422/83743e82-7194-11e5-9bf5-b747e85f3396.jpg)

me indica que esta trabajando en formato 16:9 para ajustarlo mejor al formato del reproductor de youtube.

**Comment by Luis-Fernando-Molina** [comment]
Gracias Jorge, @m471c4 no me convence ninguno de los propuestos hasta ahora. Deberias incluir en la propuesta donde iria el logo del equipo, el logo de la plataforma (2d o puede ser la moneda 3d de esa plataforma) el logo de si es GUI / UX , el logo de fermat y el de bitdubai que ya está.

**Comment by m471c4** [comment]
@Luis-Fernando-Molina muy bien, haré nuevas propuestas, crearé issues para el logo de cada grupo. Acá algunos bocetos para los logos de UX y GUI:

UX Versión 1 (falta mejorar la forma según el material design, pero es una propuesta inicial):
![ux1](https://cloud.githubusercontent.com/assets/13468350/10497847/fdc40124-7291-11e5-8a8b-f0c90d0dc934.png)

UX Versión 2 (tipográfica):
![ux2](https://cloud.githubusercontent.com/assets/13468350/10497846/fdb1b85c-7291-11e5-8e7e-b57582dfeb40.png)

GUI Versión 1 (de igual forma, falta ajustarlo al material design):
![gui1](https://cloud.githubusercontent.com/assets/13468350/10497914/60a0cb60-7292-11e5-9978-4952d227e047.png)

GUI Versión 2 (tipográfica):
![gui2](https://cloud.githubusercontent.com/assets/13468350/10497922/6f786120-7292-11e5-9504-9e325866daac.png)

**Comment by Luis-Fernando-Molina** [comment]
Me gustaria no reutilizar el tema de los circulos naranjas. Prefiero que eso queda asociado a las plataformas.

Me inclino por los iconos graficos, pero me gustaria ver otras opciones.

**Comment by m471c4** [comment]
@Luis-Fernando-Molina muy bien, mejoraré esas propuestas gráficas y las subiré acá.

**Comment by Luis-Fernando-Molina** [comment]
@m471c4 Hablá con @arnaldos porque decidimos usar como fondo las monedas 3d de @jonathanborges3d , Arnaldo tiene los detalles.
