### ISSUE TITLE
Composición artística monedas Dollar/Euro/Libra

### ISSUE THREAD

**Issue by jonathanborges3d** [bitDubai/fermat-graphic-design#168]
@Luis-Fernando-Molina Ya reuní las monedas en una sola escena e hice un primer render: 

![fiat_art_1](https://cloud.githubusercontent.com/assets/13649739/10381514/3fd7d68c-6de5-11e5-82bb-56f348474586.jpg)

No estoy seguro de que esta distribución favorezca la escena porque se pierden detalles de las monedas. Tal vez deba ser un poco más ordenada, como en torres de distintos tamaños vistas desde un ángulo superior. Qué opinas?

**Comment by Luis-Fernando-Molina** [comment]
no esta mal, con mas resolucion puede que cambie la sensación. Igual de ahi mismo se puede sacar otra toma.

Asegurate que no haya monedas en el air o en posiciones fisicamente imposible please

**Comment by jonathanborges3d** [comment]
@Luis-Fernando-Molina Un segundo render de mayor resolución:

https://raw.githubusercontent.com/bitDubai/fermat-graphic-design/9100edd84fa1add99e885d5209c74eb46e06514d/Dise%C3%B1o%203D/Composiciones%20artisticas/Monedas%20Fiat/Fiat_art.jpg?token=ANBHS9fTA2nE16DZvgcIkdc4Nic-hHD5ks5WJtNGwA%3D%3D

**Comment by Luis-Fernando-Molina** [comment]
La parte de atras de la moneda de un dolar no esta bien. la parte plateada sobre sale de la dorada. El resto puede andar, aunque tanta mezcla no lo hace tan bueno. Proba poner la camara mas cerca aunque se vean menos monedas.

**Comment by jonathanborges3d** [comment]
@Luis-Fernando-Molina Tercera versión con acercamiento a la moneda de un dollar:

https://raw.githubusercontent.com/bitDubai/fermat-graphic-design/ef1c5a1846aa3b5484b362fa6711984bb8f6eb53/Dise%C3%B1o%203D/Composiciones%20artisticas/Monedas%20Fiat/Fiat_art.jpg?token=ANBHSz-vjFA2i3vGUwtPM9GbE4YPVuS2ks5WKEe_wA%3D%3D

**Comment by Luis-Fernando-Molina** [comment]
Esta mejor la toma ahi, algunos detalles:

1) a la derecha hay dos monedas encimadas que no quedan bien (euro)
2) iz abajo, reemplaza la moneda esa de euro por una que se vea el logo de fermat derecho con la palabra fermat

el resto no lo toques que está perfecto!

**Comment by jonathanborges3d** [comment]
@Luis-Fernando-Molina Tuve que volver a simular la escena porque al hacer los cambios que me pediste se exportaba con errores y el motor de render dejaba espacios en negro por toda la escena.

Realicé un nuevo render:

https://raw.githubusercontent.com/bitDubai/fermat-graphic-design/7e2e5c1e49e48fdaf8069c756b159f037a16977c/Dise%C3%B1o%203D/Composiciones%20artisticas/Monedas%20Fiat/Fiat_art.jpg?token=ANBHSzdNpmBp-43bXnIm5NLUCn_6KULJks5WK-orwA%3D%3D

**Comment by Luis-Fernando-Molina** [comment]
:+1:  no te olvides de ir publicando en el face las escenas terminadas en maxima resolución.

**Comment by jonathanborges3d** [comment]
@Luis-Fernando-Molina Reabrí el caso para postear las nuevas escenas que incluyan todas las fiat coins

![fiat_art_3](https://cloud.githubusercontent.com/assets/13649739/11053793/5e019fe8-8736-11e5-96c0-61f86944ad9e.jpg)

**Comment by jonathanborges3d** [comment]
Versión para REAME.md

![fiat_art_3_readme_2](https://cloud.githubusercontent.com/assets/13649739/11054503/1c49c0ae-873f-11e5-9574-ac64fbb23d45.jpg)

**Comment by Luis-Fernando-Molina** [comment]
La version para el READ ME sabian tener mucho mas reflactividad de la que se ve acá, o me equivoco?

Otra cosa, no me queda claro porque se repite la de euro varias veces y de las otras hay solo una?

La modeda parada de dolar de la derecha parece estar obre la acostada...

**Comment by Luis-Fernando-Molina** [comment]
me gustaria que nuevas escenas se discutan en nuevos caso, asi es como manejamos el resto de las cosas.

En el caso de esta con background me imagino que vas a buscarle un background, no?

**Comment by jonathanborges3d** [comment]
@Luis-Fernando-Molina Ok, abriré el nuevo caso correspondiente.

Si, olvidé colocarle la reflexión a la superficie. Postearé la nueva versión de la escena con las correcciones en el nuevo issue.
