### ISSUE TITLE
Prueba de color (Tonos grises) en que se visualizarán las fotos del staff en la sitio de bitDubai 

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#169]
En este caso se probaran las fotos en tonos grises para ver su funcionalidad. de ser aprobado se procederá a actualizar las fotos el website de bitDubai

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina te comparto las fotos en blanco y negro como me lo pediste !

Coloque la foto de yordin tal cual esta actualmente, porque esta en blanco y negro, solo que tiene un efecto de luces que le salen de los brazos, probé colocarla en blanco y negro incluyendo las luces y no se ve muy bien por eso preferí dejarla tal cual esta.

![prueba de color para fotos](https://cloud.githubusercontent.com/assets/13594347/10473911/8b23f350-71fa-11e5-9e5a-5c7d54731c4e.jpg)

**Comment by Luis-Fernando-Molina** [comment]
Muy bien Arnaldo, probaste ajustar los tonos / contraste / brillo para que sea todo uniforme?

(de hacerlo asi, la foto de Jordin debe quedar en blanco y negro como todas)

**Comment by emmysm** [comment]
![team](https://cloud.githubusercontent.com/assets/15143489/10617504/bb128a92-7734-11e5-8efa-5003b24448a0.png)

@Luis-Fernando-Molina  prueba de color, fotos del team escala de grises.

**Comment by emmysm** [comment]
Sería conveniente cambiar algunas fotos que por el plano en el que fueron tomadas no logran visualizarse bien. Me gustaría saber su opinión con respeto a ello @arnaldos @Luis-Fernando-Molina

**Comment by Luis-Fernando-Molina** [comment]
@emmysm  Como cuales? A alguna gente se le puede pedir, a otra no.

**Comment by emmysm** [comment]
Ok. En este caso si se pudiera solo cambiaría las últimas fotos de la segunda fila @Luis-Fernando-Molina

**Comment by Luis-Fernando-Molina** [comment]
ok, ese en @lnacosta  y @furszy por favor suban al caso este una foto cada uno para que @emmysm lo pueda terminar. Gracias.
