### ISSUE TITLE
Definir la paleta de colores para BitDubai

### ISSUE THREAD

**Issue by m471c4** [bitDubai/fermat-graphic-design#17]
Viene del #14 

Hasta ahora se tiene esta paleta que me pasó @Luis-Fernando-Molina; pero hay muchos elementos cuyos tonos no corresponden con la misma. 

![paleta_c](https://cloud.githubusercontent.com/assets/13468350/9078060/15ffa8ca-3b00-11e5-8275-3c79ca3e27ee.png)

Es necesario definir bien los tonos (inicialmente en RGB, ya que el producto principal es la aplicación que será visualizada en pantalla) y a partir de los tonos RGB, crear una paleta para impresión, ya que más adelante seguramente será necesaria.

**Comment by Luis-Fernando-Molina** [comment]
:+1:

**Comment by m471c4** [comment]
hasta ahora esta es la paleta que se tenía:
![paleta1](https://cloud.githubusercontent.com/assets/13468350/9312688/2dea39ae-44e8-11e5-8b22-eb6cbb79dfb5.png)

Pero en los isologos para Fermat y las sub apps se estaba trabajando con esta (algunas versiones de los isologos anteriores de BitDubai también se usaba esta) 
![paleta2](https://cloud.githubusercontent.com/assets/13468350/9312689/2e041752-44e8-11e5-84d8-12363aea09ca.png)

Acá se puede observar cómo se ve el isologo de BitDubai con cada una.

![logos_colores](https://cloud.githubusercontent.com/assets/13468350/9312690/2e0ca732-44e8-11e5-8bc0-e76d222937bb.png)

Yo particularmente optaría por la segunda, ya que los colores son mucho más vivos y generan un mejor contraste entre los elementos. Espero su opinión @arnaldos y @Luis-Fernando-Molina

**Comment by arnaldos** [comment]
Si estoy de acuerdo que la segunda paleta se aprecian mejor los colores y da mejor contraste, esta paleta es con la que he venido trabajando el logo de fermat hasta el momento ! y estoy totalmente de acuerdo de definir una sola paleta de colores en RGB. Para trabajar todo bajo estos parámetros.

**Comment by Luis-Fernando-Molina** [comment]
OK usemos la segunda paleta y avancemos. 

Caso cerrado.
