### ISSUE TITLE
Crear icono para la SubApp Crypto Broker Identity 

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#171]
Viene del #170

La subaplicación **Identity**, tal como su nombre lo indica, permite a los actores crear identidades; con las cuales pueden realizar diferentes acciones dentro de la plataforma. 

Un actor es una persona o figura que realiza algún tipo de acción dentro de la plataforma Fermat.

Los **brokers** son entes encargados de actuar como intermediarios entre compradores y vendedores mediante una comisión, que puede ser fija o variable a través de diferenciales.

**Crypto** es un sistema cifrado (es la protección de mayor nivel que proporciona ayuda para  mantener una información a salvo).

**Crypto Broker Identity**: aplicación que permite crear identidades para los brokers. (a través de un sistema cifrado)

**Requisitos**

Archivo PNG de 32 bits (alpha)
Tamaño: 512 x 512 píxeles
Tamaño máximo del archivo: 1024 KB

Una vez elegido el icono, es necesario generar los tamaños, en **.PNG** para aplicarlos en lo siguientes:

**IC launcher**:

48 × 48 px (mdpi)
72 × 72 px (hdpi)
96 × 96 px (xhdpi)
144 × 144 px (xxhdpi)
192 × 192 px (xxxhdpi)
512 × 512 px (Wallet store)

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina comparto los bocetos para los iconos de Crypto Broker Identity

Versión 1

![crypto-broker-identity-1](https://cloud.githubusercontent.com/assets/13594347/10781194/3a5ff4dc-7d17-11e5-979e-858126801850.png)

Versión 2

![crypto-broker-identity-2](https://cloud.githubusercontent.com/assets/13594347/10781197/445835a8-7d17-11e5-8e5b-90bf2e102501.png)

Versión 3

![crypto-broker-identity-3](https://cloud.githubusercontent.com/assets/13594347/10781202/4b9cb384-7d17-11e5-8c91-9699ac83f677.png)

Versión 4

![crypto-broker-identity-4](https://cloud.githubusercontent.com/assets/13594347/10781203/534b339e-7d17-11e5-9f61-475c3e08af38.png)

**Comment by Luis-Fernando-Molina** [comment]
> Los brokers son entes encargados de actuar como intermediarios entre compradores y vendedores mediante una comisión, que puede ser fija o variable a través de diferenciales.

Arnaldo, en nuestros casos los brokes son personas que se dedican a comprar y vender bitcoin. No confundir con el broker de wall street. Aca son gente común. 

No entiendo el signo de + en los iconos.

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina Vale perfecto !! entonces el Crypto Broker Identity no permite crear identidades para los brockers ?

**Comment by Luis-Fernando-Molina** [comment]
Si, pero tambien permite borrarlas y modificarlas...

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina te comparto una nueva versión 

versión 5
![crypto-broker-identity-5](https://cloud.githubusercontent.com/assets/13594347/10860847/73165830-7f41-11e5-9308-0149bce81c45.png)

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina el sreenshot

![crypto-broker-identity-5-sreenshot](https://cloud.githubusercontent.com/assets/13594347/10916655/a7fb24d2-822e-11e5-89a0-645ad0a01eae.png)

**Comment by Luis-Fernando-Molina** [comment]
mas opciones

**Comment by jurene22** [comment]
![icon_subapp_crypto_broker_identity_issue171_version 1](https://cloud.githubusercontent.com/assets/15174317/10980023/170ae660-83d2-11e5-9ef6-232562c98949.png)
@Luis-Fernando-Molina Aporte para caso 171 versión 1

**Comment by jurene22** [comment]
Versión 2 @Luis-Fernando-Molina 
![icon_subapp_crypto_broker_identity_issue171_version 2](https://cloud.githubusercontent.com/assets/15174317/10982746/3b01908c-83e1-11e5-9edf-8f979c802345.png)
![vista target](https://cloud.githubusercontent.com/assets/15174317/10982753/3fb54c4a-83e1-11e5-88bd-a361aad16755.png)

**Comment by ivonnesantos** [comment]
Ambas propuestas estan orientadas hacia el tema de compra venta intercambio de tal manera que capte rapido la atencion del usuario que en este caso es el brokers y ubique su herramienta de trabajo con facilidad.

![171 subapp crypto broker identity-01](https://cloud.githubusercontent.com/assets/15238660/11076886/752a7232-87cf-11e5-83e2-c6b9a85f1199.png)

@Luis-Fernando-Molina @arnaldos

**Comment by jurene22** [comment]
![icon_subapp_crypto_broker_identity_issue171_version 3](https://cloud.githubusercontent.com/assets/15174317/11213841/6a31f602-8d10-11e5-9c82-3251a088c297.png)
![vista target version 3](https://cloud.githubusercontent.com/assets/15174317/11213842/6a322abe-8d10-11e5-8563-2971890c3f90.png)
@Luis-Fernando-Molina Versión 3 en aporte a este Icon

**Comment by arnaldos** [comment]
nos quedamos con la versión 2 de @ivonnesantos solo aumenta el ancho del elipse que hace del torso del broker para probar como se ve!!! también sube una propuesta con los colores la versión 1

**Comment by ivonnesantos** [comment]
viendo con los tonos en azul la naranja la odio!!! pero es tu decisión 
![171 subapp crypto broker identity-01](https://cloud.githubusercontent.com/assets/15238660/11227716/ed46559e-8d59-11e5-833b-7311c7c12132.png)

@arnaldos

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina versión provisional del broker identity

![crypto-broker-identity](https://cloud.githubusercontent.com/assets/13594347/11388006/2060052a-9303-11e5-861f-0c0446762266.png)

**Comment by Luis-Fernando-Molina** [comment]
como provisional puede ser pero que siga el caso abierto please

**Comment by victoralfonzohd** [comment]
@Luis-Fernando-Molina @arnaldos 

Partiendo del Icono de la Crypto boker wallet:

![crypto_broker](https://cloud.githubusercontent.com/assets/15219855/11735326/24e4f52e-9f92-11e5-8db0-2aea5b606243.jpg)

Planteo estas propuestas partiendo del mismo concepto para mantener la linea gráfica deseada:

![crypto_broker_identity](https://cloud.githubusercontent.com/assets/15219855/11735334/39cfe642-9f92-11e5-8dec-6c8001b4266d.jpg)

**Comment by victoralfonzohd** [comment]
@Luis-Fernando-Molina @arnaldos

![crypto_broker](https://cloud.githubusercontent.com/assets/15219855/11794257/81f7485a-a282-11e5-8c2a-ff7c9205750c.jpg)

**Comment by arnaldos** [comment]
@victoralfonzohd prueba otra versión plz, pero me voy por la versión del fondo blanco. combina los colores verdes y azul como se usaron en la crypto broker. puede ser el aro en verde y el usuario en azul usa la propuesta 4 de la primera serie. ve por ese camino.

**Comment by victoralfonzohd** [comment]
@arnaldos 

![crypto_broker](https://cloud.githubusercontent.com/assets/15219855/11887726/0a53c4d4-a509-11e5-9a51-865eec2415e3.jpg)

**Comment by arnaldos** [comment]
@victoralfonzohd aun lo veo muy simple prueba que otra cosa pueda ayudar a resaltar mas al usuario sin perder el concepto

**Comment by arnaldos** [comment]
usa el mismo color del aro de la community

**Comment by victoralfonzohd** [comment]
@arnaldos 

![crypto_broker](https://cloud.githubusercontent.com/assets/15219855/11889969/3b0502ec-a521-11e5-8c02-92856c708c96.jpg)

**Comment by arnaldos** [comment]
@victoralfonzohd elimina la "I".   Intenta colocar esa sombra pero partiendo de la posición original del usuario sin que se parezca a la community. también prueba hacer un fondo con tonos grises y blancos.

**Comment by victoralfonzohd** [comment]
@arnaldos

Propuestas: 

![crypto_broker 1](https://cloud.githubusercontent.com/assets/15219855/11913756/373fb046-a641-11e5-959a-6663ad6053cc.jpg)

**Comment by arnaldos** [comment]
@victoralfonzohd quilate el fondo verde a nivel cromatico has que sea igual al de la community

**Comment by victoralfonzohd** [comment]
@arnaldos 

![crypto_broker 1](https://cloud.githubusercontent.com/assets/15219855/11958106/04859e64-a898-11e5-8554-6e04fea8b4c5.jpg)

**Comment by victoralfonzohd** [comment]
@arnaldos 

![sin-titulo-1](https://cloud.githubusercontent.com/assets/15219855/11959177/27ed5594-a89e-11e5-80ac-2337ce84a7b9.jpg)

**Comment by arnaldos** [comment]
@victoralfonzohd dejamos ese !! :+1:

**Comment by arnaldos** [comment]
al de la  community planteale el mismo fondo a ver que tal

**Comment by victoralfonzohd** [comment]
![icono_cryptobroker_comunity](https://cloud.githubusercontent.com/assets/15219855/11959677/c16b85b8-a8a0-11e5-9dc9-6e5e9fa082e5.jpg)

**Comment by arnaldos** [comment]
vale subelos al repo :+1:

**Comment by victoralfonzohd** [comment]
@arnaldos @Luis-Fernando-Molina 

Propuesta 1: 

Versión 1: 

![iconos_-crypto-broker](https://cloud.githubusercontent.com/assets/15219855/12021723/4171c0ba-ad5b-11e5-82ac-a3f3edf8c770.jpg)

Versión 2: 

![iconos_-crypto-broker](https://cloud.githubusercontent.com/assets/15219855/12021724/417783ec-ad5b-11e5-86df-595b529d7ace.png)

**Comment by victoralfonzohd** [comment]
@arnaldos @Luis-Fernando-Molina 

Propuesta 2:

![iconos_-crypto-broker](https://cloud.githubusercontent.com/assets/15219855/12024656/6ca5d772-ad78-11e5-9682-7fa35e3c888c.jpg)

Propuesta 3:

![iconos_-crypto-broker1](https://cloud.githubusercontent.com/assets/15219855/12024662/79d234ae-ad78-11e5-9092-f9db48590b3d.jpg)
