### ISSUE TITLE
Crear icono para la SubApp Crypto Broker Community

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#172]
Viene del #170

La subaplicación **Community** permite que los actores, a través de sus identidades, interactúen entre ellos. Existe una por cada tipo de actor.

Un actor es una persona o figura que realiza algún tipo de acción dentro de la plataforma Fermat.

Los **brokers** son entes encargados de actuar como intermediarios entre compradores y vendedores mediante una comisión, que puede ser fija o variable a través de diferenciales.

**Crypto** es un sistema cifrado (es la protección de mayor nivel que proporciona ayuda para  mantener una información a salvo).

**Crypto Broker Community**: Es la aplicación que permite el intercambio entre los brokers. (a través de un sistema cifrado)

**Requisitos**

Archivo PNG de 32 bits (alpha)
Tamaño: 512 x 512 píxeles
Tamaño máximo del archivo: 1024 KB

Una vez elegido el icono, es necesario generar los tamaños, en **.PNG** para aplicarlos en lo siguientes:

**IC launcher**:

48 × 48 px (mdpi)
72 × 72 px (hdpi)
96 × 96 px (xhdpi)
144 × 144 px (xxhdpi)
192 × 192 px (xxxhdpi)
512 × 512 px (Wallet store)

**Comment by emmysm** [comment]
![crypto broker community](https://cloud.githubusercontent.com/assets/15143489/10794409/f1abdbd4-7d66-11e5-83cb-408d9df3f05f.png)
@Luis-Fernando-Molina

**Comment by Luis-Fernando-Molina** [comment]
@emmysm eso no creo que se vea cuando lo achicas....

Buscalo por el lado de community (conjunto de personas) y crypto broker (moneditas bitcoin)

**Comment by emmysm** [comment]
![broker community](https://cloud.githubusercontent.com/assets/15143489/10837385/1f169dd2-7e8b-11e5-9cd5-38fb6a115fa3.png)
@Luis-Fernando-Molina  aca mi segunda propuesta

**Comment by jurene22** [comment]
@arnaldos @Luis-Fernando-Molina Buen dia aqui les envio un aporte
Versión 3
![icon_subapp_crypto_broker_community_issue172_version_3_48x48](https://cloud.githubusercontent.com/assets/15174317/10846658/88b832f2-7ee3-11e5-97ed-d2c2d3da5c19.png)
![icon_subapp_crypto_broker_community_issue172_version_3](https://cloud.githubusercontent.com/assets/15174317/10846659/88ba3a16-7ee3-11e5-85f3-15cb04fd9292.png)

**Comment by Luis-Fernando-Molina** [comment]
Vamos a continuar la de  @emmysm . @arnaldos enseñale como lo mostras mas chico entre otros...

**Comment by arnaldos** [comment]
Jurene el concepto no me parecen que  mal. solo algo que veo esta
sucediendo en los iconos que trabajas es que incluyes elementos muy
pequeños y esto en su reducción máxima se van a perder.

**Comment by arnaldos** [comment]
@emmysm cuando uses varios elementos que al juntarlos forman uno, por ejemplo la moneda de bitcoin  centrarlos entre ellos para darle simetría. :smile:

**Comment by jurene22** [comment]
![icon_subapp_crypto_broker_community_issue172_version_4](https://cloud.githubusercontent.com/assets/15174317/10857505/9c0d9e18-7f20-11e5-9fdb-d09674977ed4.png)
@arnaldos @Luis-Fernando-Molina 
nuevo aporte con modificacion en tamaño de los elementos..

**Comment by jurene22** [comment]
![icon_subapp_crypto_broker_community_issue172_version_5](https://cloud.githubusercontent.com/assets/15174317/10858883/7fea5ce4-7f2a-11e5-99a5-80845e7cbdd3.png)
Versión 5

**Comment by jurene22** [comment]
![icon_subapp_crypto_broker_community_issue172_version_6](https://cloud.githubusercontent.com/assets/15174317/10858900/95701cd4-7f2a-11e5-9984-c9b20d411787.png)
Versión 6

**Comment by emmysm** [comment]
Ya lo hago, @Luis-Fernando-Molina ;)

**Comment by emmysm** [comment]
![prueba de colores](https://cloud.githubusercontent.com/assets/15143489/10861895/9b114fd4-7f64-11e5-985e-f62f46943c81.png)
Propuesta de colores @Luis-Fernando-Molina 
![propuesta de colores 2](https://cloud.githubusercontent.com/assets/15143489/10861931/1e00b78a-7f66-11e5-8ce6-8eb92ceab915.png)

**Comment by emmysm** [comment]
@arnaldos

**Comment by emmysm** [comment]
![sreenshot](https://cloud.githubusercontent.com/assets/15143489/10862032/6a84955a-7f6a-11e5-8ffe-2b500bdcea93.png)
@Luis-Fernando-Molina

**Comment by emmysm** [comment]
![banner](https://cloud.githubusercontent.com/assets/15143489/10862098/8b5f75a4-7f6c-11e5-9fe3-86031cab5cd1.jpg)
prueba de color

**Comment by Luis-Fernando-Molina** [comment]
@emmysm proba quitarle las costuras a las B please. Ya casi estamos llegando.

**Comment by Luis-Fernando-Molina** [comment]
@emmysm los banners se discuten en otro caso. @arnaldos y una vez que el icono esté aprobado. 
@arnaldos Agrega ese procedimiento al README please.

**Comment by arnaldos** [comment]
@emmysm  acuérdate de bajar el tamaño del sreenshot para que se aprecie el icono al tamaño real

**Comment by emmysm** [comment]
@Luis-Fernando-Molina  sí, estaba haciendo pruebas de color. Haré los ajustes.

**Comment by emmysm** [comment]
![propuesta de colores](https://cloud.githubusercontent.com/assets/15143489/10893549/8bfe11ee-817b-11e5-8201-4dac49e968ff.png)

**Comment by emmysm** [comment]
![screen](https://cloud.githubusercontent.com/assets/15143489/10894984/cbb8fe0e-8183-11e5-97c5-1eb711401e91.png)

@Luis-Fernando-Molina

**Comment by Luis-Fernando-Molina** [comment]
:+1:

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina este caso ya lo podemos cerrar ?

**Comment by Luis-Fernando-Molina** [comment]
cuando ponto :+1:  significa que esta aprobado.

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina perfecto !!!

**Comment by victoralfonzohd** [comment]
@Luis-Fernando-Molina @arnaldos

Partiendo del Icono de la Crypto boker wallet:

![crypto_broker](https://cloud.githubusercontent.com/assets/15219855/11735377/aad2cb16-9f92-11e5-97e5-6e014e48f21f.jpg)

Planteo estas propuestas partiendo del mismo concepto para mantener la linea gráfica deseada:

![crypto_broker_comunity](https://cloud.githubusercontent.com/assets/15219855/11735380/b558c824-9f92-11e5-818e-a306cef05e8d.jpg)

**Comment by arnaldos** [comment]
@victoralfonzohd  me inclino por la propuesta 3 o 5. mas por la 5 no se que opines @Luis-Fernando-Molina

**Comment by victoralfonzohd** [comment]
@Luis-Fernando-Molina @arnaldos

![crypto_brokerc](https://cloud.githubusercontent.com/assets/15219855/11794221/5476466a-a282-11e5-904f-2fec100f9ea2.jpg)

**Comment by Luis-Fernando-Molina** [comment]
No esperes por mi, ya no me da el tiempo para revisar esto, por favor procedan de acuerdo a los criterios que varias veces expresé o que ustedes mismos tengan.

**Comment by arnaldos** [comment]
@victoralfonzohd aumenta el tamaño un poco a las personas sin llegar tan cerca del borde.propuesta 2 el de la izquierda

**Comment by victoralfonzohd** [comment]
@arnaldos 

![sin-titulo-1](https://cloud.githubusercontent.com/assets/15219855/11801742/1c4a5e0a-a2bb-11e5-84b7-cdee710214ff.jpg)

**Comment by arnaldos** [comment]
@victoralfonzohd en los usuarios has que el espacio de arriba se el mismo que abajo respecto al circulo, podrías subirle un poquito mas el tamaño de los usuarios. si ves que al centrarlo no hace falta déjalo así. del resto esta bien :+1:

**Comment by victoralfonzohd** [comment]
@arnaldos  

Corrección de tamaño y espacio:

![sin-titulo-1](https://cloud.githubusercontent.com/assets/15219855/11887273/c9808f72-a504-11e5-9417-ec06a1224be3.jpg)

Preparare la carpeta con el resto de los formatos

**Comment by arnaldos** [comment]
perfecto !!! :+1:   sube los archivos al repo
