### ISSUE TITLE
Crear icono para la SubApp Crypto Customer Identity

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#173]
Viene del #170

La subaplicación Identity, tal como su nombre lo indica, permite a los actores crear identidades; con las cuales pueden realizar diferentes acciones dentro de la plataforma.

Un actor es una persona o figura que realiza algún tipo de acción dentro de la plataforma Fermat.

**Crypto** es un sistema cifrado (es la protección de mayor nivel que proporciona ayuda para  mantener una información a salvo).

**Customer** (Cliente) es el receptor de un servicio, producto o buena idea, que se obtiene a partir de un vendedor,  o proveedor. 

**Crypto Customer Identity** Es la aplicación que permite crear identidades a los customers. (a través de un sistema cifrado)

**Requisitos**

Archivo PNG de 32 bits (alpha)
Tamaño: 512 x 512 píxeles
Tamaño máximo del archivo: 1024 KB

Una vez elegido el icono, es necesario generar los tamaños, en **.PNG** para aplicarlos en lo siguientes:

**IC launcher**:

48 × 48 px (mdpi)
72 × 72 px (hdpi)
96 × 96 px (xhdpi)
144 × 144 px (xxhdpi)
192 × 192 px (xxxhdpi)
512 × 512 px (Wallet store)

**Comment by ivonnesantos** [comment]
![icon_crypto-01](https://cloud.githubusercontent.com/assets/15238660/10755129/07e9da44-7c6e-11e5-84f5-f01dc4941ef8.jpg)

Hice un icono basándome en la linea de unos que ya ustedes habian trabajado. Atenta a cualquier comentarios.

@arnaldos

**Comment by arnaldos** [comment]
hola @ivonnesantos  no necesariamente tienes que usar los colores de fermat, ya que cada subaplicación va a tener su propia identidad, por lo que se puede jugar con otra paleta de colores. 

Si haces uso de la paleta de colores asegurate que sea la que ya esta establecida.

Para el icono en si, me gustaria ver algo mas elaborado que pueda representar la creación de **una nueva identidad para el customer** 

Lo del sistema cifrado es una propiedad de la aplicación a nivel de desarrollo.

@Luis-Fernando-Molina no se que opines al respecto ?

**Comment by Luis-Fernando-Molina** [comment]
Veamos mas opciones.

**Comment by ivonnesantos** [comment]
Buenas noches adjunto mas opciones
![icon_crypto-01-01-01](https://cloud.githubusercontent.com/assets/15238660/10779425/c13bb262-7d02-11e5-8170-7633e63efb71.jpg)

@arnaldos @Luis-Fernando-Molina

**Comment by Luis-Fernando-Molina** [comment]
gracuas @ivonnesantos , una pregunta, porqué el signo mas?

**Comment by ivonnesantos** [comment]
Bueno porque yo entiendo que ese icono es para agregar identidades de usuario, estoy equivoca?

**Comment by ivonnesantos** [comment]
*equivocada?

**Comment by Luis-Fernando-Molina** [comment]
Es para un APP que le permite a un usuario de ese tipo administrar sus identidades. Crear una nueva, modificar alguna existente. Que son las identidades? El equivalente a tu perfil en la wallet. 

Transaccionando con cierta gente tu pudieras queres identificarte como Ivonne y poner tu foto real, mientras que con otra pudieras proteger tu identidad poniendo un alias sin foto. El sitio donde creas esas identidades y le das mantenimiento es en esta sub app llamada Crypto Customer Identity

**Comment by ivonnesantos** [comment]
![icon_crypto-01](https://cloud.githubusercontent.com/assets/15238660/10837497/580f8b98-7e8c-11e5-935e-caeca67f230d.jpg)

@arnaldos @Luis-Fernando-Molina

**Comment by Luis-Fernando-Molina** [comment]
La manera de representar una identidad se me ocurre por el lado de una mascara. Sigamos aportando. gracias

**Comment by ivonnesantos** [comment]
![icon_crypto-02](https://cloud.githubusercontent.com/assets/15238660/10856013/081b4c36-7f17-11e5-8d57-f5c6aecb7699.png)
![icon_crypto-01](https://cloud.githubusercontent.com/assets/15238660/10856016/0be33392-7f17-11e5-9934-bb6e88fb05d2.png)

@Luis-Fernando-Molina

**Comment by ivonnesantos** [comment]
![icon_crypto_mesa de trabajo 5](https://cloud.githubusercontent.com/assets/15238660/10864888/ec9c6cc6-7fcd-11e5-9da2-c54aa7b99d62.jpg)

@Luis-Fernando-Molina

**Comment by ivonnesantos** [comment]
![icon_crypto_mesa de trabajo 6](https://cloud.githubusercontent.com/assets/15238660/10865283/ea4be4d2-7fd8-11e5-850f-a00ffb89d3d2.jpg)

@arnaldos @Luis-Fernando-Molina

**Comment by ivonnesantos** [comment]
4 propuestas presentadas a tamaño
![icon_crypto-01](https://cloud.githubusercontent.com/assets/15238660/10899276/7acd1c2e-81a5-11e5-868e-99d415485b80.png)

@arnaldos @Luis-Fernando-Molina

**Comment by emmysm** [comment]
![sreenshot editable3](https://cloud.githubusercontent.com/assets/15143489/10899364/19531c22-81a6-11e5-8503-c7b3c0fe6439.png)
@Luis-Fernando-Molina

**Comment by emmysm** [comment]
![screen](https://cloud.githubusercontent.com/assets/15143489/10899632/da59acc2-81a8-11e5-8d80-efe39168177c.png)

**Comment by Luis-Fernando-Molina** [comment]
ok, vamos con la de  @emmysm la primera, solo ponele por favor una monedita de bitcoin o un codigo QR para representar la parte CRYPTO

**Comment by emmysm** [comment]
Perfecto, @Luis-Fernando-Molina, voy a eso ;)

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina  viendo las propuestas, siento que la versión 1 de @ivonnesantos que se muestra en el screenshot se apega mas al concepto. tiene el tamaño perfecto y los elementos esta bien balanceados, el icono esta solido y al reducirlo no pierde visibilidad. me apunto por ese ! no se que opines ? 

@emmysm para la versión 1 tuya has que los elementos estén mas integrados, y a pesar de que sean varios elementos, has que estos parezcan que son uno, evita colocar los elemento muy pegados al borde del icono esto genera ruido. si vas a sangrar un elemento has que ese sangrado sea mas notorio. :smile:

**Comment by emmysm** [comment]
Ok, gracias, @arnaldos

**Comment by Luis-Fernando-Molina** [comment]
> viendo las propuestas, siento que la versión 1 de @ivonnesantos 

ok pero ya nos fuimos por otro camino...

**Comment by ivonnesantos** [comment]
Por otro camino? Explíquese mejor por favor.

@Luis-Fernando-Molina

**Comment by emmysm** [comment]
![sreenshot editable3](https://cloud.githubusercontent.com/assets/15143489/10926246/5b3b3428-8267-11e5-8934-491fe78a9a9d.png)

@Luis-Fernando-Molina

**Comment by emmysm** [comment]
![screen crypto customer identity 2](https://cloud.githubusercontent.com/assets/15143489/10927312/e844b5f2-8270-11e5-8cf0-6926eb4af0e8.png)
@Luis-Fernando-Molina

**Comment by emmysm** [comment]
![screen crypto customer identity](https://cloud.githubusercontent.com/assets/15143489/10927374/5c9f3d82-8271-11e5-8e1b-cea207e0eb2b.png)
@Luis-Fernando-Molina

**Comment by emmysm** [comment]
![crypto customer identity](https://cloud.githubusercontent.com/assets/15143489/10929159/3ed42a0e-8282-11e5-8c63-8aeb900cb3c3.png)
@Luis-Fernando-Molina

**Comment by Luis-Fernando-Molina** [comment]
> Por otro camino? Explíquese mejor por favor.

@ivonnesantos  Significa que ya seleccioné una de las propuestas y habria que partir de esa para seguir proponiendo, mejorandola, refinandola. 

@emmysm sale mejor si pones todas las opciones en un mismo comentario y me tageas solo una vez, sino me llegan un mail por cada comentario donde estoy tageado, que multiplicado por mucha gente son cientos de emils. :smile:  Ademas, ponele cada imagen el nro de version 1, 2, n etc.

No veo la diferencia entre la primera y la segunda...

**Comment by jurene22** [comment]
![icon_subapp_crypto_customer_identity_issue173_version 1](https://cloud.githubusercontent.com/assets/15174317/11036113/a5cdd45e-86c8-11e5-98d4-4c81d2599079.png)
![vista target](https://cloud.githubusercontent.com/assets/15174317/11036116/ab77acd6-86c8-11e5-9522-101e42608786.png)
Aporte para este Issue @Luis-Fernando-Molina

**Comment by jurene22** [comment]
![icon_subapp_crypto_customer_identity_issue173_version 1](https://cloud.githubusercontent.com/assets/15174317/11036263/c5e03e2a-86c9-11e5-96da-0273d443ca3a.png)
![vista target](https://cloud.githubusercontent.com/assets/15174317/11036268/cb5753ca-86c9-11e5-82cc-e260618a9a67.png)
@Luis-Fernando-Molina Version 2

**Comment by Luis-Fernando-Molina** [comment]
mas opciones plase

**Comment by emmysm** [comment]
![screen crypto customer identity](https://cloud.githubusercontent.com/assets/15143489/11067268/fba2b860-879d-11e5-94c5-646cd28ffa26.png)
@Luis-Fernando-Molina 
![cripto customer identity](https://cloud.githubusercontent.com/assets/15143489/11067274/017f212e-879e-11e5-9464-86c50026eebc.png)

**Comment by emmysm** [comment]
![cripto customer identity](https://cloud.githubusercontent.com/assets/15143489/11068766/20619b38-87a5-11e5-8ab4-eab6ecf45847.png)

**Comment by emmysm** [comment]
@arnaldos  cómo quedó este caso? :)

**Comment by arnaldos** [comment]
@emmysm me gusta la paleta de colores, lo que veo es que los customers laterales no se integran entre el resto de los elementos, colócalos alineados a la mitad del teléfono como lo hiciste en la propuesta anterior, otro cosa podrías probar es colocar otra síntesis para representar a los customers. :smile:
