### ISSUE TITLE
Crear icono para la SubApp Crypto Customer Community

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#174]
Viene del #170

La subaplicación **Community** permite que los actores, a través de sus identidades, interactúen entre ellos. Existe una por cada tipo de actor.

Un actor es una persona o figura que realiza algún tipo de acción dentro de la plataforma Fermat.

**Crypto** es un sistema cifrado (es la protección de mayor nivel que proporciona ayuda para  mantener una información a salvo).

**Customer** (Cliente) es el receptor de un servicio, producto o buena idea, que se obtiene a partir de un vendedor,  o proveedor. 

**Crypto Customer Community** Es la aplicación que permite el intercambio entre los customers. (a través de un sistema cifrado)

**Requisitos**

Archivo PNG de 32 bits (alpha)
Tamaño: 512 x 512 píxeles
Tamaño máximo del archivo: 1024 KB

Una vez elegido el icono, es necesario generar los tamaños, en **.PNG** para aplicarlos en lo siguientes:

**IC launcher**:

48 × 48 px (mdpi)
72 × 72 px (hdpi)
96 × 96 px (xhdpi)
144 × 144 px (xxhdpi)
192 × 192 px (xxxhdpi)
512 × 512 px (Wallet store)

**Comment by jurene22** [comment]
Buen dia, anexo 2 versiones para este Icon
![icono customer community 1-01](https://cloud.githubusercontent.com/assets/15174317/10789542/3f86f95e-7d50-11e5-976b-abdac12840a9.jpg)
version 1

![icono customer community 1-02](https://cloud.githubusercontent.com/assets/15174317/10789551/4837b4e4-7d50-11e5-9c60-49e32c2b1689.jpg)
version 2

**Comment by jurene22** [comment]
@arnaldos  que opinas?

**Comment by Luis-Fernando-Molina** [comment]
> Crypto Customer Community Es la aplicación que permite el intercambio entre los customers. (a través de un sistema cifrado)

@arnaldos hace por favor revisar estas definiciones por los lideres del equipo en cuestion asi te explican que hace realmente esa aplicación. 

En este caso se trata de la APP que permite encontrar a la gente que normalmente compra o vende bitcoins sin dedicarse a eso como negocios (osea son clientes de un broker que si se dedica a eso como negocio). La APP le permite por ejemplo a un broker potencialmente encontrar otros clientes. 

Una vez que se encuentran pueden "conectarse entre si" si uno le envia una solicitud y el otro la acepta.

Por favor revisa todas estas definiciones para que sean mas claras.

**Comment by jurene22** [comment]
@arnaldos @Luis-Fernando-Molina 
Vesión 3
![icon_subapp_crypto_customer_community_issue174_version_3](https://cloud.githubusercontent.com/assets/15174317/10821894/ed79dece-7e26-11e5-99f6-afd755acab96.jpg)

**Comment by Luis-Fernando-Molina** [comment]
Busquemos por favor que a partir del icono se pueda deducir de que app se trata.

**Comment by jurene22** [comment]
![icon_subapp_crypto_customer_community_issue174_version_4](https://cloud.githubusercontent.com/assets/15174317/10884653/63df372c-814b-11e5-8f55-726b8ccdd2fd.png)
![icon_subapp_crypto_customer_community_issue174_version_4_target](https://cloud.githubusercontent.com/assets/15174317/10884654/63e371d4-814b-11e5-93de-aa703ef6d566.png)
Versión 4 @arnaldos @Luis-Fernando-Molina 
Reflejando la utilización de la herramienta en el icono

**Comment by isahq23** [comment]
@arnaldos @Luis-Fernando-Molina 
Aporte para icono de Crypto Customer Community
Presentacion en grande y aplicado sobre pantalla Nexus 5

Propuesta 1-1
![crypto_customer_community_icon_1-1](https://cloud.githubusercontent.com/assets/15214774/10886899/7675ef88-8156-11e5-8e1c-5f0f21d96c08.png)

Propuesta 1-2
![crypto_customer_community_icon_1-2](https://cloud.githubusercontent.com/assets/15214774/10886904/7b9cb596-8156-11e5-9519-3b59dd2933b0.png)

Propuesta 1-3
![crypto_customer_community_icon_1-3](https://cloud.githubusercontent.com/assets/15214774/10886911/81319076-8156-11e5-94fc-7f50c8bb920f.png)

Propuesta 1-4
![crypto_customer_community_icon_1-4](https://cloud.githubusercontent.com/assets/15214774/10886919/862d0baa-8156-11e5-8652-4d3c2d354d10.png)

Nexus
![crypto_customer_community_icon_nexus](https://cloud.githubusercontent.com/assets/15214774/10886925/8cb03506-8156-11e5-8928-28eec37e5f19.png)

**Comment by Luis-Fernando-Molina** [comment]
Mas opciones please

**Comment by isahq23** [comment]
@arnaldos @Luis-Fernando-Molina 
Nuevos aportes para el icono de Crypto Customer Community

Propuesta 2-1
![crypto_customer_community_icon_2-1](https://cloud.githubusercontent.com/assets/15214774/10970808/22039f00-83a3-11e5-8ad2-f45bc4b7d450.png)

Propuesta 2-2
![crypto_customer_community_icon_2-2](https://cloud.githubusercontent.com/assets/15214774/10970810/273e8386-83a3-11e5-96ef-17651c058357.png)

Propuesta 2-3
![crypto_customer_community_icon_2-3](https://cloud.githubusercontent.com/assets/15214774/10970816/2c8d6c9e-83a3-11e5-98ee-952f6d17c132.png)

Nexus 5
![crypto_customer_community_icon_2-nexus](https://cloud.githubusercontent.com/assets/15214774/10970821/3542b39e-83a3-11e5-869a-fb9aa9c4028c.png)

**Comment by isahq23** [comment]
@arnaldos @Luis-Fernando-Molina 

![crypto_customer_community_icon_3-1](https://cloud.githubusercontent.com/assets/15214774/11103741/85618452-8896-11e5-8c59-a027acfa3777.png)

![crypto_customer_community_icon_3-2](https://cloud.githubusercontent.com/assets/15214774/11103748/8ed17bbe-8896-11e5-8d66-31192f930aca.png)

![nexus_3](https://cloud.githubusercontent.com/assets/15214774/11103750/924c1ec0-8896-11e5-842d-9e584178111c.png)

**Comment by arnaldos** [comment]
@isahq23 me apunto con tu propuesta 3-1 busca sintetizar a los customer con otra forma, que no parezcan que son una sola persona o dos personas con un mismo cuerpo se ven algo extraño.

**Comment by jurene22** [comment]
![icono para la subapp crypto customer community 174_version 6](https://cloud.githubusercontent.com/assets/15174317/11344241/385c818e-91e2-11e5-9f68-16c1b4ddf541.png)
Nuevo aporte, sintetizando la idea de @isahq23

**Comment by ivonnesantos** [comment]
@arnaldos propuestas basándose en la aprobada de isa 
![subapp_cryptocustomercommunity_iv-01](https://cloud.githubusercontent.com/assets/15238660/11504220/6539e874-9816-11e5-9878-3722da539147.png)

**Comment by arnaldos** [comment]
@ivonnesantos no estoy muy convencido de la síntesis de los usuarios, prueba otra versión plz

**Comment by ivonnesantos** [comment]
@arnaldos 
![subapp_cryptocustomercommunity_iv-01](https://cloud.githubusercontent.com/assets/15238660/11509661/921767fc-9831-11e5-99be-5c415aee3c54.png)

**Comment by arnaldos** [comment]
propuesta 6 :+1:

**Comment by victoralfonzohd** [comment]
@arnaldos 

Propuesta 1:

![crypto_customer_identity1](https://cloud.githubusercontent.com/assets/15219855/12040265/c8f79c92-ae39-11e5-99ac-76b28851e4bf.png)

Versión sin costuras: 

![crypto_customer_identitys1](https://cloud.githubusercontent.com/assets/15219855/12040320/44d73ca0-ae3a-11e5-8a19-54111c6061eb.png)

Propuesta 2:

![crypto_customer_community](https://cloud.githubusercontent.com/assets/15219855/12040247/900594fc-ae39-11e5-933e-4b9080c9a8be.png)

Versión sin costuras: 

![crypto_customer_identitys2](https://cloud.githubusercontent.com/assets/15219855/12040327/5052cd9c-ae3a-11e5-88f2-259214ecceee.png)

**Comment by arnaldos** [comment]
@victoralfonzohd  propuesta 2 :+1:

**Comment by arnaldos** [comment]
la de las costuras
