### ISSUE TITLE
Crear icono para la SubApp Intra user Identity

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#176]
Viene del #175

La subaplicación **Identity**, tal como su nombre lo indica, permite a los actores crear identidades; con las cuales pueden realizar diferentes acciones dentro de la plataforma. 

Un actor es una persona o figura que realiza algún tipo de acción dentro de la plataforma Fermat.

**User** Una persona que utiliza una computadora. Esto incluye expertos programadores, así como los principiantes. Un usuario final es cualquier persona que corre un aplicación del programa.

**Intra User** se define al propio usuario 

**Intra user Identity** aplicación que permite crear identidades a los usuarios.

**Requisitos**

Archivo PNG de 32 bits (alpha)
Tamaño: 512 x 512 píxeles
Tamaño máximo del archivo: 1024 KB

Una vez elegido el icono, es necesario generar los tamaños, en **.PNG** para aplicarlos en lo siguientes:

**IC launcher**:

48 × 48 px (mdpi)
72 × 72 px (hdpi)
96 × 96 px (xhdpi)
144 × 144 px (xxhdpi)
192 × 192 px (xxxhdpi)
512 × 512 px (Wallet store)

**Comment by victoralfonzohd** [comment]
@Luis-Fernando-Molina @arnaldos Propuesta 1 para Icono de SubApp Intra user Identity, como concepto pense en usar una huella digital que es algo que representa totalmente lo que es una Identidad, Cada huella sera unica para el usuario al igual que la accion que realicé dentro de la app.
#176

![app_intrauseridentity_p1-01](https://cloud.githubusercontent.com/assets/15219855/10800662/31fb0e30-7d85-11e5-9167-32b60e7f3977.png)

**Comment by victoralfonzohd** [comment]
@Luis-Fernando-Molina @arnaldos El mismo concepto pudiese funcionar para la SubApp Intra user Community #177

**Comment by victoralfonzohd** [comment]
@Luis-Fernando-Molina @arnaldos En estas propuestas hice una sintesis del usuario y de la forma del dedo (Huella) Siguiendo el concepto de la propuesta 1. #176 

Propuesta 2 ![app_intrauseridentity_p2-01-01](https://cloud.githubusercontent.com/assets/15219855/10771667/2864a2e4-7cc4-11e5-8a0b-f56d5ee576ab.png)

Propuesta 3 ![app_intrauseridentity_p3-01-01-01](https://cloud.githubusercontent.com/assets/15219855/10771671/2caa9a8e-7cc4-11e5-87e5-e28aae77390f.png)

**Comment by Luis-Fernando-Molina** [comment]
Se va a llamar Wallet User Community, con lo cual pueden refinar la idea a partir de saber que se trata de un usuario de wallet.

**Comment by Luis-Fernando-Molina** [comment]
Ami se me ocurre una variante del logo de Fermat donde en vez de tener tres pequeñas billeteras encima, tengan tres personitas, con los mismos colores, y con costuras para mantener la semejanza.

**Comment by Luis-Fernando-Molina** [comment]
En el comentario anterio me referia a la Wallet User Community no a la Wallet User Identity al cual se refiere este caso. Sorry.

**Comment by victoralfonzohd** [comment]
@Luis-Fernando-Molina Probe usando la misma idea usar el Wallet de Fermat y el icono del usuario.

Propuesta 1

![intrauseridentity_p1_c2-01](https://cloud.githubusercontent.com/assets/15219855/10801030/7ef00734-7d87-11e5-967e-bf8df5ebd295.png)

Propuesta 2

![intrauseridentity_p2_c2-01](https://cloud.githubusercontent.com/assets/15219855/10801039/85c36880-7d87-11e5-9ad5-9fa24fa0cef4.png)

**Comment by Luis-Fernando-Molina** [comment]
@victoralfonzohd puede andar por ese lado. Revisa la wallet que no se ve igual a la que ya tenemos. Y mostrá otras variantes.

**Comment by victoralfonzohd** [comment]
@Luis-Fernando-Molina  Modificacion del wallet

Propuesta 1

![app_intrauseridentity_p-3](https://cloud.githubusercontent.com/assets/15219855/10831754/96e48734-7e59-11e5-8be7-aa76e01e2a72.png)

Propuesta 2
![app_intrauseridentity_p-2](https://cloud.githubusercontent.com/assets/15219855/10831758/99ea9fea-7e59-11e5-847c-345795b07cb8.png)

**Comment by Luis-Fernando-Molina** [comment]
Vamos con la propuesta 2, con la gente arriba. Fijate si podes poner 3 de los mismos colores que el logo de fermat y en la misma posiciones que las wallets chiquitas de ese logo.

Proba tambien hacerle costuras a las personitas.

**Comment by victoralfonzohd** [comment]
@Luis-Fernando-Molina Agregue al personaje faltante, hay un cambio en la posicion de los personajes en una de ellas tienen la inclinacion de los wallets pequeños del logo de fermat, en la otra los personjes estan totalmente verticales

Propuesta 1

![icono_intra_user_identity_p2](https://cloud.githubusercontent.com/assets/15219855/10849970/7c1eba9a-7ef5-11e5-9e5f-fb5e171abf23.png)

Propuesta 2 Aquí agregue los detalles de costura a los personajes, lo hice de esta manera para darles un poco mas de volumen

![icono_intra_user_identity_p3](https://cloud.githubusercontent.com/assets/15219855/10850066/e07ff404-7ef5-11e5-8efe-8520d2c6f22d.png)

**Comment by victoralfonzohd** [comment]
@Luis-Fernando-Molina Propuesta, cambie la posición de la costura 

![icono_intra_user_identity_2](https://cloud.githubusercontent.com/assets/15219855/10897958/2e45faea-8198-11e5-8183-7c02f2583387.png)

Tamaño Icono:

![sin-titulo-1](https://cloud.githubusercontent.com/assets/15219855/10897987/76aca2b6-8198-11e5-9420-a8231bdb2b83.png)

En dispositivo móvil:

![a60123e4-8156-11e5-8036-a4e48a0ffe00](https://cloud.githubusercontent.com/assets/15219855/10897997/8e5a14ca-8198-11e5-83c2-6859bd2a43c7.png)

**Comment by Luis-Fernando-Molina** [comment]
No me parece que las personitas vayan cambiando de tamaño. Ponelas del mismo tamaño y rotadas igual que las wallets del logo de fermat plase.

**Comment by victoralfonzohd** [comment]
@Luis-Fernando-Molina 

![icono_intra_user_identity_4](https://cloud.githubusercontent.com/assets/15219855/10898655/d4a3943c-819e-11e5-9282-f16c5fec957d.png)

**Comment by victoralfonzohd** [comment]
@Luis-Fernando-Molina Como vamos con este caso?

**Comment by arnaldos** [comment]
@victoralfonzohd aprobado el icono sube los fuentes al repo !!!

**Comment by victoralfonzohd** [comment]
@arnaldos Perfecto, voy a crear todos los formatos para subirlos al repo

**Comment by emmysm** [comment]
![intra user identity](https://cloud.githubusercontent.com/assets/15143489/11888213/6b966c66-a50d-11e5-8e92-1a9c056865ad.png)

@arnaldos @Luis-Fernando-Molina

**Comment by emmysm** [comment]
![screen crypto customer identity](https://cloud.githubusercontent.com/assets/15143489/11888353/aa41d648-a50e-11e5-9db3-34686d099463.png)

**Comment by emmysm** [comment]
![screen crypto customer identity](https://cloud.githubusercontent.com/assets/15143489/11888500/779b4a7e-a510-11e5-8c38-38b80c7aec5d.png)

![sin titulo-4](https://cloud.githubusercontent.com/assets/15143489/11888490/43364428-a510-11e5-81ff-a9448c6a00e5.png)
@arnaldos

**Comment by arnaldos** [comment]
@emmysm prueba usar como base el plano de la bitcoin wallet y al usuario en blanco para probar como se ve igual para la comunity

**Comment by emmysm** [comment]
![intra user identity-01](https://cloud.githubusercontent.com/assets/15143489/11908008/c8e6e146-a5aa-11e5-8a90-b3e6445e3da1.png)
@arnaldos  @Luis-Fernando-Molina

**Comment by emmysm** [comment]
![intra user community e identity-02](https://cloud.githubusercontent.com/assets/15143489/11915262/d7b330fa-a670-11e5-9e0e-c745e7a336f0.png)

@arnaldos

**Comment by victoralfonzohd** [comment]
@arnaldos  

Propuesta 1:

![sin-titulo-1](https://cloud.githubusercontent.com/assets/15219855/12021799/e46a3d4c-ad5b-11e5-943a-22f743078c6c.jpg)

**Comment by victoralfonzohd** [comment]
@arnaldos  @Luis-Fernando-Molina 

Propuesta 2:

Version 1:

![bit-coin-wallet](https://cloud.githubusercontent.com/assets/15219855/12024590/b947e1ac-ad77-11e5-927c-77a6d1f94c34.png)

Version 2:

![bit-coin-wallet1](https://cloud.githubusercontent.com/assets/15219855/12024547/6296be64-ad77-11e5-8b5a-d78f07c74dda.png)

**Comment by arnaldos** [comment]
toma la version 2 como base y donde estan las monedas sustituyelas por mascaras del mismo tamaño de las monedas

**Comment by victoralfonzohd** [comment]
@arnaldos 

![intra-usser-identity](https://cloud.githubusercontent.com/assets/15219855/12025242/bc6495cc-ad7e-11e5-85b4-d989c1388e83.png)

**Comment by arnaldos** [comment]
@victoralfonzohd revisa que todas las mascaritas tengan el mismo angulo de inclinación y el tono verde sea el mismo que se uso en las monedas, no se si es por el tono gris que tiene al lado hae que se vea mas claro revisa eso plz.

**Comment by victoralfonzohd** [comment]
@arnaldos 

El color es el mismo Arnaldo, se ve mas claro por que no lo vemos como un tono principal el color blanco de la mascara se roba la fuerza del color verde.. En las monedas este color tiene mas espacio para el por lo que se ve mas marcado.

Corrección en el angulo de las mascaras:

![intra-usser-identity](https://cloud.githubusercontent.com/assets/15219855/12036953/e04b6fd0-ae1c-11e5-95d2-14394ead3ea5.png)

**Comment by arnaldos** [comment]
@victoralfonzohd provemos con la versión 2 de las monedas ... genera las imagenes y pasale a matias probemos que tal se ven ya en la app.
