### ISSUE TITLE
Crear icono para la SubApp Intra user Community

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#177]
Viene del #175 

La subaplicación **Community** permite que los actores, a través de sus identidades, interactúen entre ellos. Existe una por cada tipo de actor.

Un actor es una persona o figura que realiza algún tipo de acción dentro de la plataforma Fermat.

**User** Una persona que utiliza una computadora. Esto incluye expertos programadores, así como los principiantes. Un usuario final es cualquier persona que corre un aplicación del programa.

**Intra User** se define al propio usuario

**Intra user Community** Es la aplicación que permite el intercambio o interacción entre usuarios.

**Requisitos**

Archivo PNG de 32 bits (alpha)
Tamaño: 512 x 512 píxeles
Tamaño máximo del archivo: 1024 KB

Una vez elegido el icono, es necesario generar los tamaños, en **.PNG** para aplicarlos en lo siguientes:

**IC launcher**:

48 × 48 px (mdpi)
72 × 72 px (hdpi)
96 × 96 px (xhdpi)
144 × 144 px (xxhdpi)
192 × 192 px (xxxhdpi)
512 × 512 px (Wallet store)

**Comment by isahq23** [comment]
@arnaldos @Luis-Fernando-Molina propuestas para el icono Intra User Community 

Propuesta 1
![intra_user_community_icons_1](https://cloud.githubusercontent.com/assets/15214774/10764646/5a1820ea-7ca1-11e5-9a85-554ed6c4f9be.jpg)

Propuesta 2
![intra_user_community_icons_2](https://cloud.githubusercontent.com/assets/15214774/10764651/60e877e4-7ca1-11e5-84c5-96a93b06bde2.jpg)

Propuesta 3
![intra_user_community_icons_3](https://cloud.githubusercontent.com/assets/15214774/10764665/6c534708-7ca1-11e5-9dca-8ae6dd3df259.jpg)

Propuesta 4
![intra_user_community_icons_4](https://cloud.githubusercontent.com/assets/15214774/10764672/71ce010a-7ca1-11e5-8ae3-85fb5516cffb.jpg)

Propuesta 5
![intra_user_community_icons_5](https://cloud.githubusercontent.com/assets/15214774/10764679/76e2eac0-7ca1-11e5-9758-4eb14d93dbb4.jpg)

**Comment by arnaldos** [comment]
@isahq23 viendo las propuestas me gustaría que nos pudieses mostrar algo mas colorido, con mayor síntesis gráfica que nos permita identificar las bondades de la sub aplicación. 

No se que opines @Luis-Fernando-Molina ?

**Comment by Luis-Fernando-Molina** [comment]
Hay un problema con este caso y es que ya no se llama Intra User sino "Wallet User Community" . Representa a la aplicacion donde los usuarios de ese tipo de wallets pueden encontrar a otros usuarios.

Ami se me ocurre una variante del logo de Fermat donde en vez de tener tres pequeñas billeteras encima, tengan tres personitas, con los mismos colores, y con costuras para mantener la semejanza. Pero no tiene que ser necesariamente eso, es una idea.

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina para este Caso fue reflejado en el issue #138 de aquí se dio a conocer el nombre que se coloco. ya procedo a cambiar el nombre. a **Wallet User Community**

**Comment by isahq23** [comment]
@arnaldos @Luis-Fernando-Molina segunda ola de propuestas para el icono de Wallet User Community
Personalmente creo que manejar los mismos colores de Fermat y el estilo lineal fue una excelente idea, mantener el estilo en una marca es muy importante.

Propuesta 1
![wallet_user_community_icon_2-1](https://cloud.githubusercontent.com/assets/15214774/10794095/bbcd2be0-7d65-11e5-959a-ad85cc107c63.png)

Propuesta 2
![wallet_user_community_icon_2-2](https://cloud.githubusercontent.com/assets/15214774/10794099/c1e5cd8e-7d65-11e5-9704-724ee9565df1.png)

Propuesta 3
![wallet_user_community_icon_2-3](https://cloud.githubusercontent.com/assets/15214774/10794104/c7ddccd2-7d65-11e5-9d9c-f23db4e29457.png)

Propuesta 4
![wallet_user_community_icon_2-4](https://cloud.githubusercontent.com/assets/15214774/10794117/d6207682-7d65-11e5-862d-9f384f9e2e78.png)

**Comment by arnaldos** [comment]
Aclaro los puntos sobre el caso que estamos tratando es una Sub App que permite las conexiones entre dispositivos, para que una persona pueda conectarse con otros usuarios. esto define a la **Intra user Community**

**Comment by Luis-Fernando-Molina** [comment]
OMG quizás cree una confusión sin darme cuenta. Cuando dije "wallet user community" no me refería a que era una wallet. Es una sub app como dice @arnaldos , solo que "Intra User" lo vamos a llamar "wallet user". Sorry si confundí :smile:

**Comment by isahq23** [comment]
Muy bien, duda aclarada. Finalmente, qué opinan de las nuevas propuestas?

**Comment by arnaldos** [comment]
@isahq23 para esta aplicación podrías usar elementos que refleje la conexión entre usuarios ejemplo  unas flechas invertidas y al extremo los usuarios, algo que refeje la bondad de la App. 

Por otro lado te invito a usar otros tonos de colores no necesariamente debes usar los de Fermat. ya que cada una de las subapp son totalmente independientes y deben tener su propia identidad.

**Comment by jurene22** [comment]
@Luis-Fernando-Molina @arnaldos aqui un aporte mas
![icon-subapp_intra_user_community_issue177_version_1](https://cloud.githubusercontent.com/assets/15174317/10850083/f8f59e9e-7ef5-11e5-8dbb-c42a40a5bba2.png)
Versión 1

**Comment by isahq23** [comment]
@arnaldos Nuevos aportes con la simbologia de flechas que conectan a los usuarios

Prop 3-1
![wallet_user_community_icon_3-1](https://cloud.githubusercontent.com/assets/15214774/10851455/5949cfa2-7efd-11e5-8997-f6aa82138cf6.png)

Prop 3-2
![wallet_user_community_icon_3-2](https://cloud.githubusercontent.com/assets/15214774/10851458/5f030f44-7efd-11e5-84d7-6fa8b4fc0fb8.png)

Prop 3-3
![wallet_user_community_icon_3-3](https://cloud.githubusercontent.com/assets/15214774/10851463/64543446-7efd-11e5-9f72-1f4d7d672b54.png)

**Comment by jurene22** [comment]
![icon-subapp_intra_user_community_issue177_version_2](https://cloud.githubusercontent.com/assets/15174317/10856897/034357d4-7f1d-11e5-8a47-f5c23e7322d1.png)
Versión 2

**Comment by Luis-Fernando-Molina** [comment]
hola @jurene22  los diseños de iconos solo los reviso en su tamaño target desde ahora, para evitar aprobar cosas que muy chiquitas no se verian. Preguntale a @arnaldos cual es el target y como mostrarlos. Gracias

@arnaldos agrega esto que dije a los procedimientos del README please.

**Comment by jurene22** [comment]
![vista target issue 177](https://cloud.githubusercontent.com/assets/15174317/10886158/07349fa0-8153-11e5-8b38-b43757edf707.png)
@Luis-Fernando-Molina Icon ubicado en target solicitado

**Comment by Luis-Fernando-Molina** [comment]
Mas opciones por favor, gracias.

**Comment by MelissaDugarte** [comment]
@Luis-Fernando-Molina 
Icono
![crear icono para la subapp intra user community 177_issue_1](https://cloud.githubusercontent.com/assets/15186093/10924624/2db5834e-825a-11e5-9dcd-31aed081e388.jpg)

version 1
![desktop1](https://cloud.githubusercontent.com/assets/15186093/10924620/2543202c-825a-11e5-96e8-78103e855dec.jpg)

**Comment by Luis-Fernando-Molina** [comment]
Mas--

**Comment by MelissaDugarte** [comment]
@Luis-Fernando-Molina 

Versión 2 Crear icono para la SubApp Intra user Community #177
Icono
![crear icono para la subapp intra user community 177_issue_2](https://cloud.githubusercontent.com/assets/15186093/10956351/328bf56e-832d-11e5-95fc-72bac7563967.jpg)
![desktop2-01](https://cloud.githubusercontent.com/assets/15186093/10956557/afb79e3e-832e-11e5-8657-b571677d4f2d.jpg)

Version 3 Crear icono para la SubApp Intra user Community #177
Icono
![crear icono para la subapp intra user community 177_issue_3](https://cloud.githubusercontent.com/assets/15186093/10956354/353f1d5e-832d-11e5-85be-356d516b2da3.jpg)
![desktop3-01](https://cloud.githubusercontent.com/assets/15186093/10956508/6eaf0e2c-832e-11e5-8f99-0132dc1d6fa6.jpg)

**Comment by Luis-Fernando-Molina** [comment]
mas opciones

**Comment by jurene22** [comment]
![icon-subapp_intra_user_community_issue177_version 3](https://cloud.githubusercontent.com/assets/15174317/11035030/e4d3d664-86c1-11e5-9730-d28de77b6512.png)
![vista target](https://cloud.githubusercontent.com/assets/15174317/11035031/e993f152-86c1-11e5-9569-54e5a63cbd22.png)
@Luis-Fernando-Molina Versión 3

**Comment by Luis-Fernando-Molina** [comment]
mas opciones please

**Comment by isahq23** [comment]
@arnaldos @Luis-Fernando-Molina 

Propuesta 1-1
![intra_user_com_1-1](https://cloud.githubusercontent.com/assets/15214774/11075572/06acda04-87c8-11e5-9bb3-8afd02dc961d.png)

Propuesta 1-2
![intra_user_com_1-2](https://cloud.githubusercontent.com/assets/15214774/11075575/0bc8e28a-87c8-11e5-8e4d-1918a6bd65a0.png)

Nexus1
![intra_user_com_nexus1](https://cloud.githubusercontent.com/assets/15214774/11075580/12033376-87c8-11e5-97cc-f66b532959d9.png)

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina nuevas versiones enfocados en la comunidad que se mueve en el mundo del bitCoin dentro de fermat 

Versión 1

![issue-177-intra-user-community-as4](https://cloud.githubusercontent.com/assets/13594347/11224077/5f11f95e-8d45-11e5-937d-16c3a2000888.png)

![issue-177-intra-user-community-as](https://cloud.githubusercontent.com/assets/13594347/11224078/5f22876a-8d45-11e5-8e17-4f9f2da90f79.png)

Versión 2

![issue-177-intra-user-community-as2](https://cloud.githubusercontent.com/assets/13594347/11224110/81a00132-8d45-11e5-907f-81ebd6af0830.png)

![issue-177-intra-user-community-as5](https://cloud.githubusercontent.com/assets/13594347/11224109/819d9a82-8d45-11e5-9e17-de5bbbc85a31.png)

Versión 3

![issue-177-intra-user-community-as3](https://cloud.githubusercontent.com/assets/13594347/11224122/92ed0192-8d45-11e5-8172-981b3c7d1c8a.png)

![issue-177-intra-user-community-as6](https://cloud.githubusercontent.com/assets/13594347/11224123/92f323e2-8d45-11e5-852e-4b8bdb741406.png)

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina  de mis propuestas apunto por la versión 1

**Comment by ivonnesantos** [comment]
@arnaldos aca mi aporte
![issues 177 intra user community-01](https://cloud.githubusercontent.com/assets/15238660/11230396/bd6f521e-8d70-11e5-8466-9508bfb1ca44.png)

**Comment by jurene22** [comment]
![intra user community 177_ 4_5_6](https://cloud.githubusercontent.com/assets/15174317/11244279/f059c470-8dde-11e5-94c5-89bea6377182.png)
@Luis-Fernando-Molina Nuevos aportes

**Comment by jurene22** [comment]
![vista target](https://cloud.githubusercontent.com/assets/15174317/11244877/18e1020c-8de2-11e5-99d5-da1946be38ff.png)
Vista target

**Comment by arnaldos** [comment]
@jurene22  esta es la misma idea que planteo @victoralfonzohd para este caso Intra user Identity #176 cuidado con eso, plantea otra propuesta

**Comment by ivonnesantos** [comment]
@arnaldos 
![issues 177 intra user community-01](https://cloud.githubusercontent.com/assets/15238660/11251769/f885473e-8e04-11e5-9ad8-f5a1e5e3166c.png)

**Comment by victoralfonzohd** [comment]
@Luis-Fernando-Molina @arnaldos 

Propuesta:

![sin-titulo-1](https://cloud.githubusercontent.com/assets/15219855/11260336/52353a5a-8e3c-11e5-8f6b-869f0b512dc1.png)

Icono:

![intra-user-community](https://cloud.githubusercontent.com/assets/15219855/11260380/d3bda6de-8e3c-11e5-8dcd-1d23946477c1.png)

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina Intra user Community

![intra user community](https://cloud.githubusercontent.com/assets/13594347/11388066/da355f72-9303-11e5-9ee9-23fe981625b7.png)

**Comment by Luis-Fernando-Molina** [comment]
puede ser como provisional.

**Comment by emmysm** [comment]
![sin titulo-3](https://cloud.githubusercontent.com/assets/15143489/11888409/34edcda6-a50f-11e5-8cb2-3883e8c0c6bf.png)

**Comment by emmysm** [comment]
![sin titulo-3-03](https://cloud.githubusercontent.com/assets/15143489/11904867/3668a4fe-a595-11e5-9081-1933daff4b02.png)
![sin titulo-3-02](https://cloud.githubusercontent.com/assets/15143489/11904868/3690c1b4-a595-11e5-911f-601b52fca6b4.png)
![sin titulo-3-01](https://cloud.githubusercontent.com/assets/15143489/11904870/38ec950a-a595-11e5-968b-736881085bd0.png)

@arnaldos

**Comment by emmysm** [comment]
![sin titulo-3-02](https://cloud.githubusercontent.com/assets/15143489/11905018/ff8f0d1e-a595-11e5-9901-0cb0cd06cca4.png)
@arnaldos

**Comment by emmysm** [comment]
![sin titulo-2](https://cloud.githubusercontent.com/assets/15143489/11906999/bc3995ae-a5a2-11e5-8732-ebe959ca65ac.png)
@arnaldos

**Comment by emmysm** [comment]
![propuesta de color-01](https://cloud.githubusercontent.com/assets/15143489/11907728/a90358c0-a5a8-11e5-85ac-cef9e93125fd.png)

**Comment by emmysm** [comment]
![intra user community-01](https://cloud.githubusercontent.com/assets/15143489/11915261/c86d9bc6-a670-11e5-8e5f-046ed3d111ff.png)
@arnaldos

**Comment by arnaldos** [comment]
colócalo con el fondo griss y el marco azul plz a ver que tal se ven

**Comment by emmysm** [comment]
![intra-user-community-](https://cloud.githubusercontent.com/assets/15143489/11915826/502e8e8a-a68a-11e5-8ae8-d98cd2889d2e.png)

**Comment by arnaldos** [comment]
@emmysm :+1:

**Comment by victoralfonzohd** [comment]
@arnaldos 

Propuesta 1:

![intra-usser-identity](https://cloud.githubusercontent.com/assets/15219855/12039187/79ba5bc8-ae30-11e5-827f-828199fc7308.png)

Propuesta 2: 

![intra-usser-identity](https://cloud.githubusercontent.com/assets/15219855/12039364/0404a2ba-ae32-11e5-9f4b-53a91e1d770c.png)

Propuesta 3:

![intra-usser-identity2](https://cloud.githubusercontent.com/assets/15219855/12039528/898bef96-ae33-11e5-9185-38c95dff6d16.png)

**Comment by victoralfonzohd** [comment]
@arnaldos 

Propuesta 4:

![intra-usser-identity](https://cloud.githubusercontent.com/assets/15219855/12039435/a0c7ab4c-ae32-11e5-9f69-1aff7676a406.png)

Propuesta 5: 
![intra-usser-identity1](https://cloud.githubusercontent.com/assets/15219855/12039493/2961a570-ae33-11e5-9054-6df20e778424.png)

**Comment by arnaldos** [comment]
propuesta 3
