### ISSUE TITLE
Logo para el equipo CoinDiggers

### ISSUE THREAD

**Issue by m471c4** [bitDubai/fermat-graphic-design#178]
Viene del #167

@furszy @lnacosta, en este issue haremos el briefing y discutiremos brevemente cómo quisieran representar su equipo, este logo será utilizado inicialmente en las portadas de las reuniones.

Pueden participarle a los demás miembros del equipo.

**Comment by Luis-Fernando-Molina** [comment]
En este caso debería ser solo @lnacosta ya que @furszy tiene su propio equipo ahora. Creale un caso independiente para el por favor.

**Comment by furszy** [comment]
Ok, voy a incluir a mi equipo ya que esto va a ser entre todos.
@nattyco @Exilum @wildeivid @josemanueldsds .

**Comment by arnaldos** [comment]
@furszy @nattyco @Exilum @wildeivid @josemanueldsds cuando puedan ayuden nos a conceptualizar lo que desean transmitir en el logo del equipo. :smile:

**Comment by furszy** [comment]
Estamos en reunión para definir el nuevo nombre del equipo, ya que tuvimos grandes cambios en la conformación del equipo.

**Comment by furszy** [comment]
El nuevo nombre del Team, será:

### CoinDiggers

Desde acá en más vamos a ir charlando el logo por aqui

**Comment by arnaldos** [comment]
@bitDubai/graphic-design-selection los invito a participar en este issue :smile:

**Comment by m471c4** [comment]
@Luis-Fernando-Molina @furszy @arnaldos @nattyco @Exilum @wildeivid @josemanueldsds acá una primera versión del logo para los CoinDiggers :)

Utilicé el brazo de una retroexcavadora, no hay mucho más que decir al respecto. Aun no estoy segura del uso del Bitcoin, no se si prefieren algún orto tipo de currency. En fin, se aceptan comentarios, sugerencias, lo que sea.

![coindiggers1](https://cloud.githubusercontent.com/assets/13468350/10991633/0ed877fa-8431-11e5-9788-ac2962191342.png)

**Comment by MelissaDugarte** [comment]
@Luis-Fernando-Molina @furszy @arnaldos @nattyco @Exilum @wildeivid @josemanueldsds 
Version logo  coin diggers yo según mi propuesta trabaje la excavación como tal por eso incluí el elemento tierra y un hoyo  sobre las cuales se muestran unos coins obteniendo como resultado final la salida de las monedas individuales
![logo coindiggers](https://cloud.githubusercontent.com/assets/15186093/11009428/f83f78cc-84a8-11e5-8fe0-607d2421e8e0.jpg)

**Comment by furszy** [comment]
Están buenos, pero siento como que necesitan fuerza . podrían darle un poco de calidad a estos y mezclarlos con algo nuestro y quizás un aguila en algún lado :

![bitcoin-miner](https://cloud.githubusercontent.com/assets/5377650/11011072/57aed8d8-84c3-11e5-8d8f-383b675930d1.jpg)

---

![bitcoinmining](https://cloud.githubusercontent.com/assets/5377650/11011077/5fc9fc32-84c3-11e5-848d-449cb8de5fbd.jpg)

**Comment by nattyco** [comment]
Me gustan las propuestas deMatias

**Comment by MelissaDugarte** [comment]
@Luis-Fernando-Molina @furszy @arnaldos @nattyco @Exilum @wildeivid @josemanueldsds

Segun las imagenes y sugerencias se me ocurrio esto a ver 
![logo coindiggers](https://cloud.githubusercontent.com/assets/15186093/11012873/988a1d4a-84cd-11e5-839f-7e1ee4e5cd2a.jpg)

**Comment by emmysm** [comment]
![coindiggers](https://cloud.githubusercontent.com/assets/15143489/11013291/2c34a528-84d9-11e5-9954-74e6e9c29c98.png)

Según los requerimientos de @furszy ilustré un águila, con elementos de excavación y moneditas de bitcoin al fondo.

**Comment by furszy** [comment]
Que buena onda!.
Me gustó la última propuesta, podrías hacer un cambio en las monedas que quedan como forzadas y como otra opción intentarlo vectorizado y menos caricaturesco haber como queda?.
Muchas gracias son lo más!.

**Comment by emmysm** [comment]
Hola, Matias! Sí, voy a hacer una sintesis de esta y a pedirle recomendaciones a @jonathanborges3d  para que sea llevado a 3D. Haré los ajustes que me pides, @furszy gracias :D

**Comment by Luis-Fernando-Molina** [comment]
@emmysm Jonahtan interviene cuando ya esta en version final, terminado y aprobado. saludos

**Comment by emmysm** [comment]
Sí, lo tenía entendido, y es bueno que se recalque esto por aca. De igual forma me gustarían algunas recomendaciones o sugerencias por su parte para presentar mi próxima propuesta, @Luis-Fernando-Molina  Saludos ;)

**Comment by jonathanborges3d** [comment]
@emmysm Se ve muy bien! Puedo recomendarte lo siguiente pensando en la versi{on final y en 3D:

1) Generalmente se llevan a una versión moneda, así que la forma circular va bien. Procura mantenerla.
2) Estoy de acuerdo con @furszy, si se vectoriza un poco será mucho mejor llevarlo a 3D
3) Cuando subas la versión final al repositorio, por favor incluye la tipografía si estás usando alguna en particular.

**Comment by victoralfonzohd** [comment]
@Luis-Fernando-Molina @furszy @arnaldos @nattyco @Exilum @wildeivid @josemanueldsds  Propuesta de logo para el equipo Coin diggers, basándome en los elementos pedidos por @furszy

![coin diggers](https://cloud.githubusercontent.com/assets/15219855/11036490/05b34096-86cb-11e5-8f98-bbe4e826341a.png)

**Comment by emmysm** [comment]
![coinsdiggers 3](https://cloud.githubusercontent.com/assets/15143489/11044704/a43cde1e-86f5-11e5-8a58-52e1f42c0451.png)

**Comment by isahq23** [comment]
@arnaldos @Luis-Fernando-Molina 
Aportes para el logo de CoinDiggers

Propuesta 1-1
![logo_coindiggers_1-1](https://cloud.githubusercontent.com/assets/15214774/11046721/222a6886-8701-11e5-9258-b71695783f7c.png)

Propuesta 1-2
![logo_coindiggers_1-2](https://cloud.githubusercontent.com/assets/15214774/11046724/274f4ed0-8701-11e5-87e8-ab2a2cd011ab.png)

**Comment by Luis-Fernando-Molina** [comment]
que decida @bitDubai/malo-team o como quiera que se llamen ahora :smile:

**Comment by arnaldos** [comment]
@furszy Aquí les subo una propuesta nueva, espero les guste :smile: 

**Versión 9**

![logo-coindiggers-1](https://cloud.githubusercontent.com/assets/13594347/11083139/17ad97ae-87fe-11e5-963a-e3c90e513338.jpg)

**Comment by furszy** [comment]
Sos demasiado capo. Logo Elegido :smile: :smile:

**Comment by arnaldos** [comment]
@furszy gracias !!! ya subo los editables para que @jonathanborges3d haga su magia. :smile:

**Comment by arnaldos** [comment]
@furszy un wallpaper 

![logo-coindiggers-1](https://cloud.githubusercontent.com/assets/13594347/11161999/6d16609a-8a60-11e5-8fa2-e4b9d2f6c080.jpg)

![logo-coindiggers-2](https://cloud.githubusercontent.com/assets/13594347/11162000/6d1df4ae-8a60-11e5-9416-2f8004432f87.jpg)

**Comment by furszy** [comment]
@arnaldos podrías hacer uno con un fondo con el estilo parecido a los desktops que ofrece ubuntu?
Gracias!

**Comment by jonathanborges3d** [comment]
@Luis-Fernando-Molina @bitDubai/coin-diggers-team  Primera versión 3D del logo:

![coindiggers_1](https://cloud.githubusercontent.com/assets/13649739/12008616/653191f8-ac19-11e5-91b9-f25f2bfb5ca4.jpg)

**Comment by Luis-Fernando-Molina** [comment]
ok llevalo a moneda plase

**Comment by jonathanborges3d** [comment]
@Luis-Fernando-Molina Segunda versión:

![coindiggers_2](https://cloud.githubusercontent.com/assets/13649739/12011401/249ce87a-ac9d-11e5-8034-77956b1346fd.jpg)

**Comment by Luis-Fernando-Molina** [comment]
ok, aplicale lo mismo que a la anterior asi estandarizamos. (cobre con patterns)

**Comment by jonathanborges3d** [comment]
@Luis-Fernando-Molina Con los cambios:
![coindiggers_3](https://cloud.githubusercontent.com/assets/13649739/12011856/454db1ac-acb2-11e5-86a1-372a1ab2c1ac.jpg)

**Comment by Luis-Fernando-Molina** [comment]
el fondo era con cada segunda linea desplazada , como una pared de ladrillos

**Comment by jonathanborges3d** [comment]
@Luis-Fernando-Molina Corregido. Lo hice un poco más grande para que se note mejor.

![coindiggers_4](https://cloud.githubusercontent.com/assets/13649739/12023170/e91232b6-ad68-11e5-992c-f4f0cdeb5ceb.jpg)

**Comment by Luis-Fernando-Molina** [comment]
ok listo, enviala al media kit y al READ Me please. Fijate en el readme que se habia borrado el nombre del equipo.
