### ISSUE TITLE
Logo para el equipo Thunder

### ISSUE THREAD

**Issue by m471c4** [bitDubai/fermat-graphic-design#179]
Viene del #167

@acostarodrigo, en este issue haremos el briefing y discutiremos brevemente cómo quisieran representar su equipo, este logo será utilizado inicialmente en las portadas de las reuniones.

Puedes participarle a los demás miembros del equipo.

**Comment by arnaldos** [comment]
@acostarodrigo  nos comenta que el nombre del equipo thunders, es  por los thundercats... originalmente el nombre fue los thunder coins...pero parecía una alternative coin, por lo tanto quedo solo  **thunder**

A lo que el quiere el logo de la moneda de fermat y el de los thunder cats en frente por ejemplo

**Comment by Luis-Fernando-Molina** [comment]
Invitemos a los miembros edl equipo @bitDubai/thunder-team a que tiren ideas sobre como debiera ser su logo.

**Comment by darkestpriest** [comment]
Yo me imagino algo como la billetera de Fermat con la imagen de un felino corriendo o en posición de ataque.

**Comment by franklinmarcano1970** [comment]
La billetera de fermat y la foto de thunderscat....

**Comment by darkestpriest** [comment]
¿No habrá problemas de Copyright si usamos el logo de los thundercats? Otra idea, u rayo cayendo, que no se parezca al rayo de The Flash, y en el medio del rayo, la billetera de Fermat. O, una billetera de Fermat, con un rayo en el medio.

**Comment by nindriago** [comment]
mmmm, si puede ser el logo de una wallet, con un Rayo en ella, claro no estilo Flah, pensaba en un Dios asi como ZEUS pero seria demasiado copia... pero de que tiene que ir un Rayo, tiene que ir xD

El que queda aca es una Moneda y un Rayo, pero es practicamente la insignia de Hercules en la pelicula de Disney xD

pero si, debemos combinar.
- Coin
- Rayo
- Wallet

**Comment by acostarodrigo** [comment]
otra opción podria ser algo similar a la imagen pero lo que se refleja sea la monea de Fermat
![image](https://cloud.githubusercontent.com/assets/9518556/10760801/289bd72c-7c9d-11e5-8fed-471938b41ecc.png)

**Comment by franklinmarcano1970** [comment]
Jajajajaja, Esta bueno lo de chetara, @acostarodrigo, me parece bien el logo y en el fondo lo de fermat...

**Comment by nindriago** [comment]
![retro-zeus-holding-a-thunder-bolt-in-blue-white-and-yellow-by--476712](https://cloud.githubusercontent.com/assets/13187461/10760995/79bea6f4-7c91-11e5-884b-16b2b538982a.jpg)
![thundercats_large](https://cloud.githubusercontent.com/assets/13187461/10760996/79c9c0a2-7c91-11e5-83d1-8286c781536a.jpg)

una fusion aca jajajaja

**Comment by javafrank** [comment]
Yo voto por el rayo y algo que tenga que ver con bitcoin o de fermat como
tal.

Saludos equipo,

**Comment by campol** [comment]
seria bueno una version animada de cada miembro del equipo y todos juntos
sosteniendo un bitcoin con el logotipo de fermat

2015-10-27 20:40 GMT-04:30 Frank Contreras notifications@github.com:

**Comment by darkestpriest** [comment]
¿y si ponemos el relámpago del catatumbo? Ya que la mayoría de los miembros del equipo son del Estado Zulia.
![image](https://cloud.githubusercontent.com/assets/10060413/10806547/7181db60-7da8-11e5-9004-8baa10d428e9.png)

https://es.wikipedia.org/wiki/Rel%C3%A1mpago_del_Catatumbo

**Comment by arnaldos** [comment]
@bitDubai/thunder-team les comparto las primeras propuestas del logo de thunder

Versión 1
![logo-thunder-1](https://cloud.githubusercontent.com/assets/13594347/10928299/70abadbc-8279-11e5-99d7-dfc21d7f1d77.png)

Versión 2
![logo-thunder-2](https://cloud.githubusercontent.com/assets/13594347/10928300/70d04aa0-8279-11e5-8fe9-2a0f4448fad8.png)

Versión 3
![logo-thunder-3](https://cloud.githubusercontent.com/assets/13594347/10928301/70d18712-8279-11e5-87ef-d5d0f0b15241.png)

**Comment by franklinmarcano1970** [comment]
Voto por la Version 1

**Comment by darkestpriest** [comment]
Mi voto es para la Versión 1.

**Comment by javafrank** [comment]
Versión 1 también

2015-11-03 22:32 GMT-04:30 Manuel Pérez notifications@github.com:

**Comment by acostarodrigo** [comment]
muy buenas!
el mio tambien para el 1

**Comment by nindriago** [comment]
Sublime... se ve genial el 1ero es cierto, parece que es unanime :+1:

**Comment by arnaldos** [comment]
@acostarodrigo plz confirmarme si nos quedamos con la versión 1 ? :smiley_cat:

**Comment by arnaldos** [comment]
que opinan el reto del equipo ?

**Comment by acostarodrigo** [comment]
si, por votación cerramos con el 1

**Comment by arnaldos** [comment]
@acostarodrigo  perfecto !!!! entonces subo los fuentes al repo y cierro el caso !!!

**Comment by Luis-Fernando-Molina** [comment]
@jonathanborges3d aquí tenes otro input para tu arte. Si les hacés una moneda Thunder o una placa metálica mas de uno se vuelve loco acá....  :smile:  Ademas de eso agenda la version 3D tal cual está.

**Comment by arnaldos** [comment]
@nindriago aqui te comparto la imagen del logo a mayor resolución como me solicitaste :+1: 

![logo-thunder-1](https://cloud.githubusercontent.com/assets/13594347/10977876/17cab794-83c6-11e5-9f42-35d74b8a1583.png)

**Comment by nindriago** [comment]
Excelente, Gracias por el logo @arnaldos para El Equipo

**Comment by acostarodrigo** [comment]
El fondo de pantalla que todo el equipo esta usando...gracias @nindriago 
Vamos con el espíritu de equipo!
![forever_thunder](https://cloud.githubusercontent.com/assets/9518556/10978516/3167120a-83d6-11e5-8413-599c0d4aed38.jpg)

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina  ya subi los fuentes al repo !!! ya listo esto cierro el caso :+1:

**Comment by jonathanborges3d** [comment]
@bitDubai/thunder-team Versión 3D:

![thunder_logo_art](https://cloud.githubusercontent.com/assets/13649739/10988870/96f78dfc-8412-11e5-816f-ac216014201c.jpg)

**Comment by acostarodrigo** [comment]
muy bueno!

**Comment by franklinmarcano1970** [comment]
Como diria el camarada @darkestpriest quedo Mortal.

**Comment by darkestpriest** [comment]
¡Mortal, brutal y genial!

**Comment by jonathanborges3d** [comment]
Gracias! Todo el crédito a @arnaldos por la creación del logo :smile: :+1:

**Comment by nindriago** [comment]
se ve genial @jonathanborges3d  :+1:  como quedaria en una moneda ;) ?

**Comment by arnaldos** [comment]
abro el caso nuevamente para que @jonathanborges3d postee las solicitudes de las monedas

**Comment by Luis-Fernando-Molina** [comment]
@jonathanborges3d esa como version artistica puede ser, pero necesitamos la version ortogonal similar al logo de Fermat para poner en los ReadMe o donde corresponda . Gracias

**Comment by jonathanborges3d** [comment]
@bitDubai/thunder-team @Luis-Fernando-Molina Primera versión del logo en moneda:

![thnder_coin_1](https://cloud.githubusercontent.com/assets/13649739/11013611/a11c5a86-84e6-11e5-90d4-0d5e788a07ac.jpg)

**Comment by franklinmarcano1970** [comment]
Genial....

**Comment by acostarodrigo** [comment]
La tipografía de Thnuder no queda muy clara en la moneda me parece. Queda bien en 2D.
Quizás podrias separar un poco las letras dejando un poco más de espacio entre ellas?

**Comment by darkestpriest** [comment]
Brutal @jonathanborges3d

**Comment by nindriago** [comment]
se ve Genial @jonathanborges3d  haces buenos trabajos :+1:  

ah y es cierto veo que las letras en el "canto" de la moneda no se distinguen mucho, y creo que el nombre de "bitDubai" deberia ir mas bien en el otro lado de la moneda, aca solo deberia decir Team Thunder.

seria mucho pedir o si me explico bien jeje a ver, como se veria la moneda "parada" osea de canto pero a su vez con efecto de giro pero asi tan rapido que se vean los 2 lados de la moneda (no se si sera posible claro) - ojo solo es sugerencia ya que suena a mucho trabajo xD

**Comment by javafrank** [comment]
A mi me parece que puede mejorarse dejándose ver mejor la moneda con un
mejor ángulo, de resto está brutalisimo, buenisimo!

**Comment by Luis-Fernando-Molina** [comment]
@jonathanborges3d por favor usa fermat en vez de bitDubai. En este caso pudieras poner la palabra TEAM arriba y fermat a ambos costados.

De fondo proba aplicarle un patron formado por el logito (el tigre solo) en material cobre. 

Inventate algun otro tipo de dentado para el costado de estas monedas que representan los equipos. La palagra THUNDER en el costado pudiera er sutil en un sobre relive sobre el dentado.

**Comment by jonathanborges3d** [comment]
@Luis-Fernando-Molina @bitDubai/thunder-team Gracias por el feedback muchachos, he tratado de recopilar las opiniones y sugerencias de todos para mejora el modelo, a excepción de la última de @nindriago porque primero se debe definir cuál será la otra cara de la moneda, pero es una idea muy factible si se palican las técnicas fotográficas correctas.

Segunda versión:

![thnder_coin_2](https://cloud.githubusercontent.com/assets/13649739/11055120/dd647026-8745-11e5-8877-7f0839ee715b.jpg)

**Comment by Luis-Fernando-Molina** [comment]
El canto quedo muy bueno.

El patron sobre el cobre no deberia ser un cuadribulado, proba con otros patrones por favor. Quizas desplazada la segunda linea o no se, fijate.

Pone Fermat mas chico, similar a las otras menedas, y ponele una estrella entre cada palabra please.

Nota para @bitDubai/graphic-design-selection : El logo no puede tener demasiados detalles como para que en una moneda quede demasiado cargado. Acá se ha logrado un muy buen equilibrio poiendo la cada del tigre mezclada con el rayo. Tener en cuenta esto para los logos de los otros equipos por favor.

**Comment by franklinmarcano1970** [comment]
Mortal quedo excelente.

**Comment by campol** [comment]
quedo excelente

2015-11-10 10:56 GMT-04:30 Franklin Marcano notifications@github.com:

**Comment by mariavictoriapp** [comment]
Increible, que buen trabajo el de @arnaldos y @jonathanborges3d son unos "pranes" jaja! EXCELENTE

**Comment by arnaldos** [comment]
gracias @mariavictoriapp :smile:

**Comment by jonathanborges3d** [comment]
@bitDubai/thunder-team @Luis-Fernando-Molina Con los ajustes solicitados:

![thnder_coin_3](https://cloud.githubusercontent.com/assets/13649739/11138380/8f50d820-8993-11e5-867d-155ff1c91096.jpg)

Gracias @franklinmarcano1970, @campol y @mariavictoriapp, :+1:

**Comment by darkestpriest** [comment]
¡¡BRUTAL!!

**Comment by javafrank** [comment]
Quedó buenisimo, gran trabajo!

**Comment by Luis-Fernando-Molina** [comment]
@jonathanborges3d perfecto va muy bien. Probemos un par de cositas mas please: poner una estrella de cada lado entre fermat y Thunder, vas a tener que hacer un poquito de espacio, quizas reduciendo el tamaño de las estrellas de arriba. 2) proba el logo tileado de fondo que sea un poco mas grande, incluso mas grande que la opcion anterior a ver como queda. Gracias

**Comment by jonathanborges3d** [comment]
@Luis-Fernando-Molina Versión para el README:

![thnder_coin_5](https://cloud.githubusercontent.com/assets/13649739/12008565/17ee46dc-ac16-11e5-98a1-200eaa8e9180.jpg)

**Comment by Luis-Fernando-Molina** [comment]
ok pasalo al media kit y luego al dev readme reemplazando al que esta ahi please
