### ISSUE TITLE
Mejorar la diagramación de la lámina: Sustained Competitive Advantage

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#18]
Viene del #12 

En esta sección de la presentación, sugiero replantear el esquema explicativo de como funciona la plataforma, realizándola de forma mas ligera y fácil de entender, ya que en la forma de como esta planteada dificulta la lectura. 

![ima_1](https://cloud.githubusercontent.com/assets/13594347/9078238/dba8c544-3b04-11e5-9aea-213d12bdcf37.jpg)

**Comment by Luis-Fernando-Molina** [comment]
@arnaldos para poder discutir cada cosa mas fácilmente sería bueno que cada slide se corresponda con un Issue. Pudieras dejar este issue para el primero y crear dos mas para los otros dos.

**Comment by m471c4** [comment]
Estoy de acuerdo. Hace falta mejorar la diagramación de los textos para evitar los rios (espacios entre palabras que son muy amplios y se repiten en varias líneas de un párrafo). 

Creo que esta es la lámina que presenta mayor problema. Crearé issues separados para las otras.

**Comment by Luis-Fernando-Molina** [comment]
:+1:
