### ISSUE TITLE
Logo para el equipo Nelson

### ISSUE THREAD

**Issue by m471c4** [bitDubai/fermat-graphic-design#180]
Viene del #167

@nelsonalfo, en este issue haremos el briefing y discutiremos brevemente cómo quisieran representar su equipo, este logo será utilizado inicialmente en las portadas de las reuniones.

Puedes participarle a los demás miembros del equipo.

**Comment by nelsonalfo** [comment]
bueno primero déjame cuadrar con mi equipo si le colocamos otro nombre al equipo porque Yorch era por Jorge y "equipo Nelson" me parece un poco pretencioso de mi parte jejeje

**Comment by arnaldos** [comment]
jajajajaja claro te entiendo fue solo para hacer referencia a que ahora es tu equipo !! :+1:

**Comment by nelsonalfo** [comment]
Bueno ya tenemos nombre de equipo es **DBZ Team**!! El DBZ es por "**D**ragon **B**all **Z**"  (ya que todos somos sayayines de corazon :angel: jajaja) pero le colocamos las siglas como para no ser tan directos jajajaja.

Con respecto al logo quiero que sea algo de estilo _minimal_, para mi menos es mas, pueden mostrarme logos tipográficos o con símbolos, sabiendo el motivo del nombre del equipo.

Espero sus propuestas! :smiley:

**Comment by m471c4** [comment]
@arnaldos @nelsonalfo acá las primeras versiones para el equipo DBZ. Espero comentarios y sugerencias :)

Versión 1, símbolo Kanji de Goku (go) que significa "sabiduría",también es la primera parte de los nombres Goku, Gohan y Goten:
![dbzteam1](https://cloud.githubusercontent.com/assets/13468350/12398672/5550d26e-bde7-11e5-9712-a10b217ab643.png)

Versión 2, esfera del dragón de 7 estrellas: 
![dbzteam2](https://cloud.githubusercontent.com/assets/13468350/12398671/55505fd2-bde7-11e5-937e-b234d7299400.png)

Versión 3, esfera del dragón de 1 estrella: 
![dbzteam3](https://cloud.githubusercontent.com/assets/13468350/12398675/5554b7b2-bde7-11e5-9054-61e315925bf6.png)

Versión 4, síntesis del cabello de Goku, en modo Super Sayayín:
![dbzteam4](https://cloud.githubusercontent.com/assets/13468350/12398673/55519e10-bde7-11e5-8e7a-f9f02ca7afba.png)

Versión 5, síntesis del rostro y cabello de Goku, en modo Super Sayayín:
![dbzteam5](https://cloud.githubusercontent.com/assets/13468350/12398674/5551fbd0-bde7-11e5-9e12-2828c5a8d9cf.png)

**Comment by nelsonalfo** [comment]
La version 1 y  4 son las que mas nos gustan. Estamos por decidir cual de las dos elegimos

**Comment by nelsonalfo** [comment]
Ya nos decidimos. La versión 1 es la que vamos a elegir :smile:

**Comment by m471c4** [comment]
@nelsonalfo dos versiones de wallpapers para el equipo DBZ.

Versión 1:
![dbzteamwallpaper1](https://cloud.githubusercontent.com/assets/13468350/12683453/854815fc-c68b-11e5-98ac-c761ae813973.jpg)

Versión 2:
![dbzteamwallpaper2](https://cloud.githubusercontent.com/assets/13468350/12683455/866aef40-c68b-11e5-97ae-5659a1408799.jpg)

**Comment by yalayn** [comment]
Felicitaciones estan muy buenos sus diseños.

**Comment by m471c4** [comment]
Gracias @yalayn, @jonathanborges3d cuando puedas por favor haz la versión 3D para poder cerrar el caso.

**Comment by jonathanborges3d** [comment]
@m471c4 Enterado! :+1:

**Comment by jonathanborges3d** [comment]
@bitDubai/dbz-team @m471c4 Primera versión 3D:

![dbz_1](https://cloud.githubusercontent.com/assets/13649739/13031316/0f0721b8-d29c-11e5-8e45-d0d0f19acb75.jpg)

**Comment by m471c4** [comment]
Ya que ninguno de los muchachos se ha manifestado, @jonathanborges3d creo que se ve muy bien, aunque algún elemento plateado ayudaría a que no se viera tan plano (ya que este logo es muy minimalista). Tal vez el kanji, o el aro que lo rodea. Por lo demás, está muy bien, todas las monedas quedan increíbles.

**Comment by guillermo20** [comment]
hey!!! yo si me manifiesto, no se porque no me habia notificado esto al correo, pero se ve CHISIMA! :D :+1:

**Comment by yalayn** [comment]
Hola buenos días esta genial. Excelente trabajo, felicitaciones
@jonathanborges3d https://github.com/jonathanborges3d. Aunque la
observacion de Dayana esta buena, un detalle en plateado se veria muy bien,
algo asi como en el del mordo team. :)

Saludos...

ATTE.
ING. YORDIN DA ROCHA

2016-02-15 22:13 GMT-04:30 Guillermo Gutierrez notifications@github.com:

**Comment by nelsonalfo** [comment]
en general se ve muy bien, me gusta, estaría bueno que se haga otra propuesta con los cambios que sugiere @m471c4 para decidirnos por alguna de las dos: la que ya mostraste y la nueva propuesta

**Comment by arnaldos** [comment]
avisenme si esto esta listo para cerrar el caso

**Comment by jonathanborges3d** [comment]
@Fermat-ORG/dbz-team @m471c4 Gracias y a la vez perdonen el retardo en responder. Hice una versión más con el Kanji en plata, sucede que el borde que le colocaron a éste logo coincide con el borde que es común a todas las monedas en material de oro, si le coloco otro la diferencia sería muy notable al compararla con la de otros equipos.

![dbz_2](https://cloud.githubusercontent.com/assets/13649739/13415195/1a532b5c-df2b-11e5-847c-9b9db88e7159.jpg)

**Comment by m471c4** [comment]
@jonathanborges3d entiendo, aunque creo que así queda mucho mejor, ¡está muy bonita! Solo hay que esperar la opinión de los muchachos de @Fermat-ORG/dbz-team :)

**Comment by yalayn** [comment]
Buenos días Estimado.

Esta muy bonito, De verdad muchas felicitaciones Jonathan Borges,
excelente trabajo. Esta Genial.

ATTE.
ING. YORDIN DA ROCHA

**Comment by jonathanborges3d** [comment]
Gracias @yalayn! Me gustaría saber si así quedará, para subirla al DEV-TEAM-README. @Fermat-ORG/dbz-team

**Comment by guillermo20** [comment]
:O se ve muy bonita esa moneda con el simbolo en plateado, yo voto por esa :)

**Comment by yalayn** [comment]
De mi parte si. dejame recordarle al resto del equipo que te de su punto de
vista.

ATTE.
ING. YORDIN DA ROCHA

2016-03-08 13:26 GMT-04:30 Jonathan Borges notifications@github.com:

**Comment by abicelis** [comment]
Disculpen la demora, :+1: 

Buenisimo el ultimo render

**Comment by nelsonalfo** [comment]
el ultimo render FTW!

**Comment by jonathanborges3d** [comment]
:+1:  Ok, va para el repo entonces :smile:

**Comment by emmysm** [comment]
¡Me encantó este render! :smile_cat: Buenísimo chicos @m471c4 @jonathanborges3d :clap:

**Comment by m471c4** [comment]
Gracias @emmysm :)

**Comment by vlzangel** [comment]
:+1:

**Comment by jonathanborges3d** [comment]
Gracias @emmysm. y gracias a @m471c4 por el diseño original.

**Comment by arnaldos** [comment]
excelente !!! cierro el caso
