### ISSUE TITLE
Logo para el equipo Disruptors

### ISSUE THREAD

**Issue by m471c4** [bitDubai/fermat-graphic-design#181]
Viene del #167

@Rart3001, en este issue haremos el briefing y discutiremos brevemente cómo quisieran representar su equipo, este logo será utilizado inicialmente en las portadas de las reuniones.

Puedes participarle a los demás miembros del equipo.

**Comment by arnaldos** [comment]
@Rart3001 Plz en lo que puedas comparte-nos que desearías para representar en el logo de este equipo ?

**Comment by Rart3001** [comment]
@m471c4 @arnaldos @emmysm @hendry19901990 muchachos hay unas letras que yo vi con el nombre, que me gustarían en lo posible la utilizaran. Ha yo no quisiera un logo muy colorido
![disruptors](https://cloud.githubusercontent.com/assets/12099493/10967569/955a183c-838d-11e5-9641-e8fe800af388.jpg)

Y si hay forma que el fondo tengan como lineas de código fuente. Y utilizar algo así como este robot.

![1213801_large](https://cloud.githubusercontent.com/assets/12099493/10968387/fd423c72-8392-11e5-8e36-a3c5e42bc0d2.jpg)

Y las letras que dicen "Team" sean algo parecidos a la de esta imagen "corp.".

![logo-buffalo-corp-blanc](https://cloud.githubusercontent.com/assets/12099493/10968098/23b0cd1c-8391-11e5-90eb-b898bf3e11b9.jpg)

**Comment by Rart3001** [comment]
@m471c4 @arnaldos @emmysm jejejeje miren consegui de donde salen las primeras letras seguro les puede interesar http://abduzeedo.com/design-disruptors-documentary-huge-step-design-community

**Comment by hendry19901990** [comment]
Buenisimo apoyo a Roberto @m471c4 @arnaldos @emmysm

**Comment by Luis-Fernando-Molina** [comment]
@arnaldos invitá a todo el @bitDubai/graphic-design-selection para que participe en este tipo de casos también.

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina perfecto luis !!!

**Comment by Andreinamora** [comment]
Ok buenisimo!!

**Comment by jpcrear** [comment]
Buen día publique algo por allá no se si sera así lo dejo por aquí a ver si
es así o me expliquen por favor...

2015-11-05 17:41 GMT-04:30 Andreina notifications@github.com:

> Ok buenisimo!!
> El 5/11/2015 17:13, "Arnaldo Santamaria" notifications@github.com
> escribió:
> 
> > @Luis-Fernando-Molina https://github.com/Luis-Fernando-Molina perfecto
> > luis !!!
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/bitDubai/fermat-graphic-design/issues/181#issuecomment-154202287
> > 
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/bitDubai/fermat-graphic-design/issues/181#issuecomment-154211487
> .

## 

www.jpcrear.tk
www.jpcrear.blogspot.com

**Comment by victoralfonzohd** [comment]
@Luis-Fernando-Molina @Rart3001 @arnaldos Propuesta de logo para Disruptors, Utilicé la tipografia pedida, ilustre un ave robot con los colores del robot de la imagen de referencia.. Pense en un ave ya que asocie el nombre de Disruptors con velocidad y rapidez 

![disruptors_propuesta-1](https://cloud.githubusercontent.com/assets/15219855/11007386/b2e6a7f8-849b-11e5-95ea-605c991c9160.jpg)

**Comment by oswardsalazar** [comment]
Buenas Tardes, estaba un poco ocupado, aqui les dejo unas ideas
![prueba disruptors 01 - osward salazar](https://cloud.githubusercontent.com/assets/15205074/11016743/d6deaad2-855b-11e5-8d22-bdf34d2a4d25.png)

**Comment by oswardsalazar** [comment]
![prueba disruptors 02 - osward salazar](https://cloud.githubusercontent.com/assets/15205074/11016755/12456a20-855c-11e5-9ec5-7123ed079730.png)
![prueba disruptors 03 - osward salazar](https://cloud.githubusercontent.com/assets/15205074/11016756/178c4ff8-855c-11e5-9285-53a91252b3bf.png)
![prueba disruptors 04 - osward salazar](https://cloud.githubusercontent.com/assets/15205074/11016757/1bcc25ca-855c-11e5-89aa-6313e33939b3.png)

**Comment by oswardsalazar** [comment]
au no entiendo mucho como es la cosa, pero poco a poco me pongo al dia, saludos

**Comment by Rart3001** [comment]
@oswardsalazar me gustaron muchos las primeras letras en azules, y @victoralfonzohd  no esta mal tu idea, pero la forma en si del ave no me convence mucho no la noto muy real, que opinas tu @hendry19901990

**Comment by hendry19901990** [comment]
Me gustan las letras azules y el fondo azul @oswardsalazar

**Comment by victoralfonzohd** [comment]
@Rart3001 @hendry19901990 Hice un cambio en la forma del ave, esta es un poco mas real pero sigue teniendo rasgos roboticos para seguir con el concepto inicial.. También cambié los colores y el tamaño de la tipografía para que se note mas el nombre del equipo.

![logo_disruptors](https://cloud.githubusercontent.com/assets/15219855/11038535/a86f509a-86d5-11e5-915d-979e76c4b193.jpg)

**Comment by Rart3001** [comment]
@victoralfonzohd en discusión con @hendry19901990 pensamos que mejor el ave no porque vimos que en los otros equipos ya hay unos con aves. Si pueden utilizar las primeras letras azules que hizo  @dsalazar pero con otra imagen que no sea el ave, puede ser la misma cara del robot que pusimos dentro de un circulo, y en el fondo condigo fuente algo así... que mas nos recomiendan... o probar con un buffalo robot como este

![image](https://cloud.githubusercontent.com/assets/12099493/11046172/008485d4-86fe-11e5-88a6-531fdcf2060d.png)

**Comment by victoralfonzohd** [comment]
@Rart3001 @hendry19901990 Me gusto la idea del buffalo, les adjunto la ilustración del mismo.. No se que tal se vería con la tipografía que realizo @dsalazar, necesitaría los vectores de esa tipografía para montarla con la ilustración.

![disruptors 3](https://cloud.githubusercontent.com/assets/15219855/11052349/51daaa82-8729-11e5-992d-10512b190bcc.jpg)

**Comment by oswardsalazar** [comment]
Llegando a la oficina envió los vectores que programa usas

**Comment by victoralfonzohd** [comment]
@oswardsalazar Illustrator cs6

**Comment by hendry19901990** [comment]
@oswardsalazar por que no usamos como emblema el de terminator 
![disruptors](https://cloud.githubusercontent.com/assets/13169230/11062704/436b0370-8783-11e5-940f-a97ec71b3807.jpg)

o el de el general Grievous de star wars que opinas @Rart3001 

![general](https://cloud.githubusercontent.com/assets/13169230/11062748/b236884c-8783-11e5-8712-669fce71c30f.jpg)

**Comment by oswardsalazar** [comment]
Ok le pongo

**Comment by victoralfonzohd** [comment]
@Rart3001 @hendry19901990 

![logo_disruptors](https://cloud.githubusercontent.com/assets/15219855/11077849/44b0ae5a-87d4-11e5-9b1a-dca7f01c546b.jpg)

**Comment by Rart3001** [comment]
@oswardsalazar @victoralfonzohd Muchachos por favor pueden probar con un buffalo envistiendo, algo así:

![image](https://cloud.githubusercontent.com/assets/12099493/11091065/67b502c8-8849-11e5-9b46-44dacb54a728.png)

![image](https://cloud.githubusercontent.com/assets/12099493/11091118/c6a47eb2-8849-11e5-967e-7227058342ef.png)

![image](https://cloud.githubusercontent.com/assets/12099493/11091172/1ce57f74-884a-11e5-874b-0c8111dcf37e.png)

El ultimo me gusta mas convirtiendo la raya recta a un relámpago o algo así...

**Comment by victoralfonzohd** [comment]
@Rart3001 @hendry19901990 

![disruptors](https://cloud.githubusercontent.com/assets/15219855/11105831/c1b452ba-88a3-11e5-9e8b-1034b9a60903.jpg)

**Comment by Rart3001** [comment]
@victoralfonzohd Me gustaron las letras, pero pudieras poner las letras de "TEAM" abajo y el buffalo le le falta algo, se lo mostré a mi esposa y a simple vista dijo que parecía era un ave, que pareciera que el   cacho es un pico, puedes probar con el logo azul del buffalo cambiándole la raya roja por un rayo o algo así y otros colores.

**Comment by victoralfonzohd** [comment]
@Rart3001 @hendry19901990 Trabaje mucho mas la estructura de la imagen que me dieron como referencia, como no quieren repetir elementos que ya existan en los otros equipos cambie la idea del rayo ya que el logo de uno de los equipos usa un relámpago, entonces  para seguir con la onda robótica la raya roja la transforme en una especie de mirada de rayo láser que da un efecto bastante singular y equilibrio a la imagen por la posición tan marcada del buffalo.

Para los colores use 2 azules bastantes contrastantes pero a la vez sutiles

![disruptors_buffalo_v2](https://cloud.githubusercontent.com/assets/15219855/11204103/98aab5fc-8ccd-11e5-90c5-4688820a2d75.jpg)

**Comment by hendry19901990** [comment]
excelente @oswardsalazar @victoralfonzohd

**Comment by hendry19901990** [comment]
yo digo esta @Rart3001  que el buffalo con el laser apunte la moneda algo asi nose
![disruptormatrix](https://cloud.githubusercontent.com/assets/13169230/11224629/2699917e-8d48-11e5-8b82-751b9d2e4eb9.jpg)

**Comment by victoralfonzohd** [comment]
@Rart3001 @hendry19901990 Quieren que la moneda tenga el código binario a su alrededor? Estos elementos podrían perderse al momento de hacer una reducción al logo.

**Comment by hendry19901990** [comment]
no @victoralfonzohd es solo una cryptomoneda  que el buffalo apunte con su laser el codigo binario que no salga

**Comment by victoralfonzohd** [comment]
@hendry19901990 @Rart3001 

Version 1:
![logo_disruptors v1](https://cloud.githubusercontent.com/assets/15219855/11273549/17c04ea4-8ea6-11e5-901c-fca929c1eb8b.jpg)
Version 2:
![logo_disruptors-v2](https://cloud.githubusercontent.com/assets/15219855/11273559/1fb84bac-8ea6-11e5-93e4-23967b87c3fe.jpg)
Version 3:
![logo_disruptors-v3](https://cloud.githubusercontent.com/assets/15219855/11273565/2701a7b4-8ea6-11e5-9edb-434a070ecc51.jpg)

**Comment by jonathanborges3d** [comment]
@victoralfonzohd Hola! tiene éste logo ya una versión final? espero por eso para hacer la versión en 3D. Gracias :smile:

**Comment by victoralfonzohd** [comment]
@jonathanborges3d Hola, aun no terminamos de concluir con la idea para este logo.. @hendry19901990 @Rart3001 Que opinan de estas ultimas versiones?

**Comment by Rart3001** [comment]
En realidad todavía no me gusta mucho, le falta algo no me convence y esa moneda no me parece bien. @jonathanborges3d @jonathanborges3d @hendry19901990

**Comment by victoralfonzohd** [comment]
@Rart3001 La moneda fue un elemento agregado por @hendry19901990 

Esta es la version sin la crypto moneda: 

![disruptors_buffalo_v2](https://cloud.githubusercontent.com/assets/15219855/12024707/179df10a-ad79-11e5-966c-b692df7b4660.jpg)

**Comment by arnaldos** [comment]
@Rart3001  @hendry19901990 una propuesta para su logo de equipo 

Versión 1
![disruptors1](https://cloud.githubusercontent.com/assets/13594347/12029289/9a0e8b14-adb9-11e5-828a-d21512defc5b.png)

Versión 2
![disruptors2](https://cloud.githubusercontent.com/assets/13594347/12029290/9a212bc0-adb9-11e5-947e-2df3a25cc695.png)

Versión 3
![disruptors3](https://cloud.githubusercontent.com/assets/13594347/12029291/9bc1b5c6-adb9-11e5-8ac4-92cc902040eb.png)

Versión 4
![disruptors](https://cloud.githubusercontent.com/assets/13594347/12029293/9e96fc98-adb9-11e5-8847-4842e97d31e1.png)

**Comment by Rart3001** [comment]
@victoralfonzohd el concepto de la moneda no estaba mal lo que me refería es que la moneda que escogieron no estaba bonita, y el logo lo veo muy azul, pudieran por favor ponerle las otras letras a las versiones 1 y 3 de la propuesta de @arnaldos para ver como se ve

**Comment by arnaldos** [comment]
@Rart3001 vale ya genero otra versión con otra tipografía diferente

**Comment by Rart3001** [comment]
@arnaldos por favor utiliza las que están al principio del issue.

**Comment by hendry19901990** [comment]
@victoralfonzohd y @arnaldos usen la idea del comienzo del issue

**Comment by arnaldos** [comment]
@Rart3001 @hendry19901990  disculpen la demora ... Roberto aquí les envió unos ajustes según lo conversado.

### Versión 1

## ![disruptors1](https://cloud.githubusercontent.com/assets/13594347/13730001/874d625c-e914-11e5-9a83-49cbd3d8df77.jpg)

### Versión 2

![disruptors2](https://cloud.githubusercontent.com/assets/13594347/13730002/87531418-e914-11e5-8d38-aa555d8566a2.jpg)

**Comment by arnaldos** [comment]
La versión dos me gusta mas, no se que opinen ustedes

**Comment by Rart3001** [comment]
Muchas gracias @arnaldos me gusto mucho la segunda versión, yo voto por esa vamos a ver que opina @hendry19901990

**Comment by hendry19901990** [comment]
Igual @Rart3001 me gusta la version 2, gracias  @arnaldos

**Comment by furszy** [comment]
A mi también :D

**Comment by Rart3001** [comment]
jajaja gracias @furszy

**Comment by jonathanborges3d** [comment]
@arnaldos Excelente! Puedes subir el editable al repo por favor?, para cuando vaya a hacer la moneda pueda tener el archivo original. Gracias.

**Comment by arnaldos** [comment]
@jonathanborges3d te dejo el enlace donde puedes ubicar los archivos del logo https://github.com/Fermat-ORG/fermat-graphic-design/tree/95fb4bcd79e986d3889fc6b7f2f7a8ada2bfa0ad/2D%20Design/bitDubai/Logotypes%20Teams%20bitDubai/Logo_disruptors_team/logo%20disruptors

**Comment by arnaldos** [comment]
@jonathanborges3d @Rart3001 Tambien te hago referencia de este caso para definir el 3D del logo en el caso https://github.com/Fermat-ORG/fermat-graphic-design/issues/695 cierro el caso
