### ISSUE TITLE
Infografía Descriptiva de los Procesos de los modulos de Fermat org

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#183]
Se realizara una infografía descriptiva para el proceso de cada modulo correspondiente a Fermat.org

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina luis te compato la infografia para los procesos de los modulos 

Versión 1
![infografia-de-procesos-de-los-modulos-de-fermat-org-vs1](https://cloud.githubusercontent.com/assets/13594347/10502725/c63d2ae2-72b8-11e5-9aa9-7b1962d6adee.jpg)

Versión 2
![infografia-de-procesos-de-los-modulos-de-fermat-org-vs2](https://cloud.githubusercontent.com/assets/13594347/10502726/c6446136-72b8-11e5-8f0f-6e3879e0a7f8.jpg)

**Comment by Luis-Fernando-Molina** [comment]
Arnaldo, por favor volve a mirar el video donde te explique esto. Tenes que crear 2 contendores, uno para el header del proceso y otro para cada paso. Cada paso va a estar asociado a una fichita, y debe contener el numero, el titulo y la descripcion dentro del contenedor del paso, no por fuera. Por favor mira el video de nuevo.

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina con la primeras dos versiones pence que podía hacer algo mas dinámico por eso las plantee de esa forma, pero continuación te comparto esta dos nuevas versiones. :smiley: 

Versión 3
![infografia-de-procesos-de-los-modulos-de-fermat-org-vs3](https://cloud.githubusercontent.com/assets/13594347/10505677/bef3fd94-72d9-11e5-9a2d-c6cc25b53e7d.jpg)

Versión 4
![infografia-de-procesos-de-los-modulos-de-fermat-org-vs4](https://cloud.githubusercontent.com/assets/13594347/10505678/befa46f4-72d9-11e5-862c-ae4f50422168.jpg)

**Comment by Luis-Fernando-Molina** [comment]
ok, vamos a continuar la version 3:
- Proba de poner el numero del lado izquierdo, luego la ficha y luego el texto.
- Proba mas estilos de bordes, fondo, colores para la ficha en general y para el numero tambien.
  *El header del proceso plantea mas opciones, buscate algo mas elaborado por favor.

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina te comparto nuevas versiones de la infografia para los procesos de los modulos.

Versión 5

![infografia-de-procesos-de-los-modulos-de-fermat-org-vs5](https://cloud.githubusercontent.com/assets/13594347/10556396/abc3729a-744b-11e5-98ff-1848ea5f6826.jpg)

Versión 6
![infografia-de-procesos-de-los-modulos-de-fermat-org-vs6](https://cloud.githubusercontent.com/assets/13594347/10556397/abc810de-744b-11e5-8008-c2e9c756aee9.jpg)

Versión 7
![infografia-de-procesos-de-los-modulos-de-fermat-org-vs7](https://cloud.githubusercontent.com/assets/13594347/10556398/abd109fa-744b-11e5-9112-9834a1b6a9b7.jpg)

Versión 8
![infografia-de-procesos-de-los-modulos-de-fermat-org-vs8](https://cloud.githubusercontent.com/assets/13594347/10556399/abd29be4-744b-11e5-833b-64553a204cdb.jpg)

**Comment by Luis-Fernando-Molina** [comment]
Hola Nelson, 

Vamos a ir por la version 8 con las siguientes modificaciones:

1) En el titulo del proceso se debe incluir espacio para la descripcion del proceso
2) En cada paso la parte verde hacela mas ancha asi la descripcion puede ser mas abundante.
3) La linea que une los pasos debe ser simple no dobre y negra.
4) El boton en el titulo del proceso lo vamos a usar como un TOGGLE para expandir los pasos o contraerlos en algun futuro.
5) Debes mostrar como quedaría el proceso ante una bifurcacion de 2 caminos y de 3 caminos (osea cuando la secuencia no es lineal y se bifurca por dos o mas caminos)
6) La sobra del titulo no debiera estar tan separada. Pregunta: si tiene sobra el titulo no debiera tener todo el resto? o ninguno?

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina comparto los ajustes que me solicitaste 

Versión 9 ( los elementos sin sombras )
![infografia-de-procesos-de-los-modulos-de-fermat-org-vs9](https://cloud.githubusercontent.com/assets/13594347/10625237/d7da07aa-776a-11e5-9474-741abb7cebf3.jpg)

Versión 10 ( los elementos todos con sombras )
![infografia-de-procesos-de-los-modulos-de-fermat-org-vs10](https://cloud.githubusercontent.com/assets/13594347/10625240/d9020de4-776a-11e5-8a54-957b601e3b14.jpg)

**Comment by Luis-Fernando-Molina** [comment]
vamos con la 10

faltaria que hagas las bifurcaciones, el resto esta ok

**Comment by Miguelcldn** [comment]
Sorry, me tardé porque era algo complicado ponerle flujos de prueba

![bifurcado](https://cloud.githubusercontent.com/assets/5544266/10656300/48bcc2e6-7847-11e5-9c33-50b058148210.png)
Este es un flujo separado en 2, se separan en forma de T de manera que si dos elementos provienen del mismo paso, tendrán la misma posición Y

![trifurcado](https://cloud.githubusercontent.com/assets/5544266/10656316/6987a04a-7847-11e5-85b5-f64213130441.png)
Si la cantidad de hijos es impar, el espacio de abajo simplemente se distribuye simétricamente, todas las líneas partiendo del punto central de la T

De haber más hijos, sólo se agregarán a los lados, dependiendo si la cantidad es par o impar.

**Comment by Miguelcldn** [comment]
**Pro Tip:** Cuando hagan un commit en referencia a un issue (así no esté terminado) pueden escribir en el título o comentario del commit el número del issue al que está relacionado. Esto hace que aquí en el issue se pueda ver los aportes que tienen que ver con esto. Por ejemplo, si hacen un commit con los diseños de este issue, al escribir #183 en la descripción yo podría ver qué commit ha sido y por ende qué archivos son los relacionados.

Si escriben Fix #183 este issue se cerraría automáticamente al combinarse el commit con el repo principal y se dejaría la referencia para saber qué cambios se hicieron.

**Comment by Luis-Fernando-Molina** [comment]
Buen PRO TIP, sabia lo del fix, pero no lo del número solo. Lo sabrá el resto de los developers?

**Comment by Miguelcldn** [comment]
Gracias, lo descubrí al hacer un commit "Mid work of #xxx" y apareció la referencia

**Comment by Luis-Fernando-Molina** [comment]
deberías comentarselo al resto    :smile:

**Comment by Miguelcldn** [comment]
Compartido por el grupo :+1:

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina @Miguelcldn a continuación les comparto la ficha de los procesos, con sus bifurcaciones.
![infografia-de-procesos-de-los-modulos-de-fermat-org-vs11](https://cloud.githubusercontent.com/assets/13594347/10730895/f883e652-7bc4-11e5-8385-734afa1e841b.jpg)

**Comment by Miguelcldn** [comment]
Los procesos siguen la misma numeración entre todos (las bifurcaciones deberían ser 03, 04, y 05; mientras que las que están más abajo serían 06 y 07).

Y otra cosa, los pasos siempre están conectados (el actual paso 03 no se quién llega a él, por la alineación asumo que sigue al paso 02 que tiene 2 niveles arriba)

¿Por qué algunos pasos tienen un círculo a la derecha? Podrían las líneas salir desde el mismo número?

**Comment by arnaldos** [comment]
@Miguelcldn  ok déjame replantear el seguimiento de la enumeración de los procesos, referente al circulo de la derecha  se refiere a un botón que al pulzarlo desplegara el resto del contenido que tenga el paso 2 en este caso. de esa manera lo estoy enfocando nose si se trabajara con botones

**Comment by Miguelcldn** [comment]
Dale, chévere.

Cuando se dibuje el flujo se dibujará el flujo completo al mismo tiempo, el usuario no necesita dar click, no te preocupes por eso

**Comment by arnaldos** [comment]
ok perfecto !!!

**Comment by Luis-Fernando-Molina** [comment]
No esta mal que se pueda expandir , aunque no lo implementemos ahora mismo. Ademas un flujo puede conectarse con otro flujo. Yo dejaria el boton ahi.

Otra cosa @Miguelcldn me parece que ya tenes la info necesaria para proceder.

Estoy de acuerdo que la linea debe salir desde los numeros.

**Comment by Miguelcldn** [comment]
No veo las imágenes necesarias en el repositorio, donde estan @arnaldos?

**Comment by arnaldos** [comment]
@Miguelcldn no las he subido ya que nose como las necesitas  ?  si hay que hacer algun trabajo especial o solo con el svg basta ?

**Comment by Miguelcldn** [comment]
Dame el svg y un png por si acaso, dejando el espacio en blanco del lugar de la ficha y sin textos, números ni líneas de conexión

**Comment by arnaldos** [comment]
vale perfecto !!!

**Comment by arnaldos** [comment]
ya subo la ficha !!

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina , @Miguelcldn este caso ya esta resuelto o nos falta definir algo mas ?

**Comment by Miguelcldn** [comment]
Déjame hacer unas revisiones, hay varios detalles respecto a programación y no estoy seguro si necesitar algo al respecto, dejalo abierto un tiempo más por si las moscas, yo te aviso cuando esté listo.

Porque tenía unos problemas con las sombras pero pensaba que era problema de diseño por el png, pero era culpa mía

**Comment by arnaldos** [comment]
@Miguelcldn vale perfecto !!

**Comment by Miguelcldn** [comment]
@arnaldos el issue se puede cerrar, ya hice las revisiones :+1: Gracias

**Comment by arnaldos** [comment]
@Miguelcldn  perfecto ya cierro el caso !!! :+1:
