### ISSUE TITLE
Versión 3D del logo de Fermat P2P

### ISSUE THREAD

**Issue by jonathanborges3d** [bitDubai/fermat-graphic-design#184]
Viene del #139 

Versión plana actual:

![p2p](https://cloud.githubusercontent.com/assets/13649739/10502678/5043715c-72b8-11e5-9903-41c77ec02de3.jpg)

**Comment by jonathanborges3d** [comment]
@Luis-Fernando-Molina Versión 3d:

En el editor:

![f_p2p_1](https://cloud.githubusercontent.com/assets/13649739/10683583/2bfe2e30-790d-11e5-9b00-c2ba92012789.jpg)

Versión en moneda (Cover de Hangouts):

![f_p2p_2](https://cloud.githubusercontent.com/assets/13649739/10683632/c1bd0a0e-790d-11e5-9969-3abc433e5f9a.jpg)

Versión .json para 3d.fermat.com:

![f_p2p_3](https://cloud.githubusercontent.com/assets/13649739/10683601/52852040-790d-11e5-8aea-5eda0abd5fd0.jpg)

![f_p2p_4](https://cloud.githubusercontent.com/assets/13649739/10683608/6b647f70-790d-11e5-997f-60020e2af723.jpg)

![f_p2p_5](https://cloud.githubusercontent.com/assets/13649739/10683617/7b763354-790d-11e5-9fef-90551cfc6c6e.jpg)

**Comment by Luis-Fernando-Molina** [comment]
Jonathan en la imagen grande veo como que el anillo plateado vuela sobre la parte de cobre (un poquito) , estas 100% seguro de que no hay un espacio??

**Comment by jonathanborges3d** [comment]
@Luis-Fernando-Molina Si, 200%. Hice un render de oclusión ambiental de la misma escena, el centro que tiene material de cobre es una sola pieza con el aro y el anillo exterior como se puede visualizar en la segunda imagen. Tal vez sea una sensación que da por la reflexión de ambos materiales.

![ao](https://cloud.githubusercontent.com/assets/13649739/10701745/17bd3a38-798f-11e5-9173-cbc50ee3e465.jpg)

![shaded](https://cloud.githubusercontent.com/assets/13649739/10701925/1e985c4c-7990-11e5-8be5-18f6ae2c37ed.jpg)

**Comment by Luis-Fernando-Molina** [comment]
:+1:  no hay problema.
