### ISSUE TITLE
Versión 3D del logo de Fermat BCH

### ISSUE THREAD

**Issue by jonathanborges3d** [bitDubai/fermat-graphic-design#185]
Viene del #139 

Versión plana actual:

![bch](https://cloud.githubusercontent.com/assets/13649739/10502797/80c3ada0-72b9-11e5-9fee-ceeb412a77b5.jpg)

**Comment by jonathanborges3d** [comment]
@Luis-Fernando-Molina Versión 3d:

En el editor:

![f_bch_1](https://cloud.githubusercontent.com/assets/13649739/10706330/ccb26dbc-79af-11e5-9d84-7057cc822839.jpg)

Versión en moneda (Covers de Hangouts):

![f_bch_2](https://cloud.githubusercontent.com/assets/13649739/10706337/dbb67948-79af-11e5-87ab-b004a2293b89.jpg)

Versión .json para 3d.fermat.org:

![f_bch_3](https://cloud.githubusercontent.com/assets/13649739/10706379/2afdc07e-79b0-11e5-9b10-e6d6978715b9.jpg)

![f_bch_4](https://cloud.githubusercontent.com/assets/13649739/10706405/6f8fa996-79b0-11e5-987a-701beca0d8fb.jpg)

![f_bch_5](https://cloud.githubusercontent.com/assets/13649739/10706410/78d98ddc-79b0-11e5-9596-26c666fb5117.jpg)

**Comment by Luis-Fernando-Molina** [comment]
:+1:
