### ISSUE TITLE
Versión 3D del logo de Fermat OSA

### ISSUE THREAD

**Issue by jonathanborges3d** [bitDubai/fermat-graphic-design#186]
Viene del #139 

Versión plana actual:

![osa](https://cloud.githubusercontent.com/assets/13649739/10502851/2159d0b4-72ba-11e5-8cc4-782a7dc1143f.jpg)

**Comment by jonathanborges3d** [comment]
@Luis-Fernando-Molina Versión 3d:

En el editor:

![f_osa_1](https://cloud.githubusercontent.com/assets/13649739/10707054/3bddbc12-79b7-11e5-84d8-f078b382fe58.jpg)

Versión en moneda (Covers de Hangouts)

![f_osa_2](https://cloud.githubusercontent.com/assets/13649739/10707114/ac838500-79b7-11e5-93bc-ed32ebaf8253.jpg)

Versión .json de 3d.fermat.org:

![f_osa_3](https://cloud.githubusercontent.com/assets/13649739/10707070/5e26ebf4-79b7-11e5-93d1-01d9548ebb59.jpg)

![f_osa_4](https://cloud.githubusercontent.com/assets/13649739/10707227/2add80c6-79b9-11e5-9e03-c9c7e86dbeb2.jpg)

![f_osa_5](https://cloud.githubusercontent.com/assets/13649739/10707256/82e54506-79b9-11e5-9374-2dd02c76e2da.jpg)

**Comment by Luis-Fernando-Molina** [comment]
:+1:
