### ISSUE TITLE
Renders para los covers de hangouts

### ISSUE THREAD

**Issue by jonathanborges3d** [bitDubai/fermat-graphic-design#187]
Viene del #167 

@Luis-Fernando-Molina Hice algunas propuestas de materiales para el soporte donde están las monedas, @m471c4 no sé si tienes definido el arte que irá sobre éstas imágenes para identificar los hangouts, pero me gustaría saber si se usará la misma paleta de colores de fermat y si el espacio disponible fuera del área de la moneda es suficiente para lo que se deba colocar.

Versiones:

1)
![cor](https://cloud.githubusercontent.com/assets/13649739/10504074/6e4e1e14-72c6-11e5-92e2-ff07769f9dac.jpg)

2)
![cor_2](https://cloud.githubusercontent.com/assets/13649739/10504131/fa023ee0-72c6-11e5-8260-19becc2ad9bc.jpg)

3)
![cor_3](https://cloud.githubusercontent.com/assets/13649739/10504184/7cc64628-72c7-11e5-90c5-f5d1112c2b8d.jpg)

4)
![cor_4](https://cloud.githubusercontent.com/assets/13649739/10504362/8e93491c-72c9-11e5-9fcd-5486b9ff9017.jpg)

**Comment by arnaldos** [comment]
a mi me parece que la versión 3 seria la indicada ya que tiene buen balance de los colores de fermat, y es muy limpio, lo que permite colocar texto y los iconos sobre la imagen sin tener muchos elementos que nos puedan causar ruido en la lectura de los mismos, nose que opine @Luis-Fernando-Molina al respecto.

**Comment by Luis-Fernando-Molina** [comment]
Vamos a probar con la 1 y la 3 ponerle el titulo de la caratula y los logos del equipo, UX / GUI, etc. Podes hacerla mas grande así @arnaldos ya puede trabajar con eso? 

Ayer te dije que mantuvieras la moneda del mismo tamaño y solo incluyeras mas fondo, hoy digo que mejor se agrande un poco en la nueva imagen mas grande y ademas que se vea mas fondo.

**Comment by jonathanborges3d** [comment]
@Luis-Fernando-Molina Nueva versión, mayor resolución y tamaño de la moneda:

![cor_5](https://cloud.githubusercontent.com/assets/13649739/10561313/938b9a48-74ed-11e5-81bb-bd32eceaa6c5.jpg)

@arnaldos El espacio del fondo visible en la imagen es suficiente para ponerle el título y los logos?

**Comment by Luis-Fernando-Molina** [comment]
:+1:  vamos a usar esta imagen.  Si, el espacio es suficiente porque no vamos a poner "Fermat Core Meeting" ya que lo dice la misma moneda y es muy visible. Solo algunos iconos mas que irían en las esquinas.

@arnaldos por favor encargate de terminar la carátula por favor con el equipo de graphic design 2d
