### ISSUE TITLE
Renders para las redes sociales de Fermat Venezuela

### ISSUE THREAD

**Issue by jonathanborges3d** [bitDubai/fermat-graphic-design#188]
@nindriago @Luis-Fernando-Molina Primera versión de la imagen de perfil:

![ven_2](https://cloud.githubusercontent.com/assets/13649739/10532612/2b72f82a-738a-11e5-8d50-6e1bcb0febd4.jpg)

**Comment by nindriago** [comment]
se ve excelente @jonathanborges3d  :) - esperemos confirmacion de @Luis-Fernando-Molina para poderla utilizar en el Facebook

**Comment by Luis-Fernando-Molina** [comment]
:+1:  dale nomas

**Comment by jonathanborges3d** [comment]
@nindriago @Luis-Fernando-Molina Una primera versión para la portada:

![portada_1](https://cloud.githubusercontent.com/assets/13649739/10544210/f532650e-73eb-11e5-95e3-610191c2da13.jpg)

Me gustaría saber su opinión sobre cuales elementos pueden agregarse.

**Comment by nindriago** [comment]
bueno como te habia comentado @jonathanborges3d  me parece que se veria bien si se puede colocar algo asi como unos pines en cada estado donde esta cada uno de los integrantes de aca de Vzla y si da oportunidad o se ve bien, colocar algo asi como un aviso, valla, pancarta que una todos los pines y se vea que diga FERMAT

**Comment by Luis-Fernando-Molina** [comment]
Como mas les guste.

**Comment by jonathanborges3d** [comment]
@nindriago  Segunda versión: 
![portada_2](https://cloud.githubusercontent.com/assets/13649739/10561334/0fd7d030-74ee-11e5-9631-6d64b452399c.jpg)

Coloqué los estados donde estamos ubicados en color dorado, lo cual puede actualizarse con el ingreso futuro de nuevos integrantes.

**Comment by nindriago** [comment]
Se ve genial :+1:  - lastima no quedara bien la sugerencia anterior... Gracias @jonathanborges3d 
ya la coloco en la portada y damos inicio al face :+1:

**Comment by jonathanborges3d** [comment]
@nindriago Siempre a la orden. Cualquier modificación que hacerle me avisas.

**Comment by Luis-Fernando-Molina** [comment]
:+1:  le diste a @nindriago  una version de demasiada baja resolución y tamaño. Por favor actualizalo así reemplaza lo que ya subió.

**Comment by Luis-Fernando-Molina** [comment]
Realmente esos son los unicos estados que abarcan toda la gente de Venezuela??? Están seguros de eso?

En el mapa se ve el país entero?

**Comment by jonathanborges3d** [comment]
@Luis-Fernando-Molina Ya estoy haciendo el nuevo render, la subiré al repositorio, 

Para hacer la lista de los estados pregunté en el grupo skype de Venezuela, nadie más manifestó conocer compañeros de otros estados.

**Comment by nindriago** [comment]
si Luis, solo ocupamos 6 de los 24 estados del Pais. ese es mapa completo.

La mayor parte de nosotros esta en Zulia y Caracas

**Comment by jonathanborges3d** [comment]
@Luis-Fernando-Molina @nindriago Aquí está la nueva imágen:

https://raw.githubusercontent.com/bitDubai/fermat-graphic-design/f2459e652db06a15ad7e46041d6585c17da3c118/Dise%C3%B1o%203D/Renders%20Redes%20Venezuela/Portada_facebook.jpg?token=ANBHSwE-Ki2hg_PpFLtYdQDB59wnPj2Rks5WLFSSwA%3D%3D

Tiene la relación de aspecto de la imagen de perfil de facebook.

**Comment by nindriago** [comment]
@jonathanborges3d Gracias y @Luis-Fernando-Molina Listo el cambio en la pagina :+1:

**Comment by Luis-Fernando-Molina** [comment]
:+1:  quedó perfecto!
