### ISSUE TITLE
Definir una paleta tipográfica para BitDubai

### ISSUE THREAD

**Issue by m471c4** [bitDubai/fermat-graphic-design#19]
Viene del #14

A partir del Isologo, será necesario definir una paleta tipográfica para titulación y para textos.

![isologo](https://cloud.githubusercontent.com/assets/13468350/9078253/fe7741c2-3b04-11e5-8ecd-69d8e08175bb.png)
@arnaldos, no conocemos la fuente usada en el isologo, así que será necesario identificarla.

**Comment by arnaldos** [comment]
Para la paleta tipografica podriamos jugar con 3 tipografías por ejemplo los textos con helvética, los títulos con musket o canaro son buenas fuentes y los subtitulos alguna otra que nos de dinamismo y armonia.

**Comment by arnaldos** [comment]
Con Tipografía empleada en el logo, aunque no estoy muy seguro podría decir que es Futura. sugiero iniciar el proceso con esta tipografía a ver si ambas coinciden.

**Comment by Luis-Fernando-Molina** [comment]
:+1:
