### ISSUE TITLE
Broker Identity Design - Lista de Identidades

### ISSUE THREAD

**Issue by Neoperol** [bitDubai/fermat-graphic-design#191]
![view_broker_list](https://cloud.githubusercontent.com/assets/6201081/10606111/3e0ec28e-76fa-11e5-90db-ce56380e498e.jpg)

**Comment by Luis-Fernando-Molina** [comment]
@Neoperol las pantallas se ven bien, pero debe haber un issue por cada una. Tambien es posible crear lo que llamamos un SUPER ISSUE del cual se desprenden issues hijos, cuando todavia se quiere tener una discución de mas alto nivel, pero al final tiene que terminar una pantalla por issue para poder discutirla individualmente y poder cerrar caso por caso.

**Comment by Neoperol** [comment]
Parte del Issue #192

**Comment by Luis-Fernando-Molina** [comment]
@ui-ux-design-team la pantalla se ve bien, pero me gustaría saber cual fue el análisis realizado para llegar a este diseño.

Mi opinión es que un broker probablemente nunca tenga mas de una identidad, si acaso quizás 2 o como mucho 3. Tampoco creo que use una foto de su persona en este tipo de actividad comercial. Sabiendo eso, yo hubiera repleanteado la pantalla de otra forma.

Entonces vuelvo al punto de la importancia de expresar que se tuvo en cuenta para ofrecer una propuesta. A lo largo de la vida del caso, podemos ir completando y refinando las cosas  a tener en cuenta y el diseño debe ser un reflejo de eso mismo. Ya que vamos a empezar a usar esta herramienta par ir caso por caso, empecemos por favor así como les planteo. Asegurense de que en cada caso esté claro cual fue el criterio utilizado para llegar a esa propuesta.

@Neoperol @vnesita  sus comentarios.

**Comment by vnesita** [comment]
@Luis-Fernando-Molina , por lo poco que he visto, cuando se crea un identidad el sistema te pide una foto, y si ya la tienes en las otras apps debería mostrarse en todas, los avatares sirven para el fácil y rápido reconocimiento del usuario, pero como esta vista no lo cree yo y no sé cual es y de donde sale,  esperemos a @Neoperol

**Comment by Neoperol** [comment]
Si esta pantalla es la lista de las identidades. En estas subapp es donde puedes crear la Identidad o Editarla. Cuando hable con Nelson sobre esta app, el funcionamiento para el usuario es este, ver tu lista de identidades creadas, poder crear una identidad que posee dos elementos; Foto y Nombre, con y con la opción de poder hacer la identidad publica o no. Además de crear una identidad nuevo si desde la lista entras a la vista de detalle de una identidad puedes editarla.

**Comment by Luis-Fernando-Molina** [comment]
@Neoperol estoy de acuerdo en que esa es la funcionalidad de esta sub app. Para poder hacer un análisis desde el punto de vista de la experiencia de usuario esperamos un análisis con un poco mas de profundidad. Lo que te dijo Nelson es exactamente lo que yo le dije a él. Alguien tiene que sentarse a profundizar mas en cada situación de uso para sacar la mejor experiencia de usuario posible y en este caso esa es vuestra misión como diseñadores de UI/UX.

En otras palabras, no podés esperar que lo que yo diga o Nelson o cualquier otro diga sea el análisis más profundo que se puede hacer en cada caso, eso se lo dejamos a ustedes en UX.

En este caso, por favor replanteá el diseño actual para que refleje lo que indiqué mas arriba:

1 - Que probablemente exista como mucho 1 identidad y 3 como mucho.
2 - Que no se use una foto real, sino un logo de una empresa o algo por el estilo.

**Comment by Neoperol** [comment]
Ok, pero las acciones principales que debe hacer el usuario son solo esas, Crear y Administrar sus identidades? Además de los datos que puede ingresar solo foto y nombre. 
El tipo de foto que use para identificarse no cambia para nada la diagramación que pueda tener la vista, si solo va a constar de dos elementos que son la foto y el nombre. Si solo es de 1 a 3 usar otro tipo de distribución de la lista como Grids va a crear mas espacio vació en la vista. Lo que puedo hacer es cambiar el tamaño de los elementos.

**Comment by Luis-Fernando-Molina** [comment]
Exacto, un cambio de tamaño me parece bien. En la imagen también porque un logo no creo que se vea en ese circulito. Quizas pudieras ser en un formato de banner que ocupe el ancho de la pantalla, como los que creó @arnaldos en https://github.com/bitDubai/fermat-graphic-design/issues/161 . (No digo que haya que diseñar un banner, sino que el broker pudiera poner un banner en vez de una fotito).
