### ISSUE TITLE
Iconos para identificar las meetings de GUI y UX

### ISSUE THREAD

**Issue by m471c4** [bitDubai/fermat-graphic-design#197]
Viene del #167

Se requiere crear dos iconos que serán usados en los covers de las meetings.

**Comment by m471c4** [comment]
@Luis-Fernando-Molina cree un nuevo issue para este caso. Acá algunas versiones, no he usado color, ya que lo mejor será ajustarlas al cover que hizo Jonathan. También las hice planas, pero eso se puede ajustar.

Para UX:
![ux-gui1](https://cloud.githubusercontent.com/assets/13468350/10621668/f9817538-774b-11e5-9d3b-00b7799981da.png)

Para GUI:
![ux-gui2](https://cloud.githubusercontent.com/assets/13468350/10621669/f9856df0-774b-11e5-864d-aaa55e021e89.png)

Con tipografía:
![ux-gui7](https://cloud.githubusercontent.com/assets/13468350/10621764/908e62ec-774c-11e5-8673-65f3959829a6.png)

Sin los círculos:
![ux-gui8](https://cloud.githubusercontent.com/assets/13468350/10621765/90ab753a-774c-11e5-9621-91b532c419f6.png)

**Comment by Luis-Fernando-Molina** [comment]
Para GUI prefiero algo de este estilo, con tipografia. el tipo de letra esta ok.

![gui](https://cloud.githubusercontent.com/assets/9479367/10622152/ea240a50-775b-11e5-951a-e7c5acd75847.png)

**Comment by Luis-Fernando-Molina** [comment]
Para UX plantea otra opciones

**Comment by m471c4** [comment]
@Luis-Fernando-Molina primeras pruebas para GUI, con la mano más estilizada y la tipografía. Con respecto a los colores, aun habría que probarlos sobre el fondo creado por Jonathan, pero pueden adaptarse según sea necesario.

![gui_new](https://cloud.githubusercontent.com/assets/13468350/10701250/6b55c0f0-798c-11e5-9578-8bc9d8041ff5.png)

**Comment by Luis-Fernando-Molina** [comment]
no me convence, no se si es el circulo o que. Proba ponerlas sobre la caratula 3d a ver como quedan, o plantea algo mas, no se.
