### ISSUE TITLE
CCP / SUPER ISSUE: Bitcoin Wallet UX

### ISSUE THREAD

**Issue by Neoperol** [bitDubai/fermat-graphic-design#198]
Vista Actual

![seleccion_046](https://cloud.githubusercontent.com/assets/6201081/10627295/74ba6d88-7781-11e5-8b40-cf1c2c39b238.png)

Vista Nueva

![view_matias_send_detail](https://cloud.githubusercontent.com/assets/6201081/10627510/556fffe4-7784-11e5-939d-35cd70287c22.jpg)

La acción de enviar un request se debe hacer en una nueva actividad para que el usuario tenga la posibilidad de regresar a la vista anterior si presiono el floating button por error o si no quiere realizar ningún request, además de demostrarle al usuario que esta en lugar nuevo dentro de la app. 

Color Information

Send Detail

```
Background: #ffffff

Header - Action Bar

    Background: #12aca1
    Text: #FFFFFF

Content
    Padding Left: 16 dp
    Padding Right: 16dp

    Elements
        Titles: 12 SP #e8e8e9
        TextView Active: 14 SP #33333b

    Button
        Background: #1173aa
        Text: 14 SP #ffffff
```

**Comment by vnesita** [comment]
estoy de acuerdo en que se haga en una actividad nueva.
Algo que me parece complicado de esta vista es agregar contacto nuevo, yo dejaría esta función que solamente se realice en la vista de contactos, -que ya en esa vista existe un botón para esto-, y en esta vista solo dejaría la función a la que realmente voy que es enviar los btc. No se que les parece, o si estoy pasando por alto la necesidad de esa función ahí @furszy @Luis-Fernando-Molina esto aplicaría también para la vista de Send Request y Receive.

**Comment by furszy** [comment]
@vnesita  El hecho de que se encuentre ahí es por la restricción que tenemos de que para cualquier tipo de acción que se requiera el usuario debe tener registrado a la otra persona como contacto.
 Por eso se le da la este shortcut de no ir a contactos para agregarlo. Si no, que lo puede hacer desde cualquier vista, al intentar realizar una transacción/request y no tener al otro usuario como contacto.

**Comment by Luis-Fernando-Molina** [comment]
El envío debe hacerse desde una nueva actividad. Hasta donde tenia entendido en esta de acá, lo que se vería sería la lista de transacciones de envio realizadas y la lista de transacciones de envios recibidos, no el formulario de envio en si mismo.

Mejor discutamos en un caso para creado para esto la pantalla de HOME y quedamos todos 100% claro lo que va ahí y como, para luego seguir discutiendo las otras actividades, tambien cada una en su caso.

Mientras tanto adelanto acá cual sería mi análisis por lo menos de la parte principal.

### Actividades que visualizo para esta wallet:

#### Home con 3 tabs: Received | Balance | Sent

Mi granito de arena para la pantalla de HOME: (después lo pueden copiar en otro caso si es necesario)

El usuario de esta wallet debiera tener visible el balance de su wallet, grande y claro. Seria interesante que tuviera algún elemnto gráfico que apoye esta visual como este:

![ccp bitcoin balance](https://cloud.githubusercontent.com/assets/9479367/10636891/e9ea603e-77d8-11e5-9077-62d2c50a1e83.jpg)

Donde el circulo completo pudiera por ejemplo representar el balance promedio (tomando información histórica), la parte pintada, la cantidad que uno tiene en relación al promedio, eso mismo indicaría el porcentaje de arriba. Con otro color en la misma dona, se pudiera representar el balance booked, de manera que si hay una diferencia entre el booked y el available se puede ver a simple vista. En el centro, donde dice 2min, yo pondria 2 BTC y donde dice /60 pondria el tipo de balance que se está mostrando "available" o "booked"

Abajo del círculo, yo pondría un par de iconos que representes cosas del interés del usuario, como por ejemplo:

Si tiene requests pendientes de contestar, pondria un icono que represente los request y el número con la cantidad.

Si tiene requests pendientes de que le contesten a el pondria un icono y la cantidad.

Si recibió algún pago del cual todavía no fue a ver el detalle, pondría un icono y la cantidad de elementos de este tipo.

Si envió algún pago y estos todavía no llegaron a un estado de IRREVERSIBLE pondria un incono y la cantidad de elementos.

Lo anterior es lo que a mi juicio el usuario de esta wallet estaría feliz de ver en su pantalla HOME. Esta pantalla sería la que chequería a cada rato para ver si algo cambió. (su balance, requests entrantes y salientes, pagos entrantes y salientes) todo está ahi de manera muy grafica y agradable.

Como bien explicó Matias, en esta wallet para enviar pagos o requerimientos de que te paguen, debe ser contra un contacto en la wallet.

Osea que siempre hay que seleccionar primero el contacto y luego ir a pagarle.

Para esto identificamos dos caminos:

a. Ir a la actividad de contactos, seleccionar uno por los medios disponibles, y desde adentro del contacto entrar a la actividad de pago o requerimiento de pago.

b. Ir al histórico de pagos realizados y desde ahí entrar a la actividad de pago, tocando en un icono que a su vez está dentro de un registro del histórico, que a su vez tiene asociado un contacto.

Si este histórico se organiza mostrando el ultimo pago primero, sería mas facil iniciar un pago a una persona frecuente desde ahí que yendo por la agenda de contactos, por eso lo organizamos así.

Entonces de ahí surge que en la pestaña del costado izquierdo, están los pagos realizados (SENT no SEND como dice ahora) ordenados del mas reciente al menos reciente. Y a la derecha los pagos recibidos (RECEIVED y no RECEIVE como dice ahora).

#### Contacts Functionality

Lista de contactos con multiples metodos para encontrar los contactos:
1. Search box con filtrado automático
2. Abecedario a la derecha
3. Escroleando la lista

##### Contact Detail

Detalle del contacto con toda su info y disparadores de ciertas acciones como SEND, y REQUEST

##### Add Contact

Alta del contacto.

##### Edit Contact

Modificación del contacto

#### Requests Functionality

##### Requests Received

Histórico de Requests recibidos

##### Request Received Detail

Detalle de un request recibido y dependiendo de su estado, la posibilidad de contestarlo (aceptando o declinando)

##### Requests Sent

Historico de Requests enviados

##### Request Sent Detail

Detalle de un request enviado y dependiendo de su estado, la posibilidad de cancelarlo.

##### Request

Formulario para solicitar que te envien. Se llega aca con un contacto seleccionado.

#### Send Functionality

##### Send

Formulario para enviar. Recordar que se llega aca con un contacto previamente seleccionado.
Su funcionamiento también depende de si se trata de un intra actor o un exta actor.

##### Settings Functionality

Los settings que gobiernan el funcionamiento de esta wallet.

---

Terminemos de discutir en este caso si esas serán las actividades de esta wallet e inmediatamente despues de que estemos de acuero ( @furszy @vnesita y yo) entonces   @vnesita crea un caso por cada actividad donde la discutimos, aprobamos uno por uno y se cierra la discución para esta versión de como tiene que funcionar.

**Comment by vnesita** [comment]
@Luis-Fernando-Molina estoy un poco confundida, pensé que esta wallet estaba lista en cuanto a funcionalidad, que ya tenían claro cómo funciona todo y que solo le faltaba corregir bugs y acomodar la interfaz gráfica, ya que si la entrega es para el 30 de este mes agregar o discutir funcionalidad en este momento obviamente retrasaría esa entrega. Estoy de acuerdo si lo que planteas es una actualización de la misma, y en ir pensando cómo mejorarla, pero por ahora debemos enfocarnos en sacar esta app lo mejor posible tal y como está.

**Comment by Luis-Fernando-Molina** [comment]
El 90 % de la carga de que la wallet funcione esta por debajo, dentro del sistema fermat. Eso es lo que prácticamente está listo.

El 10% de Android no ha parado de evolucionar pasando por diferentes versiones. Es cierto que tenemos que cerrar una lo antes posible, pero la verdad es que no hay una versión cerrada toadvía y lo que yo propongo en realidad es incluso mas o menos lo que hay (salvo la pantalla de balance que es cierto que introduje un aspecto gráfico que nunca se discutió).

Por primera vez estamos discutiendo esto formalmente entre todas las partes que deben decidir: el developer @furszy , UX: @vnesita  y el representante del usuario, osea yo.

En otras palabras todo el trabajo es en gran medida acomodar la interfaz gráfica. Espero que esto aclare :smile:

**Comment by Luis-Fernando-Molina** [comment]
<br>

#### Balance Functionality

---

##### Show Balance

###### Caso Relacionado:

https://github.com/bitDubai/fermat-graphic-design/issues/211

###### Frecuencia de uso:

Frecuencia: 10

Aca se muestra el balance de los distintos tipos, con o sin grafico, como sea.

<br>

#### Transactional Functionality

---

##### Send

###### Frecuencia de uso:

Frecuencia: 7

Formulario para enviar. Recordar que se llega aca con un contacto previamente seleccionado.
Su funcionamiento también depende de si se trata de un intra actor o un exta actor.

Hay tres caminos para llegar al formulario de pago donde se digita el monto:

###### Caso de Uso 1: Botón de Envio

Si hubiera un boton de pago, este navegaría a la lista de contactos donde al seleccionar uno, navegaria al formulario de envío.

###### Caso Relacionado:

https://github.com/bitDubai/fermat-graphic-design/issues/227

Esta lista de contactos estaría ordenada por los contactos a los que se le han realizado la mayor cantidad de envios estarian primero. 

###### Frecuencia de uso:

Frecuencia: 6

###### Caso de Uso 2: Ir por el historico de pago

El usuario recurda que ya le pago a ese contacto recientemente y sabe que el historico esta ordenado por fecha y lo va a encontrar mas rapido ahi.

###### Frecuencia de uso:

Frecuencia: 5

###### Caso de Uso 3 ir por la lista de contactos.

Si estas medio perdido entonces entras a contacto y en el detalle de un contacto encontrarias otro boton de envio que te lleva directo al formulario de pagos.

###### Frecuencia de uso:

Frecuencia: 2

##### Recive

###### Frecuencia de uso:

Frecuencia: 1

Con los intra actors el dinero se recibe sin intervencion del usuario, pero con los exta actor se necesita la funcionalidad necesaria para entrengarle al otro una direccion.

##### Sent history

###### Caso Relacionado:

https://github.com/bitDubai/fermat-graphic-design/issues/211

###### Frecuencia de uso:

####### Caso de Uso 1: Cuando vas al historico para encontrar a alguien a quien pagarle. 

Frecuencia: 6

####### Caso de Uso 2: Cuando uno va a consultar lo que ha enviado y su estado. 

Frecuencia: 2

Necesitamos un histórico de lo que enviamos.

##### Sent Record Detail

###### Frecuencia de uso:

Frecuencia: 1

Detalle del registro de un envió.

##### Recived History

###### Caso Relacionado:

https://github.com/bitDubai/fermat-graphic-design/issues/211

###### Frecuencia de uso:

Frecuencia: 7

Necesitamos un histórico de lo que recibimos.

##### Receive Record Detail

###### Frecuencia de uso:

Frecuencia: 2

Detalle del registro de un una recepción de dinero.

<br>

#### Requests Functionality

---

##### Request

###### Frecuencia de uso:

Frecuencia: 2

Formulario para solicitar que te envien. Se llega aca con un contacto seleccionado. 

Hay dos tipos de request: los que se realizan contra usuarios internos y los que se realizan contra usuarios externos, estos ultimos hay que generar un codigo o un URL para compartirselo por un medio externo al usuario de otro tipo de wallet (no fermat wallet).

En la versión 1 nos vamos con Request contra usuarios internos.

##### Requests Sent

###### Frecuencia de uso:

Frecuencia: 2

Histórico de Requests enviados

##### Request Sent Detail

###### Frecuencia de uso:

Frecuencia: 1

Detalle de un request enviado y dependiendo de su estado, la posibilidad de cancelarlo.

##### Requests Received

###### Frecuencia de uso:

Frecuencia: 2

Histórico de Requests recibidos

##### Request Received Detail

###### Frecuencia de uso:

Frecuencia: 1

Detalle de un request recibido y dependiendo de su estado, la posibilidad de contestarlo (aceptando o declinando)

<br>

#### Contacts Functionality

---

##### Contact  List

###### Caso Relacionado:

 https://github.com/bitDubai/fermat-graphic-design/issues/203

###### Frecuencia de uso:

####### Caso de Uso 1: Consultar la lista de contactos fuera del circuito de pago. 

Frecuencia: 4

####### Caso de Uso 2: Consultar la lista de contactos para realizar un pago  / request. 

Frecuencia: 7

Lista de contactos con múltiples métodos para encontrar los contactos:
1. Search box con filtrado automático
2. Abecedario a la derecha
3. Escroleando la lista

##### Contact Detail

###### Frecuencia de uso:

####### Caso de Uso 1: Consultar la lista de contactos fuera del circuito de pago. 

Frecuencia: 4

####### Caso de Uso 2: Consultar la lista de contactos para realizar un pago  / request. 

Frecuencia: 7

Detalle del contacto con toda su info y disparadores de ciertas acciones como SEND, y REQUEST

##### Add Contact

###### Frecuencia de uso:

####### Caso de Uso 1: Intra Wallet User. 

Frecuencia: 3

####### Caso de Uso 2: Extra Wallet User. 

Frecuencia: 1

Alta del contacto.

Tener en cuenta de que hay dos sub tipos de contactos, los usuarios internos, y los externos. Los contactos internos son conexiones que se transforman en contactos.

##### Edit Contact 1

###### Frecuencia de uso:

####### Caso de Uso 1: Editar un contacto interno. 

Frecuencia: 1

####### Caso de Uso 2: Editar un contacto externo. 

Frecuencia: 2

Modificación del contacto

##### Delete Contact 1

###### Frecuencia de uso:

Frecuencia: 1

Eliminar del contacto

<br>

##### Settings Functionality

---

##### Wallet Setting

###### Frecuencia de uso:

Frecuencia: 1

Los settings que gobiernan el funcionamiento de esta wallet.

##### User Preferences

###### Frecuencia de uso:

Frecuencia: 1

Si hubiera, aquí irían las preferencias del usuario.

<br>

##### Menú de la aplicación

---

Navigation Drawer

###### Caso Relacionado:

https://github.com/bitDubai/fermat-graphic-design/issues/205

**Comment by Luis-Fernando-Molina** [comment]
Estamos de acuerdo con esta definicion? @vnesita @furszy

**Comment by Luis-Fernando-Molina** [comment]
:+1:

**Comment by vnesita** [comment]
:+1:

**Comment by furszy** [comment]
:+1:  :smile:
