### ISSUE TITLE
Customer Broker Wallet Wireframe

### ISSUE THREAD

**Issue by Neoperol** [bitDubai/fermat-graphic-design#199]
En desarrollo el wireframe del Customer Wallet. 
Se establecieron 3 actividades principales. 

Home, donde se manejan las negociaciones y los contratos. 
Broker List, con el listado de los Brokers que ya fueron agregados de la Broker Community por el Customer. 
Contract History, donde se pueden ver los contratos en sus diferentes estados.

La acción principal que hace el usario después de enlazar su Identity a la wallet es enviar Negociaciones a los Brokers de su lista de Brokers y manejar dichas negociaciones interactuando con el Broker modificando las clauslas correspondiente a cada tipo de negociación. 

https://ninjamock.com/s/6R33T

**Comment by Luis-Fernando-Molina** [comment]
Perfecto, transforma esto en un SUPER ISSUE por favor y discutamos cada pantalla de esta Wallet en su propio caso.
