### ISSUE TITLE
Bocetar ideas para la imagen de Fermat

### ISSUE THREAD

**Issue by m471c4** [bitDubai/fermat-graphic-design#20]
Viene del #13

Hasta ahora se ha trabajado con una especie de icono de wallet. En necesario crear un isologo que represente verdaderamente la aplicación y todo el concepto detrás de ella.

![fermat_dmp_lq](https://cloud.githubusercontent.com/assets/13468350/9078810/f95eadbc-3b0c-11e5-933c-f05078762d17.png)

**Comment by Luis-Fernando-Molina** [comment]
:+1:

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina Propongo realizar varias series de bocetos (3 propuestas de logo) para la creación del isotipo de Fermat. 

Puedo realizar una primera serie de bocetos en un tiempo estimado de 1 día y medio.

**Comment by Luis-Fernando-Molina** [comment]
:+1:  ponganse de acuerdo entre ustedes. Cada cosa que hagás , aunque sea intermedia subila al issue así se puede ir viendo y se puede ir opinando.

**Comment by arnaldos** [comment]
ok perfecto !!! voy a ir trabajando en eso !!

**Comment by arnaldos** [comment]
Para el logo de fermat se creó un teléfono con billetes con el símbolo de bitcoin para representar una wallet digital, formando un icono fácil de identificar.
También doy sugerencia de un refrescamiento de tipografía podemos  apreciarlo en las imágenes que envío. 
Esta tipografía es una tipografía fresca e innovadora que nos transmite tecnología que es otro punto que se quiere vender, ya que la wallet digital es parte de una nueva tecnología que nos permite tener acceso a nuestro dinero desde una plataforma digital a través de un teléfono, pc u otros, y poder hacer uso de el cuándo lo deseemos. 

![fermat_version_1-1](https://cloud.githubusercontent.com/assets/13594347/9175991/736a5b76-3f52-11e5-8f79-f2ce855d0ba4.jpg)
![fermat_version_1-2](https://cloud.githubusercontent.com/assets/13594347/9175992/73a1154e-3f52-11e5-8daa-6befc389304c.jpg)
![fermat_version_1-3](https://cloud.githubusercontent.com/assets/13594347/9175993/73b098de-3f52-11e5-9f40-a67862c53419.jpg)
![fermat_version_1-4](https://cloud.githubusercontent.com/assets/13594347/9175994/73bb289e-3f52-11e5-9541-a5bb1b607964.jpg)
![fermat_version_1-5](https://cloud.githubusercontent.com/assets/13594347/9175995/73bd86a2-3f52-11e5-8f81-fa3bad3370ea.jpg)

**Comment by arnaldos** [comment]
Hola @Luis-Fernando-Molina a continuación envío las primera propuestas del logo de Fermat. quedo atento a los comentarios.

**Comment by Luis-Fernando-Molina** [comment]
@arnaldos  se ve lindo pero hay varias cosas que no aplican:

1-La plataforma no es para teléfono (empezamos por Android pero corren en cualquier sistema operativo)
2-No es para bitcoin (es solo la primera crypto currency que implementamos)

El fin de semana escribí el README del proyecto. Te recomiendo leerlo porque es un buen resumen de lo que es fermat:  https://github.com/bitDubai/fermat/blob/master/README.md

Sigamos avanzando.

Saludos,
Luis

**Comment by m471c4** [comment]
Hola @arnaldos, tengo algunos comentarios:

Una de las cosas que quería corregirse en los isologos anteriores era la presencia de elementos muy pequeños que se perderían en la reducción. Acá ese problema persiste, además hay algunos elementos que hacen ruido (los indico en la imagen de abajo). 

![fermat](https://cloud.githubusercontent.com/assets/13468350/9179200/c547723c-3f64-11e5-8850-62ef8df7c492.png)

**Comment by arnaldos** [comment]
Hola @m471c4 gracias por las criticas constructivas las voy a tomar en cuenta en los próximos ajustes, aunque este no es el definitivo, en este momento voy a replantear el concepto siguiendo los comentarios  que dejo luis.

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina 
En esta versión buscamos dar énfasis en la billetera, creando un imagotipo sencillo y fácil de recordar.
![fermat_version_1-7](https://cloud.githubusercontent.com/assets/13594347/9190731/aa2dfd96-3fc2-11e5-9c80-06436b1c3734.jpg)
![fermat_version_1-8](https://cloud.githubusercontent.com/assets/13594347/9190732/aa9de610-3fc2-11e5-8ce8-fd81e7639f6a.jpg)
![fermat_version_1-6](https://cloud.githubusercontent.com/assets/13594347/9190733/aaa1e620-3fc2-11e5-864c-5fdf17e04564.jpg)

**Comment by Luis-Fernando-Molina** [comment]
Me gustaría encontrar una representación gráfica mas allá de la inicial de la palabra. Para la Digital Money Platform la encontramos con la billetera grande que contenia otras chiquitas. Para esto no se como puede ser, pero me gustaría seguir esa línea.

**Comment by arnaldos** [comment]
Hola a continuación muestro los nuevo ajustes del logo fermat: 
![fermat_version_1-8](https://cloud.githubusercontent.com/assets/13594347/9226903/a09e094c-40da-11e5-88b3-e7ae67843e4a.jpg)
![fermat_version_1-6](https://cloud.githubusercontent.com/assets/13594347/9226904/a0a3c0f8-40da-11e5-92a6-eb80ed272f8e.jpg)
![fermat_version_1-7](https://cloud.githubusercontent.com/assets/13594347/9226905/a0a5a526-40da-11e5-97be-496b06a3242a.jpg)

**Comment by arnaldos** [comment]
disculpen estos son los mismo anteriores.

**Comment by arnaldos** [comment]
Hola a continuación los ajustes de la identidad de Fermat:
Se realizó una síntesis de una billetera, combinado de una paleta de colores de tonos naranja y blancos que nos permite tener un icono más limpio y fácil de entender. 
La idea de esto es que el icono permita identificarse con la menor cantidad de elementos posibles. 
En esta serie de bocetos podemos encontrar:
1-El primer concepto está asociado a la network, ya que se busca un vínculo entre los usuarios y la billetera digital, por lo tanto podemos ir enfocando este concepto para Fermat P2P.
2-El segundo concepto se enfoca únicamente a la Wallet como único icono, que sería el que representara a Fermat como app principal. Para ellos muestro dos formas de diagramación del mismo.

**Comment by arnaldos** [comment]
![fermat_version_1-9](https://cloud.githubusercontent.com/assets/13594347/9232153/d4edb39e-40f5-11e5-8c26-468c3e868121.jpg)
![fermat_version_1-10](https://cloud.githubusercontent.com/assets/13594347/9232154/d4f5ffc2-40f5-11e5-95bc-1a9a255bbe00.jpg)
![fermat_version_1-11](https://cloud.githubusercontent.com/assets/13594347/9232155/d4fcbe02-40f5-11e5-8813-2158f0d5b9d4.jpg)
![fermat_version_1-12](https://cloud.githubusercontent.com/assets/13594347/9232156/d5182c28-40f5-11e5-9280-9d7837b4221a.jpg)

**Comment by Luis-Fernando-Molina** [comment]
![icono fermat](https://cloud.githubusercontent.com/assets/9479367/9232987/d7494fa0-4130-11e5-8e35-bc2ad1b49159.jpg)

**Comment by arnaldos** [comment]
Ajustes logo fermat, se modifico pequeños detalles en los iconos para genera mejor lectura del mismo 

![fermat_version_2-1](https://cloud.githubusercontent.com/assets/13594347/9235229/322c4b54-4107-11e5-8a92-159aac0ce209.jpg)
![fermat_version_2-2](https://cloud.githubusercontent.com/assets/13594347/9235230/32310b44-4107-11e5-8b44-8a79ee8a88a6.jpg)
![fermat_version_2-3](https://cloud.githubusercontent.com/assets/13594347/9235231/325c518c-4107-11e5-843a-4bb00ae11638.jpg)

**Comment by Luis-Fernando-Molina** [comment]
@arnaldos muy bien! Hay que elegir o como es el tema?

**Comment by arnaldos** [comment]
Si @Luis-Fernando-Molina referente al icono coloque varias versiones para poder discutir cual se adapta mejor para la aplicación mi recomendación es el que esta afuera del circulo con el texto por debajo. se ve mas limpio y mantiene la paleta de colores.

**Comment by Luis-Fernando-Molina** [comment]
que opine @m471c4

**Comment by arnaldos** [comment]
Hola @m471c4 cuando tengas un tiempo dame tus comentarios para ver si podemos avanzar con este caso.

**Comment by m471c4** [comment]
Hola, buenas tardes. Me parece que el 7mo es el mejor, ya que no tiene el círculo que lo encierra. @arnaldos ¿qué tipografía estás usando? ¿podrías subirlo en grande para poder apreciarlo mejor?

**Comment by arnaldos** [comment]
ok @m471c4 ya lo subo !!! la tipografía que tiene esa versión es la que tenia por defecto  Myriad pro podríamos colocarle Caviar Dreams y así queda alineado con la tipografía de bigDubai. ya subo las versiones con ambas tipografías para ver como se comportan.

**Comment by arnaldos** [comment]
Con la tipografía Myriad pro
![fermat_version_2-4](https://cloud.githubusercontent.com/assets/13594347/9286657/cbc79b54-42c1-11e5-9402-e637d22b3130.jpg)

**Comment by arnaldos** [comment]
Con la tipografía Caviar Dreams
![fermat_version_2-5](https://cloud.githubusercontent.com/assets/13594347/9286662/e2be6fb8-42c1-11e5-818d-ac06d8a31ff6.jpg)

**Comment by arnaldos** [comment]
Con la tipografía Canaro
![fermat_version_2-6](https://cloud.githubusercontent.com/assets/13594347/9286665/f8d35e9e-42c1-11e5-83e8-df616cb253c6.jpg)

**Comment by Luis-Fernando-Molina** [comment]
La tipografía me gustan las 3, eligan ustedes.

**Comment by Luis-Fernando-Molina** [comment]
Corrijo, cualqueira de las 2 ultimas. Pudiera ser la ultima así nos separamos un toque de bitDubai?

**Comment by arnaldos** [comment]
ok perfecto !!! si la idea es tener un toque diferenciador da bigDubai sin perder el enlace entre ellos

**Comment by Luis-Fernando-Molina** [comment]
Entonces que la 3ra tipografía para fermat, no?

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina  perfecto!!! el logo de Fermat queda con la 3ra tipografia (Canaro) con esto cerramos el caso.
