### ISSUE TITLE
CCP/ Navigation Drawer

### ISSUE THREAD

**Issue by vnesita** [bitDubai/fermat-graphic-design#200]
vista actual
![screenshot_2015-10-20-17-42-35](https://cloud.githubusercontent.com/assets/6201065/10628372/693af956-77a3-11e5-9035-105f95b017df.png)
vista nueva
![view_drawer](https://cloud.githubusercontent.com/assets/6201065/10628458/4a5396f0-77a4-11e5-9b0b-a173d7d375bd.jpg)
Cambiar el estilo y los colores (los colores se encuentran en el doc del drive https://docs.google.com/document/d/10pSOX2s2xUsKOeJiaJ2rdtdVn29C2b_KcLIItL58Sm8/edit?usp=sharing, en la parte de Navigation Drawer, los recursos se encuentran en su respectiva carpeta)
- Funcionalidad: si la flecha de cambiar identidad aún no va a funcionar yo aconsejaría quitarla hasta que esté lista esta función, ya que colocar botones que no hagan funciones puede confundir al usuario.
- Animación: cuando presiono el botón del menú el navigation drawer debería deslizarse por encima de las vista, opacando un poco lo que queda debajo, cuando le doy a algun enlace el navigation drawer debe deslizarse de regreso y aparecer la vista a donde quiero ir, sin tener pantalla negra de loading, el loading debe hacerse dentro de la misma vista.

nota: @Neoperol @furszy los enlaces de la vista nueva no concuerdan con la actual, como quedarían? con los enlaces de la actual o de la nueva?

**Comment by Luis-Fernando-Molina** [comment]
Por favor tener en cuenta la discución que se está llevando en https://github.com/bitDubai/fermat-graphic-design/issues/198 para determinar los items que irían en el Navigation Drawer.

Desde el punto de vista estético mi opinión es que los renglones son muy finos y queda demasiado espacio en blanco sin utilizar. 

Veamos antes que nada que opciones deberían estar realmente allí.

**Comment by Luis-Fernando-Molina** [comment]
@vnesita sabemos que cada wallet va a tener su propio estilo gráfico y que este deriva inicialmente de icono y en segunda medida del banner de la wallet. Como impacta esto en el estilo gráfico de esta wallet? podemos tener un caso donde lo discutamos? colores, donde van, tipo de letra, etc, y demás.

**Comment by Neoperol** [comment]
> @vnesita sabemos que cada wallet va a tener su propio estilo gráfico y que este deriva inicialmente de icono y en segunda medida del banner de la wallet. Como impacta esto en el estilo gráfico de esta wallet? podemos tener un caso donde lo discutamos? colores, donde van, tipo de letra, etc, y demás.

Está wallet ya se diseño tomando en cuenta los colores del logo. Lo único que falta es unificar la tipografia que en varias partes de la APP se usan estilos diferentes. 

@Luis-Fernando-Molina 
@furszy

**Comment by Luis-Fernando-Molina** [comment]
> Está wallet ya se diseño tomando en cuenta los colores del logo. Lo único que falta es unificar la tipografia que en varias partes de la APP se usan estilos diferentes. 

Estoy de acuerdo con eso
