### ISSUE TITLE
CCP/ Corregir vista Contacts

### ISSUE THREAD

**Issue by vnesita** [bitDubai/fermat-graphic-design#203]
vista actual
![screenshot_2015-10-20-17-42-47](https://cloud.githubusercontent.com/assets/6201065/10637650/8c31e6f8-77e5-11e5-912e-ccd085812e64.png)
vista nueva
![view_contacts](https://cloud.githubusercontent.com/assets/6201065/10638045/b4f38590-77e7-11e5-8472-bb7bce23b6c5.jpg)
- Cambiar colores de la barra del buscador, los colores y los tamaños y estilo de las tipografias están en el doc de drive 
  https://docs.google.com/document/d/10pSOX2s2xUsKOeJiaJ2rdtdVn29C2b_KcLIItL58Sm8/edit
- Cambiar icono de lupa en la barra del buscador (recurso en drive)
- Cambiar el botón de crear nuevo usuario (recurso en drive)

**Comment by vnesita** [comment]
Vista de lista de contactos contiene: Buscador de contactos, Contactos listados alfabéticamente, es scroliable, botón para agregar un nuevo contacto

Cambios: color de la barra de buscador y forma de la imagen del usuario ahora es circular.

![view_contact](https://cloud.githubusercontent.com/assets/6201065/10732128/b7d19512-7bdf-11e5-9273-dd88c87a72a1.jpg)
@Luis-Fernando-Molina

**Comment by Luis-Fernando-Molina** [comment]
Me gustaria ver el analisis de que pasa cuando escribis en SEARCH: yo filtraria dinamicamente los contactos y resaltaria la parte del nombre con otro color remarcando donde está encontrándose la coincidencia.

Otra cosa, en algun momento teníamos un alfabeto a la derecha que servia para ir a una letra en particular. No lo vamos a tener al final? @furszy @vnesita ?
