### ISSUE TITLE
CCP / Diseño Navigation Drawer 

### ISSUE THREAD

**Issue by vnesita** [bitDubai/fermat-graphic-design#205]
- Crear el diseño del menú para la bitDubai Bitcoin Wallet
- Llevar apariencia y colores planteados en el icono y el banner de esta wallet, también tomando en cuenta la iconografía y tipografía usada en la app.

**Comment by vnesita** [comment]
![view_drawer2](https://cloud.githubusercontent.com/assets/6201065/10649274/d7e286ac-7821-11e5-8d4e-71bde674bfd9.jpg)

**Comment by vnesita** [comment]
@Luis-Fernando-Molina mira ahora el drawer, aquí podríamos discutir la apariencia

**Comment by Luis-Fernando-Molina** [comment]
Ok, respecto a la apariencia, el nombre queda bien al costado porque la foto esta al otro costado. Cuando la foto esté al centro no va a quedar tan bien, correcto?

Respecto al contenido me parece que hay cosas que faltan, @vnesita   ya pensaste en el contenido?

**Comment by vnesita** [comment]
![view_drawer3](https://cloud.githubusercontent.com/assets/6201065/10666868/f773330e-78b2-11e5-98fd-a83870d72503.jpg)
pienso que de igual manera se ve bien, en cuanto al contenido, espero porque lo definamos hoy en la reunión con Matias, por ahora solo coloque el que está en la versión actual.

**Comment by vnesita** [comment]
@Luis-Fernando-Molina disculpa no te nombre ayer en este

**Comment by Luis-Fernando-Molina** [comment]
Y claro con esa foto que pusiste como no se va a ver bien!!!! JA JA, dale agregamos la discución de este punto a la reunion de esta tarde :smile:

**Comment by vnesita** [comment]
vista drawer con secciones habladas en reunión 
![view_navigation](https://cloud.githubusercontent.com/assets/6201065/10711866/c4f2a14c-7a67-11e5-96b1-dad9fdc2ce5e.jpg)

**Comment by Luis-Fernando-Molina** [comment]
PRegunta, el Navigation Drawer, solo aparecería sobre la vista home? o en todas las otras? Me parece que solo en la home, con lo cual que tenga una opción HOME no me parece que valga la pena, no?

**Comment by vnesita** [comment]
el navigation aparecería en todas las vistas padre, o sea las que están en este menú @Luis-Fernando-Molina

**Comment by vnesita** [comment]
de esta forma navegaría por toda la app sin tener que llegar a un sitio específico para ir a donde quiero ir

**Comment by Luis-Fernando-Molina** [comment]
ok, de acuerdo con eso.

**Comment by vnesita** [comment]
para mi esta vista está lista, @Luis-Fernando-Molina espero por tu aprobación para pasarla a los desarrolladores

**Comment by Luis-Fernando-Molina** [comment]
:+1:

**Comment by Neoperol** [comment]
@furszy 
@Luis-Fernando-Molina  

Los recursos están en la carpeta view_Navigation_Drawer

Navigation Drawer

```
Background: #ffffff

Header
    Image 
        Height 160 dp
    Username
        Background: #33000000 / id: bg_black_a20
                    Text: id: Roboto Light #FFFFFF
                    Height:40dp


List Elements
    Padding left: 14 dp
            Padding right: 14 dp
    Icons 26 x 26 dps
    Alert Icon: 16 x 16 dp
Active
    Text: #669d8c
    Normal
        Text: #4a4a4a 

    Divider: #e1e1e1
```

**Comment by Neoperol** [comment]
@furszy 

Cambios en el Navigation Drawer.

Cambiar el icono de la vista que esta Activa. 

Cambiar los colores. 
Active
    Text: #669d8c
Normal
    Text: #4a4a4a 

Agregar el icono en el Notification Payment request
ic_drawer_alert.png
