### ISSUE TITLE
CCP/ Vista agregar nuevo contacto

### ISSUE THREAD

**Issue by vnesita** [bitDubai/fermat-graphic-design#208]
vista cuando le doy por primera vez a agregar contacto
![screenshot_2015-10-22-11-42-39](https://cloud.githubusercontent.com/assets/6201065/10668433/0b793b3e-78bb-11e5-9f7e-b41145fd5f88.png)
esta vista no me queda muy clara lo que se va a hacer, me parece que puede confundir al usuario, por qué no se muestra desde un principio esta vista?
![screenshot_2015-10-21-17-35-59](https://cloud.githubusercontent.com/assets/6201065/10668510/5bc19654-78bb-11e5-9c6c-8919521f0d02.png)
con estos cambios
![view_contacts_popup](https://cloud.githubusercontent.com/assets/6201065/10669186/3ab82e66-78be-11e5-9b66-dc2b0ddee05c.jpg)
 Los colores y estilo están en doc del drive

**Comment by nattyco** [comment]
@furszy Matias fijate lo que comenta Vanessa, asi me explicas como seria este tema.

**Comment by Luis-Fernando-Molina** [comment]
@furszy explicá por favor cual es la lógica en el manejo de contactos. Estamos hablando específicamente de la actividad ADD CONTACT.

#### Mi análisis:

---

Hay dos tipos de contactos: 

##### Contactos internos:

Para este tipo de contacto se requiere la siguiente información:
1. Nombre
2. Foto (opcional)
3. Alias

Los contactos internos son "Crypto Wallet Intra Users" o lo que antes llambamos simplemente "Intra Users" con los cuales el usuario ya tiene una conexión establecida (es decir envio una solicitud de conexión y se la aceptaron o recibió una solicitud y la aceptó, todo esto en la "Crypto Wallet Intra User Community" SUB APP. (al público quizas tenga otro nombre).

Con lo cual para este tipo de contacto, realmente lo que se hace es seleccionar de la conexiones establecidas que todavía no son contactos, cual quiere el usuario transformar como contacto en esta wallet. 

El nombre y la foto no son datos editables porque vienen desde el otro usuario. Si el Alias, que lo puede poner este usuario libremente.

##### Contactos externos:

Para este tipo de contacto se requiere la siguiente información:
1. Nombre (se digita)
2. Crypto Address  (se digita, se escanea el código, se pega el contenido del porta papeles.)
3. Foto (opcional) (se selecciona de la galeria, se toma con la camara)
4. Alias (opcional) (se digita)

Toda la información en este caso se tiene que ingresar porque no hay contacto con el usuario interno a través del sistema.

**Comment by furszy** [comment]
Eso estuvimos hablando hace unos momentos. nosotros, en el home, a la hora de recibir,enviar dinero o enviar un request lo que hacemos es escribir en el campo el nombre del contact, mientras vas escribiendo letra a letra el nombre, te aparece una lista de sugeridos. en esa lista se van a mostrar dos tipos de datos:
- Los contactos de la wallet en un color, ( estos pueden ser intra o extra users que ya se encuentran agregados como contacto)
- Las conexiones previamente agregadas en la subApp intra user community,

Si el usuario decide seleccionar una conexión lo que se hace es agregarla a la wallet como nuevo contacto y realizar la acción que se requiera.
Si el usuario no encuentra el contacto quiere decir que se requiere agregar un extra user por lo cual se abré el popup de agregar un contacto con el address activo.

**Comment by Luis-Fernando-Molina** [comment]
> Eso estuvimos hablando hace unos momentos. nosotros, en el home, a la hora de recibir,enviar dinero o enviar un request lo que hacemos es escribir en el campo el nombre del contact, mientras vas escribiendo letra a letra el nombre, te aparece una lista de sugeridos. en esa lista se van a mostrar dos tipos de datos:

A la hora de enviar? 

Acá tenemos una discrepancia mayor. Para llegar al formulario de enviar se va por dos caminos que ya lo expliqué en otro caso: 
1. Seleccionando el contacto.
2. Usando el historico de SENT o de RECEIVED.

No vamos a permitir de que se llegue a la pantalla de enviar para seleccionar un contacto en ese momento.

> escribir en el campo el nombre del contact, mientras vas escribiendo letra a letra el nombre, te aparece una lista de sugeridos. en esa lista se van a mostrar dos tipos de datos:
> 
>    Los contactos de la wallet en un color, ( estos pueden ser intra o extra users que ya se encuentran agregados como contacto)
> 
>    Las conexiones previamente agregadas en la subApp intra user community,
> 
> Si el usuario decide seleccionar una conexión lo que se hace es agregarla a la wallet como nuevo contacto y realizar la acción que se requiera.
> 
> Si el usuario no encuentra el contacto quiere decir que se requiere agregar un extra user por lo cual se abré el popup de agregar un contacto con el address activo. 

Lo que vos estás describiendo puede ser que funcione así la pantalla de agregar contacto, pero no el de enviar. De todas maneras en este caso estamos dicutiendo la pantalla de agregar un contacto, asi que podemos dejar la discución de lo que pasa en la de enviar para el caso correspondiente.
