### ISSUE TITLE
SUPER ISSUE: Intra User Community App Design

### ISSUE THREAD

**Issue by Neoperol** [bitDubai/fermat-graphic-design#209]
Crear vistas para la Intra User Community App.
La APP contara con 4 Vistas Principales.
Explore, donde se podrán buscar nuevos usuarios para conectarse y estarán ordenados por distancia.
Your friends, es una lista de los usuarios a los que ya estas conectados. 
Notifications, donde llegaran las notificaciones sobre nuevos usuarios que quieran conectarse contigo. 
Settings, donde se podrá configurar la APP, en una primera etapa solo se podrá cambiar el Identity que está relacionada con esta APP.

@Luis-Fernando-Molina 
@Luda16

**Comment by furszy** [comment]
@Luis-Fernando-Molina, toda tuya.

**Comment by Luis-Fernando-Molina** [comment]
Deberia existir además:
1. Un detalle de la conexión, donde uno potencialmente pudiera desconectarse de esa otra persona, y ver alguna info relacionada a la conexion (como por ejmplo desde cuando).
2. Una vista del Perfil de la otra persona, serviria para ver información mas detallada del otro antes de aceptar la conexion (aunque ahora no se explote o disponga de otras informaciones en el futuro cercano pudiera existir).

**Comment by Neoperol** [comment]
Esa vista extra y el dialog para aceptar la conexión están en los issues de sus respectivas vistas. 

> Un detalle de la conexión, donde uno potencialmente pudiera desconectarse de esa otra persona, y ver alguna info relacionada a la conexion (como por ejmplo desde cuando).
> Una vista del Perfil de la otra persona, serviria para ver información mas detallada del otro antes de aceptar la conexion (aunque ahora no se explote o disponga de otras informaciones en el futuro cercano pudiera existir).

**Comment by furszy** [comment]
@Neoperol groso!

**Comment by furszy** [comment]
@Luis-Fernando-Molina @Neoperol  Quisiera saber el estado total de está sub app ya que fueron discutidas todas las pantallas.

**Comment by Neoperol** [comment]
@Luis-Fernando-Molina Creo que Matias está un poco ansioso en comenzar a hacer los cambios en está Sub APP. Nos avisas si piensas que hay algo en el aire, pero creo que no. Esta Sub APP es bastante sencilla y las modificaciones que se hicieron fueron tomando en cuenta que en futuro la SUP APP puede crecer y tener Chat y mayor interacción entre los usuarios.

**Comment by Luis-Fernando-Molina** [comment]
Cada vez que pongo :+1:  @Neoperol podes cerrar ese caso.

Si estan todos los casos cerrados del SUPER ISSUE, cerras el superissue.

Si en algun caso esperan por mi por mas de un día, etiquetame de nuevo que quizas se me pasó.

**Comment by Neoperol** [comment]
@furszy 
@josemanueldsds
