### ISSUE TITLE
Intra User Community App Design / Explorer

### ISSUE THREAD

**Issue by Neoperol** [bitDubai/fermat-graphic-design#210]
#209

Explore, donde se podrán buscar nuevos usuarios para conectarse y estarán ordenados por distancia.
Your friends, es una lista de los usuarios a los que ya estas conectados. 
Además cuenta con un buscador. 
Si se puede tomar la información de la distancia, se puede colocar en el grid ese dato al lado de un icono. 

@Luis-Fernando-Molina 
@Luda16 

![view_home](https://cloud.githubusercontent.com/assets/6201081/10721703/41c6aff2-7b7a-11e5-997a-1c2e43b59f72.jpg)

**Comment by Neoperol** [comment]
Vista de los grids, con un usuario sin imagen. 

![view_home_empty](https://cloud.githubusercontent.com/assets/6201081/10855911/731aa384-7f16-11e5-9257-60b47496e005.jpg)

Vista del grid vacio. En caso de que no le llegue data al usuario. 

![view_home_empty_list](https://cloud.githubusercontent.com/assets/6201081/10855912/731c1fac-7f16-11e5-80dc-33fece118917.jpg)

@Luis-Fernando-Molina

**Comment by Luis-Fernando-Molina** [comment]
1. Se dice "there are no users available"
2. La busqueda debe ser por nombre y por lugar ej: Gregory | Pais | Estado, Provincia | Ciudad
3. Si te va a llegar el dato de donde está: Ciudad | Estado, Provincia | Pais y lo debieras poner sintentizado en la grilla.

**Comment by Neoperol** [comment]
@Luis-Fernando-Molina 

View Explore con el Location de los usuarios. 

![view_home](https://cloud.githubusercontent.com/assets/6201081/10864533/cb227776-7fc2-11e5-9d26-a5d973d4bc48.jpg)

**Comment by Neoperol** [comment]
Esta pendiente por revisión

@Luis-Fernando-Molina 
@furszy

**Comment by Luis-Fernando-Molina** [comment]
:+1:

**Comment by Neoperol** [comment]
@furszy 

Los recursos de esta vista están en la carpeta view_explorer. 
Colores y tamaños. 

https://docs.google.com/document/d/1FYbk4A5Cgbtpy33UVGo4X5da4o3tgVRhgXMr5jdigEs/edit

**Comment by Neoperol** [comment]
@furszy 
@josemanueldsds

**Comment by Neoperol** [comment]
![view_home](https://cloud.githubusercontent.com/assets/6201081/11889325/34a9a72e-a51a-11e5-98ea-82583f0ab438.jpg)

Online
 Background: #0072bb
 Text: 14sp #ffffff
Offline
 Background: #ffffff
 Text: 14sp #4d4d4d

El nombre debe estar con un tamaño mas grande 15SP y estilo mas grueso que el indicador offline y online; regular o normal. 

@josemanueldsds 
@Luis-Fernando-Molina

**Comment by Luis-Fernando-Molina** [comment]
Puede ser asi. Fijate @josemanueldsds que me parece que el tamaño del texto y de las barras en tu app son mas grande que lo que plantea @Neoperol

**Comment by josemanueldsds** [comment]
@Luis-Fernando-Molina El layout posee las especificaciones dadas por @Neoperol en el texto mencionado arriba

**Comment by Luis-Fernando-Molina** [comment]
@Neoperol revisa entonces la APP porque luce como que no se ve igual con las especificaciones que pasas. O quizas soy yo o mi telefono.
