### ISSUE TITLE
CCP/ vista Home

### ISSUE THREAD

**Issue by vnesita** [bitDubai/fermat-graphic-design#211]
Crear a vista home de la bitDubai Bitcoin Wallet, teniendo en cuenta sus principales funciones:
1. Enviar BTC (send)
2. Recibir BTC (received)
3. Recibir request de personas (request)
4. Mostrar el Balance 

Mi Análisis para esta vista:
- Debe tener fácil acceso para ir entre Request, Received y Send 
- Los secciones de Request y Received deben tener una forma de aviso que ha llegado uno o varios nuevos, para cuando estes en alguna otra vista u otra sección puedes saber que llegó.
- El Balance debe estar visible siempre en esta vista, ya que es información importante para el usuario.
- Las secciones de Request, Received y Send deben tener un botón para crear nuevo

**Comment by Luis-Fernando-Molina** [comment]
Este caso es hijo de https://github.com/bitDubai/fermat-graphic-design/issues/198

**Comment by vnesita** [comment]
![view_home_request2](https://cloud.githubusercontent.com/assets/6201065/10696420/702351d4-7986-11e5-914f-f907ed620ff5.jpg)

**Comment by vnesita** [comment]
<br>

#### Puntos destacados de la reunión:
- Mostrar Balance
- Tener un tabbar con las lista de Sent y Reiceved (este último deben tener alguna forma de notificar si hay nueva)
- Tener visible el botón de Enviar

**Comment by vnesita** [comment]
vista home  book balance
![home](https://cloud.githubusercontent.com/assets/6201065/10711836/d4ed28c0-7a66-11e5-9a29-44ce7e135867.jpg)
vista home  available balance
![home_b_av](https://cloud.githubusercontent.com/assets/6201065/10711838/d9f35786-7a66-11e5-94f9-797b66581251.jpg)

**Comment by Luis-Fernando-Molina** [comment]
Ok, en general esta muy bien. Podemos empezar a discutir los detalles.

**Comment by vnesita** [comment]
Estoy haciendo otra versión, aún el gráfico en porcentaje no me termina de cuadrar. @Luis-Fernando-Molina

**Comment by Luis-Fernando-Molina** [comment]
Ok , de paso corregy el type RECEIVE deberia ser RECEIVED

Pregunta, el circulito con la cantidad de cosas nuevas (2) no deberia ser Naranja? me parece que en todas las APPs es de ese color, o rojo o algo asi.

**Comment by vnesita** [comment]
ok ya corrijo el RECEIVED. 

El color del icono depende del diseño, fíjate por ejemplo en whatsapp. Lo podría colocar rojo a ver que tal se ve @Luis-Fernando-Molina

**Comment by vnesita** [comment]
aquí las correcciones y la nueva versión, aunque tengo otra idea para que el gráfico se vea un poco más vistoso y sea en circulo, creo que de esta forma se entendería mucho más.

home cuando los dos balances no están iguales
![home_balance 2](https://cloud.githubusercontent.com/assets/6201065/10712403/1d1098be-7a79-11e5-9ac5-ad49c54ee173.jpg)

home cuando los dos balances están iguales
![home_balance 2 iguales](https://cloud.githubusercontent.com/assets/6201065/10712407/46d5c05c-7a79-11e5-93ff-0f41126014d8.jpg)

Aquí en el balance mostramos realmente lo que quiere ver el usurio que es la cantidad de dinero que tiene en los dos tipos de balance y sin tener que tocar para ir de uno al otro @Luis-Fernando-Molina @furszy 

en un rato subo la otra propuesta con este mismo enfoque.

**Comment by Luis-Fernando-Molina** [comment]
Hay una cosa que tenes que saber: a muy poca gente le interesa el book balance. Debe existir porque te permite saber porque no tenes determianda cantidad de dinero todavia, pero su frecuencia es muy inferiorio a la del available.

**Comment by Luis-Fernando-Molina** [comment]
Si pudieras mostrarlo quizas en la eventualidad que no coincidan, pero mucho mas chiquito que el otro, mientras coincidan, quizas que ni se vea.

**Comment by vnesita** [comment]
home igual que el primero, agrego porcentaje 
![home received](https://cloud.githubusercontent.com/assets/6201065/10712674/ea82913e-7a7f-11e5-8991-6773566e2ac7.jpg)

**Comment by vnesita** [comment]
aqui esta la tercera versión del balance, tendríamos que discutir cuál es la que se entiende más, y ver cómo se pueden mejorar, en esta lo que veo es que cuando la diferencia de los montos sea muy grande esta gráfica se vería un poco rara

![home_balance 3](https://cloud.githubusercontent.com/assets/6201065/10712744/64595fa0-7a81-11e5-9ea7-a2d457061b5d.jpg)

![home_balance 3book](https://cloud.githubusercontent.com/assets/6201065/10712745/69905eb0-7a81-11e5-8a8b-8e7706879ce8.jpg)

**Comment by Luis-Fernando-Molina** [comment]
> home igual que el primero, agrego porcentaje 

Vamonos por este lado, con los dos colores.

Te explico un poquito mas cuando hay una diferencia entre el Available y el Booked Balance. Básicamente hay dos situaciones:

1 ) Cuando envias un pago, se te baja inmediatamente el balance disponible pero el book se mantiene hasta el momento en que el pago lo acepta la red bitcoin (pueden pasar hasta 10 minutos). Mientras eso sucede el Book es Mayor que el Available.

2) Cuando recibís un pago se te autmenta el balance Booked y el Available permanece igual hasta que la transacción la confirma la red bitcoin. (tambien puede tardar hasta 10 minutos). En este caso el Book tambien es mayor que el Available.

Por lo anterior se deduce que un grafico con dos colores se vería bien y se entendería bien. El Available debiera ser un color sólido y el Booked uno o bien trasparente o con un pattern que haga pensar de que es algo potencial pero no 100% real o disponible.

**Comment by vnesita** [comment]
ok, perfecto, entonces se entiende tal y como están? @Luis-Fernando-Molina @furszy 

CAMBIOS: más transparente el color del book y agregue porcentaje a los dos  

home available balance 
![home_b_av](https://cloud.githubusercontent.com/assets/6201065/10729918/cc73070a-7bd3-11e5-99c0-b96235eec9fa.jpg)

home book balance
![home_b_b](https://cloud.githubusercontent.com/assets/6201065/10729926/e277ac72-7bd3-11e5-93fc-b9be09ea3e1e.jpg)

**Comment by furszy** [comment]
Ok, el porcentaje lo voy a sacar para una primera instancia ya que es un control totalmente a parte, es un extra y va a consumir mucho tiempo el cual se puede aprovechar en otra cosa. Vamos a dejarlo para una próxima versión o cuando se esté más tranquilo en cuanto a los tiempos.
Lo dona la voy a empezar a desarrollar, que voy a demorar un toque, es una custom view nueva de cero que va a quedar en el android api.

**Comment by Luis-Fernando-Molina** [comment]
@furszy me parece bien lo que decis. Respecto al diseño exacto de la dona para este uso en particular pudieramos abrir un caso con @arnaldos de diseño 2d para que planteen varias opciones gráficas.

Tratemos de llegar un acuerdo respecto al contenido, voy a hacer una lista a continuación de que cosas yo estoy o no de acuerdo a esta altura:

Los puntos checkeados no necesitan mayor discusión: 
- [x]   1.  TITULO: Bitcoin Wallet
- [ ]   2.  ICONO DE PAGO: Estoy de acuerdo a que exista y que esté ahí, @arnaldos debiera proponer opciones en un Issue.
- [ ]   3.  DONA CON TRES COLORES: 
- [x]  a. De acuerdo a que exista y que este ahi, mas o menos de ese tamaño. 
- [ ]   b. @arnaldos y su equipo debe proponer opciones.
- [ ]   4. CENTRO DE DONA: 
- [x]  a. Estoy de acuerdo que ahí esté el balance, la moneda y el tipo de balance. 
- [ ]  b. Necesito un razonamiento o análisis mas profundo de que se va a mostrar exactamente ahí.

TIP: Si un usuario tiene siempre mucho menos de un bitcoin, no debieramos mostrarle el balance en mBTC (mili bitcoins)? Ademas deberiamos permitir switchearse entre las distintas unidades: BTC, mBTC, uBTC y satoshis. 
- [ ]  c. Yo propongo que un swipe up o down sobre el monto o moneda, cambie el tipo de moneda por otro (incluyendo el balance reformateado).
- [ ]  d. Realmente vamos a poner "touch to change"? Pensemos en alternativas.
- [ ]   5. TABS:  
- [x]  a. De acuerdo con que existan. 
- [ ]  b. No necesariamente a esa altura ni con ese estilo gráfico. 
- [x]  c. Si con que digan SENT y RECEIVED.
- [ ]   6. NOTIFICACION DE ELEMENTOS NUEVOS: 
- [x]  a. De acuerdo que existan, 
- [ ]  b. no necesariamente que se vean exactamente asi.
- [ ]   7. LISTA DE ENVIOS RECIBIDOS: 
- [x]  a. De acuerdo a que exista.
- [ ]  b. FOTO: De acuerdo, aunque no necesariamente redonda, ni de ese tamaño. 
- [x]  c.  NOMBRE Y APELLIDO: De acuerdo.
- [x]  d.  CANTIDAD Y TIPO DE MONEDA: De acuerdo. El tipo de Moneda debe mostrar la ultima seleccion que el usuario haya realizado respecto al tipo de moneda. Ej si su balance lo quiere ver en mBTC, ahi debe mostrar la lista en mBTC.
- [x]  e.  FECHA: De acuerdo en que exista y la posición. El texto debe ser el resultado de una función por proximidad a la actualidad. Ej:

Hace 3 minutos.
Hace 1 hora.
A las 8:30 AM
Ayer
Miércoles 12 de Octubre.
23/01/2014
- [x]  e. MEMO: Ok.
- [x]  f. CANTIDAD DE RECORDS: Ok.
- [ ]   8. FORMATO DEL REGISTRO DE LA LISTA: @arnaldos me gustaría ver opciones.

**Comment by Neoperol** [comment]
@furszy 

```
Graphic
    Background: #06356f

    Circulo
        Width: 3 dp
        Background: #022346

        Text “Number”: Roboto Bold #ffffff
        Text “BTC”: Roboto Regular #05ddd2
        Text “Available Balance”:  Roboto Light #05ddd2
        Text “touch to change”:  Roboto Light #aeb6c6

        Percentage
            Background 30 x 30 DP
            Text “Number with %” :  #05ddd2
```

**Comment by furszy** [comment]
Issue completed.
