### ISSUE TITLE
Crypto Customer Wallet Design / Home Negotiation Tab view Design

### ISSUE THREAD

**Issue by Neoperol** [bitDubai/fermat-graphic-design#219]
#218

Propuesta para la vista principal de la Crypto Customer Wallet, en la cual el usuario puede ver la listas de sus negociaciones activas. Los Market references dependiendo a la mercancía que quiere intercambiar y un botón principal para comenzar una negociación con los brokers que se encuentre en su lista de Contactos previamente seleccionados en la Community APP y filtrados por el tipo de mercancía. 

![view_home](https://cloud.githubusercontent.com/assets/6201081/10712913/289f1004-7a72-11e5-8997-7d3e8288f886.jpg)

**Comment by nelsonalfo** [comment]
@Luis-Fernando-Molina

**Comment by nelsonalfo** [comment]
@jorgeejgonzalez

**Comment by Luis-Fernando-Molina** [comment]
Me encanto el degrade de colores @Neoperol !

> Propuesta para la vista principal de la Crypto Customer Wallet, en la cual el usuario puede ver la listas de sus negociaciones activas. 

Hasta acá vamos bien.

> Los Market references dependiendo a la mercancía que quiere intercambiar 

Ok esto se ve muy bien, solo yo pondria los dos precios del mismo color.

> y un botón principal para comenzar una negociación con los brokers que se encuentre en su lista de Contactos previamente seleccionados en la Community APP y filtrados por el tipo de mercancía.

No me parece un botón ahi. Mas bien para hacer esa acción debiera ir a su lista de contactos y de ahí iniciarla. Alguna razón especial para que el botón esté ahi?

Detalles cosméticos:
1. El indicador de tab selecionado ponelo por favor del violeta claro.
2. Negotiations y Contracts yo los pondria del mismo color, dejando que el indicador de 1 sugiera cual está seleccionado. Al haber solo dos tabs no queda bien que ambos tengan colores diferentes.
3. La barra de wainting for you y waitng for the broker las pondria del mismo color tambien, sin la flecha hacia abajo porque pareciera un boton para colapsar esos records (lo es?) .El color tiene que tener relacion con los violetas de arriba, o ser los dos grises como la primera barra.

@Neoperol TIP:  Cuando redactes el caso, poné las cosas punto por punto así se puede decir con facilidad en que se está de acuerdo y en que no.

**Comment by Luis-Fernando-Molina** [comment]
Otra cosa que te falta en tu análisis es como funcionarian ciertas cosas en la pantalla, por ejemplo como se cambia de un par BTC/USD a uno BTC/BOL y cualquier otra cosa que se pueda hacer.

**Comment by Neoperol** [comment]
Ok, respondiendo a tus dudas. 

> Ok esto se ve muy bien, solo yo pondria los dos precios del mismo color.
> Ese misma sugerencia me la hizo ayer Jorge en una reunio previa que tuvimos, además se agrego el título de Market Exchange Rate. 
> 
> No me parece un botón ahi. Mas bien para hacer esa acción debiera ir a su lista de contactos y de ahí iniciarla. Alguna razón especial para que el botón esté ahi?

La razón principal por la cual el boton "Start Negotiation" esta en esta vista es porque es la acción principal que se realiza en la aplicación y por consiguiente se debe poder hacer en la pantalla principal de la APP, La Lista de contactos existe, como se ve representada en el Wireframe, este botón es solo un acceso rápido a esa lista, para seleccionar al Broker con quien quieres comenzar una Negociación. 

> El indicador de tab selecionado ponelo por favor del violeta claro.

Muestra con el violeta, yo creo que con el valor Blanco se destaca mas el Tab Seleccionado. 
Algo que falta es colocar el icono de alerta cuando una nueva negociación llega en una de las listas. 

![view_home_001](https://cloud.githubusercontent.com/assets/6201081/10761263/beac23da-7c92-11e5-99d8-9fbe595d6855.jpg)

Tab Active. 

![view_home_active](https://cloud.githubusercontent.com/assets/6201081/10761385/568b126a-7c93-11e5-82cd-7210e066ab56.jpg)

> Negotiations y Contracts yo los pondria del mismo color, dejando que el indicador de 1 sugiera cual está seleccionado. Al haber solo dos tabs no queda bien que ambos tengan colores diferentes.
> Realmente no tienen colores diferentes, solo que uno tiene una opacidad para determinar cual es el que esta seleccionado en ese momento. 
> 
> La barra de wainting for you y waitng for the broker las pondria del mismo color tambien, sin la flecha hacia abajo porque pareciera un boton para colapsar esos records (lo es?) .El color tiene que tener relacion con los violetas de arriba, o ser los dos grises como la primera barra.

Si las flechas son para indicacar si esa lista esta acoplada o no, y los dos colores diferentes es para que se puedan diferenciar los dos botones cuando la lista de arriba este oculta. El color gris que tiene el Waiting for you es debido al color Violeta del Tab Bar. 

![view_home_acoplado](https://cloud.githubusercontent.com/assets/6201081/10761235/a04c1558-7c92-11e5-9e34-598ad720da0b.jpg)

![view_home](https://cloud.githubusercontent.com/assets/6201081/10760910/0577e9fe-7c91-11e5-934d-771fea7a18f3.jpg)

**Comment by Luis-Fernando-Molina** [comment]
ok, por mi dale asi :+1:

**Comment by nelsonalfo** [comment]
por mi también el diseño esta bien, están todos los elementos discutidos

**Comment by nelsonalfo** [comment]
Le doy el :+1: 
Considero que este Issue se puede cerrar @Luis-Fernando-Molina

**Comment by nelsonalfo** [comment]
Ahora falta crear el enlace de los colores, las fuentes y los tamaños para los elementos de esta pantalla como hiciste en el Issue #264

**Comment by Neoperol** [comment]
@nelsonalfo 
Aquí, esta el enlace
https://docs.google.com/document/d/1KfzNMo4Kv3B40EjDUO3oy6gbj5OghNt06nNS8sbJBFo/edit

**Comment by nelsonalfo** [comment]
@Neoperol necesito que me indiques los estilos del header Market Exchange Rate
