### ISSUE TITLE
Crear las distintas acepciones del isologo BitDubai

### ISSUE THREAD

**Issue by m471c4** [bitDubai/fermat-graphic-design#22]
Viene del #14

Una vez completado el issue #16 será necesario crear las acepciones en positivo, negativo y outline del isologo BitDubai para tener una imagen más versátil.

**Comment by arnaldos** [comment]
Coincido contigo @m471c4 me parece que eso se puede manejar dentro del manual de marca de bitDubai y que este incluya : 

-Logo 
-Paleta de colores
-Aplicaciones permitidas y las no permitidas:
     *Logo en positivo               *Fondo de color
     *Logo en negativo              *Intercambiar los colores del logo
     *Logo en outline                 *Sobreponer letra arabe por encima de bitDubai

-Fuentes aplicadas
-Mínima reducción que soporta el logo
-Área de reserva

Creo que tu coincides en lo mismo,  

Que otras cosas se le puedan incluir dentro del manual de marca?.

**Comment by m471c4** [comment]
Versión a color:
![bitdcolor](https://cloud.githubusercontent.com/assets/13468350/9322935/46c46966-4544-11e5-86ca-6951f8578b73.png)

Versión en positivo:
![bitdpos](https://cloud.githubusercontent.com/assets/13468350/9322937/46cb2ea4-4544-11e5-84a2-20a765ce97a1.png)

Versión en negativo:
![bitdneg](https://cloud.githubusercontent.com/assets/13468350/9322936/46ca50ec-4544-11e5-86e1-cfcf1c789be4.png)

Outline:
![bitdout](https://cloud.githubusercontent.com/assets/13468350/9322938/46cca4b4-4544-11e5-9db1-23aeeec93777.png)

**Comment by Luis-Fernando-Molina** [comment]
Antes de cerrar este caso me gustaría ver si no cambia el tamaño de la palabra en árabe de acuerdo al lago cuadrado.

**Comment by m471c4** [comment]
Versiones finales con la palabra árabe escalada de acuerdo al isologo cuadrado (aumentó un poco su tamaño).

![bitdcolor](https://cloud.githubusercontent.com/assets/13468350/9391066/a68b0fb6-473e-11e5-9ae1-447352128738.png)
![bitdpos](https://cloud.githubusercontent.com/assets/13468350/9391067/a6affcc2-473e-11e5-9e12-ff461dbde130.png)
![bitdneg](https://cloud.githubusercontent.com/assets/13468350/9391075/acedd55a-473e-11e5-8ea1-7a15303675be.png)
![bitdout](https://cloud.githubusercontent.com/assets/13468350/9391076/ad0b53be-473e-11e5-95c0-45ad25cc5370.png)

**Comment by Luis-Fernando-Molina** [comment]
Ok, damos por terminado este issue, pero continua sus ramificaciones en https://github.com/bitDubai/fermat-graphic-design/issues/77
