### ISSUE TITLE
Crear icono para la SubApp Asset Factory

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#221]
Viene del #220

**Asset Factory** se refiere a una fabrica de Asset. 

Los Asset Se usa como un concepto genérico.Son activos digitales, que pueden ser representados de diferentes maneras, Ejemplo:  Baucher, cupones, acciones de empresas, servicios, elementos de marketing o productos, entre otros. que puede ser intercambiable. 

**Requisitos**

Archivo PNG de 32 bits (alpha)
Tamaño: 512 x 512 píxeles
Tamaño máximo del archivo: 1024 KB

Una vez elegido el icono, es necesario generar los tamaños, en **.PNG** para aplicarlos en lo siguientes:

**IC launcher**:

48 × 48 px (mdpi)
72 × 72 px (hdpi)
96 × 96 px (xhdpi)
144 × 144 px (xxhdpi)
192 × 192 px (xxxhdpi)
512 × 512 px (Wallet store)

**Comment by victoralfonzohd** [comment]
@Luis-Fernando-Molina  @arnaldos Esta propuesta de icono se basa en mostrar o desplegar 3 Rectangulos, estos representan los activos digitales (Bauches, cupones, etc..) ya que es la forma mas comun entre ellos.
#221

Propuesta

![icono_assetfactoryp1-01](https://cloud.githubusercontent.com/assets/15219855/10801992/427bbc08-7d8c-11e5-8dc5-01d28f193dec.png)

**Comment by Luis-Fernando-Molina** [comment]
@victoralfonzohd me gustaría que en la medida de lo posible el icono sea tan explícito que uno reconozca que es una "Asset Factory". De ultima si no se llega a reconocer, entre una coleccion de iconos al menos uno pudiera deducir que ese es el de una "Asset Factory".

**Comment by victoralfonzohd** [comment]
@Luis-Fernando-Molina Me pediste que el icono sea explicito, por eso pense en unas tarjetas debito/credito estas representan consumo de activos diarios y es algo bastante reconocible, la forma circular la asocie con un boton de accion de un pago aprovado, por estas mismas caracteristicas use un color verde 

Propuesta 2

![assetfactory_p2-01](https://cloud.githubusercontent.com/assets/15219855/10804177/649270fa-7d98-11e5-93e7-b7012652cb2f.png)

**Comment by Luis-Fernando-Molina** [comment]
En general nosotro reprsentamos digital assets con figuras geometricas simples como circulo, cuadrado y triangulo. Luego una fabrica me imagino que encontraras como representarla.

**Comment by arnaldos** [comment]
otra cosa que se debe tener en cuenta es que **La asset factory** permite crear y publicar los assets

**Comment by victoralfonzohd** [comment]
@Luis-Fernando-Molina  @arnaldos Esta propuesta, la asset Factory se presenta como tal, una fabrica que genera los assets 

![icono_asset_factory_concepto2](https://cloud.githubusercontent.com/assets/15219855/10833750/80f59d7a-7e66-11e5-837d-09a089edb2c8.png)

**Comment by Luis-Fernando-Molina** [comment]
la idea va bien, pero no el formato ortogonal.

La fabrica : si
La linea de produccio : si
Que salgan los assets cono una figura geometrica : si

**Comment by MelissaDugarte** [comment]
@arnaldos y @Luis-Fernando-Molina  
Adjunto propuestas  icono para la SubApp Asset Factory

![icono subapp asset factory_issue_1](https://cloud.githubusercontent.com/assets/15186093/10847866/2ece2aaa-7eeb-11e5-885e-348d8f5fddba.jpg)
![icono subapp asset factory_issue_2](https://cloud.githubusercontent.com/assets/15186093/10847867/2ecfea84-7eeb-11e5-87ea-a84fcdc9c9e3.jpg)

**Comment by victoralfonzohd** [comment]
@Luis-Fernando-Molina @arnaldos Propuesta en vista frontal y lateral 

![icono_asset_factory_p2](https://cloud.githubusercontent.com/assets/15219855/10849203/c595413e-7ef1-11e5-9296-db706785caf5.png)

**Comment by Luis-Fernando-Molina** [comment]
sigue abierto este issue para participar... 
- recuerden que es un icono, porque no lo hacen directamente en el tamaño de un icono a ver si se ve bien ahi?

**Comment by victoralfonzohd** [comment]
@Luis-Fernando-Molina Disculpe, 512 x 512 pix.

Vista Frontal

![icono_asset_factory_p1](https://cloud.githubusercontent.com/assets/15219855/10850182/70e8929e-7ef6-11e5-9ae7-a87a0608807e.png)

Vista Lateral 

![icono_asset_factory_p2](https://cloud.githubusercontent.com/assets/15219855/10850219/9ddfa10c-7ef6-11e5-85d7-86f25c7768b1.png)

**Comment by arnaldos** [comment]
Hay que tomar en cuenta que estamos trabajando con iconos.  Que van a
identificar la aplicación.  Por lo que es importante tener en cuenta la
cantidad de elementos, ya que en sus máxima reducción varios de estos
elemento se perderán, los iconos se trabajan partiendo de un formato
cuadrado este debe verse aplicado así sea por cerramiento,  ya que los
formatos rectangulares al momento de aplicarlos sobre el desktop no
funcionará.

**Comment by victoralfonzohd** [comment]
@arnaldos Claro, entiendo completamente.. A partir de lo que me comentaste realice una síntesis de todo el concepto, adjunto la propuesta @Luis-Fernando-Molina 

Propuesta

![asset-factory-p3](https://cloud.githubusercontent.com/assets/15219855/10851711/cd8a6178-7efe-11e5-909f-6127b84be9a8.png)

**Comment by victoralfonzohd** [comment]
@Luis-Fernando-Molina @arnaldos Un cambio en la propuesta,  ya no esta el brillo del icono.. En su lugar agregue una sombra sutil a la imagen que contiene el icono.. Dejandolo un poco mas plano pero mas limpio 

![icono_asset_factory_p4-01](https://cloud.githubusercontent.com/assets/15219855/10853745/e25687e8-7f09-11e5-8365-0e126dfb15e6.png)

**Comment by MelissaDugarte** [comment]
Ok @arnaldos entendido

**Comment by MelissaDugarte** [comment]
@arnaldos y @Luis-Fernando-Molina 
Versión  3 subapp asset factory
![icono subapp asset factory_issue_1](https://cloud.githubusercontent.com/assets/15186093/10860131/b132dfc2-7f36-11e5-97fa-bd67724d0f95.jpg)

Versión 4 subapp asset factory
![icono subapp asset factory_issue_2](https://cloud.githubusercontent.com/assets/15186093/10860139/cc649e70-7f36-11e5-83ca-d1cd24774f07.jpg)

**Comment by Luis-Fernando-Molina** [comment]
Los diseños de iconos solo los reviso en su tamaño target desde ahora, para evitar aprobar cosas que muy chiquitas no se verian. Preguntale a @arnaldos cual es el target y como mostrarlos. Gracias

@MelissaDugarte los assets no son crypto currency como bitcoin. Aunque la version 4 tiene onda :smile: prefiero que de ver el icono la gente deduzca que se trata de La APP asset factory.

**Comment by ivonnesantos** [comment]
![asset factory 221-01](https://cloud.githubusercontent.com/assets/15238660/10865424/c476cd5e-7fdc-11e5-9ba4-90975f32902a.jpg)

@Luis-Fernando-Molina @arnaldos

**Comment by MelissaDugarte** [comment]
@arnaldos y @Luis-Fernando-Molina 
Aporte según lo sugerido de  La APP asset factory.
Icono solo 
![icono subapp asset factory_issue_4](https://cloud.githubusercontent.com/assets/15186093/10886941/a10eac94-8156-11e5-986e-3d202f7b1fa0.jpg)

Versión 4
![desktop 4](https://cloud.githubusercontent.com/assets/15186093/10886945/a60123e4-8156-11e5-8036-a4e48a0ffe00.jpg)

Icono solo
![icono subapp asset factory_issue_2](https://cloud.githubusercontent.com/assets/15186093/10886681/74932830-8155-11e5-9782-1ef630d415a7.jpg)

Version 5
![desktop 2](https://cloud.githubusercontent.com/assets/15186093/10886694/8254b182-8155-11e5-941c-46156ee5b3ee.jpg)

**Comment by Luis-Fernando-Molina** [comment]
@MelissaDugarte puesto en el celular no se entiende
@ivonnesantos   solo reviso cuando estan en el celu version chiquita, gracias

**Comment by Luis-Fernando-Molina** [comment]
@victoralfonzohd solo se revisan los iconos en version final en el celular , gracias

**Comment by MelissaDugarte** [comment]
@arnaldos y @Luis-Fernando-Molina 

Adjunto propuesta La APP asset factory.
Icono
![icono subapp asset factory_issue_2](https://cloud.githubusercontent.com/assets/15186093/10896091/f1568770-8189-11e5-9699-d2a14ebab42d.jpg)

Version 4 (con ajustes)
![desktop 2](https://cloud.githubusercontent.com/assets/15186093/10896177/681a120a-818a-11e5-9611-a3c60558145f.jpg)

**Comment by Luis-Fernando-Molina** [comment]
Mas opciones please.

**Comment by ivonnesantos** [comment]
![asset factory 221-01](https://cloud.githubusercontent.com/assets/15238660/10899896/857f5ea6-81ab-11e5-9cfb-1500e8e984b6.png)

@Luis-Fernando-Molina @arnaldos

**Comment by Neoperol** [comment]
Saludos. 
Cuando los hagan usen el Product Icon Grid. 

https://www.google.com/design/spec/style/icons.html#

Asi saben de que ancho deben hacer las lineas para que no se pierdan detalles cuando los cambien de tamaño. 

https://www.google.com/design/spec/resources/sticker-sheets-icons.html#sticker-sheets-icons-components

En esta pagina se llama System icon sticker sheet el archivo que pueden bajar como guía.

En esa guia son un poco extremos en cuanto a lo sencillo que se debe hacer el Launcher Icon, en parte porque a partir de ese logo se debe hacer un Push Notification Icon. Pero creo que en nuestro caso no lo vamos a usar.

**Comment by victoralfonzohd** [comment]
@Luis-Fernando-Molina 

Popuesta:

![asset factory 1](https://cloud.githubusercontent.com/assets/15219855/10901158/222155b0-81bc-11e5-8e8d-f56bfc31cd54.png)

Tamaño Icono:

![asset factory target](https://cloud.githubusercontent.com/assets/15219855/10901166/36d894fa-81bc-11e5-8d11-7655a0ed9113.png)

En dispositivos Moviles:

![asset-factory-2](https://cloud.githubusercontent.com/assets/15219855/10901167/410b8112-81bc-11e5-9a86-8567903f2a3b.png)

**Comment by MelissaDugarte** [comment]
@Luis-Fernando-Molina 

Icono 6 
![icono subapp asset factory_issue_6](https://cloud.githubusercontent.com/assets/15186093/10910033/2f048bc8-820f-11e5-9144-e0bf5128ff6f.jpg)

Version 6
![desktop 6](https://cloud.githubusercontent.com/assets/15186093/10909993/df0934a2-820e-11e5-974f-57b8c31b1c1b.jpg)

**Comment by Luis-Fernando-Molina** [comment]
Mas opciones please. 

@Neoperol muy bien tu aporte :+1:

**Comment by victoralfonzohd** [comment]
@Luis-Fernando-Molina 

Propuesta:

![sin-titulo-1](https://cloud.githubusercontent.com/assets/15219855/10924412/a48cca9c-8258-11e5-8a19-2d6ce9d9c49a.png)

Icono:

![sin-titulo-2](https://cloud.githubusercontent.com/assets/15219855/10924476/1e1ccf2e-8259-11e5-84d8-71e54deeeddb.png)

Dispositivo Movil:

![a60123e4-8156-11e5-8036-a4e48a0ffe00](https://cloud.githubusercontent.com/assets/15219855/10924446/e324c84a-8258-11e5-9b0d-a308bc6e6377.png)

**Comment by ivonnesantos** [comment]
el la propuesta 2 y 3 represente una fabrica de la manera mas simple posible y le coloque la moneda de bitcoins en un verde que representa la actividad.

![asset factory 221-01](https://cloud.githubusercontent.com/assets/15238660/11015288/c1ebf49e-852a-11e5-9ea9-c9567315222c.jpg)

@arnaldos @Luis-Fernando-Molina

**Comment by ivonnesantos** [comment]
En estas dos propuestas me enfoque representar el proceso de contruccion o de cambio en la 4 hice como una especie de impresora arriba esta el papel en blanco y luego aparece el papel en verde como de activacion de dinero en la 5 es como un proceso de elaboracion por eso los engranajes

![asset factory 221-01](https://cloud.githubusercontent.com/assets/15238660/11073558/4918c99e-87bd-11e5-808a-6a160cfe42ab.png)

@arnaldos @Luis-Fernando-Molina

**Comment by arnaldos** [comment]
Recuerden que debemos representar una Fabrica de Asset la sub-aplicacion **Asset Factory** permite crear y publicar los assets

Debemos darle prioridad a este caso.

@bitDubai/2d-graphic-design-team

**Comment by victoralfonzohd** [comment]
@Luis-Fernando-Molina @arnaldos 

Propuesta:

![asset-factory](https://cloud.githubusercontent.com/assets/15219855/11200627/df50ec52-8ca9-11e5-92e3-0bfbbec01224.jpg)

Icono:

![asset-factory-1](https://cloud.githubusercontent.com/assets/15219855/11200631/e7a346b6-8ca9-11e5-93ae-977ad78718d2.png)

**Comment by arnaldos** [comment]
@victoralfonzohd  podrías incluir algún elemento que represente los asset

**Comment by victoralfonzohd** [comment]
@arnaldos Los represente como elementos circulares que parten de la misma estructura de la entrada de la fabrica 

Versión 1

![asset-factory-v1](https://cloud.githubusercontent.com/assets/15219855/11201476/cc6b1c3c-8cb0-11e5-909c-a624be8c03c2.png)

Versión 2

![asset-factory-v2](https://cloud.githubusercontent.com/assets/15219855/11201481/d7f3a7ea-8cb0-11e5-900c-501f1e601813.png)

Versión 3

![asset-factory-v3](https://cloud.githubusercontent.com/assets/15219855/11201487/e1c19ee4-8cb0-11e5-9afc-93763ffcbd8a.png)

Iconos:

![asset factory versiones](https://cloud.githubusercontent.com/assets/15219855/11201510/0893812c-8cb1-11e5-9a86-ef0dff7006a8.png)

**Comment by jurene22** [comment]
@victoralfonzohd que buen aporte, solo que con ese color tan oscuro no se aprecian cada uno de los elementos.. quizas con colores claros te funcione bastante bien.. la versión 1 es la mejor! "Opinion personal" ;)

**Comment by victoralfonzohd** [comment]
@jurene22 Gracias, se te ocurren algunos posibles colores? Para probar con ellos

**Comment by arnaldos** [comment]
@victoralfonzohd  revisando los iconos me gustan tus propuestas, pero los elementos que dices que forman los asset, se aprecia como si fuese una entrada a la fabrica y no como elementos que puedan representar los asset, entiendo lo colocas para que sea un ciono solido y no esten los elementos dispersos pero vamos a intentar representarlos de alguna manera los asset manteniendo el concepto que planteas.

**Comment by emmysm** [comment]
![asset factory](https://cloud.githubusercontent.com/assets/15143489/11221041/38e49652-8d35-11e5-9e6d-20b647892c95.png)

@arnaldos  @Luis-Fernando-Molina

**Comment by emmysm** [comment]
Para este icono realicé la sintesis de una factory y representé los asset con figuras geometricas

![asset factory](https://cloud.githubusercontent.com/assets/15143489/11221253/541c0a3a-8d36-11e5-9c5a-fee75ebbb374.png)
  @arnaldos

**Comment by emmysm** [comment]
![asset factory](https://cloud.githubusercontent.com/assets/15143489/11221466/86be657c-8d37-11e5-9040-8d4c1037fa21.png)

**Comment by arnaldos** [comment]
@emmysm  estandariza los angulos de las chimenas de la fabrica, usa la paleta del primer icono, nose si la propuesta del sobre sea la correcta plantea otra propuesta plz

**Comment by emmysm** [comment]
Vale, ya genero los ajustes, @arnaldos

**Comment by victoralfonzohd** [comment]
@arnaldos Agregue una flecha con bastante movimiento al rededor del circulo central, el color de la misma da un contraste atractivo y a la vez enfoca el elemento circular que seria el Asset.. La flecha también representa la salida rápida de los assets y su publicación.

![asset-factory](https://cloud.githubusercontent.com/assets/15219855/11229060/ff186294-8d63-11e5-9835-0e94f1d1b981.png)

Icono:

![asset-factory](https://cloud.githubusercontent.com/assets/15219855/11229106/6a4648d8-8d64-11e5-84bc-c8d0e95a3506.png)

**Comment by arnaldos** [comment]
se aprobo este icono actualmente esta en uso 
![icono-wallet-factory9](https://cloud.githubusercontent.com/assets/13594347/12346272/1c2a8148-bb25-11e5-81f8-7a528e82108e.jpg)
