### ISSUE TITLE
Crear icono para la SubApp Asset issuer community

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#222]
Viene del #220

La subaplicación **Community** permite que los actores, a través de sus identidades, interactúen entre ellos. Existe una por cada tipo de actor.

Un actor es una persona o figura que realiza algún tipo de acción dentro de la plataforma Fermat.

**Issuer** son una entidad juridica (corporaciones, sociedad de inversión, empresas) autorizados para generar oferta  de sus propios valores. 

Los tipos más comunes de los valores emitidos son, acciones, bonos, pagarés  y derivados.

Los **Asset** Se usa como un concepto genérico.Son activos digitales, que pueden ser representados de diferentes maneras, Ejemplo: Baucher, cupones, acciones de empresas, servicios, elementos de marketing o productos, entre otros. que puede ser intercambiable.

**Asset issuer community**: Es la aplicación que permite el intercambio de asset entre entidades.

**Requisitos**

Archivo PNG de 32 bits (alpha)
Tamaño: 512 x 512 píxeles
Tamaño máximo del archivo: 1024 KB

Una vez elegido el icono, es necesario generar los tamaños, en **.PNG** para aplicarlos en lo siguientes:

**IC launcher**:

48 × 48 px (mdpi)
72 × 72 px (hdpi)
96 × 96 px (xhdpi)
144 × 144 px (xxhdpi)
192 × 192 px (xxxhdpi)
512 × 512 px (Wallet store)

**Comment by victoralfonzohd** [comment]
@Luis-Fernando-Molina  @arnaldos  Esta propuesta parte del mismo concepto del icono para Asset Factory  #221.

A cada rectangulo se le agrego la silueta de un usuario, para representar a las entidades 
#222

Propuesta 

![icono_assetissuercomunityp1-01](https://cloud.githubusercontent.com/assets/15219855/10801949/1933e99c-7d8c-11e5-8a92-12ad138c5542.png)

**Comment by Luis-Fernando-Molina** [comment]
Hola @victoralfonzohd un gusto verte por acá.

Por favor proba hacer un Drag & Drop de la imagen al box donde escribis el comentario, asi se ve directamente la imagen aquí sin tener que tocar en el link.

**Comment by victoralfonzohd** [comment]
@Luis-Fernando-Molina Esta propuesta parte del mismo concepto del icono para Asset Factory #221.

Propuesta 2

![assetcomunity_p2-01](https://cloud.githubusercontent.com/assets/15219855/10804604/870c1b16-7d9a-11e5-8beb-6339207d9556.png)

**Comment by ivonnesantos** [comment]
![asset_community_222-01-01](https://cloud.githubusercontent.com/assets/15238660/10848525/7b90d2a4-7eee-11e5-8964-eaf0ce7ba2b6.png)
@arnaldos  @Luis-Fernando-Molina

**Comment by Luis-Fernando-Molina** [comment]
@arnaldos   Por favor, desde ahora, todos los casos que son iconos proponganlos directamente en el tamaño de un icono. Gracias.

**Comment by victoralfonzohd** [comment]
@Luis-Fernando-Molina  

![assetcomunity_p3-01](https://cloud.githubusercontent.com/assets/15219855/10854036/7d4e02a2-7f0b-11e5-95ae-97171a28b278.png)

**Comment by ivonnesantos** [comment]
![asset_community_222-01-01-01](https://cloud.githubusercontent.com/assets/15238660/10855443/ba5c9958-7f13-11e5-9186-656463c58803.png)
@Luis-Fernando-Molina

**Comment by Luis-Fernando-Molina** [comment]
Hola, por falta de tiempo, solo reviso en la version final, tamaño icono puesto en el celular, gracias

**Comment by jurene22** [comment]
@Luis-Fernando-Molina aporte para issue 222
![icon_subapp_asset_issuer_community_issue222](https://cloud.githubusercontent.com/assets/15174317/10940850/bdc39338-82da-11e5-9a92-8c7cc44990d5.png)
![vista target](https://cloud.githubusercontent.com/assets/15174317/10940852/c14ebdfc-82da-11e5-99c9-7c0a3cc96ac2.png)

**Comment by Luis-Fernando-Molina** [comment]
More options please.

**Comment by jurene22** [comment]
![icon_subapp_asset_issuer_community_issue222_version 2 peq](https://cloud.githubusercontent.com/assets/15174317/10978816/18d2c2e4-83cb-11e5-8c3c-672ca8bede54.png)
![vista target](https://cloud.githubusercontent.com/assets/15174317/10978831/30daf1f4-83cb-11e5-8e32-6b7d8cc1d1e7.png)
@Luis-Fernando-Molina Nuevo aporte
Version 2

**Comment by victoralfonzohd** [comment]
@Luis-Fernando-Molina @arnaldos 

Propuesta:

![asset](https://cloud.githubusercontent.com/assets/15219855/11259986/eb023458-8e38-11e5-9b01-c4c6b2aa7d6a.jpg)

Icono:

![asset issuer community](https://cloud.githubusercontent.com/assets/15219855/11260029/69a70ad6-8e39-11e5-9421-24e4fc3cf753.png)

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina  te parece este provicional ?

![icon-asset-issuer-comunity](https://cloud.githubusercontent.com/assets/13594347/11547920/dac15b90-9929-11e5-9c26-bc17370af266.png)

**Comment by Luis-Fernando-Molina** [comment]
si provisional

**Comment by ivonnesantos** [comment]
![asset_issuer_community_iiv-01](https://cloud.githubusercontent.com/assets/15238660/11841199/d582af90-a3cd-11e5-8a78-0954c0547f9d.png)

@arnaldos @Luis-Fernando-Molina
