### ISSUE TITLE
Crear icono para la SubApp Reddem point community

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#223]
Viene del #220

La subaplicación **Community** permite que los actores, a través de sus identidades, interactúen entre ellos. Existe una por cada tipo de actor.

Un actor es una persona o figura que realiza algún tipo de acción dentro de la plataforma Fermat.

Los **Asset** Se usa como un concepto genérico.Son activos digitales, que pueden ser representados de diferentes maneras, Ejemplo: Baucher, cupones, acciones de empresas, servicios, elementos de marketing o productos, entre otros. que puede ser intercambiable.

**Reddem point community**: es la aplicación que permite el canje de **Asset** sobre una entidad. (es el punto de intercambio de **Asset**). 

**Requisitos**

Archivo PNG de 32 bits (alpha)
Tamaño: 512 x 512 píxeles
Tamaño máximo del archivo: 1024 KB

Una vez elegido el icono, es necesario generar los tamaños, en **.PNG** para aplicarlos en lo siguientes:

**IC launcher**:

48 × 48 px (mdpi)
72 × 72 px (hdpi)
96 × 96 px (xhdpi)
144 × 144 px (xxhdpi)
192 × 192 px (xxxhdpi)
512 × 512 px (Wallet store)

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina te comparto las propuestas para la Reddem point community

versión 1

![reddem-point-community-version-1](https://cloud.githubusercontent.com/assets/13594347/10779594/3f62962c-7d05-11e5-8e17-ceffee8e7a67.png)

versión 2

![reddem-point-community-version-2](https://cloud.githubusercontent.com/assets/13594347/10779596/49479f8e-7d05-11e5-8c65-02fda1a883d1.png)

versión 3

![reddem-point-community-version-3](https://cloud.githubusercontent.com/assets/13594347/10779600/51ddd0d2-7d05-11e5-98b9-a048c873b61b.png)

**Comment by Luis-Fernando-Molina** [comment]
Un Reedem point en un sitio donde vos entregas con tu celula un digital asset y te dan un bien fisico. Fijate si podes graficar eso en el icono.

**Comment by arnaldos** [comment]
ok perfecto !!!

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina Te comparto nuevas versiones 

versión 4
![reddem-point-community-4](https://cloud.githubusercontent.com/assets/13594347/10832489/f200fbbc-7e5d-11e5-9ab7-67a2082a3456.png)

versión 5
![reddem-point-community-5](https://cloud.githubusercontent.com/assets/13594347/10832490/f2076a38-7e5d-11e5-93a2-a81582a24065.png)

versión 6
![reddem-point-community-6](https://cloud.githubusercontent.com/assets/13594347/10832491/f20c16c8-7e5d-11e5-838e-99d1adccad52.png)

versión 7
![reddem-point-community-7](https://cloud.githubusercontent.com/assets/13594347/10832492/f2138a7a-7e5d-11e5-9dd5-0325889c2a33.png)

**Comment by Luis-Fernando-Molina** [comment]
Sigamos a partir de la 5

**Comment by arnaldos** [comment]
vale perfecto !!

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina que te parece esta versión? me enfoque en la versión 5 pero buscando que los elementos estén mas integrados. 

versión 8
![reddem-point-community-8](https://cloud.githubusercontent.com/assets/13594347/10861919/8c7246c6-7f65-11e5-838b-851e07161ffc.png)

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina el sreenshot

![reddem-point-community-8-sreenshot](https://cloud.githubusercontent.com/assets/13594347/10916597/599f66b8-822e-11e5-9184-bb756792c139.png)

**Comment by Luis-Fernando-Molina** [comment]
prefiero la 5 con un poco de naranja

**Comment by arnaldos** [comment]
vale perfecto !!

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina  Ajustes del icono de la Reddem Point

![reddem-point-community-9-1](https://cloud.githubusercontent.com/assets/13594347/11224291/67d078b2-8d46-11e5-9a10-4794ed115e7a.png)

![reddem-point-community-9](https://cloud.githubusercontent.com/assets/13594347/11224292/67f44dbe-8d46-11e5-8e99-33b61036c8c2.png)

**Comment by ivonnesantos** [comment]
@arnaldos partiendo de tu idea cree estas propuestas
![issues 223 reddem point community-01](https://cloud.githubusercontent.com/assets/15238660/11245042/eb1af980-8de2-11e5-91f0-8f7b9d3d255a.png)

**Comment by ivonnesantos** [comment]
@arnaldos agrego 2 propuestas que se parecen mas al concepto que aprobaron
![issues 223 reddem point community-01](https://cloud.githubusercontent.com/assets/15238660/11245573/970bf292-8de5-11e5-80fa-c70ff7253746.png)

**Comment by arnaldos** [comment]
@ivonnesantos  la opción 4 :+1:
