### ISSUE TITLE
Crear icono para la SubApp Asset user comunity

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#224]
Viene del #220

La subaplicación **Community** permite que los actores, a través de sus identidades, interactúen entre ellos. Existe una por cada tipo de actor.

Un actor es una persona o figura que realiza algún tipo de acción dentro de la plataforma Fermat.

**User** Una persona que utiliza una computadora. Esto incluye expertos programadores, así como los principiantes. Un usuario final es cualquier persona que corre un aplicación del programa.

Los **Asset** Se usa como un concepto genérico.Son activos digitales, que pueden ser representados de diferentes maneras, Ejemplo: Baucher, cupones, acciones de empresas, servicios, elementos de marketing o productos, entre otros. que puede ser intercambiable.

**Asset user comunity**: Es la aplicación que permite el intercambio de asset entre usuarios.

**Requisitos**

Archivo PNG de 32 bits (alpha)
Tamaño: 512 x 512 píxeles
Tamaño máximo del archivo: 1024 KB

Una vez elegido el icono, es necesario generar los tamaños, en **.PNG** para aplicarlos en lo siguientes:

**IC launcher**:

48 × 48 px (mdpi)
72 × 72 px (hdpi)
96 × 96 px (xhdpi)
144 × 144 px (xxhdpi)
192 × 192 px (xxxhdpi)
512 × 512 px (Wallet store)

**Comment by arnaldos** [comment]
SubApp Asset user comunity

**Comment by jurene22** [comment]
aqui puedo dejar 2 versiones como aporte @arnaldos @Luis-Fernando-Molina 
![subapp asset user comunity 1-01](https://cloud.githubusercontent.com/assets/15174317/10791201/89ecf210-7d59-11e5-996b-ed1d12131ba4.jpg)
Versión 1
![subapp asset user comunity 1-02](https://cloud.githubusercontent.com/assets/15174317/10791209/929a4ef8-7d59-11e5-9a2d-f790104f790a.jpg)
Versión 2

**Comment by jurene22** [comment]
![icon_subapp_crypto_customer_community_issue174_version_1-03-01](https://cloud.githubusercontent.com/assets/15174317/10799733/8ba31d42-7d80-11e5-9bc0-4483f1e911c7.jpg)
version 3

**Comment by Luis-Fernando-Molina** [comment]
@jurene22 buscalo por el lado de : 

Community (conjunto de personas)
Digital Asset (lo representamos en otros iconos como figuras geometricas simples: cuadrado circulo , triangulo)

fijate si te sirve, adicional a eso recorda que el icono luego es pequeño y se tiene que entender cuando sea chiquito.

**Comment by jurene22** [comment]
Ok perfecto! trabajeré en base a eso.. gracias por la aclaratoria

**Comment by jurene22** [comment]
Versión 4
![icon_subapp_asset_user_comunity_issue224_version_4-01](https://cloud.githubusercontent.com/assets/15174317/10818793/5f00f264-7e16-11e5-96c3-1de80d6d633b.jpg)

**Comment by arnaldos** [comment]
me agrada el concepto, solo recuerda que los iconos tienen mínimo de reducción que pueden llegar hasta 24x24 px. y aquí veo elementos que en el momento de la reducción podrían perderse, referente a la representación de los assest, cuando se comenta que se ha representado por figuras geométricas no necesariamente tienen que ser herramientas de geometría, por lo que yo eliminaría la escuadra, si vas a jugar con las figuras geométricas has que sean mas notorias para que en el momento de reducción no se pierdan. para las versiones finales por favor cuida construcción de los vectores fíjate que los espacios entre ellos no todos tienen el mismo espesor.

**Comment by isahq23** [comment]
@arnaldos @Luis-Fernando-Molina 
Aporte para el icono de Asset User Community

Propuesta 1
![asset_user_community_icon_1-1](https://cloud.githubusercontent.com/assets/15214774/10823538/5455df4c-7e2e-11e5-8057-a65c87f2f701.png)

Propuesta 2
![asset_user_community_icon_1-2](https://cloud.githubusercontent.com/assets/15214774/10823547/5a058302-7e2e-11e5-92a2-ec5ab4b8df7b.png)

Propuesta 3
![asset_user_community_icon_1-3](https://cloud.githubusercontent.com/assets/15214774/10823557/5f54e6b8-7e2e-11e5-91f4-babc9bab7f50.png)

Propuesta 4
![asset_user_community_icon_1-4](https://cloud.githubusercontent.com/assets/15214774/10823567/65d40c76-7e2e-11e5-8969-04d002f193ad.png)

**Comment by jurene22** [comment]
modificacion de Versión 4
![icon_subapp_asset_user_comunity_issue224_version_4](https://cloud.githubusercontent.com/assets/15174317/10824913/bac15cf6-7e34-11e5-9fd6-c7c9c95260db.png)
@arnaldos @Luis-Fernando-Molina

**Comment by Luis-Fernando-Molina** [comment]
Continuemos por favor la idea de @jurene22 . Probemos con las figuras dentro del pentagono blanco del centro.. Veamos como queda mas chico (tamaño icono)

**Comment by emmysm** [comment]
![asset user community-2](https://cloud.githubusercontent.com/assets/15143489/10833280/e902e688-7e62-11e5-8541-7843f85ac9c1.png)

![asset user community 1](https://cloud.githubusercontent.com/assets/15143489/10833254/cb438062-7e62-11e5-8f7d-aa620838cafb.png)
@Luis-Fernando-Molina  aca te presento dos propuesta, a ver si te sirve :)

**Comment by Luis-Fernando-Molina** [comment]
@emmysm :

> Continuemos por favor la idea de @jurene22 . Probemos con las figuras dentro del pentagono blanco del centro.. Veamos como queda mas chico (tamaño icono)

sigamos a partir de esa idea.

**Comment by MelissaDugarte** [comment]
@arnaldos y @Luis-Fernando-Molina  Aporte para el icono de Asset User Community
![reddem point community_issue_1](https://cloud.githubusercontent.com/assets/15186093/10834533/4db1e602-7e6c-11e5-9a98-cac29c25c050.jpg)

**Comment by MelissaDugarte** [comment]
@arnaldos y @Luis-Fernando-Molina Aporte para el icono de Asset User Community 
Version 2

![reddem point community_issue_2](https://cloud.githubusercontent.com/assets/15186093/10834994/6b4b643c-7e70-11e5-9da9-1c85ecdf787e.jpg)

**Comment by jurene22** [comment]
![icon_subapp_asset_user_comunity_issue224_version_4](https://cloud.githubusercontent.com/assets/15174317/10835819/87c41e62-7e78-11e5-814a-1155458045eb.jpg)
@Luis-Fernando-Molina  @arnaldos 
Versión 4 modificado a tamaño 24x24 px

**Comment by jurene22** [comment]
![icon_subapp_asset_user_comunity_issue224_version_4_2](https://cloud.githubusercontent.com/assets/15174317/10835847/cb2b8dac-7e78-11e5-83eb-79475d7d78b0.jpg)
un poco mas grandes

**Comment by jurene22** [comment]
![icon_subapp_asset_user_comunity_issue224_version_4_modif_2pq](https://cloud.githubusercontent.com/assets/15174317/10835986/9657c56c-7e7a-11e5-99f5-eaaf187d0a86.png)
![icon_subapp_asset_user_comunity_issue224_version_4_modif_2](https://cloud.githubusercontent.com/assets/15174317/10835987/96a83c7c-7e7a-11e5-95f3-fa14fe6b2966.png)
modificacion 2 de la versión 4
@Luis-Fernando-Molina @arnaldos

**Comment by Luis-Fernando-Molina** [comment]
Vamos a ir con la version 1 de @MelissaDugarte sin las flechitas. @arnaldos explicale como hacias tu para mostrar la version entre otros iconos en un desktop de telefono. Asi la puede refinar si hay detalles que no se vean bien.

**Comment by arnaldos** [comment]
Vale perfecto Luis ya le explico

**Comment by MelissaDugarte** [comment]
@arnaldos  y @Luis-Fernando-Molina 

Icono solo
![reddem point community_issue_1](https://cloud.githubusercontent.com/assets/15186093/10886216/3eea8d4c-8153-11e5-849d-3001f7a2ce26.jpg)

Version 1 seleccionada Aplicada en el Desktop

![reddem point community_issue_1](https://cloud.githubusercontent.com/assets/15186093/10885259/996559b4-814e-11e5-81a6-61a2c6ffb055.jpg)

**Comment by Luis-Fernando-Molina** [comment]
@MelissaDugarte lo blanco ponelo transparente y que sea un poco mas grueso los brazos please

**Comment by MelissaDugarte** [comment]
@Luis-Fernando-Molina 

Adjunto lo solicitado
![nexus desktop](https://cloud.githubusercontent.com/assets/15186093/10895642/719a40aa-8187-11e5-8c26-7cf5dc211e6d.jpg)

**Comment by Luis-Fernando-Molina** [comment]
No le veo transparente, sino gris al fondo del icono.

Las figuras siguen muy fina. 

Pone una de cada color please

**Comment by MelissaDugarte** [comment]
@Luis-Fernando-Molina  y @arnaldos 
Icono 
![reddem point community_issue_1](https://cloud.githubusercontent.com/assets/15186093/10911472/2bac65ce-8217-11e5-844f-f8bef5a4dbf9.jpg)

Versión Aporte para el icono de Asset User Community
![nexus desktop](https://cloud.githubusercontent.com/assets/15186093/10911277/3fe22e3a-8216-11e5-8a00-683b0a5a8440.jpg)

**Comment by Luis-Fernando-Molina** [comment]
ok, va quedando, probemos otros colores, o combinaciones

**Comment by MelissaDugarte** [comment]
@Luis-Fernando-Molina 

Iconos 
version 4
![reddem point community_issue_2 version4](https://cloud.githubusercontent.com/assets/15186093/10920824/804e9110-8244-11e5-9117-96971e702bcb.jpg)
version 5
![reddem point community_issue_2](https://cloud.githubusercontent.com/assets/15186093/10920864/b09b130c-8244-11e5-8c0a-76451f203959.jpg)
version 6
![reddem point community_issue_2 version](https://cloud.githubusercontent.com/assets/15186093/10920868/b753a98e-8244-11e5-94bf-e67c86c9d40f.jpg)

Versión Aporte para el icono de Asset User Community
![nexus desktop-](https://cloud.githubusercontent.com/assets/15186093/10920875/be89c134-8244-11e5-9ea7-c3a2d3c9ea21.jpg)
![nexus desktop-1](https://cloud.githubusercontent.com/assets/15186093/10920881/c6928f46-8244-11e5-954c-2c4479f47ca0.jpg)
![nexus desktop-2](https://cloud.githubusercontent.com/assets/15186093/10920898/d28fd268-8244-11e5-989c-dd69cf80cc13.jpg)

**Comment by Luis-Fernando-Molina** [comment]
ok la version 5, pero lo veo muy chiquito en el celu. Esta en la proporcion que tiene que estar???

**Comment by MelissaDugarte** [comment]
@Luis-Fernando-Molina voy checar y lo posteo de nuevo

**Comment by MelissaDugarte** [comment]
@Luis-Fernando-Molina  icono para la SubApp Asset user comunity #224
Estaba un poquito mas pequeño 
![nexus desktop-2-1](https://cloud.githubusercontent.com/assets/15186093/10953722/c40ba60e-831b-11e5-9392-919ecde64882.jpg)

**Comment by Luis-Fernando-Molina** [comment]
lo sigo viendo pequeño, por favor ensancha las lineas y las cabezas aunque queden mas juntas please

**Comment by MelissaDugarte** [comment]
@Luis-Fernando-Molina 
No se si es algo asi¡?
![subapp asset user comunity pantalla 224](https://cloud.githubusercontent.com/assets/15186093/11008020/fafc1196-849f-11e5-8020-eea22f77378b.jpg)

**Comment by emmysm** [comment]
![sin titulo-1](https://cloud.githubusercontent.com/assets/15143489/11078246/df2796cc-87d6-11e5-8733-ea1a5a49024c.png)
![screen crypto customer identity](https://cloud.githubusercontent.com/assets/15143489/11078251/e41d10b2-87d6-11e5-8cdc-0106047f1300.png)
 @Luis-Fernando-Molina

**Comment by emmysm** [comment]
Usé las iniciales AC para representar la asset community y los círculos como usuarios.

**Comment by victoralfonzohd** [comment]
@Luis-Fernando-Molina @arnaldos Propuesta, realice la síntesis de dos personas en una posición arqueada. Ambas crean una forma circular que representan las Assets, los elementos centrales son semicírculos que representan el intercambio o la interacción entre los usuarios.

Propuesta 1

![version-1](https://cloud.githubusercontent.com/assets/15219855/11123409/b8d0f304-8931-11e5-8bdd-8a6694e9db6f.png)

Icono

![719a40aa-8187-11e5-8c26-7cf5dc211e6d](https://cloud.githubusercontent.com/assets/15219855/11123427/d63f7f28-8931-11e5-8c72-e83a75ab3028.png)

**Comment by arnaldos** [comment]
@victoralfonzohd plantealo sin el fondo blanco. Deja el icono sin fondo a ver como se aprecia. y ponle una sombra.

**Comment by victoralfonzohd** [comment]
@arnaldos @Luis-Fernando-Molina 

Version 1: Cambie el fondo circular blanco, por una linea de contorno del mismo color

![version-1](https://cloud.githubusercontent.com/assets/15219855/11146068/2d1b1a4a-89dd-11e5-98a6-5c1b97ae4bf0.png)

Version 2: En esta esta el icono con una sombra muy sutil 

![version-2](https://cloud.githubusercontent.com/assets/15219855/11146096/664194ca-89dd-11e5-9382-ff73e98a5298.png)

Version 3: El icono con sombras fuertes

![version-3](https://cloud.githubusercontent.com/assets/15219855/11146124/9e664b2a-89dd-11e5-9366-fd4ea6409cf9.png)

Iconos:

![versiones-icono](https://cloud.githubusercontent.com/assets/15219855/11146130/acba4348-89dd-11e5-82a5-72e971d57b7f.png)

**Comment by victoralfonzohd** [comment]
@Luis-Fernando-Molina @arnaldos 

Propuesta 2:

![asset-user-comunity](https://cloud.githubusercontent.com/assets/15219855/11488257/5c539f68-9797-11e5-882d-bc837d5bb386.png)

Icono:

![montaje-de-icono](https://cloud.githubusercontent.com/assets/15219855/11488305/aefb9586-9797-11e5-914a-a6b38c165209.png)

**Comment by victoralfonzohd** [comment]
@Luis-Fernando-Molina @arnaldos 

Propuesta 3:

![asset-user-comunity_2](https://cloud.githubusercontent.com/assets/15219855/11506371/60627be4-9821-11e5-8b6b-7981592fb7f8.png)

Icono:

![montaje-de-icono](https://cloud.githubusercontent.com/assets/15219855/11506430/b29a2a7e-9821-11e5-97b8-3efc9a54909d.png)

**Comment by victoralfonzohd** [comment]
@Luis-Fernando-Molina @arnaldos 

Propuesta 4:

![asset-user-comunity_3](https://cloud.githubusercontent.com/assets/15219855/11506924/e8e29c5e-9823-11e5-8e97-a20ebf455803.png)

Icono:

![montaje-de-icono](https://cloud.githubusercontent.com/assets/15219855/11506973/2c7f2482-9824-11e5-92d9-41d4cdb2ad2c.png)

**Comment by arnaldos** [comment]
@victoralfonzohd vamonos con la propuesta 3
