### ISSUE TITLE
Intra User Community App Design / Notification Design

### ISSUE THREAD

**Issue by Neoperol** [bitDubai/fermat-graphic-design#225]
#209

@Luda16 
Notifications, donde llegan las notificaciones sobre nuevos usuarios que quieran conectarse contigo. 

![view_notifications](https://cloud.githubusercontent.com/assets/6201081/10721715/6fbc7e0a-7b7a-11e5-8943-3ef5b8239dfe.jpg)

**Comment by Luis-Fernando-Molina** [comment]
No deberia haber un boton para aceptar o declinar cada conexion? O como tenes pensado eso?

**Comment by Neoperol** [comment]
Realmente es un icono al lado del mensaje. 
Pensando en las futuras acciones que pueden existir dentro de está app aquí se van a manejar todos los Push Notifications que le lleguen al usuario, como invitaciones o nuevos chats. 
Una duda por cierto que tengo, es porque los usuarios deben esperar una respuesta para conectarse con una persona muy similar a como se aceptan las invitaciones en Facebook o como en otras redes se manejan las invitaciones a usuarios que están privados y estos usuarios deben aceptar dicha invitación para poder conectarse. En Facebook es normal que este sistema se use porque las conexiones se tratan de filtrar para que este conectados con solo con tus amigos, pero las podemos manejar libres como en Twitter o Instagram, eso puede facilitar el numero de conexiones entre usuarios. 

Vista con mensaje Activo.
![view_notifications_active](https://cloud.githubusercontent.com/assets/6201081/10759632/9bf9c200-7c8a-11e5-88d2-49103f17aeb7.jpg)

Vista con Dialog, para poder responder la invitación que le llega al usuario. 

![view_notifications_popup](https://cloud.githubusercontent.com/assets/6201081/10759786/9645e518-7c8b-11e5-8163-9a484e5aded2.jpg)

**Comment by Luis-Fernando-Molina** [comment]
No estoy seguro si entendí. 

Tenes que tocar el icono con un + para que te aparezca el pop up?

Aqui vamos por ahora hacer que las conexiones haya que haceptarlas. Como es un sistema P2P sin una autoridad central como Facebook, no hay a quien reclamarle si uno te jode, por eso tenes que aceptarla y podes desconectarte.

**Comment by Neoperol** [comment]
> No estoy seguro si entendí.
> 
> Tenes que tocar el icono con un + para que te aparezca el pop up?
> 
> Aqui vamos por ahora hacer que las conexiones haya que haceptarlas. Como es un sistema P2P sin una autoridad central como Facebook, no hay a quien reclamarle si uno te jode, por eso tenes que aceptarla y podes desconectarte.

No hay que tocar el icono, si tocas cualquier elemento de la lista se abre el dialog up. Cuando esta blanco es que es una notificación que aún no has respondido. 

@Luis-Fernando-Molina

**Comment by Luis-Fernando-Molina** [comment]
ok entiendo. 

El pop up  deberia decir YES   NO , en vez de NO YES

**Comment by Neoperol** [comment]
> El pop up deberia decir YES NO , en vez de NO YES

La posición de los botones en los dialogs, es inversa a la que se usa en la Web, no se toma como referencia el sentido de lectura, sino la facilidad para precionar los botones, por eso los buttones de afirmación se colocan del lado derecho, porque son mas faciles de presionar para el usuario con el pulgar derecho. 

https://www.google.com/design/spec/components/dialogs.html#dialogs-behavior

@Luis-Fernando-Molina

**Comment by Neoperol** [comment]
Esta pendiente por revisión

@Luis-Fernando-Molina 
@furszy

**Comment by Luis-Fernando-Molina** [comment]
> La posición de los botones en los dialogs, es inversa a la que se usa en la Web, no se toma como referencia el sentido de lectura, sino la facilidad para precionar los botones, por eso los buttones de afirmación se colocan del lado derecho, porque son mas faciles de presionar para el usuario con el pulgar derecho. 

Me encantó la explicacion y que haya un criterio.

Si le ponemos a la vista de nombre Connection Request te doy un  :+1:

**Comment by Neoperol** [comment]
Lo voy a cerrar porque solo faltaba cambiarle el nombre xD. 

![Uploading view_notifications_active.jpg…]()

Los recursos de esta vista están en la carpeta view_notifications. 

@furszy

**Comment by Neoperol** [comment]
@furszy 
@josemanueldsds
