### ISSUE TITLE
Intra User Community App Design / Navigation Drawer Design

### ISSUE THREAD

**Issue by Neoperol** [bitDubai/fermat-graphic-design#226]
#209

@Luda16 
Navigation drawer.

![view_navigation](https://cloud.githubusercontent.com/assets/6201081/10721751/e5310e4e-7b7a-11e5-95ff-9112a44b8e9b.jpg)

**Comment by Luis-Fernando-Molina** [comment]
Ok, se ve bien , salvo que friends, debiera ser YOUR CONNECTIONS

**Comment by Neoperol** [comment]
Actualización de la vista Navigation

Falto la explicación sobre la vista, cabe aclarar que el usuario puede cambiar de Identidad al abrir la pestaña que esta al lado de su nombre. En settings la única configuración que puede hacer el usuario es activar esas identidades que quiere manejar en esta app. 

![view_navigation](https://cloud.githubusercontent.com/assets/6201081/10759810/bb6e2cec-7c8b-11e5-8b68-f12a72eec7c8.jpg)

Navigation Drawer / Con la lista de identidades desplegadas. 

![view_navigation_select_identities](https://cloud.githubusercontent.com/assets/6201081/10760826/aff48258-7c90-11e5-81c4-7aced33cbeb1.jpg)

**Comment by Luis-Fernando-Molina** [comment]
Perfecto :+1:

**Comment by Neoperol** [comment]
@furszy 
@josemanueldsds
