### ISSUE TITLE
CCP / Vistas cuando se presiona el botón de enviar

### ISSUE THREAD

**Issue by vnesita** [bitDubai/fermat-graphic-design#227]
Crear las vista paso a paso de proceso de envío partiendo desde el botón principal de enviar

**Comment by vnesita** [comment]
#### Primer paso:

Seleccionar el contacto
Esta vista es la continuación al presionar el botón principal de enviar. Contiene: buscador de contacto, lista de los contactos más usados, y lista de todos los contactos ordenado alfabéticamente, es scroliable.  
![view_send_1step](https://cloud.githubusercontent.com/assets/6201065/10731066/a46731bc-7bda-11e5-8429-fad552298c10.jpg)

**Comment by Luis-Fernando-Molina** [comment]
En general me parece bien. Me gustaria estar para estar seguro, una descripcion de las distintas funcionaldiades dentro de esta vista. Ej que pasa cuando escribo un nombre, cuanta cantidad muestra "MOST USED" y cual es el criterio para aparecer ahi.

Necesito ese nivel de descripcion para cerrar el caso, o al menos esta primera vista del proceso (debería haber un issue par cada vista)
