### ISSUE TITLE
Diseñar panel de desarrollador

### ISSUE THREAD

**Issue by Miguelcldn** [bitDubai/fermat-graphic-design#228]
En fermat.org, cuando una ficha tiene un desarrollador asignado, se le puede dar click a un botón para mostrar información de este.

![developer](https://cloud.githubusercontent.com/assets/5544266/10739261/8d6eeece-7bed-11e5-98f8-e1755509f9ab.png)

Se crea un espacio en la pantalla (el cual está delimitado aquí por un cuadro rojo) con información de éste:
- Foto de perfil
- Nombre de usuario en github
- Nombre personal (si lo tiene definido)
- Correo electrónico (si lo tiene definido)
- Un botón para ver su Timeline (si tiene al menos uno)

Se necesita que se diseñe este panel para mostrarlo de una mejor manera, siguiendo la misma metodología de las fichas: se me provee un svg y png (y un png adicional con texto de prueba para ver las ubicaciones de los textos) y yo lo lleno dinámicamente al usarse.

**Comment by MelissaDugarte** [comment]
@arnaldos, @Miguelcldn y @Luis-Fernando-Molina 
Adjunto panel Version 1 panel de desarrollador #228

![panel de desarrollador_issue_1](https://cloud.githubusercontent.com/assets/15186093/10835650/30c35ce6-7e77-11e5-8f09-a336db942597.jpg)

**Comment by arnaldos** [comment]
@MelissaDugarte  quilale el logo del github, y aplica el de fermat, github no pertenece a fermat ni a bitDubai, aplica al arte en forma horizontal, donde dice git no se entiende para que es ??

**Comment by MelissaDugarte** [comment]
@arnaldos y @Luis-Fernando-Molina 
Ok Adjunto las modificaciones y una nueva versión panel de desarrollador #228

![panel de desarrollador_issue_1](https://cloud.githubusercontent.com/assets/15186093/10847153/c4150ca0-7ee6-11e5-80f8-8eb1c134474b.jpg)
![panel de desarrollador_issue_2](https://cloud.githubusercontent.com/assets/15186093/10847154/c418810a-7ee6-11e5-96db-9471905a1473.jpg)

**Comment by Luis-Fernando-Molina** [comment]
Prefiero la orientación horizontal sin referencia a una wallet (costuras). Veamos mas opciones.

**Comment by Luis-Fernando-Molina** [comment]
Les recomiendo entrar a www.fermat.org / Architecture y ver la onda de lo que ya hay diseñado. Tocar en una fichita y luego en la foto de un developer para sugerir algo de la misma onda. Pueden proponer el diseño incluido en una captura de esa pantalla.

**Comment by MelissaDugarte** [comment]
@arnaldos y @Luis-Fernando-Molina 
Aporte de panel de desarrollador #228
Versión 4
![panel de desarrollador_issue_4-01](https://cloud.githubusercontent.com/assets/15186093/10884763/0a18caa4-814c-11e5-8d4a-f51d850b471a.jpg)

Versión 5
![panel de desarrollador_issue_5-01](https://cloud.githubusercontent.com/assets/15186093/10889112/3b682ce2-8162-11e5-966e-b0a06236f3c9.jpg)

**Comment by Luis-Fernando-Molina** [comment]
@MelissaDugarte muy linda la version 5, la refinemos un poco por favor.

1.no va el telefono
2, cada developer ha construido una cantidad de plugins y eso determina su rango. Fijate de poner la cantidad con el icono de un plugin que es el que pusiste abajo a la derercha.
3.si queres decorar mas su tarjeta podes poner el logo de las plataformas en la que ha trabajado. Aca pusiste uno (la fabrica) pero potencialmente son mas. 
4.Tambien pidieras poner la cantidad de "estrellas" que ha sumado (en nuestro caso son billeteras chiquitas). @arnaldos te lo puede explicar mejor si no me entendes.
5.El logo de Fermat no iria

**Comment by MelissaDugarte** [comment]
@Luis-Fernando-Molina  perfecto hare los ajustes :+1:

**Comment by Miguelcldn** [comment]
Estoy viendo más detalles de los que colectamos:
- Cantidad de elementos (o sólo plugins?) desarrollados (aunque se podría agregar sumándole 1 a cada developer por cada plugin en producción hecho por este)
- Punto 3: Se espera poner en ese panel los platforms y super layers donde el developer ha trabajado? cabrían ahí 17 logos?
- Qué es "Wallet Manager"?

Con respecto al diseño, a todos los elementos en la página les lleno con texto usando <canvas> si utilizas fuentes que no son estándares en entorno web necesitaré que me proveas el archivo (.otf, .ttf, o el que sea) para hacer que el cliente se lo descargue tambien para poder dibujar dicho texto.

**Comment by Luis-Fernando-Molina** [comment]
jajja te veo muy atento @Miguelcldn 

> Cantidad de elementos (o sólo plugins?) desarrollados (aunque se podría agregar sumándole 1 a cada developer por cada plugin en producción hecho por este)

correcto

> Punto 3: Se espera poner en ese panel los platforms y super layers donde el developer ha trabajado? cabrían ahí 17 logos?

era solo una idea, podemos descartar esto por ahora

> Qué es "Wallet Manager"?

eso no iria... me imagino que le puso un cargo a Manuel...

**Comment by MelissaDugarte** [comment]
@Luis-Fernando-Molina y @arnaldos 

Versión Fusion Aporte de panel de desarrollador #228
![panel de desarrollador_issue_4](https://cloud.githubusercontent.com/assets/15186093/10915453/157704c8-8229-11e5-80e6-6c7cb0d7a68b.jpg)

**Comment by Luis-Fernando-Molina** [comment]
> @MelissaDugarte muy linda la version 5, la refinemos un poco por favor.

ya me gustaba la 5

**Comment by Luis-Fernando-Molina** [comment]
tene en cuenta por favor lo que dice Miguel, no vamos a poner lo que yo decia que sugiere que no por ahora

**Comment by MelissaDugarte** [comment]
@Luis-Fernando-Molina 
Version5 Aporte de panel de desarrollador #228
![panel de desarrollador_issue_5-1-01](https://cloud.githubusercontent.com/assets/15186093/10921066/bec07840-8245-11e5-9929-52affe879c42.jpg)

**Comment by Luis-Fernando-Molina** [comment]
1. La lupita que funcion cumpliria?
2. Quita por favor los 3 iconos de la derecha.
3. Agranda un poco el panal de abejas, y mete el CHECK TIME LINE en el centro, con flecha y haz de luz incluido please

**Comment by MelissaDugarte** [comment]
@Luis-Fernando-Molina 
1. La lupa es para ampliar la imagen y distinguir mejor el Developer (son muchos) la he visto implementada en la web y con solo colocar el cursor se amplía solo la foto..

Versión 5 panel de desarrollador #228

![panel de desarrollador_issue_5-01-01](https://cloud.githubusercontent.com/assets/15186093/10953286/71097d34-8319-11e5-91a0-bf2a5b780d86.jpg)

 Versión 6 panel de desarrollador #228
![panel de desarrollador_issue_6-01](https://cloud.githubusercontent.com/assets/15186093/10953287/710dd4a6-8319-11e5-908f-9f54d1e5fa48.jpg)

**Comment by Miguelcldn** [comment]
Sí, pero el problema es que por ahora estamos evitando hacer que los objetos en la página respondan a cuando el mouse pase por encima porque como es 3D implica muchos cálculos por segundo saber en dónde está el mouse en cada momento. De por sí el botón _Check Timeline_ tendré que usar un plano distinto al panel para hacer que responda al click. Algo que tengo que destacar es que dicho botón puede no aparecer, porque si el Developer no tiene ningún timeline el botón no debería salir

**Comment by emmysm** [comment]
![panel de desarrollador propuesta 2](https://cloud.githubusercontent.com/assets/15143489/10974051/6493662a-83b2-11e5-9a92-96d06151b6ef.png)
![panel de desarrollador propuesta](https://cloud.githubusercontent.com/assets/15143489/10974052/64ab8d9a-83b2-11e5-8534-449f8aedc96b.png)

Dejo unas propuestas por aca,  @Luis-Fernando-Molina , la parte lateral derecha pudiese funcionar como un boton o un panel desplegable, a ver si te sirve, @Miguelcldn

**Comment by Luis-Fernando-Molina** [comment]
@MelissaDugarte vamos con la version 5 sin la lupita y con el panal un poquito mas abajo y un poquito mas grande (el boton del mismo tamaño)

@emmysm en este issue ya estamos encaminados, podés aportar pero tomando lo que ya se va confirmando (osea los fuentes de la ultima version selecionada de @MelissaDugarte . gracias

**Comment by emmysm** [comment]
@Luis-Fernando-Molina , gracias.

**Comment by MelissaDugarte** [comment]
@Luis-Fernando-Molina 

Versión 5 panel de desarrollador #228
![panel de desarrollador 228-01](https://cloud.githubusercontent.com/assets/15186093/11008270/92dd4038-84a1-11e5-938e-987bdf0f6a2a.jpg)

**Comment by ivonnesantos** [comment]
@arnaldos  @Luis-Fernando-Molina @emmanuelcolina 

Propuesta 1
![panel de desarrollador_6_iv-01](https://cloud.githubusercontent.com/assets/15238660/11640242/c2162052-9d03-11e5-8fc3-0aefd8c5866e.png)

Propuesta 2
![panel de desarrollador_6_iv-02](https://cloud.githubusercontent.com/assets/15238660/11640254/cecf2bd6-9d03-11e5-9cb1-4e82881e4013.png)

**Comment by arnaldos** [comment]
propuesta 1 el texto del boton, prueba otra tipografía.

**Comment by ivonnesantos** [comment]
![panel de desarrollador_6_iv-01](https://cloud.githubusercontent.com/assets/15238660/11643050/adba0852-9d13-11e5-9621-1f634cbc366b.png)

@arnaldos

**Comment by arnaldos** [comment]
@ivonnesantos crea los archivos y pasa le a @Miguelcldn plz

**Comment by arnaldos** [comment]
@Miguelcldn esto esta implementado ? es para cerrar el caso ..... avisame cuando puedas plz

**Comment by Miguelcldn** [comment]
Sí, está listo, ya este caso puede cerrarse
