### ISSUE TITLE
Crear estilo de flecha para navegar dentro de Fermat.org

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#229]
se propondrán varios estilos de flechas para navegar en Fermat.org

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina estilos de flechas 

Versión 1

![navigator arrow-01](https://cloud.githubusercontent.com/assets/13594347/10779681/5bbd14ea-7d06-11e5-8620-41ad39cb6ddf.png)

Versión 2

![navigator arrow-02](https://cloud.githubusercontent.com/assets/13594347/10779683/66e1bef2-7d06-11e5-943d-1647f595e864.png)

Versión 3

![navigator arrow-03](https://cloud.githubusercontent.com/assets/13594347/10779686/701b948e-7d06-11e5-8bf1-8d14d9c76991.png)

Versión 4

![navigator arrow-04](https://cloud.githubusercontent.com/assets/13594347/10779689/770151bc-7d06-11e5-9dea-29a4195f6a49.png)

**Comment by Luis-Fernando-Molina** [comment]
Tomemos la version 3 y la continuemos. La mitad de la derecha, por favor hundile el fondo hacia la izquierda un poquito. Planteá otras variantes de colores a ver como queda.

**Comment by Luis-Fernando-Molina** [comment]
Antes de cerrar este caso me gustaria ademas que hicieras una captura de pantalla de Fermat ORG y pusieran las flechas ahi para ver como quedan por favor.

**Comment by arnaldos** [comment]
vale perfecto !!

**Comment by pancho693** [comment]
@arnaldos @Luis-Fernando-Molina  Icono Flecha Para navegar Fermat
Flecha # 7
![flecha 7](https://cloud.githubusercontent.com/assets/15208237/10808738/ddbbe510-7dc0-11e5-9bf7-a56bcdec07fa.jpg)
Flecha # 8
![flecha 8](https://cloud.githubusercontent.com/assets/15208237/10808779/319bdf50-7dc1-11e5-90f9-0eb313bb735d.jpg)

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina comparto el estilo de la flechas ta lcono me solicitaste, partiendo de la ultima publicación

Versión 9

![fermatorg_arrow_navigator_5](https://cloud.githubusercontent.com/assets/13594347/10810700/c18a4a98-7dd5-11e5-8ad8-d2f6236f8dba.png)

Versión 10

![fermatorg_arrow_navigator_6](https://cloud.githubusercontent.com/assets/13594347/10810725/1eca381c-7dd6-11e5-8e52-5fd25778aaeb.png)

Versión 11

![fermatorg_arrow_navigator_7](https://cloud.githubusercontent.com/assets/13594347/10810732/2a4476d0-7dd6-11e5-9cc0-3c25d0ce6738.png)

Versión 12

![fermatorg_arrow_navigator_8](https://cloud.githubusercontent.com/assets/13594347/10810742/39762432-7dd6-11e5-877b-d1a013b606b2.png)

Ejemplos

## ![example-1](https://cloud.githubusercontent.com/assets/13594347/10810808/c8e39ba4-7dd6-11e5-9a6c-420b278cbf56.jpg)

## ![example-2](https://cloud.githubusercontent.com/assets/13594347/10810809/c8e9641c-7dd6-11e5-90cd-aa3b03ddb619.jpg)

## ![example-3](https://cloud.githubusercontent.com/assets/13594347/10810810/c91129a2-7dd6-11e5-93dd-71baf9814e47.jpg)

![example-4](https://cloud.githubusercontent.com/assets/13594347/10810811/c91d185c-7dd6-11e5-8c48-da35b31df8d6.jpg)

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina  de las que publique apunto hacia la versión 10

**Comment by Luis-Fernando-Molina** [comment]
Vamonos con la version 10 :+1:   Por favor cerrá el caso una vez que @Miguelcldn lo aplique en el sitio. Gracias

**Comment by Miguelcldn** [comment]
Quedo pendiente del commit @arnaldos referencia este issue con el commit para verlo cuando se haga

**Comment by arnaldos** [comment]
vale perfecto @Miguelcldn ya hago el commit y cierro el caso

**Comment by arnaldos** [comment]
@Miguelcldn listo el commit

**Comment by Miguelcldn** [comment]
Aplicadas las flechas, @arnaldos, esas flechas tienen un texto que las acompaña, qué tipografía y color estaría bien para ponerle?

**Comment by arnaldos** [comment]
@Miguelcldn  yo usaría (source sans pro, roboto o la canaro que fue la que se uso para fermat ) y el color podría ser el mismo negro que estas usando rebajado a un 90 - 95 %.

**Comment by Miguelcldn** [comment]
Chevere, ya lo aplico a ver cómo queda :+1:
