### ISSUE TITLE
Mejorar la diagramación de la lámina: Competitive Advantage

### ISSUE THREAD

**Issue by m471c4** [bitDubai/fermat-graphic-design#23]
Viene del #12

Es necesario mejorar varias cosas de esta lámina; por ejemplo, el tamaño de algunos textos -señadalos con flechas rojas-, que no se aprecian bien (si bien serán visualizadas en algún tipo de proyector, se puede lograr que se vean mejor). 

También hay demasiadas imágenes que generan un caos visual.

![screen1](https://cloud.githubusercontent.com/assets/13468350/9099169/68e5ddbe-3b98-11e5-80e2-444d214fd0b3.png)

**Comment by Luis-Fernando-Molina** [comment]
:+1:
