### ISSUE TITLE
Crear Propuestas para una tarjeta de negocios de Fermat.

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#230]
Se realizaran Propuestas para una tarjeta de negocios de Fermat las cuales serán discutidas en este caso.

**Requisitos**

Medidas standar de las tarjetas 

8,5 x 5,5 cm
8 x 5 cm
5,5 x 5,5 cm

**Comment by victoralfonzohd** [comment]
@Luis-Fernando-Molina @arnaldos Presento dos propuestas para la tarjeta de negocios de Fermat, Su formato es de 8,5 x 5,5 cm.

Propuesta 1

![tdp-1](https://cloud.githubusercontent.com/assets/15219855/10925780/606da768-8263-11e5-82fe-c22b8de4068f.png)

Propuesta 2

![tdp-2](https://cloud.githubusercontent.com/assets/15219855/10925784/6ba6bdae-8263-11e5-8e19-3ee350e4fa53.png)

**Comment by m471c4** [comment]
@Luis-Fernando-Molina @arnaldos acá una versión vertical.

![tarjetafermat](https://cloud.githubusercontent.com/assets/13468350/10932507/81bdba3a-82a3-11e5-9e21-65d334e6c33f.png)

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina comparto unas versiones de tarjetas 

Versión 1

![vs1](https://cloud.githubusercontent.com/assets/13594347/10947191/ded76cfc-82f8-11e5-9faf-e2c8dc4f16e4.jpg)
![tarjetra de presentacion-01](https://cloud.githubusercontent.com/assets/13594347/10947192/df9a5140-82f8-11e5-85fa-371b5a8ceebb.jpg)
![tarjetra de presentacion-02](https://cloud.githubusercontent.com/assets/13594347/10947193/dfe5f276-82f8-11e5-9a59-b869a0183689.jpg)

Versión 2

![vs2](https://cloud.githubusercontent.com/assets/13594347/10947182/d745b930-82f8-11e5-9ac5-9d75e6cd278b.jpg)
![tarjetra de presentacion-03](https://cloud.githubusercontent.com/assets/13594347/10947183/d74e5ba8-82f8-11e5-9733-7898e196a468.jpg)
![tarjetra de presentacion-04](https://cloud.githubusercontent.com/assets/13594347/10947184/d752dfd4-82f8-11e5-887b-03aa178472f4.jpg)

Versión 3

![tarjetra de presentacion-05](https://cloud.githubusercontent.com/assets/13594347/10947211/f0d97896-82f8-11e5-880e-5e83ab0046b7.jpg)
![tarjetra de presentacion-06](https://cloud.githubusercontent.com/assets/13594347/10947212/f0dd97be-82f8-11e5-8f3d-25bb254ec261.jpg)
![vs3](https://cloud.githubusercontent.com/assets/13594347/10947213/f1082916-82f8-11e5-8dc6-a0cc9b1366c7.jpg)

**Comment by Luis-Fernando-Molina** [comment]
No me gusta el negro., mas opciones please. Que participe el resto tambien.

**Comment by Luis-Fernando-Molina** [comment]
perdon no habia visto las otras de arriba...

La version 2 de @victoralfonzohd , la cara del frente me gusta. Aunque debiera usar el logo 3d de fermat en su ultima version.

Probemos ponerle la foto de la persona.

La tarjeta es de Fermat no de bitDubai.

**Comment by victoralfonzohd** [comment]
@Luis-Fernando-Molina Modificacion en el Tiro de la tarjeta, 

Propuesta 1: Use las wallets 3D como elemento de fondo, dejando el Logo de Fermat en 2D

![tdp-1](https://cloud.githubusercontent.com/assets/15219855/10953295/7fbb7710-8319-11e5-8e01-5725879f2756.png)

Propuesta 2: Coloque el Logo de Fermat en 3D, dejando en el fondo las wallets planas. 

![tdp-2](https://cloud.githubusercontent.com/assets/15219855/10953296/7fed20bc-8319-11e5-8b12-99d761790e94.png)

**Comment by Luis-Fernando-Molina** [comment]
> en su ultima version.

no estas usando la ultima version... @arnaldos revisa que pasó con la ultima please.

Para el frente sigamos con la propuesta 1. Fijate de agrandar un poco la wallet 3d y moverla un poco para arriba asi no queda el triangulito blanco y se ve mas la roja chiquita. gracias

> Probemos ponerle la foto de la persona.

Mas opciones para la parte de atras please.

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina nuevas propuestas

Versión 4

![tarjetra de presentacion2-03](https://cloud.githubusercontent.com/assets/13594347/10979483/fe2cacf8-83ce-11e5-9313-ce73c91926ac.jpg)

![tarjetra de presentacion2-04](https://cloud.githubusercontent.com/assets/13594347/10979484/fe33b55c-83ce-11e5-8b07-f866cbb06b78.jpg)

![vs4](https://cloud.githubusercontent.com/assets/13594347/10979498/12026fe2-83cf-11e5-99a9-cdfd3e1a2bcd.jpg)

Versión 5

![tarjetra de presentacion2-06](https://cloud.githubusercontent.com/assets/13594347/10979517/305541cc-83cf-11e5-82bf-47e39444ca60.jpg)

![tarjetra de presentacion2-05](https://cloud.githubusercontent.com/assets/13594347/10979518/305b641c-83cf-11e5-9951-9734ee888d0e.jpg)

![vs5](https://cloud.githubusercontent.com/assets/13594347/10979530/3e351380-83cf-11e5-8ade-53252fb59529.jpg)

Versión 6

![tarjetra de presentacion2-09](https://cloud.githubusercontent.com/assets/13594347/10979545/510f4f16-83cf-11e5-9229-abd53b9e632c.jpg)

![tarjetra de presentacion2-07](https://cloud.githubusercontent.com/assets/13594347/10979547/51f0ba46-83cf-11e5-889d-624fbb6708ac.jpg)

![vs6](https://cloud.githubusercontent.com/assets/13594347/10979556/63080ea6-83cf-11e5-89f3-dfddb695fa90.jpg)

Versión 7

![tarjetra de presentacion2-08](https://cloud.githubusercontent.com/assets/13594347/10979564/6d39fd62-83cf-11e5-8d83-352db884b8c5.jpg)

![tarjetra de presentacion2-10](https://cloud.githubusercontent.com/assets/13594347/10979565/6d790d68-83cf-11e5-946e-b61ba4dd61e1.jpg)

![vs7](https://cloud.githubusercontent.com/assets/13594347/10979573/770798f4-83cf-11e5-9d98-9b7e2bb167bc.jpg)

**Comment by victoralfonzohd** [comment]
@Luis-Fernando-Molina Correcciones de tamaño y posición del Wallet 3d en el tiro de la tarjeta, nueva propuesta para el Retiro

![version-3](https://cloud.githubusercontent.com/assets/15219855/10985951/d5c0c55a-83f7-11e5-962e-10d398456bf1.png)

**Comment by Luis-Fernando-Molina** [comment]
@victoralfonzohd la parte del frente puede quedar asi, la de atrás hay que seguir buscando. 

Fijate la parte de atras si poner de nuevo la billetera.

**Comment by victoralfonzohd** [comment]
@Luis-Fernando-Molina Pruebas para el retiro de la tarjeta

Versión 1

![retiro-v1](https://cloud.githubusercontent.com/assets/15219855/11039644/e79d111c-86da-11e5-8166-4356cc5ea677.png)

Versión 2 

![retiro-v2](https://cloud.githubusercontent.com/assets/15219855/11039655/f141760e-86da-11e5-86ce-a1abd52696ba.png)

**Comment by Luis-Fernando-Molina** [comment]
@victoralfonzohd  Vamos con la version 2

FRENTE:

Esta casi listo, salvo por el hecho de que para el logo chiquito no tomaste la ultima version del logo. Por favor usa la ultima.

REVERSO:

En general esta bien.
1. Pone por favro el Nombre en una sola linea.
2. Ponele algun color a los iconitos del tel , ubicación , mail.
3. Pone un iconito de github y la dirección del repositorio

Mostrá la imagen mas grande que no se ven los detalles.

Con eso estaríamos.

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina  antes del últimos post que realizo @victoralfonzohd coloque unas propuestas no se si le pueda servir a victor para que las adapte a su propuesta para el reverso de la tarjeta. es solo una sugerencia. :+1:

**Comment by victoralfonzohd** [comment]
@Luis-Fernando-Molina cuando dices el logo chiquito, hablamos del logo 2D?.. Creo estar usando la ultima versión, esta me la facilito Dayana.. @arnaldos Si hay una versión actualizada por favor indícame cual es, gracias por tu sugerencia voy a adaptarla un poco en otra propuesta..

Adjunto las modificaciones pedidas

Tiro

![tiro-1](https://cloud.githubusercontent.com/assets/15219855/11076460/0d891130-87cd-11e5-8956-fc9244de13f1.png)

Retiro

![retiro-1](https://cloud.githubusercontent.com/assets/15219855/11076566/98628426-87cd-11e5-8489-b07ee7c090e1.png)

**Comment by arnaldos** [comment]
@victoralfonzohd  cuando @Luis-Fernando-Molina se refiere a la ultima versión. Es a la versión del logo en 3D. Ya que ese sera la versión que se va a usar para Fermat en todos los artes donde se deba aplicar la marca. 

@Luis-Fernando-Molina es así cierto ?

**Comment by Luis-Fernando-Molina** [comment]
correcto, el 2D sirvio para llegar al 3d
