### ISSUE TITLE
Crear Propuestas de logo para el Fermat Book

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#231]
El **Fermat Book** es un libro que nos habla acerca de la misión, visión y el origen del proyecto Fermat .

**Comment by victoralfonzohd** [comment]
@Luis-Fernando-Molina @arnaldos En esta propuesta use El Wallet principal del logo de Fermat, este lo desplegue agregandolo como elemento principal en el icono del libro.. La idea del despliegue es para mostrar la parte interna del Wallet, como si este se abriera para enseñarnos su "misión, visión y origen"
#231
![logo_fermatbook_propuesta1-01-01-01](https://cloud.githubusercontent.com/assets/15219855/10773375/49393abc-7ccd-11e5-9b62-3b33b8532951.png)

**Comment by Luis-Fernando-Molina** [comment]
@victoralfonzohd El libro se ve bien, quizas la billetere pudiera servir como de cierre, como sucede con alguna agendas. No se si desplegada.

Otra posible idea es que el libro tenga características similares a la billetera, como costura. Sigamos probando.

**Comment by victoralfonzohd** [comment]
@Luis-Fernando-Molina Aplique los detalles de costura a la cara principal del libro, cambie los colores del lomo, el wallet ya no esta desplegado y por su posicion da pie la idea del cierre o solapa, quizas el tamaño del wallet este algo grande es para que el mismo no se pierda y solo se vea el libro.

Propuesta

![fermatbook_p2-01](https://cloud.githubusercontent.com/assets/15219855/10801833/9190b84e-7d8b-11e5-9db4-3b897b95707f.png)

**Comment by Luis-Fernando-Molina** [comment]
va mejorando, revisá la tipografia no es la de fermat, pone book sin bold y en el mismo renglon. 

En vez de la wallet solo el cierre de la misma.... please

**Comment by victoralfonzohd** [comment]
@Luis-Fernando-Molina En vez de un cierre pense en una cerradura, como en los libros antiguos! Ya modifique la tipografia 

Propuesta 3

![logo_fermat_book_p4-01](https://cloud.githubusercontent.com/assets/15219855/10830564/7ed90b30-7e52-11e5-879d-1736ebab6594.png)

**Comment by Luis-Fernando-Molina** [comment]
La cerradura me gusta, pero cambiaste el color, me gustaba mas antes.  Podes rotar el agujero de la llave 90 grados?

> pone book sin bold y en el mismo renglon. 

Book sale mas grande que fermat y no está en el mismo renglón.

**Comment by victoralfonzohd** [comment]
@Luis-Fernando-Molina Correciones

![logo_fermatbook_p4-01](https://cloud.githubusercontent.com/assets/15219855/10831304/0aa6bbcc-7e57-11e5-8ee3-9e9796bae9c1.png)

**Comment by Luis-Fernando-Molina** [comment]
@arnaldos opiniones? revisa que los espacios blancos sean de acuerdo al estandard, el tamaño de las costuras tambien. 

Revosa si corresponde el uso del negro en la cerradura.

Va quedando...

**Comment by victoralfonzohd** [comment]
@Luis-Fernando-Molina  Por los espacios en blanco tome como guia  la separación que hay en el logo de Fermat, el tamaño de las costuras son las mismas..

 ![logo_fermat_book_2](https://cloud.githubusercontent.com/assets/15219855/10832120/9698bba4-7e5b-11e5-84fb-54a1f4c84d28.png)

![logo_fermat_book_3](https://cloud.githubusercontent.com/assets/15219855/10832121/96caf7cc-7e5b-11e5-97b6-1a6ad4d1df47.png)

**Comment by victoralfonzohd** [comment]
@Luis-Fernando-Molina @arnaldos Como vamos con esta propuesta?

**Comment by Luis-Fernando-Molina** [comment]
bien, lo unico que no me cierra es la cerradura y su borde en negro, proba en rojo oscuro please

**Comment by victoralfonzohd** [comment]
@Luis-Fernando-Molina  El borde es marrón, no es negro! 

Prueba en Rojo 

![logo_fermat_book_1](https://cloud.githubusercontent.com/assets/15219855/10896485/9491d438-818c-11e5-9f64-a6393db297c2.png)

Prueba en Rojo Oscuro

![logo_fermat_book_2](https://cloud.githubusercontent.com/assets/15219855/10896488/9c61dcbc-818c-11e5-85b8-346619b17f19.png)

**Comment by Luis-Fernando-Molina** [comment]
Ok, sigamos con el rojo oscuro, el ultimo.

Proba por favor ponerle arriba las 3 billeteras del logo de fermat (lo cual lo trasnformaria en el fermat book)

**Comment by victoralfonzohd** [comment]
@Luis-Fernando-Molina 

Prueba 

![logo_fermat_book_3](https://cloud.githubusercontent.com/assets/15219855/10898302/58d92338-819b-11e5-80ec-d7878a0fe4a5.png)

**Comment by victoralfonzohd** [comment]
@Luis-Fernando-Molina Para adaptar un poco mas el logo con el de Fermat, cambie el color rojo por el del Wallet principal del Logo de Fermat

Prueba 

![logo_fermat_book_4](https://cloud.githubusercontent.com/assets/15219855/10900754/d822add4-81b5-11e5-8d03-593d0d803566.png)

**Comment by Luis-Fernando-Molina** [comment]
genial, ahora solo verifica que las lineas blancas dentro del libro sean de acuerdo al standard, veo dos tamaños. @arnaldos referencia el standard please.

**Comment by Luis-Fernando-Molina** [comment]
vamos con la version verde

**Comment by victoralfonzohd** [comment]
@Luis-Fernando-Molina Listo, hice los ajustes usando de referencia el Logo de Fermat 

![logo_fermat_book_2](https://cloud.githubusercontent.com/assets/15219855/10923777/fcabbcaa-8254-11e5-8f54-ebe795969a6c.png)

**Comment by Luis-Fernando-Molina** [comment]
:+1:  @arnaldos podes cerrar  este caso luego de que se generen todos los formatos que necesitamos.

Asegurense que la distancia de la palabra al libro sea la misma que en el logo de Fermat, y el tamaño de la letra tambien.

@jonathanborges3d por favor tomá esto para hacer la versión 3D. (crea tu propio caso y linkealo)

@victoralfonzohd good job!

@gustl-arg para vos!!

**Comment by victoralfonzohd** [comment]
@Luis-Fernando-Molina  En cuanto al tamaño del texto es un poco mas pequeño que el de Fermat, no use el mismo tamaño ya que "Fermat Book" son dos palabras y ese tamaño desequilibra la imagen en general dándole mucho peso al texto.

Corrección en la separación del texto con el elemento gráfico:

![logo_fermat_book_2](https://cloud.githubusercontent.com/assets/15219855/10950975/e87dec72-830c-11e5-8aa8-6aa070300167.png)

Comenzare a generar los formatos finales.

**Comment by gustl-arg** [comment]
que equipazo! mb el logo..totalemnte coherente!

El 4 de noviembre de 2015, 16:56, Luis Fernando Molina <
notifications@github.com> escribió:

> [image: :+1:] @arnaldos https://github.com/arnaldos podes cerrar este
> caso luego de que se generen todos los formatos que necesitamos.
> 
> Asegurense que la distancia de la palabra al libro sea la misma que en el
> logo de Fermat, y el tamaño de la letra tambien.
> 
> @jonathanborges3d https://github.com/jonathanborges3d por favor tomá
> esto para hacer la versión 3D. (crea tu propio caso y linkealo)
> 
> @victoralfonzohd https://github.com/victoralfonzohd good job!
> 
> @gustl-arg https://github.com/gustl-arg para vos!!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/bitDubai/fermat-graphic-design/issues/231#issuecomment-153845586
> .

## 

Gustavo Corradi
Cel. (0351) 15 2011 110

**Comment by Luis-Fernando-Molina** [comment]
:+1:

**Comment by gustl-arg** [comment]
@victoralfonzohd  buenisimo ! cuando se que esta aprobado y lo puedo linkear como imagen en el libro?
donde esta ubicada?
@Luis-Fernando-Molina  por el asciidoc tengo creada un folder images en la ruta del libro (/fermat/fermat-book), la ponemos ahi ??

**Comment by Luis-Fernando-Molina** [comment]
@arnaldos  te va a pasar un link...

**Comment by jonathanborges3d** [comment]
@gustl-arg  Aquí están los archivos de la versión 3D del logo: https://github.com/bitDubai/fermat-graphic-design/commit/5dfbbd1cb3ff7253636c132e9ee6883a2a48168f

**Comment by Luis-Fernando-Molina** [comment]
los logos hay que linkearlos al Media Kit no al repositorio de graphic desing que es privado, sino solo lo pueden ver quienes tengan acceso pero no el publico en genera.

@arnaldos @jonathanborges3d @gustl-arg

**Comment by jonathanborges3d** [comment]
@Luis-Fernando-Molina  Ok, ya están en el repositorio correcto también. 
@gustl-arg 
https://github.com/bitDubai/media-kit/commit/5597d96da70fe0ef359076517f48d2a6efeafa6d

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina @gustl-arg  les dejo el enlace para las imagenes de los readme https://github.com/bitDubai/media-kit/tree/master/Readme%20Image/Fermat%20book%20logotype

**Comment by arnaldos** [comment]
cierro el caso los fuentes ya se subieron y el logo esta aplicado :+1:
