### ISSUE TITLE
CCP / Send Form

### ISSUE THREAD

**Issue by vnesita** [bitDubai/fermat-graphic-design#232]
![view_send_2step](https://cloud.githubusercontent.com/assets/6201065/10760770/63f6f38a-7ca5-11e5-940f-aa3a631938e6.jpg)

**Comment by Neoperol** [comment]
@furszy 

Vista Actual. 

![seleccion_054](https://cloud.githubusercontent.com/assets/6201081/11016584/ea4c53a6-8558-11e5-940c-5d3a4e258d12.png)

Vista Final. 

![view_matias_send_detail](https://cloud.githubusercontent.com/assets/6201081/11016598/4490aa2e-8559-11e5-85d0-f55694916bcf.jpg)
Cambios, Agregar los colores y los titulos y los textview

Agregar el titulo Description sobre el Edit Text 
Colores

Cambiar el icono del menu por el icono back. 

ic_action_back.png

Title “green” : #12aca1
Text content : #4f4f4f
Button Send: Background: #1173aa Text:#ffffff

**Comment by furszy** [comment]
completed
