### ISSUE TITLE
Versión 3D del logo de Fermat

### ISSUE THREAD

**Issue by jonathanborges3d** [bitDubai/fermat-graphic-design#236]
Se requiere el logo de Fermat a color en versión 3D

Actual:

![alt text](https://github.com/bitDubai/fermat-graphic-design/blob/master/2D%20Design/Fermat/Fermat%20Logotype/logo_jpg/logo_github_readme.jpg)

Primera Versión 3D:
![fermat](https://cloud.githubusercontent.com/assets/13649739/10775406/3b22cab2-7cda-11e5-8840-e4cb8f5e7c21.jpg)

@Luis-Fernando-Molina Qué opinas?

**Comment by Luis-Fernando-Molina** [comment]
No me gusta el bode blanco, eso deberia volar.
La palabra Fermat se ve rara
Le resto no esta mal.

Las dos primeras wallet parecieran que estan adentro, la roja parece fuera de la verde.

**Comment by jonathanborges3d** [comment]
@Luis-Fernando-Molina Ok, corregí el borde, le di mayor profundidad a la palabra Fermat y en la segunda imagen la roté un poco hacia arriba para que quedara de frente.

![fermat_2](https://cloud.githubusercontent.com/assets/13649739/10776761/89327e80-7ce6-11e5-8695-1595966daaa1.jpg)

![fermat_3](https://cloud.githubusercontent.com/assets/13649739/10776976/c76fa8f6-7ce8-11e5-9146-fb50cb75b3bb.jpg)

**Comment by Luis-Fernando-Molina** [comment]
La wallet :+1: 
La palabra dejala sin rotar pero bajale la altura al minimo que no se vea mal. No necesito que se vea evidentemetne en 3d, puede ser prácticamente 2D

**Comment by jonathanborges3d** [comment]
Puede ser algo así?

![fermat_5](https://cloud.githubusercontent.com/assets/13649739/10777960/1b0dd136-7cf3-11e5-8ef2-0396218b497d.jpg)

**Comment by Luis-Fernando-Molina** [comment]
Yes, genera los distintos formatos por favor, incluyendo la version README, Veersion cuadrada, etc. Quedó perfecto! :+1:

**Comment by Luis-Fernando-Molina** [comment]
Luego pasame el link para ponerlo en el README plase

**Comment by jonathanborges3d** [comment]
@Luis-Fernando-Molina Listo, ya estan en el repositorio. 

El raw link para la imágen del Readme:

https://raw.githubusercontent.com/bitDubai/fermat-graphic-design/master/3D%20Design/3DLogotypes/FermatLogotype3D/Fermat_Logo_3D_Readme_header.jpg?token=ANBHS_iMFk9GjzYe_4GykDGSLl0uxqrPks5WOYOcwA%3D%3D

**Comment by Luis-Fernando-Molina** [comment]
@Miguelcldn por favor usa este logo en Fermat ORG en vez de la version actual.

@arnaldos por favor hacete la version sin la palabra "Fermat" y ademas la version icono, que es laque vamos a usar en la APP Fermat en Android. Cuando este avisale  a @furszy asi atualiza la APP con ese icono.

Gracias!

**Comment by Luis-Fernando-Molina** [comment]
@jonathanborges3d  falta la versión cuadrada. Acordate de manter una version para README en el repo.

**Comment by Luis-Fernando-Molina** [comment]
@Miguelcldn @arnaldos  aguantes un minuto: @jonathanborges3d podes mover la billetera roja hacia la derecha de manera que salga desde la billetera verde antes de la curva? Pienso que eso puede mejorar el ejecto de que sale desde adentro, sino parece estar atras. Una vez que ajustemos eso el resto puede tomar este como el nuevo logo oficial de fermat. (Fijate la billetera del medio si debe acompañar el movimiento un poquitito par que quede todo perfecto)

**Comment by Miguelcldn** [comment]
@jonathanborges3d puedes poner los modelos del logo y las letras por separado? En la página animamos para que el logo se vaya para arriba y las letras para abajo.

**Comment by jonathanborges3d** [comment]
@Luis-Fernando-Molina Aquí está la versión corregida, si se aprueba genero las versiones para subirlas al repositorio incluyendo los elementos por separado @Miguelcldn.

![fermat_6](https://cloud.githubusercontent.com/assets/13649739/10799728/83fa98c2-7d80-11e5-90b8-337a3a070572.jpg)

**Comment by Luis-Fernando-Molina** [comment]
@jonathanborges3d veo algo raro en la imagen, no se ve tan nitida como la anterior. Revisalo por fvor.

**Comment by jonathanborges3d** [comment]
@Luis-Fernando-Molina En mayor resolución:

![fermat_7](https://cloud.githubusercontent.com/assets/13649739/10800507/4b33f070-7d84-11e5-80c1-5cc0680b48a5.jpg)

**Comment by Luis-Fernando-Molina** [comment]
:+1:  

Listo vamos a usar este logo desde ahora, que cada uno genere lo que tenga que generar @Miguelcldn @arnaldos @jonathanborges3d 
1. Version README  (Luis Molina)
2. Version cuadrada para facebook  Fermat. (Luis Molina)
3. Version Icono para la APP Fermat ( @furszy  )
4. Version Fermat ORG Loader ( @Miguelcldn )
5. Version Loader de la Wallet (cuado arranca la APP)  @furszy 

@arnaldos crate un caso por cada uno de los puntos anteriores y cerralos cuando los veas aplicado en cada lugar. Empuja a quien haga falta para que lo aplique.

**Comment by jonathanborges3d** [comment]
@Luis-Fernando-Molina @Miguelcldn Se usará un modelo .json en fermat.org o el render del modelo que se aprobó aquí?

Ya me comuniqué con Ricardo y me aclaró el asunto.

Aquí están las versiones del logo renderizado: https://github.com/bitDubai/fermat-graphic-design/commit/9db010a1ce784585b06da23b3b0516ecabd97be1

**Comment by Luis-Fernando-Molina** [comment]
Tratemos de usar el render.

**Comment by Luis-Fernando-Molina** [comment]
@arnaldos punto 2 done.

**Comment by Luis-Fernando-Molina** [comment]
@arnaldos punto 1 done.

**Comment by Miguelcldn** [comment]
- [x] Version README (Luis Molina)
- [x] Version cuadrada para facebook Fermat. (Luis Molina)
- [ ] Version Icono para la APP Fermat ( @furszy )
- [x] Version Fermat ORG Loader ( @Miguelcldn )
- [ ] Version Loader de la Wallet (cuado arranca la APP) @furszy

(Probando a ver si otros usuarios pueden editar mi comentario si se ponen así)

**Comment by Miguelcldn** [comment]
@jonathanborges3d cuando puedas, podrías generarme otros .png con la mitad de la resolución de la última vez? o 75% de esta? La imagen del logo del .png que tengo es 1Mb, se tarda alguito para bajarse, quiero ver si en menor resolución se sigue viendo bien.

**Comment by jonathanborges3d** [comment]
@Miguelcldn, Listo el commit, tienes a 75 y a 50% del tamaño original. https://github.com/bitDubai/fermat-graphic-design/commit/b98a79a52e73ee4886eefee6c220f48b381cc2c1

**Comment by Miguelcldn** [comment]
Gracias, y disculpa la molestia pero podría haber también versiones con proyección ortogonales de las mismas resoluciones? Es muy sutil pero noto que la proyección es en perspectiva y la F de fermat está ligeramente inclinada por esto mismo

**Comment by jonathanborges3d** [comment]
@Miguelcldn No te preocupes. Prueba con éstos: https://github.com/bitDubai/fermat-graphic-design/commit/fbaea357fe97783312bac61b0ea246226f791876, son renders con cámara ortogonal.

**Comment by jonathanborges3d** [comment]
@Miguelcldn No sé si pasará en mi máquina nada más, pero estoy viendo así el logo de fermat al cargar la página:

![fermat_org](https://cloud.githubusercontent.com/assets/13649739/10864397/fe882786-7fbe-11e5-9449-764613a5ec25.png)

Supongo que estás usando los elementos por separado, tal vez las carteras bajaron un poco la posición, se están solapando detrás del nombre. Si es un asunto del archivo .png me avisas para generar uno nuevo, aunque los veo bien en el repositorio.

**Comment by Miguelcldn** [comment]
Solucionado, fue porque se actualizó el código pero no las nuevas imágenes en vista ortogonal, limpien la caché de su navegador y verán la nueva versión

**Comment by jonathanborges3d** [comment]
@Luis-Fernando-Molina Le entregué a @furszy los íconos para la app y ya me informó que aplicó el logo en la splashscreen.
