### ISSUE TITLE
Logo para el equipo Code Butchers (carniceros de código)

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#237]
@lnacosta, en este issue haremos el briefing y discutiremos brevemente cómo quisieran representar su equipo, este logo será utilizado inicialmente en las portadas de las reuniones.

Pueden participarle a los demás miembros del equipo.

**Comment by leonacostaok** [comment]
@arnaldos ok, voy a pensar para que lado me gustaría apuntar.

**Comment by arnaldos** [comment]
vale perfecto !!!

**Comment by leonacostaok** [comment]
@arnaldos, I want to name my team "Code Butchers", in Spanish should be something like "carniceros de código". Have you got some ideas for the Logotype?

**Comment by leonacostaok** [comment]
What about a butcher's knife over a <code/> like almost cutting it?

**Comment by arnaldos** [comment]
:+1:

**Comment by MelissaDugarte** [comment]
@arnaldos  @lnacosta 

Versión 1 Logo para el equipo Code Butchers (carniceros de código) #237
![logo para el equipo code butchers carniceros de codigo 237_issue_1](https://cloud.githubusercontent.com/assets/15186093/10922776/5bac4be4-824f-11e5-9ca7-28499ab1ab22.jpg)

**Comment by Luis-Fernando-Molina** [comment]
no es un icono, asi que puede y debe ser mas grande :smile:

**Comment by MelissaDugarte** [comment]
:+1:  perfecto lei mal jeje

**Comment by leonacostaok** [comment]
Preferiría que sea más bien un cuchillo de carnicero y que tenga algún juego con los tags html o palabras reservadas de java/android y sangre, obvio. El rojo me copa.
<image src="http://www.stu711.com/images/MEAT-CLEVER.jpg"/>
<image src="http://uxrepo.com/static/icon-sets/font-awesome/svg/code.svg"/>

**Comment by MelissaDugarte** [comment]
@arnaldos @lnacosta

Versión 2 Logo para el equipo Code Butchers (carniceros de código) #237
![logo para el equipo code butchers carniceros de codigo 237_issue_1](https://cloud.githubusercontent.com/assets/15186093/10945407/81cc7a24-82ef-11e5-9241-8751b9d97ca0.jpg)

**Comment by victoralfonzohd** [comment]
@Luis-Fernando-Molina @arnaldos @lnacosta Propuesta de logo Code Butchers

![sin-titulo-2](https://github-cloud.s3.amazonaws.com/assets%2F15219855%2F10957585%2Fefcbfa16-8337-11e5-8362-3b5f57317b2e.png)

**Comment by leonacostaok** [comment]
@victoralfonzohd me fascinó tu propuesta!! podrías probar cambiando las palabras de atrás por lo que se ve acá? [Link](http://docs.oracle.com/javase/tutorial/java/nutsandbolts/_keywords.html) y con unos <code>for(int i = 0 ; i < list.size() ; i++) </code> y <code>while(true){}</code>

Y capaz algunas gotas de sangre desparramadas, vos sabrás mejor que yo como hacer para que quede equilibrado!

**Comment by victoralfonzohd** [comment]
@lnacosta Intente desparramar mas la sangre pero se perdía un poco el trabajo del fondo con los códigos, por lo que pensé en ensangrentar la tipografía, y agregue un par de gotas de sangre caidas

![logo-carniceros-de-codigo](https://cloud.githubusercontent.com/assets/15219855/10959086/bc5c6706-8346-11e5-8eec-97331d841538.png)

**Comment by leonacostaok** [comment]
@victoralfonzohd siento como que la imágen está muy cargada del lado derecho, no quedaron muy bien las gotas que caen. 
El efecto en la tipografía está genial, de fondo tratá de lograr el mismo efecto que habías hecho antes y usá el mismo color por favor para todas las letras (que queda tipo matrix y está bueno el fecto).
Podrías probar como queda (es horrible lo que estoy diciendo jajaja) pero un derramamiento de sangre en el sector izquierdo del círculo, como apenas viniendo del lado superior?

**Comment by Luis-Fernando-Molina** [comment]
No quedaria mejor la parte roja de las letras abajo? como que se va llenando de sangre? 

Otra cosa, fijate que el nombre sea lo suficientemenete grande como para que se vea cuando todo se achique mucho. En lo posible usá la proporción del logo de fermat de la palabra al grafico.

**Comment by victoralfonzohd** [comment]
@Luis-Fernando-Molina @Inacsota  Adjunto 4 imágenes, todas tienen en común: Corrección en el tamaño del texto y corrección del fondo.. Son pruebas: con o sin el detalle del derramamiento de sangre del lado izquierdo, y la tipografía llena de sangre en ambas direcciones de arriba hacia abajo y al contrario.

![logo-carniceros-de-codigo](https://cloud.githubusercontent.com/assets/15219855/10975391/df094a18-83b8-11e5-8152-25be0d27648d.png)

Versión 1

![logo-carniceros-de-codigo1](https://cloud.githubusercontent.com/assets/15219855/10975577/dd140fb2-83b9-11e5-9e0e-429d06dcd3c7.png)

Versión 2

![logo-carniceros-de-codigo2](https://cloud.githubusercontent.com/assets/15219855/10975591/f0f99ad8-83b9-11e5-8fe2-10bb780a0ae8.png)

Versión 3 

![logo-carniceros-de-codigo3](https://cloud.githubusercontent.com/assets/15219855/10975600/f970e180-83b9-11e5-87b2-9b746890df5f.png)

Versión 4

![logo-carniceros-de-codigo4](https://cloud.githubusercontent.com/assets/15219855/10975606/01f106aa-83ba-11e5-9e01-014b5fb531c5.png)

**Comment by Luis-Fernando-Molina** [comment]
se perdio el codigo en blanco que le habias puesto antes.

Que elija @lnacosta

**Comment by victoralfonzohd** [comment]
@Luis-Fernando-Molina Si, @lnacosta me pidió usar un solo color en el texto del fondo.

**Comment by arnaldos** [comment]
@bitDubai/graphic-design-selection los invito a participar en este issue, creación del Logo para el equipo Code Butchers :smile:

**Comment by jpcrear** [comment]
![code butchers](https://cloud.githubusercontent.com/assets/14338086/10999757/01688044-8470-11e5-9488-f04b4ed777fb.jpg)
Soy nuevo por aquí... Saludos a todos...

**Comment by leonacostaok** [comment]
@victoralfonzohd te pido por favor que pruebes con dos últimas modificaciones, me gusta el 1, pero a la letra del nombre ponele dos tonalidades de rojo, no el gris y el rojo a la vez, y el derramamiento de sangre hacéselo un poco más a la izquierda o sea como que casi pise el borde del logo

**Comment by victoralfonzohd** [comment]
@lnacosta Modificaciones

![logo-carniceros-de-codigo](https://cloud.githubusercontent.com/assets/15219855/11037743/940cfaca-86d1-11e5-8632-0e3c2d02b28e.png)

**Comment by ilustravida** [comment]
![cazadores-de-codigo-logo](https://cloud.githubusercontent.com/assets/15271510/11048532/9fce7440-870a-11e5-84fa-0277b48269eb.jpg)

Hola! tambien soy nueva por aca, yo lo asocie a un equipo intimidante

**Comment by jpcrear** [comment]
No ntiendo..

**Comment by jpcrear** [comment]
Podria nviarme oteo correo y explicarme fuera de este para ntender como se
trabaja x aqui x favor

**Comment by victoralfonzohd** [comment]
@lnacosta Como vamos con las modificaciones?

![logo-carniceros-de-codigo](https://cloud.githubusercontent.com/assets/15219855/11105884/3314eb68-88a4-11e5-975c-06ecff87958e.png)

**Comment by arnaldos** [comment]
@lnacosta comparto una versión para el logo espero les guste 

Versión 9

![logo-code-butchers](https://cloud.githubusercontent.com/assets/13594347/11162737/e911c7d6-8a81-11e5-8245-e0bedd87d39e.png)

**Comment by ivonnesantos** [comment]
@emely-puerta este ya esta mas adelantado ve que puedes aportar aqui

**Comment by jonathanborges3d** [comment]
@arnaldos Hola, tiene éste logo un definitivo? creo que es el único que falta para agregar a la página web.

**Comment by arnaldos** [comment]
@jonathanborges3d aun no, @lnacosta quiere cambiar el concepto inicial me voy a re unir con el y luego te aviso

**Comment by proseuz** [comment]
Buenas noches chicos estas son mis propuestas @lnacosta @arnaldos @emmysm 
Propuesta 1
![logo2](https://cloud.githubusercontent.com/assets/17308060/14695532/c40c3a4c-073c-11e6-9af8-78abdc7c01c7.jpg)

Propuesta2
![logo1-01](https://cloud.githubusercontent.com/assets/17308060/14695533/c44cf2e4-073c-11e6-9323-4c47dd67b6a4.jpg)

Propuesta 3
![logo3-01](https://cloud.githubusercontent.com/assets/17308060/14695719/9d5edcc2-073e-11e6-9a91-49699b15cf39.jpg)

PD: las estrellas de fondo que sugirió @lnacosta no funcionan debido a que de por si el diseño es bastante complejo y termina sobrecargandolo

**Comment by emmysm** [comment]
Propuesta 3, con stroke blanco en la tipografía @jhonmarquez92

**Comment by proseuz** [comment]
propuesta 3  con el stroke sugerido por @emmysm 
@arnaldos @inacosta 
![logo4-01](https://cloud.githubusercontent.com/assets/17308060/14725213/6cc3345e-07e4-11e6-83bc-2b6635ae3a52.jpg)

**Comment by proseuz** [comment]
@arnaldos @arnaldos @lnacosta 
4
![logo 6](https://cloud.githubusercontent.com/assets/17308060/14728830/2dee2c70-0802-11e6-953f-031241291d25.jpg)
5
![logo 7](https://cloud.githubusercontent.com/assets/17308060/14728831/2dfc3054-0802-11e6-8fe4-1f799904731e.jpg)
6
![logo 5](https://cloud.githubusercontent.com/assets/17308060/14728832/2e1fd158-0802-11e6-8249-8b5b502340e9.jpg)

**Comment by emmysm** [comment]
@jhonmarquez92  @jonathanborges3d versión 4

**Comment by arnaldos** [comment]
@emmysm @jhonmarquez92 de acuerdo la versión 4. solo quisiera probar algo antes de que @jonathanborges3d haga el 3D @jhonmarquez92 sube el texto un poco y aumenta el tamaño para que quede lo mas centrado a la hoja.

**Comment by jonathanborges3d** [comment]
@arnaldos @jhonmarquez92 Está chévere el logo muchachos pero quisiera que tomaran en cuenta que al llevar el logo a una moneda debe poder colocarse dentro de un círculo al igual que los demás. Por otro lado, les recuerdo que al hacer la conversión a modelo 3D, detalles como los trazos de púrpura sobre el cyan no se notarán, al igual que los degradados y efectos de volumen del texto porque sólo dispongo de 3 materiales básicos para texturizar la moneda (común en todas las monedas de los equipos): Oro, plata y cobre.

**Comment by proseuz** [comment]
@arnaldos @emmysm @lnacosta   la primera es la **máxima expresión** del logo y la segunda es la **versión simplificada** 

![logo6](https://cloud.githubusercontent.com/assets/17308060/14926676/11c32760-0e17-11e6-81df-868bca8bc573.jpg)

@jonathanborges3d la tercera es la **versión plana** para la moneda
![logo plano monda](https://cloud.githubusercontent.com/assets/17308060/14926443/0f715ce4-0e16-11e6-8343-ef19c258bdf1.jpg)

**Comment by emmysm** [comment]
@jonathanborges3d sirve así? @lnacosta qué opinas? :)

**Comment by leonacostaok** [comment]
@emmysm I like the new design. Please continue.

**Comment by jonathanborges3d** [comment]
@emmysm Si, así puede ser, :+1:

**Comment by karentvillegas** [comment]
@jhonmarquez92 @emmysm @Inacosta @arnaldos Propuestas para el banner del team Purple Haze

1
![propuesta1](https://cloud.githubusercontent.com/assets/19273211/15169792/13400be4-1709-11e6-9ab3-afc37f0d1c25.png)
2
![propuesta2](https://cloud.githubusercontent.com/assets/19273211/15169798/20402d56-1709-11e6-9548-2c24011e2105.png)
3
![propuesta3](https://cloud.githubusercontent.com/assets/19273211/15169804/29e00994-1709-11e6-9c75-04f518001b4e.png)

**Comment by emmysm** [comment]
@karentvillegas  woow, me encanta el primero. Yo ampliaría el logo y solo dejaría el background, sin los elementos que están a los lados. Qué opinas, @lnacosta? @jhonmarquez92

**Comment by proseuz** [comment]
totalmente, el logo más grande @karentvillegas

**Comment by leonacostaok** [comment]
@emmysm could you try with green color in the things of the background?

**Comment by karentvillegas** [comment]
@jhonmarquez92 @emmysm @Inacosta @arnaldos proposal whith color green
4
![propuesta4](https://cloud.githubusercontent.com/assets/19273211/15202051/a8eb4840-17c0-11e6-9b5f-f2508af1ba0e.png)
5
![propuesta5](https://cloud.githubusercontent.com/assets/19273211/15202054/ad3c6898-17c0-11e6-8eaf-d757ec7d0892.png)
6
![propuesta6](https://cloud.githubusercontent.com/assets/19273211/15202057/b08f9c22-17c0-11e6-9d16-c74dc071dbe9.png)
7
![propuesta7](https://cloud.githubusercontent.com/assets/19273211/15202060/b9930f8e-17c0-11e6-8822-8cc95564c4a8.png)
8
![propuesta8](https://cloud.githubusercontent.com/assets/19273211/15202066/be3f2194-17c0-11e6-810a-093d51b82115.png)
9
![propuesta9](https://cloud.githubusercontent.com/assets/19273211/15202068/c1983d62-17c0-11e6-9d65-3a7c04aefddc.png)

**Comment by proseuz** [comment]
El número 5 me parece que está genial, pero le pondría  la sombra negra  más amplia y simétrica  por todos lados. que opinan? @arnaldos @emmysm @lnacosta

**Comment by emmysm** [comment]
Me gusta bastante el 5 @jhonmarquez92 .

**Comment by jonathanborges3d** [comment]
@Fermat-ORG/code-butchers-team  @arnaldos @emmysm 

Primera versión 3D
![purple_1](https://cloud.githubusercontent.com/assets/13649739/15343396/1af8715c-1c66-11e6-9945-6ae1bec6a6b0.jpg)

**Comment by jonathanborges3d** [comment]
Tuve que colocar el logo un poco desplazado hacia abajo y fuera del borde porque dentro no se notaba el nombre y no quedaría bien repetirlo en el lugar que ocupan ahora las estrellas.

**Comment by proseuz** [comment]
a mi me gusta mucho

**Comment by emmysm** [comment]
woow. me encanta :clap: @jonathanborges3d

**Comment by leonacostaok** [comment]
@jonathanborges3d @emmysm WOW nice.
