### ISSUE TITLE
Logo para el equipo de Miguel (Fermat.org Charlie)

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#238]
@Miguelcldn, en este issue haremos el briefing y discutiremos brevemente cómo quisieran representar su equipo, este logo será utilizado inicialmente en las portadas de las reuniones.

Pueden participarle a los demás miembros del equipo.

**Comment by Miguelcldn** [comment]
Equipo @bitDubai/fermat-org-team 

PD: Si necesitas hablar con todos o quien sea del equipo de fermar.org puedes mencionarnos como sale así, nos saldrá la mención a todos los miembros del equipo :+1:

**Comment by arnaldos** [comment]
vale miguel @Miguelcldn :+1:

**Comment by Luis-Fernando-Molina** [comment]
Miguel, despues pasame el Nombre así ajusto el nombre del equipo en Github

**Comment by arnaldos** [comment]
@Miguelcldn que han pensado para este caso, tienen algún nombre ?

**Comment by Miguelcldn** [comment]
Estamos hablando los miembros del equipo cliente - servidor a ver si ponemos uno parecido en ambos, porque ví que hay un issue aparte para el equipo de @fuelusumar

**Comment by arnaldos** [comment]
@Miguelcldn si cree un caso porque tengo entendido que son dos equipos distintos, si no es así avisame y cierro el caso. y nos quedamos trabajando en este.

**Comment by Miguelcldn** [comment]
Los nombres de los equipos ya están decididos:

| Equipo | Nombre |
| --- | --- |
| fermat.org - Cliente | Fermat.org Charlie |
| fermat.org - Servidor | Fermat.org Sierra |

**Comment by arnaldos** [comment]
@Miguelcldn cual equipo es el tuyo y cual es el de luis ?

**Comment by ricardo460** [comment]
@Miguelcldn esta a cargo de Fermat.org Charlie(fermat.org - Cliente) y luis de Fermat.org Sierra(fermat.org - Servidor). @arnaldos

**Comment by arnaldos** [comment]
perfecto, gracias @ricardo460  !!!

**Comment by victoralfonzohd** [comment]
@Miguelcldn @fuelusumar Que tal? Ya tienen idea de como quieren representar el logotipo para sus equipos?

**Comment by ivonnesantos** [comment]
@bitDubai/fermat-org-team @Miguelcldn dejaré a @emely-puerta encargada de esto para ver si cerramos Aquí emely vas a postear el logo de Charlie el grupo encargado de la web public deberías hacer algo relacionado con eso para que lo ubiquemos con facilidad cuando necesitemos de ellos =) , este logo es la representación visual de cada equipo developer que compone fermat este trabajo en particular te lo deben aprobar los integrantes de grupo. 
Si alguien tiene alguna acotacion en particular color forma estilo puede plantearla lo mas pronto posible.

**Comment by Miguelcldn** [comment]
Sludos @emely-puerta, nosotros actualmente nos renombramos como _Navi_ porque somos los encargados de la _navegación_ de la plataforma. Así que nos gustaría que el logo me gustaría que reflejara eso. Igualmente _Navi_ se separa en dos sub-equipos primordiales: _Charlie_ (los que programamos el 3D que se ve en la página) y _Sierra_ (Los que programan el servidor que nos surte la información). Sobre colores a mí me gusta el azul trueno (también los grises pero para esto me parecería un tanto muerto) y sería bien que Sierra tenga un color rojo, que es complementario del azul aunque no se si @fuelusumar quiera participar y elegir algún otro ^_^

**Comment by emely-puerta** [comment]
Buenas chicos, acá les dejo algo de lo que he realizado... @Miguelcldn @ivonnesantos 
![sierra](https://cloud.githubusercontent.com/assets/17557647/13801767/61b513ce-eb07-11e5-98d3-85aa9b073c62.jpg)

**Comment by Miguelcldn** [comment]
@emely-puerta me gustaría que tomara más énfasis en "Navegación" que en "cliente <-> servidor". Como en las películas futuristas que tienen una inteligencia artificial en las naves espaciales para ayudar en la navegación, pero esta navegación es en el cyber-espacio. No se si estoy siendo muy complicado :sweat_smile:

**Comment by arnaldos** [comment]
@jayborges por favor toma este caso quedo abandonado ! lo necesitamos con suma urgencia

**Comment by JefersonBorgesS** [comment]
![logo charlie-02](https://cloud.githubusercontent.com/assets/17457984/14504206/9f970d50-017d-11e6-9030-2cc66c431a7b.jpg)

![logo charlie-03](https://cloud.githubusercontent.com/assets/17457984/14504207/9f9a7b84-017d-11e6-9b2c-3d9e922ce36c.jpg)

![logo charlie-01](https://cloud.githubusercontent.com/assets/17457984/14504208/9fa05022-017d-11e6-8955-87abe5b61c13.jpg)

**Comment by Miguelcldn** [comment]
Me gusta la primera pero me causa ruido ver la C inclinada hacia abajo, sobre todo por la parte de arriba de la apertura

**Comment by JefersonBorgesS** [comment]
![logo charlie2-02](https://cloud.githubusercontent.com/assets/17457984/14511299/4bc1a1c2-01a0-11e6-9d60-1fd839f901e2.jpg)

**Comment by Miguelcldn** [comment]
Chévere, se queda :+1:

**Comment by arnaldos** [comment]
@jayborges plz sube los archivos de la ultima version al repo para que @jonathanborges3d  haga los renders de las monedas

**Comment by arnaldos** [comment]
@Miguelcldn @jonathanborges3d  avísame si como va esto?
