### ISSUE TITLE
Intra User Community App Design / Your Connections

### ISSUE THREAD

**Issue by Neoperol** [bitDubai/fermat-graphic-design#239]
#209

@Luda16 

Lista de las personas con las que estas conectadas, las acciones en esta vista es poder entrar en el detalle del usuario que ya estas conectado. 

![view_friend_list](https://cloud.githubusercontent.com/assets/6201081/10778565/b9fc4e0c-7cf9-11e5-8fc7-507a47d6feec.jpg)

**Comment by Luis-Fernando-Molina** [comment]
:+1:

**Comment by Neoperol** [comment]
@furszy 
@josemanueldsds

**Comment by Neoperol** [comment]
Cambio en la vista de la Lista de las conexiones. 

Background:  #010c12

```
Element List

    Normal
    Divider: #e0e2e1
    Name: 16sp #0173ba
    Text: 16sp #ffffff
    Image
        Border: #030e14
        width: 40dp
        height: 40dp
```

![view_friend_list](https://cloud.githubusercontent.com/assets/6201081/11861722/165631c2-a455-11e5-9171-aba3995d396f.jpg)

@Luis-Fernando-Molina 
@josemanueldsds

**Comment by Luis-Fernando-Molina** [comment]
Porque en la misma app una pantalla tiene fondo negro y otra gris??

**Comment by Luis-Fernando-Molina** [comment]
ahhh ahora lo dejaste todo negro, ok

**Comment by Neoperol** [comment]
@Luis-Fernando-Molina 

Si me dijeron que igualara los fondos. Si falta algun dato para pintar la vista me avisan.

@josemanueldsds
