### ISSUE TITLE
Intra User Community App Design / Connection Detail

### ISSUE THREAD

**Issue by Neoperol** [bitDubai/fermat-graphic-design#240]
#209

@Luda16 

Vista de detalle de un usuario con el cual estas conectado. La acción en esta vista es poder desconectarte del usuario y poder ver la información extra de dicho usuario. 

![view_other_profile](https://cloud.githubusercontent.com/assets/6201081/10778637/521fc380-7cfa-11e5-9587-8a8265de7b53.jpg)

Vista sin imagen del usuario. 

![view_other_profile_no_image](https://cloud.githubusercontent.com/assets/6201081/10778638/52af401e-7cfa-11e5-998f-2fed7b9c9a3d.jpg)

**Comment by Luis-Fernando-Molina** [comment]
Y como te desconectas? Tocando que cosa?

**Comment by Neoperol** [comment]
> Y como te desconectas? Tocando que cosa?

El mismo botón, tiene dos estados dependiendo si estas conectado con esa persona, si no estas conectado lo que hace es enviar el connect request al otro usuario y si ya estas conectado a esa persona se abre un dialog para verificar que realmente quieres dejar de estar conectado con esa persona. 

Estado Sin conexión. 
![view_other_profile_without_connect](https://cloud.githubusercontent.com/assets/6201081/10795908/0ab86898-7d6e-11e5-840d-3225ad79eafe.jpg)

Estado Conectado. 

![view_other_profile_no_image](https://cloud.githubusercontent.com/assets/6201081/10795929/214ca7ea-7d6e-11e5-9823-2e2cec115277.jpg)

Presionando el boton conectados. 

![view_other_profile_dialog](https://cloud.githubusercontent.com/assets/6201081/10795958/419fbe42-7d6e-11e5-85a7-64836e191de1.jpg)

**Comment by Luis-Fernando-Molina** [comment]
> El mismo botón, tiene dos estados dependiendo si estas conectado con esa persona, si no estas conectado lo que hace es enviar el connect request al otro usuario y si ya estas conectado a esa persona se abre un dialog para verificar que realmente quieres dejar de estar conectado con esa persona. 

Cuando el boton dice CONNECTED no hay nada que me haga pensar que tocandolo me voy a desconectar. 

Me parece que se está mezclando un ESTADO con una ACCION. 

Fuera de eso las pantallas se ven bonitas

**Comment by furszy** [comment]
Me gustó la pantalla, cierrenla que ya la quiero hacer :+1:

**Comment by Neoperol** [comment]
> Cuando el boton dice CONNECTED no hay nada que me haga pensar que tocandolo me voy a desconectar.
> 
> Me parece que se está mezclando un ESTADO con una ACCION.

Te explico, los estados son del boton, que cambian de color y el texto dependiendo si estas conectado a ese usuario o no. Este boton en sus dos estados tienen acciones en relacion a los mismos solo que una tiene un proceso de verificacion. 

Connect - El Usuario 1 envia la solicitud de para conectarse con el usuario 2. 

Connected - El Usuario 1 ya esta conectado al Usuario 2, si presiona el boton el dialog aparece para verificar si esa es la accion que quiere hacer el usuario 1, que es desconectarse del Usuario 2. 

Podemos cambiar los nombres de conectarse y conectado, por seguir y seguido o follow y unfollow. Pero el funcionamiento es el mismo como en muchas otras redes sociales.

**Comment by Luis-Fernando-Molina** [comment]
en este caso seria entonce Connect y Disconnect :+1:

**Comment by Neoperol** [comment]
Vista de botones disables. 

Button.
 Text Color: #ffffff
 Background: #828688

![view_other_profile_rejected](https://cloud.githubusercontent.com/assets/6201081/11861550/bb541e48-a453-11e5-842d-86b8d66c811e.jpg)
![view_other_profile_waiting_respond](https://cloud.githubusercontent.com/assets/6201081/11861549/ba65e3e0-a453-11e5-9db9-bc79e10c8776.jpg)

@Luis-Fernando-Molina 
@josemanueldsds

**Comment by Luis-Fernando-Molina** [comment]
El texto es "Connection Request Sent" o "Request Sent"

**Comment by Neoperol** [comment]
El corto mejor "Request Sent"
@Luis-Fernando-Molina 
@josemanueldsds 

![view_other_profile_waiting_respond](https://cloud.githubusercontent.com/assets/6201081/11889442/6904fafe-a51b-11e5-8464-3df84005c60d.jpg)
