### ISSUE TITLE
SUPER ISSUE: Broker Wallet Wireframe and Design

### ISSUE THREAD

**Issue by Neoperol** [bitDubai/fermat-graphic-design#242]
En desarrollo el wireframe del Broker Wallet. 

Home, donde se manejan las negociaciones y los contratos. 
Contract History, donde se pueden ver los contratos en sus diferentes estados.
Settings, donde se maneja la configuración de Location, Bank Accounts, Stock Managment y Public Information. 

La acción principal que hace el usario después de enlazar su Identity a la wallet es recibir negociaciones de los Customers que se han enlazado con el en la Broker Community Sup APP y manejar dichas negociaciones interactuando con el customer y modificando las clauslas correspondiente a cada tipo de negociación.

https://ninjamock.com/s/TFL1T

@Luis-Fernando-Molina 
@jorgeejgonzalez

**Comment by Luis-Fernando-Molina** [comment]
Los Mock ups debieramos verlos en reunion. Cuando me convoquen, voy.
