### ISSUE TITLE
Broker Wallet Wireframe Design / Home Negotiation tab view Design

### ISSUE THREAD

**Issue by Neoperol** [bitDubai/fermat-graphic-design#243]
#242

Propuesta para la vista principal de la Broker Wallet.

En esta vista, el Broker puede interactuar con las Negociaciones y Contractos activos. 
Ver el Market Exchange rate de las mercancía en la cual este interesado. Con valores que y un gráfico que falta por definir. 
Ver el Stock de cada Mercancía que tiene enlazada a esta Wallet. 

![view_home](https://cloud.githubusercontent.com/assets/6201081/10803515/c4c3c086-7d94-11e5-9929-c265fb501bd5.jpg)

@jorgeejgonzalez

**Comment by nelsonalfo** [comment]
El diseño me gusta mucho, pero tengo algunos dudas y sugerencias
1. Como es eso de "Buying 2.000 USD - 212USD @ 1.1 BTC"? Entiendo que "Buying 2.000 USD" es cuanta mercancía va a comprar el Customer y que "212 USD @ 1.1 BTC" es a cuanto esta vendiendo la mercancía el Broker, pero no debería ser por ejemplo: "Buying 2.000 USD - 1 USD @ 1.1 BTC"? es decir, que cada dolar lo estas vendiendo a 1.1BTC
2. Propongo que la gráfica de Marker Exchange Rate sea un gráfico de barras sencillo, donde se muestre el valor de cierre de los últimos 7 días y que cuando pulses alguna de las barras te aparezca el valor de la misma sobre dicha barra.
3. Seria bueno tener también la pantalla del Home pero mostrando esta vez la pestaña de contratos, para saber que colores van a tener los items de la lista y la información que se va a mostrar en esa lista

**Comment by Luis-Fernando-Molina** [comment]
@Neoperol al gráfico le faltan los días y la barra del target y otras cosas que ya hemos hablado varias veces.  :-1: 

Cuando tenga todo lo que ya hablamos, avisame y lo reviso.

En general se ve muy bonito. :smile:

**Comment by Neoperol** [comment]
> Como es eso de "Buying 2.000 USD - 212USD @ 1.1 BTC"? Entiendo que "Buying 2.000 USD" es cuanta mercancía va a comprar el Customer y que "212 USD @ 1.1 BTC" es a cuanto esta vendiendo la mercancía el Broker, pero no debería ser por ejemplo: "Buying 2.000 USD - 1 USD @ 1.1 BTC"? es decir, que cada dolar lo estas vendiendo a 1.1BTC}

Esto lo hablamos ayer, a pesar que tanto customer y broker compran y vende, debemos estandarizar las listas. Los customers compran debido a que ellos comienzan la operación y buscan entre la lista de broker la mercancia que quieren cambiar, mientras que los Brokers venden. 

> Propongo que la gráfica de Marker Exchange Rate sea un gráfico de barras sencillo, donde se muestre el valor de cierre de los últimos 7 días y que cuando pulses alguna de las barras te aparezca el valor de la misma sobre dicha barra.
> 
> @Neoperol al gráfico le faltan los días y la barra del target y otras cosas que ya hemos hablado varias veces.  :-1:

Para aclarar, el gráfico que tiene los indicadores como Target y Limit es el gráfico del Broker Stock. 
Este gráfico debe mostrar el valor de X mercancía con su valor a la compra y la venta. Solo debemos determinar cuantos días debemos mostrar y si el usuario puede ir mas atrás en el tiempo además de esos días que le estamos mostrando. A la final en una negociación tanto el broker como el customer van a tomar la decisión del exchange rate con las referencias del día actual, los días anteriores debe verlo para saber si ese precio a variado mucho en los últimos días. 

En un rato subo la vista actualizada. 

@Luis-Fernando-Molina 
@jorgeejgonzalez

**Comment by Luis-Fernando-Molina** [comment]
> Para aclarar, el gráfico que tiene los indicadores como Target y Limit es el gráfico del Broker Stock. 

ahhhhhhhhhhhhh tenes razón. 

Si querés ver como se muestra normalmente el precio de mercado mira: http://www.coindesk.com/

**Comment by Neoperol** [comment]
Lo que pediste Nelson. 

Vista de la Negociación, haciendo la diagramación de la lista de contratos cambie la organización de la lista en el Contrato el Customer debe ser el primero en enviar la Mercancía, además en la lista se muestra la forma en que se hace la entrega para poder diferenciar un contrato de otro. El waiting for you en los contratos esta como ultimo paso para cerrar el Contrato. 

![view_home_contracts](https://cloud.githubusercontent.com/assets/6201081/10837567/17bc9364-7e8d-11e5-8d88-376e510f5d1c.jpg)

El gráfico muestra los últimos 7 días y si se presiona sobre un día se puede ver la información sobre ese día. 

![view_home_negotiations](https://cloud.githubusercontent.com/assets/6201081/10837590/6a3d53bc-7e8d-11e5-8689-28e501940969.jpg)

**Comment by Neoperol** [comment]
Propuesta para la vista de home con el tab de negociaciones desplegados.
El gráfico se cambio. 

![view_home_negotiations](https://cloud.githubusercontent.com/assets/6201081/10908986/e6bf5b60-8207-11e5-9886-c8c49dbfff24.jpg)

@Luis-Fernando-Molina

**Comment by Luis-Fernando-Molina** [comment]
:+1:

**Comment by nelsonalfo** [comment]
:+1:

**Comment by nelsonalfo** [comment]
considero que se puede cerrar este Issue

**Comment by nelsonalfo** [comment]
@Neoperol necesito los colores de la sección que muestra el Market Exchange Rate, o no se si se hace un Issue aparte para dicha seccion del home
