### ISSUE TITLE
Wallpaper para el desktop la Bitcoin Wallet

### ISSUE THREAD

**Issue by m471c4** [bitDubai/fermat-graphic-design#248]
Se deben generar las diferentes versiones a partir del arte creado para el wallpaper (que se encuentra actualmente en formato 2560x1440). Los formatos requeridos son:

2880x1800px
1920x1200px
1680x1050px

**Comment by arnaldos** [comment]
este issues solo pertenece a @m471c4

**Comment by m471c4** [comment]
Se realizaron ajustes para adecuar el arte al formato 2880x1800 (del cual se desprenden los de 1920x1200 y 1680x1050); ya que redimensionar el original implicaría perder elementos del diseño. A continuación se puede ver el original y la versión nueva, ya @furszy y @Neoperol tienen los archivos en png y se estarán subiendo al repositorio los editables.

Original (con la paleta de colores nueva):
![wallpaper1](https://cloud.githubusercontent.com/assets/13468350/10825448/3abe24aa-7e37-11e5-813e-944c6635c508.png)

Versión 2880x1800:
![wallpaper2](https://cloud.githubusercontent.com/assets/13468350/10825457/4234809e-7e37-11e5-8a72-c3a588c86778.png)
