### ISSUE TITLE
Mejorar la diagramación de la lámina: Solution / Product

### ISSUE THREAD

**Issue by m471c4** [bitDubai/fermat-graphic-design#25]
Viene del #12 

Esta lámina se puede mejorar con ayuda de la retícula (propuesta en el issue #24) para evitar que se vea como ese gran y pesado bloque de texto que no facilita la lectura.

![screen2](https://cloud.githubusercontent.com/assets/13468350/9099577/aac93a98-3b9b-11e5-9f0c-6214c192a0d0.png)

**Comment by Luis-Fernando-Molina** [comment]
:+1:
