### ISSUE TITLE
Crypto Customer Wallet Design / Navigation Drawer

### ISSUE THREAD

**Issue by Neoperol** [bitDubai/fermat-graphic-design#251]
#218

Diseñar la vista del Navigation Drawer para la Customer Wallet, tomando los colores aprobados en la vista de home como referencia. 

![menu](https://cloud.githubusercontent.com/assets/6201081/10850676/245ded68-7ef9-11e5-83bc-c4de9fd88fd5.png)

**Comment by arnaldos** [comment]
@nelsonalfo @gregory @Luis-Fernando-Molina propuesta para **Crypto Customer Wallet Design / Navigation Drawer**

![view_navigation](https://cloud.githubusercontent.com/assets/13594347/11314865/3254cdfa-8fbc-11e5-8321-35ff48b68924.jpg)

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina @Neoperol  @furszy ajustes del drawer 

Versión 2

![view_navigation2](https://cloud.githubusercontent.com/assets/13594347/11316584/2f8077be-8fdf-11e5-8948-bfa00ff07d70.jpg)

**Comment by Luis-Fernando-Molina** [comment]
@arnaldos este es un caso de @Neoperol que se cierra cuando termina su trabajo e impacta en sus estadísticas personales. La discución debe seguir en un caso de diseño gráfico que impacte en las estadísticas de quien sea el responsable no de @Neoperol que su trabajo es definir la experiencia de usuario. Entiendo que te puede parecer lógico que siga acá pero rompe los esquemas administrativos. Con un link desde tu caso a este para indicar de donde proviene alcanza para que cualquiera que lo lea pueda seguirlo e informarse. Si lo que necesitas es que @Neoperol participe, tagealo en tu caso y el va a verlo y participar. Por favor sigamos donde estábamos y aplica este concepto en el resto de los casos. Gracias.

**Comment by arnaldos** [comment]
Te entiendo perfectamente @Luis-Fernando-Molina pero coloque el caso aquí ya que previamente @Neoperol conversamos y me oriento a colocar la pieza acá para ser discutida. pero ya mismo creo un caso nuevo y lo muevo para ese que va hacer creado. y aplicare el mismo método para resto de los casos. :+1:
