### ISSUE TITLE
Crypto Customer Wallet Design / Home Contract Tab view Design

### ISSUE THREAD

**Issue by Neoperol** [bitDubai/fermat-graphic-design#254]
#218

@nelsonalfo 

Diseñar la vista de Home cuando se abre el Tab Contract. 

![contracts tab](https://cloud.githubusercontent.com/assets/6201081/10851091/6a4b6a9c-7efb-11e5-9893-2671f68e08c6.png)

**Comment by nelsonalfo** [comment]
@Neoperol necesito el diseño de esta pantalla para poder seguir adelantando
