### ISSUE TITLE
Crypto Customer Wallet Design / Broker List view Design

### ISSUE THREAD

**Issue by Neoperol** [bitDubai/fermat-graphic-design#256]
#218

@nelsonalfo 

Diseñar la vista de broker list, esta lista se llena dependiendo de los Brokers que se han enlazado en la Broker Community y la mercancia que el customer quiere operar. Además de mostrar el ordenamiento de la lista. 

![broker list](https://cloud.githubusercontent.com/assets/6201081/10851230/14f535d6-7efc-11e5-8061-eb9309f325a0.png)

![broker sort](https://cloud.githubusercontent.com/assets/6201081/10851237/23a7939e-7efc-11e5-8bc6-e2443e32a222.png)

**Comment by nelsonalfo** [comment]
@Neoperol necesito el diseño de esta pantalla para poder seguir adelantando en esta wallet

**Comment by Neoperol** [comment]
![view_broker_list_002](https://cloud.githubusercontent.com/assets/6201081/11367010/0da75972-9283-11e5-99d4-81e449c28356.jpg)

@nelsonalfo

**Comment by nelsonalfo** [comment]
voy a trabajar con este diseño hasta que se le de el :+1: definitivo

**Comment by nelsonalfo** [comment]
Ya entrando en detalle, el broker no indica cuanta cantidad de mercancia que va a vender, sino solo la mercancia que vende.

**Comment by nelsonalfo** [comment]
@Luis-Fernando-Molina que te parece esta propuesta?

**Comment by nelsonalfo** [comment]
esa barra verde que se ve en los items es una lista horizontal scrolleable que indica las tasas de cambio de la mercancia que vende el broker en las diferentes monedas que acepta como pago

**Comment by nelsonalfo** [comment]
yo voy a tomar el tamaño de las imágenes y de los textos que usamos en las otras listas como base

**Comment by Luis-Fernando-Molina** [comment]
1-Yo prefiero un banner para la identidad del broker, no una fotito redonda.
2-En la barra con info del mercado yo pondria:

USD/BTC: 322.43  VEN/USD: 870 . 

3-Separaria en la lista cada record como una tarjetita para que no haya confusión si el precio pertenece al broker de arriba o al ade abajo.

**Comment by Neoperol** [comment]
@Luis-Fernando-Molina 

Tocara hacer el estilo tipo Card entonces, eso lo estabamos hablando Nelson y yo ayer. El problema que tiene el elemento de la lista es que no puede crecer verticalmente, si el Broker tiene mas 4 o mas exchange rates tenemos que hacer scroll horizonal sobre esos elementos. 
Tipo Google Play.

**Comment by Luis-Fernando-Molina** [comment]
> si el Broker tiene mas 4 o mas exchange rates tenemos que hacer scroll horizonal sobre esos elementos. 

suena bien.

**Comment by Neoperol** [comment]
@Luis-Fernando-Molina 
@nelsonalfo 

Esta esa la muestra con los elementos en cards. Espero observaciones. 
![view_broker_list_003](https://cloud.githubusercontent.com/assets/6201081/11382879/ae5e292e-92d6-11e5-8523-3d8c3705416a.jpg)

Y extendiendo la image. 

![view_broker_list_002](https://cloud.githubusercontent.com/assets/6201081/11382821/59753718-92d6-11e5-9a48-38d00d49c7f1.jpg)

**Comment by Luis-Fernando-Molina** [comment]
Esta mejor. El tema de Buying 400 USD no va porque en ese momento no se sabe lo que el cliente va a hacer. Las cotizaciones pudieran ir dentro de esa misma area de alguna forma.

**Comment by Neoperol** [comment]
@Luis-Fernando-Molina 

Las cotizaciones es el elemento que tiene scroll horizontal. Tienen que estar en un row solos para que el usuario pueda hacer slide si hay mas de 4. 

![view_broker_list_004](https://cloud.githubusercontent.com/assets/6201081/11382935/0016250a-92d7-11e5-9b95-de7fb94fb5f0.jpg)

**Comment by nelsonalfo** [comment]
Propongo que se parezca a algo como la siguiente imagen, donde se destaca la imagen de la marca:

![propuesta](https://cloud.githubusercontent.com/assets/1823627/11384506/8b56b7e6-92e2-11e5-95fc-b33c32472233.png)

O que los items tengan este estilo, solo que en nuestro caso no tendriamos un boton expandible, sino que alli tendriamos esa seccion donde vemos las contizaciones, es decir, la lista horizontal:

![prupuesta 2](https://cloud.githubusercontent.com/assets/1823627/11384638/9fa9bce2-92e3-11e5-8693-dd128943a3f3.png)

**Comment by Neoperol** [comment]
@nelsonalfo 

Pero con esa diagramacion entran muy pocos items en una pantalla, si hay 100 Brokers, cuanto scroll hay que hacer para poder llegar a los de abajo. Tecnicamente se le va dar solo prioridad a los primeros elementos de la lista.

**Comment by Neoperol** [comment]
@Luis-Fernando-Molina 
@nelsonalfo 

Por cierto para explicarte algo de la vista Luis, los exchange rates no se pueden mostrar ordenados verticalmente porque no se puede extender el tamaño vertical de los elementos de la lista, que Nelson te explique mejor el problema. 
Y en general dos cosas sobre la vista, para mi lo mejor es colocar la imagen o foto del Broker de un tamaño que no afecte el alto de la a Card, por varias razones, esta es la lista de Broker List, el usuario quiere seleccionar al broker con el cual quiere comenzar una negociación y eso va a estar determinado para la Mercancia que esta vendiendo y el Exchange rate, lo que hace que la foto sea totalmente irrelevante en comparación a los datos que realmente quiere consumir el usuario en está vista. Lo otro es como ya escribi en los comentarios superiores, entre mas grande es la foto hace que el item sea mas grande y sea mas complicado ver mas brokers. 

![view_broker_list_003](https://cloud.githubusercontent.com/assets/6201081/11386088/735bc114-92f0-11e5-8c35-880c2d72d979.jpg)

**Comment by Luis-Fernando-Molina** [comment]
> si hay 100 Brokers

el dia que haya 100 brokers cercanos al usuario yo voy a estar muy feliz.

El resto de lo que decis OK.

**Comment by nelsonalfo** [comment]
ya realicé una primera implementación de esta pantalla tomando como base la ultima propuesta de @Neoperol

**Comment by Neoperol** [comment]
@Luis-Fernando-Molina 
lol Tienes razón, pero siempre piensas en las tres cosas al ver la vista, si no items, si hay muchos y la opción optima. 

@nelsonalfo 
Igual me avisan si creen que hay que cambiar algo, Arnaldo esta pendiente de hacer las propuestas para las otras pantallas, para poder cerrar los casos mas rápidos.

**Comment by Luis-Fernando-Molina** [comment]
Por mi pudieramos dejarla asi en una version 1

**Comment by nelsonalfo** [comment]
por mi no hay problema tampoco. @Neoperol entonces pasame los colores y tamaños para el estilo de esta pantalla
