### ISSUE TITLE
Composición artística Nº1 con la moneda 3D Fiat Libra

### ISSUE THREAD

**Issue by jonathanborges3d** [bitDubai/fermat-graphic-design#257]
Viene del #182 

El concepto es un closeup de la moneda en un grupo mezclado de forma aleatoria

![alt text](https://raw.githubusercontent.com/bitDubai/fermat-graphic-design/45665e435b6ebbb67d55c52e6afd48212e8bb126/3D%20Design/3DArtScenes/FiatCoins/Fiat_pound_art_1.jpg?token=ANBHS1htEMsiQbo8lRDQMQrF5XuMNRZ3ks5WPNKDwA%3D%3D)

@Luis-Fernando-Molina tu opinión por favor.

**Comment by jonathanborges3d** [comment]
@Luis-Fernando-Molina Cuando puedas me das tu opinión por favor. Gracias.

**Comment by Luis-Fernando-Molina** [comment]
:+1:  perfecta!
