### ISSUE TITLE
Broker Wallet Design / Home Contract Tab view Design

### ISSUE THREAD

**Issue by Neoperol** [bitDubai/fermat-graphic-design#264]
#242

@nelsonalfo 

Diseñar la vista Home con el tab de Contractos abiertos. 

![contracts tab](https://cloud.githubusercontent.com/assets/6201081/10852752/8e555494-7f04-11e5-8a03-1dd1d0d01a53.png)

**Comment by Neoperol** [comment]
Propuesta para la vista de home con el tab de contratos desplegados.

![view_home_contracts](https://cloud.githubusercontent.com/assets/6201081/10908911/570a3940-8207-11e5-8b05-76f6a5545704.jpg)

@Luis-Fernando-Molina

**Comment by Luis-Fernando-Molina** [comment]
:+1:

**Comment by nelsonalfo** [comment]
:+1:

**Comment by nelsonalfo** [comment]
@Neoperol dado que ya esta cerrado este Issue necesitaria de tu parte que me pases los codigos de los colores y las tipografias, etc para este view

**Comment by Neoperol** [comment]
@nelsonalfo 

Este es el enlace de los colores, las fuentes y los tamaños 
Y en las carpetas de cada vista hay una carpeta que se llama resources con las imágenes. 

https://docs.google.com/document/d/1zLCwYLcd62H3AIpODw0av57VqDlJKWZY-yw68rCshtc/edit

**Comment by nelsonalfo** [comment]
@Neoperol necesito que me indiques los estilos del header Market Exchange Rate, tanto para el texto como para la grafica
