### ISSUE TITLE
Broker Wallet Design / Wizard Identity view Design

### ISSUE THREAD

**Issue by Neoperol** [bitDubai/fermat-graphic-design#267]
#242

@nelsonalfo 

Diseñar la vista de para la configuración de la Identity de la Wallet. Se debe mostrar la listas de las identidades creadas por el usuario y la opción de seleccionar uno de ellos.

![identity](https://cloud.githubusercontent.com/assets/6201081/10853138/c8bb118a-7f06-11e5-9bed-dddda8e79c82.png)

**Comment by Neoperol** [comment]
Propuesta Step 1 del Wizard para configurar la Broker Wallet. 
En este paso se seleccionan las Identidades que no estén previamente conectadas con otra Broker Wallet. 
Y se advierte al usuario que esta selección no puede modificar. 

![view_wizard_identity](https://cloud.githubusercontent.com/assets/6201081/10873005/a64dd4ae-80df-11e5-87a8-44c13becff49.jpg)

@Luis-Fernando-Molina

**Comment by nelsonalfo** [comment]
el botón _Start_ esta desactivo? creo que se debería sustituir dicho botón por uno que diga _Siguiente_ y que este en el costado derecho, para dar a entender que son varios pasos lo que hay que completar

**Comment by Neoperol** [comment]
Si esa es la vista con el botón desactivado. Al seleccionar una identidad cambia, en la noche te hago las dos opciones.

**Comment by Luis-Fernando-Molina** [comment]
1. REvisa tu ingles.
   2.recorda que los brokers van a poner su logo, con lo cual fotos redonditas no conviene.

**Comment by Neoperol** [comment]
> REvisa tu ingles. 2.recorda que los brokers van a poner su logo, con lo cual fotos redonditas no conviene.

Tranquilo Luis voy a cambiar los contenedores de las imágenes. Pero esa razón es bastante debatible.
En Instragram los contenedores de los User Profiles son redondos y bastantes empresas usan instagram. Si un logo no se puede ver bien pequeño y en cualquier contenedor, el problema es del logo. 

https://instagram.com/polarpilsen/?hl=en

https://instagram.com/uefachampionsleague/

**Comment by Neoperol** [comment]
Vista para la selección de una identidad. 

![view_wizard_identity_normal](https://cloud.githubusercontent.com/assets/6201081/10898757/01877dd2-81a0-11e5-8940-912e58cdb7d7.jpg)

Vista con una Identidad Seleccionada. 
![view_wizard_identity_selected](https://cloud.githubusercontent.com/assets/6201081/10898758/01a20b0c-81a0-11e5-91b2-73a821bb4b60.jpg)

@Luis-Fernando-Molina

**Comment by Luis-Fernando-Molina** [comment]
1. Please choose one  identity to use in this wallet. This step can not be undone.

**Comment by Neoperol** [comment]
Vista actualizada. 

![view_wizard_identity_normal](https://cloud.githubusercontent.com/assets/6201081/11035944/a86fb21e-86c7-11e5-83fe-c4467fa7b661.jpg)

@Luis-Fernando-Molina

**Comment by Luis-Fernando-Molina** [comment]
Por mi está bien, aunque puede que el START deba ser un NEXT STEP

:+1:

**Comment by Neoperol** [comment]
![view_wizard_identity](https://cloud.githubusercontent.com/assets/6201081/11109773/88edb8ae-88c6-11e5-97a4-3c54a63abe00.jpg)

Los recursos están en esta carpeta view_wizard

@nelsonalfo
