### ISSUE TITLE
Broker Wallet Design / Wizard Merchandise view Design

### ISSUE THREAD

**Issue by Neoperol** [bitDubai/fermat-graphic-design#269]
#242

@nelsonalfo 

Diseñar la vista de para la configuración de la Mercancía de la Broker Wallet. 
Se deben seleccionar 2 Mercancias, si se selecciona un Cryto luego se debe seleccionar la wallet con la cual se va a operar.

![merchandise](https://cloud.githubusercontent.com/assets/6201081/10853209/360fee40-7f07-11e5-9a28-55dc13e45188.png)

**Comment by Neoperol** [comment]
Propuesta selector de mercancía. 
Las mercancias se seleccionan con los botones que tienen los dos estados, Azul Deseleccionada y Gris Seleccionada.
En caso de que la mercancia necesite de una wallet se abre un Dialog para que el usuario seleccione de sus wallets correspondientes a esa Mercancia.

Luego de seleccionar la wallet se muestran los campos de los Spreads con los controladores para modificar el porcentaje. Por cierto si este termino no es muy conocido entre los Brokers hay que colocar un pequeño textos explicativo.
El usuario tiene la opción de eliminar la mercancia de las mercancias seleccionadas, por lo que el Botón pasa de Gris a Azul para que pueda volver a seleccionar dicha mercancía y se abra el Dialog nuevamente. 

![view_wizard_merchandise](https://cloud.githubusercontent.com/assets/6201081/11110185/1bc81ba2-88cb-11e5-96df-29fab899302b.jpg)

![view_wizard_merchandise_dialog](https://cloud.githubusercontent.com/assets/6201081/11110186/1bdcd27c-88cb-11e5-866d-9abe0d68e712.jpg)

@Luis-Fernando-Molina 
@nelsonalfo

**Comment by Luis-Fernando-Molina** [comment]
1.  Para el selector de moneda, pudieramos usar las monedas 3d de @jonathanborges3d , que tendria que hacer una para bolivares. Las que tienen fondo blanco serian utiles aca. (las que usamos en el readme)

2.bitcoin se escribe todo junto.
1. Para el selector de wallets ademas del nombre debe salir el icono de la wallet.

4- Se dice, you should select at least 2
