### ISSUE TITLE
SUPER ISSUE: Mejorar el sitio web para BitDubai

### ISSUE THREAD

**Issue by m471c4** [bitDubai/fermat-graphic-design#27]
Este issue es para sugerir cambios generales y que de acá se desprendan otros issues. Sería bueno dividir el sitio en varias páginas; por ejemplo:
1. The Project
2. Decentralized Wallet Production Line
3. Prototype
4. Why Fermat?
5. Get Involved!
6. The Team
7. Get in touch!

Esto con el fin de que no sea una página tan larga. Entiendo que desde el botón superior se puede tener un shortcut hasta cada punto, pero podría resultar poco intuitivo. Si no me equivoco estamos trabajando con la plataforma de wordpress y creo que es posible realizarlo. De cualquier modo, espero comentarios y sugerencias.

**Comment by Luis-Fernando-Molina** [comment]
@m471c4 hay una tendencia hacia sitios de una sola página. Mas adelante me imagino que tendremos un web master para mantener los sitios / blogs, etc , mientras tanto yo lo mejoraría sin cambiar eso.

**Comment by m471c4** [comment]
¡Perfecto! En ese caso propondré otros issues para casos más específicos.
