### ISSUE TITLE
Broker Wallet Design / Contract list  view Design

### ISSUE THREAD

**Issue by Neoperol** [bitDubai/fermat-graphic-design#271]
#242

@nelsonalfo 

Diseñar la vista de Contract list, con los diferentes tipos de contratos y el ordenamiento de la lista dependiendo de los distintos tipos de casos.

![contracts](https://cloud.githubusercontent.com/assets/6201081/10853410/13c23658-7f08-11e5-91c9-d7464d3836d0.png)

Vista con el filtro de la lista abierto. Se debe filtrar por la clase de Contractos que se pueden manejar. 

![contracts filter](https://cloud.githubusercontent.com/assets/6201081/10854463/13eca752-7f0e-11e5-9d8f-90d29454305e.png)

**Comment by Neoperol** [comment]
Vista del historial de contratos. 

![view_contract_history](https://cloud.githubusercontent.com/assets/6201081/11202549/85d7eb14-8cbb-11e5-8742-735675710e61.jpg)

@Luis-Fernando-Molina

**Comment by nelsonalfo** [comment]
habiamos quedado en que los colores de fondo se iba a usar para identificar el estado en que termino el contrato correcto?

**Comment by nelsonalfo** [comment]
@Neoperol @Luis-Fernando-Molina voy a tomar este primer diseño como base para la pantalla, hasta que se le de el go definitivo

**Comment by Luis-Fernando-Molina** [comment]
ok
