### ISSUE TITLE
Broker Wallet Design / Negotiation Detail view Design

### ISSUE THREAD

**Issue by Neoperol** [bitDubai/fermat-graphic-design#272]
#242

@nelsonalfo 

Diseño de la vista de una Negociación. 
Hay que diseñar todos los casos dependiendo los diferentes tipos de negociaciones que se pueden realizar. 

Elementos deben estar inactivos y activarse a medida que se van completando las clausulas, tomando como muestra el Apple Store en http://www.apple.com/

![cash detail transfer](https://cloud.githubusercontent.com/assets/6201081/10854569/b166a122-7f0e-11e5-8c54-0bc555c567d7.png)

**Comment by Neoperol** [comment]
Propuesta para el Negotiation Details 
![view_negotiation_detail](https://cloud.githubusercontent.com/assets/6201081/10929477/50f8f828-8286-11e5-9562-9489a7c2cd69.jpg)
@Luis-Fernando-Molina

**Comment by Luis-Fernando-Molina** [comment]
1.  me gustaria mejorar el diseño grafico. La primera ficha se ve bien el resto no tanto.
2.  los numeros asi en la esquinita y tan chiquitos no me convence.
3.  el SEND debiera ser CONFIRM CHANGES
4.  No me queda claro cuales registros ya estan aceptados por ambos o cuales sufrieron un acambio desde la ultima vez que entré.
5. La nota debiera ser un paso mas o no estar directamente

**Comment by Neoperol** [comment]
@Luis-Fernando-Molina 

En este caso, la que esta en verdad es la que el usuario está confirmando. 
Las que están en gris son las que faltan por confirmación. 
El nombre del botón, se cambio de Confirm a Change en una reunión con Jorge. 
Y la Nota es opcional, se debe agregar en un dialog. Ya te hago ese caso.

**Comment by Luis-Fernando-Molina** [comment]
> El nombre del botón, se cambio de Confirm a Change en una reunión con Jorge. 

yo me referia al SEND de abajo de todo.

> Y la Nota es opcional, se debe agregar en un dialog. Ya te hago ese caso. 

y como se ve la nota recibida?

**Comment by Neoperol** [comment]
Vista con la muestra de una nota enviada por el Customer al Broker. 
El elemento verde es el que esta activo y los grises son los que el Broker aun no a confirmado o editado. 

![view_negotiation_detail_withnote_01](https://cloud.githubusercontent.com/assets/6201081/10959403/3b16b832-834a-11e5-8bc3-147bb32e1b42.jpg)

@Luis-Fernando-Molina

**Comment by Neoperol** [comment]
![view_negotiation_detail_01](https://cloud.githubusercontent.com/assets/6201081/10975447/33c8d96a-83b9-11e5-8db3-474e0ee4988f.jpg)

El botón creo que es mejor dejarle ese nombre genérico, o cambiar de nombre dependiendo de lo que haga el Broker, porque si le abre una Negociación que le llegue del customer y no cambia nada solo agrega la información para hacer las transferencias y los días de hacer los intercambios, eso no sería un CONFIRM CHANGES. Cambie o no cambie las clausulas el Broker le esta enviando esta negociación al Customer. 

![view_negotiation_detail_note](https://cloud.githubusercontent.com/assets/6201081/10975448/33e10e04-83b9-11e5-874b-f021280606bd.jpg)

Esta es la vista para agregar la nota, se hace en un dialog full screen. 

@Luis-Fernando-Molina

**Comment by Luis-Fernando-Molina** [comment]
estamos discutiendo demasiadas cosas en el mismo caso, la nota debiera ir en otro.

**Comment by Luis-Fernando-Molina** [comment]
> los numeros asi en la esquinita y tan chiquitos no me convence.

Lo del SEND ok se puede quedar asi.

En la ficha 1, no entiendo que significa cada campo, solo del Martek Reference. El de Your exchange rate debiera ser This Trade rate o algo asi.

**Comment by Neoperol** [comment]
> En la ficha 1, no entiendo que significa cada campo, solo del Martek Reference. El de Your exchange rate debiera ser This Trade rate o algo asi.
> 
> Rate reference: 1 USD / 0.3 BTC
> Rate dado por el sistema bitdubai
> Market rate reference: 1 USD / 0.4 BTC
> Rate dado por el mercado fuera de bitdubai
> Your rate: 1 USD  / 0.2 BTC
> El rate que con el cual se va a hacer la negociación. 

Si les quieres cambiar los nombres me avisas. 

> los numeros asi en la esquinita y tan chiquitos no me convence.

Los números pueden estar dentro o fuera de los títulos, los quite de los títulos porque son un poco irrelevantes, La manera que se hablo con Jorge para hacer la negociación es que el usuario pase por cada Paso y Confirme o Cambie dicho paso antes de ir al próximo. No puede editar el paso 7, si no ha hecho los pasos del 1 al 6. Y si después de confirmar o cambiar todos los pasos cambia un paso "x" que afecta los subsiguientes pasos todos esos pasos se reinician para que siga desde ese paso.  

Lo otro es que los tamaños en este screen son relavitos. esos numeros son de 18 sp, mientras que los títulos son de 20 SP. Bastante grandes en comparación a los textos del contenido de cada ficha que son de 14 SP.

@Luis-Fernando-Molina

**Comment by Luis-Fernando-Molina** [comment]
Los datos se pueden cambiar en cualquier orden, no  @nelsonalfo ? Lo que si sucede es que dependiendo de lo que uno elija en ciertas fichas, pueden cambiar las fichas de abajo y cambiarse por otras. Ej si elijo transferencia bancaria en vez de pago cash, abajo se me agregan fichas para los datos de la transferencia.

Respecto a los textos, si cambialos.

**Comment by nelsonalfo** [comment]
@Neoperol cuando hablamos con jorge fue para la View de iniciar una negociación (en la Crypto Customer Wallet), que nos basaríamos en el comportamiento de esta pagina: http://www.apple.com/shop/buy-iphone/iphone6s que es como tu describes.

Cuando ya estamos en el proceso de negociación (que es como le llega al Broker) es como dice @Luis-Fernando-Molina que se puede modificar cualquier paso en cualquier orden, solo que van a haber algunos pasos que dependen de otros, como el ejemplo que el da

**Comment by nelsonalfo** [comment]
Creo que seria buena idea colocar un color diferente a aquellos pasos que editas de aquellos que apruebas

**Comment by Neoperol** [comment]
> Creo que seria buena idea colocar un color diferente a aquellos pasos que editas de aquellos que apruebas

Puede ser así. 

![view_negotiation_detail_01](https://cloud.githubusercontent.com/assets/6201081/11022650/256d6834-8636-11e5-91cf-f887396b953b.jpg)

Y manejamos 3 estados en cada clasula, 
Por revisar: Gris.
Modificada: Azul
Confirmada: Verde 

@Luis-Fernando-Molina 
@nelsonalfo

**Comment by nelsonalfo** [comment]
Me parece bien esa selección de colores que sugieres y los estados a los que harían referencia, pero en la imagen están invertidos los colores (el verde como modificado y el azul como confirmado)

**Comment by Neoperol** [comment]
> Me parece bien esa selección de colores que sugieres y los estados a los que harían referencia, pero en la imagen están invertidos los colores (el verde como modificado y el azul como confirmado)

Por revisar: Gris.
Modificada: Verde
Confirmada: Azul

Si tienes razon. 

@Luis-Fernando-Molina 
@nelsonalfo

**Comment by Luis-Fernando-Molina** [comment]
No me gustan los numeritos en la forma que están en una esquinita. El resto pudiera andar.

**Comment by Neoperol** [comment]
Propuesta con cambio de posición de los números de la clausula. 

![view_negotiation_detail_001](https://cloud.githubusercontent.com/assets/6201081/11094031/a8408ffe-885f-11e5-8680-2cddf4b38529.jpg)

@Luis-Fernando-Molina

**Comment by nelsonalfo** [comment]
me gusta el diseño de esta ultima propuesta

**Comment by Luis-Fernando-Molina** [comment]
:+1: genial! lo dejamos así

**Comment by nelsonalfo** [comment]
lo que no veo es la opción del **Cancelar** en esta pantalla, se supone que tanto el Customer como el Broker pueden cancelar una negociación. Esa opcion te mostraria el dialogo del Issue #273

**Comment by Neoperol** [comment]
Un menu de opciones en el Action Bar. 

![view_negotiation_detail-recovered_01](https://cloud.githubusercontent.com/assets/6201081/11164165/ccbe1470-8aba-11e5-8679-48d3be594e88.jpg)

Abre la opción para cancelar la Negociación. 

![view_negotiation_detail-_01](https://cloud.githubusercontent.com/assets/6201081/11164180/3c7dc148-8abb-11e5-8c9d-f5211fd10355.jpg)

@nelsonalfo Cuando estes hoy por ahi, me escribes para ver como te exporto los numeros, se me ocurrio algo para evitar exportar un numero diferente por cada estado de la clausula. Y saber si el background lo vas a hacer con shape o con un 9patch.

**Comment by nelsonalfo** [comment]
> @nelsonalfo Cuando estes hoy por ahi, me escribes para ver como te exporto los numeros, se me ocurrio algo para evitar exportar un numero diferente por cada estado de la clausula. Y saber si el background lo vas a hacer con shape o con un 9patch. 

dejame discutir eso con @furszy para darte una respuesta pero estoy casi seguro que me va a decir 9patch :joy:

**Comment by furszy** [comment]
9patch por ahora :p
