### ISSUE TITLE
Broker Wallet Design / Navigation Drawer view Design

### ISSUE THREAD

**Issue by Neoperol** [bitDubai/fermat-graphic-design#275]
#242

@nelsonalfo 

Diseño de la vista del Navigation Drawer de la app. 
Además de los enlaces a las vistas principales hay que agregar la información del Stock de la Mercancia que tiene el Broker. 

![menu](https://cloud.githubusercontent.com/assets/6201081/10855039/a855713c-7f11-11e5-85b2-7e52274c85ab.png)

**Comment by Neoperol** [comment]
Propuestas para el Navigation Drawer. 

![view_navigation_white](https://cloud.githubusercontent.com/assets/6201081/10865824/36ad2572-7feb-11e5-9f97-890f09af5b9d.jpg)
![view_navigation_color](https://cloud.githubusercontent.com/assets/6201081/10865846/f168de6a-7feb-11e5-8891-b074bd16d7f5.jpg)

@Luis-Fernando-Molina

**Comment by nelsonalfo** [comment]
me gusta mas la segunda propuesta (la azul), creo que va mas acorde con los colores del icono de la wallet

**Comment by Luis-Fernando-Molina** [comment]
Vamos con la azul si quieren.

1.La foto no debiera ser redonda, sino rectagular y que ocupe todo el espacio. Un broker en general no va a usar su foto sino el logo de su "empresa".

2.La parte de abajo , la ultima tablita dene tener las columans alineadas.
1. No me queda claro  los numeros debajo de Weekly que son. Si se refieren a las ganancias como decia el mock up te recuerdo que las ganancias son por cada par de trading: USD BTC, USD BOL, BOL BTC, no por cada mercaderia.
2. El titulo debiera ser Current Stock

**Comment by Neoperol** [comment]
> No me queda claro los numeros debajo de Weekly que son. Si se refieren a las ganancias como decia el mock up te recuerdo que las ganancias son por cada par de trading: USD BTC, USD BOL, BOL BTC, no por cada mercaderia.

Si es para las ganancias, y el icono es para poder cambiar entre los diferentes tiempos en que puedes ver tu ganancia. 

> El titulo debiera ser Current Stock

![view_navigation_color](https://cloud.githubusercontent.com/assets/6201081/10900097/c5fed82e-81ad-11e5-8890-3bcb704abe86.jpg)

@Luis-Fernando-Molina

**Comment by Luis-Fernando-Molina** [comment]
ahora me gusto mas! 

Ponelo asi:

## Current Stock

bitcoins ....................   220
us dollars................. 1,400
bolívares .............. 344,566

## Weekly Earnings

us dollars................... 14.44
bolívares ............... 3,434.55

Nota : los puntitos son espacios
