### ISSUE TITLE
Broker Wallet Design / Contract list view Design

### ISSUE THREAD

**Issue by Neoperol** [bitDubai/fermat-graphic-design#276]
#242

@nelsonalfo 

Diseñar la vista de la sección settings de la app. Consta de los mismos elementos que se configuran en el Wizad Setup con excepción de la parte del Identity debido a que los usuarios no pueden cambiar de identity. 

![settings](https://cloud.githubusercontent.com/assets/6201081/10855100/f608fafc-7f11-11e5-8dce-c2c7f18e7bca.png)

**Comment by nelsonalfo** [comment]
deberias cambiar el nombre del Issue a Broker Wallet Design / **Settings** view Design. ahorita esta es Broker Wallet Design / **Contract list** view Design

**Comment by Neoperol** [comment]
Hey, creo que cree otra que se llama así. https://github.com/bitDubai/fermat-graphic-design/issues/291

Este hay que cerrarlo.
