### ISSUE TITLE
Broker Wallet Design / Earnings view Design

### ISSUE THREAD

**Issue by Neoperol** [bitDubai/fermat-graphic-design#277]
#242

@nelsonalfo 

Diseño de la vista de la sección Earnings, donde se muestran las ganancias de los Brokers por cada una de las mercancías que maneja. 

![earnings](https://cloud.githubusercontent.com/assets/6201081/10855194/6f8a1cb2-7f12-11e5-919e-3e79bf2dbf65.png)

Se debe agregar un filtro a la vista para ordenar las ganancias por tiempo. 

![earning config](https://cloud.githubusercontent.com/assets/6201081/10855195/6fa339e0-7f12-11e5-89a6-cbf7bf4268a7.png)

**Comment by Neoperol** [comment]
![view_earnings](https://cloud.githubusercontent.com/assets/6201081/12645579/2c0e73bc-c59d-11e5-8a5d-0ac6b71725ba.jpg)

@nelsonalfo 

En el grafico se pueden mostrar solo las variaciones, por ejemplo en la lista de abajo del grafico se muestra el mes, en que monto termino y cuanto fue la ganancia con respecto al mes anterior. 
El grafico puede tomar esos para graficar esas variaciones y debajo de la lista mostramos mas detalles de ese grafico. 
Puede ser muy complicado dejar que el usuario pueda cambiar de Mes a Día. Pero seria bueno. 
Escribeme por aqui para cuadrar bien esto.

**Comment by nelsonalfo** [comment]
Esta es una implementación que hice de la pantalla de Earnings, a ver que se puede tomar de aquí:

![Earnings Screen](https://cloud.githubusercontent.com/assets/1823627/12648318/9db06f80-c5ab-11e5-848e-1798b73ff26a.png)

Esa implementación esta inspirada en esta imagen: http://storage.googleapis.com/vloggdotcom.appspot.com/uploads/2013/11/AdsenseEarningsInAndroidApp.png

Con respecto a lo de los filtros para los dias y eso, no creo que sea tan complicado, la cosa es que el plugin de donde voy a sacar esa data no esta implementado y no se si e va a ofrecer esa información. 

Los indicadores pueden ser algo fastidioso de implementar pero tampoco es mal de morir, solo que puede tomarme algo de tiempo.

**Comment by nelsonalfo** [comment]
Hablando con leon, las ganancias se han de mostrar por pares de mercancias y no por monedas directamente, por que se puede dar el caso de que para BTC/USD la ganancia sea en USD y para BTC/VEF tambien sea USD, pero sus saldos van a ser diferentes

**Comment by Neoperol** [comment]
![view_earnings](https://cloud.githubusercontent.com/assets/6201081/12676442/7a1d3850-c664-11e5-89cf-cdc4c76d9955.jpg)

@nelsonalfo 

Avisame si se puede implementar poder filtrar por mes y dias o incluso por semana.

**Comment by nelsonalfo** [comment]
Si se puede implementar el filtro; le comente eso a @lnacosta y lo va a tener en cuenta. Algo que no me cuadra es el la sección de **"This Month so far**". Que pasa filtro por dia? también se va a cambiar ese valor? si es así, a cual valor se cambiaria? porque ya en Today estas indicando las ganancias de hoy

**Comment by Neoperol** [comment]
@nelsonalfo 

Los indicadores superiores son independientes de la lista. Infoerior, por eso los estaba colocando sobre otro fondo. Pero si no lo nostaste de una, creo que hay hacer unos cambios visuales.

**Comment by nelsonalfo** [comment]
los vi mas como tabs en realidad :stuck_out_tongue:

**Comment by nelsonalfo** [comment]
Igual ya voy a empezar a realizar los que propones. Para ir adelantando

**Comment by nelsonalfo** [comment]
Ya realicé la implementación de la pantalla:

![Earnings Screen new Implememtation ](https://cloud.githubusercontent.com/assets/1823627/12695925/d5d08df8-c72e-11e5-817d-43e85b80b086.png)
