### ISSUE TITLE
Mejorar la visualización del isologo BitDubai en el sitio web

### ISSUE THREAD

**Issue by m471c4** [bitDubai/fermat-graphic-design#28]
Viene del #27

Es necesario mejorar la visibilidad del isologo BitDubai en la barra superior del sitio web, ya que la transparencia y las fotos del slide hacen que la palabra "bit" se pierda.

![screen4](https://cloud.githubusercontent.com/assets/13468350/9104249/bd25b756-3bd3-11e5-9667-bcf14da9e4b0.png)

Podría corregirse aumentando la opacidad de la barra, aumentando el tamaño del isologo o cambiando las fotografías. En todo caso sería necesario realizar pruebas.

**Comment by arnaldos** [comment]
@m471c4 porfa revisa este caso a ver si podemos cerrarlo.
