### ISSUE TITLE
Wallet Factory App Design - Lista de projectos con Float Button abierto. 

### ISSUE THREAD

**Issue by Neoperol** [bitDubai/fermat-graphic-design#281]
#195

Vista principal de la Factory Wallet con la lista de los projectos con el float button abierto. 
Las opciones que despliega el floating button son crear un projecto nuevo o clonar uno existente. 

![view_projects_button_open](https://cloud.githubusercontent.com/assets/6201081/10855747/7cc68b9c-7f15-11e5-8ae0-c63ae27c80cf.jpg)

**Comment by Luis-Fernando-Molina** [comment]
1. Es Wallet Factory no Factory Wallet
2. Los iconos sin el cuadrado ni el fondo blanco.
3. El clonado no debe hacerse a partir de seleccionar una wallet.
