### ISSUE TITLE
Bocetar ideas para la imagen de Fermat MKT

### ISSUE THREAD

**Issue by m471c4** [bitDubai/fermat-graphic-design#29]
Viene del #3 

Actualmente el logo se tomó prestado de otro concepto. Se debe realizar uno nuevo. Hacerlo directamente con la nueva paleta de colores.

![fermat-mkt](https://cloud.githubusercontent.com/assets/9479367/9057462/735d795e-3a9a-11e5-9b5c-a7a0b40d3c6d.png)

**Comment by Luis-Fernando-Molina** [comment]
:+1:

**Comment by m471c4** [comment]
@Luis-Fernando-Molina, este es el primer boceto para Fermat Marketing Platform. 

![fermat_mkt](https://cloud.githubusercontent.com/assets/13468350/9489279/b80771b6-4ba9-11e5-865a-18844380b53c.png)

**Comment by Luis-Fernando-Molina** [comment]
Muy bien! el icono me parece que puede quedar asi, fijate si el color de la barritas pudiera andar algun otro, sino lo dejamos asi.

**Comment by m471c4** [comment]
¿Te parece mejor invirtiendo los colores de la flecha y las barras? Creo que funciona mejor.

![fermat_mkt2](https://cloud.githubusercontent.com/assets/13468350/9491387/556f0f8c-4bb8-11e5-94b0-d2fffa86f740.png)

**Comment by Luis-Fernando-Molina** [comment]
:+1:  si , ahí está mejor, queda un detalle con la sobre desde la billetera (que no existe)

**Comment by m471c4** [comment]
¿Te refieres a la sombra? Acá está corregido.

![fermat_mkt3](https://cloud.githubusercontent.com/assets/13468350/9500275/45ecbee8-4bee-11e5-9a97-f9b414a9a847.png)

**Comment by m471c4** [comment]
Versión final, la subo para cerrar el issue.

![fermatmkt2](https://cloud.githubusercontent.com/assets/13468350/9613449/355056e6-50b5-11e5-92ae-6a4c80cf01e9.png)
