### ISSUE TITLE
Broker Wallet Design / Settings view Design

### ISSUE THREAD

**Issue by Neoperol** [bitDubai/fermat-graphic-design#291]
#242

@nelsonalfo 

Diseñar la vista Settings, los elementos de la vistas deben abrir vistas con una diagramación parecida al wizard.

![settings](https://cloud.githubusercontent.com/assets/6201081/10871722/4a9af6aa-80c1-11e5-8731-951f7338b36f.png)

**Comment by Neoperol** [comment]
Propuestas para la vista de settings. 

La lista son enlaces que abren los fragmentos usados en el Set up Wizard. 

![view_settings](https://cloud.githubusercontent.com/assets/6201081/10871730/81e1f474-80c1-11e5-9bd2-2f0afc3b4b0f.jpg)

@Luis-Fernando-Molina

**Comment by nelsonalfo** [comment]
el diseño me parece bien, se entiende que cada uno de ellos son botones que te envían a otra actividad

**Comment by Luis-Fernando-Molina** [comment]
por favor enlazar los casos a los que se iria apretando cada cosa para poder definir si esta ok o no. Gracias

**Comment by Luis-Fernando-Molina** [comment]
@MelissaDugarte por ahora no estarán participando en los casos marcados como UI/UX Design.  @arnaldos por favor aclarale esto al resto, gracias.

**Comment by MelissaDugarte** [comment]
ok sorry :-1:  ya lo quito jeje

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina  si yo les explique a todos que solo participaríamos en los casos de 2D design. ya les recalco la información :+1:
