### ISSUE TITLE
Crear una versión del logo de bitDubai sin la palabra en árabe. 

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#292]
En esta versión se debe mantener los mismos colores sin el texto en arabe.

@m471c4 encargarte de este issue.

**Comment by m471c4** [comment]
@Luis-Fernando-Molina @arnaldos con respecto a este caso, ¿se desea mantener la misma disposición del texto? O se desea crear una versión completamente nueva? Particularmente siento que pierde fuerza y sería necesario replantear algunas cosas.

Acá el logo sin la palabra árabe, manteniendo la disposición anterior:

Versión horizontal:
![bitdubai_sinarab1](https://cloud.githubusercontent.com/assets/13468350/10932432/dc26f47e-82a2-11e5-8909-c303fa189331.png)
Versión cuadrada:
![bitdubai_sinarab2](https://cloud.githubusercontent.com/assets/13468350/10932433/dc2710bc-82a2-11e5-90f3-a7b81198c46b.png)

**Comment by Luis-Fernando-Molina** [comment]
basicamente me gustaria que inventemos un nuevo logo. No necesariamente tiene que salir la palabras bitDubai

**Comment by ivonnesantos** [comment]
![logo bit dubai-01](https://cloud.githubusercontent.com/assets/15238660/10983429/9bd4ddd0-83e4-11e5-8532-c315cea8c1fa.png)

@Luis-Fernando-Molina  @arnaldos

**Comment by m471c4** [comment]
@Luis-Fernando-Molina @arnaldos se me ocurre utilizar algo que sea representativo de Dubai en el logo, Acá una versión con la Palma Jumeirah (donde además está la ubicación física de la empresa; tal como aparece en el sitio web).

La Palma Jumeirah fue construida con la forma de una palma datilera, que es parte de la flora típica del país.

![bitdnewlogo1](https://cloud.githubusercontent.com/assets/13468350/10990846/a9901008-8429-11e5-9482-415511d2b4ab.png)

**Comment by Luis-Fernando-Molina** [comment]
la palmera es una buena idea. Hace una representación de la palmera que pueda terminar en una moneda 3d.

La que pusiste no es muy exacta a como realmente es

**Comment by m471c4** [comment]
@Luis-Fernando-Molina acá hay una versión que se ajusta más a la real, ¿la prefieres así? Quisiera geometrizarla un poco, pero no se si prefieres que se mantenga así.

![bitdnewlogo2](https://cloud.githubusercontent.com/assets/13468350/11055543/68f1746e-874a-11e5-84a2-0cf75c37f173.png)

Creo que para la moneda podríamos usar la palmera en el centro, y el texto "bitDubai" alrededor, en el borde.

![bitdnewlogopalm](https://cloud.githubusercontent.com/assets/13468350/11055548/70241944-874a-11e5-9549-234070bab228.png)

**Comment by Luis-Fernando-Molina** [comment]
sacale la dos islas de abajo, y fijate si podes hacer la palmera mas redonde que ovalada asi coincide co nla moneda., Geometrizada  va bien.

**Comment by m471c4** [comment]
@Luis-Fernando-Molina aquí la hice más redondeada, sin embargo creo que no se ve bien.

![bitdnewlogocolor2](https://cloud.githubusercontent.com/assets/13468350/11139683/aceebac6-89a4-11e5-8960-1aeec095a427.png)

Acá una versión diferente, construída eométricamente y partiendo de la palma datilera también:

![bitdnewlogocolor1](https://cloud.githubusercontent.com/assets/13468350/11139430/6bb71d12-89a1-11e5-90ca-7d7ebedbf6ca.png)
![bitdnewlogo3](https://cloud.githubusercontent.com/assets/13468350/11139436/7543e9e6-89a1-11e5-821c-09df5bbbfdc5.png)

**Comment by Luis-Fernando-Molina** [comment]
Volve a la palmera tradicional, fijate de que la medialuna sea mas redonda pero desde arriba del tronco, o no se...

**Comment by arnaldos** [comment]
como quedamos con esto ?
