### ISSUE TITLE
Logo para el equipo de Luis Fuenmayor (Fermat.org Sierra)

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#293]
@fuelusumar, en este issue haremos el briefing y discutiremos brevemente cómo quisieran representar su equipo, este logo será utilizado inicialmente en las portadas de las reuniones.

Pueden participarle a los demás miembros del equipo.

**Comment by Miguelcldn** [comment]
Los nombres de los equipos ya están decididos:

| Equipo | Nombre |
| --- | --- |
| fermat.org - Cliente | Fermat.org Charlie |
| fermat.org - Servidor | Fermat.org Sierra |

**Comment by ivonnesantos** [comment]
@bitDubai/fermat-org-team @Miguelcldn dejaré a @emely-puerta encargada de esto para ver si cerramos Aquí emely vas a postear el logo de sierra el grupo encargado de la web developer deberías hacer algo relacionado con eso para que lo ubiquemos con facilidad cuando necesitemos de ellos =) , este logo es la representación visual de cada equipo developer que compone fermat este trabajo en particular te lo deben aprobar los integrantes de grupo. 
Si alguien tiene alguna acotacion en particular color forma estilo puede plantearla lo mas pronto posible.

**Comment by Miguelcldn** [comment]
Hola @emely-puerta, dejé un comentario en otro issue relacionado https://github.com/Fermat-ORG/fermat-graphic-design/issues/238#issuecomment-195096575

**Comment by emely-puerta** [comment]
@ivonnesantos Hola! Perfecto trabajaré en ello. :)

**Comment by arnaldos** [comment]
@adryx83 por favor toma este caso quedo abandonado ! lo necesitamos con suma urgencia

**Comment by adryx83** [comment]
Buenos días, Les dejo por acá la propuesta para el logo del team.

![logo sierra team](https://cloud.githubusercontent.com/assets/17273349/14495618/0bc7bdcc-015a-11e6-83c0-b6fb8e24f7fd.jpg)

**Comment by arnaldos** [comment]
@Miguelcldn @fuelusumar aqui para que le den los comentarios a @adryx83

**Comment by arnaldos** [comment]
@Miguelcldn plz ayúdame a elegir esto para cerrar el caso

**Comment by Miguelcldn** [comment]
Podría ser el algo igual a como el que se aprobó en Charlie pero que sea una S y de color rojo como ruby?

**Comment by arnaldos** [comment]
vale perfecto !

**Comment by arnaldos** [comment]
@adryx83  el logo que se refiere @Miguelcldn https://github.com/Fermat-ORG/fermat-graphic-design/issues/238 apegate a esto para las correcciones

**Comment by adryx83** [comment]
@arnaldos aca unas ideas basadas en el otro logo

![logo sierra team2](https://cloud.githubusercontent.com/assets/17273349/14677142/2b6897ca-06da-11e6-9dd5-4c7bba937dfa.jpg)

**Comment by Miguelcldn** [comment]
Quisiera verlo con la misma textura y tipografía que tiene el logo de Charlie. La cosa es que ambos teams son complementarios

**Comment by adryx83** [comment]
@arnaldos Listo Segun tus sugerencias...

![logo sierra team3](https://cloud.githubusercontent.com/assets/17273349/14687879/7dd1241c-0709-11e6-9a1f-ec8517c77e79.jpg)

**Comment by Miguelcldn** [comment]
Excelente! Se queda :+1:

**Comment by arnaldos** [comment]
@Miguelcldn @jonathanborges3d  avísame si como va esto?

**Comment by Miguelcldn** [comment]
Ya ambos logos fueron seleccionados, esos dos últimos en cada issue

**Comment by arnaldos** [comment]
vale perfecto !!!! gracias !! siendo asi cierro los casos
