### ISSUE TITLE
CCP / Vista Settings

### ISSUE THREAD

**Issue by Neoperol** [bitDubai/fermat-graphic-design#300]
#198

En esta vista, por los momentos solo se va a permitir cambiar el estado de los Push Notifications de la app. 

![view_settings](https://cloud.githubusercontent.com/assets/6201081/10944333/e1ed5b1c-82ea-11e5-9f34-2024abe90f23.jpg)

Notifications activas. 

![view_settings_on](https://cloud.githubusercontent.com/assets/6201081/10944375/1149c45e-82eb-11e5-83f1-44d418925143.jpg)

@Luis-Fernando-Molina

**Comment by Luis-Fernando-Molina** [comment]
@Neoperol el titulo del caso no esta de acuerdo al standar, con lo cual no se de que app estas hablando...

**Comment by Neoperol** [comment]
Use el mismo nombre que tenia este SUPER ISSE y los casos a los que están enlazado
https://github.com/bitDubai/fermat-graphic-design/issues/198
CCP / SUPER ISSUE: Bitcoin Wallet UX y el nombre de los casos que tenia enlazado. 

@Luis-Fernando-Molina

**Comment by Neoperol** [comment]
@furszy 

Recursos en la carpeta view_settings
Icono
Size width 34 dp height 20dp
ic_settings_switch_on.png
ic_settings_switch_off.png

Colores

Background : #ffffff
Title “Notifications”:
    Text: 14 sp #12aca1
Background #f3f3f4
Text “Phone Notifications”: 14 sp #4f4f4f
