### ISSUE TITLE
Composición artística Nº1 con la moneda 3D Fiat Euro

### ISSUE THREAD

**Issue by jonathanborges3d** [bitDubai/fermat-graphic-design#301]
Viene del #182 
@Luis-Fernando-Molina Primera versión:

![alt text](https://raw.githubusercontent.com/bitDubai/fermat-graphic-design/b8be7a77ca6c9e4f93f7313e50731812a48ff8ff/3D%20Design/3DArtScenes/FiatCoins/Fiat_euro_art_1.jpg?token=ANBHSx8ZXJB3KQ3kqL8Rzd8dduRyx2Aoks5WQ9K1wA%3D%3D)

**Comment by jonathanborges3d** [comment]
@Luis-Fernando-Molina Segunda versión, se corrigió la ubicación de la moneda en posición vertical que muestra el reverso con el logotipo de Fermat.

![all text](https://raw.githubusercontent.com/bitDubai/fermat-graphic-design/c36849198c4b4767778262d847a7047bf7a92f07/3D%20Design/3DArtScenes/FiatCoins/Fiat_euro_art_1.jpg?token=ANBHS0ud44n1o4rYn66T4Qits4d2uVmYks5WQ_O8wA%3D%3D)

**Comment by Luis-Fernando-Molina** [comment]
ponele una luz un poco mas potente va bien. Separa las dos monedas paradas un poco please

**Comment by jonathanborges3d** [comment]
@Luis-Fernando-Molina Tercera versión con los cambios:

![alt text](https://raw.githubusercontent.com/bitDubai/fermat-graphic-design/ae53b08a19a3305d8a5aec5d4148a1e6a8a3c115/3D%20Design/3DArtScenes/FiatCoins/Fiat_euro_art_1.jpg?token=ANBHS4VZ-Kbqqayd2weUKR1-3izxNv8Xks5WRkeFwA%3D%3D)

**Comment by Luis-Fernando-Molina** [comment]
:+1:  seguí sacando mas escenas con otros backgronds. No abandones el face...
