### ISSUE TITLE
CCP / Home Record Open

### ISSUE THREAD

**Issue by Neoperol** [bitDubai/fermat-graphic-design#306]
@furszy 

![home_record_open](https://cloud.githubusercontent.com/assets/6201081/11016966/feb542ee-8562-11e5-999b-d253bec274f0.png)

Colors. 

List elements
Background: #ffffff 
Text:
Numbers: #1d1d26
Object: #5b5993
Date: #6e6e71
Divider: #949494

**Comment by furszy** [comment]
Issue completed
