### ISSUE TITLE
CCP / Contact Detail

### ISSUE THREAD

**Issue by Neoperol** [bitDubai/fermat-graphic-design#307]
@furszy 

Vista Actual
![seleccion_057](https://cloud.githubusercontent.com/assets/6201081/11017015/6b16c1b4-8564-11e5-9ae3-a0705c7444ec.png)

Cambiar el icono de share 
Recursos en la vista 
view_contact_detail

Colores

Title “green” : #12aca1
Text content : #4f4f4f
Button Request: Background #12aca1 Text: #ffffff
Button Send: Background: #1173aa Text:#ffffff

Vista Final
![view_contacts_detail](https://cloud.githubusercontent.com/assets/6201081/11017022/836ed0e4-8564-11e5-8d82-5b292df6e698.jpg)

**Comment by furszy** [comment]
Issue completed
