### ISSUE TITLE
CCP / Contact Detail Extra User

### ISSUE THREAD

**Issue by Neoperol** [bitDubai/fermat-graphic-design#308]
@furszy 

Vista Actual.

![seleccion_058](https://cloud.githubusercontent.com/assets/6201081/11017218/ddf7756a-856a-11e5-9e04-e9d1ce412497.png)

Cambios Agregar Titulos a los textview
Cambiar los Iconos
se cuentra en la carpeta view_contact_extra

Vista Final

![view_contact_extra](https://cloud.githubusercontent.com/assets/6201081/11017246/71c64730-856b-11e5-89af-aee32c78f771.jpg)

**Comment by furszy** [comment]
completed
