### ISSUE TITLE
Crear un Modal para la sección "En construcción" para fermat.org

### ISSUE THREAD

**Issue by Miguelcldn** [bitDubai/fermat-graphic-design#310]
http://fermat.org usa un esquema de 'secciones' para su navegación, sin embargo hay algunas que no están terminadas y su contenido queda en blanco, como en la siguiente imagen.

![context](https://cloud.githubusercontent.com/assets/5544266/11048659/6a01d130-870b-11e5-958a-851f875d4f92.png)

Para que el usuario esté consiente que no se espera ninguna animación o contenido por ahora, se quiere dejar en el centro de la sección alguna señal indicándole al usuario que dicha sección está en construcción. Esta sí sera con contenido estático.

**Comment by arnaldos** [comment]
Un Modal es una ventana secundaria que interrumpe la interacción de los usuarios para darle un mensaje determinado antes de que puedan volver a operar la aplicación o el sitio web.

En la Web, a menudo se utilizan para mostrar imágenes en detalle.

**Comment by Miguelcldn** [comment]
Si, pero no queremos que interrumpa en nada al usuario, sino que esté ahí en el centro. El usuario puede seguir dandole a las flechas e irse a donde quiera. Porque son varias secciones las que están en construcción

**Comment by arnaldos** [comment]
@Miguelcldn  Vale perfecto !! podríamos llamarlo un modal fijo ? por darle un nombre

**Comment by Miguelcldn** [comment]
Chévere, yo lo conozco como Placeholder, pero no quiero abusar del ingles jajaja

**Comment by arnaldos** [comment]
@Miguelcldn  vale perfecto, usemos el termino correcto !! jaja

**Placeholder**

Los marcadores o placeholder son páginas web temporales que los diseñadores o programadores colocan en un sitio web durante la etapa de desarrollo del sitio.

En nuestro caso solo sera una venta tipo Modal ya que solo sera una sección de la  web que esta en construcción. 

Defino los conceptos para los que participen en el caso. :+1:

**Comment by Miguelcldn** [comment]
Chévere entonces :+1: el contenido de dicha ventana modal se pondrá en un plano que el usuario verá flotando en el centro de la sección en contrucción, yo creo que en una resolución de 640x480 estaría bien para esto

**Comment by mariavictoriapp** [comment]
Hola, buenas tardes, podrían especificar el tamaño por favor?

**Comment by arnaldos** [comment]
Hola @mariavictoriapp la media la coloca miguel en el comentario de arriba. igual aclaro tu duda @Miguelcldn sugiere 640x480 px para esto. Claro esta que la medida pudiese variar en caso que miguel lo solicite :smile:

**Comment by mariavictoriapp** [comment]
Oops! No había visto el comentario de arriba! Gracias!!!

**Comment by arnaldos** [comment]
tranquila no pasa nada !!

**Comment by Miguelcldn** [comment]
También podría cambiar si el diseño que tengan en mente cambia, no hay restricción en eso ^_^ lo único es que no use la plantalla completa, tienen toda libertad de lo que se haga, sólo queremos decirle al usuario que estamos trabajando en esa sección (en inglés, claro)

**Comment by mariavictoriapp** [comment]
Propuesta 1 @arnaldos @Luis-Fernando-Molina @Miguelcldn 
![under_construction-01](https://cloud.githubusercontent.com/assets/15197279/11071894/5f8d382a-87b5-11e5-8645-239fbb0e4e51.png)

**Comment by arnaldos** [comment]
@mariavictoriapp no esta mal pero podríamos probar con algo similar a lo que se trabajo en el issue #112 para que valla alineado con lo que se ah trabajado para http://fermat.org/ no se que opinen @Miguelcldn y @Luis-Fernando-Molina

**Comment by jurene22** [comment]
![modal para la seccion en construccion para fermat](https://cloud.githubusercontent.com/assets/15174317/11092142/2b425084-8853-11e5-9678-82f72555ce1d.png)
@arnaldos @Luis-Fernando-Molina Buen dia aqui un aporte a este issue

**Comment by isahq23** [comment]
@arnaldos @Luis-Fernando-Molina 

![modal_fermat_1-1](https://cloud.githubusercontent.com/assets/15214774/11101650/568cbdd8-888a-11e5-9485-3d16c3ec059d.png)

![modal_fermat_1-2](https://cloud.githubusercontent.com/assets/15214774/11101656/5b41aff0-888a-11e5-91aa-83d9916e83fa.png)

![modal_fermat_1-3](https://cloud.githubusercontent.com/assets/15214774/11101658/5f4244ac-888a-11e5-8809-9b032ace06ba.png)

**Comment by jurene22** [comment]
![modal para la seccion en construccion para fermat_version 2](https://cloud.githubusercontent.com/assets/15174317/11103863/73c2992e-8897-11e5-8e35-406664774923.png)
@arnaldos @Luis-Fernando-Molina Versión 2 con pequeños cmbios y refinamiento de vectores :)

**Comment by mariavictoriapp** [comment]
![under_costruction2-01](https://cloud.githubusercontent.com/assets/15197279/11127642/836a34c6-8947-11e5-84ea-37d8323af72c.png) Modificación 1

**Comment by Luis-Fernando-Molina** [comment]
@Miguelcldn @arnaldos vamos a usar la version de @mariavictoriapp :+1:

**Comment by Miguelcldn** [comment]
Chévere, @mariavictoriapp sube esa imagen en formato png con fondo transparente para aplicarlo. Súbelo en un issue que en el título contenga `Fix #310` para ver la referencia y encontrarlo

**Comment by mariavictoriapp** [comment]
Hola, buenas noches listo, ya creé el issue que contiene la imagen solicitada @Miguelcldn @Luis-Fernando-Molina @arnaldos

**Comment by Miguelcldn** [comment]
Lo siento, me di cuenta que es mi culpa, escribi _issue_ en vez de _commit_ :disappointed:

**Comment by mariavictoriapp** [comment]
![modal_under_construction](https://cloud.githubusercontent.com/assets/15197279/11136404/6465b620-8980-11e5-9a04-6ab458e9f2d6.png)
 Ahora si, acá está el comment si pueden borren el caso que cree por confusión... Fix #310
