### ISSUE TITLE
Crear La Portada y Contraportada del Fermat Book

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#311]
La portada tiene que tener un efecto de suavizado en los bordes, para crear el efecto de 3D.

**Comment by ricardo460** [comment]
![image](https://cloud.githubusercontent.com/assets/13169767/11070967/83583f16-87b0-11e5-9728-202160b31460.png)
El suavizado es para crear un efecto parecido a este. También crear la cubierta de la parte de atrás del libro. dimensiones 580 x 700.

**Comment by ivonnesantos** [comment]
@arnaldos ese libro es solo para uso digital?

**Comment by emmysm** [comment]
Sí @ivonnesantos. Al repositorio van a subir el logo del libro de fermat para que lo incluyas en tus propuestas :)

**Comment by emmysm** [comment]
![portada fermat book](https://cloud.githubusercontent.com/assets/15143489/11125408/fa129e1c-893b-11e5-8b94-beaa4ea11034.png)
![portada fermat book 2](https://cloud.githubusercontent.com/assets/15143489/11125409/fbe6abfc-893b-11e5-9eeb-4e4db1db3110.png)

Portadas
@Luis-Fernando-Molina

**Comment by emmysm** [comment]
![portada3](https://cloud.githubusercontent.com/assets/15143489/11126240/275e8558-8940-11e5-8f11-0a5a5cd1745d.png)

**Comment by ricardo460** [comment]
@emmysm la portada no debe tener objetos que sobresalgan.

**Comment by emmysm** [comment]
gracias @ricardo460 , ya hago los ajustes. En cuánto a información qué deberían llevar la portada y contraportada?

**Comment by ricardo460** [comment]
@emmysm unos detalles que acabo de descubrir, la portada no debe tener espacios hacia los lados, la imagen debe llegar hasta la sombra, Aquí la portada montada en el libro con los detalles mencionados: 
![image](https://cloud.githubusercontent.com/assets/13169767/11130810/3bc05166-8959-11e5-8ce9-ea8ff7c5947f.png)
y aumentar un poco la resolución de la imagen.

**Comment by ricardo460** [comment]
@emmysm bueno la contraportada nada por ahora, y en la parte de atrás del libro una imagen también con los mismos efectos de suavizado.

nota: todavía falta una portada para el readme y el whitepaper. pero con menos detalles, hay que esperar a @Luis-Fernando-Molina para que nos de su opinión sobre cual sera la portada definitiva de los libros. por ahora solo necesito unos avances para ir probando.

**Comment by ivonnesantos** [comment]
![311 portada_contraporta de fermat book-01](https://cloud.githubusercontent.com/assets/15238660/11132939/1a4dcf7a-8965-11e5-9325-b2b25065f663.png)
![311 portada_contraporta de fermat book-02](https://cloud.githubusercontent.com/assets/15238660/11132940/1a5fdb84-8965-11e5-9717-d70c99a87ab1.png)

@arnaldos @Luis-Fernando-Molina

**Comment by ricardo460** [comment]
@emmysm sigue teniendo el mismo problema, la portada no puede tener espacios vacíos en los lados . @ivonnesantos esa propuesta me sirve, faltaría la portada del readme y el whitepaper.

**Comment by emmysm** [comment]
![portada4](https://cloud.githubusercontent.com/assets/15143489/11134345/14824f18-896e-11e5-840f-73c622a9250d.png)

**Comment by emmysm** [comment]
Sí, ya lo ajusté @ricardo460 . Cuáles son las medidas de las otras portadas que necesitas?

**Comment by ricardo460** [comment]
@emmysm las mismas.

**Comment by ivonnesantos** [comment]
correcciones de propuesta 1 y agregue la parte trasera de la portada 
![311 portada_contraporta de fermat book-01](https://cloud.githubusercontent.com/assets/15238660/11164825/14f356d4-8ace-11e5-9e8f-e1ac441fc4fd.png)
![311 portada_contraporta de fermat book-02](https://cloud.githubusercontent.com/assets/15238660/11164826/15032618-8ace-11e5-9611-03eb6ff29da0.png)
![311 portada_contraporta de fermat book-03](https://cloud.githubusercontent.com/assets/15238660/11164827/15150310-8ace-11e5-8124-fbf12a7b57a0.png)

@arnaldos

**Comment by ivonnesantos** [comment]
propuesta 2
![311 portada_contraporta de fermat book_2-01](https://cloud.githubusercontent.com/assets/15238660/11164841/78741086-8ace-11e5-8ae7-6614059251c0.png)
![311 portada_contraporta de fermat book_2-02](https://cloud.githubusercontent.com/assets/15238660/11164842/788433da-8ace-11e5-9c4d-d477479a7b4e.png)
![311 portada_contraporta de fermat book_2-03](https://cloud.githubusercontent.com/assets/15238660/11164843/7898e03c-8ace-11e5-820b-c22bf9413c4f.png)

@arnaldos

**Comment by arnaldos** [comment]
@ivonnesantos para la portada interna y contraportada interna nos podemos quedar con el que tiene la trama de lineas blancas con el fondo rojo. muéstrame una imagen donde se aprecie donde termina y donde comienza cada portada y contraportada. para apreciarlas mejor. pero de momento te diria la versión 1. sustituye el logo del fermat book con los colores correctos que te pase por skype. esos también los subi al repo en varios formatos

**Comment by jurene22** [comment]
![portada y contraportada del fermat book 311](https://cloud.githubusercontent.com/assets/15174317/11188467/2ef4a200-8c5d-11e5-8ffc-f0c599c84140.png)
@arnaldos aqui un aporte de la portada

**Comment by arnaldos** [comment]
@jurene22 muy buen trabajo pero nos quedamos con la versión 1 de @ivonnesantos. @ricardo460  en unos minutos subimos los archivos al repo

**Comment by jurene22** [comment]
![portada y contraportada del fermat book 311 version 2](https://cloud.githubusercontent.com/assets/15174317/11191412/5199c104-8c6d-11e5-9e8d-9db502970623.png)
@arnaldos ultimo aporte ya lo tenia listo.. disculpa estaba trabajando en eso durante la mañana no quise dejarlo de subir de todas maneras..
PORTADA Y CONTRAP. versión 2

**Comment by ivonnesantos** [comment]
@arnaldos 
![311 portada_contraporta de fermat book-01](https://cloud.githubusercontent.com/assets/15238660/11191686/b3859d06-8c6e-11e5-8a97-016c7db90149.png)
![311 portada_contraporta de fermat book-02](https://cloud.githubusercontent.com/assets/15238660/11191690/b5251c2c-8c6e-11e5-94bb-8d1b2508ee2e.png)
![311 portada_contraporta de fermat book-03](https://cloud.githubusercontent.com/assets/15238660/11191689/b45894ae-8c6e-11e5-9105-752f9012658b.png)

**Comment by Luis-Fernando-Molina** [comment]
@arnaldos a partir de ahora, en casos como este o cualquier otro que requiera la aprobación u opinión del rol que corresponde al "Usuario Final", por favor en vez de tagearme amí, tageá al @bitDubai/end-users-team así opinan y enriquecen la discución. 

Aplica esto en los casos en los que todavía exista una discusión abierta y siempre que tagees a este equipo aclará que es lo que se espera de él (revisar, opinar, aprobar, etc)

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina perfecto !! en ese caso los voy a etiquetar en los casos de las otras portadas asi nos dan su opinion

**Comment by arnaldos** [comment]
los artes ya están aplicados en el website

**Comment by gustl-arg** [comment]
@arnaldos Hermoso todo el trabajo de portadas! pregunta: donde puedo ver la del libro "aplicada en el website" NO LO ENCUENTRO EN FERMAT.ORG NI EN 3D.FERMAT.ORG

**Comment by arnaldos** [comment]
Hola @gustl-arg tienes que entrar en http://fermat.org/ y en la sección de Learning Area entras ahí y te llevara a los distintos libros, ese en especifico esta por aplicarse, pronto ya estará activo en la web @ricardo460 esta trabajando en ello. :smile:
