### ISSUE TITLE
Versión 3D del logo de Fermat Book

### ISSUE THREAD

**Issue by jonathanborges3d** [bitDubai/fermat-graphic-design#313]
Viene del #231 

@Luis-Fernando-Molina Primera versión 3D:

![fermat_book_1](https://cloud.githubusercontent.com/assets/13649739/11110878/022a4c52-88d4-11e5-82ec-16cc6b78e9e8.png)

**Comment by Luis-Fernando-Molina** [comment]
1 - donde va la llave, proba que sea undido en vez de levantado.
2- la billetera del medio tiene la costura descontinuada. Esto pasa tambien en el logo de fermat, podes arreglar las dos? please, luego genera de nuevo los formatos y asegurate que se actualice por todos lados

**Comment by jonathanborges3d** [comment]
@Luis-Fernando-Molina Con los cambios:

![fermat_book_2](https://cloud.githubusercontent.com/assets/13649739/11160912/4d9ecbc0-8a43-11e5-898f-aee86291e120.png)

Ya está listo el logo de fermat en los dos repositorios: https://github.com/bitDubai/media-kit/commit/ba09c4fe827ed9f54d6c07414ba2c7f74a33723a y https://github.com/bitDubai/fermat-graphic-design/commit/bc67ec85a608260fb5e808f2b5da138225f533d6

**Comment by Luis-Fernando-Molina** [comment]
:+1:  listo, generá todos los formatos please y ponelo en los 2 repos segun corresponda.

**Comment by Luis-Fernando-Molina** [comment]
@victoralfonzohd mirá como quedó...

**Comment by jonathanborges3d** [comment]
@Luis-Fernando-Molina Ok, ya están en el repositorio los archivos correspondientes.

https://github.com/bitDubai/fermat-graphic-design/commit/5dfbbd1cb3ff7253636c132e9ee6883a2a48168f

**Comment by victoralfonzohd** [comment]
@jonathanborges3d @Luis-Fernando-Molina Se ve muy bien!
