### ISSUE TITLE
Composición artística Nº2 con la moneda 3D Fiat Libra 

### ISSUE THREAD

**Issue by jonathanborges3d** [bitDubai/fermat-graphic-design#314]
Viene del #182 
@Luis-Fernando-Molina Primera versión:

![alt text](https://raw.githubusercontent.com/bitDubai/fermat-graphic-design/8d3e297c2284e4d8b5e5487d8280453be381498b/3D%20Design/3DArtScenes/FiatCoins/Fiat_pound_art_2.jpg?token=ANBHS653F0Xc0gYwSvrU-H5SjsswDaldks5WTbeAwA%3D%3D)

**Comment by Luis-Fernando-Molina** [comment]
:+1:
