### ISSUE TITLE
Fix #310

### ISSUE THREAD

**Issue by mariavictoriapp** [bitDubai/fermat-graphic-design#315]
![modal_under_construction](https://cloud.githubusercontent.com/assets/15197279/11135418/f3f52230-8976-11e5-9880-d38082c5cbcd.png)

Modal Formato PNG sin fondo

**Comment by mariavictoriapp** [comment]
@arnaldos @Miguelcldn @Luis-Fernando-Molina

**Comment by arnaldos** [comment]
@mariavictoriapp  se encargara de este caso.

**Comment by Miguelcldn** [comment]
Me refería a un commit, no un nuevo issue, @arnaldos asiste a @mariavictoriapp en el proceso xfa

**Comment by Miguelcldn** [comment]
Lo siento, me di cuenta que es mi culpa, escribi _issue_ en vez de _commit_ :disappointed:

**Comment by mariavictoriapp** [comment]
Jaja, a mi me pareció extraño que me mandaran a crear un issue para esto...

**Comment by arnaldos** [comment]
vale @Miguelcldn  ya la ayudo con esto !!!
