### ISSUE TITLE
SUPER ISSUE: DAP Asset Factory Rediseño

### ISSUE THREAD

**Issue by Neoperol** [bitDubai/fermat-graphic-design#316]
Re-diseño de la Asset Factory. 
En esta aplicación los usuarios pueden crear Assets, editarlos, y prepararlos para la publicación. 
No se harán cambios drásticos en la programación, en estos momentos solo se mejoraran errores que puedan tener las pantallas.

**Comment by acostarodrigo** [comment]
@Neoperol por favor, como lo habíamos hablado prioricemos las wallet, comenzando con la Issuer Wallet.

La factory tiene mucha mejora, pero es la más completa a nivel android, en cambio las wallet las necesitariamos con bastante urgencia y están practicamente vacías.
