### ISSUE TITLE
DAP Asset Factory / Home

### ISSUE THREAD

**Issue by Neoperol** [bitDubai/fermat-graphic-design#317]
#316

Propuesta para la vista principal de la Asset Factory

Se muestran los dos tipos de Assets, los que son editables y los que se están publicando. 

![view_home](https://cloud.githubusercontent.com/assets/6201081/11137465/0d371fb0-898a-11e5-8211-15bec26ab12c.jpg)

@acostarodrigo 
@Luis-Fernando-Molina

**Comment by acostarodrigo** [comment]
Bien, aunque me parece que no queda muy en claro los estados de los assets.
Nosotros en el factory manejamos 3 estados, 
Draft: que se puede editar y modificar.
Pending_final: que está en proceso de publicación y creación. Durante este proceso, el asset no es editable. Si ocurre un error o alguna validación falla, entonces vuelve a estar en modo Draft para poder editarlo y corregir lo que sea necesario.
Final: el asset ya fue emitido y no es más editable.

**Comment by Neoperol** [comment]
@acostarodrigo 

Cambios a la vista de inicio, se muestran los 3 estados de los assets. En un futuro deberíamos
 mover los Assets ya publicados a otra vista, y asi dejamos solo los items con estados editables y en proceso de publicación en esta vista. 

![view_home_001](https://cloud.githubusercontent.com/assets/6201081/11160312/50b35bcc-8a3a-11e5-8900-75e1d043e6de.jpg)

**Comment by acostarodrigo** [comment]
@franklinmarcano1970 tus comentarios.

**Comment by franklinmarcano1970** [comment]
@Neoperol @acostarodrigo excelente me parece bien! solo si se pudiera mostrar los que estan en edicion al momento de cargar la pantalla

**Comment by acostarodrigo** [comment]
@nelsonalfo yo creo que seria necesario mostrar los ya emitidos en otra seccion distinta, ya que seria a modo historico. y en la pantalla principal del home solamente mostraria los editables o los que estan en progreso de ser generados.

**Comment by nelsonalfo** [comment]
@acostarodrigo creo que el comentario iba dirigido a @Neoperol jejeje

**Comment by Neoperol** [comment]
@nelsonalfo Quieres estar en todas. xD

Ok estas deben ser las dos pantallas, una con los Assets Editables y en proceso de Publicación. 
Y otra con los ya Publicados. 
La vista de detalles se abren al tocar cualquier parte de la Card. Y desde ahí se pueden editar, eliminar o publicar dicho Asset. 

Como son pocas vistas podemos hacer un Navigation Tab Bar, y sustituir las palabras por los iconos de las dos vistas. 

El buscador en el action bar es por si se debe filtrar en dichos grids. 

![view_home](https://cloud.githubusercontent.com/assets/6201081/11170703/1c8a778e-8bae-11e5-9ddb-e7a84c626ca9.jpg)
![view_published](https://cloud.githubusercontent.com/assets/6201081/11170754/a1999d5a-8baf-11e5-8b93-4088e50d4b2f.jpg)

@acostarodrigo

**Comment by fvasquezjatar** [comment]
Los iconos no se pueden colocar en estos momentos @furszy esta trabajando en la implementacion de estos runtimes, por ahora van textos **EDITABLE** & **PUBLISHED**

**Comment by furszy** [comment]
Implementación realizada :wink:  , para cargar una imagen debes cargarla en el runtime hardcoded desde un archivo hasta que pasemos todo a github.

**Comment by fvasquezjatar** [comment]
oookei, ahora me explicas, de igual forma es reemplazar los nombres por una imagen en el runtime asi que es mas importante terminar de implementar dichos tabs..

PD: @furszy que grotzoo!

**Comment by acostarodrigo** [comment]
Ahi veo el cambio.
Hay algunas cosas que arreglar, pero fundamentalmente (por favor ASAP ya que nos frena las pruebas de integración), necesitamos poder publicar el asset.
![image](https://cloud.githubusercontent.com/assets/9518556/11341489/69edd8e8-91e1-11e5-959f-81a2ff0a650d.png)

La implementación en el module ya existe, es necesario agregar el boton de publicarlo.
@furszy @fvasquezjatar 
@franklinmarcano1970

**Comment by fvasquezjatar** [comment]
@acostarodrigo segun este diseño donde va ese boton para publicar?

**Comment by acostarodrigo** [comment]
@fvasquezjatar @furszy 
ponelo como estaba antes.
Es decir, al hacer el long click, aparece la opcion de publicar.

@Neoperol decide luego si eso es final o no

**Comment by fvasquezjatar** [comment]
Ok, al long click el menu que te va a dar la opcion para publicar. @acostarodrigo

**Comment by acostarodrigo** [comment]
@fvasquezjatar Verifica que tanto en Editable como Published se pueden ver todos los assets sin importar el estado. eso no es correcto.
![image](https://cloud.githubusercontent.com/assets/9518556/11352882/dab7e28a-921d-11e5-815b-4fcbe563c692.png)

**Comment by fvasquezjatar** [comment]
@acostarodrigo Im working on it...

**Comment by Neoperol** [comment]
@acostarodrigo 
@fvasquezjatar 

Se puede cambiar el fondo del tabe Seleccionado para que quede como el screeshot ?
Tengo que cambiar el tamaño de esos 9patch para que no tengan tanto padding. 

![view_home](https://cloud.githubusercontent.com/assets/6201081/11375895/efe8308c-92af-11e5-9eff-e0123921f002.jpg)

**Comment by fvasquezjatar** [comment]
@Neoperol debido a que no tengo el control sobre el tab el comportamiento por ahora debe ser comun para todas las apps que quieran usar el componente de navegacion por tabs. asi que por ahora solo tienes un indicator y un selected text.
