### ISSUE TITLE
DAP Asset Factory / Asset Detail

### ISSUE THREAD

**Issue by Neoperol** [bitDubai/fermat-graphic-design#318]
#316

Propuesta de la vista de detalle de un asset que ya ha sido creado, los elementos que se van a agregar es la foto y el botón de back en el action bar para poder salir de la vista si no se quiere modificar o eliminar el asset. 

![view_asset_detail](https://cloud.githubusercontent.com/assets/6201081/11147048/73be5b3a-89e5-11e5-9201-c3098b6dedcd.jpg)

@Luis-Fernando-Molina 
@acostarodrigo

**Comment by acostarodrigo** [comment]
Ok, para mí. debes agregar una propiedad más que manejamos relacionada a la fecha de expiración.
El Asset puede no expirar o tener fecha de expiración.

@Neoperol

**Comment by Neoperol** [comment]
@acostarodrigo 

Cambios a la vista de detalle de los assets. 

![view_asset_detail](https://cloud.githubusercontent.com/assets/6201081/11158583/71891148-8a2b-11e5-8c96-ae3364c1b262.jpg)

**Comment by Neoperol** [comment]
@acostarodrigo 

Por cierto la otra función que falta en esta vista, es una confirmación si se presiona el botón Delete. 
Se debe abrir un Dialog para confirmar que se desea borrar el Asset y no se presiono el botón por error. 

![view_asset_detail_dialog](https://cloud.githubusercontent.com/assets/6201081/11158842/1fbe37ce-8a2d-11e5-9422-42444667b4ba.jpg)

**Comment by acostarodrigo** [comment]
@Neoperol 
@franklinmarcano1970 
De acuerdo con la confirmación.
Por favor, quita la opcion de Asset Redeemable, ya que por defecto todos lo son, por lo tanto no es una opción que tengamos que mostrar.

**Comment by franklinmarcano1970** [comment]
@Neoperol @acostarodrigo entonces debemos de guardar directamente en el campo Redeemable que sea verdadero y dejar dicho campo en la tabla por si mas adelante se considera de q el asset pueda ser redimido o no

**Comment by acostarodrigo** [comment]
@franklinmarcano1970 correcto.

**Comment by acostarodrigo** [comment]
Otra cosa que no te mencione es que @Neoperol relacionado con los bitcoins que se especifiquen, debemos permitir al usuario seleccionar la wallet de Bitcoins (la de la plataforma CCP) desde donde se obtendran esos fondos.

Nosotros devolvemos la lista de Bitcoin Wallet instaladas y el usuario debe seleccionar que Bitcoin wallet se usará para obtener esos bitcoins.

Luego nosotros comprobaremos que existan saldo suficiente para generar los assets.

**Comment by Neoperol** [comment]
Por lo que me estas explicando ahora, yo debo mostrar cuanto es el total de todos los bit coins que voy a necesitar para crear todos los assets, el precio en bitcoins de cada asset y de que Wallet proceden. todos los bitcoins. 

Al presionar el textview de Source of Bitcoins se abre el dialog donde se debe mostrar al usuario sus wallet y el balance de dicha wallet. Si no tiene balances para cubrir los Bit Coins total el boton de SAVE queda desabilitado. Esto es igual que en la creación del Asset. 
Screen shots en este issue. #327

![view_asset_detail](https://cloud.githubusercontent.com/assets/6201081/11171373/dfa6f438-8bc0-11e5-9b9b-88ae71e3c40b.jpg)

![view_asset_detail_dialog_wallet](https://cloud.githubusercontent.com/assets/6201081/11171395/5a05d0d2-8bc1-11e5-817c-5c673caa1aec.jpg)

El boton de delete se movio a un menu en el action bar. 
![view_asset_detail_delete](https://cloud.githubusercontent.com/assets/6201081/11171376/e00d35f4-8bc0-11e5-9cc1-7108a45a4503.jpg)
![view_asset_detail_dialog](https://cloud.githubusercontent.com/assets/6201081/11171377/e0bcfdae-8bc0-11e5-8cdb-f31a07ee505b.jpg)

**Comment by acostarodrigo** [comment]
@fvasquezjatar, asi va a ser el diseño de la Asset Factory, tus comentarios para comenzar a realizar las modifiaciones a la existente.

@Neoperol 
@franklinmarcano1970

**Comment by fvasquezjatar** [comment]
Realizo el cambio de todo y cableo la funcionalidad donde eliges el source wallet de donde se va a descontar el price? @acostarodrigo

**Comment by acostarodrigo** [comment]
@fvasquezjatar utilizando el getInstalledWallets del module que tienes implementado.

**Comment by fvasquezjatar** [comment]
Ok.

**Comment by acostarodrigo** [comment]
@Neoperol por favor, continuemos con la Asset Issuer Wallet.

**Comment by acostarodrigo** [comment]
@fvasquezjatar Francisco, por favor tus comentarios para saber cuándo va a estar terminado esto.
Lo tienes desde hace una semana y me comentaste que ya iba a estar terminado desde hace unos dias.

cc @furszy

**Comment by furszy** [comment]
Según lo que tengo entendido lo terminaba hoy que se quedaba el fin de semana para hacerlo.

**Comment by fvasquezjatar** [comment]
@acostarodrigo Los elementos digitales me fueron facilitados el viernes pasado, sólo tengo el home y para el dia de mañana asumo que tendré los elementos digitales para empezar con la pantalla de crear/detalle/editar/eliminar.
