### ISSUE TITLE
Crear Portada y Contraportada para la sección del README de Fermat en Fermat.org

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#319]
Es necesario crear una portada y contra portada para el **README** de Fermat que sera como una revista informativa digital. 

Dimensiones **580 x 700 px**.

También es necesario realizar la portada y contra portada interna algo sencillo no muy colorida.

El **README**  de Fermat habla sobre el  proyecto en si y la visión del mismo.

**Fecha de entrega 14/11/15**

Este caso es super **urgente** !!

La Portada y Contra portada externa debe llevar un efecto similar a la referencia del caso #311

**Comment by emmysm** [comment]
Portada readme
![portada-fermat](https://cloud.githubusercontent.com/assets/15143489/11164184/55f2934c-8abb-11e5-9abd-a1c39c59956c.png)

contra portada
![contra-portada-fermat](https://cloud.githubusercontent.com/assets/15143489/11164186/63783eb8-8abb-11e5-8e65-383aaecdb1e1.png)

portada interna
![portada-interna-readme](https://cloud.githubusercontent.com/assets/15143489/11164187/67605db2-8abb-11e5-9609-5101f684e636.png)

contra portada interna
![contra-portada-interna-readme](https://cloud.githubusercontent.com/assets/15143489/11164188/6dcc9a6c-8abb-11e5-989d-38f3c9c97514.png)

@arnaldos

**Comment by arnaldos** [comment]
@emmysm para la portada reduce el tamaño de la palabra README, adicional a eso baja el texto de Fermat y las lineas que tiene a los laterales, no las pegues tanto al texto dale mas aire. 

Revisa el circulo que le colocaste al logo de fermat se ve como un ovalo el logo lo pegues mucho al borde del circulo.

Revisa los colores !!! :smile:

**Comment by ricardo460** [comment]
@arnaldos por favor avísame cuando estén listo los cambios para añadirlos!!

**Comment by arnaldos** [comment]
vale @ricardo460  te aviso apenas se generen los ajustes

**Comment by emmysm** [comment]
![contra-portada-readme](https://cloud.githubusercontent.com/assets/15143489/11173974/bee97c8c-8bef-11e5-9044-cc6a81109cea.png)
![portada-readme](https://cloud.githubusercontent.com/assets/15143489/11173975/beedcc60-8bef-11e5-81c4-a513b22d9e06.png)

**Comment by arnaldos** [comment]
@emmysm sube los fuentes al repo para que @ricardo460  las monte. :+1:

**Comment by arnaldos** [comment]
@bitDubai/end-users-team de primera instancia y por la premura aprobé esta versión de portada y contra portada para la sección del **Readme** en fermat.org, tanto interna como externa, quisiera saber su opinión respecto al caso. y de esta manera optimizar el trabajo. :smile:
