### ISSUE TITLE
Crear Portada y Contraportada para la sección del White Paper de Fermat en Fermat.org

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#320]
Es necesario crear una portada y contra portada para el **White Paper** de Fermat que sera como una revista informativa digital. 

Dimensiones **580 x 700 px**.

También es necesario realizar la portada y contra portada interna algo sencillo no muy colorida.

El **White Paper**  de Fermat habla sobre el funcionamiento de las plataformas, plugins y add-ons que conforman a Fermat.

**Fecha de entrega 14/11/15**

Este caso es super **urgente** !!

La Portada y Contra portada externa debe llevar un efecto similar a la referencia del caso #311

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina Portada y contraportada **White Paper**

Portada
![white-paper-portait2](https://cloud.githubusercontent.com/assets/13594347/11162391/be4acb52-8a71-11e5-896a-e3b79eb26db6.jpg)

Contra portada
![white-paper-portait1](https://cloud.githubusercontent.com/assets/13594347/11162392/c14221fc-8a71-11e5-8dd1-68c3dbb28e26.jpg)

Portada Interna
![white-paper-portait4](https://cloud.githubusercontent.com/assets/13594347/11162393/c7addf72-8a71-11e5-8e07-5f265b892a5b.jpg)

Contra portada Interna
![white-paper-portait3](https://cloud.githubusercontent.com/assets/13594347/11162394/cb159c54-8a71-11e5-91c1-407a6267ede3.jpg)

Todas Juntas
![white-paper-portait](https://cloud.githubusercontent.com/assets/13594347/11162402/28939a52-8a72-11e5-9c37-93ddf9486afd.jpg)

**Comment by arnaldos** [comment]
@ricardo460 Aquí comparto las portadas y contra portadas del white paper.

**Comment by ricardo460** [comment]
@arnaldos ya están listas para aplicarlas?

**Comment by arnaldos** [comment]
@ricardo460 si esta la podemos aplicar así !!!  ya subo los archivos al repo para que los tomes de ahi

**Comment by arnaldos** [comment]
@bitDubai/end-users-team de primera instancia y por la premura aprobé esta versión de portada y contra portada para la sección del **White Paper** en fermat.org, tanto interna como externa, quisiera saber su opinión respecto al caso. y de esta manera optimizar el trabajo. :smile:

**Comment by arnaldos** [comment]
ya los artes están aplicados en fermat.org cierro el caso !
