### ISSUE TITLE
Composición artística Nº 2 con las monedas 3D Fiat

### ISSUE THREAD

**Issue by jonathanborges3d** [bitDubai/fermat-graphic-design#325]
Viene del #182 

@Luis-Fernando-Molina La primera versión que publiqué de ésta escena estaba en otro caso:

![fiat_art_3](https://cloud.githubusercontent.com/assets/13649739/11053793/5e019fe8-8736-11e5-96c0-61f86944ad9e.jpg)

Ahora hice una segunda versión utilizando como textura de la superficie ésta imágen:

![banknote](https://cloud.githubusercontent.com/assets/13649739/11166768/1e152f82-8b17-11e5-9457-5feeca0be546.jpg)

![alt text](https://raw.githubusercontent.com/bitDubai/fermat-graphic-design/7ce66246425692a84960405da5333a75d0b4cbcf/3D%20Design/3DArtScenes/FiatCoins/Fiat_art_2.jpg?token=ANBHS7Bnyb2iHDg8u2u4PmNqaliKU_Qzks5WcevAwA%3D%3D)

Mi intención con la textura era dar la idea de que las monedas estuviesen sobre billetes, pero no sé si se logró el efecto. Cuando puedas me das tu opinión.

**Comment by Luis-Fernando-Molina** [comment]
Esta buenisimo el fondo!

Fijate de que no se vean las lineas blancas que producen el cuadriculado. Muy bueno el efecto que lograste similar a los billetes. 

Te animás a hacer el billete de 1 Fermat? (en otro issue)

**Comment by jonathanborges3d** [comment]
@Luis-Fernando-Molina Hice una versión para README de ésta escena pero con el punto de vista de las demás monedas con fondo blanco.

![fiat_art_3_wb](https://cloud.githubusercontent.com/assets/13649739/11701657/f61a8442-9ea2-11e5-8d79-7399335d78d0.jpg)

**Comment by Luis-Fernando-Molina** [comment]
perfecto , subila al media kit . A la original tambien (acordate de que subirla significa tambien listarla en el README del media kit., si te olvidaste de ponerlas ahi a otras escenas, hacelo por favor.)
