### ISSUE TITLE
DAP Asset Factory / Asset Creation

### ISSUE THREAD

**Issue by Neoperol** [bitDubai/fermat-graphic-design#327]
#316

En está vista se debe mostrar cuanto es el total de todos los bit coins que se necesitan para crear todos los assets, el precio en bitcoins de cada asset y de que Wallet proceden. todos los bitcoins. 

![view_new_asset_detail](https://cloud.githubusercontent.com/assets/6201081/11171428/883919d6-8bc2-11e5-976e-2f9ad0111f69.jpg)

Al presionar el textview de Source of Bitcoins se abre el dialog donde se debe mostrar al usuario sus wallet y el balance de dicha wallet. Si no tiene balance para cubrir los BitCoins total el botón de CREATE queda desabilitado y no podrá crear los Assets. 

![view_new_asset_dialog](https://cloud.githubusercontent.com/assets/6201081/11171430/90080258-8bc2-11e5-9105-f6667961d344.jpg)

Saldra un Toast de aviso al usurio y el botón de Create quedara desactivado. 

![view_new_asset_toast](https://cloud.githubusercontent.com/assets/6201081/11171433/a8e07e5e-8bc2-11e5-8adc-5487635ec1c2.jpg)

@acostarodrigo 
@Luis-Fernando-Molina

**Comment by acostarodrigo** [comment]
@Neoperol exacto. así es correcto el flujo.
