### ISSUE TITLE
Propuestas para el diseño del billete de Fermat

### ISSUE THREAD

**Issue by jonathanborges3d** [bitDubai/fermat-graphic-design#328]
@Luis-Fernando-Molina Ésta es la versión que se tiene hasta el momento:

![banknote](https://cloud.githubusercontent.com/assets/13649739/11166768/1e152f82-8b17-11e5-9457-5feeca0be546.jpg)

Es un boceto donde sólo se aprecia el logo de Fermat y algunos elementos decorativos en forma de espiro-gramas y óvalos. Faltaría definir otros elementos que acompañen el diseño completo, cómo en el billete de un dollar:

![](https://upload.wikimedia.org/wikipedia/commons/2/24/Onedolar2009series.jpg)

Para el retrato propongo usar el de Pierre de Fermat:

![](https://upload.wikimedia.org/wikipedia/commons/f/f3/Pierre_de_Fermat.jpg)

del cual le hice una versión vectorizada como se estila en el papel moneda:

![pierre_de_fermat_3](https://cloud.githubusercontent.com/assets/13649739/11174565/bd97dc72-8bf7-11e5-9ac8-eeb3ae5c4ada.jpg)

También se utilizan Guilloches y rosetas, que son las figuras típicas que se encuentran en casi todos los billetes, por ahí vi un generador en línea muy interesante:

http://2008.sub.blue/projects/guilloche.html

![](http://images.gofreedownload.net/guilloche-rosette-6325.jpg)

@arnaldos @m471c4 me gustaría que opinaran al respecto, porque aunque el diseño será para una escena 3D, se necesitará una imagen plana de textura para los billetes. Gracias!

**Comment by Luis-Fernando-Molina** [comment]
Bien estoy de acuerdo con lo anterior. Para opinar tambien tenemos desde ahora al @bitDubai/end-users-team .

**Comment by jonathanborges3d** [comment]
@Luis-Fernando-Molina Un avance en el diseño:
![numero_1](https://cloud.githubusercontent.com/assets/13649739/11551629/404b7efa-994d-11e5-8595-46e2f36baaca.jpg)

Actualización del retrado de Pierre de Fermat:
![pierre_de_fermat_4](https://cloud.githubusercontent.com/assets/13649739/11551630/406533d6-994d-11e5-9f3d-9566668fb565.jpg)

**Comment by Luis-Fernando-Molina** [comment]
se esta viendo cool

**Comment by jonathanborges3d** [comment]
@Luis-Fernando-Molina Segunda versión del billete, aún faltan detalles que se ven en la referencia:

![banknote](https://cloud.githubusercontent.com/assets/13649739/11641751/280b2cd8-9d0c-11e5-9f46-44b756f5ea0e.jpg)

**Comment by jonathanborges3d** [comment]
@Luis-Fernando-Molina Me gustaría saber qué debería ir en la parte superior e inferior del logo de Fermat, donde dice "FEDERAL RESERVE NOTE" y "ONE DOLLAR", Propongo hacer una especie de marco parecido al del billete de un dollar pero que diga en la parte superior "DIGITAL MONEY PLATFORM", u otro que sea mucho más concreto y fácil de asimilar para cualquier persona, porque si  mal no recuerdo mencionaste anteriormente que eso era para programadores.

**Comment by Luis-Fernando-Molina** [comment]
debiera decir: A Peer-to-Peer Financial Application Framework

**Comment by jonathanborges3d** [comment]
@Luis-Fernando-Molina Incluyendo el texto y reorganizando los elementos:

![bank_note_fermat_2](https://cloud.githubusercontent.com/assets/13649739/11705846/974eaf06-9ec5-11e5-9da4-9d2a0257281f.jpg)

**Comment by Luis-Fernando-Molina** [comment]
hay cosas que no me gustan

El viejo fermat pormas que lo lograste convertir a formato billete, no me gusta, quizas porque representa algo del pasado. viejo.

Deja este caso en suspenso para mas adelante y avancemos por otro lado por favor.
