### ISSUE TITLE
Bocetar ideas para la imagen de Fermat DPN

### ISSUE THREAD

**Issue by m471c4** [bitDubai/fermat-graphic-design#33]
Viene del #4 

Actualmente el logo se tomó prestado de otro concepto. Se debe realizar uno nuevo. Hacerlo directamente con la nueva paleta de colores.

![fermat-dpn](https://cloud.githubusercontent.com/assets/9479367/9057418/2bc134be-3a9a-11e5-9bcf-b61a6ef46a9b.png)

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina @m471c4 primer boceto Fermat DPN Device Private Network
Se creó un icono con una wallet en el centro que tiene alrededor una red entre dispositivos que la conectan entre ellos.

![fermat_sub_app_2](https://cloud.githubusercontent.com/assets/13594347/9499265/55c97d16-4be8-11e5-8a00-312b7a2d66c6.jpg)

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina @m471c4 Segundo boceto Fermat DPN Device Private Network aplicando las sugerencias que se dieron en la reunión
![fermat_sub_app_6](https://cloud.githubusercontent.com/assets/13594347/9527744/9f656494-4cba-11e5-8613-01bef13ed336.jpg)

**Comment by Luis-Fernando-Molina** [comment]
:+1: este se puede quedar asi. Andá actualizando a Miguel con los que ya estén listos.

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina  ok perfecto !!! con esto ya cerramos el caso !!

**Comment by Luis-Fernando-Molina** [comment]
@arnaldos Estuve revisando de nuevo este logo, en realiad donde está la billetera debería haber una billetera y al lado una cajita fuerte. Para que entre no va a poder ser la misma caja fuerte que en otros iconos porque no se verían los detalles.

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina ajustes de Fermat DPN 
![fermat_dpn](https://cloud.githubusercontent.com/assets/13594347/9647205/70cbbe64-51a4-11e5-8159-f50413366793.png)

**Comment by Luis-Fernando-Molina** [comment]
no, la caja fuerte y la billetera debieran ser elementos diferentes.

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina Puedo remplazar uno de los dispositivos por la caja fuerte? Ya que el espacio es limitado y se hace complicado colocar tantos elementos juntos, o la billetera la podemos colocar mucho mas pequeña.

**Comment by Luis-Fernando-Molina** [comment]
se puede usar una de las billeteras pequeñas

**Comment by arnaldos** [comment]
ok perfecto !!

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina veamos que tal funciona asi 

![fermat_dpn2](https://cloud.githubusercontent.com/assets/13594347/9671503/2ae5890c-525d-11e5-8979-8d8c3ef19b6c.png)

**Comment by Luis-Fernando-Molina** [comment]
1) sacale la barra vertical
2) la caja fuerte no es la misma de antes en version pequeña.

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina  Aqui subo el icono con la caja fuerte de la primera imagen, mas pequeña y eliminamos la barra vertical

![fermat_dpn3](https://cloud.githubusercontent.com/assets/13594347/9677589/b6fef3e0-52a5-11e5-92c5-207f6444722c.png)

**Comment by Luis-Fernando-Molina** [comment]
Ok, no va andar con la caja tan chiquita.

Pone la version de la caja mas grande al medio y armá un exágono de 6 dispositivos (3 diferentes en pares en pares).

Los dispositivos conectados entre si y a la caja fuerte.

La billetera desaparece.

**Comment by arnaldos** [comment]
ok perfecto !!!

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina ajustes de Fermat DPN
![fermat-dnp](https://cloud.githubusercontent.com/assets/13594347/9720692/778beabc-555a-11e5-8e87-aaa31f68476a.png)

**Comment by Luis-Fernando-Molina** [comment]
Más grande  exagono please

Pone los dispositivos iguales opuestos

**Comment by arnaldos** [comment]
no los coloque de manera opuesta porque no había simetría
pero ya genero los cambios y los subo

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina subo dos versiones con variación de la posición de los dispositivos 
![fermat-dnp2](https://cloud.githubusercontent.com/assets/13594347/9721926/f698475c-556d-11e5-926e-6fcfcb0a1376.png)
![fermat-dnp3](https://cloud.githubusercontent.com/assets/13594347/9721927/f6c6e7ec-556d-11e5-9ca6-e43debdbc877.png)

**Comment by Luis-Fernando-Molina** [comment]
Usemos la de abajo. La caja fuerte es la misma de siempre?

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina  no, es diferente a la que realizo dayana, esta caja fuerte es otra versión ya que cuando iniciamos a trabajar con este icono se dio como sugerencia de trabajar una diferente para que se apreciaran todos los elementos, en cuanto al color, inicialmente era verde pero lo cambie ya que había mucho verde dentro del icono

**Comment by Luis-Fernando-Molina** [comment]
Entonces la de Dayana ya no va? 

Probemos con la versión de ella y con esta en verde please

**Comment by arnaldos** [comment]
si la de Dayana va !!! pero para esta versión me pediste que probara otra sintesis de caja fuerte que inicialmente estaba en verde, ya voy a probar y la comparto

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina aquí subo la caja de color verde y rojo.
![fermat-dnp4](https://cloud.githubusercontent.com/assets/13594347/9725208/756c0404-55ac-11e5-822e-0def76205470.png)
![fermat-dnp5](https://cloud.githubusercontent.com/assets/13594347/9725209/75ad885c-55ac-11e5-898a-48235f028265.png)

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina esta es la versión de la caja fuerte que realizo Dayana 

![fermat-dnp6](https://cloud.githubusercontent.com/assets/13594347/9725221/bf148ed2-55ac-11e5-9745-cd726c5b04cb.png)

**Comment by Luis-Fernando-Molina** [comment]
OK usemos la de Dayana por favor. Actualiza el icono o en fermat.org

**Comment by arnaldos** [comment]
ok perfecto!!!

**Comment by arnaldos** [comment]
ya las subo al repo para que miguel actualice

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina  te comparto los ajustes que sugeriste en la reunión de hoy :+1: 

![fermat_dpn](https://cloud.githubusercontent.com/assets/13594347/9894732/f5d88bfe-5bf0-11e5-9d83-6a40b089954b.png)

**Comment by Luis-Fernando-Molina** [comment]
Esta muy bien, un pequeño detallet. Las T que se forman, fijate si podes hacer que la parte verde interna sea continua. Con eso estaría.

**Comment by arnaldos** [comment]
perfecto ya lo ajusto

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina listo !! por favor avísame si así estamos bien, y lo subo al repo para que @Miguelcldn actualice el icono :smile: 

![fermat_dpn2](https://cloud.githubusercontent.com/assets/13594347/9911107/4ffc2324-5c6a-11e5-9899-e13492194e3f.png)

**Comment by Luis-Fernando-Molina** [comment]
:+1:

**Comment by Miguelcldn** [comment]
Chevere, estoy pendiente para subirlo apenas esté en el repo. @arnaldos prueba mencionarme en el commit a ver si me sale la notificación cuando lo subas

**Comment by arnaldos** [comment]
ok perfecto ya lo subo al repo !!
