### ISSUE TITLE
Mejoras Visuales de la App de Fermat 

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#331]
Se debe analizar la aplicación y buscar esas fallas visuales, de esta manera proponer mejoras gráficas para la aplicación desde el punto de vista estético.

Adentro de esta aplicación estarán una serie de aplicaciones y suplicaciones donde los usuarios podrán interactuar con cada una de ellas según las necesidades, sumando un total de 24 hasta el momento. 

Les dejo una captura de pantalla como muestra

![screenshot_2015-11-16-11-20-11](https://cloud.githubusercontent.com/assets/13594347/11225147/c893b75a-8d4a-11e5-8a43-b5ba1d1d9f6f.png)

**Comment by Luis-Fernando-Molina** [comment]
La idea no es postear aca todos los problemas que existan, sino mas bien, identificar el mayor problema de todos, el que mas impacto tiene. Cada quien tiene que emitir su opinion en que seria lo que hay que cambiar para solucionar el mayor problema de todos.
