### ISSUE TITLE
SUPER ISSUE: Asset Issuer Wireframe and Design

### ISSUE THREAD

**Issue by Neoperol** [bitDubai/fermat-graphic-design#332]
En desarrollo el wireframe del Asset Issuer
La guia para realizar las vistas es el wireframe que se encuentra en el enlace. 

Wireframe en desarrollo, se pueden dejar los comentarios en cada vista de la aplicación ninjamock. 

http://ninjamock.com/s/QRH9T

@Luis-Fernando-Molina 
@acostarodrigo 
@@bitDubai/skynet-team

**Comment by acostarodrigo** [comment]
@Neoperol 
muy bueno! ahi te puse un comentario.

**Comment by acostarodrigo** [comment]
@fvasquezjatar , Gregory me dice que con esto ya tenes para comenzar con el desarrollo de la issuer wallet.
Me lo podès confirmar?
cc: @furszy

**Comment by fvasquezjatar** [comment]
se puede implementar la navegabilidad de la wallet sin un estilo específico mientras se diseña el estilo. @acostarodrigo

**Comment by acostarodrigo** [comment]
@javafrank podés comenzar con el #342, que es el Home.

**Comment by nindriago** [comment]
@bitDubai/skynet-team
