### ISSUE TITLE
Reorganización de los iconos del escritorio y el fondo de la App de Fermat

### ISSUE THREAD

**Issue by jonathanborges3d** [bitDubai/fermat-graphic-design#333]
Es necesario reorganizar los íconos en un nuevo diseño, el actual comprende 6 pantallas dónde los iconos están distribuidos por grupos según las funcionalidades.

![captura_1](https://cloud.githubusercontent.com/assets/13649739/11261984/c6c57358-8e4b-11e5-82c8-94e914d13f89.jpg)

La idea es que el diseño se asemeje al sistema operativo android, de modo que el usuario tenga la sensación de que accede a una parte del mismo donde hay aplicaciones de índole financiero.

Se proponen los siguientes cambios:

1) Organizar los iconos de las wallets instaladas en líneas de 4, 

2) Añadir slider lateral para cambiar de categorías de wallets disponibles

3) Organizar los íconos de community, identity y wallet store en una línea inferior a la de las wallets, de modo que se tenga acceso permanente a éstos independiente de la categoría de wallets mostradas en el momento.

4) Añadir notificaciones (círculos naranja en la parte superior derecha) en los íconos de las wallets que indiquen información nueva para el usuario.

5) Agregar espacio para el balance de las carteras en el tipo de moneda seleccionado, para ello se podrá utilizar los modelos de monedas creados anteriormente.

6) Replantear el diseño del background de la app, adaptandolo a los elementos que se colocaran en primer plano.

(Tomado parcialmente de: https://github.com/bitDubai/fermat/issues/995)

@Luis-Fernando-Molina

**Comment by ivonnesantos** [comment]
![issues 333 reorganizacion de los iconos del escritorio-01](https://cloud.githubusercontent.com/assets/15238660/11287047/0eeccce0-8eeb-11e5-9ef2-9ddd8730bac5.png)
@jonathanborges3d @arnaldos hice esto sencillo, le puse una fuente distinta pero eso no se tiene que cumplir lo que si me parece importante es reducir el tamaño porque los títulos de por si son largos y ocupan mucho espacio.

**Comment by victoralfonzohd** [comment]
@Jonathanborges3d @arnaldos @Luis-Fernando-Molina La aplicación es bastante compleja, por lo que pensé en una introducción interactiva de pantallas que sean una guía para el usuario 

Intro:

![pantallas](https://cloud.githubusercontent.com/assets/15219855/11289231/ec74aa7c-8efc-11e5-96b7-7a0346a95ae9.jpg)

Con respecto al panel principal, para organizar todos los iconos me parece que es necesario la creación de iconos generales por plataforma, y que a partir de este icono exista una pantalla secundaria con las Sub apps de esta plataforma.

Realice una propuesta gráfica de la pantalla principal usando secciones de color por cada plataforma en la que también  agregue tres puntos en la barra derecha que indican que hay una pantalla siguiente que se despliega.

En la parte inferior de la propuesta hay un panel con círculos que indican la cantidad de pantallas que hay en la aplicación 

Use el logo de Fermat como referencia.

Panel principal:

![sin-titulo-4](https://cloud.githubusercontent.com/assets/15219855/11289194/9d037e96-8efc-11e5-9a00-3639a56bee90.jpg)

Pantallas Secundarias: Iconos de las Sub APP / Use el logo de Fermat como referencia.

![sin-titulo-5](https://cloud.githubusercontent.com/assets/15219855/11289502/c7addefe-8eff-11e5-8534-177560c1c1fd.jpg)

Utilice los colores propios de la imagen de Fermat.

**Comment by Luis-Fernando-Molina** [comment]
Las sub apps ahora mismo estan bastante repetitivas en cada plataforma. En todas hay un community o mas de una, en todas están los identities. Una posibilidad es agrupar todas las comunities en una sola pagina y poner un icono abajo como se muestra en el caso linkeado que represente a todas las communities. Lo mismo para la identities. Un icono que las agrupe a todas.

En el sistema operativo android ahora hay tambien iconos que representan un folder, que cuando uno lo toca tiene acceso a los iconos que hay adentro. Se pudiera usar eso tambien.

Ejemplo de icono de folder y vista de los iconos inferiores:

![1](https://cloud.githubusercontent.com/assets/9479367/11299900/6f110248-8f69-11e5-9624-40cddc957fbf.jpeg)

Ejemplo de folder abierto:

![2](https://cloud.githubusercontent.com/assets/9479367/11299905/7a97895c-8f69-11e5-8a36-d51c1b6d2201.jpeg)

De acuerdo con el siguiente principio de diseño en Android:

Give me tricks that work everywhere
People feel great when they figure things out for themselves. Make your app easier to learn by leveraging visual patterns and muscle memory from other Android apps. For example, the swipe gesture may be a good navigational shortcut.

Si nosotros pudieramos hacer creer al usuario que sigue dentro del sistema operativo, le resultaria por demas intuitivo.

@furszy  @nelsonalfo @fvasquezjatar  o alguien que investigue si se puede tomar la imagen de fondo del desktop de Android y copiarla o usarla directamente desde donde está, o incluso correr nuestra APP en modo transparente pero sin los iconos de otars APPs abajo pero conservando el desktop. Si logramos reutilizar el fondo que el usuario ya le puso a Android sería el caso ideal para producir el ejecto de que todo sigue y continúa ahí dentro.

Solo tendríamos que pensar que cosas van en la primera pagina, que cosas en folders, que cosas en los iconos de abajo, y no habría mucho que explicar, salvo cuando entre en cada APP.

Si logramos eso, el usuario final percibiria que fermat no es una APP sino una extensión del sistema operativo que le permite bajar y usar especificamente aplicaciones financieras que incluyen entre otras cosas, wallets de todo tipo.
