### ISSUE TITLE
Mejorar el Navigation Drawer para la Bitcoin Wallet.

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#336]
Proviene del issue #335

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina @furszy @Neoperol les comparto las mejoras del Navigation Drawer  

**Versión 1**

![view_navigation_v1_ar](https://cloud.githubusercontent.com/assets/13594347/11311154/4547125e-8fa0-11e5-89af-6554d6890796.png)

**Versión 2**

![view_navigation_v2_ar](https://cloud.githubusercontent.com/assets/13594347/11311160/4a52b244-8fa0-11e5-82b7-e1740658f27e.png)

**Comment by Luis-Fernando-Molina** [comment]
Tiene que ser con la foto completa como la opción 1. El diseño se puede reforzar un poco mas.

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina @Neoperol  @furszy  ajustes solicitados 

Versión 3

![view_navigation_v4_ar](https://cloud.githubusercontent.com/assets/13594347/11316575/b2997b38-8fde-11e5-85e7-b27ac8e2ed17.jpg)

**Comment by Luis-Fernando-Molina** [comment]
Se ve muybien, por favor, agrandá un poco el logo hasta que se lea la palabra mas chica.

**Comment by Luis-Fernando-Molina** [comment]
Quizas el logo con una sombra difusa alrededor quede mejor.

**Comment by arnaldos** [comment]
vale perfecto !!

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina te comparto varios tamaños del logo 

Versión 1

![view_navigation_v3_ar1](https://cloud.githubusercontent.com/assets/13594347/11339303/219666e8-91cb-11e5-901c-ac35bc2725ca.jpg)

Versión 2

![view_navigation_v3_ar2](https://cloud.githubusercontent.com/assets/13594347/11339301/218e3ac2-91cb-11e5-8deb-6d1cf33f0cb5.jpg)

Versión 3

![view_navigation_v3_ar3](https://cloud.githubusercontent.com/assets/13594347/11339302/21943bd4-91cb-11e5-812a-0d9732f719e2.jpg)

**Comment by arnaldos** [comment]
Me apunto por la versión dos me parece un buen tamaño para el logo. Para que se vea la palabra de abajo tendríamos que aumentarle el tamaño mucho mas lo que hace que se pierda lo delicado del logo. propongo eliminar la palabra de abajo para poder aplicarlo en esta sección y de esta manera evitar el ruido que genera la palabra sobre el logo en su maxima reducción.

**Comment by Luis-Fernando-Molina** [comment]
ok dale hacelo asi y llevalo a la wallet

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina Listo los ajustes aquí te coloco la versión con sombra al rededor del logo y otra sin sombra, sin sombra se ve mas limpia la imagen.

Versión 4

![view_navigation_v3_ar4](https://cloud.githubusercontent.com/assets/13594347/11340140/ceacf9b6-91ce-11e5-981d-36884dd774d5.jpg)

Versión 5

![view_navigation_v3_ar5](https://cloud.githubusercontent.com/assets/13594347/11340141/ceb468cc-91ce-11e5-9846-a0f4162eb2a4.jpg)

**Comment by Luis-Fernando-Molina** [comment]
version 4 :+1:

**Comment by arnaldos** [comment]
actualmente el navigaticon drawer tiene una barra de color verde el cual se definió. aplicada sobre la imagen de cualquier usuario no se ve también como en la propuesta 

Imagen predeterminada 
![screenshot_2015-12-30-10-41-27](https://cloud.githubusercontent.com/assets/13594347/12130007/82fcea9e-b3d9-11e5-9dd7-84422a9b6fe2.png)

Imagen del usuario 
![screenshot_2015-12-15-00-32-08](https://cloud.githubusercontent.com/assets/13594347/12130008/83030604-b3d9-11e5-9771-799109a6745f.png)

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina 

Propuesta 

![icons_2 7](https://cloud.githubusercontent.com/assets/13594347/12130041/d770b92a-b3d9-11e5-9e4d-8f5d9429967b.jpg)

**Comment by Luis-Fernando-Molina** [comment]
:+1:

**Comment by arnaldos** [comment]
perfecto !!
