### ISSUE TITLE
Mejorar la barra del Tab de la Bitcoin Wallet.

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#337]
Proviene del issue #335

**Comment by emmysm** [comment]
![app](https://cloud.githubusercontent.com/assets/15143489/11313210/779bc1b6-8fad-11e5-9dcf-904c8c7e27c0.jpg)
@arnaldos  @furszy @Luis-Fernando-Molina

**Comment by furszy** [comment]
Emmy, no queda bien así. Acordate quien estamos en un celular. La tipografía tiene que ser entendible y el tamaño de la letra también. Existen convenciones para estos temas preguntenle a @neoperol que les va a dar vínculos a todo esto.

**Comment by emmysm** [comment]
Vale @furszy  ya hago los ajustes segun lo indica @Neoperol  :+1:

**Comment by Luis-Fernando-Molina** [comment]
Por favor, los vinculos que terminen en el READ ME de graphic design @arnaldos para que todos sigan las mismas convenciones.
