### ISSUE TITLE
Mejorar la pantalla inicial donde esta el contador de balance.

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#338]
Proviene del issue #335

**Comment by ivonnesantos** [comment]
@arnaldos @furszy matias te paso las propuestas para que las analices y me digas que se hace con codigo y que necesitas en png, acotacion la parte de arriba queda tal cual a lo que esta hecho.
![home-01](https://cloud.githubusercontent.com/assets/15238660/11304599/f6bd71ac-8f7a-11e5-9c7b-668d60e67475.png)
![Uploading home-02.png…]()

**Comment by ivonnesantos** [comment]
@arnaldos @furszy matias te paso las propuestas para que las analices y me digas que se hace con codigo y que necesitas en png, acotacion la parte de arriba queda tal cual a lo que esta hecho.
![home-02](https://cloud.githubusercontent.com/assets/15238660/11305019/cadf3e7e-8f7c-11e5-9255-d5a69a0ac394.png)

**Comment by Luis-Fernando-Molina** [comment]
@ivonnesantos me gusto la primera propuesta tal cual esta, (con las sombras). Se puede hacer una imagen de background con el pattern y que incluya las sobra de los tabs, dejando lisa la parte donde se dibuja la dona. Para eso el impacto en el codigo es minimo y ya se puede aplicar.

Si @furszy ve que solo se trata de modificar algo en algun archivo de estilo para agregar el background, les va a explicar como se hace en una reunion grabada, para que lo aprendan y luego lo escriban en el README de ustedes. Hasta donde yo se, alcanza con modificar un estilo (un archivo XML) y no hace falta programar si solo se incorpora ese background.
