### ISSUE TITLE
Mejorar el modal de contactos.

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#340]
Proviene del issue #335

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina propuesta para el modal del contacto

versión 1
![icon_contacts_6_vs1](https://cloud.githubusercontent.com/assets/13594347/12156769/4021e992-b49f-11e5-86b5-208649050694.jpg)

versión 2
![icon_contacts_6_vs2](https://cloud.githubusercontent.com/assets/13594347/12156771/402cda78-b49f-11e5-9b69-7f1b794d17e9.jpg)

versión 3
![icon_contacts_6_vs3](https://cloud.githubusercontent.com/assets/13594347/12156770/402c3226-b49f-11e5-9797-b8027897c6f8.jpg)

**Comment by Luis-Fernando-Molina** [comment]
version 2
