### ISSUE TITLE
Mejorar el estilo del fondo para cuando hay un espacio vació en la Bitcoin Wallet.

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#341]
Proviene del issue #335

**Comment by arnaldos** [comment]
Actualmente esta  con un fondo claro con una textura como se aprecia en la siguiente imagen

![screenshot_2015-12-15-00-33-28](https://cloud.githubusercontent.com/assets/13594347/12129591/beee6b98-b3d6-11e5-8650-dd3d9e530a49.png)

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina propuesta de fondo. Usamos el fondo con degrades con los tonos que representan a la bitcoin wallet. para darle limpieza a los los elementos que estarán expuestos en esta área. 

![icons_2 2](https://cloud.githubusercontent.com/assets/13594347/12129615/e8190bb8-b3d6-11e5-8ea2-d7b1e0d67800.jpg)

**Comment by Luis-Fernando-Molina** [comment]
:+1:

**Comment by arnaldos** [comment]
perfecto !!! ya me pongo en contacto con @furszy
