### ISSUE TITLE
DAP Asset Issuer / Home My Assets List

### ISSUE THREAD

**Issue by Neoperol** [bitDubai/fermat-graphic-design#342]
#332

Diseñar la vista de My Assets List, es el home de la Wallet. En esta vista se muestran los Assets que están activos:
 Assets que aún se puedan entregar
 Assets que han sido entregados en su totalidad pero aún no han sido usados (Reddem, Apropieted) en su totalidad.
 Assets que no se han entregado en su totalidad pero se vencieron, por lo que no pueden ni ser entregados o usados. 

La lista tiene que mostrarlos en este orden, pero se puede agregar un filtro para que el usuario pueda ordenarlos dependiendo de otras características. 

![assets list](https://cloud.githubusercontent.com/assets/6201081/11311831/87c18688-8fa4-11e5-9e56-65b494726405.png)

@Luis-Fernando-Molina 
@acostarodrigo .

...

**Comment by Neoperol** [comment]
Propuesta Vista My Assets. 

![view_home](https://cloud.githubusercontent.com/assets/6201081/11545316/f0470b60-9918-11e5-8cc3-14b8d9b56bb2.jpg)

@acostarodrigo 
@Luis-Fernando-Molina

**Comment by acostarodrigo** [comment]
@Neoperol Deberíamos permitir alguna accion sobre el asset en esta pantalla, como por ejemplo distribuirlo? o ver las estadisticas?

**Comment by Neoperol** [comment]
En el actionbar me falto colocar el boton de Filtrar, con eso el usuario debe poder filtrarlo por fecha o nombre por ejemplo. Y la parte de las estadisticas se van a ver en el detalle del Asset. 
Que es este. https://github.com/bitDubai/fermat-graphic-design/issues/367

**Comment by acostarodrigo** [comment]
Perfecto, pero en el action bar también deberiamos tener la posibilidad de distribuir cualquier asset que tenga balance disponible en esta pantalla. Para ello, deberìamos también poder seleccionar los assets, no?

**Comment by Neoperol** [comment]
Ok, Vamos a aclarar como es el comportamiento de la vista.

En esta vista en el action bar debería poder hacer la Accion de Buscar para que el usuario pueda buscar por nombre un Asset y además con el Icono de Filtrar, poder filtrar la lista de los Assets. 

![view_home](https://cloud.githubusercontent.com/assets/6201081/11636371/15364a3e-9cee-11e5-8233-1d8749d58d50.jpg)

El usuario al presionar cualquier parte de esa Card que contiene toda la información del Asset debe abrir la vista de Detalle del asset. 

![view_asset_detail](https://cloud.githubusercontent.com/assets/6201081/11636455/613944b8-9cee-11e5-91bd-4a57fdd20155.jpg)

Desde esta vista se hacen todas las acciones referentes a este Asset en particular y el boton de Back me regresa a mi vista de Home. 

@acostarodrigo 
@javafrank
