### ISSUE TITLE
Crypto Broker Community App Design / Explore

### ISSUE THREAD

**Issue by victoralfonzohd** [bitDubai/fermat-graphic-design#348]
Viene del #343 

Donde se podrán buscar nuevos usuarios para conectarse y estarán ordenados por distancia.

**Comment by victoralfonzohd** [comment]
@Luis-Fernando-Molina @arnaldos @nelsonalfo @neoperol

Queria preguntar si el formato cuadrado de la foto del usuario se debe mantener? O puedo proponer otro formato de forma? 

![view_explore](https://cloud.githubusercontent.com/assets/15219855/11725369/95ad7d68-9f4b-11e5-852d-3ca7229dbc2d.jpg)

**Comment by nelsonalfo** [comment]
has la propuesta a ver que tal

**Comment by victoralfonzohd** [comment]
@Luis-Fernando-Molina @arnaldos @nelsonalfo @neoperol

1ra Propuesta de forma: 

Background 1:

![view_explore_version-1](https://cloud.githubusercontent.com/assets/15219855/11787193/a6ace680-a25c-11e5-8a92-b6e707053113.jpg)

Background 2:

![view_explore_version-1 1](https://cloud.githubusercontent.com/assets/15219855/11787285/0edc9ab6-a25d-11e5-8342-2b9002eb5ff6.jpg)
