### ISSUE TITLE
Crypto Customer Community App Design / Navigation drawer

### ISSUE THREAD

**Issue by m471c4** [bitDubai/fermat-graphic-design#354]
Viene del #344

Lleva la foto del usuario y un menú.

**Comment by m471c4** [comment]
@Luis-Fernando-Molina @nelsonalfo @Neoperol acá hay dos versiones del drawer con distintas paletas cromáticas. Se eliminó la opción "Settings" tal como lo solicitó Nelson.

![navigation_drawer](https://cloud.githubusercontent.com/assets/13468350/11406641/9b617e3e-9380-11e5-9d4a-a2fda51dd08a.png)

**Comment by nelsonalfo** [comment]
@m471c4 me gusta mas la opción de la Izquierda, solo que el degradado no me convence. Tambien me gustaria que ese contenedor donde esta el nombre y la foto (con el color fucia de fondo) abarcara todo el ancho.

**Comment by m471c4** [comment]
@nelsonalfo coincido contigo, el de la izquierda es mucho más agradable. Haré los cambios que me pides y lo subo acá.

**Comment by m471c4** [comment]
@nelsonalfo acá con los cambios solicitados. Por ahora le dejé el degradado y agregué la vista que permite seleccionar las diferentes identidades.

![navigation_drawer_2](https://cloud.githubusercontent.com/assets/13468350/11468277/6fc38c88-9720-11e5-8aed-cb79c9d17de2.png)

**Comment by nelsonalfo** [comment]
me parace bien
