### ISSUE TITLE
Crear una identidad (Logo) para la sub app **Redeem Point** que sera implementado como icono dentro de la App de Fermat

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#357]
Proviene del caso #138

**Comment by arnaldos** [comment]
@furszy @acostarodrigo ayuden me a definir el concepto de este caso para proceder a generar la identidad de esta sub app.

**Comment by acostarodrigo** [comment]
@arnaldos la sub app Redeem Point no existe como tal.
Las que existen son Redeem Point Community y Redeem Point Identity.

El concepto de redeem Point  es genérico a aquel actor que está autorizado para redimir o canjear un asset de un issuer en particular.

La sub app de Redeem point Community agrupa a todos aquellos Redeem Points conectados en la plataforma y la sub app permite realizar diferentes acciones entre sí.

La sub app Redeem Point Identity, al igual que otras sub apps identity, crea la identidad de este tipo de actor específico.

**Comment by m471c4** [comment]
@arnaldos https://github.com/bitDubai/fermat-graphic-design/issues/136

**Comment by arnaldos** [comment]
perfecto !!! esto lo plantee segun los iconos que vi en la app de fermat
