### ISSUE TITLE
Crear una identidad (Logo) para la sub app **Asset User** que sera implementado como icono dentro de la App de Fermat

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#358]
Proviene del caso #138

**Comment by arnaldos** [comment]
@furszy @acostarodrigo ayuden me a definir el concepto de este caso para proceder a generar la identidad de esta sub app.

**Comment by acostarodrigo** [comment]
@arnaldos la sub appAsset User no existe como tal.
Las que existen son Asset User Community y Asset User Identity.

El concepto de Asset User  es genérico a aquel actor que recibe y es beneficiario de assets. Al ser beneficiario, el asset user puede redimirlos en un Redeem Point o apropiarlos y quedarse con los bitcoins asociados a ese asset-

La sub app de Asset User Community agrupa a todos aquellos Asset User conectados en la plataforma y la sub app permite realizar diferentes acciones entre sí.

La sub app Asset User Identity, al igual que otras sub apps identity, crea la identidad de este tipo de actor específico.
