### ISSUE TITLE
Crear una identidad (Logo) para la sub app **Asset Identity User** que sera implementado como icono dentro de la App de Fermat

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#359]
Proviene del caso #138

**Comment by arnaldos** [comment]
@furszy @acostarodrigo ayuden me a definir el concepto de este caso para proceder a generar la identidad de esta sub app.

**Comment by acostarodrigo** [comment]
La sub app Asset Identity User no existe como tal.
Creo que te refieres a Asset User Identity, que al igual que otras sub apps de identity, sirve para dar identidad al actor asset User

**Comment by arnaldos** [comment]
ok perfecto !!

**Comment by arnaldos** [comment]
Asset user Identity provisional

![asset user identity](https://cloud.githubusercontent.com/assets/13594347/11388044/91f81420-9303-11e5-98b2-690d0866f23c.png)

**Comment by ivonnesantos** [comment]
![asset_user_identity_iv-01](https://cloud.githubusercontent.com/assets/15238660/11886624/592df2ce-a4fe-11e5-9073-9cbe95e94aaa.png)

@arnaldos @Luis-Fernando-Molina

**Comment by arnaldos** [comment]
@ivonnesantos busca algo mas que se asemeje a un dentity

**Comment by ivonnesantos** [comment]
![asset_user_identity_iv-01](https://cloud.githubusercontent.com/assets/15238660/11887468/b12ee106-a506-11e5-8b8e-400fb83a90f7.png)

@arnaldos @Luis-Fernando-Molina

**Comment by arnaldos** [comment]
te dejo la version que fue aprobada para que tomes referencia de colores ![asset_user_wallet](https://cloud.githubusercontent.com/assets/13594347/11889552/a2dfacb4-a51c-11e5-88ed-1444df7ec188.png)

**Comment by arnaldos** [comment]
![icon_-asset_user_wallet_definitivo](https://cloud.githubusercontent.com/assets/13594347/11889569/dacac302-a51c-11e5-891c-74cb8303f2e6.png)

**Comment by arnaldos** [comment]
@ivonnesantos podría ir por la propuesta 3 juega con lo los elementos, crea te una nueva version prueba otra síntesis para definir al usurario

**Comment by ivonnesantos** [comment]
![asset_user_identity_iv-01](https://cloud.githubusercontent.com/assets/15238660/11915377/6f3df13a-a676-11e5-9d9f-7711b1f27d0f.jpg)

@arnaldos @Luis-Fernando-Molina

**Comment by arnaldos** [comment]
@ivonnesantos replantealo
