### ISSUE TITLE
Crear una identidad (Logo) para la sub app **Asset Identity Issuer** que sera implementado como icono dentro de la App de Fermat

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#360]
Proviene del caso #138

**Comment by arnaldos** [comment]
@furszy @acostarodrigo ayuden me a definir el concepto de este caso para proceder a generar la identidad de esta sub app.

**Comment by acostarodrigo** [comment]
La sub app Asset Identity Issuer no existe como tal.
Creo que te refieres a Asset Issuer Identity, que al igual que otras sub apps de identity, sirve para dar identidad al actor asset Issuer.

El Asset Issuer es el generador de assets dentro de la plataforma. Es quien crea y distribuye los assets entre distintos usuarios (Asset Users) de la plataforma.

**Comment by ivonnesantos** [comment]
Propuesta 
![asset identity issuer 360iv-01](https://cloud.githubusercontent.com/assets/15238660/11413021/5737e028-93b6-11e5-8ba5-ed2183facfb2.png)

@arnaldos @Luis-Fernando-Molina

**Comment by Luis-Fernando-Molina** [comment]
En ingles se dice "Asset Issuer Identity" 
- Los assets los representamos con figuras geometricas.
- Las identidades con mascaras.
- Un Issuer, no se.

**Comment by ivonnesantos** [comment]
![asset identity issuer 360iv-01](https://cloud.githubusercontent.com/assets/15238660/11425465/57e70c76-9427-11e5-894d-879391ea53e9.png)

@arnaldos  @Luis-Fernando-Molina

**Comment by Luis-Fernando-Molina** [comment]
mas propuestas please

**Comment by ivonnesantos** [comment]
@arnaldos @Luis-Fernando-Molina 

![asset identity issuer 360iv-01](https://cloud.githubusercontent.com/assets/15238660/11445659/431c3986-9500-11e5-8715-85fb82074c29.png)

**Comment by arnaldos** [comment]
@ivonnesantos propuesta 2 provisional que opinas @Luis-Fernando-Molina

**Comment by ivonnesantos** [comment]
![asset identity issuer 360iv-01](https://cloud.githubusercontent.com/assets/15238660/11513898/f1a14d58-9847-11e5-85f1-b4b432e6b25e.png)

@arnaldos

**Comment by arnaldos** [comment]
@ivonnesantos fíjate que el issuer es una entidad jurídica busca la manera de representar eso en el icono, me ira por la propuesta 8 y 6 pero haciendo énfasis en la entidad jurídica

**Comment by acostarodrigo** [comment]
no es una identidad jurídica, es algo más abstracto. Es un generador de assets. 
Yo apuntaria a representar un asset en el ícono y una persona con un signo + que haga pensar de creación o generación.

**Comment by arnaldos** [comment]
ok perfecto !! @acostarodrigo

**Comment by ivonnesantos** [comment]
@arnaldos 
![asset identity issuer 360iv-01](https://cloud.githubusercontent.com/assets/15238660/11536160/6d6d9d3c-98e9-11e5-9b89-95808301cc0c.png)

**Comment by acostarodrigo** [comment]
mi opinion, pero la figura de las propuestas 10, 5,6 ,7 y 8 me hace pensar de una persona con antifaz y un ladron...algo no bueno para nuestro issuer :-)

**Comment by ivonnesantos** [comment]
@acostarodrigo tienes razon yo me inclino por la 9, que te parece la figura de cupon?

**Comment by acostarodrigo** [comment]
si, yo me inclino por la 9.

Aunque el circulo con la fecha me hace pensar mas en reciclado, pero quizas mas opciones con ese detalle solamente.

**Comment by arnaldos** [comment]
@ivonnesantos efectivamente las flechas en circulo parece algo de reciclaje eliminalas, la síntesis del usuario podrías hacerla mas completa no tan simple. si ves que es necesario incluir las flechas para transmitir algo en especifico replantealas, pero soy partidario de eliminarlas

**Comment by ivonnesantos** [comment]
@arnaldos @acostarodrigo 
![asset identity issuer 360iv-01](https://cloud.githubusercontent.com/assets/15238660/11542065/c7a5d972-9907-11e5-9137-9d993a7cc9b6.png)

**Comment by acostarodrigo** [comment]
vamos con la 12.
El ok final lo da @Luis-Fernando-Molina

**Comment by ivonnesantos** [comment]
@acostarodrigo ok entonces lo subo como provisional?

**Comment by acostarodrigo** [comment]
si por favor.
GRacias!

**Comment by arnaldos** [comment]
@ivonnesantos aumentale un poco el tamaño del personaje

**Comment by Luis-Fernando-Molina** [comment]
si como provisional, luego vemos si quedará definitivo o no.

**Comment by ivonnesantos** [comment]
![asset identity issuer 360iv-01](https://cloud.githubusercontent.com/assets/15238660/11705042/3e4b500e-9ebf-11e5-8b9d-37a564d931af.png)

@arnaldos @Luis-Fernando-Molina

**Comment by arnaldos** [comment]
@ivonnesantos propuesta 16 :+1:
