### ISSUE TITLE
Crear una identidad (Logo) para la sub app **Asset Redeem Point Identity** que sera implementado como icono dentro de la App de Fermat

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#361]
Proviene del caso #138

**Comment by arnaldos** [comment]
@furszy @acostarodrigo ayuden me a definir el concepto de este caso para proceder a generar la identidad de esta sub app.

**Comment by acostarodrigo** [comment]
Esta sub app, al igual que el resto de las identity, da identidad al actor Redeem Point. Siendo lo menos abstracto posible, en el siguiente ejemplo tenemos:
Depto Marketing de Mac Donalds como Asset Issuer
Los locales de Mac Donalds son los Redeem Point
y los clientes son Asset User.

**Comment by m471c4** [comment]
@arnaldos @Luis-Fernando-Molina @acostarodrigo en ese caso, ¿se podría usar este de forma provisional?

![rpidentity](https://cloud.githubusercontent.com/assets/13468350/11408597/629c829a-938c-11e5-8907-0150db44012d.png)
![rpidentitymu](https://cloud.githubusercontent.com/assets/13468350/11408599/6a8b612e-938c-11e5-93f2-8d42af7d3249.png)

**Comment by Luis-Fernando-Molina** [comment]
de forma provisional si, pero que el caso siga abierto.
