### ISSUE TITLE
Crear una identidad (Logo) para la sub app **Customer** que sera implementado como icono dentro de la App de Fermat

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#362]
Proviene del caso #138

**Comment by arnaldos** [comment]
@furszy @acostarodrigo ayuden me a definir el concepto de este caso para proceder a generar la identidad de esta sub app.

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina versión provisional del customer

![customer](https://cloud.githubusercontent.com/assets/13594347/11387949/5779b53e-9302-11e5-8ea7-cc89ac8a20c0.png)

**Comment by Luis-Fernando-Molina** [comment]
provisional ok
