### ISSUE TITLE
Crear una identidad (Logo) para la sub app **Developer** que sera implementado como icono dentro de la App de Fermat

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#363]
Proviene del caso #138

**Comment by arnaldos** [comment]
@furszy @acostarodrigo ayuden me a definir el concepto de este caso para proceder a generar la identidad de esta sub app.

**Comment by ivonnesantos** [comment]
![developer_identidad_fermat-01](https://cloud.githubusercontent.com/assets/15238660/11378158/08d25314-92bc-11e5-847d-a519bc10dc24.png)
@arnaldos

**Comment by arnaldos** [comment]
@ivonnesantos propuesta 3 prueba incluir la silueta de una persona para probar como se ve :smile:

**Comment by acostarodrigo** [comment]
una silueta de  persona con anteojos, para dar la apariencia de un nerdie programmer.

**Comment by ivonnesantos** [comment]
![developer_identidad_fermat-01](https://cloud.githubusercontent.com/assets/15238660/11384571/0e1b7d88-92e3-11e5-862e-400dc98578bd.png)

@arnaldos

**Comment by arnaldos** [comment]
@ivonnesantos propuesta 5 :+1:

**Comment by furszy** [comment]
@arnaldos este logo me parece mejor para la sub app de technical support.

**Comment by ivonnesantos** [comment]
![developer_fermat_512-01](https://cloud.githubusercontent.com/assets/15238660/11810052/7a97a2e6-a2fd-11e5-8fb2-5d8ff3224193.png)

@arnaldos @Luis-Fernando-Molina

**Comment by victoralfonzohd** [comment]
@arnaldos 

Propuesta 1:

![sin-titulo-1](https://cloud.githubusercontent.com/assets/15219855/12246829/ea55b074-b882-11e5-899a-5d2ba62d3d14.png)

Propuesta 2:

![logo_developer](https://cloud.githubusercontent.com/assets/15219855/12247169/f8c7ef76-b884-11e5-88b5-5ffa95112a01.png)

Propuesta 3:

![logo_developer](https://cloud.githubusercontent.com/assets/15219855/12247273/6d937b90-b885-11e5-8255-aac1ee4c7873.png)

**Comment by arnaldos** [comment]
@victoralfonzohd propuesta 2 :+1:
