### ISSUE TITLE
Mejorar el Navigation Drawer para la Crypto Customer Wallet.

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#364]
Proviene del caso #251

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina tal como me recomendaste coloco los ajustes en este caso :+1: 

![view_navigation2](https://cloud.githubusercontent.com/assets/13594347/11316584/2f8077be-8fdf-11e5-8948-bfa00ff07d70.jpg)

**Comment by Luis-Fernando-Molina** [comment]
ok, tenes que hacer el logo mas visible ahi ni se lee lo que dice.

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina Perfecto !!

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina listo  !!

![view_navigation3](https://cloud.githubusercontent.com/assets/13594347/11340316/958755c2-91cf-11e5-8a9e-953e7fe913ea.jpg)

**Comment by Luis-Fernando-Molina** [comment]
:+1:

**Comment by leonacostaok** [comment]
che, para mi el círculo de la cara no está muy bueno.... no se si es porque es muy chico o que...
el logo así gigante tampoco queda muy bueno

**Comment by furszy** [comment]
Lo hablamos con Arnaldo y Nelson eso, por mi parte y disculpen mi sinceridad, no me convence absolutamente nada.

**Comment by arnaldos** [comment]
Voy a replantear una propuesta donde el logo este mas chico y el caso de la foto para no quede recargado

**Comment by Luis-Fernando-Molina** [comment]
Lo del circulo lo podemos dejar fuera porque requiere programacion y quizas lleve un tiempo. El resto puede aplicarse asi. Luego pueden discutir todo lo que quieran sobre como mejorarlo aun mas. Ahora necesitamos que estas mejores lleguen rapido a la APP para poder mostrar algo con calidad.

**Comment by arnaldos** [comment]
vale perfecto !! propongo colocarla de una forma mas sencilla tal como el drawer de la bitcoin wallet

**Comment by arnaldos** [comment]
ya la muestro

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina ajustes dejando el circulo por fuera 

![view_navigation4](https://cloud.githubusercontent.com/assets/13594347/11346702/10223af2-91f0-11e5-989c-fb0c5d28a2c1.jpg)

**Comment by Luis-Fernando-Molina** [comment]
:+1:

**Comment by nelsonalfo** [comment]
Hola @arnaldos necesito los iconos de este Navigation Drawer para ya dejarlo listo, así como en el de la Bitcoin Wallet de @furszy necesito los iconos en estado _normal_ y en estado _seleccionado_ y el logo que me pasaste que sea mas transparente

**Comment by arnaldos** [comment]
@nelsonalfo vale ya te genero los iconos
