### ISSUE TITLE
Crear un indicador para las capas de cada ficha de Fermat.org

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#365]
Proviene del caso 

https://github.com/bitDubai/fermat-org/issues/175#issuecomment-158107684

por favor revisar antes de diseñar

**Comment by arnaldos** [comment]
@ivonnesantos  encargate de este caso plz

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina comparto versiones del indicador la diferencia es la posición del texto

Versión 1

![indicador-de-capa1](https://cloud.githubusercontent.com/assets/13594347/11375873/e17337f4-92af-11e5-92da-7abc7f160a8c.png)

Versión 2

![indicador-de-capa2](https://cloud.githubusercontent.com/assets/13594347/11375874/e1798b0e-92af-11e5-984c-7fd894c6df5f.png)

**Comment by Luis-Fernando-Molina** [comment]
La version 1 esta OK, pero debe estar todo en una sola linea y la ficha comparada con la otra debe ser:

1) De la misma altura que la ficha verde.
2) De ancho equivalente a 3 fichas verdes.

La letra esta bien en tipo y color, solo que tienen que ser mucho mas grande para que se pueda leer incluso con un zoom out importante . 

Darle prioridad a este caso por favor.

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina ajuste del indicador 

![indicador-de-capa3](https://cloud.githubusercontent.com/assets/13594347/11388272/96078f34-9306-11e5-94eb-b04cdcaffde5.png)

**Comment by arnaldos** [comment]
aquí dejo el indicador solo, para apreciarlo sin tipografia 

![indicador-de-capa](https://cloud.githubusercontent.com/assets/13594347/11388288/be9c6dc0-9306-11e5-9022-89f567a4caeb.png)

**Comment by Luis-Fernando-Molina** [comment]
:+1:  pasaselo a @Miguelcldn para que lo aplique de una vez por favor. Miguel, fijate que el tamaño de la letra no varíe de capa en capa, debe ser un tamaño donde todas las capas funcionen bien en una sola linea por favor. Gracias

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina listo !!!! @Miguelcldn ya le pase las fichas a @emmanuelcolina

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina cerramos el caso ?

**Comment by Luis-Fernando-Molina** [comment]
si, antes linkealo con el aso de eMMANUEL

**Comment by arnaldos** [comment]
@emmanuelcolina  listo este caso bitDubai/fermat-org#175 (comment)
