### ISSUE TITLE
DAP Asset Issuer / Asset Detail

### ISSUE THREAD

**Issue by Neoperol** [bitDubai/fermat-graphic-design#367]
#332

Diseñar la vista de Asset Detail.
En esta vista se muestra toda la información del Asset y hay enlaces para ver las listas de los usuarios que se les ha entregado el Asset, quienes lo han usado y cuantos faltan por entregar. 

![assets detail](https://cloud.githubusercontent.com/assets/6201081/11367456/e824c484-9285-11e5-8408-2bd845f5160c.png)

@Luis-Fernando-Molina 
@acostarodrigo .

**Comment by Neoperol** [comment]
Propuesta del Asset Detail. 

![view_asset_detail](https://cloud.githubusercontent.com/assets/6201081/11636156/d2af2362-9cec-11e5-8d5e-2fb946e6c2d3.jpg)

@acostarodrigo 
@Luis-Fernando-Molina

**Comment by acostarodrigo** [comment]
@nindriago por favor, comenzá con el desarrollo en Android de esta pantalla en la Issuer Wallet.

cc @javafrank 

@Yayotron te puede dar una mano para sacar entender qué métodos utilizar para las estadísticas.

**Comment by acostarodrigo** [comment]
@javafrank 
como hablamos en la reunion con @Neoperol  y @nindriago debes cambiar lo siguiente:
- Modificar el boton de Available por Delivered.
- Invertir las acciones de los botones entre el de Asset Remaining --> te debe llevar a la ventana de distribución y el Available (que renombras a Delivered) te muestra la pantalla de Asset Delivered List

el video de la meeting fue este para revisarlo
https://www.youtube.com/watch?v=rIhwflO5KyA

**Comment by nindriago** [comment]
@pennyxz

**Comment by javafrank** [comment]
Buen día @Neoperol 

Así va quedando la pantalla "Asset Detail"
- Abajo de la información del asset agregué un fondo con un color que tome de la imagen propuesta, veo que hay un degradado pero no es el mismo background de la app, quedaría bien así o que me recomiendas?
- Que opinas en general de la pantalla?

Adjunto la vista.

Saludos,

cc @acostarodrigo 

![oie_totwmiwheg51](https://cloud.githubusercontent.com/assets/13275281/12171186/c6ad5af8-b519-11e5-861d-a4f2b0ff4c0f.png)

![oie_dronlrfsprfo](https://cloud.githubusercontent.com/assets/13275281/12171192/ce7b20ee-b519-11e5-968c-37e5fa2ff13c.png)

**Comment by javafrank** [comment]
Esta es la pantalla de seleccion de usuarios y grupos.
- El color que me indicaste para el tab creo que está erroneo #4D000000, eso es negro. Lo que hice fue tomar el color del prototipo. Hasta ahora no estoy indicando otro color cuando se selecciona un tab u otro, eso tengo que ver como lo hago.
- Que opinas de la vista?

Saludos,

cc @acostarodrigo 

![oie_ltq8agszljr6](https://cloud.githubusercontent.com/assets/13275281/12171435/1ac0035a-b51c-11e5-99ce-d4c26904ba32.png)

**Comment by Neoperol** [comment]
@javafrank 
#4D000000 Esto es negro pero los dos primeros digitos de ese color es el nivel de opacidad. 
La vista se ve bien, lo unico que falta es diferenciar que tab esta selecionado, eso lo queria lograr con los fondos diferentes. 
Muy probable que el tab no este tomando la opacidad del color.
