### ISSUE TITLE
DAP Asset Issuer / Asset Delivery

### ISSUE THREAD

**Issue by Neoperol** [bitDubai/fermat-graphic-design#368]
#332

Diseño de la Asset Delivery 
En esta vista el usuario puede seleccionar la cantidad de Assets que quiere entregar. 
Selecciono el tipo de usuario al que quiere entregar, puede ser por nombre, agregar en bulk o grupos creados en la vista de contactos. 

Además de poder seleccionar con que prioridad se entregaran estos assests a dichos usuarios. 

![copy of page 3](https://cloud.githubusercontent.com/assets/6201081/11367512/59f17404-9286-11e5-83b6-b690671f3607.png)

@Luis-Fernando-Molina 
@acostarodrigo .

**Comment by Neoperol** [comment]
![view_asset_deliver](https://cloud.githubusercontent.com/assets/6201081/11914212/013d95fc-a64c-11e5-84ae-f69a1dc6d583.jpg)

Propuesta visual de la Asset Delivery view. 

@acostarodrigo 
@Luis-Fernando-Molina

**Comment by acostarodrigo** [comment]
@Neoperol estarìa faltando especificar la cantidad de assets a enviar.
Ademas, necesitamos poder especificar de qué bitcoin Wallet vamos a utilizar los fondos para enviar los bitcoins.

Escribir los nombres de los usuarios a los que vamos a enviar no creo que sea correcto.
Deberia ser una multiple seleccion.

**Comment by Neoperol** [comment]
Hey eso es lo del Amount to deliver, estaba mal escrito pero cambie ese texto. 
Y en cuanto a agregar a los usuarios, se puede hacer en dos pasos, pense que se iba a usar como en la Wallet Bitcoin donde puede salir una lista en la misma vista, pero mejor si se hace en una vista aparte. En esa otra vista esta un icono para seleccionar a quien le quieres enviar los Assets, para enviar a gran cantidad de personas deberíamos implementar la creación de grupos y que estos grupos esten al principio de estas listas de usuarios. 

![view_asset_deliver](https://cloud.githubusercontent.com/assets/6201081/11914338/25e92f16-a650-11e5-886c-ea5f9bef210a.jpg)

![view_asset_deliver_list](https://cloud.githubusercontent.com/assets/6201081/11914339/25ff6cc2-a650-11e5-8808-f985a2dc7655.jpg)

@acostarodrigo

**Comment by acostarodrigo** [comment]
perfecto. La implementación de los grupos ya esta hecha a nivel Java.
Todo esta listo para crear grupos, agregar usuarios, etc.

**Comment by acostarodrigo** [comment]
en la delivery List que mostras los usuarios, tambien podrias mostrar los grupos? con un icono distinto?

**Comment by Neoperol** [comment]
![view_asset_deliver_list](https://cloud.githubusercontent.com/assets/6201081/12131519/6d1d3e16-b3e5-11e5-84ba-0031f9e4c35e.jpg)

Lista de usarios para entregar assets. 
Con tabs para pasar de usuarios a grupos y el icono con los dos estados. 

@acostarodrigo

**Comment by javafrank** [comment]
Buen día @Neoperol 

Así va quedando la pantalla Assets Deliver
- No indicaste font para el content del campo de texto
- Qué estilo me puedes recomendar para el boton Select Users? está bien así?
- Quizas el titulo de la pantalla lo deberiamos cambiar a "Asset Delivery" en lugar de el nombre del asset.
- Ah, cambié los padding en información del asset, creo que se ve mejor así, que opinas?
- Qué opinas de la pantalla en general?

Saludos,

cc @acostarodrigo 

![oie_s1osiyp2cpgn](https://cloud.githubusercontent.com/assets/13275281/12171001/35ddc87e-b518-11e5-8b7b-5b9fad8b4ae3.png)

**Comment by Neoperol** [comment]
@javafrank Los padding laterales los puedes dejar en 16 dp. 
En el texto de los colores busca esto "Asset Delivery" debajo están todos los estilos de los colores de esta vista.
