### ISSUE TITLE
Bocetar ideas para la imagen de Fermat BNK

### ISSUE THREAD

**Issue by m471c4** [bitDubai/fermat-graphic-design#37]
Viene del #5 

Actualmente el logo se tomó prestado de otro concepto. Se debe realizar uno nuevo. Hacerlo directamente con la nueva paleta de colores.

![fermat-dpn](https://cloud.githubusercontent.com/assets/9479367/9057489/a9512e7a-3a9a-11e5-9371-c9d524608351.png)

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina Primer boceto de Fermat BNK
![fermat-bnc](https://cloud.githubusercontent.com/assets/13594347/9556592/c618e68e-4d9f-11e5-975b-ebde6806eb8d.png)

**Comment by Luis-Fernando-Molina** [comment]
me gustaria ver otras opciones

**Comment by arnaldos** [comment]
perfecto voy a trabajar otras opciones para este icono !!

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina comparto los últimos ajustes de Fermat BNK
![fermat_bnk](https://cloud.githubusercontent.com/assets/13594347/9584445/02072506-4fdb-11e5-98ed-cb9b2ca73b0d.png)

**Comment by Luis-Fernando-Molina** [comment]
@arnaldos el banquito pudier andar, lo que está al frente no.

proba usar la caja fuerte y/o las billeteras

**Comment by arnaldos** [comment]
ok perfecto !

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina  que tal así ?
![fermat_bnk-2](https://cloud.githubusercontent.com/assets/13594347/9587593/1ea7788e-4fed-11e5-9133-899947cc00e0.png)

**Comment by Luis-Fernando-Molina** [comment]
Proba con la caja fuerte mas grande y solo el techo del banco cubriendola

**Comment by arnaldos** [comment]
ok perfecto !!!

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina los ajustes de Fermat BNK
![fermat_bnk-3](https://cloud.githubusercontent.com/assets/13594347/9592622/97e81dd6-500e-11e5-803b-a46bad34e789.png)

**Comment by Luis-Fernando-Molina** [comment]
va queriendo...quitale por favor el piso y hace 2 propuedas, una con la parte del abajo del techo en blanco como está, y la otra en rojo por favor.

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina  ok perfecto !!

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina  ajustes Fermat BNK
![fermat_bnk-5](https://cloud.githubusercontent.com/assets/13594347/9625421/cba119ea-511f-11e5-9d6e-96a7941e7728.png)
![fermat_bnk-6](https://cloud.githubusercontent.com/assets/13594347/9625422/cba9179e-511f-11e5-86a0-5d6a71261bb4.png)

**Comment by Luis-Fernando-Molina** [comment]
la 2da opcion va mejor. Sin tocar el techo, baja un poco la caja fuerte para que no toque el techo y hacela un poquito mas grande. 

Revisa los bordes blancos que tienen que estar del tamaño estandar por todos lados mas allá de las manipulaciones de escala que hayas hecho antes.

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina   listo los ajustes del techo y tamaño de la caja fuerte
![fermat_bnk](https://cloud.githubusercontent.com/assets/13594347/9647135/b572bb36-51a3-11e5-9ab8-4e4a2fea90dd.png)

**Comment by Luis-Fernando-Molina** [comment]
:+1: este pudiera quedar así

**Comment by arnaldos** [comment]
Perfecto, cerramos el caso con este.
