### ISSUE TITLE
Crear un icono cuya función sera contener todas las subapp Identity dentro de Fermat App

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#370]

**Comment by emmysm** [comment]
![icono](https://cloud.githubusercontent.com/assets/15143489/11388795/0c01c0d8-930c-11e5-8c0f-80155bf15e92.png)

![icono](https://cloud.githubusercontent.com/assets/15143489/11388771/ce4b595c-930b-11e5-8bca-aa06e87bb53b.png)

@arnaldos @Luis-Fernando-Molina

**Comment by Luis-Fernando-Molina** [comment]
hacete dos mascaras como las que se usan para representar el teatro, una sonriendo y otra triste, pudieran basarse en la mascara de anonymous

**Comment by emmysm** [comment]
![propuestas 3 y 4](https://cloud.githubusercontent.com/assets/15143489/11412624/4b9a4454-93b1-11e5-904a-fce4dafda0c0.png)
![propuestas 1 y 2](https://cloud.githubusercontent.com/assets/15143489/11412625/4bc47b48-93b1-11e5-812c-031765043e13.png)
@Luis-Fernando-Molina @arnaldos 
![screen](https://cloud.githubusercontent.com/assets/15143489/11412662/b38ec382-93b1-11e5-99ee-882abf48a16c.png)

**Comment by Luis-Fernando-Molina** [comment]
proba hacerla mas parecida a la mascara de "anonymous" googleala.

**Comment by emmysm** [comment]
Hola @Luis-Fernando-Molina , había hecho la forma de la máscara tomando de referencia la máscara de anonymus, pero no sabía que tan parecida la querías, ya hago los ajustes ;)

**Comment by emmysm** [comment]
![icono mascara de anonymus](https://cloud.githubusercontent.com/assets/15143489/11430769/b5bb6dde-945d-11e5-968a-eb91ea236c38.jpg)

![screen](https://cloud.githubusercontent.com/assets/15143489/11430841/e7e08e2e-945e-11e5-8b40-a2de289242c6.png)

@Luis-Fernando-Molina

**Comment by Luis-Fernando-Molina** [comment]
Por ahi puede andar, Aunque no veo que se parezca lo suficiente.

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina definí este icono para el contenedor de las identitys ya le paso a matias para que sustituya el icono
![icon](https://cloud.githubusercontent.com/assets/13594347/11887666/afa9b066-a508-11e5-8f65-e3d96dea5322.png)
