### ISSUE TITLE
Crear un icono cuya función sera contener todas las subapp Community dentro de Fermat App

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#371]

**Comment by ivonnesantos** [comment]
![contenedor_community-01](https://cloud.githubusercontent.com/assets/15238660/11382636/37f77b4c-92d5-11e5-97fc-123b8140862b.png)

@arnaldos @Luis-Fernando-Molina

**Comment by arnaldos** [comment]
@ivonnesantos propuesta 1 prueba otro fondo plz para probar como se ve :smile:

**Comment by ivonnesantos** [comment]
![contenedor_community-01-01](https://cloud.githubusercontent.com/assets/15238660/11383629/c80f93e4-92db-11e5-8423-8506d9f9fdfe.png)

@arnaldos

**Comment by arnaldos** [comment]
@ivonnesantos  planteate otra propuesta a ver plz !!

**Comment by ivonnesantos** [comment]
![contenedor_community-01](https://cloud.githubusercontent.com/assets/15238660/11400745/442bfe38-9361-11e5-8eb5-47ee458b53d3.png)

@arnaldos

**Comment by arnaldos** [comment]
@ivonnesantos  replanteate el icono partiendo de la propuesta 1

**Comment by ivonnesantos** [comment]
![371_contenedor_community-01](https://cloud.githubusercontent.com/assets/15238660/11443587/761acee8-94f0-11e5-96b3-0211899b7460.png)

@arnaldos propuestas a partir de la 1

**Comment by arnaldos** [comment]
@ivonnesantos por el momento la propuesta 7, muestrame unos ajustes de colores

**Comment by ivonnesantos** [comment]
@arnaldos propuestas de color
![371_contenedor_community-01](https://cloud.githubusercontent.com/assets/15238660/11510739/74dacea8-9837-11e5-94e8-6941df65a2bf.png)

**Comment by arnaldos** [comment]
@ivonnesantos vamos con propuestas 7_1 con el outline blanco

**Comment by ivonnesantos** [comment]
![371_contenedor_community-01](https://cloud.githubusercontent.com/assets/15238660/11514064/c82d26b2-9848-11e5-951d-05e712a2b51f.png)

@arnaldos Propuesta 7_1 con trazo

**Comment by arnaldos** [comment]
@ivonnesantos listo !! lo dejamos así :+1:

**Comment by ivonnesantos** [comment]
Propuesta luego de haber escuchado la observación de luis 
@arnaldos @Luis-Fernando-Molina 
![371_contenedor_community-01](https://cloud.githubusercontent.com/assets/15238660/11743520/68624e26-9fda-11e5-81a1-4c97182b822d.png)

**Comment by ivonnesantos** [comment]
agrego otra propuesta
![371_contenedor_community-01](https://cloud.githubusercontent.com/assets/15238660/11762763/5048bfa6-a0c4-11e5-8e96-0ca4d7d61b86.png)

@arnaldos @Luis-Fernando-Molina

**Comment by arnaldos** [comment]
@Ivonnesantos muéstrame otras propuestas plz

**Comment by ivonnesantos** [comment]
![371_contenedor_community-01](https://cloud.githubusercontent.com/assets/15238660/11828825/243c7f58-a36a-11e5-901b-4344493b3968.png)
@arnaldos @Luis-Fernando-Molina

**Comment by arnaldos** [comment]
@ivonnesantos  planteate otra propuestas basadas en la propuesta 10 y 5_1

**Comment by ivonnesantos** [comment]
![371_contenedor_community-01](https://cloud.githubusercontent.com/assets/15238660/11887813/eb64c892-a509-11e5-96d1-91c33a7c3b55.png)

@arnaldos @Luis-Fernando-Molina

**Comment by arnaldos** [comment]
@ivonnesantos replantea la propuesta plz

**Comment by ivonnesantos** [comment]
![371_contenedor_community-01](https://cloud.githubusercontent.com/assets/15238660/11915638/7d3f61d2-a681-11e5-9066-41f75f805482.jpg)

@arnaldos @Luis-Fernando-Molina

**Comment by arnaldos** [comment]
@ivonnesantos replantealos

**Comment by victoralfonzohd** [comment]
@arnaldos 

Rediseño del icono actual:

![371_contenedor_community](https://cloud.githubusercontent.com/assets/15219855/12273528/7470220c-b938-11e5-85b6-b3f581bd73c0.png)

---

Nuevas Propuestas

Propuesta 1:

![sin-titulo-1](https://cloud.githubusercontent.com/assets/15219855/12270521/a4d6a19c-b928-11e5-97cf-88590b6a7642.png)

Propuesta 2:

![icono_contenedor_communitys](https://cloud.githubusercontent.com/assets/15219855/12271340/a6c813c4-b92c-11e5-8681-5c26a0dc9f8b.png)

Propuesta 3:

![icono_contenedor_communitys](https://cloud.githubusercontent.com/assets/15219855/12271606/22959dfe-b92e-11e5-90ac-0da2ae70a5f3.png)

**Comment by arnaldos** [comment]
toma como base la propuesta 1. has propuestas de colores y genera otra propuesta partiendo de la base.

**Comment by victoralfonzohd** [comment]
@arnaldos 

Versión 1:

![1](https://cloud.githubusercontent.com/assets/15219855/12294450/c566fb92-b9cc-11e5-9510-1c7d2e40f5a3.png)

Versión 2:

![2](https://cloud.githubusercontent.com/assets/15219855/12294458/d048018c-b9cc-11e5-9c44-d88ea24afd08.png)

Versión 3:

![4](https://cloud.githubusercontent.com/assets/15219855/12294464/daadcf80-b9cc-11e5-89d9-f92a6e1a06b2.png)

Versión 4:

![3](https://cloud.githubusercontent.com/assets/15219855/12294468/e5b94db4-b9cc-11e5-8262-94c3c9bfc05b.png)

**Comment by arnaldos** [comment]
@victoralfonzohd no habia visto la version del rediseño .... plantea una fusion del rediseño con la propuesta 1

**Comment by victoralfonzohd** [comment]
@arnaldos 

![icono_contenedor_communitys](https://cloud.githubusercontent.com/assets/15219855/12302085/9b95b636-b9f5-11e5-9b8b-53721fab0c2d.png)

**Comment by arnaldos** [comment]
@victoralfonzohd :+1:

**Comment by arnaldos** [comment]
@astrih por favor retoma este caso, lo necesitamos con suma urgencia

**Comment by astrih** [comment]
@arnaldos 
Propuesta01
![iconofermatcommunity-01](https://cloud.githubusercontent.com/assets/17072146/13197543/beab5028-d7c2-11e5-9e21-1bb4086fea37.png)
Propuesta02
![iconofermatcommunity-02](https://cloud.githubusercontent.com/assets/17072146/13197544/beb08610-d7c2-11e5-832d-7dfe25b3532a.png)
Propuesta03
![iconofermatcommunity-03](https://cloud.githubusercontent.com/assets/17072146/13197545/beb6432a-d7c2-11e5-932f-23cbaea4a62f.png)
Propuesta04
![iconofermatcommunity-04](https://cloud.githubusercontent.com/assets/17072146/13197546/bebd74b0-d7c2-11e5-9b86-792d76efdbbb.png)
Aplicacion
![aplicacion](https://cloud.githubusercontent.com/assets/17072146/13197550/d8e48388-d7c2-11e5-878e-c1ce19d09290.png)

**Comment by arnaldos** [comment]
@astrih lo que propones tiene similitud a una propuesta que se trabajo anteriormente y no funciono, podemos hacer que los  user salgan de la parte interna del aro, eliminando la billetera. te dejo una muestra de la idea que te comento.
![untitled-1](https://cloud.githubusercontent.com/assets/13594347/13199908/041f4f4a-d806-11e5-9bf5-cb3302c60f5f.jpg)

**Comment by astrih** [comment]
@arnaldos los 4 iconos se propusieron antes? no estoy segura de entender la imagen que me envias, pero subo 2 propuestas adicionales

Propuesta05
![iconofermatcommunity-05](https://cloud.githubusercontent.com/assets/17072146/13203361/7318bd0a-d888-11e5-8ee9-e2817f215d5d.png)
Propuesta06
![iconofermatcommunity-06](https://cloud.githubusercontent.com/assets/17072146/13203364/80a3b7e0-d888-11e5-8b27-ef2283fc329b.png)

**Comment by arnaldos** [comment]
@astrih el aro de afuera mas chico, usa otra paleta de colores para ver como se comporta el icono de la propuesta 06

**Comment by astrih** [comment]
@arnaldos 
Propuesta07
![iconofermatcommunity-07](https://cloud.githubusercontent.com/assets/17072146/13237219/95ca8b20-d99c-11e5-89ce-cf828d88d7a7.png)

**Comment by arnaldos** [comment]
@astrih Propuesta 07 aprobada :smile_cat:
