### ISSUE TITLE
Crear un icono identificar el centro de soporte de Fermat App

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#372]

**Comment by victoralfonzohd** [comment]
@Luis-Fernando-Molina @arnaldos 

Propuesta 1:

Versión 1:

![centro de soporte](https://cloud.githubusercontent.com/assets/15219855/11402356/aeb10214-9369-11e5-834e-c3ccda2b5fae.jpg)

Versión 2: 

![centro-de-soporte-v1](https://cloud.githubusercontent.com/assets/15219855/11402430/132f88f0-936a-11e5-9b93-e97958cb07d2.jpg)

Icono:

![montaje-de-icono](https://cloud.githubusercontent.com/assets/15219855/11402503/7fbc3798-936a-11e5-9ee5-c1dd4ae3f079.png)

**Comment by victoralfonzohd** [comment]
@Luis-Fernando-Molina @arnaldos 

Propuesta 2:

Versión 1: 

![centro de soporte p2](https://cloud.githubusercontent.com/assets/15219855/11402696/64419872-936b-11e5-9625-a4499fd1dc17.jpg)

Versión 2:  

![centro de soporte p2 v1](https://cloud.githubusercontent.com/assets/15219855/11402707/70ffcd72-936b-11e5-9ae1-3a56742cee51.jpg)

Icono:

![montaje-de-icono](https://cloud.githubusercontent.com/assets/15219855/11402825/012e07a6-936c-11e5-9b35-56450a907a5c.png)

**Comment by arnaldos** [comment]
@victoralfonzohd plz realiza otra propuesta partiendo de la versión 1 de la propuesta 2 fijate que puedes hacer para que resalte mas el engranaje que la billetera

**Comment by victoralfonzohd** [comment]
@Luis-Fernando-Molina @arnaldos 

![centro-de-soporte-p2](https://cloud.githubusercontent.com/assets/15219855/11404122/8c52fbce-9372-11e5-9662-f05c3eb5cec1.jpg)

**Comment by Luis-Fernando-Molina** [comment]
El soporte tecnico normalmente se representa con una persona hablando con unos audifonos manos libres. No veo la relacion de los engranajes en este caso, ni el porque de la wallet.

**Comment by victoralfonzohd** [comment]
@Luis-Fernando-Molina @arnaldos Lo había visto mas por configuraciones, por eso use el engranaje.. El porque de la Wallet es por el simple hecho de identidad, creo que Fermat tiene una identidad muy marcada.. Por eso creo que lo mas conveniente es mantener esa linea y agregar el wallet, aqui otra propuesta:

![icono_centrodesopote_fermat](https://cloud.githubusercontent.com/assets/15219855/11409323/55e1cb1e-9391-11e5-8345-64cdf82201b7.jpg)

**Comment by victoralfonzohd** [comment]
@Luis-Fernando-Molina  @arnaldos  

Propuesta sin el Wallet

![icono_centrodesopote_fermat](https://cloud.githubusercontent.com/assets/15219855/11423875/71925052-941a-11e5-9d96-5a0a69076ef5.jpg)

**Comment by Luis-Fernando-Molina** [comment]
Preferiria que no haya un circulo que lo contenga. Otro tema es que cuando se achique quizas no se vea el mic. El tipo de adifono es mas para volar un helicóptero que para dar soporte tecnico JA JA

**Comment by victoralfonzohd** [comment]
@Luis-Fernando-Molina  @arnaldos 

Propuesta 3:

Versión 1:

![icono_centrodesopote_fermat](https://cloud.githubusercontent.com/assets/15219855/11425382/bf5c264e-9426-11e5-9459-af1d70e70490.jpg)

Versión 2:

![icono_centrodesopote_fermat1](https://cloud.githubusercontent.com/assets/15219855/11425423/0d38e6ea-9427-11e5-9ab3-0184ce066e26.jpg)

**Comment by victoralfonzohd** [comment]
@Luis-Fernando-Molina 

![icono_centrodesopote_fermat](https://cloud.githubusercontent.com/assets/15219855/11431562/1ed38342-946d-11e5-82a4-202c8717a9d4.jpg)

**Comment by Luis-Fernando-Molina** [comment]
Puede ir por el lado de la billetera con los audifonos puestos, proba algunas opciones en esa linea por favor.

**Comment by victoralfonzohd** [comment]
@Luis-Fernando-Molina 

![icono_centrodesopote_fermat](https://cloud.githubusercontent.com/assets/15219855/11447100/eb14cc2c-9512-11e5-9d38-1dc86a9a6eed.jpg)

**Comment by arnaldos** [comment]
@victoralfonzohd usa los primeros audifonos que planteastes y unelos con la billetera

**Comment by victoralfonzohd** [comment]
@Luis-Fernando-Molina  @arnaldos 

Version 1:

![icono_centrodesopote_fermat](https://cloud.githubusercontent.com/assets/15219855/11449269/33e85986-9541-11e5-99b9-524bccab7b7d.jpg)

Sin borde:

![icono_centrodesopote_fermat](https://cloud.githubusercontent.com/assets/15219855/11449279/7602dba2-9541-11e5-87b6-a922aa8cc8f1.jpg)

**Comment by victoralfonzohd** [comment]
@Luis-Fernando-Molina @arnaldos  Prueba de colores

Versión 1: 

![icono_centrodesopote_fermat_color1](https://cloud.githubusercontent.com/assets/15219855/11473807/dc68e0ec-9746-11e5-84dc-83911cf15286.jpg)

Versión 2:

![icono_centrodesopote_fermat_color2](https://cloud.githubusercontent.com/assets/15219855/11473810/e6366b4e-9746-11e5-9ab5-a6fed43272ac.jpg)

Versión 3:

![icono_centrodesopote_fermat_color3](https://cloud.githubusercontent.com/assets/15219855/11473814/f17a3b7a-9746-11e5-9301-4b4d1e474d2a.jpg)

**Comment by victoralfonzohd** [comment]
@Luis-Fernando-Molina @arnaldos 

Propuesta: 

![icono_centrodesopote_fermat](https://cloud.githubusercontent.com/assets/15219855/11536233/a903c9de-98e9-11e5-820a-06c552363553.jpg)

**Comment by victoralfonzohd** [comment]
@Luis-Fernando-Molina @arnaldos 

Propuesta:

Versión 1: 

![icono_centrodesopote_fermat](https://cloud.githubusercontent.com/assets/15219855/11538456/5b679ca4-98f4-11e5-99bf-be6f33921cc1.jpg)

Versión 2: 

![icono_centrodesopote_fermat1](https://cloud.githubusercontent.com/assets/15219855/11538483/7359ee66-98f4-11e5-84ea-5524814252bd.jpg)
