### ISSUE TITLE
Mejorar visualmente el Header del Navigation view (drawer) de la Bitcoin Wallet que contendrá el espacio vació de la foto del perfil del usuario

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#373]
## Alta prioridad

Realizar propuestas del header en este caso se debe plantear un diseño bastante elaborado que marque la diferencia. 

No se debe conformar con solo colocar el icono que represente el usuario.

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina  para el header del Navigation view propongo realizar ilustraciones que predeterminadas que permitan al usuario sentirse cómodo permitiendo, elegir si quieren mostrar algunos de los **characters** ilustrados o una foto, haciendo de esta aplicación algo mas dinámica. 

Si la idea funciona podremos realizar distintas ilustraciones con este estilo gráfico que nos permita estandarizar las imagenes de los **characters**

![avatar-1](https://cloud.githubusercontent.com/assets/13594347/11390573/b3f2f67a-931d-11e5-8f7a-0e9a1e2bb6cb.png)

![view_navigation_v4_ar](https://cloud.githubusercontent.com/assets/13594347/11390636/552614aa-931e-11e5-8c09-766d077bb67e.png)

**Comment by Luis-Fernando-Molina** [comment]
Me gustó la idea. Hace el primer caracter mas integrado a los colores de esta wallet. Lo mismo el fondo, ponele algo que lo integre.

Name Profile debiera ser: Alias

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina perfecto !! ya me pongo con eso

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina  los ajustes del avatar 

Versión 2

![avatar2](https://cloud.githubusercontent.com/assets/13594347/11402839/0cecaf16-936c-11e5-940c-ca370aff5bed.png)

![view_navigation_v4_ar3](https://cloud.githubusercontent.com/assets/13594347/11402857/21d3b96a-936c-11e5-85d3-48d2b55b3632.png)

Versión 3

![avatar3](https://cloud.githubusercontent.com/assets/13594347/11402849/13f6f24e-936c-11e5-889b-88e06c4b7aac.png)

![view_navigation_v4_ar1](https://cloud.githubusercontent.com/assets/13594347/11402871/28f89062-936c-11e5-9af0-28f4d865a47d.png)

Versión 4

![avatar4](https://cloud.githubusercontent.com/assets/13594347/11402851/16c78286-936c-11e5-955f-f4606e9b14b9.png)

![view_navigation_v4_ar2](https://cloud.githubusercontent.com/assets/13594347/11402878/2d6a9dde-936c-11e5-807f-9d952adabfc9.png)

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina me apunto por la versión 3 esta mas ligera y lleva los colores de la identidad aplicados de una manera mas sutil que lo hace a la vista mas atractivo.

**Comment by Luis-Fernando-Molina** [comment]
:+1: Version 3

**Comment by furszy** [comment]
@Luis-Fernando-Molina 
La imágen de profile no debe tener sexo ya que la wallet puede ser utilizada tanto por hombres y mujeres indistintamente.

**Comment by Luis-Fernando-Molina** [comment]
@furszy Luego se va a poder elegir otra con un swipe. Ademas con la que hay no se le ve el sexo, puede ser una mujer disfrazada :smile:

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina @furszy  les presento a la sra doe .. ya la subo al repo para que @furszy la pueda aplicar en la app 

![profile_female](https://cloud.githubusercontent.com/assets/13594347/11905896/3ba7dd1c-a59b-11e5-8f33-bcbe7402a339.png)
