### ISSUE TITLE
Composición artística Nº2 con la moneda 3D Fiat Euro

### ISSUE THREAD

**Issue by jonathanborges3d** [bitDubai/fermat-graphic-design#374]
Viene del #182 

@Luis-Fernando-Molina Primera versión:

![alt text](https://raw.githubusercontent.com/bitDubai/fermat-graphic-design/db0bf8e9d5ccebaf1146ac4df2878e554d68d4d2/3D%20Design/3DArtScenes/FiatCoins/Fiat_euro_art_2.jpg?token=ANBHS1PHnx8mdcfkSb5zWv97NCJaacotks5WaL-3wA%3D%3D)

**Comment by Luis-Fernando-Molina** [comment]
la pila de monedas se ve bien, aunque deberias mostrar en la imagen desde la primera de abajo. La torre atras no me gusta mucho. Proba con otros fondos please.

**Comment by jonathanborges3d** [comment]
@Luis-Fernando-Molina Segunda versión:

![](https://raw.githubusercontent.com/bitDubai/fermat-graphic-design/7ce66246425692a84960405da5333a75d0b4cbcf/3D%20Design/3DArtScenes/FiatCoins/Fiat_euro_art_2.jpg?token=ANBHS_Cgbh1Bumpamgs3avN7HKu7ADycks5Wah3PwA%3D%3D)

**Comment by Luis-Fernando-Molina** [comment]
esta mejor, aunque no necesariamente super cool. No habra algun fondo royalty free super cool sobre el cual se pueda poner la escena? propone algunas opciones please

**Comment by jonathanborges3d** [comment]
@Luis-Fernando-Molina Una versión con fondo blanco para READMEs:

![fiat_euro_art_3_wb](https://cloud.githubusercontent.com/assets/13649739/11749995/297d39c2-a003-11e5-9062-e82ef4995eef.jpg)

**Comment by Luis-Fernando-Molina** [comment]
ok, perdecto, no te olvides que cuando la agregues en el media kit, la tenes que agregar tambien al README del media kit, que es como un catalogo de lo que está ahi.
