### ISSUE TITLE
DAP Asset Issuer / Assets User Delivered List

### ISSUE THREAD

**Issue by Neoperol** [bitDubai/fermat-graphic-design#376]
#332

Diseño de la vista de los usuarios a los que se les entrego un respectivo Asset, mostrando los estados en los cual se encuentra el asset. 

![delivered_1](https://cloud.githubusercontent.com/assets/6201081/11397383/3594e828-934b-11e5-96a4-25064db38ba2.png)

@Luis-Fernando-Molina 
@acostarodrigo

**Comment by Neoperol** [comment]
Propuesta vista, de la lista de usuarios a que se le enviaron Assets. 

![view_user_list](https://cloud.githubusercontent.com/assets/6201081/11915048/88420de2-a667-11e5-8091-2a842b465c4c.jpg)

@acostarodrigo 
@Luis-Fernando-Molina

**Comment by acostarodrigo** [comment]
@Neoperol perfecta.
cc @javafrank @nindriago

**Comment by javafrank** [comment]
@Neoperol desde donde podriamos acceder a esta pantalla? imagino que desde la vista de detalle pero aun no tengo claro que opcion es la correcta para que aparezca esta vista, esta vista muestra lo que pasó con los assets que fueron distribuidos.

cc @nindriago @acostarodrigo

**Comment by Neoperol** [comment]
https://github.com/bitDubai/fermat-graphic-design/issues/367

En la parte de abajo esta la lista de los Assets que se enviaron, esta lista es la primera, donde se ven todos los usuarios a los que se les envio este asset en particular. Seria buena discutir si son necesarias las otras vistas donde solo se muetran la lista de usuario por estatus, como Redeem o Unused. 

En el texto de colores esta toda la información, para armar la vista.

@javafrank
