### ISSUE TITLE
DAP Asset Issuer / Assets User Redeemed List

### ISSUE THREAD

**Issue by Neoperol** [bitDubai/fermat-graphic-design#377]
#332

Diseño de la vista de los usuarios a los que han redemido el Asset, esta vista se abre desde la vista de detalle del Asset. 

![redeemed](https://cloud.githubusercontent.com/assets/6201081/11397600/e8becbd4-934c-11e5-88fb-042ae8547caa.png)

@Luis-Fernando-Molina 
@acostarodrigo

**Comment by Neoperol** [comment]
![view_user_list](https://cloud.githubusercontent.com/assets/6201081/12130827/0c12241a-b3e0-11e5-8997-6a62b42fc138.jpg)

@acostarodrigo

**Comment by acostarodrigo** [comment]
cc @nindriago @javafrank
