### ISSUE TITLE
DAP Asset Issuer / Navigation Drawer

### ISSUE THREAD

**Issue by Neoperol** [bitDubai/fermat-graphic-design#380]
#332

Diseño de la vista Navigation Drawer de la Asset Issuer. 

![menu](https://cloud.githubusercontent.com/assets/6201081/11398780/12c80f78-9355-11e5-9ab5-b65a145e9417.png)

@Luis-Fernando-Molina 
@acostarodrigo

**Comment by Neoperol** [comment]
Propuesta para el NAvigation Drawer. 

![view_navigation](https://cloud.githubusercontent.com/assets/6201081/11635544/acb8e290-9ce9-11e5-8de4-fac532285046.jpg)

@acostarodrigo 
@Luis-Fernando-Molina

**Comment by acostarodrigo** [comment]
@nindriago si @javafrank toma la del detalle del Asset, por favor prioriza entonces esta pantalla.

**Comment by nindriago** [comment]
Buenas tardes, por favor necesito las images (png) del navigation drawer.

My Assets
History
Stadistics
Users

gracias :)

**Comment by nindriago** [comment]
Igualmente necesito el drawer_body que se visualizara de fondo en el navigation_drawer, por favor

**Comment by nindriago** [comment]
Buenos dias chicos, por favor quien me puede ayudar en esto que necesito. 

@Neoperol  @acostarodrigo  @arnaldos

**Comment by Neoperol** [comment]
![view_navigation](https://cloud.githubusercontent.com/assets/6201081/12130549/75e0c17e-b3dd-11e5-8938-8cc48ae3975b.jpg)

Actualización del Navigation Drawer. 
Solo va a tener estas vistas principales. 
My Assets
History
Stadistics

@acostarodrigo 
@nindriago

**Comment by acostarodrigo** [comment]
de acuerdo
cc @javafrank
