### ISSUE TITLE
Diseño del Fermat Application Token

### ISSUE THREAD

**Issue by jonathanborges3d** [bitDubai/fermat-graphic-design#382]
@Luis-Fernando-Molina 

Concepto inicial:

![](http://www.attraction-tickets.info/wp-content/uploads/2012/08/tickets.jpg)

Primera Versión 3D:

![token_1](https://cloud.githubusercontent.com/assets/13649739/11453053/b36f70c6-95ce-11e5-8b25-e74fb5cf10e1.jpg)

![token_2](https://cloud.githubusercontent.com/assets/13649739/11453080/72abd0f6-95cf-11e5-8c35-d6c319557b0d.jpg)

Hice una variante del circuito presente en la moneda de Fermat/Bitcoin, adaptado a la forma rectangular del objeto. Faltaría definir qué deberá ir en los espacios laterales, dónde están en la referencia los números: 123456.

**Comment by Luis-Fernando-Molina** [comment]
va bien.

A los costados pudiera decir "one fermat" . Ojo que en minusculas fermat en este caso prque se refiere al token y no al proyecto.

Los bordes los veo muy simples, fijate si le podes poner la decoracion del borde de la moneda.

Las lineas del circuito las veo muy gruesas para el tamaño del toquen. Quizas la palabra Fermat no deba ir junto al logo en este caso.

El dentado de los costados pudiera ser mas sutil

Se nota la circunferencia en las puntas.

**Comment by jonathanborges3d** [comment]
@Luis-Fernando-Molina Segunda versión:

![token_3](https://cloud.githubusercontent.com/assets/13649739/11454020/06e12ab0-95f2-11e5-8281-da31cf98bbc2.jpg)

**Comment by Luis-Fernando-Molina** [comment]
los dos "one fermat" deberian ir enla misma direccion.

El logo ponelo mas centrado verticalmente. 

Fijate si le podes poner la decoracion de la moneda que estaba del lado interno del borde por favor.

**Comment by jonathanborges3d** [comment]
@Luis-Fernando-Molina Tercera versión con los cambios sugeridos:

![token_4](https://cloud.githubusercontent.com/assets/13649739/11454505/28a8b63c-9600-11e5-80a1-b5dac0a32588.jpg)

**Comment by Luis-Fernando-Molina** [comment]
las lineas quedaron muy finitas, quedan mejor como estaban antes, sorry.

Proba el chanfle mas pequeño please. Mas sutil.

Proba otra version mas con cobre de fondo.

**Comment by jonathanborges3d** [comment]
@Luis-Fernando-Molina Tres versiones con las modificaciones:

![token_5](https://cloud.githubusercontent.com/assets/13649739/11454839/b1664858-9610-11e5-9dd2-1d6e8426f506.jpg)

![token_6](https://cloud.githubusercontent.com/assets/13649739/11454857/33c3705a-9611-11e5-90f8-55d019b62c89.jpg)

![token_7](https://cloud.githubusercontent.com/assets/13649739/11454872/d06f1efe-9611-11e5-8ba2-5907f038320a.jpg)

**Comment by Luis-Fernando-Molina** [comment]
Perdón,  me refería al mismo dorado,  pero con cobre de fondo

**Comment by Luis-Fernando-Molina** [comment]
El chanfle esta bien así pero le sacaste el dentado...

**Comment by Luis-Fernando-Molina** [comment]
perdon, en el celu no se veia.

**Comment by Luis-Fernando-Molina** [comment]
Ahora en la compu veo que achicaste el dentado y no el chanfle. Me refiero a viselado del borde.

**Comment by jonathanborges3d** [comment]
@Luis-Fernando-Molina :smile: Ok, no entendía bien lo del chanfle, pensaba que era el dentado.

Hice una nueva versión:

![token_8](https://cloud.githubusercontent.com/assets/13649739/11459835/f80259f4-96b1-11e5-8f11-326c42791658.jpg)

**Comment by Luis-Fernando-Molina** [comment]
Puede ser, podes aplicarle al cobre un pattern como el del billete que estabas haciendo?

**Comment by jonathanborges3d** [comment]
@Luis-Fernando-Molina Con el patrón aplicado:

![token_9](https://cloud.githubusercontent.com/assets/13649739/11460842/31a9a4c2-96c7-11e5-8a99-414cf3aa9998.jpg)

**Comment by Luis-Fernando-Molina** [comment]
Va quedando, no podés poner una flor del patron atras de la billetera? a ver como queda. Tambien agranda un poco el dentado, un termino medio entre el original y este por favor.

**Comment by jonathanborges3d** [comment]
@Luis-Fernando-Molina Incluí un patrón gilloché bajo el logo de Fermat y en las esquinas redondeadas También volví a modelar el dentado para hacerlo un poco más grande.

![token_10](https://cloud.githubusercontent.com/assets/13649739/11461406/f375017a-96d4-11e5-9117-b0bb5c5b7264.jpg)

**Comment by Luis-Fernando-Molina** [comment]
Ahi va quedando. Probemos lo siguiente:
1. Que en vez de decir "one fermat" diga "fermat" y un poquito mas grande y gureso.
2. Poner el numero 1 en un par de esquinas del circuito para representar que es un Fermat, como se hace en los billetes.

**Comment by arnaldos** [comment]
@jonathanborges3d  una sugerencia voltea el texto de **Fermat** has que quede la lectura de abajo hacia arriba es mas fácil a para las personas, ya que las personas leen de izquierda a derecha. :smile:

**Comment by jonathanborges3d** [comment]
@arnaldos Gracias! sugerencia aplicada :+1: 
@Luis-Fernando-Molina Nueva versión: Coloqué los dos numeros "1" en las esquinas, pero lo hice incluyéndolos como parte del circuito:

![alt text](https://raw.githubusercontent.com/bitDubai/fermat-graphic-design/4ade4413c5a05fcad74110832e7aa9990ba365f3/Drafts/3D%20Design/token_11.jpg?token=ANBHS_iAaEmI6BRTieVcR-pmtVJHUf6iks5WZ29wwA%3D%3D)

**Comment by Luis-Fernando-Molina** [comment]
Proba que solo sea el 1 sin la placa. Mas o menos de ese tamaño y grueso el numero.

**Comment by Luis-Fernando-Molina** [comment]
Proba que solo sea el 1 sin la placa. Mas o menos de ese tamaño y grueso el numero.

**Comment by jonathanborges3d** [comment]
@Luis-Fernando-Molina nueva versión:

![](https://raw.githubusercontent.com/bitDubai/fermat-graphic-design/17f462dd1f660ce4cb017340b5f3a752bde48beb/Drafts/3D%20Design/token_11.jpg?token=ANBHS9HTUXPgPCYFRZjn6-AZx_24j-5Wks5WaLwcwA%3D%3D)

**Comment by Luis-Fernando-Molina** [comment]
ok va bien, fijate de ponerle otro tipo de letra al 1 que se note mas. FIjate de las que tienen una base abajo, pero que no se pierda el ancho que asi esta bien.

**Comment by jonathanborges3d** [comment]
@Luis-Fernando-Molina Con el cambio de tipografía:
![](https://raw.githubusercontent.com/bitDubai/fermat-graphic-design/fe26be02469efcb9c7012918a0f0e89e73c124b8/Drafts/3D%20Design/token_11.jpg?token=ANBHS6nRMnCCBEvG2wCHoVmnOl1zXYQOks5WaN9WwA%3D%3D)

**Comment by Luis-Fernando-Molina** [comment]
ahi esta vamos a dejarlo asi.

Genera por favor los diferentes formatos incluyendo el que iria en la misma posicion a la moneda sobre fondo blanco para ponerlo en presentaciones y README.

**Comment by jonathanborges3d** [comment]
@Luis-Fernando-Molina Ok, puede ser así la que se use en los README?
![token_13](https://cloud.githubusercontent.com/assets/13649739/11605263/829889a2-9acd-11e5-958f-096ef96961d7.png)

**Comment by Luis-Fernando-Molina** [comment]
No, tiene que ser con el mismo efecto que tienen las monedas, desde el mismo angulo , misma iluminacion, mismo reflejo, etc.

**Comment by jonathanborges3d** [comment]
@Luis-Fernando-Molina Ok, aquí está en las mismas condiciones que las monedas:

![token_14](https://cloud.githubusercontent.com/assets/13649739/11636253/6660068a-9ced-11e5-91b5-b3c741c916cd.jpg)

**Comment by Luis-Fernando-Molina** [comment]
perfecto , rota 180 las dos palabras Fermat y quedria.

**Comment by jonathanborges3d** [comment]
@Luis-Fernando-Molina Con el texto rotado:

![token_15](https://cloud.githubusercontent.com/assets/13649739/11642067/21910402-9d0e-11e5-986e-5e03f0c32436.jpg)

**Comment by Luis-Fernando-Molina** [comment]
lo siento , estaba mejor para el otro lado. Volvelo como estaba y cerremos el caso.

**Comment by jonathanborges3d** [comment]
Listo, ya está en el repositorio de media-kit, también va para el de diseño gráfico.
