### ISSUE TITLE
Crear un Logo para Fermat CER (Currency Exchange Rates)

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#384]
Fermat CER es una súper capa que va a encargarse de ofrecer precios de mercado a los plugins de la plataforma, así como lo hace dólar today, surbitcoin o coinbase.

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina, @nelsonalfo aqui una propuesta para el logo de la capa 

![fermat_cer](https://cloud.githubusercontent.com/assets/13594347/11513512/d5884560-9845-11e5-8717-98b4cb1ffe78.png)

**Comment by nelsonalfo** [comment]
me gusta! :+1:

**Comment by Luis-Fernando-Molina** [comment]
Hace una mezcla del logo de MKT con las moneditas esas. Osea el grafico de barras abajo y las moneditas que salgan por detras.

**Comment by arnaldos** [comment]
ok perfecto !!

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina me a punto por la versión 2 

Versión 1
![fermat_cer_1](https://cloud.githubusercontent.com/assets/13594347/11816167/732f0da4-a321-11e5-8006-8b6d4d818cd5.png)

Versión 2

![fermat_cer_2](https://cloud.githubusercontent.com/assets/13594347/11816180/89a1813e-a321-11e5-804e-64840b63738a.png)

Versión 3

![fermat_cer_3](https://cloud.githubusercontent.com/assets/13594347/11816187/937ea0ba-a321-11e5-8d53-279f4748690b.png)

**Comment by ivonnesantos** [comment]
![fermat_cer-05](https://cloud.githubusercontent.com/assets/15238660/11987256/06016612-a9ae-11e5-8951-cab616964277.jpg)

@arnaldos @Luis-Fernando-Molina

**Comment by arnaldos** [comment]
las barra de finanzas ponlas mas planas plz y verifica las sombras

**Comment by ivonnesantos** [comment]
propuesta_2
![fermat_cer-06](https://cloud.githubusercontent.com/assets/15238660/12028310/79794a7c-ada7-11e5-9e85-7797313b2b0f.jpg)

Propuesta_3
![fermat_cer-07](https://cloud.githubusercontent.com/assets/15238660/12028315/8ebd4c44-ada7-11e5-872f-89f569f3eb90.jpg)

@arnaldos @Luis-Fernando-Molina

**Comment by Luis-Fernando-Molina** [comment]
La propuesta 3 puede andar :+1:   Asegurate que llegue a fermat.org. Gracias

**Comment by arnaldos** [comment]
@ivonnesantos toma en cuenta el espesor de los stroke blanco que llevan los elementos fíjate en los otros logos para que se mantenga la misma proporción, y ajusta la sombra que esta por detrás de todos los elementos. debe tener una inclinación de 45º. revisa eso antes de que pase a fermat org
