### ISSUE TITLE
Crear banner de presentación para la Asset Issuer wallet

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#387]
El Banner de presentación o gráfico de funciones es una potente herramienta que permite mostrar tus recursos creativos y atraer a los usuarios. Este sera publicado en la Wallet Store.

Requisitos

Archivo JPEG o PNG de 24 bits (no alpha)
Tamaño: 1024x500 píxeles

**Comment by arnaldos** [comment]
Identidad de la wallet

![asset_issuer](https://cloud.githubusercontent.com/assets/13594347/11580879/3468b370-9a0e-11e5-8214-10814bf2f61e.png)

**Comment by arnaldos** [comment]
Viene del #131

**Comment by emmysm** [comment]
![propuesta 2](https://cloud.githubusercontent.com/assets/15143489/11598139/550e3d50-9a92-11e5-99e2-3aef0a8b1410.jpg)
![propuesta 3](https://cloud.githubusercontent.com/assets/15143489/11598140/55173ba8-9a92-11e5-9103-ff020f5a7a77.jpg)

@arnaldos @Luis-Fernando-Molina
