### ISSUE TITLE
Crear banner de presentación para la Asset User Wallet

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#388]
El Banner de presentación o gráfico de funciones es una potente herramienta que permite mostrar tus recursos creativos y atraer a los usuarios. Este sera publicado en la Wallet Store.

Requisitos

Archivo JPEG o PNG de 24 bits (no alpha)
Tamaño: 1024x500 píxeles

**Comment by arnaldos** [comment]
Identidad de la wallet

![asset_user_wallet](https://cloud.githubusercontent.com/assets/13594347/11580905/65433e84-9a0e-11e5-8ee2-ff5c277920f8.png)

**Comment by arnaldos** [comment]
viene del #134

**Comment by arnaldos** [comment]
se definió este banner para esta wallet provisionalmente 

![banner_asset_user_wallet](https://cloud.githubusercontent.com/assets/13594347/13120810/a0789568-d581-11e5-8a6a-4f6a2df7cc9b.png)

**Comment by ivonnesantos** [comment]
@MaviDavsa ve si puedes crear una mejor propuesta para esto ese logo esta en el repositorio 2d/icons_sub_apps_icon_asset_user_wallet alli puedes encontrar el editable crea la carpeta en Draft issue_388_Banner_asset_user_wallet las medidas las indica arnaldo arriba

**Comment by arnaldos** [comment]
@ivonnesantos  incluso el icono creo podemos mejorarlo también no se que te parece ?

**Comment by ivonnesantos** [comment]
@arnaldos si puede se el caso de ese icono aun esta abierto?

**Comment by MaviDavsa** [comment]
![propuestas](https://cloud.githubusercontent.com/assets/17273005/13798205/0b095c22-eae6-11e5-836a-ffed52633c4b.jpg)

@ivonnesantos  :))

**Comment by ivonnesantos** [comment]
@MaviDavsa yo no veo mucha diferencia en el icono. El mapa no va muy bien con este tema la asset usser es algo más de compra de consumo que de conexion global si bien existe una conexión no seria como tal algo enfocado en lo global  vamos a seguir con el estilo de la dos pero diagramada como la tres, un detalle las cosas que descargues de internet cambialas un poquito. Esos cuadritos de colores donde pusiste los teléfonos ponle los colores del logo de asset user que creo que tiene bastantes.

**Comment by MaviDavsa** [comment]
![banner_ asser_ user](https://cloud.githubusercontent.com/assets/17273005/13800085/c1d947a8-eaf7-11e5-9019-0ef11d4e674c.png)

@ivonnesantos Algo asì!
