### ISSUE TITLE
Crear banner de presentación para la Redeem Point Wallet

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#389]
El Banner de presentación o gráfico de funciones es una potente herramienta que permite mostrar tus recursos creativos y atraer a los usuarios. Este sera publicado en la Wallet Store.

Requisitos

Archivo JPEG o PNG de 24 bits (no alpha)
Tamaño: 1024x500 píxeles

**Comment by arnaldos** [comment]
Identidad de la wallet 

![redeempoint-512x512](https://cloud.githubusercontent.com/assets/13594347/11580867/09f89e84-9a0e-11e5-84dd-14f4c8d603bc.png)

**Comment by arnaldos** [comment]
viene del #137

**Comment by victoralfonzohd** [comment]
@arnaldos @Luis-Fernando-Molina 

![banner-redeem-point-wallet](https://cloud.githubusercontent.com/assets/15219855/11634906/8388d9ba-9ce5-11e5-9f9b-527feaafefec.jpg)

**Comment by arnaldos** [comment]
@victoralfonzohd @Luis-Fernando-Molina  por el momento esta este banner aprobado provisionalmente 
![banner-redeem-point](https://cloud.githubusercontent.com/assets/13594347/11642465/1f11172e-9d10-11e5-851d-2ec0e6ab8d3e.jpg)
