### ISSUE TITLE
proponer mejoras del Navigation Drawer view de la Broker Wallet

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#390]
viene de https://github.com/bitDubai/fermat-graphic-design/issues/275

**Comment by victoralfonzohd** [comment]
@Luis-Fernando-Molina @arnaldos @nelsonalfo 

Propuesta1:

![view_navigation_propuesta-3](https://cloud.githubusercontent.com/assets/15219855/11595759/4370682a-9a83-11e5-8b46-2c6aacbfa981.jpg)

Propuesta 2:

![view_navigation_propuesta 1](https://cloud.githubusercontent.com/assets/15219855/11595786/5fcba23c-9a83-11e5-9cf0-007efbf7698b.jpg)

Se podría agregar un recuadro que nos permita ver con mas facilidad donde nos posicionamos dentro de las opciones del view

![view_navigation_propuesta 2](https://cloud.githubusercontent.com/assets/15219855/11595830/9c8fadf8-9a83-11e5-848c-5ba11a34a62f.jpg)

**Comment by nelsonalfo** [comment]
me gusta mas la propuesta 3
