### ISSUE TITLE
Crear una identidad (Logo) para la **Banking Wallet** que sera implementado como icono dentro de la App de Fermat

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#391]
Es una wallet donde puedes tener cuentas de un banco, sera un administrador de cuentas bancarias, ahí se realizaran operaciones de Depósitos, Transferencias, Consulta de saldo, Movimientos.

**Comment by emmysm** [comment]
![wallet2-02](https://cloud.githubusercontent.com/assets/15143489/11726287/20ce8a64-9f50-11e5-863d-a77cef9819de.png)
![wallet-01](https://cloud.githubusercontent.com/assets/15143489/11726288/20f8cb9e-9f50-11e5-8c89-39050325d392.png)
![67d078b2-8d46-11e5-9a10-4794ed115e7a](https://cloud.githubusercontent.com/assets/15143489/11726291/24b55734-9f50-11e5-854e-0f441d4d1e18.png)

@arnaldos @Luis-Fernando-Molina

**Comment by victoralfonzohd** [comment]
@arnaldos

Propuesta de color:

Versión 1:

![wallet1](https://cloud.githubusercontent.com/assets/15219855/11886626/638b947e-a4fe-11e5-81c3-b75bc52ba490.jpg)

Versión 2: 

![wallet](https://cloud.githubusercontent.com/assets/15219855/11886632/77a1b16e-a4fe-11e5-9616-2cc14824a115.jpg)

**Comment by arnaldos** [comment]
@victoralfonzohd otra propuesta !

**Comment by victoralfonzohd** [comment]
@arnaldos 

Nueva propuesta:

![icono_bankingwallet](https://cloud.githubusercontent.com/assets/15219855/11888683/76c4036e-a512-11e5-8090-e287662ae209.jpg)

**Comment by arnaldos** [comment]
@victoralfonzohd  replantea el techo no se si cambiar una combinación de colores tal ves evalualo, el plano que esta a la derecha de la columna eliminala. vamos a ver que tal se ve

**Comment by victoralfonzohd** [comment]
@arnaldos 

Izq: Con el plano a la derecha de la columna 

Der: Sin el plano 

![sin-titulo-1](https://cloud.githubusercontent.com/assets/15219855/11889253/67f6e5f2-a519-11e5-9ea2-fb62ae80ddd3.jpg)

Propuestas para el techo:

Versión 1: 

![icono_bankingwallet](https://cloud.githubusercontent.com/assets/15219855/11889381/ef5bcf7a-a51a-11e5-853c-26a6faf71923.jpg)

Versión 2: 

![icono_bankingwallet-1](https://cloud.githubusercontent.com/assets/15219855/11889384/f6011920-a51a-11e5-8c42-b4b96e437090.jpg)

Version 3:

![icono_bankingwallet-2](https://cloud.githubusercontent.com/assets/15219855/11889386/fe0393e6-a51a-11e5-96b2-555f23d77bf4.jpg)

Version 4:

![icono_bankingwallet3](https://cloud.githubusercontent.com/assets/15219855/11889390/0493553e-a51b-11e5-8d9c-40e12d3cf457.jpg)

**Comment by arnaldos** [comment]
@victoralfonzohd  versión 2 con el triangulo interno del techo en azul

**Comment by victoralfonzohd** [comment]
@arnaldos 

![icono_bankingwallet](https://cloud.githubusercontent.com/assets/15219855/11889513/30d1d390-a51c-11e5-9c43-232bbaa6c670.jpg)

**Comment by arnaldos** [comment]
@victoralfonzohd perfecto !! solo aumenta el tamaño de las monedas un poco para darle mayor jerarquía

**Comment by victoralfonzohd** [comment]
@arnaldos 

![logo_banking_wallet](https://cloud.githubusercontent.com/assets/15219855/11889809/4e80b62e-a51f-11e5-9c8e-a27ba9562bc0.jpg)

**Comment by arnaldos** [comment]
@victoralfonzohd listo !!! queda así genera los archivos :+1:

**Comment by victoralfonzohd** [comment]
Ya subo los archivos al repo!!

**Comment by victoralfonzohd** [comment]
@arnaldos 

Mejoras de color para logo actual:

Versión 1:

![1](https://cloud.githubusercontent.com/assets/15219855/12300960/e20117ec-b9ef-11e5-96bf-c939dadce92d.jpg)

Versión 2:

![2](https://cloud.githubusercontent.com/assets/15219855/12300972/ecfa695a-b9ef-11e5-803d-82306e455435.jpg)

---

Nuevas Propuestas:

Propuesta 1:

![3](https://cloud.githubusercontent.com/assets/15219855/12300986/01a6b890-b9f0-11e5-9c41-1380cd750e9d.jpg)

Propuesta 2:

![4](https://cloud.githubusercontent.com/assets/15219855/12301004/141369d8-b9f0-11e5-92d1-9ca850b42235.jpg)

Propuesta 3:

![5](https://cloud.githubusercontent.com/assets/15219855/12301009/1b2f0f6a-b9f0-11e5-93cf-69c6828b4c97.jpg)

**Comment by arnaldos** [comment]
ponlos sobre el desktop para ver como se comporta

**Comment by victoralfonzohd** [comment]
@arnaldos 

![montaje-de-icono](https://cloud.githubusercontent.com/assets/15219855/12301747/dd73d29c-b9f3-11e5-9ae3-5758c23e62e3.png)

**Comment by arnaldos** [comment]
viéndolos todos, se aprecia cierta similitud entre ellos, genera una propuesta nueva para el icono de esta app

**Comment by victoralfonzohd** [comment]
@arnaldos 

Nueva propuesta:

Versión 1: 

![1](https://cloud.githubusercontent.com/assets/15219855/12335196/1c9cca96-bad0-11e5-8f40-f0dffbd0c080.jpg)

Versión 2:

![mejoras-banking-wallet](https://cloud.githubusercontent.com/assets/15219855/12335205/26bebfde-bad0-11e5-821e-f93fef18b7f0.jpg)

Versión 3:

![2](https://cloud.githubusercontent.com/assets/15219855/12335211/324c4c36-bad0-11e5-86ee-65413a1a3416.jpg)

**Comment by victoralfonzohd** [comment]
@arnaldos 

![mejoras-banking-wallet](https://cloud.githubusercontent.com/assets/15219855/12337860/c2f19a12-bade-11e5-93b4-074fd456a8b3.jpg)

**Comment by victoralfonzohd** [comment]
@arnaldos 

Cambios en la dirección de las sombras

![mejoras-banking-wallet](https://cloud.githubusercontent.com/assets/15219855/12337947/4e54933e-badf-11e5-8f21-4adcf27b8cda.jpg)

**Comment by arnaldos** [comment]
@victoralfonzohd no me parece que este mal pero esta versión parece una caja fuerte, prueba otra versión plz

**Comment by victoralfonzohd** [comment]
@arnaldos 

Versión 1:

![2](https://cloud.githubusercontent.com/assets/15219855/12353599/8efdf294-bb62-11e5-9055-f135d7c949c7.jpg)

Versión 2:

![1](https://cloud.githubusercontent.com/assets/15219855/12353606/953ec3c2-bb62-11e5-847d-619c147e26cf.jpg)

Versión 3:

![3](https://cloud.githubusercontent.com/assets/15219855/12353613/99da257a-bb62-11e5-8fd5-0be5dd58a74c.jpg)

**Comment by arnaldos** [comment]
@victoralfonzohd la sintesis de la estructura que representa a un banco no me parece que esta mal. lo que veo es que aun no trasmite la idea de que es una wallet. busca darle ese enfoque. el broche en el techo no va a funcionar parace una chimenea, replantea eso del broche.

**Comment by victoralfonzohd** [comment]
@arnaldos 

Nuevas Propuestas:

P1:

![3](https://cloud.githubusercontent.com/assets/15219855/12393485/29ec86fa-bdc8-11e5-9ec3-0f1aaf6a424c.png)

P2:

![2](https://cloud.githubusercontent.com/assets/15219855/12393489/2ee6fa78-bdc8-11e5-88cb-450d64e2bfff.png)

P3:

![1](https://cloud.githubusercontent.com/assets/15219855/12393500/42c4ab94-bdc8-11e5-8b01-4dce5600b1e5.png)

**Comment by victoralfonzohd** [comment]
@arnaldos 

P4:

![mejoras-banking-wallet](https://cloud.githubusercontent.com/assets/15219855/12397443/64683254-bddf-11e5-8376-42810227f285.jpg)

**Comment by arnaldos** [comment]
@victoralfonzohd el P4 aunque lo podríamos mejorar. comparte pruebas de colores, colocale una costura al rededor del plano que hace de billetera. prueba una versin sin las monedasplz

**Comment by victoralfonzohd** [comment]
@arnaldos 

Prueba del logo con/sin el elemento de las modedas:

![mejoras-banking-wallet](https://cloud.githubusercontent.com/assets/15219855/12405826/9ee49a14-be19-11e5-9c39-fc37dd948efa.jpg)

---

Pruebas de color:

P1:

![mejoras-banking-wallet1](https://cloud.githubusercontent.com/assets/15219855/12406056/deca0b08-be1b-11e5-8cef-5fb16f3ccd22.jpg)

P2:

![mejoras-banking-wallet2](https://cloud.githubusercontent.com/assets/15219855/12406060/e54dbfc4-be1b-11e5-8ed6-7b3d39a91ecc.jpg)

P3:

![mejoras-banking-wallet3](https://cloud.githubusercontent.com/assets/15219855/12406070/02bd71da-be1c-11e5-8a85-ab44cd757658.jpg)

P4:

![mejoras-banking-wallet4](https://cloud.githubusercontent.com/assets/15219855/12406076/125e6f2c-be1c-11e5-8efc-d3ae563e3d11.jpg)

**Comment by victoralfonzohd** [comment]
@arnaldos 

Nuevas Versiones:

P1:

![mejoras-banking-wallet](https://cloud.githubusercontent.com/assets/15219855/12524178/7af55762-c12d-11e5-95a9-98a1a6c3e3ad.jpg)

P2:

![mejoras-banking-wallet](https://cloud.githubusercontent.com/assets/15219855/12524290/46b6a180-c12e-11e5-9588-65ffba11880b.jpg)

**Comment by victoralfonzohd** [comment]
@arnaldos 

Nueva Propuesta:

![mejoras-banking-wallet](https://cloud.githubusercontent.com/assets/15219855/12526356/dccd19c8-c13e-11e5-82df-2efa5c330ae0.jpg)

**Comment by arnaldos** [comment]
vamos a trabajar sobre la ultima, revisa el porcentaje de los grises ya que hay algunos que son muy similares, y apenas se deja ver una profundidad. mejora eso para ver si terminamos de dar los ultimos ajustes a este icono

**Comment by victoralfonzohd** [comment]
@arnaldos 

![mejoras-banking-wallet](https://cloud.githubusercontent.com/assets/15219855/12553759/5ff05b18-c34b-11e5-8a44-391858aa18ed.jpg)

**Comment by arnaldos** [comment]
podemos mejorar los escalones para que se vean con mayor detalle, tal ve generando un drop shadow ayude a darle mayor profundidad

**Comment by victoralfonzohd** [comment]
@arnaldos 

![mejoras-banking-wallet](https://cloud.githubusercontent.com/assets/15219855/12555349/f851dc90-c352-11e5-8c6f-b8346ebfe26c.jpg)

**Comment by arnaldos** [comment]
dejemos la versión de sombra plana de los escalones. vamos a dejar esa versión prepara los archivos
