### ISSUE TITLE
Mejorar gráficamente el Home Contract Tab de la Broker Wallet

### ISSUE THREAD

**Issue by m471c4** [bitDubai/fermat-graphic-design#392]
Issue referencial: #264

**Comment by victoralfonzohd** [comment]
@Luis-Fernando-Molina  @arnaldos  @nelsonalfo 

Contracts:

![view_home_contracts_propuesta-1](https://cloud.githubusercontent.com/assets/15219855/11662533/54f2c326-9da9-11e5-9575-bbabc81157a0.jpg)

Negotiations:

![view_home_negotiations_propuesta-1](https://cloud.githubusercontent.com/assets/15219855/11662589/a7b3fd78-9da9-11e5-887c-fe8deb212392.jpg)

**Comment by nelsonalfo** [comment]
- El gráfico no es el correcto, sino el que esta en Issue #264 
- Por ahora la barra de Tabs no le podemos colocar diferentes colores de fondo cuando esta seleccionada o no

por lo demas, me parece bien :)

**Comment by victoralfonzohd** [comment]
@nelsonalfo  Corrección en el Gráfico y barra de Tabs.. Creo que podrida considerarse el cambio de colores en la barra de tabs al momento de la selección ya que a mi parecer estos deben diferenciarse uno del otro 

Contracts:

![view_home_contracts_propuesta-1](https://cloud.githubusercontent.com/assets/15219855/11704474/3b385a24-9eba-11e5-8f14-00fcd22bdc57.jpg)

Negotiations: 

![view_home_negotiations_propuesta-1](https://cloud.githubusercontent.com/assets/15219855/11704553/dc862334-9eba-11e5-80f3-9b67c18ec3df.jpg)

**Comment by nelsonalfo** [comment]
Tienes razón, pero es algo a nivel de programación, que todavía no tenemos disponible. A eso me refería con:

> Por ahora la barra de Tabs no le podemos colocar diferentes colores de fondo cuando esta seleccionada o no
