### ISSUE TITLE
Mejorar gráficamente el Contract finish Detial de la Broker Wallet

### ISSUE THREAD

**Issue by m471c4** [bitDubai/fermat-graphic-design#394]
Issue referencial: #266

**Comment by emmysm** [comment]
![vista 266](https://cloud.githubusercontent.com/assets/15143489/11857204/677808e6-a428-11e5-87a0-b2fa00211f8c.jpg)
@nelsonalfo @Luis-Fernando-Molina

**Comment by nelsonalfo** [comment]
1. la barra que dice "Client Information" colócala con colore solido
2. Se me ocurre algo como esto con respecto a la descripción y disposición de los elementos:

![propuesta](https://cloud.githubusercontent.com/assets/1823627/11878698/861bae0a-a4c9-11e5-91e2-8a120c3ec15c.png)

**Comment by emmysm** [comment]
Está muy bien, @nelsonalfo . Ya hago los ajustes

**Comment by emmysm** [comment]
![contract detail 2](https://cloud.githubusercontent.com/assets/15143489/11882429/8d65ce38-a4de-11e5-988f-68fd8e8c6d35.jpg)
![contract detail](https://cloud.githubusercontent.com/assets/15143489/11882430/8fdcdfda-a4de-11e5-8841-fdd5cacdd631.jpg)

@nelsonalfo @Luis-Fernando-Molina

**Comment by nelsonalfo** [comment]
me gusta mas la segunda

**Comment by emmysm** [comment]
Chevere, ya subo los archivos @nelsonalfo
