### ISSUE TITLE
Mejorar gráficamente el Contract list de la Broker Wallet

### ISSUE THREAD

**Issue by m471c4** [bitDubai/fermat-graphic-design#395]
Issue referencial: #271

**Comment by emmysm** [comment]
![view_contract](https://cloud.githubusercontent.com/assets/15143489/11700720/a5730bc2-9e9d-11e5-9c42-54bcd659231a.jpg)

@nelsonalfo @arnaldos @Luis-Fernando-Molina

**Comment by emmysm** [comment]
![view_contract 2](https://cloud.githubusercontent.com/assets/15143489/11718882/5c550db8-9f2a-11e5-9010-551dbade5c5d.jpg)

![view_contract-3](https://cloud.githubusercontent.com/assets/15143489/11719153/98381bda-9f2b-11e5-9c35-45d9af93deb3.jpg)

@nelsonalfo  @Luis-Fernando-Molina

**Comment by nelsonalfo** [comment]
me gusta mas la ultima propuesta, que tiene fondo de items blanco

**Comment by emmysm** [comment]
![view_contract-recuperado](https://cloud.githubusercontent.com/assets/15143489/11726487/176afb28-9f51-11e5-8da7-d1e08299f854.png)

@nelsonalfo  con los ajustes

**Comment by nelsonalfo** [comment]
:+1:
