### ISSUE TITLE
Mejorar gráficamente el Contract Cancel Detial de la Broker Wallet

### ISSUE THREAD

**Issue by m471c4** [bitDubai/fermat-graphic-design#398]
Issue referencial: #274

**Comment by emmysm** [comment]
![view contract cancel](https://cloud.githubusercontent.com/assets/15143489/11855529/04bbf9b6-a41d-11e5-8a9b-a28433ce1881.jpg)
![sin titulo-1](https://cloud.githubusercontent.com/assets/15143489/11855538/0dddf454-a41d-11e5-8bed-ded4e9f53058.jpg)

@nelsonalfo  @Luis-Fernando-Molina
