### ISSUE TITLE
Mejorar gráficamente el Navigation Drawer de la Broker Wallet

### ISSUE THREAD

**Issue by m471c4** [bitDubai/fermat-graphic-design#399]
Issue referencial: #275

**Comment by victoralfonzohd** [comment]
@Luis-Fernando-Molina  @arnaldos @nelsonalfo Viene de del #275 y #390

![view_navigation_propuesta 2](https://cloud.githubusercontent.com/assets/15219855/11663545/16db520a-9daf-11e5-9b30-baa94b8fe2bc.jpg)

**Comment by nelsonalfo** [comment]
me parece bien esta propuesta
