### ISSUE TITLE
Mejorar gráficamente el Earnings de la Broker Wallet 

### ISSUE THREAD

**Issue by m471c4** [bitDubai/fermat-graphic-design#400]
Issue referencial: #277

**Comment by victoralfonzohd** [comment]
@Luis-Fernando-Molina @arnaldos @nelsonalfo @neoperol

Propuesta para la pantalla: Earnings de la Broker Wallet #277 

---

Pregunta: En el panel donde esta la tabla de gráficos faltan algunos datos? Al parecer faltan datos que deban acompañarlo, si no es así debo rediseñar esta sección para que el gráfico se vea mas solido

---

![earnings-b](https://cloud.githubusercontent.com/assets/15219855/11817957/becd8292-a329-11e5-94d2-9d200818b894.jpg)

---

Vista del Despliegue:

![earnings-a](https://cloud.githubusercontent.com/assets/15219855/11818054/5d55dba8-a32a-11e5-8254-84ff4de2bd4c.jpg)

---

Dependiendo de los datos de movimientos del usuario, se mostrarán las transacciones por pantalla permitiendo desplazarse a través de los puntos ubicados en la parte inferior de la pantalla.

Propuesta:

![earnings-2](https://cloud.githubusercontent.com/assets/15219855/11818725/2f2a1024-a32e-11e5-8afd-36cfec213bc3.jpg)
