### ISSUE TITLE
Mejorar gráficamente el Home Negotiation Tab, Stock Panel open de la Broker Wallet

### ISSUE THREAD

**Issue by m471c4** [bitDubai/fermat-graphic-design#401]
Issue referencial: #279

**Comment by victoralfonzohd** [comment]
@Luis-Fernando-Molina @arnaldos @nelsonalfo 

![view_home_balance-open_propuesta-1](https://cloud.githubusercontent.com/assets/15219855/11664204/9aec8548-9db2-11e5-9430-c3ec07d85dc0.jpg)

**Comment by nelsonalfo** [comment]
no me convence ese circulo en el medio donde esta NOV 2015

**Comment by victoralfonzohd** [comment]
@nelsonalfo 

![view_home_balance-open_propuesta-1](https://cloud.githubusercontent.com/assets/15219855/11704095/db204988-9eb6-11e5-9a3a-ea40761f7bcf.jpg)

**Comment by Luis-Fernando-Molina** [comment]
cual es la pantalla actual que se esta mejorando?
