### ISSUE TITLE
Mejorar los colores de las fichas de fermat.org

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#403]
Consiste en mejorar los colores establecidos para las fichas contenedoras de información de las capas o módulos, de fermat.org.

La estructura se mantendrán en cada una de ellas. solo se mejoraran los colores no necesariamente deben mantener los colores corporativos, estos colores deben variar únicamente en el backgraund de la ficha buscando que los colores sean tengan mas protagonismo. y no se vean tan pálidos si los comparamos con los colores de la flecha.

A continuación dejo referencias.

![captura de pantalla de 2015-12-10 12-36-35](https://cloud.githubusercontent.com/assets/13594347/11722664/433cd7d6-9f3c-11e5-97a2-ae91cee01421.png)

![captura de pantalla de 2015-12-10 12-36-14](https://cloud.githubusercontent.com/assets/13594347/11722666/45b1c6f2-9f3c-11e5-93fa-5870af31d144.png)

![captura de pantalla de 2015-12-10 12-37-04](https://cloud.githubusercontent.com/assets/13594347/11722667/46991c82-9f3c-11e5-9952-7ffacc14bcc6.png)

![captura de pantalla de 2015-12-10 12-37-29](https://cloud.githubusercontent.com/assets/13594347/11722668/496bdc56-9f3c-11e5-87b8-55c9dda496d2.png)

**Comment by m471c4** [comment]
@Luis-Fernando-Molina @arnaldos acá la primera prueba de color, las subo todas juntas para que puedan ver el contraste de los colores.

![prueba_todas](https://cloud.githubusercontent.com/assets/13468350/11730030/a17bb146-9f64-11e5-89aa-4a9eefb6d7b2.png)

Acá se puede apreciar cómo se ven al lado del indicador amarillo cada una de ellas:

![prueba](https://cloud.githubusercontent.com/assets/13468350/11729995/71c7ae5a-9f64-11e5-9085-fd568a4a8b49.png)

**Comment by arnaldos** [comment]
@m471c4 plantea otra propuesta de color para la 1 y la 4  plz

**Comment by m471c4** [comment]
@arnaldos aun no estoy segura del verde, pero ¿qué te parece así?

![muestra](https://cloud.githubusercontent.com/assets/13468350/11798513/b1bdda3e-a29d-11e5-8c9d-f1bc0e04f257.png)

**Comment by arnaldos** [comment]
@m471c4 nos quedamos con la 1ra versión de fichas, la ficha 4 modifica  los tonos grises para que no se vea tan opaco de la 1 los tonos oscuros dale mayor claridad. sin llegar a que los colores se vean apagados :smile:

**Comment by arnaldos** [comment]
@m471c4 deja la 1 así

**Comment by m471c4** [comment]
@arnaldos oscureciendo los tonos grises creo que resalta más, además hace buen contraste con el naranja:

![ficha_descriptiva_fermat_org_concepto_16-9_3](https://cloud.githubusercontent.com/assets/13468350/11804876/658913fe-a2d9-11e5-8251-ffdd75569d12.png)

Acá se pueden apreciar todas junto a los indicadores:

![muestra2](https://cloud.githubusercontent.com/assets/13468350/11804951/1fda7e6e-a2da-11e5-993a-b70bc9a23e86.png)

**Comment by m471c4** [comment]
@arnaldos ¿sustituyo los archivos originales con los colores anteriores o creo una carpeta adicional en el repositorio para el nuevo esquema de color?

**Comment by Luis-Fernando-Molina** [comment]
yo no cambiaria el color original, osea la que era verde debe seguir verde, la que era roja debe serguir roja o como mucho naranja, la que era amarilla debe seguir amarilla (Aunque esta ultima si puede cambiar por celeste para que no sea igual a la capa)

**Comment by m471c4** [comment]
@arnaldos acá una versión de las fichas con los colores originales más intensos, tal como sugirió @Luis-Fernando-Molina:

![prueba_todas2](https://cloud.githubusercontent.com/assets/13468350/11857605/06969174-a42c-11e5-8751-b5a629fe0699.png)

Así es como se ven junto al indicador amarillo:

![prueba2](https://cloud.githubusercontent.com/assets/13468350/11857610/14997ebc-a42c-11e5-9c62-589c2739fc02.png)

Acá sustituyendo el color amarillo por el azul:

![prueba3](https://cloud.githubusercontent.com/assets/13468350/11857615/231c05fe-a42c-11e5-9aeb-57458c379aa5.png)

Yo optaría por el color naranja el lugar del azul.

**Comment by Luis-Fernando-Molina** [comment]
Deja el Naranja para QA y para CONCEPT cambia el gris por el celeste.

**Comment by Luis-Fernando-Molina** [comment]
Osea, de los 8 que presentanste qudan : 

el nro 1, el 2 y el 3. Al nro 4 cambiale el color gris por celeste como esta en el 7,

**Comment by m471c4** [comment]
@arnaldos @Luis-Fernando-Molina acá con los cambios sugeridos:

![muestra3](https://cloud.githubusercontent.com/assets/13468350/11858014/c031bba6-a42f-11e5-8ae0-4cdb6c375935.png)

Junto a los indicadores:

![prueba4](https://cloud.githubusercontent.com/assets/13468350/11858018/c9df77e2-a42f-11e5-8bc1-79f9ae140207.png)

**Comment by Luis-Fernando-Molina** [comment]
ok, al 4to sacale el rojo y ponele un azul igual al que esta en esta pagina en el label "fermat" arriba a la derecha. El resto esta ok.

**Comment by m471c4** [comment]
@arnaldos @Luis-Fernando-Molina acá con los últimos cambios.

![new_ficha_descriptiva_fermat_org_concepto_16-9_3](https://cloud.githubusercontent.com/assets/13468350/11875626/c62bc97e-a4b7-11e5-8499-c23da346b5a4.png)

![muestra](https://cloud.githubusercontent.com/assets/13468350/11875648/e1f5637c-a4b7-11e5-835a-c1f0941abfb7.png)

**Comment by Luis-Fernando-Molina** [comment]
Ok, ahi quedo aplica todo en Fermat org lo antes posible. 

Saludos :+1:

**Comment by m471c4** [comment]
Excelente @Luis-Fernando-Molina.

@Miguelcldn subiré los fondos, los aros y las estrellas aparte, tal como se hizo con las versiones anteriores. Tú dime si necesitas alguna otra cosa en particular.

Saludos.

**Comment by arnaldos** [comment]
@Miguelcldn avísame cuando este aplicado para cerrar el caso
:+1:
