### ISSUE TITLE
Sombra cortada en flujos

### ISSUE THREAD

**Issue by Miguelcldn** [bitDubai/fermat-graphic-design#404]
![cut](https://cloud.githubusercontent.com/assets/5544266/11799880/e371e686-a2a9-11e5-96f4-9630a2c8367a.png)
Lo que se ve es el .png de los flujos, agregándoles un fondo más amplio. Como se ve, la sombra se corta de repente. En el tamaño original no se nota porque la sombra llega al borde de la imagen, pero en un entorno sí se nota que la sombra no se desvanece completamente al llegar al borde.

Se anexa las cabeceras de flujos y los flujos en su fondo ampliado:
![cut shadow](https://cloud.githubusercontent.com/assets/5544266/11799980/88554698-a2aa-11e5-925e-79d6f9dad49f.png)

![header cut](https://cloud.githubusercontent.com/assets/5544266/11799982/8bb6c4e2-a2aa-11e5-9913-a981622b181b.png)

Necesitamos que la sombra se desvanezca completamente antes de llegar al borde. Si se puede mantener las dimensiones del png mejor para nosotros, para no cambiar código, pero si es necesario ampliar la imagen podemos defendernos.

Nota: Se recuerda que el fondo del png debe ser transparente, tal como está actualmente.

Este issue es urgente para nosotros.

**Comment by arnaldos** [comment]
@Miguelcldn ya resuelvo eso !! :+1:

**Comment by arnaldos** [comment]
@Miguelcldn  @emmanuelcolina aquí los ajustes solicitados dijanme si asi esta todo en orden ?  aqui les dejo el commit 7531fee

![box_platform_info_process_90dpi](https://cloud.githubusercontent.com/assets/13594347/11823342/ab50445e-a345-11e5-826a-adf8282ead92.png)

![header_platform_info_process-90dpi](https://cloud.githubusercontent.com/assets/13594347/11823345/b288f54a-a345-11e5-9835-091a2968edc8.png)

**Comment by Miguelcldn** [comment]
Voy a descargar las imágenes manualmente desde el commit, pero si lo mezclabas con el repo principal hubiera sido más fácil :+1:

**Comment by arnaldos** [comment]
estan en el repo  !!  :+1:
