### ISSUE TITLE
Mejorar visualmente la sección Explore de la Wallet User  Community

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#406]
![screenshot_2015-12-15-14-17-32](https://cloud.githubusercontent.com/assets/13594347/11848012/6475e63a-a3f2-11e5-8e6e-8065a8f380f1.png)

---

![screenshot_2015-12-15-00-34-34](https://cloud.githubusercontent.com/assets/13594347/11848014/683fe400-a3f2-11e5-9f08-963d46dab057.png)

**Comment by ivonnesantos** [comment]
![indicaciones-01](https://cloud.githubusercontent.com/assets/15238660/11859518/e6a69622-a43d-11e5-8d69-773040f48566.png)

@arnaldos @furszy esta pantalla estaba bien lo que no me parece es que tenga opciones search and notifications (esta ya esta en el navegador no es necesario ponerla dos veces) como vez no tiene los 3 puntos sino la lupita de busqueda, bueno mi propuesta de mejora se enfoca en eso. Para "users not available" creo que hay que hacer un icono mas elaborado 
utilizando como base la identidad de fermat que se coloque en todas las pantallas en lo que ocurra eso adaptándolo al color (es mi opinión).
