### ISSUE TITLE
Mejorar visualmente la sección Connections de la Wallet User Community

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#407]
Icono original

![screenshot_2015-12-15-00-34-57](https://cloud.githubusercontent.com/assets/13594347/12062842/015b4e2a-af76-11e5-89f4-cb156b862f00.png)

**Comment by ivonnesantos** [comment]
![indicaciones-01](https://cloud.githubusercontent.com/assets/15238660/11870083/c0a35092-a496-11e5-9eff-86fb73c97898.png)

@arnaldos @furszy

**Comment by furszy** [comment]
@ivonnesantos  el search deberia ser un expandible en el toolbar que cuando tocas la lupa te permita escribir allí y te vaya pintando en pantalla los resultados. Esto estaba implementado pero todavía no tenemos el funcionamiento para que esto corra desde la capa de comunicación.
