### ISSUE TITLE
Mejorar visualmente el icono "Notifications" de la intra User Community

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#408]
Icono original

![screenshot_2015-12-31-01-46-21](https://cloud.githubusercontent.com/assets/13594347/12062794/3dca945c-af75-11e5-9f2d-f432724f5e58.png)

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina propuesta del icono

![icons-05](https://cloud.githubusercontent.com/assets/13594347/12062818/55470660-af75-11e5-9ba1-1465f0d4c14c.jpg)

**Comment by Luis-Fernando-Molina** [comment]
puede ser

**Comment by arnaldos** [comment]
vale perfecto !!! viendo el resto de los comentarios ya replanteo los iconos

**Comment by emmysm** [comment]
![no notification-01](https://cloud.githubusercontent.com/assets/15143489/12149644/01f6b9e0-b477-11e5-8a3f-82a6b06011d0.png)
@arnaldos

**Comment by emmysm** [comment]
![propuesta de color-01](https://cloud.githubusercontent.com/assets/15143489/12151175/f4ed2d34-b47f-11e5-901b-3b445dfe09af.png)

@arnaldos  @Luis-Fernando-Molina  una propuesta de color para el fondo.

**Comment by arnaldos** [comment]
@emmysm  centra el texto plz

**Comment by emmysm** [comment]
![propuesta de color-01](https://cloud.githubusercontent.com/assets/15143489/12151259/6e2b734a-b480-11e5-8eca-3449a74b8fe2.png)

@arnaldos ajustes

**Comment by emmysm** [comment]
![screen conection-02-02](https://cloud.githubusercontent.com/assets/15143489/12163657/c0354d76-b4e1-11e5-8fdc-94bf8ffb3e2d.png)
@arnaldos

**Comment by emmysm** [comment]
![any notification-04](https://cloud.githubusercontent.com/assets/15143489/12243679/04fd758a-b872-11e5-8294-18e94660730f.png)
![any notification-03](https://cloud.githubusercontent.com/assets/15143489/12243680/0503b24c-b872-11e5-9874-e463e2d1b892.png)
![any notification-01](https://cloud.githubusercontent.com/assets/15143489/12243682/06b8d680-b872-11e5-8e6d-c8e7959625eb.png)

@arnaldos

**Comment by emmysm** [comment]
![any notification](https://cloud.githubusercontent.com/assets/15143489/12244803/8f91e35c-b877-11e5-92ef-a2daca7f59ba.jpg)

@arnaldos @Luis-Fernando-Molina

**Comment by arnaldos** [comment]
@emmysm la version de la "X" con el outline blanco, estandariza el tamaño de la "X" y el espesor del outline. :smile:

**Comment by emmysm** [comment]
![any notification-02](https://cloud.githubusercontent.com/assets/15143489/12250228/942788f2-b897-11e5-978f-3acfda49f2a7.png)
![any notification-04](https://cloud.githubusercontent.com/assets/15143489/12250229/942b9974-b897-11e5-86c7-2ea71f85b92f.png)

@arnaldos

**Comment by arnaldos** [comment]
@emmysm usa outline blanco como te mencione antes

**Comment by emmysm** [comment]
![any notification-02](https://cloud.githubusercontent.com/assets/15143489/12269525/0f4b2160-b924-11e5-8728-be7d7be66187.png)
![any notification-04](https://cloud.githubusercontent.com/assets/15143489/12269536/1a4e6586-b924-11e5-8c90-608d728be194.png)
@arnaldos

**Comment by arnaldos** [comment]
:+1:

**Comment by emmysm** [comment]
Cuál de los dos? :yum:

**Comment by arnaldos** [comment]
campana
