### ISSUE TITLE
Mejorar visualmente el icono "cripto wallet user" de la intra User Community

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#409]
Icono original

![screenshot_2015-12-31-01-46-05](https://cloud.githubusercontent.com/assets/13594347/12062757/a650130e-af74-11e5-8e1b-28117619ae16.png)

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina  propuesta del icono estandarizando los iconos con la bitcoin wallet

![icons-04](https://cloud.githubusercontent.com/assets/13594347/12062762/aff2fbc4-af74-11e5-93eb-1c25bc67e5e1.jpg)

**Comment by arnaldos** [comment]
@furszy así planteo los iconos para la wallet

**Comment by furszy** [comment]
@arnaldos, no me parece que sea lo mejor. Fíjate algún empty screen de otras app para encaminar mejor la cosa y también léete la página de material design.

**Comment by emmysm** [comment]
![no user available-02](https://cloud.githubusercontent.com/assets/15143489/12432310/cc18d58c-becc-11e5-9909-193a548e2dd8.png)
![no user available-01](https://cloud.githubusercontent.com/assets/15143489/12432311/cc39bcc0-becc-11e5-8d90-12893658b7d0.png)

@arnaldos

**Comment by emmysm** [comment]
![sin titulo-1-02](https://cloud.githubusercontent.com/assets/15143489/12432355/f93d27f2-becc-11e5-82c3-f4da41984d30.png)

**Comment by arnaldos** [comment]
@emmysm version 2 :+1:
