### ISSUE TITLE
Bocetar ideas para la imagen de Fermat CDN

### ISSUE THREAD

**Issue by m471c4** [bitDubai/fermat-graphic-design#41]
Viene del #6 

Actualmente el logo se tomó prestado de otro concepto. Se debe realizar uno nuevo. Hacerlo directamente con la nueva paleta de colores.

![fermat-cdn](https://cloud.githubusercontent.com/assets/9479367/9057436/48a083b4-3a9a-11e5-823f-8a6ff53d9f78.png)

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina @m471c4 primer boceto Fermat CDN Crypto Distribution Network
Se creó un icono con una wallet como elemento central con flechas que parten de la wallet para dar a entender que es una red de distribución.
![fermat_sub_app_1](https://cloud.githubusercontent.com/assets/13594347/9499868/d4635432-4beb-11e5-8b2d-d408a3c8ce84.jpg)

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina @m471c4 Segundo boceto Fermat CDN Crypto Distribution Network aplicando las sugerencias que se dieron en la reunión
![fermat_sub_app_3](https://cloud.githubusercontent.com/assets/13594347/9527612/0354a650-4cba-11e5-9654-05217c127918.jpg)

**Comment by Luis-Fernando-Molina** [comment]
pudiera ser algo asi, pero en vez del documento debiera ser una moneda lo que se distribuye. La nube no entendí para que está ahi.

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina lo de la nube era para hacer énfasis de que la plataforma funciona a través de la web, pero veo que no se entiende, creo que esto puede distraer por lo que voy a eliminar el elemento, ya sustituyo el documento por una moneda.

**Comment by Luis-Fernando-Molina** [comment]
Respecto a lo de la nube esta bien la idea si funcionara a través de la web, pero la platforma esta justo no tienen relación con la web. Los distpositivos seinterconectan entre si a través de una red P2P que no dependede ningun servidor web :smile:

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina  ajustes del Logo de Fermat CDN empleando una moneda como lo comentamos en la ultima reunion
![fermat_cdn](https://cloud.githubusercontent.com/assets/13594347/9556706/9de3e334-4da0-11e5-8bf0-50b5896fb3d6.png)

**Comment by Luis-Fernando-Molina** [comment]
No se entiende que es una moneda y menos ue es una de bitcoin. Fijate como se representa una moneda bitcoin y adaptala a nuestro estilo.

**Comment by arnaldos** [comment]
ok perfecto !!

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina comparto los últimos ajustes de Fermat CDN
![fermat_cdn](https://cloud.githubusercontent.com/assets/13594347/9584433/ed07a608-4fda-11e5-8443-52064dca39e7.png)

**Comment by Luis-Fernando-Molina** [comment]
no me convence, podés hacer algunas otras opciones?

Proba hacer una jerarquía de 3 niveles. Por otro lado la moneda sale en un color que no pega mucho.

**Comment by arnaldos** [comment]
voy a replantear el icono

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina ajustes Fermat CDN
![fermat_cdn-2](https://cloud.githubusercontent.com/assets/13594347/9597174/bfa4cec0-5048-11e5-803f-3285eaa29c26.png)
![fermat_cdn-3](https://cloud.githubusercontent.com/assets/13594347/9597175/bfa63ab2-5048-11e5-9d53-98da555bf7ec.png)

**Comment by Luis-Fernando-Molina** [comment]
Sigue sin convencer. Volvé al logo original (el primero de este issue) y reemplazá los papiros por billeteritas de las nuestras en su tamaño estandard mas chico. Corregi la forma de la conexión por la nuestra estandard y veamos como queda por favor.

**Comment by arnaldos** [comment]
ok perfecto !!

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina ajustes partiendo del icono original
![fermat_cdn-4](https://cloud.githubusercontent.com/assets/13594347/9625363/5c90660a-511f-11e5-87e5-00575fbc9cd4.png)

**Comment by Luis-Fernando-Molina** [comment]
> reemplazá los papiros por billeteritas de las nuestras en su tamaño estandard mas chico

te faltó leer esa parte :smile_cat:

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina si se me paso :smile:  aquí te comparto la corrección
![fermat_cdn](https://cloud.githubusercontent.com/assets/13594347/9647190/47004eba-51a4-11e5-811b-d9a29bf64b19.png)

**Comment by Luis-Fernando-Molina** [comment]
:+1:  puede quedar ahí o puede que derivés una billetera mas desde la del medio, probemos eso.

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina  Dale, perfecto. Ya hago los ajustes y los subo.

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina  esta versión se ve mejor, se logra cubrir el espacio que quedaba en la alterior

![fermat_cdn2](https://cloud.githubusercontent.com/assets/13594347/9669125/18b62a1a-524f-11e5-80e5-84de3670fd6a.png)

**Comment by Luis-Fernando-Molina** [comment]
ok, cambia de lugar la que esta abajo por la roja por favor, gracias

**Comment by arnaldos** [comment]
ok perfecto !!

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina subo los ajustes de la billetera en el icono 

![fermat_cdn3](https://cloud.githubusercontent.com/assets/13594347/9677622/1e212cfa-52a6-11e5-9f2e-1a702b7e2947.png)

**Comment by Luis-Fernando-Molina** [comment]
:+1: listo terminamos con este :smile:    Cuando esté actualizado en fermat.org, cerrá el caso.

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina perfecto !!!! ya subo este icono en el repo asi @Miguelcldn lo pueden sustituir en fermat.org

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina listo ya subi al repo !!
