### ISSUE TITLE
Mejorar visualmente el Navigation View de la Wallet User  Community

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#410]
![screenshot_2015-12-15-00-34-49](https://cloud.githubusercontent.com/assets/13594347/11848024/7aa20010-a3f2-11e5-9142-64b6f9878ebb.png)

**Comment by emmysm** [comment]
![view_navigation](https://cloud.githubusercontent.com/assets/15143489/12164820/c2028bce-b4ea-11e5-8fbe-233bc7b4c8e8.png)

@arnaldos

**Comment by emmysm** [comment]
![view_navigation 2](https://cloud.githubusercontent.com/assets/15143489/12164863/10dbc8dc-b4eb-11e5-9661-cbae1b49e28e.png)

**Comment by emmysm** [comment]
![view navigation_](https://cloud.githubusercontent.com/assets/15143489/12332530/2b2374b6-bac1-11e5-9967-0f24c78195b6.png)
![view navigation](https://cloud.githubusercontent.com/assets/15143489/12332531/2b53d12e-bac1-11e5-962e-4a2c191d98d3.png)
@arnaldos

**Comment by arnaldos** [comment]
@emmysm incluye la parte de atras de la app ..... para que se aprecie completa los elementos

**Comment by emmysm** [comment]
Voy @arnaldos

**Comment by emmysm** [comment]
![view navigation_](https://cloud.githubusercontent.com/assets/15143489/12338856/21b9a4fe-bae4-11e5-8b6e-6cada8bedaa9.png)

![view navigation](https://cloud.githubusercontent.com/assets/15143489/12339129/6f615462-bae5-11e5-88c3-0727ebbdf3e0.png)

@arnaldos

**Comment by emmysm** [comment]
![view navigation](https://cloud.githubusercontent.com/assets/15143489/12360458/55e66c66-bb8a-11e5-8ee6-42db9991069b.png)
![viewnavigation](https://cloud.githubusercontent.com/assets/15143489/12360459/56c87c8c-bb8a-11e5-9ff6-5a322349816f.png)

@arnaldos

**Comment by arnaldos** [comment]
hasta el momento la 2da no se que opina @Neoperol ?
