### ISSUE TITLE
Mejorar visualmente el icono "conections" de la intra User Community

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#411]
Icono original

![screenshot_2015-12-31-01-46-15](https://cloud.githubusercontent.com/assets/13594347/12062853/4d1a9bcc-af76-11e5-88e6-ba5962cb10a2.png)

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina propuesta del icono

![icons-06](https://cloud.githubusercontent.com/assets/13594347/12062861/64c42022-af76-11e5-9692-f538a88d2685.jpg)

**Comment by Luis-Fernando-Molina** [comment]
no se deduce eso del icono

**Comment by emmysm** [comment]
![pantalla-conexion](https://cloud.githubusercontent.com/assets/15143489/12100001/55fea112-b2fe-11e5-8279-721cbb17cd3f.gif)
@arnaldos @Luis-Fernando-Molina

**Comment by emmysm** [comment]
![pantalla transferencia-02](https://cloud.githubusercontent.com/assets/15143489/12100855/c3c6100e-b303-11e5-9d92-29612c123053.png)
![pantalla transferencia-01](https://cloud.githubusercontent.com/assets/15143489/12100859/c7fa23fe-b303-11e5-8373-b9774489a250.png)

**Comment by emmysm** [comment]
![sin titulo-2](https://cloud.githubusercontent.com/assets/15143489/12102970/f5313ada-b310-11e5-9fba-d9a021a4e2e3.png)
@arnaldos ajustes

**Comment by emmysm** [comment]
![connection 2-03](https://cloud.githubusercontent.com/assets/15143489/12149828/0f02af44-b478-11e5-8668-e2a3dfc75df5.png)
![screen connections-02-02-03](https://cloud.githubusercontent.com/assets/15143489/12149986/ff674a08-b478-11e5-815c-3ec62bb99162.png)

@arnaldos

**Comment by arnaldos** [comment]
@emmysm plantea otros caracteres para representar a los usuarios ... y el texto centralo plz usa flechas mas delgadas trata de que los elementos guarden cierta similitud con los que estamos trabajando para la bitcoin wallet ... ya que esta sub app esta relacionada con esa wallet :smile:

**Comment by emmysm** [comment]
Vale, voy a eso  :D

**Comment by emmysm** [comment]
![screen dont conections-01](https://cloud.githubusercontent.com/assets/15143489/12163706/0d0be56a-b4e2-11e5-9244-cf1e6d00cc4c.png)

@arnaldos

**Comment by emmysm** [comment]
![sin titulo-1](https://cloud.githubusercontent.com/assets/15143489/12246256/acf6a22c-b87f-11e5-98a7-c745a57fb5b1.jpg)

@arnaldos

**Comment by arnaldos** [comment]
@emmysm usa en este icono el mismo estilo de los que te comente en el caso #408, una sugerencia usa la versión del centro, con las siguientes características; deja los usuarios de los laterales y elimina el del centro colocando unas flechas en el centro que vallan de una dirección a otra. y otra versión que quieras interpretar :smile:

**Comment by emmysm** [comment]
![any conection -02](https://cloud.githubusercontent.com/assets/15143489/12251237/74e13da0-b89f-11e5-9647-add5a1e8ed93.png)
![any conection -03](https://cloud.githubusercontent.com/assets/15143489/12251239/750b94b0-b89f-11e5-8e23-f2707aac6c51.png)
@arnaldos

**Comment by arnaldos** [comment]
@emmysm la 2da propuesta usando el outline blanco y incluye la "X"

**Comment by emmysm** [comment]
![any connections-03](https://cloud.githubusercontent.com/assets/15143489/12269592/62e8e9a6-b924-11e5-963d-a9668bd90d08.png)
@arnaldos

**Comment by arnaldos** [comment]
@emmysm replantea la diagramacion de los elementos plz. tal ves la equis encima de las flechas por ahi. juega con la diagramacion :smile:

**Comment by emmysm** [comment]
![any connections2-02](https://cloud.githubusercontent.com/assets/15143489/12302716/d5951806-b9f8-11e5-97b7-80b3c5f13237.png)
![any connections2-04](https://cloud.githubusercontent.com/assets/15143489/12302718/d75be994-b9f8-11e5-9814-b30c124e28ed.png)

@arnaldos

**Comment by emmysm** [comment]
![any connections2-03](https://cloud.githubusercontent.com/assets/15143489/12306653/fe6c65e0-ba0c-11e5-968a-5f17c83e4855.png)

@arnaldos Ajustes.

**Comment by arnaldos** [comment]
:+1:
