### ISSUE TITLE
Mejorar visualmente el icono del search contact de la Bitcoin Wallet 

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#412]
![screenshot_2015-12-31-01-45-13](https://cloud.githubusercontent.com/assets/13594347/12062667/c72fe52e-af72-11e5-882a-e921732c4efc.png)

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina sugiero usar este estilo gráfico para los iconos para cuando el usuario no tiene contactos 

![icons-02](https://cloud.githubusercontent.com/assets/13594347/12062668/d175be32-af72-11e5-8175-4b0653164905.jpg)

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina ajustes icono de contacts

![icons_2 2](https://cloud.githubusercontent.com/assets/13594347/12129733/b5b7dd9c-b3d7-11e5-8901-88bbd2804557.jpg)

![icons_2 3](https://cloud.githubusercontent.com/assets/13594347/12129734/b5d83aba-b3d7-11e5-9009-802a8f3cc4ea.jpg)

**Comment by arnaldos** [comment]
![icons_2 4](https://cloud.githubusercontent.com/assets/13594347/12129790/214327ba-b3d8-11e5-9a64-42af3acf944c.jpg)

**Comment by furszy** [comment]
@Luis-Fernando-Molina @arnaldos 
Que hacemos con John y Jane Doe? en esta ultima foto tienen fotos de contactos nulos.

**Comment by Luis-Fernando-Molina** [comment]
Están OK.  Solo que saldrían las fotos de John y jane porque no hay forma de que sea nulo.

**Comment by Luis-Fernando-Molina** [comment]
Arnaldo me gusta la calidad que vas logrando,  seguí así.

**Comment by arnaldos** [comment]
gracias luis !!!

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina versiones para el search contact 

Versión 1
![icon_contacts_7_vs1](https://cloud.githubusercontent.com/assets/13594347/12187328/144d2e1a-b57d-11e5-9936-d9b1a2fd6655.jpg)

Versión 2
![icon_contacts_7_vs2](https://cloud.githubusercontent.com/assets/13594347/12187329/145285c2-b57d-11e5-91e4-5bf2a0b51505.jpg)

Versión 3
![icon_contacts_7_vs3](https://cloud.githubusercontent.com/assets/13594347/12187330/14889036-b57d-11e5-9757-39c5807e0912.jpg)

Versión 4
![icon_contacts_7_vs4](https://cloud.githubusercontent.com/assets/13594347/12187331/1494db98-b57d-11e5-9d84-f7052379baa0.jpg)

**Comment by Luis-Fernando-Molina** [comment]
la 4 es la que se ve mejor
