### ISSUE TITLE
Mejorar visualmente del icono de no history send or recive de la Bitcoin Wallet 

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#413]
![screenshot_2015-12-31-01-45-22](https://cloud.githubusercontent.com/assets/13594347/12062712/ff7c41b0-af73-11e5-87e3-f7451c8f6255.png)

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina sugiero usar este estilo gráfico para los iconos para cuando el usuario no hay historial de dinero recibido o enviado 

![icons-03](https://cloud.githubusercontent.com/assets/13594347/12062726/3769a5ea-af74-11e5-9b8b-5bb9a1243d87.jpg)

**Comment by Luis-Fernando-Molina** [comment]
por un lado no me convence mucho, no veo que del icono alguien pueda interpretar ese mensaje.

Por otro lado, le veo falta de inteligencia a esa pantalla. Si no tiene ninguna trabascción enviada, le pudiera sugerir enviar dinero  para ver que se siente @furszy o algo asi

**Comment by furszy** [comment]
@Luis-Fernando-Molina @arnaldos 
 Si, esta pantalla debería tener un botón flotante o alguna forma de poder enviar request.

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina @furszy 

propuestas de iconos mas el boton flotante

versión 1
![icons_2 5](https://cloud.githubusercontent.com/assets/13594347/12129713/9157a9b4-b3d7-11e5-9265-e7dc9130d4a2.jpg)

versión 2
![icons_2 6](https://cloud.githubusercontent.com/assets/13594347/12129714/915c87f4-b3d7-11e5-8100-62cce1d63c75.jpg)
