### ISSUE TITLE
Mejorar visualmente el icono de no transactions de la Bitcoin Wallet 

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#414]
![screenshot_2015-12-30-10-41-18](https://cloud.githubusercontent.com/assets/13594347/12062690/65623080-af73-11e5-8761-8ef9e6480248.png)

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina sugiero usar este estilo gráfico para los iconos para cuando el usuario no tiene transacciones 

![icons-01](https://cloud.githubusercontent.com/assets/13594347/12062696/8abd14a8-af73-11e5-8e88-86d73808e563.jpg)

**Comment by Luis-Fernando-Molina** [comment]
provisionalmente puede ser, pero se puede hacer algo mejor

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina mejoras en el icono de transactions, también podremos apreciar un ajuste para el fondo. de esta app. proveniente del caso #341

![icons_2 1](https://cloud.githubusercontent.com/assets/13594347/12129452/ee8928c6-b3d5-11e5-9fc6-1b7513fc9b49.jpg)

![icons_2](https://cloud.githubusercontent.com/assets/13594347/12129453/ee8e94f0-b3d5-11e5-884a-3309ab2e9711.jpg)

**Comment by Luis-Fernando-Molina** [comment]
:+1:

**Comment by arnaldos** [comment]
perfecto !
