### ISSUE TITLE
Mejorar los iconos para las subapp Identity y Community de la Crypto Customer Wallet

### ISSUE THREAD

**Issue by m471c4** [bitDubai/fermat-graphic-design#415]
Partiendo de la identidad creada para la Crypto Customer Wallet, crear dos logos para las subaplicaciones Identity y Community, respectivamente.

La idea es estandarizar su apariencia, logrando que guarden relación con el icono creado para la Wallet.

![icono-crypto-customer](https://cloud.githubusercontent.com/assets/13468350/11878461/3689b34c-a4c8-11e5-805c-98a6f9aa4403.png)

Requisitos

Archivo PNG de 32 bits (alpha)
Tamaño: 512 x 512 píxeles
Tamaño máximo del archivo: 1024 KB

Una vez elegido el icono, es necesario generar los tamaños, en .PNG para aplicarlos en lo siguientes:

IC launcher:

48 × 48 px (mdpi)
72 × 72 px (hdpi)
96 × 96 px (xhdpi)
144 × 144 px (xxhdpi)
192 × 192 px (xxxhdpi)
512 × 512 px (Wallet store)

**Comment by m471c4** [comment]
@Luis-Fernando-Molina @arnaldos acá la primera propuesta para los iconos:

Para la subaplicación Identity:

![cryptocustomeriden](https://cloud.githubusercontent.com/assets/13468350/11878527/99999af6-a4c8-11e5-857b-0f7e92c07d29.png)

![cryptocustomeriden_mu](https://cloud.githubusercontent.com/assets/13468350/11878530/9a5cc260-a4c8-11e5-95f0-18d2570d79d6.png)

Para la subaplicación Community:

![cryptocustomercom](https://cloud.githubusercontent.com/assets/13468350/11878536/a65fc9f4-a4c8-11e5-9133-047ddb0260a7.png)

![cryptocustomercom_mu](https://cloud.githubusercontent.com/assets/13468350/11878537/a6646ad6-a4c8-11e5-991c-a5c331d8fb2e.png)

**Comment by Luis-Fernando-Molina** [comment]
Este tipo de casos miralo con @arnaldos por favor, gracias

**Comment by m471c4** [comment]
Muy bien, espero entonces respuesta de @arnaldos para hacer los ajustes en caso de ser necesarios y subirlo al repositorio en sus versiones finales.

**Comment by arnaldos** [comment]
@m471c4 prueba usar la "C" del icono para el cuerpo del user gira la"C" 90grados y ponle una esfera para la cabeza de color morado y fuscia en gradiente como tiene la billetera.   Para la comunity replantea la propuesta.

**Comment by m471c4** [comment]
@arnaldos acá hice la prueba que me pediste para la Identity.

![cryptocustomeriden2](https://cloud.githubusercontent.com/assets/13468350/11899577/0797161a-a572-11e5-92d0-ff04a4830304.png)

![cryptocustomeriden_mu2](https://cloud.githubusercontent.com/assets/13468350/11899610/5d0ba156-a572-11e5-816c-e3777e219ed1.png)

**Comment by arnaldos** [comment]
@m471c4 prueba con un solo arco plz

**Comment by m471c4** [comment]
@arnaldos acá una propuesta para ambos casos usando un solo arco:

![cryptocustomer](https://cloud.githubusercontent.com/assets/13468350/11944151/13f62058-a816-11e5-9ee6-bbdff327a8da.png)

Identity:
![cryptocustomeriden_mu3](https://cloud.githubusercontent.com/assets/13468350/11944184/6bfc4bce-a816-11e5-913c-7c44b4914a57.png)

Community:
![cryptocustomercom_mu2](https://cloud.githubusercontent.com/assets/13468350/11944189/7346c706-a816-11e5-9dc2-fd7d20c2d311.png)

**Comment by victoralfonzohd** [comment]
@arnaldos @Luis-Fernando-Molina 

Propuesta 1:

![crypto_customer_identity](https://cloud.githubusercontent.com/assets/15219855/12022195/c8db8334-ad5f-11e5-820d-cb2d60af6f1f.png)

**Comment by victoralfonzohd** [comment]
@arnaldos @Luis-Fernando-Molina 

Propuesta 2:

Version 1:

![crypto_customer_identity](https://cloud.githubusercontent.com/assets/15219855/12024834/7d32f6fe-ad7a-11e5-8404-0367b7a6c4b6.png)

Versión 2: 

![crypto_customer_identity](https://cloud.githubusercontent.com/assets/15219855/12024890/3fc827de-ad7b-11e5-9da7-0babbd23e8b8.png)

**Comment by arnaldos** [comment]
aumenta el tamaño de la mascara y los elementos al rededor

**Comment by victoralfonzohd** [comment]
@arnaldos 

![crypto_customer_identity](https://cloud.githubusercontent.com/assets/15219855/12025127/a17db51e-ad7d-11e5-8d45-900f07d22ccf.png)

**Comment by arnaldos** [comment]
@victoralfonzohd deja este asi genera los formatos y subelos al repo. y le haces llegar a matias

**Comment by victoralfonzohd** [comment]
@arnaldos Perfecto
