### ISSUE TITLE
Crear icono para la SubApp Cash Wallet

### ISSUE THREAD

**Issue by emmysm** [bitDubai/fermat-graphic-design#416]
**Cash Wallet** es una cartera donde podrás manejar un balance de dinero en efectivo. 

**Requisitos**

Archivo PNG de 32 bits (alpha)
Tamaño: 512 x 512 píxeles
Tamaño máximo del archivo: 1024 KB

Una vez elegido el icono, es necesario generar los tamaños, en .PNG para aplicarlos en lo siguientes:

**IC launcher:**

48 × 48 px (mdpi)
72 × 72 px (hdpi)
96 × 96 px (xhdpi)
144 × 144 px (xxhdpi)
192 × 192 px (xxxhdpi)
512 × 512 px (Wallet store)

**Comment by victoralfonzohd** [comment]
@arnaldos @Luis-Fernando-Molina 

Propuesta 1:

Versión 1:

![icono_cashwallet](https://cloud.githubusercontent.com/assets/15219855/11885173/8f32208c-a4f1-11e5-8715-a8945f6db281.jpg)

Versión 2: 

![icono_cashwallet](https://cloud.githubusercontent.com/assets/15219855/11885752/a650e354-a4f4-11e5-804d-e754cb0131d6.jpg)

Versión 3:

![icono_cashwallet](https://cloud.githubusercontent.com/assets/15219855/11885921/471ff85a-a4f6-11e5-94a8-a88b5f7f2728.jpg)

**Comment by arnaldos** [comment]
@victoralfonzohd prueba la versión 2 sin el fondo

**Comment by victoralfonzohd** [comment]
@arnaldos 

Versión 2 sin fondo: 

![icono_cashwallet](https://cloud.githubusercontent.com/assets/15219855/11887513/2cb1b056-a507-11e5-8376-7e3c73f28cdc.jpg)

**Comment by arnaldos** [comment]
@victoralfonzohd con el fondo se ve mejor .. revisa los vectores en las curvas se ven algo raras en la construcción, del lado derecho del billete hay una sección en donde se unen ambos billetes ya que tienen el mismo color busca la manera de colocarle una sombra o algo que permita que los billetes se separen, también podría ser el borde amarillo.

**Comment by victoralfonzohd** [comment]
@arnaldos 

![icono_cashwallet](https://cloud.githubusercontent.com/assets/15219855/11890080/c22939ae-a522-11e5-8698-b4d9575e60d4.jpg)

**Comment by arnaldos** [comment]
@victoralfonzohd busca la manera de integrar el símbolo de las otras fiat currencies como el euro y la lira exterlina .. para dar a entender que puedes guardar efectivo de cualquier divisa

**Comment by victoralfonzohd** [comment]
@arnaldos 

![icono_cashwallet](https://cloud.githubusercontent.com/assets/15219855/11914113/04f1987c-a649-11e5-8e56-4e555d1d3ffe.jpg)

**Comment by arnaldos** [comment]
@victoralfonzohd  prueba usar las monedas de la banking

**Comment by victoralfonzohd** [comment]
@arnaldos 

![icono_cashwallet](https://cloud.githubusercontent.com/assets/15219855/11958177/7dfd6074-a898-11e5-94e5-e75141c42620.jpg)

**Comment by victoralfonzohd** [comment]
@arnaldos 

Nueva Propuesta:

Versión 1:

![1](https://cloud.githubusercontent.com/assets/15219855/12336934/61fdd1a8-bad9-11e5-829a-5ac3a709c7cd.jpg)

Versión 2:

![2](https://cloud.githubusercontent.com/assets/15219855/12336937/66e21f62-bad9-11e5-9b39-d4dbef25aeaa.jpg)

Versión 3:

![3](https://cloud.githubusercontent.com/assets/15219855/12336941/6c804192-bad9-11e5-9787-7050ad6d9937.jpg)

**Comment by arnaldos** [comment]
@victoralfonzohd replantea el icono, por una versión donde tenga mas detalle plz

**Comment by victoralfonzohd** [comment]
@arnaldos 

Propuesta 1:

![icono_cashwallet](https://cloud.githubusercontent.com/assets/15219855/12339184/d2a1adce-bae5-11e5-963e-e187b6c58272.jpg)

Propuesta 2:

![icono_cashwallet2](https://cloud.githubusercontent.com/assets/15219855/12339759/dc9f6138-bae8-11e5-8b5e-892713e1ef87.jpg)

**Comment by victoralfonzohd** [comment]
@arnaldos 

Mejora de color:

![icono_cashwallet](https://cloud.githubusercontent.com/assets/15219855/12339910/f84a8ab0-bae9-11e5-81fb-31ed562200e4.jpg)

**Comment by victoralfonzohd** [comment]
@arnaldos 

![icono_cashwallet](https://cloud.githubusercontent.com/assets/15219855/12341716/c4b0f070-baf5-11e5-8a23-049275da8676.jpg)

**Comment by arnaldos** [comment]
@victoralfonzohd colocale una costura en la tapa, para que se aprecie mejor que es una billetera. prueba otros colores. revisa los tonos de los billetes se ven como opacos. no se si sea por el dorado del símbolo del dolar. revisa eso a ver plz.

**Comment by victoralfonzohd** [comment]
@arnaldos 

Propuestas de color:

Propuesta 1:

![icono_cashwallet](https://cloud.githubusercontent.com/assets/15219855/12352280/c634e4e0-bb56-11e5-9666-b7b84400ca04.jpg)

Propuesta 2

![icono_cashwallet](https://cloud.githubusercontent.com/assets/15219855/12352394/cf3b9a38-bb57-11e5-9936-30081ba73926.jpg)

Propuesta 3:

![icono_cashwallet](https://cloud.githubusercontent.com/assets/15219855/12352469/7db228a2-bb58-11e5-8afa-7ddfcab590df.jpg)

**Comment by arnaldos** [comment]
@victoralfonzohd el concepto esta bien lo que veo es que hay que darle mayor detalle a la costura, no la coloques tan cerca del borde porque parece un elemento externo a la billetera has que funcionen en un conjunto, por otro lado tiene in marco que después de analizarlo por un rato, hace a la pieza parecer una caja fuerte, los colores se ven oscuros no se si sea por el gradiente que estas trabajando revisa eso plz

**Comment by victoralfonzohd** [comment]
@arnaldos 

Versión 1:

![icono_cashwallet1](https://cloud.githubusercontent.com/assets/15219855/12358541/ee5be670-bb7f-11e5-8681-83af4bbdf56c.jpg)

Versión 2:

![icono_cashwallet](https://cloud.githubusercontent.com/assets/15219855/12358642/7c0b63d8-bb80-11e5-9a08-02718d91616b.jpg)

Versión 3:

![icono_cashwallet2](https://cloud.githubusercontent.com/assets/15219855/12358715/d6eec718-bb80-11e5-8284-c02acefdfd9e.jpg)

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina te comparto esta versión tomando como base la propuesta de victor 

Versión 1
![icon-cash-wallet1](https://cloud.githubusercontent.com/assets/13594347/12370063/751b3fca-bbd6-11e5-8775-2d495788f2e5.png)

Versión 2
![icon-cash-wallet2](https://cloud.githubusercontent.com/assets/13594347/12370064/751ebf4c-bbd6-11e5-8c68-e741481b89e2.png)

Versión 3
![icon-cash-wallet3](https://cloud.githubusercontent.com/assets/13594347/12370065/75253d2c-bbd6-11e5-9d7e-c235a6590161.png)
