### ISSUE TITLE
SUPERISSUE: Crear imagenes que apoyen el texto del Fermat White Paper

### ISSUE THREAD

**Issue by jonathanborges3d** [bitDubai/fermat-graphic-design#417]
Es necesario crear una serie de imágenes que apoyen visualmente el White Paper, asi como ya esta el Fermat App Token desarrollado e implementado en el texto.

Se deberan realizar algunas tareas puntuales:

1) Mejorar el gráfico que representa el Core concept utilizando recursos propios y no de terceros.

2) Generar una escena con un dispositivo (puede ser el teléfono empleado en otras escenas) que muestre la interfaz de usuario de Fermat en pantalla.

3)  Representar el mecanismo de mineria descrito en el white paper

4) Crear representaciones de las micro licencias y los incentivos

5) Representar la característica de privacidad en la red Fermat

@Luis-Fernando-Molina

**Comment by Luis-Fernando-Molina** [comment]
La nueva version del white paper está aca: 

https://github.com/bitDubai/strategy/blob/master/White-Paper-v2-Draft.md

@gustl-arg  Vas a tener que decirle con mas precisión a Jonathan como deber ser porque sino no va a funcionar. No podemos esperar 2 semanas a que lo deduzcan porque el deadline para tener la version 2 lista es el fin de semana que viene, y no hay margen para esperar mas. 

@jonathanborges3d cada infográfico hace un issue aparte y tageame ami tambien asi opino.

suerte!

**Comment by gustl-arg** [comment]
@jonathanborges3d por favor investigar y encontrar con que programa se hacen estas ilustraciones esquematicas que utiliza IBM en su blockchain 
https://github.com/openblockchain/obc-docs/blob/master/biz/usecases.md

para que @Luis-Fernando-Molina pueda realizar la verison basica de las infografía y luego vos aplicar todo tu arte 3d.

**Comment by jonathanborges3d** [comment]
@gustl-arg Generalmente éste tipo de infografías se realizan con un editor de imágenes vectoriales como Adobe Ilustrator, o también Photoshop. Lo que que se me ocurre por lo pronto es que realice el boceto en prezzi o powerpoint, utilizando formas prediseñadas o figuras geométricas indicando el elemento que se quiere ver representado y la relación que tiene con otros a través de flechas, lineas y algún texto. Detallar qué elementos se quiere ver en el producto final es muy importante, así no se divaga en buscar el mejor ejemplo de representación y con éso bastaría para generar una versión 3D de alta calidad.

**Comment by gustl-arg** [comment]
me parece buena tu propuesta..vemos que opina @Luis-Fernando-Molina

**Comment by Luis-Fernando-Molina** [comment]
Acaba de entrar una persona que se va a dedicar a especificar los infro graphics y luego vos los dibujas. Demosle un tiempito a que arranque y ya va a empezar a crear los casos.
