### ISSUE TITLE
Cash Wallet Design / Home View

### ISSUE THREAD

**Issue by Neoperol** [bitDubai/fermat-graphic-design#422]
#421

Diseño de la vista principal, que consta de una lista de transacciones y un scroll horizontal para ver las transacciones totales mensuales. Y dos Dialogs. 

![home](https://cloud.githubusercontent.com/assets/6201081/11889764/f64677fa-a51e-11e5-9fd7-bf21c1266a66.png)
![withdrawal](https://cloud.githubusercontent.com/assets/6201081/11889765/f661b93e-a51e-11e5-86d7-28d82747385c.png)
![deposit](https://cloud.githubusercontent.com/assets/6201081/11889766/f6796f70-a51e-11e5-96ad-72caed2ce386.png)

@Luis-Fernando-Molina 
@abicelis

**Comment by Neoperol** [comment]
![home](https://cloud.githubusercontent.com/assets/6201081/11889824/6e61eeae-a51f-11e5-9f24-4aa1c70a7495.png)

**Comment by Neoperol** [comment]
Propuesta para los dialogs.
@abicelis 

![home_dialog_deposit](https://cloud.githubusercontent.com/assets/6201081/11919983/6212ccc0-a733-11e5-86c8-66ba195cd44f.png)
![home_dialog_withdraw](https://cloud.githubusercontent.com/assets/6201081/11919984/6229c948-a733-11e5-9948-270276e55be5.png)

**Comment by Neoperol** [comment]
![home](https://cloud.githubusercontent.com/assets/6201081/11964147/da7aaaa8-a8bd-11e5-997f-2de5179073df.png)

@abicelis

**Comment by abicelis** [comment]
@Neoperol 

Veo aplicados todos los cambios que dicsuti con @Luis-Fernando-Molina 
- Eliminaste los meses en el home (Quiza ésta idea le sirva al bank wallet?)
- Pusiste el book balance mas pequeno que el available balance
- La lista de transaccinoes esta OK

Los dialogs hara falta que los vea @Luis-Fernando-Molina a ver que opina
