### ISSUE TITLE
Habilitar un espacio para colocar la imagen del Mantainer dentro las Fichas de fermat.org 

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#423]
Las fichas deben mantener la forma, diseño y ubicación original del developer solo se debe incluir al mantainer y debe tener la siguiente información:
- Nombre del mantainer
- Usuario de github del mantainer

Dejo referencia de las fichas ya aprobadas 

Caso #403

**Comment by ivonnesantos** [comment]
![presentacion-01](https://cloud.githubusercontent.com/assets/15238660/11915132/1e1eed82-a66b-11e5-9d1e-f179582c72a9.jpg)

@arnaldos @Luis-Fernando-Molina

**Comment by arnaldos** [comment]
@ivonnesantos el 1 ok, el 2 el mantainer colocalo en el area blanca, el icono de android colocalo a la derecha al lado del otro icono, el 3 igual al 2, el 4 replantealo.

**Comment by m471c4** [comment]
@arnaldos @Luis-Fernando-Molina propuesta estandarizando la forma en que se muestra el mantainer.

![fichasmantainer](https://cloud.githubusercontent.com/assets/13468350/11938526/b56d360c-a7ed-11e5-9b4a-3ddc58f899bd.png)

**Comment by arnaldos** [comment]
@m471c4 para la azul alinea el modulo del mantainer y sube los editables 
plz :+1:

**Comment by m471c4** [comment]
@arnaldos no alineé el módulo del mantainer al centro en la ficha azul porque queda muy ahogado con la foto del desarrollador; y hacerla más pequeña limitaría mucho el espacio para el nombre. Por eso la alineé hacia abajo.

Ya los editables están en el repositorio. @Miguelcldn @ricardo460 favor revisar este caso cuanto antes, subí también los fondos por separado con los espacios para ambas fotografías. Una vez estén actualizadas las fichas en fermat.org podremos cerrar el caso.

**Comment by Miguelcldn** [comment]
Chévere, implementar esos cambios para fermat.org llevará su tiempo, así que pónganse cómodos jajaja, yo les estaré avisando cuando esté listo :+1:

**Comment by arnaldos** [comment]
@Miguelcldn perfecto !!! pero ya tenemos los archivos listos para cuando los vallas a implementar :smile:

**Comment by m471c4** [comment]
@arnaldos última actualización para las fichas. Ya los editables están en el repositorio y @ricardo460 está ocupándose de subirlos a fermat.org.

![fichas_descriptivas_fermat_org](https://cloud.githubusercontent.com/assets/13468350/11962737/5c3dc57a-a8b4-11e5-9422-7da7f02124b7.png)

**Comment by arnaldos** [comment]
@m471c4 perfecto :+1:
