### ISSUE TITLE
Generar un Banner para el concurso de Fermat

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#424]
Medidas 
- 851x315 (facebook)
- 1920x1053 (website)

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina te comparto el banner

![banner_concurso](https://cloud.githubusercontent.com/assets/13594347/11937413/7461ea42-a7e6-11e5-8399-f3da1e064267.jpg)

**Comment by Luis-Fernando-Molina** [comment]
"La programación te apasiona?" reemplaza a los 2 primeros
al final abajo del logo agregale "y te llevamos a Dubai"

Te invitamos a participar en un concurso para medir tus destrezas y meterte de lleno en el mundo de las crypto currencies, digital assets y sistemas P2P.

**Comment by arnaldos** [comment]
perfecto !!!

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina con el texto corregido

![banner_concurso_2](https://cloud.githubusercontent.com/assets/13594347/11938376/a13b3a54-a7ec-11e5-818c-3c1e482794bc.jpg)

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina Versión del Broshure

![broshure_concurso](https://cloud.githubusercontent.com/assets/13594347/11939274/23f6d6fa-a7f3-11e5-9504-8a78d2da67a7.jpg)

**Comment by Luis-Fernando-Molina** [comment]
El brochure no puede tapar la imagen. HaceloHacelo en otro caso porque es otro problema. Mira el brochure pasado,  tiene las bases y condiciones y que te ganas.

**Comment by arnaldos** [comment]
ok perfecto !!! ..... al banner ya le hice la correcciones esta bien así ?

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina los ajustes solicitados 

![banner_concurso_3](https://cloud.githubusercontent.com/assets/13594347/11951218/45dea900-a861-11e5-84e8-212495a5e7dc.jpg)

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina ajustes de ltexto del banner

Versión 4
![banner_concurso_4](https://cloud.githubusercontent.com/assets/13594347/11964368/5b048bac-a8bf-11e5-8012-137eb3bb0e61.jpg)

Versión 5
![banner_concurso_5](https://cloud.githubusercontent.com/assets/13594347/11964369/5b0ce306-a8bf-11e5-9674-3692ef1618ce.jpg)

Versión 6
![banner_concurso_6](https://cloud.githubusercontent.com/assets/13594347/11964370/5b0e6b86-a8bf-11e5-9fa6-846c0178feca.jpg)

**Comment by Luis-Fernando-Molina** [comment]
Y ganate un viaje a Dubai

Medí tus destrezas y metete de lleno...

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina ajustes del texto

Versión 7
![banner_concurso_7](https://cloud.githubusercontent.com/assets/13594347/11965101/911cc498-a8c4-11e5-9c1d-ad5e516d810e.jpg)

**Comment by Luis-Fernando-Molina** [comment]
Ok, ponele una sombra difusa al texto y logo

**Comment by arnaldos** [comment]
ok perfecto

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina esta bien la sombra, o la hago notar mas ?
![banner_concurso_8](https://cloud.githubusercontent.com/assets/13594347/11965572/8a92f4aa-a8c7-11e5-9e64-3a20af55a7a6.jpg)

**Comment by Luis-Fernando-Molina** [comment]
que se note mucho mas, solo la veo en el logo y no en el resto

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina aquí los ajustes de la sombra, dos versiones de saturacion.

Versión 1
![banner_concurso_8](https://cloud.githubusercontent.com/assets/13594347/11969495/435ab184-a8ec-11e5-8ee7-4af9eb92212c.jpg)

Versión 2
![banner_concurso_9](https://cloud.githubusercontent.com/assets/13594347/11969496/435f5c20-a8ec-11e5-8b5b-57521686a8d3.jpg)

**Comment by arnaldos** [comment]
ya monto otra con la sombra mas saturada

**Comment by arnaldos** [comment]
![banner_concurso_10](https://cloud.githubusercontent.com/assets/13594347/11969538/e32c981c-a8ec-11e5-9b71-07e2018515a8.jpg)

**Comment by Luis-Fernando-Molina** [comment]
Arnaldo, la sobra es TODOS LOS TEXTOS y DIFUSA

**Comment by arnaldos** [comment]
ok

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina  listo !
![banner_concurso_11](https://cloud.githubusercontent.com/assets/13594347/11969867/1641cc1c-a8f3-11e5-8ccf-d8f8892e0faf.jpg)

**Comment by Luis-Fernando-Molina** [comment]
Adoptá

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina listo !!!

![banner_concurso_12](https://cloud.githubusercontent.com/assets/13594347/11970007/9dc3ce2c-a8f5-11e5-897f-0f88c5573d75.jpg)

**Comment by Luis-Fernando-Molina** [comment]
ok listo subi aca la version con el peso apropiado y tamaño para la pagina

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina propuesta del marco 

Versión 1
![banner_concurso_13](https://cloud.githubusercontent.com/assets/13594347/11970573/9c94e41e-a8ff-11e5-81b7-679aad3d4648.jpg)

Versión 2
![banner_concurso_14](https://cloud.githubusercontent.com/assets/13594347/11970574/9c9a797e-a8ff-11e5-9c45-28bb5532caf4.jpg)

**Comment by Luis-Fernando-Molina** [comment]
OK vamos von la segunda. 

Postea en el tamaño y peso apropiado

**Comment by arnaldos** [comment]
ok perfecto !!!

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina  listo tamaño y peso

![banner_1](https://cloud.githubusercontent.com/assets/13594347/11971002/00ce9116-a908-11e5-8f08-5c2f9b21b5dc.jpg)

**Comment by Luis-Fernando-Molina** [comment]
:+1:
