### ISSUE TITLE
Crear un icono de Help para la bitcoin wallet

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#425]

**Comment by victoralfonzohd** [comment]
@arnaldos 

![icono_ayuda](https://cloud.githubusercontent.com/assets/15219855/11914519/868cbef0-a655-11e5-96af-677b24e44fe8.jpg)

**Comment by arnaldos** [comment]
create otra propuesta plz

**Comment by victoralfonzohd** [comment]
@arnaldos 

Usando la misma propuesta:

![icono_ayuda1](https://cloud.githubusercontent.com/assets/15219855/11941606/095dab42-a803-11e5-8635-495408a04b71.jpg)

**Comment by victoralfonzohd** [comment]
@arnaldos 

![icono_ayuda](https://cloud.githubusercontent.com/assets/15219855/11941611/18d6c84c-a803-11e5-8103-15fddbe61a32.jpg)

**Comment by victoralfonzohd** [comment]
@arnaldos 

Propuestas de forma:

![icono_ayuda](https://cloud.githubusercontent.com/assets/15219855/11943654/ce90b856-a811-11e5-96a8-983adb651bbb.jpg)

**Comment by victoralfonzohd** [comment]
@arnaldos 

![icono_ayuda](https://cloud.githubusercontent.com/assets/15219855/11943896/ac906d44-a813-11e5-988f-ff92e9addd18.jpg)

**Comment by arnaldos** [comment]
@victoralfonzohd  vamos a usa este, ya le pase el icono a matias

![help_buton_48dp](https://cloud.githubusercontent.com/assets/13594347/11959904/172500dc-a8a2-11e5-966d-6deff50bb157.png)

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina icono de help para esta propuesta busque estandarizar el tono referente a lo que se viene trabajando por ello coloque en diapo (blanco) recomiendo la versión 1 o 2. de esta serie.

Versión 1
![icons-09](https://cloud.githubusercontent.com/assets/13594347/12062586/89b305f6-af71-11e5-8ae7-02f64855350e.jpg)

Versión 2
![icons-10](https://cloud.githubusercontent.com/assets/13594347/12062587/89b6d640-af71-11e5-9653-07076cef8165.jpg)

Versión 3
![icons-11](https://cloud.githubusercontent.com/assets/13594347/12062588/89bc2d66-af71-11e5-9f15-29dbaeae67af.jpg)

Versión 4
![icons-12](https://cloud.githubusercontent.com/assets/13594347/12062585/89ae766c-af71-11e5-8819-0fb84c51f415.jpg)

Versión 5
![icons-08](https://cloud.githubusercontent.com/assets/13594347/12062591/9ad19f0a-af71-11e5-9f31-c12681a04759.jpg)
