### ISSUE TITLE
Crear un banner de gráficos para la User Wallet Community 

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#426]

**Comment by emmysm** [comment]
![banner inta user community-02](https://cloud.githubusercontent.com/assets/15143489/11915790/5a57d7d2-a689-11e5-9d3e-139d344a8de8.png)

![banner inta user community-01](https://cloud.githubusercontent.com/assets/15143489/11915787/3eb751b0-a689-11e5-8541-8e50b7c0a6ce.png)

@arnaldos

**Comment by arnaldos** [comment]
@emmysm la 1ra version prueba en el fondo del banner colocar en la parte superior el tono gris y abajo blanco, la tipografía coloca tonos azules.

**Comment by emmysm** [comment]
![banner inta user community-01](https://cloud.githubusercontent.com/assets/15143489/11942332/fb1d8d9a-a807-11e5-9577-e82f9752fcef.png)

![banner inta user community-02-02-02](https://cloud.githubusercontent.com/assets/15143489/11942555/9bea11d4-a809-11e5-9774-691bd9846d7f.png)

@arnaldos

**Comment by emmysm** [comment]
![banner inta user community-02](https://cloud.githubusercontent.com/assets/15143489/11942780/08fd8840-a80b-11e5-8a0d-fab97c00d378.png)

**Comment by arnaldos** [comment]
@emmysm prueba otra tipografía plz y juega con los tonos azules

**Comment by emmysm** [comment]
![banner inta user community](https://cloud.githubusercontent.com/assets/15143489/11946044/8f0c0372-a828-11e5-9e2a-f915448c1c26.png)

@arnaldos

**Comment by emmysm** [comment]
![banner inta user community](https://cloud.githubusercontent.com/assets/15143489/11946053/c25fad6e-a828-11e5-9740-cb64bf854af4.png)

**Comment by arnaldos** [comment]
@emmysm usa otra tipografía plz ..... prueba varias tipo sanserif

**Comment by emmysm** [comment]
![banner inta user community-01](https://cloud.githubusercontent.com/assets/15143489/11960244/f137af08-a8a3-11e5-8c3e-d69bc48b5f2d.png)
![banner inta user community-02](https://cloud.githubusercontent.com/assets/15143489/11960245/f15bc398-a8a3-11e5-99fe-7154cea69ef6.png)

@arnaldos

**Comment by arnaldos** [comment]
@emmy hasta que no se definan los nuevos logos enfocate en otro caso :smile_cat:

**Comment by emmysm** [comment]
![banner inta user community-02](https://cloud.githubusercontent.com/assets/15143489/12044816/60aea65e-ae6a-11e5-8570-af463b95f58d.png)
![banner intra user identity](https://cloud.githubusercontent.com/assets/15143489/12044817/6187a544-ae6a-11e5-93bf-473a52144ede.png)

@

**Comment by emmysm** [comment]
![banner inta user community-01](https://cloud.githubusercontent.com/assets/15143489/12044863/10b1b3e8-ae6b-11e5-86a9-9b5d65a038d9.png)
@arnaldos

**Comment by emmysm** [comment]
@arnaldos @Luis-Fernando-Molina 

![banner intra user identity-01-01](https://cloud.githubusercontent.com/assets/15143489/12401206/33d87a8c-bdf7-11e5-9e88-442bd1151341.png)

**Comment by emmysm** [comment]
![banner intra user community-02](https://cloud.githubusercontent.com/assets/15143489/12401728/8dbf7516-bdfa-11e5-8ecc-a16b75bc5164.png)

**Comment by emmysm** [comment]
![banner -02](https://cloud.githubusercontent.com/assets/15143489/12428252/c91ba588-beb5-11e5-8656-6e513b6d51ce.png)
![banner -01](https://cloud.githubusercontent.com/assets/15143489/12428255/cb60f136-beb5-11e5-9ae5-f7ccc1ff5461.png)
@arnaldos

**Comment by arnaldos** [comment]
@emmysm  :+1:
