### ISSUE TITLE
Generar un Broshure para el concurso de Fermat

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#427]

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina comparto el broshure

Versión 1
![broshure-01](https://cloud.githubusercontent.com/assets/13594347/11951201/1b82e3d8-a861-11e5-9b93-80aea07c3cbc.jpg)

Versión 2
![broshure-02](https://cloud.githubusercontent.com/assets/13594347/11951202/1b872880-a861-11e5-9ab1-2eddffb023a7.jpg)

Versión 3
![broshure-03](https://cloud.githubusercontent.com/assets/13594347/11951203/1b8b8f42-a861-11e5-8f7c-88530eee6610.jpg)

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina aqui los ajustes que hablamos 

Versión 4 
![broshure-04](https://cloud.githubusercontent.com/assets/13594347/11963316/3fd41f98-a8b8-11e5-8037-629b0f83df54.jpg)

Versión 5 
![broshure-05](https://cloud.githubusercontent.com/assets/13594347/11963317/3fd5e7ba-a8b8-11e5-8e6f-d80f6f4e1f1b.jpg)

**Comment by Luis-Fernando-Molina** [comment]
Version 4

Solo debes seguir los siguientes pasos
1. Solicitá tu componente... 
2. Mejorado lo más posible para sumar puntos
3. Viajábamos a Dubai con su autor original y los otros ganadores. 

El filtro oscuro ponelo lo más transparente que se pueda

**Comment by Luis-Fernando-Molina** [comment]
Adoptá un componente y viajá  a Dubai! 

Proba otro colo para esa frase y ponela como dice acá

**Comment by Luis-Fernando-Molina** [comment]
Bases de concurso: www.bitDubai.com......

**Comment by arnaldos** [comment]
perfecto !!

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina los ajustes solicitados

Versión 6
![broshure-07](https://cloud.githubusercontent.com/assets/13594347/11964887/ee6656ac-a8c2-11e5-9c0e-4629803a0715.jpg)

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina ajustes

Versión 7
![broshure-08](https://cloud.githubusercontent.com/assets/13594347/11965146/e3e03afc-a8c4-11e5-9813-fbe33ebbee5c.jpg)

**Comment by Luis-Fernando-Molina** [comment]
Poné textualmente esto:
1. Aprendé que es Fermat.
2. Solicitá tu componente Fermat en adopción.
3. Mejoralo lo mas posible para sumar puntos.
4. Viajá a Dubai con su autor y los otros ganadores.   (sin salto de linea)

**Comment by Luis-Fernando-Molina** [comment]
Pone:

Bases del Concurso:

**Comment by Luis-Fernando-Molina** [comment]
En algun lado pone: "El premio incluye..."   Skydive Dubai + Desert Tour + .....

**Comment by Luis-Fernando-Molina** [comment]
Al filto sobre el barco aplicale un degradé para que sea mas oscuro sobre las letras y vaya siendo mas transparente a medida que se acerca al barco.

**Comment by Luis-Fernando-Molina** [comment]
Ganate un viaje a dubai ponelo en blanco

**Comment by arnaldos** [comment]
ok perfecto !!

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina los ajustes + cambio de color del texto que esta sobre el plano negro

Versión 8
![broshure-09](https://cloud.githubusercontent.com/assets/13594347/11965763/0ba11800-a8c9-11e5-8b40-7588de2462bf.jpg)

Versión 9
![broshure-10](https://cloud.githubusercontent.com/assets/13594347/11965764/0ba54bf0-a8c9-11e5-9cb7-024038d3461f.jpg)

Versión 10
![broshure-11](https://cloud.githubusercontent.com/assets/13594347/11965765/0ba9ebe2-a8c9-11e5-9b30-87b2054c1345.jpg)

**Comment by arnaldos** [comment]
en cuanto al color del texto me quedo con el de la Versión 8 funciona mejor visualmente

**Comment by Luis-Fernando-Molina** [comment]
no me entendiste lo del premio Era para armar algo junto a las imagenes que ya tenes puestas

**Comment by Luis-Fernando-Molina** [comment]
sigamos con la version 10

**Comment by Luis-Fernando-Molina** [comment]
A la frase Adoptá un componente... salale la "negritas" y ponela en blanco. A la franja negra tambien hacela mas transparente a la derecha.

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina coloque dos versiones cuya diferencia es la tipografía en la frase Adoptá un componente...

para el plano negro esta bien asi de transparente del lado derecho ?

versión 11
![broshure13](https://cloud.githubusercontent.com/assets/13594347/11969450/cd173e48-a8eb-11e5-98c1-d19820a13648.jpg)

versión 12
![broshure-12](https://cloud.githubusercontent.com/assets/13594347/11969451/cd1c2930-a8eb-11e5-9472-663e166f6e82.jpg)

**Comment by Luis-Fernando-Molina** [comment]
A la frase Adopta un componente  ponele el tipo de letra que usaste en el banner. El fondo de esta frase parece terminar junto con la palabra DUBAI, no queda bien, que llegue hasta el final como estaba antes, aunque suave.

Me gustaba mas cuando los circulitos estaban arriba. Busca la forma de que queden ahi y que tenga el otro texto también

**Comment by Luis-Fernando-Molina** [comment]
Ponele una sombra interna tambien sobre la linea rosa de abajo

**Comment by arnaldos** [comment]
ok ya lo ajusto

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina y le coloque los ajustes 

Versión 13

![broshure14](https://cloud.githubusercontent.com/assets/13594347/11969837/a18d1976-a8f2-11e5-9a4f-e827a729ee1c.jpg)

**Comment by Luis-Fernando-Molina** [comment]
Solo tenés que seguir los siguientes pasos;

Dubai es sin acento en la í

**Comment by arnaldos** [comment]
ok

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina  listo los ajustes en el texto
![broshure15](https://cloud.githubusercontent.com/assets/13594347/11969996/63faab8e-a8f5-11e5-8673-185213ecf65f.jpg)

**Comment by Luis-Fernando-Molina** [comment]
pasos:

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina  listo 
![broshure16](https://cloud.githubusercontent.com/assets/13594347/11970436/3dcbb162-a8fd-11e5-8a33-091060c21b7f.jpg)

**Comment by Luis-Fernando-Molina** [comment]
OK postea la versión con el peso y tamaño apropiado

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina  listo tamaño y peso 

![broshure_1](https://cloud.githubusercontent.com/assets/13594347/11970997/edea317c-a907-11e5-9254-a715236e7ff2.jpg)

**Comment by Luis-Fernando-Molina** [comment]
:+1:
