### ISSUE TITLE
Crear un Logo para Fermat CHT (Chat Platform)

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#428]
Es una plataforma de chat

**Comment by ivonnesantos** [comment]
![fermat chat-01](https://cloud.githubusercontent.com/assets/15238660/11969098/1db141aa-a8e7-11e5-854f-bf74df6b84bc.jpg)

@arnaldos @Luis-Fernando-Molina @emmanuelcolina

**Comment by Luis-Fernando-Molina** [comment]
Hola Ivonne, el logo tienen que seguir la linea de todos los otros logos que hay en www.fermat.org en la parte de arquitectura

**Comment by ivonnesantos** [comment]
![fermat chat-01](https://cloud.githubusercontent.com/assets/15238660/11970317/f6157c24-a8fa-11e5-8083-4941072abca1.jpg)

@arnaldos @Luis-Fernando-Molina

**Comment by arnaldos** [comment]
@ivonnesantos para las sombras usa la inclinación de 45º.

**Comment by ivonnesantos** [comment]
@arnaldos le corregí las que no estaban a 45 porque la del fondo son las mismas que los demás iconos 
![fermat_cht-01](https://cloud.githubusercontent.com/assets/15238660/11987308/0e765004-a9af-11e5-8f25-e26b08d8b002.jpg)

**Comment by arnaldos** [comment]
@ivonnesantos genera otras versiones basadas en la propuesta 1

**Comment by arnaldos** [comment]
y verifica la inclinación de las sombras de los elementos estén a 45º

**Comment by ivonnesantos** [comment]
![fermat_cht-02](https://cloud.githubusercontent.com/assets/15238660/12027915/d1b39cf8-ada0-11e5-93db-2ad7d6ac64ce.jpg)

@arnaldos @Luis-Fernando-Molina

**Comment by arnaldos** [comment]
@ivonnesantos estandariza los stroke según lo que ya se ha trabajado. La versión sangrada no funciona ya que rompe con el standar de los otros logos. por favor revisa las sombras no tienen la misma inclinación que los otros logos. la propuesta 1_1 es muy igual a la 1 .. cuando mensionaba ver otras versiones basadas en la propuesta 1. me referia a buscar otra propuesta  tal ves cambiando la forma del globo de los mensajes y tal ves manteniendo la misma diagramación de los elementos. dale la vuelta a esto. toma en cuenta lo de **la sombra y el stroke** ve como se colocaron en los otros logos para que lo apliques en este.

**Comment by ivonnesantos** [comment]
![fermat_cht-02](https://cloud.githubusercontent.com/assets/15238660/12060197/9c6e5914-af3c-11e5-8647-8c6f2383e6cf.jpg)

@arnaldos @Luis-Fernando-Molina

**Comment by Luis-Fernando-Molina** [comment]
para mi va por el lado de la 1 o la 1_1

**Comment by ivonnesantos** [comment]
@arnaldos @Luis-Fernando-Molina propuesta basándose en la 1
![fermat_cht-03](https://cloud.githubusercontent.com/assets/15238660/12106216/300d8c80-b32f-11e5-840e-ceb13516b249.jpg)

**Comment by Luis-Fernando-Molina** [comment]
:+1:
