### ISSUE TITLE
Cash Wallet Design / Setup View

### ISSUE THREAD

**Issue by Neoperol** [bitDubai/fermat-graphic-design#431]
#421

Propuesta para la vista de Set up de la Cash Wallet. 
![setup](https://cloud.githubusercontent.com/assets/6201081/11985305/856d17a2-a995-11e5-91cc-bdc0a202d3c8.png)

@Luis-Fernando-Molina 
@abicelis

**Comment by Neoperol** [comment]
![wizard](https://cloud.githubusercontent.com/assets/6201081/11985376/5fd2e4b2-a996-11e5-9116-b747d0d1d6ac.jpg)

@abicelis

**Comment by Luis-Fernando-Molina** [comment]
"Please note that this step can not be undone"

La frase debe estar mas chica o de alguna manera notar que no es tan importante como la otra

**Comment by Neoperol** [comment]
![wizard](https://cloud.githubusercontent.com/assets/6201081/11996286/ca42e874-aa31-11e5-8433-9d6b786099ab.jpg)

Que tal así. 

@Luis-Fernando-Molina

**Comment by abicelis** [comment]
@Neoperol 

De repente es muy jodio/necio de mi parte, pero por mi un blur al "MacBook Air" que se lee al fondo

**Comment by Luis-Fernando-Molina** [comment]
tiene razon @abicelis , el resto puede quedar asi

**Comment by Neoperol** [comment]
![wizard](https://cloud.githubusercontent.com/assets/6201081/12003831/e4f46ae6-ab01-11e5-994c-2a65edf706ba.jpg)

Buen punto. No lo habia notado.
En la carpeta resources de cada vista, estan las imagenes que se necesitas y en el texto los colores y las dimensiones. 

@abicelis

**Comment by abicelis** [comment]
@neoperol dale, estaré pendiente del drive para cuando subas los recursos para aplicarlos a la wallet
