### ISSUE TITLE
SUPERISSUE: Crear un video infográfico acerca de Fermat

### ISSUE THREAD

**Issue by jonathanborges3d** [bitDubai/fermat-graphic-design#432]
El video estará dirigido a un público que se asume ya tiene conocimiento acerca de bitcoin. Basicamente será explicar el proyecto en unos 2 minutos utilizando material ya generado en combinación con ilustraciones nuevas.

@Luis-Fernando-Molina  @AnaPietrosanti  @sharikarvelo

**Comment by Luis-Fernando-Molina** [comment]
Ya estoy trabajando en el script de este primer video, cuando lo tenga mas pulido, lo colocaré aquí.

**Comment by jonathanborges3d** [comment]
Voy a colocar aquí la primera parte de una propuesta de history board basada en el script:

Percibo éste script como tres escenas de ideas generales con una serie de sub-escenas que representan ideas concretas:

## Escena 1

### \* Escena 1A #480

### \* Escena 1B #481

### \* Escena 1C #482

## Escena 2

### \* Escena 2A #483

### \* Escena 2B #484

### \* Escena 2C #485

## Escena 3

### \* Escena 3A #492

### \* Escena 3B #493

### \* Escena 3C #494

### \* Escena 3D #495

### \* Escena 3E #496

## Escena 4 #497

Lo describo a continuación:

## What is Fermat? (Escena 1)

Aquí aparecerían palabra por palabra hasta que  se muestra el logo de Fermat

### "Fermat is an open source software project that runs on android devices. This software can run Fermat APPs, which are like mobile APPs except that they run on top of Fermat." (Escena 1A)

#### ...Fermat is...

Se mantendría el logo en pantalla pero desaparecerían las palabras "What is".

#### ...open source software project..

Me parece que aquí se puede utilizar el emblema que representa ésta característica en otros softwares
![](http://www.cioal.com/wp-content/uploads/osource.jpg)

#### ... that runs on android devices.

Aquí se requerirán dos o tres modelos de teléfonos y tablets distintas para ilustrar variedad de dispositivos donde corre Fermat. Todos los dispositivos deberían tener en pantalla el logo de Fermat, luego uno solo se queda en primer plano.

#### ...This software can run Fermat APPs, which are like mobile APPs except that they run on top of Fermat...

Se hace zoom in hacia el dispositivo y se muestra el desktop de la app con los iconos, se pueden resaltar con alguna animación. Antes de pasar a la siguiente escena se hace zoom out y el dispositivo sale por alguno de los lados.

### "Technically, Fermat is a Framework, a p2p Network and an Ecosystem of Fermat APPs.  It is similar to WordPress, since the goal is to easily build APPs using plug-ins.  There are some differences though.  Fermat runs on Android devices instead of servers. It’s also not intended for building web sites, but to build and run Fermat APPs." (Escena 1B)

#### ...Technically, Fermat is a Framework...

Aquí es necesario emplear una imagen que represente bien el concepto de "framework", puede ser una biblioteca, armario o una estructura como he visto en algunas imágenes.

#### ....a p2p Network...

Se representaría con diversos dispositivos conectados entre si, computadoras, laptos, tablas, teléfonos y algunos servidores que establezcan las conexiones. 

#### ...and an Ecosystem of Fermat APPs...

Pueden aparecer los iconos de empleados en la escena del desktop de Fermat formando un círculo y girando en un sentido. 

#### ...It is similar to WordPress, since the goal is to easily build APPs using plug-ins...

Nó sé si aquí se puede utilizar el logo de WordPress directamente pero sería bueno incluirlo ya que se le hace mención. Lo siguiente sería animar un pequeño puzzle que se va armando o conexiones entrelazadas de varios cables pero que al final muestre un icono de APP.

#### ...There are some differences though.  Fermat runs on Android devices instead of servers. It’s also not intended for building web sites, but to build and run Fermat APPs.

Se pueden colocar los logos de Fermat y WordPress dividiendo la imagen en forma vertical y bajo estos aparecen Dispositivos android (tablets, teléfonos) y servidores, luego iconos de Fermat APPs y un monitor mostrando una página web o logos de navegadores.

### "Fermat APPs use the Fermat p2p Network to exchange information. This fact makes them censorship resistant." (Escena 1C)

#### ...Fermat APPs use the Fermat p2p Network to exchange information...

Se mostraría una red de dispositivos android y servidores conectados por líneas y se trazan rutas de animación para un elemento que represente la Meta Data que circule por éstas líneas de un dispositivo a otro cruzando la red.

#### ...This fact makes them censorship resistant...

Sobre la escena anterior se superpone una imágen como ésta:

![](http://domtotal.com/img/artigos/2912_799.jpg)

que luego se puede animar desmoronándose o quebrándose.

## Let's look at how it works: (Escena 2)

Puede aparecer palabra por palabra en una manera similar a la Escena 1 ("What is Fermat"), sincronizado con el audio de la narración

### "Fermat has an existing network of developers, designers, academics, and artists working on the project. They have laid the initial groundwork in order to build APPs on top of Fermat." (Escena 2A)

#### ...Fermat has an existing network of developers, designers, academics, and artists working on the project...

Aquí se puede representar cada una de las funciones de los miembros del proyecto utilizando personajes con características físicas similares pero atuendos diferentes, por ejémplo:

 ...developers..   Personaje de lentes (lo común pensado) con una franela que 
                          tenga como diseño "(</>)", el logo de android u otra que recuerde programación.

 ...designers...   Debería tener algún bloc de dibujo, lápices, una estilográfica, reglas u otros 
                          elementos que le asocien con el diseño, También puede seguir la idea de la franela
                          identificada con los iconos de software de diseño o figuras geométricas.

 ...academics...  Lo que se me ocurre es un personaje de chaqueta, barba y con algunos libros en 
                          las manos.

...and artists...   Probablemente esté bien alguien con una boina de pintor u otro elemento que lo
                          relacione con las artes.

Podrían ir apareciendo en pantalla a medida que los nombren. Pueden ser animados, con algún movimiento corporal mínimo.

#### ...They have laid the initial groundwork in order to build APPs on top of Fermat...

Se pueden organizar los personajes mostrados anteriormente de forma circular alrededor de un dispositivo móvil que aparecen en medio del círculo y muestra el desktop de fermat con los iconos de las apps.

### "Developers can build Fermat APPs re-using existing components. Usually new Fermat APPs add more components to the pool to be further re-used." (Escena 2B)

#### ...Developers can build Fermat APPs re-using existing components...

Ésta característica en particular puede denotarse haciendo una animación donde el personaje del desarrollador  arma una app utilizando partes de un puzzle que pueden representar los componentes. 

También puede ser dentro del dispositivo mostrado en la escena anterior donde se ve una mano que arma el puzzle y forma el icono de la app.

#### ...Usually new Fermat APPs add more components to the pool to be further re-used.

 Aquí aparecen muchas más piezas de puzzle de diferentes colores o mostrando secciones de otros iconos de Fermat apps en la pantalla del dispositivo. Zoom out hasta ver el personaje del programador con el dispositivo en la mano.

### "Developers own the components they build, meaning that they can attach a Micro-Use-License to each of them to later receive a stream of micro-payments. These micro-payments are generated from end users using Fermat APPs that needed those components." (Escena 2C)

#### ...Developers own the components they build, meaning that they can attach a Micro-Use-License to each of them to later receive a stream of micro-payments...

Aquí se introduce el tema de la propiedad sobre los componentes construidos en fermat, la micro licencia de uso y el sistema de micro pagos que recibiría e desarrollador por el uso de sus componentes.

Pienso en un personaje que se anima escribiendo en un teléfono, luego muestra en primer plano la pantalla con un icono de puzzle (para darle coherencia con las idea mostrada en otras escenas, de que el puzzle representa componentes) con una pequeña imagen del mismo personaje en un lado, como si tuviese una fotografía, de modo que se refuerce la idea de propiedad sobre el componente. Posteriormente puede aparecer junto al icono de puzzle y la "fotografía" del personaje una imagen similar a ésta:

(Solo el papel, no el monitor)
![](http://www.prefsuite.com/img/content/thumbs/PrefSuite_licencia.png)

Ésto sería para representar las micro licencias y luego pueden ir apareciendo monedas que salen de la parte lateral del dispositivo a un ritmo constante, dando la idea de los micro pagos.

#### ...These micro-payments are generated from end users using Fermat APPs that needed those components

(por desarrollar)

## What are the advantages of Fermat APPs to developers? (Escena 3)

(por desarrollar)

### \* The biggest advantage is that you don't have to code it yourself. Currently there is a queue where you can add your proposed project, and if it’s a good fit, it can be coded for free by the current network of developers. (Escena 3A)

(por desarrollar)

### \* Your Fermat APP will be peer to peer, meaning that it won't need to go through any third party to exchange information between two devices. It can still go to your back-end web services to access your core systems. (Escena 3B)

(por desarrollar)

### \* Your APP will easily handle both cryptocurrency and digital assets. This opens up the market for your services to the entire world. (Escena 3C)

(por desarrollar)

### \* Your APP can be cloned and re-used with a different look and feel but still going to your back-end services.  This can drive more adoption and users to your business.  The goal of this feature is to reach niche audiences globally. (Escena 3D)

(por desarrollar)

### \* Your APP will be open source meaning that anyone can check the code and review it.

### \* Your APP can include any of the already built functionality just by re-using already built components. (Escena 3E)

(por desarrollar)

## If you are interested in joining the Fermat project, or to learn more, please visit Fermat.org (Escena 4)

(por desarrollar)

@Luis-Fernando-Molina @AnaPietrosanti @sharikarvelo

**Comment by jonathanborges3d** [comment]
Me gustaría que me diesen sus opiniones respecto al borrador del story board que coloqué arriba. Todavía faltan partes del script, iré actualizándolo. 

@Luis-Fernando-Molina @AnaPietrosanti @sharikarvelo @gustl-arg

**Comment by Luis-Fernando-Molina** [comment]
@jonathanborges3d me parece que va bien orientado. Dividí por favor cada sub-escena en un caso apuntando a este asi podemos discutirs los detalles de cada una individualmente sin que sea un caos.

**Comment by AnaPietrosanti** [comment]
Gracias @jonathanborges3d , con esto puedo añadirlo al storyboard que estoy trabajando, separado por escena con gráficos referenciales para determinar los iconos y gráficos que necesitamos.

**Comment by AnaPietrosanti** [comment]
@Luis-Fernando-Molina @jonathanborges3d @sharikarvelo 

Para mejor organización del proceso de creación del vídeo les desgloso aquí los pasos para lograrlo:
1. Brainstorming
2. Script (guión)
3. Desglose de escenas (guión técnico)
4. Storyboard (borrador y puesta en escena, aquí se definen tanto los elementos a utilizar y como serán las acciones/animaciones a mostrar. Con este storyboard aprobado, se tendrá una idea bastante clara de lo que sucederá en el vídeo y también determinaremos si esa idea que se quiere dar, funciona.)
5. Ilustración y diseño de los personajes y paquete gráfico (según ejemplos aprobados en el storyboard.)
6. Locución de off. (esto es imprescindible tenerlo antes de pasar al siguiente paso).
7. Animación de los elementos y personajes en escena. 
8. Un lindo vídeo que atraerá muchas personas a participar en el proyecto Fermat.

**Comment by jonathanborges3d** [comment]
Ya las escenas están desglosadas por casos y vinculadas a éste al principio del script. Debemos ir generando propuestas de storyboard según cada fragmento del script para luego pasar a la ilustración y diseño. @AnaPietrosanti @sharikarvelo

**Comment by jonathanborges3d** [comment]
Estado y progreso general del video:
- [x] Brainstorming (100%)
- [x] Script (guión) (100%)
- [x] Desglose de escenas (guión técnico) (100%)
- [x] Storyboard (100%)
- [x] Ilustración y diseño de los personajes y paquete gráfico (100%)
- [x] Locución de off. (100%)
- [x] Animación de los elementos y personajes en escena. (60%)
- [ ] Edición de audio (efectos de sonido y música de fondo) 
- [ ] Publicación.

Fecha pautada de publicación: Semana del 29/02 al 4/03

**Comment by Luis-Fernando-Molina** [comment]
Jonathan, necesitamos tener ciclos de feedback antes de que este todo listo. Sino te vas a encontrar con que van a tener que rehacer gran parte del trabajo, ya vas a ver. Por eso te venía pidiendo que cuando tengan una version completa, aunque sin audio o musica o lo que fuera, tienen que mandarla para arriba para obtener feedback. No estoy para nada de acuerdo con ver esto por primera vez recien a fin de mes.

**Comment by jonathanborges3d** [comment]
Video Publicado:

https://www.youtube.com/watch?v=87CNZups6OM
