### ISSUE TITLE
Crear un logo para el website dev.fermat.org 

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#433]

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina  te comparto las versiones para el logo de dev.fermat.org me apunto por la diagramación de la Versión 1.

Versión 1
![fermat_dev1](https://cloud.githubusercontent.com/assets/13594347/12042986/808db248-ae52-11e5-812b-aef40683b575.png)

Versión 2
![fermat_dev2](https://cloud.githubusercontent.com/assets/13594347/12042987/8090a23c-ae52-11e5-96d7-ed110a41baa5.png)

Versión 3
![fermat_dev3](https://cloud.githubusercontent.com/assets/13594347/12042988/809661d6-ae52-11e5-8e3e-0343d66372c2.png)

Versión 4
![fermat_dev4](https://cloud.githubusercontent.com/assets/13594347/12042991/85f46628-ae52-11e5-8de2-c47e33e1d1ca.png)

Versión 5
![fermat_dev5](https://cloud.githubusercontent.com/assets/13594347/12042993/8ee2900c-ae52-11e5-9a40-a8d062f0ae2c.png)

Versión 6
![fermat_dev6](https://cloud.githubusercontent.com/assets/13594347/12042997/9142bea8-ae52-11e5-9d53-08d3c4810d4b.png)

**Comment by arnaldos** [comment]
la Versión 6 también podría funcionar.

**Comment by Luis-Fernando-Molina** [comment]
Version 4 que solo diga Devs

**Comment by arnaldos** [comment]
perfecto !!!

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina 

Versión 7
![fermat_dev7](https://cloud.githubusercontent.com/assets/13594347/12043098/88888814-ae53-11e5-911f-f4974fd63855.png)

Versión 8
![fermat_dev8](https://cloud.githubusercontent.com/assets/13594347/12043097/888401a4-ae53-11e5-9ff3-0e6d9a35ce79.png)

**Comment by Luis-Fernando-Molina** [comment]
Listo, voy a usar la version 7
:+1:

**Comment by Luis-Fernando-Molina** [comment]
Pasale a @Miguelcldn para que reemplace el que el tiene en el sitio.

**Comment by arnaldos** [comment]
perfecto !!
