### ISSUE TITLE
Crear una versión del logo de Github para mostrar en el website de Fermat 

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#434]
La versión del logo github (el gato pulpo) verde con costuras

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina aquí te comparto la versión con la costura .... habría que hacerle un marco circular, según lo que hemos venido trabajando para fermat org ?

![octocatvector_fermat](https://cloud.githubusercontent.com/assets/13594347/12011270/e4c539b8-ac98-11e5-8aa0-c2f1dd681e61.png)

**Comment by Luis-Fernando-Molina** [comment]
pone la version original tambien para compararla por favor

**Comment by arnaldos** [comment]
vale ya la coloco

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina 
![octocatvector_fermat2](https://cloud.githubusercontent.com/assets/13594347/12011306/4571f3b8-ac9a-11e5-8620-c784e663dfac.png)

**Comment by Luis-Fernando-Molina** [comment]
la version que subiste en PNG tiene fondo transparente y el peso justo listo para usarse?

**Comment by arnaldos** [comment]
de que tamaño lo van a usar ?

**Comment by Luis-Fernando-Molina** [comment]
un cuarto de ese

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina te comparto varios tamaños en png

Tamaño 512x512
![octocat_fermat_512x512](https://cloud.githubusercontent.com/assets/13594347/12021526/9a93d770-ad59-11e5-84f3-2cdb534cc4ae.png)

Tamaño 320x320
![octocat_fermat_320x320](https://cloud.githubusercontent.com/assets/13594347/12021529/9e902112-ad59-11e5-91a5-7cf2f207f246.png)

Tamaño 200x200
![octocat_fermat_200x200](https://cloud.githubusercontent.com/assets/13594347/12021545/befdaca8-ad59-11e5-8619-107e29213849.png)

Tamaño 100x100
![octocat_fermat_100x100](https://cloud.githubusercontent.com/assets/13594347/12021550/c97802e6-ad59-11e5-9765-a0b599fbca75.png)

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina a quien le paso los archivos del octo cat ?

**Comment by Luis-Fernando-Molina** [comment]
a nadie, ya lo subi yo al sitio, el resto guardalo en tu repo
