### ISSUE TITLE
Crear un icono para el boton Add de la bitcoin wallet

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#436]

**Comment by emmysm** [comment]
![add botton 32 x 32 dp-01](https://cloud.githubusercontent.com/assets/15143489/12028739/9c63a9cc-adae-11e5-91ef-eee0d6297a0e.png)
![add button 32 x 32 dp-02](https://cloud.githubusercontent.com/assets/15143489/12028740/9c658d50-adae-11e5-9c2d-13bb50586167.png)

@arnaldos

**Comment by emmysm** [comment]
![add_but-01](https://cloud.githubusercontent.com/assets/15143489/12040502/bdf8e038-ae3b-11e5-807d-f9919f93c114.png)
![add_but2-02](https://cloud.githubusercontent.com/assets/15143489/12040503/bdfdfee2-ae3b-11e5-820c-2daef3dcacd3.png)
![but_add-01](https://cloud.githubusercontent.com/assets/15143489/12040508/c6c99ebe-ae3b-11e5-9f9a-cc8b14b834c6.png)
![butt_add-02](https://cloud.githubusercontent.com/assets/15143489/12040509/c6eec284-ae3b-11e5-838a-ba8eaa511ad6.png)

**Comment by arnaldos** [comment]
@emmysm usa el boton de la personita, solo una sugerencia reduce el tamaño para que no quede pegada al borde del stroke blanco

**Comment by emmysm** [comment]
Ya hago los ajustes =)

**Comment by emmysm** [comment]
![sin titulo-2](https://cloud.githubusercontent.com/assets/15143489/12053362/9cf67724-aeea-11e5-907b-b8a9d5c5d306.jpg)
@arnaldos

**Comment by emmysm** [comment]
![sin titulo-3](https://cloud.githubusercontent.com/assets/15143489/12053551/7f3fc670-aeec-11e5-990d-fe1259586d1c.jpg)
@arnaldos

**Comment by emmysm** [comment]
@Neoperol

**Comment by arnaldos** [comment]
@emmysm usa este icono y pasale a @furszy paraque lo aplique!!!

![icon_add](https://cloud.githubusercontent.com/assets/13594347/12055849/35a5992e-af03-11e5-832f-1d79586424a6.png)

![icon_add_button](https://cloud.githubusercontent.com/assets/13594347/12055850/35aa1332-af03-11e5-823f-d756debd1684.png)

**Comment by emmysm** [comment]
OK....

**Comment by furszy** [comment]
@emmysm  este icono ya se encuentra en el drive?
