### ISSUE TITLE
Crear un conjunto de iconos para red P2P

### ISSUE THREAD

**Issue by Miguelcldn** [bitDubai/fermat-graphic-design#437]
(Este caso puede alargarse más, por ello dejaré abajo una lista de tareas, de manera que las que están hechas tendrán un gancho)

![p2p](https://cloud.githubusercontent.com/assets/5544266/12036078/e90af954-ae14-11e5-98ae-23c9329845a0.png)

Actualmente se está desarrollando una manera de ver la red P2P de Fermat, es decir, los distintos dispositivos conectados en esta red. Lo que ven arriba es una red de prueba, representando cada nodo de la red con un cuadro negro. Al dar click en un cuadro negro, se ven cuadros azules hijos de este. Pero estos cuadros son sólo para motivos de prueba, pero se espera que los nodos sean iconos que representen el tipo de dispositivo o nodo que son. Dichos iconos serán lo que se conoce como "sprite": imágenes 2D en un espacio 3D que siempre están mirando al espectador y son imágenes PNG generalmente pequeñas digamos 150x150px (pueden ser mas grande si es necesario, pero preferiblemente de dimensión cuadrada) y de fondo transparente.

Los tipos de nodos ya confirmados que se necesitan son los siguientes:

[Tipo de nodo]: [Descripción de la imagen]
- [x] Servidor: Una super computadora o servidor.
- [x] PC: Una computadora personal.
- [x] Teléfono: Un smartphone.
- [x] Dispositivo móvil: Una tabla.
- [ ] Network Service: _por definirse_.
- [ ] Actor Network Service: _por definirse_.
- [x] Actor (Genérico): El icono de una persona, como los muñequitos del messenger `QEPD`. Cuando se agreguen los tipos de Actor's a este mismo muñeco se le pondrán detalles de su rol.
- [ ] Wallet (Genérico): El icono de una wallet, este también está ideado para tener otras versiones de clases especiales de wallets a futuro.

Nota: Yo voy a estar aprobando las propuestas, sin embargo, en caso que @Luis-Fernando-Molina apruebe alguna otra diferente a la mía, prevalece su decisión. Él me ayudará a definir los nodos que faltan, así que dicha lista de arriba estará cambiando cuando se complete la información.

**Comment by Rart3001** [comment]
@Miguelcldn el  **Actor Network Service** es un tipo de **Network Service** especializado para registrar a los actores con los servidores y obtener las lista de los actores que están "online", y están clasificados para cada tipo de actor.

**Comment by Miguelcldn** [comment]
Gracias por la aclaratoria @Rart3001! Ahora solo falta definirles un "rostro" a los Network Services

**Comment by arnaldos** [comment]
@Miguelcldn avísame cuando estén definidos:
- Network Service
- Actor Network Service

y así creo los casos para estos dos iconos

**Comment by Miguelcldn** [comment]
@arnaldos me gustaría que entre sus issues exista un label que sea `fermat-org` de manera que yo pueda filtrar los issues sobre la página

**Comment by arnaldos** [comment]
@Miguelcldn vale ya la creo y la clasifico

**Comment by arnaldos** [comment]
@Miguelcldn avisame si ya tenemos todos los iconos para la red P2P o nos faltan algunos, si estamos listos avisame si ya puedo cerrar estos casos

**Comment by Miguelcldn** [comment]
Siguen faltando los Network Service Y Actor Network Service por definirse, no se si quieran cerrar el caso por ahora y lo reabro cuando estén definidos o dejan el issue abierto y le bajan prioridad. También le pedí a @Luis-Fernando-Molina que pasara por aquí a dar su feedback pero al parecer ha estado ocupado. Los considerare aprobados todos los diseños que aprobaste tu.

**Comment by Luis-Fernando-Molina** [comment]
aca estoy... donde esta lo que tengo que revisar??? saludos

**Comment by Miguelcldn** [comment]
Aqui arriba estan todos los issues vinculados, es uno para cada tipo de nodo definido hasta ahora

**Comment by Miguelcldn** [comment]
Agregado un nuevo icono: Wallet (Genérico)

**Comment by arnaldos** [comment]
vale perfecto !!

**Comment by Miguelcldn** [comment]
Este issue puede cerrarse por ahora, no se verán los Network Services ni Wallets por ahora
