### ISSUE TITLE
Crear icono de un Servidor: Una super computadora o servidor.  para red P2P de Fermat org

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#438]
proviene del caso #437

**Comment by ivonnesantos** [comment]
![servidor](https://cloud.githubusercontent.com/assets/15238660/12188639/69317a24-b589-11e5-8858-8d61026552ef.jpg)

@arnaldos @Miguelcldn @Luis-Fernando-Molina

**Comment by arnaldos** [comment]
@ivonnesantos esta versión no esta mal, pero me gustaria ver una versión donde los elementos se aprecien mas o no tenga elemento tan pequeños ya que en una reducción se perderian

**Comment by ivonnesantos** [comment]
![servidor](https://cloud.githubusercontent.com/assets/15238660/12284522/6b5174a6-b982-11e5-8769-f64df5b6ceb7.jpg)

@arnaldos @Luis-Fernando-Molina

**Comment by arnaldos** [comment]
@ivonnesantos propuesta 2 ..... aunque contradiciendo el comentario anterior usa los elementos pequeños a ver como se comportan con esta versión.

**Comment by ivonnesantos** [comment]
@arnaldos 
![servidor](https://cloud.githubusercontent.com/assets/15238660/12303479/c42c871c-b9fc-11e5-95c2-fc878535e543.jpg)

**Comment by arnaldos** [comment]
version 2 :+1:
