### ISSUE TITLE
Crear icono de un PC: Una computadora personal.  para red P2P de Fermat org

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#439]
proviene del caso #437

**Comment by ivonnesantos** [comment]
@Miguelcldn @arnaldos @Luis-Fernando-Molina 
![computer_personal-01](https://cloud.githubusercontent.com/assets/15238660/12105734/c7bbbeae-b329-11e5-8d87-f81644175414.jpg)

**Comment by arnaldos** [comment]
@ivonnesantos otra propuesta

**Comment by Luis-Fernando-Molina** [comment]
Los circulos rojos esos los usamos para las plataformas y superlayers, no para otra cosa. gracias

**Comment by ivonnesantos** [comment]
Basandome en la propuesta que le agrado a arnaldo

![computer_personal](https://cloud.githubusercontent.com/assets/15238660/12162373/35eb5768-b4d3-11e5-929c-26c1ebf78a2e.png)

@arnaldos @Luis-Fernando-Molina  @Miguelcldn

**Comment by ivonnesantos** [comment]
@arnaldos @Luis-Fernando-Molina @Miguelcldn 
![computer_personal](https://cloud.githubusercontent.com/assets/15238660/12312154/2a5bc8f4-ba2f-11e5-96fd-bad1c81ada64.jpg)

**Comment by arnaldos** [comment]
propuesta 2 :+1:

**Comment by arnaldos** [comment]
genera los archivos y se los pasas a @Miguelcldn
