### ISSUE TITLE
Crear icono de un Teléfono: Un smartphone. para red P2P de Fermat org

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#440]
proviene del caso #437

**Comment by ivonnesantos** [comment]
![smartphone](https://cloud.githubusercontent.com/assets/15238660/12213487/00c70fb8-b64b-11e5-83ee-f5cdd934eb33.jpg)

@arnaldos @Miguelcldn @Luis-Fernando-Molina

**Comment by arnaldos** [comment]
@ivonnesantos lo mismo que en el caso de la tablet

**Comment by ivonnesantos** [comment]
@arnaldos @Luis-Fernando-Molina 
![smartphone](https://cloud.githubusercontent.com/assets/15238660/12252971/40d10bd0-b8ae-11e5-9142-7667a47a4db7.jpg)

**Comment by Miguelcldn** [comment]
Podría ver la propuesta 1 sin el muñequito en la pantalla? Eso llega a confundir con el tipo de nodo `Actor`

**Comment by ivonnesantos** [comment]
propuesta 1 con observacion de @Miguelcldn y de @arnaldos sobre el telefono mas grande 

![smartphone_p1-obeservacion-de-miguel](https://cloud.githubusercontent.com/assets/15238660/12266027/d9bcc7d0-b912-11e5-8025-acab3e55f25c.jpg)

**Comment by Miguelcldn** [comment]
Bien, habría que ver ahora cómo queda la Tablet si se hiciera así tambien

**Comment by arnaldos** [comment]
@ivonnesantos replantea la forma del tlf plz. aunque si nos enfocamos en la tecnología los tlf y tablets tienen formas similares. creo que para hacer la diferencia seria cuestión de colocar el tlf un poco mas alargada la pantalla.y si puedes incluye el auricular en a sintesis

**Comment by ivonnesantos** [comment]
![smartphone](https://cloud.githubusercontent.com/assets/15238660/12283276/2132d5fa-b977-11e5-8183-e2cef8612d14.jpg)

@arnaldos @Luis-Fernando-Molina @Miguelcldn

**Comment by arnaldos** [comment]
@ivonnesantos la propuesta 7,pero pruebala con el aro de la 6

**Comment by ivonnesantos** [comment]
![smartphone](https://cloud.githubusercontent.com/assets/15238660/12283516/2b6c2858-b979-11e5-8cb0-5bd87049c6af.jpg)

@arnaldos

**Comment by arnaldos** [comment]
@ivonnesantos :+1: usa estilo grafico para estandarizar el resto de los iconos
