### ISSUE TITLE
Crear icono de un Dispositivo móvil: Una tabla. para red P2P de Fermat org

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#441]
proviene del caso #437

**Comment by ivonnesantos** [comment]
![tablet](https://cloud.githubusercontent.com/assets/15238660/12213781/01198940-b651-11e5-8de4-42ffcd5a2452.jpg)

@arnaldos @Miguelcldn @Luis-Fernando-Molina

**Comment by arnaldos** [comment]
hola @ivonnesantos busca darle mayor protagonismo a la tablet en si. por favor postea otras propuestas.

**Comment by ivonnesantos** [comment]
![tablet](https://cloud.githubusercontent.com/assets/15238660/12283900/320b3812-b97d-11e5-8cac-fd31e079efc7.jpg)

@arnaldos

**Comment by arnaldos** [comment]
@ivonnesantos la propuesta 3 pero busca otro elemento que nos defina que es una tablet.  no estoy seguro de la manito.

**Comment by ivonnesantos** [comment]
@arnaldos 

![tablet](https://cloud.githubusercontent.com/assets/15238660/12304243/b4bfc858-ba00-11e5-8845-5bcb4a41edcc.jpg)

**Comment by arnaldos** [comment]
colocale cuadraditos como si fuesen aplicaciones probemos con eso a ver que tal

**Comment by ivonnesantos** [comment]
![tablet](https://cloud.githubusercontent.com/assets/15238660/12313718/4658d4a4-ba3c-11e5-98fb-42bf4ec5a771.jpg)
@arnaldos

**Comment by arnaldos** [comment]
@ivonnesantos podemos mejorar usando los cuadros mas estilizados y eliminando la manito, porque así parece un launchpad para hacer dubstep. :smile_cat:

**Comment by ivonnesantos** [comment]
![tablet](https://cloud.githubusercontent.com/assets/15238660/12340574/de87ed4e-baed-11e5-97cd-379607d46791.jpg)
@arnaldos

**Comment by ivonnesantos** [comment]
![tablet](https://cloud.githubusercontent.com/assets/15238660/12342706/36c4ac2a-baff-11e5-9e38-a56b673ba9cc.jpg)
@arnaldos

**Comment by arnaldos** [comment]
version 4 :+1:
