### ISSUE TITLE
Crear icono de un Actor  para red P2P de Fermat org

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#442]
Actor (Genérico): El icono de una persona, como los muñequitos del messenger QEPD. Cuando se agreguen los tipos de Actor's a este mismo muñeco se le pondrán detalles de su rol.

proviene del caso #437

**Comment by ivonnesantos** [comment]
@Miguelcldn @arnaldos @Luis-Fernando-Molina 

![actor generico-01](https://cloud.githubusercontent.com/assets/15238660/12097881/8f54be6e-b2f0-11e5-95d9-37f8c63ad49d.jpg)

**Comment by arnaldos** [comment]
@ivonnesantos muestra otra version plz

**Comment by Miguelcldn** [comment]
Podría verlos sin las costuras?

**Comment by ivonnesantos** [comment]
@miguel @Luis-Fernando-Molina 

miguel le quite los circulos rojo porque luis me hizo una observación en otro caso con respecto a eso aca te dejo dos propuestas sin las costuras

![actor generico_2-01](https://cloud.githubusercontent.com/assets/15238660/12132949/fe6088f8-b3f2-11e5-93c7-2d51c3d96bee.jpg)

**Comment by Miguelcldn** [comment]
Sí, estoy al tanto del comentario, sin embargo al cambiar este diseño el de PC también tocará cambiar, como todas estas imágenes se mostrarán como nodos en la misma red, es necesario que tengan una armonía gráfica entre ellos. En lo personal, prefiero formas circulares para esto como en la propuesta 4, porque los nodos generalmente se representan con círculos. Para #439 diseña la pc como esa propuesta (o si tienes más circulares también)

**Comment by ivonnesantos** [comment]
estoy de acuerdo contigo @Miguelcldn por eso me gustaría definir uno para poder trabajar los demás con una base, aca dos propuestas mas con circulos.
![actor-generico_2](https://cloud.githubusercontent.com/assets/15238660/12151057/5d7dc878-b47f-11e5-8605-c051931f0726.jpg)

**Comment by arnaldos** [comment]
@ivonnesantos propuesta 5 solo una observación la cabeza del user esta muy pegada al borde del torso esto puede genera ruido, o la separas mas o haces que se unan ambos elementos para evitar que esto genere ruido .... pero de las dos ultimas propuestas .. la 5 se ve mejor

**Comment by ivonnesantos** [comment]
@arnaldos hice algo parecido a la propuesta 5 adaptándolo a los demás y aparte otra dos opciones
@Luis-Fernando-Molina 
![actor-generico_2](https://cloud.githubusercontent.com/assets/15238660/12312704/affa137c-ba33-11e5-8b22-531fad19d843.jpg)

**Comment by arnaldos** [comment]
propuesta 7 :+1:
