### ISSUE TITLE
Mejorar Icono de la Sub app Asset Issuer Community

### ISSUE THREAD

**Issue by victoralfonzohd** [bitDubai/fermat-graphic-design#444]
Viene del #443

**Comment by victoralfonzohd** [comment]
@arnaldos 

Propuesta 1:

![assetissuerwallet](https://cloud.githubusercontent.com/assets/15219855/12051100/ca5cbd32-aed0-11e5-9238-f30086c5f366.png)

Propuesta 2:

![assetissuerwallet1](https://cloud.githubusercontent.com/assets/15219855/12051064/496b1642-aed0-11e5-9e6b-7a23ab76e89d.png)

Propuesta 3:

![assetissuerwallet2](https://cloud.githubusercontent.com/assets/15219855/12051077/91668ca6-aed0-11e5-8345-0006e43b1e5b.png)

**Comment by arnaldos** [comment]
propuesta 2 :+1:
