### ISSUE TITLE
Mejorar Icono de la Sub app Asset Issuer Identity

### ISSUE THREAD

**Issue by victoralfonzohd** [bitDubai/fermat-graphic-design#445]
Viene del #443

**Comment by victoralfonzohd** [comment]
@arnaldos 

Propuesta 1:

![assetissuerwallet1](https://cloud.githubusercontent.com/assets/15219855/12050965/d49993da-aece-11e5-8ade-e1a794bc1be5.png)

Propuesta 2:

![assetissuerwallet2](https://cloud.githubusercontent.com/assets/15219855/12050970/dfac14b4-aece-11e5-8b34-5891c261421e.png)

Propuesta 3:

![assetissuerwallet3](https://cloud.githubusercontent.com/assets/15219855/12050974/e8615984-aece-11e5-8824-0429c40e1bbc.png)

Propuesta 4:

![assetissuerwallet4](https://cloud.githubusercontent.com/assets/15219855/12050978/f12e2bc8-aece-11e5-8d16-9f9b4b9e6b39.png)

**Comment by arnaldos** [comment]
@victoralfonzohd  replantealo plz !

**Comment by victoralfonzohd** [comment]
@arnaldos 

Propuesta 5:

![assetissuerwallet](https://cloud.githubusercontent.com/assets/15219855/12051915/cb34813a-aedb-11e5-88a8-27ceb59e8c16.png)

Versión sin costuras: 

![assetissuerwallet1](https://cloud.githubusercontent.com/assets/15219855/12051924/da0fbd32-aedb-11e5-9d7e-84f40f79b89b.png)

Propuesta 6:

![assetissuerwallet2](https://cloud.githubusercontent.com/assets/15219855/12051927/e258436a-aedb-11e5-9fda-c55ff0697e6b.png)

Versión sin costuras: 

![assetissuerwallet3](https://cloud.githubusercontent.com/assets/15219855/12051929/ee4e072c-aedb-11e5-88de-66a0b3935db7.png)

**Comment by arnaldos** [comment]
@victoralfonzohd prueba con una version que la mascara salga del bolsillo. pero el bolsillo que esta del lado izquierdo y la mascara del lado derecho a ver que tal y el texto que diga identity ... con lectura de abajo hacia arriba sobre el bolsillo

**Comment by victoralfonzohd** [comment]
@arnaldos 

Nueva Versión: 

Propuesta 1:

![assetissuerwallet](https://cloud.githubusercontent.com/assets/15219855/12153383/bd494104-b48b-11e5-8b37-b1d43c29dee4.png)

Propuesta 2:

![assetissuerwallet](https://cloud.githubusercontent.com/assets/15219855/12153514/65a22e42-b48c-11e5-8a4a-a0c80e6fe26d.png)

**Comment by arnaldos** [comment]
propuesta 2 trata de colocar la misma tipografía que se uso para la wallet, has que la T tenga el mismo estilo que en la wallet

**Comment by victoralfonzohd** [comment]
@arnaldos 

![assetissuerwallet](https://cloud.githubusercontent.com/assets/15219855/12174753/a591390e-b530-11e5-8259-8cbc908e96d2.png)

**Comment by arnaldos** [comment]
@victoralfonzohd :+1:  genera los archivos

**Comment by victoralfonzohd** [comment]
:+1: Listo!
