### ISSUE TITLE
Mejorar Icono para la SubApp Asset User Community 

### ISSUE THREAD

**Issue by victoralfonzohd** [bitDubai/fermat-graphic-design#447]
Viene del #446

**Comment by victoralfonzohd** [comment]
@arnaldos 

Propuesta  1:

![icon_-asset_user_wallet](https://cloud.githubusercontent.com/assets/15219855/12175828/86b7c5b0-b536-11e5-9e15-7accd9216ef2.png)

**Comment by arnaldos** [comment]
@victoralfonzohd los colores de los user no estoy seguro sean los correctos replantealos, se que estan en la wallet pero para esta version no se ajustan. dale la vuelta.

**Comment by victoralfonzohd** [comment]
@arnaldos 

Estos son los colores que estan en los elementos internos del logo de la wallet principal:

![icon_-asset_user_wallet](https://cloud.githubusercontent.com/assets/15219855/12199763/dbcc970e-b5ec-11e5-817b-860c77cd8177.png)

Otra versión:

![icon_-asset_user_wallet](https://cloud.githubusercontent.com/assets/15219855/12199810/2a3abdf8-b5ed-11e5-9e32-280e51827554.png)

**Comment by arnaldos** [comment]
@victoralfonzohd revisa el brochese ve un poco mas pequeño, colocalo del mismo tamaño de la identity

**Comment by arnaldos** [comment]
de las ultimas 2 versiones apunta por la 1ra ..... generate otras 2 partiendo de esta

**Comment by victoralfonzohd** [comment]
@arnaldos Corrección del tamaño del broche lista

Versiones: 

![1](https://cloud.githubusercontent.com/assets/15219855/12239217/d76636f6-b859-11e5-9b47-88a0125854bb.png)

![2](https://cloud.githubusercontent.com/assets/15219855/12239477/1f7d4186-b85b-11e5-9f4a-af17365ef249.png)

![3](https://cloud.githubusercontent.com/assets/15219855/12239486/258c0d82-b85b-11e5-9530-0f90646386b7.png)

**Comment by arnaldos** [comment]
@victoralfonzohd  versión 2 de las ultimas 3 :+1:

**Comment by victoralfonzohd** [comment]
@arnaldos 

Version 1:

![icon_-asset_user_wallet](https://cloud.githubusercontent.com/assets/15219855/12554717/0b66f07a-c350-11e5-9d42-032696b65b35.png)

Version 2:

![icon_-asset_user_wallet1](https://cloud.githubusercontent.com/assets/15219855/12555094/b2630ac0-c351-11e5-8058-b50c00c845bd.png)

**Comment by arnaldos** [comment]
para este ya tenemos aprobado la versión 2 ..
