### ISSUE TITLE
Mejorar Icono para la SubApp Asset User Identity 

### ISSUE THREAD

**Issue by victoralfonzohd** [bitDubai/fermat-graphic-design#448]
Viene del #446

**Comment by victoralfonzohd** [comment]
@arnaldos 

Propuesta 1:

Versión 1: 

![icon_-asset_user_wallet1](https://cloud.githubusercontent.com/assets/15219855/12052334/149f5418-aee0-11e5-9fe6-6ad421fd9dd2.png)

Versión 2: 

![icon_-asset_user_wallet](https://cloud.githubusercontent.com/assets/15219855/12052337/1ab2f7ec-aee0-11e5-852a-55a98b6ee2a3.png)

**Comment by arnaldos** [comment]
@victoralfonzohd prueba la sugerencia que nos dio luis en la reunión para este icono en el cual era sustituir los elementos que hacen de asset por la mascara. ubica el icono original y aplica los ajustes que te comento

**Comment by victoralfonzohd** [comment]
@arnaldos 

Propuesta 1:

![icon_-asset_user_wallet](https://cloud.githubusercontent.com/assets/15219855/12090910/107620ea-b2c5-11e5-8dfa-55f6677714ec.png)

Propuesta 2:

![icon_-asset_user_wallet](https://cloud.githubusercontent.com/assets/15219855/12090989/b8e659fc-b2c5-11e5-858e-61ea9227db25.png)

**Comment by victoralfonzohd** [comment]
@arnaldos 

Propuesta 3:

![icon_-asset_user_wallet](https://cloud.githubusercontent.com/assets/15219855/12144420/b35a0c8c-b459-11e5-9cc3-6c0cf0782b7c.png)

**Comment by arnaldos** [comment]
@victoralfonzohd centra el circulo del broche y amplia un ppoco su tamaño. prueba un color diferente en el borde de la mascara puede ser igual oscura pero rebajale el brillo que tiene. hace que se valla a hacia los tonos morados. (esto de los bordes es para proba como se veria con otro tono)

**Comment by victoralfonzohd** [comment]
@arnaldos Correciones

Versión 1: 

![icon_-asset_user_wallet](https://cloud.githubusercontent.com/assets/15219855/12152256/cc26b8a6-b485-11e5-8470-e987f4a1dffb.png)

Versión 2: 

![icon_-asset_user_wallet1](https://cloud.githubusercontent.com/assets/15219855/12152320/236b2818-b486-11e5-953d-2cec336a7d52.png)

**Comment by arnaldos** [comment]
@victoralfonzohd  version 1
