### ISSUE TITLE
Bocetar ideas para la imagen de Fermat CRY

### ISSUE THREAD

**Issue by m471c4** [bitDubai/fermat-graphic-design#45]
Viene del #7 

Actualmente el logo se tomó prestado de otro concepto. Se debe realizar uno nuevo. Hacerlo directamente con la nueva paleta de colores.

![fermat-cry](https://cloud.githubusercontent.com/assets/9479367/9057361/e6f7f994-3a99-11e5-875d-3deac4963b8d.png)

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina @m471c4 primer boceto Fermat CRY Crypto
Partiendo de una síntesis de una red de wallet enfocamos el elemento central con la síntesis de una cadena para dar a entender que están encriptadas entre si 
![fermat_sub_app](https://cloud.githubusercontent.com/assets/13594347/9499913/036e5bfa-4bec-11e5-9b5f-4e4c226ee5fa.jpg)

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina @m471c4 Segundo y Tercer boceto Fermat CRY Crypto aplicando las sugerencias que se dieron en la reunión

![fermat_sub_app_4](https://cloud.githubusercontent.com/assets/13594347/9527802/f39a144c-4cba-11e5-8474-9881b7d4fb2d.jpg)
![fermat_sub_app_5](https://cloud.githubusercontent.com/assets/13594347/9527803/f3a8424c-4cba-11e5-8052-23528019cde3.jpg)

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina de las tres propuestas subidas me parece que el 1ro se comportan mejor los elementos y se ve mas limpio. no se que opina @m471c4

**Comment by Luis-Fernando-Molina** [comment]
me  gusta mas la cadena circular, pero esta muy chica. Se verian mas incluso cuando se achique el logo si los eslabones son del tamaño de los que estan al medio. Las billeteras pudieran estar en el sentido de la cadena.Tambien pudieras variar y que no sea siempre la misma billetera.

**Comment by Luis-Fernando-Molina** [comment]
ahh no habia visto el primero, puede andar, pero que no sea siempre la misma billetera

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina referente a lo que comentas acerca de la mismas billeteras, te refieres a variarlas en color ? o variar su forma ?  Para la cadena voy probar aumentar el tamaño aunque yo digo que el que tiene mejor lectura, es cuando las billeteras no están unidas por las cadenas, como esta en la primera versión

**Comment by Luis-Fernando-Molina** [comment]
Variarlas en color, normalment nosotros tenemos 3, no? Quizas debamos tener 4 para los casos en que hacen falta 4 y usar siempre las mismas.

Lo de las cadenas puede ser que la dejes así como esta en el boceto 1. Probemos

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina ajustes deFermat CRY
![fermat_cry](https://cloud.githubusercontent.com/assets/13594347/9556628/21fb3772-4da0-11e5-89c1-40b914b08a70.png)

**Comment by Luis-Fernando-Molina** [comment]
1) el cierre de una esta en verde
2) la que esta en rojo no la vamos a usar. En su lugar poné la billetera de abajo (mismo color) pero hacele una adaptación para que parezca una caja fuerte (crypto vault). (osea arriba y abajo crypto vault , a los costados wallets (las dos de los costados del color de la de la derecha)

**Comment by Luis-Fernando-Molina** [comment]
3) Las sombras no están de todos los elementos.

**Comment by arnaldos** [comment]
ok voy a colocar el color original de los cierres

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina comparto los últimos ajustes de Fermat CRY
![fermat_cry](https://cloud.githubusercontent.com/assets/13594347/9584413/d5ce6bc0-4fda-11e5-82f9-cbedba04502f.png)

**Comment by Luis-Fernando-Molina** [comment]
la cajita fuete debiera reemplazar las billeteras de arriba y de abajo. @m471c4 habia hecho tambien una caja fuerte, ponganse de acuerdo para usar solo un modelo.

La billetera pudiera estar dentro de la imagen de la caja fuerte o como la hizo @m471c4 tambien esta buena.

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina  ok perfecto voy ponerme de acuerdo con @m471c4 para definir cual usamos aunque el icono de @m471c4 me parece que esta muy bueno

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina  que tal así ?
![fermat_cry-2](https://cloud.githubusercontent.com/assets/13594347/9587620/3a039d56-4fed-11e5-9bf0-ae8056b994a4.png)

**Comment by Luis-Fernando-Molina** [comment]
Puede ser, proba poner las cajas fuertes en los costados asi pueden ir un poco mas grande y se ven mejor y las billeteras arriba y abajo. Otra cosa, la sobra no esta bien calculda.

**Comment by arnaldos** [comment]
ya le hago los cambios

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina aquí los últimos ajustes solicitados
![fermat_cry-3](https://cloud.githubusercontent.com/assets/13594347/9592821/d63d7fa2-5010-11e5-9300-5b5a940e3f9a.png)

**Comment by arnaldos** [comment]
este si es el ultimo cambio 
![fermat_cry-3](https://cloud.githubusercontent.com/assets/13594347/9592904/0bfc1d8c-5012-11e5-9ef8-4292456a5862.png)

**Comment by Luis-Fernando-Molina** [comment]
Proba que tire sombra desde todos los elementos please. Cambiale el nombre por BCH y que diga Fermat Blockchains.

Respecto al icono asegurate de que las dos caja fuertes esten exactamente a la misma distancia de la cadena, y además que el vinculo que las une pase exactamente por el medio de cada una.

**Comment by arnaldos** [comment]
ya realizo los ajustes !

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina ajustes para Fermat Blockchains. (sombra en todos los elementos)
![fermat_cry-4](https://cloud.githubusercontent.com/assets/13594347/9625288/c25fdb1a-511e-11e5-9ad5-81d41713872b.png)

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina perdon me equivoque de logo este si es 
![fermat_cry-6](https://cloud.githubusercontent.com/assets/13594347/9625329/1983378e-511f-11e5-9566-8ef61c234db8.png)

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina en este solo se le arroja la sombra a la cadena y una sombra general
![fermat_cry-5](https://cloud.githubusercontent.com/assets/13594347/9625352/3e0192ea-511f-11e5-8068-4a574b7114c2.png)

**Comment by Luis-Fernando-Molina** [comment]
@arnaldos mis observaciones:

1) es BCH
2) veo que estás haciendo sobras de diferentes intensidades. Eso no lo habíamos hecho antes. Prefiero que nos quedemos con una sola intensidad standard. Asegurate que en ningún otro logo se nos haya pasado eso.

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina listo los ajustes 
![fermat_bch](https://cloud.githubusercontent.com/assets/13594347/9647149/d5a8d4a8-51a3-11e5-8587-7f1237562d10.png)

**Comment by Luis-Fernando-Molina** [comment]
:+1: listo, pasaselo a @Miguelcldn . Miguel: de paso fijate que en las fichitas de las supercapas no sale el codigo arriba a la dercha.

**Comment by arnaldos** [comment]
perfecto cierro el caso !!!
