### ISSUE TITLE
Bank Wallet Design / Home View

### ISSUE THREAD

**Issue by Neoperol** [bitDubai/fermat-graphic-design#450]
#449

Diseño de la vista principal, consta de una lista de las cuentas agregadas a la wallet y un boton para agregar cuentas nuevas. 

![untitled-1_03](https://cloud.githubusercontent.com/assets/6201081/12075862/3c7958b6-b161-11e5-9edb-8904718165aa.png)

@Luis-Fernando-Molina 
@guillermo20

**Comment by Neoperol** [comment]
Propuesta para la vista principal. 

![home](https://cloud.githubusercontent.com/assets/6201081/12075849/c4f1cd00-b160-11e5-9045-64cfc1830b52.png)

Vista sin cuentas agregadas. 

![home_empty](https://cloud.githubusercontent.com/assets/6201081/12075850/c527c63a-b160-11e5-865a-273bc864a93f.png)

@Luis-Fernando-Molina 

Hice un cambio en el action bar, reemplazando el button de opciones por un icono de "Mas" para agregar las cuentas. @guillermo20 

@nelsonalfo

**Comment by nelsonalfo** [comment]
me parece bien, pero no veo el uso del Navigation Drawer

**Comment by guillermo20** [comment]
si. aqui me parece que el navigation drawer esta de mas, de hecho en el wireframe ni siquiera esta contemplado.

seria dejarla asi como esta a excepcion del navigation drawer, que seria un backbutton regular, no?

**Comment by nelsonalfo** [comment]
sin el back button porque ese es el home

**Comment by guillermo20** [comment]
cierto... excelente!

**Comment by Neoperol** [comment]
Así, quedaría entonces. 

![home](https://cloud.githubusercontent.com/assets/6201081/12125564/1f35b736-b3be-11e5-8593-73aaae3c65e4.png)

@guillermo20 
@nelsonalfo

**Comment by nelsonalfo** [comment]
correcto :+1:
