### ISSUE TITLE
Logo para el equipo Mordor

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#451]
Mordor (la tierra de Sauron, el villano del Señor de los anillos)

Podía ser un volcán en un desierto, un dragón, el ojo de un dragón.

**Comment by darkestpriest** [comment]
![http-dribbble comshots1476445-mordor-animationlistbucketsoffset3](https://cloud.githubusercontent.com/assets/10060413/12118594/8fc436b4-b399-11e5-88a6-93f3abd3f673.gif)

@arnaldos  esta imagen puede servir como referencia

**Comment by m471c4** [comment]
@arnaldos @darkestpriest acá las primeras versiones para el logo del equipo Mordor.

Versión 1:
![mordorteam1](https://cloud.githubusercontent.com/assets/13468350/12123530/b3bef8dc-b3b3-11e5-8bcf-4d853739280a.png)

Versión 2:
![mordorteam2](https://cloud.githubusercontent.com/assets/13468350/12123531/b3c07c52-b3b3-11e5-9ba1-4fcc1dade5eb.png)

**Comment by darkestpriest** [comment]
@m471c4  ¡La versión 2 está genial! "una app para gobernarlas a todas" Voy a consultar con mi equipo a ver cual versión gana.

**Comment by darkestpriest** [comment]
@m471c4 @arnaldos mi equipo seleccionó la versión 1.

**Comment by m471c4** [comment]
@darkestpriest excelente, lo subiré al repositorio para que @jonathanborges3d pueda trabajar en la versión 3D. Les haré unas versión para wallpaper :)

**Comment by darkestpriest** [comment]
Gracias @m471c4 :+1:

**Comment by m471c4** [comment]
@darkestpriest mejoré un poco el ojo y cree una versión que pueden usar para wallpaper (lo pueden descargar directamente desde acá o cuando lo suba al repositorio)

![mordorteamfinal](https://cloud.githubusercontent.com/assets/13468350/12146964/dac29186-b468-11e5-9045-0841f69ae290.png)

![mordorteamwallpaper](https://cloud.githubusercontent.com/assets/13468350/12146969/de2b6578-b468-11e5-9588-f2277f311ef3.png)

**Comment by darkestpriest** [comment]
Genial @m471c4 ya el wallpaper lo estoy usando en mi PC.

**Comment by jonathanborges3d** [comment]
@m471c4 @Luis-Fernando-Molina @darkestpriest Les presento la primera versión en moneda:

![mordor_1a](https://cloud.githubusercontent.com/assets/13649739/12159851/30b2a2d0-b4b8-11e5-8171-33960c33c4c2.jpg)

**Comment by darkestpriest** [comment]
The best coin EVER! @jonathanborges3d Excelente trabajo.

**Comment by Luis-Fernando-Molina** [comment]
no se supperpone demasiado el material de las letras con el del fondo? y si las montañas fueran de plata?

**Comment by jonathanborges3d** [comment]
Gracias @darkestpriest 

@Luis-Fernando-Molina Segunda versión:

![mordor_2a](https://cloud.githubusercontent.com/assets/13649739/12188538/69bad27a-b588-11e5-828d-2a82c210cabf.jpg)

**Comment by m471c4** [comment]
@jonathanborges3d ¡qué bien queda! Se ve muy bien con el plateado :+1:

**Comment by darkestpriest** [comment]
Dejaré mi palabra típica, ¡BRUTAL! @jonathanborges3d la segunda versión de la moneda está mucho mejor :metal:

**Comment by Luis-Fernando-Molina** [comment]
:+1:

**Comment by Luis-Fernando-Molina** [comment]
fijate que la moneda quede enteramente sobre fondo blanco igual que las otras antes de ponerla en el READ ME DEV

**Comment by arnaldos** [comment]
@jonathanborges3d avísame si terminaste todos los renders referentes a este caso para cerrarlo

**Comment by jonathanborges3d** [comment]
@arnaldos Si, ya la versión final está lista.
