### ISSUE TITLE
Logo para el equipo Kabuto

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#452]
Se llamara Kabuto en honor al comic Mazinger Z.

proviene 
https://github.com/bitDubai/fermat/issues/3676

**Comment by franklinmarcano1970** [comment]
![image](https://cloud.githubusercontent.com/assets/8689068/12125575/2b890a10-b3be-11e5-9509-0df3069f186b.png)

@arnaldos Solo como referencia esa imagen.

**Comment by m471c4** [comment]
@franklinmarcano1970 @arnaldos primeras versiones para el equipo Kabuto.

Versión 1:
![kabutoteam3](https://cloud.githubusercontent.com/assets/13468350/12178458/bf5937ca-b543-11e5-8fc0-fe308f7404c7.png)

Versión 2:
![kabutoteam4](https://cloud.githubusercontent.com/assets/13468350/12178459/bf5afa24-b543-11e5-8982-49a5e877c357.png)

Versión 3:
![kabutoteam2](https://cloud.githubusercontent.com/assets/13468350/12178462/c80d3128-b543-11e5-8825-c47a1c616f0b.png)

Versión 4:
![kabutoteam1](https://cloud.githubusercontent.com/assets/13468350/12178461/c7e7e062-b543-11e5-9133-2f51f41bd038.png)

**Comment by franklinmarcano1970** [comment]
@arnaldos @m471c4 @josejcb @JDVilchez Escuho opiniones Jose Cardozo y Jose Vilchez, por otra parte creo que podemos colocar la figura de Bitcoin en la bolita de la cabeza, mi inclino por el 3 o 4 pero las letras no en Rojo.

**Comment by franklinmarcano1970** [comment]
@m471c4 Podria tambien hacer un arte con el casco de koji kabuto, o donde salga mazinger y koji.

**Comment by josejcb** [comment]
y si lo ponen con efecto de negativo, o escala de grises? así t olvidas de los colores.

**Comment by JDVilchez** [comment]
Me gusta el 3 pero los colores no me cuadran mucho.

**Comment by josejcb** [comment]
coincido

**Comment by m471c4** [comment]
Muy bien @franklinmarcano1970 @JDVilchez @josejcb, tomaré sus sugerencias y haré otras propuestas y las subo para que las vean. Los colores los tomé del original, pero puedo modificarlos si quieren y trataré de incluir a Koji.

**Comment by m471c4** [comment]
@arnaldos @franklinmarcano1970 @JDVilchez @josejcb acá subo otras versiones, más tarde puedo poner algunas más. Espero sugerencias y opiniones:

Versión anterior, mejorada con el símbolo del bitcoin y los colores:
![kabuto1](https://cloud.githubusercontent.com/assets/13468350/12339198/e8ca3328-bae5-11e5-9e36-fa38c42e02f7.png)

Versión2, Koji minimalista:
![kabuto2](https://cloud.githubusercontent.com/assets/13468350/12339199/e8caa600-bae5-11e5-80cf-e6acff4dab97.png)

Versión 3:
![kabuto3](https://cloud.githubusercontent.com/assets/13468350/12339197/e8c7ff22-bae5-11e5-8730-3d28143964c2.png)

**Comment by franklinmarcano1970** [comment]
@arnaldos @franklinmarcano1970 @JDVilchez @josejcb @m471c4 @Lozadaa
Escucho opiniones muchachos me voy por la opcion de kabuto minimilista.

**Comment by arnaldos** [comment]
@franklinmarcano1970 de la ultimas 3 me gusta la síntesis de la primera imagen del robot. un buen trabajo que realizo @m471c4. pero ya es cuestión del equipo kabuto quien tome la decisión. la verdad todas las sintesis están buenas, pero pero mi opinión particular la primera imagen de las ultimas tres me parece es la mejor porque tiene simetría los elementos estan perfectamente balanceados y cuando se lleve al 3D en las monedas se verán muy bien !!!!

**Comment by franklinmarcano1970** [comment]
@JDVilchez @josejcb  @Lozadaa espero sus opiniones

**Comment by josejcb** [comment]
la minimalista tmb

**Comment by franklinmarcano1970** [comment]
@arnaldos  @JDVilchez @josejcb @m471c4 @Lozadaa Arnlados hemos tomado la primera imagen de las ultimas 3, la de la imagen de Mazinger con el logo de bitcion en la bolita, procedan que puedan usarse como fondo de pantalla.

**Comment by arnaldos** [comment]
@franklinmarcano1970  perfecto !!! ya se le enviaran los archivos a @jonathanborges3d para que haga su magia en 3D

**Comment by franklinmarcano1970** [comment]
@arnaldos Dale perfecto, esperamos las imagenes en 3d y las monedas.

**Comment by jonathanborges3d** [comment]
@arnaldos @m471c4 Ok, por favor sube los editables al repo, éste logo no lo puedo hacer con el arte final en .png, necesito los objetos separados para darles el volumen adecuado. Gracias!

**Comment by m471c4** [comment]
@jonathanborges3d muy bien, los subiré al repositorio :)

**Comment by m471c4** [comment]
@franklinmarcano1970 @JDVilchez @josejcb versiones para wallpapers. Pueden descargarlas desde acá o del repositorio.

Versión fondo oscuro:
![kabuto_team_wallpaper1](https://cloud.githubusercontent.com/assets/13468350/12521199/65743032-c11b-11e5-8687-6f2ecb742b9e.png)

Versión fondo claro:
![kabuto_team_wallpaper2](https://cloud.githubusercontent.com/assets/13468350/12521200/65784dca-c11b-11e5-88ba-3d1b602c9a15.png)

**Comment by jonathanborges3d** [comment]
Primera versión 3D:

![kabuto_1](https://cloud.githubusercontent.com/assets/13649739/12689532/a7967116-c6af-11e5-972e-b524bedf3013.jpg)

**Comment by franklinmarcano1970** [comment]
Brutal..
@bitDubai/kabuto-team Su opinion.

**Comment by josejcb** [comment]
Aprobado

**Comment by Luis-Fernando-Molina** [comment]
Fijate que el fondo tiene que quedar todo blanco como el resto.

**Comment by jonathanborges3d** [comment]
Si, quedará como las otras, la edito antes de subirla, el render original no queda totalmente blanco.

**Comment by Luis-Fernando-Molina** [comment]
:+1:
