### ISSUE TITLE
Bank Wallet Design / Set up View

### ISSUE THREAD

**Issue by Neoperol** [bitDubai/fermat-graphic-design#453]
#449

![untitled-1_01](https://cloud.githubusercontent.com/assets/6201081/12094507/2d6e2aec-b2db-11e5-8a4c-d9966552e2d8.png)

Diseño de la vista de Set Up de la wallet. 

@Luis-Fernando-Molina 
@guillermo20

**Comment by Neoperol** [comment]
Propuesta para la vista Set up. En la vista solo tiene una acción y es ingresar el nombre del Banco. 

![wizard](https://cloud.githubusercontent.com/assets/6201081/12094896/897ce77c-b2dd-11e5-8cf9-c90ef57fb4b9.jpg)

@Luis-Fernando-Molina 
@guillermo20 
@nelsonalfo

**Comment by nelsonalfo** [comment]
Faltarían estos otros campos que se muestran en la imagen y el campo del tipo de cuenta, a menos que vayas a crear una pantalla por cada campo, que en lo personal no me parece

![captura de pantalla de 2016-01-05 14 35 26](https://cloud.githubusercontent.com/assets/1823627/12124825/e32aebfc-b3b9-11e5-80ad-8f8b268f573c.png)

**Comment by guillermo20** [comment]
@nelsonalfo  aqui en el setup, como estan propuestos los wireframe. El setup seria solo el nombre del banco, ya que agregar una cuenta esta en el home de la wallet con un botoncito de "+" en el title bar que es el que despliega la pantalla esa que esta arriba para agregar una cuenta.

**Comment by nelsonalfo** [comment]
tienes razon, disculpa, es que lo vi como si fuera el setting y es el wizard

**Comment by Neoperol** [comment]
@nelsonalfo 
@guillermo20 
Este paso es irreversible cierto ? no se puede cambiar el nombre del Bank Wallet.
Por eso no tenemos una vista de settings donde se pueda cambiar.

**Comment by nelsonalfo** [comment]
tengo entendido es como dices, que es irreversible
