### ISSUE TITLE
Fiat currency Peso Argentino/Fermat Moneda 3d

### ISSUE THREAD

**Issue by jonathanborges3d** [bitDubai/fermat-graphic-design#455]
@Luis-Fernando-Molina Primera versión de la moneda:

![peso_arg_1](https://cloud.githubusercontent.com/assets/13649739/12097390/ad9403e2-b2ed-11e5-9d3b-c6381fcafca9.jpg)

![peso_arg_2](https://cloud.githubusercontent.com/assets/13649739/12097554/7335478c-b2ee-11e5-94fd-a71724bd03d6.jpg)

**Comment by Luis-Fernando-Molina** [comment]
puede ser, como se sabe que es argentino? pesos hay por varios lados.

**Comment by jonathanborges3d** [comment]
Pensé que con el sol de mayo, de la bandera argentina se notaría de una vez. Algún monumento o lugar que se pueda incorporar aquí?

**Comment by Luis-Fernando-Molina** [comment]
me imagino que el obelisco es el mas conocido

**Comment by jonathanborges3d** [comment]
@Luis-Fernando-Molina Una segunda versión con una configuración de colores diferente. Estoy usando acá la silueta del monumento a la bandera, me pareció que se veía bien. Tu opinión?

![peso_arg_3](https://cloud.githubusercontent.com/assets/13649739/12189930/da3ed13e-b594-11e5-85a8-16f44c560183.jpg)

**Comment by Luis-Fernando-Molina** [comment]
ni idea cual es ese monumento, queda bien pero no es el monumento mas conocido, es mas yo no lo conozco. El fondo de la moneda se ve bien.
