### ISSUE TITLE
Favicon para fermat.org

### ISSUE THREAD

**Issue by Miguelcldn** [bitDubai/fermat-graphic-design#457]
Diseñar un favicon de Fermat para que el navegador lo asigne a la pestaña o en marcadores. Los favicon son una imagen en formato (preferiblemente) `.ico` de resolución 16x16 o 32x32, usando colores de 8 o 16 bits.

**Comment by ivonnesantos** [comment]
![favicon](https://cloud.githubusercontent.com/assets/15238660/12151813/2a7d1f24-b483-11e5-930d-82af73ef20db.jpg)

@Miguelcldn @arnaldos @Luis-Fernando-Molina

**Comment by arnaldos** [comment]
@ivonnesantos aquí realmente se debe crear o generar una imagen del logo de fermat bajo las especificaciones que nos da @Miguelcldn. creo que la confusión se da cuando el habla de diseñar. aquí te dejo una imagen para que te ayude a ver lo que se esta solicitando :smile: 

![favicon](https://cloud.githubusercontent.com/assets/13594347/12157786/7c5ba27a-b4a6-11e5-8dc8-dc82e92b22cc.png)

**Comment by arnaldos** [comment]
una ves generes el icono envíale a @Miguelcldn

**Comment by ivonnesantos** [comment]
Claro @arnaldos pero yo vi varios ejemplos y la mayoria utilizaban el logo de manera simplificada incluso la mayoria crea una forma solida a un color. Pero esta bien yo tomo la carterita y se la paso a Miguel

**Comment by arnaldos** [comment]
vale te entiendo @ivonnesantos, yo lo interprete de esta forma, pero si usaremos una version simplificada debemos mantener la carterita principal que usamos en fermat, no estoy seguro de usar una version simplificada, ya que el logo se rediseño hace poco y es una marca prácticamente nueva, por lo muchas personas aun no conocen de fermat y habría que darle impulso al logo que representa a Fermat. mas a delante creo que se puede jugar con una version mas simple del logo.

**Comment by Miguelcldn** [comment]
![logo](https://cloud.githubusercontent.com/assets/5544266/12183888/06d27060-b564-11e5-9d62-594e5f07426f.png)

Puede ser este logo? Así sin la palabra Fermat, claro, no uso burdamente esta imagen escalada, preferiría ver cómo se termina viendo la imagen exportada correctamente al tamaño que se necesita

**Comment by Miguelcldn** [comment]
Ah, ya tengo un Pull Request sobre el favicon, que @ivonnesantos tuvo problemas con el github. Ya este issue se puede cerrar entonces. Me gustaría que al ser así se informe por aquí puesto que de esa manera puedo mantener cada tema en su hilo, ya añado el favicon :+1:
