### ISSUE TITLE
Identities Icons 

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#458]
Este caso es para debatir sobre el estilo de iconos de las identities.

Viendo lo que se está trabajando sobre la sugerencia de colocar las máscaras de anonimous en todas las identities, al verlas todas juntas no aprecio que sea la mejor forma de representarlas. Creo que debemos darle un enfoque distinto para representar las identities, que permita darle mayor armonía.

Dejo una imagen comparativa de los iconos de las mascaras de anonimus y la sugerencia a seguir:

![logos iconos](https://cloud.githubusercontent.com/assets/13594347/12131694/31293192-b3e7-11e5-8be0-6f4375d497cf.jpg)

**Comment by Luis-Fernando-Molina** [comment]
Yo no lo veo mal,  ajenos no peor que lo que había antes. Si pondría la Asmara más chica y en el caso de assets adentro del bolsillo. Usemosla hasta que se mejore la idea en algún momento.

**Comment by arnaldos** [comment]
vale perfecto !!!
