### ISSUE TITLE
Bocetar ideas para los personajes del primer video infográfico de Fermat

### ISSUE THREAD

**Issue by jonathanborges3d** [bitDubai/fermat-graphic-design#460]
Viene del #432 

Se necesita crear varios personajes para ser utilizados en el video infográfico de Fermat, Podrá continuarse el trabajo realizado por @arnaldos en las imágenes de perfil de la bitcoin wallet o empezar algo nuevo.

Voy a dejar por acá la vista actual de los personajes actuales:

![](https://raw.githubusercontent.com/bitDubai/fermat-graphic-design/master/2D%20Design/apps_resources/bitcoin_wallet/profile_image_bitcoin_wallet/male/png/profile_image.png?token=ANBHSyNr3jJN8NIlxLk4x67hBiw1reRqks5Wlw7EwA%3D%3D)

![](https://raw.githubusercontent.com/bitDubai/fermat-graphic-design/master/2D%20Design/apps_resources/bitcoin_wallet/profile_image_bitcoin_wallet/female/png/profile_image.png?token=ANBHS4FjGXe4mrUmt6X36orbdd9WFuCFks5Wlw8HwA%3D%3D)

Tomar en cuenta:
- Deben ser de cuerpo entero
- Deben poder animarse tanto en motricidad gruesa como fina y expresiones faciales
- Generar dos o tres versiones de una misma plantilla, cambiado color de ojos, cabello, ropa etc.
- Procurar generar vistas frontal y de medio perfil para cada personaje

@AnaPietrosanti @sharikarvelo

**Comment by AnaPietrosanti** [comment]
@Luis-Fernando-Molina @jonathanborges3d @sharikarvelo 
Aquí unas propuestas de personajes, el estilo es más plano que los personajes realizados para el perfil de bitcoin wallet, con la finalidad de hacer los elementos estilo el video de referencia bitcoin.
¿Qué dicen ustedes?
![boy1](https://cloud.githubusercontent.com/assets/16405172/12192486/28131822-b5b1-11e5-8d18-d0beb8acc846.png)
![man1](https://cloud.githubusercontent.com/assets/16405172/12192487/2816a370-b5b1-11e5-854c-e8d4748ec2b6.png)
![man2](https://cloud.githubusercontent.com/assets/16405172/12192488/28193c02-b5b1-11e5-8a72-1f267b470911.png)
![women1](https://cloud.githubusercontent.com/assets/16405172/12192489/281c67b0-b5b1-11e5-83e0-de21b386f40e.png)
![women2](https://cloud.githubusercontent.com/assets/16405172/12192490/281feade-b5b1-11e5-896e-ee0870df8f9c.png)

**Comment by Luis-Fernando-Molina** [comment]
Que opine @arnaldos .

La idea es que sigan la linea de los 2 que ya hay (y terminarlos de cuerpo entero a los dos que ya hay). Los colores de fondos son propios de la bitcoin wallet, no tenemos que seguir con estos turquesas, trabajemos por ahora con blanco de fondo please.

**Comment by jonathanborges3d** [comment]
Ok, entonces en ese caso necesitarán los editables: 

https://github.com/bitDubai/fermat-graphic-design/tree/master/2D%20Design/apps_resources/bitcoin_wallet/profile_image_bitcoin_wallet

@AnaPietrosanti puede encargarse del chico y @sharikarvelo de la chica.

**Comment by sharikarvelo** [comment]
![personaje femenino-02](https://cloud.githubusercontent.com/assets/16376747/12225786/0e6529bc-b7e4-11e5-89ee-f724ecf7dde5.jpg)
![personaje femenino-03](https://cloud.githubusercontent.com/assets/16376747/12225787/0e6bb4b2-b7e4-11e5-8c6e-f0bea9b73bd5.jpg)
Con respecto al personaje femenino esto es lo que he ido trabajando, las expresiones de rostro y dos modelos de cuerpo para darle un poco mas de dinamismo.@AnaPietrosanti @Luis-Fernando-Molina @jonathanborges3d

**Comment by AnaPietrosanti** [comment]
Opciones de vestuario complementario y calzado personaje del chico.
![man 1b](https://cloud.githubusercontent.com/assets/16405172/12228571/9f4207ea-b80f-11e5-8c9b-a6e8b8da8061.png)

![man 2b](https://cloud.githubusercontent.com/assets/16405172/12228573/9f4b2ce4-b80f-11e5-8f35-214e62d15b8a.png)

![man 2a](https://cloud.githubusercontent.com/assets/16405172/12228612/45112a34-b810-11e5-9d88-584db8971c32.png)

**Comment by Luis-Fernando-Molina** [comment]
muy bien todo esto!. 

Arranquemos por favor con el script para descomponerlo en escenas y ver como seguimos. Me gustaria que esa parte se avance en paralelo asi tomamos velocidad.

Adicional a los personajes vamos a necesitar tambien otro tipo de elementos gráficos, ya hay un inventario de eso?

NOTA: Es script cambió, por favor revisarlo.

**Comment by TatianaMoroz** [comment]
Guys, all the women's characters are hyper sexualized.  The bra showing?  The skirts are WAY too short, and it's a bit over the top.  This is supposed to appeal to everyone, so in the interest of that, I would tone it down and also make the men a bit more exciting.  This may be OK in South America, but this could offend a lot of people in other regions like the US  :/  During my time in the Bitcoin space, this type of thing has caused massive backlash and turns women off.  Women are in charge of most finances in the home, and we want to inclusive.  You can make a woman look beautiful without going over the top with the sexuality.  It should be more equal.

**Comment by sharikarvelo** [comment]
![personaje femenino v-06](https://cloud.githubusercontent.com/assets/16376747/12313359/f8e0fe3e-ba38-11e5-920d-1e1904a03bca.jpg)
![Uploading PERSONAJE FEMENINO V-08.jpg…]()
![personaje femenino v-09](https://cloud.githubusercontent.com/assets/16376747/12313360/f8e25ba8-ba38-11e5-9d9d-ec263c57203a.jpg)
Hola!! les coloco las nuevas propuestas del personaje femenino, hay 4 cuerpos y 3 estilos totalmente diferentes! @AnaPietrosanti @Luis-Fernando-Molina @jonathanborges3d
Saludos

**Comment by TatianaMoroz** [comment]
This looks much better in my opinion, though the outfits on the left are just too boring, the other 3 are great.  The skirts can be a tiny bit shorter too. We don't want them to look like dorks :) I think I understood the questions you wrote in Spanish correct?  They are very pretty cartoons but now will make women feel like they identify with them. Thanks and have a good night! Feel free to message whenever if you want any feedback.

**Comment by victoralfonzohd** [comment]
@jonathanborges3d  @AnaPietrosanti 

Propuesta de estilo para personajes:

![sin-titulo-1](https://cloud.githubusercontent.com/assets/15219855/12680814/eef11552-c67d-11e5-95b7-fedfb313aa24.png)

**Comment by TatianaMoroz** [comment]
Hey there :)  Like the colors and the funny shirt, but I am not crazy about his nose or facial hair.  His eyes look a little evil too hehe.  Thanks!TatianaTatiana MorozFounder & CEO (917) 832-2014Tatiana@CryptoMediaHub.comwww.CryptoMediaHub.com@CryptoMediaHubwww.TatianaMoroz.com@QueenTatiana

-------- Original Message --------
Subject: Re:_[fermat-graphic-design]_Bocetar_ideas_para_los
_personajes_del_primer_video_infográfico_de_Fermat _(#460)

**Comment by victoralfonzohd** [comment]
Cambios:

![personaje-ref](https://cloud.githubusercontent.com/assets/15219855/12683947/99bd2f60-c68e-11e5-82d1-46fb503b6a03.png)

**Comment by TatianaMoroz** [comment]
Yes, much better!  The eyes are still, I dunno, they just don't make me comfortable. Does he need to wear glasses?  Also, maybe no collar on the shirt?  Does he have to have facial hair?  Love the fast turnaround time, and we are close!  Thank you ;)TatianaTatiana MorozFounder & CEO (917) 832-2014Tatiana@CryptoMediaHub.comwww.CryptoMediaHub.com@CryptoMediaHubwww.TatianaMoroz.com@QueenTatiana

-------- Original Message --------
Subject: Re:_[fermat-graphic-design]_Bocetar_ideas_para_los
_personajes_del_primer_video_infográfico_de_Fermat _(#460)

**Comment by victoralfonzohd** [comment]
Does he need to wear glasses? Yes, it is one of the characteristics of the character

![personaje-ref2](https://cloud.githubusercontent.com/assets/15219855/12684685/70be88f8-c692-11e5-9802-3a4b9e2a45f7.png)

**Comment by TatianaMoroz** [comment]
OK cool, he looks handsome clean shaven, but up to you :)  The goatee was ok, perhaps I am letting myself be swayed because I am not crazy for facial hair hehe.  The glasses are ok, thanks for showing me the alt version as well!Tatiana MorozFounder & CEO (917) 832-2014Tatiana@CryptoMediaHub.comwww.CryptoMediaHub.com@CryptoMediaHubwww.TatianaMoroz.com@QueenTatiana

-------- Original Message --------
Subject: Re:_[fermat-graphic-design]_Bocetar_ideas_para_los
_personajes_del_primer_video_infográfico_de_Fermat _(#460)

**Comment by victoralfonzohd** [comment]
haha, okay .. for nothing! I will continue with the rest of the characters :)

**Comment by TatianaMoroz** [comment]
Thank you :)  Get some blonde ladies too, I feel left out hehe Tatiana MorozFounder & CEO (917) 832-2014Tatiana@CryptoMediaHub.comwww.CryptoMediaHub.com@CryptoMediaHubwww.TatianaMoroz.com@QueenTatiana

-------- Original Message --------
Subject: Re:_[fermat-graphic-design]_Bocetar_ideas_para_los
_personajes_del_primer_video_infográfico_de_Fermat _(#460)

**Comment by victoralfonzohd** [comment]
Diseñador:

![personaje-ref4](https://cloud.githubusercontent.com/assets/15219855/12688061/dbc063f2-c6a5-11e5-8fe3-7b314ca37ee8.png)

**Comment by victoralfonzohd** [comment]
Artista:

![personaje-ref3](https://cloud.githubusercontent.com/assets/15219855/12687936/1b6a0a2c-c6a5-11e5-972e-2db1d6bc7ae7.png)

**Comment by TatianaMoroz** [comment]
Cute :)Tatiana MorozFounder & CEO (917) 832-2014Tatiana@CryptoMediaHub.comwww.CryptoMediaHub.com@CryptoMediaHubwww.TatianaMoroz.com@QueenTatiana

-------- Original Message --------
Subject: Re:_[fermat-graphic-design]_Bocetar_ideas_para_los
_personajes_del_primer_video_infográfico_de_Fermat _(#460)

**Comment by TatianaMoroz** [comment]
Can you make an (extremely beautiful of course) blonde guitar playing girl?  Is that a character?  :)Tatiana MorozFounder & CEO (917) 832-2014Tatiana@CryptoMediaHub.comwww.CryptoMediaHub.com@CryptoMediaHubwww.TatianaMoroz.com@QueenTatiana

-------- Original Message --------
Subject: Re:_[fermat-graphic-design]_Bocetar_ideas_para_los
_personajes_del_primer_video_infográfico_de_Fermat _(#460)

**Comment by victoralfonzohd** [comment]
haha ok .. Sure, give me a moment :)

Academico:

![personaje-ref](https://cloud.githubusercontent.com/assets/15219855/12688916/9109a93a-c6ab-11e5-86a2-d1ec5e207644.png)

**Comment by TatianaMoroz** [comment]
He looks very smart :)

**Comment by victoralfonzohd** [comment]
I hope you like it :)

![sin-titulo-1](https://cloud.githubusercontent.com/assets/15219855/12690150/b7312dec-c6b3-11e5-832f-b48c4e0cf53c.png)

**Comment by TatianaMoroz** [comment]
Can you make it more feminine, an acoustic guitar and a peace sign instead?  :)Tatiana MorozFounder & CEO (917) 832-2014Tatiana@CryptoMediaHub.comwww.CryptoMediaHub.com@CryptoMediaHubwww.TatianaMoroz.com@QueenTatiana

-------- Original Message --------
Subject: Re:_[fermat-graphic-design]_Bocetar_ideas_para_los
_personajes_del_primer_video_infográfico_de_Fermat _(#460)

**Comment by victoralfonzohd** [comment]
![guitarrista](https://cloud.githubusercontent.com/assets/15219855/12690899/06c2b3c6-c6b9-11e5-9c67-17b6520f5505.png)

**Comment by TatianaMoroz** [comment]
Much better, I like that you gave her bigger boobs lol.Tatiana MorozFounder & CEO (917) 832-2014Tatiana@CryptoMediaHub.comwww.CryptoMediaHub.com@CryptoMediaHubwww.TatianaMoroz.com@QueenTatiana

-------- Original Message --------
Subject: Re:_[fermat-graphic-design]_Bocetar_ideas_para_los
_personajes_del_primer_video_infográfico_de_Fermat _(#460)

**Comment by jonathanborges3d** [comment]
@Luis-Fernando-Molina Por favor danos tu opinión de los personajes que ha hecho @victoralfonzohd

**Comment by Luis-Fernando-Molina** [comment]
Por mi estan bien :+1:

**Comment by victoralfonzohd** [comment]
Ajustes finales:

![personajes-ajustes](https://cloud.githubusercontent.com/assets/15219855/12718432/c5bbb72e-c8c0-11e5-9031-4786869ae7f5.jpg)

**Comment by AnaPietrosanti** [comment]
Nice! :) @victoralfonzohd

**Comment by jonathanborges3d** [comment]
:+1:
