### ISSUE TITLE
View send request bitcoin wallet

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#461]

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina 

![icon_request_send_1](https://cloud.githubusercontent.com/assets/13594347/12187379/9f39045e-b57d-11e5-88d7-03e2b38b3a28.jpg)

![icon_request_send_2](https://cloud.githubusercontent.com/assets/13594347/12187380/9f3d9852-b57d-11e5-8aec-975eeb7f6e1e.jpg)

**Comment by Luis-Fernando-Molina** [comment]
tenes que ver como queda con multiples records padre y algunos records hijo. La foto no se debe repetir en los hijos
