### ISSUE TITLE
View recived request bitcoin wallet

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#462]

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina recived request 

![icon_request_recived](https://cloud.githubusercontent.com/assets/13594347/12187410/e9b0c3e6-b57d-11e5-934a-968ccb5b264b.jpg)
![icon_request_recived_history](https://cloud.githubusercontent.com/assets/13594347/12187411/e9b62d54-b57d-11e5-97f0-04fcc1f1c0d6.jpg)

**Comment by Luis-Fernando-Molina** [comment]
se ve bien
