### ISSUE TITLE
DAP User Wallet / View Home

### ISSUE THREAD

**Issue by Neoperol** [bitDubai/fermat-graphic-design#466]
#465

@acostarodrigo 

![view_home](https://cloud.githubusercontent.com/assets/6201081/12199680/2a89d786-b5ec-11e5-869a-b33b8a1cb68d.jpg)

Propuesta vista home de la User Wallet.

**Comment by acostarodrigo** [comment]
gracias.
cc @javafrank @nindriago

**Comment by nindriago** [comment]
El fondo que se ve aca, degradado de esa manera azul, sera igual que en la issuer wallet una imagen ? ya se encuentra disponible? @Neoperol

**Comment by Neoperol** [comment]
No, es otra imagen.  @nindriago 
En el drive hay una carpeta que se llama DAP/User Wallet/view_home/resources
Y dentro de la carpeta User Wallet esta otro archivo de colores, con las especificaciones de la vista, aunque estamos manteniendo la diagramación y la mayoria de los valores que se usaron en la Asset Issuer

**Comment by Neoperol** [comment]
![view_home](https://cloud.githubusercontent.com/assets/6201081/12212589/94a39c0e-b63e-11e5-939e-440d09a7b5ce.jpg)

La imagen de fondo y el color del action bar se cambiaron. 

@acostarodrigo 
@nindriago

**Comment by nindriago** [comment]
cuando este disponible en el Drive nos avisas :)

**Comment by ricardo460** [comment]
hola @Neoperol me podrías facilitar una versión con estas dimensiones 540(w) x 960(h).

**Comment by Neoperol** [comment]
@ricardo460 
Que necesitas? un Screenshot de esta pantalla con este tamaño?

**Comment by ricardo460** [comment]
si, para añadirla a fermat-org.
