### ISSUE TITLE
DAP User Wallet / View Redeem Point List

### ISSUE THREAD

**Issue by Neoperol** [bitDubai/fermat-graphic-design#468]
#465

Diseño de la vista de redeem points, esta lista se abre al presionar el boton de redeem en el Asset, por consiguiente hay una lista por cada Asset. 

@acostarodrigo 

Hay evaluar los datos que se pueden mostrar de cada Redeem Point, en este caso estoy usando Una foto, dirección y teléfono. No se si hay otros datos que tengas contemplado usar, como la distancia desde el usuario al Redeem Point. 

![view_redeem_points-list](https://cloud.githubusercontent.com/assets/6201081/12217614/5249a2fa-b6d8-11e5-97f9-f7599f6cb6e0.jpg)

**Comment by nindriago** [comment]
Esta excelente esta vista Gregory, los datos que se manejan para el Redeem Point serian estos:

"location_latitude";
"location_longitude";
"contact_information";
"address_country_name";
"address_province_name";
"address_city_name";
"address_postal_code";
"address_street_name";
"address_house_number";
"hours_of_operation";

Hay datos que no estan considerados como obligatorios pero puede estudiarse...

luego puede manejarse que haciendo TAP en la direccion te Ejecute la App de Mapas del Equipo Movil y te la pueda mostrar para comodidad del Usuario para asi poderse dirigir al sitio.

y arriba en el actionBar se podrian manejar algunos filtros de locacion u otros posibles.

Si ves algun otro campo que pasara por alto, informanos por favor.

@Neoperol  @acostarodrigo  @bitDubai/skynet-team

**Comment by acostarodrigo** [comment]
@Neoperol Ponete si podes un link a google maps o un botoncito para poder ver la direccion del redeemer en un mapa.

luego lo implementaremos.

**Comment by Neoperol** [comment]
![view_redeem_points_small_list](https://cloud.githubusercontent.com/assets/6201081/12252261/dc788a74-b8a7-11e5-99da-e5c7b4b54e58.jpg)

@acostarodrigo 
@nindriago 

Vista de la lista de los redeem points. En la lista solo se muestra el nombre y la dirección. 
El boton derecho tiene dos estados y es para poder seleccionar mas de un redeem point, para proceder a realizar el redeem se debe presionar el boton "Redeem" que esta en el action bar. El boton Back del Action bar te regresa a la vista anterior y omite las selecciones.
