### ISSUE TITLE
Mejorar Icono para la Sub App Redeem Point Identity 

### ISSUE THREAD

**Issue by victoralfonzohd** [bitDubai/fermat-graphic-design#471]
Partiendo del siguiente logo 

![redeempoint](https://cloud.githubusercontent.com/assets/15219855/12243603/a7bf56a4-b871-11e5-97b4-b21275f1a1bf.png)

**Comment by victoralfonzohd** [comment]
@arnaldos 

Propuesta 1: 

![1](https://cloud.githubusercontent.com/assets/15219855/12243648/e2e87cec-b871-11e5-8240-58ea9aa41a94.png)

Propuesta 2:

![2](https://cloud.githubusercontent.com/assets/15219855/12243658/ebaabb38-b871-11e5-8302-f11a4aadf05c.png)

Propuesta 3:

![3](https://cloud.githubusercontent.com/assets/15219855/12243660/f16958ae-b871-11e5-9838-5097c37aa508.png)

Propuesta 4:

![4](https://cloud.githubusercontent.com/assets/15219855/12243671/fe989f08-b871-11e5-9f7b-163f8c901d07.png)

Propuesta 5:

![reddempoint_identity_community](https://cloud.githubusercontent.com/assets/15219855/12244093/15520264-b874-11e5-8b5e-ed8b78eafcd3.png)

**Comment by arnaldos** [comment]
@victoralfonzohd propuesta 1 pero genera una propuesta sin el glow que esta por detras de la mascara. y así comparamos

**Comment by victoralfonzohd** [comment]
@arnaldos 

Comparación del glow 

![reddempoint_identity_community](https://cloud.githubusercontent.com/assets/15219855/12267626/41707b12-b91b-11e5-849c-1e1bbb0cec05.png)

**Comment by arnaldos** [comment]
@victoralfonzohd con el glow

**Comment by arnaldos** [comment]
:+1:
