### ISSUE TITLE
Mejorar Icono para la Sub App Redeem Point Community

### ISSUE THREAD

**Issue by victoralfonzohd** [bitDubai/fermat-graphic-design#472]
Partiendo del siguiente logo:

![redeempoint](https://cloud.githubusercontent.com/assets/15219855/12243626/c567f8b4-b871-11e5-90f3-aff691448137.png)

**Comment by victoralfonzohd** [comment]
@arnaldos 

Propuesta 1:

![1](https://cloud.githubusercontent.com/assets/15219855/12245327/18fc8438-b87a-11e5-8c9f-50dc492b5638.png)

Propuesta 2:

![2](https://cloud.githubusercontent.com/assets/15219855/12245331/1eaf6abc-b87a-11e5-9f42-bbb4ef65de67.png)

Propuesta 3:

![3](https://cloud.githubusercontent.com/assets/15219855/12245338/243e6adc-b87a-11e5-8b2f-5349e5cb1d43.png)

Propuesta 4:

![4](https://cloud.githubusercontent.com/assets/15219855/12245341/2d38475c-b87a-11e5-9ebe-bd8c2d7a7a5a.png)

Propuesta 5:

![5](https://cloud.githubusercontent.com/assets/15219855/12245418/8b4b8dcc-b87a-11e5-86d3-6f91d8a224c6.png)

**Comment by arnaldos** [comment]
@victoralfonzohd propuesta 1

**Comment by arnaldos** [comment]
:+1:

**Comment by victoralfonzohd** [comment]
@arnaldos 

Comparación del glow

![reddempoint_identity_community1](https://cloud.githubusercontent.com/assets/15219855/12267658/62816e38-b91b-11e5-8338-21e66f2e608a.png)

**Comment by arnaldos** [comment]
@victoralfonzohd fijate que en la identity la mascara es blanca con borde vinotinto. trabaja el user del centro bajo este mismo concepto. para probar como se ve.   y versión con el glow

**Comment by victoralfonzohd** [comment]
@arnaldos 

![reddempoint_identity_community](https://cloud.githubusercontent.com/assets/15219855/12268047/49559450-b91d-11e5-8559-c2eb63d45085.png)

**Comment by arnaldos** [comment]
@victoralfonzohd version 2 :+1:
