### ISSUE TITLE
DAP Redeem Point / View Asset Detail

### ISSUE THREAD

**Issue by Neoperol** [bitDubai/fermat-graphic-design#474]
#473

Diseño de la vista de detalle del Asset. 
Además de la información del Asset se muestra una lista de los usuarios que han hecho redeem y la fecha en que se efectuo. Ordenados por el mas reciente. 

![view_asset_detail](https://cloud.githubusercontent.com/assets/6201081/12272505/01ba2276-b933-11e5-9c37-96b5cd3f21c3.jpg)

@acostarodrigo 
@nindriago

**Comment by nindriago** [comment]
@bitDubai/skynet-team

**Comment by nindriago** [comment]
@Neoperol pregunta, esa cinta donde sale el titulo Redeemed User List que se ve con un tono mas oscuro de color, es un componente añadido adicionalmente correcto? y que tono de color es ese ???
