### ISSUE TITLE
DAP Redeem Point

### ISSUE THREAD

**Issue by Neoperol** [bitDubai/fermat-graphic-design#475]
#473

Diseño de la vista del Home. 

![view_home](https://cloud.githubusercontent.com/assets/6201081/12272809/5e8cb8dc-b934-11e5-8ab8-3d8ea638de5f.jpg)

Recursos en la carpeta view_home/resources 

@acostarodrigo 
@nindriago

**Comment by ricardo460** [comment]
hola @Neoperol me podrías facilitar una versión con estas dimensiones 540(w) x 960(h).

**Comment by ivonnesantos** [comment]
Dos maquetas para propuestas del home de la redeem point 
![maqueta_01-01](https://cloud.githubusercontent.com/assets/15238660/13230451/9be37f00-d977-11e5-9927-6781b4a54d50.jpg)
@yojoaquin @acostarodrigo
