### ISSUE TITLE
DAP User Wallet / View Asset Redeem

### ISSUE THREAD

**Issue by Neoperol** [bitDubai/fermat-graphic-design#476]
#465

Diseño de la vista de detalle del Asset Redeem, esta vista se abre al presionar el boton Redeem en la vista de detalle. Y para poder hacer Redeem hay que seleccionar el Redeem Point o los Redeem Points. 

Los recursos están en la carpeta view_asset_redeem/resources
Y los colores en el texto de colores. 

![view_asset_redeem](https://cloud.githubusercontent.com/assets/6201081/12273017/b8b733b8-b935-11e5-9ea5-c7a1bc7e94be.jpg)

@acostarodrigo

**Comment by javafrank** [comment]
@Neoperol en lugar de "Deliver to" deberia decir "Redeem to", y en lugar de "Select the redeem point" deberia decir "Select redeem points".

Saludos,
