### ISSUE TITLE
Intra User Community App Design / View Home

### ISSUE THREAD

**Issue by Neoperol** [bitDubai/fermat-graphic-design#477]
@furszy 
@josemanueldsds 

![view_home_dialog](https://cloud.githubusercontent.com/assets/6201081/12281620/f8968022-b969-11e5-9fff-7ea19f601d25.jpg)

Colores del Gradiente de fondo.
Background 
 #0072bb
 #0a629b
Text: Font 16 SP regular  #FFFFFF

El dialog se abre si no hay conexion. 
Y si no hay datos que mostrar se muestra la vista vacia. 

![view_home_empty_connection](https://cloud.githubusercontent.com/assets/6201081/12281724/ba36a3d8-b96a-11e5-83d7-6fb8548f1f2e.jpg)

Text"Line1": Font 16 SP regular #FFFFFF
Text"Line2": Font 16 SP light #FFFFFF

Recursos en la carpeta view_home/resources

**Comment by furszy** [comment]
@Luis-Fernando-Molina

**Comment by Luis-Fernando-Molina** [comment]
el icono de la fermat framework debiera ser el mismo que se use en el panel de android.

El mensaje no esta correcto. Depende ademas de cual sea la situacion:

1) La Fermat Network esta deshabilitada: "The access to the Fermat Network is disabled." "Cancel  |  Enable"

Cancel quita el pop up, Enable te lleva al setting en el panel para que lo hagas desde ahi.

2)  La fermat Network esta habilitada pero no hay conexion. "You are not connected to the Fermat Network" "Cancel | Connect"

Cancel te quita el pop up, Connect te lleva al panel, desde el cual tocando en el icono intentaria conectarse.

**Comment by Neoperol** [comment]
@josemanueldsds 
Vistas vacias
![view_home_empty_connection_fermat](https://cloud.githubusercontent.com/assets/6201081/12344829/d04b3058-bb13-11e5-9fd4-42e48e8132fd.jpg)
![view_home_empty_connection](https://cloud.githubusercontent.com/assets/6201081/12344830/d062ac06-bb13-11e5-9d30-146f399ae759.jpg)

**Comment by Neoperol** [comment]
@josemanueldsds 

Dialogs

Los recursos estan en la carpeta, view_home/resources

![view_home_dialog](https://cloud.githubusercontent.com/assets/6201081/12344893/931fe128-bb14-11e5-9584-77ef220070fc.jpg)

![view_home_dialog_connection](https://cloud.githubusercontent.com/assets/6201081/12344894/9387b280-bb14-11e5-8b3e-5ad6a72eb0d6.jpg)
