### ISSUE TITLE
Fermat Desktop Launcher

### ISSUE THREAD

**Issue by Neoperol** [bitDubai/fermat-graphic-design#479]
Diseño del Status Bar de Fermat. 
La barra de status de abre desde el boton de "Settings"
Y al presionar los iconos de la respectiva red se obliga al sistema a conectarse a dicha red. Deben mostrarse ambos iconos con sus respectivos estados de Conectado y Desconectado. 

![fermat-app-launcher_settings_close](https://cloud.githubusercontent.com/assets/6201081/12284108/417ab5a0-b97f-11e5-9821-5640ddd6ca50.jpg)

![fermat-app-launcher_settings](https://cloud.githubusercontent.com/assets/6201081/12284163/b46efd46-b97f-11e5-8fa7-7e8c37134c90.jpg)

@arnaldos 
@Luis-Fernando-Molina

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina  aquí las versiones de iconos Desktop Launcher

Versión 1 
![settings app-08](https://cloud.githubusercontent.com/assets/13594347/12284940/014fe114-b987-11e5-8518-22cbdba7fd00.jpg)

Versión 2

![settings app-07](https://cloud.githubusercontent.com/assets/13594347/12285001/b814d42c-b987-11e5-88f2-1eef7f81f61a.jpg)

Versión 3

![settings app-05](https://cloud.githubusercontent.com/assets/13594347/12285004/c5a2646a-b987-11e5-84e6-fcde7fd8fd73.jpg)

**Comment by Luis-Fernando-Molina** [comment]
Ok vamos con la version 2, pero las palabras tienen que estar en 2 renglones y entrar 4 iconos por linea. Por ahora solo tenemos esos dos, pero ya van a venir mas cosas. Está bien que haya uno de settings ahi, nos va a servir.

**Comment by Luis-Fernando-Molina** [comment]
El icono de setting puede mejorarse. Fijate quizas usando los colores fermats para representar que son los setting de todo fermat.

**Comment by arnaldos** [comment]
vale perfecto !!!

**Comment by furszy** [comment]
@arnaldos
 Hacete por favor un wireframe con los 4 iconos por fila y el documento con el tamaño de los iconos, color de los textos, background, grado de transparencia así lo implementamos.
Gracias.

**Comment by arnaldos** [comment]
vale @furszy ya creo el wireframe y el doc

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina comparto los ajustes 

Versión 1
Activo

## ![settings app-13](https://cloud.githubusercontent.com/assets/13594347/12306561/9ab78b74-ba0c-11e5-9140-efc25efe14be.jpg)

Inactivo

## ![settings app-14](https://cloud.githubusercontent.com/assets/13594347/12306562/9ab89d98-ba0c-11e5-8962-4fc938b34b91.jpg)

Solo el boton de setings
![settings app-15](https://cloud.githubusercontent.com/assets/13594347/12306563/9ac0e976-ba0c-11e5-8ac8-e041860c7fe8.jpg)

Versión 2
Activo

## ![settings app-16](https://cloud.githubusercontent.com/assets/13594347/12306564/9ac4e90e-ba0c-11e5-9c74-223e7b5d7fce.jpg)

Inactivo
![settings app-17](https://cloud.githubusercontent.com/assets/13594347/12306560/9ab33f56-ba0c-11e5-906a-9e42402eab45.jpg)

**Comment by Luis-Fernando-Molina** [comment]
1.la altura del panel estaba bien al principio, ahora corta la palabra WALLETS que esta abajo.
2.Habia pedido que las palabras esten en dos renglones "Fermat" en 1 y "Network" en el 2do.
3.El fondo blanco semi transparente estaba bien.
4.El boton de settings cuando no esta desplegado no encaja con lo que hay. Vamos a usar medio boton, a la iz. La otra mitad se debe perder fuera de la pantalla. Debe ser del color de WALLETS con el mismo estilo y sobra. El tamaño lo podemos probar, igual que la alineacion vertical.
5.@furzy en el panel vamos a poner solo lo que nos va haciendo falta. El boton de settings por ahora no porque no tenemos definido ningun setting global que yo sepa, cuando lo tenemos lo agregamos. Tenes que hacer que los iconos se distribuyan equitativamente en el espacio horizontal si son menos de 4, si son 4 ocupan todo el espacio y si son mas se tienen que poder mover con el dedo para los costados. Desde el punto de vista funcional, tocando sobre uno deberia encendero o apagarlo. Mas adelante manteniendolo apretado abriria un fragmento donde se pudiera ver mas detalles, por ahora no estamos en eso.
6.Deberia haber un iconon para representar que la Fermat Network esta conectada, y que la bitcoin Network esta conectada, otro para indicar que estan "encendidos" y otro "apagados". Estar encendidos significa que el usuario desea que se conecte, estar apagado significa que el usuario no desea que se conecte. Si esta encendido puede estar conectada o no dependiendo del servicio de bajo nivel que reprsente esas redes, en el caso del Fermat, el cloud client ahora mismo, en el caso de bitocin la "bitcoin crypto network plugin" deberia decirte si esta o no conectada y disparar eventos cuando cambie de estado.

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina @furszy  los ajustes solicitados mas 3 versiones del boton settings 

Boton settings versión 1
![settings-app20](https://cloud.githubusercontent.com/assets/13594347/12331602/69ed6c74-babc-11e5-994a-b739bb3a7c77.jpg)

Boton settings versión 2
![settings-app21](https://cloud.githubusercontent.com/assets/13594347/12331603/6a160d14-babc-11e5-91ac-1c3fcfb1cbce.jpg)

Boton settings versión 3
los botones de del network activos 

## ![settings-app22](https://cloud.githubusercontent.com/assets/13594347/12331599/69c246ca-babc-11e5-8f76-0f45b83cf880.jpg)

los botones de del network Inactivos 

## ![settings-app23](https://cloud.githubusercontent.com/assets/13594347/12331600/69d025d8-babc-11e5-9448-1839713763a6.jpg)

Boton del settings oculto a la mitad mostrando el lado izquierdo.
![settings-app24](https://cloud.githubusercontent.com/assets/13594347/12331601/69dc1348-babc-11e5-84db-e36441093fb4.jpg)

**Comment by Neoperol** [comment]
@Luis-Fernando-Molina @arnaldos 
Yo pensaba que el icono de Settings servia para poder abrir y cerrar el panel?

**Comment by Luis-Fernando-Molina** [comment]
> Yo pensaba que el icono de Settings servia para poder abrir y cerrar el panel? 

puede ser pero no el que esta ahora, sino el mas chiquito que mencioné mas arriba. El dia que aparezca un settings ahi sería para abrir un fragmento con configuraciones a nivel de fermat completo.

**Comment by Luis-Fernando-Molina** [comment]
@arnaldos vos leiste lo que yo escribí?

> Vamos a usar medio boton, a la iz.

lee bien los otros puntos tambien please.

**Comment by arnaldos** [comment]
vale perfecto luis ya ajusto la vista y la comparto

**Comment by Neoperol** [comment]
@furszy 
Ok creo esta todo claro entonces, el panel se abre y se cierra con un boton. 
@arnaldos 
Pero hay que diagramarlo de tal forma que este en otro linea. 
Así el botón de abrir y cerrar queda separado de los iconos de los status. 

![fermat-app-launcher_settings](https://cloud.githubusercontent.com/assets/6201081/12333663/c0f2c428-bac7-11e5-9186-56a04f5e75a9.jpg)

**Comment by arnaldos** [comment]
ok perfecto ya lo diagramo y lo comparto

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina dejo dos versiones una con las sugerencias que me diste y otra siguiendo las sugerencias de @Neoperol 

Versión 1
![version-1](https://cloud.githubusercontent.com/assets/13594347/12336524/2affd3e2-bad7-11e5-839b-66e6411fd641.jpg)

Versión 2
![version-2](https://cloud.githubusercontent.com/assets/13594347/12336525/2b050cae-bad7-11e5-8f1e-1f5ee0399fb7.jpg)

**Comment by Luis-Fernando-Molina** [comment]
Vamos con la versión 2.

Agrega un iconon que represente DPN o Device Private Network. En el texto pone solo "Private Network".

Vamos bien ahora.

**Comment by Luis-Fernando-Molina** [comment]
Ese ultimo icono tambien puede estar deshabilitado, habilitado y habilitado y conectado.

**Comment by arnaldos** [comment]
perfecto !!!

**Comment by arnaldos** [comment]
comparto el icono 
![5](https://cloud.githubusercontent.com/assets/13594347/12345898/e36e0dba-bb20-11e5-8660-826e788b9ece.png)

**Comment by furszy** [comment]
issue cerrado
