### ISSUE TITLE
Generate Banner+Brochure for competition in english

### ISSUE THREAD

**Issue by gustl-arg** [bitDubai/fermat-graphic-design#486]
@arnaldos no se bien como armar el issue, pero basicamente @daveo90 empieza hoy a traducir la web donde figura el concurso y vamos a necesitar las imagenes traducidas tambien.
@Luis-Fernando-Molina me encargo esto ayer.
Gracias!

**Comment by arnaldos** [comment]
perfecto @gustl-arg lo unico es si me puedes ayudar con la redacción del texto en ingles ya que mi ingles no es muy bueno XD yo puedo crear una version pero necesitaria que la corrigieras una ves presente la propuesta.

**Comment by gustl-arg** [comment]
@arnaldos para esto esta la fantastica colaboracion de David, nuestro traductor oficial ! @daveo90 (skype: dalejandro_90) Contactalo a el !

**Comment by daveo90** [comment]
@arnaldos @gustl-arg Hello guys, fun stuff jeje

**Comment by arnaldos** [comment]
@gustl-arg @daveo90  aquí les comparto los artes avísenme si debo ajustar el texto 

Banner

## ![english_banner](https://cloud.githubusercontent.com/assets/13594347/12469080/04f5efea-bfbb-11e5-86dc-c1b41bf6a7e0.jpg)

Broshure
![broshure_vs_english](https://cloud.githubusercontent.com/assets/13594347/12469071/f0609b7a-bfba-11e5-8303-4eab115dea55.jpg)

**Comment by arnaldos** [comment]
no se si el enlace sea el mismo

**Comment by gustl-arg** [comment]
@arnaldos hermoso el arte!, veo algunas correcciones, no obstante le pido a @daveo90 que le de el vistazo final.
link: www.bitdubai.com/wp/adopt-a-component
titulo: Developers competition
1. Learn what is Fermat

**Comment by arnaldos** [comment]
perfecto ya lo ajusto !!

**Comment by arnaldos** [comment]
@gustl-arg  ya genenere las correcciones que me solicitaste. 

![broshure_vs_english](https://cloud.githubusercontent.com/assets/13594347/12482677/2ce5fd3e-c023-11e5-9025-44970725c1ef.jpg)

**Comment by daveo90** [comment]
Hola muchachos aqui las correciones.@arnaldos @gustl-arg y si los graficos y el arte se ven geniales

![image](https://cloud.githubusercontent.com/assets/15698060/12487722/960e4b2e-c03a-11e5-97b7-770d07ecd44a.png)

**Comment by arnaldos** [comment]
perfecto @daveo90 ya realizo los cambios y les comparto

**Comment by arnaldos** [comment]
@gustl-arg @daveo90 listos los ajustes !!!

Banner

## ![english_banner](https://cloud.githubusercontent.com/assets/13594347/12501030/f3aa2b0e-c08a-11e5-9332-2b86f953949d.jpg)

Broshure
![broshure_vs_english](https://cloud.githubusercontent.com/assets/13594347/12501033/fee49662-c08a-11e5-8ac4-fffdcf8c1b1c.jpg)

**Comment by daveo90** [comment]
Hola @arnaldos 
solo falto: you just need to follow these steps:
y en el banner que pegues la coma de la palabra currencies
thank you :)

**Comment by arnaldos** [comment]
perfecto !!

**Comment by gustl-arg** [comment]
@arnaldos hola Arnaldo! donde estan las dos imagenes ( banner y brochure) asi las bajo y las aplico a la pagina??

**Comment by arnaldos** [comment]
ajustes
![broshure_vs_english](https://cloud.githubusercontent.com/assets/13594347/12591422/dd4ed3f2-c439-11e5-8ffc-72b47b16423a.jpg)

**Comment by arnaldos** [comment]
@gustl-arg lo puedes tomar desde aquí del post

**Comment by arnaldos** [comment]
ya te indico la ruta del repo para que lo tomes de ahi si es mas comodo

**Comment by gustl-arg** [comment]
@arnaldos gracias..decidi vos si va en el media-kit, yo lo voy a colocar en el repo de competition que alli si va. Gracias!!
