### ISSUE TITLE
Logo para el equipo Skynet

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#487]
@nindriago como les gustaría que fuese su logo ? que quisieran reflejar en el logo ?

**Comment by nindriago** [comment]
@bitDubai/skynet-team

**Comment by pennyxz** [comment]
Propongo que se utilice el logo original de Skynet, sin las letras. De ser posible, no se que piensa el resto del equipo, que este se vea texturizado con hexagonos regulares.

**Comment by nindriago** [comment]
@pennyxz  imagino te refieres a este logo 

![t0417---skynet](https://cloud.githubusercontent.com/assets/13187461/12355437/ccf60d14-bb6e-11e5-8b50-04f623f39738.png)

**Comment by pennyxz** [comment]
@nindriago Correcto, pero sin el texto. Y con textura de hexagonos.

**Comment by nindriago** [comment]
Al ser Skynet tiene que ser algo que tenga que ver tambien con la RED Mundial y abarcar diferentes aspectos

![artificial-intelligence](https://cloud.githubusercontent.com/assets/13187461/12369144/4b3a0b98-bbc5-11e5-92eb-e739d9efdee2.jpg)

**Comment by pennyxz** [comment]
Me gusta la imagen del cerebro. No estaría mal esa también como textura.

**Comment by jinmyjbv** [comment]
Concuerdo con penny en la textura del cerebro

**Comment by m471c4** [comment]
@arnaldos @nindriago @pennyxz @jinmyjbv acá algunas versiones para e logo de su equipo. Tomé el logo de Skynet e hice muchas modificaciones a partir del hexágono. Espero sugerencias de su parte.

Versión idéntica a la original:
![skynett](https://cloud.githubusercontent.com/assets/13468350/12380605/28affb3e-bd49-11e5-8a7e-d79b74910cf5.png)

Versión 1, descomponiendo el hexágono:
![skynet1](https://cloud.githubusercontent.com/assets/13468350/12380607/3dad622e-bd49-11e5-9b7d-dd690492ffdc.png)

Versión2, igual a la anterior, pero con textura: 
![skynet2](https://cloud.githubusercontent.com/assets/13468350/12380608/3e1a0f6e-bd49-11e5-92e2-0800c109ecf7.png)

versión 3: 
![skynet3](https://cloud.githubusercontent.com/assets/13468350/12380609/3ef625e4-bd49-11e5-9da2-1c8e3f047b6f.png)

Versión 4:
![skynet4](https://cloud.githubusercontent.com/assets/13468350/12380611/3f4ed3d8-bd49-11e5-86bf-760d7714a0c8.png)

Versión 5:
![skynet5](https://cloud.githubusercontent.com/assets/13468350/12380612/3f7a1b92-bd49-11e5-8356-55f1f6ecba1e.png)

Versión 6:
![skynet6](https://cloud.githubusercontent.com/assets/13468350/12380613/3f8234a8-bd49-11e5-8436-1c03e0e1ac13.png)

Versión 7:
![skynet7](https://cloud.githubusercontent.com/assets/13468350/12380614/3fb2269a-bd49-11e5-90ed-0b290c90324e.png)

Versión 8:
![skynet8](https://cloud.githubusercontent.com/assets/13468350/12380615/3fbc0516-bd49-11e5-90ee-a59ba2007197.png)

**Comment by pennyxz** [comment]
@m471c4 ¡Muchas Gracias por los logos! Mi favorito es la Version 4, al cual le agregaría la textura de circuitos, como la imagen del cerebro que adjunto @nindriago.

**Comment by nindriago** [comment]
Epale @m471c4 Te toco hacer este trabajo jejeje te toco facil que barbaro jajajaja ;)

pero si la version 4 es la que se ve mejor, intenta por favor agregale de fondo asi el diseño del cerebro osea la "circuiteria" a ver como se ve asi

**Comment by m471c4** [comment]
@nindriago  de hecho estoy trabajando en los logos de varios equipos, ¿por qué dices que es fácil? :) @pennyxz, @jinmyjbv les adjunto 4 versiones con la textura del circuito. Yo les sugeriría la versión 1 o la 2, ya que el contraste es mucho mejor.

Versión1:
![skynetteam1](https://cloud.githubusercontent.com/assets/13468350/12384169/3fb60f16-bd81-11e5-9a9e-f56be70db5b8.png)

Versión 2:
![skynetteam2](https://cloud.githubusercontent.com/assets/13468350/12384170/3fbcb08c-bd81-11e5-8eb4-3cc2badf34b1.png)

Versión 3:
![skynetteam3](https://cloud.githubusercontent.com/assets/13468350/12384171/3fcf7654-bd81-11e5-8091-8779bc37245d.png)

Versión 4:
![skynetteam4](https://cloud.githubusercontent.com/assets/13468350/12384172/3fd495a8-bd81-11e5-8788-4c0202b108ad.png)

**Comment by nindriago** [comment]
@m471c4  Excelente Dayana se ve mejor esta version, es verdad lo que decis que se ven mejor el 1 y el 2.

pero si se pudiera hacer que sea mas visible o mas notoria la circuiteria dentro seria mejor, prueba con colores diferentes en cada segmento a ver como queda por favor, quizas alguna especie de recorrido osea como si estuviera moviendose osea como si hubiera actividad en cada segmento jejeje

**Comment by m471c4** [comment]
Vale @nindriago, déjame ver qué puedo hacer. Recuerda también que la imagen del cerebro tiene un efecto (como de neón), que será difícil lograr en la versión 3D, que es el acabado final, por lo cual decidí dejarlo de lado.

Las pruebas de color ya las llevé a cabo, las que subí son las mejores, pero déjame ver cómo puedo lograr ese efecto que quieres.

**Comment by m471c4** [comment]
@nindriago @pennyxz @jinmyjbv versión mejorada:

![skynetteamf1](https://cloud.githubusercontent.com/assets/13468350/12409468/89017a78-be3c-11e5-923c-5557f5617316.png)
![skynetteamf2](https://cloud.githubusercontent.com/assets/13468350/12409469/8904cb1a-be3c-11e5-87ce-bbf8918703f1.png)

**Comment by nindriago** [comment]
@m471c4  Dayana, al parecer nos vamos a decidir por la version 1 pero de la tanda anterior, ya que esta no nos gusto como quedo jejeje

**Comment by nindriago** [comment]
esperamos ahora la version 3D :+1:  @arnaldos @m471c4 - version 1 pero de la penultima opcion que hizo @m471c4

**Comment by nindriago** [comment]
![skynet](https://cloud.githubusercontent.com/assets/13468350/12384169/3fb60f16-bd81-11e5-9a9e-f56be70db5b8.png)

**Comment by m471c4** [comment]
@nindriago @pennyxz @jinmyjbv nuevas versiones con algunas mejoras sugeridas por Nerio, por favor definamos cuál será la final para que @jonathanborges3d pueda hacer la moneda.

Mi sugerencia como diseñadora es la versión 1, ya que se ve menos recargado, se asocia al BTC y es mucho más elegante.

Versión 1, con el símbolo de BTC:
![skynetteam1](https://cloud.githubusercontent.com/assets/13468350/12527948/7edcc3c0-c159-11e5-83f4-128a5556eff9.png)

Vresión 2, con tres símbolos:
![skynetteam2](https://cloud.githubusercontent.com/assets/13468350/12527947/7edb5896-c159-11e5-9406-b1ca7b92fd99.png)

Propuesta para el wallpaper:
![skynetteamwallpaper](https://cloud.githubusercontent.com/assets/13468350/12527974/fdc63e82-c159-11e5-9dfa-4aff044192ff.png)

**Comment by pennyxz** [comment]
@m471c4 Nos encanto la version 1, es la que mas destaca. Nuestro equipo @bitDubai/skynet-team ha decido que ese sera el logo definitivo. Muchisimas Gracias. Y el Wallpaper esta de maravilla.

**Comment by m471c4** [comment]
Perfecto @pennyxz ¡me alegra mucho que les haya gustado! Les dejo acá la versión en png, con el fondo transparente. Los editables estarán en el repositorio y el wallpaper lo puedes descargar también directamente del issue :)

![logo_skynet_team](https://cloud.githubusercontent.com/assets/13468350/12528492/ccba8f72-c169-11e5-8885-69abb8022aa5.png)

**Comment by jonathanborges3d** [comment]
@m471c4 Excelente! por favor sube los editables al repo para hacer la versión 3D, no sea que @nindriago desate "the judgment day" en Fermat :smile:

**Comment by m471c4** [comment]
@jonathanborges3d ya las archivos están en el repo, recuerda que debes buscarlos en el fork de @arnaldos :)

Te dejo el enlace acá: https://github.com/arnaldos/fermat-graphic-design/tree/master/2D%20Design/bitDubai/Logotypes%20Teams%20bitDubai/Logo_Skynet_Team

**Comment by jonathanborges3d** [comment]
Primera versión 3D:

![skynet_1](https://cloud.githubusercontent.com/assets/13649739/12763079/b04702b8-c9c4-11e5-96cd-c9b40dc13a01.jpg)

**Comment by nindriago** [comment]
@jonathanborges3d  chamo al fin jajajaja naaah mentira, que bueno :) se ve bien pero el logo no se denota mucho de la estructura de la moneda.

pregunto el nombre del TEAM debe ser asi en color Dorado o hay otras opciones?

**Comment by jinmyjbv** [comment]
@jonathanborges3d Esta muy genial!, por mi parte me gusta como se ve el skynet , no se...

**Comment by pennyxz** [comment]
@jonathanborges3d Me gusta mucho el resultado. Esta chevere.

**Comment by jonathanborges3d** [comment]
@nindriago Jajaja! Nunca es tarde cuando el render llega XD. La opción sería añadir un borde plateado a los hexágonos para resaltarlo. Debo conservar el material cobrizo de fondo porque es común a todas las monedas de los equipos. Si, el color del nombre puede variar pero entre los materiales que se están usando para éstas monedas: Oro, plata, plata mate y cobre. Cual sugieres?

@jinmyjbv @pennyxz Gracias!

**Comment by nindriago** [comment]
suena bien lo de resaltar los haexagonos con plateado, y no me referia a cambiar el color cobrizo de fondo sino a eso a resaltar el logo porque no se ve mucha separacion o diferencia entre el fondo de la moneda y el logo como tal.

gustaria probar el plateado para el nombre, pero ya seria mucho plateado jajaja, veamos como se ve con los hexagonos plateados para empezar xD

**Comment by jonathanborges3d** [comment]
Dos versiones más:

![skynet_3](https://cloud.githubusercontent.com/assets/13649739/12764456/0b0366fe-c9cc-11e5-9dea-bf1971da1b19.jpg)
![skynet_2](https://cloud.githubusercontent.com/assets/13649739/12764457/0b5e20ee-c9cc-11e5-8163-72e32ccec53e.jpg)

**Comment by nindriago** [comment]
me gusta un poco mas la ultima version de todo plateado :)

**Comment by jonathanborges3d** [comment]
Entonces...aprobado con mayoría calificada? :smile:

**Comment by nindriago** [comment]
a los muchachos les gusta el primero, y bueno por mayoria entonces el primero de los nuevos :)

**Comment by jonathanborges3d** [comment]
:+1: Ya lo subo al Dev-Teams-Readme.

**Comment by arnaldos** [comment]
perfecto !!! cierro este caso entonces !!!!
