### ISSUE TITLE
Crear icono para la SubApp Chat Fermat

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#488]
Chat Fermat Es una app similar al whatsapp su función es poder charlar entre usuarios.

Requisitos

Archivo PNG de 32 bits (alpha)
Tamaño: 512 x 512 píxeles
Tamaño máximo del archivo: 1024 KB

Una vez elegido el icono, es necesario generar los tamaños, en .PNG para aplicarlos en lo siguientes:

IC launcher:

48 × 48 px (mdpi)
72 × 72 px (hdpi)
96 × 96 px (xhdpi)
144 × 144 px (xxhdpi)
192 × 192 px (xxxhdpi)
512 × 512 px (Wallet store)

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina  comparto esta versión para el icono de la app chat fermat 

![icon-fermat-chat](https://cloud.githubusercontent.com/assets/13594347/12370089/6f96c924-bbd7-11e5-8386-49faee956c72.png)

**Comment by victoralfonzohd** [comment]
@Luis-Fernando-Molina @arnaldos 

Propuesta:

Versión 1:

![sin-titulo-1](https://cloud.githubusercontent.com/assets/15219855/12391811/a0bd0806-bdbc-11e5-9aad-10aa3b5a32df.png)

Versión 2:

![sin-titulo-2](https://cloud.githubusercontent.com/assets/15219855/12391816/a56f9a12-bdbc-11e5-92de-50e24a3180bc.png)

**Comment by victoralfonzohd** [comment]
@arnaldos 

Propuesta 2:

Versión 1:

![fermat-chat](https://cloud.githubusercontent.com/assets/15219855/12394529/a597df56-bdce-11e5-8974-7f75ee527bc8.png)

Versión 2:

![fermat-chat](https://cloud.githubusercontent.com/assets/15219855/12394582/03f76a3a-bdcf-11e5-8763-9ee7d4225c0c.png)

**Comment by arnaldos** [comment]
@victoralfonzohd has lo similar al whatsapp evitando que sea igual

**Comment by victoralfonzohd** [comment]
@arnaldos 

Propuesta 3:

Versión 1:

![fermat-chat](https://cloud.githubusercontent.com/assets/15219855/12397165/a6fd63e8-bddd-11e5-84ad-890df4832857.png)

Versión 2:

![fermat-chat2](https://cloud.githubusercontent.com/assets/15219855/12397167/aca34b96-bddd-11e5-9768-e2dafc1ae52d.png)

**Comment by arnaldos** [comment]
otra propuesta, usa otros colores plz. aunque podria ir por la version 1 aunque hay que buscar marcar diferencia con el whatsapp

**Comment by victoralfonzohd** [comment]
@arnaldos 

Propuestas de color:

v1:

![fermat-chat](https://cloud.githubusercontent.com/assets/15219855/12405486/d813e3ec-be16-11e5-9937-654796003a5a.png)

v2:

![fermat-chat1](https://cloud.githubusercontent.com/assets/15219855/12405413/12779520-be16-11e5-93dc-026d3ffe60d0.png)

v3:

![fermat-chat2](https://cloud.githubusercontent.com/assets/15219855/12405442/65d37892-be16-11e5-84e0-976016db0683.png)

v4:

![fermat-chat4](https://cloud.githubusercontent.com/assets/15219855/12405651/3ed0f1c8-be18-11e5-9069-5eb8a741410a.png)

**Comment by victoralfonzohd** [comment]
Para marcar diferencias con whatsapp lo mas simple es duplicar el elemento:

Propuesta 4:

V1:

![fermat-chat](https://cloud.githubusercontent.com/assets/15219855/12405577/aaf75ce4-be17-11e5-843d-3b2eac8aa33a.png)

V2:

![fermat-chat1](https://cloud.githubusercontent.com/assets/15219855/12405580/b506abb8-be17-11e5-8111-a3bd1520eca6.png)

V3:

![fermat-chat2](https://cloud.githubusercontent.com/assets/15219855/12405586/bac670c4-be17-11e5-8efe-57c62d919f86.png)

V4:

![fermat-chat3](https://cloud.githubusercontent.com/assets/15219855/12405663/4f043046-be18-11e5-9f88-d9ff07fdb74e.png)

También podría emplearse una forma cuadrada:

![fermat-chat](https://cloud.githubusercontent.com/assets/15219855/12418317/ca5f3692-be80-11e5-9361-0f2de6d241ef.png)

**Comment by victoralfonzohd** [comment]
@arnaldo 

Version 1:

![fermat-chat](https://cloud.githubusercontent.com/assets/15219855/12524608/6c9f8a72-c130-11e5-9dc0-8d531b761a0f.png)

Version 2:

![fermat-chat](https://cloud.githubusercontent.com/assets/15219855/12525421/61731406-c136-11e5-92d4-f3359e2dbbeb.png)

Version 3:

![fermat-chat1](https://cloud.githubusercontent.com/assets/15219855/12525424/698981c0-c136-11e5-8b84-f1c2f12dab5a.png)

**Comment by arnaldos** [comment]
@victoralfonzohd versión 2  solo prueba los puntos en blanco

**Comment by victoralfonzohd** [comment]
@arnaldos 

Versión 2: Comparación de colores

![fermat-chat](https://cloud.githubusercontent.com/assets/15219855/12553247/814e7072-c348-11e5-94fe-122382ebc653.png)

![fermat-chat1](https://cloud.githubusercontent.com/assets/15219855/12553250/858e19d0-c348-11e5-866c-f398ca72b707.png)

**Comment by arnaldos** [comment]
versión blanco los puntos
