### ISSUE TITLE
Mejorar la pantalla del detalles del broker de la "Crypto Broker Identity" 

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#489]
- colocar una flecha en el action bar para el boton de Back
- la imagen del usuario que abarque el ancho de la pantalla
- colocar un layer encima de la imagen en la parte inferior para colocar un texto
- texto blanco alineado a la izquierda
- abajo de la imagen colocar un switch que permite mostrar si esta activo o inactivo. (Visible - No visible)
- debe aparecer el teclado para editar el nombre 

version actual
![img-20160118-wa0002](https://cloud.githubusercontent.com/assets/13594347/12399932/27c7f40a-bdef-11e5-93ad-044f39bbe7af.jpg)

**Comment by ivonnesantos** [comment]
![propuesta_01](https://cloud.githubusercontent.com/assets/15238660/12419080/0194c55a-be86-11e5-8190-61d1ece86c0b.png)
![propuesta_01_editname](https://cloud.githubusercontent.com/assets/15238660/12419081/01a1a018-be86-11e5-8287-3844b2cf5c1c.png)

@arnaldos

**Comment by ivonnesantos** [comment]
se resolvió en el issue #491
