### ISSUE TITLE
Bocetar ideas para la imagen de Fermat OSA

### ISSUE THREAD

**Issue by m471c4** [bitDubai/fermat-graphic-design#49]
Viene del #8 

Actualmente el logo se tomó prestado de otro concepto. Se debe realizar uno nuevo. Hacerlo directamente con la nueva paleta de colores.

![fermat-osa](https://cloud.githubusercontent.com/assets/9479367/9057301/6aaa7e3e-3a99-11e5-9600-08fa4cd434b2.png)

**Comment by m471c4** [comment]
@Luis-Fernando-Molina ¿podrías decirme de qué va esta sub-app?

**Comment by Luis-Fernando-Molina** [comment]
Es una capa que permite que la plataforma sea multi sistema operativo

Osea que cora en Android, Windows, Linux y OSX (Apple)

Tecnicamente no es una Sub App, sino una Super Capa

**Comment by m471c4** [comment]
@Luis-Fernando-Molina: este sería el primer boceto para Fermat Osa:

![fermatosa](https://cloud.githubusercontent.com/assets/13468350/9515900/7ee0c9da-4c6e-11e5-8cde-049191df387f.png)

**Comment by Luis-Fernando-Molina** [comment]
El logo está lindo, pero no lo veo representativo del concepto. 

OSA es la parte del sistema que permite que corra en Android , Windows , Linux y Apple. Abria que ver si se pueden incoportar esos sistemas operativos sin violar la trade mark de los mismos.

**Comment by m471c4** [comment]
@Luis-Fernando-Molina los logos de Windows y Apple tienen licencias que no nos permitirían usarlos. El robot de Android si podría ser utilizado, al igual que el logo de Linux. Es por eso que escogí estas tuercas, para representar el concepto de sistema operativo.

**Comment by Luis-Fernando-Molina** [comment]
@m471c4 mirá el logo de DPN que tiene varios dispositivos interconectados, esos dispositivos se pueden ajustar para que parezcan un iphone, android, windows, etc de alguna manera. Además se puede poner Pcs de escritorio la tipica forma de una MAC , un servidor, etc.

**Comment by acostarodrigo** [comment]
@Luis-Fernando-Molina no era Operating System API?

**Comment by Luis-Fernando-Molina** [comment]
@acostarodrigo si, no entiendo la pregunta.

**Comment by acostarodrigo** [comment]
@Luis-Fernando-Molina que está escrito Operative System API

**Comment by Luis-Fernando-Molina** [comment]
ahhh, es cierto está mal escrito. @m471c4 por favor corregilo y asegurate que llege a miguel, gracias.

Debe decir "Operating System"

**Comment by m471c4** [comment]
@Luis-Fernando-Molina @acostarodrigo muy bien, me aseguraré de corregirlo.

**Comment by m471c4** [comment]
@Luis-Fernando-Molina con el título corregido y una nueva propuesta:

![fermatosa2](https://cloud.githubusercontent.com/assets/13468350/9626807/e7678402-5129-11e5-8fff-53d0794f4133.png)

**Comment by Luis-Fernando-Molina** [comment]
puede ser, revisa la sobra del device de la iz. El resto puede quedar asi. 

Una cosa que le dije a @arnaldos  es que los bordes blancos deben tener un tamaño estandar (quizas hayan dos, uno fino y otro mediano) pero no pueden depender de que el elemento se haya escalado previamente. Tenemos que ser consistente con eso en todos los logos de esta serie.

**Comment by m471c4** [comment]
@Luis-Fernando-Molina con las correcciones. Tenemos 3 tamaños de borde estandar, lo que hice fue engrosar al de mayor tamaño el del engranaje y la llave, para que sea igual al de los dispositivos.

![fermatosa3](https://cloud.githubusercontent.com/assets/13468350/9651941/84038c78-51e0-11e5-928d-c6d69bd154a0.png)

**Comment by Luis-Fernando-Molina** [comment]
:+1:  listo, actualizá Fermat.org y cerrá el caso.

**Comment by m471c4** [comment]
Muy bien @Luis-Fernando-Molina. @Miguelcldn los logos de Fermat OSA y CBP fueron actualizados, por favor cámbialos cuando puedas.
