### ISSUE TITLE
Mejorar la pantalla de la lista de broker de  la "Crypto Broker Identity" 

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#490]
- aumentar el tamaño del action bar y mejorar gráficamente el mismo.
- debe aperecer la imagen del broker del ancho de la pantalla 
- colocar un layer encima de la imagen en la parte inferior para colocar un texto
- nombre blanco alineado a la derecha y el estado blanco y alineado a la izquierda
- mejorar gráficamente acorde a la paleta de colores

versión actual 

![img-20160118-wa0001](https://cloud.githubusercontent.com/assets/13594347/12399942/3bf47e76-bdef-11e5-91a6-32c28564a378.jpg)

**Comment by ivonnesantos** [comment]
![propuesta_01_lista](https://cloud.githubusercontent.com/assets/15238660/12433006/c5934fa4-bed0-11e5-8c35-f91538a7e60a.png)

@arnaldos @furszy @Luis-Fernando-Molina

**Comment by ivonnesantos** [comment]
se resolvio en el issue #491
