### ISSUE TITLE
Mejorar la pantalla de usuario nuevo de la "Crypto Broker Identity" 

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#491]
- el en accion bar colocar un boton que permita crear una identidad nueva
- crear un icono que permita identificar el espacio vació siendo representado con una empresa.
- colocar una flecha en el action bar para el boton de Back
- mejorar graficamente lo que esta planteado 

versión actual
![screenshot_2016-01-18-14-27-49](https://cloud.githubusercontent.com/assets/13594347/12402277/0818d908-bdfe-11e5-83ef-32612d73b8a9.png)

**Comment by ivonnesantos** [comment]
![archivo-de-indicaciones](https://cloud.githubusercontent.com/assets/15238660/12460194/c87b306a-bf84-11e5-8ed8-12bd2bd805c7.png)

@arnaldos @Luis-Fernando-Molina @furszy

**Comment by ivonnesantos** [comment]
@arnaldos @nelsonalfo @vlzangel 
![archivo de indicaciones_mesa de trabajo 2](https://cloud.githubusercontent.com/assets/15238660/12569451/3e3e1dc4-c3a1-11e5-83d0-9df56fffa69d.jpg)

**Comment by adryx83** [comment]
@arnaldos aqui esta una primera propuesta del boton, con un pequeño menú desplegable, espero se entienda.

![propuesta_iconoeditandcreate contact](https://cloud.githubusercontent.com/assets/17273349/13538868/15b000a6-e21f-11e5-83fb-47d6f1182f32.jpg)

**Comment by nelsonalfo** [comment]
No me convence... es confuso porque según el titulo ya estas dentro de la pantalla de crear una identidad. no le veo mucho sentido a ese menú button ahi...

**Comment by vlzangel** [comment]
Correcto, y si esta en la pantalla del listado, la opción de editar no me parece que debiese estar en el menú.

**Comment by leonacostaok** [comment]
@arnaldos por favor denle una vuelta de tuerca más.
Ahí la imagen se ve bien cuando está el teclado, pero cuando entras, que no está el teclado, la imagen se encuentra como muy grande, podrían poner un ejemplo en donde se vea como debería quedar sin el teclado?
Y por favor, ese botón 3d que dice Visible Not Visibile... Tiene que haber otra cosa que se pueda poner ahí un poco más amigable...

Si pueden ver como está en la app para ver cuál sería la mejor estrategia para encararlo...

**Comment by arnaldos** [comment]
@nelsonalfo @lnacosta @vlzangel Las mejoras se estarán posteando en estos casos #645 #673 #672 #674

**Comment by nelsonalfo** [comment]
gracias @arnaldos para cuando podemos tener esas propuestas listas?

**Comment by arnaldos** [comment]
estamos trabajando en eso el día de hoy en la tarde ya tendremos propuestas de las mejoras
