### ISSUE TITLE
Primer Video de Fermat: Escena 4

### ISSUE THREAD

**Issue by jonathanborges3d** [bitDubai/fermat-graphic-design#497]
Viene del #432 

Coloco aquí el borrador del storyboard correspondiente a la Escena 4 (última):
#### "If you are interested in joining the Fermat project, or to learn more..."

Me gustaría intentar algo como dar a entender que todo el video estaba siendo visto por un personaje (diferente a los que tenemos, podemos llamarlo "userDev") en una tablet. Para esto se debe tomar el último fotograma de la escena 3-E y animar un zoom out dejándo ver el personaje con la tablet en mano mostrando tal fotograma. Tal vez con una vista del plano por encima del hombro del personaje estaría bien. 
#### "...please visit Fermat.org"

Luego el userDev pasa la pantalla en el dispositivo con el dedo hacia la izquierda y aparece el logo de fermat con el nombre en gris, del cual salen por un costado las letras ".org" una por una, para colocarse delante de "Fermat", tal como aparece el logo en 1A. Usemos un color diferente al gris para éstas.

(Aquí vamos a incluir el motto del proyecto, "Dream bigger.")

Toda la escena sale por la izquierda y queda el logo de Fermat en primer plano, para mostrarse primero con el nombre y luego con el motto, que lo suplanta de izquierda a derecha. Se desvanece y finaliza.

**Comment by jonathanborges3d** [comment]
@victoralfonzohd @Yinellydesign @AnaPietrosanti Guión actualizado.

**Comment by victoralfonzohd** [comment]
@jonathanborges3d Jonathan, hay que cambiar un poco la idea para "If you are interested in joining the Fermat project, or to learn more..."  Cuando pasa el zoom out de la escena 3E y vemos el personaje UserDev sosteniendo la tableta, la vista por encima del hombro que propones va a limitar la visión de lo que pasa en la pantalla del dispositivo, y una vista totalmete cenital a mi parecer no va a quedar bien.. 

Propongo la siguiente vista para realizar esta idea y que veamos lo que ocurre en la pantalla:
Que opinan tu y @AnaPietrosanti @Yinellydesign ?

[personaje-escena4-v1](https://cloud.githubusercontent.com/assets/15219855/12966057/25145ed8-d02d-11e5-90f4-1117014a2507.jpg)

**Comment by jonathanborges3d** [comment]
Ah perfecto! Estoy de acuerdo. Así se vé mejor de cómo lo imaginé :smile: 

Vamos a hacerle a éste personaje su ambiente completo, puede ser una oficina, o la sala de una casa, no sé, dispón de ello. Tal vez debas cambiar el ¿puff?, ¿sillón? no sé que es, pero me da la impresión de que se caerá de repente jaja!

**Comment by victoralfonzohd** [comment]
@jonathanborges3d jajajaja era un puff..

Sillon:

[personaje-final](https://cloud.githubusercontent.com/assets/15219855/12966748/30697c72-d033-11e5-8023-b06263690011.jpg)

**Comment by jonathanborges3d** [comment]
:+1: Perfecto, ahora sácala del mundo de "pocoyó" con un ambiente :smile:

**Comment by victoralfonzohd** [comment]
@jonathanborges3d 

Entorno: Para el entorno preferí ir por el lado de la habitación de una casa, para que se entienda que Fermat, y sus servicios estan disponibles para personas comunes, no solo empresarios, y developers, que el alcance va mucho mas allá 

[personaje-final](https://cloud.githubusercontent.com/assets/15219855/12968015/ad61a7ee-d03e-11e5-96e8-8ac035aad876.jpg)

**Comment by jonathanborges3d** [comment]
A mí me parece chévere, Que opinan @AnaPietrosanti y @Yinellydesign ?

**Comment by victoralfonzohd** [comment]
@jonathanborges3d 

Storyboard Escena 4:

[storyboard-4](https://cloud.githubusercontent.com/assets/15219855/12992676/f28ed93c-d0e7-11e5-9805-82f60b08c527.jpg)

**Comment by jonathanborges3d** [comment]
Por mi :+1: Qué dicen @AnaPietrosanti y @Yinellydesign ?

**Comment by AnaPietrosanti** [comment]
@victoralfonzohd  solo cambio de salida de texto .org

**Comment by victoralfonzohd** [comment]
@jonathanborges3d @AnaPietrosanti 

Cambios:

![storyboard-4](https://cloud.githubusercontent.com/assets/15219855/12993324/b0851cdc-d0eb-11e5-8dbc-23b7320290e2.jpg)
