### ISSUE TITLE
Diseñar diferentes denominaciones para los *fers* o milésimas de 1 Fermat token

### ISSUE THREAD

**Issue by jonathanborges3d** [bitDubai/fermat-graphic-design#499]
Se necesitarán representaciones de los _**fers**_ o milésimas de **Fermats** de las siguientes denominaciones:

1
10
100

Podrían crearse como monedas en forma de aros o con un diseño de algún calado interno, para diferenciarlas de las fiat currency ya realizadas y de un único material cada una, pueden ser: cobre, bronce y plata, reservando el material dorado para la representación de los Fermat tokes.

Al igual que los Fermats, los fers tendrían un símbolo para expresar las cantidades de su valor, sería una "f" con dos barras horizontales en vez de una, pero en éste caso minúscula, para indicar un valor decimal.

Propuestas para el símbolo:

Versión 1: Agrega una barra horizontal por debajo de la existente
![fermat_simbolo_4](https://cloud.githubusercontent.com/assets/13649739/12534040/e878d272-c219-11e5-8201-6302b29b205a.JPG)

Versión 2: barra adicional por encima de la anterior.
![fermat_simbolo_5](https://cloud.githubusercontent.com/assets/13649739/12534046/2c9336dc-c21a-11e5-80cb-79041cb6f846.JPG)

Versión 3: sustituye la barra original por dos equidistantes.
![fermat_simbolo_6](https://cloud.githubusercontent.com/assets/13649739/12534048/3dc9d9ec-c21a-11e5-86a0-aeab24b34b34.JPG)

A su vez, los _fers_ pudiesen tener en el centro un diseño basado en el símbolo propuesto pero en forma de orificio, como los siguientes ejemplos:

![](http://nycsubway.org.s3.amazonaws.com/images/articles/tokens-token2.jpg)

![](http://www.rochestersubway.com/images/a3004/rochester_subway_token_780d-1.jpg)

@Luis-Fernando-Molina

**Comment by Luis-Fernando-Molina** [comment]
Vamos con la version 3 pero asegurate de que el espacio entre las dos barras sea del mismo ancho que las barras plesae.

Porbemos lo del hueco en la imagen 1

**Comment by jonathanborges3d** [comment]
Primeras versiones de las denominaciones 1, 10 y 100 fers:

![fers_1](https://cloud.githubusercontent.com/assets/13649739/12538271/dd6b2f68-c2a7-11e5-8fcc-221eb65af478.jpg)

![fers_2](https://cloud.githubusercontent.com/assets/13649739/12538276/eeb8d126-c2a7-11e5-954e-af459f3d7757.jpg)

![fers_3](https://cloud.githubusercontent.com/assets/13649739/12538277/03d725a8-c2a8-11e5-8cab-aea5980567ff.jpg)

![fers_4](https://cloud.githubusercontent.com/assets/13649739/12538280/14d96b54-c2a8-11e5-9e80-ab77f0c8a590.jpg)

![fers_5](https://cloud.githubusercontent.com/assets/13649739/12538282/20ca4d34-c2a8-11e5-882e-9e98340abb52.jpg)

![fers_6](https://cloud.githubusercontent.com/assets/13649739/12538283/2116ae0e-c2a8-11e5-988e-77ca40a7e5a4.jpg)

**Comment by Luis-Fernando-Molina** [comment]
ok se ven bien. Pero deberia ser 1 cobre, 10 plata, 100 oro. 

Proba las letras en un material diferente a la bases y las estrellas en el tercer material . Anda rotandolos.

Fermat App Token el texto esta como muy grande, no es tan relevante. Es mas no se si lo pondria.

**Comment by Luis-Fernando-Molina** [comment]
El problema con que sea huevo es que del otro lado se va a ver al reves, pero bueno, probemos.

**Comment by Luis-Fernando-Molina** [comment]
los bordes (el canto) pudieran ser mas elaborados tambien con mas elaboracion a medida que aunmenta el valor

**Comment by jonathanborges3d** [comment]
Nuevas versiones: Cambié el calado interno por un alto relieve de la _f_, así no habría problemas con el lado opuesto, aunque en las imágenes de referencia hay una con _R_ en ambos sentidos.
También ordené los materiales como indicaste.

![fers_7](https://cloud.githubusercontent.com/assets/13649739/12592954/e60c8096-c440-11e5-982b-56d10d8bbf24.jpg)
![fers_8](https://cloud.githubusercontent.com/assets/13649739/12592955/e6231068-c440-11e5-9e7d-52e067d58899.jpg)
![fers_9](https://cloud.githubusercontent.com/assets/13649739/12592956/e637f0be-c440-11e5-968c-5494aa8cd823.jpg)

**Comment by Luis-Fernando-Molina** [comment]
te falto esto

> Proba las letras en un material diferente a la bases y las estrellas en el tercer material . Anda rotandolos.

**Comment by jonathanborges3d** [comment]
Pasé por alto ése detalle. Tercera versión:

![fers_10](https://cloud.githubusercontent.com/assets/13649739/12600185/d2cb0d3a-c469-11e5-904f-7a76f06c79d3.jpg)
![fers_11](https://cloud.githubusercontent.com/assets/13649739/12600186/d2e2e70c-c469-11e5-8158-895b290cb0a3.jpg)
![fers_12](https://cloud.githubusercontent.com/assets/13649739/12600187/d2f73f40-c469-11e5-8445-7410b8d262d6.jpg)

**Comment by Luis-Fernando-Molina** [comment]
las mitades de billetertas no me convencen.  Fijate de sacarselas.

Aun si eso todavia le falta, no se que.

**Comment by jonathanborges3d** [comment]
Agregué un circuito en la zona central a ver que tal quedaría.

![fers_13](https://cloud.githubusercontent.com/assets/13649739/12693586/83ce1a78-c6e0-11e5-99bd-3c5bc6bae0e2.jpg)

**Comment by Luis-Fernando-Molina** [comment]
Queda bien, pero esta muy colorido, probemos con 2 colores, fijate las 2 combinaciones posible en este caso. Otra cosa, proba hacer el circuito mucho mas fina y mas denso. Se ve muy tosco en esa escala.

**Comment by jonathanborges3d** [comment]
Nueva versión del circuito y propuestas de combinación de materiales:

Cobre y plata
![fers_14](https://cloud.githubusercontent.com/assets/13649739/12699960/4010e8ac-c7a2-11e5-9669-db105e4a584e.jpg)

Cobre y oro
![fers_15](https://cloud.githubusercontent.com/assets/13649739/12699978/126a98c0-c7a3-11e5-9a71-33f734cb14e8.jpg)

**Comment by Luis-Fernando-Molina** [comment]
ok mejoro, pero no me decido, cual te parece mejor a vos?

**Comment by jonathanborges3d** [comment]
Me gusta más la de cobre con plata, el contraste es mejor.

Versión nueva de 10 fers:

![fers_16](https://cloud.githubusercontent.com/assets/13649739/12703091/fc773c26-c80b-11e5-89b7-5b9b001c34b6.jpg)

**Comment by Luis-Fernando-Molina** [comment]
:+1:

**Comment by jonathanborges3d** [comment]
Versión nueva de 100 fers

![fers_17](https://cloud.githubusercontent.com/assets/13649739/12706498/d7fdbcf6-c858-11e5-8312-0c6cd5a2788b.jpg)

**Comment by Luis-Fernando-Molina** [comment]
Esta no queda bien. Proba todo oro.

**Comment by jonathanborges3d** [comment]
Y que tal ésta?

![fers_18](https://cloud.githubusercontent.com/assets/13649739/12706862/5ef26e1e-c85e-11e5-9a49-3545fcc4899c.jpg)

**Comment by Luis-Fernando-Molina** [comment]
mucho mejor, que material es?

**Comment by jonathanborges3d** [comment]
es un oro oscurecido, el mismo que le coloqué al bitcoin

**Comment by jonathanborges3d** [comment]
es para que se noten los elementos que van en relieve. Hago otra propuesta?

**Comment by Luis-Fernando-Molina** [comment]
puede andar por ahora, asi esta bien :+1:

**Comment by jonathanborges3d** [comment]
Ok, aquí dejo un render de presentación de las tres monedas.
![fers_19](https://cloud.githubusercontent.com/assets/13649739/12760696/bed1fd02-c9b9-11e5-8a5a-764ca27e4cb5.jpg)

Cómo se necesitan los renders individuales? con el formato para los archivos de README?

**Comment by Luis-Fernando-Molina** [comment]
aguanta un toque con todo esto porque parece que hay un cambio que se va a aplicar pronto, donde los fermats se dividen en dos tokens diferentes. Suspende todo lo relacionado hasta aclarar eso please.

**Comment by jonathanborges3d** [comment]
Entendido :+1:
