### ISSUE TITLE
Generar un banner para Asset user Identity 

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#500]
medidas del banner :
1025x500 pixeles 

proviene del siguiente caso:
https://github.com/bitDubai/fermat/issues/4572
este caso hace referencia a la demo de la app

**Comment by emmysm** [comment]
![asset user 3-03](https://cloud.githubusercontent.com/assets/15143489/12633689/d707ed28-c545-11e5-8f78-85762efacc14.png)
![asset user 3-02](https://cloud.githubusercontent.com/assets/15143489/12633690/d730acb8-c545-11e5-9d42-0cd42ab03ed9.png)

@arnaldos  @Luis-Fernando-Molina

**Comment by arnaldos** [comment]
la ultima versión :+1:   pero ajusta el elemento del porcentaje, no esta centrado.
