### ISSUE TITLE
Generar un banner para Asset user comunity

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#501]
medidas del banner :
1025x500 pixeles 

proviene del siguiente caso:
https://github.com/bitDubai/fermat/issues/4572
este caso hace referencia a la demo de la app

**Comment by emmysm** [comment]
![asset user-01](https://cloud.githubusercontent.com/assets/15143489/12593785/0f5c770e-c445-11e5-8f2c-257c4be97582.png)
@arnaldos

**Comment by emmysm** [comment]
![asset user 2-01](https://cloud.githubusercontent.com/assets/15143489/12593966/eded7d9c-c445-11e5-8be2-a15b7ae8e429.png)
@arnaldos

**Comment by emmysm** [comment]
![asset user 4-01](https://cloud.githubusercontent.com/assets/15143489/12601145/f87b948a-c470-11e5-8416-e02d169302e6.png)

**Comment by arnaldos** [comment]
busca de representar gráficamente los asset dentro del banner, los elementos mas pequeños eliminalos, en ves de realzar la ´pieza genera ruido, el simbolo de bitcoin aqui no tiene sentido en ese espacio coloca asset en ves de bitcoins.

**Comment by arnaldos** [comment]
este comentario era para los dos primeros, estoy evaluando xD

**Comment by arnaldos** [comment]
para la propuesta 3 si aplica lo del simbolo e bitcoin remplazalo por asset. usa otra tipografia, en esta oportunidad creo que no funcionan todas en altas, si vas a usar todas en altas abre el interletrado.  centra el icono de la community en caso de usarlo centrado, ahorita no esta ni centrado ni justificado a la derecha revisa eso.

**Comment by emmysm** [comment]
![asset user 2-03](https://cloud.githubusercontent.com/assets/15143489/12620292/f1be3288-c4ed-11e5-89f0-ac156f4092f2.png)
![asset user 2-04](https://cloud.githubusercontent.com/assets/15143489/12620293/f1bfbf54-c4ed-11e5-8918-6718513954e3.png)
![asset user 2-01](https://cloud.githubusercontent.com/assets/15143489/12620294/f1c195b8-c4ed-11e5-8c67-e3e929dd6e59.png)
![asset user 2-02](https://cloud.githubusercontent.com/assets/15143489/12620295/f1c4d7e6-c4ed-11e5-880d-27c5f05427f1.png)

@arnaldos @Luis-Fernando-Molina

**Comment by emmysm** [comment]
![asset user completo-01](https://cloud.githubusercontent.com/assets/15143489/12633607/42842dc4-c545-11e5-821e-835a9741c1fb.png)

@arnaldos

**Comment by arnaldos** [comment]
ultima propuesta :+1:
