### ISSUE TITLE
Generar un banner para Asset Issuer Identity 

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#502]
medidas del banner :
1025x500 pixeles 

proviene del siguiente caso:
https://github.com/bitDubai/fermat/issues/4572
este caso hace referencia a la demo de la app

**Comment by m471c4** [comment]
@arnaldos 

Versión 1:
![aiiden-banner1](https://cloud.githubusercontent.com/assets/13468350/12694349/3a09cb18-c6fd-11e5-913a-5c7e85a2a619.png)

Versión 2:
![aiiden-banner2](https://cloud.githubusercontent.com/assets/13468350/12694350/3a0a8fe4-c6fd-11e5-8a02-2b5a6be0a778.png)

Versión 3:
![aiiden-banner3](https://cloud.githubusercontent.com/assets/13468350/12694351/3a1e7d2e-c6fd-11e5-93c3-22d082ef5643.png)

**Comment by arnaldos** [comment]
@m471c4  lo mismo que te comento en el #503.

**Comment by arnaldos** [comment]
veo que usas figuras geométricas para representar  los asset se que en un momento se planteo esto pero no estoy seguro que nos transmita a un asset issuer. replantealo plz

**Comment by m471c4** [comment]
@arnaldos es que el logo y el icono de la asset issuer tiene, de hecho, esas figuras geométricas, que fue la forma en la que Luis quiso que se representaran los assets. Estoy usando los mismos elementos para ser coherente con la imagen principal.

![aiwallet4](https://cloud.githubusercontent.com/assets/13468350/12699293/77ecc7ba-c788-11e5-85b0-b3768ab2e367.png)

**Comment by arnaldos** [comment]
si te entiendo pero se ven raro y no transmite que se trata de una identidad jurídica o empresa que distribuye asset .... la idea del banner de gráficos es vender la app de manera visual. aquí estos elementos no te están ayudando puedes usarlo en el banner pero busca transmitir eso que te digo. ya el logo se definió bajo esa estructura, ahora busca definir el banner buscando como objetivo la distribución de asset.

**Comment by m471c4** [comment]
Vale @arnaldos, haré otras propuestas y las subo para ambos casos.

**Comment by m471c4** [comment]
@arnaldos ¿algo así te parece bien?

Versión 1:
![aiiden-banner4](https://cloud.githubusercontent.com/assets/13468350/12711762/8d1e8b66-c894-11e5-8348-876696e549b9.png)

Versión 2:
![aiiden-banner5](https://cloud.githubusercontent.com/assets/13468350/12711763/8d291658-c894-11e5-8884-ef8a5f30d46f.png)

**Comment by m471c4** [comment]
@arnaldos para esta versión varié el color del fondo:

![aiiden-banner7](https://cloud.githubusercontent.com/assets/13468350/12903766/605ca0c8-ce9c-11e5-9c8b-0c0efd08f329.png)

**Comment by arnaldos** [comment]
@m471c4 para esta versión replantea el banner esta muy gris ..... busca un equilibrio cromatico.. por otro lado la diagramacion es muy igual a la community. juega con los elementos dentro del espacio buscando una diagramacion que se diferencie de la community.

**Comment by m471c4** [comment]
@arnaldos 

![aiiden-banner8](https://cloud.githubusercontent.com/assets/13468350/12960132/c8875c40-d00b-11e5-8529-c143196c3ef1.png)

**Comment by arnaldos** [comment]
listo !!! :+1: sube los archivos

**Comment by arnaldos** [comment]
@nindriago @acostarodrigo este banner ya esta listo avísenme cuando este aplicado para cerrar el caso
