### ISSUE TITLE
Generar un banner para Asset Issuer comunity

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#503]
medidas del banner :
1025x500 pixeles 

proviene del siguiente caso:
https://github.com/bitDubai/fermat/issues/4572
este caso hace referencia a la demo de la app

**Comment by m471c4** [comment]
@arnaldos 

Versión 1:
![aicom-banner1](https://cloud.githubusercontent.com/assets/13468350/12694357/56455a18-c6fd-11e5-9630-4a00f26ebb67.png)

Versión 2:
![aicom-banner2](https://cloud.githubusercontent.com/assets/13468350/12694358/5648fb1e-c6fd-11e5-9fda-a7408392e9fd.png)

**Comment by arnaldos** [comment]
@m471c4 busca la manera que transmita dentro del banner el asset issuer que se resume a una entidad jurídica que distribuye asset. a nivel tipográfico usa una mas estructurada, esta que usas para la palabra community se ve como si la hubiesen aplastado. y no te ayuda en la pieza.busca una que te realce la pieza.

**Comment by m471c4** [comment]
@arnaldos 

Versión 1:
![aicom-banner3](https://cloud.githubusercontent.com/assets/13468350/12711778/aff7fd7a-c894-11e5-849c-194af9d010fa.png)

Versión 2:
![aicom-banner4](https://cloud.githubusercontent.com/assets/13468350/12711779/b01b4a8c-c894-11e5-8c80-bca4726eb885.png)

**Comment by m471c4** [comment]
@arnaldos con las mejoras sugeridas:

![aicom-banner5](https://cloud.githubusercontent.com/assets/13468350/12727669/1c8a77e6-c8f0-11e5-9db7-d8f67847d955.png)

**Comment by m471c4** [comment]
@arnaldos mejoras:

Versión 1:
![aicom-banner6](https://cloud.githubusercontent.com/assets/13468350/12743749/02463ccc-c962-11e5-94d9-f421d07baa93.png)

Versión 2:
![aicom-banner7](https://cloud.githubusercontent.com/assets/13468350/12743773/29983d34-c962-11e5-8e4d-2778f2fc8c4a.png)

Versión 3:
![aicom-banner8](https://cloud.githubusercontent.com/assets/13468350/12743750/025a45aa-c962-11e5-8538-8f1d61a0e06c.png)

Yo optaría por alguna de las dos primeras versiones. Espero tus comentarios.

**Comment by m471c4** [comment]
@arnaldos con las últimas mejoras:

![aicom-banner9](https://cloud.githubusercontent.com/assets/13468350/12902718/005fc4d6-ce95-11e5-9ddf-48bfe8afc711.png)

**Comment by arnaldos** [comment]
@m471c4 ultima propuesta :+1:

**Comment by arnaldos** [comment]
@nindriago @acostarodrigo este banner ya esta listo, avísenme cuando este aplicado para cerrar el caso

**Comment by acostarodrigo** [comment]
mañana lo aplicamos y te avisamos.
@nindriago

**Comment by arnaldos** [comment]
perfecto !!

**Comment by ivonnesantos** [comment]
@acostarodrigo esto esta aplicado?
