### ISSUE TITLE
Generar un banner para Redempoint comunity

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#504]
medidas del banner :
1025x500 pixeles 

proviene del siguiente caso:
https://github.com/bitDubai/fermat/issues/4572
este caso hace referencia a la demo de la app

**Comment by ivonnesantos** [comment]
![banner_community-01](https://cloud.githubusercontent.com/assets/15238660/12598137/bbd27c76-c45a-11e5-8e71-5c32e2f40170.jpg)
![banner_community-02](https://cloud.githubusercontent.com/assets/15238660/12598141/bd7f4360-c45a-11e5-8274-78c31ecfacd4.jpg)
![banner_community-03](https://cloud.githubusercontent.com/assets/15238660/12598142/bfabcb2c-c45a-11e5-84c2-94e6d983c306.jpg)

@arnaldos @Luis-Fernando-Molina

**Comment by arnaldos** [comment]
@ivonnesantos propuesta 2

**Comment by ivonnesantos** [comment]
@arnaldos este es el banner que se quedara?
