### ISSUE TITLE
Generar un banner para Redempoint Identity

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#505]
medidas del banner :
1025x500 pixeles 

proviene del siguiente caso:
https://github.com/bitDubai/fermat/issues/4572
este caso hace referencia a la demo de la app

**Comment by ivonnesantos** [comment]
![banner_identity-01](https://cloud.githubusercontent.com/assets/15238660/12599657/0f5b0af6-c466-11e5-8396-9e2c3ca58268.jpg)
![banner_identity-02](https://cloud.githubusercontent.com/assets/15238660/12599658/0f62087e-c466-11e5-94ec-76ce83c9a93d.jpg)
![banner_identity-03](https://cloud.githubusercontent.com/assets/15238660/12599659/0f78dad6-c466-11e5-8a12-fd3be5b73138.jpg)
@arnaldos

**Comment by arnaldos** [comment]
@ivonnesantos propuesta 3
