### ISSUE TITLE
Crear un señalador para identificar la app en la sección de la web de fermat.

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#507]
Debemos identificar que es android y que es Fermat. solo es para mostrar en la sección web del Prototype App.

---

![captura de pantalla 4](https://cloud.githubusercontent.com/assets/13594347/12616164/e136734c-c4db-11e5-9d4d-6b840bacf99d.png)

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina 

versión 1

---

## ![prototype-fermat-appv1](https://cloud.githubusercontent.com/assets/13594347/12616234/4ace383a-c4dc-11e5-91bc-5583c154aeb1.png)

![prototype-fermat-appv2](https://cloud.githubusercontent.com/assets/13594347/12616235/4ad0891e-c4dc-11e5-825f-0e54d4377c8a.png)

**Comment by Luis-Fernando-Molina** [comment]
1-la idea es esa pero podes hacer algo que se vea mas lindo.
2. La primera imagen no puede estar oscurecida , quita eso
3. Lo de abajo debiera decir "This is a Fermat APP"
4. En la primera "This is Android"
5. 2da y 3ra "This is Fermat"
6. Proba con algo diagonal que solo tampe una esquina. Ponele mas onda al diseño.

gracias

**Comment by arnaldos** [comment]
perfecto !!!

**Comment by ivonnesantos** [comment]
@arifernandez esto es un material para la página web que sirve para mostrarle a los usuarios de la página en que consiste fermat crea una propuesta tomando en cuenta las correcciones que indica luis 
aca esta en enlace de la pagina http://bitdubai.com/wp/fermat
