### ISSUE TITLE
Generar Banner pra Sub app Crypto Broker Identity 

### ISSUE THREAD

**Issue by victoralfonzohd** [bitDubai/fermat-graphic-design#508]

**Comment by victoralfonzohd** [comment]
@arnaldos 

Version 1:

![banner-1](https://cloud.githubusercontent.com/assets/15219855/12650117/c7cfb3cc-c5b3-11e5-9133-08b59425f169.png)

Version 2:

![banner2](https://cloud.githubusercontent.com/assets/15219855/12650134/d336d43e-c5b3-11e5-88a3-e087a8e48406.png)

**Comment by arnaldos** [comment]
@victoralfonzohd versión 2 :+1:
