### ISSUE TITLE
Generar Banner pra Sub app Crypto Broker Community

### ISSUE THREAD

**Issue by victoralfonzohd** [bitDubai/fermat-graphic-design#509]

**Comment by victoralfonzohd** [comment]
@arnaldos 

Version 1:

![sin-titulo-1](https://cloud.githubusercontent.com/assets/15219855/12650338/ae5b62e6-c5b4-11e5-8ab6-7eb6a838c124.png)

Version 2:
![sin-titulo-12](https://cloud.githubusercontent.com/assets/15219855/12650469/2b66f976-c5b5-11e5-9566-1328150ec121.png)

**Comment by arnaldos** [comment]
@victoralfonzohd  genera una nueva version plz.

**Comment by victoralfonzohd** [comment]
@arnaldos 

Version 3:

![banner-crypto-broker](https://cloud.githubusercontent.com/assets/15219855/12663459/9b04020c-c5fa-11e5-8c56-11e2cf1a3c6f.png)

Version 4:

![banner-crypto-broker1](https://cloud.githubusercontent.com/assets/15219855/12663468/ae598818-c5fa-11e5-992d-d367cbf8da98.png)

**Comment by victoralfonzohd** [comment]
@arnaldos 

Version 5:

![banner-crypto-broker1](https://cloud.githubusercontent.com/assets/15219855/12664000/abcf2996-c5fe-11e5-8e73-c9d7c91892b2.png)

Version 6:
![banner-crypto-broker](https://cloud.githubusercontent.com/assets/15219855/12664007/b8b3f1b4-c5fe-11e5-85a0-f0a97e7979d3.png)

Version 7:
![banner-crypto-broker](https://cloud.githubusercontent.com/assets/15219855/12664038/f62e783e-c5fe-11e5-81e0-1f088f2b8f94.png)

**Comment by victoralfonzohd** [comment]
@arnaldos 

![banner-crypto-broker](https://cloud.githubusercontent.com/assets/15219855/12680887/36186cdc-c67e-11e5-81a1-9217038cd8ba.png)

**Comment by victoralfonzohd** [comment]
@arnaldos 
![banner-crypto-broker](https://cloud.githubusercontent.com/assets/15219855/12933887/da74ffb6-cf5c-11e5-8b90-6c094e454364.png)

**Comment by arnaldos** [comment]
:+1: sube los fuentes !!

**Comment by proseuz** [comment]
Primera propuesta para el banner @emmysm @Luis-Fernando-Molina 
![banner crypto broker community2](https://cloud.githubusercontent.com/assets/17308060/13240276/77560d60-d9b3-11e5-88bd-e51fe2e6b182.jpg)

**Comment by Luis-Fernando-Molina** [comment]
Porque este caso esta etiquetado como DAP?

**Comment by Luis-Fernando-Molina** [comment]
porque es high priority?

**Comment by Luis-Fernando-Molina** [comment]
porque estamos haciendo algo de nuevo que ya estaba?

**Comment by emmysm** [comment]
Este caso nunca se cerró porque se había decidido replantear el banner. Y las etiquetas eran viejas :) @Luis-Fernando-Molina

**Comment by emmysm** [comment]
Por eso tenía high priority

**Comment by Luis-Fernando-Molina** [comment]
ok, y no tenemos nada mas urgente, como las pantallas de DAP?

**Comment by emmysm** [comment]
Sí. Le asigné este para que se fuera familiarizando con fermat. Ya le asigno que me ayude con la DAP.

**Comment by Luis-Fernando-Molina** [comment]
ok, vale, este puede cerrarse con lo que presentó, por ahora alcanza. saludos.
