### ISSUE TITLE
Mejoras gráficas de la Banking Wallet 

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#510]

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina @guillermo20

![sec-1](https://cloud.githubusercontent.com/assets/13594347/12661193/5c7c7d1c-c5ea-11e5-97b9-f0c8c790bbcd.jpg)

---

![sec-2](https://cloud.githubusercontent.com/assets/13594347/12661194/5c81f558-c5ea-11e5-8fcb-9ab6ddd9f9c2.jpg)

---

![sec-3](https://cloud.githubusercontent.com/assets/13594347/12661195/5c876790-c5ea-11e5-89ef-9d3d11df3608.jpg)

**Comment by Luis-Fernando-Molina** [comment]
:+1:

**Comment by Luis-Fernando-Molina** [comment]
@arnaldos que podes hacer vos de todo esto a nivel de los layouts?

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina seria cuestión que @guillermo20 me indique como están configurados los layaouts e iniciar a implementar los cambios con previa asistencia ya que hay cosas que aun no manejo.

**Comment by Luis-Fernando-Molina** [comment]
ok vale

**Comment by arnaldos** [comment]
@guillermo20  estamos listo con esto ?
