### ISSUE TITLE
Crear mejoras graficas para la Asset Factory

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#511]
Se postearan las mejoras visuales de la app Asset Factory

**Comment by ivonnesantos** [comment]
![archivo de indicaciones_mesa de trabajo 2](https://cloud.githubusercontent.com/assets/15238660/12683541/056b5410-c68c-11e5-9c65-233d70af057d.jpg)
@arnaldos

**Comment by ivonnesantos** [comment]
@arnaldos @Luis-Fernando-Molina 
![archivo de indicaciones_mesa de trabajo 2](https://cloud.githubusercontent.com/assets/15238660/12721823/d83e312a-c8d3-11e5-8e41-188f9162f900.jpg)

**Comment by Luis-Fernando-Molina** [comment]
Hola @ivonnesantos , si bien lo que presentas se ve mucho mejor que antes, en este caso, estas pantallas no estan diagramadas correctamente. 

Necesito que ademas de hacer que se vean mejor vearn como mejorar la usabilidad en los casos que sean necesario.

Por ejemplo: Si vos estuvieras en un departamento de marketing y estuvieras  diseñando una campaña para una promoción y tuvieras varias promociones parecidas, en esa imagen tan chiquita no distinguirias de cuales se trataria. 

Quien diseño esta pantall no tuvo en cuenta ese tipo de cosas y por mas que mejores el aspecto estamos trabajando sobre algo que no esta bien pensado.

Lo mas importante acá en la imagen y debe ocupar el mauor espacio disponible. 

Otra cosa que se ve es que no hay suficiente espacio para una descripcion ahi.

El tema del Asset Value tampoco esta explicado ni se entiende. Vos entedes para que sirve?

Mi mensaje es: no se pongan a mejorar algo que no saben como ni para que sirve. Averiguen y entiendanlo y si ven que algo no esta bien, es el momento de arreglarlo antes de que siga mal pero mas lindo.

El domingo se hizo un demo sobre esto, busca el video y vas a ver. 

Las otras visas con 4 assets por pantalla tampoco me parece adecuado. Cada uno debiera ocupar el ancho entero. 

Saludos!

**Comment by ivonnesantos** [comment]
Diseño de lista y cargar imagen para crear un asset

![archivo de indicaciones_mesa de trabajo 2](https://cloud.githubusercontent.com/assets/15238660/12826269/66d88258-cb4c-11e5-9f01-dc2e9eda8020.jpg)
@Luis-Fernando-Molina @arnaldos @acostarodrigo

**Comment by acostarodrigo** [comment]
hola @ivonnesantos , las pantallas para cargar la imagen del asset me parecen muy bien.
No me queda claro qué se está mostrando en las 2 imagenes de abajo. Eso sería en la edición del asset?

**Comment by ivonnesantos** [comment]
esa es la lista de draf en la primera hago una muestra en caso que el usuario muestre su imagen recortada y además aprovechó de mostrar el menú de opciones y la segunda es si el usuario decide ajustar al ancho una imagen rectangular apaisada en este ejemplo lo muestro de las dos formas porque le estamos dando la opción de elegir al usuario y necesito mostrar como queda en ambos casos (este ejemplo lo puedes ver en el instagram cuando colocas una imagen que no es cuadrada)

**Comment by acostarodrigo** [comment]
ok, perfecto.

**Comment by ivonnesantos** [comment]
![archivo de indicaciones_mesa de trabajo 02](https://cloud.githubusercontent.com/assets/15238660/12829695/a59d1470-cb5d-11e5-9b57-e6827320fcf3.jpg)
Si hay alguna persona que tenga un mejor ingles que me pueda corregir esos textos la pueden etiquetar. Gracias
@Luis-Fernando-Molina @arnaldos @acostarodrigo

**Comment by Luis-Fernando-Molina** [comment]
@ivonnesantos me parece que ahora todo va mucho mejor encaminado. Me gusta que ya estes aplicando criterios de usabilidad y no solo mejorando como se ve.

@yojoaquin necesitamos que todos los diseñadores se vayan adaptando a esto como lo está haciendo @ivonnesantos 

Muy bien @ivonnesantos !

**Comment by Luis-Fernando-Molina** [comment]
@furszy acá vas a encontrar mas componentes para tu librería que luego pueden ser reutilizados.

**Comment by Luis-Fernando-Molina** [comment]
@arnaldos compartiste con todos los miembros de tu equipo los criterios de diseño android? se están aplicando en los diseños de pantallas?

**Comment by acostarodrigo** [comment]
tambien me sumo, muy bien @ivonnesantos 
Con respecto a los textos, yo pondria:
1) Create new asset
2) Load image
3) Complete data
4) Validate and save

**Comment by furszy** [comment]
Ok, de acá me llevo para la api: El selector de wallets, el reloj, el calendario. La ultima pantalla ya se puede hacer con lo que tenemos.

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina si le he compartido varios enlaces que nos ayudan a entender los criterio de android.

**Comment by ivonnesantos** [comment]
Mejoras Graficas tomando en cuenta recomendaciones de android que desconocía @Luis-Fernando-Molina @arnaldos @acostarodrigo 
![archivo de indicaciones_mesa de trabajo 2](https://cloud.githubusercontent.com/assets/15238660/12931266/112b7cd2-cf4f-11e5-94c6-e46b1e449973.jpg)

**Comment by ivonnesantos** [comment]
@acostarodrigo hola rodrigo aca esta la propuesta de los campos de informacion como ves trate de darle una información más completa sobre lo sus gastos para crear asset ademas hice un ticket para que el usuario vea una resumen de informacion y que desde esa ventana termine de crear sus asset espero haber dado a entender bien lo que me explicaste.
![archivo de indicaciones-02](https://cloud.githubusercontent.com/assets/15238660/12931435/05751ab4-cf50-11e5-9d67-f76bd522c31e.jpg)

@Luis-Fernando-Molina @arnaldos

**Comment by acostarodrigo** [comment]
me encantó. Entiendo que la sección Balance deberia mostrar en Balance Total: la suma de todo, es decir, fee \* valor del asset \* cantidad, correcto?

cc @furszy por si hay que agregar algo al toolbox.

**Comment by Luis-Fernando-Molina** [comment]
Me parece que va bien encaminado pero hay varias cosas que refinar.

Esta bien que el asset este dividido en tres pantallas. Todo el tiempo estamos diciendo que un asset es:

1) Un elemento multimedia (por ahora una imagen)
2) Un "Terms & Conditions" no "information"
3) Un "Crypto Currency" que permite registrarlo en una blochain y lo hace inclonable.

1) sobre la parte de la imagen esta bien ,mi unico comentario ahi es que no entiendo como se pasa a la siguiente pantalla. Bien pudiera ser un PAGER de 3 paginas, pero para eso tendria que haber 3 puntitos abajo.

2) La parte de TERMS & CONDITIONS no me queda clara la interfaz. Si es que cuando toco en un label me sale una ventanita para completar, pudiera ser, pero que despues no me muestre el dato no lo veo intuitivo.

3) La parte de CRYPTO CURRENCY no lo veo muy intuitivo tampoco. Lo que tiene que decidir un ISSUER es lo siguiente (no quiere decir que tenga que estar expresado asi mismo)

*deberia tener pre seleccionada bitcoin como unica posibilidad ahora mismo, pero estar claro ahi
- tiene que saber cuanto es el fee standard en ese momento.
- tiene que saber el monto minimo para poder crear la transacción que entiendo que es de 1 satoshi
- Tiene que decidir si quiere ponerle un fee o no a la transacción de generación del asset (quizas no quiere y esta dispuesto a esperar que en algun momento se genere)
- Tiene que decidir si le envia (o incluye) el fee que va a necesitar el usuario para redimirlo. (esto debiera preguntarse solo si el asset es redimible)
- Tiene que decidir si quiere regalarle al usuario algo de bitcoin y cuanto.

Hoy se está haciendo todo eso en un solo paso pidiendo que se cargue el monto en bitcoin, pero es impractico tener que estar averiguando cuanto es el fee standard, y calculando a mano cuanto tengo que poner para que me de justo para mi fee mas el del usuario sin que sobre ni que falte.

*\* Puede que incluso me este olvidande de algun detalle.

Me parece que la pagina de "Crypto Currency" le queda mucho espacio para mejorarse.

**Comment by ivonnesantos** [comment]
Ok @Luis-Fernando-Molina los de los campos de texto lo entiendo ellos se ocultan para que el usuario no tenga que hacer scroll pero si tienes razon puede ser poco intuitivo, con respecto a el CRYPTO CURRENCY 
-deberia tener pre seleccionada bitcoin como unica posibilidad ahora mismo, pero estar claro ahi 
Si el por deafult deberia tener la billetera que tenga más bitcoins o la última utilizada por eso tiene un lapiz a un lado que representa que se puede editar y elegir otra para esto aparece una ventana emergente que muestra las billeteras las que no tengan el saldo suficiente las coloca en gris claro 
y no da la oportunidad de seleccionar.
-tiene que saber el monto minimo para poder crear la transacción que entiendo que es de 1 satoshi
Arriba al inicio de la pantalla lo tiene solo que lo puse como bitcoin en el ejemplo
-Tiene que decidir si quiere regalarle al usuario algo de bitcoin y cuanto.
Yo entendi segun el video que vi que esto es obligatorio hay que ponerle al menos un monto minimo para que no sea clonable, si nos es asi entonce se le debe formular una opcion

Yo hice dos secciones una que indica al que esta creando el asset cuanto sera el valor de ese beneficio para el receptor del asset
otra seccion que le calcula al creador del asset según el costo total de su operacion en este caso son 3 assets entonces 0,005*3 en un campo luego abajo muestra otros gastos que se generan de los que me hablo @acostarodrigo ese valor se suma y muestra el total es decir cuantos bitcoins necesita de tal manera que el usuario no tenga que estar sacando la cuenta de cuanto le va a costar todo.

No tengo Claro que es un fee por eso no se si el proceso que te describo anteriormente responde a estas observaciones
"Hoy se está haciendo todo eso en un solo paso pidiendo que se cargue el monto en bitcoin, pero es impractico tener que estar averiguando cuanto es el fee standard, y calculando a mano cuanto tengo que poner para que me de justo para mi fee mas el del usuario sin que sobre ni que falte."
@acostarodrigo

**Comment by Luis-Fernando-Molina** [comment]
> Si el por deafult deberia tener la billetera que tenga más bitcoins o la última utilizada por eso tiene un lapiz a un lado que representa que se puede editar y elegir otra para esto aparece una ventana emergente que muestra las billeteras las que no tengan el saldo suficiente las coloca en gris claro
> y no da la oportunidad de seleccionar.

Probablemente sea asi, aunque @acostarodrigo vaya implementando esa funcionalidad por etapas, porque ciertas cosas no las tiene hoy en día.

> -Tiene que decidir si quiere regalarle al usuario algo de bitcoin y cuanto.
> Yo entendi segun el video que vi que esto es obligatorio hay que ponerle al menos un monto minimo para que no sea clonable, si nos es asi entonce se le debe formular una opcion

No estoy seguro como funciona ahora, pero para el usuario final debiera ser mas o menos como detalle yo. Lo podemos discutir con @acostarodrigo En general  toda esa parte debe estar bien pensada para que sea intuitivo y facil de entender para el que no conoce los detalles de abajo. Si vas a poner un monto tenes que saber porque pones una cosa u otra porque en definitiva es dinero.

**Comment by acostarodrigo** [comment]
@Luis-Fernando-Molina  @ivonnesantos Las distintas alternativas de manejo con el fee es algo que no estamos manejando en Fermat aún.

Por ejemplo, la bitcoin Wallet agrega el fee al monto total especificado por el usuario, mientras que las wallets de Assets toman el fee del valor del asset. Hoy en dia es un valor fijo y esto debe mejorarse en los procesos transaccionales y visualmente en todas las wallets.

De lo tuyo, van mis comentarios:

> tiene que saber cuanto es el fee standard en ese momento.

Podemos agregar un calculador de fee basado en el estandard de un monto fijo según el tamaño de la transacción. Este sería el valor por default de fee a definir para el asset. 

> Tiene que decidir si quiere ponerle un fee o no a la transacción de generación del asset (quizas no quiere y esta dispuesto a esperar que en algun momento se genere)

@ivonnesantos Esto significa que el usuario puede cambiar o incluso poner en cero el valor del fee que seteamos como estandard. Es decir que en la propuesta tuya deberías dar opciones de seteo del fee. Quizas una sección más que muestre el valor por default, pero permita aumentarlo o reducirlo a cero. Debemos explicar con algun tipo de warning que mientras menor sea el fee, más puede tardar la transacción en confirmarse, o incluso nunca confirmarse si está en cero.

> tiene que saber el monto mínimo para poder crear la transacción que entiendo que es de 1 satoshi

Es correcto. @ivonnesantos para que se entienda, el usuario puede decidir que el asset va a tener el valor mínimo posible que es un satoshi. 

> Tiene que decidir si le envia (o incluye) el fee que va a necesitar el usuario para redimirlo. (esto debiera preguntarse solo si el asset es redimible)

@Luis-Fernando-Molina Esto no es tan fácil y requiere de un cambio importante. Las Asset wallets para cada transacción sacan el fee del valor del asset, hasta que el mismo se agote y no pueda generarse otra transacción. Que el pago del fee del asset se saque de la wallet del usuario no está contemplado aún. 

> Tiene que decidir si quiere regalarle al usuario algo de bitcoin y cuanto.

@Luis-Fernando-Molina acá no me queda claro qué queres decir. El valor que el issuer le ponga al asset (que como mínimo puede ser 1 satoshi) es lo que le va a dar al usuario. El usuario siempre puede appropiar el asset y quedarse con el valor del mismo.

**Comment by Luis-Fernando-Molina** [comment]
> Tiene que decidir si quiere regalarle al usuario algo de bitcoin y cuanto.
> 
> @Luis-Fernando-Molina acá no me queda claro qué queres decir. El valor que el issuer le ponga al asset (que como mínimo puede ser 1 satoshi) es lo que le va a dar al usuario. El usuario siempre puede appropiar el asset y quedarse con el valor del mismo.

El issuer pudiera querer mandarle 1 bitcoin entero a un usuario de regalo. Hoy en dia vos decis que si pone 1 BTC le come de ahi el fee de la generacion y el fee del envio, osea que no le llegaria 1 btc.

Yo lo que digo es que la informacion se le tiene que pedir por separado.

ISSUING FEE: Idem para el fee de la generacion.
DELIVERY FEE: Si yo quiero agregar un fee para el envio, lo mismo con un check box alcanza.
REDEMPTION FEE: Si yo quiero agregar el fee para redimir, me debiera permitir checkear un checkbox y listo.
CRYPTO GIVE AWAY: Si yo quiero regalar 1 BTC en un campo o selector deberia poder poner 1 btc y que eso sea mi regalo. 

El valor del fee debiera estar en el selector donde por defecto te ponga el estimado de cuanto es el fee apropiado.

Probablemente lo que el tipo selecciona aca debieras acarrearlo dentro del digital contract o no se donde, para ir aplicando estas definiciones a lo largo del ciclo de vida del asset. 

Estoy de acuerdo con el hecho de que se genere el asset con la suma de todo lo que selecciono y de ahi se va consumiendo. No planteo un cambio respecto a eso. En un principio mi cambio es estetico y en la forma en que se captura la informacion. Puede que tenga un impacto mas abajo si uno quiere hacerle caso a lo que el tipo dijo respecto a donde quiere y donde no quiere que hayan fees. 

Pudieras al menos capturar bien la informacion aunque tengas que hacerle caso mas abajo un poco mas adelante o encolar ese cambio.

**Comment by ivonnesantos** [comment]
Aca dejo el cambio con respecto a los campos de texto los arrgle para que no tenga que cerrarse y otra propuesta de color un poco mas ligera a ver si les gusta
Proopuesta que se ha trabajado
![archivo de indicaciones-03](https://cloud.githubusercontent.com/assets/15238660/12968831/75f50a70-d049-11e5-8e1e-5b019f1c1dbb.jpg)

nueva propuesta de color numero 2 
![archivo de indicaciones-04](https://cloud.githubusercontent.com/assets/15238660/12968837/908f59b2-d049-11e5-95ed-4555e4d963f5.jpg)

@Luis-Fernando-Molina

**Comment by acostarodrigo** [comment]
@Luis-Fernando-Molina , También deberiamos agregar el Transfer fee por ejemplo?

El Issuing Fee lo paga la Bitcoin Wallet que es de donde sale el dinero, por lo tanto no deberíamos agregarlo como detalle porque me parece que confunde.

Igualmente te parece poner tanto detalle? Tené en cuenta que el Asset al redimirse se recicla y se vuelve a iniciar el ciclo. Actualmente, cuando ya la cantidad de bitcoins disponibles del asset no alcanzan para iniciar un ciclo, cuando vuelve al issuer se appropia automaticamente.

Quizas podríamos poner la cantidad de ciclos que querés permitir y en base a esa cantidad, mostrar el valor del fee.

Por ejemplo:
Full cycles fee: 1
- [checkbox] Delivery: 15000 satoshis
- [checkbox]  Redemption: 15000 satoshis
- Total Fee Balance: 30000 satoshis

Full cycles fee: 2
- [checkbox] Delivery: 30000 satoshis
- [checkbox]  Redemption: 30000 satoshis
- Total Fee Balance: 60000 satoshis

@ivonnesantos de acuerdo con poner la fecha en gris hasta que no se seleccione el Expiration Date.

**Comment by ivonnesantos** [comment]
aca una maqueta de las funciones @Luis-Fernando-Molina @acostarodrigo @javafrank 
![definicion de maueta-03](https://cloud.githubusercontent.com/assets/15238660/12992385/5da0456e-d0e6-11e5-9b7f-18680701d6ef.jpg)

**Comment by acostarodrigo** [comment]
@ivonnesantos que software puedo usar para rápidamente dibujar pantallas asi simples? Para mostrarte la idea que tengo y tambien para nuevos desarrollos.

**Comment by yojoaquin** [comment]
Les sugiero el balsamiq mockups 3 para crear mockups

2016-02-11 19:15 GMT-03:00 Rodrigo notifications@github.com:

**Comment by Luis-Fernando-Molina** [comment]
gente me salgo de la charla, no me da el tiempo, terminen ustedes de decidir y pasen esto a producción.

**Comment by acostarodrigo** [comment]
@furszy Matias, esto se puede hacer?
Que si la imagen seleccionada no cubre el 100% de la pantalla, entonces se especifique un color de fondo?

![image](https://cloud.githubusercontent.com/assets/9518556/13052392/67fff00a-d3dd-11e5-97ba-3c1b42e64cc2.png)

**Comment by furszy** [comment]
Si, eso es cambiarle el fondo al contenedor principal o a algún container del layout que arma esa vista.

**Comment by acostarodrigo** [comment]
va a haber algo en el toolbox para usar?

**Comment by furszy** [comment]
Podríamos hacer un selector de colores para este caso.

**Comment by yojoaquin** [comment]
Consutla: en lugar de programar eso por qué no damos las medidas de la imagen y que con el cropper la ajusten?

**Comment by furszy** [comment]
Es una solución también. Pueden dar una medida y ajustarla. Eso ya depende de como se quiera mostrar.

**Comment by ivonnesantos** [comment]
@furszy yo diseñe un selector de color con un limite de 4 colores que son de la identidad de la app para que no desentone.

**Comment by javafrank** [comment]
Approach 1. Asset Factory - Create/Edit, by @Fermat-ORG/skynet-team 

This is expandable layout based user interface, in a only screen.

![factory_create_edit5 jinmy](https://cloud.githubusercontent.com/assets/13275281/14478908/89f93c6a-00e3-11e6-8a20-bc7e068e0e12.png)
![factory_create_edit4 jinmy](https://cloud.githubusercontent.com/assets/13275281/14478909/8a031d02-00e3-11e6-8112-ea3709390562.png)

Approach 2. Asset Factory - Create/Edit, by @Fermat-ORG/skynet-team 

This is a wizard based user interface, at final screen the information is showed to user, for verification. The last image of this approach is a proposal of edit option of an asset.

![asset factory crear 1](https://cloud.githubusercontent.com/assets/13275281/14498933/2a1764ec-0166-11e6-842c-93a53f592955.jpg)
![asset factory crear 2](https://cloud.githubusercontent.com/assets/13275281/14498942/2ed86b0c-0166-11e6-9e6f-248749c74a7b.jpg)
![prototipo - asset factory - modificar](https://cloud.githubusercontent.com/assets/13275281/14499514/6e6d5f96-0168-11e6-8198-e8839e631f69.png)

Asset Factory Home Approach.

![screenshot from 2016-04-12 19 01 56](https://cloud.githubusercontent.com/assets/13275281/14479053/bd5d77d2-00e4-11e6-949f-cde549b1a268.png)

cc @ivonnesantos @acostarodrigo

**Comment by ivonnesantos** [comment]
Design Approach 2. Asset Factory 
I need your opinion on these proposals color

N1
![propuesta_ux_04-01](https://cloud.githubusercontent.com/assets/15238660/14866093/b59f2de4-0c8b-11e6-9e17-ce303f611e49.jpg)

N2
![propuesta_ux_04-02](https://cloud.githubusercontent.com/assets/15238660/14866102/bdf6bd90-0c8b-11e6-97ac-300e4d795c14.jpg)

N3
![propuesta_ux_04-03](https://cloud.githubusercontent.com/assets/15238660/14866108/c3bf6542-0c8b-11e6-9e25-77f680974c71.jpg)

@pennyxz @javafrank @nindriago @arnaldos @jinmyjbv

**Comment by emmysm** [comment]
Mis propuestas
![asset factory](https://cloud.githubusercontent.com/assets/15143489/14871416/a8b0c7bc-0cab-11e6-9a5b-135d9de18548.jpg)

@Fermat-ORG/skynet-team @javafrank

**Comment by arnaldos** [comment]
### Trabajemos en base a la versión de @emmysm

1- Manten los colores ya que la identidad de la asset factory tiene colores azules asegúrate sean los mismos.
2- La linea indicadora de la ubicación del wizzard no hazla mas orgánica similar a la de ivonne sin dejar la linea fina tan delgada.
3- Coloca un fondo sutil en los wizzards.
4- Los botones que no abarquen el el total de pantalla.
5-Juega con las Tipografía light o regular. usa helvetica neue 
6-En el formulario coloca texto simulado con color mas claro asi podremos apreciar como se vera el texto en esa área.
7-Cuando elijes la foto del asset tenemos foto y botones coloca esos elementos dentro de un marco. (wizzard 1)
8-El campo donde se coloca el texto colocale una transparencia para que haga constraste con el fondo(el que vas a hacer)

### Dejo ejemplos:

#### Fondo y boton

![3](https://cloud.githubusercontent.com/assets/13594347/14872618/d73ca05e-0cb7-11e6-8bdd-16ad69a0491e.jpg)

#### Transparencia en los campos de textos

![1](https://cloud.githubusercontent.com/assets/13594347/14872625/e9204546-0cb7-11e6-8c03-cb2c5e6cc61e.jpg)

#### Marco mas fondo

![2](https://cloud.githubusercontent.com/assets/13594347/14872653/32d3d84c-0cb8-11e6-972a-5bbded9f0e0b.jpg)

**Comment by arnaldos** [comment]
obviamente ajusta los elementos al tamaño correspondiente para que quede todo bien diagramado. no como deje en los ejemplos

**Comment by emmysm** [comment]
Ok @arnaldos. En mis propuestas usé light y Regular :). Trabajaré en los otros ajustes.

**Comment by ivonnesantos** [comment]
@emmysm un detalle que estoy viendo ahorita en el bonton de foto y galeria utilizaste en un boton icono y en el otro texto puedes porfa unificar eso sea icono o texto pero ambos igual

**Comment by arnaldos** [comment]
@ivonnesantos tienes razon, @emmy prueba dos versiones un con ambos con icono y otro con texto pero combinados no resulta.

**Comment by emmysm** [comment]
Vale, perfecto @arnaldos @ivonnesantos

**Comment by pennyxz** [comment]
Buenos días. Me gusta mucho la propuesta para la wizard, y no tengo ningún agregado que ofrecer, me parece que esta chevere. 

También necesitamos por favor, que nos generen el diseño para el Asset Factory Home Approach como lo propuso Frank en este comentario, a lo ultimo. https://github.com/Fermat-ORG/fermat-graphic-design/issues/511#issuecomment-209156409

Ya estamos trabajando en la base de el, tanto para la pantalla de DRAFT como la de ISSUED, pero necesitamos que obviamente este representado con su respectivo diseño y recursos. Tambien para estas pantallas necesitamos una imagen de fondo para indicar cuando no hay assets, como se han hecho en las demás wallets.

Muchisimas gracias @emmysm @ivonnesantos

**Comment by emmysm** [comment]
![factory](https://cloud.githubusercontent.com/assets/15143489/14958417/88f84dd0-1054-11e6-88da-5389f424fde9.jpg)

Buenos días chicos, @pennyxz @Fermat-ORG/skynet-team @arnaldos. Aca les dejo varias propuestas para el wizzard. 
@pennyxz ya trabajo en las pantallas y recursos que necesitas.

**Comment by acostarodrigo** [comment]
No usaria el término Terms And Conditions, ya que no es lo que se va a especificar en esa sección.

Esa sección se debe llamar Asset Details o Asset Properties
y debe incluir:
- nombre
- description
- Es redimible con un check mark
- Es transferible con un check mark
- Es exchangable con un check mark.

Mas adelante, en otras plataformas vamos a tener tipos de assets que seguramente van a necesitar especificar términos y condiciones, pero para los assets generales el nombre no es apropiado.

**Comment by javafrank** [comment]
me gustan la 1 y la 2

**Comment by jinmyjbv** [comment]
Me gusta la propuesta 1

**Comment by emmysm** [comment]
![factory home-01](https://cloud.githubusercontent.com/assets/15143489/14973620/de8d4c1e-10b3-11e6-90d0-b2d85b7d9bf1.jpg)

@Fermat-ORG/skynet-team @javafrank @acostarodrigo

**Comment by nindriago** [comment]
de ese ultimo Emmy, pues la propuesta 2 y 2da opcion

**Comment by emmysm** [comment]
@nindriago :+1:

**Comment by pennyxz** [comment]
Para la propuestas del Wizard expuestas en el comentario https://github.com/Fermat-ORG/fermat-graphic-design/issues/511#issuecomment-216267306 Me gusta la primera.

De las propuestas del home, tu ultima publicación, me gusta la segunda opción de la Propuesta 2, al igual que @nindriago

**Comment by emmysm** [comment]
![asset factory 2-01](https://cloud.githubusercontent.com/assets/15143489/15060564/a1cc5b82-12f5-11e6-8747-dbe1035882c9.png)

@Fermat-ORG/skynet-team

**Comment by pennyxz** [comment]
Excelente @emmysm

**Comment by arnaldos** [comment]
para esta propuesta podemos mejorar algunos elementos @emmysm reúnete conmigo

**Comment by emmysm** [comment]
![propuestas de color 2-03](https://cloud.githubusercontent.com/assets/15143489/15089500/0716c080-13ce-11e6-8395-dfba829123e7.png)
![propuestas de color 2-01](https://cloud.githubusercontent.com/assets/15143489/15089501/071c6bca-13ce-11e6-9224-8bf7f98b598a.png)
![propuestas de color 2-02](https://cloud.githubusercontent.com/assets/15143489/15089502/071d15e8-13ce-11e6-84f2-fcdcf3472153.png)

@Fermat-ORG/skynet-team

**Comment by jinmyjbv** [comment]
Me gusta la propuesta 3 @emmysm

**Comment by javafrank** [comment]
1 y 2 me gustan a mi

**Comment by arnaldos** [comment]
@emmysm  la propuesta 1 :+1:  sube los recursos para que los muchachos apliquen.

**Comment by emmysm** [comment]
Perfecto @arnaldos :+1:

**Comment by arnaldos** [comment]
@emmysm @jinmyjbv @javafrank esto esta implementado para cerrar el caso ??
