### ISSUE TITLE
Crear mejoras gráficas para la Asset user wallet

### ISSUE THREAD

**Issue by emmysm** [bitDubai/fermat-graphic-design#512]

**Comment by emmysm** [comment]
![sin titulo-1](https://cloud.githubusercontent.com/assets/15143489/12698904/44a68118-c77c-11e5-824b-f1c1540e8f61.png)
![sin titulo-2](https://cloud.githubusercontent.com/assets/15143489/12698905/46517978-c77c-11e5-983e-1c07f8b1444c.png)

@arnaldos @nindriago @Luis-Fernando-Molina

**Comment by emmysm** [comment]
![pantallas](https://cloud.githubusercontent.com/assets/15143489/12760082/d93cbaa4-c9b6-11e5-86ea-30f300a27fa8.png)
@arnaldos

**Comment by arnaldos** [comment]
mejora el icono de  **"+"** solo eso

**Comment by emmysm** [comment]
Asset user community
![vistas](https://cloud.githubusercontent.com/assets/15143489/12837326/c37095f4-cb93-11e5-99a5-12c41f20ecfd.png)
![vistas 2](https://cloud.githubusercontent.com/assets/15143489/12837327/c48ea7e6-cb93-11e5-931e-61bdbc2774ac.png)

@arnaldos @Luis-Fernando-Molina @rodrigogerez @nindriago

**Comment by Luis-Fernando-Molina** [comment]
Vas muy bien Emmy. Fijate de entender bien la APP y lo que hace para no solo hacer que se vea mejor sino aplicar las mejores practicas de diseño de APPs que podés encontrar en : http://developer.android.com/design/get-started/principles.html . Cada elemento de la pantalla debiera estar justificado en uno o mas de estos criterios. Estudialos, entendelo y por favor aplicalos. saludos! @arnaldos @yojoaquin asegurense de transmitir este mensaje al resto de las personas que están ayudando en el diseño de las pantallas, @acostarodrigo incluyendo los programadores que hacen la primera versión. La experiencia de usuario la tenemos que pulir entre todos.

**Comment by acostarodrigo** [comment]
@emmysm por favor cambiemos el texto de Administrate Groups a Manage Groups.

**Comment by emmysm** [comment]
Excelente, @Luis-Fernando-Molina  muchas gracias :D. Ya estoy estudiando los criterios que me proporcionaron tú y Arnaldo. Saludos!

@acostarodrigo ya genero los ajustes

**Comment by emmysm** [comment]
![view navigation-01](https://cloud.githubusercontent.com/assets/15143489/12901781/acd18ee4-ce8f-11e5-8246-a309389d8d80.png)

![asset user community modificaciones-02](https://cloud.githubusercontent.com/assets/15143489/12901728/5dfe89e8-ce8f-11e5-9083-52332b650aef.png)
![asset user community modificaciones-03](https://cloud.githubusercontent.com/assets/15143489/12901729/5e009756-ce8f-11e5-8d70-10bbcf475d37.png)

![asset user community modificaciones-04](https://cloud.githubusercontent.com/assets/15143489/12901812/cbb9d794-ce8f-11e5-8778-65c5b66700b3.png)

![asset user community modificaciones-05](https://cloud.githubusercontent.com/assets/15143489/12901731/5e26d7c2-ce8f-11e5-8a7a-c1a86e9fc018.png)

**Comment by acostarodrigo** [comment]
Cambiar la opción del menu Administrate Group por Manage Group.

Vamos a estar sacando la leyenda que dice Crypto Address: No, porque eso es de uso interno y el usuario final no lo va a entender, @nindriago  está trabajando para cambiar el status de conexion que estamos mostrando. 

En cuanto esté listo les enviamos un screenshot.

**Comment by emmysm** [comment]
![asset user community draw-01](https://cloud.githubusercontent.com/assets/15143489/12902070/0c7a78d2-ce91-11e5-87d7-fbcdc33dd8d3.png)

Lo había pasado por alto, @acostarodrigo, aca los ajustes

**Comment by emmysm** [comment]
Asset user wallet propuestas - @Luis-Fernando-Molina @arnaldos @nindriago @acostarodrigo 

![asset user community modificaciones - copia-03](https://cloud.githubusercontent.com/assets/15143489/12936754/cedb71be-cf73-11e5-8770-d566c626d674.png)
![asset user community modificaciones - copia-01](https://cloud.githubusercontent.com/assets/15143489/12936755/cedee52e-cf73-11e5-802a-3cbcf04cfde7.png)
![asset user community modificaciones - copia-02](https://cloud.githubusercontent.com/assets/15143489/12936756/cee0f44a-cf73-11e5-90ab-e1a27d625b09.png)

**Comment by acostarodrigo** [comment]
@emmysm Hola Emmy, estamos haciendo un cambio importante a la user Wallet que seguramente luego replicaremos en el resto de las wallets. Lo va a estar haciendo @javafrank 

Vamos a quitar las acciones actuales (Reedem Asset y appropriate Asset) y las nuevas (Transfer Asset y Sell Asset) a un menú de opciones, y vamos a mostrar las transacciones que ocurren en la wallet, en una tabla nueva.

Luego que tengamos listos los cambios, te voy a pedir que nos ayudes a realizar cualquier corrección o mejora sobre estos cambios tambien.

cc @nindriago

**Comment by emmysm** [comment]
Excelente, @acostarodrigo, estaré atenta a los cambios y modificaciones que me indicas. Saludos :)

**Comment by emmysm** [comment]
![asset user wallet](https://cloud.githubusercontent.com/assets/15143489/12996047/74cf762a-d0fe-11e5-8a47-68f6905bd94c.png)

Hola, @acostarodrigo aca te dejo unos ajustes que hice al diseño de las vistas.

**Comment by yojoaquin** [comment]
@acostarodrigo o @javafrank buenas, tenemos documentación del scope de la wallet con todo esto? (1) me gustaría repasar con @emmysm los docs y hacer los mockups para rever la UX y la UI. Hay dimensiones que no están buenas para hacer "tap". El botón de atrás en android no tiene sentido pues es un botón físico en el device.
Los busco por skype y charlamos!

(1) edit: pregunto esto porque sino Emmy trabaja una y otra vez sobre cosas que no van a ver la luz y podríamos aprovechar su tiempo en otra cosa.

**Comment by acostarodrigo** [comment]
@yojoaquin @emmysm juntemonos a las 10AM de Venezuela.
Me agregan por skype asi les paso el link. Mi id es acosta_rodrigo

**Comment by yojoaquin** [comment]
A las 2:30 PM de Venezuela porfa.
