### ISSUE TITLE
Composición artística Nº4 con la moneda 3D Fiat Dollar

### ISSUE THREAD

**Issue by DexybelVillanueva** [bitDubai/fermat-graphic-design#513]
Viene del #182 
(Por desarrollar)

**Comment by jonathanborges3d** [comment]
@DexybelVillanueva Pudiese ser algo cómo ésto:

![](https://ras-servers.com/media/ayuda_monedas.jpg)

pero con una relación de aspecto 16:9 (formato full hd).

**Comment by DexybelVillanueva** [comment]
Prueba con Motor de Render ( Keyshot)

![dollar 20](https://cloud.githubusercontent.com/assets/16962860/12734382/45042808-c912-11e5-8595-94b92608b93c.jpg)

![untitled 35](https://cloud.githubusercontent.com/assets/16962860/12734410/899222cc-c912-11e5-9e5f-53d944d2695a.jpg)

**Comment by DexybelVillanueva** [comment]
![untitled 33](https://cloud.githubusercontent.com/assets/16962860/12734452/dc9d5b62-c912-11e5-8eed-e48633e4be67.jpg)

![untitled 39](https://cloud.githubusercontent.com/assets/16962860/12734504/297678ba-c913-11e5-80f3-566d2a6125dc.jpg)

![untitled 12](https://cloud.githubusercontent.com/assets/16962860/12734561/914b281e-c913-11e5-831b-9214192368c9.jpg)

**Comment by jonathanborges3d** [comment]
@DexybelVillanueva Creo que puede mejorar el resultado, aplica una iluminación basada en un envmap, en el repositorio está el .hdr que he usado en otras escenas. Tal vez eso ayude a cambiar un poco el aspecto plástico que tiene el material para el oro en el logo de Fermat.

@Luis-Fernando-Molina Se está tratando de igualar la calidad de éste render con la de los aprobados en otras escenas. Qué opinas de éste motor?

**Comment by Luis-Fernando-Molina** [comment]
Me imagino que puede andar cuando se le ponga el material al fondo y otras cosas que le falta, pero la verdad no lo se.

**Comment by DexybelVillanueva** [comment]
@jonathanborges3d ya utilize la iluminación basada en el envmap, que te parece ahora?, también aplique la rugosidad y opacidad en los materiales y sombra,  para un toque mas realista como me habías recomendado.

![dollar prueba 1 62](https://cloud.githubusercontent.com/assets/16962860/12751611/3fa62a68-c990-11e5-928a-bee6a2bce3fe.jpg)

![dollar prueba 1 66](https://cloud.githubusercontent.com/assets/16962860/12751627/4feeea9a-c990-11e5-888a-709a1b79612b.jpg)

![dollar prueba 1 71](https://cloud.githubusercontent.com/assets/16962860/12751636/5e5aede0-c990-11e5-9bd1-94dbf2ebaf0c.jpg)

**Comment by DexybelVillanueva** [comment]
![monedas agrupadas 78](https://cloud.githubusercontent.com/assets/16962860/12796259/0cf9a22e-ca90-11e5-95a5-aaff2b041e5d.jpg)

![monedas agrupadas 74](https://cloud.githubusercontent.com/assets/16962860/12796320/5d0c3fd8-ca90-11e5-937d-3b69d12b3869.jpg)

![monedas agrupadas 75](https://cloud.githubusercontent.com/assets/16962860/12796321/5d13f4d0-ca90-11e5-893f-4ae1ad49b9f8.jpg)

![monedas agrupadas 77](https://cloud.githubusercontent.com/assets/16962860/12796322/5d198422-ca90-11e5-9c93-af6ce0dcf347.jpg)
![monedas agrupadas 82](https://cloud.githubusercontent.com/assets/16962860/12796323/5d1bd524-ca90-11e5-95d9-4d3c23fa2753.jpg)

![monedas agrupadas 84](https://cloud.githubusercontent.com/assets/16962860/12796324/5d254aa0-ca90-11e5-98cb-ae05ca2007ee.jpg)

![monedas agrupadas 86](https://cloud.githubusercontent.com/assets/16962860/12796325/5d291bda-ca90-11e5-8d21-d9248e9ede9b.jpg)
![monedas agrupadas 87](https://cloud.githubusercontent.com/assets/16962860/12796327/5d35b750-ca90-11e5-9e2f-c5bb8f7eb32a.jpg)

![monedas agrupadas 88](https://cloud.githubusercontent.com/assets/16962860/12796328/5d3cf68c-ca90-11e5-8ee2-292bf5dabdd5.jpg)

![monedas agrupadas 89](https://cloud.githubusercontent.com/assets/16962860/12796329/5d41dcb0-ca90-11e5-8263-3c6c070adca7.jpg)

![monedas agrupadas 93](https://cloud.githubusercontent.com/assets/16962860/12796330/5d438b46-ca90-11e5-91a0-e6ada188866d.jpg)

**Comment by jonathanborges3d** [comment]
@DexybelVillanueva Algunas observaciones: El material de plata que está bajo la estatua debe ser brillante, similar al del fondo punteado que tiene el reverso pero sin relieve.

Vamos a usar un material reflectivo para el piso como el que tiene actualmente pero que sea blanco, similar al efecto que tienen otras escenas de éste tipo.

Los renders 2, 5, 10 y 11 (los que dejan ver claramente la moneda y la pila sin dejar ninguna) están bien para ésta escena.

**Comment by jonathanborges3d** [comment]
Aumenta un poco la claridad del material del puente, se nota más oscuro que el anterior. 

No sé si me engaña la posición y el ángulo de la cámara pero me parece que hay monedas más grandes que otras, de ser así corrige el tamaño para que sean todas iguales por favor.

**Comment by DexybelVillanueva** [comment]
@jonathanborges3d Listo,ya le hice los cambios, ahora que te parece?

![monedas agrupadas 104](https://cloud.githubusercontent.com/assets/16962860/12801060/d23fdfd8-caab-11e5-829e-776637738bad.jpg)
![monedas agrupadas 105](https://cloud.githubusercontent.com/assets/16962860/12801061/d24480ec-caab-11e5-8080-a930a482f859.jpg)
![monedas agrupadas 107](https://cloud.githubusercontent.com/assets/16962860/12801062/d249f946-caab-11e5-964c-50a05a92a1ab.jpg)

![monedas agrupadas 108](https://cloud.githubusercontent.com/assets/16962860/12801063/d25210a4-caab-11e5-85d1-d657beafa2ca.jpg)

![monedas agrupadas 110](https://cloud.githubusercontent.com/assets/16962860/12801064/d25814fe-caab-11e5-9295-895648ce54e8.jpg)

![monedas agrupadas 111](https://cloud.githubusercontent.com/assets/16962860/12801065/d25e6e3a-caab-11e5-9548-43b4c4787ae6.jpg)

![monedas agrupadas 113](https://cloud.githubusercontent.com/assets/16962860/12801066/d2710c02-caab-11e5-89d1-6725bd3ab27e.jpg)

![monedas agrupadas 116](https://cloud.githubusercontent.com/assets/16962860/12801067/d275fc12-caab-11e5-8300-9e675240223b.jpg)

![monedas agrupadas 121](https://cloud.githubusercontent.com/assets/16962860/12801244/46b981b0-caad-11e5-9b5f-c5f748c1c897.jpg)

**Comment by DexybelVillanueva** [comment]
1) ![monedas con los materiales listo 158](https://cloud.githubusercontent.com/assets/16962860/12849704/392870aa-cbf3-11e5-9403-49cf685d4156.jpg)

**Comment by DexybelVillanueva** [comment]
2) ![monedas con los materiales listo 159](https://cloud.githubusercontent.com/assets/16962860/12849779/99a7228c-cbf3-11e5-82f3-1c6cd9a9f8f4.jpg)

**Comment by DexybelVillanueva** [comment]
3) ![monedas con los materiales listo 160](https://cloud.githubusercontent.com/assets/16962860/12849828/dd4e797c-cbf3-11e5-9d49-3ca8d1225fb2.jpg)

4) ![monedas con los materiales listo 161](https://cloud.githubusercontent.com/assets/16962860/12849829/dd52c14e-cbf3-11e5-892b-ed1804740bda.jpg)

**Comment by jonathanborges3d** [comment]
@DexybelVillanueva Versión 2  :+1:

**Comment by Luis-Fernando-Molina** [comment]
gira la moneda mas cercana por favor para que el puente se vea derecho. gracias

**Comment by DexybelVillanueva** [comment]
1)![monedas con los materiales listo 164](https://cloud.githubusercontent.com/assets/16962860/12859098/23e04b4a-cc26-11e5-9048-015e5dde0592.jpg)

2)![monedas con los materiales listo 165](https://cloud.githubusercontent.com/assets/16962860/12859099/23e54e38-cc26-11e5-9c01-f5efeb30c6ab.jpg)

**Comment by Luis-Fernando-Molina** [comment]
genial :+1:

**Comment by DexybelVillanueva** [comment]
Graciass! :)

**Comment by DexybelVillanueva** [comment]
Cambio de Motor de Keyshot a Fryrender

![dollar](https://cloud.githubusercontent.com/assets/16962860/13336032/1d9a0a80-dbe6-11e5-8a2d-659e90534b71.jpg)

**Comment by jonathanborges3d** [comment]
:+1: Listo.
