### ISSUE TITLE
Money selector custom view

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#519]
viene del caso https://github.com/bitDubai/fermat/issues/4636

**Comment by arnaldos** [comment]
@furszy te comparto una primera versión 

![money-selector](https://cloud.githubusercontent.com/assets/13594347/12793088/f8383b02-ca80-11e5-9993-5fd9a84ffe41.png)

**Comment by furszy** [comment]
Ok, dos cosas:
 el usuario puede editar el número ahí no?
Yo lo haría con menos puntos y lo hacemos con un swipe hacia los costados para cambiar de moneda.
El único tema que te digo que hay que pensar es la facilidad de uso, porque si quiero ir de una moneda a otra y tengo 40 monedas en la lista, a nadie le gustaría estar haciendo swipe por mucho tiempo. Tiene que ser fácil y rápido de usar.

**Comment by arnaldos** [comment]
si el usuario puede editar dejame sumarle otras vistas mas para mostrar de manera mas completa las funciones

**Comment by arnaldos** [comment]
@furszy  @Luis-Fernando-Molina versiones para el Money selector

Versión 1
![1](https://cloud.githubusercontent.com/assets/13594347/12799123/5be98aac-ca9f-11e5-8acd-1dced699c006.jpg)

---

Versión 2
![2](https://cloud.githubusercontent.com/assets/13594347/12799121/5bdcf116-ca9f-11e5-8cc4-8bcc64d13980.jpg)

---

Versión 3
![3](https://cloud.githubusercontent.com/assets/13594347/12799122/5be75a5c-ca9f-11e5-878d-4836a263766b.jpg)

**Comment by furszy** [comment]
Pueden ser varios template distintos,están buenos todos. Lo que habría que ver es el uso más sencillo, al segundo lo veo bueno pero si quiero agregar más monedas nos queda corto, al primero lo veo más preparado para aguantar varias monedas con un swipe, por más que sea tedioso el programador va a decidir cuales son los 5 básicos y después cuales están ocultos y se muestran con el swipe.

**Comment by Luis-Fernando-Molina** [comment]
@yojoaquin revisa esto please.

**Comment by arnaldos** [comment]
este caso ya esta implementado quedo la Versión 1
