### ISSUE TITLE
Modelo 3D Tatiana Coin

### ISSUE THREAD

**Issue by jonathanborges3d** [bitDubai/fermat-graphic-design#520]
Primera versión:

![tatiana_coin_1](https://cloud.githubusercontent.com/assets/13649739/12801053/c9a89266-caab-11e5-9562-f0c9e52dabe6.jpg)

@TatianaMoroz 
@Luis-Fernando-Molina

**Comment by TatianaMoroz** [comment]
Wow it looks so FANCY!  :)Tatiana MorozFounder & CEO (917) 832-2014Tatiana@CryptoMediaHub.comwww.CryptoMediaHub.com@CryptoMediaHubwww.TatianaMoroz.com@QueenTatiana

-------- Original Message --------
Subject: [fermat-graphic-design] Modelo 3D Tatiana Coin (#520)

**Comment by Luis-Fernando-Molina** [comment]
@TatianaMoroz please follow up this stuff yourself. 

I would probably not put such a long text below.

**Comment by TatianaMoroz** [comment]
I did follow up myself, and I don't know what the standards are for the bottom part, it doesn't have to be there

**Comment by Luis-Fernando-Molina** [comment]
just suggest Jonathan changes and he will be happy to apply them

**Comment by TatianaMoroz** [comment]
I just don't know what changes to suggest :/ I think it looks ok, maybe the bottom part shouldn't be there, I have no idea... ? I'll look again on the way to the city

**Comment by jonathanborges3d** [comment]
Hi @TatianaMoroz Some changes to apply in this model? :smile: Thank you!

**Comment by TatianaMoroz** [comment]
Hi :)  I don't see it anywhere?Tatiana MorozFounder & CEO (917) 832-2014Tatiana@CryptoMediaHub.comwww.CryptoMediaHub.com@CryptoMediaHubwww.TatianaMoroz.com@QueenTatiana

-------- Original Message --------
Subject: Re: [fermat-graphic-design] Modelo 3D Tatiana Coin (#520)

**Comment by jonathanborges3d** [comment]
Sorry, I mean the first version:

![tatiana_coin_1](https://cloud.githubusercontent.com/assets/13649739/12801053/c9a89266-caab-11e5-9562-f0c9e52dabe6.jpg)

**Comment by jonathanborges3d** [comment]
@TatianaMoroz Hi! Do you have any modfication for this coin model? Where you need to place it?

![tatiana_coin_1](https://cloud.githubusercontent.com/assets/13649739/12801053/c9a89266-caab-11e5-9562-f0c9e52dabe6.jpg)

**Comment by TatianaMoroz** [comment]
Hi Jonathan,This looks great thanks, but can we take the silhouette off of it?  I think that will be better.  And also take off the word musical and we can see how it looks then?Thank you!TatianaTatiana MorozFounder & CEO (917) 832-2014Tatiana@CryptoMediaHub.comwww.CryptoMediaHub.com@CryptoMediaHubwww.TatianaMoroz.com@QueenTatiana

-------- Original Message --------
Subject: Re: [Fermat-ORG/fermat-graphic-design] Modelo 3D Tatiana Coin
(#520)

**Comment by TatianaMoroz** [comment]
Hey what happened to the one you were supposed to redo without the silhouette behind the logo?Thanks!TatianaTatiana MorozFounder & CEO (917) 832-2014Tatiana@CryptoMediaHub.comwww.CryptoMediaHub.com@CryptoMediaHubwww.TatianaMoroz.com@QueenTatiana

-------- Original Message --------
Subject: Re: [Fermat-ORG/fermat-graphic-design] Modelo 3D Tatiana Coin
(#520)
