### ISSUE TITLE
Composición artística Nº3 con la moneda 3D  Euro_Hungría

### ISSUE THREAD

**Issue by DexybelVillanueva** [bitDubai/fermat-graphic-design#521]
viene de #182

**Comment by DexybelVillanueva** [comment]
,

**Comment by DexybelVillanueva** [comment]
Monedas cayendo con diferente iluminación

1) ![monedas cayendo](https://cloud.githubusercontent.com/assets/16962860/13362826/861c47dc-dc98-11e5-987c-eb9290875c01.jpg)

2)![monedas2](https://cloud.githubusercontent.com/assets/16962860/13362827/8633ac10-dc98-11e5-8d1b-56c0a7e04993.jpg)

**Comment by DexybelVillanueva** [comment]
1)![monecaye3](https://cloud.githubusercontent.com/assets/16962860/13394259/73c4703c-deb9-11e5-867a-7c1d7c43cea6.jpg)
2)![monecaye5](https://cloud.githubusercontent.com/assets/16962860/13394260/73cb0956-deb9-11e5-90dc-a9119149b859.jpg)

**Comment by DexybelVillanueva** [comment]
Render en  alta resolución 1920x1080

![monedas cayendo alta resolución 2](https://cloud.githubusercontent.com/assets/16962860/13414240/3c78fca0-df23-11e5-9fc1-fcdef642dc67.jpg)

**Comment by jonathanborges3d** [comment]
:+1: 

@Luis-Fernando-Molina Qué te parece ésta última?
