### ISSUE TITLE
Composición artística Nº3 con la moneda 3D Fiat Libra

### ISSUE THREAD

**Issue by DexybelVillanueva** [bitDubai/fermat-graphic-design#522]
viene de #182

**Comment by DexybelVillanueva** [comment]
@jonathanborges3d 

![image](https://cloud.githubusercontent.com/assets/16962860/13209400/9968d950-d8f5-11e5-9d8e-58b56df7d4c0.png)

**Comment by DexybelVillanueva** [comment]
.

**Comment by jonathanborges3d** [comment]
@DexybelVillanueva  Ok. Algunas observaciones:

1) A simple vista pareciera no tener nada que ver con lo que es Fermat. Tal vez si explicas un poco cuál es la relación que ves entre el reloj de arena, las monedas y Fermat podríamos mejorar el concepto pero hasta ahora me cuesta un poco relacionarlo. La imagen que posteaste de referencia para el reloj parece indicar la conversión de las monedas en billetes a lo largo del tiempo, tal vez el artista quiso representar la inflación, no se.

2) Este tipo de escenas dónde los objetos colisionan hay que estar pendientes de que la física sea lo más real posible. Me parece ver monedas en posiciones imposibles. Si estas usando una simulación para ubicarlas dale tiempo a que todo termine de "caer" donde debe, a veces se debe avanzar en la línea de tiempo hasta unos 1000 o 1500 frames para ver el resultado final y renderizar (o exportar) los objetos en ésa posición.

3) La forma del cuello del reloj de arena debería ser más suave, como el cuello de una copa, no importa que uses muchos más polígonos en esa zona, pero que el resultado se vea menos angular y más suavizado. Actualmente recuerdan dos matraces de laboratorio.

4) Revisa el material del puente en la moneda, me parece que está en blanco en la primera y última  imagen, debe ser la plata un poco más oscura y opaca, como el puente de la moneda de Dollar.

Intentemos un render de la primera propuesta que hiciste en éste caso por favor, las monedas cayendo, creo que será más sencillo y de objetivo simple: mostrar la moneda. 

Luego vemos si procede el del reloj de arena dependiendo el feedback que tengamos.

**Comment by arnaldos** [comment]
@DexybelVillanueva @jonathanborges3d una acotación, si para esta escena están trabajando en 3D max podrían probar usar técnicas de HDRI para obtener mayor realismo en los materiales, esto ayuda mucho en los reflejos del vidrio cuando no tienes nada al rededor del objeto principal. :smile:

**Comment by DexybelVillanueva** [comment]
.

**Comment by Luis-Fernando-Molina** [comment]
Porque las monedas de la primera imagen parecen mas de oro que las nuestras? Me gustaria que las nuestras parezcan mas de oro que la primera imagen. Podemos mejorar eso?

**Comment by DexybelVillanueva** [comment]
@jonathanborges3d  nuevas propuestas

![camino 4](https://cloud.githubusercontent.com/assets/16962860/13222623/fdd03458-d952-11e5-8412-036f27764795.jpg)
![camino de monedas 1](https://cloud.githubusercontent.com/assets/16962860/13222624/fdd4bc58-d952-11e5-8fdb-0e2685d089df.jpg)
![camino de monedas 3](https://cloud.githubusercontent.com/assets/16962860/13222625/fddb186e-d952-11e5-9308-66ce1353c913.jpg)

**Comment by jonathanborges3d** [comment]
@DexybelVillanueva La 2ª va bien, pero todavía tenemos algunos detalles que mejorar para que quede lista: 
- Aumenta un poco la intensidad de la luz. Sólo un poco para generar algunos puntos más brillantes.
- Probemos con un poco más de rugosidad en el material del piso, para que el efecto de reflexión se vea un poco más difuminado.
- ¿Podremos tener algo de efecto de profundidad de campo como en la imagen referencial? intenta jugar con los valores de la cámara.

**Comment by DexybelVillanueva** [comment]
@jonathanborges3d listo, ya realize las modificaciones ahora que le parece?

![camino1](https://cloud.githubusercontent.com/assets/16962860/13265789/0fe94dc4-da47-11e5-864f-aaaa9d900229.jpg)

**Comment by jonathanborges3d** [comment]
:+1: Ya puedes hacer el render final en HD por favor. Gracias.

**Comment by DexybelVillanueva** [comment]
Listo render en alta resolución

![camino de monedas alta resolucion](https://cloud.githubusercontent.com/assets/16962860/13271295/4e34894e-da66-11e5-8c68-d7016fe0af2f.jpg)
