### ISSUE TITLE
Generar mejoras gráficas para la App Chat fermat 

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#525]

**Comment by arnaldos** [comment]
@darkestpriest @acostarodrigo @franklinmarcano1970 les comparto las mejoras visuales del chat fermat. espero sus comentarios 

![2](https://cloud.githubusercontent.com/assets/13594347/12828048/c0fe4792-cb54-11e5-9cfc-b162b3ad6ece.png)

---

![1](https://cloud.githubusercontent.com/assets/13594347/12828051/c3e9fd20-cb54-11e5-8e37-71017f9530c6.png)

**Comment by acostarodrigo** [comment]
cc @furszy que tenemos hecho de esto que podamos reutilizar?

yo la veo muy bien. @franklinmarcano1970  y @darkestpriest qué les parece? esta faltando alguna pantalla?

**Comment by furszy** [comment]
@acostarodrigo Tienen la pantalla del chat hecha, van a tener que customizarla a su medida para que quede igual que esa. lo básico ya está implementado como libreria https://github.com/bitDubai/fermat/issues/4670
PD: si, necesito UX conmigo urgente

**Comment by Luis-Fernando-Molina** [comment]
> PD: si, necesito UX conmigo urgente 

Estas buscando? 

@yojoaquin te puede ayudar en ux y ademas a conseguir gente para un equipo de ux

**Comment by Luis-Fernando-Molina** [comment]
@arnaldos en esta caso la consigna no era innovar en la interfaz gráfica sino hacer whatsapp over fermat, usando el criterio de diseño de que la gente quiere aprovechar lo que ya conoce, y todo el mundo conoce whatsapp.

En ese sentido fijate de alinearte a eso en este reference APP.  Luego otros sacaran variantes con otras interfaces.

@arnaldos veo que estas introducionendo funcionalidades que no estaban previstas como poner el estado en la lista de contactos. Este tipo de cosas parecen una tonteria pero involucran todo una serie de cosas. Whatsapp no lo hace porque entre otras cosas tendria que ir a cada usuario a ver cual es su estado en ese momento, cosa que lo hace cuando uno entra al chat de ese contacto. Por favor en este caso no te desvies de la consigna, ademas el equipo CHT se va a avaluar de acuerdo con ella.

**Comment by Luis-Fernando-Molina** [comment]
Si en este caso replicaramos whatsapp dentro de fermat estariamos bien. Lo unico que yo le cambiaria seria el fondo de pantalla en la ventana de chat y haria unos dibujitos propios de fermat en vez de capturar los de whatsapp. El resto lo haria todo igual y lo venderia como un whatsapp p2p. Obviamente en nuestra primera version seria un whasapp sin mensajes de audio ni llamadas, ni muchas otras cosas, pero el resto lo haria igual. No necesitamos en este caso en invertir recursos, cabeza ni tiempo en definir UX. Todo el mundo lo usa, todo el mundo lo conoce y esta super estudiado porque es así.

**Comment by franklinmarcano1970** [comment]
@GaboHub @josejcb @lostwood  A mi parece bien.

**Comment by darkestpriest** [comment]
Estoy de acuerdo con @franklinmarcano1970 me parecen bastante bien.

**Comment by arnaldos** [comment]
perfecto luis !!! ya me pongo a generar otras vistas siguiendo las sugerencias !!

**Comment by arnaldos** [comment]
@acostarodrigo @darkestpriest @furszy @Luis-Fernando-Molina nuevo ajuste del chat fermat

## ![1](https://cloud.githubusercontent.com/assets/13594347/12906106/42c1c102-ceaf-11e5-8e2e-d031ebc80bda.png)

![2](https://cloud.githubusercontent.com/assets/13594347/12906107/42c6b342-ceaf-11e5-94ce-b9c9044a2960.png)

**Comment by franklinmarcano1970** [comment]
Excelente...

**Comment by darkestpriest** [comment]
Gran trabajo @arnaldos :+1:

**Comment by Luis-Fernando-Molina** [comment]
Mis observaciones. 

1) en los tabs chat debe ir a la iz y contacts a la derecha
2) ponele color verde a la app no rojo
3) el fondo de la pantalla de chat:
a) lo que uno escribe va a la derecha con color de fondo
b) lo que escribe el otro a la izquierda sobre fondo blanco
c) los dibujitos deben ser mas chiquitos, mas variados y notarse menos.
d) el logo del medio mas chico, sin superponerse con los dibujitos, y del mismo todo
4) No veo para que TYPE MESSAGE en el perfil de alguien

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina @acostarodrigo @darkestpriest @franklinmarcano1970 Ajustes solicitados de fermat chat, para el nombre de la app le coloque messenger fermat como propuesta de nombre. puedo colocar el nombre inical **(fermat chat)** si es requerido. adjunto logo. 

**Color del logo ajustado:**

![fermat_chat_app_version2-09](https://cloud.githubusercontent.com/assets/13594347/12954305/27b82c10-cff0-11e5-8b93-977547ca1a36.jpg)

**Secuencias de vistas**

## ![fermat_chat_app_version2-11](https://cloud.githubusercontent.com/assets/13594347/12954274/061d33c0-cff0-11e5-95b7-79620d9bd3e3.jpg)

![fermat_chat_app_version2-12](https://cloud.githubusercontent.com/assets/13594347/12954275/063360d2-cff0-11e5-98d8-090ae541c965.jpg)

**Comment by Luis-Fernando-Molina** [comment]
algunas cosas estan otras no como por ejemplo:

El logo de fermat mezclado entre los dibujitos debiera ser mas chico y no superponerse con los debujitos de abajo, tampoco la palabra Fermat, los dibujitos deben rodearla integrandose a de manera cool.

El resto se ve bastante bien, salvo el menu contextual donde dice "delete messages" se ve muy primitivo.

Los colores de las burbujas de texto y el color del texto ponelos como wahtsaspp, letras negras sobre blanco y negras sobre verde.

gracias

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina @acostarodrigo @darkestpriest @franklinmarcano1970 
comparto los ajustes solicitados:

## ![fermat_chat_app_version3](https://cloud.githubusercontent.com/assets/13594347/12997371/d50506fc-d10a-11e5-8f47-a5a6b767c828.png)

![fermat_chat_app_version31](https://cloud.githubusercontent.com/assets/13594347/12997441/69dcc1ac-d10b-11e5-8935-462849af640b.png)

**Comment by franklinmarcano1970** [comment]
Por mi parte se ven bien...

**Comment by lostwood** [comment]
Burnas tardes una cosa que dijo luis fue las burbujas fondo blanco texto negro y la otra fondo verde texto negro como whatsapp
On Fri, Feb 12, 2016 at 11:48 AM, Franklin Marcano <notifications@github.com<mailto:notifications@github.com>> wrote:

Por mi parte se ven bien...

**Comment by arnaldos** [comment]
100% negro ? creo que rebajando el % del negro se ve mejor y hace mejor contraste con la paleta de colores que estamos manejando, ya les comparto con las letras totalmente negras y asi toman una decisión. :smile:

**Comment by arnaldos** [comment]
@lostwood @darkestpriest @franklinmarcano1970 @acostarodrigo  aquí les comparto la versión con las burbujas en blanco y verdes y texto negro.

![fermat_chat_app_version32](https://cloud.githubusercontent.com/assets/13594347/13015149/b81e2f30-d189-11e5-9df9-e3e0e497f0eb.png)

**Comment by lostwood** [comment]
Bueno en lo particular me parece mejor visualmente la del fondo blando hice una mini encuesta con otras personas y opinan igual
On Fri, Feb 12, 2016 at 1:08 PM, Arnaldo Santamaria <notifications@github.com<mailto:notifications@github.com>> wrote:

@lostwoodhttps://github.com/lostwood @darkestpriesthttps://github.com/darkestpriest @franklinmarcano1970https://github.com/franklinmarcano1970 @acostarodrigohttps://github.com/acostarodrigo aquí les comparto la versión con las burbujas en blanco y verdes y texto negro.

A nivel cromático propongo la versión de las burbujas grises y verde con texto en negro rebajado al 60%.

[fermat_chat_app_version32]https://cloud.githubusercontent.com/assets/13594347/13015025/f2316af8-d188-11e5-843c-49db5741a11e.png

**Comment by Luis-Fernando-Molina** [comment]
Hey! esta quedando pro!

**Comment by Luis-Fernando-Molina** [comment]
La letra de CHAT Y CONTACTS me parece que esta muy oscura @arnaldos 

Proba ponerle una sombre al action bar (title bar) que caiga sobre los dibujitos

**Comment by josejcb** [comment]
@arnaldos mientras afinas esto último, podes ir pasandonos los códigos d colores, los recursos y demás para ir nosotros montando esto. Gracias.

**Comment by arnaldos** [comment]
ya se están generando los resources

**Comment by arnaldos** [comment]
los ajustes solicitados 
- Texto CHAT y CONTACTS 
- Sombra del actions bar arrojada hacia el background

## ![fermat_chat_app_views1](https://cloud.githubusercontent.com/assets/13594347/13096053/6728a0e4-d4e8-11e5-864b-ac90d9a0e9b4.png)

![fermat_chat_app_views2](https://cloud.githubusercontent.com/assets/13594347/13096054/672d3262-d4e8-11e5-89b0-bd506bc63323.png)

**Comment by yojoaquin** [comment]
Qué font estamos usando @arnaldos ? Por qué no usamos la de Whatsapp que tiene un espaciado muy bueno y es legible: Helvetica Neue. Confío que quedaría mejor.
Otra cosa, le daría más aire entre la flecha de atrás y la foto del avatar así no hay conflicto con los fat-fingers.
En lugar del delineado de las chat bubbles probemos una sobra muy finita alrededor de estas.
En la lista de chats subiría el nombre un poco y dejaría los últimos x caracteres del chat con esa persona así le brindamos contexto al usuario.

**Comment by arnaldos** [comment]
@yojoaquin la tipografía que estamos usando es Roboto, ya la cambio por Helvetica Neue.
Cuando hablas de flecha asumo es el boton de back.
Las chat bubbles tienen una sombra, voy ajustar eso para que no se ven como de lineado.

ya genero todos estos cambios y los subo

**Comment by arnaldos** [comment]
@yojoaquin listos los ajustes incluyendo los del color conversados previamente 

![fermat_chat_app_views_2 1](https://cloud.githubusercontent.com/assets/13594347/13114600/5212696e-d566-11e5-89eb-428e18cda596.png)

---

![fermat_chat_app_views_2 2](https://cloud.githubusercontent.com/assets/13594347/13114599/520f888e-d566-11e5-9e54-0137767db4f7.png)

**Comment by arnaldos** [comment]
@yojoaquin plz avísame si ya esta todo ok para generar los resources y pasarlos para que los implementen ..

**Comment by yojoaquin** [comment]
Mis comentarios finales:
- En la tab de chats debería aparecer una línea del último chat con esa persona.
- El nombre alineado con el border superior del avatar y en negrito y la hora alineada tb a esa altura
- Ajusta la sobra de las bubbles a que sea un poco más sólida y que no parezca taan flotante
- La hora del mensaje hacela un poco más clara, que no tenga el mismo tono del texto porque es info secundaria
- Las tabs Chat y Contact capitalizalas (primera letra en mayúscula). Fijate que tenés un typo en la tab de Contacts, dice "contacs".
- La flecha para atrás en Fermat Chat a dónde va? Si no va a ningún lado eliminala, caso contrario dale más aire
- Cómo se accede a Profile? Desde el submenu de Fermat Chat imagino. Dale más aire a esa flecha tb. 
- Hay mucho verde, quitale el reborde a la foto del perfil.
- En lugar de "user name" debería ser "Type Your Name Here"

**Comment by franklinmarcano1970** [comment]
@lostwood @josejcb Pendiente con las recomendaciones, para ver si se pueden ir implementando, de @yojoaquin

**Comment by josejcb** [comment]
Chat ahora mismo no tiene perfil del usuario local, pero si perfil de cada
contacto. Seria mas bien 'Type Alias Here', dado que solo podemos modificar
esto al usuario en nuestra lista de contactos.

Casualmente iba a comentar hace unos dias lo de las letras mayusculas en
los Tabs, en la implementacion lo probamos asi y se ve mucho mejor.

**Comment by arnaldos** [comment]
Comparto los últimos ajustes @yojoaquin @franklinmarcano1970 @darkestpriest 

## ![fermat_chat_app_views_3](https://cloud.githubusercontent.com/assets/13594347/13259878/76320434-da2b-11e5-8127-2f3cdcd77938.png)

![fermat_chat_app_views_31](https://cloud.githubusercontent.com/assets/13594347/13259879/765606a4-da2b-11e5-81ec-8423b0c95395.png)

**Comment by arnaldos** [comment]
los resources están en esta carpeta https://github.com/Fermat-ORG/fermat-graphic-design/tree/master/2D%20Design/Apps/fermat%20chat

**Comment by yojoaquin** [comment]
Divino

**Comment by Luis-Fernando-Molina** [comment]
:+1: Procedan a aplicar esto por favor a ver si podemos verlo andando.

**Comment by franklinmarcano1970** [comment]
@lostwood @josejcb procedan a llevar esos recursos a los disenos.

**Comment by josejcb** [comment]
Saludos, revisando los recursos noté que faltan los fondos de los mensajes individuales (propios y del contacto), adjunto los que tenemos ahora para que tengan una idea de la necesidad, y se hagan los del diseño utlizando estas medidas.
![in_message_bg 9](https://cloud.githubusercontent.com/assets/7374940/13262587/dd536264-da37-11e5-8525-1ecb4249d681.png)
![out_message_bg 9](https://cloud.githubusercontent.com/assets/7374940/13262588/dd55e3ea-da37-11e5-8139-616d27e165b5.png)
Adicionalmente, no veo en el diseño los ticks de estatus de mensaje, los de que cuando envias un mensaje te dice si fue enviado, entregado o leido, ahora mismo utilizamos estos, que entre si no se parecen y son de tamaños diferentes:
![tickdelivered](https://cloud.githubusercontent.com/assets/7374940/13262683/395c5eda-da38-11e5-975f-0631b8c3cd01.png)
![tickread](https://cloud.githubusercontent.com/assets/7374940/13262684/3962403e-da38-11e5-8308-50ae7ab75943.png)
![ticksent](https://cloud.githubusercontent.com/assets/7374940/13262685/39688b24-da38-11e5-9069-f7f53522840f.png)
@arnaldos @darkestpriest @franklinmarcano1970

**Comment by arnaldos** [comment]
@josejcb perfecto que medidas exactamente se deben colocar las burbujas ? veo que estan usando las imágenes 9patch, dame las medidas para generar te los recursos que faltan. Los check status no pence que se mostrarían en una primera versión por eso no los coloque pero ya genero ese recurso también.

**Comment by josejcb** [comment]
@arnaldos no se sacar esas medidas, subí las imágenes para que se guien. Si estas no sirven, bajalas de acá, están las mismas 5 imágenes [drawable cht josejcb](https://github.com/josejcb/fermat/tree/develop/CHT/android/sub_app/fermat-cht-android-sub-app-chat-bitdubai/src/main/res/drawable). Otra cosa, al colocar las imágenes no cuadraron como en el diseño y se ven más grandes, no se si pueden darle más aire alrededor a las imágenes relacionadas con el toolbar y botones, en específico al ok y al send buttom. En este link dan una idea de lo que comento [icon size in android stackoverflow](http://stackoverflow.com/questions/11244918/action-bar-icon-size). El ícono de back sería seguir lo que dice el link, que sea cuadrado el png, pero el símbolo, en vez de dejarlo centrado, lo pegas a la izquierda. Así quedaría el símbolo lo bastante pegado al borde como en el diseño.

**Comment by arnaldos** [comment]
de cuanto estas usando el padding ? eso puede estar influyendo.

**Comment by arnaldos** [comment]
acabo de revisar el icono del action bar y el padding debe ser de 24 dp y el contenido interno "el icono" de 17,77 dp. si colocas la imagen directamente a 24 dp se vera mas grande. ahora yo coloque los iconos al tamaño del contenido. ahora esos iconos como los necesitas referente al padding ?
