### ISSUE TITLE
Settings view - Basic template

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#526]
viene del caso https://github.com/bitDubai/fermat/issues/4650

**Comment by arnaldos** [comment]
@furszy te comparto varias propuestas avísame si falta algo por incluir 

Versión 1

## ![settings-01](https://cloud.githubusercontent.com/assets/13594347/12869175/9eb375c2-cce9-11e5-9c3d-cd9559ab3888.jpg)

Versión 2

## ![settings-02](https://cloud.githubusercontent.com/assets/13594347/12869176/9eb571f6-cce9-11e5-9fd0-065ebfac554b.jpg)

Versión 3

## ![settings-03](https://cloud.githubusercontent.com/assets/13594347/12869177/9ebc92f6-cce9-11e5-89ac-9398cc903ade.jpg)

Versión 4

## ![settings-04](https://cloud.githubusercontent.com/assets/13594347/12869178/9ec15958-cce9-11e5-8c08-da63c45a5d27.jpg)

Versión 5

## ![settings-05](https://cloud.githubusercontent.com/assets/13594347/12869179/9ec60520-cce9-11e5-96e9-751dbc04539f.jpg)

Versión 6

## ![settings-06](https://cloud.githubusercontent.com/assets/13594347/12869180/9eccc676-cce9-11e5-977e-daa6436534da.jpg)

Versión 7
![settings-07](https://cloud.githubusercontent.com/assets/13594347/12869181/9ed2c468-cce9-11e5-93a0-40806cdb5177.jpg)

**Comment by furszy** [comment]
@arnaldos , por favor seguí las indicaciones que dice la página de material design.
https://www.google.com/design/spec/patterns/settings.html#
Gracias.

**Comment by furszy** [comment]
@arnaldos tambien le tenemos que poner un botón para exportar la clave. Fíjate en el link que te dí y hacelo así por favor.

**Comment by Luis-Fernando-Molina** [comment]
@furszy la exportacion o backup de la clave privada no me parece que sea wallet por wallet, no es practico porque ademas todo forma parte de una wallet HD que abarca a todas las wallets en el sistema

Debiera ser un setting de la Crypto Network de bitcoin que se accede por el panelcito ese que arrancaste y que no se terminó. Quizas teniendo apretado el iconito un ratito entres en los settings de ahi y podas recuperar la llave para backapearla o inyectarle una llave nueva solo si la APP está recien instalada. (asumiendo que perdiste el telefono y queres recuperar tus bitcoins). La posibilidad de inyectar la llave entiendo que a esta altura no esta programada, por ahora dejalo en sacar el backup.

**Comment by arnaldos** [comment]
@furszy versión nueva del settings usando el material design de android con colores base en tonos grises.

Versión 1

---

## ![settings2](https://cloud.githubusercontent.com/assets/13594347/12897872/3963c80e-ce7c-11e5-8844-328f716218d5.png)

Versión 2

---

## ![settings22](https://cloud.githubusercontent.com/assets/13594347/12897873/397f1852-ce7c-11e5-9e29-8c2dd55a0f81.png)

![settings23](https://cloud.githubusercontent.com/assets/13594347/12897874/39849fac-ce7c-11e5-925b-23fefdda3e3b.png)

**Comment by furszy** [comment]
Ok, armo uno así con material design y lo dejo custom para que le puedan pasar los colores que se quieran.

**Comment by arnaldos** [comment]
perfecto !!!

**Comment by furszy** [comment]
Completado

**Comment by arnaldos** [comment]
perfecto cierro el caso :+1:
