### ISSUE TITLE
Banner de gráficos para la Banking Wallet

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#528]
Realizar un banner que nos describe visualmente de que trata la app.

La Banking Wallet sera una billetera que permite administrar varias cuentas bancarias desde la app.

Medidas:

1024x500px

**Comment by astrih** [comment]
Propuesta 01 ![bankingwallet_propuesta01](https://cloud.githubusercontent.com/assets/17072146/12900580/4d87db10-ce89-11e5-8510-daf356dad3fd.jpg)

Propuesta02 ![bankingwallet_propuesta02](https://cloud.githubusercontent.com/assets/17072146/12900581/4d8ef9c2-ce89-11e5-89b2-2c23ecfa261a.jpg)

**Comment by arnaldos** [comment]
@astrih excelente trabajo !! nos quedamos con la propuesta 1. sube los editables al repo :smile:

**Comment by astrih** [comment]
@arnaldos gracias! ya subi los archivos

**Comment by arnaldos** [comment]
@guillermo20 esto ya esta implementado ?

**Comment by guillermo20** [comment]
oopsie! se me olvido comentar esto, si @arnaldos  esto ya esta implementado, thank you :)

**Comment by arnaldos** [comment]
@guillermo20 no pasa nada, solo estoy haciendo seguimiento para cerrar el caso :+1:
