### ISSUE TITLE
Banner de gráficos para la Cash Wallet

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#529]
Realizar un banner que nos describe visualmente de que trata la app.

Cash Wallet es una billetera que permite administrar el dinero. de la siguiente manera:

visualizar el balance
visualizar las transacciones 
realizar depósitos
realizar retiros

**Medidas del banner:**
1024x500px

**Comment by Luis-Fernando-Molina** [comment]
esto para que es?

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina cuando abres la app de cash wallet para el dialog de help

**Comment by Luis-Fernando-Molina** [comment]
ah ok

**Comment by astrih** [comment]
@arnaldos adjunto 3 variantes, quedo atenta a sus comentarios.
Propuesta01
![cash wallet banner-01](https://cloud.githubusercontent.com/assets/17072146/12930264/7058caa8-cf49-11e5-8fca-29e9c1c8de52.png)
Propuesta02
![cash wallet banner-02](https://cloud.githubusercontent.com/assets/17072146/12930265/705b323e-cf49-11e5-99a0-60392e3f83de.png)
Propuesta03
![cash wallet banner-03](https://cloud.githubusercontent.com/assets/17072146/12930266/70647a06-cf49-11e5-9f7e-a66d05e5abce.png)

**Comment by arnaldos** [comment]
@astrih trabajemos con la propuesta 1 

**Ajustes:**
- Las lineas segmentadas hay que darle mayor espesor se ven muy chicas. (este banner dara entrada a la aplicación y si estan muy quequeñas pueden perderse)
- La sombra de la costura se esta pronunciando mas que la propia costura revisa eso plz

**Comment by astrih** [comment]
@arnaldos perfecto! adjunto con los cambios y subo los editables
![cash wallet banner-01](https://cloud.githubusercontent.com/assets/17072146/12967092/bc7faa72-d035-11e5-8af3-bcd8a390b68f.png)

**Comment by m471c4** [comment]
@arnaldos acá algunas versiones para el banner:

Versión 1:
![banner2](https://cloud.githubusercontent.com/assets/13468350/13869180/e1c758fe-eca3-11e5-9e25-3b51f442d8c5.png)

Versión 2:
![banner3](https://cloud.githubusercontent.com/assets/13468350/13869181/e1c7c12c-eca3-11e5-942c-f0c416eed936.png)

Versión 3:
![banner4](https://cloud.githubusercontent.com/assets/13468350/13869182/e1dde006-eca3-11e5-85ff-57a47e1eae43.png)

**Comment by m471c4** [comment]
@arnaldos con las mejoras que me comentaste:

![banner5](https://cloud.githubusercontent.com/assets/13468350/13870208/66a927be-ecae-11e5-881e-16ac781944f9.png)

**Comment by Luis-Fernando-Molina** [comment]
se ve muy bien el ultimo Dayana

**Comment by m471c4** [comment]
@Luis-Fernando-Molina qué bien que te guste. Si les parece que ya está bien, lo subo al repo y cerramos el caso, @arnaldos.

**Comment by arnaldos** [comment]
@m471c4 si estamos listos con esto sube al repo, y avisale a alejandro para que implemente

**Comment by m471c4** [comment]
@Luis-Fernando-Molina @arnaldos ya los editables están en el repositorio. Faltaría que @abicelis los implemente. Podemos cerrar el caso.

**Comment by arnaldos** [comment]
@m471c4 perfecto !!!

**Comment by abicelis** [comment]
Great job @m471c4. Manana integro estos recursos a la cash wallet

**Comment by arnaldos** [comment]
perfecto !! me avisas y asi cierro el caso

**Comment by abicelis** [comment]
@m471c4 @arnaldos 
Es en https://github.com/arnaldos/fermat-graphic-design/tree/master/2D%20Design/Wallets/Cash%20Wallet donde estan los PNG del icono (95kB) y banner(217kB) de la cash wallet?
Los veo algo pesados, por lo menos el icono. No revise en que resolucion estan, pero los iconos que veo implementados en fermat rondan los ~10kB y los banners ~100kB

Habra forma de comprimirlos mas?
