### ISSUE TITLE
Mejorar el logo de Fermat P2P

### ISSUE THREAD

**Issue by m471c4** [bitDubai/fermat-graphic-design#53]
Viene del #9 

Ver si se puede mejorar este isologo desde el punto de vista del diseño y reaplicar la nueva paleta de colores.

![fermat_p2p_hq](https://cloud.githubusercontent.com/assets/9479367/9057279/381e9f5e-3a99-11e5-87a0-def8af2ac6d2.png)

**Comment by arnaldos** [comment]
primera versión de refrescamiento de logo para Fermat P2P
![fermat_version_2-7](https://cloud.githubusercontent.com/assets/13594347/9286682/9387941e-42c2-11e5-91a1-470c6140fb84.jpg)

**Comment by Luis-Fernando-Molina** [comment]
@arnaldos Ek kigi de p2p yo no lo cambiaría mucho, me gusta y costó trabajo llegar hasta ahi. Si hace falta podés hacere retoques si no se ve algo cuando escala o cosas asi, pero preferiría seguir para encontrar los logos equivalentes de otros gruos de plugin que por ahora no existen.

**Comment by arnaldos** [comment]
ok perfecto @Luis-Fernando-Molina voy a mantener el aro blanco en los logos para que entre si tengan un elemento que los relacione.

**Comment by Luis-Fernando-Molina** [comment]
:+1:

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina @m471c4 subo logo Fermat P2P se realizo un refrescamiento de la versión original del logo, buscando resaltar un poco mas cada elemento que se encuentra dentro del mismo y darle una mayor lectura a cada uno de ellos. En la estrella quitamos el brillo que estaba por debajo de ella y colocamos un plano de color blanco para resaltar la figura. ya que el glow genera mucho ruido y dificulta su lectura. 
![fermat_version_2-10](https://cloud.githubusercontent.com/assets/13594347/9317153/837f5adc-4503-11e5-9045-5f6a6f517cba.jpg)

**Comment by arnaldos** [comment]
En esta versión guarda la similitud de la anteriormente enviada con a variación de eliminar la palabra Network y colocarla en siglas al lado de P2P. con la finalidad de simplificar el nombre del mismo y evitar que se pierda en una posible reducción del logo  
![fermat_version_2-13](https://cloud.githubusercontent.com/assets/13594347/9317358/e2e94658-4504-11e5-930d-67f390d6ac6b.jpg)

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina una ves definido el logo y la paleta de colores como lo especifica @m471c4  en el issues #17 cerramos el caso y subo los editables al repositorio.

**Comment by Luis-Fernando-Molina** [comment]
Lo de poner solo la N no es posible porque en los otros logos cuando hay más de una palabra ,  que pondríamos? 

Lo que tenemos que hacer es poner las palabras y tener una versión reducida directamente sin ellas. 

Respecto al cambio en el icono,  Proba ponerle un borde blanco alrededor de las wallets en vez de rojo por favor.

**Comment by arnaldos** [comment]
ok perfecto ya subo los otros iconos que estoy trabajando en sus respectivos issues !!

**Comment by m471c4** [comment]
@arnaldos ya ese caso está cerrado. Nos quedamos con la paleta que has estado utilizando tu :)

**Comment by arnaldos** [comment]
ok perfecto !!

**Comment by arnaldos** [comment]
Icono con bordes blancos en las wallets 
![fermat_version_2-16](https://cloud.githubusercontent.com/assets/13594347/9318439/5e714bba-450d-11e5-8b01-f0b7635a083a.jpg)

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina creo que con los bordes blancos mas delgados se ven mejor las wallets 
![fermat_version_2-17](https://cloud.githubusercontent.com/assets/13594347/9318508/eb9b2a7e-450d-11e5-8995-391d5c9df1d4.jpg)

**Comment by Luis-Fernando-Molina** [comment]
Una preocupación,  porque fermat no tiene la tipografía que ya elegimos??? 

Proba poner la parte de a dentro de la estrella en rojo oscuro.

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina Ajustes de tipografía y color de la estrella ![fermat_version_3-1](https://cloud.githubusercontent.com/assets/13594347/9319160/1a4f5a0a-4515-11e5-8286-db318770694a.jpg)

**Comment by Luis-Fernando-Molina** [comment]
Mucho mejor esta tipografía 

Proba ponerle un borde blanco interno y externo a las líneas de la estrella. 

Proba otras tipografías Para p2p, me parece que se puede mejorar. Quizás una de esas más informáticas.

**Comment by arnaldos** [comment]
ok perfecto !! ya realizo lo ajustes !

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina  Ajustes en la tipografía en P2P y ajustes sobre la estrella
![fermat_version_4-1](https://cloud.githubusercontent.com/assets/13594347/9338383/4cba1cac-45ae-11e5-911e-2f389d76ae16.jpg)

**Comment by Luis-Fernando-Molina** [comment]
Un poquito más ancho el borde blanco please. 

Network no puede ir espaciado,  si bien no queda mal acá,  tiene que ser consistente con los otros. 

Tampoco todo en mayúsculas.

**Comment by arnaldos** [comment]
Ok perfecto !!! ya le hago los ajustes que me solicitas

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina  Ajustes del borde de la estrella y tono de la palabra network
![fermat_version_4-4](https://cloud.githubusercontent.com/assets/13594347/9401856/7d27e69c-479f-11e5-8ea2-b3fcb0b71565.jpg)

**Comment by Luis-Fernando-Molina** [comment]
Deja por favor todo el centro de la estrella en blanco como estaba al principio.

Es posible que la estrella termine como esta aca: https://cloud.githubusercontent.com/assets/13594347/9317358/e2e94658-4504-11e5-930d-67f390d6ac6b.jpg

Pero proba antes la version actual con blanco adentro.

La palabra network se ve muy suave. Si va a ser tan chica la letra el contraste debiera ser mas alto.

**Comment by arnaldos** [comment]
ok perfecto !!! ya ajusto la estrella y la palabra nework

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina ajustes de la estrella y la palabra network
![fermat_version_4-7](https://cloud.githubusercontent.com/assets/13594347/9458736/1ea6125e-4abc-11e5-9360-d406a0cfdd24.jpg)

**Comment by Luis-Fernando-Molina** [comment]
:+1:  listo, caso cerrado, subí al repo los fuentes.

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina perfecto !!! ya subo los fuentes al repo !
