### ISSUE TITLE
Infográfico Nº 1 para el White Paper V2

### ISSUE THREAD

**Issue by jonathanborges3d** [bitDubai/fermat-graphic-design#530]
Viene del #417 

Se debe representar gráficamente la metáfora que describe la red P2P de Fermat como un organismo  multicelular.

Propuestas para la "célula" del gráfico:

![celula_1](https://cloud.githubusercontent.com/assets/13649739/12907440/a5c8fa3c-cebd-11e5-85f0-213f8f7b1aa0.jpg)

![celula_2](https://cloud.githubusercontent.com/assets/13649739/12907447/b0a80c68-cebd-11e5-87bd-a510a862135a.jpg)

@Luis-Fernando-Molina @gustl-arg

**Comment by Luis-Fernando-Molina** [comment]
muy bien, vas bien... Quizas dos celulas tocandose con alguno de esos tentaculos pueda representar una conexion nerviosa (si se pintan de un color nervio) y dos celulas tocandose por otros tentaculospuede representar una conexion de valor , color sangre, incluso se pudiera mostrar por la tuberia en ese caso unas bolitas pasando (ensanchado el tubito) mientras quen la conexion nerviosa, algo que represente informacion, unos ceritos y unos pudieras ser, un rayito o que se yo.

**Comment by jonathanborges3d** [comment]
Ok, hice ésta propuesta para ver que tal quedan las células conectadas por esas terminaciones, aún es un borrador. Utilicé el color rojo para la conexión de valor y azul para la de datos, las secciones ampliadas son un detalle del flujo de datos y valor en las conexiones.

Creo que para asociar mejor el concepto de valor al flujo en la conexión roja pudiésemos colocar círculos amarillos que recuerden monedas.

![celula_3](https://cloud.githubusercontent.com/assets/13649739/12933537/cd4c0070-cf5a-11e5-9f8f-7f60d3e99003.jpg)

**Comment by jonathanborges3d** [comment]
Para el centro de las células podemos colocar la silueta o icono de un dispositivo? un telefono, tablet o pc? para separarlo un poco del esquema biológico y reforzar la idea del dispositivo como célula del sistema Fermat.

**Comment by jonathanborges3d** [comment]
Hice la propuesta de una vez a ver que tal, me das tus impresiones cuando puedas.
![celula_4](https://cloud.githubusercontent.com/assets/13649739/12936936/914abede-cf75-11e5-91b1-166e15c9d91a.jpg)

**Comment by gustl-arg** [comment]
@jonathanborges3d el camino medio entre la representación biologica y tecnologica me parece un muy buen punto de partida ( se ven que son celulas y al mismo tiempo que son dispositivos).
2) quizas deberian existir otras celulas NO FERMAT (que tienen otro ADN) para contrastar con las que sin pertenecen al "organismo" fermat..
3) los flujos de valor y de informacion quizas se puedieran aclarar aun mas con un simbolo por fuera del canal, por ej. algo como $$ en el rojo y algo como hojitas escritas o sobrecitos o libritos para el azul (info).

**Comment by Luis-Fernando-Molina** [comment]
1- No me suena bien un dispositivo adentro de una celula, cuando en la realidad es al revez, la celula vive en un dispositivo.
2 - Yo me imaginaba las conexxiones actuales tocandose, no un canal mas gordo como el que pintaste.

3- Esta bien que plnatien un zoom de esos canales

4-En vez de circulitos amarillos pone nuestra monedita bitcoin.

5- Quizas los "pelos" de las celulas debieran ser mas grande para que salgan del dispositivo si pones las celulas adentro de cada dispositivo

**Comment by jonathanborges3d** [comment]
@Luis-Fernando-Molina @gustl-arg Qué les parece así?

![celula_5](https://cloud.githubusercontent.com/assets/13649739/12966644/55e263d4-d032-11e5-977d-5471abd613d7.jpg)

Faltaría hacer la edición e incluir las monedas y los ceros y unos para las partes ampliadas.

**Comment by Luis-Fernando-Molina** [comment]
No me convence,  me parece que tenemos que volver a los mensajes que identificamos qué teníamos que emitir en la prezi

**Comment by jonathanborges3d** [comment]
Revisé el prezi nuevamente y volví a leer el WPv2, me parece que añadiendo los demás dispositivos y las conexiones entre éstos mejora el asunto.

![celula_7](https://cloud.githubusercontent.com/assets/13649739/12985960/24fa83d8-d0c7-11e5-89d9-c69a664adec7.jpg)

**Comment by Luis-Fernando-Molina** [comment]
Puede ser, anda abriendo los casos de otros infograficos asi se va avanzando en paralelo, todo esto necesita tiempo de madurar y feedback continuo. Si lo haces en serie no terminamos mas. Gracias.

**Comment by gustl-arg** [comment]
@Luis-Fernando-Molina comprendido lo del trabajo en paralelo, me toca a mi identificar los otros..ya me comunico con @jonathanborges3d

**Comment by gustl-arg** [comment]
@jonathanborges3d si creo que mejora al ver el entramado de conexiones..sin embargo consulto..
a) esto es un esquema y luego va a adquirir mas detalle y "profundidad" cuando encontremos el diseño basico 2d de las celulas+dispositivos+canales+conexiones ?
b) hay algo de "organicidad", o sea, la idea de una "totalidad" mas grande que abarca todos los dispositivos, los nodos y las interconexiones que me falta, pero no logro identificar como hacerla visible a traves de un dibujo..escribo esto a manera de "fijar" el concepto...

**Comment by jonathanborges3d** [comment]
@gustl-arg El gráfico tiene aspecto 2D actualmente pero es un diseño 3D, se intenta darle poca profundidad para que parezca un  punto intermedio entre 2d y 3d como dijo @Luis-Fernando-Molina un 2.5D. Se deben mejorar las texturas y el fondo pero en ésta fase puede considerarse una versión beta del infográfico final.

Con respecto a la idea de la totalidad puede pensarse en un gráfico de tres niveles de detalle:
1) EL macro, todo el organismo. una red de puntos, como una molécula o estructura molecular compleja, una nube de puntos o algo que asemeje a una esfera u otra figura con miles de puntos interconectados. ésto es posible.
2) Medio . la parte donde se muestran los dispositivos interconectados pero se diferencian unos de otros, tablets, cells, laptos etc...
3) Detalle, donde se muestra la forma celular del ADN de Fermat, que actualmente se ve en tres disponitivos del gráfico actual.

Gráficos con éste tipo de estructura se ven en todos los libros y material relacionado con estructuras biológicas. Podemos buscar inspiración en ello: 

![](http://www.nacion.com/archivo/cuerpo_humano_LNCIMA20140606_0241_3.jpg)

![](https://mir-s3-cdn-cf.behance.net/project_modules/disp/3571be15882631.5629835e88298.jpg)

![](http://miraiscope.com/wp-content/uploads/2015/07/SocialNetwork-0-00-13-25.jpg)

**Comment by Luis-Fernando-Molina** [comment]
me gusta el ejemplo que pusiste, no hay limetes respecto a 2d 2.5 o 3d lo que quiero que sea vea super bien y que ayude a explicar lo que tenemos. Buscale la vuelta.

**Comment by arnaldos** [comment]
El efecto de la ultima imagen ... si usan afer effects . lo pueden lograr con el plugins tracode mir. 
dejo ejemplos de cosas que se pueden hacer con ese plungin.
https://www.youtube.com/watch?v=7KKDStLvW_A

**Comment by jonathanborges3d** [comment]
Ok. Gracias por la sugerencia @arnaldos, sólo que la estoy realizando enteramente en 3D pero hay alternativas para lograrlo desde acá. De todos modos los efectos que se ven ahi son geniales :smile: 

@Luis-Fernando-Molina Podemos partir de un modelo así para el organismo en el nivel macro? Me refiero al modelo, el color de los materiales puede variar pero quiero saber si representa la idea que se quiere dar.

![organismo_1](https://cloud.githubusercontent.com/assets/13649739/13131430/b30b4d1a-d5bd-11e5-9f4e-c0973b31692d.jpg)

**Comment by arnaldos** [comment]
vale jonathan solo era una sugerencia :smile_cat:

**Comment by Luis-Fernando-Molina** [comment]
no creo que vayamos a llegar a partir de esa red.

Prefiero un infografico mas parecido al de arriba, al del cuerpo humano. Con una mezcla de grafico y texto.

**Comment by jonathanborges3d** [comment]
@Luis-Fernando-Molina @gustl-arg 

Una vista previa sin colocarle textos o señalizaciones al infográfico. Se trata de cuatro niveles de detalle, el primero corresponde a la esfera seccionada compuesta por miles de pequeñas esferas, representaría el organimso multicelular formado por toda la red Fermat. Los puntos luminosos en la esfera corresponden a los procesos activos que transitan por la red y pueden volver a cada dispositivo. Aún falta desarrollar éste concepto.

El segundo es un detalle de éstas pequeñas esferas que representan las células del organismo, Las células vienen a ser los dispositivos y el núcleo, lugar biológico del ADN, sería Fermat, del cual se tienden conexiones hacia las demás células del sistema, unas rojas, para la cryptonetwork y otras azules para la Fermat network.

El tercer nivel de detalle comprende la conexión entre los tres dispositivos en primer plano, cada uno con el núcleo (ADN) de Fermat y sus respectivas conexiones.

Y por último el cuarto nivel que especifica cual es la función de cada conexión, por ello se ven dos secciones de cilindro con simbología de datos (11110101110101010110101) y monedas (bitcoin) circulando por su interior.

![4](https://cloud.githubusercontent.com/assets/13649739/13361167/43dd6f4e-dc8f-11e5-815f-78cbddde4b51.jpg)
