### ISSUE TITLE
Render artistico con el logo de Fermat

### ISSUE THREAD

**Issue by DexybelVillanueva** [bitDubai/fermat-graphic-design#531]
@jonathanborges3d 
@Luis-Fernando-Molina  (Propuestas de materiales)

1)Material: Red oak
![logo fermat 189](https://cloud.githubusercontent.com/assets/16962860/12924212/2b3e4060-cf2b-11e5-9b1c-66c66c3bfc7a.jpg)

2) Material: Aluminium
![logo fermat 184](https://cloud.githubusercontent.com/assets/16962860/12924242/4d959942-cf2b-11e5-8ff4-60fafaa348e0.jpg)

3) Material: Glass cubes orange
![logo fermat 180](https://cloud.githubusercontent.com/assets/16962860/12924244/54d8f4e2-cf2b-11e5-895f-92123bf19978.jpg)

4) Material: Travertine Walnut
![logo fermat 187](https://cloud.githubusercontent.com/assets/16962860/12924253/5cf9d916-cf2b-11e5-941a-d99b8880a842.jpg)

5) Material: Clear rough plastic red
![logo fermat 179](https://cloud.githubusercontent.com/assets/16962860/12925383/383734b6-cf30-11e5-97ad-3364428f867d.jpg)

6) Material: Stell galvanized
![logo fermat 190](https://cloud.githubusercontent.com/assets/16962860/12925455/8e12460a-cf30-11e5-84dd-3fc8c99f60aa.jpg)

---

1) Material: Glass less dense 
![logo fermat y eslogan 202](https://cloud.githubusercontent.com/assets/16962860/12924465/7405e356-cf2c-11e5-8aec-e7c49ab46881.jpg)

2) Material: Stell galvanized
![logo fermat y eslogan 205](https://cloud.githubusercontent.com/assets/16962860/12924564/f650ab20-cf2c-11e5-82da-37b28d20603b.jpg)

3) Material: Metal chipped red
![logo fermat y eslogan 199](https://cloud.githubusercontent.com/assets/16962860/12925051/aa47fc7c-cf2e-11e5-9a10-2d3db1b17dba.jpg)

4) Material: Hard rough plastic 
![logo fermat y eslogan 204](https://cloud.githubusercontent.com/assets/16962860/12925158/182a08fc-cf2f-11e5-9139-01857809ccbd.jpg)

5) Material: Wood
![logo fermat y eslogan 201](https://cloud.githubusercontent.com/assets/16962860/12925296/d90c226c-cf2f-11e5-923f-1c8d325c846c.jpg)

**Comment by Luis-Fernando-Molina** [comment]
Hola, los que se ve la billetera transparente y las chiquitas superpuestas no nos van a servir. Fijate de acomodar eso para que esos materiales tambien puedan ser considerados.

**Comment by Luis-Fernando-Molina** [comment]
Otra cosa, el mapa de la textura debiera aplicarse individualmente a cada billetera

**Comment by DexybelVillanueva** [comment]
Buenas tardes!, ya realize las modificaciones

Modificaciones del Modelado 3D para materiales transparentes

1)Material: Glass cube Orange
![logo fermat materiales transparente 224](https://cloud.githubusercontent.com/assets/16962860/12955083/96ad304a-cff3-11e5-9185-eb108e6b0ebb.jpg)

2)Material: Glass less dense
![logo fermat materiales transparente 216](https://cloud.githubusercontent.com/assets/16962860/12955123/d21c6222-cff3-11e5-9574-65659e2ac3ef.jpg)

3)Material: Glass Basic Red
![logo fermat materiales transparente 226](https://cloud.githubusercontent.com/assets/16962860/12955158/eed8a876-cff3-11e5-94f1-6f0ec715b422.jpg)

---

Materiales sólidos/ Modificaciones del mapa de textura individual para cada billetera

1) Material: Metal Chipped Red
![logo fermat materiales solidos 220](https://cloud.githubusercontent.com/assets/16962860/12955181/0c2cc768-cff4-11e5-9f93-48e352e886f0.jpg)

2)Material:Wood
![logo fermat materiales solidos 221](https://cloud.githubusercontent.com/assets/16962860/12955221/3ea924f2-cff4-11e5-9fff-5934641be841.jpg)

3) Material: Travertine Walnut
![logo fermat 187](https://cloud.githubusercontent.com/assets/16962860/12955267/6ca7b116-cff4-11e5-9c37-c23c8f389964.jpg)

4) Material: Stell Galvanized
![logo fermat materiales solidos 223](https://cloud.githubusercontent.com/assets/16962860/12955292/8aa4881a-cff4-11e5-902a-9887e2f93db3.jpg)

5) Material: Hard rough plastic 
![logo y eslogan dream bigger 228](https://cloud.githubusercontent.com/assets/16962860/12955331/b5a7a2f4-cff4-11e5-9d14-fdb794ce2e17.jpg)

6)Material:Wood
![logo y eslogan dream bigger 229](https://cloud.githubusercontent.com/assets/16962860/12955332/b5b48faa-cff4-11e5-80c8-a739b1cbbe1b.jpg)

**Comment by jonathanborges3d** [comment]
Muy bien, para el último de éste segundo grupo, el 6º de madera, la dirección de la textura debe ir en el sentido en que están giradas las wallets pequeñas. 

Intentemos sombras un poco más agresivas, que denoten mucho más el detalle del logo, ya que se pierde en ocasiones con materiales que tienen mapas de bits más complejos como el acero galvanizado.

**Comment by DexybelVillanueva** [comment]
@Luis-Fernando-Molina Sr luis, ya realize las modificaciones que me dijo y las de jhonathan, cual de estas propuestas le parece y cuales no? 

Materiales transparentes

1)Material: Glass cube Orange
![logo fermat materiales transparente 224](https://cloud.githubusercontent.com/assets/16962860/12955083/96ad304a-cff3-11e5-9185-eb108e6b0ebb.jpg)

2)Material: Glass less dense
![logo fermat materiales transparente 216](https://cloud.githubusercontent.com/assets/16962860/12955123/d21c6222-cff3-11e5-9574-65659e2ac3ef.jpg)

3)Material: Glass Basic Red
![logo fermat materiales transparente 226](https://cloud.githubusercontent.com/assets/16962860/12955158/eed8a876-cff3-11e5-94f1-6f0ec715b422.jpg)

---

Materiales sólidos/ Modificaciones del mapa de textura individual para cada billetera

1) Material: Metal Chipped Red
![logo fermat materiales solidos 220](https://cloud.githubusercontent.com/assets/16962860/12955181/0c2cc768-cff4-11e5-9f93-48e352e886f0.jpg)

2)Material:Wood
![logo fermat materiales solidos 221](https://cloud.githubusercontent.com/assets/16962860/12955221/3ea924f2-cff4-11e5-9fff-5934641be841.jpg)

3) Material: Travertine Walnut
![logo fermat materiales solidos1 243](https://cloud.githubusercontent.com/assets/16962860/12968273/a5157dc4-d041-11e5-9ffd-d2cb88a1be48.jpg)

4) Material: Stell Galvanized
![logo fermat materiales solidos1 241](https://cloud.githubusercontent.com/assets/16962860/12968168/55a8da0c-d040-11e5-9a21-f31d44476d8e.jpg)

5) Material: Hard rough plastic 
![logo y eslogan dream bigger 228](https://cloud.githubusercontent.com/assets/16962860/12955331/b5a7a2f4-cff4-11e5-9d14-fdb794ce2e17.jpg)

6)Material:Wood
![logo fermat materiales solidos1 239](https://cloud.githubusercontent.com/assets/16962860/12968164/4c745006-d040-11e5-9c06-5b92ede6031b.jpg)

**Comment by Luis-Fernando-Molina** [comment]
hay varias que se ven bien, podemos retomar este caso mas adelante cuando estemos mas cerca de usar estas imagnes. gracias
