### ISSUE TITLE
Mejoras gráficas para la Cash Wallet

### ISSUE THREAD

**Issue by m471c4** [bitDubai/fermat-graphic-design#532]
Viene del #421

A partir de las siguientes pantallas, mejorar la apariencia de la wallet.

![view_original](https://cloud.githubusercontent.com/assets/13468350/12931166/7c9bff74-cf4e-11e5-82f9-8473ea72a232.png)

**Comment by m471c4** [comment]
@Luis-Fernando-Molina @arnaldos primeras pantallas con un nuevo esquema de color, a partir del logo de la wallet. Faltarían únicamente los dialogs.

![view_new](https://cloud.githubusercontent.com/assets/13468350/12931181/9cce6214-cf4e-11e5-8194-0fe7d70a4cf0.png)

**Comment by m471c4** [comment]
@Luis-Fernando-Molina @arnaldos con el botón de ayuda y unas mejoras:

![view_new2](https://cloud.githubusercontent.com/assets/13468350/12934843/b2c0ab30-cf63-11e5-9193-9f4c1a069f95.png)

Los dialogs:

![view_newdialogs](https://cloud.githubusercontent.com/assets/13468350/12934799/78588ba2-cf63-11e5-9831-5551b3e21820.png)

Para el dialog de bienvenida, usé una de las propuestas de banner (no aprobadas aun) que subió @astrih, luego se sustituirá por la versión final.

**Comment by m471c4** [comment]
@abicelis si puedes revisa este caso, por favor.

**Comment by abicelis** [comment]
@m471c4 @arnaldos @Luis-Fernando-Molina 

Me gusta el diseno nuevo de la wallet, se ve bien bueno :)

Una sola cosa:
- Arriba en el home del wallet en donde sale el available balance hay un _book balance_ (Unconfirmed Balance se llama en la Bank wallet, creo). Este balance puede ser igual o distinto al available balance, en casos en donde son distintos, deben mostrarse ambos (El book balance debe ser graficamente mas pequeno, pues es menos importante).

Ahora que veo, en los screenshots del diseno anterior nunca salio el book balance, asi que no habria forma de que supieras que ese caso existe :)

**Comment by m471c4** [comment]
Perfecto @abicelis, aplicaré ese cambio que me comentas y lo subo :)

**Comment by m471c4** [comment]
@abicelis puse el Book Balance al lado del Available Balance, pero me preocupa que hayan cantidades demasiado grandes que puedan "chocar" entre ellas. ¿Tú qué crees?

![home](https://cloud.githubusercontent.com/assets/13468350/12955496/89d18f7c-cff5-11e5-9c34-b4bfe39581fd.png)

**Comment by abicelis** [comment]
Hmm.. Tienes razon.
Si se manejan bolivares, facilmente veo esos dos numeros superpuestos.

Sin saber lo que estoy hablando, quiza sirva colocar algo como lo que estaba originalmente, y al tener que mostrar un book balance colocar:

<pre>
      BALANCE
     59.94 ARS
     Available
--------------------
      28.5 ARS
        Book 
</pre>

Haciendo un poco mas grande la parte celeste superior del wallet de necesitar el espacio. Y de esa forma ambos numeros tienen amplio espacio.

Quiza haya mejores ideas, que opinan @Luis-Fernando-Molina? o @arnaldos ?

**Comment by m471c4** [comment]
@abicelis si, definitivamente podrían superponerse. A continuación con tu recomendación, que creo que solventa el problema (si fue necesario aumentar el área azul)

![home2](https://cloud.githubusercontent.com/assets/13468350/12960769/3bdd221c-d00f-11e5-9809-7c197b81bc32.png)

@arnaldos @Luis-Fernando-Molina ¿qué les parece?

**Comment by Luis-Fernando-Molina** [comment]
@abicelis @arnaldos todos estos cambios quien los esta aplicando? Alejandro o ustedes en Graphic Design Team Arnaldo?

Me gusta como va

**Comment by abicelis** [comment]
@Luis-Fernando-Molina todavia no se ha aplicado nada en la wallet. Una vez que se apruebe el diseno (que ya tiene mi visto bueno) podemos hablar @arnaldos @m471c4 para organizarnos y aplicarlo.

**Comment by arnaldos** [comment]
@abicelis como va la implementacion de este caso? avisame lo mas pronto para cerrar este caso

**Comment by abicelis** [comment]
@arnaldos no he cuadrado con @m471c4 para pedirle los recursos e implementarlos en los layouts. Voy a eso y te aviso.

**Comment by m471c4** [comment]
@abicelis ya los resources y el documento estratégico están en el repositorio (debes buscarlos en el fork @arnaldos). Avísame si necesitas alguna otra cosa :)

**Comment by arnaldos** [comment]
ya hago el pull r para que quede en el repo principal

**Comment by arnaldos** [comment]
@abicelis te comparto el enlace https://github.com/Fermat-ORG/fermat-graphic-design/tree/master/2D%20Design/Apps/Cash_Wallet donde están los recursos que subió @m471c4

**Comment by arnaldos** [comment]
@abicelis @m471c4 @nelsonalfo  chicos como vamos con esto ? ya fue implementado ?

**Comment by abicelis** [comment]
@arnaldos ya está implementado, puedes cerrar este issue

**Comment by arnaldos** [comment]
perfecto !!! @abicelis gracias !!!
