### ISSUE TITLE
Crear banner de presentación para la Crypto Customer Identity

### ISSUE THREAD

**Issue by ivonnesantos** [bitDubai/fermat-graphic-design#533]
Proviene de  #128
El icono es el último de caso #415

**Comment by astrih** [comment]
@arnaldos 
Propuesta 01
![crypto customer identity banner-01](https://cloud.githubusercontent.com/assets/17072146/13033968/47bb020a-d2fa-11e5-898b-eb6382fe807b.png)
Propuesta 02
![crypto customer identity banner-02](https://cloud.githubusercontent.com/assets/17072146/13033969/47d2e424-d2fa-11e5-9582-f6ac5a0c94cb.png)

**Comment by arnaldos** [comment]
@astrih propuesta 02, prueba con la trama de fondo en azul plz

**Comment by astrih** [comment]
@arnaldos 
Propuesta 03
![crypto customer identity banner-03](https://cloud.githubusercontent.com/assets/17072146/13037529/c10b16a4-d354-11e5-86ef-4921b9a1f58c.png)

**Comment by arnaldos** [comment]
@astrih aprobado propuesta 03 :+1:  sube los archivos al repo !!

**Comment by arnaldos** [comment]
@vlzangel @nelsonalfo @abicelis @guillermo20 este es el banner de la customer identity avisame cuando lo implementen para cerrar el caso

**Comment by vlzangel** [comment]
@arnaldos ya realice la implementación del banner y se lo pase a @nelsonalfo.

**Comment by arnaldos** [comment]
gracias @vlzangel!!! cierro el caso.
