### ISSUE TITLE
Crear banner de presentación para la Crypto Customer Community

### ISSUE THREAD

**Issue by ivonnesantos** [bitDubai/fermat-graphic-design#534]
proviene del caso #128
Icono aprobado por arnaldo en #174

**Comment by astrih** [comment]
@arnaldos 
Propuesta 01
![crypto customer community banner-01](https://cloud.githubusercontent.com/assets/17072146/13033818/3e66f668-d2f6-11e5-9a49-a52b81562c8f.png)
Propuesta 02
![crypto customer community banner-02](https://cloud.githubusercontent.com/assets/17072146/13033819/3e80ecda-d2f6-11e5-9c8a-190fd5070b2e.png)

**Comment by Luis-Fernando-Molina** [comment]
wow se ve muy bien!

Yo usaría la version de abajo y le agregaria los circulitos de arriba.

**Comment by Luis-Fernando-Molina** [comment]
los circulos incluyendo su sombra.

Tambien le pndria una sobre de la barra de abajo sobre elfondo azul. y ddel recuadro del medio tambien sobre el azul pero mas difuminado asi parece que esta mas alto.

**Comment by astrih** [comment]
@arnaldos @Luis-Fernando-Molina gracias! abajo con los ajustes
![crypto customer community banner-03](https://cloud.githubusercontent.com/assets/17072146/13034022/d661927a-d2fb-11e5-92d0-cd4b263b646b.png)

**Comment by arnaldos** [comment]
@astrih  creo que con eso cambios esta bien, no se que opine @Luis-Fernando-Molina

**Comment by arnaldos** [comment]
aprobado :+1: @vlzangel @nelsonalfo @abicelis @guillermo20 este es el banner de la customer community avisenme cuando lo implementen, para cerrar el caso.

**Comment by nelsonalfo** [comment]
ok, se ve bien. Por favor entregamos la imagen en el tamaño adecuado para poder colocarlo en la app

**Comment by arnaldos** [comment]
@nelsonalfo https://github.com/Fermat-ORG/fermat-graphic-design/blob/master/2D%20Design/CryptoCustomerCommunity/banner/PNG/Crypto%20Customer%20Community%20Banner.png aqui puedes encontrar el banner de la community

**Comment by ivonnesantos** [comment]
esto ya se aplico @nelsonalfo

**Comment by nelsonalfo** [comment]
si, ya se aplicó

**Comment by arnaldos** [comment]
perfecto cierro el caso
