### ISSUE TITLE
Picker Units Selector 

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#535]
Selector de unidades de divisa y bitcoins 

**Ejemplo:**
- (USD,EUR,ARG,VEF)
- (mili,micro,satoshis,etc)

**Comment by arnaldos** [comment]
@furszy propuestas para el Bitcoin Picker

Versión 1

## ![version-1](https://cloud.githubusercontent.com/assets/13594347/12950533/d7d425d8-cfdf-11e5-902e-80f1bbba7083.png)

Versión 2

## ![version-2](https://cloud.githubusercontent.com/assets/13594347/12950534/d7eaf880-cfdf-11e5-8556-16e41c25c068.png)

Versión 3

## ![version-3](https://cloud.githubusercontent.com/assets/13594347/12950535/d80aff9a-cfdf-11e5-8b34-f0fa19f5e224.png)

Versión 4
![version-4](https://cloud.githubusercontent.com/assets/13594347/12950536/d81b47e2-cfdf-11e5-8809-0a8424a52ba6.png)

**Comment by furszy** [comment]
Arnaldo, esto como una pantalla entera no es de utilidad, imagínate que se va a usar cuando el usuario quiera cambiar de monto, de bitcoin a satoshis por ejemplo, por lo que tiene que ser una vista pequeña que entre en otra pantalla

**Comment by arnaldos** [comment]
ok ya quito el resto de los elementos y solo dejo el picker. lo coloque en conjunto para mostrar el comportamiento con el resto de los elementos

**Comment by furszy** [comment]
Explica el comportamiento con las animaciones como va a funcionar, así Clelia lo ve igual que vos a la hora de hacerlo

**Comment by arnaldos** [comment]
vale perfecto !!!

**Comment by furszy** [comment]
@arnaldos fijate de agregar a Clelia a este repo así puede ver las cosas

**Comment by arnaldos** [comment]
@furszy @clp3z

Versión 1
![version-2](https://cloud.githubusercontent.com/assets/13594347/13012380/406cec3a-d17d-11e5-916e-026c4942cf52.jpg)

## Versión 2

![version-2-2](https://cloud.githubusercontent.com/assets/13594347/13012381/40716526-d17d-11e5-9eec-812468aea4f2.jpg)

## Versión 3

![version-2-3](https://cloud.githubusercontent.com/assets/13594347/13012382/408c8568-d17d-11e5-9a10-d6779a056dcc.jpg)

**Comment by furszy** [comment]
La primera esta buena, simple y eficaz

**Comment by arnaldos** [comment]
perfecto !!

**Comment by arnaldos** [comment]
@clp3z dime como va esto te falta algo ? o cerramos el caso ?

**Comment by clp3z** [comment]
Voy bien, estoy haciendo el spinner custom. No creo que me haga falta ningún recurso, ya que no creo que sea posible ampliar el elemento de la lista cuando se presiona. Mas si el color y la letra. De encontrar una forma, haría falta la imagen naranja.

**Comment by arnaldos** [comment]
ok ok perfecto genero la imagen y te la envio. como la necesitas ?

**Comment by arnaldos** [comment]
en 9 patch ?

**Comment by arnaldos** [comment]
o solo la imagen ?

**Comment by clp3z** [comment]
Genera el 9patch. Pero me envías ambos, por si el 9patch no me funciona bien.

**Comment by clp3z** [comment]
Y así yo te digo que se debe de cambiar.

**Comment by arnaldos** [comment]
ok perfecto !!

**Comment by arnaldos** [comment]
ya esta implementado
