### ISSUE TITLE
Storyboard del primer video de Fermat

### ISSUE THREAD

**Issue by jonathanborges3d** [bitDubai/fermat-graphic-design#536]
Viene del #432 

Postearemos aquí todos los storyboards de las escenas para el video. Procuremos el orden cronológico de las escenas por favor.

@victoralfonzohd @AnaPietrosanti @Yinellydesign

**Comment by victoralfonzohd** [comment]
# Storyboard Escena 1:

## Escena 1A

![storyboard 1a](https://cloud.githubusercontent.com/assets/15219855/12993996/b899dff8-d0ef-11e5-92b7-6b65d30da00d.jpg)

## Escena 1B

![storyboard-1b](https://cloud.githubusercontent.com/assets/15219855/13116252/5aef360a-d56d-11e5-95fa-f8636f4b7d0a.jpg)

## Escena 1C

![escena-1-c](https://cloud.githubusercontent.com/assets/15219855/13009275/c43201c8-d16d-11e5-833a-17efc8c94805.jpg)

**Comment by victoralfonzohd** [comment]
# Storyboard Escena 2:

## Escena 2A

![storyboard-2-a_version2](https://cloud.githubusercontent.com/assets/15219855/12991829/4ff10370-d0e3-11e5-999c-e3cf6574716d.png)

## Escena 2B

![storyboard-2-b1](https://cloud.githubusercontent.com/assets/15219855/13163321/3d501d6e-d67e-11e5-949f-b7fea6ac62b0.jpg)

## Escena 2C

![storyboard-2-c](https://cloud.githubusercontent.com/assets/15219855/13163299/1a23593c-d67e-11e5-803f-5e3883025b4e.jpg)

**Comment by victoralfonzohd** [comment]
# Storyboard Escena 3:

## Escena 3A

![storyboard1_3a](https://cloud.githubusercontent.com/assets/15219855/13179182/fa1c8272-d6f4-11e5-9365-06a956f318e1.jpg)

## Escena 3B

## Versión 1:

![storyboard_v1-3b](https://cloud.githubusercontent.com/assets/15219855/13179297/7e5f46dc-d6f5-11e5-9600-72b2eda25ef6.jpg)

## Versión 2:

![storyboard_v2-3b](https://cloud.githubusercontent.com/assets/15219855/13179303/83945962-d6f5-11e5-8ee6-caaf8510b4e9.jpg)

## Escena 3C

![storyboard2-3c](https://cloud.githubusercontent.com/assets/15219855/13191169/046435f6-d734-11e5-8230-8f9a47cd03d5.jpg)

## Escena 3D

![storyboard-3d](https://cloud.githubusercontent.com/assets/15219855/13194213/43df1350-d75b-11e5-97da-a42749edb5e6.jpg)

## Escena 3E

![storyboard-3e](https://cloud.githubusercontent.com/assets/15219855/13269646/079db47a-da5b-11e5-88e8-fd19dfe520c5.jpg)

**Comment by victoralfonzohd** [comment]
# Storyboard Escena 4

![storyboard-4](https://cloud.githubusercontent.com/assets/15219855/12993441/4af65506-d0ec-11e5-9200-45a3d96e1b1e.jpg)

**Comment by jonathanborges3d** [comment]
@yojoaquin @Luis-Fernando-Molina Aquí está el storyboard del video completo, se ha ido actualizando con los cambios más recientes y las sugerencias que hemos recibido.

**Comment by Luis-Fernando-Molina** [comment]
Invitanos a una reunión de Feedback para discutir el story board y dar feedback.

**Comment by AnaPietrosanti** [comment]
youtu.be/E5b9_5ujsZY Este es el avance del animatic hasta la escena 3B sin las correcciones de la escena 1.

**Comment by jonathanborges3d** [comment]
@AnaPietrosanti Para que podamos verlo debes entrar en la configuración del video en youtube y compartirlo desde ahí, porque sino sale privado. :smile:

**Comment by yojoaquin** [comment]
Buenas, sigue estando privado. Podrías cambiarlo @AnaPietrosanti  porfa?

**Comment by jonathanborges3d** [comment]
@yojoaquin Aquí si podrás verlo. Aunque ésta versión ya está des actualizada. Hoy se generarán cambios en una nueva.
[Animatic Escenas 1A a 3B](https://www.youtube.com/watch?v=mvhih9PPzyQ&feature=youtu.be)

**Comment by AnaPietrosanti** [comment]
youtu.be/_BuK9bC3LG0 @jonathanborges3d @yojoaquin Escena1ABC_V2

**Comment by AnaPietrosanti** [comment]
@Luis-Fernando-Molina @yojoaquin  @jonathanborges3d @victoralfonzohd @Yinellydesign 

Link para ver el Animatic completo: youtube.com/watch?v=txAvneioNhQ
Version 2 de la escena 1 completa: youtube.com/watch?v=L7V2ccZABR0

**Comment by jonathanborges3d** [comment]
@Luis-Fernando-Molina @yojoaquin Storyboards actualizados en el primer post. Por favor revisar el 3B que tiene dos versiones para que decidan cual será la indicada. Gracias.

**Comment by Luis-Fernando-Molina** [comment]
@yojoaquin fijate vos please

**Comment by AnaPietrosanti** [comment]
Actualización del animatic V2: youtu.be/uBQ-ryOElr8
@Luis-Fernando-Molina @yojoaquin @jonathanborges3d

**Comment by victoralfonzohd** [comment]
@yojoaquin 

# Escena 2B - Nueva versión

### ## Versión 1:

![storyboard-2-b](https://cloud.githubusercontent.com/assets/15219855/13292566/75598bfe-daee-11e5-9281-f58295ec8b91.jpg)

### Versión 2:

![storyboard-2-b2](https://cloud.githubusercontent.com/assets/15219855/13292575/79fcd79c-daee-11e5-99b0-f6b524f1ca0b.jpg)

**Comment by victoralfonzohd** [comment]
@yojoaquin 

# Escena 2C - Nueva Versión

![storyboard-2-c](https://cloud.githubusercontent.com/assets/15219855/13292651/c755422c-daee-11e5-94e7-5643c0e301ca.jpg)

**Comment by victoralfonzohd** [comment]
@yojoaquin 

# Escena 3B - Nueva Versión

![storyboard_v1-3b](https://cloud.githubusercontent.com/assets/15219855/13292727/185d8012-daef-11e5-8206-816311c7425a.jpg)

# Escena 3C - Nueva Versión

![storyboard2-3c](https://cloud.githubusercontent.com/assets/15219855/13292753/2d2b602c-daef-11e5-854e-27ff2e6d9ce2.jpg)

# Escena 3D - Nueva Versión

![storyboard-3d](https://cloud.githubusercontent.com/assets/15219855/13292763/38543e1a-daef-11e5-97a8-06425d6dc66c.jpg)

# Escena 3E - Nueva Version

![storyboard-3e](https://cloud.githubusercontent.com/assets/15219855/13292783/5284fa36-daef-11e5-9fa0-bf63c04ccce9.jpg)

**Comment by jonathanborges3d** [comment]
Últimas escenas subidas al canal:

[Animatic V5: ](https://www.youtube.com/watch?v=fEnZSKs1PL4)
[Escena 2B V1](https://www.youtube.com/watch?v=iSEnn84tVyg)
[Escena 3BC V1](https://www.youtube.com/watch?v=n-URai57APg)

@yojoaquin @Luis-Fernando-Molina

**Comment by AnaPietrosanti** [comment]
https://youtu.be/I7cGrd9KeHw 
Animatic V6 
@Luis-Fernando-Molina @jonathanborges3d @yojoaquin

**Comment by AnaPietrosanti** [comment]
Fermat Video Final V1 con música.
https://youtu.be/oLI96nNt0M0
@Luis-Fernando-Molina @yojoaquin @jonathanborges3d  @victoralfonzohd @Yinellydesign

**Comment by Luis-Fernando-Molina** [comment]
Ok, esta muchisimo mejor que antes.

Mis observaciones:

1- Esta bien que la musica arranque empezada, de manera que el final coincida con el final de la musica como lo hicieron, pero.

a) revisa el final y vas a ver que si bien la cancion termina casi con un silencio, se escucha un poquitito de algo mas, por favor quitalo.

b) si bien el comienzo depende del final, busca la manera que quede mejor, aunque se demore unos segundos en aparecer la musica. @jonathanborges3d sieno musico te debiera poder ayudar ahí.

2) Cuando se ve el flujo de informacion representados por ceros y unos, yo preferiria que sean letras y numeros mezclados, y en vez de viajar de punta, debieran viajar de costado las letras.

3) Se nota una diferencia de calidad en los dibujos cuando se trata de  un icono tomado de los hechos para el sistema, y el resto delos dibujos en general (con calidad me refiero a la resolucion, y nivel de detalle) me gustaría levantar esa calidad para que sea mas pareja.

4) Para cada aplicación fermat hay "banners" @arnaldos puede decirle cuales y donde están. SI los usaran en multiples casos en el video también les ayudaría a levantar la calidad y además lo acercaría mas a la realidad de lo que tenemos.

5) De la misma manera hay toda una serie de iconos que representan aplicaciones que o bien ya existen o están muy cerca de existir. Tambíen pudieran valerse de todos esos iconos para mejorar aun mas lo que tienen.

6) Posiblemente se puedan usar screenshots de Fermat APPs existentes en vez de dibujos, de hacerlo asegurense de capturar las mejores vistas de estas APPs, con datos y no lo primero que les aparezca.

Con estos puntos corregidos ya lo pondríamos en la página para reemplazar el video anterior.

saludos y gracias por el esfuerzo!

**Comment by jonathanborges3d** [comment]
@Luis-Fernando-Molina Versión con los cambios sugeridos:

https://www.youtube.com/watch?v=UnQ0rxKknk8

**Comment by AnaPietrosanti** [comment]
@jonathanborges3d video subido en la cuenta Fermat Videos https://youtu.be/87CNZups6OM

**Comment by jonathanborges3d** [comment]
:+1:
