### ISSUE TITLE
CCP Community SubApp New Icons

### ISSUE THREAD

**Issue by nattyco** [bitDubai/fermat-graphic-design#537]
Se necesita un icono para la pantalla de "Crypto Wallet User" que inidique que se esta esperando la aprobacion del envio de pedido de conexion sobre un actor. Y se debe cambiar el actual icono que se muestra ahora de google+ que indica que el actor es una conexion.
![community](https://cloud.githubusercontent.com/assets/10051490/13009955/053c7332-d17e-11e5-8157-59e9176f8a04.png)

**Comment by arnaldos** [comment]
@nattyco te comparto las opciones de los iconos 

## ![icon_contact_conect-01](https://cloud.githubusercontent.com/assets/13594347/13014660/297d6fc2-d187-11e5-9ebf-69222cc17713.jpg)

## ![icon_contact_conect-03](https://cloud.githubusercontent.com/assets/13594347/13014662/2988b238-d187-11e5-82b1-01556a109e23.jpg)

## ![icon_contact_conect-04](https://cloud.githubusercontent.com/assets/13594347/13014663/298d0680-d187-11e5-8e3c-c3fecea31800.jpg)

![icon_contact_conect-02](https://cloud.githubusercontent.com/assets/13594347/13014661/29854026-d187-11e5-8629-35801a2e89b5.jpg)

**Comment by arnaldos** [comment]
@nattyco @furszy ajustes del icono

## ![icon_contact_conect](https://cloud.githubusercontent.com/assets/13594347/13018921/a4f70232-d19e-11e5-89d3-51e0ba7481e8.png)

## ![icon_contact_conect2](https://cloud.githubusercontent.com/assets/13594347/13018922/a52d76d2-d19e-11e5-92b7-88284c65e904.png)

![icon_contact_conect3](https://cloud.githubusercontent.com/assets/13594347/13018930/a9a4c530-d19e-11e5-933e-dbd30e6a7962.png)

**Comment by arnaldos** [comment]
![icon_contact_conect4](https://cloud.githubusercontent.com/assets/13594347/13019083/65a8c880-d19f-11e5-9d7d-1caffa1a18dd.png)

**Comment by furszy** [comment]
ok, el blanco va bien. @nattyco agregalo

**Comment by arnaldos** [comment]
@nattyco  @furszy así se ve el de espera 

## ![icon_contact_conect6](https://cloud.githubusercontent.com/assets/13594347/13020851/dae833b0-d1a9-11e5-8d7b-1ef0edb831fc.png)

![icon_contact_conect5](https://cloud.githubusercontent.com/assets/13594347/13020855/de869b60-d1a9-11e5-8bb2-b8811d77c84e.png)

**Comment by acostarodrigo** [comment]
@arnaldos podrias armar algo similar pero con las imagenes de las communities de DAP? Nosotros estamos usando otras imagenes y quiero ver si los íconos seleccionados quedan bien con las otras fotos.

Estaría faltando un ícono adicional a cuando el usuario no acepta la conexión, y podría ser algo como la imagen de la figura y un cartelito de prohibido o algo similar, que indique que la conexión no se hizo porque el destino no lo aceptó.

cc @nindriago

**Comment by furszy** [comment]
@acostarodrigo que bonito, ahora robando ideas eh.

**Comment by acostarodrigo** [comment]
jeje, para que vamos a reinventar la rueda

**Comment by arnaldos** [comment]
jajajaja ...  vale @acostarodrigo

**Comment by furszy** [comment]
@nattyco @arnaldos si ya se encuentra activo cierren el issue por favor

**Comment by arnaldos** [comment]
este es el icono que faltaba

![icon_contact_conect8](https://cloud.githubusercontent.com/assets/13594347/13085298/b5f40f62-d4af-11e5-9ac7-c0f7a6f28e95.png)

**Comment by arnaldos** [comment]
como quedamos con esto @furszy @nattyco  podemos cerrar el caso ? o generamos otras propuestas ?
