### ISSUE TITLE
Generar un Banner de gráficos de Fermat para la Playstore

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#538]
El Banner de gráficos sirve para describir visualmente de que trata la aplicación.

**Medidas:** 1024x500

**Fermat** es una aplicación financiera que te permite crear, administrar, compartir, comunicar todo lo referente a la obtención del mercado de divisas, bitcoins y asset digitales a nivel mundial.
Permitiendo que este mundo financiero sea mas fácil para los usuarios.
## Adjunto logo:

![fermat_logo_3d_2](https://cloud.githubusercontent.com/assets/13594347/13011551/7d2334b2-d179-11e5-9e5a-a33bbfe8fa15.png)

**Comment by astrih** [comment]
@arnaldos 
Propuesta 01
![banner fermat playstore-01](https://cloud.githubusercontent.com/assets/17072146/13034408/ca195a10-d306-11e5-9be2-db6ec5fc352f.png)
Propuesta 02
![banner fermat playstore-02](https://cloud.githubusercontent.com/assets/17072146/13034409/ca2baeb8-d306-11e5-8761-456293e47d1a.png)

**Comment by arnaldos** [comment]
@astrih para este banner:
- Sustituye el logo por la versión 3D que te coloque en la descripción del issue, ve si esa imagen te funciona, si no puedes conseguirla en el repo en la carpeta 3D.
- Has una especie de fusión de ambos artes:
  1- Colocando la trama de los billetes, billeteras y el simbolo de bitcoin, en escala de grises. para que quede como una marca de agua.
  2- Los iconos que representan las distintas plataformas integrarlas a la barra de color salmon.

**Comment by astrih** [comment]
@arnaldos 
Propuesta 03
![banner fermat playstore-03](https://cloud.githubusercontent.com/assets/17072146/13037579/7685106a-d356-11e5-9264-98456a09f913.png)

**Comment by astrih** [comment]
@arnaldos 
Propuesta 04
![banner fermat playstore-04](https://cloud.githubusercontent.com/assets/17072146/13107394/a72b6724-d53f-11e5-9ea4-542fa0a871be.png)

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina ajustes del banner 

## Versión 5

## ![banner de fermat app2](https://cloud.githubusercontent.com/assets/13594347/13153472/81056394-d646-11e5-9236-60adc99f8cdc.jpg)

## Versión 6

![banner de fermat app](https://cloud.githubusercontent.com/assets/13594347/13153471/80fde696-d646-11e5-8f06-b29ac343775e.jpg)

**Comment by arnaldos** [comment]
## View de la playstore

---

![1](https://cloud.githubusercontent.com/assets/13594347/13154432/1ea6ee0c-d64b-11e5-8701-e73b18bf574b.png)

**Comment by Luis-Fernando-Molina** [comment]
la version 6 se ve bien, lo unico que la frase no aplica.

Las monedas debieran ser las que hizo jonathan

Ya que pusiste una frase, reemplaza" more than" por "peer to peer"   y del otro lado "APPs"

Y dentro del telefono pone el logo que dice Dream Bigger.

**Comment by Luis-Fernando-Molina** [comment]
las monedas de jonathan deben estar en la posicion que la usamos en los readme

**Comment by Luis-Fernando-Molina** [comment]
los iconos debieran seguir la curvatura de la linea de abajo

**Comment by arnaldos** [comment]
vale perfecto !!! ya genero los cambios !!!

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina @furzy los ajustes solicitados, mas dos variaciones.

## Versión 7

## ![banner de fermat app3](https://cloud.githubusercontent.com/assets/13594347/13161948/642566e8-d673-11e5-8e5f-36d59b3c2fac.jpg)

## Versión 8

## ![banner de fermat app4](https://cloud.githubusercontent.com/assets/13594347/13161949/642a40b4-d673-11e5-9afc-af22a56390ca.jpg)

## Versión 9

![banner de fermat app5](https://cloud.githubusercontent.com/assets/13594347/13161950/642fe78a-d673-11e5-8025-df836f444aa5.jpg)

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina así queda con el ajuste final 

![banner de fermat app playstore](https://cloud.githubusercontent.com/assets/13594347/13164675/4748f0b0-d689-11e5-933a-e139b178aa39.jpg)
