### ISSUE TITLE
Crear un ImageCropper

### ISSUE THREAD

**Issue by m471c4** [bitDubai/fermat-graphic-design#539]
Crear una vista que contenga un cropper visual para el end user.

**Comment by furszy** [comment]
@m471c4 fijate que esto no es tan importante. en la lista hay otras cosas más prioritarias.

**Comment by m471c4** [comment]
@furszy vale, ¿el IdentitySelector está bien?

**Comment by furszy** [comment]
Si, ese lo podemos hacer tipo swipe desde el navigation view o algún dialog

**Comment by m471c4** [comment]
@furszy vale, voy a crear el caso.

**Comment by arnaldos** [comment]
@furszy comparto una secuencia del image cropper
El cropper se ve reflejado al final 

![profile-fragment](https://cloud.githubusercontent.com/assets/13594347/13323770/1a1a1744-dbad-11e5-88d0-b49ae691fcb3.jpg)

**Comment by arnaldos** [comment]
@furszy  esto quedaría así ??? cierro este caso ?? o se genera otra propuesta?
