### ISSUE TITLE
Crear un fermat Crypto Currencie Exchange widget

### ISSUE THREAD

**Issue by emmysm** [bitDubai/fermat-graphic-design#541]
crear un widget para el inicio y desktop de android con el valor del bitcoin de fermat

**Comment by emmysm** [comment]
![widget-02](https://cloud.githubusercontent.com/assets/15143489/13086095/cc5975c2-d4b3-11e5-9aa1-b544e747d8bc.png)
![widget-01](https://cloud.githubusercontent.com/assets/15143489/13086094/cc58d73e-d4b3-11e5-9a2c-ce41f5de4fbd.png)

@furszy

**Comment by furszy** [comment]
Faltaría el símbolo de fermat en algún lado como para dejar en claro que es nuestro.

**Comment by emmysm** [comment]
Ok. Ya lo coloco @furszy

**Comment by emmysm** [comment]
![widget 3-02](https://cloud.githubusercontent.com/assets/15143489/13088456/7b9ccee4-d4be-11e5-90e7-aedcc4c33983.png)

![widget-01-01](https://cloud.githubusercontent.com/assets/15143489/13088885/56a72e7a-d4c0-11e5-8048-bb57f0f2be89.png)

@furszy

**Comment by leonacostaok** [comment]
@emmysm  probá con algún icono de wallet en vez del logo de fermat, y no pongas el simbolo de btc y al lado el de peso... 
para la bitcoin wallet, estaría bueno que pongas el monto en btc en grande, así: "1.532 btc" y en los casilleritos de abajo se podría mostrar la conversión a USD/ARS/VFE
la fecha no hace falta,, porq esta en la barra de notificaciones arriba... podrías poner ahí un "fermat"
probá también haciendo el widget más grande (viste que son agrandables)
y hace una lista de las ultimas transacciones, de paso usá los mismos colores de la bitcoin wallet actual...
abajo del monto en btc podrías poner también un  "available balance" bien chiquito

**Comment by furszy** [comment]
No peguemos este widget a la wallet ni a ningún saldo, usemos los plugin de CER para que el usuario pueda ver cuanto está el btc y ver el símbolo de Fermat al lado (es un truco visual para que cuando piensen en btc piensen en Fermat). Como si fuera uno de los que usamos habitualmente pero nuestro.
Después podemos hacer otro para ver el balance de una wallet en especifica

**Comment by leonacostaok** [comment]
ok, entiendo! si está buena la idea!

**Comment by emmysm** [comment]
![widget_propuesta_2-01](https://cloud.githubusercontent.com/assets/15143489/13150407/da381f56-d637-11e5-9064-eb78bfc2cd5e.png)
![widget 3-01](https://cloud.githubusercontent.com/assets/15143489/13150408/db3f1d00-d637-11e5-8c5b-d050d8e8d455.png)
![widget-01](https://cloud.githubusercontent.com/assets/15143489/13150412/dccfb774-d637-11e5-8e92-452889a4fdaa.png)

![widget-01](https://cloud.githubusercontent.com/assets/15143489/13150484/2e1199ea-d638-11e5-872d-466b1d858fed.png)

**Comment by arnaldos** [comment]
@emmysm usa tipografías mas light tipo Avant Garde - Hallo Sans - Panton si no las tienes te las comparto... para la versión azul no te recomiendo usar esa sombra debajo del texto, los textos no los pegues tanto a los bordes te genera tensión en la lectura, dale mas aire. :smile_cat:

**Comment by arnaldos** [comment]
@furszy para el Widget se puede usar cualquier tipografía? o solo web ? tipo Roboto, Source Sans Pro, Helvetica Neue ?

**Comment by emmysm** [comment]
Yo me había casado con Roboto @arnaldos. Voy a buscar esta tipografía si se puede usar, si no la encuentro te aviso para que las compartas.
