### ISSUE TITLE
DAP_icon_community_status_conexion

### ISSUE THREAD

**Issue by ivonnesantos** [bitDubai/fermat-graphic-design#542]
@arifernandez 
Crear Iconos de status de conexión para la lista de Asset Community.
La Asset Community tiene dos la user(usuario) community y la issuer(editor) community
Los Status son:
En espera de conexión - Conectado -Rechazado-  
Tamaño de icono pequeño de 24 x 24 o 48 x 48 vamos a hacerlo de ambos tamaños y probarlo en la pantalla para definir el tamaño base. el caso #537 es parecido guiate por ese.

**Comment by arifernandez** [comment]
@ivonnesantos Aqui estan los iconos, en 24 porque en 48 quedaban muy grandes

![dap_icon_community_status_conexion24y48pxmockups-01](https://cloud.githubusercontent.com/assets/16305653/13120521/53e8f630-d580-11e5-91da-60dbf0c55867.jpg)
![dap_icon_community_status_conexion24y48pxmockups-02](https://cloud.githubusercontent.com/assets/16305653/13120522/53ee7a24-d580-11e5-82c2-2cc89fa44ff6.jpg)

**Comment by ivonnesantos** [comment]
@arifernandez el status queda muy pequeño dale el protagonismo al status y restale al user no me parece que blanco sea un buen color puedes usar y gris oscuro y algo transparente.

**Comment by arifernandez** [comment]
![dap_icon_community_status_conexion24y48pxmockups-01](https://cloud.githubusercontent.com/assets/16305653/13153973/dd8052c6-d648-11e5-848a-185dd8d99346.jpg)
![dap_icon_community_status_conexion24y48pxmockups-02](https://cloud.githubusercontent.com/assets/16305653/13153974/dd9f1af8-d648-11e5-9cda-46295c25b23c.jpg)

@ivonnesantos Te coloque varias versiones, para que me digas cual es la mejor, elimine el triangulito.

**Comment by ivonnesantos** [comment]
@arifernandez dejemos estas propuestas hasta aca por ahora vamos a crear otra utilizando los iconos del reloj, un check y un icono de stop siguelo trabajando en circulo gris y crea una diferencia de color entre ellos en espera puede ser gris claro aceptado en verde y rechazado en rojo no hagas enfasis en el usuario

**Comment by arifernandez** [comment]
![dap_icon_community_status_conexion24y48pxmockups2-02](https://cloud.githubusercontent.com/assets/16305653/13157977/d905dd1a-d65c-11e5-8618-a654a67d690d.jpg)
![dap_icon_community_status_conexion24y48pxmockups2-01](https://cloud.githubusercontent.com/assets/16305653/13157978/d90be48a-d65c-11e5-8f49-cc6269baa48d.jpg)

@ivonnesantos Que tal estos?

**Comment by ivonnesantos** [comment]
@arifernandez me gusta la ubicación en que lo pusiste arriba definitivamente vamos a quitarle el usuario estorba mucho y no interesa mostrarlo vas a utilizar como base el icono de rechazado; que todos tengan el mismo estilo (el brillo), el grosor del los trazos. hice un esquema basandome en los criterios de android para que veas cómo realizar la diagramación del icono sobre la foto y el icono internamente.

![esquema de icono para icono community-01-01](https://cloud.githubusercontent.com/assets/15238660/13159507/61537036-d664-11e5-9944-1eadc11730e7.png)

**Comment by ivonnesantos** [comment]
@nindriago

**Comment by nindriago** [comment]
Podria conservarse el mismo diseño azul de tarjetita que se definio para CCP Crypto Community, pero que la silueta de lo que se vea no sea una persona sino referente a cada uno de los actores de DAP, issuer, user, redeem Point

que opinas como va quedando @acostarodrigo

**Comment by acostarodrigo** [comment]
muy buenos,!

**Comment by arnaldos** [comment]
@arifernandez  los iconos no se notan con la foto de fondo, busca la manera de resaltar los tal ves con un fondo detrás del icono que permita separar la foto del icono, estas usando los iconos en outlines su lectura con el fondo es muy difícil. busca la simplicidad de los iconos. revisa el **material design de google**  te dejo el enlace https://design.google.com/icons/ también te comparto lo que se trabajo para CCP en el issue #537

**Comment by arifernandez** [comment]
![dap_icon_community_status_conexion24y48pxmockups3-01](https://cloud.githubusercontent.com/assets/16305653/13197759/245f20d8-d7c9-11e5-8b4e-ee3e644124a2.jpg)
![dap_icon_community_status_conexion24y48pxmockups3-02](https://cloud.githubusercontent.com/assets/16305653/13197758/243f9d3a-d7c9-11e5-9968-3370e73fea1e.jpg)

@ivonnesantos @nindriago Aqui hay diferentes versiones

**Comment by ivonnesantos** [comment]
@arifernandez la segunda ilera de la primera pantalla encerrado en un circulo como el de la tercera.
Solo arregla algunos detalles
1 que el grosor de los tres sea el mismo
2 el reloj lo puedes hacer de un color azul claro como el que se esta usando en el diseño pantalla

Te recomiendo que leas lo de construccion de iconos es muy importante que lo hagas para tener un resultado impecable.

**Comment by ivonnesantos** [comment]
@arifernandez sin el recuadro azul creo que con el circulo es suficiente para corregir lo que te dijo arnaldo

**Comment by ivonnesantos** [comment]
![connetion_asset_iusser_commu-01](https://cloud.githubusercontent.com/assets/15238660/13237986/1a7aa65c-d9a2-11e5-930b-e99d47c83f3a.jpg)

@yojoaquin

**Comment by arifernandez** [comment]
![dap_icon_community_status_conexion24y48pxmockups4-01](https://cloud.githubusercontent.com/assets/16305653/13274035/3c9a1320-da7a-11e5-82ae-6f57c7a2c204.jpg)

**Comment by ivonnesantos** [comment]
@arifernandez usaremos los tuyos pero debo corregir unos detalles sube los editables al repositorio para trabajarlos crea la carpeta en Drafts/2D desing /Issues_542_DAP_icon_status_conexion

**Comment by ivonnesantos** [comment]
![correcciones de ariana-01](https://cloud.githubusercontent.com/assets/15238660/13332307/93ad0a28-dbd3-11e5-8609-91f813dadb63.jpg) 
Se parte de la propuesta de  @arifernandez  simplificando los efectos 
@emmysm te parece si utilizamos estos mismos icono para los status de todas las aplicaciones DAP pero adaptando los colores según el diseño que hagamos de cada una?  
@acostarodrigo

**Comment by emmysm** [comment]
Pudiera ser. 
- Quitaría el stroke gris. Se pudiese trabajar con sombra o dejarlo plano. 
- Los tres botones que queden del mismo tamaño. El check lo veo un poco más grande que los demás.
  -Al check se le puede agregar un stroke interno verde. Se pudieran evaluar propuestas.
- Quitarle al reloj los elementos que indican la hora, se van a ver muy pequeños y van a generar ruido. solo le dejaría las manecillas.

Un ejemplo de como pudiese ver el check.

![check-01-01](https://cloud.githubusercontent.com/assets/15143489/13333812/1087dcce-dbdb-11e5-8552-2e8755f5bdb4.png)

![check-01-01-01](https://cloud.githubusercontent.com/assets/15143489/13333898/743cf02e-dbdb-11e5-8f2b-813bec0ae601.png)

El check y el stroke del circulo que tengan el mismo grosor. 
Qué opinas @ivonnesantos ?

**Comment by ivonnesantos** [comment]
![dap_icon_status_conexion_24px-03](https://cloud.githubusercontent.com/assets/15238660/13398288/d61ef354-decf-11e5-8917-f5eeb090b57e.jpg)
@emmysm que tal???

**Comment by ivonnesantos** [comment]
Aprobado
