### ISSUE TITLE
Generar un Brochure para concurso de Fermat

### ISSUE THREAD

**Issue by emmysm** [bitDubai/fermat-graphic-design#543]

**Comment by emmysm** [comment]
## ![concurso de diseno2-01-01](https://cloud.githubusercontent.com/assets/15143489/13098812/3c851424-d4fe-11e5-9f74-233918c0413f.png)

![concurso de diseno2-01](https://cloud.githubusercontent.com/assets/15143489/13098813/3c87eec4-d4fe-11e5-91cf-a2d08bd84e52.png)

**Comment by emmysm** [comment]
@Luis-Fernando-Molina @arnaldos, pueden orientarme en las bases del concurso? Por favor :smile:

**Comment by arnaldos** [comment]
@emmysm la versión 2. no le pongas concurso, cambialo por; 
- Participa en el proceso de selección para diseñadores gráficos 
- Para optar por un puesto vacante 

@yojoaquin ayudamos con el texto a incluir en este broshure

**Comment by yojoaquin** [comment]
Selección de Diseñadores
Fermat convoca profesionales del área de diseño gráfico e ilustración a participar del proceso de selección.
Requisitos
1 Eviar portfolio personal
2 Ganas de Aprender
3 Proactividad

Envía un email a rhh.graphic.design@bitdubai.com con una presentación breve sobre ti y tu portfolio y te diremos cómo participar.

**Comment by emmysm** [comment]
Ajustes
![concurso de diseno-01-01](https://cloud.githubusercontent.com/assets/15143489/13114911/cbda9388-d567-11e5-8bf4-ffdc3d120e69.png)

@arnaldos @yojoaquin

**Comment by arnaldos** [comment]
baja el tamaño de los iconos que estan por debajo del logo, evita que peguen en el borde del plano rosado. una vez bajes el tamaño dale mayor fuerza al logo de fermat que a los iconos. el tamaño de la tipografía donde dice **SELECCIÓN DE** debe tener el mismo tamaño que **DISEÑADORES**  para que no se vean desproporcionados, juega con la familia tipográfica. si estas usando helvetica juega con las variantes que trae la tipografia. 

en la frase donde esta  el correo si estas usando una tipografia **regular**, para el correo usa **medium** o **bold** juega con eso. :smile_cat:

**Comment by Luis-Fernando-Molina** [comment]
no me parece que se vea como algo que sorprenderia a otros diseñadores graficos, siganlo puliendo un poco mas por favor.

**Comment by emmysm** [comment]
![concurso de diseno-01](https://cloud.githubusercontent.com/assets/15143489/13116980/4790d746-d570-11e5-8486-e391ee41caff.png)
![concurso de diseno-02](https://cloud.githubusercontent.com/assets/15143489/13116981/47917070-d570-11e5-94f4-48aa68ba689c.png)

**Comment by emmysm** [comment]
Vale, @Luis-Fernando-Molina

**Comment by emmysm** [comment]
![concurso de diseno-02](https://cloud.githubusercontent.com/assets/15143489/13127000/4fb33d40-d59f-11e5-934b-834529fa9067.png)

@arnaldos @Luis-Fernando-Molina @yojoaquin

**Comment by emmysm** [comment]
![concurso de diseno-02](https://cloud.githubusercontent.com/assets/15143489/13129269/1c98176e-d5ae-11e5-9491-b7ff3d3b603b.png)

@arnaldos

**Comment by arnaldos** [comment]
bajale el tamaño de los iconos para que no peguen en los bordes dale mas aire, el gradiente del color del plano donde esta **SELECCION DE** colócalo a un solo color.. el texto **¡Participa.... !** pasa lo mismo que con los iconos se ven como ahogados, dale mas aire. :smile:

**Comment by emmysm** [comment]
![concurso de diseno-02](https://cloud.githubusercontent.com/assets/15143489/13131023/115b1c5e-d5bb-11e5-8a8a-34f0228a2ca0.png)
![concurso de diseno-03](https://cloud.githubusercontent.com/assets/15143489/13131022/1159d24a-d5bb-11e5-959e-fe259439056b.png)

@arnaldos

**Comment by arnaldos** [comment]
- los iconos mas chicos
- el gradiente donde esta el texto **SELECCION DE** un solo tono 
- el borde rosa debajo de 3er item haslo mas pronunciado o eliminalo casi no se nota genera ruido.
- el texto opta por un puesto vacante alinea lo con algún elemento.
- el punto de los números eliminalos solo deja el guion.

**Comment by emmysm** [comment]
![concurso de diseno-03](https://cloud.githubusercontent.com/assets/15143489/13146499/46fff5f6-d628-11e5-817f-414e47d6596a.png)

@arnaldos @yojoaquin @Luis-Fernando-Molina
