### ISSUE TITLE
Crear un Mnemonic Dialog

### ISSUE THREAD

**Issue by m471c4** [bitDubai/fermat-graphic-design#548]
Pantalla (dialog) con la clave mnemotécnica para exportar.

**Comment by furszy** [comment]
Puede ser diálog o una pantalla completa, el que puede decir mejor como entraría bien el texto es @acostarodrigo

**Comment by m471c4** [comment]
@furszy @acostarodrigo primera versión, espero sus comentarios:

![mnemonicdialog](https://cloud.githubusercontent.com/assets/13468350/13127653/b4f282c6-d5a2-11e5-83d9-1bac102cef2c.png)

**Comment by acostarodrigo** [comment]
un dialogo se ve bien. No deberíamos dar la opción de exportarlo, copiarlo o compartirlo tambien?

**Comment by furszy** [comment]
Dayana me dijo eso pero no lo veo bien, que se mande por mail, se comparta por twitter o donde sea la clave de tus bitcoins es como jodido.
Dejemos un lindo cartelito para que lo pasen a papel o podemos poner para que lo exporten a un archivo dentro del celular.

**Comment by acostarodrigo** [comment]
tene en cuenta que esto de mostrar el codigo es algo intermedio. el dia de mañana, el mismo código se va a distribuir entre todos tus dispositivos para que si te roban el celular, no pierdas tus bitcoins.

Es cierto que lo mejor es en un papel, pero es medio impracticable. Quizas el compartir sea que se tome un screenshot en binario del código y le das la opción al usuario que si quiere se lo envie por mail o lo escriba en un papel.

**Comment by m471c4** [comment]
@furszy @acostarodrigo creo que en ese caso podríamos cambiar esta pantalla por un fullscreen dialog, para que al presionar la opción enviar por correo, se abra un dialog simple donde se introduzca el correo al cuál se desea enviar, y un sackbar para confirmar el envío.

**Comment by furszy** [comment]
Pantalla completa y botón de mail va bien por mi.
Avisame cuando lo tengas que estoy iluminado en cuanto a la seguridad y como lo voy a hacer.

**Comment by m471c4** [comment]
@furszy @acostarodrigo

![mnemonicdialog1](https://cloud.githubusercontent.com/assets/13468350/13133392/06a7716a-d5cd-11e5-8df7-ccc6d2b7d4ca.png)

![mnemonicdialog2](https://cloud.githubusercontent.com/assets/13468350/13133394/073128a6-d5cd-11e5-9dde-6b88f6381b0b.png)

**Comment by m471c4** [comment]
@furszy @acostarodrigo con la vista del teclado:

![mnemonicdialog3](https://cloud.githubusercontent.com/assets/13468350/13133771/08d3273c-d5d1-11e5-94c9-809b49dfa1d7.png)

**Comment by furszy** [comment]
Lo dejaría centrado el texto y arriba le pondría algo explicando lo que es eso, la opción del mail la sacaría de arriba a la derecha.
Así no vemos la pantalla tan vacía.

**Comment by m471c4** [comment]
@furszy @acostarodrigo cambié el título por Mnemonic seed, que es más apropiado. use una breve explicación y un ícono de alerta para que el usuario lea y maneje cuidadosamente la semilla y cambié el botón share por send, para evitar confusiones.

Me pareció innecesario sacar el botón enviar del menú ya que con la explicación se ve bien distribuida la información en la pantalla, pero espero sus sugerencias.

![mnemonicdialog4](https://cloud.githubusercontent.com/assets/13468350/13183477/22816106-d709-11e5-845d-96e58786fafb.png)

![mnemonicdialog5](https://cloud.githubusercontent.com/assets/13468350/13183478/22862af6-d709-11e5-9e17-3e7f9189413b.png)

**Comment by m471c4** [comment]
@furszy @acostarodrigo ¿estas pantallas quedarán así? ¿podemos cerrar el caso?
