### ISSUE TITLE
Generar logo para la Tokens Platform

### ISSUE THREAD

**Issue by emmysm** [bitDubai/fermat-graphic-design#550]

**Comment by proseuz** [comment]
Propuesta 1
![tokens](https://cloud.githubusercontent.com/assets/17308060/13479251/c605f36c-e0a7-11e5-941d-a2cb28f8f457.png)
@emmysm @Luis-Fernando-Molina

**Comment by saraguerrerot** [comment]
![image](https://cloud.githubusercontent.com/assets/19808868/16103520/5541d6ee-3347-11e6-95f1-5207f578e5a5.png)
 @arnaldos @emmysm

**Comment by saraguerrerot** [comment]
![image](https://cloud.githubusercontent.com/assets/19808868/16103578/a77fe70c-3347-11e6-8b27-120416f9c8a8.png)

propuesta 2

@arnaldos @emmysm

**Comment by saraguerrerot** [comment]
![image](https://cloud.githubusercontent.com/assets/19808868/16103593/c4084df6-3347-11e6-89b9-c3a0dc78111b.png)

propuesta 3 
@arnaldos @emmysm

**Comment by emmysm** [comment]
Me gustaría ver más propuestas @saraguerrerot

**Comment by saraguerrerot** [comment]
![image](https://cloud.githubusercontent.com/assets/19808868/16126224/37594ca6-33c5-11e6-8c80-6e74736dd550.png)

![image](https://cloud.githubusercontent.com/assets/19808868/16126243/46d84dee-33c5-11e6-8763-bda4bf9eb396.png)

@emmysm @arnaldos

**Comment by saraguerrerot** [comment]
![image](https://cloud.githubusercontent.com/assets/19808868/16126867/1774153a-33c8-11e6-9449-37190bfb4d0b.png)

@emmysm @arnaldos

**Comment by emmysm** [comment]
Me agrada bastante la propuesta del maletín, @saraguerrerot  Puedes variar los colores?

**Comment by saraguerrerot** [comment]
![image](https://cloud.githubusercontent.com/assets/19808868/16136258/06c68b76-33f7-11e6-8464-1c4f4d9b4534.png)

![image](https://cloud.githubusercontent.com/assets/19808868/16136270/1dbcbf3a-33f7-11e6-9364-5e8762baa8e8.png)

![image](https://cloud.githubusercontent.com/assets/19808868/16136287/45fca122-33f7-11e6-8a94-c2a1a343e76a.png)

@arnaldos @emmysm
