### ISSUE TITLE
Crear el Transactions fragment

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#551]

**Comment by arnaldos** [comment]
@furszy @clp3z propuesta Transactions fragment avisenme si hay alguna corrección 

## ![transactions fragment-03](https://cloud.githubusercontent.com/assets/13594347/13194780/238b4e92-d770-11e5-8a76-5d669c2922c1.jpg)

![transactions fragment-01](https://cloud.githubusercontent.com/assets/13594347/13194779/2386988e-d770-11e5-8f9f-d28e838178f7.jpg)

**Comment by arnaldos** [comment]
@furszy @clp3z que tal esto ?

**Comment by clp3z** [comment]
Hola Arnaldo, buenos días.

Según la descripción del itém, creo que lo único que faltaría es especificar el destinatario y el receptor.
No sabría si el total está de más y qué indica ese total. ¿Cómo se debería actualizar? @furszy 

Es el 28: 
https://docs.google.com/spreadsheets/d/18N0KAarhDL8SzLF6buHDGoMdHZZUdG_zne7h-tCBpm8/edit?pref=2&pli=1#gid=0

"ventana de transacciones con valores básicos como lo son: el sender, destination, amount, date, description".

**Comment by arnaldos** [comment]
@clp3z @furszy ajustes del transactions fragments 

## ![transactions-fragment2-01v](https://cloud.githubusercontent.com/assets/13594347/13328435/ce83c0aa-dbc0-11e5-8b3c-39a5ac1ae24f.png)

![transactions-fragment2-03v](https://cloud.githubusercontent.com/assets/13594347/13328436/ce8ec66c-dbc0-11e5-97d6-acdd43064df8.png)

**Comment by clp3z** [comment]
Hola por aquí.

Matías ha revisado la vista y me comentó que el campo Available Balance sobra, pero los otros campos están bien. Por lo que incluyendo esa correción, quedaría finalizada la vista.

**Comment by arnaldos** [comment]
ok ya subo la corrección

**Comment by arnaldos** [comment]
@clp3z  te comparto el ajuste avísame cualquier cosa

![transactions-fragment-04](https://cloud.githubusercontent.com/assets/13594347/13341097/c2d9cc6c-dc07-11e5-8f5c-13f2daada830.jpg)
