### ISSUE TITLE
Replantear el diseño del icono del Redeem Point Community 

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#552]
Icono actual 

![icono_launcher_512x512](https://cloud.githubusercontent.com/assets/13594347/13164022/4901425e-d684-11e5-8274-de51698ee080.png)

**Comment by astrih** [comment]
@arnaldos 
Propuesta01
![iconoredeempointcommunity-01](https://cloud.githubusercontent.com/assets/17072146/13197633/d23ec6e4-d7c5-11e5-8cd5-660ddca2bed9.png)
Propuesta02
![iconoredeempointcommunity-02](https://cloud.githubusercontent.com/assets/17072146/13197634/d24353c6-d7c5-11e5-8d36-d7b7e6b0c41d.png)

**Comment by arnaldos** [comment]
@astrih trabajemos la propuesta 1, dejando solo los user elimina el aro de color mostaza.

**Comment by astrih** [comment]
@arnaldos 
Propuesta03
![iconoredeempointcommunity-03](https://cloud.githubusercontent.com/assets/17072146/13203223/4c5b3c4a-d885-11e5-9a62-20323b21cf4b.png)

**Comment by arnaldos** [comment]
@astrih Propuesta01, sube los archivos
