### ISSUE TITLE
Replantear el diseño del icono del Redeem Point Identity

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#553]
Icono Actual 

![icono_launcher_512x512](https://cloud.githubusercontent.com/assets/13594347/13164062/a2d719d4-d684-11e5-8edd-1a18094d3409.png)

**Comment by astrih** [comment]
@arnaldos 
Propuesta01
![iconoredeempointidentity-01](https://cloud.githubusercontent.com/assets/17072146/13197676/096a9480-d7c7-11e5-962a-8e16f4ab6d85.png)
Propuesta02
![iconoredeempointidentity-02](https://cloud.githubusercontent.com/assets/17072146/13197677/096f8b20-d7c7-11e5-9955-5ab06da0ed6f.png)

**Comment by arnaldos** [comment]
@astrih trabajemos la propuesta 1, dejando solo la mascara elimina el aro de color mostaza.

**Comment by arnaldos** [comment]
solo para ver como se comportan los elementos

**Comment by astrih** [comment]
@arnaldos 
Propuesta03
![iconoredeempointidentity-03](https://cloud.githubusercontent.com/assets/17072146/13203233/8f98ed36-d885-11e5-9db7-4d48d9b8321a.png)

**Comment by arnaldos** [comment]
@astrih Propuesta01, sube los archivos
