### ISSUE TITLE
Mejoras de la Interfeace de la App Fermat 

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#556]

**Comment by arnaldos** [comment]
@furszy comparto los ajustes para el desktop launcher de la APP
- Quitar el icono de settings de la esquina superior izquierda, para incorporarlo en la parte inferior con los iconos de las identities, communities, etc.
- Mejorar la ventana contenedora de Identities y Comunities.
- Estandarizar los diálogos para que no difieran entre si.
- Mejora en la diagramacion del Settings.
- Para seleccionar el Status App basta con mantener pisado el el icono y se desplega un spiner hacia el lateral permitiendo ver las otras opciones las cuales se podrán elegir.

**Nota** Iconos del Status App aun no están definidos.

## ![1](https://cloud.githubusercontent.com/assets/13594347/13191220/69ceb7fe-d734-11e5-8da1-d27c8fdff4c1.png)

![2](https://cloud.githubusercontent.com/assets/13594347/13191221/69d242de-d734-11e5-8f76-b6523489fc00.png)

**Comment by furszy** [comment]
La primera de abajo a la izquierda no la entiendo mucho, queda linda pero no se puede hacer lo esperado. Nosotros tenemos que poder entrar a otra pantalla o apagar la red desde el panel. por eso estaban ahí arriba antes.
La segunda y la tercera el diseño de arriba está bueno, sería bueno ponerle el simbolo del icono totalizador ahí en vez de la wallet esa que se repite por todos lados (o sea el icono del menú de abajo). La parte de la vista de esas dos vistas no creo que nos sirva, pensá que pueden ser cientos de communities e identities (cosa que no comparto) ahí mismo y el usuario se va a tener que mover por entre ellas para elegir.

**Comment by arnaldos** [comment]
ok ya replanteo las vistas !!!

**Comment by arnaldos** [comment]
@furszy  @Luis-Fernando-Molina 

#### Nueva propuesta para el settings

## ![1](https://cloud.githubusercontent.com/assets/13594347/13239324/962fea24-d9ab-11e5-8096-02f7c6c61793.png)

#### Dos versiones para las carpetas contenedoras de identities y communities

![2](https://cloud.githubusercontent.com/assets/13594347/13239325/96436612-d9ab-11e5-85c8-d81aedb64f88.png)

**Comment by Luis-Fernando-Molina** [comment]
> Quitar el icono de settings de la esquina superior izquierda, para incorporarlo en la parte inferior con los iconos de las identities, communities, etc.

Tiene que ser a la iz no a la derecha. El escaner pornerlo enla derecha. Gracias.

Arnaldo, por favor numera las opciones, no es practico estar diciendo la primera de arriba del segundo posts o cosas como esas.

Anyway, de tu ultimo post:

Me gustó la idea de la primera fila tercera columna. Observaciones:
1. Debajo de "Fermat Network" debe decir "Connected to" renglon de abajo "1 Node" en otro color de letra y en bold. 
2. Mati: Private Network tiene que salidr en gris por ahora porque no existe.
3. Bitcoin Network: Tiene que salr abajo: "Mainnet" en el mismo color anterior y en bold. (y cambiar cuando este conectado a otra red). (Una APP o wallet puede ser cambiada de manera individual, este es un switch master que cambia a todos en general).
4. Lo que dice "APP release" debe decir "APP Filter" y mostrar abajo en bold y de otro color "Release|Beta||Alpha|Develop" de acuerdo a lo que esté seleccionado.

Me parece bien la listita que sube para arriba cuando tocas en esa opcion. Tambien es valida para la bitcoin network para cambiar todo a otra red. En Private Network por ahora no pasa nada, y en Fermat network tampoco.

En el icono de Alpha noto que pusiste un signo de OMEGA que es otra letra griega diferente. Pudieras poner la letra Alpha mejor.

Donde dive ahora "Network Settings" poné "More Settings" y ponele al area gris, al medio una "flechita hacia arriba" como para indicar que es un panel que se puede mover con el dedo hacia arriba, lo cual desplegaría otros settings a nivel de todo el sistema. Si se mueve, ocuparia toda la pantalla, forzando a que los inonos de arriba salgan de la visata.

Ahí debiera ir Mati el tema del backup y por ahora nada mas.

**Comment by Luis-Fernando-Molina** [comment]
Respecto a las identities y communities, pudiera andar la ultima opcion de la derecha, osea con pantalla completa. El diseño me parece bien, pero recorda que se necesitan nombres mas largos que ocupen dos renglones.

**Comment by furszy** [comment]
Ok bien, antes de que me ponga a desarrollar digo algunas cosas:

1 - El desplegable del status de la app no lo veo que vaya a funcionar, vamos a cargar mucho la pantalla con eso, imaginen se cuando tengamos más de esas opciones (el swipe hacia los costados) y quiero desplegar más de una al mismo tiempo que tengan ese efecto, las animaciones no van a quedar "elegantes" con todas las cosas bajando y subiendo simultáneamente, va a ser un juego en vez de una app. Ahí yo me inclino por un buen dialog/pantalla con transparencia (bien diseñado) con las 4 opciones y los radio button en su lado derecho, bien sencillo de entender para el usuario.

2- Me gusta la idea del "more settings" en el footer, esa pantalla nos va a dejar poner configuraciones a un nivel más macro de la app. (Arnaldo esa pantalla tiene que ser un settings bien simple con material design, mirá el link que te pasé la otra vez para armar eso)

En lo demás comparto en todo con ambos, va a quedar bueno.

**Comment by Luis-Fernando-Molina** [comment]
> El desplegable del status de la app no lo veo que vaya a funcionar, vamos a cargar mucho la pantalla con eso, imaginen se cuando tengamos más de esas opciones y quiero desplegar más de una al mismo tiempo, las animaciones no van a quedar "elegantes" con todas las cosas bajando y subiendo simultáneamente, va a ser un juego en vez de una app. Ahí yo me inclino por un buen dialog/pantalla con transparencia (bien diseñado) con las 4 opciones y los radio button en su lado derecho, bien sencillo de entender para el usuario.

Es muy dificil de hacer como para ver como queda andando?

**Comment by furszy** [comment]
Lo tengo anotado para armarlo en el toolbox así que lo tengo que hacer genérico para todos. Arriba de eso le puedo dar ese estilo así lo ves, si arreglamos eso sin el swipe.
A lo que voy es imaginarlo en uso es complicado, imagínate eso con varios items más,
1-  cuando se haga un swipe, el menú este puede quedar en el medio con el desplegabe.
2 - si el menú está abierto y hacemos el swipe tenemos que cerrarlo al mismo tiempo, no podemos correrlo por toda la pantalla abierto, le saca el foco a lo que el usuario quiere hacer que es el swipe.
3- si aparecen más de estos items vamos a tener una montaña rusa en nuestro desktop :P. 

Es una cuestión de no molestar tanto al usuario con tantas animaciones que se hace más simple y entendible con una buena pantalla de selección.

**Comment by arnaldos** [comment]
@furszy  @Luis-Fernando-Molina Comparto las mejoras del desktop:

Version 1 (Fondos simples)

## ![v1](https://cloud.githubusercontent.com/assets/13594347/13292162/d2d329fe-daec-11e5-8f39-f5741ebf4d09.png)

Version 2 (Fondo transparente)
![v2](https://cloud.githubusercontent.com/assets/13594347/13292163/d2f09e1c-daec-11e5-863e-25badad3987f.png)

**Comment by arnaldos** [comment]
Al tocar el icono de settings se despliega el menu con todas las acciones que se podrán realizar, 
luego si tocamos alguna de estas acciones nos aparece un dialogo permitiendo elegir cualquiera de las opciones establecidas.

**Comment by furszy** [comment]
Las opciones esas que vos agregaste en el menu desplegable van en el bottom menu que se desliza hacia los costados en el desktop, en la pantalla de settings que se expande , es la pantalla de abajo al medio de la versión 2 que mandaste,(poneles número por favor a las pantallas) tienen que estar otros iconos como el de exportar la clave mnemonic entre otros, tiene que ser distinta la forma de acomodar las cosas.

**Comment by arnaldos** [comment]
@furszy esta versión es antes de ver tu ultimo comentario, cuando puedas llámame porque no entiendo lo que me explicas, lo estoy entendiendo de otra manera por lo que veo.

Version 3 
- Pantalla 1 boton settings inactivo 
- Pantalla 2 se ve el settings abierto. con un dialogo que sale una ves se presione el App Filter
- Pantalla 3 se ve el settings abierto. con un dialogo que sale una ves se presione alguna network 

![v3](https://cloud.githubusercontent.com/assets/13594347/13295677/346779b8-dafc-11e5-80f8-27233c28f5f8.png)

**Comment by furszy** [comment]
abajo ponele solo "more" en la pantalla 2 así no repetimos la palabra settings.
@Luis-Fernando-Molina mirá la "pantala 2",  si das el ok la armo. Lo que no tenemos por ahora es lugar para el mnemonic, va a quedar vacio en el desplegable de abajo.

**Comment by Luis-Fernando-Molina** [comment]
no me vuelve loco pero es mejor que lo que hay, asi que dale
