### ISSUE TITLE
DAP_icon_settings

### ISSUE THREAD

**Issue by ivonnesantos** [bitDubai/fermat-graphic-design#558]

**Comment by ivonnesantos** [comment]
@yojoaquin @nindriago 
![icon_settings-01](https://cloud.githubusercontent.com/assets/15238660/13198802/abb644e2-d7e4-11e5-8e0c-f0f45c71ce56.jpg)

Ejemplo en el head los colores varían según cada sub aplicacion pero la forma seria la misma en todos

**Comment by yojoaquin** [comment]
No me convence ese ícono. Se asemeja a uno de "settings". 
Algo así tal vez? 
https://thenounproject.com/search/?q=redeem&i=116517
O alguno de acá
https://thenounproject.com/search/?q=exchange+

**Comment by ivonnesantos** [comment]
@yojoaquin ese icono es de settings lo que pasa es que no se todavia donde lo vamos a poner y lo puse allí pero si es de settings

**Comment by yojoaquin** [comment]
Hmmm me harías el favor de ponerlo en contexto en una pantalla porfa?

**Comment by nindriago** [comment]
es el mismo icon de setttings que usan en la CCP Wallet, pero para DAP lo quisiera en Negro y otro en Blanco
aca el ejemplo de una de las wallet: https://github.com/Fermat-ORG/fermat-graphic-design/issues/385

se colocara igual en el navigation_drawer pero para que se mantenga la igualdad con los demas icon que se usan, se necesita en negro y blanco

**Comment by arifernandez** [comment]
![settings_b_walletstore1](https://cloud.githubusercontent.com/assets/16305653/13268528/3285cd40-da55-11e5-9424-9efc8289c4d8.png)
![settings_b_walletstore2](https://cloud.githubusercontent.com/assets/16305653/13268529/328ab3a0-da55-11e5-9cd7-224fb788aa05.png)

@ivonnesantos

**Comment by nindriago** [comment]
bonitos, pero ambos transparentes por favor.

**Comment by ivonnesantos** [comment]
bien si @nindriago eso me imagino que lo puso ella para que los pudieramos ver. Estamos Listos por aca @arifernandez genera el PNG en 90x90 y puedes subirlo al repositorio

**Comment by nindriago** [comment]
me avisan cuando esten para bajarlo, gracias a las 2 :)
