### ISSUE TITLE
Add fermat user view

### ISSUE THREAD

**Issue by emmysm** [bitDubai/fermat-graphic-design#559]
Pantalla para elegir usuarios de fermat y agregarlos como contacto de la reference wallet

**Comment by emmysm** [comment]
![add fermat user-01-01](https://cloud.githubusercontent.com/assets/15143489/13235800/2724c15e-d992-11e5-9f8f-163f9ec2821b.png)
![add fermat user-01-02](https://cloud.githubusercontent.com/assets/15143489/13235801/272c21b0-d992-11e5-9e7d-a4197e6d57df.png)

Hola, @nattyco , te dejo aca dos propuestas.

**Comment by nattyco** [comment]
La primera opcion esta bien, el check hay que alinearlo con el resto de los datos de la fila.

**Comment by nattyco** [comment]
tambien plantea alguna opcion donde los usuarios entiendan que tienen que presionar sobre un contacto (o varios) para marcarlo para agregar.

**Comment by emmysm** [comment]
![add-01-01](https://cloud.githubusercontent.com/assets/15143489/13239520/2a49c79c-d9ad-11e5-86b3-21ead8c1a9ec.png)
![add-01-02](https://cloud.githubusercontent.com/assets/15143489/13239521/2a4cddb0-d9ad-11e5-8d17-473b04c11715.png)

![add-01-02-02](https://cloud.githubusercontent.com/assets/15143489/13239553/7a9618ea-d9ad-11e5-84c8-35ca3924a804.png)

@nattyco

**Comment by emmysm** [comment]
![add-04-04](https://cloud.githubusercontent.com/assets/15143489/13273208/022be7b4-da74-11e5-9f89-34fb2e895e81.png)
@nattyco

**Comment by nattyco** [comment]
@emmysm  la pantalla esta bien, cerramos el caso, solo un detalle que en lugar de Add arriba dejamos el boton
