### ISSUE TITLE
Mejorar el logo de Fermat PIP

### ISSUE THREAD

**Issue by m471c4** [bitDubai/fermat-graphic-design#56]
Viene del #10 

Ver si se puede mejorar este isologo desde el punto de vista del diseño y reaplicar la nueva paleta de colores.

![fermat_pip_hq](https://cloud.githubusercontent.com/assets/9479367/9057259/0d09053e-3a99-11e5-8069-5c2cbe013b85.png)

**Comment by arnaldos** [comment]
Primera versión de refrescamiento de logo Fermat PIP
![fermat_version_2-8](https://cloud.githubusercontent.com/assets/13594347/9286697/f8187d6c-42c2-11e5-9961-b875ae2111e6.jpg)

**Comment by Luis-Fernando-Molina** [comment]
@arnaldos lo mismo que en el caso anteior, a este logo se llego luego de bastante trabajo para representar el concepto. Yo no lo tocaria mas que en algun detalle y reflejar la nueva paleta de colores.

Pregunta @m471c4 , lo colores cambiaron o no? Veo que los que usa @arnaldos no coinciden con los anteriors pero me parece que tu digiste que al final no cambiaban. En que quedamos?

**Comment by arnaldos** [comment]
Hola @Luis-Fernando-Molina perfecto ya le realizo esos ajustes que me comentas, referente a la paleta de colores no la he variado mantuve la misma que están en los editables del repositorio. De igual manera voy a revisar para ver que puede haber pasado en los archivos que estoy manipulando.

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina antes de iniciar con lo que me solicitas quería comentarte en que me había basado para este icono:   Para esta versión que trato de vender, lo enfoque cuando el usuario va a interactuar con la wallet, dicha wallet puede conectarse  a los distintos plugins que están a su alcance y de esta manera enfoque gráficamente una wallet adherida a un conector o un enchufe. Busque la manera de simplificar todo el contenido que posee el icono original, en un solo  esquema grafico ya que el icono inicial pose muchos elementos que si implementamos una reducción mucho de estos elementos se podrían perder en dicha reducción.

**Comment by Luis-Fernando-Molina** [comment]
@arnaldos tené en cuenta que la gráfica que estamos haciendo no toda es orientada al mismo público.

Este icono en particular es orientado a programadores que lo van a ver en presentaciones especializadas de nuestro producto. 

Hay otros elementos que son para los usuarios finales de las billeteras. Vas a tener que distinguir entre ests cosas si querés mantener el foco. Una forma fácil de darse cuenta es donde se está usando ahora. Aunque a veces con eso no es suficiente para determinar cual es el publico.

**Comment by arnaldos** [comment]
ok perfecto !!

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina @m471c4  Ajustes del logo manteniendo los elementos originales 
![fermat_version_2-12](https://cloud.githubusercontent.com/assets/13594347/9318634/29251bb0-450f-11e5-9e90-b0725704fdb1.jpg)

**Comment by Luis-Fernando-Molina** [comment]
Tipografía???

**Comment by Luis-Fernando-Molina** [comment]
Busca la consistencia a lo largo de todos los logos,  si en el otro le pusimos blanco alrededor de cada billeterita,  a estos también deberíamos. 

Otra cosa,  el borde de cada enchufe en el tablero verde,  proba blanco please.

**Comment by arnaldos** [comment]
ok ya le hago los ajustes, la tipografía no la había incluido porque no habíamos cerrado el caso

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina ajustes de borde y tipografia
![fermat_version_3-2](https://cloud.githubusercontent.com/assets/13594347/9319148/fa38e0f6-4514-11e5-8b37-167b67e814bd.jpg)

**Comment by Luis-Fernando-Molina** [comment]
OK el logo y fermat ya esta,  igual que en el otro caso,  busquemos que pip quede mejor.

**Comment by arnaldos** [comment]
ok perfecto !! ya realizo lo ajustes !

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina  Ajustes en la tipografía en PIP
![fermat_version_4-2](https://cloud.githubusercontent.com/assets/13594347/9338364/2d4a39b0-45ae-11e5-89ab-8cb6f2c438a7.jpg)

**Comment by Luis-Fernando-Molina** [comment]
No estoy seguro de las letras rojas...

**Comment by arnaldos** [comment]
ok ya pruebo con otro tono y vemos como se comporta

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina  ajustes del tono de color del 
![fermat_version_4-5](https://cloud.githubusercontent.com/assets/13594347/9401898/e480421c-479f-11e5-8456-90c728e25175.jpg)
nombre de la sub-app

**Comment by Luis-Fernando-Molina** [comment]
Estos ajustes, probalos en un solo logo, y cuando se apruebe ahi replicalo :smile:

**Comment by arnaldos** [comment]
Ok perfecto!!

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina  ajustes del texto Plu-ings Platform

![fermat_version_4-8](https://cloud.githubusercontent.com/assets/13594347/9458763/95f2ba88-4abc-11e5-8a60-f5aa4d924ac9.jpg)

**Comment by Luis-Fernando-Molina** [comment]
:+1: listo, terminado.
