### ISSUE TITLE
Mejorar gráficamente el Wizzard Providers de la Crypto Broker

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#560]
Vista actual 
## ![b1](https://cloud.githubusercontent.com/assets/13594347/13232071/be2b1d90-d97f-11e5-87e2-12d77608d236.png)

![b2](https://cloud.githubusercontent.com/assets/13594347/13232072/be2f03f6-d97f-11e5-9571-52ba453ae88d.png)

**Comment by m471c4** [comment]
@arnaldos @nelsonalfo @abicelis a continuación apliqué la paleta de colores y mejoré las vistas, pero tengo algunas dudas en cuanto al funcionamiento de las pantallas que creo que se pueden mejorar:

![wizardproviders1](https://cloud.githubusercontent.com/assets/13468350/13275379/a26f2918-da86-11e5-8baf-28eca890a667.png)

![wizardproviders2](https://cloud.githubusercontent.com/assets/13468350/13275378/a26f0dca-da86-11e5-9efa-251fb2a207b9.png)

Otra cosa cosa que se puede mejorar son los textos en inglés, las instrucciones no quedan claras.

**Comment by m471c4** [comment]
@arnaldos @nelsonalfo @abicelis mejora en las vistas, estandarizándolas con todos los wizards de la customer y la broker.

En esta puse botones de selección en el dialogo para seleccionar rodos los proveedores que se deseen, luego los vemos listados en la pantalla y podemos eliminarlos desde ahí:
![wizardproviders1-1](https://cloud.githubusercontent.com/assets/13468350/13387113/8cb7cd2a-de85-11e5-918a-9e36768ab3f8.png)

![wizardproviders1-2](https://cloud.githubusercontent.com/assets/13468350/13387114/8cbaab8a-de85-11e5-9da4-b5b8a08d4e6b.png)

![wizardproviders1-3](https://cloud.githubusercontent.com/assets/13468350/13387115/8cc1c456-de85-11e5-9c17-c1c1c1aec7fd.png)

En esta vista no tengo idea de dónde poner el Automathic restock, puse dos "versiones":
![wizardproviders1-4](https://cloud.githubusercontent.com/assets/13468350/13387116/8ceae020-de85-11e5-948c-cd2db26846b4.png)

**Comment by nelsonalfo** [comment]
Me parece bien :+1: En la pantalla del Automatic Restock, utilizamos la "version" 1

**Comment by m471c4** [comment]
Excelente @nelsonalfo, generaré los documentos para pasártelos y que puedas implementar los cambios :)

**Comment by arnaldos** [comment]
@nelsonalfo confirmarme si esto esta implementado ?

**Comment by nelsonalfo** [comment]
todavía no lo hemos implementado

**Comment by arnaldos** [comment]
ok avisame cuando este listo para cerrar el caso

**Comment by abicelis** [comment]
@arnaldos @m471c4 pueden cerrar este issue

**Comment by arnaldos** [comment]
@abicelis perfecto ya lo cierro
