### ISSUE TITLE
Mejorar gráficamente el Wizzard Merchandises de la Crypto Broker

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#561]
Vista actual
## ![b5](https://cloud.githubusercontent.com/assets/13594347/13232147/138261a4-d980-11e5-8cac-6f50777278e8.png)

![b6](https://cloud.githubusercontent.com/assets/13594347/13232148/138a3c1c-d980-11e5-8508-6c8ce6d1ddb5.png)

**Comment by m471c4** [comment]
@arnaldos @nelsonalfo @abicelis primera propuesta para las vistas del Wizard.

En el dialog de la segunda pantalla, ¿se pueden seleccionar varias wallets a la vez? Quisiera saber si vale la pena poner checks para ver cuáles se han seleccionado.

![wizardmerchandise](https://cloud.githubusercontent.com/assets/13468350/13272697/2ebd8372-da70-11e5-84d4-642e54c423cb.png)

**Comment by arnaldos** [comment]
@m471c4 
- Elimina la marca de agua o colócala menos visible fijate que puede interferir con la lectura de la lista de mercancías que se agreguen.
- Podrias colocar un linea que se pare los textos del listado.
- El texto de **NO SELECTED WALLET** centralo dentro del área libre que se forma entre los botones.

**Comment by m471c4** [comment]
@arnaldos @nelsonalfo @abicelis 

![wizardmerchandise2](https://cloud.githubusercontent.com/assets/13468350/13276723/6ca858dc-da94-11e5-8ba4-13dc9415e089.png)

**Comment by m471c4** [comment]
@arnaldos @nelsonalfo @abicelis acá los dialogs para crear una Cash Wallet y una Bank Wallet:

Cash:
![wizardmerchandise3](https://cloud.githubusercontent.com/assets/13468350/13308309/52cb0238-db44-11e5-80cb-44e16f0b7d2b.png)

Bank:
![wizardmerchandise4](https://cloud.githubusercontent.com/assets/13468350/13308280/22ec47fc-db44-11e5-94dc-07ebaba190b9.png)

**Comment by nelsonalfo** [comment]
Muchísimo mejor que lo que esta ahorita xD Me gusta

**Comment by m471c4** [comment]
@arnaldos @nelsonalfo @abicelis mejora en las vistas, estandarizándolas con todos los wizards de la customer y la broker.

![wizardmerchandise1-1](https://cloud.githubusercontent.com/assets/13468350/13387279/453658ca-de87-11e5-9ebe-871cc455bd89.png)

![wizardmerchandise1-2](https://cloud.githubusercontent.com/assets/13468350/13387280/4539c9d8-de87-11e5-8521-484b11143ea5.png)

![wizardmerchandise1-3](https://cloud.githubusercontent.com/assets/13468350/13387281/455cbbbe-de87-11e5-9952-8927c54ce79b.png)

**Comment by arnaldos** [comment]
@nelsonalfo confirmarme si esto esta implementado ?

**Comment by nelsonalfo** [comment]
todavía no lo hemos implementado

**Comment by abicelis** [comment]
@arnaldos @m471c4 pueden cerrar este issue

**Comment by arnaldos** [comment]
@abicelis perfecto !!!
