### ISSUE TITLE
Mejorar gráficamente el Settings de la Crypto Customer

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#562]
Vista actual

![c4](https://cloud.githubusercontent.com/assets/13594347/13232224/73d8462c-d980-11e5-9f0a-d98e0ccde4b0.png)

**Comment by arnaldos** [comment]
@nelsonalfo 
Mejora del settings

![crypto customers-05](https://cloud.githubusercontent.com/assets/13594347/13340365/e5a70fd0-dc01-11e5-9c97-46d476be0055.jpg)

**Comment by nelsonalfo** [comment]
Excelente! mucho mejor

**Comment by arnaldos** [comment]
perfecto esto puede quedar asi ? siendo asi para generar el doc

**Comment by nelsonalfo** [comment]
si, se puede quedar así :+1:

**Comment by arnaldos** [comment]
perfecto !!!

**Comment by arnaldos** [comment]
@nelsonalfo confirmarme si esto esta implementado ?

**Comment by nelsonalfo** [comment]
todavia no esta inplementado

**Comment by vlzangel** [comment]
You can close this @arnaldos
