### ISSUE TITLE
Mejorar gráficamente el Location Wizzard de la Crypto Customer

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#563]
Vista actual

![c3](https://cloud.githubusercontent.com/assets/13594347/13232381/17918526-d981-11e5-82c5-0c67e910f49f.png)

**Comment by arnaldos** [comment]
@nelsonalfo te comparto las mejoras del wizzar Location. en imagenes por separado y la secuencia avisame si me falta algo adiciona en la secuencia.

## ![crypto customers-08](https://cloud.githubusercontent.com/assets/13594347/13340657/597452a4-dc04-11e5-9765-f4ccadceb9a4.jpg)

## ![crypto customers-09](https://cloud.githubusercontent.com/assets/13594347/13340658/599c7f5e-dc04-11e5-9c3e-f13b9b750711.jpg)

## ![crypto customers-10](https://cloud.githubusercontent.com/assets/13594347/13340659/59c4342c-dc04-11e5-8b7c-df79196fc615.jpg)

Secuencia

---

![secuencia-2](https://cloud.githubusercontent.com/assets/13594347/13340669/69054c50-dc04-11e5-88be-5883c63ebff6.jpg)

**Comment by nelsonalfo** [comment]
Lo que entiendo aqui es que la misma pantalla va a funcionar como formulario y listado? En general esta bien, lo que no me convence es el action bar. Tengo entendido que en los wizards no se muestra el action bar

**Comment by arnaldos** [comment]
Ok perfecto !!  si de primera instancia sera un formulario que al ser llenado y creado. quedaria como un listado como lo estoy presentando también te daría la opción de crear una nueva o editar la que ya esta existente.

lo del accion bar en este caso seria eliminar el boton y quedaria la barra como titulo unicamente de esta manera el usuaria sabra donde esta ubicado

**Comment by arnaldos** [comment]
@nelsonalfo aclárame algo, los wizards le dan entrada a la app cierto ? por lo tanto son una serie de wizards que  nors permite llenar cierta información antes de acceder a la propia app. No se si ya esta establecido pero no hay una manera que puedas volver al wizard anterior para modificar algún parámetro si te equivocas en la información que estas colocando.

**Comment by arnaldos** [comment]
por eso habia dejado un back en el action bar

**Comment by m471c4** [comment]
@arnaldos @nelsonalfo pesando en eso también había incluido un back button en las últimas vistas. Creo que realmente sería bueno tener esa opción disponible.

**Comment by nelsonalfo** [comment]
como dices arnaldo el wizard son una serie de pasos que debes llenar antes de entrar a la app propiamente dicha, y si, tiene sentido lo poder devolverse en caso de querer modificar algo. Esta bien, se deja el back

**Comment by arnaldos** [comment]
Ok perfecto !!! el back en el action bar !!! siendo así esta vista queda lista ?? confirmarme para generarte el doc con los parametros

**Comment by arnaldos** [comment]
@nelsonalfo que nos falta para cerrar este caso ??

**Comment by nelsonalfo** [comment]
agregar el botón **Next Step**

**Comment by arnaldos** [comment]
perfecto !! ya lo ajusto

**Comment by arnaldos** [comment]
@nelsonalfo next step buttom 

![crypto-customers-08](https://cloud.githubusercontent.com/assets/13594347/13856083/c0bf0a2a-ec45-11e5-8ab7-c86182823b5a.jpg)

**Comment by nelsonalfo** [comment]
eso no rompe un poco con el esquema de las otras pantallas del wizard?

**Comment by arnaldos** [comment]
@nelsonalfo si, totalmente de acuerdo pero estabamos trabajando a un solo boton abajo. lo que podemos hacer es colocar una flecha similar a la que esta en el back pero en sentido contrario en el status bar o un boton con la palabra next

**Comment by arnaldos** [comment]
@nelsonalfo ajustes del boton 

#### versión 1

![crypto-customers-11](https://cloud.githubusercontent.com/assets/13594347/13868453/16e13982-ec9b-11e5-9ff7-2f116b2ec6f6.jpg)

#### versión 2

![crypto-customers-10](https://cloud.githubusercontent.com/assets/13594347/13868452/16e12a3c-ec9b-11e5-98bb-f54b258cfa4c.jpg)

**Comment by arnaldos** [comment]
@nelsonalfo @vlzangel que me dicen de este caso solo falta aprobar el boton

**Comment by vlzangel** [comment]
You can close this @arnaldos
