### ISSUE TITLE
Mejorar gráficamente el Providers Wizzard de la Crypto Customer

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#564]
Vista actual
## ![c12](https://cloud.githubusercontent.com/assets/13594347/13232473/7a61184c-d981-11e5-89b8-5565037f8bc5.png)

![c13](https://cloud.githubusercontent.com/assets/13594347/13232474/7a7fcd46-d981-11e5-82fd-8484ba686c8e.png)

**Comment by m471c4** [comment]
@arnaldos @nelsonalfo @abicelis propuesta para este Wizard

![wizardproviders1](https://cloud.githubusercontent.com/assets/13468350/13361712/88fa9aae-dc92-11e5-98ad-1cac7d4647a3.png)

![wizardproviders2](https://cloud.githubusercontent.com/assets/13468350/13361713/8912d4e8-dc92-11e5-9d2b-37bea21b8c20.png)

![wizardproviders3](https://cloud.githubusercontent.com/assets/13468350/13362010/33cd4fca-dc94-11e5-9005-715cedbb3663.png)

**Comment by m471c4** [comment]
@nelsonalfo @abicelis puse un botón de "atrás", en caso de que el user quiera volver al paso anterior y reajustar los settings, déjenme saber qué les parece, y si está bien podemos aplicarlo a las demás vistas.

Acá la vista con los proveedores seleccionados:
![wizardproviders3](https://cloud.githubusercontent.com/assets/13468350/13362425/a01bc4d4-dc96-11e5-9262-40187ae9e35e.png)

**Comment by nelsonalfo** [comment]
en general esta bien, lo que no me convence es el action bar (donde esta el titulo BITCOIN WALLET AND PROVIDERS) Tengo entendido que en los wizards no se muestra el action bar

**Comment by m471c4** [comment]
@nelsonalfo perfecto. Hago los cambios y los subo.

**Comment by m471c4** [comment]
Mejora en las vistas, estandarizándolas con todos los wizards de la customer y la broker.

![wizardproviders1-1](https://cloud.githubusercontent.com/assets/13468350/13386921/d54f8926-de83-11e5-8d54-62507a822139.png)

![wizardproviders1-2](https://cloud.githubusercontent.com/assets/13468350/13386922/d5550824-de83-11e5-92e2-172336a81ec3.png)

![wizardproviders1-3](https://cloud.githubusercontent.com/assets/13468350/13386923/d569f86a-de83-11e5-9470-7ab853a47c62.png)

**Comment by arnaldos** [comment]
@nelsonalfo esto ya esta implementado o nos falta algo ?

**Comment by nelsonalfo** [comment]
todavía no lo hemos implementado pero no veo que les falte algo

**Comment by arnaldos** [comment]
ok perfecto entonces cierro el caso cualquier cosa lo reabrimos
