### ISSUE TITLE
Mejorar gráficamente el Bank Account Wizzard de la Crypto Customer

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#565]
Vista actual

![c8](https://cloud.githubusercontent.com/assets/13594347/13232607/0f314636-d982-11e5-8121-72b2291619a9.png)

**Comment by arnaldos** [comment]
@nelsonalfo  te comparto las mejoras del wizzar. en imagenes por separado y la secuencia avisame si me falta algo adiciona en la secuencia.

## ![crypto customers-06](https://cloud.githubusercontent.com/assets/13594347/13340554/612ee816-dc03-11e5-9e24-32001a7496ee.jpg)

## ![crypto customers-07](https://cloud.githubusercontent.com/assets/13594347/13340555/61351718-dc03-11e5-9bf7-9e512eb71a04.jpg)

## Secuencia

![secuencia-1](https://cloud.githubusercontent.com/assets/13594347/13340589/aa698536-dc03-11e5-8dda-50149bdb10de.jpg)

**Comment by nelsonalfo** [comment]
El titulo "Create Account" quitalo de donde esta y colócalo mejor como el titulo del action bar

**Comment by arnaldos** [comment]
vale perfecto !!

**Comment by arnaldos** [comment]
![crypto-customers-06](https://cloud.githubusercontent.com/assets/13594347/13481605/44f1aad4-e0b9-11e5-94a3-1163734abf40.jpg)

**Comment by arnaldos** [comment]
@nelsonalfo te comparto el ajuste del titulo

**Comment by arnaldos** [comment]
@nelsonalfo @guillermo20 estamos listos con esto cierto ??

**Comment by nelsonalfo** [comment]
Si esta bien esta pantalla. Lo que falta es la pantalla donde se muestra la lista de Cuentas bancarias, que es desde donde vas a poder acceder a la pantalla que esta en este Issue

**Comment by arnaldos** [comment]
ok perfecto !!

**Comment by arnaldos** [comment]
@nelsonalfo bank list 

![crypto-customers-09](https://cloud.githubusercontent.com/assets/13594347/13856062/a7049e88-ec45-11e5-8465-add08f8b1006.jpg)

**Comment by nelsonalfo** [comment]
Esta bien :+1: Solo quitale el Avilable Balance

**Comment by arnaldos** [comment]
perfecto !!

**Comment by arnaldos** [comment]
@nelsonalfo los ajustes 

![crypto-customers-12](https://cloud.githubusercontent.com/assets/13594347/13868445/0109de02-ec9b-11e5-96c2-02393dc6fb99.jpg)

**Comment by arnaldos** [comment]
@nelsonalfo confirmame esto plz

**Comment by vlzangel** [comment]
You can close this @arnaldos
