### ISSUE TITLE
Mejorar gráficamente el Broker List de la Crypto Customer

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#566]
Vista actual

![c5](https://cloud.githubusercontent.com/assets/13594347/13232645/3d609444-d982-11e5-88c2-f34929fcec9c.png)

**Comment by arnaldos** [comment]
@nelsonalfo te comparto las versiones de mejoras para la broker list. recomiendo la versión 4 

Versión 1

## ![crypto customers-01](https://cloud.githubusercontent.com/assets/13594347/13340312/8b2320c6-dc01-11e5-8ba0-e2c2593d8d9a.jpg)

Versión 2

## ![crypto customers-02](https://cloud.githubusercontent.com/assets/13594347/13340313/8b2b8220-dc01-11e5-81c4-b2a2815069e3.jpg)

Versión 3

## ![crypto customers-03](https://cloud.githubusercontent.com/assets/13594347/13340314/8b2d3ce6-dc01-11e5-9faa-e8921a83605f.jpg)

Versión 4
![crypto customers-04](https://cloud.githubusercontent.com/assets/13594347/13340311/8b21e77e-dc01-11e5-80e3-4b248e7595dc.jpg)

**Comment by nelsonalfo** [comment]
la versión 4 es la que mejor se adapta a la implementación y se ve bien! La sección que muestra los precios, es una barra horizontal a la que se puede hacer scroll hacia los lados

**Comment by arnaldos** [comment]
@nelsonalfo perfecto esta quedaría así ? o nos falta una función mas ?

**Comment by nelsonalfo** [comment]
no, básicamente es eso. Se puede dejar así

**Comment by arnaldos** [comment]
perfecto !!!

**Comment by arnaldos** [comment]
@nelsonalfo puedo cerrar el caso ?

**Comment by nelsonalfo** [comment]
puedes cerrarlo
