### ISSUE TITLE
Mejorar gráficamente el Contact Detail de la Crypto Customer

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#567]
Vista actual

![c1](https://cloud.githubusercontent.com/assets/13594347/13232671/5db1f9ea-d982-11e5-9492-2d72f049b1b7.png)

**Comment by m471c4** [comment]
@arnaldos @nelsonalfo @abicelis @guillermo20 acá las primeras versiones para el Contract Details view:

Versión 1:
![contract_details1](https://cloud.githubusercontent.com/assets/13468350/13510981/7d0fe050-e165-11e5-92e2-2c765408233c.png)

Versión 2:
![contract_details2](https://cloud.githubusercontent.com/assets/13468350/13511112/feb6c63c-e165-11e5-86e0-b670db6bf15e.png)

Versión 3:
![contract_details3](https://cloud.githubusercontent.com/assets/13468350/13511129/0faeeb36-e166-11e5-9aec-1637c66140c8.png)

Versión 4:
![contract_details4](https://cloud.githubusercontent.com/assets/13468350/13511169/41c33b18-e166-11e5-8b01-4f2bb9cf6735.png)

@arnaldos ¿tenemos alguna versión de imagen genérica (para cuando no hay foto) para esta plataforma?

**Comment by abicelis** [comment]
Yo voto por v1 y v4. Estan todas super nice tho :)

**Comment by guillermo20** [comment]
yo voto por la v1

**Comment by nelsonalfo** [comment]
También voy por la versión 1

**Comment by m471c4** [comment]
@arnaldos @nelsonalfo @abicelis @GuilleGlad Negotiation details:

Versión 1:
![negotiation_details1](https://cloud.githubusercontent.com/assets/13468350/13531918/19e8ac46-e1fb-11e5-862a-eff268d38296.png)

Versión 2:
![negotiation_details2](https://cloud.githubusercontent.com/assets/13468350/13531916/19ce7bd2-e1fb-11e5-9cda-524c920c2718.png)

Versión 3:
![negotiation_details3](https://cloud.githubusercontent.com/assets/13468350/13531917/19e69f32-e1fb-11e5-8c4a-487aa90ecca1.png)

**Comment by arnaldos** [comment]
@m471c4 @nelsonalfo @abicelis Del primer View del contract detail que aparece, la versión 1 podríamos trabajar con esa, del listado de las clausulas del convenio pudiese andar con la versión 1 quisiera ver los textos, para evaluar su comportamiento así definimos eso creo que seria lo único que falta ! muy buen trabajo dayana !!

**Comment by m471c4** [comment]
¡Gracias @arnaldos! Ya subo la versión 1 con los textos :)

**Comment by nelsonalfo** [comment]
si, los colores van mas en la linea de diseño de la wallet, pero me imagino
que los numero van a ser traslucidos para que resalte el contenido. La version 1 me gusta mas

Otra cosa es el colore del Status Bar (la barra con la hora y el cargador) El color es muy oscuro y rompe con las lineas de diseño de Material Design

**Comment by m471c4** [comment]
@arnaldos @nelsonalfo @abicelis @guillermo20 acá la versión con los textos. Dejé de lado la apariencia "editable" de las variables, y me ocupé de resaltarlas con la tipografía y opacidad. También reduje un poco el tamaño de los números para que no interfiera con el texto.

Hice dos versiones, la primera con los números a la izquierda al 50% de opacidad, y la segunda con los números a la derecha, al 100% de opacidad. Creo que funciona de ambas formas, así que la decisión es de ustedes. 

Versión 1:
![negotiation_det_text1](https://cloud.githubusercontent.com/assets/13468350/13539042/ffaf7754-e21f-11e5-862c-5d22245e3732.png)

Versión 2:
![negotiation_det_text2](https://cloud.githubusercontent.com/assets/13468350/13538975/a3f43eae-e21f-11e5-907b-25f1d3734a1b.png)

**Comment by arnaldos** [comment]
@m471c4 replantea la diagramacion del los textos de la ficha, sobre todo los números tan pegados a los bordes. creo debemos replantear la ficha.. :smile_cat:

**Comment by nelsonalfo** [comment]
me iría por la versión 2 con opacidad, pero no me convence que los numero estén todos pegados al borde de las tarjetas, colócale un margen por favor. No me parece que se entienda que los campos  son editables, especialmente el paso 5 (place to deliver) que también es editable, es decir, que si le doy click el me va a mostrar un menú desplegable

**Comment by m471c4** [comment]
@arnaldos @nelsonalfo vale, voy a replantearlos. Tenía entendido que estos campos ya no podían editarse, porque las tarjetas solo están mostrando información sobre una transacción ya hecha. ¿Me puedes confirmar eso Nelson?

**Comment by nelsonalfo** [comment]
Disculpa @m471c4 ! tienes toda la razón! es que el titulo de Issue me confundió xD o mejor dicho no le paré :stuck_out_tongue_closed_eyes: En este punto esa vista no es editable

**Comment by nelsonalfo** [comment]
pensé que era la pantalla de **Open Negotiation Details**, pero esta es la pantalla de **Closed Contract Details** y **Closed Negotiation Details**

**Comment by m471c4** [comment]
@nelsonalfo jaja no hay problema. ¿Habría que cambiar los nombres de las vistas en el action bar? ¿O pueden quedar como están?

**Comment by nelsonalfo** [comment]
no hace falta cambiar los títulos de action bar, es mas para nosotros, saber diferenciar de acuerdo a su funcionalidad

**Comment by arnaldos** [comment]
@guillermo20 @nelsonalfo avisame cuando este implementado plz y asi cierro el caso

**Comment by arnaldos** [comment]
o si hace falta algo mas

**Comment by nelsonalfo** [comment]
todavía no hemos aplicando los cambios propuestos

**Comment by vlzangel** [comment]
You can close this @arnaldos

**Comment by vlzangel** [comment]
You can close this @arnaldos
