### ISSUE TITLE
Generar vista setting  para la Fermat user

### ISSUE THREAD

**Issue by emmysm** [bitDubai/fermat-graphic-design#568]

**Comment by emmysm** [comment]
![add-03](https://cloud.githubusercontent.com/assets/15143489/13239328/9900785e-d9ab-11e5-81ca-3aa2e7ad05fb.png)
![add-02](https://cloud.githubusercontent.com/assets/15143489/13239345/aa9c50f6-d9ab-11e5-903b-000f9245114f.png)

@nattyco

**Comment by furszy** [comment]
Emmy, fíjate blanco como el settings de android. Y la segunda opción es mucho mejor con el popup que está hecho que tiene radioButtons a la derecha y el texto a la izquierda.
Esta pantalla no tiene que tener cosas raras, cuanto más simple y común mejor.
