### ISSUE TITLE
Mejoras del icono de la Cash Wallet

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#569]
El ajuste consiste en eliminar los billetes del icono, el icono debe mantener su forma.y colores celestes,  se puede probar una versión del a billetera cerrada.

![icon-cash-wallet1](https://cloud.githubusercontent.com/assets/13594347/13239726/a7022d28-d9ae-11e5-9f26-80cddf82bea0.png)

**Comment by arnaldos** [comment]
como vamos con esto ??

**Comment by arnaldos** [comment]
@jayborges ayúdame con esto plz

**Comment by arnaldos** [comment]
@jayborges esta caso se va hacer cargo @m471c4

**Comment by m471c4** [comment]
@arnaldos probé dos versiones de la cartera cerrada, manteniendo la misma paleta cromática. Creo que la opción dos es la que se ve mejor.

Versión 1:
![cashwicon_v1](https://cloud.githubusercontent.com/assets/13468350/13834278/fde072a8-ebbf-11e5-81fb-ada0619e3e63.png)

![cashwicon_v1mu](https://cloud.githubusercontent.com/assets/13468350/13834268/dcb40946-ebbf-11e5-93ff-07d50cafca19.png)

Versión 2:
![cashwicon_v3](https://cloud.githubusercontent.com/assets/13468350/13834270/dcc6f6c8-ebbf-11e5-83dc-50184ce01ca7.png)

![cashwicon_v3mu](https://cloud.githubusercontent.com/assets/13468350/13834271/dcd4d496-ebbf-11e5-8125-9fd1b21a7715.png)

**Comment by arnaldos** [comment]
@m471c4  Me gusta la versión 2 pero lo único es el texto no se lee no se de que manera representarlo, pondría ser algo similar a la "g" de Google que usa en su icono prueba algo así pero con la "C" o en su defecto usa solo la palabra cash.

**Comment by m471c4** [comment]
@arnaldos tienes razón, se pierde. Voy a hacer algunas versiones y las subo.

**Comment by arnaldos** [comment]
perfecto !!

**Comment by m471c4** [comment]
@arnaldo, hice estas cuatro versiones, creo que la 3ra es la mejor.

![cashwalletall](https://cloud.githubusercontent.com/assets/13468350/13835943/e2408088-ebce-11e5-801f-2d6707a16101.png)

Versión 1:
![cashwalletmu1](https://cloud.githubusercontent.com/assets/13468350/13835948/eb70af52-ebce-11e5-8d7f-d53f090693ae.png)

Versión 2:
![cashwalletmu2](https://cloud.githubusercontent.com/assets/13468350/13835951/f3563a84-ebce-11e5-87cb-b70312b2394b.png)

Versión 3:
![cashwalletmu3](https://cloud.githubusercontent.com/assets/13468350/13835954/f9ef614a-ebce-11e5-9612-0f0ddba190dc.png)

Versión 4:
![cashwalletmu4](https://cloud.githubusercontent.com/assets/13468350/13835957/015643ea-ebcf-11e5-84c6-676f998d9f77.png)

**Comment by arnaldos** [comment]
@m471c4 plz prueba una version en blanco colocando la sombra como el de google a ver como se comporta

**Comment by m471c4** [comment]
@arnaldos dos versiones, porque no estoy segura de entender a qué sombra te refieres:

Versión 1 (sombra paralela):
![cashwicon_v8](https://cloud.githubusercontent.com/assets/13468350/13837585/ef069d1a-ebde-11e5-8b56-5769cb977900.png)

![cashwicon_v8mu](https://cloud.githubusercontent.com/assets/13468350/13837586/ef392000-ebde-11e5-9e25-2454f290b3a5.png)

Versión 2 (sombra paralela + sombra a 45º)
![cashwicon_v9](https://cloud.githubusercontent.com/assets/13468350/13837591/fa0b85a4-ebde-11e5-80aa-d97b58c11d5c.png)

![cashwicon_v9mu](https://cloud.githubusercontent.com/assets/13468350/13837592/fa6808b0-ebde-11e5-9f74-b9496afc7dd3.png)

**Comment by arnaldos** [comment]
La versión 2 de la ultima serie, realiza los ajustes que me comentaste. y creo que con eso estamos listo

**Comment by m471c4** [comment]
@arnaldos acá probé engrosar las costuras pero se sigen perdiendo cuando lo vemos pequeño. Sin embargo creo que queda mejor y la proporción de colores va acorde con la interfaz de la app. ¿puede quedar así?

![cashwiconfinal](https://cloud.githubusercontent.com/assets/13468350/13863527/a5f480b8-ec6c-11e5-8eed-8fec807ff3d5.png)

![cashwiconfinal_mu](https://cloud.githubusercontent.com/assets/13468350/13863589/00e28fce-ec6d-11e5-883d-4c9a85bce36d.png)

**Comment by arnaldos** [comment]
@m471c4 perfecto sube los archivos

**Comment by m471c4** [comment]
Vale @arnaldos, ya los subo. Puedes revisar el banner también :)

**Comment by arnaldos** [comment]
listo !!! :+1:

**Comment by m471c4** [comment]
@Luis-Fernando-Molina @arnaldos ya los editables están en el repositorio. Faltaría que @abicelis los implemente. Podemos cerrar el caso.

**Comment by abicelis** [comment]
Great job @m471c4. Manana integro estos recursos a la cash wallet

**Comment by arnaldos** [comment]
perfecto !! me avisas y asi cierro el caso

**Comment by abicelis** [comment]
@arnaldos @m471c4 
Ver [este comentario](https://github.com/Fermat-ORG/fermat-graphic-design/issues/529) en el issue del banner de la cash wallet plz

**Comment by arnaldos** [comment]
@m471c4 plz revisa lo que nos comenta @abicelis referente a los pesos de los PNG

**Comment by abicelis** [comment]
@arnaldos ya hable con @m471c4 y me paso los recursos del icono y banner, puedes cerrar este issue

**Comment by arnaldos** [comment]
perfecto !!!
