### ISSUE TITLE
SUPER ISSUE  Mejoras gráficas para la Asset user wallet

### ISSUE THREAD

**Issue by emmysm** [bitDubai/fermat-graphic-design#570]
Mejoras gráficas para la view Detail #571
Mejoras gráficas para la view Trasaction History #572
Mejoras gráficas para la view home #578
Mejorás gráficas para la navigation drawer #573
Mejoras gráficas para la view Redeem point #579
Improve Asset transfer user view wallet  #724
Mejoras gráficas para la view sell asset #656 
 DAP_transation_history #614 (Change to Transaction for Asset a History Wallet) - all wallets

**Comment by emmysm** [comment]
![rp_ux_02-01](https://cloud.githubusercontent.com/assets/15143489/13266430/4a785a22-da4a-11e5-87a5-6d87589d77bf.png)
![rp_ux_02-04](https://cloud.githubusercontent.com/assets/15143489/13266432/4a7ff1ba-da4a-11e5-9db3-6e8062f99231.png)
![rp_ux_02-06](https://cloud.githubusercontent.com/assets/15143489/13266433/4a81b34c-da4a-11e5-87b0-74365656d2ca.png)
![rp_ux_02-07](https://cloud.githubusercontent.com/assets/15143489/13266434/4a849454-da4a-11e5-9e38-80f04bda8e88.png)
![rp_ux_02-05](https://cloud.githubusercontent.com/assets/15143489/13266435/4a875482-da4a-11e5-9144-5c09b77cacc0.png)

@yojoaquin @acostarodrigo @nindriago @Luis-Fernando-Molina

**Comment by acostarodrigo** [comment]
Van mis comentarios:
- En el Navigation Drawer, no necesitamos My Assets, ya que los assets los mostramos en el home.
- En el Asset Detail, por ahora no vamos a soportar multiples imágenes para los assets. Esta información viaja por P2P y quizás sea mucho tráfico por ahora. Mostremos solamente una imágen.
- En el Asset Detail, tengan en cuenta que el issuer durante la creación define si el asset se puede Redimir y si se puede vender. Quizás no todos los Issuers permitan esto para sus assets. Podemos mostrar estas propiedades como checkboxes, u ocultar los botones si no es posible por ejemplo venderlo. Quizás tengamos que trabajar más opciones.
- En el ASset Detail, las acciones que actualmente estamos soportando son:
  - Redimir Asset: requiere seleccionar un Redeem Point
  - Transferir Asset: requiere seleccionar un Usuario
  - Apropiar Asset: no requiere seleccionar nada
  - Vender Asset: requiere seleccionar un usuario
- La accion de ejemplo Transfer Redeem no existe.
- En la última pantalla de Redeem Point que ponen, recuerden que todas las acciones son sobre un Asset seleccionado, lo cual significa que no es necesario especificar una cantidad de assets. Simplemente el usuario va a redeemir el asset seleccionado. y en esta misma pantalla, se debe poder seleccionar el Redeem Point donde se va a redimir mostrando la foto y la dirección.

#### **Les pido por favor que creemos un issue separado para cada una de las pantallas y no usemos solamente un issue para todo**

Estas son las pantallas:
Asset Home
Asset Detail
Asset Transfer
Asset Sell
Asset Redeeem
Asset Appropriate --> definir si realmente requiere una pantalla adicional.
Transaction History

cc @javafrank

**Comment by emmysm** [comment]
@acostarodrigo ya hago las correcciones. Hay un caso para cada pantalla. Te mencioné en cada uno :smile:
