### ISSUE TITLE
Mejoras gráficas para la view detail de la asset user wallet

### ISSUE THREAD

**Issue by emmysm** [bitDubai/fermat-graphic-design#571]
Proviene del caso #570

**Comment by emmysm** [comment]
![rp_ux_02-04](https://cloud.githubusercontent.com/assets/15143489/13266502/95c122f2-da4a-11e5-9262-585a362bc8d5.png)
@yojoaquin @acostarodrigo @nindriago @Luis-Fernando-Molina

**Comment by emmysm** [comment]
![muckup-01](https://cloud.githubusercontent.com/assets/15143489/13271269/262acf58-da66-11e5-8a52-8d14e67844b8.png)

@acostarodrigo @javafrank

**Comment by acostarodrigo** [comment]
No me convence, pero creo que no se entiende bien lo que quiero explicar.
Hoy nos reunimos a las 4PM de Venezuela asi lo revisamos.

Me explico:
El issuer cuando crea los assets, especifica si el asset se va a poder vender, redimir y transferir. Son propiedades que se definen al momento de la creación.

Cuando el usuario recibe ese asset, le debemos informar qué acciones puede hacer. Estas son las opciones que se me ocurren:
- Que solamente se muestre en el menu desplegable las acciones permitidas: es decir, mostrar las opciones de Redimir, transferir o vender el asset si es que están permitidas para este asset en particular.
- En el detalle del asset, mostrar estas propiedades e indicar si están permitidas por ejemplo, poniendo un tilde en el checkbox. Los checkboxes son read only, el usuario no define si puede o no vender el asset, es decir que no puede quitar los tildes de los checkboxes.
- En el detalle del asset, mostrar las propiedades e indicar si estan permitidas poniendo una imágen de un tilde en verde o una cruz en rojo que indicaria que no.

Yo creo que deberia ser la primer y ultima opción combinadas.

Las propiedades podrian ser:

You can transfer this asset  (Tilde verde / cruz en rojo)
You can redeem this asset  (Tilde verde / cruz en rojo)
You can sell this asset  (Tilde verde / cruz en rojo)
You can appropiate this asset (Tilde en verde ya que siempre se pueden apropiar)

Y en el menu desplegable mostrar solamente las que puede hacer.

**Comment by emmysm** [comment]
![asset detail view-01](https://cloud.githubusercontent.com/assets/15143489/13340046/6035165a-dbff-11e5-84bb-83881ee99263.png)

![asset detail 3](https://cloud.githubusercontent.com/assets/15143489/13340461/93bf4b0a-dc02-11e5-8c81-a635059af0ad.png)

@acostarodrigo

**Comment by acostarodrigo** [comment]
tendria que ser un mix de la propuesta 1 y la 2.
Los indicadores abajo de lo que se puede y no se puede hacer, y tambien en el menu habilitando y des habilitando lo que se puede y no se puede hacer.

**Comment by emmysm** [comment]
![asset detail correcciones](https://cloud.githubusercontent.com/assets/15143489/13341835/476f8326-dc0e-11e5-902b-1a63bd51d0b9.png)

@acostarodrigo

**Comment by acostarodrigo** [comment]
perfect. vamos con esta

**Comment by emmysm** [comment]
Gracias! Vale :smile_cat:

**Comment by emmysm** [comment]
![portafolioo-01](https://cloud.githubusercontent.com/assets/15143489/13365786/4295202c-dca9-11e5-8fee-4f7f3d4552bf.png)

@acostarodrigo @javafrank @yojoaquin

**Comment by acostarodrigo** [comment]
podriamos generar ademas pequeños íconos para cada una de las transacciones. En principio los podriamos poner en el menú.
serian para 
- redeem
- appropriate
- transfer
- sell

**Comment by emmysm** [comment]
Trabajaremos en eso, @acostarodrigo

**Comment by proseuz** [comment]
Propuesta de iconos N°1 @emmysm @acostarodrigo @Luis-Fernando-Molina 
![icono view detail](https://cloud.githubusercontent.com/assets/17308060/13369898/dc7b5f02-dccd-11e5-9848-eb21f3861fa6.jpg)

**Comment by proseuz** [comment]
Propuesta de iconos N°2 @emmysm @acostarodrigo @Luis-Fernando-Molina![icono view detail1](https://cloud.githubusercontent.com/assets/17308060/13369908/0839c002-dcce-11e5-804b-a319628a3035.jpg)

**Comment by proseuz** [comment]
Propuesta de iconos N°3 (cambio en el icono de Appropriate) @emmysm @acostarodrigo @Luis-Fernando-Molina![icono view detail2](https://cloud.githubusercontent.com/assets/17308060/13369919/31ba081a-dcce-11e5-886a-9802c779613c.jpg)

**Comment by proseuz** [comment]
Propuesta de iconos N°4 @emmysm  
![icono view detail4](https://cloud.githubusercontent.com/assets/17308060/13370453/97b6e7ae-dcd9-11e5-9ef5-0fa3bbb0f600.jpg)

**Comment by emmysm** [comment]
Me gusta más la propuesta 4 @jhonmarquez92 . Coloca la tijera un poco más pequeña y la linea punteada un poco más grande. Qué te parecen @acostarodrigo ?

**Comment by proseuz** [comment]
Corrección de la propuesta 4 @emmysm 
![icono view detail4](https://cloud.githubusercontent.com/assets/17308060/13370576/334e86c8-dcde-11e5-97b8-a320960e09c2.jpg)

**Comment by proseuz** [comment]
Cambio en el icono Reedem @emmysm @acostarodrigo ![icono view detail5](https://cloud.githubusercontent.com/assets/17308060/13406365/45369fb0-def5-11e5-8b42-479e3feefd85.jpg)

**Comment by emmysm** [comment]
![asset detail](https://cloud.githubusercontent.com/assets/15143489/13531853/d0864cfc-e1fa-11e5-9aae-1a501cf7d1db.png)

@acostarodrigo @yojoaquin @Luis-Fernando-Molina @javafrank

**Comment by emmysm** [comment]
![rp_ux_02-06-06-04](https://cloud.githubusercontent.com/assets/15143489/13533716/df214eca-e203-11e5-8226-9e75375c050c.png)
![rp_ux_02-06-06-06](https://cloud.githubusercontent.com/assets/15143489/13533717/df67a104-e203-11e5-97aa-eb50fe4c7927.png)

![rp_ux-05-05](https://cloud.githubusercontent.com/assets/15143489/13537505/73be9318-e217-11e5-9bd9-7ff5877fb973.png)

Con los ajustes sugeridos, @yojoaquin
