### ISSUE TITLE
Mejoras gráficas para el navigation drawer de la asset user wallet

### ISSUE THREAD

**Issue by emmysm** [bitDubai/fermat-graphic-design#573]
proviene del caso #570

**Comment by proseuz** [comment]
Propuesta 1 ![rp_ux_04](https://cloud.githubusercontent.com/assets/17308060/13299532/bf3bdc26-db0d-11e5-90cc-7c293fb90b25.jpg) @emmysm @Luis-Fernando-Molina

**Comment by proseuz** [comment]
Propuesta 2![rp_ux_02](https://cloud.githubusercontent.com/assets/17308060/13299668/5457ad6c-db0e-11e5-8a1a-893f75ba2fe4.jpg)
@emmysm @Luis-Fernando-Molina

**Comment by proseuz** [comment]
Propuesta 3![rp_ux_03](https://cloud.githubusercontent.com/assets/17308060/13299707/896ffc16-db0e-11e5-8fed-955a838e8939.jpg) @emmysm @Luis-Fernando-Molina

**Comment by proseuz** [comment]
Propuesta 4![rp_ux_06](https://cloud.githubusercontent.com/assets/17308060/13299751/bbe73ef2-db0e-11e5-9c36-5ad1914d362e.jpg) @emmysm @Luis-Fernando-Molina

**Comment by emmysm** [comment]
@jhonmarquez92  Asegúrate que estés trabajando en RGB, se ven los colores muy pálidos. Replantea la propuesta 2. Vamos a sustituir el icono de settings por el que veníamos trabajando anteriormente. para el icono de home que todos los elementos tengan la misma proporción.

**Comment by proseuz** [comment]
@emmysm @Luis-Fernando-Molina @acostarodrigo   mejora de la propuesta número 2 ![rp_ux_2 2](https://cloud.githubusercontent.com/assets/17308060/13332599/07cafb3a-dbd5-11e5-9c69-38dc0c4a8e79.jpg)

**Comment by acostarodrigo** [comment]
nice :-)

**Comment by emmysm** [comment]
Me gusta :smile: 
Solo un ajuste más, el username centralo un poco de abajo hacia arriba.

@ivonnesantos con este Drawer se trabajará en la otra app, qué te parece?

**Comment by proseuz** [comment]
@emmysm   Username centrado
 ![rp_ux_2 2](https://cloud.githubusercontent.com/assets/17308060/13346831/6304cd30-dc3b-11e5-92d9-afdcea726d94.jpg)

**Comment by proseuz** [comment]
@emmysm @Luis-Fernando-Molina @acostarodrigo @yojoaquin Amplié la barra del username según las sugerencias de google, pero  le quita visibilidad a la imagen. ![rp_ux_2 5](https://cloud.githubusercontent.com/assets/17308060/13346865/b712fb18-dc3b-11e5-924f-268ce679d9cb.jpg)

**Comment by proseuz** [comment]
@emmysm @Luis-Fernando-Molina  @acostarodrigo @yojoaquin  Propuesta 1 con barra amplia![rp_ux_2 6](https://cloud.githubusercontent.com/assets/17308060/13346923/10f6a40e-dc3c-11e5-96ac-0a6f3fe3d019.jpg)

**Comment by proseuz** [comment]
@emmysm @Luis-Fernando-Molina @acostarodrigo @yojoaquin Propuesta 2 con barra amplia 
![rp_ux_2 3](https://cloud.githubusercontent.com/assets/17308060/13347003/bbd78f0a-dc3c-11e5-8046-8db23e2183a5.jpg)

**Comment by ivonnesantos** [comment]
@jhonmarquez92  Me voy por esta
![image](https://cloud.githubusercontent.com/assets/15238660/15366419/081aa31a-1cee-11e6-8ac7-df7c1ad2181b.png)
Observaciones
1-Quitar la curva de la esquina de arriba dejar solo la de la esquina de abajo.
2- el recuadro de la transparencia con el nombre lo puedes colocar el negro o blanco con la transparencia en menor porcentaje al que tiene, es decir debe verse un poco más transparente.
3- El tamaño del recuadro puede ser de 38px de alto y la tipografía del nombre puede tener 14px.

eso es todo por ahora

**Comment by pennyxz** [comment]
@jhonmarquez92 Yo tambien me voy por esa como lo menciona @ivonnesantos. Tambien acotar que podria ponerse el logo centrado de la Wallet User en la parte mas baja del navigation drawer.

**Comment by proseuz** [comment]
@pennyxz @ivonnesantos  creé una versión negativa del logo de la Asset User  
![navigation_drawer_asset_user-01](https://cloud.githubusercontent.com/assets/17308060/15372073/7b076b5a-1d08-11e6-8c05-c29a95e57701.png)

**Comment by ivonnesantos** [comment]
Mejor sio que creo que a la carterita del logo le falta una de las figuras que estan dentro

**Comment by ivonnesantos** [comment]
Tambien puedes poner el logo con cierta transparencia

**Comment by ivonnesantos** [comment]
Tambien puedes poner el logo con cierta transparencia

**Comment by ivonnesantos** [comment]
Si te falta un triángulo pequeñito blanco entre el circulo y el triangulo grande

**Comment by proseuz** [comment]
@ivonnesantos  este es el logo original Ivonne
![icon_ asset_user_wallet_definitivo-01](https://cloud.githubusercontent.com/assets/17308060/15372857/6284ccae-1d0c-11e6-99c1-33c627803dd8.png)
Logo al 65% de opacidad
![navigation_drawer_asset_user3-01](https://cloud.githubusercontent.com/assets/17308060/15372858/6298f79c-1d0c-11e6-99de-3b3b8eb65716.png)

**Comment by ivonnesantos** [comment]
@jhonmarquez92 se ve bien genera los recursos y el archivo de indicaciones

**Comment by proseuz** [comment]
Vale @ivonnesantos
