### ISSUE TITLE
Mejoras gráficas para la view redeem asset

### ISSUE THREAD

**Issue by emmysm** [bitDubai/fermat-graphic-design#575]
Proviene del caso #570

**Comment by emmysm** [comment]
![rp_ux_02-06](https://cloud.githubusercontent.com/assets/15143489/13266466/707f4492-da4a-11e5-8942-aa44f3b3ae55.png)

@acostarodrigo @yojoaquin @nindriago @Luis-Fernando-Molina

**Comment by emmysm** [comment]
![rp_ux_02-06](https://cloud.githubusercontent.com/assets/15143489/13267342/fece48b6-da4e-11e5-8981-0564cf85bfe5.png)
@acostarodrigo @yojoaquin @nindriago @Luis-Fernando-Molina @javafrank

**Comment by acostarodrigo** [comment]
Mis comentarios:
- El título debe ser Redeem Asset (Transfer Asset es otra pantalla distinta)
- El Asset se redime en un Redeem Point, por lo tanto deben mostrar Redeem Points y no usuarios. 
- Solamente se van a mostrar los Redeem Points donde el asset en particular es redimible, por lo tanto no va a ser una gran cantidad de Redeem Points. 3 o 4 como mucho, por lo tanto creo que lo mejor seria mostrarlos en cuadrados con la imágen del Redeem Point y datos básicos como el nombre y la dirección.

cc @javafrank
