### ISSUE TITLE
SUPPERISSUES DAP_Redeem_point

### ISSUE THREAD

**Issue by ivonnesantos** [bitDubai/fermat-graphic-design#577]
DAP_home_redeem_point #611 
 DAP_detail_redeem_point #612 
 DAP_history_redeem_point #613 
 DAP_transation_history #614  (Change to Transaction for Asset a History Wallet) - all wallets

**Comment by ivonnesantos** [comment]
![maqueta-01](https://cloud.githubusercontent.com/assets/15238660/13265482/4f339888-da45-11e5-8b2e-bf2d8d47edc8.jpg)

@yojoaquin @acostarodrigo Propuesta de maqueta completa de la app reddeem point, la pantalla de detail no se si sea necesaria o le quieren agregar algo más.

**Comment by acostarodrigo** [comment]
Va quedando bien. Mis correcciones son:
- No es necesario mostrar los BTC del Asset en el home. Quizas en el header del Asset, además del nombre, deberíamos mostrar la imágen y nombre del issuer.
- No creo que deberíamos mostrar los tres estados al mismo tiempo, sino el Accept y el Reject. Si el Asset es aceptado, entonces luego se puede entregar, no les parece?
- Creo que queda bien mostrar los Assets por fecha.
- Los nombres de los tabs creo que los deberiamos cambiar. Uno podria ser: Incoming o In Progress, y la otra Delivered o History.
- Estoy de acuerdo con hacer el asset Detail, ahi podriamos mostrar más detalle.

cc @javafrank

**Comment by ivonnesantos** [comment]
"deberíamos mostrar la imágen y nombre del issuer."
Pero explicame el issuer no es mismo usuario de la redeem point?
"No creo que deberíamos mostrar los tres estados al mismo tiempo, sino el Accept y el Reject. Si el Asset es aceptado, entonces luego se puede entregar, no les parece?"
Te parece que la opción de entregado quedara solo en el detail?

**Comment by acostarodrigo** [comment]
> Pero explicame el issuer no es mismo usuario de la redeem point?

No. En DAP existen tres actores distintos cada uno con roles distintos:
- Asset Issuer: por ejemplo, McDonalds, es el creador del Asset.
- Asset User: un cliente cualquier de McDonalds, es el que recibe el asset.
- Redeem Point: un local de McDonalds, es donde el asset se redime.

Un Redeem Point, puede redimir Assets de multiples issuers, por eso te digo de mostrar tambien el Issuer. Por ejemplo, un centro de canje que es un Redeem Point, puede recibir assets de McDonalds, Coca cola, etc.

> Te parece que la opción de entregado quedara solo en el detail?

Creo que no, porque obligaría al Redeem Point a hacer un click más para poder marcarlo como entregado, y si tiene una cola de gente, como por ejemplo podría ser en Mc Donalds, podría ser contraproducente.

Digo de no mostrarlo junto porque el Asset no va a existir realmente, hasta que no lo acepte, entonces debemos prevenir que lo marque como entregado.

**Comment by ivonnesantos** [comment]
Entonces @acostarodrigo podemos hacer que una vez aceptado los botones de aceptado y rechazado desaparezcan y en su lugar este el de entregado?

**Comment by ivonnesantos** [comment]
Lo podemos hacer en gris y cuando el actor pulse se pone verde y ya luego pasa a history @acostarodrigo para que sea mas interactivo y que el actor sepa que existe una acción

**Comment by acostarodrigo** [comment]
exacto.

**Comment by ivonnesantos** [comment]
@acostarodrigo hice dos alternativas para organizar los elementos dentro del datail y el home segun las correcciones que me hiciste
@yojoaquin 

Alternativa 1 
![maqueta-01](https://cloud.githubusercontent.com/assets/15238660/13292467/10443480-daee-11e5-8026-a13af217837d.jpg)

Alternativa 2
![maqueta-02](https://cloud.githubusercontent.com/assets/15238660/13292501/2f714a64-daee-11e5-9664-5b08b6164916.jpg)

**Comment by ivonnesantos** [comment]
@acostarodrigo @yojoaquin un detalle que estoy viendo es que ponerle menú de opciones no es necesario ya que todo se puede mantener en el navigation Drawer o lo contrario de tener menú de opciones no veo necesario en navigation drawer pero como todas se están trabajando con esas funciones no se las quise quitar

**Comment by acostarodrigo** [comment]
> un detalle que estoy viendo es que ponerle menú de opciones no es necesario ya que todo se puede mantener en el navigation Drawer o lo contrario de tener menú de opciones no veo necesario en navigation drawer pero como todas se están trabajando con esas funciones no se las quise quitar

creo que el navigation drawer es para acciones generales de la wallet, mientras que el menú de opciones son para activar acciones específicas de la pantalla que estamos viendo, en este caso el asset detail. Pero yo no sé mucho de UX, @yojoaquin vos qué pensás?

Con respecto a las propuestas, algo no me queda claro. Al seleccionar un asset, el mismo se expande y ahi se muestra la foto del usuario? Y luego si se selecciona la foto del usuario pasarìamos a otra pantalla del detalle del asset?

Creo que otra alternativa sería poner los botones del accept y reject en el header del asset, para que sea pueda aceptar sin tener que expandirlo.

**Comment by ivonnesantos** [comment]
al Seleccionar el asset te lleva a la pantalla de detail que tiene la foto del user por default pero pero si el actor quiere ver la foto del asset mas grande puede deslizar de derecha a izquierda para verla pero la pantalla detail es una sola. Nunca tienes que expandir nada los botones para aceptar y rechazar estan disponibles en todo momento hasta que acepte luego en su lugar aparece el boton de entregar estos botones se encuentran en la lista del home y la pantalla de detail @acostarodrigo

**Comment by acostarodrigo** [comment]
y a esta pantalla que no muestra la imagen del usuario grande cómo se llega?
![image](https://cloud.githubusercontent.com/assets/9518556/13297297/66139460-db10-11e5-979c-a3a08feaf686.png)

**Comment by ivonnesantos** [comment]
@acostarodrigo A esa se accede por el Tap que esta en el home que dice HISTORY esa pantalla sirve solo de registro

**Comment by acostarodrigo** [comment]
ah ok. Está bien agrupar por fecha.

Pero que el historial sea del tipo transaccional, es decir mostrar una sola fila por operación, en la que figure el asset y el usuario con sus fotos.

**Comment by ivonnesantos** [comment]
![rp_ux_01-03-03](https://cloud.githubusercontent.com/assets/15238660/13297752/1147611e-db06-11e5-8b5f-7c00b88fd366.jpg)
@acostarodrigo algo asi

**Comment by ivonnesantos** [comment]
o algo como esto? @acostarodrigo 
![rp_ux_01-06](https://cloud.githubusercontent.com/assets/15238660/13298092/952ffdfa-db07-11e5-8f34-9190793e2647.jpg)

**Comment by acostarodrigo** [comment]
algo como esta última pantalla. Pero sin mostrar el 2BTC ni el Status 16:00. solamente la fila de arriba con el nombre del asset y el nombre del usuario.

**Comment by acostarodrigo** [comment]
Al seleccionar cualquier asset, ya sea de los pendientes o del historial, mostraríamos la pantalla de Asset Detail donde podemos mostrar más cosas.

Tienen que pensar que quien ve esto es un cajero de Mc Donalds por ejemplo, por lo tanto hay que mostrar la información necesaria y visible a simple vista.

Agreguemos la el botón de Buscar por nombre tambien con el dibujo de la lupa.

**Comment by ivonnesantos** [comment]
@acostarodrigo pero al menos el status debería quedar opino yo para que se lleve un registro de lo que sucedió con ese asset se le puede poner chiquito el icono sobre la foto del asset te parece?

**Comment by acostarodrigo** [comment]
Es que todos los que van al history son assets entregados, no veo otro estado posible para el historial.

Si el asset no se acepto, entonces no lo mostramos en ningun lado. 
Una vez aceptado, lo que queda en entregarlo. Una vez entregado va al history

**Comment by ivonnesantos** [comment]
Los rechazados no van al historial?

**Comment by acostarodrigo** [comment]
no.

**Comment by ivonnesantos** [comment]
![rp_ux_01-06](https://cloud.githubusercontent.com/assets/15238660/13299531/bef25ec0-db0d-11e5-9229-f1a49ad359d0.jpg)
@acostarodrigo una vez corregido todo cual de las alternativas te pareció mejor?

**Comment by ivonnesantos** [comment]
Corrección con la foto rectangular como se definió en la reunión de 24/02
![maqueta-01](https://cloud.githubusercontent.com/assets/15238660/13305208/e43484ce-db2b-11e5-8828-c2b9f739bed3.jpg)
@acostarodrigo @yojoaquin

**Comment by acostarodrigo** [comment]
perfecto.
