### ISSUE TITLE
Mejoras gráficas para la view home asset user wallet

### ISSUE THREAD

**Issue by emmysm** [bitDubai/fermat-graphic-design#578]
proviene del caso  #570

**Comment by emmysm** [comment]
![rp_ux_02-09](https://cloud.githubusercontent.com/assets/15143489/13272223/bd1a4e38-da6c-11e5-9447-1a0697d7493e.png)

@acostarodrigo @javafrank

**Comment by acostarodrigo** [comment]
qué es el primer asset que se muestra?
Recordá por favor que todos los assets dependen y están agrupados por un issuer. Por lo tanto un asset no puede estar por fuera de la agrupación de los issuers.

**Por favor, es necesario que entiendan lo que estamos tratando de mostrar**

Hacete un ejemplo de por ejemplo un issuer que dice que tiene tres assets, y adentro de ese agrupado tres assets. 

Cada fila es un asset, no es necesario mostrar 1 Asset para cada uno.

**Comment by emmysm** [comment]
![rp_ux_-09-09](https://cloud.githubusercontent.com/assets/15143489/13294397/f6f1fcee-daf5-11e5-9889-d185004b101e.png)

@acostarodrigo

**Comment by acostarodrigo** [comment]
está ok. Quitá el "1 Asset" que mostras al lado de cada asset ya que no es necesario porque cada fila es un asset.

La imagen del Asset debe ocupar mayor tamanio ya que es lo más importante. Prácticamente la mitad de la pantalla, de acuerdo a lo que hablamos con Luis,

**Comment by emmysm** [comment]
![rp_ux_02-07-03](https://cloud.githubusercontent.com/assets/15143489/13299581/ef2969c6-db0d-11e5-93ee-aca576064a90.png)

**Comment by javafrank** [comment]
@emmysm @acostarodrigo El título de esta pantalla debería ser "My Assets", y creo que se puede aprovechar el espacio de la derecha de cada asset para mostrar algo mas de información.

Saludos,

**Comment by acostarodrigo** [comment]
Además, mostremos más grande la foto y pongamos la descripción del asset tambien.

**Comment by emmysm** [comment]
![my asset view-01](https://cloud.githubusercontent.com/assets/15143489/13335450/5f975e2c-dbe3-11e5-86d8-32e26a05a2fe.png)

@acostarodrigo @javafrank

**Comment by acostarodrigo** [comment]
Vamos con la propuesta 2.

**Comment by emmysm** [comment]
![asset detail-04](https://cloud.githubusercontent.com/assets/15143489/13415415/b4865c52-df2c-11e5-80d2-79a6cfd823c6.png)
![asset detail-03](https://cloud.githubusercontent.com/assets/15143489/13415416/b486fd60-df2c-11e5-96ed-51a055d9b677.png)

@yojoaquin

**Comment by emmysm** [comment]
![rp_ux_02-06-06-06-03](https://cloud.githubusercontent.com/assets/15143489/13537030/1c85e92c-e215-11e5-9c62-b8438bc65dfd.png)
![asset detail-03](https://cloud.githubusercontent.com/assets/15143489/13545569/d00badea-e262-11e5-87f8-0cfebe235c36.png)

@yojoaquin dos propuestas de colores. Me inclino más por el background blanco, qué opinas?

**Comment by yojoaquin** [comment]
Sí. La opción blanca va. Podemos mejorar esas flechitas? Las veo muy 1990.

**Comment by javafrank** [comment]
attached a set of proposals for the user wallet home, changing to card style and removing the asset detail for a better user experience, according to metting: https://www.youtube.com/watch?v=yeokWJ650rY

![img_20160316_092721](https://cloud.githubusercontent.com/assets/13275281/13829006/d22f123c-eb96-11e5-891b-67b5aff3e89a.jpg)

![img_20160316_092750](https://cloud.githubusercontent.com/assets/13275281/13829064/24b3dfec-eb97-11e5-8bf8-e341b022e03c.jpg)

![img_20160316_092803](https://cloud.githubusercontent.com/assets/13275281/13829109/5ee5b032-eb97-11e5-8495-4106024948a5.jpg)

![img_20160316_092823](https://cloud.githubusercontent.com/assets/13275281/13829165/b51c73be-eb97-11e5-8bc6-2020a2643a65.jpg)

![img_20160316_092844](https://cloud.githubusercontent.com/assets/13275281/13829196/e6a061de-eb97-11e5-85b3-7eb084f310a0.jpg)

@acostarodrigo @Luis-Fernando-Molina @yojoaquin @emmysm @ivonnesantos @nindriago

**Comment by nindriago** [comment]
![1](https://cloud.githubusercontent.com/assets/13187461/13833031/d9056012-ebb3-11e5-8ec8-aa9e28838788.png)

**Comment by emmysm** [comment]
![propuestas-01](https://cloud.githubusercontent.com/assets/15143489/13834115/7254701e-ebbe-11e5-8dc0-440bcd7bffd5.png)

@Fermat-ORG/skynet-team @javafrank

**Comment by ivonnesantos** [comment]
Emmy me gusta pero yo pienso que el navegador lo debes continuar trabajando en azul y para que no se repita el color en la card lo puedes poner en otro tono de esa misma gama de azul es una sugerencia

**Comment by emmysm** [comment]
![propuestas-01](https://cloud.githubusercontent.com/assets/15143489/13834896/eaf8f156-ebc4-11e5-877e-05d1b033cd4f.png)
![propuestas-02](https://cloud.githubusercontent.com/assets/15143489/13834897/eb1c9b2e-ebc4-11e5-85f5-74a8ad8f52f1.png)

**Comment by emmysm** [comment]
@ivonnesantos gracias, ya hice otras propuestas de color :smile_cat: 

@Fermat-ORG/skynet-team @javafrank

**Comment by emmysm** [comment]
![propuestas-02](https://cloud.githubusercontent.com/assets/15143489/13835213/eb024ff0-ebc7-11e5-83df-3e8c782630f9.png)
![sin-titulo-2](https://cloud.githubusercontent.com/assets/15143489/13835214/eb28281a-ebc7-11e5-8bb8-6343acb25328.png)

@javafrank  @Fermat-ORG/skynet-team

**Comment by javafrank** [comment]
Beautiful, but i think that "Pending" string should not be, and the clock icon should be in the up-right corner, above "2 hours ago" string. Also, the Asset name i think should be a little bigger. What do you think?

Muy bonito, pero pienso que la etiqueta "Pending" no debería estar, y el icono del reloj debería estar en la esquina superior izquierda, arriba de "2 hours ago". Además, el nombre del asset creo que debería ser un poco mas grande. Que opinan?

**Comment by javafrank** [comment]
in the issuer or user name, showed at top of card should be added "Delivered by", above.

en el nombre del issuer o user, mostrado en la parte de arriba de la card, debería estar acompañado el texto "Delivered by", arriba de este.

**Comment by emmysm** [comment]
Ya genero los ajustes. @javafrank

**Comment by emmysm** [comment]
![home_desing](https://cloud.githubusercontent.com/assets/15143489/13860998/3ceee310-ec5d-11e5-9854-076c41c65497.png)

@Fermat-ORG/skynet-team @javafrank con los ajustes que sugirió Frank y otra propuesta de color.

**Comment by pennyxz** [comment]
I like the last changes. Should a tag be added somewhere close the date? Maybe the final user won't understand this date (Like I do now, but the difference is that I can guess it). @Fermat-ORG/skynet-team @javafrank what do you think?

**Comment by javafrank** [comment]
i agree with @pennyxz , maybe like older UI, "EXP" text above the date with align to right, maybe in bold or another color.
i don't like the clock icon position, may be be under "2 hour ago" text.

estoy de acuerdo con @pennyxz , tal vez como en la UI antigua, un texto "EXP" encima de la fecha alineada a la derecha, pudiera ser en bold u otro color.
no me gusta la posición del icono del reloj, pudiera estar debajo del texto "2 hour ago".

**Comment by emmysm** [comment]
![propuesta-finaal](https://cloud.githubusercontent.com/assets/15143489/13866522/55bf4df0-ec88-11e5-9ab2-180c68666c9f.png)

correcciones
@javafrank  @Fermat-ORG/skynet-team

**Comment by pennyxz** [comment]
I think it's perfect now @emmysm . @javafrank @Fermat-ORG/skynet-team what do you think?

**Comment by yojoaquin** [comment]
I think those icons are really difficult to tap on. May be we should place
an actions button as it was previously designed. Also what if the name of
the asset is larger than "asset name"?
Lets use real assets names so we know how they will look like, try "Coupon
for 20% discount on Shirts" for instance.

On Fri, Mar 18, 2016 at 2:52 PM, Penelope Quintero <notifications@github.com

**Comment by nindriago** [comment]
the icons are well, I was inspired by Instagram (easy and simple) just separate them a little more with each other.
EXP as you comment, lower it a bit and make adequate space.

**Comment by emmysm** [comment]
ok, i will generate the adjustments :) @nindriago @yojoaquin

**Comment by emmysm** [comment]
@Fermat-ORG/skynet-team @javafrank @yojoaquin 

![home_desing-ajustes](https://cloud.githubusercontent.com/assets/15143489/13894914/4ba8fca0-ed3f-11e5-9c40-d5327057c5da.png)

**Comment by nindriago** [comment]
WOW, I LIKED :+1: - Great @emmysm

**Comment by javafrank** [comment]
I like it too, good job! @emmysm

**Comment by pennyxz** [comment]
Perfect.

**Comment by acostarodrigo** [comment]
Super! great Job!

**Comment by emmysm** [comment]
Thanks   @Fermat-ORG/skynet-team @javafrank  :blush:
