### ISSUE TITLE
Mejoras gráficas para la view redeem point de la asset user wallet

### ISSUE THREAD

**Issue by emmysm** [bitDubai/fermat-graphic-design#579]
proviene del caso #570

**Comment by emmysm** [comment]
![rp_ux_02-05](https://cloud.githubusercontent.com/assets/15143489/13266671/593089f8-da4b-11e5-9303-0830c2845524.png)

@yojoaquin @acostarodrigo @nindriago @Luis-Fernando-Molina

**Comment by yojoaquin** [comment]
Emmy de dónde viene Place?
Los redeem points se van a listar uno abajo de otro luego de Amount. Con su foto, nombre y dirección.
Edit: El asset name lo pondría arriba de la foto del asset. En el header en lugar de donde dice "redeem point" debería decir "Redeem Asset".

**Comment by acostarodrigo** [comment]
Recuerden que no va a ir el Amount, solamente permitiremos redimir un asset a la vez.

El amunt lo vamos a evaluar en la Issuer Wallet, para que el issuer pueda enviarle el asset a, por ejemplo, 100000 usuarios a la vez.

**Comment by emmysm** [comment]
![redeem asset](https://cloud.githubusercontent.com/assets/15143489/13271953/c4d1fd58-da6a-11e5-9cf0-54856ecb4cba.png)
@acostarodrigo @javafrank

**Comment by acostarodrigo** [comment]
Pero por qué seguís mostrando el botón que dice Select Redeem Point? si los redeem points los vamos a mostrar listados abajo? Ese boton se debe quitar.

No me convence la parte de arriba con una imagen chiquita del asset y la info que estamos mostrando.

**Comment by emmysm** [comment]
![rp_ux_02-04-04-07](https://cloud.githubusercontent.com/assets/15143489/13292691/fc049b76-daee-11e5-8489-61e391b5727e.png)

Ya quité el botón Rodrigo. En mi primera propuesta no se me indicó que se debía quitar. Solo que no se debía colocar el Amount.
Pido por favor resolver todas las inquietudes que se tengan por ventana para así facilitar el proceso, como se hizo en las otras.

Pregunto, se puede en esta view ampliar la imagen del Asset al presionar la foto de la tab de la parte superior?

En los tab de abajo estarán por lista, se puede ver la dirección, fecha y hora del Redeem cuando desplegas la opcion. Esa información está bien estructurada? 

@acostarodrigo

**Comment by emmysm** [comment]
![sin titulo-3-01](https://cloud.githubusercontent.com/assets/15143489/13295299/5f35807e-dafa-11e5-9cf2-76cec4086a8f.png)

**Comment by acostarodrigo** [comment]
> Pregunto, se puede en esta view ampliar la imagen del Asset al presionar la foto de la tab de la parte superior?

Si, pero tene en cuenta que venis de la pantalla de Asset Detail en la que el Asset ya se ve grande ocupando la mitad de la pantalla. Es necesario volver a ocupar mitad de la pantalla volviendo a mostrar el asset? Creo que seria mejor ocupar pantalla mostrando lo Redeem Points.

> En los tab de abajo estarán por lista, se puede ver la dirección, fecha y hora del Redeem cuando desplegas la opcion. Esa información está bien estructurada?

La info a mostrar es: 
- foto del redeem point
- Nombre del Redeem Point
- Dirección

Fecha y hora no existen.

**Comment by emmysm** [comment]
Chevere, ya hago los ajustes

**Comment by emmysm** [comment]
![rp_ux_02-07](https://cloud.githubusercontent.com/assets/15143489/13299599/018d5a32-db0e-11e5-9e37-1cf721f2cf4a.png)

**Comment by acostarodrigo** [comment]
esta ok.
Te habia pedido tambien de mostrar cuadrados como en la Community ya que lo normal va a ser tener 2 o 3 como máximo de redeem points disponibles

**Comment by emmysm** [comment]
![redeem asset-01](https://cloud.githubusercontent.com/assets/15143489/13336386/e1fd926a-dbe7-11e5-936a-8b8b809fb1ae.png)

@acostarodrigo , la segunda propuesta usa scroll

**Comment by acostarodrigo** [comment]
Vamos con la 1.

**Comment by proseuz** [comment]
@emmysm @Luis-Fernando-Molina @yojoaquin @acostarodrigo  Propuesta gráfica 1![reedem asset 3](https://cloud.githubusercontent.com/assets/17308060/13345543/c6b3abb2-dc31-11e5-8825-2910decd81d8.jpg)

**Comment by proseuz** [comment]
@emmysm @yojoaquin @acostarodrigo @Luis-Fernando-Molina  Propuesta gráfica 2![reedem asset 2](https://cloud.githubusercontent.com/assets/17308060/13345582/17a5811c-dc32-11e5-8c3b-6bfac62a8ef5.jpg)

**Comment by proseuz** [comment]
@emmysm @yojoaquin @acostarodrigo @Luis-Fernando-Molina  Propuesta gráfica 3![reedem asset 1](https://cloud.githubusercontent.com/assets/17308060/13345594/395a4d06-dc32-11e5-83fb-84cd18fe2eb2.jpg)

**Comment by emmysm** [comment]
Muy bien! Me gusta la propuesta 2. Genera una propuesta con colores planos, sin bisel a ver con cual nos quedamos . Todas las fotos deben quedar del mismo tamaño, veo unas un poco más anchas que otras. Mejor no usemos el icono de location :smile_cat: . @jhonmarquez92

**Comment by proseuz** [comment]
@emmysm @Luis-Fernando-Molina  Propuesta colores planos
![reedem asset 4](https://cloud.githubusercontent.com/assets/17308060/13358844/7a101f00-dc83-11e5-9d12-7bd853d77533.jpg)

**Comment by yojoaquin** [comment]
Yo lo veo así.. por la longitud de los nombres y las direcciones de los lugares.

![select-a-redeem-point](https://cloud.githubusercontent.com/assets/16956971/13359631/0db9011c-dc94-11e5-8dcd-72160deeec52.gif)

**Comment by emmysm** [comment]
Me gusta más así, @yojoaquin

**Comment by acostarodrigo** [comment]
adhiero, queda mejor así.

**Comment by javafrank** [comment]
si no existe ningún redeem point en la lista, qué debería ir en ese espacio?

**Comment by emmysm** [comment]
Quedaría la pantalla en blanco o se pueden agregar redeem desde esa lista para colocarle un icono?
@javafrank @yojoaquin

**Comment by yojoaquin** [comment]
Debería aparecer una leyenda que diga: "En este momento no se encuentra
ningún lugar disponible para redimir el asset."

**Comment by Lilynwn** [comment]
![redeemenviar-01](https://cloud.githubusercontent.com/assets/17750301/13721261/84b723de-e7f2-11e5-8ea7-c5703a3c9c99.png)
@acostarodrigo @emmysm @Luis-Fernando-Molina

**Comment by emmysm** [comment]
![sin titulo-2](https://cloud.githubusercontent.com/assets/15143489/13976620/ad5ecfa4-f093-11e5-91a4-cc024c4fbb8d.png)

@Fermat-ORG/skynet-team @yojoaquin @javafrank

**Comment by pennyxz** [comment]
I like proposal number 3. But the selected redeem point its not that clear. Maybe the check can be the same color as the redeem point name? Or having a border. I think that there must be a button in the top-right corner named Redeem that displays the confirmation dialog, that way, if user selected a redeem point by error, he doesn't get displayed with this Confirmation Dialog all of sudden and would be able to see the actual selection. If the user selects and the confirmation dialog gets displays at once, then he would never see the check.

The box in the Haggar Clothing's Redeem Point is confusing. What is it?

Me gusta mas la propuesta 3. Pero el Redeem Point seleccionado no se ve tan claro. Tal vez puedes poner el check de otro color (El mismo color de los nombres de los Redeem, tal vez) o ponerle un borde. Pienso que un botón debe ser mostrado en la esquina superior derecha para Redeem, que al ser apretado muestre la ventana de confirmación. De esa forma, si el usuario por error selecciono a un redeem point, no se le despliegue este Dialog de repente, y también así podrá ver que fue lo que se selecciono. Si un usuario es seleccionado y de una vez muestra el Dialog de confirmación, no vería el check.

La cajita o icono en el Redeem de Haggar Clothings es confuso. ¿Que es?

**Comment by emmysm** [comment]
Ya genero los ajustes, @pennyxz, no me parecía la idea que no llevara ningún botón para reedimir. Ese icono indica que el redeem ha sido enviado.

**Comment by javafrank** [comment]
i like the proposal 3, i think the check needless because when tap the user the app must go to the action

me gusta la propuesta 3, pienso que el check no es necesario debido a que cuando se seleccione al usuario se debe ir a la accion directamente.

**Comment by pennyxz** [comment]
@javafrank the problem of what you commented is that is too prone to user error. Even if the action includes a confirmation, user has to select to close the dialog if he mistakes and see users again. User will swype down and up often in that fragment, so a tap mistake will happend a lot. This action can't be direct.

El problema de lo que comenta @javafrank es que es muy propenso a errores. Incluso si la acción incluya una confirmación, el usuario va a tener que ocultar la confirmación y volver a seleccionar el usuario. En esta ventana, el usuarios hará swype de arriba hacia abajo muchas veces, por lo que se le puede escapar un tap que le hará mostrar esta ventanita de confirmación. Por eso menciono lo del boton, por que esta acción no debería ser directa.

**Comment by emmysm** [comment]
![redeem-02](https://cloud.githubusercontent.com/assets/15143489/14002024/7388fd80-f11b-11e5-9889-0f7dc6a12229.png)

@pennyxz

**Comment by pennyxz** [comment]
I like both 1 and 2.
@Fermat-ORG/skynet-team @javafrank Help me choosing, please!

@emmysm Don't forget the checks suggestions when the RP is selected.
