### ISSUE TITLE
Organizar las fuentes del isologo Fermat PIP en el repositorio

### ISSUE THREAD

**Issue by m471c4** [bitDubai/fermat-graphic-design#58]
Viene del #10

Organizar debidamente las fuentes del isologo, así como los distintos tamaños sugeridos, en sus respectivos formatos (png, ico, etc).

**Comment by arnaldos** [comment]
@m471c4 @Luis-Fernando-Molina @jonathanborges3d Los fuentes ya estan organizados en el repo aca les dejo el enlace https://github.com/arnaldos/fermat-graphic-design/tree/master/Logos_sub-app_fermat/Fermat_PIP

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina por favor avísame si todo esta en orden, de estar todo correcto podemos cerrar el caso.

**Comment by Luis-Fernando-Molina** [comment]
nop, están en tu repo, no en el de bitDubai. Pedile ayuda a tus compañeros de equipo para actualizar el repo de bitDubai please.
