### ISSUE TITLE
SUPPERISSUES DAP_Asset_Wallet_Issuer

### ISSUE THREAD

**Issue by ivonnesantos** [bitDubai/fermat-graphic-design#582]
DAP__home_Asset_Wallet_Issuer #646 
 DAP__detail_Asset_Wallet_Issuer #647 
 DAP__contactos_Asset_Wallet_Issuer #649 
 DAP__stats_Asset_Wallet_Issuer #767 
 DAP_transation_history #614 (Change to Transaction for Asset a History Wallet) - all wallets

**Comment by ivonnesantos** [comment]
Maqueta @acostarodrigo @yojoaquin 
![maqueta-01](https://cloud.githubusercontent.com/assets/15238660/13305290/711b7da2-db2c-11e5-8f93-a650badfc8fc.jpg)

**Comment by acostarodrigo** [comment]
muy buena. Pero si son 5000 assets a enviar? Ese semi circulo sería manejable?

Para el issuer, manejamos el concepto de Grupos de Usuarios. Esta funcionalidad ya existe. Quizas podriamos separar los users y grupos en dos tabs.

cc @furszy para que veas lo del circulo para seleccionar cantidad. Esas cantidades pueden ser pequeñas o muy grandes.

**Comment by ivonnesantos** [comment]
@acostarodrigo si tienes razon en lo del circulo estaba pensando ponerle un icono de (+) y (-) para hacerlo mas controlable y ademas tengo espacio pero recuerda luis pidió eso tipo ecualizador.
bajo que criterio se maneja eso de los grupos de usuarios?

**Comment by acostarodrigo** [comment]
El issuer los acomodará como quiera. Por ejemplo puede crear un grupo llamado Venezuela y poner todos los usuarios conectados ahi.

**Comment by ivonnesantos** [comment]
Ok y si se da el caso que tiene 50 asset para distribuir y el grupo es de 28 personas por ejemplo?

**Comment by acostarodrigo** [comment]
solamente se distribuyen a esas 28 personas. 
La wallet se encarga de las validaciones

**Comment by ivonnesantos** [comment]
ok ok osea a unos les van quedar 2 asset y otros no? igual si es mas usuarios que asset algunos quedarin sin asset? tendría que poner un botón de crear nuevo grupo cierto? es chevere poner un filtro de organizar por ciudad y eso verdad?

**Comment by acostarodrigo** [comment]
> ok ok osea a unos les van quedar 2 asset y otros no?

Correcto, Ahora a nivel programación, los distribuye entre todos a los que se quiera enviar. Algunos recibiran 2.

> igual si es mas usuarios que asset algunos quedarin sin asset? 

La validación daria un error que se está intentando distribuir más de lo que realmente se tiene.

> tendría que poner un botón de crear nuevo grupo cierto?

La administracion de los grupos se hace por ahora en laUser  community.

> es chevere poner un filtro de organizar por ciudad y eso verdad? POr ahora no pongamos filtros.

Sí, pero todavía la plataforma no maneja bien la localización.

**Comment by ivonnesantos** [comment]
@yojoaquin @acostarodrigo 
![maqueta-01](https://cloud.githubusercontent.com/assets/15238660/13479613/64d7e796-e0aa-11e5-92ec-d126a9c240d7.jpg)

**Comment by ivonnesantos** [comment]
diseño home #646 
diseño del detail #647 
Pantalla de contactos #649

**Comment by arifernandez** [comment]
![dap_detail_asset_wallet_issuer 647_1-01](https://cloud.githubusercontent.com/assets/16305653/13606225/6b5b815a-e51d-11e5-9ca7-530827d5b405.jpg)
![dap_detail_asset_wallet_issuer 647_1-02](https://cloud.githubusercontent.com/assets/16305653/13606226/6b8bc608-e51d-11e5-987a-17f83a6e7e95.jpg)

@ivonnesantos propuestas

**Comment by ivonnesantos** [comment]
@arifernandez podemos reducir un poco el 1500 esta muy grande es mas fijate el nombre del asset colocalo en el head donde dice redeem point y asset send y asset avaliable los ponemos alinedos arriba uno junto al otro el acceso a contactos ponlo en la esquina de abajo me gusta mas las dos por me parece un poco mas funcional pero explicame algo cada barra representa un digito de 0 a 9?

**Comment by ivonnesantos** [comment]
@acostarodrigo ya que volviste me puedes dar tu opinion sobre estas funcionalidades

**Comment by arifernandez** [comment]
@ivonnesantos Si, cada barra de la segunda gráfica representa del 0 al 9 y tambien tiene los botones de manejo manual para mayor comodidad.

**Comment by ivonnesantos** [comment]
ok @arifernandez  entonces me gusta mas la segunda opcion tuya que la mía @Brinelddy ariana va a subir al repositorio esta plantilla editable aplica los cambios que le indique arriba y adicional esto agregale otras barritas de tal manera que se pueda aumentar la cifra para enviar asset enviar mas asset ya te paso el link del repositorio para que la puedas descargar y trabajar

**Comment by arifernandez** [comment]
![dap_detail_asset_wallet_issuer 647_2-02](https://cloud.githubusercontent.com/assets/16305653/13648626/cc68c13a-e60b-11e5-904c-9d8bd846ecb8.jpg)

@ivonnesantos Aquí esta con las modificaciones, coloque asset send y asset available alineados y el head es el nombre del asset, lo que no se que te parece si elimino o no el 1500 que esta sobre las barras

**Comment by ivonnesantos** [comment]
Cierto bueno pon los numeros sobre las barras un poco mas pequenos agrega dos barras mas a ver que dice @acostarodrigo segun yo entiendo el usuario debe empezar la cifra de derecha a izquierda y eso no se si se le podra hacer complicado al ususario

**Comment by javafrank** [comment]
Attached a new proposal for the issuer wallet home.
In this view initially shown who have redeemed and appropriate assets in addition to assets which have not been used.
Questions and suggestions are welcomed.

Specifications
https://www.google.com/design/spec/components/lists.html

![screenshot from 2016-04-08 10 59 36](https://cloud.githubusercontent.com/assets/13275281/14443913/0fd79ef4-000c-11e6-8853-ee5f695c1f7b.png)

cc @ivonnesantos @acostarodrigo @nindriago @yojoaquin

**Comment by acostarodrigo** [comment]
Keep in mind that we also need to show selled assets, and tomorrow we might have 10 more transaction types that we collect statistics from.

**Comment by ivonnesantos** [comment]
@acostarodrigo bueno pero para ese momento se puede hacer algo como una lista separada por categorias o filtros

**Comment by javafrank** [comment]
@acostarodrigo @ivonnesantos what do you think about this?

![screenshot from 2016-04-11 19 29 12](https://cloud.githubusercontent.com/assets/13275281/14446088/fb5d32da-001b-11e6-85f9-8fa2504cbbaa.png)

**Comment by ivonnesantos** [comment]
a mi me parece que la segunda opcion se debe tomar como base aca dejo el issue de status  #767 para desarrollar la idea individual.
