### ISSUE TITLE
Ventana_pop-up_Asset_user_wallet

### ISSUE THREAD

**Issue by ivonnesantos** [bitDubai/fermat-graphic-design#586]
Esta ventana es para confirmar si el user esta seguro de redimir a un determinado Redeem point, el texto debe estar en inglés
El video donde se discutió sobre este tema
Material de apoyo
https://www.google.com/design/spec/components/dialogs.html#dialogs-specs
Las medidas la encuentras en el caso #585

**Comment by arifernandez** [comment]
![ventana_pop-up_asset_issuer_wallet](https://cloud.githubusercontent.com/assets/16305653/13404685/102c8242-deed-11e5-83ce-a5a3c167e0a1.png)

@ivonnesantos

**Comment by arifernandez** [comment]
![ventana_pop-up_asset_user_wallet](https://cloud.githubusercontent.com/assets/16305653/13404834/d29c2c24-deed-11e5-850f-437ae9a961d8.png)

**Comment by ivonnesantos** [comment]
@arifernandez trabajemos con colores planos la paleta de colores de la redeem ya esta definida es decir ya @yojoaquin me aprobó unos colores aca esta la paleta que tiene android cargada https://www.google.com/design/spec/resources/color-palettes.html instala eso y luego la gama principal es la que parte de TEAL 500 (009688) y se utiliza como segundaria la gama BLUE GREY, con respecto a los textos si @yojoaquin @Luis-Fernando-Molina @acostarodrigo nos pudieran ayudar  porque creo que tienen un mejor inglés que el mio

**Comment by Luis-Fernando-Molina** [comment]
El encargado de los textos es @gustl-arg

**Comment by arifernandez** [comment]
![ventana_pop-up_asset_issuer_wallet](https://cloud.githubusercontent.com/assets/16305653/13447524/6a27aa18-dfee-11e5-9841-e96ca11c3af0.png)
![ventana_pop-up_asset_user_wallet 2](https://cloud.githubusercontent.com/assets/16305653/13447525/6b48e39e-dfee-11e5-9bfd-9ec0e4f6ec7a.png)

@ivonnesantos @Luis-Fernando-Molina @yojoaquin @acostarodrigo @gustl-arg

**Comment by yojoaquin** [comment]
Aclararía el título de la versión gris. El resto está ok.

**Comment by ivonnesantos** [comment]
@arifernandez a la version que te indica joaquin redondeale las puntas 2px que equivale a dos dp puedes verificarlo aca http://angrytools.com/android/pixelcalc/ aplica los cambios que te indica joaquin

Una pregunta @furszy @acostarodrigo este tipo de ventanas ustedes los desarrolladores las hacen con puro codigo cierto? nosotros solo debemos crear un archivo indicando las medidas de fuente y botones espacios y de más?

**Comment by arifernandez** [comment]
![ventana_pop-up_asset_user_wallet1](https://cloud.githubusercontent.com/assets/16305653/13493557/e09b00dc-e110-11e5-91e7-567cc8f4257b.png)
![ventana_pop-up_asset_issuer_wallet2](https://cloud.githubusercontent.com/assets/16305653/13493558/e0a5dcfa-e110-11e5-9fff-7a12c026158b.png)

@yojoaquin Ese era el color mas claro de la paleta, asi que oscurecí un poco el fondo y le redondee las puntas 2px como dijo @ivonnesantos

**Comment by yojoaquin** [comment]
Si si. Esta bien así. El texto no tiene sentido pero es contenido eso, no
importa ahora.

**Comment by ivonnesantos** [comment]
@arifernandez subelo al repositorio En Drafts para esto solo debe hacerse un archivo de indicaciones que te voy a enseñar a preparar pero subelo primero para yo verificar las medidas base

**Comment by ivonnesantos** [comment]
@gustl-arg podrias ayudar con estos textos para que no se pase este detalle en la app

**Comment by gustl-arg** [comment]
OK. @acostarodrigo porfa indicame donde esta este texto, no lo encuentro en https://github.com/acostarodrigo/fermat/blob/develop/DAP/android/reference_wallet/fermat-dap-android-reference-wallet-redeem-point-bitdubai/src/main/res/values/strings.xml

Tambien necesito aclaración del circuito de redencion, pues no me hace sentido que un Asset User tenga que aceptar un Redeem Point, sino mas bien, aceptar que su asset sea redimido en un REDEEM POINT especifico, o sea, por una redeem point wallet especifica...

**Comment by ivonnesantos** [comment]
@gustl-arg si esta ventana debería estar orientada a preguntar
1 si esta seguro de redimir el asset a un redeem point
2 si esta seguro de enviar el asset a x persona
porque es usuario puede redimir enviar y apropiar el asset tengo entendido que es asi @emmysm me falta otra cosa

**Comment by emmysm** [comment]
Exacto, redimir, apropiar, transferir y vender

**Comment by ivonnesantos** [comment]
@gustl-arg este caso yo lo abri con el fin de unificar el diseño de todas las pop-up pero como cada una debe tener su texto por eso te lo indico para que no se les pase por alto https://www.youtube.com/watch?v=SFEKdnuiNcA aca esta el video entre el minuto 50 y 52 se habla sobre esto pero mas que todo a nivel de estético
