### ISSUE TITLE
Mejorar el logo de Fermat DMP

### ISSUE THREAD

**Issue by m471c4** [bitDubai/fermat-graphic-design#59]
Viene del #11

Ver si se puede mejorar este isologo desde el punto de vista del diseño y reaplicar la nueva paleta de colores.

![fermat_dmp_hq](https://cloud.githubusercontent.com/assets/9479367/9057022/4931ead2-3a97-11e5-904c-b85aac6a553c.png)

**Comment by arnaldos** [comment]
Primera versión de refrescamiento de logo Fermat DMP.   En esta versión no hubo muchas variaciones
![fermat_version_2-9](https://cloud.githubusercontent.com/assets/13594347/9286724/de0b7c5c-42c3-11e5-94a6-48aecf1626a6.jpg)

**Comment by Luis-Fernando-Molina** [comment]
El circulo con el aro blanco me gusta, si lo hacemos aca, debería ir en todos los otros lados, no?

**Comment by Luis-Fernando-Molina** [comment]
Las billeteras chiquitas nuevas no estoy seguro que queden mejor que las anteriores, podes probar ponerlas como antes, y solo dejarle el borde rojo alrededor?

**Comment by Luis-Fernando-Molina** [comment]
@m471c4 @arnaldos sería bueno que asignen el caso a uno u a otro para saber quien es el que lo esta haciendo o va  a hacer

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina logo Fermat DMP con la paleta de colores ajustadas
![fermat_version_2-11](https://cloud.githubusercontent.com/assets/13594347/9318622/059465de-450f-11e5-89f4-1b38811ea7bb.jpg)

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina logo con ajuste de tipografía, en esta versión no le coloque el borde en blanco a las billeteras, ya que en el borde mantener el color del fondo nos permite ver como las billeteras están superpuestas entre si y nos brinda profundidad dentro de la sintesis.
![fermat_version_3-3](https://cloud.githubusercontent.com/assets/13594347/9319017/8c0f9b0c-4513-11e5-8719-69e90e313d78.jpg)

**Comment by Luis-Fernando-Molina** [comment]
OK logo y fermat listo. Falta de.

**Comment by Luis-Fernando-Molina** [comment]
Falta dmp.

**Comment by arnaldos** [comment]
ok perfecto !! ya realizo lo ajustes !

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina  Ajustes en la tipografía en DMP
![fermat_version_4-3](https://cloud.githubusercontent.com/assets/13594347/9338346/11f92932-45ae-11e5-80b0-e2799e48a1fe.jpg)

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina ajustes de tono al nombre de la sub app
![fermat_version_4-6](https://cloud.githubusercontent.com/assets/13594347/9401883/c5a53744-479f-11e5-8640-38b314169043.jpg)

**Comment by Luis-Fernando-Molina** [comment]
En este tmaño se ve bien, pero me pregunto que pasa cuando se reduce un poco.

**Comment by arnaldos** [comment]
si al reducir el logo se perdería este elemento y no tendría lectura ya subo una muestra para que lo puedas apreciar, voy aplicarlo a las otras sub app también

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina  Ajuste del texto digital money

![fermat_version_4-9](https://cloud.githubusercontent.com/assets/13594347/9458745/625a9a74-4abc-11e5-8cff-eb51e1fb582a.jpg)

**Comment by Luis-Fernando-Molina** [comment]
:+1: esto está listo.
