### ISSUE TITLE
Mnemonic import (dialog)

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#601]
pantalla o vista para importar la clave mnemonic

**Comment by arnaldos** [comment]
@furszy

**Comment by m471c4** [comment]
@arnaldos este caso ya existe, es el #548 :)

**Comment by arnaldos** [comment]
son dos de estos uno es import y otro export

**Comment by arnaldos** [comment]
cierro este caso, fue resuelto a nivel de desarrollo
