### ISSUE TITLE
Spinner nacionalidad,provincia

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#608]
Un spinner para selección de nacionalidad

**Comment by arnaldos** [comment]
@furszy @acostarodrigo

**Comment by acostarodrigo** [comment]
no seria para nacionalidad solamente, sino provincia / estado ,etc.
Todo lo necesario para especificar una dirección de un local.

**Comment by arnaldos** [comment]
ok perfecto

**Comment by clp3z** [comment]
![pop_up_background](https://cloud.githubusercontent.com/assets/8752959/13514950/29d4192a-e1a5-11e5-82b9-0710f4c8e4aa.png)

Te escribo por aquí la lista de modificaciones que habría que hacer
- A la imagen de fondo hay que quitarle la línea negra.
- Agregarle el color del objecto seleccionado. Es decir, colocar la barra de color morado(azul) encima de la del fondo. Para que de la apariencia de que el elemento que está siempre seleccionado es el del centro, con ese sombreado.
- Hay que hacer una versión para 5 elementos.
