### ISSUE TITLE
Organizar las fuentes del isologo Fermat DMP en el repositorio

### ISSUE THREAD

**Issue by m471c4** [bitDubai/fermat-graphic-design#61]
Viene del #11

Organizar debidamente las fuentes del isologo, así como los distintos tamaños sugeridos, en sus respectivos formatos (png, ico, etc).

**Comment by arnaldos** [comment]
@m471c4 @Luis-Fernando-Molina @jonathanborges3d Los fuentes ya estanorganizados en el repo aca les dejo el enlace https://github.com/arnaldos/fermat-graphic-design/tree/master/Logos_sub-app_fermat/Fermat_DMP
