### ISSUE TITLE
SendForm

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#610]
desarrollar una vista envió de dinero

**Comment by arnaldos** [comment]
@furszy

**Comment by m471c4** [comment]
@arnaldos @furszy @clp3z por favor indicarme si hace falta algún campo:

![sendform](https://cloud.githubusercontent.com/assets/13468350/13326123/cff88524-dbb6-11e5-9dfa-ff82caafd4f3.png)

**Comment by furszy** [comment]
- falta un address (direccion bitcoin) que se pueda esconder/desplegar de alguna forma
- falta el tipo de monto, si en btc,litecoin,dodgecoin,dash,etc ,
- falta la unidad del monto si son btc,satoshis,mili, etc 
  y la vista no me convence mucho por más que sea simple, los botones deberian ser del mismo tamaño o con otra forma, el color es indistinto porque es la base y se puede cambiar.

**Comment by m471c4** [comment]
@furszy ¿qué no te convence a parte de los botones? Los cambié por flat porque imagino que esto será una especie de fullscreen dialog.

![sendform2](https://cloud.githubusercontent.com/assets/13468350/13328139/4c731e5e-dbbf-11e5-9570-76ca9898e494.png)

**Comment by furszy** [comment]
el bitcoin address dije desplegable porque se me ocurrió que se podia ocultar y luego mostrar, no es un desplegable de esa forma tipo spinner

**Comment by m471c4** [comment]
@furszy ya entiendo, aunque no se me ocurre cómo desplegar la opción, déjame revisar. Por ahora lo pongo como campo de texto:

![sendform3](https://cloud.githubusercontent.com/assets/13468350/13328691/4111aa96-dbc2-11e5-920a-25c8b75d0759.png)

**Comment by clp3z** [comment]
Creo que para ocultarlo y mostrarlo podríamos colocar un botón delante del texto y que cuando se presione se despliegue el campo de texto y al mismo tiempo cambie el ícono.

Algo como:
 .>  Bitcoin Wallet Address (Cuando no está presionado - sin el punto)

 v Bitcoin Wallet Address (Cuando esté presionado)

   Type here...

---

Y los íconos de los botones serían:
https://design.google.com/icons/#ic_chevron_right
https://design.google.com/icons/#ic_expand_more

¿Qué opinan?

**Comment by m471c4** [comment]
@clp3z acá con tus sugerencias, habría que ver qué le parecen a @furszy 

![sendform4](https://cloud.githubusercontent.com/assets/13468350/13334482/4a44717c-dbde-11e5-9745-c313c509a3bb.png)

Si no se selecciona una bitcoin wallet adress, ¿a qué parte se envía el dinero? No basta con ponerle un nombre, a menos de que ese nombre esté asociado a un user de la plataforma Fermat.

**Comment by m471c4** [comment]
Ya @clp3z ha dejado lista esta vista. Podemos cerrar el caso.

**Comment by arnaldos** [comment]
listo !!
