### ISSUE TITLE
DAP_home_redeem_point

### ISSUE THREAD

**Issue by ivonnesantos** [bitDubai/fermat-graphic-design#611]
El Supperissues es #577

**Comment by ivonnesantos** [comment]
![propuestas-01](https://cloud.githubusercontent.com/assets/15238660/13328167/68753ce0-dbbf-11e5-8408-edee26bb3571.jpg)

@acostarodrigo @yojoaquin

**Comment by acostarodrigo** [comment]
muy buena. prefiero la 2.

**Comment by acostarodrigo** [comment]
@java

**Comment by ivonnesantos** [comment]
Ok @acostarodrigo entonces seguire haciendo la detail en base a la propuesta 2 hasta que alguien diga lo contrario

**Comment by ivonnesantos** [comment]
@acostarodrigo @yojoaquin 
Propuestas segun recomendacion de joaqui por slack
![propuestas-01](https://cloud.githubusercontent.com/assets/15238660/13376450/0db67acc-dd8f-11e5-8b01-84b82d92921e.jpg)

**Comment by yojoaquin** [comment]
Ahora estamos hablando :)
Me gusta la propuesta 3. Podrías usar otros colores para las tabs y la línea de "active". Y fijate que podés usar íconos para Accept y Reject y darle un poco de aire.

**Comment by ivonnesantos** [comment]
![propuestas-01](https://cloud.githubusercontent.com/assets/15238660/13401644/18ae0872-dedf-11e5-8262-bc80f5f6384b.jpg)

@yojoaquin

**Comment by yojoaquin** [comment]
Agrandaría los botones. Les daría más aire entre ellos y los bordes.
No me quedan claro los estados.
Arriba a la derecha es la hora en la que se pidió el redeem? Qué función cumple?
Me gusta la opción 2 de colores, pero alternaría los colores, el activo es el claro y el oscuro el otro.

**Comment by ivonnesantos** [comment]
Debería ser la hora en que se envió el asset a redeem y el reloj es un proceso de comprobación que hace el sistema eso le entendi a @acostarodrigo

**Comment by ivonnesantos** [comment]
![propuestas-01](https://cloud.githubusercontent.com/assets/15238660/13407896/f26d5550-defc-11e5-9581-e26d3838ded4.jpg)
Correcciones @yojoaquin

**Comment by ivonnesantos** [comment]
@yojoaquin que te pareció esta propuesta?

**Comment by ivonnesantos** [comment]
@acostarodrigo lo del status está bien?

**Comment by pennyxz** [comment]
Hola @ivonnesantos. Estamos por iniciar una nueva etapa donde aplicaremos los nuevos diseños a la Wallet de Redeem Point y Issuer. Para todas las pantallas de Redeem Point tomamos como base la mejor propuesta. Para este caso, nos gusto mucho la ultima propuesta. Quisiéramos aplicar un pequeño cambio en el card view del usuario, solo para ver que tal luce y ver si ponemos aplicarlo. Nos gustaría ver como se vería la card del usuario con un header del mismo color de la wallet (Como se hizo para la User Wallet nueva)

**Comment by ivonnesantos** [comment]
aca dos propuestas de color lo hice con la misma gama de color que el head pero entono distinto para mantener la jerarquía de color @pennyxz @jinmyjbv 
Propuesta_1
![home_desing_aproved-04](https://cloud.githubusercontent.com/assets/15238660/14445377/550605ba-0016-11e6-9f46-e45bec6c1995.jpg)

Propuesta_2
![home_desing_aproved-05](https://cloud.githubusercontent.com/assets/15238660/14445379/551df4d6-0016-11e6-94ef-fc92d134354b.jpg)

**Comment by ivonnesantos** [comment]
propuesta_1 aprobada

**Comment by ivonnesantos** [comment]
Resources generedos

**Comment by pennyxz** [comment]
@ivonnesantos Necesitamos una imagen de fondo, como en las demas wallets, para indicar que no hay assets en este wallet. Que sea tanto para la pantalla de Pending como para History.

**Comment by ivonnesantos** [comment]
No asset @pennyxz @jinmyjbv 
![no_asset-01](https://cloud.githubusercontent.com/assets/15238660/14959901/a2d47736-105b-11e6-9e03-4f39ec3be227.jpg)

**Comment by pennyxz** [comment]
Excelente @ivonnesantos  esperamos por los recursos.
