### ISSUE TITLE
DAP_detail_redeem_point

### ISSUE THREAD

**Issue by ivonnesantos** [bitDubai/fermat-graphic-design#612]
El Supperissues #577

**Comment by ivonnesantos** [comment]
![detail-01](https://cloud.githubusercontent.com/assets/15238660/13337368/25203160-dbed-11e5-8f65-6203511bb297.jpg)
@acostarodrigo @yojoaquin

**Comment by ivonnesantos** [comment]
![propuestas-02](https://cloud.githubusercontent.com/assets/15238660/13410907/7246bd52-df0c-11e5-9b27-3cee2997dead.jpg)

@yojoaquin @acostarodrigo

**Comment by ivonnesantos** [comment]
chicos que les parecio este trabajo hago otras? @acostarodrigo @yojoaquin

**Comment by pennyxz** [comment]
Hola @ivonnesantos. Estamos por iniciar una nueva etapa donde aplicaremos los nuevos diseños a la Wallet de Redeem Point y Issuer. Para todas las pantallas de Redeem Point tomamos como base la mejor propuesta. Para este caso, nos gusto mucho la propuesta 1, pero quisiéramos hacerle un pequeño cambio. Primero que nada, nos gustaría quitar la imagen del asset en el tool bar que resulta redundante. Tambien nos gustaria, de alguna forma, mejorar el estilo de el slider de imagenes, pues esta parte del detail es muy parecida al card view del home. La idea principal es que no de la sensación de que están en la misma pantalla del home. Adjunto la propuesta 1 con los diferentes estados que puede tener la pantalla a ser reflejados pero sin cambios mayores en la parte del slider. Tal vez unas cuantas propuestas nos ayuden a mejorarla y tomar la decisión.

![detail redeem point](https://cloud.githubusercontent.com/assets/16389008/14434051/bb91de26-ffda-11e5-943e-4dee0d5d2017.png)

**Comment by ivonnesantos** [comment]
![detail_desing-02](https://cloud.githubusercontent.com/assets/15238660/14444711/2190dcc8-0011-11e6-8554-bc031e7d940f.jpg)
![detail_desing-04](https://cloud.githubusercontent.com/assets/15238660/14444717/284c2c70-0011-11e6-986c-a5bbda027b72.jpg)
![detail_desing-05](https://cloud.githubusercontent.com/assets/15238660/14444723/32a8e460-0011-11e6-8ceb-5af86de19fd0.jpg)
@pennyxz @jinmyjbv hay un detalle el asset name no puede repetirse en el head y sobre la foto por eso no lo puse sobre la foto.

**Comment by pennyxz** [comment]
@ivonnesantos Listo. Esta perfecto. Cuando puedas, nos generas los recursos
