### ISSUE TITLE
DAP_history_redeem_point

### ISSUE THREAD

**Issue by ivonnesantos** [bitDubai/fermat-graphic-design#613]
El Supperissues #577

**Comment by ivonnesantos** [comment]
![hystory_desing-01](https://cloud.githubusercontent.com/assets/15238660/13337938/b1eb2b2e-dbf0-11e5-8f47-9a0332cb565a.jpg)
@acostarodrigo @yojoaquin

**Comment by ivonnesantos** [comment]
![hystory_desing-02](https://cloud.githubusercontent.com/assets/15238660/13444169/f8f1a3d8-dfd6-11e5-8976-317c1efd565c.jpg)
Nueva propuesta Basándose en correcciones de @yojoaquin @acostarodrigo

**Comment by yojoaquin** [comment]
Cómo quedaría con nombres de personas y de assets largos? Podés armar una
propuesta porfa?

**Comment by ivonnesantos** [comment]
@yojoaquin tienes razon no se da muy bien esa disposición quedarían cortados los nombres si son muy largos te muestro un ejemplo y otra propuesta que desde mi punto de vista puede funcionar y se adapta a los criterios android
![propuestas-03](https://cloud.githubusercontent.com/assets/15238660/13466288/7cb62812-e06b-11e5-81c4-d861a56c15c1.jpg)

**Comment by ivonnesantos** [comment]
@acostarodrigo @yojoaquin cual les parece mejor?

**Comment by yojoaquin** [comment]
La propuesta 2 para history está bien. 
Pending sería igual? O hay una propuesta?

**Comment by ivonnesantos** [comment]
seria esta que ya esta casi definida solo falta detallar algunas cosas de los botones que me habias pedido https://github.com/Fermat-ORG/fermat-graphic-design/issues/611

**Comment by pennyxz** [comment]
Hola @ivonnesantos. Estamos por iniciar una nueva etapa donde aplicaremos los nuevos diseños a la Wallet de Redeem Point y Issuer. Para todas las pantallas de Redeem Point tomamos como base la mejor propuesta. Para este caso, nos gusto mucho la propuesta 2, pero quisiéramos hacerle un pequeño cambio para una futura implementacion. Te adjunto un pequeño bosquejo del cambio que queremos aplicarle para que generes su respectivo diseño. 

![history redeem point](https://cloud.githubusercontent.com/assets/16389008/14433835/b73f1b0a-ffd9-11e5-9036-00f50e348aad.png)

**Comment by ivonnesantos** [comment]
![hystory_desing-02](https://cloud.githubusercontent.com/assets/15238660/14439727/6bf2481c-fff6-11e5-84ce-5ea3203aa417.jpg)

@pennyxz @jinmyjbv

**Comment by jinmyjbv** [comment]
@ivonnesantos hay un detalle en la sección **History** El texto rojo de la derecha es un poco confuso, no se sabe si indica un numero de día referente a fecha o a una cantidad de assets registrados por día(la cual creo que es la que debe ir allí y la que tratas de expresar), creo que ese texto no debe contener la palabra **Day**, ya que de por si, el texto gris de la derecha ya expresa el día en cuestión. propongo que dia algo como " **4 Assets** ".

**Comment by ivonnesantos** [comment]
Yo quiero expresar algo así como los asset del dia si tienen alguna sugerencia. Ya aplicó la corrección de ese detalle.

**Comment by ivonnesantos** [comment]
![hystory_desing-02](https://cloud.githubusercontent.com/assets/15238660/14468205/7dd6fd36-00a8-11e6-98c0-7c0c54738838.jpg)
@jinmyjbv @pennyxz

**Comment by ivonnesantos** [comment]
@pennyxz @jinmyjbv cuando ya estén satisfechos con el resultado me avisan para generar los recursos. =)

**Comment by pennyxz** [comment]
@ivonnesantos Estamos satisfechos con ellos. Puedes generar los recursos

**Comment by ivonnesantos** [comment]
Resources generados
