### ISSUE TITLE
DAP_transation_history

### ISSUE THREAD

**Issue by ivonnesantos** [bitDubai/fermat-graphic-design#614]

**Comment by ivonnesantos** [comment]
Esta pantalla se va a utilizar para todas las wallet de la DAP y la redeem point la pantalla sera la misma con el head de cada una de las wallet que se discuten en los siguientes SUPPERISSUES
#582 
#577
#570

**Comment by ivonnesantos** [comment]
Maqueta
![transaction-history_ux_01-01](https://cloud.githubusercontent.com/assets/15238660/13358836/72d6c1f8-dc83-11e5-8a05-414b59532229.jpg)
@acostarodrigo @yojoaquin esto fue diagramado tomado en cuenta que el asset puede ser tranferido varias veces y que eso se refleje en el historial para esto se debe hacer scroll hacia los lados

**Comment by acostarodrigo** [comment]
Lo que decis es cierto pero no es lo que queremos mostrar.
La pantalla de transacciones solamente mostrará la transacción dentro de ese dispositivo, no el historial de todo el asset. 

Podemos pensar algo asi para las transacciones del Asset Issuer, pero no para las del user y el Redeem Point.

**Comment by ivonnesantos** [comment]
![transaction-history_ux_01-01](https://cloud.githubusercontent.com/assets/15238660/13362818/7f3c8d78-dc98-11e5-99b1-b6822f20661e.jpg) eso de Quantity asset no me covence lo puse porque esta ahorita en lo que me mostraste pero si el registro es del asset individual entonces siempre sera 1

**Comment by acostarodrigo** [comment]
sigue estando mal el concepto. Created, Sell y Redeem son transacciones. Cada una debe estar en una fila como una transacción.

La transacción tiene que tener:
Origen | Asset | Destino

por ejemplo
Asset Issuer con foto | Nombre Asset, imagen y tipo de Transaccion como por ejemplo Delivery | Asset User con Foto

Quedamos diferenciar las transacciones entrantes y salientes con la imagen de una flecha o los colores rojo y verde al principio de la transacción.

Entonces la pantalla de Transacciones de una wallet será:

-> | Rodrigo | Asset 1 Transferencia | Juan
-> | McDonalds | Asset 2 Delivery | Juan
<- | Juan | Asset 2 Redeem | Local1
etc

hagan propuestas en base a esto por favor.

**Comment by ivonnesantos** [comment]
ok esta bien

**Comment by ivonnesantos** [comment]
![transaction-history_ux_01-01](https://cloud.githubusercontent.com/assets/15238660/13366137/9181774c-dcab-11e5-980b-f5a20675aaeb.jpg)
 veamos si ahora si le doy al blanco =D @acostarodrigo

**Comment by acostarodrigo** [comment]
exacto! El check o el  status en el Asset no es necesario.
Si en el destino, porque puede pasar que se lo estemos enviando a alguien y el destino no lo acepte. Entonces se genera una transacción de rollback.

El destino en lugar de un check en algunos casos va a tener la X de error.

**Comment by ivonnesantos** [comment]
@emely-puerta  este es un detalle muy importante para diseñar listas https://www.google.com/design/spec/components/grid-lists.html#grid-lists-behavior

**Comment by ivonnesantos** [comment]
@emely-puerta

**Comment by emely-puerta** [comment]
![transaction-history_ux_01](https://cloud.githubusercontent.com/assets/17557647/13552297/68823960-e32e-11e5-89c9-3a9ec61c7278.jpg)
@ivonnesantos

**Comment by ivonnesantos** [comment]
@emely-puerta me gusta la primera en base a esta crea una que sea un poco mas sutil no se que piense @yojoaquin

**Comment by yojoaquin** [comment]
Adhiero. Alinearía los iconos en la columna izq.

**Comment by emely-puerta** [comment]
Hola buenas tardes, @ivonnesantos perfecto, ya trabajo en eso. Ahora @yojoaquin te refieres a los iconos que representan las transacciones entrantes y salientes??. Podrías explicarte mejor por fa. 

Saludos

**Comment by emely-puerta** [comment]
![transaction-history_ux_01-1](https://cloud.githubusercontent.com/assets/17557647/13656494/9ab8343a-e639-11e5-826a-fa91955e6214.jpg)
@ivonnesantos @yojoaquin

**Comment by ivonnesantos** [comment]
@emely-puerta el head va del color de la aplicacion en este caso estamo trabajando ese verde porque es el unico definido hasta ahora ya luego a cada pantalla le pones el color de cada una, me gusta la dos  los iconos en negro no me gustan coloca el puntico del centro el un color gris clarito y la flechita entrada en verde y salida en rojo a ver si @yojoaquin  tienen alguna sugerencia

**Comment by emely-puerta** [comment]
Buenas noches, acá dejo las correcciones solicitadas y una propuesta cambiando el color de fondo por un gris más claro. Yo considero que si se colocan los iconos de las transacciones salientes y entrantes en verde y rojo según sea el caso, esto puede confundir ya que por lo general son usados para aprobación y negación. @ivonnesantos 

![transaction-history_ux_01-2](https://cloud.githubusercontent.com/assets/17557647/13692174/3748fd02-e711-11e5-85f8-d1cacf43e233.jpg)

**Comment by ivonnesantos** [comment]
@emely-puerta ahora me gusta mas la 1 pero con los iconos de la 2 sabes que se hizo unos icono asi de check y de x que creo que seria bueno usar en este caso estan en el repositorio UIUX/APPS/PALTAFORMA_DAP/ICONS/STATUS usalos a ver que tal se ven pero yo creo que esta pantalla ya esta casi casi

**Comment by ivonnesantos** [comment]
@emely-puerta vamos a hacer unas correcciones en los trazos aca te dejo un video que te dice que herramienta usar y como usarla https://www.youtube.com/watch?v=oL8ct2Q3_oM&feature=em-upload_owner tambien vamos a colocar una fila en un tono mas oscuro y que se intercalen sube los iconos de entrada y salida alinealos con la foto

**Comment by emely-puerta** [comment]
Hola @ivonnesantos  acá adjunto los cambios solicitados.
![transaction-history_ux_01-3](https://cloud.githubusercontent.com/assets/17557647/13725696/79492068-e87b-11e5-9277-d402f9ba95ce.jpg)

**Comment by yojoaquin** [comment]
Podríamos hacer una versión integrando el tipo de transacción a la fila en lugar de una columna separada?
Le quitaría las líneas divisorias entre fila y fila porque es suficiente con el cambio de color de fondo.
Qué pasa si el nombre del usuario y/o del asset es más largo?

**Comment by emely-puerta** [comment]
Buenas noches @yojoaquin @ivonnesantos acá les dejo las correcciones solicitadas, si se diera el caso de que el nombre del usuarío y/o del asset es más largo, este se podría abreviar y colocar puntos suspensivos. En la corrección hice un ejemplo.

Saludos
![transaction-history_ux_01 new_01](https://cloud.githubusercontent.com/assets/17557647/13799157/34572196-eaef-11e5-9b71-573092ed02c8.jpg)

**Comment by yojoaquin** [comment]
Gracias Emily. Sabes que me di cuenta que no tiene fecha ni hora de
referencia cada transacción. Podrías incluirla porfa?
Hay poco espacio en el margen derecho donde está el nombre con ... No
debería pasar esto. Debe ser congruente con todos los espacios.
Saludos

**Comment by ivonnesantos** [comment]
si emely @emely-puerta los bordes a los lados siempre son de 16dp=16px en mdpi eso aparece en el material design que te pase mosca con esos detalles tambien te falto una ilera al final fijate que la ultima esta mas grande lo que tienes es que oscurecerla de seguro si esta pero no la oscureciste, crea una propuesta con la informacion alli y crea una propuesta con la informacion oculta en una burbuja de tal manera que si el usuario quiere ver informacion detallada pulse y le aparezca esto lo hago pensando que esta pantalla esta enfocada en informar la condicion del asset si llego a su destino o no y segundo plano la informacion de cada transaccion no se si @yojoaquin estara de acuerdo pero hagamos la prueba a ver

**Comment by ivonnesantos** [comment]
Esta Propuesta muestra tanto la información  como la foto con el orden del proceso no es exactamente lo que se habló pero creo que logra mostrar todo y no sería necesario abreviar los nombres si son muy largos como en propuestas anteriores 
![transaction-history_ux_01 new-02](https://cloud.githubusercontent.com/assets/15238660/13867487/7bb81768-ec91-11e5-8a08-8100542f5a54.png)

@nindriago @franklinmarcano1970 @acostarodrigo @yojoaquin

**Comment by ivonnesantos** [comment]
Otra propuesta con las sugerenrencias de joaquin por slack 
![transaction-history_ux_iv_p2-01](https://cloud.githubusercontent.com/assets/15238660/13931819/4b7667a6-ef77-11e5-919f-8e771c550923.png)

@yojoaquin @nindriago @javafrank @emmysm @acostarodrigo

**Comment by ivonnesantos** [comment]
![sin titulo-1-01](https://cloud.githubusercontent.com/assets/15238660/13967011/45e9bf6a-f047-11e5-9bcd-30230f075d7b.png)

@acostarodrigo @nindriago @yojoaquin @emmysm @javafrank

**Comment by arnaldos** [comment]
@nindriago @javafrank @ivonnesantos esto ya esta aplicado ??  avísenme para cerrar el caso
