### ISSUE TITLE
Infográfico Nº 2 para el White Paper V2

### ISSUE THREAD

**Issue by jonathanborges3d** [bitDubai/fermat-graphic-design#615]
Viene del #417 

@gustl-arg @Luis-Fernando-Molina 
Éste gráfico debe representar la construcción de una fermat app, partiendo de los componentes escenciales y los plugins que se conectan a éstos.

Lo percibí como una esfera dividida en 36 partes, tres de las cuales pertenen al núcleo y las restantes forman una capa externa conectada a las tres primeras. Éste concepto aún está en estudio.

![infografic_2](https://cloud.githubusercontent.com/assets/13649739/13373140/26860f26-dd31-11e5-9e16-079ff4ce8b36.jpg)

He pensado en colocar en la "cara" de los plugins que forman la esfera un icono que represente su funcionalidad o los iconos de las plataformas de Fermat. Nó sé si voy encaminado en el concepto.

**Comment by Luis-Fernando-Molina** [comment]
Las pelotitas se ven bien, pero conceptualmente no esta bien la explicación. Si me consiguieran un programa para yo hacer la base de los esquemas como el que uso ibm en su open source de su sistema blockchain, yo pudiera hacer el esquema inicial y ustedes mejorarlo. Sino, la verdad me parece que esto no va andar.

**Comment by gustl-arg** [comment]
@Luis-Fernando-Molina lamento opinar igual que vos. Se me ha escapado la claridad conceptual sobre Fermat y entonces se me hace aun mas dificil tratar transmitirsela a @jonathanborges3d que logicamente está más desinformado en ese aspecto. Esta es la causa, a la que se agregan otros problemas de intercomunicación. Vamos a buscar el programa.

**Comment by gustl-arg** [comment]
@jonathanborges3d a mi me parece buena la forma de graficar la "construccion" de una Fermat App, el problema es que me falta entendimento para definir cada "salto" en la secuencia...por ejemplo..pense que se podria partir de una esfera completa mas pequeña que los primeros tres componentes y poner que eso es el "core" (la capa mas profunda de Fermat), luego a partir de alli, no se si la secuencia esta bien:
[] esferita del CORE
[] primera capa de 3 componentes = 3 superlayers ( BCH, OSA, CER )
[] segunda capa de X componentes = otras capas relevantes (communication layer / netwrok services layer / transactions layer / wallet layer / )
[] tercera capa ? o ya es la superficie ? = android-core layer, ??/ APP con GUI componentes visibles (skin+botones+menues)

no se como marcar el workflow que es como un hilo que une la secuencia de activacion de los plug-ins ...

@Luis-Fernando-Molina fijate que en si el modelo es graficamente valido, aunque conceptualmente hay que pulirlo...

**Comment by jonathanborges3d** [comment]
@gustl-arg Se me ocurre que también puede representarse como una estructura molecular, no necesariamente son simétricas y permiten múltiples conexiones. Éstos enlaces entre los átomos (?) podrían considerarse como el workflow, ya que permite ramificaciones diversas.

![](http://thumbs.dreamstime.com/z/modelo-molecular-de-la-dopamina-9645019.jpg)

![](https://i-msdn.sec.s-msft.com/dynimg/IC686272.png)

**Comment by Luis-Fernando-Molina** [comment]
todo esto vamos a dejar que lo especifique Katherine y veamos como nos va

**Comment by gustl-arg** [comment]
@jonathanborges3d aca hay un simple ejemplo de como otros poryectos grafican el stack=la pila de capas una sobre otras http://source.android.com/images/android_framework_details.png

**Comment by Luis-Fernando-Molina** [comment]
Please pause this issue until @Kate99 presents the specification for the diagrams to draw.
