### ISSUE TITLE
Generar Banner para el Fermat Chat 

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#617]

**Comment by arnaldos** [comment]
Propuesta banner fermat chat @darkestpriest @franklinmarcano1970 @josejcb 

![banner](https://cloud.githubusercontent.com/assets/13594347/13385319/75a2f8e4-de71-11e5-8c57-254456b5e3f3.png)

**Comment by arnaldos** [comment]
@darkestpriest @franklinmarcano1970 @josejcb este banner quedo así o hay que hacer una mejora ??

**Comment by franklinmarcano1970** [comment]
@josejcb Como quedamos con esto ya es la version final?

**Comment by josejcb** [comment]
listo
