### ISSUE TITLE
Generar un icono para la plataforma Artist (ART)

### ISSUE THREAD

**Issue by emmysm** [bitDubai/fermat-graphic-design#624]
Icono para la plataforma Artist

**Comment by emmysm** [comment]
![art plat--01](https://cloud.githubusercontent.com/assets/15143489/13437109/b9d5bc2e-dfb4-11e5-8e31-72a28fa3615e.png)

@darkestpriest @Luis-Fernando-Molina

**Comment by darkestpriest** [comment]
@emmysm está muy bien, pero creo que está muy enfocado a la pintura, debería tener alguna referencia a la música, un instrumento, una corchea o clave de sol.
CC: @lostwood @GaboHub

**Comment by emmysm** [comment]
Vale, ya hago las modificaciones @darkestpriest

**Comment by GaboHub** [comment]
Me gusta, y estoy de acuerdo con @darkestpriest  sobre su sugerencia. @emmysm

**Comment by emmysm** [comment]
![art plat](https://cloud.githubusercontent.com/assets/15143489/13442895/9d8988ea-dfd0-11e5-94c3-94bc89b9e223.png)

@GaboHub @darkestpriest ajustes

**Comment by lostwood** [comment]
Hola el primer diseño me gusto, pero como comentaron le hacia falta la parte de musica, pero el microfono en el diseño no lo veo muy bien, y si fueran unos audifonos, afuera y dentro el diseño inicial

**Comment by emmysm** [comment]
![art plat-02](https://cloud.githubusercontent.com/assets/15143489/13445545/0cdcb31c-dfdf-11e5-89cf-6650adb46491.png)
![art plat-01](https://cloud.githubusercontent.com/assets/15143489/13445546/0cdeaf8c-dfdf-11e5-9355-8b135f927590.png)

@darkestpriest @lostwood @GaboHub

**Comment by lostwood** [comment]
El que contiene los audifonos segun mi opinion, la imagenes estan clara en demostrar que existe relacion con la musica y el arte excelente emmy

**Comment by darkestpriest** [comment]
Me gusta la versión de los audífonos, genial @emmysm

**Comment by emmysm** [comment]
Gracias, chicos :smile_cat:  @lostwood @darkestpriest

**Comment by Luis-Fernando-Molina** [comment]
la billetera esta fuera de lugar

Una nota musical o la clave de sol puede reprsentar la musica. Una foto se representa con una foto polaroid. El pincel y la lapicera estan bien.

**Comment by emmysm** [comment]
![iconos art-10](https://cloud.githubusercontent.com/assets/15143489/13504718/e1fac03e-e147-11e5-8450-ae878b09ee52.png)

@Luis-Fernando-Molina

**Comment by darkestpriest** [comment]
Me gusta más esta nueva versión :+1:

**Comment by Luis-Fernando-Molina** [comment]
por favor agrega un microfono y la foto que sea polaroid, osea con un borde blanco grande abajo

**Comment by Luis-Fernando-Molina** [comment]
quita por favor el disquito negro

**Comment by Joseangel2v** [comment]
![art](https://cloud.githubusercontent.com/assets/17457499/13860795/6ae6b9b4-ec8a-11e5-8e9f-fb5d73ddc211.png)
Plataforma Art_01

**Comment by Joseangel2v** [comment]
![22](https://cloud.githubusercontent.com/assets/17457499/13860820/8873f334-ec8a-11e5-8f87-ac8c55311562.png)
Plataforma Art_02

**Comment by Joseangel2v** [comment]
![33](https://cloud.githubusercontent.com/assets/17457499/13860830/940b8a4a-ec8a-11e5-895d-9908b5d54008.png)
Plataforma Art_03

**Comment by Joseangel2v** [comment]
@emmysm

**Comment by Luis-Fernando-Molina** [comment]
Ok, quita la foto de abajo y volve a poner la nota musical y con eso quedaria.

**Comment by Joseangel2v** [comment]
![art 1](https://cloud.githubusercontent.com/assets/17457499/13937876/e8f868ca-efc8-11e5-8c0d-e4922fa49dce.png)
Plataforma Art_04

**Comment by Joseangel2v** [comment]
![ar 2t](https://cloud.githubusercontent.com/assets/17457499/13937889/fae5a7f0-efc8-11e5-96e2-e77d6a06e67c.png)
Plataforma Art_05

**Comment by Joseangel2v** [comment]
![art 3](https://cloud.githubusercontent.com/assets/17457499/13937896/082e53e4-efc9-11e5-8756-01c0025a0116.png)
Plataforma Art_06

**Comment by emmysm** [comment]
Después de eliminar la foto se puede ampliar los otros elementos, y la nota que sea más visible @Joseangel2v

**Comment by Joseangel2v** [comment]
Algo asi? @emmysm 
![2](https://cloud.githubusercontent.com/assets/17457499/13939051/83e093d2-efd1-11e5-80d8-cabdc0796cbb.png)
Plataforma Art_07

**Comment by emmysm** [comment]
Sube los ajustes que te pedí @Joseangel2v  por favor.

**Comment by Joseangel2v** [comment]
![3](https://cloud.githubusercontent.com/assets/17457499/13996258/320d2a72-f12d-11e5-824a-5d0b2f8b07b0.png)
Plataforma Art_08

**Comment by Joseangel2v** [comment]
![art 22](https://cloud.githubusercontent.com/assets/17457499/13996292/4b160cdc-f12d-11e5-97c2-853b7e1813c3.png)

Plataforma Art_09

**Comment by emmysm** [comment]
La propuesta 8 @Joseangel2v , genera los archivos, porfa
