### ISSUE TITLE
Generar un icono para la plataforma Marketplace

### ISSUE THREAD

**Issue by emmysm** [bitDubai/fermat-graphic-design#625]

**Comment by proseuz** [comment]
Propuesta 1 @emmysm  @@darkestpriest @Luis-Fernando-Molina 
 ![icono marketplace1](https://cloud.githubusercontent.com/assets/17308060/13443969/d9c2c8a8-dfd5-11e5-8821-1d5b6f0221b8.png)

Propuesta 2
![icono marketplace2](https://cloud.githubusercontent.com/assets/17308060/13443970/d9d1f346-dfd5-11e5-84c8-abfb8955881e.png)

**Comment by emmysm** [comment]
Los colores de la primera propuesta están más oscuros. Se pueden agregar más elementos a estas propuestas. Genera otra, @jhonmarquez92  :smile_cat:

**Comment by Luis-Fernando-Molina** [comment]
Ya tenemos un carrito de compras, pero asi y todo esto no es una tienda, sino un mercado donde se compra y venden cosas. Segui buscando y olvidate de seguir poniendo las billeteras por todos lados por favor.

**Comment by Luis-Fernando-Molina** [comment]
Los casos tienen que estar asignados.

**Comment by proseuz** [comment]
Propuesta 1
![icono marketplace5](https://cloud.githubusercontent.com/assets/17308060/13504522/0eeea02a-e147-11e5-9c77-c5861bff0cea.png)

Propuesta 2
![icono marketplace4](https://cloud.githubusercontent.com/assets/17308060/13504530/1afe1dc8-e147-11e5-98d1-10d6d173fced.png)

Propuesta 3
![icono marketplace7](https://cloud.githubusercontent.com/assets/17308060/13504537/26ea07fa-e147-11e5-90ef-283dddab80b4.png)

Propuesta 4

![icono marketplace6](https://cloud.githubusercontent.com/assets/17308060/13504543/2feb3e6e-e147-11e5-8998-157673b6a18f.png)

@emmysm @Luis-Fernando-Molina

**Comment by Luis-Fernando-Molina** [comment]
bitcoin no puede aparecer porque el sistema no depende de bitcoin, solo lo usa

Lo de las manos ya se ha usado para otra cosa.

**Comment by proseuz** [comment]
Haré otras propuestas @Luis-Fernando-Molina

**Comment by proseuz** [comment]
propuesta 1
![icono marketplace8](https://cloud.githubusercontent.com/assets/17308060/13576458/fdcc17fc-e45f-11e5-86ae-333d4aed5ab4.png)

propuesta 2
![icono marketplace7](https://cloud.githubusercontent.com/assets/17308060/13576452/f583f4f2-e45f-11e5-8e68-2c317f42fd78.png)

@emmysm @Luis-Fernando-Molina

**Comment by emmysm** [comment]
@Luis-Fernando-Molina cómo vamos por aca?

**Comment by Joseangel2v** [comment]
![4 mkp](https://cloud.githubusercontent.com/assets/17457499/13864629/6b16c528-eca3-11e5-9dce-7511564c457a.png)
Iconoplataformamarketplace_01

**Comment by Joseangel2v** [comment]
![5 mkp](https://cloud.githubusercontent.com/assets/17457499/13864652/a6abdff6-eca3-11e5-9c6a-e19123a9f99a.png)
Iconoplataformamarketplace_02

**Comment by Joseangel2v** [comment]
![2 mkp](https://cloud.githubusercontent.com/assets/17457499/13864780/c74c8f02-eca4-11e5-9aa7-0c2993e62bad.png)
Iconoplataformamarketplace_03

**Comment by Joseangel2v** [comment]
![1 mkp](https://cloud.githubusercontent.com/assets/17457499/13865092/cd9f7524-eca7-11e5-8876-e3c4c4726dd0.png)
Iconoplataformamarketplace_04

**Comment by Joseangel2v** [comment]
@emmysm

**Comment by Joseangel2v** [comment]
![2 mkp](https://cloud.githubusercontent.com/assets/17457499/13865640/af1059ce-ecad-11e5-9e3b-ee7c39af86a7.png)
Iconoplataformamarketplace_03_02

**Comment by emmysm** [comment]
@Joseangel2v me gustó bastante la última propuesta. @Luis-Fernando-Molina cómo vamos con esto?

**Comment by Luis-Fernando-Molina** [comment]
Un marketplace es un lugar donde hay multiples negocios no uno solo. Esto parece el icono de un shop.

**Comment by Joseangel2v** [comment]
![m1](https://cloud.githubusercontent.com/assets/17457499/14161716/1b14d34c-f6e6-11e5-9f9a-def7b1462337.png)
Iconoplataformamarketplace_05

**Comment by Joseangel2v** [comment]
![1 mk](https://cloud.githubusercontent.com/assets/17457499/14161723/27b0ffa4-f6e6-11e5-9107-6595211212a7.png)
Iconoplataformamarketplace_06

**Comment by Joseangel2v** [comment]
![2 mk](https://cloud.githubusercontent.com/assets/17457499/14161727/3300071a-f6e6-11e5-9368-644e258f4f93.png)
Iconoplataformamarketplace_07

**Comment by Joseangel2v** [comment]
![3 mk](https://cloud.githubusercontent.com/assets/17457499/14161731/3bdb1d5c-f6e6-11e5-9673-c8a3763217a4.png)
Iconoplataformamarketplace_08

**Comment by Joseangel2v** [comment]
![4 mk](https://cloud.githubusercontent.com/assets/17457499/14161739/43ecb44c-f6e6-11e5-83b9-1fb07b2a4fa3.png)
Iconoplataformamarketplace_09

**Comment by emmysm** [comment]
@Luis-Fernando-Molina

**Comment by Luis-Fernando-Molina** [comment]
para ir cerrando esto vamos con el ultimo, refinalo un poco y usemos esa idea

**Comment by Joseangel2v** [comment]
![icono mk 1](https://cloud.githubusercontent.com/assets/17457499/14299690/b6bc0d6a-fb55-11e5-8220-e2df72ed7633.png)
Iconoplataformamarketplace_10
