### ISSUE TITLE
Generar icono para la Singers Platform

### ISSUE THREAD

**Issue by emmysm** [bitDubai/fermat-graphic-design#626]

**Comment by emmysm** [comment]
![iconos art-04-03](https://cloud.githubusercontent.com/assets/15143489/13446942/bde5bdb6-dfe9-11e5-8be8-e8ee4dc59f11.png)
![iconos art-04-04](https://cloud.githubusercontent.com/assets/15143489/13446943/be07e94a-dfe9-11e5-8877-e6c982f88c82.png)

@darkestpriest @lostwood

**Comment by lostwood** [comment]
En este caso me inclino mas al primero, tienes buena imaginación :+1:

**Comment by darkestpriest** [comment]
Los dos están geniales @emmysm pero me inclino por el segundo.¿que opinas @GaboHub ?

**Comment by GaboHub** [comment]
Me gusta mas el primero c:

**Comment by lostwood** [comment]
:+1:

**Comment by Luis-Fernando-Molina** [comment]
el mic esta bien, pero la estrellas no. Proba con una guitarra, una nota musical, la clave de sol o cosas asi. Principal debiera ser el mic que es el instrumento de un cantante.

**Comment by emmysm** [comment]
Vale, ya genero los ajustes. @Luis-Fernando-Molina

**Comment by edwarmas** [comment]
@emmysm 
![logo](https://cloud.githubusercontent.com/assets/17460993/13534841/4ba8611e-e209-11e5-8aaf-71505da419d3.jpg)
![logo2](https://cloud.githubusercontent.com/assets/17460993/13534846/51bab138-e209-11e5-8f1a-7b28ae78e770.jpg)
![logo3](https://cloud.githubusercontent.com/assets/17460993/13534849/547d8bfc-e209-11e5-8e03-01415ce89d23.jpg)
![logo3](https://cloud.githubusercontent.com/assets/17460993/13534865/688d92c2-e209-11e5-9386-d6c0b7b396f0.jpg)

**Comment by emmysm** [comment]
Cuando subas una propuesta, trata en lo posible que sea la última que se vaya a escoger. Usa la paleta indicada que te di como ejemplo. La guitarra y el mic no tienen el mismo estilo gráfico. genera otra propuesta con una sistensis del instrumento, por favor. @edwarmas

**Comment by edwarmas** [comment]
ok perfecto

**Comment by edwarmas** [comment]
@Luis-Fernando-Molina mis propuestas:
![guitarrra4-06](https://cloud.githubusercontent.com/assets/17460993/13713864/58548304-e79d-11e5-8589-fa2821ad618e.jpg)
![guitarrra2-06](https://cloud.githubusercontent.com/assets/17460993/13713865/5bdc081c-e79d-11e5-9760-bc1606341556.jpg)
![guitarrra3-06](https://cloud.githubusercontent.com/assets/17460993/13713867/5fea7dc6-e79d-11e5-88da-c4f133f9d525.jpg)

**Comment by proseuz** [comment]
@Luis-Fernando-Molina  mis propuestas:
1
![singers platform 1](https://cloud.githubusercontent.com/assets/17308060/13713950/c3dc43a0-e79d-11e5-8ef8-f6c3d2b7b23f.png)
2
![singers platform](https://cloud.githubusercontent.com/assets/17308060/13713951/c3ec0af6-e79d-11e5-995d-b2b9d8d7daa9.png)

**Comment by emmysm** [comment]
Me gusta la primera propuesta. Prueba con otro micrófono a ver cómo queda :smiley: @jhonmarquez92

**Comment by proseuz** [comment]
@emmysm 
![singers platform 2](https://cloud.githubusercontent.com/assets/17308060/13720489/729cd128-e7dc-11e5-9f88-87927852d496.png)

![singers platform 3](https://cloud.githubusercontent.com/assets/17308060/13720515/141270a8-e7dd-11e5-9c37-2487f0c24d4a.png)

**Comment by emmysm** [comment]
@Luis-Fernando-Molina cómo vamos con esto?

**Comment by Luis-Fernando-Molina** [comment]
Usemos la ultima de todas :+1:

**Comment by edwarmas** [comment]
@Luis-Fernando-Molina gracias por la oportunidad @emmysm me informo que se termino la prueba y no continuare. Sin embargo me hubiera gustado seguir. Saludos
