### ISSUE TITLE
Generar logo para la Insurace Platform (INS)

### ISSUE THREAD

**Issue by emmysm** [bitDubai/fermat-graphic-design#628]

**Comment by proseuz** [comment]
Propuesta 1  
![insurance 3](https://cloud.githubusercontent.com/assets/17308060/13450943/b4b41e7c-e00c-11e5-9b9e-7db15b785bfb.png)

Propuesta 2
![insurance 2](https://cloud.githubusercontent.com/assets/17308060/13450969/d9d90c3a-e00c-11e5-861e-1bc4295c0658.png)

Propuesta3
![iconos desarrolladores 4](https://cloud.githubusercontent.com/assets/17308060/13450980/e3468c66-e00c-11e5-9bef-1b0090ed3415.png)

@emmysm @Luis-Fernando-Molina

**Comment by emmysm** [comment]
Me quedo con la última propuesta.Qué opinas, @Luis-Fernando-Molina ?

**Comment by Luis-Fernando-Molina** [comment]
no va por el lado de los escudos. no se por donde, se trata de compañias de seguro

**Comment by proseuz** [comment]
Propuesta 1
![insurance 6](https://cloud.githubusercontent.com/assets/17308060/13509859/f7c3f2c4-e15f-11e5-9850-91646676bc92.png)

Propuesta 2
![insurance 5](https://cloud.githubusercontent.com/assets/17308060/13509860/f7df6874-e15f-11e5-8022-7fad27057c91.png)

@emmysm  @Luis-Fernando-Molina

**Comment by Luis-Fernando-Molina** [comment]
la propuesta 1 va bien, cambia el billetito por un autito

**Comment by proseuz** [comment]
![insurance 7](https://cloud.githubusercontent.com/assets/17308060/13531324/232fc9ae-e1f8-11e5-84a6-33f7b40b4529.png)
@Luis-Fernando-Molina

**Comment by emmysm** [comment]
@Luis-Fernando-Molina  cómo vamos por aca?

**Comment by Luis-Fernando-Molina** [comment]
:+1:
