### ISSUE TITLE
Generar logo para la Reputation Platform (REP)

### ISSUE THREAD

**Issue by emmysm** [bitDubai/fermat-graphic-design#629]

**Comment by emmysm** [comment]
![iconos art-06-05](https://cloud.githubusercontent.com/assets/15143489/13451039/606f43b8-e00d-11e5-8445-810e498ef420.png)

@Luis-Fernando-Molina

**Comment by Luis-Fernando-Molina** [comment]
Ademas de las estrellas debiera haber algo que represente el texto de los reviews.

**Comment by proseuz** [comment]
Propuesta 1
![reputation](https://cloud.githubusercontent.com/assets/17308060/13512789/f801e296-e16e-11e5-9165-6061a40d5207.png)

Propuesta 2
![reputation 2](https://cloud.githubusercontent.com/assets/17308060/13512795/070628b0-e16f-11e5-90d4-89fc725ca626.png)

Propuesta 3
![reputation 3](https://cloud.githubusercontent.com/assets/17308060/13512801/0e2bd766-e16f-11e5-9214-6db184156a3d.png)

Propuesta 4
![reputation 4](https://cloud.githubusercontent.com/assets/17308060/13512807/1bf23ed0-e16f-11e5-886d-970cb11ecf9e.png)

@emmysm @Luis-Fernando-Molina

**Comment by Luis-Fernando-Molina** [comment]
Usemos la 4  :+1:

**Comment by Luis-Fernando-Molina** [comment]
@emmysm las aprobadas por favor asegurate de que se implementen en el sitio dev.ferma.org pasandole a  @Miguelcldn lo que le haga falta para esto. Gracias

**Comment by emmysm** [comment]
Vale, @Luis-Fernando-Molina me encargo de eso.

**Comment by Miguelcldn** [comment]
@Luis-Fernando-Molina REP depende de algun platform?

**Comment by Luis-Fernando-Molina** [comment]
no lo se no hicimos el analisis todavia

**Comment by Miguelcldn** [comment]
Entonces dime si espero a que tengan eso listo para agregarlo o lo agrego por ahora sin dependencia y de último en la tabla (columna más derecha). Estaremos pendientes por aquí @fuelusumar y yo.

**Comment by Luis-Fernando-Molina** [comment]
agregalos sin dependencias y despues se colocarán. gracias
