### ISSUE TITLE
Composición artística Nº 1 con el token de "1 fer"

### ISSUE THREAD

**Issue by jonathanborges3d** [bitDubai/fermat-graphic-design#630]
Viene del #627 

(Por desarrollar)

@DexybelVillanueva

**Comment by DexybelVillanueva** [comment]
@Luis-Fernando-Molina  El concepto es una escena con Los token 1 fers en movimiento, en una superficie o fondo blanco

1)![fer 1 prueba 2](https://cloud.githubusercontent.com/assets/16962860/13482927/5b179c3e-e0c2-11e5-85a2-39ed05e1a4e2.jpg)

2)![fers prueba 3](https://cloud.githubusercontent.com/assets/16962860/13482928/5b18cd2a-e0c2-11e5-831c-0d0898f2f60a.jpg)

3)![fers prueba 4](https://cloud.githubusercontent.com/assets/16962860/13482929/5b1c55d0-e0c2-11e5-8637-9a1d120b97d5.jpg)

**Comment by Luis-Fernando-Molina** [comment]
pueden ser cualquiera de las 2 o 3 o las dos, pero pongnale por favor un piso y/o fondo excelente que levante mucho mas las monedas.

**Comment by DexybelVillanueva** [comment]
Propuestas de fondos 
Versión baja resolución

1)![fers 1 fondo de prueba 1](https://cloud.githubusercontent.com/assets/16962860/13543659/7d1f5122-e23f-11e5-8f2d-b830f8cd2fd1.jpg)

2)![fer 1 prueba 2 2](https://cloud.githubusercontent.com/assets/16962860/13543662/841bc4c4-e23f-11e5-8644-9d47feafd939.jpg)

3)![fer 1 prueba 3](https://cloud.githubusercontent.com/assets/16962860/13543669/8afdc8be-e23f-11e5-8cf3-9892369824cf.jpg)

4)![fer1 prueba 4](https://cloud.githubusercontent.com/assets/16962860/13543672/996e5148-e23f-11e5-8377-172cbe233c57.jpg)

5)![fers1 fondo de prueba 5](https://cloud.githubusercontent.com/assets/16962860/13543674/a1d04d64-e23f-11e5-8dda-d692d820c445.jpg)

**Comment by Luis-Fernando-Molina** [comment]
Con fondo no me refiero a no solo a aplciarle un material, sino a algo que produzca un WOW effect. Van a tener que probablemente salir pronto de las imagenes con solo monedas y empezar a mezclarlas con objetos reales. Yo espero algo de no menor calidad que estas imágenes:

![20160305033925](https://cloud.githubusercontent.com/assets/9479367/13547344/eb8689be-e2ad-11e5-8d6f-3550520a69be.jpg)
![20160305033938](https://cloud.githubusercontent.com/assets/9479367/13547345/ecab4c26-e2ad-11e5-9a7a-52ae54173067.jpg)

Definitivamente nuestras imágenes tienen que superar todo lo que ya hay dando vuelta.

**Comment by DexybelVillanueva** [comment]
Modificaciones pertinentes de acuerdo a la sugerencia, son pruebas a baja resolución , todavía le falta modificar la iluminación un poco mas y los materiales del reloj para hacer un render mas realista

Versión 1 baja resolución
![reloj propuesta 1](https://cloud.githubusercontent.com/assets/16962860/13588213/35d9a52a-e4a0-11e5-89c8-a72e650cd0ed.jpg)

Versión 2 baja resolución
![reloj propuesta2](https://cloud.githubusercontent.com/assets/16962860/13588538/9c20a930-e4a2-11e5-8511-0ebd07dcdd56.jpg)

**Comment by Luis-Fernando-Molina** [comment]
no me referia tampoco a recrear exactamente la misma escena.

En todo caso de hacer algo mus similar se tiene que usar monedas que digan ferman en el canto.

Si vas a usar un reloj, no necesariamente debe ser un reloj pulsera. No hay modelos hechos de elemnetos de ese tamaño que se puedan usar directamente? Un reloj de mesa de luz , de esos antiguos con campanitas arriba pudiera andar.

**Comment by DexybelVillanueva** [comment]
@Luis-Fernando-Molina que le parece estas nuevas escenas? de acuerdo a lo que me habia comentado 

1)![reloj despertador 1](https://cloud.githubusercontent.com/assets/16962860/13646967/171a962a-e604-11e5-8113-f2001ebec2f2.jpg)

2)![reloj despertador 2](https://cloud.githubusercontent.com/assets/16962860/13646968/1721f424-e604-11e5-8363-3400aed577b5.jpg)

**Comment by jonathanborges3d** [comment]
Ok, Te dejo mis impresiones:

1) Debemos trabajar mejor el reloj, se ve algo lowpoly, se notan los segmentos del cilindro en el borde externo. Agregar detalles que realcen la estética general del modelo, como manecillas decoradas o las marcas de los segundos y horas.
Fíjate éste ejémplo:
![](http://fotorecurso.com/images/2015/10/08/despertador_reloj_mencillas_numero_despertar_metal_modelado_3d_render_objetos.png)

2) La escena debe tener muchas más monedas o en su defecto un ambiente mejor, te dejo como opciones posibles:  a) Modelar una cornisa o mesita de noche (Dónde generalmente se ve éste tipo de reloj), pero solo lo que se verá en el render, la superficie y una gaveta tal vez. Colocar alguna lámpara que le proporcione la iluminación a la escena y las monedas allí junto al reloj como están ahora. 
b) Colocar suficientes monedas apiladas como en la imagen referencial tanto que no den espacio de ver más allá de la superficie en que está el reloj.

Recuerda que la idea es llevar las monedas a escenas cada vez más realistas, sacarlas del ambiente virtual en el que se ven hasta ahora.

**Comment by Luis-Fernando-Molina** [comment]
Jonathan tienen que switchearse urgentemente a los conceptos nuevos y dejar las monedas para otro momento. Ya hablaste con Arnaldo o viste lo que estamos haciendo?

**Comment by jonathanborges3d** [comment]
Si Luis, he visto lo que están haciendo. Nos ponemos en eso. Ésta era una escena que estaba pendiente por terminar. La dejaremos en espera.
