### ISSUE TITLE
Composición artística Nº 1 con los tokens de "1, 10 y 100 fers"

### ISSUE THREAD

**Issue by jonathanborges3d** [bitDubai/fermat-graphic-design#633]
Viene del #627 

El concepto es una escena con muchos tokens mezclados sobre una superficie, similar a las escenas realizadas para la moneda de bitcoin y las Fiat currency.

**Comment by jonathanborges3d** [comment]
Primera versión de la escena

(Baja resolución)
![fers_art_2](https://cloud.githubusercontent.com/assets/13649739/13481298/b098c932-e0b6-11e5-8cb8-ff017d73e605.jpg)

@Luis-Fernando-Molina

**Comment by Luis-Fernando-Molina** [comment]
ahora que los veo junto noto que las de 1 fer debieran ser mas finos y de menor diametro que los de 10 fers. Los de 10 debieran quedar tal cual, y los de 100 debieran  ser mas grandes y gordos.

**Comment by jonathanborges3d** [comment]
Segunda versión:
![fers_art_2](https://cloud.githubusercontent.com/assets/13649739/13540371/3204461e-e228-11e5-8d82-156cb543a31e.jpg)

@Luis-Fernando-Molina

**Comment by Luis-Fernando-Molina** [comment]
Esta buena, revisa el tema de la iluminación, por ahí estas usando una luz de masiado blanca, porque se ve todo muy palido. Proba con spots de luz calida.

Para otra escena podes jugar haciendo pasar la luz a traves de una moneda y mostrar la sombra de la moneda con la f iluminada.

**Comment by jonathanborges3d** [comment]
Tercera versión:
![fers_art_1](https://cloud.githubusercontent.com/assets/13649739/13552033/bd62f9a4-e321-11e5-8223-a781380723eb.jpg)
