### ISSUE TITLE
Generar icono para la Lodging Platform

### ISSUE THREAD

**Issue by emmysm** [bitDubai/fermat-graphic-design#634]
![iconos art-06-06](https://cloud.githubusercontent.com/assets/15143489/13451024/3ec6405e-e00d-11e5-9732-6da89da2ca80.png)

@Luis-Fernando-Molina

**Comment by Luis-Fernando-Molina** [comment]
no entendiste que signivica lodging. Significa alojamiento. Fijate lo que hace el sitio Airbnb.com

**Comment by emmysm** [comment]
![iconos art-08](https://cloud.githubusercontent.com/assets/15143489/13482797/6187255e-e0c1-11e5-9b15-4a28ee627964.png)

@Luis-Fernando-Molina

**Comment by Joseangel2v** [comment]
![icono 1](https://cloud.githubusercontent.com/assets/17457499/13547569/cad0df82-e2d8-11e5-9b3d-9e0983c2a9c5.png)

**Comment by Joseangel2v** [comment]
![icono 2](https://cloud.githubusercontent.com/assets/17457499/13547573/f191f6a6-e2d8-11e5-89c6-b8baf12b2352.png)

**Comment by Joseangel2v** [comment]
![icono 3](https://cloud.githubusercontent.com/assets/17457499/13547589/6c7d8ca4-e2d9-11e5-8999-2b17b432c144.png)

**Comment by Luis-Fernando-Molina** [comment]
ok vamos a usar la de la casa :+1:
