### ISSUE TITLE
Generar icono para la Photography platform (PHT)

### ISSUE THREAD

**Issue by emmysm** [bitDubai/fermat-graphic-design#635]

**Comment by proseuz** [comment]
Propuesta 1
![photography](https://cloud.githubusercontent.com/assets/17308060/13452097/0a646c8c-e017-11e5-87ca-0b39ce8d8487.png)

@emmysm @Luis-Fernando-Molina

**Comment by Luis-Fernando-Molina** [comment]
Va bien pero la camara pudiera estar mejor.

**Comment by proseuz** [comment]
Mejora de la propuesta 1
![photography3](https://cloud.githubusercontent.com/assets/17308060/13480128/007a355c-e0ae-11e5-96c7-1c502d947e4b.png)

Mejora de la propuesta 2
![photography2](https://cloud.githubusercontent.com/assets/17308060/13480139/0c0a3b74-e0ae-11e5-99cb-3d2775ed8c2a.png)

Mejora de la propuesta 3
![photography1](https://cloud.githubusercontent.com/assets/17308060/13480146/16a96316-e0ae-11e5-97ec-f87201ba22a9.png)

@emmysm @Luis-Fernando-Molina

**Comment by Luis-Fernando-Molina** [comment]
Ok usemos la 3  :+1:
