### ISSUE TITLE
Generar logo para la Traking Platform (TRK)

### ISSUE THREAD

**Issue by emmysm** [bitDubai/fermat-graphic-design#636]

**Comment by emmysm** [comment]
![iconos art-07](https://cloud.githubusercontent.com/assets/15143489/13461418/63f981ec-e053-11e5-8a3f-daff0227404c.png)

@Luis-Fernando-Molina

**Comment by proseuz** [comment]
me gusta @emmysm

**Comment by Luis-Fernando-Molina** [comment]
mostra directamente un mapa sin el celular. El puntito y el camino recorrido.

**Comment by emmysm** [comment]
![iconos art-12](https://cloud.githubusercontent.com/assets/15143489/13504786/2dd53fde-e148-11e5-8fc6-4f2ef55c8c97.png)
![iconos art-12](https://cloud.githubusercontent.com/assets/15143489/13504731/f43c6a5e-e147-11e5-911c-db731f7725b9.png)
@Luis-Fernando-Molina

**Comment by emmysm** [comment]
@Luis-Fernando-Molina cómo vamos con esto?

**Comment by Luis-Fernando-Molina** [comment]
el concepto esta bien, lounico que no se nota que es un mapa

**Comment by emmysm** [comment]
Propuesta 1
![sin titulo-5-01](https://cloud.githubusercontent.com/assets/15143489/14032227/8c75c01c-f1e3-11e5-9876-0835708b9bd1.png)

Propuesta 2

![sin titulo-5-03](https://cloud.githubusercontent.com/assets/15143489/14033080/a6575ad0-f1e9-11e5-93e6-54fef3191db8.png)

Propuesta 3

![sin titulo-5-02](https://cloud.githubusercontent.com/assets/15143489/14033098/cc47a600-f1e9-11e5-903d-b6c9d2b7d7af.png)

@Luis-Fernando-Molina

**Comment by Luis-Fernando-Molina** [comment]
Usemos la propuesta 1. :+1:  saludos

**Comment by emmysm** [comment]
Gracias, @Luis-Fernando-Molina, saludos :+1:
