### ISSUE TITLE
Generar logo para la Jobs platform (JOB)

### ISSUE THREAD

**Issue by emmysm** [bitDubai/fermat-graphic-design#637]

**Comment by proseuz** [comment]
Propuesta 1
![jobs 1](https://cloud.githubusercontent.com/assets/17308060/13451977/e3cad53a-e015-11e5-97c0-19b5f662418b.png)

Propuesta 2
![jobs 2](https://cloud.githubusercontent.com/assets/17308060/13451992/fcf20a06-e015-11e5-9a97-fea87a231ae5.png)

Propuesta 3
![jobs](https://cloud.githubusercontent.com/assets/17308060/13451996/0cb0d4ea-e016-11e5-8310-3550c0c8a09c.png)

@emmysm @Luis-Fernando-Molina

**Comment by Luis-Fernando-Molina** [comment]
La 1,  :+1: Asegurate que llegue al sitio web lo antes posible.
