### ISSUE TITLE
Crear un componente de Conections para Fermat Chat

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#643]
Este componente nos permitirá elegir la conexion entre los actores existentes dentro de la plataforma de Fermat.

Los actores deben mostrarse en un listado con un check box o Radio Bottom. de esta manera activar las conexiones de los actores.

**Comment by arnaldos** [comment]
esto es lo que se ha definido https://github.com/Fermat-ORG/fermat-graphic-design/issues/525

**Comment by isahq23** [comment]
Pregunta: cuando habla sobre permitir elegir la conexión entre actores se refiere a "activar la conexión entre actores" o a "elegir el tipo de conexión a activar"? 
En caso de ser la segunda opción, qué tipos de conexión existen?

**Comment by arnaldos** [comment]
con quieres conectarte para chatear

**Comment by arnaldos** [comment]
@franklinmarcano1970 @darkestpriest @josejcb 

###### Versión 1

---

![fermat_chat_conecxion-1](https://cloud.githubusercontent.com/assets/13594347/13545143/9337ca1a-e254-11e5-9984-3e7485f5d0ff.png)

###### Versión 2

---

![fermat_chat_conexion-2](https://cloud.githubusercontent.com/assets/13594347/13545144/933cd32a-e254-11e5-90f0-c49ced285339.png)

**Comment by franklinmarcano1970** [comment]
Me gusta la versión 2.

**Comment by arnaldos** [comment]
perfecto !!

**Comment by arnaldos** [comment]
@franklinmarcano1970 @darkestpriest chicos estamos listos con esto ? puedo cerrar el caso ?

**Comment by josejcb** [comment]
listo

**Comment by arnaldos** [comment]
perfecto cierro el caso!
