### ISSUE TITLE
Crear un componente de Identities para Fermat Chat

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#644]
Este componente te permitirá elegir con cual identidad que tiene el usuario desea elegir para interactuar dentro de la app de chat. 

Una ves elegida tambien se debe permitir al usuario cambiar de identidad si asi lo desea.

**Comment by arnaldos** [comment]
esto es lo que se ha definido https://github.com/Fermat-ORG/fermat-graphic-design/issues/525

**Comment by isahq23** [comment]
Pregunta: cuántas identidades por usuario existen?

**Comment by arnaldos** [comment]
las que pueda crear

**Comment by m471c4** [comment]
@arnaldos acá una versión con un spinner sencillo para escoger la identidad. La idea sería poder hacer slide en las fotografías directamente, o elegir los nombres con las flechas:

Vista final:
![chatidentity1](https://cloud.githubusercontent.com/assets/13468350/13544915/9fdc2450-e24f-11e5-99c3-de6bdf25c97b.png)

Vista completa del spinner:
![chatidentity2](https://cloud.githubusercontent.com/assets/13468350/13544916/9ffd238a-e24f-11e5-9adb-608264617c7c.png)

**Comment by arnaldos** [comment]
@m471c4 esta bueno me gusta no se que opinen @franklinmarcano1970 @darkestpriest @josejcb

**Comment by franklinmarcano1970** [comment]
Me parece excelente.

**Comment by arnaldos** [comment]
@franklinmarcano1970 voy cerrando este caso, esto ya esta implementado cierto ??
