### ISSUE TITLE
Mejora pantallas de creación y edición la identidad de la Crypto Customer Identity

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#645]
Se debe mejorar la pantalla en que al entrar te permita realizar la acción de crear una identidad nueva. y otra de editarla un ves creada.

Podemos ver los mockups en el caso #491 
Podemos ver la vista actual en el caso #673

**Comment by arnaldos** [comment]
@vlzangel aquí el caso donde se discutirán las mejoras del boton.

**Comment by adryx83** [comment]
Hola Arnaldo, ya estoy activa veo la tarea de mejorar el boton, mi duda es
puedo acceder al editable y trabajar alli?? o debo hacerlo aparte??

Saludos,
Adry

On Fri, Mar 4, 2016 at 1:57 AM, Arnaldo Santamaria <notifications@github.com

> wrote:
> 
> Assigned #645
> https://github.com/Fermat-ORG/fermat-graphic-design/issues/645 to
> @adryx83 https://github.com/adryx83.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Fermat-ORG/fermat-graphic-design/issues/645#event-577353361
> .

## 

---

Fight back spam! Download the Blue Frog.
http://www.bluesecurity.com/register/s?user=YWRyaWFuYV9tb2xpbmE4OTgy

**Comment by adryx83** [comment]
Buenos dias, Aqui les dejo la propuesta para el Cripto Costumer Identity. @arnaldos 

![propuesta costumer identity 2](https://cloud.githubusercontent.com/assets/17273349/13672616/ccefaadc-e6a7-11e5-9fac-c4a0856c3f30.jpg)

**Comment by vlzangel** [comment]
Hola @adryx83 y @arnaldos, en el diseño de la customer identity lo que varia con respecto a la broker identity son solo dos cosas:
1. La paleta de colores (Que es como la que se usa en este modelo)
2. El botón de Visible / Not visible (En el caso del Customer el no tiene la opción para cambiar la visibilidad de su identidad)

Es decir, que el diseño tiene que ser similar al del Broker Identity pero cambiando los dos puntos antes indicados.

**Comment by arnaldos** [comment]
@adryx83  viendo lo que dice angel, apegate al diseño que se esta discutiendo en el caso #672 solo varia los puntos que nos comenta angel.

**Comment by leonacostaok** [comment]
Me gusta este diseño también, podría funcionar. Lo que si cambiaría es el tipo con el traje, capaz pondría algo más unisex. Y si lo podés presentar sin el Visible Not Visible, sería genial.

**Comment by arnaldos** [comment]
@lnacosta a mi me gusta el diseño de esta pero como @vlzangel comenta que es igual al customer y entendi quieren unificar. 

Pero pudiésemos trabajar estos ajustes a la actual propuesta que nos muestra @adryx83:

a- Usaria el fondo colo el color oscuro de la identidad (morado-azulado) de esta manera tratar de darle ese toque unisex que comenta leon. o en su defecto un gris oscuro podemos probar.
b- El icono cuando el espacio esta vació sin gradiente.
c- En las fichas colocar el nombre en en centro de la ficha.
d- El campo de la ficha diagramarlo para que se vean 3 en pantalla ocupando la pantalla

**Comment by adryx83** [comment]
@arnaldos Ok voy a trabajar en esos cambios y posteo entonces la propuesta.

**Comment by vlzangel** [comment]
Hola @arnaldos en realidad el diseño del Customer se comento que podría ser similar al del Broker, pero no necesariamente.

Si a @lnacosta le parece bien este diseño, entonces se puede usar este sin problemas.

Lo que comenta león de hacerlo más unisex (Según entiendo) es la imagen del hombre con la corbata, es decir, cambiarla por otra.

Y lo otro es lo del botón de "Visible / Not Visible" que como te comente antes no es necesario en la identity del customer.

**Comment by adryx83** [comment]
Buenas Tardes, Adjunto dos propuestas en relación a las recomendaciones sobre la primera propuesta, modifique el icono por uno mas general (ni masculino, ni femenino) elimine el boton de Visible/Not Visible, e hice la prueba con las fotos colocando el formato redondo y el otro rectangular parecido a la propuesta del Broker.

![propuesta customer identity 3](https://cloud.githubusercontent.com/assets/17273349/13712705/56e43556-e797-11e5-92a0-68bf9be7009d.jpg)

**Comment by adryx83** [comment]
![propuesta customer identity 4](https://cloud.githubusercontent.com/assets/17273349/13712731/764de0ae-e797-11e5-8917-1a714d53f08d.jpg)

**Comment by adryx83** [comment]
Buenos dias, aca les dejo la ultima propuesta con unos cambios sugeridos por @arnaldos.

![propuesta costumer identity final](https://cloud.githubusercontent.com/assets/17273349/13747268/a6bd7982-e9c9-11e5-9967-53e9e1f18ee1.jpg)

**Comment by arnaldos** [comment]
@adryx83  muy buen trabajo !!!  y doy el ok :+1:  que opinan ustedes ? @lnacosta @vlzangel @nelsonalfo

**Comment by leonacostaok** [comment]
Please, let's start commenting in English.
I think that's OK, please @vlzangel talk to @gustl-arg for the messages in the views. For example, here I think that we have to show a _**NO identities**_ instead of _**NOT identities**_ label, maybe it's a detail, but we must to be in each one of them. Where it says _**Name**_ is _**Name or Alias**_.
The tutorials must be correctly spelled and semantically attained, too.

**Comment by vlzangel** [comment]
OK perfect.

**Comment by arnaldos** [comment]
@vlzangel avísame cuando esto este implementado, y si les hace falta alguna cosa.

**Comment by vlzangel** [comment]
You can close this @arnaldos
