### ISSUE TITLE
DAP__home_Asset_Wallet_Issuer

### ISSUE THREAD

**Issue by ivonnesantos** [bitDubai/fermat-graphic-design#646]

**Comment by ivonnesantos** [comment]
![propuestas-01](https://cloud.githubusercontent.com/assets/15238660/13502201/212eb26c-e13c-11e5-92cd-e8331a880cbf.jpg)
@yojoaquin

**Comment by ivonnesantos** [comment]
@yojoaquin tengo toda esta app estancada porque aun no definimos esto podrías revisar esto los el supperissues es el #582 es donde esta la como funciona la aplicación en general y los casos de las panatllas es #647 detail/send y  #649 contactos en este te hice unos comentarios

**Comment by javafrank** [comment]
Attached a new proposal for the issuer wallet home, questions and suggestions are welcomed.

![screenshot from 2016-04-08 08 32 19](https://cloud.githubusercontent.com/assets/13275281/14398498/6d52ceec-fdae-11e5-9aca-186ff0c95d25.png)

Specifications
https://www.google.com/design/spec/components/cards.html#cards-content-blocks

![screenshot from 2016-04-08 08 24 22](https://cloud.githubusercontent.com/assets/13275281/14398609/4851863c-fdaf-11e5-820a-5244cbbe8212.png)

cc @ivonnesantos @acostarodrigo @nindriago @yojoaquin

**Comment by ivonnesantos** [comment]
@javafrank la foto debe ser grande voy a tomar las funciones que aplicaste en tu boceto y la voy a integrar a mi propuesta. Así es como trabajaremos esto. @acostarodrigo @nindriago  si ya hicieron el analisis por favor notifiquenmelo para yo saber lo que hay que hacer. Gracias

**Comment by javafrank** [comment]
@ivonnesantos i think that the picture don't have to be too big, because the issuer knows that have, and he as company should be manage several assets, my proposal is follow the google recomendations, about the screen below i think we should follow the google standards as much as possible, because this standards are created meticulously and fit very well on android OS and devices. I would like to know the point of views of @nindriago @acostarodrigo and @yojoaquin and reach agreement on this.

**Comment by ivonnesantos** [comment]
@javafrank la foto grande la pidio luis hace mucho tiempo eso es una correccion que el hizo que es lo que dice luis, que el issuer va a tener muchos asset y necesita ver con facilidad cada asset y a mi me parece que está en lo cierto.

**Comment by Luis-Fernando-Molina** [comment]
coincido con lo que dice Luis.  :+1:  You have to imagine a marketing guy making several different types of promotions some of them similar to the others. It should be easy for him to see the different assets by watching at the pictures.

**Comment by ivonnesantos** [comment]
@javafrank @nindriago @pennyxz @arnaldos @jinmyjbv  me pueden dar su opinión sobre la propuesta de colores que hice

**Comment by ivonnesantos** [comment]
![home_issuer-03](https://cloud.githubusercontent.com/assets/15238660/14477002/f8cad31a-00d4-11e6-96d9-cd252e188ec5.jpg)
@javafrank @javafrank @pennyxz @jinmyjbv

**Comment by ivonnesantos** [comment]
Yo pienso que la opccion de stats y transaction deberia estar en las opciones generales como lo planteo en la segunda propuesta:
![home_issuer-04](https://cloud.githubusercontent.com/assets/15238660/14477251/64d5b1be-00d6-11e6-9c94-23ba80303ff6.jpg)
@nindriago @javafrank

**Comment by ivonnesantos** [comment]
Propuesta_1
![home_issuer-03](https://cloud.githubusercontent.com/assets/15238660/14480954/e65cb22a-00f7-11e6-98cd-c119439575cc.jpg)

Propuesta_2
![home_issuer-04](https://cloud.githubusercontent.com/assets/15238660/14480961/f87ce5ce-00f7-11e6-8efb-8eb943fdc0bb.jpg)

Propuesta_3
![home_issuer-05](https://cloud.githubusercontent.com/assets/15238660/14480965/02bef554-00f8-11e6-9cbe-6ce8a407ccfc.jpg)

@nindriago @javafrank @jinmyjbv @pennyxz

**Comment by pennyxz** [comment]
@ivonnesantos I like proposal number 2 the most, but in my opinión, the buttons take out some asset pic visibility. I would rather put them like the bottom part of proposal number 3. And the number of assets in the left corner aren't that visible. Can be bigger maybe? 

Me gusta la segunda propuesta mas, pero en mi opinión los botones restan visibilidad a la imagen del asset. Yo los pondría abajo como la parte baja de la tercera propuesta (como iconos). La cantidad de assets no se ve muy bien. Tal vez ponerla un poco mas grande pero sin restar visibilidad. Tal vez también jugar con otros colores allí.

**Comment by javafrank** [comment]
Issuer Wallet Home, by @Fermat-ORG/skynet-team , for discussion..

![screenshot from 2016-04-13 09 34 47](https://cloud.githubusercontent.com/assets/13275281/14496185/2c35610c-015c-11e6-9c44-30f5c1f316a6.png)

cc @acostarodrigo @ivonnesantos

**Comment by ivonnesantos** [comment]
Propuesta_1
![home_issuer-01](https://cloud.githubusercontent.com/assets/15238660/14500248/1f1105a8-016b-11e6-904d-63e382b8caad.jpg)

Propuesta_2
![home_issuer-02](https://cloud.githubusercontent.com/assets/15238660/14500262/2d4cea92-016b-11e6-8bcf-4e45e5993e2e.jpg)

@javafrank @nindriago 
tienen una pequeña diferencia en la cantidad de asset a mi me gusta la 1

**Comment by acostarodrigo** [comment]
From the last two, I would choose number 1.

But keep in mind than in the next version we will be generating assets per millions, so wouldn't be strange to have huge amounts of assets.

I would go with Frank's proposal of having the number out of the image on top.

**Comment by ivonnesantos** [comment]
@acostarodrigo ya voy a hacer dos propuestas considerando eso

**Comment by ivonnesantos** [comment]
@jinmyjbv @nindriago @pennyxz @javafrank @acostarodrigo 
Propuesta_1
![home_issuer-01](https://cloud.githubusercontent.com/assets/15238660/14506096/f60fcc0a-0185-11e6-851d-ef276e2b26af.jpg)

Propuesta_2
![home_issuer-02](https://cloud.githubusercontent.com/assets/15238660/14506103/fefbcd8c-0185-11e6-96bb-5d5a1f4e3ee6.jpg)

Propuesta_3
![home_issuer-03](https://cloud.githubusercontent.com/assets/15238660/14506110/0665bae2-0186-11e6-9e53-066964403563.jpg)

**Comment by jinmyjbv** [comment]
Of the last to i would go with proposal 1, that way the lower part os not loaded with too much text,  and the red color fits the wallet colors. 

De las ultimas dos propuestas me gusta la numero 1, pienso que de esa forma no se carga tanto de texto la sección inferior y el color rojo no desentona con los colores de la wallet.

**Comment by ivonnesantos** [comment]
@jinmyjbv son tres propuesta cual te gusto las dos la que tiene el color verde?

**Comment by jinmyjbv** [comment]
@ivonnesantos Disculpa,  de las ultimas tres propuestas me gusto la primera,  la que tiene el numero dr los assets arriba con el fondo rojo.

**Comment by ivonnesantos** [comment]
![home_issuer-01](https://cloud.githubusercontent.com/assets/15238660/14541501/0f3adea8-0254-11e6-9b05-e453d3f55799.jpg)
Resultado Final @nindriago le subi un poco el texto del nombre asset y le subi un poco el tamaño a la fuente esto esta aprobado y se estan generando los recursos para desarrollo
@javafrank

**Comment by nindriago** [comment]
Excellent :+1:

**Comment by ivonnesantos** [comment]
Recursos generados y en repositorio https://github.com/ivonnesantos/fermat-graphic-design/commit/085799c5833324ea715a177716389f923f30b311 @javafrank @nindriago

**Comment by adryx83** [comment]
Buen dia @ivonnesantos aca unas ideas para el icono del Asset Issuer

![icon no asset home_issuer](https://cloud.githubusercontent.com/assets/17273349/14610321/453a9f1a-0557-11e6-8b81-33fc8a1b3427.jpg)

**Comment by ivonnesantos** [comment]
Nos vamos por la 4.
1. Quita la card
2. puedes utilizar el mismo color de los iconos variando las tonalidades
3. mejora un poco forma de cupón para que se vea mejor que es un cupón 
4. crea una composición que exprese que "no hay cupones" sin necesidad de tener  la frase "No assets".

puedes cambiar el color de fondo en este caso siempre y cuando se vea sutil no utilices gradients porque en esta app no se está trabajando ese estilo. Puedes utilizar patones siempre que no interfiera con el icono central y no moleste a la vista si lo ves en teléfono.

**Comment by adryx83** [comment]
Buenas tardes, aca otras propuestas... @ivonnesantos 

![icon no asset 1](https://cloud.githubusercontent.com/assets/17273349/14617403/e15cea86-0577-11e6-9925-6725a255c9b7.jpg)

![icon no asset 2](https://cloud.githubusercontent.com/assets/17273349/14617405/e26bf962-0577-11e6-841c-085433233537.jpg)

![icon no asset 3](https://cloud.githubusercontent.com/assets/17273349/14617408/e56312e0-0577-11e6-8a9d-084223d01203.jpg)

**Comment by ivonnesantos** [comment]
desarrolla la primera (quitale la card el recuadro con puntas redondeadas y sombra) porque el uso de card tiene un objetivo específico. otras propuestas de colores parece una maqueta y no lo es.

**Comment by adryx83** [comment]
@ivonnesantos aca unas propuestas con color... 
![icon no asset 4](https://cloud.githubusercontent.com/assets/17273349/14619984/2cdf49ac-0584-11e6-8348-4f810adabd63.jpg)

**Comment by ivonnesantos** [comment]
Propuesta 2: Aumenta el recuadro o disminuye los cupones de tal manera que te quede un margen de 20px en el trazo del recuadro disminuye el grosor y no le coloques un color resaltante mas bien mantente en la misma gama sea mas oscuro o mas claro.

Con la propuesta 2 y 3 vas a crear propuestas de color distintas. Vas a entrar en https://color.adobe.com/es/ y con el color 536DFE como base vas a hacer combinaciones distintas.

En total me estarias entregando 3 propuestas.

**Comment by adryx83** [comment]
@ivonnesantos Pruebas de color...

![icon no asset 5](https://cloud.githubusercontent.com/assets/17273349/14622834/8add7c7e-0596-11e6-90d8-38a94e7eed5f.jpg)

**Comment by ivonnesantos** [comment]
Me gusta la primera unos detalles el simbolo que utilizaste para not (stop) colocalo en este color E53935, el recuadro lo vas a dividir en dos en sentido vertical y a la mitad derecha le vas a poner el tono azul que pusiste en el segundo cupon de la segunda propuesta.@adrix83

**Comment by adryx83** [comment]
@ivonnesantos 

![icon no asset 6](https://cloud.githubusercontent.com/assets/17273349/14639514/f84d1222-0606-11e6-910e-30b95e0fb978.jpg)

**Comment by ivonnesantos** [comment]
@adryx83 me gustaba mas como estaba con el recuadro antes los cupones si están bien. le puedes poner una sombrita leve y listo.

**Comment by arnaldos** [comment]
@ivonnesantos @adryx83 si este icono es para indicar que no hay assets les recomiendo trabajar formas mas simples, veo en  los assets están separados con sombras. yo trabajaria algo similas a esto los tickest o cupones son vectores separados. fijense en el ejemplo esta a un solo tono y se entiende igualmente los elementos sin ser recargados 

![untitled-1vs](https://cloud.githubusercontent.com/assets/13594347/14644791/20461d4e-061d-11e6-8bb0-04808d0cc519.jpg)

**Comment by ivonnesantos** [comment]
@adrix lo que puedes hacer es el corte como el el ejemplo que te indica arnaldo y agrandar la esquinas de los cupones hacia adentro, puedes hacer crecer el icono de stop y poner las lineas punteadas y el simbolo de stop en azul pero tendria que ser el mismo tono de azul si lo que quieres es que se vea hueco este icono no me gustaria tan simple por su tamaño, ubicacion y uso pero si asi como se esta trabajando en las otras app pues vamos a mantenerlo simple. Crea una propuesta a ver deja esta que hiciste como esta para no descartarla todavia. Busca simplicidad pero que se vea bien.

**Comment by ivonnesantos** [comment]
@adrix vamos a hacer esta propuesta podemos colocar el trazo mas grueso en el tono azul que estas usando como base y la parte de dentro del recuadro sea en un tono gris claro muy claro los cupones los trabajas en los tonos azules  que planteaste en la propuesta de color 2 pero puedes utilizarlo de distinta forma unos pueden ser con el relleno azul en los tres tono otros pueden ser gris o blanco con trazo en azul y asi juega con eso para que sea algo simple pero original que no se vea prefabricado.

**Comment by adryx83** [comment]
@ivonnesantos Tambien me parece mas la sencillez para este tipo de iconos, trate de darle sencillez y jugar un poco con los colores, según lo que me sugeriste. 

![icon no asset 8](https://cloud.githubusercontent.com/assets/17273349/14653915/21fa0e48-0645-11e6-8032-34cc380f2fb1.jpg)
![icon no asset 9](https://cloud.githubusercontent.com/assets/17273349/14654072/bec2790e-0645-11e6-99e4-2a8b4b7ac0df.jpg)

**Comment by ivonnesantos** [comment]
Propuesta 1 aclara mas el fondo del recuadro que quede casi blanco pero que no llegue al blanco los dos cupones que están detras los vas poner de tonos del azul base mas claro.

**Comment by ivonnesantos** [comment]
Propuestas basandome en lo que hizo @adryx83, espero por las correcciones que te hice arriba y vemos cual nos gusta mas entre estas dos mias y las que tu subas.
![icon no asset 2-01](https://cloud.githubusercontent.com/assets/15238660/14661407/3688f3e2-0677-11e6-8044-17ad0733f1fe.png)
![icon no asset 2-02](https://cloud.githubusercontent.com/assets/15238660/14661408/3770118c-0677-11e6-8931-10a32d06a35f.png)

**Comment by adryx83** [comment]
@ivonnesantos aca esta la propuesta que sugeriste con el cambio...

![icon no asset 10](https://cloud.githubusercontent.com/assets/17273349/14674680/f6da16ec-06ce-11e6-8520-b4caa14b2d0a.jpg)

**Comment by ivonnesantos** [comment]
Claro pero hay una correccion que nunca aplicaste el corte de los cupones hazlo recto porfa

**Comment by ivonnesantos** [comment]
Y algo que note cuando vi el editable es el la base esta rectangular colocala cuadrada

**Comment by adryx83** [comment]
@ivonnesantos ah ok disculpa aqui esta con esos cambios...

![icon no asset 11](https://cloud.githubusercontent.com/assets/17273349/14675744/46a912ea-06d4-11e6-88a3-fab20ddedca6.jpg)

**Comment by ivonnesantos** [comment]
Subelo al repo voy a hacerle una correccion que creo que no estoy explicando bien no se y te aviso para que tu generes el archivo de indicaciones y los recursos

**Comment by adryx83** [comment]
@ivonnesantos  Por alguna razón no me deja subir al repo, nose sale como private me puedes ayudar con eso??

**Comment by ivonnesantos** [comment]
@javafrank este es la pantalla definitiva del homa sin asset @adryx83 te esta generando los recursos y creando el archivo de indicaciones para que la puedas montar
![home_no asset-01](https://cloud.githubusercontent.com/assets/15238660/14685742/9869adb2-06ff-11e6-86e7-89445a2158c0.png)

**Comment by arnaldos** [comment]
@nindriago @javafrank esto ya esta aplicado ??  avísenme para cerrar el caso
