### ISSUE TITLE
DAP__detail_Asset_Wallet_Issuer

### ISSUE THREAD

**Issue by ivonnesantos** [bitDubai/fermat-graphic-design#647]
La función de esta pantalla es ver el detalle de asset para enviarle el asset a varios usser

**Comment by ivonnesantos** [comment]
@arifernandez en esto vas a participar conmigo yo voy a dar una propuesta y tu otra si quieres busca otra manera de agregar los asset que se van a enviar que sea asi tipo ecualizador pero que no sea circular a ver que tal ingeniate esa función y montala en la maqueta haces un prototipo en gris y luego le metemos diseño

**Comment by arifernandez** [comment]
![dap_detail_asset_wallet_issuer 647-02](https://cloud.githubusercontent.com/assets/16305653/13545900/6b6df612-e26d-11e5-8b81-25824734656a.jpg)
![dap_detail_asset_wallet_issuer 647-01](https://cloud.githubusercontent.com/assets/16305653/13545901/6b9da81c-e26d-11e5-9793-6946418a4d4e.jpg)

Aquí hay dos propuestas @ivonnesantos @yojoaquin @Luis-Fernando-Molina

**Comment by Luis-Fernando-Molina** [comment]
no entiendo cual es el proposito de esta pantalla. Que funcionlidad se está discutiendo? Al comienzo de cada caso debiera estar la explicación. Imaginate si yo no se de que hablan, lo que pudiera deducir una persona nueva entrando aca..

**Comment by ivonnesantos** [comment]
@Luis-Fernando-Molina en el  Supperissues esta la explicacion de toda la aplicacion

**Comment by ivonnesantos** [comment]
@arifernandez el usuario aquí no va en tal caso va el nombre de asset porque este es el detail del asset con esta pantalla el issuer va a enviar los asset a los usuarios en el video que te pase se explica eso en los botones de confirmación vas a poner uno solo para ir a contactos. Porque te pregunto segun tu pantalla como va acceder el issuer a los contactos para poder enviar los asset? debes analizar todo lo que que dice en el suppreissues porque para eso los cree para discutir la funcionalidad completa de la app.

**Comment by ivonnesantos** [comment]
Esta maqueta del detail les parece funcional? @nindriago @javafrank 
https://cloud.githubusercontent.com/assets/15238660/13479613/64d7e796-e0aa-11e5-92ec-d126a9c240d7.jpg

**Comment by ivonnesantos** [comment]
@javafrank @nindriago @pennyxz @jinmyjbv si eliminamos esta pantalla como hacemos para determinar la cantidad de asset?

**Comment by nindriago** [comment]
por regla solo se envia 1 asset a cada usuario

**Comment by ivonnesantos** [comment]
ok entonces si envías a un solo usuario automáticamente se resta un asset de la cantidad y listo?

**Comment by ivonnesantos** [comment]
bueno aclarado el punto cierro el caso
