### ISSUE TITLE
Crear interface grafica y estetica para nueva Wallet Loss Protected

### ISSUE THREAD

**Issue by nattyco** [bitDubai/fermat-graphic-design#648]
**Loss Protected Wallet**

Se va  a desarrollar una nueva wallet llamada Loss Protected cuyo uso esta destinado al ahorro y a proteger al usuario de la perdida de btc al tratar de gastarlos cuando la cotizacion del dolar este por debajo del valor al cual se compraron los btc.

Para esta wallet se necesita el logotipo, colores y formato de las pantallas y navegacion.

Las pantallas y funcionalidad sera similar a la bitcoin wallet, pero se agregan algunas funciones nuevas como
- Posibilidad de hacer una transferencia a la bitcoin wallet desde esta wallet
- Pantalla para ver informacion estadisticas de bloques de valor y cuando se uso de cada uno
- Impedir que se puedan enviar btc si la cotizacion actual es menor a la cotizacion del ultimo ingreso de btc.

Las pantallas seran:

Home: resumen del balance actual de la wallet (available y book)
Listado de las ultimas transacciones enviadas y recibidas.
Se mostrara la cotizacion actual de los btc en dolares.
Barra de menu similar a la Bitcoin Wallet con icono de help y send
Menu deplegable de la derecha similar a la Bitcoin Wallet con opcion de contactos, payments request, settings, consumos y tranferencias entre wallets.

Para agrega contactos tendra las mismas opciones de la bitcoin wallet de agregar Fermat User o External User.

**Comment by m471c4** [comment]
Hola @nattyco, hace algún tiempo se habían creado este icono y este banner. ¿Se deben cambiar los diseños?

https://github.com/Fermat-ORG/fermat-graphic-design/issues/115
https://github.com/Fermat-ORG/fermat-graphic-design/issues/116

Saludos.

**Comment by nattyco** [comment]
@emmysm  @m471c4  Me parece que si podemos usar el logotipo que ya habian aprobado

**Comment by emmysm** [comment]
El icono está muy lindo @m471c4 @nattyco

**Comment by m471c4** [comment]
@nattyco @emmysm @arnaldos acá los primeros wireframes para la Loss Protected:

Vista del Home, con los bloques de valor y detalles desplegados en caso de tenerlos (por favor confirmar cuáles serían):
![wireframe1](https://cloud.githubusercontent.com/assets/13468350/13894025/d2348b40-ed35-11e5-99e2-035a8eab81d2.png)

Vista del Home, con la lista de transacciones y detalles desplegados en caso de tenerlos (por favor confirmar cuáles serían):
![wireframe2](https://cloud.githubusercontent.com/assets/13468350/13894026/d23683e6-ed35-11e5-9ed9-d9ab63a70405.png)

Vista del navigation Drawer:
![wireframe3](https://cloud.githubusercontent.com/assets/13468350/13894027/d247b3e6-ed35-11e5-853d-63525a1bb067.png)

**Comment by m471c4** [comment]
@nattyco por ahora te comparto el cambio con el Balance en el toolbar, que inicialmente muestra el Available y al tocar muestra el Book. También muestra los detalles del bloque de valor (aun no incluyo el indicador de porcentaje gráfico).

Versión 1:
![wireframechunkv1](https://cloud.githubusercontent.com/assets/13468350/13896507/c5246f18-ed5f-11e5-91ba-a63b015099ca.png)

Versión 2:
![wireframechunkv2](https://cloud.githubusercontent.com/assets/13468350/13896508/cabe52a4-ed5f-11e5-9b01-e7e7d167b378.png)

**Comment by m471c4** [comment]
@nattyco hice un cambio en el Chunk Value view, porque creo que puede mostrar un historial de gasto amplio que no queda bien en un desplegable. Lo saqué a otra vista e hice 3 versiones de porcentaje gráfico:

Versión 1 (dona):
![wireframechunkv3](https://cloud.githubusercontent.com/assets/13468350/13908202/316e52b2-eed0-11e5-93b9-14fe0b166a7c.png)

Versión 2 (barra horizontal):
![wireframechunkv4](https://cloud.githubusercontent.com/assets/13468350/13908221/35d91328-eed0-11e5-89d1-575c4da278fa.png)

Versión 3 (barra vertical):
![wireframechunkv5](https://cloud.githubusercontent.com/assets/13468350/13908223/3a930f7c-eed0-11e5-9eaf-cb703f1670b2.png)

**Comment by nattyco** [comment]
@m471c4  la version 2 me gusta mas con el porcentaje en barra horizontal

**Comment by m471c4** [comment]
@nattyco perfecto, armaré los mockups y los subo al caso :)

**Comment by m471c4** [comment]
@nattyco @Fermat-ORG/coin-diggers-team primeras versiones para el home:

Versión 1:
![lossprotected_homev1](https://cloud.githubusercontent.com/assets/13468350/13966055/ecadb676-f042-11e5-89a3-2fca6a132367.png)

Versión 2:
![lossprotected_homev2](https://cloud.githubusercontent.com/assets/13468350/13966092/1535f1da-f043-11e5-9b20-9fc546a26375.png)

**Comment by nattyco** [comment]
@m471c4  Vamos a cambiar la info a mostrar en el home, para que el usuario tenga una vista rapida de cuantos btc perdio o gano ya que esta wallet esta basada en la cotizacion del dolar y si puede gastar los btc que tiene o no.

La idea es mostrar un numero de cuantos btc gano hasta el momento con una flecha para arriba verde o si perdio la flecha va para abajo roja.

El tab de Chunk Value lo vamos a trasladar a otra pantalla a la que accede desde el menu que se abre desde la izquierda. Sobre cada fila los tildes y cruces habria q reemplazarlos por un color, verde o rojo, para que sepa que bloques de btc puede gastar si la cotizacion del dia es mayor a la cotizacion a la que entraron esos bloques. Y de ahi ir al detalle de consumos.

Estamos pensando si la transacciones van a estar en el home en otro tab o no.

**Comment by m471c4** [comment]
@nattyco @furszy 

![lossprotected_homev3sm](https://cloud.githubusercontent.com/assets/13468350/14028481/f7a6a064-f1ce-11e5-8154-b20a3731d693.png)

**Comment by m471c4** [comment]
@nattyco con las últimas mejoras que me pediste:

![lossprotected_homev4](https://cloud.githubusercontent.com/assets/13468350/14030410/9b518e18-f1d9-11e5-8733-471d1bad17af.png)

**Comment by m471c4** [comment]
@nattyco @Fermat-ORG/coin-diggers-team 

Pantallas del home:
![lossprotectedwallet1](https://cloud.githubusercontent.com/assets/13468350/14034998/2a302a56-f1fb-11e5-885c-82bca640ad03.png)

Pantallas de transacciones (enviadas y recibidas):
![lossprotectedwallet2](https://cloud.githubusercontent.com/assets/13468350/14035000/2cfbee50-f1fb-11e5-8218-8f37ae4a7684.png)

Pantallas de chunk values y detalles:
![lossprotectedwallet3](https://cloud.githubusercontent.com/assets/13468350/14035001/320ffd6e-f1fb-11e5-85ba-e5b8594ecfeb.png)

**Comment by m471c4** [comment]
@nattyco @Fermat-ORG/coin-diggers-team dos propuestas de color para el navigation drawer:

![lossprotectedwallet4](https://cloud.githubusercontent.com/assets/13468350/14038041/8d48f92a-f21d-11e5-8bf4-b5486b53c693.png)

**Comment by nattyco** [comment]
@m471c4  En el home en la parte de ganacias dejaria solo un dato de lo que seria el balance de perdidas o ganacias del dia, se mostraria solo un dato que seria positivo (flecha verde) o negativo (flecha roja) y lo pondria como mas grande

En la lista de Chunk Values no tendrian flechas, solo darle un color verde (o algun otro indicativo grafico) a la fila del chunk que puede gastar en este momento y rojo para el bloque que no puede gastar.

En el chunk value detail elindicativo de cuento gasto seria de izquierda a derecha si gasto 25% se pinta de izquierda a derecha un 25% de la franja.
En el listado seria la fecha , losbtc que gaste  y a que exchange rate.

En la parte del Navigation drawer que quieren decir esas otras imagenes de personas que se ven?
El icono de payment request seguimos usando el de la manito como en la otra wallet.

**Comment by nattyco** [comment]
@m471c4  otro detalle en el listado de chunck values arriba va a mostrar el resumen del balance como tiene en el home

**Comment by m471c4** [comment]
@nattyco perfecto, ya estoy aplicando los cambios.

En el drawer esas serían otras identidades que maneje el user, pero si no van puedo quitarlas.

**Comment by nattyco** [comment]
@m471c4  otro detalle en el listado de chunck values arriba va a mostrar el resumen del balance como tiene en el home

**Comment by m471c4** [comment]
@nattyco acá están las mejoras que me pediste.

Home:
![lossprotectedwallet5](https://cloud.githubusercontent.com/assets/13468350/14084131/2497f39a-f4e3-11e5-9164-40d9b33729cd.png)

Chunk values:
![lossprotectedwallet6](https://cloud.githubusercontent.com/assets/13468350/14084132/24a2d378-f4e3-11e5-9630-ad8312e2a877.png)

Falta cambiar el icono del drawer, ¿qué versión de color prefieres?

**Comment by nattyco** [comment]
@m471c4  Para el navigation drawer me gusta la version en azul
