### ISSUE TITLE
DAP__contactos_Asset_Wallet_Issuer

### ISSUE THREAD

**Issue by ivonnesantos** [bitDubai/fermat-graphic-design#649]
Elaborar la pantalla de contactos para seleccionar usuarios individuales y para seleccionar por grupos es decir 2 pantallas utilizar la plantilla que esta en el SUPPERISSUE #582

**Comment by MaviDavsa** [comment]
![propuestas](https://cloud.githubusercontent.com/assets/17273005/13537417/0aaaeca0-e217-11e5-8704-e4942fc1a0af.jpg)

@yojoaquin @ivonnesantos 

Propuestas de Contactos para la Issuer Wallet. Estos serán los usuarios que van a disfrutar de Asset (cupones).

**Comment by yojoaquin** [comment]
@MaviDavsa fijate en este link https://www.google.com/design/spec/style/color.html para seguir con la paleta de colores que propone y guía Google.

Te gusta esa experiencia de usuario? La entendés si es la primera vez que la ves? Podés redefinir eso?

Gracias

**Comment by MaviDavsa** [comment]
@yojoaquin Realmente si me gusta! :)... Si estamos hablando únicamente de la parte de contactos creo que esta bastante fácil de entender ...

Por otra parte, necesita que redefina una sola o las 4?

**Comment by yojoaquin** [comment]
Las cuatro son iguales.. me gustaría que usaras las paletas que muestra Google ahí. De todas maneras hay que seguir los colores que usa ese app. Te mostraron las otras pantallas?
No entiendo donde dice "Adriana" con el + al lado.. qué significa? es un usuario agregado? qué pasa si tengo 20 usuarios?

**Comment by ivonnesantos** [comment]
@yojoaquin el simbolo de mas es para agregar otros despues que ya has agregado algun usuario uno si quieres agregar 20 usuarios pues tildas veinte al la vez, lo de los colores de esta app no se han definido  por eso @MaviDavsa hizo varias propuestas de color y yo en el home #646 hice tres propuestas porfa revisa el supperissues #582 para que veas la funcion completa

**Comment by MaviDavsa** [comment]
![nueva propuesta foto](https://cloud.githubusercontent.com/assets/17273005/13692525/5a24e6bc-e714-11e5-92ee-dc63fba332f9.jpg)
![nueva propuesta 1 foto](https://cloud.githubusercontent.com/assets/17273005/13692526/5a2a1b46-e714-11e5-87f7-ea84b012c2c6.jpg)

@ivonnesantos Propuestas nena! :)

**Comment by javafrank** [comment]
Attached a new proposal for the issuer wallet deliver assets screen, questions and suggestions are welcomed.

![screenshot from 2016-04-08 09 57 06](https://cloud.githubusercontent.com/assets/13275281/14398788/b75e9a32-fdb0-11e5-95b2-db740b043bf8.png)

Specifications
https://www.google.com/design/spec/components/lists.html
https://www.google.com/design/spec/components/chips.html

cc @ivonnesantos @acostarodrigo @nindriago @yojoaquin

**Comment by acostarodrigo** [comment]
me parece bien. no te olvides que vamos a mantener tambien los grupos.

**Comment by javafrank** [comment]
Proposal of deliver assets screen with tabs (users, groups).

![screenshot from 2016-04-11 11 51 11](https://cloud.githubusercontent.com/assets/13275281/14438200/a8cdf946-ffee-11e5-8636-be578c2d820b.png)

cc @ivonnesantos @acostarodrigo @nindriago @yojoaquin

**Comment by ivonnesantos** [comment]
@nindriago @javafrank @acostarodrigo creo que el manejo de los grupos que trabajo frank tiene algunas incoherencias y no se que diferencia hay entre lo que se propuso al inicio del caso entonces cree esto a lo que todavia le faltaria como crear grupos
![delivery_issuer-03](https://cloud.githubusercontent.com/assets/15238660/14616600/e112ee70-0574-11e6-9577-a7b723ef9fbd.png)
![delivery_issuer-01](https://cloud.githubusercontent.com/assets/15238660/14616599/e1035654-0574-11e6-9710-d86613d26349.png)
![delivery_issuer-02](https://cloud.githubusercontent.com/assets/15238660/14616601/e1208062-0574-11e6-8ff8-6e8a3e08b186.png)

**Comment by javafrank** [comment]
En la primera pantalla no entiendo mucho como sería el funcionamiento, para que sería esa sombra? el control utilizado para la selección no me parece el mas adecuado ya que parecen unos radio button y hace pensar que se puede seleccionar un solo usuario, prefiero la selección de la forma como es la user wallet sobre la imagen del usuario, link del issue https://github.com/Fermat-ORG/fermat-graphic-design/issues/724 otra cosa es que no se si será necesario tener las letras del alfabeto cuando arriba de la lista hay un cuadro de búsqueda, no se que opinen ustedes al respecto @nindriago @pennyxz @jinmyjbv, para los grupos creo que es bueno dejar la imagen, asi ya eso estaria construido cuando a los grupos se le puedan personalizar las imagenes. Saludos.

cc @ivonnesantos @MaviDavsa

**Comment by ivonnesantos** [comment]
@javafrank esa sombra es la forma que encontré para que el usuario no confunda la lista de filtro de búsqueda con la lista general de los usuarios, yo si veo necesario darle algo de orden visual al usuario ya que puede tener una lista muy extensa bien podria el usuario organizar sus envíos por orden alfabético no lo sabemos de verdad no se las letras no molestan no se ven mal y agregan cierto orden para facilitar la experiencia de usuario dime por favor con bases porque no te parecen las letras? y resolvemos. El cuadro de busqueda para mi es una opción que el usuario puede usar o no, es desicion del usuario no lo podemos encasillar en usar el filtro de busqueda o si no tu vida sera miserable. Lo de los controles de seleccion si lo entiendo solo que no tenia claro si se podian seleccionar varios o ususrios o si para enviar a varios se debe crear un grupo pero ya lo arreglo

**Comment by ivonnesantos** [comment]
view de filtro busqueda
![delivery_issuer-03](https://cloud.githubusercontent.com/assets/15238660/14695964/da5aafaa-0740-11e6-83e8-7bcf3b38880b.png)
View users
![delivery_issuer-02](https://cloud.githubusercontent.com/assets/15238660/14695972/eeda1060-0740-11e6-9581-a7a4b0cd8984.png)
View Groups
![delivery_issuer-01](https://cloud.githubusercontent.com/assets/15238660/14695977/f730f760-0740-11e6-8223-7eca3d1f7d45.png)

@javafrank @nindriago

**Comment by pennyxz** [comment]
Me parece que el View de filtro de búsqueda es muy confuso, porque sobrepone como dos listas de usuarios, y se presta a bastante confusión. Soy partidaria de que se utilice el botón de búsqueda de la barra de herramientas, como siempre se ha hecho, asi se deja mas espacio para los usuarios. Y que conforme se filtre, muestre los registros filtrados y que este no afecte a la actual selección de usuarios, es decir, que el usuario pueda ir acumulando los usuarios seleccionados e ir filtrando.

**Comment by ivonnesantos** [comment]
En estas dos hice algunos cambios en la posicion de los botones
![delivery_issuer-01](https://cloud.githubusercontent.com/assets/15238660/14716526/41b8abd6-07b7-11e6-84c1-89a728838b0a.png)
![delivery_issuer-02](https://cloud.githubusercontent.com/assets/15238660/14716527/41bfe2a2-07b7-11e6-911b-7c3112fcb3bc.png)

esta la hice tomando en cuenta la observacion de @pennyxz e investigando segun otras aplicaciones cual es la mas funcional y encontre que la ventana de contactos desplazable se habre solo cuando es un accesso directo dentro de otra funcion ejemplo en mensajeria pulsas buscar y se abre una ventana de desplanzamiento sobre la funcion de mensajeria mientras que cuando pulsas en el icono de contactos entras a la agenda y la busqueda cumple la funcion de filtro que reduce las opciones. Si bien lo que podrían hacer es en el detail poner la opcion de busqueda de usuarios y en ese caso si aplicaria lo que Frank propuso en su maqueta.

![delivery_issuer-03](https://cloud.githubusercontent.com/assets/15238660/14716745/2bf1203e-07b8-11e6-98bb-45542d2897c6.png)

@nindriago @jinmyjbv @javafrank

**Comment by javafrank** [comment]
bueno, lo que me parece es que estamos mezclando 2 cosas distintas, mi propuesta con los llamados chips era un tanto diferente a lo que hemos estado haciendo en el pasado, y como le estamos dejado el abecedario y creo que la mayoría está familiarizado con lo que hemos venido trabajando entonces propongo que quitemos los llamados chips y coloquemos solo el cuadro de busqueda para que filtre en la misma pantalla, creo que esa ha sido tu ultima propuesta @ivonnesantos, lo que aun no se es si está mejor colocarlo en el toolbar o en la pantalla, en el toolbar me parece bueno porque ahorramos espacio abajo, pero no se, que piensan al respecto @nindriago @jinmyjbv ?

**Comment by ivonnesantos** [comment]
![delivery_issuer-04](https://cloud.githubusercontent.com/assets/15238660/14729424/7ef3aa78-0807-11e6-90a6-105f5afad187.png) @nindriago @javafrank propuesta con la sugerencia de frank a mi me gusta bastante

**Comment by ivonnesantos** [comment]
@javafrank @nindriago generando recursos y archivo de indicaciones

**Comment by ivonnesantos** [comment]
icono no user no groups con el mismo estilo no asset del home
![delivery_no-groups-user-01](https://cloud.githubusercontent.com/assets/15238660/14890504/c286287c-0d2c-11e6-998d-a4955c1510d6.jpg)
![delivery_no-groups-user-02](https://cloud.githubusercontent.com/assets/15238660/14890505/c2875ba2-0d2c-11e6-879e-6aaebaa51ebd.jpg)

**Comment by javafrank** [comment]
haciendo la UI e interactuando con ella me parece que el botón cancel lo que hace es confundir mas al usuario deshaciendo los cambios realizados y cerrando el search, creo que lo mejor es mantener un solo boton y llamarlo "Done", al fin y al cabo es el mismo usuario quien esta viendo lo que esta haciendo en una vista que abarca su propia busqueda, bueno esa es mi opinión y fue la sensación que tuve al interactuar con la UI, que opinan ustedes? @ivonnesantos @nindriago @pennyxz @jinmyjbv

**Comment by arnaldos** [comment]
@nindriago @javafrank esto ya esta aplicado ??  avísenme para cerrar el caso
