### ISSUE TITLE
Generar logo para la capa World (WRD)

### ISSUE THREAD

**Issue by emmysm** [bitDubai/fermat-graphic-design#650]
Generar logo para la capa World. Esta capa se va a encargar de conectar a Fermat con otros sistemas externos al nuestro.

**Comment by poklouz** [comment]
![fermat_capaworld_1](https://cloud.githubusercontent.com/assets/17454702/13543105/61cf6c22-e23a-11e5-9e99-fd3de5ed0aa0.png)

Fermat_capaWORLD_1

**Comment by poklouz** [comment]
![fermat_capaworld_2](https://cloud.githubusercontent.com/assets/17454702/13543111/6eef58c2-e23a-11e5-970f-1f1418448f65.png)

Fermat_capaWORLD_2

**Comment by poklouz** [comment]
![fermat_capaworld_3](https://cloud.githubusercontent.com/assets/17454702/13543118/7de7256c-e23a-11e5-89f2-588c3ca37e65.png)

Fermat_capaWORLD_3

**Comment by poklouz** [comment]
![fermat_capaworld_4](https://cloud.githubusercontent.com/assets/17454702/13543124/8a780ae4-e23a-11e5-8ff1-a18d1fc13b18.png)

Fermat_capaWORLD_4

**Comment by emmysm** [comment]
Muy bien @poklouz! @darkestpriest, @Luis-Fernando-Molina vamos por buen camino?

**Comment by darkestpriest** [comment]
Me gustan las versiones 1 y 4, pero elegiría la 1 por ser más simplista y se notan los meridianos del planeta, aunque, a la 1 le colocaría la variedad de dispositivos conectados a Fermat como lo tienen el resto de las versiones.

**Comment by Luis-Fernando-Molina** [comment]
Me parece que están en este como en otros diseños dandole demasiada importancia a la billetera, cuando en muchos casos no hay nunguna relacion con ese concepto.

El criterio creando estos logos siempre fue que del logo se tiene que poder deducir el nombre de la plataforma y en este caso yo dudo que alguien deduzxa la palabra World de estas propuestas. Alcanzaría con dibujar un planeta.

**Comment by Luis-Fernando-Molina** [comment]
Otra cosa a tener en cuenta es el tema de las sombras, que sea coherente con el resto de esta linea de diseño.

**Comment by Joseangel2v** [comment]
![1](https://cloud.githubusercontent.com/assets/17457499/13654329/fa417c22-e657-11e5-89a8-d41187083cb1.png)
Fermat_capaWORLD_5

**Comment by Joseangel2v** [comment]
![2](https://cloud.githubusercontent.com/assets/17457499/13654430/8d8e7a02-e658-11e5-848b-d19a9afd5f31.png)
Fermat_capaWORLD_6

**Comment by Joseangel2v** [comment]
![2-1](https://cloud.githubusercontent.com/assets/17457499/13654436/96c7eb8a-e658-11e5-904e-648ad94ff239.png)
Fermat_capaWORLD_7

**Comment by Joseangel2v** [comment]
![3](https://cloud.githubusercontent.com/assets/17457499/13654446/aa56f5c4-e658-11e5-8101-8bac00b9bf63.png)
Fermat_capaWORLD_8

**Comment by Joseangel2v** [comment]
![3-1](https://cloud.githubusercontent.com/assets/17457499/13654456/b6b80efc-e658-11e5-90f2-d17522341d54.png)
Fermat_capaWORLD_9

**Comment by Joseangel2v** [comment]
![3-2](https://cloud.githubusercontent.com/assets/17457499/13654469/ccb9abac-e658-11e5-84b9-0491ece8bb18.png)
Fermat_capaWORLD_10

**Comment by Joseangel2v** [comment]
![3-3](https://cloud.githubusercontent.com/assets/17457499/13654479/daa22e60-e658-11e5-932f-cc98b5f74722.png)
Fermat_capaWORLD_11

**Comment by Joseangel2v** [comment]
![4](https://cloud.githubusercontent.com/assets/17457499/13654487/f21bd0e6-e658-11e5-8b61-79d26a093482.png)
Fermat_capaWORLD_12

**Comment by darkestpriest** [comment]
Saludos @Joseangel2v podrías colocarle un número de versión a cada icono, así puedo hacer referencia al mismo, gracias.

**Comment by Joseangel2v** [comment]
Ok. Listo!

**Comment by darkestpriest** [comment]
Los logos están geniales, yo me quedaría con la versión 9.

**Comment by Luis-Fernando-Molina** [comment]
Podemos usar la version 9 pero dibujale un continente que se reconozca como de nuestro planeta. Gracias.

**Comment by emmysm** [comment]
@Joseangel2v Recuerda ajustar las dimensiones y la sombra que te indiqué :smile:

**Comment by Joseangel2v** [comment]
![1](https://cloud.githubusercontent.com/assets/17457499/13686146/aaa2f534-e714-11e5-8cc4-0cf33ce0cd74.png)
Fermat_capaWORLD_13

**Comment by Joseangel2v** [comment]
![2](https://cloud.githubusercontent.com/assets/17457499/13690091/0dab1bc0-e72e-11e5-8897-2cfd807ab953.png)

Fermat_capaWORLD_14

**Comment by Joseangel2v** [comment]
![3](https://cloud.githubusercontent.com/assets/17457499/13686166/d018beca-e714-11e5-8dee-72ce4151075a.png)
Fermat_capaWORLD_15

**Comment by Joseangel2v** [comment]
![4](https://cloud.githubusercontent.com/assets/17457499/13686179/e04059ca-e714-11e5-9f4f-2af3bfb3ba2b.png)
Fermat_capaWORLD_16

**Comment by Joseangel2v** [comment]
![5](https://cloud.githubusercontent.com/assets/17457499/13686187/eadd0162-e714-11e5-8770-367de6cb2e42.png)
Fermat_capaWORLD_17

**Comment by emmysm** [comment]
Me inclino por la penúltima propuesta. @Luis-Fernando-Molina qué opinas?

**Comment by darkestpriest** [comment]
Yo me quedaría con la versión 17. @emmysm ¿podrías colocar este logo a la plataforma TOK provisionalmente? Mientras se diseña el logo de la misma.

**Comment by emmysm** [comment]
Vale, ya lo hago @darkestpriest

**Comment by arnaldos** [comment]
@emmysm @Joseangel2v muy buen trabajo !!! me inclino por la versión 17 ya que 16 como dice emmy engloba solo el continente americano. en cambio el 17 se puede apreciar que abarca todos los continentes.

**Comment by Luis-Fernando-Molina** [comment]
> Yo me quedaría con la versión 17. @emmysm ¿podrías colocar este logo a la plataforma TOK provisionalmente? Mientras se diseña el logo de la misma.

La plataforma de Tokenly debiera llamarse TKY para seguir con la lógica de los nombres que llevamos.
