### ISSUE TITLE
Infografia para The Sharing Economy To Peer to Peer Economy

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#653]
Consiste en realizar un gráfico que represente el intercambio de productos entre dos personas, teniendo como intermediario a una empresa. 

A continuación comparto una imagen como ejemplo que sirve como idea base. 

![jcafdjeg](https://cloud.githubusercontent.com/assets/13594347/13531417/a4b3228c-e1f8-11e5-9cbf-b489b05763e8.png)

Debemos mejorar la estética de estas síntesis gráficas.

La estructura debe ser 
#### Versión 1

Las dos personas en el medio en la parte superior de las manos el producto y en la parte inferior la empresa los logos de estas empresas deben ser extraídos de internet.
#### Versión 2

Las dos personas en el medio el logo la empresa los logos de estas empresas deben ser extraídos de internet.

enlace de la reunión 

https://www.youtube.com/watch?v=bTUcnUg6tmQ

**Comment by ivonnesantos** [comment]
@Brinelddy encargate de hacer unas propuestas los logos lo mismos que estan alli

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina  @gabymado así va el avance de la infografia 
![infografia2](https://cloud.githubusercontent.com/assets/13594347/13542070/966f81b8-e232-11e5-9e7e-7e595696ebbd.jpg)

**Comment by arnaldos** [comment]
debo ajustar cosas como los logos y los productos !! lo voy subiendo en un momento espero sus comentarios

**Comment by Luis-Fernando-Molina** [comment]
Tenes mis ultimas observaciones no @arnaldos ? no recuerdo por donde te las envié.

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina te comparto las versiones según las observaciones que me diste 

## Versión 1

![infografia21](https://cloud.githubusercontent.com/assets/13594347/13548147/5ea535dc-e2bb-11e5-91ba-232d01029b1c.jpg)

## Versión 2

![infografia22](https://cloud.githubusercontent.com/assets/13594347/13548148/5ea9c7aa-e2bb-11e5-9252-a2deda8e8e0b.jpg)

**Comment by Luis-Fernando-Molina** [comment]
ok vamos con la version 2.

Proba por favor que:
- EL circulo de cada empresa, ponelo como en perspectiva asi parece como si fuese una mesa. El logo tiene que estar en perspectiva pero se tiene que ver bien
- Para empresas super conocidas como Airbn y otras que tienen logo y palabra, pone el logo mas grande y abajo mas chiquita la palabra.
- Tenes que poner todos los elementos que salien en la imagen original y mas empresas que lo representen.

**Comment by isahq23** [comment]
Buenas tardes, aquí dejo un par de propuestas de cómo puede ser el "Peer to Peer"
Principalmente la relación entre usuarios y el producto

![ptp_1](https://cloud.githubusercontent.com/assets/15214774/13580653/6ab51e9e-e475-11e5-9498-d7d8efd09e3d.jpg)

![ptp_2](https://cloud.githubusercontent.com/assets/15214774/13580658/702dd5b4-e475-11e5-8bbd-5fcafac115e4.jpg)

**Comment by Luis-Fernando-Molina** [comment]
No estoy seguro que las flechas hagan falta

**Comment by adryx83** [comment]
Buenas Tardes, aquí les dejo una propuesta para la diagramación de la gráfica de The Sharing Economy.

![propuesta infografia](https://cloud.githubusercontent.com/assets/17273349/13581475/3f9a8182-e479-11e5-8c8a-0dfc97d5f75f.jpg)

**Comment by isahq23** [comment]
@Luis-Fernando-Molina las flechas las había visualizado como de retroalimentación, pero también puede funcionar sin ellas.
Muy bien, qué tal así?

![ptp_1-1](https://cloud.githubusercontent.com/assets/15214774/13581898/5c790e84-e47b-11e5-9426-b426b83eddcb.jpg)

![ptp_2-1](https://cloud.githubusercontent.com/assets/15214774/13581902/61d9175c-e47b-11e5-8766-bfb726c0158b.jpg)

**Comment by adryx83** [comment]
Buenas Tardes, esta es otra propuesta de la gráfica, con los nuevos avatars.

![propuesta infografia2](https://cloud.githubusercontent.com/assets/17273349/13585974/adb093c0-e490-11e5-8bce-4c7dae567482.jpg)

**Comment by Luis-Fernando-Molina** [comment]
Que paso con esto que dije los otros dias:

> EL circulo de cada empresa, ponelo como en perspectiva asi parece como si fuese una mesa. El logo tiene que estar en perspectiva pero se tiene que ver bien
> Para empresas super conocidas como Airbn y otras que tienen logo y palabra, pone el logo mas grande y abajo mas chiquita la palabra.
> Tenes que poner todos los elementos que salien en la imagen original y mas empresas que lo representen.

**Comment by Luis-Fernando-Molina** [comment]
El grafico tiene que mostrar al mismo tiempo la Sharing Economy y la P2P economy 

El tema del celular en el medio no me parece. Si pudieran estarn en los circulitos y organizados de alguna manera diferente a la grilla original

**Comment by arnaldos** [comment]
Luis lo que me comentabas del gif

![b1](https://cloud.githubusercontent.com/assets/13594347/13588356/5a194cbe-e4a1-11e5-9d2e-af80054eb3ad.gif)

**Comment by Luis-Fernando-Molina** [comment]
@arnaldos Vamos a usar la linea gráfica definida en https://github.com/Fermat-ORG/fermat-graphic-design/issues/662#issuecomment-193508567 . Respecto a los gifs, vamos a hacer la animación pero sin los frame en blanco. Vamos a usar solo dos frames por gif y un delay diferente en cada uno para que sea medio al azar.

Procede a hacer varios y pasaselo a @robertggovias para que lo pruebe en una grilla en una pagina web de ejemplo. La pagina debiera mostrar en full screen las dos economias una al lado de la otra como teníamos arriba.

Cuando termines con todo esto @arnaldos seguí con los casos habituales.

**Comment by m471c4** [comment]
@Luis-Fernando-Molina @arnaldos con la línea gráfica del caso 662 aplicada:

![infografia](https://cloud.githubusercontent.com/assets/13468350/13616248/425ebcf8-e54b-11e5-859b-e0f6327832f3.jpg)

Faltaría hacer los gifs de cada grupo.

**Comment by arnaldos** [comment]
@robertggovias @m471c4 @adryx83 así debe quedar la infografia va constar de una cuadricula en el como se muestra, nuestra misión: generar los gif como la muestra que coloco aquí abajo.

##### Infografia

## ![infografia3](https://cloud.githubusercontent.com/assets/13594347/13620089/4eceeb98-e55f-11e5-8204-972f4b4d645d.jpg)

##### Gif

![gif2](https://cloud.githubusercontent.com/assets/13594347/13620358/34e10a66-e561-11e5-96b1-910a0ef6336b.gif)

###### Los gif debe tener:
- Tamaño de 150x150 px
- Sin fondo o fondo transparente 
- La animación consta de 2 frames 
- Cada frame 1,5 seg
- El gif debe tener la opción de loop activado

Por el momento esas son las especificaciones, pueden variar su tamaño de acuerdo las recomendaciones de @robertggovias

La idea es la animación de los gif salgan de manera aleatoria, en cada cuadricula correspondiente.

@m471c4 Encárgate del lado de Sharing Economy 
@adryx83 Encárgate del lado de Peer to Peer Economy

**Comment by Luis-Fernando-Molina** [comment]
No alcanza con 8 parejas,  tienen que ser por lo menos el doble,  abajo de las actuales,  sin repetir la gente ni las empresas.Decile a Gaby Arnaldo qué te pase más empresas.

**Comment by Luis-Fernando-Molina** [comment]
Veo que el gif de ejemplo arranca  en blanco,  no debe ser así. Debe arrancar con el frame 1.

Adicional a eso casa gif debe tener un time diferente para cambiar cada frame.  Deben ir en el rango de medio segundo a 3segundos x feameframe,  colocarle el valor aleatoria mente para que la grilla se cambie cada pareja en momentos diferentes con un look ramdom
