### ISSUE TITLE
Composición artística Nº 2 con los tokens de "1, 10 y 100 fers"

### ISSUE THREAD

**Issue by jonathanborges3d** [bitDubai/fermat-graphic-design#655]
Viene del #627

Primera versión:
(Baja resolución)
![fers_art_4](https://cloud.githubusercontent.com/assets/13649739/13543720/1e138134-e240-11e5-81c6-afd75fba756a.jpg)

@Luis-Fernando-Molina

**Comment by Luis-Fernando-Molina** [comment]
muy bueno, yo solole cambiaria que pondria la F bien vertical en las monedas que están paradas. Tambien un poquito mas desordenadas las de un fer porque se ven irreales tan derecha, las de 10 tambien.

**Comment by jonathanborges3d** [comment]
Segunda versión:
![fers_art_4](https://cloud.githubusercontent.com/assets/13649739/13557067/cc02cb58-e3ba-11e5-8423-4184ece2ee7b.jpg)
