### ISSUE TITLE
Mejorar el Container de las Comunities de Fermat App

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#659]
Actualmente el contenedor, es una carpeta que nos muestra todos los iconos de las communities existentes.

Se debe re-estructurar esta sección, la cual se va a trabajar con los banners de cada una de ellas, se vera reflejado un listado de banners, de esa manera podremos identificar cada una de las communities

**Comment by arnaldos** [comment]
@furszy te comparto el contenedor de las communities

#### Version 1

---

## ![community-view-1](https://cloud.githubusercontent.com/assets/13594347/13626016/f1d2fcb4-e58f-11e5-8b04-329b83c8bb3b.png)

## ![community-view-2](https://cloud.githubusercontent.com/assets/13594347/13626017/f1d8aa6a-e58f-11e5-9489-67e895f0796e.png)

## ![community-view-3](https://cloud.githubusercontent.com/assets/13594347/13626018/f1dd6456-e58f-11e5-8190-691a1de57cf3.png)

![community-view-5](https://cloud.githubusercontent.com/assets/13594347/13626015/f1d0073e-e58f-11e5-8dc2-fb8687158141.png)

#### Version 2

---

## ![community-view-4](https://cloud.githubusercontent.com/assets/13594347/13626054/36104a08-e590-11e5-886a-6ae63fbc4be9.png)

![community-view-6](https://cloud.githubusercontent.com/assets/13594347/13626055/36176d74-e590-11e5-99c2-a31442368ee7.png)

**Comment by furszy** [comment]
@arnaldos van a quedar chicos los banners con 4, el teléfono que pusiste de imagen es una tv de 20 pulgadas maso menos, hagamos lo de 3. Falta saber donde ubicamos el filtro.

**Comment by arnaldos** [comment]
vale ya me pongo con eso

**Comment by furszy** [comment]
@arnaldos ....

**Comment by furszy** [comment]
@Luis-Fernando-Molina decime si armo esto sin el velo ese blanco que cruza la pantalla y con los cambios que le pedí a @arnaldos hace rato.
