### ISSUE TITLE
White Paper Illustration:  The Fermat P2P Network

### ISSUE THREAD

**Issue by Kate99** [bitDubai/fermat-graphic-design#660]
Illustration for White Paper to contain the following elements: 
1)  Internet
2)  Fermat P2P Network
3)  Nodes
4)  Fermat Extended Network
5)  Network clients (devices)

This illustration has three main parts, the Internet, the Fermat P2P Network and the Fermat Extended Network. Show the Fermat P2P Network on top on the Internet, and the Fermat Extended Network, which includes the Fermat P2P Network, on top of the Fermat P2P Network.

Inside the P2P Network, the Nodes are connected. On approximately two prominent lines that connect the Nodes, add the label ‘Fermat protocol’. 

The Nodes also connect to Network Clients outside the Fermat P2P Network, but within the Fermat Extended Network.

**Comment by gustl-arg** [comment]
@Kate99 thanks for your clear collaboration...I think this issue needs someone to be assigned, and the rest of us to follow it...let me ask @Luis-Fernando-Molina  who to assign...
