### ISSUE TITLE
Infografia para representar el concepto de Competitions to Collaborations

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#661]
Como se hablo en la reunión, debemos resaltar gráficamente la evolución de el concepto de la competencia entre Empresas o Start-ups, en busqueda posicionar un producto en el mercado, a la colaboración entre si para sacar un producto de calidad y luego establecer su mercado partiendo del producto ya establecido.

dejo el enlace de la reunión 

https://www.youtube.com/watch?v=bTUcnUg6tmQ

**Comment by MaviDavsa** [comment]
![infografia 1](https://cloud.githubusercontent.com/assets/17273005/13580808/06cb95ba-e476-11e5-97e7-add95ed7f793.jpg)
![infografia 2](https://cloud.githubusercontent.com/assets/17273005/13580809/06d1f1bc-e476-11e5-8e2f-beaf5f62455d.jpg)

Hola muy buenas tardes! :) Esta fue la idea que maneje para representar el concepto de Competitions to Collaborations... En cuanto al tema esta fue la idea que me vino y aquí esta diseñada, creo que hay que pulirla tal vez más pero, este es el diseño o son los diseños... En uno agrego un items con lo que seria la corporación porque me parece importante comentarlo, dar a entender lo que es y en el segundo manejo un concepto mas al grano, al quitar todo en cuanto a la corporación se refiere... :) 

@ivonnesantos @arnaldos @Luis-Fernando-Molina

**Comment by ivonnesantos** [comment]
ok viendo el video de nuevo entiendo en la infografía debe verse el resultado de cuando se compite y el resultado de cuando se coopera y ya luego explicar que después que se trabajo en cooperación se logra una gran idea y dentro de esa gran idea pueden desarrollarse todos los que cooperaron es asi @Luis-Fernando-Molina ?

**Comment by arifernandez** [comment]
![infografia para representar el concepto de competitions to collaborations 661-01](https://cloud.githubusercontent.com/assets/16305653/13585764/ded05f54-e48f-11e5-8b39-2357f9c145fe.jpg)

@ivonnesantos @Luis-Fernando-Molina @yojoaquin Esta es mi propuesta para la imagen

**Comment by ivonnesantos** [comment]
![ingrafia competition-01](https://cloud.githubusercontent.com/assets/15238660/13586580/03563746-e494-11e5-8e50-b609ee240b6d.jpg)
@Luis-Fernando-Molina  aca hice algo pero no se si se comprende

**Comment by ivonnesantos** [comment]
![ingrafia competition-02](https://cloud.githubusercontent.com/assets/15238660/13586994/ff043942-e496-11e5-9d20-ba23ef141223.jpg)
@Luis-Fernando-Molina

**Comment by Luis-Fernando-Molina** [comment]
Hola,  en ninguno de los casos se puede deducir el concepto que queremos transmitir

**Comment by arnaldos** [comment]
Hola @MaviDavsa  te hago una observación, cuida la construcción de los vectores, se que por la urgencia tal ves se te escapo uno que otro nodo. pero debes cuidar esos detalles antes de presentar una propuesta.

**Comment by MaviDavsa** [comment]
@arnaldos Si tienes razón! Eso mismo paso! Pero si lo haré! Gracias! :)

**Comment by ivonnesantos** [comment]
Propuesta de grafica @Luis-Fernando-Molina 
![grafica_competition_to_colaborate-01](https://cloud.githubusercontent.com/assets/15238660/13591412/74e6ab36-e4ba-11e5-99f7-bf20bb38dd11.jpg)

**Comment by emely-puerta** [comment]
![grafico](https://cloud.githubusercontent.com/assets/17557647/13592212/47d55068-e4c2-11e5-9843-17038c4c11f9.jpg) Holaa! Según lo entendido, adjunto mi prouesta @Luis-Fernando-Molina

**Comment by m471c4** [comment]
@Luis-Fernando-Molina @ivonnesantos @arnaldos mi aporte:

![competitionvscollaboration](https://cloud.githubusercontent.com/assets/13468350/13593150/12ce79b8-e4cb-11e5-83a7-741076ad753f.png)

**Comment by Luis-Fernando-Molina** [comment]
Va por el lado de lo que está proponiendo @ivonnesantos .

Crea por favor una grilla donde los iconos no toquen las lineas.

Acomoda los iconos en la misma posición que los dejé yo en la presentación. Veo que pusiste en el mismo renglon las enciclopedias con los sistemas operativos.

Buscale otra solucion para el coloreado de la parte de competition y colaboration

Los colores del fondo que usaste no creo que vayan a encajar en el sitio web

**Comment by Luis-Fernando-Molina** [comment]
Incentivized open source deber ir al tope de la escala

**Comment by Luis-Fernando-Molina** [comment]
@ivonnesantos tomá la línea gráfica de lo que hicieron en https://github.com/Fermat-ORG/fermat-graphic-design/issues/662#issuecomment-193508567 y aplicalo al gráfico tuyo con las observaciones anteriores. No puede haber fondo multicolor atrás, fijate como mejor podes adaptarte a la linea que crearon allí.

**Comment by arifernandez** [comment]
![grafica_competition_to_colaborate-01](https://cloud.githubusercontent.com/assets/16305653/13610111/55540830-e52e-11e5-90d6-b80beab360be.jpg)

@Luis-Fernando-Molina Aquí esta la propuesta modificadas, trate de asimilar lo mas que pude la linea grafica

**Comment by ivonnesantos** [comment]
@arifernandez se ve bien un detalle yo siento que la atención se centra en wikipedia y android veamos que dice @Luis-Fernando-Molina  yo solo le veo eso

**Comment by arifernandez** [comment]
Si, yo tambien me fije en eso @ivonnesantos

**Comment by ivonnesantos** [comment]
Bueno esperemos a ver si luis piensa igual o si tiene otra observacion

**Comment by ivonnesantos** [comment]
Bueno esperemos a ver si luis piensa igual o si tiene otra observacion

**Comment by Luis-Fernando-Molina** [comment]
1-los ejes con sombras no se ven bien. Debieran estar más estilizados,  más finos. 

2-el color en los labels de los ejes no se entiende 

3-la línea qué asciende no debiera tener quiebres 

4-las líneas auxiliarees debieran estar x distantes o formar una grilla

**Comment by Luis-Fernando-Molina** [comment]
Cada icono debiera estar dentro de un círculo como en el caso de las personas de Emmy

**Comment by ivonnesantos** [comment]
![grafica_competition_to_colaborate-01](https://cloud.githubusercontent.com/assets/15238660/13616933/467f1c3a-e54e-11e5-801e-8a08bbcb8961.jpg)
@Luis-Fernando-Molina  @emmysm le puse el tamaño de la mesa de trabajo igual al tuyo si cambia avisame

**Comment by emmysm** [comment]
@ivonnesantos la última mesa de trabajo que propuse tiene estas medidas: 1587,36 px x 1218,82 px, cuando amplío no se pierden detalles

**Comment by Luis-Fernando-Molina** [comment]
Ivonne ya esta mejor pero no llegamos todavía. 
Recrea el sistema de planetitos qué hizo el equipo de Emmy y mete los iconos en las órbitas como hizo ella. Tienen que quedar más o menos en la misma posición de ahora,  pero en las órbitas y más decoración de otros circuitos.

**Comment by ivonnesantos** [comment]
![grafica_competition_to_colaborate_2-01](https://cloud.githubusercontent.com/assets/15238660/13639661/eb46c5d4-e5e3-11e5-9068-220699f86e35.jpg)
@Luis-Fernando-Molina
