### ISSUE TITLE
Infografia para definir el concepto de evolucion de Inernet To Internet People

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#662]
Consiste en que el internet que actualmente funciona en la llamada nube, funcionara a través de de la plataforma entre dispositivos, sin depender de una empresa a quien pagar. quienes tienen su propia plataforma y los usuarios deben acceder para tener la comunicación entre ellos.

Enlace de la reunión

https://www.youtube.com/watch?v=bTUcnUg6tmQ

**Comment by emmysm** [comment]
![sin titulo-1-02](https://cloud.githubusercontent.com/assets/15143489/13587112/f600e40c-e497-11e5-9c9b-be799d83f9dd.png)

@Luis-Fernando-Molina indicame si voy por buen camino. Esto lo podemos ir puliendo.

**Comment by Luis-Fernando-Molina** [comment]
Esto es todo lo que tenés?

**Comment by Luis-Fernando-Molina** [comment]
Nicesito ver el gráfico completo donde se muestra la evolución del Internet

**Comment by emmysm** [comment]
![infografia recursos-03](https://cloud.githubusercontent.com/assets/15143489/13593878/9e8b1ba4-e4d1-11e5-87d2-9df0befafaea.png)

![infografia recursos-02](https://cloud.githubusercontent.com/assets/15143489/13593879/9ea2c7f4-e4d1-11e5-98d3-e104d5f57a40.png)

![infografia recursos-01-01](https://cloud.githubusercontent.com/assets/15143489/13593880/9eaced4c-e4d1-11e5-859e-6e69e870f6ed.png)

Aporte de @jhonmarquez92 y mis aportes

@Luis-Fernando-Molina

**Comment by Luis-Fernando-Molina** [comment]
ahora si me gusta!

Vamos a usar la version 2 del internet of things.

Mis observaciones:
1. La gente alredor de la nube no s puede repetir. Pedile a @arnaldos el tiene un montón de personajitos para dar variedad.
2. Ponele mas de un ROL por persona. 
3. Aumenta la variedad de Roles. Fijate en lo que esta haciendo arnaldo para sacar mas situaciones de aplicaciones peer to peer.
4. En el caso de Fermat NO ES UNA NUBE sino una RED. Tenes que representarlo de esa menera. Si la representación de la red son esos nodos y circunsferencias, está bien, pero deberían de alguna menera 

a) indicar que son nodos FERMAT, y (algunos de esos circulos pueden tener el logo solo y otros una parte del catalogo, todo va a tener que ser mas grande para que entre.) 
b) que cada nodo tiene una parte del catalogo de roles.

En general hacer la imagen mas grande, como para full sreen.
1. Les falta el grafico que represente el "INTERNET" actual, que yo lo explicaba con el caso de WHATSAPP, mira el video.

Van bien, me gusta el estilo gráfico. Para ir unificando diganle a @ivonnesantos y @arnaldos que vamos a extender este estilo a los otros gráficos en lo que respecta a colores, formas, etc.

**Comment by Luis-Fernando-Molina** [comment]
Para el caso del internet of things, busca en internet que otras cosas abarca (puertas, sensores, iluminacion, etc,) y dibujalos asi tenemos una mayor variedad. Ponelos alrededor de la nube como en el caso de las personas que hiciste. En este caso SI HAY UNA NUBE y al mostrarlo mas o menos igual, con circulos y conexciones, etc, deberia notarse que en internet of PEOPLE NO HAY Nube, sino NODOS Fermats que ayudan a conectar a la gente entre si.

**Comment by emmysm** [comment]
@Luis-Fernando-Molina 

![infografia recursos-03](https://cloud.githubusercontent.com/assets/15143489/13616668/1a61aea2-e54d-11e5-84d4-4d53ca059911.png)
![infografia recursos-02](https://cloud.githubusercontent.com/assets/15143489/13616669/1b437d1e-e54d-11e5-84cb-8d89da854f67.png)

**Comment by proseuz** [comment]
@Luis-Fernando-Molina 

![infografia internet normal](https://cloud.githubusercontent.com/assets/17308060/13624064/3338ad1a-e57d-11e5-9ddc-8f34b84cb7e6.png)

![infografia recursos jhon](https://cloud.githubusercontent.com/assets/17308060/13624101/8653045a-e57d-11e5-8974-086e6e9b3fda.png)

**Comment by emmysm** [comment]
@jhonmarquez92 en la primera infografía rueda los tres iconos de la nube un poco a la derecha para que queden más centrados. El logo de skype de la izquierda también hace falta centrarlo :smile:

**Comment by Luis-Fernando-Molina** [comment]
@Emmy lo tuyo esta muy bien yo pondría la nueva e un poco más chica y más elementos conectados, qué también les reduciría el tamaño para que queden con sustenten con los otros gráficos. 

Jhon lo tuyo también va bien,  necesita estos ajustes :

*en Internet todos los iconos deben estar en la nube y ninguno en los círculos externos. Además agrega empresas fuera de las de Chat,  face book twitter,  Uber,  Airbnb,  todo lo más conocido poniendo los iconos más chicos para que entren más. 

*en el Internet of people no hay un nido central,  la contrario,  solo nodos descentralizados,  con lo cual algunos tienen el logo fermat y otros parte del catalogo.

**Comment by Luis-Fernando-Molina** [comment]
Emmy tu gráfico no compatibilizar al 100% con el de John probablemente porque loselectrodomesticos no están en círculos.  Asegúrate qué armonice todo porque se muestra todo junto.

**Comment by gustl-arg** [comment]
@jhonmarquez92 en Internet of People, que es lo que creamos como algo totalmente nuevo, gracias a la existencia de una fermat app en cada dispositivo de un end user, que para funcionar necesita la existencia de la fermat network (nodes) y la fermat extended network ( nodes+end user's devices), me hace ruido que FERMAT ocupe el mismo lugar central, en un grafico circular, donde parece que FERMAT "centralizara" lo que antes centralizaba la "nube"..y creo que eso choca con uno de los conceptos pilares de fermat como una "cuasi (extension) sistema operativo" para APPs DISTRIBUIDAS y DECENTRALIZADAS...
quizas se podria mostrar esto, como si fermat fuera una estructura subyacente a las personas que viven y transitan la "superficie" del planeta tierra, tal cual se ve en el video mas viejo que esta en la web ( https://youtu.be/bLiqhTrEWMU)...
expando otra idea que sigue a esta en otro comment..
@Luis-Fernando-Molina  se entiende lo de fermat como underlying mechanism connecting people on a p2p basis ? (an almost invisible, transparent to the end user?)

**Comment by gustl-arg** [comment]
Otra idea mas elaborada seria la de tener tres planos espfericos concentricos:
1) exterior extra planetario de una grilla que conecte a capas mas superiores de Fermat ( las fermats apps para hacer funcioner versiones p2p de uber, airbnb, etc)
![network above earth](https://cloud.githubusercontent.com/assets/13950983/13652225/b740660a-e629-11e5-98ef-3ec2febedf5d.jpg)
![crystalline-matrix](https://cloud.githubusercontent.com/assets/13950983/13652231/c54b82ac-e629-11e5-9d21-9d78ba5b7f5b.jpg)

2) superficie planetaria: donde viven las personas (end user's) y sus dispositivos haciendo transacciones..

3) un interior planetaria: donde fluya la metadata (info) y el valor (cryptonetnorks) y todo lo que sea de mas bajo nivel en la fermat app

![flux inner earth](https://cloud.githubusercontent.com/assets/13950983/13652236/cb8ebc42-e629-11e5-9881-2d5d777e9404.gif)
