### ISSUE TITLE
Personajes para Infografia para The Sharing Economy To Peer to Peer Economy

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#663]
Estos personajes seran incluidos en la infografia que se esta discutiendo en el caso #653

**Comment by JefersonBorgesS** [comment]
![infografia2 - 1-02](https://cloud.githubusercontent.com/assets/17457984/13580409/5d2b7850-e474-11e5-8420-58d211f376d8.jpg)

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina aquí estamos posteando los personajes

**Comment by Luis-Fernando-Molina** [comment]
OK ya tenes el total de parejas que vamos a usar?

**Comment by arnaldos** [comment]
ya estoy por postear otros caracteres mas

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina Aquí posteo todos los characters que trabajamos junto a @jayborges 

![infografia_character](https://cloud.githubusercontent.com/assets/13594347/13584562/6080f0a6-e489-11e5-91c3-9a031b9e794d.jpg)

**Comment by arnaldos** [comment]
@jayborges coloque todos los personajes, tanto los tuyos como los mios en una sola pagina para que se aprecien mejor.

**Comment by arnaldos** [comment]
esta si es la serie de 7 feminas y 7 masculinos 

![infografia_character](https://cloud.githubusercontent.com/assets/13594347/13584871/9fe12530-e48a-11e5-8f1a-6348f6e1bb0d.jpg)
