### ISSUE TITLE
SUPPER ISSUE New Landing Page Fermat.Org (General Structure)

### ISSUE THREAD

**Issue by robertggovias** [bitDubai/fermat-graphic-design#664]
First Goal of the landing page must be to give to the interested people, reasons to desire join Fermat, as a big contributor //not necessary mentioned), as a developer, as advertiser, as designer, etc.... to obtain revenue in the moment, and then for every time someone need his micro component and changed for Fermat Tokens

Following the meeting to define the new visual concept for Fermat from march 4th, we define 3 core concepts
1. P2p b2b (Peer to Peer Business to Business)
2. Shifting from Competition to Collaboration
3. Internet People
Now we need to transform the actual landing page to match the new conceptual understanding of Fermat
[Link of the video of the new visual concept for Fermat ](https://www.youtube.com/watch?v=bTUcnUg6tmQ)

The first Structure
**Menu**
1. Technical details (All platforms explained)
2. Project Progress  (The progress of every platform and Component, and who is in charge)
3. Get Involve (Every step to get in the project and finally the form to make a solicitud)
4. About us (Mission, Objectives, Plan, Strategies, History (what was made until today), All members of the community)

**Hero Shoot** (The Web Page first Attractive Image)
1. Unique Selling Proposition
2. Infographics (Dna Connection between cellphone making a p2p b2b, where every Adn links (adn covalent bonds), represent one of us, being revenue, with a micropayment, trough the fermat platforms)
3. Benefits

**post**
every news of the project
**Testimonial**
Happy members of the team
**Links**
1. P2p b2b (Peer to Peer Business to Business)
2. Shifting from Competition to Collaboration
3. Internet People

**Comment by gustl-arg** [comment]
@robertggovias your first issue is a big one! Let's ask @Luis-fernando-molina for suggestions..

**Comment by gustl-arg** [comment]
@robertggovias I agree that the main goal is to attract people to contribute to the project, but to "build the whole city", so to share the vision and the business proposition (added value)

**Comment by robertggovias** [comment]
For the Hero Shoot (Web page big image), it's necessary a friendly, fast and interactive interface visualization. "google docs presentation" have been chosen to gain effort and time. Try  it for yourself, you can move every there, don't be shy, thanks to the review history, we can get back.
[just clic here](https://docs.google.com/presentation/d/11JW8RsanQSf0p0jNxwBJDgJv3zhtpRiARFbxLQ8Kh8A/edit#slide=id.g10c679535c_2_2)
How to use it.
Take time to understand the 3 levels:
1. Communication objectives
2. Graphics Elements
3. Layout

Then we can go to Photoshop, Illustrator, Corel, Dream Weaver, Inkskape, 3ds Max, Maya, Blender, Wordpress.

**Comment by gustl-arg** [comment]
The 3 core concepts introduced by @Luis-Fernando-Molina are going to be work out in the teams: publishing+2d design+3d design. So, I propose that @arnaldos and @jonathanborges3d participate in this superissue and I also joined them in a private slack chat with @robertggovias and me.

**Comment by gustl-arg** [comment]
This issue is closed #664 and replace by https://github.com/Fermat-ORG/publishing-team/issues/1 at the publishing-team repo.

**Comment by arnaldos** [comment]
can I close this ?

**Comment by robertggovias** [comment]
Yes, my friend, thanks for ask!

**Comment by arnaldos** [comment]
Robert, thanks for close this
