### ISSUE TITLE
SUPERISSUE: Segundo video infográfico de Fermat

### ISSUE THREAD

**Issue by jonathanborges3d** [bitDubai/fermat-graphic-design#667]
Aquí haremos la discusión del guión del segundo video de Fermat.

@Luis-Fernando-Molina Tomando en consideración la analogía que hiciste en una reunión con el equipo de diseño gráfico 2D (Fermat como la ciudad en construcción), podríamos dejar como mensaje principal el concepto de evolución desde COMPETENCIA------- a ----------CONTRIBUCIÓN con un PLAN DE NEGOCIOS. 

La propuesta sería manejar las diferencias entre ambos extremos en el contexto de la construcción de una ciudad. Los ejemplos que se dieron en la reunión acerca de las líneas de metro y servicios básicos nos pueden servir de punto de partida y la existencia de un MASTER PLAN para la construcción del sistema Fermat como punto de llegada e invitación a entrar al proyecto, colaborando y recibiendo el incentivo de los micropagos.

@AnaPietrosanti @Yinellydesign @victoralfonzohd Vamos a hacer aportes en el tema y así le damos forma a la idea si nos quedamos con ésta o si quieren propongan otra cosa así tendremos mayores opciones.

**Comment by Luis-Fernando-Molina** [comment]
Por favor poné los links a los videos que grabé con los diseñadores 2d asi todos los ven.

No va por el lado del a ciudad. Los 3 conceptos a explicar son los presentados en estos 3 casos:

https://github.com/Fermat-ORG/fermat-graphic-design/issues/662#issuecomment-194126176
https://github.com/Fermat-ORG/fermat-graphic-design/issues/661#issuecomment-193903947
https://github.com/Fermat-ORG/fermat-graphic-design/issues/653#issuecomment-193530259

y extensamente explicados en los videos que te mencione.

Escriban un script sobre esos 3 conceptos y lo vemos.

**Comment by jonathanborges3d** [comment]
Aunque ya los hemos visto, dejo por acá los vínculos a los vídeos dónde se explican los tres conceptos por si hay dudas los encuentran rápido.

https://www.youtube.com/watch?v=JYBsO-p7gS4
https://www.youtube.com/watch?v=bTUcnUg6tmQ
https://www.youtube.com/watch?v=VEkD6GR0ES4

También les dejo ésta infografía que los resume.
![](https://cloud.githubusercontent.com/assets/13594347/13721792/ec044740-e803-11e5-8e84-1245bca5be88.jpg)
