### ISSUE TITLE
Sugerencia de trabajo 

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#67]
Viendo la variedad de issues que ha creado @m471c4 coincido perfectamente con todos, solo sugiero reorganizarlos en un super issues, ya que siento que están un por dispersos.

Podríamos organizar de la siguiente manera:

Fermat (como marca)

1- Logo Fermat

a-Realizar refrescamiento del Logo
b-Definir Paleta de colores
c- Definir Aplicaciones permitidas y las no permitidas:
*Logo en positivo *Fondo de color
*Logo en negativo *Intercambiar los colores del logo
*Logo en outline *Sobreponer letra arabe por encima de bitDubai

d- Fuentes aplicadas
e- Mínima reducción que soporta el logo
f- Área de reserva

2- Reestructurar o refrescar el logo de cada función que tiene Fermat:

a-Fermat DMP
- Plantear bocetos de isologo (sugerencia de Dayana)
- Definir y organizar Fuentes usadas en isologo (sugerencia de Dayana)

b-Fermat P2P
- Plantear bocetos de isologo (sugerencia de Dayana)
- Definir y organizar Fuentes usadas en isologo (sugerencia de Dayana)

c-Fermat PIP
- Plantear bocetos de isologo (sugerencia de Dayana)
- Definir y organizar Fuentes usadas en isologo (sugerencia de Dayana)

3- Iniciar propuestas de mejoras de la presentación de Prezzi 

a- Sustituir cada un de los logos nuevos ya aprobados en todos los sitios aplicados
b- Plantear nuevas propuestas de diagramación de la presentación.

y de esta manera creo que podríamos ir avanzando en el diseño y asignar las tareas

**Comment by Miguelcldn** [comment]
Tip: Si en un issue quieren presentar una lista de tareas que irán realizando paso a paso, pueden hacer una check-list:
- [ ] Tarea 1
- [ ] Tarea 2
- [ ] Tarea 3

Para esto solo deben escribir de la siguiente manera:
"- [ ] Tarea 1"

Nótese que entre los corchetes hay un espacio vacío, si ese espacio se llena con una 'x' entonces la tarea estara checkeada. Al dar click en un cuadro esta se marcará y se guardará.

**Comment by Luis-Fernando-Molina** [comment]
buenísimo! @bitDubai/malo-team @bitDubai/thunder-coin-team @bitDubai/george-team buen tip de Miguel!

**Comment by Luis-Fernando-Molina** [comment]
@arnaldos Acordate que existe también el concepto de Milestone que es donde agrupas los issues de acuerdo al plan en función del tiempo en que los vas a resolver.

**Comment by arnaldos** [comment]
ok perfecto, lo voy a tomar en cuenta!!
