### ISSUE TITLE
Gif para el gráfico Sharing Economy

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#670]
Aqui compartiremos los gif de cada economía del grafico, el cual se esta discutiendo en el caso #653

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina comparto los gif

###### Gif The Peer to Peer Economy

## ![imagen1](https://cloud.githubusercontent.com/assets/13594347/13623684/9d983ade-e57a-11e5-9bb0-e375e78ca8d5.gif)

## ![imagen2](https://cloud.githubusercontent.com/assets/13594347/13623685/9d9cbf46-e57a-11e5-82ad-624385fb9dfd.gif)

## ![imagen3](https://cloud.githubusercontent.com/assets/13594347/13623686/9da0f23c-e57a-11e5-80c6-fabfe21ca75f.gif)

## ![imagen4](https://cloud.githubusercontent.com/assets/13594347/13623687/9db8beee-e57a-11e5-97f0-21e6ca6c7fb6.gif)

## ![imagen5](https://cloud.githubusercontent.com/assets/13594347/13623688/9dc18222-e57a-11e5-9ad7-3c1635095396.gif)

## ![imagen6](https://cloud.githubusercontent.com/assets/13594347/13623689/9dc47360-e57a-11e5-83bc-a6f6bf020677.gif)

## ![imagen7](https://cloud.githubusercontent.com/assets/13594347/13623690/9dd40b18-e57a-11e5-8110-c868a20f9827.gif)

![imagen8](https://cloud.githubusercontent.com/assets/13594347/13623691/9dd88cb0-e57a-11e5-9fef-f47681f68f08.gif)

**Comment by m471c4** [comment]
@Luis-Fernando-Molina @arnaldos acá los gifs:

![1](https://cloud.githubusercontent.com/assets/13468350/13625441/0123ceb0-e58a-11e5-9427-65d14a775f28.gif)

![2](https://cloud.githubusercontent.com/assets/13468350/13625442/01251766-e58a-11e5-8f00-cc88401185fc.gif)

![3](https://cloud.githubusercontent.com/assets/13468350/13625548/ff067168-e58a-11e5-9739-1bb7146799e4.gif)

![4](https://cloud.githubusercontent.com/assets/13468350/13625590/75d70c80-e58b-11e5-8ff8-437a5baba4e3.gif)

![5](https://cloud.githubusercontent.com/assets/13468350/13625633/f16034c6-e58b-11e5-89a4-8074c057dbb1.gif)

![6](https://cloud.githubusercontent.com/assets/13468350/13625688/5ba0038e-e58c-11e5-9657-dc0544de9ba8.gif)

![7](https://cloud.githubusercontent.com/assets/13468350/13625745/0a16c614-e58d-11e5-9931-964a108e455d.gif)

![8](https://cloud.githubusercontent.com/assets/13468350/13625747/0e2a241c-e58d-11e5-83a5-c9f19cdc1562.gif)
