### ISSUE TITLE
Mejorar el diseño actual de la Broker Identity

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#672]
1. Generar el diseño de las pantallas de creación y edición (Agregando el boton de Crear o Editar en las respectivas pantallas)
2. En la pantalla de edición, representar nuevamente el botón de visible/Not Visible para que se adapte mejor al resto del diseño.
3. Para la Broker Identity mejorar el fondo a establecer y el icono de No Identities
###### Listado de Identidades

![listado broker](https://cloud.githubusercontent.com/assets/13594347/13639632/ce63e762-e5e3-11e5-8870-26ad152d4f66.png)

**Comment by arnaldos** [comment]
@isahq23 este caso es todo tuyo

**Comment by isahq23** [comment]
Aquí dejo la propuesta para esta sub app
@arnaldos 
![screen_broker_identity_issues672-muestra-07](https://cloud.githubusercontent.com/assets/15214774/13651055/c6898950-e617-11e5-84bd-610a7d71b1cb.png)

**Comment by vlzangel** [comment]
@isahq23 @arnaldos  hola, en la pantalla del listado falta el botón de ayuda, con el que se muestra dialogo de ayuda y en la pantalla de edición falta el botón de UPDATE.

**Comment by vlzangel** [comment]
@isahq23 @arnaldos  y en la pantalla de crear y editar, cuando esta sin teclado, podrían hacer un diseño de como quedaría con un tamaño fijo, es decir que no abarque toda la pantalla.

**Comment by nelsonalfo** [comment]
que tal si colocan los botones de la cámara y la galería en el borde inferior derecho y lo de **Visible/NOT Visible** quitarlo y colocar algo un poco mas discreto como un switch que sea similar el indicador Visible que proponen en la ultima imagen, donde esta la lista de identidades. Lo pueden colocar en el borde superior izquierdo o el borde inferior izquierdo.

Por lo demás me gusta, tambien hay que tomar la sugerencia de @vlzangel de que exista un boton **UPDATE** para actualizar la data

**Comment by nelsonalfo** [comment]
Puede tomar como ejemplo en la pagina de ajustes de Whatsapp la opcion perfilque muestra le foto que se puede editar y el nombre

**Comment by isahq23** [comment]
@nelsonalfo la parte de visible/not visible es realmente un señuelo, como para apartar el espacio. Hay alguien más encargado del diseño de ese detalle.

**Comment by arnaldos** [comment]
@isahq23 muy buen trabajo :smile: 

@vlzangel @nelsonalfo el boton de **UPDATE** nos llevara a una pantalla para actualizar o es para sincronizar que acción hace ? 

Angel, cuando comentas esto: **y en la pantalla de crear y editar, cuando esta sin teclado, podrían hacer un diseño de como quedaría con un tamaño fijo, es decir que no abarque toda la pantalla.** a que te refieres? a la foto ?

**Comment by nelsonalfo** [comment]
aaah ok @isahq23 gracias por la aclaratoria!

**Comment by vlzangel** [comment]
Hola @arnaldos el boton de UPDATE es para que los cambios se guarden, es por motivos de usabilidad para que el usuario pueda persistir los cambios solo si el lo desea, como esta en este momento se guardan los datos al salir de la pantalla de edición, quiera el usuario o no, lo que se quiere es que el usuario pueda decidir cuando se guardan los cambios y cuando no.

Lo otro, si me refiero a la foto, un diseño donde la foto no ocupe todo el alto de la pantalla, sino que quede mas o menos del tamaño que tiene con el teclado desplegado, para evitar que esta se deforme como lo hace ahora.

**Comment by isahq23** [comment]
@arnaldos @vlzangel 
Cambios

![screen_broker_identity_issues672-muestra2-07](https://cloud.githubusercontent.com/assets/15214774/13685511/02f94daa-e6e3-11e5-91a8-23562e1df136.png)

**Comment by vlzangel** [comment]
Hola isahq23, el diseño en general me parece muy bien y tiene todo lo que se necesita.

Falta que @lnacosta y @nelsonalfo lo revisen e indiquen sus comentarios.

**Comment by nelsonalfo** [comment]
Dos ultimas sugerencias: 
1. el campo de texto que esta debajo de la imagen no sobre ella
2. El botón de crear tenga las mismas dimensiones que el del update

Por lo demás me parece que lo podemos dejar asi :smiley:

**Comment by arnaldos** [comment]
@isahq23 Muy bueno mejoro bastante fíjate dos cosas:
- El boton de **Update** se ve muy claro no se si en la pantalla de android se lea el texto, aconsejaria oscurecerlo un poco lo necesario como para que no se funda con el blanco del texto.
- El boton de visible/not visible su ubicacion estas segura es la mejor ubicación ? podemos probar mas al centro del espacio cuadrado que se forma entre el boton Update y el campo de texto.

@nelsonalfo el campo de texto, no me disgusta como lo plantea isa. Visualmente no afecta a la lectura porque tiene un tono oscuro que le permite resaltar el texto blanco. Tiene buena lectura, lo único que haria es oscurecerla un pequeño porcentaje, por si el usuario tiene una imagen muy colorida o muchos elementos, no afecte la lectura, me agrada como se ve. 

No se que opinen ustedes ?

**Comment by leonacostaok** [comment]
Me parece bien el campo de texto encima de la imagen, con las correcciones que propone arnaldo me parece que quedaría perfecto.

**Comment by nelsonalfo** [comment]
dale @arnaldos hagamos como sugieres :+1:

**Comment by vlzangel** [comment]
Saludos @arnaldos @isahq23, cuando tengan los elementos me los pasan para aplicarlos lo antes posible, gracias.

**Comment by arnaldos** [comment]
@isahq23 aplica el boton de visible  /  not visible que esta trabajando @jayborges en el caso #674 una ves realice los ajustes.

mientras me generando los recursos y luego se los pasas a @vlzangel

**Comment by leonacostaok** [comment]
me gusta más el que se presento acá eh, pero si querés vemos una versión como para contrastar

**Comment by isahq23** [comment]
Work in on it!

**Comment by isahq23** [comment]
Arreglo de detalles
Aún espero por el archivo del visible/ not visible de @jayborges 
- oscurecí un 5% la sección del nombre
- oscurecí el tono del botón "update"
- bajé un poco el switch

![screen_broker_identity_issues672-muestra3-08](https://cloud.githubusercontent.com/assets/15214774/13712957/a45fe694-e798-11e5-8e7f-840501fb64aa.png)

**Comment by isahq23** [comment]
Hi everyone!
Here is the last view for Broker Identity with the switches made by @jayborges :)

My question here, @arnaldos are you sure about the switches´s place?

![screen_broker_identity_issues672-muestra_4-14](https://cloud.githubusercontent.com/assets/15214774/13855993/3c9e4db4-ec45-11e5-9a18-9ad51df3f5d9.png)

**Comment by arnaldos** [comment]
@isahq23 Place it in the place that you think is right and we discussed it. show me

**Comment by isahq23** [comment]
@arnaldos I think version 2 or 3 would be best. I know there´s a lot of space, but the functionality of the switch related with its position works best when it´s closer to other actions.

![screen_broker_identity_issues672-muestra_5-15](https://cloud.githubusercontent.com/assets/15214774/13887489/212d6690-ed0e-11e5-8a58-65aafe9f77ce.png)

**Comment by arnaldos** [comment]
@isahq23 abajo queda mejor sube los resources y le dices a @vlzangel donde ubicarlos para que los implemente :+1:

**Comment by isahq23** [comment]
@arnaldos yes sir!

**Comment by arnaldos** [comment]
@vlzangel este caso lo podemos cerrar ? o nos falta algo mas ??

**Comment by vlzangel** [comment]
Close it, is ready

**Comment by arnaldos** [comment]
good !!! :+1:
