### ISSUE TITLE
Mejorar el botón de visible/Not Visible 

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#674]
El boton sera implementado en el Broker Identity y Customer Identity.

El botón debe ser como un switch
Tal como se muestra en los casos #673 y #672

**Comment by JefersonBorgesS** [comment]
Aqui estan 2 propuestas del botón de Visible / Not visible

![switches visible notvisible1-01-01](https://cloud.githubusercontent.com/assets/17457984/13650252/ed3f5b0a-e613-11e5-88d2-29f1f671c397.jpg)

![switches visible notvisible2-02-02](https://cloud.githubusercontent.com/assets/17457984/13650257/f2fb7880-e613-11e5-9e40-c91123e3e9d0.jpg)

**Comment by arnaldos** [comment]
@jayborges probemos otra versión plz  el del switch revisa la perspectiva del texto referente al switch. el otro boton no lo entiendo muy bien

**Comment by JefersonBorgesS** [comment]
![switches visible notvisible1-01-01-01](https://cloud.githubusercontent.com/assets/17457984/13681304/c873938e-e6ce-11e5-834e-b22623045006.jpg)

![switches visible notvisible2-02-02-03](https://cloud.githubusercontent.com/assets/17457984/13681310/d0928b38-e6ce-11e5-87a5-d48863f05f78.jpg)

**Comment by arnaldos** [comment]
@jayborges me gusta esta ultima propuesta, solo seria las siguientes observaciones:
- El botón de ancho esta bien, solo reduce un poco el alto.
- Los textos prueba una tipografía mas light.
- Deberíamos probar algo que refuerce que esta visible o not visible, tal ves jugando con los colores del texto ejemplo: visible en verde y not visible en rojo. o algún elemento que simule una especie de led verde o rojo para el caso de que fusión use el usuario

**Comment by JefersonBorgesS** [comment]
![switches visible notvisible312-05](https://cloud.githubusercontent.com/assets/17457984/13712392/8493ad1c-e795-11e5-8fa8-376f4a177aae.jpg)

![switches visible notvisible2-02-02-03-04-04](https://cloud.githubusercontent.com/assets/17457984/13712393/84bc104a-e795-11e5-83a2-c2d1f9553bf4.jpg)

**Comment by arnaldos** [comment]
@jayborges  genera el cambio que te solicite y montalo en el fondo para probar como se ve y decidimos

**Comment by JefersonBorgesS** [comment]
@arnaldos aqui los cambios de lo anterior solicitado. ![switches visible notvisible564jpg-06](https://cloud.githubusercontent.com/assets/17457984/13715103/f579b396-e7a4-11e5-91fa-e7398ba44538.jpg)

**Comment by leonacostaok** [comment]
Le podrías poner un tono más oscuro al botón cuando se hace no visible?

**Comment by arnaldos** [comment]
@jayborges también se le pudiese agregar encima del boton un led circular similar al que uso @isahq23 colocando el texto en un tono y lo que haría la diferencia seria el color del led

**Comment by JefersonBorgesS** [comment]
Aca unos cambios @arnaldos 

![switches visible notvisible-2-04](https://cloud.githubusercontent.com/assets/17457984/13789337/a6a890d4-eab5-11e5-937e-f0284b4ec5f1.jpg)

![switches visible notvisible-2-06](https://cloud.githubusercontent.com/assets/17457984/13789339/a6b27536-eab5-11e5-89c2-73f5e20eb380.jpg)

![switches visible notvisible-2-03](https://cloud.githubusercontent.com/assets/17457984/13789340/a6b3f262-eab5-11e5-8f65-06a5ce22f9db.jpg)

![switches visible notvisible-2-05](https://cloud.githubusercontent.com/assets/17457984/13789338/a6abe360-eab5-11e5-95c0-9f372ea5eaa3.jpg)

**Comment by arnaldos** [comment]
@jayborges algo así me refería, este que te muestro esta mal montado es solo para el ejemplo.

![boton](https://cloud.githubusercontent.com/assets/13594347/13790876/a31b18b8-eabc-11e5-89da-bd182cce6126.gif)

**Comment by JefersonBorgesS** [comment]
@arnaldos  ok ya listo monto los ajustes

**Comment by JefersonBorgesS** [comment]
@arnaldos 

![switches visible notvisible-06](https://cloud.githubusercontent.com/assets/17457984/13791247/5f1dff66-eabe-11e5-953e-0ea6b1bd42a0.jpg)

![switches visible notvisible-07](https://cloud.githubusercontent.com/assets/17457984/13791248/5f1fb7ca-eabe-11e5-8351-605cea433072.jpg)

![switches visible notvisible-08](https://cloud.githubusercontent.com/assets/17457984/13791246/5f1cadbe-eabe-11e5-8394-71c2bf278949.jpg)

**Comment by arnaldos** [comment]
@jayborges  pasale este boton la version 2 de la ultima serie a  @isahq23 para que lo aplique
