### ISSUE TITLE
#664 Landing Page Fermat.org - Visual Structure

### ISSUE THREAD

**Issue by robertggovias** [bitDubai/fermat-graphic-design#675]
Reference to Super Issue #664 Landing Page Fermat (General Structure)

The 3 core concepts introduced by @Luis-Fernando-Molina are going to be work out in the teams: publishing+2d design+3d design. So, I propose that @arnaldos and @jonathanborges3d participate in this superissue and I also joined them in a private slack chat with @robertggovias and @gustl-arg.

Through this issue will define all aspects of the visual goals of the landing page, and decide the paths to get it, defining using visual communication web tools (texts, images, buttons, 

Web page big image, it's necessary a friendly, fast and interactive interface visualization. "google docs presentation" have been chosen to gain effort and time. Try it for yourself, you can move every there, don't be shy, thanks to the review history, we can get back.
just clic here
How to use it.
Take time to understand the 3 levels:
1. Communication objectives
2. Graphics Elements
3. Layout
[Click here to join the creative process](https://docs.google.com/presentation/d/11JW8RsanQSf0p0jNxwBJDgJv3zhtpRiARFbxLQ8Kh8A/edit#slide=id.g10c679535c_2_2)

Then we can go to Photoshop, Illustrator, Corel, Dream Weaver, Inkskape, 3ds Max, Maya, Blender, Wordpress.

**Comment by Luis-Fernando-Molina** [comment]
por favor mira esto que es lo ultimo sobre este tema:

**Comment by Luis-Fernando-Molina** [comment]
https://youtu.be/_fUvphI2E6g

**Comment by Luis-Fernando-Molina** [comment]
Anda pensando como vamos a poner con esa base que estará haciendo @emmysm mas explicaciones sobre los distintos conceptos.

**Comment by gustl-arg** [comment]
este issue se continua en https://github.com/Fermat-ORG/publishing-team/issues/2
