### ISSUE TITLE
Generar una Maqueta de la web con los Gráfico Infogaficos

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#676]
Listado de Graficos
- Sharing Economy turns into p2p Economy
- Internet evolves into Internet of Things and People
- Competition to Masive Collaboration

**Comment by emmysm** [comment]
![fermat web home2-03](https://cloud.githubusercontent.com/assets/15143489/13677453/409bd2ee-e6bc-11e5-862f-96e3df0d51e0.png)
![fermat web home2-01](https://cloud.githubusercontent.com/assets/15143489/13677454/40c0bc26-e6bc-11e5-9d82-da96a0c5ea10.png)

Nuestros aportes @arnaldos @m471c4 @ivonnesantos @jhonmarquez92 

@Luis-Fernando-Molina

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina Te comparto las mejoras del grafico.

## Version 1 color azul oscuro

## ![fermat-web-home-v1](https://cloud.githubusercontent.com/assets/13594347/13690886/54b6d810-e706-11e5-9045-0017075815b2.jpg)

## Version 2 color azul claro

![fermat-web-home-v2](https://cloud.githubusercontent.com/assets/13594347/13690887/54b973cc-e706-11e5-9cf1-7091bb46ef00.jpg)

**Comment by Luis-Fernando-Molina** [comment]
muy bien @arnaldos !

mis observaciones:
- Toda la imagen debe ser mas ancha (el canvas) en mi pantalla de mi laptop sobra espacio en los dos cosatados.
- El gris del fondo de cada escena ponelo levemente azulado, asi las pelotitas azules se interpretan como escenas vistas desde lejos. Lo mismo para el fondo de los logos del grafico de abajo.

1-En la Sharing Economy y P2P econnomy.

a) Las burbujas con las escenas estan muy pequeñas y no se ven los logos ni en las mas grandes. Busca la forma de agrandarlas.
b) En la escena donde hay unos corazones en la parte P2P en vez de una moneda que le de un trago .
c) En la parte de la sharing Economy, usa en algunas escenas el segundo frame donde ya se entrego la moneda y un pedacito le quedo al intermediario. Usalo en al menos una de las burbujas bien grandes y visibles.
d) el titulo debe ser "The Sharing Economy turns into the P2P Economy" 

2- En el Internet e Internet of Things and People

a) La nube en el internet ponela fuera del circulo como en los otros casos
b) Internet of Things tiene un TYPO
c) en Internet of People
- Volviste a dejar el logo de Fermat al Centro: NO DEBE HABER NINGUN LOGO AL CENTRO.
- los nodos a los cuales les pusiste un iconito lo que deben tener en realidad es una parte del catalogo distribuido de roles, osea UN ICONITO MAS ALGUNAS CARITAS que representan las personas asociadas a ese rol. Mejor aun si las caritas son las que en las otras burbujas tienen el mismo icono. Debieran haber al menos 3 caritas por cada rol en esos nodos.
  d) El titulo debe decir "The Internet Evolves into the Internet of Things and People"

3-En el Competition to Collaboration hace estos dos ajustes:

a) en la escala poner los textos todos del mismo tamaño
b) en el eje x colocar "Competition"  "Collaboration" "Massive Collaboration"
c) el grafico quedó muy alto, no entra en una pantalla.
d) la integracion con el grafico de arriba no es lo que acordamos
e) a cada sistema le faltan lineas auxiliares inclinadas.
f) la escala en y debe ser "Close Source", "Open Source", "Ecosystem Token Incentive", "Component Ownership Incentive" . En todos los casos pone una palabra por renglon.
g) para las palabras en los ejes usa el tamaño de letra mas chico por favor.
h) El punto azul entre bitcoin y ethereum esta muy grande
i) Pone las lineas de los ejes x y del mismo azul, y fijate si el ancho ese que tiene es realmente el mejor. Quizas debieran ser del ancho de las lineas del borde de las burbujas.
j) El titulo de esta parte ponele "From Competition to Massive Collaboration" ahora esta mal escrito y le falta el FROM

POR FAVOR ASEGURATE DE QUE CADA PUNTO ESTE RESUELTO ANTES DE AVISARME QUE LO REVISE.

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina últimos ajuste, lo del canvas ya eso lo tendría que ajustar @robertggovias cuando monte la web, esta maquetado para que cubra el área total de la pantalla. 

NOTA: aumente los tamaños de las burbujas del sharing economy pero se siguen perdiendo la lectura del logo, recomiendo quitar el circulo del logo para poder darle mas tamaño. y acercar a las personas.

![fermat-web-home-v3](https://cloud.githubusercontent.com/assets/13594347/13715521/735b3b34-e7a7-11e5-96ed-de95b303d62b.jpg)

**Comment by arnaldos** [comment]
![fermat-web-home-v5](https://cloud.githubusercontent.com/assets/13594347/13715834/8ae3d354-e7a9-11e5-93d9-f7b77ea2ce38.jpg)

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina adjunto los últimos ajustes realizados, trabaje el ancho de pantalla para una resolución de 1680x1050.

![fermat-web-home-v1680](https://cloud.githubusercontent.com/assets/13594347/13721766/033ad894-e803-11e5-8a56-e650efc7736e.jpg)

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina esta si es la ultima imagen ajustada, trabajada a una resolución de 1680x1050.
![fermat-web-home-v1680](https://cloud.githubusercontent.com/assets/13594347/13721792/ec044740-e803-11e5-8e84-1245bca5be88.jpg)

**Comment by Luis-Fernando-Molina** [comment]
A) en SHARING ECONOMY:

1-Reemplaza mercado libre por eBay
2-Reemplaza Ashley Madison por Tinder
3-Reempaza Shutter Stock por Uber, cambiando el icono del producto obviamente.
4-La moneda y el producto bajalos mas hasta que queden bien cerca de las manos y tapando un poquito el circulo deonde esta el logo.

B) From Competition to Massive Collaboration:

1-pone en el mismo renglon "Component Ownership" y abajo "Incentive"
2-pone en el mismo renglon "Ecosystem Token" y abajo "Incentive"

si tenes que achicar un poco la letra de esos labels para que quede bien, hacelo.

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina los ajustes del grafico

![fermat-web-home-def](https://cloud.githubusercontent.com/assets/13594347/13724692/b91ce330-e85f-11e5-8f75-2e358f2b9598.jpg)

**Comment by Luis-Fernando-Molina** [comment]
El tamaño de la letra debe ser igual en el ultimo grafico para los dos ejes.

**Comment by Luis-Fernando-Molina** [comment]
El fondo debe ser transparente y todo debe ser un PNG

**Comment by Luis-Fernando-Molina** [comment]
Las palabras en rojo, tienen todas el mismo tamaño de letra?

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina comparto los ajustes la imangen esta en PNG sin fondo.

![fermat-web-home-def](https://cloud.githubusercontent.com/assets/13594347/13729676/ed9826bc-e90c-11e5-9f88-2b691c064687.jpg)

**Comment by Luis-Fernando-Molina** [comment]
Me estas cargando? es un JPG

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina disculpa, el programa me cambio los valores y no me di cuenta. 
Te envió la imagen correcta.

![fermat-web-home-def-transparente](https://cloud.githubusercontent.com/assets/13594347/13732335/bff1c3f8-e952-11e5-92fc-2ba357e7dee4.png)

**Comment by Luis-Fernando-Molina** [comment]
Ok, solo le falta una cosa mas:

-En el internet of People, el fondo de la burbujita donde esta cada persona en vez de gris ponele el mismo celeste que la burbuja donde está la gente de pie.

**Comment by Luis-Fernando-Molina** [comment]
Luego por favor cortá el gráfico en tres partes para poder usarlo por separado (deja la versión entera tambien para @robertggovias .

**Comment by arnaldos** [comment]
ok perfecto

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina 

#### Gráfico completo

---

![fermat-web-home-def4](https://cloud.githubusercontent.com/assets/13594347/13757540/3ce9cc76-e9f7-11e5-8a92-8f1badd20fa0.png)

#### Gráficos por separados

---

###### Gráfico 1

![fermat-web-home-def1](https://cloud.githubusercontent.com/assets/13594347/13757646/ad749c1e-e9f7-11e5-880d-46cb9174079a.png)

###### Gráfico 2

![fermat-web-home-def2](https://cloud.githubusercontent.com/assets/13594347/13757653/b7fa5f48-e9f7-11e5-8316-4ea96be419cc.png)

###### Gráfico 3

![fermat-web-home-def3](https://cloud.githubusercontent.com/assets/13594347/13757659/c2258524-e9f7-11e5-9588-fc6146c31aae.png)

**Comment by arnaldos** [comment]
ya subo el material al media kit

**Comment by Luis-Fernando-Molina** [comment]
@robertggovias por favor usa el ultimo grafico de Arnaldo.

Ya está listo.

:+1:

**Comment by arnaldos** [comment]
perfecto cierro el caso los fuentes estan en esta carpeta https://github.com/Fermat-ORG/media-kit/tree/master/Infographies

**Comment by robertggovias** [comment]
Thanks for all. I will notify when the home page has been developed.
