### ISSUE TITLE
"Representación Artística del ecosistema de fermat apps Nº 1"

### ISSUE THREAD

**Issue by DexybelVillanueva** [bitDubai/fermat-graphic-design#677]
@Luis-Fernando-Molina  @jonathanborges3d  La propuesta es una escena incluyendo el mundo en rompecabezas,en el cual cada pieza tendría el logo de la app de fermat , y dentro del rompecabezas estaría una esfera, ésta tendría el logo de fermat visible por la parte que estaría sin piezas.

1)![captura de pantalla 2016-03-10 17 50 44](https://cloud.githubusercontent.com/assets/16962860/13686620/d32921e4-e6e8-11e5-8aa5-df4efe6a56a1.png)

2)
![captura de pantalla 2016-03-10 17 51 13](https://cloud.githubusercontent.com/assets/16962860/13686649/08d31304-e6e9-11e5-9e38-8fd7880f6748.png)

3)![captura de pantalla 2016-03-10 17 51 48](https://cloud.githubusercontent.com/assets/16962860/13686622/d33950f0-e6e8-11e5-8045-93dbf2f55307.png)

**Comment by Luis-Fernando-Molina** [comment]
va bien.

No estoy seguro de que debajo del rompecabezas deba estar otra esfera y el logo de Fermat, porque justamente lo que representa el rompecabezas en Fermat.

Otra cosa que noto es como las piezas se comprimen en los polos, por eso seguramente en wikipedia eligieron que la parte faltante sea la del polo norte y la posición de la camara esconde el polo sur. Me parece que vamos a tener que hacer lo mismo.

Fijate de conseguir los iconos de las APPs qu eya existen. 

Posiblemente el tamaño delas piezas esté demasiado pequeñas porque hay demasiadas piezas, fijate de ponerlo en un intermedio entre wikipedia y esto.

**Comment by jonathanborges3d** [comment]
Existe una figura geométrica que puede evitarnos el problema de la compresión en los polos de la esfera. Se trata de una figura similar a un balón de Fútbol común, con hexágonos y pentágonos, no tiene polos definidos sino que está distribuido de forma equitativa por toda la superficie. Haciéndole las correspondientes formas para que encajen unas con otras podría funcionar. Es solo una propuesta.

![1](https://cloud.githubusercontent.com/assets/13649739/13692621/6e4e90ba-e715-11e5-81be-c057be62f2df.jpg)

También puede asociarse la idea de que cada pieza se conecta de alguna manera con no menos de 6 a la vez.

Pudiese dar algo de espacio adicional para colocar los iconos con mayor comodidad y a su vez evitaría el problema de hacer algo parecido a Wikipedia. Tu nos dices.

**Comment by Luis-Fernando-Molina** [comment]
Interesante... probemos esa tambien... conseguite los iconos , veo que ahí entrarían mejor que en el caso anterior.

**Comment by DexybelVillanueva** [comment]
Vista previa de los iconos en las piezas.

1)![captura de pantalla 2016-03-11 20 42 37](https://cloud.githubusercontent.com/assets/16962860/13719569/d437cba8-e7c9-11e5-8062-b37a0fca92cc.png)

2)![captura de pantalla 2016-03-11 20 38 52](https://cloud.githubusercontent.com/assets/16962860/13719596/4bfad2c0-e7ca-11e5-8b4a-16726bf6724d.png)

**Comment by jonathanborges3d** [comment]
@Luis-Fernando-Molina 

La vista previa de ésta versión:
![1](https://cloud.githubusercontent.com/assets/13649739/13720242/df52ff56-e7d5-11e5-8957-85f5a186922b.jpg)

![2](https://cloud.githubusercontent.com/assets/13649739/13720305/6c605e60-e7d7-11e5-88d5-542555167b2e.jpg)

**Comment by Luis-Fernando-Molina** [comment]
vamos a irnos por la version de Jonathan que se ve mas futurista.

@DexybelVillanueva por favor crea un caso para hacer la version 3d de cada una de estos graficos que tenemos aca: (un caso para cada uno, aunque primero vamos a ponernos de acuerdo haciendo el primero y luego el resto van a salir en base a eso)

https://cloud.githubusercontent.com/assets/13594347/13721792/ec044740-e803-11e5-8e84-1245bca5be88.jpg

1) Sharing Economy
2) P2P Economy
3) Internet
4) Internet of Things
5) Internet of People
6) La evolución de Competition to Massive Collaboration.

Vamos a usar este sistema de planetas para explicar las ideas, como te dije avanza con el primer caso y de ahi van a salir los otros. Pone todo este texto en un SUPER ISSUE.

**Comment by Luis-Fernando-Molina** [comment]
Jonathan evita usar los iconos de las aplicaciones de identity y communities

**Comment by jonathanborges3d** [comment]
Versión 1:
![puzzle_1](https://cloud.githubusercontent.com/assets/13649739/13745334/9ed19d7a-e9bf-11e5-8562-749648f7550a.jpg)

Versión 2:
![puzzle_2](https://cloud.githubusercontent.com/assets/13649739/13745365/d271f544-e9bf-11e5-808c-4ae16675188b.jpg)

Versión 3:
![puzzle_3](https://cloud.githubusercontent.com/assets/13649739/13745404/068ab9ce-e9c0-11e5-85c6-61f568b79493.jpg)

@Luis-Fernando-Molina 
Aún me faltan iconos por incluir, pero me gustaría que fueses viendo cómo quedaría dándole colores distintos a la esfera completa o a las piezas de forma individual.

Dime si la abertura con las piezas faltantes está bien o si le quitamos algunas otras piezas y desplazamos los iconos que hay hacia los otros espacios.

**Comment by Luis-Fernando-Molina** [comment]
segui vos buscando la forma que quede lo mejor posible.  Me parece que el heho que este iluminado solo arriba no ayuda. 

De colores queda mejor. Los iconos por ahi estan demasiado grandes.

**Comment by jonathanborges3d** [comment]
@Luis-Fernando-Molina Una escena así pudiese dar la impresión de que el conjunto se debe terminar. Ésta imagen debe llevar algún título o mensaje en texto?
![puzzle_4](https://cloud.githubusercontent.com/assets/13649739/13766254/866dd4ec-ea32-11e5-84bd-0ff41391222b.jpg)

**Comment by jonathanborges3d** [comment]
Con mejoras en la iluminación y en el orden de las piezas:
![puzzle_5](https://cloud.githubusercontent.com/assets/13649739/13816720/b5142e06-eb61-11e5-9682-f1ac067fe6c1.jpg)

**Comment by Luis-Fernando-Molina** [comment]
va mejorando, pero no pueden verse piezas sin logo. Adicional a eso el logo pudiera estar mas integrado a la pieza, no se como pero no se ve natural.

**Comment by jonathanborges3d** [comment]
@Luis-Fernando-Molina Incorporé un borde en relieve alrededor de los iconos para hacer que se vean mejor integrados a las piezas. Para las que no tiene iconos podríamos usar las identities?
![puzzle_7](https://cloud.githubusercontent.com/assets/13649739/13971570/5e2796ee-f063-11e5-9ba6-4e337126c0fa.jpg)
