### ISSUE TITLE
Generar logo para la plataforma Tokenly (TKY)

### ISSUE THREAD

**Issue by emmysm** [bitDubai/fermat-graphic-design#679]

**Comment by proseuz** [comment]
Propuesta 1
![tokenly 1](https://cloud.githubusercontent.com/assets/17308060/13716520/eb575e64-e7ad-11e5-8f97-b12b0ee2650c.png)

Propuesta2
![tokenly](https://cloud.githubusercontent.com/assets/17308060/13716521/eb6f0f5a-e7ad-11e5-95d7-d788835ab4d1.png)

@Luis-Fernando-Molina @emmysm

**Comment by darkestpriest** [comment]
@jhonmarquez92 ¿sería posible que la **T** se parezca un poco más a la que se usa en el logo de Tokenly? https://tokenly.com/

**Comment by proseuz** [comment]
@darkestpriest Seguro! ya lo modifico

**Comment by Luis-Fernando-Molina** [comment]
No se tiene que parecer, tiene que ser el logo de Tokenly adaptado a nuestro formato.

**Comment by proseuz** [comment]
@Luis-Fernando-Molina 
Versión 1 

![tokenly 3](https://cloud.githubusercontent.com/assets/17308060/13724696/de4c3ea8-e85f-11e5-86dd-d35be46bac3b.png)

Versión 2

![tokenly 2 1](https://cloud.githubusercontent.com/assets/17308060/13724697/de5ceb54-e85f-11e5-9448-93890dcb6847.png)
