### ISSUE TITLE
Organizar las fuentes del isologo Fermat en el repositorio

### ISSUE THREAD

**Issue by m471c4** [bitDubai/fermat-graphic-design#68]
Viene del #13 

Una vez completada la fase de diseño, será necesario organizar debidamente en el repositorio las fuentes del isologo (con sus acepciones), así como los distintos tamaños sugeridos, en sus respectivos formatos.

**Comment by arnaldos** [comment]
@m471c4 @Luis-Fernando-Molina @jonathanborges3d ya subi los archivos y las fuentes al repositorio con sus respectivas acepciones por lo que creo ya podemos cerrar este caso
