### ISSUE TITLE
Graphic #1 – Fermat Network  

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#680]
This illustration shows the position of ‘network nodes’ in ‘Fermat’s P2P Network’ and the position of ‘client nodes’ (devices i.e. phones, tablets, laptops, servers) in ‘Fermat’s P2P Extended Network’. The ‘Fermat P2P Extended Network’ sits above the ‘Fermat’s P2P Network’. Both networks have open ends so other nodes can join. Network nodes connect to Wifi, Bluetooth or NFC before connecting to the ‘Fermat’s P2P Network’.

The yellow network diagram in figure 1 shows the way in which a P2P network is connected. Figure 2 shows the rough placement of the main components, including labels. It is not to scale and should be used as a guide and not be copied.

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina te comparto el gráfico genere 3 versiones, 1 como lo conversamos de la media luna par los dispositivos y 2 con otra diagramacion distinta. 

Me apunto por la versión 3 pero no se si se apega a lo que buscas representar, avísame cualquier cambio. 

### Version 1

---

![web rediseno 1-02](https://cloud.githubusercontent.com/assets/13594347/13724065/74292c02-e84b-11e5-9ada-8d0f98690ae9.jpg)

### Version 2

---

![web rediseno 1-03](https://cloud.githubusercontent.com/assets/13594347/13724066/74519156-e84b-11e5-860c-e8bb9775841e.jpg)

### Version 3

---

![web rediseno 1-04](https://cloud.githubusercontent.com/assets/13594347/13724067/74785a34-e84b-11e5-97d4-ed60e93a3f9d.jpg)

**Comment by Luis-Fernando-Molina** [comment]
1-El grafico no tiene dos mitades como el otro, solo tiene la Fermat P2P Network al centro y la extended al rededor

2- Los dispositivos se ven bien pero no los pongas dentro de ningun circulo

3- Cada dispositivo se tiene que conectar a uno o mas nodos de la Fermat P2P Network, no entre si

**Comment by Luis-Fernando-Molina** [comment]
4-El titulo de Fermat P2P Network debe estar dentro de la frontera no afuera
5. El titulo de la extended debe estar afuera de la frondera pero del lado de abajo

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina los ajustes de los graficos 

### Version 4

---

![web rediseno 1-06](https://cloud.githubusercontent.com/assets/13594347/13724527/994bde26-e85a-11e5-911b-78887a098b79.jpg)

### Version 5

---

![web rediseno 1-07](https://cloud.githubusercontent.com/assets/13594347/13724528/9950735a-e85a-11e5-9bdc-e87d3f5cfa0f.jpg)

### Version 6

---

![web rediseno 1-05](https://cloud.githubusercontent.com/assets/13594347/13724529/995602c0-e85a-11e5-9a50-af1cd534dc31.jpg)

**Comment by Luis-Fernando-Molina** [comment]
Es por el lado de la Version 5
1. Hace que los dispositivos den toda la vuelta.
2. La linea verde volvela a azul. La verde debe ser un circulo mas para afuera, es una frontera no otra orbita donde hay nodos. Eso empujaria los dispositivos todavia mas afuera.

**Comment by Luis-Fernando-Molina** [comment]
1. El tamaño del texto debe ser consistente.

**Comment by arnaldos** [comment]
perfecto !!!

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina te comparto los ajustes

![web rediseno 1-08](https://cloud.githubusercontent.com/assets/13594347/13724699/eea550be-e85f-11e5-877b-e83c57eed5ba.jpg)

**Comment by Luis-Fernando-Molina** [comment]
1. en verde poner "Fermat Network".
   2.El label de Fermat P2P Extended Network ponelo abajo no al constado y solo un label.
2. El label en Verde debiera ser del mismo tamaño que los otros labels

**Comment by Luis-Fernando-Molina** [comment]
1. Los nodos Fermat mas grandes achicalos un poco

**Comment by Luis-Fernando-Molina** [comment]
Move por favor el nodo fermat que entra dentro del circulo mas interno hacia afuera.

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina comparto los ajustes

![web-rediseno-1-09](https://cloud.githubusercontent.com/assets/13594347/13729677/f8d624fc-e90c-11e5-8b70-b611534d17fa.jpg)

**Comment by Luis-Fernando-Molina** [comment]
Porque achaste la letra del texto en Verde?

**Comment by Luis-Fernando-Molina** [comment]
El fondo debe ser en transparente y en PNG

**Comment by arnaldos** [comment]
El texto verde, lo puse mas pequeño según lo que me comentas:

> 2.El label de Fermat P2P Extended Network ponelo abajo no al constado y solo un label.

A lo que entiendo los textos deben unificarse tanto el verde como el salmón del mismo tamaño.

Hice varias pruebas, para el tamaño de los textos 

##### Version 1 Textos del mismo tamaño, tomando como referencia el tamaño del color verde.

El texto del centro se monta sobre los vértices y los nodos.

![web rediseno 1-10](https://cloud.githubusercontent.com/assets/13594347/13732399/25c109cc-e954-11e5-8677-9bac8cd0f61a.png)

##### Version 2 Textos del mismo tamaño, tomando como referencia el tamaño del color salmon.

Fue el que coloque, quedan muy chicos.

![web rediseno 1-08](https://cloud.githubusercontent.com/assets/13594347/13732414/7dbb12f8-e954-11e5-9f71-0bff97c56ca9.png)

##### Version 3 Texto verde mas grande, y los otros mas chicos.

Como se venia trabajando

![web rediseno 1-09](https://cloud.githubusercontent.com/assets/13594347/13732425/afdcd83e-e954-11e5-89c1-167838b2246f.png)

##### Version 4 Textos que están afuera de la frontera mas grande, y el del centro mas chico.

![web rediseno 1-11](https://cloud.githubusercontent.com/assets/13594347/13732437/f5948098-e954-11e5-92f5-cc7700028fc7.png)

La versión 4 me parece que funciona mejor.

**Comment by Luis-Fernando-Molina** [comment]
El verde tiene que ser del mismo tamaño que en los otros graficos que hicimos, y el rojo del mismo tamaño que en los otros graficos que hicimos. En otras palabras, tenes que asumir que TODOS LOS GRAFICOS LOS VAMOS A USAR EN EL MISMO LUGAR Y POR LO TANTO EL TAMAÑO DE LA LETRA DEBE SER CONSISTENTE-

**Comment by Luis-Fernando-Molina** [comment]
Genera una version por favor de acuerdo a mi ultimo comentario. gracias

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina los ajustes eñ tamaño de los textos estan estandarizados paritendo del primer grafico. el texto del centro lo coloque en 3 lineas para evitar que quede sobre los nodos y vértices.

![web-rediseno-10](https://cloud.githubusercontent.com/assets/13594347/13755793/12f71958-e9ef-11e5-80f5-717d445b9e6e.png)

**Comment by Luis-Fernando-Molina** [comment]
Ok este esta terminado :+1:

**Comment by arnaldos** [comment]
perfecto !!!!

**Comment by arnaldos** [comment]
ya subo los fuentes !!!

**Comment by Luis-Fernando-Molina** [comment]
pone el grafico en el repositorio de Media Kit como algo mas disponible para que se use libremente en los medios o la documentacion. @gustl-arg atencion asi usas este grafico en el libro o donde aplique una vez que este en el media kit. Arnaldo abri un folder para este tipo de graficos,

Cerra el caso cuando este en el media kit.

**Comment by arnaldos** [comment]
vale perfecto !!!

**Comment by arnaldos** [comment]
@gustl-arg  @Luis-Fernando-Molina cierro el caso, ya los fuente están en el media kit 
https://github.com/Fermat-ORG/media-kit/tree/master/Infographies

**Comment by Luis-Fernando-Molina** [comment]
Crea tambien una seccion en el README del media kit para estos infograficos.
