### ISSUE TITLE
Graphic #2 – The Fermat Framework 

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#681]
This illustration shows how ‘Fermat’s Framework’ enables ‘FrAPPes’ to work. It is important to show that the components (‘FrAPPlets’) are interconnected and work together. ‘Fermat’s FrAPPe Store’ contains all Apps (‘FrAPPes’), which are all made up on components (‘frAPPlets’). Underneath all this are ‘Fermat’s P2P Network’ and the device’s operating system (OS).

Figure 1 is to give a rough idea of the relationship between the illustration’s elements. Please do not take it literally and do not reproduce it. It is not to scale.

**Comment by m471c4** [comment]
@Luis-Fernando-Molina @arnaldos primera versión para el gráfico Fermat Framework:

Versión 1:
![fermat_framework2](https://cloud.githubusercontent.com/assets/13468350/13724165/7bb3dadc-e84e-11e5-9026-1b6205de0794.png)

Hice una segunda versión encerrando los componentes dentro de un círculo ya que va mejor con la línea gráfica general que estamos manejando:
![fermat_framework](https://cloud.githubusercontent.com/assets/13468350/13724143/903d7126-e84d-11e5-80ff-653758c92923.png)

**Comment by Luis-Fernando-Molina** [comment]
Me gusto en general, ahora vamos a refinar:
1. El arbol lleva componentes, no pizas sueltas.
2. Cada rama debe tener mas de un componente
3. Quita el logo de Fermat de arriba.
4. Deja el componente en grande a un costado con el titulo "Component"
5. El titulo de arriba debe ser Fermat Framework

**Comment by m471c4** [comment]
@Luis-Fernando-Molina ¿así te parece bien?

![fermat_framework_new](https://cloud.githubusercontent.com/assets/13468350/13724583/687add5e-e85c-11e5-9992-78ff809d9a2f.png)

**Comment by Luis-Fernando-Molina** [comment]
> Deja el componente en grande a un costado con el titulo "Component"

Te escribi exactamente como tenía que quedar, osea si la "s"

**Comment by Luis-Fernando-Molina** [comment]
En vez de poner las bolitas al final de cada rama, ponelas como colgando de un hilito en cada rama.

**Comment by m471c4** [comment]
Ok, hago los cambios y lo subo.

**Comment by m471c4** [comment]
@Luis-Fernando-Molina acá con los cambios que me pediste:

![fermat_framework_ball](https://cloud.githubusercontent.com/assets/13468350/13725042/32bdf2a2-e869-11e5-88af-4fc8cfede20b.png)

**Comment by Luis-Fernando-Molina** [comment]
De cada rama  QUE CUELGUE MAS DE UN COMPONENTE. A cada rama me refiero no a la que sale del tronco si no a las subdivisiones incluso. Osea elimina algunas subdivisiones para que entren mas de un componente por rama.

**Comment by Luis-Fernando-Molina** [comment]
Hace que los componentes no tapen las ramas

**Comment by m471c4** [comment]
@Luis-Fernando-Molina acá con los ajustes:

![fermat_framework_ball2](https://cloud.githubusercontent.com/assets/13468350/13725937/ec310e08-e883-11e5-8b6e-e1af57a2ff19.png)

**Comment by Luis-Fernando-Molina** [comment]
Ok va bien, hace por favor que las ramas de donde salen ramitas que no tengan componentes, solo ramitas. Los componentes solo colgarian de esas ramitas. Y debieran haber mas de un componente por ramita en lo posible.

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina el ajuste de @m471c4 

![fermat_framework](https://cloud.githubusercontent.com/assets/13594347/13758750/2cb61958-e9fd-11e5-8045-79dab53d7845.png)

**Comment by Luis-Fernando-Molina** [comment]
ok: 1- El tronco ponele una linea de punto especial como -.-.-.-.-.-.-   luego en las referencias, donde ahora esta Component agrega que significa ese tronco, en esto caso es una "Platform".

Disculpa el cambio, pero vamos a tener solo RAMAS, ninguna RAMITA. En las referencias las lineas de guiones ponele "LAYERS" y tienen que seguir siendo una linea de guiones ---------------

Arriba de todo pone no un componente grande como ahora sino 3 componentes y de otro color, verde. y en las referencias ponele "GUI Component"

Crea dos replicas del arbol resultante y ponela a los costados, y unilas con un piso de lineas de puntos .................... . En las referencias pone un recuadro etiquedado FRAMEWORK y pone adentro las lineas de puntos las de .-.-.-.-. y la de solo guiones.

Los tres arboles debieran ocupar todo el ancho y las referencias estar abajo de todo eso.

Avisame apenas este listo.

**Comment by m471c4** [comment]
@Luis-Fernando-Molina muy bien, voy a aplicar los cambios y lo subo.

**Comment by arnaldos** [comment]
@m471c4 comenta:
@luis-fernando-molina acá con los cambios. Por favor confírmame si la leyenda debe verse así. No me dijiste qué debo poner como significado de la línea punteada.

![fermat_framework](https://cloud.githubusercontent.com/assets/13594347/13763235/e927755a-ea16-11e5-84b5-62b48549907c.png)

**Comment by Luis-Fernando-Molina** [comment]
1."Layers" cambialo por "Layer"
2.¿¿?? ponele "Core"
3.  Arriba de cada arbol poné 3 componetes verdes EN CADA UNO.
4. Asegurate que el tamaño de la letra verde sea igual que en los otros diagramas. Lo mismo con la letra roja.
Ya casi estamos.
5. Al rectangulo de Framework redondeale las puntas.

**Comment by m471c4** [comment]
@Luis-Fernando-Molina acá el gráfico con las mejoras aplicadas. Hice dos versiones porque no me queda claro cómo quisieras los GUI components.

Estandaricé los tamaños de los textos, solo mantuve más pequeños los que están dentro del rectángulo.

Versión 1:
![fermat_frameworkv1](https://cloud.githubusercontent.com/assets/13468350/13788323/8035cb3c-eab1-11e5-8002-24276848efe7.png)

Versión 2:
![fermat_frameworkv2](https://cloud.githubusercontent.com/assets/13468350/13788378/b299f062-eab1-11e5-98ca-3e55e2e41d81.png)

**Comment by Luis-Fernando-Molina** [comment]
1. Es CORE no CODE.  
2. Los componentes verdes debieran estar todos unos al lado del otro  alineados al centro verticalmente.

**Comment by m471c4** [comment]
@Luis-Fernando-Molina perdón por el error. Acá lo subo con los ajustes, hice dos versiones, una con los GUI components todos del mismo tamaño y otra con los laterales más pequeños.

Versión 1:
![fermat_frameworkv3](https://cloud.githubusercontent.com/assets/13468350/13794690/6c1bb9f4-eacf-11e5-8005-6d1ff727eb7b.png)

Versión 2:
![fermat_frameworkv4](https://cloud.githubusercontent.com/assets/13468350/13794720/8c8fe44e-eacf-11e5-84c2-19467f0212ed.png)

**Comment by Luis-Fernando-Molina** [comment]
Listo :+1:

**Comment by m471c4** [comment]
@Luis-Fernando-Molina: ¡perfecto! Subiré los editables al repo. ¿Queda la versión 1 o la dos?

**Comment by Luis-Fernando-Molina** [comment]
la 2

ponerlo en el media kit y su readme junto con todos los otros

**Comment by arnaldos** [comment]
ya esta en el media kit

**Comment by Luis-Fernando-Molina** [comment]
@arnaldos un monton de veces dije que tenia que estar tambien en el README del media kit y no los veo ahi...

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina ya están incluidos los que están listos, estaba esperando por el resto para montarlos juntos, pero ya los incluí en el README https://github.com/Fermat-ORG/media-kit/blob/master/README.md

**Comment by m471c4** [comment]
@Luis-Fernando-Molina ajustes en los colores de las líneas. Usé el mismo verde que usó @arnaldos en su gráfico y el verde Fermat.

![graphics_2_new](https://cloud.githubusercontent.com/assets/13468350/13856140/02df2d7c-ec46-11e5-9a3e-509f884bd46d.png)

**Comment by m471c4** [comment]
@Luis-Fernando-Molina acá mejoró el contraste de los colores. Probé engrosando las líneas para que se noten más.

![graphics_2_new](https://cloud.githubusercontent.com/assets/13468350/13861401/4ff99336-ec5f-11e5-8e85-779856641d1b.png)
