### ISSUE TITLE
Graphic #3 – Fermat’s Framework Layers

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#682]
This illustration shows how ‘Fermat’s Framework’ consists of super layers. There are 5. Super layers commonly have between one and five layers. These layers comprise of components ‘FrAPPlets’. The FrAPPlets in each layer provide a service to those FrAPPlets in the layers above, and the FrAPPlets in the layers below consume a service.

The rough diagram is to give an idea of the relationship of the elements. Please do not take it literally and do not reproduce it. It is not to scale.

**Comment by emmysm** [comment]
![sin titulo-1](https://cloud.githubusercontent.com/assets/15143489/13724290/3396cd0e-e853-11e5-8773-343c2e794442.png)

@Luis-Fernando-Molina

**Comment by Luis-Fernando-Molina** [comment]
Hola Emmy, los componentes ponelos como los hizo @m471c4 un circulito con piezitas adentro
Y Alcanza con un solo super layer completo y dos mitades, una abajo y otra arriba.

Los textos con los formatos que ya venimos haciendo por favor

**Comment by emmysm** [comment]
Propuesta 1

![sin titulo-1-02](https://cloud.githubusercontent.com/assets/15143489/13724946/25bd1af8-e867-11e5-8b32-1958f4137b31.png)

Propuesta 2

![sin titulo-1-01](https://cloud.githubusercontent.com/assets/15143489/13724947/25f01462-e867-11e5-9642-3554af192fbe.png)

@Luis-Fernando-Molina  tengo algunas dudas con respecto a tus ajuste. checa a ver si te agarré la idea, porfa.

**Comment by Luis-Fernando-Molina** [comment]
1. La palabra layer ponela dentro del rectangulo que representa cada layer.
2. Cada componente, igual que como hizo @m471c4 ponele diferente numeros de piezas adentro y que sean de fiferentes tamaños.
3. El esquema se debe parecer mas a la propuesta 1 pero con dos super layers en vez de 3. El segundo superlayer ponele los 2 layers ultimos.

**Comment by emmysm** [comment]
![sin titulo-03](https://cloud.githubusercontent.com/assets/15143489/13757483/e035e55a-e9f6-11e5-89e6-c8b766f5ce1e.png)

**Comment by proseuz** [comment]
@Luis-Fernando-Molina  cómo vamos por acá?

**Comment by Luis-Fernando-Molina** [comment]
esto esta listo :+1:

**Comment by Luis-Fernando-Molina** [comment]
ponerlo en el media kit y su readme junto con todos los otros
