### ISSUE TITLE
Graphic #4 – Fermat’s Platforms

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#683]
This illustration shows the vertical stack of Fermat platforms in the front of a cube. In the left side of the cube are the horizontal Framework layers. The far left and right side of the cube should be left open to reflect an open system. On the top of the cube are Apps (FrAPPes), aligned with the platforms.

Each FrAPPe draws on components (FrAPPlets) from the platform. Some FrAPPlets are used by other platforms.

The rough diagram is to give an idea of the location of FrAPPlets within a platform. Please do not take it literally. It is not to scale.

**Comment by arifernandez** [comment]
![diagrama fermat platform-01](https://cloud.githubusercontent.com/assets/16305653/13724831/31716186-e864-11e5-963c-18279ea74a89.jpg)

@arnaldos

**Comment by Luis-Fernando-Molina** [comment]
Hola, al parecer no se entendió mi mensaje. La idea no es listar las plataformas que existen ni sus capas y componentes. La idea es hacer un esquema que deje entender que hay multiples plataformas y que dentro de cada una hay capas y dentro de cada capa componentes.

Los componentes tenes que graficarlos como los hizo @m471c4 

Las capas por ahora alcanza con un rectangulo horizontal.

Las plataformas como un rectangulo vertical.

Alcanza con 4 o 5 plataforma, cada una con unas 5 o 6 capas y cada una con un numero variable de componentes.

**Comment by arifernandez** [comment]
Propuesta 1

![diagrama fermat platform-01](https://cloud.githubusercontent.com/assets/16305653/13782150/312df2d0-ea98-11e5-86e5-106a9fa07bb0.jpg)

Propuesta 2

![diagrama fermat platform 2-01](https://cloud.githubusercontent.com/assets/16305653/13782166/42ce585e-ea98-11e5-942f-e2c5d6695799.jpg)

@Luis-Fernando-Molina

**Comment by Luis-Fernando-Molina** [comment]
1- Cada componente es un circulo con piecitas adentro., no las piecitas en si mismas.
2-No estas respetando el tipo tamaño y estilo de las letras de los otros diagramas, habla con  @arnaldos para que te oriente.
3-los layers no estan centrados dentro de cada plataforma
4- Las referencias deben estar mas abajo al medio y fuera de esos rectangulos
5-Dice "Fermar", realmente debieras revisar mejor lo que subis antes de presentarmelo ami. Tené en cuenta que tengo muy poco tiempo.

@arnaldos vos debieras revisar lo que hacen los de tu equipo antes de tagearme.

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina perfecto ya oriento a @arifernandez

**Comment by arifernandez** [comment]
![diagrama fermat platform-01](https://cloud.githubusercontent.com/assets/16305653/13827053/ce4c1a16-eb8c-11e5-83f1-ca257424dd6d.jpg)

@arnaldos Aquí estan las modificaciones

**Comment by Luis-Fernando-Molina** [comment]
Ok ahi estaria, gracias!

Falta que este en PNG con el fondo transapente

**Comment by arifernandez** [comment]
![diagrama fermat platform-01](https://cloud.githubusercontent.com/assets/16305653/13828715/2b452638-eb95-11e5-9b9d-cf4a9b0a5a66.png)

**Comment by arnaldos** [comment]
@arifernandez plz has el pull r de esto para pasarlo al media kit
