### ISSUE TITLE
Graphic #5 Architecture

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#684]
The Fermat System has three major architectural components:

The Network: a peer-to-peer system that allows data flows between devices without going through central servers

The Library: where reusable components (APPs) are stored or can be drawn upon for use in Fermat-powered applications (APPs) and where component additions can be made

The Front End: Where end users interact with APPs that can, at any time, be made up of dozens of components

**Comment by ivonnesantos** [comment]
Hola @Luis-Fernando-Molina según lo entendido en la descripción del issue aca hice dos propuestas vi el video de el sabado y esta parte no fue explicada espero haber dado con la idea o al menos el concepto 
![graphic_n5_propuesta1-01](https://cloud.githubusercontent.com/assets/15238660/13760758/efb975d6-ea06-11e5-9083-30056797d749.jpg)
![graphic_n5_propuesta1-02](https://cloud.githubusercontent.com/assets/15238660/13760759/efd0404a-ea06-11e5-8261-977cc2a8c696.jpg)

**Comment by Luis-Fernando-Molina** [comment]
Vamos a ir por el lado de la propuesta 2.

Cambia Library por Framework y usa algo parecido a los que hizo Dayana representando el framework, Pero sin los compoentes (los arbolitos)

En el Network, usa algo parecido a lo que hizo Arnaldo representando la network. (sin la extended network)

Cambia el Front End por el Ecosystema de Fermat APPs. Usa una version en celeste de los iconos de distintas APPs Fermat que ya tenemos mas un conjunto de componentes abajo de los iconitos. A todos los componentes agrupalos con un rectangulo y ponele como label Component Library

**Comment by ivonnesantos** [comment]
@Luis-Fernando-Molina en lo de network no se transmite que los componentes son reciclables (se perdió en la corrección que aplique ahorita) y un detalle en este texto Ecosystema de Fermat APPs esta como en español inglés creo que no esta bien.  
![graphic_n5_propuesta1-02](https://cloud.githubusercontent.com/assets/15238660/13797879/d5fcb0d6-eae2-11e5-9700-6a6e25066b22.jpg)

**Comment by Luis-Fernando-Molina** [comment]
1. pone "The Framework"
2. pone "Ecosystem of Fermat APPs"
3. Quita el texto "Label Compoent Library" y en su lugar pone muchos mas componentes.
4. El Framework no esta bien representado, revisa el diagrama que habla de eso y lee los comentarios vas a ver que las bolitas cuelgan de las ramas. gracias.

**Comment by ivonnesantos** [comment]
@Luis-Fernando-Molina 
![graphic_n5_propuesta1-02](https://cloud.githubusercontent.com/assets/15238660/13820970/e9b4257a-eb71-11e5-8e52-c3363f8920cf.jpg)

**Comment by Luis-Fernando-Molina** [comment]
la imagen debe estar en PNG

**Comment by ivonnesantos** [comment]
OK eso no lo sabia arnaldo me lo comento ayer y ya lo habia subido. Pero esta bien hecho el diagrama, llegamos al objetivo que quieres? @Luis-Fernando-Molina

**Comment by ivonnesantos** [comment]
El mismo sin ningun Cambio solo que esta en PNG @Luis-Fernando-Molina 
![graphic_n5_propuesta1-02](https://cloud.githubusercontent.com/assets/15238660/13860806/5b6ec0f4-ec5c-11e5-8573-ce83b6608b40.png)

**Comment by Luis-Fernando-Molina** [comment]
ok, esto esta listo :+1:
