### ISSUE TITLE
Graphic #6 

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#685]
INSERT INFO GRAPHIC 7 HERE EXPLAINING THE PREVIOUS PARAGRAPH (platforms) 

Need graphic making a clear distinction between layers and platforms

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina falta saber de que trata esto en el mail no sale.

**Comment by Luis-Fernando-Molina** [comment]
Este caso cerralo porque ya tenemos uno para eso, el que esta haciendo Ariana.
