### ISSUE TITLE
Graphic #7

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#686]
Agree, and the additional content should include graphics that vividly illustrate the stream of payments to developers

With all these options, the Fermat project aims to recruit thousands of developers into a global network with the highest software developing power ever amassed. By participating in Fermat, developers can achieve sustainable self-employment by disintermediating software development corporations.

Fermat’s core concept is ownership of developed components. This allows developers to enjoy a stream of micro payments flowing from around the globe. The Fermat system even allows them to trade that ownership by selling it to someone else.

**Comment by proseuz** [comment]
Mi propuesta @Luis-Fernando-Molina 

![the stream of payments to developers2](https://cloud.githubusercontent.com/assets/17308060/13762253/d75d798e-ea0f-11e5-927f-f5626a70b83f.png)

**Comment by Luis-Fernando-Molina** [comment]
No le encuentro a esto la relacion con lo que estamos tratando de esquematizar. 

YO dibujaria un planeta tierra, al rededor de el muchos dispositivos como en orbita y de todos sacaria una linea de puntos que se termina uniendo en un solo canal o STREAM y llega hasta una burbujita donde esta un developer que va acumulando moneditas. En ese canal se pudieran ver las moneditas.

Mira este video asi entendes de que estamos hablando: 

https://www.youtube.com/watch?v=UnQ0rxKknk8&feature=youtu.be

**Comment by proseuz** [comment]
Propuesta 2 (con correcciones) @Luis-Fernando-Molina 

 ![the stream of payments to developers 3](https://cloud.githubusercontent.com/assets/17308060/13795328/5d2adf8a-ead2-11e5-9c28-ed5293479c4d.png)

**Comment by Luis-Fernando-Molina** [comment]
1. Ok va bien. Revisa el tamaño y tipo de letra para que sea el mismo que en todos los otros digramas para las letras de cada color.
2. La linea de punto rojas ponela como un circulo por fuera de los dispositivos.
3. El planeta puede ser mas chico, un poco.
4. El planeta debiera ser el centro de un sistema con ejes radiales similares a los que usamos hasta ahora. Los puntos azules en los cruces como hasta ahora, y algunos con el logo de fermat. Los dispositivos conectados a esos nodos de manera aleatoria.

5.al developer ponelo de la cintura hacia arriba que se vea mas su compu y el componente y el dinero que se acumule mas cerca de su pc.

**Comment by proseuz** [comment]
@Luis-Fernando-Molina 
Lo dispuse de manera horizontal para mantener el tamaño de las demás infografías 
![the stream of payments to developers4](https://cloud.githubusercontent.com/assets/17308060/13828871/140675ca-eb96-11e5-9952-e9efd5264deb.png)

**Comment by Luis-Fernando-Molina** [comment]
> La linea de punto rojas ponela como un circulo por fuera de los dispositivos.

que paso con esto?

**Comment by Luis-Fernando-Molina** [comment]
No me entendiste. No hacia falta un circulo alrededor de cada dispositivo, sino que exista un circulo rojo , UNA ORBITA MAS, donde los dispositivos ponen sus moneditas asi se evitan todas las lineas que se enciman. ese circulo debiera ir por fuera de lo que hoy existe.

Otra cosa, los nodos Fermat y los nodos azules debes estar en las intersecciones de las orbitas y los ejes.

**Comment by proseuz** [comment]
Correcciones aplicadas @Luis-Fernando-Molina 

![the stream of payments to developers7](https://cloud.githubusercontent.com/assets/17308060/13861438/96bcb80c-ec5f-11e5-8819-122d85e8c590.png)

**Comment by Luis-Fernando-Molina** [comment]
Muchisimo mejor ahora. 
1. Pone de titulo: "Stream of Micro Payments"

y con eso estaría.

**Comment by Luis-Fernando-Molina** [comment]
Por favor necesito esto con urgencia

**Comment by proseuz** [comment]
@Luis-Fernando-Molina 

![the stream of payments to developers8](https://cloud.githubusercontent.com/assets/17308060/13887829/13197f24-ed10-11e5-8565-dca218614604.png)

**Comment by proseuz** [comment]
![stream of micro payments](https://cloud.githubusercontent.com/assets/17308060/13888476/db342948-ed13-11e5-8464-5051c7905538.png)

@Luis-Fernando-Molina @emmysm

**Comment by Luis-Fernando-Molina** [comment]
:+1:
