### ISSUE TITLE
Version 3D infografia N°1 Sharing Economy

### ISSUE THREAD

**Issue by DexybelVillanueva** [bitDubai/fermat-graphic-design#691]
Viene de #690

**Comment by DexybelVillanueva** [comment]
@Luis-Fernando-Molina @jonathanborges3d 

1era Versión de prueba

1)![captura de pantalla 2016-03-14 22 57 08](https://cloud.githubusercontent.com/assets/16962860/13767072/61c9153c-ea39-11e5-8c3e-34754f60e60d.png)

2)![captura de pantalla 2016-03-14 22 58 12](https://cloud.githubusercontent.com/assets/16962860/13767073/61d327c0-ea39-11e5-87ab-938c9633bd56.png)

3)![captura de pantalla 2016-03-14 22 59 03](https://cloud.githubusercontent.com/assets/16962860/13767074/61daacb6-ea39-11e5-933d-6f21dea2d8dc.png)

**Comment by DexybelVillanueva** [comment]
@Luis-Fernando-Molina  avance de los personajes , solo faltaría los objetos que sostiene la segunda persona  
![personajes](https://cloud.githubusercontent.com/assets/16962860/13799876/b042deac-eaf5-11e5-9f04-a1558d7ddbbc.png)

**Comment by DexybelVillanueva** [comment]
1era versión de prueba, con respecto a los personajes todavía estoy buscando una mejor opción 

1)![untitled 276](https://cloud.githubusercontent.com/assets/16962860/13835353/46a50b62-ebc9-11e5-9d3c-5ba199a71710.jpg)

2)![untitled 278](https://cloud.githubusercontent.com/assets/16962860/13835354/46aafe5a-ebc9-11e5-8d43-5dc157152758.jpg)

3)![untitled 279](https://cloud.githubusercontent.com/assets/16962860/13835355/46aea668-ebc9-11e5-83f3-b4cc5917c860.jpg)

**Comment by Luis-Fernando-Molina** [comment]
Esta mejor, algunas observaciones
1. La evolucion es uni-direccional desde la sharing hacia la p2p
   2.los logos no pueden estar en el air, sino representando de alguna manera que son intermediarios y las cosas pasan a traves de ellos.. En la sharing la gente esta mas separada.
2. Si vas a poner 3 escenas solamente buscate las empresas mas mundialmente conocidas como pertenecientes a la sharing economy: uber, aribnb y alguna otra mas.

**Comment by DexybelVillanueva** [comment]
@Luis-Fernando-Molina  buenas, como le gustaría que sean los personajes?, por ahora tengo estas propuestas sencillas, o quiere personajes mas detallados?

![untitled 281](https://cloud.githubusercontent.com/assets/16962860/13862041/df7d4e6e-ec62-11e5-9f66-6b7bfcee132c.jpg)
![untitled 282](https://cloud.githubusercontent.com/assets/16962860/13862042/df86b878-ec62-11e5-9adc-bb72e8fb65d3.jpg)

**Comment by DexybelVillanueva** [comment]
Nueva versión con los cambios correspondientes

1)![infografia personajes 2 285](https://cloud.githubusercontent.com/assets/16962860/13864638/639f5dba-ec75-11e5-8e61-925f8e8162ac.jpg)
2)![infografia personajes 2 286](https://cloud.githubusercontent.com/assets/16962860/13864631/56820024-ec75-11e5-97e9-e3dbd3ca2c46.jpg)
3)![infografia personajes 2 287](https://cloud.githubusercontent.com/assets/16962860/13864632/5687d134-ec75-11e5-93c4-595ef67579a5.jpg)

**Comment by DexybelVillanueva** [comment]
Render alta resolución 1920x 1070

1)![untitled 296](https://cloud.githubusercontent.com/assets/16962860/13939673/586a0256-efa9-11e5-8976-cb2c895dd4fd.jpg)

2)![untitled 297](https://cloud.githubusercontent.com/assets/16962860/13939674/58761da2-efa9-11e5-9f28-f1995ef3f83d.jpg)

**Comment by Luis-Fernando-Molina** [comment]
Version 2

Los logos de las empresas no se ven. Solo pone el logo sin el nombre. UBER; AIRBNB, EBAY.

Ponelos horizontales en la mesa, no parados.

**Comment by DexybelVillanueva** [comment]
Formato en alta resolución 

1)![untitled 302](https://cloud.githubusercontent.com/assets/16962860/13957755/cde4498a-f01f-11e5-8cd0-16604481f3cb.jpg)
