### ISSUE TITLE
Generate an icon for all apps recients into fermat App

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#692]

**Comment by furszy** [comment]
No estoy seguro que sea un icono, pero necesitamos uno provisorio.

**Comment by arnaldos** [comment]
@furszy mira esto si puede funcionar para recents apps 

#### Version 1

![recents-1](https://cloud.githubusercontent.com/assets/13594347/14332260/72b866fa-fc12-11e5-83a5-dd7c997b4233.jpg)

#### Version 2

![recents-2](https://cloud.githubusercontent.com/assets/13594347/14332261/72bc41da-fc12-11e5-8ac7-f65df48c2dc4.jpg)

#### Gif animado

![recents_animation](https://cloud.githubusercontent.com/assets/13594347/14332292/a301089e-fc12-11e5-91b6-7d6c2536ecec.gif)

**Comment by Luis-Fernando-Molina** [comment]
no me convence de que eso se acceda desde algo asi. Yo lo haria apretando un espacio vacio del desktop por unos segundos, sin icono ni nada.

**Comment by arnaldos** [comment]
ok pero eso ya seria a nivel de desarrollo, lo que pienso es que se puede hacer un modal explicativo, tipo tutorial para que las personas entiendan el funcionamiento, y las personas entiendan, porque de entrada si las personas nunca han interactuado con la app, va ser difícil de entender o ubicar esta función. Por eso me apegaba a la idea de una slice para sacar el boton y presionarlo, para realizar esta acción.

**Comment by Luis-Fernando-Molina** [comment]
Como yo dije @furszy
