### ISSUE TITLE
Create an empty icon

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#693]
Create an empty icon that appears when the banner image does not exist or load.

**Comment by isahq23** [comment]
Propuestas

![unavailable_banner-01](https://cloud.githubusercontent.com/assets/15214774/13759726/b6bbdb8e-ea01-11e5-9948-7c2bf0a8e823.png)

![unavailable_banner-02](https://cloud.githubusercontent.com/assets/15214774/13759729/ba72483a-ea01-11e5-8fde-134a4fe36b24.png)

**Comment by arnaldos** [comment]
@isahq23  me gusta la versión 1, que opinas @furszy ?

**Comment by furszy** [comment]
Por mi no hay problema para una versión 1. armala con los tamaños que hablamos y la empiezo a usar. Gracias.

**Comment by isahq23** [comment]
Listo @arnaldos @furszy ya subí el banner para utilizarlo al drive.

**Comment by arnaldos** [comment]
@isahq23 perfecto !!!
