### ISSUE TITLE
Create a coin for Disrruptors team

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#695]
Create a coin for disruptors team logo defined in the issue #181 

Files in this link

https://github.com/Fermat-ORG/fermat-graphic-design/tree/95fb4bcd79e986d3889fc6b7f2f7a8ada2bfa0ad/2D%20Design/bitDubai/Logotypes%20Teams%20bitDubai/Logo_disruptors_team/logo%20disruptors

@jonathanborges3d @Rart3001

**Comment by jonathanborges3d** [comment]
First version:

![disruptors_1](https://cloud.githubusercontent.com/assets/13649739/13798413/5b7f1938-eae8-11e5-9141-9ed03293d0aa.jpg)

@arnaldos @Rart3001 @Fermat-ORG/disruptors-team

**Comment by Rart3001** [comment]
@jonathanborges3d me gusta mucho, tienes alguna otras versiones?

**Comment by Rart3001** [comment]
@arnaldos @jonathanborges3d muchachos debemos definir si esta es la versión final, ya que se necesita completar algunos documentos con el logo.

**Comment by hendry19901990** [comment]
para mi esta mundial esa First version @arnaldos

**Comment by jonathanborges3d** [comment]
Chicos, disculpen, la verdad no he tenido el chance de hacer una nueva versión, estoy full con otras cosas que me ha encomendado Luis y no tengo más que mostrar por ahora.

**Comment by Rart3001** [comment]
@arnaldos @jonathanborges3d @arnaldos buenos tomemos esta como la versión final, por favor si me puedes facilitar el url del archivo para poner la imagen en el documento de README-DEV-TEAMS.MD

**Comment by jonathanborges3d** [comment]
@Rart3001 Tranquilo, éso lo hago Yo más tarde cuando esté en casa, ésa misma imagen no es la que va en el README, debo modificar los bordes y colocarla en el repo Media-kit. Hoy hago eso.

**Comment by Rart3001** [comment]
Gracias @jonathanborges3d

**Comment by Rart3001** [comment]
@arnaldos @jonathanborges3d  por favor que ha pasado con nuestro logo, ya nos dieron un ultimátum: "buenos dias, los 2 equipos sin logo, yayo team y disruptors no saldrán en la nueva versión de la web page sino lo entregan en 48 hs. (en el media kit)"

**Comment by jonathanborges3d** [comment]
@Rart3001 Ya está en el README. https://github.com/Fermat-ORG/fermat/pull/5869/commits/9a9f46c2215bd754e6675ba53c171eb7c3b46a51. Para que salga en el Readme debe estar en el media-kit.

**Comment by Rart3001** [comment]
@jonathanborges3d y eso indica que esta también en el media kit como lo están pidiendo?

**Comment by jonathanborges3d** [comment]
Aquí estan los que ya tienen logos: https://github.com/Fermat-ORG/media-kit/tree/master/Logotype/FermatTeams

**Comment by jonathanborges3d** [comment]
Los que faltan serán que no me han notificado que tienen el logo listo para hacerle la versión 3D. Yo debo esperar por la versión final aprobada.

**Comment by Rart3001** [comment]
@jonathanborges3d  Muchas gracias y quien te tiene que notificar?

**Comment by jonathanborges3d** [comment]
Acá están los otros: https://github.com/Fermat-ORG/media-kit/tree/master/MediaKit/Logotype/Fermat%20Teams

Los diseñadores, cuando terminan el logo me mencionan y me llegan las notificaciones del caso, así ya veo que están listos e intervengo la versión final.

**Comment by Rart3001** [comment]
@jonathanborges3d  Ok, bueno este caso lo podemos dar por cerrado entonces
