### ISSUE TITLE
Create a wallpaper for disruptors team 

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#696]
The  team logo defined in the issue #181

Wallpaper 
sizes 1366x768

Files logo in this link 

https://github.com/Fermat-ORG/fermat-graphic-design/tree/95fb4bcd79e986d3889fc6b7f2f7a8ada2bfa0ad/2D%20Design/bitDubai/Logotypes%20Teams%20bitDubai/Logo_disruptors_team/logo%20disruptors

**Comment by JefersonBorgesS** [comment]
![fondo disruptors 1](https://cloud.githubusercontent.com/assets/17457984/13765244/a489b2ba-ea29-11e5-92f2-892918821c0d.jpg)

![fondo disruptors 2](https://cloud.githubusercontent.com/assets/17457984/13765245/a9455674-ea29-11e5-947a-8edaf44d9881.jpg)

![fondo disruptors 3](https://cloud.githubusercontent.com/assets/17457984/13765248/aead9720-ea29-11e5-9930-4a3ffcfac616.jpg)

![fondo disruptors 4](https://cloud.githubusercontent.com/assets/17457984/13765251/b2903e10-ea29-11e5-8203-029ce2d7c9fa.jpg)

**Comment by Rart3001** [comment]
@jayborges  muy bueno,  Listo ya lo estoy usando y muchas gracias :+1:

**Comment by arnaldos** [comment]
@jayborges Muy bueno !! cierro el caso!!!  asegúrate de subir los archivos al repo plz
