### ISSUE TITLE
Explorar posibilidades de graficar la relación de la palabra "creación" y "bitcoin"

### ISSUE THREAD

**Issue by jonathanborges3d** [bitDubai/fermat-graphic-design#70]
Revisando la historia del nacimiento del proyecto me llamó mucho la atención la relación de ambas palabras en el idioma árabe con sólo añadir un punto por lo que se me ocurrieron algunas cosas:

1) Crear un modelo de bitcoin con el logo de Bitdubai en relieve parecido a los renders que vimos en la reunión de hoy.

2) Realizar una animación dónde se explique a los que no conocemos la escritura de ése idioma cómo se relacionan ambas palabras y por qué Dubai está relacionada con Bitcoin

3) Crear un logotipo animado de Bitdubai para iniciar y cerrar los videos que explican cómo funciona la plataforma Fermat.

Me gustaría saber qué opinan al respecto @Luis-Fernando-Molina @m471c4 @arnaldos

**Comment by Luis-Fernando-Molina** [comment]
1) :+1:   Crea un caso para esto y empecemos a discutir los detalles ahí.

2) No estoy muy seguro de esta, pero si creas un Issue, discutimos mas lo que tenés en mente.

3) :+1:  lo único que el logotipo debiera ser de Fermat. bitDubai es la empresa que empuja el proyecto Fermat, pero Fermat será un proyecto Open Source. Creá un Issue y vemos los detalles.
