### ISSUE TITLE
Create Logo for P2P Tickets / Events App

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#703]
| Business model | Actors involved | Description | Example |
| :-: | :-: | :-: | :-: |
| No information yet | No information yet | No information yet | evenpro, tuticket.com |

**Comment by lauraemilia** [comment]
PROPOSAL 1
![logo-events](https://cloud.githubusercontent.com/assets/19143629/15524701/78a7e84a-21ee-11e6-8425-32c80884e41b.jpg)
PROPOSAL 2
![2](https://cloud.githubusercontent.com/assets/19143629/15524709/84f61d6a-21ee-11e6-9663-c9849810e029.jpg)
PROPOSAL 3
![3](https://cloud.githubusercontent.com/assets/19143629/15524716/94f030d4-21ee-11e6-8bb9-cde21853131c.jpg)

**Comment by arnaldos** [comment]
@lauraemilia Me gusta la propuesta: pero vamos a realizare unos cambios. 
1. El texto ubicalo debajo del globo.
2. El mundo que sea formado por serpentinas de tickets, como algo que lo envuelva pero que permanezca con la forma de la circunferencia.
3. juega con otra paleta de colores. 

*Genera estos cambios para hoy plz

**Comment by lauraemilia** [comment]
PROPOSAL 1
![01](https://cloud.githubusercontent.com/assets/19143629/15595273/5852a8b0-2387-11e6-899e-2503544e5d98.jpg)
PROPOSAL 2
![02](https://cloud.githubusercontent.com/assets/19143629/15595277/6439b98e-2387-11e6-8b3b-c6a617cf465e.jpg)

**Comment by lauraemilia** [comment]
variable 1
![22](https://cloud.githubusercontent.com/assets/19143629/15659952/d45f908a-269d-11e6-902a-1d35fec8fc22.jpg)
variable 2
![22e](https://cloud.githubusercontent.com/assets/19143629/15659954/de9ad55a-269d-11e6-8956-6bce74305635.jpg)

**Comment by arnaldos** [comment]
@lauraemilia usa 3 cintas y con eso forma la esfera, esta bien que los pongas de manera ramdom pero debe verse prolijo, así como lo presentas se ve algo desordenado. la separación entre ellas debe mantener un espesor acorde a la curva.

**Comment by lauraemilia** [comment]
variable 1
![44](https://cloud.githubusercontent.com/assets/19143629/15728032/efb872de-2823-11e6-935d-b278f6bb4bb9.jpg)
variable 2
![444e](https://cloud.githubusercontent.com/assets/19143629/15728033/efdf007a-2823-11e6-9f84-d02cc6d9a554.jpg)
