### ISSUE TITLE
Create Logos for P2P Transportation Apps

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#704]
| Business model | Actors involved | Description | Example |
| :-: | :-: | :-: | :-: |
| Taxi | Driver - Passenger | A chauffeur offers transportation to a passenger who needs to get somewhere | Uber |
| Sharing vehicles | Lender - Borrower | A person has a vehicle and is willing to share/rent it to another person who needs it for a brief period of time | Spinlister |
| Shipment | Transporter - Leasee | A person needs something taken from one place to another. Another person or company has the required vehicle and can get the stuff delivered. |  |

Reference issue #702

**Comment by arifernandez** [comment]
![turo-01](https://cloud.githubusercontent.com/assets/16305653/13827249/a37b0418-eb8d-11e5-8873-baec11dbda4e.png)
![spinlister-01](https://cloud.githubusercontent.com/assets/16305653/13827250/a3ca773c-eb8d-11e5-9b05-98d60ec68d04.png)

@arnaldos No se si asi estaran bien?

**Comment by arnaldos** [comment]
La descripción estaba mal plateada, la acabo de ajustar, estas empresas que te nombro serian como ejemplo sobre la función que la app va a realizar. disculpa si te confundí.

**Comment by arifernandez** [comment]
![create logos for p2p transportation apps 704-02](https://cloud.githubusercontent.com/assets/16305653/13864586/dfd3d3ee-ec74-11e5-8f5d-fe6ad2a174cb.png)

@arnaldos

**Comment by ivonnesantos** [comment]
@arifernandez Porque hay propuestas que tienen el nombre de la app que funciona como ejemplo?

**Comment by arifernandez** [comment]
@ivonnesantos la primera hilera es para saber de cual app se esta haciendo la propuesta, no se si te refieres a las otras que dicen el nombre, no sabia que no se podia

**Comment by ivonnesantos** [comment]
Yo entendi que esos iconos son solo una referencia para que sepas que va a hacer la subapp de fermat. Si es de la manera como yo lo entendi entonces no puedes poner el nombre. @arifernandez

**Comment by ivonnesantos** [comment]
Yo entendi que esos iconos son solo una referencia para que sepas que va a hacer la subapp de fermat. Si es de la manera como yo lo entendi entonces no puedes poner el nombre. @arifernandez

**Comment by arifernandez** [comment]
Disculpa, no sabia que no debian llevar nombre @ivonnesantos

**Comment by ivonnesantos** [comment]
@arifernandez tambien me gustaria que respetaras cierto espacio entre el borde del recuadro y el contenido interno se ve todo como muy pegado y se ve desprolijo. En el material design se habla de este tipo de detalles

**Comment by arnaldos** [comment]
@arifernandez @ivonnesantos Les aclaro, debemos hacer un logo que identifique cada el modelo de negocios principal de cada categoria, mas alla de un icono es un logo seria la identidad de taxi fermat por decir. hacemos el logo y luego se lleva a icono tipo ( instagram, evernote, wunderlist, ebay, ) cada una de estas maracas son un modelo de negocios existentes, ahora en la categoría transportations estan estos modelos de negocios: Taxi, Sharing vehicles, Shipment. como dejo en la descripción de arriba. las marcas que dejo son ejemplos de compañias que existe en el mercado pero ellos al final se quedan con un porcentaje, con la versión P2P se quiere eliminar a la empresa de intermediario y evitar el cobro que se le hacen a los usuarios.

**Comment by arifernandez** [comment]
Propuesta 1

![create-logos-for-p2p-transportation-apps-704-1](https://cloud.githubusercontent.com/assets/16305653/13976317/efba57f4-f090-11e5-9ddf-a3eb9e152f12.png)
![create-logos-for-p2p-transportation-apps-704-1 1](https://cloud.githubusercontent.com/assets/16305653/13976316/efb22872-f090-11e5-8573-d4cf97a34e3e.png)

Propuesta 2

![create-logos-for-p2p-transportation-apps-704-2](https://cloud.githubusercontent.com/assets/16305653/13976319/efc5051e-f090-11e5-9f84-0151e1e06bf2.png)
![create-logos-for-p2p-transportation-apps-704-2 1](https://cloud.githubusercontent.com/assets/16305653/13976318/efbf9782-f090-11e5-8ba0-4ce21fbd8918.png)

Propuesta 3

![create-logos-for-p2p-transportation-apps-704-3](https://cloud.githubusercontent.com/assets/16305653/13976314/efa6d490-f090-11e5-9362-89bce3d0d00e.png)
![create-logos-for-p2p-transportation-apps-704-3 1](https://cloud.githubusercontent.com/assets/16305653/13976320/efd6acba-f090-11e5-8b88-755fa4f9816b.png)

Mockup

![create-logos-for-p2p-transportation-apps-704-muckup](https://cloud.githubusercontent.com/assets/16305653/13976315/efabf7f4-f090-11e5-8267-aa56ffff9f96.png)

@arnaldos

**Comment by ivonnesantos** [comment]
Tienen elementos muy pequeños que se pierden, si vas a hacer algo simple debe ser muy pulcro, consistente y original lo que propones es muy simple y se parece mucho a lo se ve en internet crea otras propuestas tomando en consideración estas observaciones @arifernandez  

ejemplo
http://cdn9.staztic.com/app/i/5565/5565236/uryde-taxi-booking-app-1-63666-l-140x140.png
Es simple y pulcro los trazos del mismo grosor todo muy bien acabado, originalidad tiene varios elementos comunes integrados entre si creando una composición; crea un concepto original que difícilmente se puede encontrar repetido

**Comment by arnaldos** [comment]
@arifernandez  plz enfocate en esto estamos atrazados con este logo lo necesitamos con urgencia.

Has un logo que defina transportations necesito eso hoy

**Comment by isahq23** [comment]
@ivonnesantos @arnaldos 

Aquí están unas propuestas a ver si damos mejor con la idea. Me tomé la libertad de escoger un nombre al azar para la app, pero por supuesto, es completamente modificable.

![transport_p2p_muestra1](https://cloud.githubusercontent.com/assets/15214774/14505569/81730904-0183-11e6-9bf2-68271ef7f014.jpg)

**Comment by ivonnesantos** [comment]
@isahq23 en mi opinión debemos partir de las dos primeras propuestas porque son mas utilizables como iconografia puedes complementar el icono de ubicación con otro elemento me gusta la combinación de naranja y gris. Tambien me gusto el color azul de la propuesta 3

**Comment by arnaldos** [comment]
totalmente de acuerdo con @ivonnesantos

**Comment by isahq23** [comment]
@ivonnesantos la opción de la carretera o calle tuve que descartarla, porque encerrada en un círculo parecía una pelota o en su defecto brillo del ícono haciendo ver en total como un globo de fiesta.

La primera opción que logré fue un volante y la segunda, un taxi bastante sencillo.

![transport_p2p_muestra2](https://cloud.githubusercontent.com/assets/15214774/14515444/fcc328b0-01c3-11e6-89c0-ccc8dcadb44f.jpg)

**Comment by arnaldos** [comment]
@isahq23 usa la versión 1 plantea el icono de esta forma de base. que te muestro seguro la imagen que te muestro debe estar pixelada porque la use como referencia de un screenshoot.  prueba colores amarillo y negro para hacer énfasis en que es de taxi .... solo para probar, porque los colores están buenos me gustan

![taxi](https://cloud.githubusercontent.com/assets/13594347/14575547/46fa79ec-032c-11e6-928b-ee48f7d90141.png)

**Comment by isahq23** [comment]
@arnaldos @ivonnesantos 

No quise descartar el del mini taxi, así que aquí propongo variaciones con el naranja y el negro+amarillo de ambos.

![transport_p2p_m3](https://cloud.githubusercontent.com/assets/15214774/14577185/6c78064a-033a-11e6-817f-7e6766104abe.jpg)

**Comment by arnaldos** [comment]
prueba la versión negro del volante sin costura y agrandalo un poco

**Comment by isahq23** [comment]
@arnaldos  así?

![transport_p2p_m4](https://cloud.githubusercontent.com/assets/15214774/14651252/f364dbc8-0638-11e6-96b9-833084e880e7.jpg)

**Comment by isahq23** [comment]
@arnaldos aquí está sobre la base que me diste 

![transport_p2p_m4](https://cloud.githubusercontent.com/assets/15214774/14651915/c184244e-063b-11e6-9e4c-003d1e8ab1ee.jpg)

**Comment by arnaldos** [comment]
subelo :+1:

**Comment by ivonnesantos** [comment]
@mawisk 
crea una propuesta para este caso  pero no seria un icono como se venía planteando  sino un logotipo y despues que tengas el logo se hace el icono en base al logo; el nombre de la aplicación es "TAXI" por lo momentos

**Comment by mawisk** [comment]
![taxi logo propuesta-07](https://cloud.githubusercontent.com/assets/19206540/15278196/e6f872ea-1ade-11e6-88f9-e1e16a4493f3.jpg)

Aqui esta una propuesta para TAXI.

Logo e Icono 

@ivonnesantos

**Comment by gabymado** [comment]
Me gustan los de fondo gris oscuro! Hay alguna forma que podríamos agregar "p2p"? Para que quede p2p Taxi

**Comment by ivonnesantos** [comment]
@mawisk hagamos otra propuestas con el P2P pero adicional porque es para probar y vas a trabajar sobre la propuesta con el fondo gris

**Comment by mawisk** [comment]
![taxi logo-09](https://cloud.githubusercontent.com/assets/19206540/15335494/688bac6a-1c3c-11e6-9cf9-9f6838e346bf.jpg)
![taxi logo-10](https://cloud.githubusercontent.com/assets/19206540/15335495/6894c336-1c3c-11e6-9eee-40ae8218e29a.jpg)
![taxi logo-12](https://cloud.githubusercontent.com/assets/19206540/15335496/6896c6a4-1c3c-11e6-836a-fa843512cb63.jpg)

**Comment by ivonnesantos** [comment]
@mawisk me gusta el ultimo pasame el editable de todos

**Comment by gabymado** [comment]
Me gustan @mawisk @ivonnesantos pero mejor dejemos el de ayer, sin p2p. El nombre de la app sería Taxi p2p (o p2p Taxi) pero que logo quede limpio nomás. Lo mismo para el ícono. Lo siguiente sería empezar con las imágenes para todas las redes sociales, con los tamaños correspondientes. Fíjense aquí creo que están actualizados al 2016: http://makeawebsitehub.com/social-media-image-sizes-cheat-sheet/

**Comment by mawisk** [comment]
![sin titulo-1](https://cloud.githubusercontent.com/assets/19206540/15339073/76c3ca6e-1c4c-11e6-83f1-7ec7fe196417.jpg)
![sin titulo-2](https://cloud.githubusercontent.com/assets/19206540/15339074/76c40434-1c4c-11e6-97aa-fc12936e8db4.jpg)

Propuesta de fondos para logo en redes sociales.
la propuesta 1 es una textura de asfalto familiarizada con taxi.
@ivonnesantos

**Comment by gabymado** [comment]
Me gusta más la primera. Ojo con los tamaños para las imagenes de perfil que suelen ser cuadradas. Fíjense el link que les dejé más arriba. @mawisk @ivonnesantos

**Comment by mawisk** [comment]
si, @gabymado  en ese caso es el banner de facebook. fijandome en las medidas que mandaste.

**Comment by gabymado** [comment]
@mawisk Con @ivonnesantos habíamos hablado que las portadas estarían basadas en el banner de la webpage, pero sin el logo al medio, para no ser repetitivos.

**Comment by ivonnesantos** [comment]
@mawisk esta seria la foto cuadrada de perfil porque la de portada primero debemos terminar el banner y luego hacer las portadas otra cosa chicos tengo que abrir un caso aparte para esto y discutirlo porque este caso es solo para el icono ya lo abro

**Comment by mawisk** [comment]
Presentación de icono en pantalla.

![ea0feab4-12fd-11e6-9d1f-f8c35af2026f2](https://cloud.githubusercontent.com/assets/19206540/15376272/b6d05b28-1d1d-11e6-986f-781eb9c9acbf.jpg)

@ivonnesantos

**Comment by ivonnesantos** [comment]
Si se ve mejor sin fondo

**Comment by arnaldos** [comment]
si usaremos ese :+1:

**Comment by arnaldos** [comment]
@mawisk  sube los archivos al repo

**Comment by ivonnesantos** [comment]
@mawisk para este caso se va crear dos aplicaciones separadas en driver y passager por tanto vamos a necesitar que hagas dos variaciones de iconos uno para passager y uno para driver deben ser iguales pero con esa variante.

Entonces en este caso queda
logo para taxi (listo)
icono driver (2 propuestas para el viernes en la tarde)
icono passager (2 propuestas para el viernes en la tarde)

**Comment by mawisk** [comment]
Propuesta para iconos de passenger y driver

![iconos passenger y driver-02](https://cloud.githubusercontent.com/assets/19206540/15787515/b7a970d6-298c-11e6-9bc3-328c38259927.jpg)

@ivonnesantos

**Comment by ivonnesantos** [comment]
Por ahi va la cosa montalo en el mockup a a ver si se pierde

**Comment by mawisk** [comment]
Presentación

![ea0feab4-12fd-11e6-9d1f-f8c35af2026f2](https://cloud.githubusercontent.com/assets/19206540/15787859/63792248-298e-11e6-9bad-ba3d74e8b16d.jpg)

@ivonnesantos

**Comment by mawisk** [comment]
se ven bien, no se pierden @ivonnesantos

**Comment by ivonnesantos** [comment]
Aprobado!

**Comment by arnaldos** [comment]
el icono que diferencia a los actores es muy pequeño, cuando se vea en una pantalla real, se reducira aun mas replantea los tamaños

**Comment by mawisk** [comment]
Tamaños replanteados

![passenger grande](https://cloud.githubusercontent.com/assets/19206540/15833685/a8dae906-2bf1-11e6-8649-1088e50c0b1c.jpg)

@ivonnesantos @arnaldos
