### ISSUE TITLE
Create Logo for P2P Lodging App

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#705]
| Business model | Actors involved | Description | Example |
| :-: | :-: | :-: | :-: |
| Home owner | Host - Guest | A person offers a property as a temporary accomodation to a person who is looking for a place to stay to vacation, travel or work | Airbnb, FlipKey, HomeAway |

Reference issue #702

**Comment by lauraemilia** [comment]
@arnaldos  
![Uploading 01.jpg…]()
![Uploading 02.jpg…]()
![Uploading 03.jpg…]()
 Muy bien, en el primer logo quise transmitir el alojamiento a travez de curvas, que a su vez simulan techos (cabañas, posadas, hoteles etc.) incluido el ícono de la señal ( líneas con el punto en el centro). El  segundo logo es la campana de un hotel con su timbre en la parte superior ymostrando nuevamente el símbolo de la señal. Explicando que por medio de la internet, la conexión, la transmisión podemos adquirir reservaciones en cualquier lugar de nuestro agrado. Y por último en el tercer logo propongo  que podemos realizar viajes a cualquier parte del mundo con el nombre de Lodging app.

**Comment by lauraemilia** [comment]
![01](https://cloud.githubusercontent.com/assets/19143629/15063637/ae3ff6ec-1315-11e6-9212-52a82ab4e716.jpg)
![02](https://cloud.githubusercontent.com/assets/19143629/15063638/ae4760f8-1315-11e6-9fe0-20ac8e48358d.jpg)
![03](https://cloud.githubusercontent.com/assets/19143629/15063639/ae75d97e-1315-11e6-84ad-bf1c05932b77.jpg)

**Comment by arnaldos** [comment]
@lauraemilia conceptualmente me gusta lo de las cabañas, posadas, hoteles.  pero recuerda que la identidad de la app la vamos a llevar al formato de un icono. te dejo imagenes de muestra de lo que hemos trabajado. para que tomes como ejemplo. genera otras propuestas patiendo del concepto de las cabañas, hotel etc. 

![a](https://cloud.githubusercontent.com/assets/13594347/15063912/1784f218-1318-11e6-8e85-9d2d35bc1dd3.jpg)

**Comment by lauraemilia** [comment]
![1](https://cloud.githubusercontent.com/assets/19143629/15168014/514bca34-16f7-11e6-9ceb-58b72aba6914.jpg)
![2](https://cloud.githubusercontent.com/assets/19143629/15168015/51516b2e-16f7-11e6-869a-1c1adca6aa41.jpg)
![3](https://cloud.githubusercontent.com/assets/19143629/15168016/515923aa-16f7-11e6-9ec7-a4affbd22428.jpg)
![4](https://cloud.githubusercontent.com/assets/19143629/15168017/515d452a-16f7-11e6-8e88-118ac4e4376f.jpg)
![5](https://cloud.githubusercontent.com/assets/19143629/15168018/516617c2-16f7-11e6-8854-6b9a0cb8dba8.jpg)
![6](https://cloud.githubusercontent.com/assets/19143629/15168019/51744540-16f7-11e6-8966-f67d6587b658.jpg)
![7](https://cloud.githubusercontent.com/assets/19143629/15168020/5179d62c-16f7-11e6-8cac-fba60731f538.jpg)

**Comment by lauraemilia** [comment]
PROPUESTA 1
![01](https://cloud.githubusercontent.com/assets/19143629/15200778/a23ed028-17b3-11e6-8a12-4a78f0a396b7.jpg)

PROPUESTA 2
![02](https://cloud.githubusercontent.com/assets/19143629/15200780/ac4cf20c-17b3-11e6-9892-20e7ca7c018b.jpg)

PROPUESTA 3
![03](https://cloud.githubusercontent.com/assets/19143629/15200782/b49b5e76-17b3-11e6-8f7d-cdf52348e427.jpg)

**Comment by arnaldos** [comment]
@lauraemilia trabajemos con la propuesta 1. 
- La parte superior has que no sea tan alta reduce un poco. 
- La linea que hace de base, separala en el centro, las puntas que llegan a los extremos mas cortos.

**Comment by lauraemilia** [comment]
Muy bien! entendido.

**Comment by lauraemilia** [comment]
Corrección de logo 01 
![001](https://cloud.githubusercontent.com/assets/19143629/15201758/206e621a-17be-11e6-82f6-0acaa45649e2.jpg)

**Comment by arnaldos** [comment]
- Las lineas que forman las torres; deja solo 3 y engrosalas para que no se pierdan en la reducción. 
- El ojo del tag map que sea redondo fíjate esta como ovalado
- Usa esta paleta de colores
  ![lodgin](https://cloud.githubusercontent.com/assets/13594347/15202044/8d873b4a-17c0-11e6-9b52-785c8780ba88.jpg)
- El color 1 para el fondo el 2 para el cuero del edificio 3 para el contorno del edificio el 4 paa el ojo del tagmap
- Las lineas de base, en la parte de inferior rectas.
- La forma del contenedor del icono no tan cuadrada. puedes ser como la de la bitcoin wallet
  te dejo el ejemplo

![bit coin wallet-12](https://cloud.githubusercontent.com/assets/13594347/15202164/ac274b2a-17c1-11e6-807f-7c2e1173a052.jpg)

**Comment by lauraemilia** [comment]
Correccion 2 icono para Lodging App

![logo-f](https://cloud.githubusercontent.com/assets/19143629/15233269/2c65278a-1871-11e6-91e2-8c0fdac56be9.jpg)

**Comment by lauraemilia** [comment]
Correccion 3 logo logging app

![logo-final](https://cloud.githubusercontent.com/assets/19143629/15235996/214f7972-188a-11e6-8ecc-ffa057def61b.jpg)

**Comment by lauraemilia** [comment]
Corrección 3
![logo-final](https://cloud.githubusercontent.com/assets/19143629/15306381/e861cd6a-1b93-11e6-9439-af429fdae8fd.jpg)

**Comment by lauraemilia** [comment]
PROPUESTAS ACCOMMODATION
![1](https://cloud.githubusercontent.com/assets/19143629/15379280/72706f6e-1d35-11e6-9fb8-67c6c018c36e.jpg)
![2](https://cloud.githubusercontent.com/assets/19143629/15379281/72738ce4-1d35-11e6-9f53-526531d988dc.jpg)

**Comment by lauraemilia** [comment]
Proposal 1
![01](https://cloud.githubusercontent.com/assets/19143629/15379950/91a22f0c-1d3b-11e6-8bf2-261d8514e4ae.jpg)
Proposal 2
![02](https://cloud.githubusercontent.com/assets/19143629/15379956/99282a42-1d3b-11e6-92b7-32ea2dd0dcde.jpg)
Proposal 3
![03](https://cloud.githubusercontent.com/assets/19143629/15379964/a199df18-1d3b-11e6-9930-e53a4dd3cde8.jpg)
Proposal 4
![04](https://cloud.githubusercontent.com/assets/19143629/15379976/abbaaa04-1d3b-11e6-86bd-0da89c63755e.jpg)
Proposal 5
![05](https://cloud.githubusercontent.com/assets/19143629/15379978/b442198c-1d3b-11e6-9a5c-68ec7ef68815.jpg)

**Comment by arnaldos** [comment]
we work with proposal  4

**Comment by lauraemilia** [comment]
Proposal number 4 variables.

![sin-titulo-1](https://cloud.githubusercontent.com/assets/19143629/15444605/6695c94a-1ebc-11e6-97ef-5bf2c0ad97ce.jpg)

**Comment by lauraemilia** [comment]
Variable

![final](https://cloud.githubusercontent.com/assets/19143629/15444643/c2ffa3f4-1ebc-11e6-991b-597064814036.jpg)
