### ISSUE TITLE
Create Logos for P2P Marketplace Apps

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#706]
| Business model | Actors involved | Description | Example |
| :-: | :-: | :-: | :-: |
| Digital files or media | Seller - Buyer | A person wants to sell a digital file/media and publishes it in a portal. Another person is looking for a product, finds it and buys it online, without any shipment needed. | Envato |
| Tangible objects | Seller - Buyer | A person wants to sell a tangible object and publishes it in a portal. Another person is looking for a product, finds it and buys it online. The product need to be delivered. | E-bay, Amazon |

Reference issue #702

**Comment by Joseangel2v** [comment]
@arnaldos Que tal los bocetos como vamos?

**Comment by emmysm** [comment]
Yo unificaría la 3era y última propuesta y partiría de ahí para hacer otra serie. Cuidado con los vectores, hay varias esquinas que vi desalineadas :smile:  @Joseangel2v

**Comment by Joseangel2v** [comment]
Jaja si debo mejorar eso, me suele pasar. pero como son bocetos, mientra van escogiendo se van perfeccionando, pero gracias por el consejo @emmysm

**Comment by arnaldos** [comment]
@Joseangel2v la ultima propuesta puede andar para uno de los modelos de negocios, hazle efecto gráfico de la segunda imagen, enumera las versiones plz es mas fácil identificarlas. Ten en cuenta que son varios modelos de negocios por categoría, en este caso son dos modelos: Digital files or media y Tangible objects. por lo que vamos a trabajar dos logos.

**Comment by Joseangel2v** [comment]
@arnaldos Ok. trabajare en eso, no habia entendido bien que eran dos diseños de logos diferentes. pense que era un logo para una app de marketplace. Pero tratare de mostrar los bocetos lo antes posible.

**Comment by Joseangel2v** [comment]
![fc1](https://cloud.githubusercontent.com/assets/17457499/14093403/eef74aae-f54d-11e5-8999-1a98372e3e30.png)
DesignMarketplaceApps_Tangible objects_01

**Comment by Joseangel2v** [comment]
![fc2](https://cloud.githubusercontent.com/assets/17457499/14093440/358d716e-f54e-11e5-90bc-44cc3ba88f7f.png)
DesignMarketplaceApps_Tangible objects_02

**Comment by Joseangel2v** [comment]
![fc3](https://cloud.githubusercontent.com/assets/17457499/14093443/3d84829a-f54e-11e5-979d-b42079f20d19.png)
DesignMarketplaceApps_Tangible objects_03

**Comment by Joseangel2v** [comment]
![fc4](https://cloud.githubusercontent.com/assets/17457499/14093446/43bb5ecc-f54e-11e5-9987-3a3feab6a684.png)
DesignMarketplaceApps_Tangible objects_04

**Comment by Joseangel2v** [comment]
![fc5](https://cloud.githubusercontent.com/assets/17457499/14093800/d4a9ff72-f550-11e5-87b4-4c68c05b539b.png)

DesignMarketplaceApps_Tangible objects_05

**Comment by Joseangel2v** [comment]
![fc6](https://cloud.githubusercontent.com/assets/17457499/14093455/51f6cff8-f54e-11e5-906f-cbf70c9304c9.png)
DesignMarketplaceApps_Tangible objects_06

**Comment by Joseangel2v** [comment]
![fc7](https://cloud.githubusercontent.com/assets/17457499/14093459/587ce3b2-f54e-11e5-8659-bf712095fce8.png)
DesignMarketplaceApps_Tangible objects_07

**Comment by Joseangel2v** [comment]
![fc8](https://cloud.githubusercontent.com/assets/17457499/14093471/627c61d0-f54e-11e5-8edc-c1dcd4b7517a.png)
DesignMarketplaceApps_Tangible objects_08

**Comment by Joseangel2v** [comment]
![fc9](https://cloud.githubusercontent.com/assets/17457499/14093479/6d922032-f54e-11e5-893c-a368896c0212.png)
DesignMarketplaceApps_Tangible objects_09

**Comment by Joseangel2v** [comment]
Create Logos for P2P Marketplace Apps Digital files or media

**Comment by Joseangel2v** [comment]
![fd1](https://cloud.githubusercontent.com/assets/17457499/14093503/98d88394-f54e-11e5-9b56-9d517d6ed00d.png)
DesignMarketplaceApps_Digital files or media_10

**Comment by Joseangel2v** [comment]
![fd2](https://cloud.githubusercontent.com/assets/17457499/14093508/a7d0cdf2-f54e-11e5-8209-ab168464b550.png)
DesignMarketplaceApps_Digital files or media_11

**Comment by Joseangel2v** [comment]
![fd3](https://cloud.githubusercontent.com/assets/17457499/14093516/b46a8da0-f54e-11e5-8551-ca45d7da2ccc.png)
DesignMarketplaceApps_Digital files or media_12

**Comment by Joseangel2v** [comment]
![fd4](https://cloud.githubusercontent.com/assets/17457499/14093523/bfa80418-f54e-11e5-89d8-88bc4894a6aa.png)
DesignMarketplaceApps_Digital files or media_13

**Comment by Joseangel2v** [comment]
![fd6](https://cloud.githubusercontent.com/assets/17457499/14093539/d2fab90c-f54e-11e5-80b7-8bb449429ee9.png)
DesignMarketplaceApps_Digital files or media_15

**Comment by Joseangel2v** [comment]
![fd9](https://cloud.githubusercontent.com/assets/17457499/14093557/ee1ccc52-f54e-11e5-879c-795d908b9914.png)
DesignMarketplaceApps_Digital files or media_18

**Comment by Joseangel2v** [comment]
![opcional](https://cloud.githubusercontent.com/assets/17457499/14093773/aa61f54e-f550-11e5-86b8-921db990bce1.png)
DesignMarketplaceApps_Tangible objects_19

**Comment by Joseangel2v** [comment]
@arnaldos Como vamos?

**Comment by Joseangel2v** [comment]
![app digital 2](https://cloud.githubusercontent.com/assets/17457499/14159317/89d955fc-f6d5-11e5-98d9-a68021a20167.png)
DesignMarketplaceApps_Tangible objects_22

**Comment by Joseangel2v** [comment]
![app real](https://cloud.githubusercontent.com/assets/17457499/14159325/9a82b286-f6d5-11e5-8e04-6d2fc2bb7cee.png)
DesignMarketplaceApps_Tangible objects_23

**Comment by Joseangel2v** [comment]
![app digital](https://cloud.githubusercontent.com/assets/17457499/14159340/ae14e62a-f6d5-11e5-82f8-96a507ae6a19.png)
DesignMarketplaceApps_Digital files or media_24

**Comment by Joseangel2v** [comment]
![app real 2](https://cloud.githubusercontent.com/assets/17457499/14159354/ba84a44a-f6d5-11e5-9b95-8a76904a1d0f.png)
DesignMarketplaceApps_Digital files or media_25

**Comment by arnaldos** [comment]
@Joseangel2v 

la version 9 me gusta para el digital files colocalo en fondo blanco, si quieres usar gris usa tonos mas suaves en este caso usa un circulo en ves de cuadrado para la base del icono. 

crea otra version partiendo de la nube usando la misma sintesis y colores de la version 9. mejor dicho prueba hacer una nube con la misma solucion grafica de la 9

para cosas tangibles usa la version 8 como base (el del triangulo invertido) aumenta el tamaño de los elementos verdes y achica los grises de una forma que trates de formar una "M" por cerramiento y a la ves tome forma de una bolsa o paquete. puedes hacer una version con estos colores y otra con los colores de de la version 13

**Comment by Joseangel2v** [comment]
![1 fd](https://cloud.githubusercontent.com/assets/17457499/14300264/2aff8c44-fb59-11e5-94ae-d06a2caf533c.png)
MKPDigital_1

**Comment by Joseangel2v** [comment]
![11 tf](https://cloud.githubusercontent.com/assets/17457499/14300934/76285d46-fb5d-11e5-9364-9877e5bfa320.png)
MKPTangible_10

**Comment by Joseangel2v** [comment]
@arnaldos

**Comment by arnaldos** [comment]
@Joseangel2v disculpa si no me dia a entender cuando me referia a la nube me gustaba la idea pero resuelta de la manera en que est el otro icono. fijate te dejo una imagen de lo que me referia, para los proximos post colocale la version en el titulo asi es mas facil de identificar. has dos versiones realizando un mash entre los logo tal como te muestro en la imagen

![untitled-2](https://cloud.githubusercontent.com/assets/13594347/14334822/cf2a7f00-fc20-11e5-9c18-49cb99ae39a4.jpg)

**Comment by arnaldos** [comment]
@Joseangel2v para market place usemos este logo.

![market-place](https://cloud.githubusercontent.com/assets/13594347/14390533/6b40cd7a-fd81-11e5-91ec-dfc84ee9b0d7.png)

plz genera las medidas necesarias para el launcher 

48 × 48 (mdpi)
72 × 72 (hdpi)
96 × 96 (xhdpi)
144 × 144 (xxhdpi)
192 × 192 (xxxhdpi)
512 × 512 (Google Play store)

La carpeta la ubicas en 2D design / Fermat app / sub apps / P2P apps

Para el otro logo si terminarlo de definirlo.

**Comment by Joseangel2v** [comment]
![192x192-01-01](https://cloud.githubusercontent.com/assets/17457499/14466410/85aa9782-00a0-11e6-9c70-2bafd92c2baf.png)

**Comment by arnaldos** [comment]
@Joseangel2v plz genera los tamaños usando el logo que te pase, el otro termina de definirlo según los comentarios que te he hecho

**Comment by Joseangel2v** [comment]
@arnaldos Listos arnaldo los archivos ya fueron generados y subidos. Aqui dejo algunas propuestas de el otro icono, me incline por el material design. para hacerlas.

**Comment by Joseangel2v** [comment]
Propuesta 1
![p2p 1](https://cloud.githubusercontent.com/assets/17457499/14526919/5ba40ccc-0210-11e6-9e3c-fb16e7fa08ca.png)

**Comment by Joseangel2v** [comment]
Propuesta 2
![p2p 2](https://cloud.githubusercontent.com/assets/17457499/14526932/6c04827c-0210-11e6-8400-592e8e0704a6.png)

**Comment by Joseangel2v** [comment]
Propuesta 3
![p2p 3](https://cloud.githubusercontent.com/assets/17457499/14526945/7d095c5a-0210-11e6-9a30-2b68a309ab54.png)

**Comment by Joseangel2v** [comment]
Propuesta 4
![p2p 4](https://cloud.githubusercontent.com/assets/17457499/14566509/a89718dc-02f9-11e6-8c38-67e51a814522.png)

**Comment by Joseangel2v** [comment]
Propuesta 5
![p2p 5](https://cloud.githubusercontent.com/assets/17457499/14566533/be49e542-02f9-11e6-93c5-fcbccaecc43e.png)

**Comment by Joseangel2v** [comment]
Propuesta 6
![p2p 6](https://cloud.githubusercontent.com/assets/17457499/14566549/cb65be36-02f9-11e6-9d52-470a29491859.png)

**Comment by Joseangel2v** [comment]
Propuesta 7
![p2p 7](https://cloud.githubusercontent.com/assets/17457499/14566562/dab35286-02f9-11e6-9cd4-ecbea46e43d4.png)

**Comment by Joseangel2v** [comment]
@arnaldos @emmysm

**Comment by Joseangel2v** [comment]
@arnaldos Como vamos??

**Comment by emmysm** [comment]
More proposals @Joseangel2v

**Comment by Joseangel2v** [comment]
Propuesta 8
![mkt2](https://cloud.githubusercontent.com/assets/17457499/14782201/90b9f710-0ab1-11e6-9dac-a3c1826780fe.png)

**Comment by Joseangel2v** [comment]
Propuesta 9
![mkt3](https://cloud.githubusercontent.com/assets/17457499/14782292/44c8af62-0ab2-11e6-857e-5cbf17f49a36.png)

**Comment by Joseangel2v** [comment]
Propuesta 10
![mkt1](https://cloud.githubusercontent.com/assets/17457499/14782367/add3b01a-0ab2-11e6-9ef0-756d63c6b574.png)

**Comment by Joseangel2v** [comment]
Propuesta 11
![mkt5](https://cloud.githubusercontent.com/assets/17457499/14782422/1081f7da-0ab3-11e6-9e28-9eac2ebf76be.png)

**Comment by Joseangel2v** [comment]
Propuesta 12
![mkt4](https://cloud.githubusercontent.com/assets/17457499/14782514/9eb5cfb8-0ab3-11e6-8f28-43e7019f87a1.png)

**Comment by emmysm** [comment]
Más propuestas, @Joseangel2v

**Comment by arnaldos** [comment]
@emmysm explícale a joseangel porque mas propuestas.

**Comment by emmysm** [comment]
Ya lo hice @arnaldos  :)

**Comment by arnaldos** [comment]
:smile:

**Comment by Joseangel2v** [comment]
Propuesta 13
![mkp1](https://cloud.githubusercontent.com/assets/17457499/14919808/506d31fe-0df4-11e6-8ab3-7fc1bb890fd9.png)

**Comment by Joseangel2v** [comment]
Propuesta 14
![mkp2](https://cloud.githubusercontent.com/assets/17457499/14919825/5fe80ffa-0df4-11e6-8707-e3f4bc7cd515.png)

**Comment by Joseangel2v** [comment]
Propuesta 15
![mkp9](https://cloud.githubusercontent.com/assets/17457499/14929910/fabb26e0-0e29-11e6-931a-b3269a25bf0b.png)

**Comment by Joseangel2v** [comment]
Propuesta 16
![mkp4](https://cloud.githubusercontent.com/assets/17457499/14929204/2aea5754-0e26-11e6-91eb-29e7f01cb9eb.png)

**Comment by Joseangel2v** [comment]
Propuesta 17
![mkp8](https://cloud.githubusercontent.com/assets/17457499/14929355/dfd0db98-0e26-11e6-9708-324d3f2f56d4.png)

**Comment by Joseangel2v** [comment]
Propuesta 18
![mkp5](https://cloud.githubusercontent.com/assets/17457499/14929395/02c3962c-0e27-11e6-96a8-e7b84ab8b589.png)

**Comment by Joseangel2v** [comment]
Propuesta 19
![mkp7](https://cloud.githubusercontent.com/assets/17457499/14929408/0fa48a90-0e27-11e6-9097-f03449fe651e.png)

**Comment by Joseangel2v** [comment]
Propuesta 20
![mkp6](https://cloud.githubusercontent.com/assets/17457499/14929451/3403cef0-0e27-11e6-8119-1801360ef3a9.png)

**Comment by Joseangel2v** [comment]
Propuesta 21
![mkp3](https://cloud.githubusercontent.com/assets/17457499/14929953/2dbc7076-0e2a-11e6-87d6-65c1904f138f.png)

**Comment by Joseangel2v** [comment]
Propuesta 22
![1dr](https://cloud.githubusercontent.com/assets/17457499/14966417/00e8b51a-107c-11e6-99d5-643feddcbe56.png)

**Comment by Joseangel2v** [comment]
Propuesta 23
![2dr](https://cloud.githubusercontent.com/assets/17457499/14966422/10165d62-107c-11e6-8f04-aa51f1df7eca.png)

**Comment by Joseangel2v** [comment]
Propuesta 24
![3dr](https://cloud.githubusercontent.com/assets/17457499/14966432/244e42d6-107c-11e6-9a3a-1fee2e3b64fa.png)

**Comment by Joseangel2v** [comment]
Propuesta 25
![4dr](https://cloud.githubusercontent.com/assets/17457499/14966440/2dce0b2a-107c-11e6-87ef-605a1d67a5b8.png)

**Comment by Joseangel2v** [comment]
![5dr](https://cloud.githubusercontent.com/assets/17457499/14966451/41722a44-107c-11e6-83cc-e77a5cb81297.png)

**Comment by Joseangel2v** [comment]
@arnaldos @emmysm Me gustan mucho las dos ultimas.
