### ISSUE TITLE
Create logo for P2P Dating App

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#707]
| Business model | Actors involved | Description | Example |
| :-: | :-: | :-: | :-: |
| Meet People (Lifestyle, interests, Geolocalization) | Person - Person | A person is looking to connect to other people to have virtual or personal encounters | Tinder |
| Meet People (Anonymous affairs) | Person - Person | A person is looking to connect to other people to have virtual or personal encounters | Ashley Madison |

Reference issue #702

**Comment by JefersonBorgesS** [comment]
Propuesta 1
De las correcciones arrancare con las demas propuestas para tener una guia.

![dating app-01](https://cloud.githubusercontent.com/assets/17457984/14123783/feeb2416-f5cb-11e5-9bd5-fb68f8ea8b36.jpg)

**Comment by arnaldos** [comment]
replantea el logo !! plz genera 3 propuestas para tener varias opciones para debatir

**Comment by JefersonBorgesS** [comment]
Propuesta 2
![123232](https://cloud.githubusercontent.com/assets/17457984/14164685/5aacb972-f6cb-11e5-814e-fa5aa25d8a39.png)

Propuesta 3
![12323123222](https://cloud.githubusercontent.com/assets/17457984/14164672/37b239d8-f6cb-11e5-87ff-d833dcb71e36.png)

**Comment by arnaldos** [comment]
@jayborges  las 2 y la 3 son las mismas, planteame 3 nuevas propuestas distintas plz

**Comment by JefersonBorgesS** [comment]
Propuestas nuevas 
-1-
![123422](https://cloud.githubusercontent.com/assets/17457984/14265587/31bfd7d2-fa8c-11e5-82a1-840df874e848.png)

-2-
![122343422](https://cloud.githubusercontent.com/assets/17457984/14265588/31d39204-fa8c-11e5-97ed-e3798e213f99.png)

**Comment by JefersonBorgesS** [comment]
-3-
![4356png](https://cloud.githubusercontent.com/assets/17457984/14284844/13e6ff88-fb13-11e5-824a-d435f5cae523.png)

**Comment by arnaldos** [comment]
@jayborges podemos usar el concepto de la propuesta 2 usando los colores rosa y azul de la propuesta de arriba y dejando únicamente la forma del corazón

**Comment by JefersonBorgesS** [comment]
Las correciones que me indicaste y algunas propuestas mas @arnaldos 
-1-
![123212333332](https://cloud.githubusercontent.com/assets/17457984/14288050/fdbe7388-fb1e-11e5-9f86-0ba94a1e3661.png)

-2- con gradiente
![qw2227](https://cloud.githubusercontent.com/assets/17457984/14288048/fdb6d722-fb1e-11e5-91a0-42111665a2d2.png)

-3- Solo el corazon
![135897](https://cloud.githubusercontent.com/assets/17457984/14288049/fdb9eb6a-fb1e-11e5-9cc9-1764f75d3ca0.png)

-4- Solo el corazon con trazo
![1243222](https://cloud.githubusercontent.com/assets/17457984/14288051/fdc1d29e-fb1e-11e5-93bb-93cbd7da4a41.png)

**Comment by arnaldos** [comment]
@jayborges estandariza el espacio que se forma eentre cada elemento, la pieza rozada el brazo por asi llamarlo debe continuar rozado, lo mismo para el azul

**Comment by JefersonBorgesS** [comment]
Corecciones @arnaldos 

1°
![41222](https://cloud.githubusercontent.com/assets/17457984/14319715/0d6362cc-fbdc-11e5-94f4-307a1eb3cdb8.png)

2°
![412232](https://cloud.githubusercontent.com/assets/17457984/14319748/344c1eb0-fbdc-11e5-8669-f5beb77fc3ba.png)

3°
![4122232](https://cloud.githubusercontent.com/assets/17457984/14319757/3e09ddd4-fbdc-11e5-9e23-1152fddeb4f2.png)

**Comment by arnaldos** [comment]
version 3 :+1:

**Comment by karentvillegas** [comment]
@arnaldos @jhonmarquez92 Nuevas propuestas de logo para P2P Datting App
1
![propuesta1](https://cloud.githubusercontent.com/assets/19273211/15334275/4b6eba46-1c37-11e6-9a9f-33eb3c80a1ee.png)
2
![propuesta2](https://cloud.githubusercontent.com/assets/19273211/15334287/59b73e48-1c37-11e6-84c6-3f39a8db5990.png)
3
![propuesta3](https://cloud.githubusercontent.com/assets/19273211/15334295/62384b84-1c37-11e6-9d35-4e7acbe63e77.png)
4
![propuesta4](https://cloud.githubusercontent.com/assets/19273211/15334300/6b8084e0-1c37-11e6-9205-4720827a4f7c.png)
5
![propuesta5](https://cloud.githubusercontent.com/assets/19273211/15334317/784c98e4-1c37-11e6-9863-6bc442ee9a36.png)
6
![propuesta6](https://cloud.githubusercontent.com/assets/19273211/15334324/8175fa6e-1c37-11e6-9060-ffc3f14efad9.png)

**Comment by proseuz** [comment]
@karentvillegas  me gustaría ver propuestas distintas a la de corazones

**Comment by proseuz** [comment]
@isahq23  esto te puede interesar. Ayudanos con este caso please

**Comment by isahq23** [comment]
@jhonmarquez92 la propuesta 3 de @karentvillegas me encanta. 
Y está bien, veré qué puedo proponer n.n

**Comment by proseuz** [comment]
@karentvillegas  presenta variaciones de la propuesta 3 please

**Comment by karentvillegas** [comment]
@arnaldos @isahq23 @jhonmarquez92 Nuevas Propuestas (sin corazones)
7
![propuesta7](https://cloud.githubusercontent.com/assets/19273211/15416431/383d8698-1e15-11e6-9ad3-42bc99b74bf0.png)
8Tomando el concepto de la frase "media naranja" referido a la mitad de una pareja ideal.
![propuesta8](https://cloud.githubusercontent.com/assets/19273211/15416433/41c73a92-1e15-11e6-819c-ad96d3e6f13a.png)
9
![propuesta9](https://cloud.githubusercontent.com/assets/19273211/15416508/ff469950-1e15-11e6-87d2-6e38d42de882.png)
10
![propuesta10](https://cloud.githubusercontent.com/assets/19273211/15416512/0ca64352-1e16-11e6-9356-2cdc610e57ba.png)

**Comment by karentvillegas** [comment]
@arnaldos @isahq23  @jhonmarquez92 Variaciones de la propuesta 3
1
![propuesta3_1](https://cloud.githubusercontent.com/assets/19273211/15416533/57015356-1e16-11e6-97a8-be5b9d2c7d17.png)
2
![propuesta3_2](https://cloud.githubusercontent.com/assets/19273211/15416537/5de4f34e-1e16-11e6-8ffe-17dec7d787e7.png)
3
![propuesta3_3](https://cloud.githubusercontent.com/assets/19273211/15416538/6325f362-1e16-11e6-9742-fa98fd9d5360.png)
4
![propuesta3_4](https://cloud.githubusercontent.com/assets/19273211/15416540/6788a242-1e16-11e6-86b2-5ba397e3c1e5.png)
5
![propuesta3_5](https://cloud.githubusercontent.com/assets/19273211/15416551/706fa298-1e16-11e6-949a-7670efe855bb.png)

**Comment by proseuz** [comment]
wow me gusta la de la media naranja, me parece que es muy pregnante. qué opinan @arnaldos @isahq23 @emmysm ?  creo que con algunos ajustes funciona

**Comment by isahq23** [comment]
@karentvillegas @jhonmarquez92 me gusta la naranja sí, pero me preocupa un poco que el corazón se pierda como ícono, porque es muy pequeño, tal vez si le quitas otro gajo a la naranja tenga un poco más de espacio. Con respecto a las variaciones de la propuesta 3, me gustan los colores y la proporción de su versión n°4 ..... intenta colocar esos mismos colores en la naranja a ver cómo quedan.
