### ISSUE TITLE
SUPER ISSUE Create Logos for P2P Services / Work Apps

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#708]
Create Logos for P2P Services / Long term job search #737
Create Logo for P2P Services / Freelance jobs / Gigs #738
Create Logo for P2P Services / Household services #739
Create Logo for P2P Services / Connections  #740

| Business model | Actors involved | Description | Example |
| :-: | :-: | :-: | :-: |
| Long term job search | Employer - Job Seeker | A company or employer is looking to hire a person for a specific position and creates a job search. The other person is looking for a job opportunity, completes a profile and applies to the searched that are most appealing. | CompuTrabajo, Monster, Indeed |
| Freelance jobs / Gigs | Contractor - Freelancer/Professional | A company or independent worker is looking for a person to do a specific task without any contract or long term relationship. | Freelancer, Upwork |
| Household services | Contractor - Service Provider | A home owner is looking for a person to take care of a manual task. A service provider is looking to find more opportunities. | Angie's list |
| Connection | Professional - Professional | Professionals want to connect and create a work network that can help them learn, get jobs or recruit others. | LinkedIn |

Reference issue #702

**Comment by proseuz** [comment]
Work app

![work app logo](https://cloud.githubusercontent.com/assets/17308060/13895184/7fa60306-ed42-11e5-9313-9aa4788e6758.png)

Job search

![job search](https://cloud.githubusercontent.com/assets/17308060/13895437/54ad2ad2-ed45-11e5-9e85-789664fd230f.png)

Freelance 

![freelance](https://cloud.githubusercontent.com/assets/17308060/13895391/fe9d9fa0-ed44-11e5-8986-a8b94162c172.png)

Household services

![household services](https://cloud.githubusercontent.com/assets/17308060/13895205/b2aab21a-ed42-11e5-9e7e-912307effd29.png)

Connection

![connection](https://cloud.githubusercontent.com/assets/17308060/13895208/c48e7e58-ed42-11e5-918c-2ae1e311a104.png)

Previsualización

![work app2](https://cloud.githubusercontent.com/assets/17308060/13895329/59d37544-ed44-11e5-8c4e-ece35a80d555.png)
![work app](https://cloud.githubusercontent.com/assets/17308060/13895330/59e1e4ee-ed44-11e5-8ce1-fb642d92865e.png)
![work app1](https://cloud.githubusercontent.com/assets/17308060/13895331/59f449cc-ed44-11e5-9c9a-92ed1e0f0ec2.png)

@arnaldos @emmysm @Luis-Fernando-Molina

**Comment by Luis-Fernando-Molina** [comment]
El logo tiene que permitir adivinar de que se trata la aplicacion, en estos casos eso no sucede

**Comment by arnaldos** [comment]
los nombres de estas apps no van a ser los mismos de las empresas que existen actualmente, por ejemplo "tinder" debería ser "Dating" los nombres deben ser según la actividad que realice esta app. por otro lado revisa bien los modelos de negocio que se plantean en este caso. por ejemplo tinder, airbnb no estan dentro de esta categoría.

**Comment by proseuz** [comment]
@arnaldos Los nombres que están en las pantallas no los tomé como referencias, solos lo dejé allí como estaban y les monte los logos que hice para previsualizar **(solo los logos)**. Sí es necesario te pido por favor un archivo editable de las pantallas para ponerles el nombre de cada uno.

**Comment by proseuz** [comment]
@arnaldos  @Luis-Fernando-Molina 
![work app2](https://cloud.githubusercontent.com/assets/17308060/13974475/27549e6c-f07e-11e5-867d-b70035f4f59c.png)

**Comment by emmysm** [comment]
Genera más propuestas, @jhonmarquez92 , porfa.

**Comment by proseuz** [comment]
![work app 4](https://cloud.githubusercontent.com/assets/17308060/14035920/29d9e2a8-f206-11e5-839f-7eef5af06b24.png)

![work app 5](https://cloud.githubusercontent.com/assets/17308060/14036138/1af1d0fa-f208-11e5-97cb-e37f1cb4fbc9.png)
El colibrí por su característico rápido aleteo representa muy bien este modelo de negocios sin contratos a largo plazo, además simboliza la libertad que permite trabajar de manera freelance.
.
![work app 6](https://cloud.githubusercontent.com/assets/17308060/14036154/4fc3778e-f208-11e5-8cb2-8841c1c138b0.png)
![work app 7](https://cloud.githubusercontent.com/assets/17308060/14036255/886939f6-f209-11e5-846c-1bb588fa93dc.png)

Previsualización en pantallas 
![pantalla1](https://cloud.githubusercontent.com/assets/17308060/14036202/d288aa86-f208-11e5-961e-ab8a3dd204e9.png)
![pantalla2](https://cloud.githubusercontent.com/assets/17308060/14036203/d2dc88ae-f208-11e5-902e-d7bb69b51974.png)

@arnaldos @Luis-Fernando-Molina @emmysm

**Comment by Luis-Fernando-Molina** [comment]
Hola, por favor un caso por cada cosa, sino se vuelve  muy complejo opinar.

**Comment by Luis-Fernando-Molina** [comment]
pueden dejar este como super issue y continuar cada uno individualmente
