### ISSUE TITLE
Create logo for P2P Marketing App

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#709]
| Business model | Actors involved | Description | Example |
| :-: | :-: | :-: | :-: |
| No information yet | No information yet | No information yet | No information yet |

**Comment by isahq23** [comment]
@arnaldos after some research I found that the best samples of P2P companies were this ones: Uber, airbnd, amazon, etc. There is no samples for a marketing company or tool that works with the P2P rules. So, I decided to design something that evolves marketing and "apps", even so, something that could look good inside a circle or a square. 

Here they are. 
Please tell me what you think about the colours, shapes, cause you may know better what we are looking for.

![logo_marketing_p2p_issue706_proposals](https://cloud.githubusercontent.com/assets/15214774/14190567/536f5c5e-f75d-11e5-8ebf-05d3ca7354c2.png)

**Comment by arnaldos** [comment]
new proposal plz

**Comment by m471c4** [comment]
@arnaldos 3 proposals for this logo:

![marketingp2p](https://cloud.githubusercontent.com/assets/13468350/15368930/4f3459e8-1cfe-11e6-9240-9a7fcb0e1520.png)
