### ISSUE TITLE
Crear un modelo 3D de una moneda con el logo de Bitdubai

### ISSUE THREAD

**Issue by jonathanborges3d** [bitDubai/fermat-graphic-design#71]
Viene del #70

Existen dos vías para lograr esto según mi experiencia:

1) Crear una imagen plana de la moneda en cuestión y usarla como mapa de relieve, así el modelo tridimensional sería solo un cilindro muy delgado con la textura aplicada. Ésta opción mejoraría el tiempo de render y el rendimiento de la escena en general pero sacrificaría la calidad de la imagen, no se vería realista.

o,

2) Usar el logo vectorizado para crear la malla completa, el relieve sería poligonal (modelado) y el modelo más detallado. Ésta opción mejoraría la calidad general de la imagen por ser un modelo de alta resolución pero tardaría un poco mas en el render y en el modelado.

Además se debe definir si las imágenes finales serán de una, varias monedas o ambas opciones.

@Luis-Fernando-Molina @arnaldos @m471c4

**Comment by Luis-Fernando-Molina** [comment]
@jonathanborges3d de acuerdo, por política simpre vamos a hacer lo de mayor calidad, osea que va la opción 2. Podés ir mostrando que tenés en mente desde que tengas algo como para ir viendo, así podemos opinar.

**Comment by jonathanborges3d** [comment]
Bien, antes de modelar me gustaría que evaluaran esta imagen y me dieran sus impresiones al respecto, Muy probablemente será modificada pero ahorrará tiempo tener el concepto claro antes de hacer la malla.

![bitcoin_bitdubai_concept](https://cloud.githubusercontent.com/assets/13649739/9187173/2f5da4fc-3f97-11e5-8376-c98a38cc7594.JPG)

Esta es una de las caras, no sé si sería conveniente colocar el isologo de fermat (una vez finalizado) en la cara posterior conservando el relieve de los bordes o el símbolo de la "B" de bitcoin, aunque ya leí en otro issue que fermat no solo funcionará para bitcoin sinó para otras crypto currencies.

@Luis-Fernando-Molina @m471c4 @arnaldos 

Editado:

Me animé a hacer una prueba, tal vez sea mejor partir desde un concepto 3D en concreto.

![render_test_bitcoin](https://cloud.githubusercontent.com/assets/13649739/9189534/a4ee4b10-3fb3-11e5-9dda-4a79b50d5b39.jpg)

**Comment by Luis-Fernando-Molina** [comment]
@jonathanborges3d como en el caso de estos rendering vamos a tener muchas imagenes, no tenemos la restricción del logo que es uno y punto. Con esto quiero decir que pudieramos asociar tanto bitDubai como Fermat en algunas de estas imagenes con bitcoin sin la restriccion anterior.

**Comment by jonathanborges3d** [comment]
Ok, entonces haré otros conceptos se las monedas y los publico.

**Comment by jonathanborges3d** [comment]
Dos conceptos que se me ocurren:

![bitcoin_bitdubai_fermat_concept](https://cloud.githubusercontent.com/assets/13649739/9209685/a91c19e0-4041-11e5-84f1-e0cf165321f5.JPG)

![bitcoin_electronic_concept](https://cloud.githubusercontent.com/assets/13649739/9209721/d257018a-4041-11e5-9b88-2526fdc0defd.JPG)

Espero sus comentarios.

@Luis-Fernando-Molina @m471c4 @arnaldos

**Comment by m471c4** [comment]
Buenos días @jonathanborges3d,

A mi parecer las ideas están buenísimas, en líneas generales solo tendría cuidado con el texto de los bordes, en caso de que resulte muy pequeño y no logre apreciarse bien. Podrías combinar ese círculo de líneas que usaste en la primera prueba que hiciste con estas dos, a ver qué tal se ve.

Con respecto a la plateada con dorado, no se si la palabra árabe pueda molestar sobre el símbolo de bitcoin. Sería buenísimo verlas renderizadas ya que el relieve ayuda mucho.

Saludos :)

**Comment by Luis-Fernando-Molina** [comment]
@jonathanborges3d te digo mis observaciones:

a) fijate si la B que usaste es la misma que se ve (en tipo de letra) por todos lados, ya que la gente de la industria la reconoce.  Ademas puede que deba estar un poco inclinada, no recuerdo.

b) la palabra en arabe sonbre la B no queda muy bien.

Seguí posteando y vamos viendo. saludos.

**Comment by jonathanborges3d** [comment]
Modifiqué la letra B y le di una inclinación similar al logo de Bitcoin con presencia en la web.También aumenté el tamaño de letra para los nombres y les di espacio, para no recargar la imagen.

![bitcoin_electronic_concept_2](https://cloud.githubusercontent.com/assets/13649739/9259840/e82e9670-41cd-11e5-993e-8528884c0632.JPG)

Un render para probar el mapa de relieve y previsualizar entes del modelado.

![bitcoin_2](https://cloud.githubusercontent.com/assets/13649739/9259878/320cd9be-41ce-11e5-80f3-884ffc0ea8ca.jpg)

**Comment by Luis-Fernando-Molina** [comment]
@jonathanborges3d bien, va tomando forma.

Fermat y bitDubai está en bajo relieve o alto?

Seguí puliendolo por favor. 

Podes probar poner el logo de Fermat del tamaño de la B y la B dentro de la billetera grande (la verde en el logo)

**Comment by jonathanborges3d** [comment]
Ok @Luis-Fernando-Molina,

bitDubai y Fermat estan en bajo relieve, la imagen confunde por la iluminación.

Hice la prueba con el logo de fermat como propones, Esta me gusta más que las otras, tal vez sea ése logo el que deba ir, dado que es el producto final, el que conocerá todo el mundo.

![bitcoin_3](https://cloud.githubusercontent.com/assets/13649739/9265030/275fb68e-41f7-11e5-8e17-6e72c2dfe422.jpg)

![bitcoin_4](https://cloud.githubusercontent.com/assets/13649739/9265205/f67828dc-41f9-11e5-8602-a8f732c3adf5.jpg)

![bitcoin_5](https://cloud.githubusercontent.com/assets/13649739/9265210/0af3c988-41fa-11e5-9a54-1fdf659963f9.jpg)

![bitcoin_6](https://cloud.githubusercontent.com/assets/13649739/9265225/35eb3176-41fa-11e5-8733-9ce10b569410.jpg)

![bitcoin_7](https://cloud.githubusercontent.com/assets/13649739/9265370/f4955b00-41fb-11e5-93cc-cc0482d8cd76.jpg)

Creo que si se le hacen algunos ajustes más ya pudiese ser modelada por completo. 

A ver que opinan @m471c4 y @arnaldos también.

**Comment by arnaldos** [comment]
En ambas versiones me gustan los bajos relieve que le das a las monedas. Solo dos cosas la "B" del icono de bitcoin creo que no debería estar presente ya que esto hace énfasis un solo tipo de divisas. O al menos que se vaya a modelar una moneda distinta para cada divisa con la que se trabaje, que no seria mala idea mostrar los tipos de divisas que se pueden manejar en fermat. la otra cosa es que apenas definamos el logo final de fermat lo subo para que puedas sustituirlo en el modelado. SE que esta pendiente espero mañana poder finiquitar el caso.

**Comment by jonathanborges3d** [comment]
@arnaldos Puede ser que más adelante, cuando se incorporen otras divisas se hagan nuevos modelos con sus respectivos símbolos, por lo pronto creo que la comunidad en general reconocería la relación entre la plataforma Fermat y las crypto currencies empleando directamente la B en las monedas. No sé si voy en la dirección correcta @Luis-Fernando-Molina, he leído el Readme del proyecto y eso me dio una mejor idea de lo que es Fermat.

Me pareció que si hacía un render como este tal vez tendríamos una mejor visión de lo que sería el modelo instanciado  en esa cantidad de objetos en una sola escena, un poco lo que se ve en las búsquedas de imágenes por la web. No es definitivo, aún queda por incorporar el logo final de Fermat que está en desarrollo.

![bitcoin_8](https://cloud.githubusercontent.com/assets/13649739/9267213/0a173bb0-4215-11e5-8aa0-98003cfe0eea.JPG)

**Comment by leonacostaok** [comment]
A mi me parece que así como hay monedas, no sólo de diferentes países, sino de diferentes valores. puede haber monedas de diferentes crypto currencies, o sea, poner la B de btc no lo ata a sólo a ella. 
@Luis-Fernando-Molina no te copa la idea de poner por ejemplo, el chain bridge, el burj khalifa, o una foto tuya (jaja) como en muchas de las monedas tradicionales?
Que una moneda tenga una billetera adentro no me cierra.. O sea, entiendo que es el símbolo del fermat, pero capaz habría que cambiar el símbolo del fermat entonces jajaja, lo estamos atando sólo a billeteras así también.. Digo, una vez que la gente asocia una imagen con una marca, es como bastante fuerte (Tengo un libro de marketing de servicios que capaz te puede interesar, "Venda lo Invisible").

**Comment by Luis-Fernando-Molina** [comment]
@jonathanborges3d me gusta mucho como evolucionó lo que venías haciendo. Creo que vamos a andar bien si seguimos explorando estas direcciones.

Es correcto que podemos tener diferentes monedas para diferentes crypto currencies. De hecho debieran ser de diferentes tamaños con diferentes diseños. Algo similar a lo que ocurre con las monedas de cualquier país. Las mas caras, son mas sofisticadas, con mas de un material , mas gruesas y mas grandes. Mientras menos valor tiene, mas chicas y mas simples. Sigamos con esa idea que la gente lo va a entender.

Siendo Bitcoin la mas exitosa de las moendas ( http://coinmarketcap.com/ ) deberia se la mas sofisticada y de dos materiales a la vez. Algunas sugerencias mias:

1) La parte de adentro deberia estar mas hundida que el borde. Es decir, el grosor de la moneda en el centro debiera ser mas fino que el borde.

2) El centro debiera ser de oro, y el borde de plata.

3) El logo de Femat sin la proyeccion de sombra como en la imagen final se ve muy bien. @arnaldos te puede dar la versión final, aunque no se si llega a impactar porque los cambios son mínimos, igual se debería usar la version final.

4) El calado de los circuitos hacerlo un toque mas sutil a ver como queda.

5) En la imagen con muchas monedas, asegurate que no quede ninguna en el aire o en una posición fisicamente imposible porque le resta realismo.

6) Quitá la mención a bitDubai. Vamos a manejar por separado bitDubai de Fermat por ahora.

7) La palabra Fermat quizas pueda tener un calado mas sutil.

@lnacosta said:

> no te copa la idea de poner por ejemplo, el chain bridge, el burj khalifa, o una foto tuya (jaja) como en muchas de las monedas tradicionales?

No es mala idea luego tener monedas que signifiquen la asociacion de Fermat con diferentes fiat currencies o monedas locales.

De alguna manera el mensaje a transmitir si uno viera esa serie de imágenes sería que fermat es el eslabón entre las crypto currencies y las fiat currencies, el cual no está mal como mensaje hacia la crypto industry.

Respecto a poner la cara mia, no creo que por ahora sume mucho  :-(

**Comment by Luis-Fernando-Molina** [comment]
@jonathanborges3d estás subiendo los fuentes al repositorio?

**Comment by Luis-Fernando-Molina** [comment]
![bitcoin](https://cloud.githubusercontent.com/assets/9479367/9280583/9162c49a-42bf-11e5-8dee-518592a9641b.png)

**Comment by Luis-Fernando-Molina** [comment]
@jonathanborges3d Ahi encontre una moneda bitcoin , que me imagino que tomaste como base o quizas alguna otra parecida. Me gustaría que la nuestra sea mejor que esta   :smile:

**Comment by jonathanborges3d** [comment]
@Luis-Fernando-Molina Si, tomé referencias de algunas parecidas.

Todavía no subo nada al repo, lo haré esta tarde, modelé el logo actual de fermat e hice un nuevo render, ahora si todo el relieve es poligonal.

![bitcoin_9](https://cloud.githubusercontent.com/assets/13649739/9281818/b41f071a-4291-11e5-9409-6ba75be0bc64.jpg)

![bitcoin_10](https://cloud.githubusercontent.com/assets/13649739/9281820/b43f9ae8-4291-11e5-99fc-41c69e9a32d4.jpg)

Queda bien el relieve de circuito electrónico? o debería hacerlo más intrincado como en la imágen que posteaste?

**Comment by Luis-Fernando-Molina** [comment]
@jonathanborges3d 

a) El logo de Fermat queda muy bueno. Quizas esta un poco grande.

b) El borde dejo de parecer el de una moneda, no se bien que cambiaste.

c) el circuito no se le nota el relieve. Fijate si la escla del circuito es la apropiada, quizas debas achicarlo un poco. El dibujo tampoco parece inegrarse mucho al logo, en realidad no parece integrarse en nada. 

d) La palabra fermat repetida quizas no sea lo mas apropiado ahí. @m471c4 @arnaldos quizás puedan opinar sobre eso.

**Comment by Luis-Fernando-Molina** [comment]
El borde debiea tener este tipo de calado:

http://rinaz.net/images/2010/06/coin3.jpg

**Comment by Luis-Fernando-Molina** [comment]
Pudieramos poner el año: http://www.collinson.biz/badges_for_sale/usbp90coin.jpg     2015

**Comment by jonathanborges3d** [comment]
@Luis-Fernando-Molina , Si, el borde está un poco más gruego que en las versiones anteriores, lo corregiré.

En cuanto al circuito, tal vez deba hacer uno similar al de la moneda refrencial que colocaste, sin terminaciones en forma de anillo, solo pistas que vayan en forma circular con alguna desviación en líneas rectas paralelas. Haré una nueva versión.

**Comment by Luis-Fernando-Molina** [comment]
@jonathanborges3d quedaría bien simular las soldaduras. Redibujar el circuito me parece bien, para que tenga una buena integración con el logo (el logo pudiera hacer las veces de un chip, con muchas terminaciones). Esta claro que para el lado del a B el circuito debiera ser otro.

**Comment by jonathanborges3d** [comment]
@Luis-Fernando-Molina Diseñé un circuito que se integrara un poco más al logo de fermat, el concepto es precisamente el que mencionas, como un microchip con sus conexiones, pero pensando en que son varias billeteras les coloqué a cada una una conexión directa. Tal vez puede representar mejor el concepto de Fermat.

![bitcoin_11](https://cloud.githubusercontent.com/assets/13649739/9291058/982b720c-4375-11e5-820a-2e5b203b2399.jpg)

El anillo exterior es una prueba a ver que se puede colocar allí, la fecha es una buena idea pero si es algo más extenso que solo "2015" sería mejor en mi opinión, casi todas las monedas tienen dos años (ejémplo 2014 - 2015)  o una fecha específica ( 15 de Agosto de 2015), lo que abarca un poco más de espacio en el anillo y se ve mejor. 

También le hice el calado del borde exterior como me indicaste. 

![bitcoin_12](https://cloud.githubusercontent.com/assets/13649739/9291059/a141de12-4375-11e5-84ca-a16137b3e275.jpg)

@arnaldos @m471c4 , me gustaría saber sus opiniones chicos.

**Comment by Luis-Fernando-Molina** [comment]
@jonathanborges3d te digo punto por punto:

1) El calado del borde anillo exterior está perfecto

2) El circuito esta mejor ahora pero creo que podemos empujar el concepto un poquito mas. Proba que las líneas no se metan para abajo de las billeteras, que siempre la evadan, salvo en el cosito ese que se usa para cerrar cada billetera. Cada cosito de eso debería tener varias terminaciones en cada uno, de manera similar a como está ahora, con un detalle, las lineas debieran ir hacia el cosito sin llegar de manera oblicua como lo hace en la wallet chiquita del medio. Ponele las soldaduras en el punto donde tocan las lineas con el cosito de la billetera.

3) Las lineas del circuito debiera tener mas relieve. Si es que tienen no se nota.

4) Respecto al año, 2015 está bien que esté solo porque representa el año donde se lanza fermat al público. Podes agregarle 3 estrellitas de cada lado del año como se ve por ahi.

5) Las billeteras no las toqués, están perfectas.

6) Probemos poner la frase "digital money" arriba, el año abajo, y fermat en cada uno de los dos costados. @arnaldos debe darte la tipografía de fermat, con esa misma poné la frase.

7) El aro alrededor me gusta, pero es posible que sea muy ancho, veremos como queda.

**Comment by jonathanborges3d** [comment]
Ok, @Luis-Fernando-Molina, haré una versión mejorada con las correcciones que mencionas.

Esta la hice antes de leer tu comentario. Qué opinas de colocar ese texto?

![bitcoin_13](https://cloud.githubusercontent.com/assets/13649739/9291189/e172ebd8-437b-11e5-956e-389fd0fdb81b.jpg)

**Comment by Luis-Fernando-Molina** [comment]
@jonathanborges3d nop eso está orientado a developers. Coloca la frase que te dije en minusculas, con la letra de fermat please.

**Comment by jonathanborges3d** [comment]
@Luis-Fernando-Molina Corregí el circuito para que coincidiera en la forma adecuada con el cierre de las billeteras, le di un mayor relieve y desvié las pistas que se escondían bajo las wallets.. 

Reduje el anillo exterior para resaltar la parte interna donde está el logo.

También agregué el texto con la tipografía "Myriad Pro" que es la que usó @arnaldos para el logo final de Fermat.

![bitcoin_14](https://cloud.githubusercontent.com/assets/13649739/9291738/f7a7f8a2-439a-11e5-84f6-97de514d637b.jpg)

![bitcoin_15](https://cloud.githubusercontent.com/assets/13649739/9291746/4674327a-439b-11e5-8582-484f18cd9118.jpg)

Algunas variaciones de los materiales:

![bitcoin_16](https://cloud.githubusercontent.com/assets/13649739/9291802/b01e9ac8-439e-11e5-802d-03813639000d.jpg)

![bitcoin_17](https://cloud.githubusercontent.com/assets/13649739/9291804/be299096-439e-11e5-8813-6c6df6a24fdb.jpg)

![bitcoin_18](https://cloud.githubusercontent.com/assets/13649739/9291807/e690658c-439e-11e5-91bc-2fb8aba0a9f6.jpg)

![bitcoin_19](https://cloud.githubusercontent.com/assets/13649739/9291808/ef0be092-439e-11e5-8bef-39fefdadcbce.jpg)

![bitcoin_20](https://cloud.githubusercontent.com/assets/13649739/9291817/445dfed6-439f-11e5-8254-547dda410236.jpg)

En esta particularmente le añadí el color verde de al fondo del centro y plateado al circuito para reforzar la idea de lo digital /electrónico.

![bitcoin_21](https://cloud.githubusercontent.com/assets/13649739/9291836/9660c7c6-43a0-11e5-95d7-918df0a25446.jpg)

![bitcoin_22](https://cloud.githubusercontent.com/assets/13649739/9291843/daadebc0-43a0-11e5-9c6c-97d0cc19e04f.jpg)

**Comment by Luis-Fernando-Molina** [comment]
@jonathanborges3d muy bueno!

1) Hacete por favor que las soldaduras en las terminaciones que enfrentan al coito que cierra las walletes, toquen el cocio, como que están conectadas allí.

2) Digtal money colocalo todo en minúscula

3) Asegurate que la curvatura de la palabra Fermat coincida con la de la moneda. Luce como que no es exactamente la misma.

4) Proba poner todo lo escrito en un tamaño inferior.

5) El logo de Fermat no parece estar centrado en la moneda, sino desplazado hacia la izquierda y quizás hacia abajo.

6) En la primera imagen que posteaste en este issue hay una decoracion en forma de acordeon al rededor del borde exterior que me gustaría probar aquí pero hecha de manera mas sutil:

a) debe tener la altura de la letras (ej 2015) y no la del borde externo. 
b) La longitud de cada diente debe ser menor que la que pusiste en la primera imagen.
c) debe estar presente también en el segundo anillo (arriba del 2015) ,  mirando hacia las letras.

para que esto entre las letras como dice el punto 4 deben ser de un tamaño inferior.

7) Las soldaduras hacelas mas altas y un poquito mas gorditas.

8) Evita las soldaduras que quedaron solas o asiladas de alguna linea. Me imagino que algunas lineas se pueden bifurcar para llenar casi todos los espacios vacíos.

**Comment by jonathanborges3d** [comment]
@Luis-Fernando-Molina Hice un nuevo circuito, al mover el logo de Fermat hubo que modificarlo todo, ésta vez procuré no dejar soldaduras sueltas y colocar las que conectan los cierres de las billeteras pegadas a ellas, se añadió el aro dentado en el anillo exterior y se modificó el texto corrigiendo la posición y escala. También modifiqué la forma y la altura de las soldaduras.

![bitcoin_23](https://cloud.githubusercontent.com/assets/13649739/9337647/61a98214-45aa-11e5-9034-622cc57b3ea0.jpg)

![bitcoin_24](https://cloud.githubusercontent.com/assets/13649739/9337677/96b422b6-45aa-11e5-9d78-31e669a14903.jpg)

Una variante:

![bitcoin_25](https://cloud.githubusercontent.com/assets/13649739/9337693/aefe9676-45aa-11e5-8c61-a39b04eac349.jpg)

![bitcoin_26](https://cloud.githubusercontent.com/assets/13649739/9337709/c4f01bb2-45aa-11e5-89d7-1814cddee5bd.jpg)

**Comment by Luis-Fernando-Molina** [comment]
Me encantó la versión todo en oro. Ya no se me ocurre nada más que pedirte. Te felicito.! 

Dala vuelta y vamos con la otra cara.

**Comment by Luis-Fernando-Molina** [comment]
Estas seguro que todas las soldaduras están levantadas?? Solo veo arriba las que tienen forma de puntito,  las rectangulares no...

**Comment by jonathanborges3d** [comment]
Gracias @Luis-Fernando-Molina , Ya hice otra versión con todas las soldaduras alzadas.

![bitcoin_27](https://cloud.githubusercontent.com/assets/13649739/9340537/08fd3344-45ba-11e5-9fc0-facc5a206a12.jpg)

![bitcoin_28](https://cloud.githubusercontent.com/assets/13649739/9340559/2b422a40-45ba-11e5-8e38-8332bd9d8169.jpg)

Ok, para la otra cara tendremos la B de bitcoin o le haremos otro diseño?

**Comment by Luis-Fernando-Molina** [comment]
Hay una línea que cruza a otra en el cuadrante abajo a la izquierda. Me parece que te quedo de antes.

**Comment by Luis-Fernando-Molina** [comment]
Del otro lado puede ser bastante parecida a la foto que postié.

**Comment by jonathanborges3d** [comment]
Si, ya lo noté, un punto se me escapó y estaba desplazado hacia afuera.

Ok. generaré un circuito par la B y cuando tenga algo concreto lo posteo.

**Comment by jonathanborges3d** [comment]
@Luis-Fernando-Molina Una primera versión de la cara posterior.

![bitcoin_29](https://cloud.githubusercontent.com/assets/13649739/9397559/c72404e8-4767-11e5-98bc-a31e54205872.jpg)

![bitcoin_30](https://cloud.githubusercontent.com/assets/13649739/9397675/e43c16fa-4768-11e5-9aee-cf40e71bc5ce.jpg)

Me gustaría probar el logo de Fermat de ésta forma, que quede en color oscuro, podría hacer mayor contraste con el circuito y se notaría mucho más, como la B. Qué opinan @m471c4 @arnaldos ?

Editado:

Hice una prueba, previa copia del logo original, está respaldado.

![bitcoin_31](https://cloud.githubusercontent.com/assets/13649739/9398888/4a1c69c2-4776-11e5-8113-d74584ef0253.jpg)

![bitcoin_32](https://cloud.githubusercontent.com/assets/13649739/9398895/60592e46-4776-11e5-8b19-029d876f26c3.jpg)

**Comment by jonathanborges3d** [comment]
Instanciada como textura.

![bitcoin_34](https://cloud.githubusercontent.com/assets/13649739/9401363/d65e40ba-4797-11e5-8550-1e4f05efe143.jpg)

![bitcoin_35](https://cloud.githubusercontent.com/assets/13649739/9401390/67f8db48-4798-11e5-8f92-d2b93247e2c9.jpg)

**Comment by arnaldos** [comment]
@jonathanborges3d  estoy subiendo el logo de fermat definitivo al repositorio, para que lo puedas descargar

**Comment by Luis-Fernando-Molina** [comment]
@jonathanborges3d te digo mis observaciones:

1) las líneas del circuito de la B o estan mas altas o son mas gruesas que las del otro lado

2) del lado de la B debiera decir "one bitcoin" en vez de "digital money"

3) Los bordes de la B pudieran ser un toque mas finos

4) El logo de Fermat queda bien tambien solo en lineas, pero en la imagen donde hay muchas monedas se necesita que ya sea el logo de fermat o a B esten rellenas para aumentar los reflejos. Lo que podemos hacer es tener 2 versiones de la moneda de un bitcoin:

a) con la B en wires y Fermat relleno.
b) con la B rellena y Fermat en wire. 

De esta form en la imagen de las monedas estarían mezcladas y síera un toque mas interesante.

5) Respecto a la primera  imagen de las monedas mezcladas, esta muy bien asi, sin comentarios. Respecto a las segunda, trabajá la superficie donde están apoyadas. Para empezar ponele un poquito de reflejo y empezá a probar con que material quedaría mejor.

**Comment by jonathanborges3d** [comment]
@Luis-Fernando-Molina Auí estan las nuevas versiones de la moneda con los cambios recientes:

Anverso 1
![cara_1](https://cloud.githubusercontent.com/assets/13649739/9421897/c8f27fee-4847-11e5-9a28-edeec457bd1a.png)

Anverso 2
![cara_2](https://cloud.githubusercontent.com/assets/13649739/9421941/0ff8fd2c-4849-11e5-8445-932ca2ef4077.png)

Reverso 1
![sello_1](https://cloud.githubusercontent.com/assets/13649739/9421972/362b8f5e-484a-11e5-93c4-8c40612fbb29.png)

Reverso 2
![sello_2](https://cloud.githubusercontent.com/assets/13649739/9422011/72d61018-484b-11e5-9558-0917b00fbdc3.png)

No sé si así te servirán @m471c4 , avísame cualquier cosa.

**Comment by m471c4** [comment]
@jonathanborges3d están perfectas, gracias :+1:

**Comment by Luis-Fernando-Molina** [comment]
@jonathanborges3d La tipografia usada y aprobada en el trabajo de @arnaldos no es la que estás usando.

Fijate en https://github.com/bitDubai/fermat-graphic-design/issues/20 y en particular https://cloud.githubusercontent.com/assets/13594347/9286665/f8d35e9e-42c1-11e5-83e8-df616cb253c6.jpg

Tanto en la palabra fermat, como todos los otros textos en la moneda, debíeras usar ese tipo de letra. (Canaro) 

Ojo con estos detalles.

**Comment by jonathanborges3d** [comment]
@Luis-Fernando-Molina, Estaba usando Myriad Pro, no me percaté que ya estaba aprobada Canaro. 

Con la tipografía correcta:

Anverso 1
![cara_1](https://cloud.githubusercontent.com/assets/13649739/9425501/a07f8242-48dc-11e5-86c1-bafb8f9033de.png)

Anverso 2
![cara_2](https://cloud.githubusercontent.com/assets/13649739/9425537/81be0aa8-48dd-11e5-9636-4882c92cb971.png)

Reverso 1
![sello_1](https://cloud.githubusercontent.com/assets/13649739/9425649/42083b3c-48e1-11e5-8500-84a036d83de9.png)

Reverso 2
![sello_2](https://cloud.githubusercontent.com/assets/13649739/9425666/4a7fbcf8-48e2-11e5-9f9a-7567ec5722ca.png)

**Comment by Luis-Fernando-Molina** [comment]
:+1: 

Cuando subás los fuentes al repositorio, damos por cerrado este caso, y abrite un par mas para discutir la imagen/es de todas las monedas desordenadas y / o apiladas.

**Comment by jonathanborges3d** [comment]
Listo, @Luis-Fernando-Molina , ya subí los archivos al repositorio. https://github.com/jonathanborges3d/fermat-graphic-desing-3D/commit/c36511b54e3d1b467584c51df32c7fcded5f1dad

**Comment by Luis-Fernando-Molina** [comment]
@jonathanborges3d no entiendo bien donde estás subiendo esto, vero que es un repositorio tuyo. Lo que tenes que hacer es un pull request sobre el repositorio de diseño gráfico que ya tenemos. Si no sabés como hacerlo, preguntale a los chicos, Dayana, Arnaldo y si ellos no saben, a Jorge o alguien que te dé las instrucciones por favor.

**Comment by jonathanborges3d** [comment]
@Luis-Fernando-Molina Listo, ya lo subí al repositorio de diseño gráfico actual.

**Comment by Luis-Fernando-Molina** [comment]
:+1:
