### ISSUE TITLE
Create Logo for P2P Lending App

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#710]
| Business model | Actors involved | Description | Example |
| :-: | :-: | :-: | :-: |
| No information yet | No information yet | No information yet | No information yet |

**Comment by ivonnesantos** [comment]
@Manufallen En este caso debes crear un icono generico para una empresa de prestamos este icono va a ir ubicado el desktop de aplicacion. El mismo debe tener una identidad independiente a la indentidad de la aplicacion.

In this case, you must create a generic icon for a business loan this icon will be located the desktop application. It must have an independent identity to the identity of the application.

desktop app
![settings app 6-02](https://cloud.githubusercontent.com/assets/15238660/15061363/ea0feab4-12fd-11e6-9d1f-f8c35af2026f.jpg)

**Comment by Manufallen** [comment]
Trabajo: Minimalist Flat Icons
Tipo de Empresa: Prestamos
Descripción del Trabajo: 
Los tres Iconos, representan el intercambio cíclico, de dinero, representado con el símbolo del $, por ser la moneda global. en todos se ve de alguna manera la visión de la entrega y la devolución del dinero, de manera minimalista y básica.

Tipo de presentacion:
1. Iconos en grande, en distintas shapes y sin shapes.
2. Iconos presentados en un Android Mockup

Encargado por:  @ivonnesantos 
Artwork by: Manuel Milano / [ `@manufallen` ](https://www.behance.net/manufallen)

![icono app prestamo](https://cloud.githubusercontent.com/assets/18602871/15075198/e8704e0a-136c-11e6-989a-b79cb9fe3323.jpg)
![icono app prestamo jpg](https://cloud.githubusercontent.com/assets/18602871/15075199/e90d1bfe-136c-11e6-8b4a-5df9fbf9d7ef.png)

**Comment by ivonnesantos** [comment]
@Manufallen podemos trabajar algo asi pero mas estetico y con una billera o distintas menedas porque no quiero hacer enfasis en tipo de moneda especifica ni dolar ni euro ni bitcoin porque hasta donde se fermat no tiene estas limitantes, tambien este icono lo poodemos trabajar con 2 o 3 colores. Si tienes algo que aclarar @arnaldo seria de ayuda. 
![image](https://cloud.githubusercontent.com/assets/15238660/15075576/d88faa2e-136e-11e6-9174-d811d6908147.png)

**Comment by Manufallen** [comment]
Ok, perfecto, me gustaría que cuando me asignen trabajos, sean lo mas claros posibles, si van a querer algo ya en especifico, por favor enviarlo como lo hacen ahorita, con ejemplos de lo que buscan lograr.

**Comment by ivonnesantos** [comment]
@Manufallen en realidad no tenia una idea especifica el ejemplo lo busque en base a tu propuesta dos pero en lugar de tener los elementos de forma independiente derian formar un solo elemento con una forma, no es que vas a hacer tal cual lo de la foto que te pase vas a hacer algo tuyo pero que tenga esa fluidez

**Comment by Manufallen** [comment]
Aquí esta una versión adaptada a las necesidades ya descritas:
- brindar créditos a las personas a un bajo costo de los intereses
- Es decir tienes que expresar que dan creditos con bajas tasas de interes
- En pocos minutos se me va la luz, asi que les paso la version de prueba (falta corregirle algunos detalles y adaptarle colores
  
  ![icono app prestamo 4](https://cloud.githubusercontent.com/assets/18602871/15078517/9044ca20-1381-11e6-9e4a-acc5a7c3e4b3.png)
  ![icono app prestamo jpg](https://cloud.githubusercontent.com/assets/18602871/15078894/7a1a826a-1383-11e6-8808-028ec26b9074.png)
  )

**Comment by ivonnesantos** [comment]
Tenemos que representar lo de bajos intereses de una forma menos compleja tambien me gustaria trabajar con dos o tres colores pueden ser dos colores fuertes y uno suti o un color muy fuerte en distintas tonalidades tambien me gustaria que las manitos en las munecas tengan un acabado mes prolijo y vamos a plantearlo sobre el recuadro como en la ultima hilera de mockup busca en el repositorio algun otro icono que este en ese tipo de recuadro para que no varíe en pequeños detalles como las esquinas redondeadas y esas cosas. aparte de eso vamos a hacer otra propuesta que se enfoque en una grafica comparitiva y los puntos altos que representan altos intereses los puedes plantear en gris como si quisieras dar a entender que eso no conviene y el punto bajo puede ser en rojo, verde o azul pero que se vea resaltante lo de presmos lo podemos repesentar con unas manitos parecidas a la propuesta 3 que planteaste al inicio

**Comment by arnaldos** [comment]
totalmente de acuerdo con los comentarios de ivonne. por otro lado acoto esto, mas que un icono, seria un logo o identidad para el modelo de negocios. que en nuestro caso se representara en un icono de app.

**Comment by mawisk** [comment]
![logo wallet-06](https://cloud.githubusercontent.com/assets/19206540/15254314/feda5da0-18ff-11e6-9e4b-aba945b0a1a2.jpg)

Propuesta

![mockup 2](https://cloud.githubusercontent.com/assets/19206540/15254426/9549913e-1900-11e6-8a9b-f5ee9c9d70ed.jpg)

@ivonnesantos

**Comment by mawisk** [comment]
![logo wallet 2-08](https://cloud.githubusercontent.com/assets/19206540/15265505/7459b4aa-194f-11e6-90f3-dc55d074b036.jpg)

Correcciónes listas, se busca reflejár de una manera simple el bajo porcentaje.
@ivonnesantos

**Comment by ivonnesantos** [comment]
@mawisk Se ve muy bien lo vamos a presentar con una figura de base y lo vamos a presentar sin fondo con la leve sombra que tienen los iconos de Android a ver como se ve mejor al principio del caso yo puse una captura de pantalla de la app en donde los podemos montar a ver como se ve.

Pero el icono me agrada

**Comment by mawisk** [comment]
![iconos propuestas](https://cloud.githubusercontent.com/assets/19206540/15415246/3b6fc2a4-1e0b-11e6-87a7-63291458ff33.jpg)

tres propuestas de icono
@ivonnesantos

**Comment by mawisk** [comment]
Propuesta 2

![logo moneda-01](https://cloud.githubusercontent.com/assets/19206540/15660323/8d4ab68c-26a4-11e6-8a34-ef92df620b8b.jpg)

@ivonnesantos

**Comment by ivonnesantos** [comment]
@mawisk me gusta esa monedita pero vamos a ubicarles las manitos talves mas simple que tu propuesta anterior, colocale en nombre "Lending app" recuerda que necesitamos imagen de la marca e icono ambos. @arnaldos tienes algo que agregar?

**Comment by arnaldos** [comment]
estoy de acuerdo @ivonnesantos, pero hay que buscar que se aprecie como un logo y luego se represente en icono como una forma mas el aplicar el logo.

**Comment by mawisk** [comment]
Propuesta de logo 

![logo moneda-02](https://cloud.githubusercontent.com/assets/19206540/15682097/da4240e6-2725-11e6-895a-022342216b29.jpg)

@ivonnesantos

**Comment by ivonnesantos** [comment]
@mawisk me gusta por mi parte esta aprobado esperemos a ver que dice @arnaldos

**Comment by ivonnesantos** [comment]
@mawisk crea el icono por favor para verlo

**Comment by mawisk** [comment]
propuesta para icono

![logo moneda-04](https://cloud.githubusercontent.com/assets/19206540/15689696/02f70f16-274a-11e6-97c4-66264e5e355e.jpg)

@ivonnesantos

**Comment by ivonnesantos** [comment]
montalo en el mockups por favor para ver como se aprecia @mawisk

**Comment by arnaldos** [comment]
Listo !!

**Comment by mawisk** [comment]
presentacion en pantalla 

![ea0feab4-12fd-11e6-9d1f-f8c35af2026f](https://cloud.githubusercontent.com/assets/19206540/15690823/28b2c24a-274f-11e6-9d15-4a62f7b2d13b.jpg)

@ivonnesantos

**Comment by ivonnesantos** [comment]
@mawisk Perfecto se ve bien subelo al repositorio de en la misma ruta que vas a subir el de taxi icono y logo yo despues veo como vamos a arreglar eso

**Comment by arnaldos** [comment]
esto ya esta en el repo ??
