### ISSUE TITLE
Create logo for P2P Sharing of Digital Information App

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#711]
| Business model | Actors involved | Description | Example |
| :-: | :-: | :-: | :-: |
| No information yet | No information yet | No information yet | Dropbox, Instagram, Vimeo |

Reference issue #702

**Comment by arismendi227** [comment]
@jhonmarquez92 @arnaldos @emmysm
propuestas 
conceptos: flechas de subir y bajar(compartir información) creando un circulo para estar contenido en algo en este caso el circulo con iconos de compartir y de archivos
1
![1](https://cloud.githubusercontent.com/assets/19276382/15417517/a046afe8-1e20-11e6-92db-98aff5ec8012.png)
2
![2](https://cloud.githubusercontent.com/assets/19276382/15417519/a475e232-1e20-11e6-8e0d-41c8d84839dc.png)
3
![3](https://cloud.githubusercontent.com/assets/19276382/15417521/aa57f96a-1e20-11e6-9ed6-1e7c2dfcb77a.png)
4
![4](https://cloud.githubusercontent.com/assets/19276382/15417533/ca86d0c6-1e20-11e6-8974-8f3ef66ea261.png)
flechas y circulos 
5
![5](https://cloud.githubusercontent.com/assets/19276382/15417564/2b6d4c44-1e21-11e6-92cc-0806577b5882.png)
6
![6](https://cloud.githubusercontent.com/assets/19276382/15417568/3576083e-1e21-11e6-85c6-04d448eeb9d3.png)
7
![7](https://cloud.githubusercontent.com/assets/19276382/15417579/4d85e994-1e21-11e6-805f-61b6e54d7478.png)
concepto: boomerang objeto que va y regresa (dar y recibir información)
8
![8](https://cloud.githubusercontent.com/assets/19276382/15417600/9183d246-1e21-11e6-9404-bb30cab5d017.png)
concepto: dos manos(dar y recibir) compartir informacion
9
![9](https://cloud.githubusercontent.com/assets/19276382/15417615/c13a6ed2-1e21-11e6-87d2-22bb2067d76a.png)
10
![10](https://cloud.githubusercontent.com/assets/19276382/15417625/d87ecc28-1e21-11e6-9670-598bd563bb62.png)
concepto: estar dentro de un circulo social donde se comparte informacion
11
![11](https://cloud.githubusercontent.com/assets/19276382/15417640/0b01f09e-1e22-11e6-876f-54f2326e5884.png)
12
![12](https://cloud.githubusercontent.com/assets/19276382/15417643/1451ad10-1e22-11e6-85ec-70839000538b.png)
13
![13](https://cloud.githubusercontent.com/assets/19276382/15417645/19737fa8-1e22-11e6-9f94-ed1907649f2f.png)

**Comment by proseuz** [comment]
@arismendi227 tienen buen concepto pero deben parecerse más a un logo. explora el elemento que aparece en la propuesta 5,6,7 y crea propuestas nuevas. Qué opinan chicos @arnaldos @emmysm  @m471c4 ?

**Comment by m471c4** [comment]
@jhonmarquez92 @arismendi227 se podría comenzar por sacarlo del recuadro. A mi me gusta el concepto de las propuestas 9 y 10, aunque tal vez lo refinaría más para que se vea más prolijo. Trata también de trabajar con una paleta de dos colores para que no se vea tan plano.

**Comment by arismendi227** [comment]
@jhonmarquez92 @arnaldos @emmysm
sintetizando para acercarme mas a un logo
propuetas

1
![1](https://cloud.githubusercontent.com/assets/19276382/15832955/5217482e-2bee-11e6-9bb0-6a8b2cd79d13.png)

2
![2](https://cloud.githubusercontent.com/assets/19276382/15832960/58c29f3e-2bee-11e6-9774-2c211a7eba50.png)

3
![3](https://cloud.githubusercontent.com/assets/19276382/15832966/61d30cd0-2bee-11e6-974a-ad1381367770.png)

4
![4](https://cloud.githubusercontent.com/assets/19276382/15832982/6ff1881e-2bee-11e6-8267-6ec20b7bef4b.png)

5
![5](https://cloud.githubusercontent.com/assets/19276382/15832996/786c29fe-2bee-11e6-979a-e52cfdd8626f.png)

6
![6](https://cloud.githubusercontent.com/assets/19276382/15833003/7e822e24-2bee-11e6-9dec-f05ef500213d.png)

7
![7](https://cloud.githubusercontent.com/assets/19276382/15833014/86a33f9e-2bee-11e6-8614-7f0afbc6011c.png)

8
![8](https://cloud.githubusercontent.com/assets/19276382/15833029/8bbec26e-2bee-11e6-865d-b422be90a730.png)

**Comment by proseuz** [comment]
Puedes explorar la  propuesta 3 incluyendo tipografía, podría ser con las iniciales de la app. Qué opinas @arnaldos ?

**Comment by arismendi227** [comment]
@jhonmarquez92 @arnaldos 
propuestas

1
![1 1](https://cloud.githubusercontent.com/assets/19276382/16100041/758d8884-3325-11e6-85d8-1cf903fffc51.jpg)

2
![1](https://cloud.githubusercontent.com/assets/19276382/16100046/7a86256c-3325-11e6-89d7-bf438f1834a2.jpg)

3
![3](https://cloud.githubusercontent.com/assets/19276382/16100048/7f4fd890-3325-11e6-97b3-890b1295152d.jpg)

4
![4](https://cloud.githubusercontent.com/assets/19276382/16100051/87240e2e-3325-11e6-8626-8cf05cc3d668.jpg)

5
![5](https://cloud.githubusercontent.com/assets/19276382/16100055/8bd29f76-3325-11e6-933d-0e21072cb58f.jpg)

6
![6](https://cloud.githubusercontent.com/assets/19276382/16100061/928e06ca-3325-11e6-9689-94cd3c9ad624.jpg)

**Comment by proseuz** [comment]
**La propuesta 2**  puede funcionar
Intenta lo siguiente:
1. Revisa la fuente de  "Sharing" crea  propuesta de combinación tipográfica por contraste. 
2. Mejora el interletrado. Separa un poco la I de la T y une un poco la T con la Forma que simula la A 
3. Mejora el vector de los símbolos que acompañan el texto. Asegúrate de que las curvas y las rectas sean perfectas.
4. Genera otras propuestas de colores 

**La propuesta 6** puedes intentar lo siguiente:
1. \- Separa un poco el logotipo del símbolo y pon mayúsculas en el inicio de cada palabra. Prueba también todo en mayúsculas.
2. \- quitale la gradación al logotipo
3. \- crea nuevas propuestas de colores.

@arismendi227 @arnaldos qué opinas?

**Comment by arismendi227** [comment]
@jhonmarquez92 @arnaldos 

modificaciones de la propuestas 2 y 6

1
![1](https://cloud.githubusercontent.com/assets/19276382/16140277/ef465be4-3418-11e6-8081-fa5ea8bc8c81.jpg)

2
![2](https://cloud.githubusercontent.com/assets/19276382/16140283/f66b5154-3418-11e6-9165-a99370e5c658.jpg)

3
![3](https://cloud.githubusercontent.com/assets/19276382/16140286/faa976ba-3418-11e6-99cc-2221175ab9b0.jpg)

4
![4](https://cloud.githubusercontent.com/assets/19276382/16140292/ffbf51ba-3418-11e6-8687-8772bf0c95aa.jpg)

5
![5](https://cloud.githubusercontent.com/assets/19276382/16140294/034807c8-3419-11e6-9197-1f9f152f9126.jpg)

6
![6](https://cloud.githubusercontent.com/assets/19276382/16140296/07b78ef0-3419-11e6-8be4-2eafc6eeb329.jpg)

**Comment by proseuz** [comment]
Definitivamente me gusta la propuesta 5 aunque no estoy seguro de los colores, qué opinas @arnaldos ?

**Comment by arnaldos** [comment]
vale perfecto por ahora demoslo así

**Comment by arnaldos** [comment]
esto ya esta en el repo ?
