### ISSUE TITLE
Create logo for P2P Delivery App

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#712]
| Business model | Actors involved | Description | Example |
| :-: | :-: | :-: | :-: |
| Food | Restaurant - Person | Company gets restaurants onboard to offer their menu on the app and clients order online. Each restaurant sorts out the delivery. | PedidosYa, Grubhub |

Reference issue #702

**Comment by Lilynwn** [comment]
![peedidos-06](https://cloud.githubusercontent.com/assets/17750301/13977010/8a35858c-f097-11e5-91c0-3fe39945a88e.png)

![peedidos-05](https://cloud.githubusercontent.com/assets/17750301/13977015/945b4cfe-f097-11e5-9741-03990e7130c2.png)

![pedidos-05](https://cloud.githubusercontent.com/assets/17750301/13977023/9b5b6eb2-f097-11e5-9b3d-3e5fb5b36f15.png)

![peedidos-09](https://cloud.githubusercontent.com/assets/17750301/13977041/befbf968-f097-11e5-856a-23891168a892.png)

**Comment by emmysm** [comment]
@Lilynwn, la app se llamará Delivery, coloca ese nombre en vez de pedidos ya. Me gusta la última propuesta. Se puede generar otra a partir de esa :smile_cat:

**Comment by arnaldos** [comment]
@Lilynwn @emmysm se puede partir de la segunda propuesta pero hay que cuidar los espacios de los elementos ya que en su maxima reduccion se pierde fijense como se comporta en la pantalla del tlf. @Lilynwn plz genera 3 versiones partiendo de la segunda :smile:

**Comment by arnaldos** [comment]
@Lilynwn @emmysm que ha pasado con esto ??

**Comment by Lilynwn** [comment]
![p2pop1](https://cloud.githubusercontent.com/assets/17750301/14297994/3fd3464a-fb4c-11e5-9ffb-d77bd4bd88e1.png)

![p2pop1app](https://cloud.githubusercontent.com/assets/17750301/14298001/44f5c0a8-fb4c-11e5-8808-4f1b6732fc07.png)

![p2pop2](https://cloud.githubusercontent.com/assets/17750301/14298008/4c82e008-fb4c-11e5-9015-30c8fe084cd1.png)

![p2pop2app](https://cloud.githubusercontent.com/assets/17750301/14298012/529d8394-fb4c-11e5-9d0c-94e2fa09cadc.png)

![p2pop3](https://cloud.githubusercontent.com/assets/17750301/14298014/57b80b9c-fb4c-11e5-844d-01fad9530a06.png)

![p2pop3app](https://cloud.githubusercontent.com/assets/17750301/14298021/5d53d824-fb4c-11e5-82d2-42af38952c52.png)

**Comment by Lilynwn** [comment]
![1](https://cloud.githubusercontent.com/assets/17750301/14519969/c070b364-01eb-11e6-8ef5-ee5159d4196a.png)

![1 1](https://cloud.githubusercontent.com/assets/17750301/14520001/dcc5f3ee-01eb-11e6-9cea-4327d6b83e27.png)

![2 2](https://cloud.githubusercontent.com/assets/17750301/14520044/2706778a-01ec-11e6-93b2-8a4844354d6c.png)

![2](https://cloud.githubusercontent.com/assets/17750301/14520012/e90d0bec-01eb-11e6-82fc-956f50c95580.png)

![3 3](https://cloud.githubusercontent.com/assets/17750301/14520018/fdda95ee-01eb-11e6-8bd5-17b0cd6989a9.png)

![3](https://cloud.githubusercontent.com/assets/17750301/14520023/0a3f6b02-01ec-11e6-98dd-60a16f2654ee.png)

**Comment by emmysm** [comment]
Me gusta la primera propuesta. realiza otras a partir de esa. Cuidado con los nodos, acomoda la pierna izquierda, que quede a la misma altura de la parte inferior del cuerpo de la paleta. El nodo de la mano sobresale en el elemento que lleva sobre ellas. Agrégale una sombra a 45° y otras propuestas de color.
@Lilynwn

**Comment by arnaldos** [comment]
@Lilynwn por favor debemos darle mayor velocidad a esto plz. otra cosa recuerda identificar las versiones plz

**Comment by emmysm** [comment]
@Lilynwn necesitamos esto con urgencia.

**Comment by Lilynwn** [comment]
![colores y correciones-01](https://cloud.githubusercontent.com/assets/17750301/14575697/56581e52-032d-11e6-88e5-2fefe3c8d706.png)

Modificaciones :)

**Comment by arnaldos** [comment]
@Lilynwn el personaje no esta mal, pero al icono en si le falta fuerza, por otro lado te rcomiendo si va a usar sombras las lineas deben ser paralelas y a 45°. recuerda que mas que un icono es un logo que se ve se presenta en icono en el desktop de la app. pero es la identidad del modelo de negocio.

**Comment by arnaldos** [comment]
prueba incluir al personaje dentro de un circulo, ajusta la sombra según lo que te comente, eso puede ayudarte a obtener mayor balance interno del icono.

**Comment by Joseangel2v** [comment]
Propuesta 1
![1d](https://cloud.githubusercontent.com/assets/17457499/14694870/7ea49aae-0736-11e6-89f6-ea9e7541caf0.png)

**Comment by Joseangel2v** [comment]
Propuesta 2
![2d](https://cloud.githubusercontent.com/assets/17457499/14694886/95d0dcec-0736-11e6-8087-b7024d029e0b.png)

**Comment by Joseangel2v** [comment]
Propuesta 3
![3d](https://cloud.githubusercontent.com/assets/17457499/14694891/a15f2672-0736-11e6-9b05-41fc7d26f986.png)

**Comment by Joseangel2v** [comment]
Propuesta 4
![4d](https://cloud.githubusercontent.com/assets/17457499/14694896/ae53cd88-0736-11e6-87c1-eb4767d415ac.png)

**Comment by Joseangel2v** [comment]
@emmysm @arnaldos Como vamos??

**Comment by emmysm** [comment]
Me gusta el concepto de la segunda propuesta. Genera otras en base a esa, hay algo que no me convence de los brazos y las piernas. Agrégale drop shadow, @Joseangel2v

**Comment by Joseangel2v** [comment]
Propuesta 5
![1](https://cloud.githubusercontent.com/assets/17457499/14722209/3a1d7d8a-07d4-11e6-90e6-faccf8efd5d2.png)

**Comment by Joseangel2v** [comment]
Propuesta 6
![4](https://cloud.githubusercontent.com/assets/17457499/14722271/899eda16-07d4-11e6-9563-a57b44bd711c.png)

**Comment by Joseangel2v** [comment]
Propuesta  7
![3](https://cloud.githubusercontent.com/assets/17457499/14722434/53f1b388-07d5-11e6-96ab-ad2223872fe0.png)

**Comment by Joseangel2v** [comment]
Propuesta 8
![2](https://cloud.githubusercontent.com/assets/17457499/14722447/65600192-07d5-11e6-8bea-9765c589fd77.png)

**Comment by emmysm** [comment]
Me gusta la propuesta 7, pero con el chef invertido hacia la derecha. Prueba otros colores, porfa @Joseangel2v

**Comment by Joseangel2v** [comment]
Propuesta 9
![11](https://cloud.githubusercontent.com/assets/17457499/14728194/82bddb34-07fc-11e6-9c41-55c9b8a1e086.png)

**Comment by Joseangel2v** [comment]
Propuesta 10
![12](https://cloud.githubusercontent.com/assets/17457499/14728214/98a62262-07fc-11e6-9ffe-253bdf85225c.png)

**Comment by Joseangel2v** [comment]
Propuesta 11
![13](https://cloud.githubusercontent.com/assets/17457499/14728231/ac16649c-07fc-11e6-92df-66bb093d20df.png)

**Comment by Joseangel2v** [comment]
Propuesta 12
![14](https://cloud.githubusercontent.com/assets/17457499/14728728/61b6a902-0801-11e6-95f1-7e587eeaa8b4.png)

**Comment by arnaldos** [comment]
@Joseangel2v prueba hacer un closeup porque la verdad es que se pierde la síntesis en la reducción. has algo así como en la imagen de muestra 

![untitled-1](https://cloud.githubusercontent.com/assets/13594347/14758121/6732b85c-08c5-11e6-9dc1-001958d4402f.jpg)

**Comment by Joseangel2v** [comment]
@arnaldos Ok ok.. Voy.

**Comment by Joseangel2v** [comment]
Propuesta 13
![1d](https://cloud.githubusercontent.com/assets/17457499/14758695/84720410-08d2-11e6-8d23-67def8e4afe4.png)

**Comment by Joseangel2v** [comment]
Propuesta 14
![2d](https://cloud.githubusercontent.com/assets/17457499/14758712/0530bc2c-08d3-11e6-85b5-158c97480e55.png)

**Comment by Joseangel2v** [comment]
@arnaldos @emmysm Como vamos por aqui??

**Comment by emmysm** [comment]
Más propuestas, @Joseangel2v . Opino que se vería mejor con salga un poco más la bata.

**Comment by Joseangel2v** [comment]
Propuesta 15
![d1](https://cloud.githubusercontent.com/assets/17457499/14905797/4c53829c-0d7e-11e6-8fba-2040c474b2a9.png)

**Comment by Joseangel2v** [comment]
Propuesta 16
![d2](https://cloud.githubusercontent.com/assets/17457499/14905813/7c51aa50-0d7e-11e6-811f-f93736190564.png)

**Comment by Joseangel2v** [comment]
Propuesta 17
![d3](https://cloud.githubusercontent.com/assets/17457499/14905817/85ee4d02-0d7e-11e6-802e-6461aeabe659.png)

**Comment by Joseangel2v** [comment]
Propuesta 18
![p2p](https://cloud.githubusercontent.com/assets/17457499/15008298/22727cc4-11a9-11e6-947b-ac12602421df.png)

**Comment by arnaldos** [comment]
por ahora dejemos la 18 sube los recursos al repo

**Comment by Joseangel2v** [comment]
Ok @arnaldos ya los archivos estan en el repo.

**Comment by arnaldos** [comment]
ok perfecto !!!
