### ISSUE TITLE
Create Logo for P2P Travel / Tourism App

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#713]
| Business model | Actors involved | Description | Example |
| :-: | :-: | :-: | :-: |
|  | Tourism company - tourist | A company offers accomodation and other services to tourists | Kayak, Booking.com, Agoda |

Reference issue #702

**Comment by Carelsy** [comment]
Version 1 and 2 for P2P tourism company

![p2p-travel](https://cloud.githubusercontent.com/assets/17755307/13969030/66f5e836-f052-11e5-8b3a-28762aaa12cc.png)

![p2p-travel2](https://cloud.githubusercontent.com/assets/17755307/13969465/46b32a22-f055-11e5-83cd-bde7a8880c9e.png)

**Comment by Carelsy** [comment]
P2P logo modification 
![p2p-travel3](https://cloud.githubusercontent.com/assets/17755307/14131261/66f0b652-f603-11e5-8530-e8bbe64f5a21.png)

**Comment by Carelsy** [comment]
P2P logo modification 
![p2p-travel4](https://cloud.githubusercontent.com/assets/17755307/14131530/fa017948-f605-11e5-80d5-b8c4f3c5951d.png)

**Comment by Carelsy** [comment]
mejoras del logo ![p2p-travel5](https://cloud.githubusercontent.com/assets/17755307/14194085/40bf40d0-f774-11e5-9d05-97285236a34a.png)

**Comment by Carelsy** [comment]
![p2p-travel6](https://cloud.githubusercontent.com/assets/17755307/14196536/4f935c34-f78f-11e5-965b-42c0cbddb098.png)

**Comment by arnaldos** [comment]
@Carelsy muy bueno !!! sube los archivo al repo. :+1:

**Comment by arnaldos** [comment]
la ultima version

**Comment by arnaldos** [comment]
hola @Carelsy cuando puedas enviame la ruta de este logo para incluirlo en la app y cerrar el caso
