### ISSUE TITLE
Create logo from P2P Insurance App

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#714]
A certain number of policyholders pool together. In the event of any claim they support each other financially.

**Comment by arnaldos** [comment]
@karentvillegas como vamos con esto ?

**Comment by karentvillegas** [comment]
@arnaldos @jhonmarquez92  Tomando en cuenta el significado de "seguro" se han generado las siguientes propuestas: 
1
![propuesta1](https://cloud.githubusercontent.com/assets/19273211/15509469/8377384e-219d-11e6-92bf-2996164563f0.png)
2
![propuesta2](https://cloud.githubusercontent.com/assets/19273211/15509474/877c80a2-219d-11e6-81b5-a2e486589105.png)
3
![propuesta3](https://cloud.githubusercontent.com/assets/19273211/15509485/8bfce9be-219d-11e6-8a0a-d0cdf0146a63.png)
4
![propuesta4](https://cloud.githubusercontent.com/assets/19273211/15509664/14973b76-219e-11e6-8165-67f356a9694c.png)
5
![propuesta5](https://cloud.githubusercontent.com/assets/19273211/15509509/999b4886-219d-11e6-8041-c958e0e3fa19.png)
6
![propuesta6](https://cloud.githubusercontent.com/assets/19273211/15509522/9fea2d38-219d-11e6-8b6d-51595a3a5974.png)

**Comment by proseuz** [comment]
Creo que va más por la idea de seguros de vida, de muebles e inmuebles No creo que va por los candaditos ni los escudos. Recuerda que debe ser figurativo mayormente. Por favor genera más propuestas @arnaldos tú qué crees?

**Comment by karentvillegas** [comment]
Propuestas nuevas @arnaldos @jhonmarquez92 
7
![propuesta7](https://cloud.githubusercontent.com/assets/19273211/15659141/d209548c-268f-11e6-898b-b2dbb6a45b2b.png)
8
![propuesta8](https://cloud.githubusercontent.com/assets/19273211/15659144/d692a5a8-268f-11e6-9351-6fa9c54974b4.png)
9
![propuesta9](https://cloud.githubusercontent.com/assets/19273211/15659152/dcfbd86a-268f-11e6-9585-eda25fd25d03.png)
10
![propuesta10](https://cloud.githubusercontent.com/assets/19273211/15659154/e0b3a8f2-268f-11e6-8746-cfd0ea030c54.png)
11
![propuesta11](https://cloud.githubusercontent.com/assets/19273211/15659155/e521f79a-268f-11e6-8f62-672310750607.png)

**Comment by arnaldos** [comment]
trabaja al menos abstracto plz

**Comment by karentvillegas** [comment]
@arnaldos @jhonmarquez92 

Propuestas menos abstractas
12
![propuesta12](https://cloud.githubusercontent.com/assets/19273211/15980869/942fb398-2f38-11e6-98e1-fd570b49a6d6.png)
13
![propuesta13](https://cloud.githubusercontent.com/assets/19273211/15980872/980f12d8-2f38-11e6-9990-e06898b38e9f.png)
14
![propuesta14](https://cloud.githubusercontent.com/assets/19273211/15980875/9d897f32-2f38-11e6-81cf-4c66b0aba792.png)
15
![propuesta15](https://cloud.githubusercontent.com/assets/19273211/15980878/a1f20eea-2f38-11e6-94ee-f85303d05781.png)
16
![propuesta16](https://cloud.githubusercontent.com/assets/19273211/15980880/a5a364d0-2f38-11e6-8589-ed62173e6c82.png)
17
![propuesta17](https://cloud.githubusercontent.com/assets/19273211/15980883/ae09c0f6-2f38-11e6-8e28-f367cfbb5e8f.png)
18
![propuesta18](https://cloud.githubusercontent.com/assets/19273211/15980888/b302567c-2f38-11e6-8027-02a412b8d2d0.png)

**Comment by proseuz** [comment]
@karentvillegas la 17 puede funcionar mejorando la síntesis del paraguas. que piensas tú @arnaldos

**Comment by karentvillegas** [comment]
@arnaldos @jhonmarquez92 

Propuestas
19
![propuesta19](https://cloud.githubusercontent.com/assets/19273211/16100323/6e7ed8ac-3327-11e6-9fb8-ed234e0ed8cf.png)
20
![propuesta20](https://cloud.githubusercontent.com/assets/19273211/16100326/71a92226-3327-11e6-86fa-0febf01019c9.png)
21
![propuesta21](https://cloud.githubusercontent.com/assets/19273211/16100328/7557274c-3327-11e6-9b02-76445e18e62d.png)
22
![propuesta22](https://cloud.githubusercontent.com/assets/19273211/16100333/80e08766-3327-11e6-975a-737a8b29b215.png)
23
![propuesta23](https://cloud.githubusercontent.com/assets/19273211/16100335/857c589a-3327-11e6-80d8-066d7a84c08c.png)
24
![propuesta24](https://cloud.githubusercontent.com/assets/19273211/16100344/95f57030-3327-11e6-9942-06d5c6b59b6e.png)
25
![propuesta25](https://cloud.githubusercontent.com/assets/19273211/16100354/9eaf12bc-3327-11e6-9a20-c91f66da4998.png)
26
![propuesta26](https://cloud.githubusercontent.com/assets/19273211/16100357/a2cadb24-3327-11e6-9e97-bc770557f7ac.png)
27
![propuesta27](https://cloud.githubusercontent.com/assets/19273211/16100360/a7e3aca8-3327-11e6-9895-0d5b5afd51dd.png)
28
![propuesta28](https://cloud.githubusercontent.com/assets/19273211/16100372/b3b04af0-3327-11e6-95ab-f93f520247b5.png)
29
![propuesta29](https://cloud.githubusercontent.com/assets/19273211/16100378/bb0cbb9e-3327-11e6-9ce9-4e70a54d7d00.png)
30
![propuesta30](https://cloud.githubusercontent.com/assets/19273211/16100382/bf7192c2-3327-11e6-9ea3-fe59daf61a3c.png)
31
![propuesta31](https://cloud.githubusercontent.com/assets/19273211/16100387/c3d9ef4e-3327-11e6-89e3-13c6bdf4e497.png)
32
![propuesta32](https://cloud.githubusercontent.com/assets/19273211/16100390/c8429144-3327-11e6-829f-df1a6b4d8d14.png)
33
![propuesta33](https://cloud.githubusercontent.com/assets/19273211/16100394/cd3becc2-3327-11e6-8503-0df793e5dcc8.png)

**Comment by proseuz** [comment]
con la **propuesta 23**
Haz pruebas cambiando la ubicación del logotipo y explora con otras tipografías.

Crea al menos 2 propuestas más please @karentvillegas

**Comment by karentvillegas** [comment]
@arnaldos @jhonmarquez92 Basado en la Propuesta 23 se generaron las siguientes propuestas

34
![propuesta34](https://cloud.githubusercontent.com/assets/19273211/16141152/40f46446-3422-11e6-9ff0-976a02b93986.png)
35
![propuesta35](https://cloud.githubusercontent.com/assets/19273211/16141156/4bd470e0-3422-11e6-98f5-14bb05549165.png)
36
![propuesta36](https://cloud.githubusercontent.com/assets/19273211/16141159/4fb3ac9e-3422-11e6-8280-40d392f0a9fa.png)
37
![propuesta37](https://cloud.githubusercontent.com/assets/19273211/16141162/53d7ab7c-3422-11e6-9164-c74734b1a6e5.png)
38
![propuesta38](https://cloud.githubusercontent.com/assets/19273211/16141165/589634d0-3422-11e6-9af1-990479f105d9.png)
39
![propuesta39](https://cloud.githubusercontent.com/assets/19273211/16141167/5d758c4e-3422-11e6-8a68-0a8668064402.png)

**Comment by proseuz** [comment]
la versión 36 o 38 funcionan bastante bien.  qué opinas @arnaldos

**Comment by arnaldos** [comment]
versión 38 prueba el punto en naranja también a ver como se ve 
@jhonmarquez92 @karentvillegas

**Comment by karentvillegas** [comment]
@arnaldos @jhonmarquez92  Propuestas a partir de la versión 38, con el punto naranja:
40
![propuesta40](https://cloud.githubusercontent.com/assets/19273211/16198233/f754a8dc-36ce-11e6-924e-38249e4be271.png)
41
![propuesta41](https://cloud.githubusercontent.com/assets/19273211/16198242/fd6f157c-36ce-11e6-9d3a-54d5df2f4bfa.png)

**Comment by arnaldos** [comment]
@karentvillegas 
ok el punto que sea un circulo no ovalo.
- Los elemento de arriba que hacen la forma de los brazos deben estar a la misma altura.
- El elemento naranja esta afuera en la parte del borde derecho fijate como solucionar eso

**Comment by karentvillegas** [comment]
@arnaldos @jhonmarquez92 Correcciones aplicadas 
Propuesta 42
![propuesta42](https://cloud.githubusercontent.com/assets/19273211/16202808/1d96f25e-36e1-11e6-8fef-133e254840ef.png)

**Comment by proseuz** [comment]
Se ve muy bien con las sugerencias. qué opinas @arnaldos ?

**Comment by proseuz** [comment]
@karentvillegas  porfa crea una versión con el violeta en la totalidad del logotipo

**Comment by arnaldos** [comment]
en la "I" el vector morado en el borde derecho se mete hacia la izquierda lo que hace que se vea como si el vector esta mal construido, si la idea es mostrar un poco mas el fondo naranja nose esta logrando recuerda que esto va a reducir y en su maxima reducción esto no se va a ver. por lo que recomiendo sea una linea recta en ves de que este inclinada

**Comment by proseuz** [comment]
estoy de acuerdo @arnaldos

**Comment by karentvillegas** [comment]
@arnaldos @jhonmarquez92 
Modificando el vector:
Propuesta 43
![propuesta43](https://cloud.githubusercontent.com/assets/19273211/16250429/1f49596e-37e7-11e6-8f1f-693a63802f00.png)

Pruebas de color para la totalidad del logotipo:
Propuesta 44
![propuesta44](https://cloud.githubusercontent.com/assets/19273211/16250432/24151dac-37e7-11e6-8b69-5df8673c597b.png)
Propuesta 45
![propuesta45](https://cloud.githubusercontent.com/assets/19273211/16250434/28218b56-37e7-11e6-9859-6b05313561d6.png)
Propuesta 46
![propuesta46](https://cloud.githubusercontent.com/assets/19273211/16250436/2bb24f6c-37e7-11e6-9964-ce646fff32dd.png)
Propuesta 47
![propuesta47](https://cloud.githubusercontent.com/assets/19273211/16250439/31d08cc4-37e7-11e6-9e02-75f0c209a546.png)

**Comment by proseuz** [comment]
La propuesta 45 @arnaldos @karentvillegas

**Comment by arnaldos** [comment]
de acuerdo ! 45 :+1:

**Comment by arnaldos** [comment]
@karentvillegas confirmarme si esto esta en el repo para cerrar el caso
