### ISSUE TITLE
Create a logotype for  Dating platform (DTG)

### ISSUE THREAD

**Issue by emmysm** [bitDubai/fermat-graphic-design#715]

**Comment by edwarmas** [comment]
propuestas @emmysm 
@Luis-Fernando-Molina 
![be07e94a-dfe9-11e5-8877-e6c982f88c82-07-07](https://cloud.githubusercontent.com/assets/17460993/13883831/7fa14cca-ecfd-11e5-95b9-3995599acd81.jpg)
![be07e94a-dfe9-11e5-8877-e6c982f88c82-07-08](https://cloud.githubusercontent.com/assets/17460993/13883829/7f9edeae-ecfd-11e5-8c8e-0ddb87b6ab79.jpg)
![be07e94a-dfe9-11e5-8877-e6c982f88c82-09](https://cloud.githubusercontent.com/assets/17460993/13883830/7f9fe600-ecfd-11e5-89f7-0ca550cafd47.jpg)
![be07e94a-dfe9-11e5-8877-e6c982f88c82-10](https://cloud.githubusercontent.com/assets/17460993/13883832/7fa1498c-ecfd-11e5-930f-d538eeae1f3e.jpg)
![be07e94a-dfe9-11e5-8877-e6c982f88c82-11-11](https://cloud.githubusercontent.com/assets/17460993/13883833/7fa1c79a-ecfd-11e5-9eb2-0f570c6190a7.jpg)

**Comment by arnaldos** [comment]
@edwarmas plz esta atento a los comentarios que se te hacen, lo de las sombras las veo igual pasan por encima del aro blanco deben finalizar en la parte interna del aro blanco. Otra cosa que noto, es que estas trabajando con una paleta de colores que no es la correcta, estos iconos se estan trabajando bajo una paleta de colores ya establecida, que es la de la identidad de Fermat. @emmysm creo ya te había hecho mención en el caso de la guitarra. si tienes dudas puedes preguntar. de todas maneras te dejo el enlace donde estan expuestos los logos para que tengas la referencia http://dev.fermat.org/

**Comment by edwarmas** [comment]
muchas gracias @arnaldos

**Comment by Lilynwn** [comment]
![dating-02](https://cloud.githubusercontent.com/assets/17750301/14131191/ba64d0bc-f602-11e5-85f7-e76f3e5a1b80.png)

![dating-03](https://cloud.githubusercontent.com/assets/17750301/14131193/c100e29e-f602-11e5-9c66-cfb3b81cab2a.png)

![dating-01](https://cloud.githubusercontent.com/assets/17750301/14131198/cef2ee06-f602-11e5-99b3-3ea1a76f1a38.png)

@arnaldos @emmysm

**Comment by emmysm** [comment]
Genera más propuestas, @Lilynwn, por favor. La sombra debe ir a 45°, por dentro del primer circulo.

**Comment by Joseangel2v** [comment]
Propuesta 1
![1 datting](https://cloud.githubusercontent.com/assets/17457499/14546128/0f5d7f12-026d-11e6-91b8-8bfa787b47a6.png)

**Comment by Joseangel2v** [comment]
Propuesta 2
![2 datting](https://cloud.githubusercontent.com/assets/17457499/14546140/2a35cb14-026d-11e6-9884-4e7e0a5f4dce.png)

**Comment by Joseangel2v** [comment]
Propuesta 3
![3 datting](https://cloud.githubusercontent.com/assets/17457499/14546143/36beea28-026d-11e6-89de-4bef11d96541.png)

**Comment by Joseangel2v** [comment]
Propuesta 4
![4 datting](https://cloud.githubusercontent.com/assets/17457499/14546148/450e8e80-026d-11e6-9db9-6d7be1714123.png)

**Comment by Joseangel2v** [comment]
@emmysm @arnaldos @joseangel2v como vamos?

**Comment by Joseangel2v** [comment]
Propuesta 5
![5 datting](https://cloud.githubusercontent.com/assets/17457499/14546514/a2526e16-026f-11e6-9dd9-6cfe0f748e71.png)

**Comment by Joseangel2v** [comment]
Propuesta 6
![6 datting](https://cloud.githubusercontent.com/assets/17457499/14546523/b1f99614-026f-11e6-9ce6-a3ec164d2723.png)

**Comment by Joseangel2v** [comment]
Propuesta 7
![7 datting](https://cloud.githubusercontent.com/assets/17457499/14546535/c10877f6-026f-11e6-8df9-1aff5479c880.png)

**Comment by emmysm** [comment]
Haz otras propuestas partiendo de la opción 4. Cuidado con los nodos @Joseangel2v

**Comment by Joseangel2v** [comment]
Propuesta 1_2
![1](https://cloud.githubusercontent.com/assets/17457499/14621936/39d57aee-0590-11e6-984f-3e7d73a4edce.png)

**Comment by Joseangel2v** [comment]
Propuesta 2_2
![2](https://cloud.githubusercontent.com/assets/17457499/14621944/4aeaa6ce-0590-11e6-81fd-fe13929bce1f.png)

**Comment by Joseangel2v** [comment]
Propuesta 3_3
![3](https://cloud.githubusercontent.com/assets/17457499/14622241/5e37f464-0592-11e6-97bc-6076199c0001.png)

**Comment by Joseangel2v** [comment]
Propuesta 4_4
![4](https://cloud.githubusercontent.com/assets/17457499/14622745/08cf50b8-0596-11e6-9a44-c7942dda5ae9.png)

**Comment by emmysm** [comment]
@Luis-Fernando-Molina cómo vamos por aqui?

**Comment by emmysm** [comment]
Me gusta la propuesta 4 @Joseangel2v :+1:

**Comment by Joseangel2v** [comment]
![4](https://cloud.githubusercontent.com/assets/17457499/14623161/64f347d4-0599-11e6-84b9-6f8dc1f59c51.png)

**Comment by Luis-Fernando-Molina** [comment]
Para mi la 3 esta bien . Por favor para evitar ambiguadades, no reinicien la numeracion de las propuestas. Ahora mismo hay mas de una 3. Yo me refiero a la ultima. Reiniciar significa tener que estar aclarando o dar lugar a equivocaciones. gracias.

**Comment by emmysm** [comment]
Nos quedamos con la 3 @Luis-Fernando-Molina
