### ISSUE TITLE
Grafico Fermat User Interface

### ISSUE THREAD

**Issue by ivonnesantos** [bitDubai/fermat-graphic-design#716]
Aca la informacion que tengo del caso
1-Reemplazar Niche APPs por Combo APPs.  
2-Quitar /Wallets de todos lados.
3-En External APPs buscar iconos de Android APPs (cualquiera que se vean bien y que pudieran de alguna manera reutilizar la funcionalidad de fermat)
4-En Reference APPs poner iconos de nuestras APPs, los mejores 
5-Todos los iconos llevarlos a todo azulado.
6-En los componentes usar lo que hizo Diana
7-Respetar la cantidad de APPs, componentes, y flechas, poner todo tal cual esta ahi.
8-Respeten tamaño y colores de letras como venimos haciendo hasta ahora.

**Boceto Suministrado por Luis**
![grafico fermat user interface](https://cloud.githubusercontent.com/assets/15238660/13815754/0300f53a-eb5e-11e5-93af-f761ba89df84.png)

**Comment by ivonnesantos** [comment]
![grafico fermat user interface 716-01](https://cloud.githubusercontent.com/assets/15238660/13860663/b8fc331a-ec5b-11e5-815b-bfe1f7d7dd7f.png)

@Luis-Fernando-Molina

**Comment by Luis-Fernando-Molina** [comment]
Hola, ok te paso las correcciones.
1. El titulo pone "Fermat User Interface Architecture"
2. Quita los circulos azules sin nada adentro.
3. Las fechas que vienen desde EXTERNAL APPS hace que apunten unicamente a los primeros componentes debajo de los iconos de REFERENCE APPS.
4. La linea verde que divide External APPs de Branded APPs cambiala de color

**Comment by ivonnesantos** [comment]
![grafico fermat user interface 716-01](https://cloud.githubusercontent.com/assets/15238660/13883040/0100fe90-ecfa-11e5-988f-067902675aa1.png) @Luis-Fernando-Molina

**Comment by Luis-Fernando-Molina** [comment]
Hay un error en donde dice Plugi-ns . debe ser Plug-ins

**Comment by ivonnesantos** [comment]
@Luis-Fernando-Molina 
![grafico fermat user interface 716-01](https://cloud.githubusercontent.com/assets/15238660/13888842/c11b8176-ed15-11e5-9434-39efd0aa34e1.png)

**Comment by Luis-Fernando-Molina** [comment]
Listo :+1:
