### ISSUE TITLE
Gráfico Splitting Information and Value

### ISSUE THREAD

**Issue by ivonnesantos** [bitDubai/fermat-graphic-design#717]
1-Lo que se ve arriba al medio es la Fermat Network (sin la extended network).
2-Meta data reemplazarlo por information
3-Poner en cada celular el mismo logo de una fermat APP como por ejemplo el de la bitcoin wallet.
**
Boceto de Grafico Suministrado por Luis **
![splitting information and value](https://cloud.githubusercontent.com/assets/15238660/13816254/ceffe5fa-eb5f-11e5-9a74-4af5924e0b23.png)

**Comment by arifernandez** [comment]
![grafico splitting information and value 717-01](https://cloud.githubusercontent.com/assets/16305653/13863057/4d079b5a-ec69-11e5-8fa7-c80189ee0808.png)

@ivonnesantos Algo asi?

**Comment by ivonnesantos** [comment]
La tipografia de arriba debe ser tal cual a la de arnaldo no cursiva, las computadoras y los dipositivos moviles deberian ser iguales a los de arriba el resto si lo veo igual a lo que te piden
No estoy segura que las monedas doradas funcionen en la composición general que se esta trabajando yo no se bien como se van aplicar estos graficos si estaran visibles todos en un plano o separado pero imaginate que esten todos en el mismo plano las moneditas resaltaran

**Comment by ivonnesantos** [comment]
@arifernandez fijate en como pusiste la flecha de abajo a la derecha esta mal la dirección

**Comment by arifernandez** [comment]
![grafico splitting information and value 717_2-02](https://cloud.githubusercontent.com/assets/16305653/13889562/6e58a64a-ed19-11e5-8594-e0d3b61aa725.png)

@ivonnesantos

**Comment by ivonnesantos** [comment]
@Luis-Fernando-Molina

**Comment by arifernandez** [comment]
Propuesta 2

![grafico splitting information and value 717_3-03](https://cloud.githubusercontent.com/assets/16305653/13890123/0ef10000-ed1c-11e5-8ea5-85e9c95cada9.png)

@ivonnesantos

**Comment by ivonnesantos** [comment]
@Luis-Fernando-Molina

**Comment by Luis-Fernando-Molina** [comment]
1-Sacale a la Fermat Network los dispositivos y el circulo verde exterior.
2.La bitcoin network representala igual que a la de arriba solo que al centro le pones una moneda de bitcoin, y logitos de bitcoin en blanco en alguno de los nodos azules. 
3. Los dos telefonos de los costados ponelos al centro verticalmente
4. Las moneditas de bitcoin al lado de value ponelas mucho mas chicas.
5. Pone el icono del dispositivo de la izquierda tambien a la derecha

Fijate si me podes entregar esto en un rato porque se me fue el tiempo

**Comment by arifernandez** [comment]
Propuesta 1

![grafico splitting information and value 717_4-03](https://cloud.githubusercontent.com/assets/16305653/13894306/82596944-ed38-11e5-9f00-21f431a2b6fb.png)

Propuesta 2

![grafico splitting information and value 717_5-05](https://cloud.githubusercontent.com/assets/16305653/13894307/825eb778-ed38-11e5-9f65-3e1cb6bf2de1.png)

@ivonnesantos

**Comment by ivonnesantos** [comment]
@Luis-Fernando-Molina

**Comment by Luis-Fernando-Molina** [comment]
Propuesta 1.
1. No se porque se agrandaron los telefonos. Volverlos al tamaño original o mas chicos inclusive.
2. Quita los dispositivos de la red bitcoin. 
3. En la red bitcoin hay nodos que no estan en la interseccion de las lineas.
4. Las lineas se ven RARAS, no bien definidas.
5. El centro de la red fermat no es transparente.
6. Las palabras Information y Value no se porque se las puso inclinadas si estaban bien horizontales.
7. Las moneditas bitcoin que no esten en perspectiva

**Comment by Luis-Fernando-Molina** [comment]
1. las flechas de arriba y de abajo deben estar simetricas

**Comment by arifernandez** [comment]
![grafico splitting information and value 717_6-03](https://cloud.githubusercontent.com/assets/16305653/13895332/65996a82-ed44-11e5-9e0d-d7f613e9ca4b.png)

@arnaldos

**Comment by arifernandez** [comment]
![grafico-splitting-information-and-value-717-7](https://cloud.githubusercontent.com/assets/16305653/13895873/fa3bcba6-ed4b-11e5-9710-36e0ba2ffe8f.png)

**Comment by arifernandez** [comment]
![grafico-splitting-information-and-value-717-7](https://cloud.githubusercontent.com/assets/16305653/13896056/6a5b2454-ed51-11e5-8719-4bb4fcd258e9.png)

@arnaldos

**Comment by arnaldos** [comment]
subelo al repo para incluirlo en el readme !!

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina así quedo y se subió al readme

![grafico-splitting-information-and-value](https://cloud.githubusercontent.com/assets/13594347/13896492/24759074-ed5f-11e5-9c6e-a4f5f6aa02a2.png)

**Comment by Luis-Fernando-Molina** [comment]
En el de Spliting information and Value A) Todo esta demasiado grande, El grafico tiene que poder entrar en la mitad del espacio vertical. B) Hay nodos en la red bitcoin QUE NO ESTAN en la internseccion de las lineas, lo cual es inconsistente con todo lo que hicimos hasta ahora.

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina @arifernandez  estos ajustes pueden verlos ya aplicados en el readme del media kit https://github.com/Fermat-ORG/media-kit/blob/master/README.md

**Comment by Luis-Fernando-Molina** [comment]
Me estas cargando no?  Redujeron los tipos de letra junto con todo lo otro
