### ISSUE TITLE
Create a new icon image No chats and No contacts to Chat App 

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#718]
The Chat App was approved in this issue
https://github.com/Fermat-ORG/fermat-graphic-design/issues/525

Reference issue https://github.com/Fermat-ORG/fermat/issues/5372

Reference image

![fermat_chat_app_views_4](https://cloud.githubusercontent.com/assets/13594347/13820150/404b5b78-eb6e-11e5-91bb-77f56f58bf64.png)

**Comment by JefersonBorgesS** [comment]
@arnaldos @vlzangel 

Version 1
![fermat_chat_app-1](https://cloud.githubusercontent.com/assets/17457984/13826023/95783d3c-eb87-11e5-9b6e-7f045b31dc43.jpg)

Version 2
![fermat_chat_app-2](https://cloud.githubusercontent.com/assets/17457984/13826025/994fc588-eb87-11e5-8a51-feadbd36d0a3.jpg)

**Comment by JefersonBorgesS** [comment]
@arnaldos @vlzangel 

Version 3
![fermat_chat_app-3](https://cloud.githubusercontent.com/assets/17457984/13857151/cf0f7880-ec4a-11e5-8b37-7aed53623306.jpg)

Version 4
![fermat_chat_app-4](https://cloud.githubusercontent.com/assets/17457984/13857170/e91b5460-ec4a-11e5-9ced-64de4e30d914.jpg)

**Comment by arnaldos** [comment]
@franklinmarcano1970 a mi me parece podemos trabajar con la versión 3 con las siguientes correcciones:
- Background gradiente con tonos grises claros 
- El floating butom integrar el signo mas "+" dentro del boton o sacarlo 
- Una sombra al floating buttom

**Comment by franklinmarcano1970** [comment]
@josejcb tu apreciacion
@Luis-Fernando-Molina por favor danos tu comentarios.

**Comment by josejcb** [comment]
me gusta la 4. es diferente. las siluetas se aprecian mas que en le 3ra. y es menos verde. juegan mas con los tonos.

**Comment by arnaldos** [comment]
@josejcb aquí los ajustes de los iconos, por el momento elimine el floating buttom para incorporarlo en los proximos componentes de la App. ya les subo los resources

![no_contacts-no_chats](https://cloud.githubusercontent.com/assets/13594347/13868829/486c3980-ec9f-11e5-83ea-306e0a9963e7.jpg)

**Comment by Luis-Fernando-Molina** [comment]
el grafico esta bien, poenele mas onda al fondo, quizas un pattern tipo bacterias o algo. Tiene mucho espacio para verse mejor.

**Comment by arnaldos** [comment]
vale ya lo resuelvo

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina @franklinmarcano1970 @josejcb 

#### Version 1

## ![no_contacts-no_chats3](https://cloud.githubusercontent.com/assets/13594347/13887514/3fc2d306-ed0e-11e5-8e04-f9b5541768fb.jpg)

#### Version 2

![no_contacts-no_chats2](https://cloud.githubusercontent.com/assets/13594347/13887515/3fc9b950-ed0e-11e5-8d7b-68a24c861e02.jpg)

**Comment by arnaldos** [comment]
#### Version 3

![no_contacts-no_chats4](https://cloud.githubusercontent.com/assets/13594347/13887579/a3150776-ed0e-11e5-84b2-c1eee97fc186.jpg)

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina recomiendo la versión 2 no se que opines

**Comment by Luis-Fernando-Molina** [comment]
esta mejor, pero no me sorprende. Segui desde la version 3

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina le coloque el fondo oscuro tal como se definió en el banner en este caso #617 de esta manera hacer el enlace entre ellos.

#### Version 4

## ![no_contacts-no_chats5](https://cloud.githubusercontent.com/assets/13594347/13890067/b8bcd2cc-ed1b-11e5-937c-68e24d0a559a.jpg)

#### Version 5

![no_contacts-no_chats6](https://cloud.githubusercontent.com/assets/13594347/13890068/b8c185c4-ed1b-11e5-90c9-277f5b629e3e.jpg)

**Comment by josejcb** [comment]
Este fondo oscuro me gusta mas que el anterior blanco - plata. En la version 4 se destacan los colores de la app, sin embargo, cualquiera de las combinaciones queda bien. @franklinmarcano1970 @Luis-Fernando-Molina que opinan?

**Comment by arnaldos** [comment]
@franklinmarcano1970  esto como quedo ?? fue aprobado ??

**Comment by franklinmarcano1970** [comment]
Bueno a mi me gusta este diseno de la version 4, @Luis-Fernando-Molina que opinas...
