### ISSUE TITLE
Create a Chat Community-UI/UX-App  Design

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#719]
The Chat App was approved in this issue
#525

Reference issue https://github.com/Fermat-ORG/fermat/issues/5371

**Comment by arnaldos** [comment]
@franklinmarcano1970 @josejcb @darkestpriest 
Pudiésemos trabajar en esta oportunidad un listado con un ratio buttom para seleccionar 
que contactos queremos agregar a la lista 
dejo los wireframes de la secuencia que debe seguir.

@adryx83 trabaja los mockup siguiendo esta secuencia:

![all](https://cloud.githubusercontent.com/assets/13594347/13836459/df4ad9b4-ebd3-11e5-8673-ba5b111ae4ba.png)

**Comment by adryx83** [comment]
Ok listo @arnaldos

**Comment by adryx83** [comment]
Buenas Tardes @arnaldos esta es la propuesta basada en la sugerencia que me diste sobre el chat community 

![pantalla community](https://cloud.githubusercontent.com/assets/17273349/13861896/098d7824-ec62-11e5-8898-283f1b465cca.jpg)

**Comment by arnaldos** [comment]
Me gusta como vas, solo habría que corregir unos detalles:

En general debemos a pegarnos a la paleta de colores establecida en chat.

###### En el Dialog
- Donde esta el icono realmente debe ir el banner este dialog nos da la bienvenida a la sub app y nos indica como usarla 

###### En el List
- Debes dejar los espacios mas distantes entre ellos fijate en el list ya definido en el chat.

###### En el Drawer
- Debes completar la altura hasta que llegue al final de la pantalla, lo unico que no se cubre es el action bar
- Del lado derecho debequedar un espacio libre de 56 dp

Te dejo este enlace : https://www.google.com/design/spec/patterns/navigation-drawer.html#navigation-drawer-specs te ayudara con el drawer

**Comment by adryx83** [comment]
Buenas tardes, ajunto la segunda propuesta con correcciones.

![pantalla community2](https://cloud.githubusercontent.com/assets/17273349/13891413/1bb0ea2e-ed23-11e5-9e59-a673ba2b3fb3.jpg)

**Comment by arnaldos** [comment]
1- Revisa los tonos de los colores, el verde esta mas brillante. no se si es el caso pero revisa estes trabajando en RGB y no CYMK si te traes el archivo de RGB a CYMK te cambian los tonos. (ojo no se si este sea el caso) el verde en hexadecimal es este #47BF73

2-El banner en el dialogo debe llevar la misma proporción que el que tienen todos. actualmente se esta trabanajdo en la siguiente medida 1024x500 escalalo a proporción para que la mantenga en el dialogo. 

3- Para identificar el de los contactos usa un icono a un solo tono sin fondo verde. tal ves puedes usar algunas fotos reales ya que a este paso los user ya deben tener su imagen de perfil.

4- cuando sale el dialogo deben salir atrás los user que están conectados

**Comment by adryx83** [comment]
Ok listo

**Comment by adryx83** [comment]
Buenos días, acá dejo las correcciones sugeridas, sobre el color @arnaldos nose porque sale así, tiene el mismo valor que me diste en la corrección y si, lo estoy trabajando en RGB, me parece raro igual lo volví a verificar en caso que no fuera el tono.

![pantallas chat community](https://cloud.githubusercontent.com/assets/17273349/13954538/73532150-f013-11e5-9646-fd14ead066e5.jpg)

**Comment by arnaldos** [comment]
@adryx83 por ahora solo ajusta el tamaño de del banner manten la proporcion que esta establecida.

@franklinmarcano1970 @josejcb que opinan de esta comunity ?

**Comment by josejcb** [comment]
a mi me gusta. @Lozadaa q opinas?

**Comment by franklinmarcano1970** [comment]
A mi parece excelente, recuerden que todas las comunity tienen unas opciones basicas, revisen cuales son esas opciones para que se las pasen a @arnaldos, y las coloquen en el diseno.
@josejcb @Lozadaa

**Comment by Lozadaa** [comment]
Me gusta bastante. @josejcb Sabes cuales son las opciones basicas? hay que verlas.

**Comment by franklinmarcano1970** [comment]
@josejcb @Lozadaa Revisa cualquier community de fermat y puedes revisar.

**Comment by arnaldos** [comment]
vale ya reviso eso

**Comment by josejcb** [comment]
Tenemos icono para la comunidad de chat? En otro orden de ideas, en el issue referenciado veran que hacemos enfasis a unos detalles que faltan respecto a las comunidades que existen en fermat, por ej: el menu se compone por Community, Connections y Notificactions, esto puede anidarse a las ocpioens propuestas como Back to Chat y Home (aunque esto es igual que Community). Tambien falta una vista de perfil de usuario, que al darle click a un contacto o miembro de la comunidad aparezca mostrando foto , nombre, si esta conectado o no, o en su defecto tenga un boton para conectar. Esta vista seria muy similar a la que se hizo para CHT. Seria solo estas 3 cosas: el menu con estas opciones, la vista de perfil de contacto, y el icono de la comunidad @arnaldos @franklinmarcano1970 @Lozadaa.

**Comment by arnaldos** [comment]
@franklinmarcano1970 @josejcb  aquí la secuencia de las mejoras de la comunity 

## ![community](https://cloud.githubusercontent.com/assets/13594347/15193186/67247240-1786-11e6-8941-5cda08f73186.jpg)

![community2](https://cloud.githubusercontent.com/assets/13594347/15193187/672bb960-1786-11e6-9600-f721cd274691.jpg)
