### ISSUE TITLE
Crear un intro animado para los videos relacionados con la plataforma fermat

### ISSUE THREAD

**Issue by jonathanborges3d** [bitDubai/fermat-graphic-design#72]
Viene del #70 

Mi inquietud nace después de ver el video incrustado en la página y notar la ausencia del mismo. Creo que también está relacionado con la imagen personalizada para la vista previa de los videos que menció @Luis-Fernando-Molina en una de las reuniones. 

Pueden ser los logos de fermat PIP, P2P Y DPM, todos parten de la misma imagen del monedero, tendria que modelarse en 3D y compararlos con los logos planos para decidir en qué estilo se ven mejor.

@m471c4 @arnaldos

**Comment by Luis-Fernando-Molina** [comment]
@jonathanborges3d de acuerdo en empezar a modelar los logos de PIP, P2P y DMP en 3d, luego vemos exactamente donde los usamos.

**Comment by jonathanborges3d** [comment]
@DexybelVillanueva Aquí está un caso que propuse hace tiempo. Un intro animado para los videos puede venirnos muy bien ya que estamos en producción. 

Se me ocurre que puede ser el logo de fermat en 3D, que esté texturizado de igual manera por ambos lados, de modo que al voltearlo no se vea blanco o plano.  La animación consistiría en presentar la cartera verde (grande) girando 360º, de la cual salen en forma de abanico las tres carteras que tiene en la parte superior, completa la vuelta y se muestra el nombre "Fermat" en la posición correcta según el logo aprobado. 
Veamos que más pudiese salir a partir de ahí.
