### ISSUE TITLE
Create a Identities-UI/UX-App Design

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#720]
The Chat App was approved in this issue
#525

Reference issue https://github.com/Fermat-ORG/fermat/issues/5373

**Comment by isahq23** [comment]
Here´s my proposal about the identity creation inside the chat.
I personally modified some of the options, the "add" and "picture selection", to what I think and have had seen as the most useful places to work with them.

If there´s any questions, I´m all ears.

![create_identities_chat_issues720_muestra1-12](https://cloud.githubusercontent.com/assets/15214774/13891334/b14ad032-ed22-11e5-8111-27b8f4b76432.jpg)

**Comment by arnaldos** [comment]
@isahq23 i like you work just we need defined if user has a many identities or just one. i like the last version. what do you think about that @franklinmarcano1970 @josejcb @darkestpriest

**Comment by franklinmarcano1970** [comment]
let's leave it for the next version.

**Comment by arnaldos** [comment]
correct we are working to get it ready for when you need it.

**Comment by arnaldos** [comment]
@franklinmarcano1970 @Lozadaa @josejcb Here I show you the suggested changes

![chat_identity-06](https://cloud.githubusercontent.com/assets/13594347/14568834/216e1534-0305-11e6-9327-bd5095bd8b96.jpg)
