### ISSUE TITLE
Representación en 3D ortogonal del Platform Stack

### ISSUE THREAD

**Issue by jonathanborges3d** [bitDubai/fermat-graphic-design#721]
La idea es representar las relaciones de dependencia y jerarquías entre las Plataformas y Capas del sistema. Básicamente serán torres o edificios cilíndricos con los logotipos de cada plataforma en la "terraza" y cuantos pisos se requieran para las capas. La vista debe ser ortogonal, para evitar la distorsión del punto de fuga. Las relaciones entre una y otra plataforma serán representadas como puentes entre los edificios.

En el caso de que algunas de las capas no existan aún en las plataformas se podrán representar como pisos del edificio que solo tienen las columnas y las que existan tendrán como "paredes y ventanas" a los componentes de cada una.

Concepto para los edificios:
(En grises por modelado rápido)

![platform_stack_1](https://cloud.githubusercontent.com/assets/13649739/13830901/203e0824-eba2-11e5-9aba-2ba0dbeb3d1e.jpg)

Así se mostrarían las capas faltantes en las plataformas:

![platform_stack_2](https://cloud.githubusercontent.com/assets/13649739/13830923/46dd6d9e-eba2-11e5-8af1-e68df8121efa.jpg)

@Luis-Fernando-Molina 
Por favor aclárame si cada plataforma tiene la misma cantidad de capas y de ser así cuantas serían en total. Las capas disponibles en cada plataforma son actualizadas constantemente? es decir, debo colocarle las capas que existan en cada plataforma tal cual como está en Fermat DEV?

**Comment by Luis-Fernando-Molina** [comment]
no todas tienen todas las capas.

de vez en cuando aparecen mas, pero es irrelevante para definir el estilo

> debo colocarle las capas que existan en cada plataforma tal cual como está en Fermat DEV?

lo que queremos es definir como tiene que quedar para que luego miguel lo programe

**Comment by jonathanborges3d** [comment]
Una vista a color y con el nombre de la plataforma:
![platform_stack_3](https://cloud.githubusercontent.com/assets/13649739/13831985/e9e6ab66-eba9-11e5-89c0-72f3167ce490.jpg)

**Comment by jonathanborges3d** [comment]
Probando un modelo de puente:
![platform_stack_4](https://cloud.githubusercontent.com/assets/13649739/13832564/92842320-ebaf-11e5-8248-d5ba4733ae5d.jpg)

**Comment by Luis-Fernando-Molina** [comment]
puede ser, yo sacaria los nombres, o los pondria a la altura del piso no en el aire.

**Comment by jonathanborges3d** [comment]
Una vista con los logos que tengo hechos y las posiciones actuales en el stack.
![platform_stack_5](https://cloud.githubusercontent.com/assets/13649739/13881857/f81a3a12-ecf4-11e5-9ad9-cd4e6fc1c585.jpg)

**Comment by jonathanborges3d** [comment]
@Luis-Fernando-Molina Tu opinión por favor. Gracias.

**Comment by Luis-Fernando-Molina** [comment]
la camara debiera estar en la misma posicion que la moneda del readme. Solo se veria el edificio mas cercano, en ningun momento todo junto, o quizas si cuando este en el sistema de Miguel.

Ponele los layers tomando una captura de lo que tiene miguel, y algunas fichitas como ventanas, porque asi es como debieran quedar.

**Comment by jonathanborges3d** [comment]
Ok, entonces para tener claro ésto, cada plataforma pudiese tener las mismas cantidad de capas, es decir son comunes a todas pero algunas no las tienen (al menos por ahora)? Si es así entonces todos los edificios deberían tener la misma cantidad de pisos y colocar en "columnas" a los que no están disponibles para la plataforma.

**Comment by Luis-Fernando-Molina** [comment]
> Ok, entonces para tener claro ésto, cada plataforma pudiese tener las mismas cantidad de capas, es decir son comunes a todas pero algunas no las tienen (al menos por ahora)? 

correcto

> Si es así entonces todos los edificios deberían tener la misma cantidad de pisos y colocar en "columnas" a los que no están disponibles para la plataforma.

correcto

**Comment by gustl-arg** [comment]
@jonathanborges3d propongo una alternativa: 
A) que las superlayers (que existen en todos los edificios), esten pintadas de otro color para saber que son las mismas ..o 
B)  las superlayers podrian ser subsuelos, o sea, niveles bajo tierra: desde lo mas profundo: OSA / BCH / P2P /CER y la planta baja empezaria con la capa:  NETWORK SERVICES ...

**Comment by jonathanborges3d** [comment]
Ok, mientras se decide como representar las superlayers posteo un avance del edifico con algunos componentes en un piso activo. Espero sus comentarios.
![1](https://cloud.githubusercontent.com/assets/13649739/13934783/177195fc-ef86-11e5-8a70-7b4abe58d2fb.jpg)
![2](https://cloud.githubusercontent.com/assets/13649739/13934784/178913bc-ef86-11e5-9016-ae833c882bba.jpg)

**Comment by Luis-Fernando-Molina** [comment]
no estamos graficando superlayers aca, sino plataformas, el dia que lo hagamos seran debajo del suelo

**Comment by Luis-Fernando-Molina** [comment]
lo que si debieras mostrar son los layers, en una parte plana de la torre

**Comment by jonathanborges3d** [comment]
Según lo que entiendo cada piso es una capa, supongo que te refieres a los nombres de éstas, si?
Así como está en el dev.fermat.org

**Comment by jonathanborges3d** [comment]
@Luis-Fernando-Molina Qué te parece colocarle en nombre en geometrías como éstas?
![1](https://cloud.githubusercontent.com/assets/13649739/13971181/4070143a-f060-11e5-904b-544dd2305a3a.jpg)

**Comment by Luis-Fernando-Molina** [comment]
correcto a la flecha amarilla, que debiera estar igual que las fichsa como una gran ventana, pero para eso esa parte del edificio deiera ser plana o algo asi. CAmbia el color de gris a blanco, que si no parece en construccion.

**Comment by Luis-Fernando-Molina** [comment]
> Qué te parece colocarle en nombre en geometrías como éstas?

no puede estar en el aire, le quita realismo.

**Comment by jonathanborges3d** [comment]
Qué te parece así? Queda la torre con un anexo donde pueden colocarse los nombres de las capas en cada espacio amarillo.
![1](https://cloud.githubusercontent.com/assets/13649739/13990764/bb255cda-f0e7-11e5-8e12-ddf3752a0748.jpg)

**Comment by Luis-Fernando-Molina** [comment]
pudiera ser, auque el codigo de arriba quedaria al revez, de pende de donde se lo mire.

proba como queda como parte de la fachada ocupando 4 o 5 ventanas. 

saludos
