### ISSUE TITLE
Create a modal with message how to use a website dev.fermat.org

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#723]
Reference image actual view

![captura de pantalla 38](https://cloud.githubusercontent.com/assets/13594347/13833518/ccab5baa-ebb8-11e5-9895-8d2742b89e51.png)

**Comment by arnaldos** [comment]
@emmysm te comparto el issue en el que vas a trabajar con @Carelsy

**Comment by Carelsy** [comment]
Proposals for message how to use the website dev.fermat.org
![propuesta-1](https://cloud.githubusercontent.com/assets/17755307/14094863/0779c02c-f524-11e5-9260-99e9702a035d.png)
![propuesta-2](https://cloud.githubusercontent.com/assets/17755307/14094864/079aab52-f524-11e5-82e1-8cd4d1a3a5ab.png)
![propuesta-3](https://cloud.githubusercontent.com/assets/17755307/14094865/079e8812-f524-11e5-8708-1af612ec10e0.png)

**Comment by arnaldos** [comment]
@Carelsy plz create an other proposal maybe a modal with the message like this example:
- https://raventools.com/blog/wp-content/uploads/2006/03/modal-718x397.jpg
- http://bashooka.com/wp-content/uploads/2014/08/remodal-1.jpg
- http://blazrobar.com/wp-content/uploads/2016/02/Website-Modal-Windows.jpg

**Comment by arnaldos** [comment]
@Carelsy como vamos con esto ?? han pasado 20 días desde que se abrió el caso, plz hay que darle velocidad a esto para cerrar el caso. @emmysm has le seguimiento a esto plz

**Comment by Carelsy** [comment]
new proposals for the message home Fermat,  Sorry for the delay @arnaldos @emmysm 
![propuesta-4](https://cloud.githubusercontent.com/assets/17755307/14304328/abc50238-fb7b-11e5-993d-05eb8408d918.png)
![propuesta-5](https://cloud.githubusercontent.com/assets/17755307/14304329/abc97f3e-fb7b-11e5-8f81-2df43dec295f.png)
![propuesta-6](https://cloud.githubusercontent.com/assets/17755307/14304330/abd04c6a-fb7b-11e5-9d7a-7def4140c746.png)

**Comment by emmysm** [comment]
3 propuestas más en base a la opción número 2 @Carelsy :smile:

**Comment by Carelsy** [comment]
![propuesta-7](https://cloud.githubusercontent.com/assets/17755307/14337331/b69e1daa-fc36-11e5-80fc-f104e6988b29.png)
![propuesta-8](https://cloud.githubusercontent.com/assets/17755307/14337332/b69e6b34-fc36-11e5-8ef0-279aa0f94d82.png)
![propuesta-9](https://cloud.githubusercontent.com/assets/17755307/14337333/b6a36c92-fc36-11e5-9994-cfee8ad80e56.png)
![propuesta-10](https://cloud.githubusercontent.com/assets/17755307/14337334/b6c591dc-fc36-11e5-9eb8-c3f68595852a.png)

**Comment by emmysm** [comment]
@Carelsy, la segunda propuesta. Solo la X cámbiala al lado derecho, y subes al repositorio los archivos

**Comment by Carelsy** [comment]
@emmysm @arnaldos @Luis-Fernando-Molina 
![propuesta-11](https://cloud.githubusercontent.com/assets/17755307/14370760/bdc536c6-fcfa-11e5-9d74-6a8e641738db.png)

**Comment by arnaldos** [comment]
listo deja este modal !! @Carelsy genera los editables y subelos al repo @emmysm asegúrate que llegue a manos de @Miguelcldn para que lo aplique en http://dev.fermat.org/

**Comment by Miguelcldn** [comment]
Fue mostrado a Molina y lo aprobó, ya creo el issue para implementarlo. (Este issue puede cerrarse si se desea, igual en el issue que yo cree saldrá linkeado aquí)

**Comment by arnaldos** [comment]
emmy asegurate de eso que dice miguel !!!

**Comment by ricardo460** [comment]
@Carelsy @emmysm Me podrían facilitar el icono de advertencia utilizado.

**Comment by arnaldos** [comment]
@ricardo460 como vamos con esto ?

**Comment by ricardo460** [comment]
@arnaldos si, ya esta en producción.
