### ISSUE TITLE
Version 3D infografia N°2 Internet/ Internet of things/ Internet of People

### ISSUE THREAD

**Issue by DexybelVillanueva** [bitDubai/fermat-graphic-design#726]
viene de #690

**Comment by DexybelVillanueva** [comment]
Version N°1 de prueba
![internet](https://cloud.githubusercontent.com/assets/16962860/13896531/ac6b9964-ed60-11e5-981e-524bcea63b5a.png)

**Comment by DexybelVillanueva** [comment]
@Luis-Fernando-Molina @jonathanborges3d 

1era Propuesta

1)![untitled 290](https://cloud.githubusercontent.com/assets/16962860/13935974/a59d83b2-ef8c-11e5-8290-59b7a07eece5.jpg)

2)![untitled 291](https://cloud.githubusercontent.com/assets/16962860/13935975/a5a675c6-ef8c-11e5-9198-cb844c210fa8.jpg)

3)![untitled 292](https://cloud.githubusercontent.com/assets/16962860/13935995/e04e8c72-ef8c-11e5-9fd0-0f6c66c50d7e.jpg)

**Comment by Luis-Fernando-Molina** [comment]
hacete un diagrama para cada cosa por separado, podes mantener este caso que los junte, pero me interesa cada uno de los 3 poer separados: Revisa el README del media kit por la ultima version de cada uno de ellos (individual).

**Comment by DexybelVillanueva** [comment]
Infografia de Internet(alta resolución) 

1)![infografia internet 1 305](https://cloud.githubusercontent.com/assets/16962860/13972608/6333cc26-f06c-11e5-9baf-8a8c2698fef5.jpg)

2)![infografia internet 1 306](https://cloud.githubusercontent.com/assets/16962860/13972610/6570ab58-f06c-11e5-9fee-db69805650b2.jpg)

**Comment by DexybelVillanueva** [comment]
Infografia (Internet of things) alta resolución 

1)![infografia of things 309](https://cloud.githubusercontent.com/assets/16962860/14005966/8fa6c79e-f13a-11e5-8981-86c8d4f99ccb.jpg)

2)![infografia of things 310](https://cloud.githubusercontent.com/assets/16962860/14005967/8faf760a-f13a-11e5-8d0a-b3fefb93d290.jpg)

**Comment by Luis-Fernando-Molina** [comment]
los dispositivos que elegiste para la internet of things no son los que la representan. Fijate en los diagramas 2d que se hicieron que tienen.

**Comment by DexybelVillanueva** [comment]
Infografia (Internet of things) 

1)![infografia de intenet of things 313](https://cloud.githubusercontent.com/assets/16962860/14085512/1704b52c-f4ea-11e5-8025-fd7120e4f4d0.jpg)

2)![infografia de intenet of things 315](https://cloud.githubusercontent.com/assets/16962860/14085513/170bcb3c-f4ea-11e5-9347-4f1eb38c6a53.jpg)

**Comment by DexybelVillanueva** [comment]
@Luis-Fernando-Molina  Infografia (Internet of people)alta resolución

1)![internet of people 317](https://cloud.githubusercontent.com/assets/16962860/14124000/0cca6910-f5cd-11e5-8e41-e3852a75aabf.jpg)

2)![internet of people 319](https://cloud.githubusercontent.com/assets/16962860/14124305/98bff31c-f5ce-11e5-8bf2-d3a51833bfde.jpg)
