### ISSUE TITLE
Graphic Internet of People 3th part 

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#727]

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina 

![graphics_internet-of-people](https://cloud.githubusercontent.com/assets/13594347/13925380/3beeda2e-ef5a-11e5-8eb7-00fa0d01397a.png)

**Comment by arnaldos** [comment]
Version 2 texto verde en el titulo

![graphics_internet-of-people2](https://cloud.githubusercontent.com/assets/13594347/13925502/af3d7af8-ef5a-11e5-94b9-d33756d6de60.png)

**Comment by Luis-Fernando-Molina** [comment]
Version 2 ok

**Comment by arnaldos** [comment]
perfecto ya  lo subo al media kit
