### ISSUE TITLE
Create a Banner to identity chat 

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#728]
Size1024x500

Reference issue #617

**Comment by isahq23** [comment]
Ok, first proposal keeping the "vendetta style" used in other identity banners.

![banner_identity_chat_issue728](https://cloud.githubusercontent.com/assets/15214774/13968097/d9765f04-f04c-11e5-9132-98d2743fac73.jpg)

**Comment by isahq23** [comment]
Proposal #2 

![banner_identity_chat_issue728_2](https://cloud.githubusercontent.com/assets/15214774/13996041/2fa9ce54-f0fe-11e5-8d5b-3e81819ef192.jpg)

**Comment by arnaldos** [comment]
@isahq23 make a new version plz.

**Comment by isahq23** [comment]
Proposal #3!

![banner_identity_chat_issue728_3](https://cloud.githubusercontent.com/assets/15214774/14122751/d0a01a80-f5c6-11e5-916e-0e438db2e916.jpg)

**Comment by arnaldos** [comment]
@isahq23 use correct sizes 1024x500 and use the choose logo in this issue #736

**Comment by isahq23** [comment]
@arnaldos I´m using the right sizes xD but I export in a small version so the weight don´t take to long to upload here. I´ll do the edition.

**Comment by isahq23** [comment]
2 Options for the banner:

![banner_identity_chat_issue728_1](https://cloud.githubusercontent.com/assets/15214774/14152822/d7292f00-f67e-11e5-974e-7517fd4364e3.png)

![banner_identity_chat_issue728_2](https://cloud.githubusercontent.com/assets/15214774/14152824/dc4d57d6-f67e-11e5-8647-3b3948cf0e89.png)

PS: both are in the right size and resolution to be use in the folder.

**Comment by arnaldos** [comment]
vesion 1 just change the typography. is the same typografy for the chat banner ??

**Comment by isahq23** [comment]
@arnaldos I used Helvetica. Do you want another one?

**Comment by arnaldos** [comment]
@isahq23 the typografy is musket, I send you for slack. change the typo and update all files.

**Comment by isahq23** [comment]
@arnaldos here they are, I´m uploading the repo

![banner_identity_chat_issue728_1](https://cloud.githubusercontent.com/assets/15214774/14289796/2b004ab8-fb26-11e5-822c-e155246a6b7a.png)

![banner_identity_chat_issue728_2](https://cloud.githubusercontent.com/assets/15214774/14289799/2dd6271c-fb26-11e5-8448-178e04c32d26.png)

**Comment by arnaldos** [comment]
@isahq23 vesion 1 :+1:
