### ISSUE TITLE
Create a Banner to community chat

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#729]
size 1024x500

Reference issue #617

**Comment by adryx83** [comment]
Buen día acá dejo el banner! 

![banner chat community](https://cloud.githubusercontent.com/assets/17273349/13987668/d7d3d332-f0da-11e5-845a-2d62646a9a89.jpg)

**Comment by arnaldos** [comment]
Busca que el banner refleje la actividad que va a representar la aplicación, en este caso la conexión entre varias personas. También crea un icono que te permita identificar que se trata de una community (Ya creo el caso para el issue)

**Comment by arnaldos** [comment]
se definio este banner ![banner_comunity](https://cloud.githubusercontent.com/assets/13594347/14471318/cae9f128-00b7-11e6-9eaf-e4b5fe7be722.png)
