### ISSUE TITLE
Crear un logo cuadrado para bitDubai

### ISSUE THREAD

**Issue by Luis-Fernando-Molina** [bitDubai/fermat-graphic-design#73]
En varios lugares como por ejemplo en github.com te dejan poner una imagen de perfil, en este caso para una compañía. En el caso de bitDubai no hay nada de lo que tenemos que encaje bien en ese formato cuadrado.

**Comment by m471c4** [comment]
Esto lo podemos hacer una vez que hayamos definido el isologo final, se creará una acepción para formatos cuadrados (como imágenes de perfil).

**Comment by m471c4** [comment]
Dos versiones del isologo BitDubai "cuadrado". El color de fondo es únicamente para que vean cómo quedan en este formato. Particularmente prefiero la segunda opción ya que la lectura es mejor. Espero sus comentarios @Luis-Fernando-Molina y @arnaldos 

![isologo_sq1](https://cloud.githubusercontent.com/assets/13468350/9287876/fa6a3c44-42f5-11e5-946c-bde0cfa8256f.png)

![isologo_sq2](https://cloud.githubusercontent.com/assets/13468350/9287877/fa768f94-42f5-11e5-9b7d-76ffcce78b51.png)

**Comment by Luis-Fernando-Molina** [comment]
@m471c4  Ninguna de las dos se puede reducir mucho como para una imagen de perfil semi icónica. Por favor probá alineando la i de dubai con la t de bit y sacandole todo el borde posible.

**Comment by Luis-Fernando-Molina** [comment]
@m471c4 otra cosa, ese color de fondo, debe quedar asi?

**Comment by arnaldos** [comment]
Si coincido contigo @m471c4 apunto por la versión 2, es el que esta mejor equilibrado peso, forma y colores.

**Comment by m471c4** [comment]
Con los cambios requeridos:

![bitdsqmin_min](https://cloud.githubusercontent.com/assets/13468350/9323076/21b766ee-4546-11e5-8567-53d5e6a9df23.png)
![bitdsqmin](https://cloud.githubusercontent.com/assets/13468350/9323057/f9fb516a-4545-11e5-81d9-886ca6411b8b.png)
![bitdsq](https://cloud.githubusercontent.com/assets/13468350/9323058/f9fc6a96-4545-11e5-854d-b65df0335d4c.png)

@Luis-Fernando-Molina, el fondo, como expliqué, era solo para ver la forma cuadrada. Le dejé un poco de aire (blanco, al rededor) para no ahogarlo tanto dentro del formato. Dime si te parece bien.

**Comment by Luis-Fernando-Molina** [comment]
Proba que eje del palito de la u de Dubai conocida con el eje del palito de la tarde de bit. 

También proba que la. Palabra en árabe tenga el mismo ancho que Dubai escalandola please.

**Comment by m471c4** [comment]
Con los cambios requeridos:

![bitdsqmin_min](https://cloud.githubusercontent.com/assets/13468350/9373383/8d79ae78-46b3-11e5-90e4-29bfd38d1e32.png)
![bitdsq](https://cloud.githubusercontent.com/assets/13468350/9373385/9117f6de-46b3-11e5-8bf5-7d2e0d9a34c5.png)

**Comment by m471c4** [comment]
Versiones finales en sus acepciones para el isologo BitDubai cuadrado. El borde del cuadrado no lleva la línea negra, lo puse solo para que se vea el límite de la imagen:

![bitdsqmin_min](https://cloud.githubusercontent.com/assets/13468350/9390981/4420b380-473e-11e5-9778-3396d87c574d.png)
![bitdsqcolor](https://cloud.githubusercontent.com/assets/13468350/9390989/4c03ecd4-473e-11e5-8c36-8fb96d156885.png)
![bitdsqpos](https://cloud.githubusercontent.com/assets/13468350/9390990/4c0f9700-473e-11e5-9945-563777ff6718.png)
![bitdsqneg](https://cloud.githubusercontent.com/assets/13468350/9390993/5247db3c-473e-11e5-9105-29e40bd6081e.png)
![bitdsqout](https://cloud.githubusercontent.com/assets/13468350/9390994/5279ea8c-473e-11e5-8e77-b62ef41b0fcf.png)

**Comment by arnaldos** [comment]
@m471c4 @Luis-Fernando-Molina @jonathanborges3d me parece que la aplicación del logo en su versión cuadrada esta totalmente equilibrada.

**Comment by Luis-Fernando-Molina** [comment]
De acuerdo , subir los fuentes al repo y cerrar el caso.
