### ISSUE TITLE
Graphic Component_types

### ISSUE THREAD

**Issue by ivonnesantos** [bitDubai/fermat-graphic-design#730]
Aplicar mismo estilo que se ha venido trabajando ejemplo #717 

**Grafico Suministrado por luis**
![component types-01](https://cloud.githubusercontent.com/assets/15238660/13970342/463f1290-f05a-11e5-98c6-6ff8f7091eaa.png)

**Comment by ivonnesantos** [comment]
![component_types-01](https://cloud.githubusercontent.com/assets/15238660/13970534/863ee9fa-f05b-11e5-8479-f18643b60eb9.png)

Le deje la flechas azules porque en un grafico anterior se trabajo en azules 

@Luis-Fernando-Molina

**Comment by Luis-Fernando-Molina** [comment]
Muy bien Ivonne! esta perfecto!

**Comment by Luis-Fernando-Molina** [comment]
aunque no hacia falta la referencia de abajo, sacasela desde la linea verde horizontal para abajo por favor

**Comment by ivonnesantos** [comment]
![component_types-01](https://cloud.githubusercontent.com/assets/15238660/13989843/4e30b398-f0e4-11e5-96c2-8379f11e9ef6.png)
@Luis-Fernando-Molina
