### ISSUE TITLE
Graphic Component_encapsulation

### ISSUE THREAD

**Issue by ivonnesantos** [bitDubai/fermat-graphic-design#731]
**Informacion suministrada por Luis**
![encapsulation-01](https://cloud.githubusercontent.com/assets/15238660/13972655/b7ecbe26-f06c-11e5-8de0-558c25f21c6a.png)

**Comment by ivonnesantos** [comment]
![component_encapsulation-01](https://cloud.githubusercontent.com/assets/15238660/13972679/e82a8618-f06c-11e5-9115-b0bdde2d1da1.png)
@Luis-Fernando-Molina

**Comment by Luis-Fernando-Molina** [comment]
Perfecto Ivonne! :+1:
