### ISSUE TITLE
Graphic Fermat Workflows

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#732]
Reference

![untitled-1](https://cloud.githubusercontent.com/assets/13594347/13973417/b47f9ab2-f074-11e5-8816-0e5d0931ad28.png)

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina te comparto 3 versiones con variación en los tonos de los componentes

#### Version 1

![fermat-workflow-1](https://cloud.githubusercontent.com/assets/13594347/13973426/d180be0c-f074-11e5-996a-3c53a6049469.png)

#### Version 2

![fermat-workflow-2](https://cloud.githubusercontent.com/assets/13594347/13973427/d1a7419e-f074-11e5-876d-8915de361599.png)

#### Version 3

![fermat-workflow-3](https://cloud.githubusercontent.com/assets/13594347/13973428/d1bd1596-f074-11e5-8229-4e38f89c40ff.png)

**Comment by Luis-Fernando-Molina** [comment]
Perfecto! use la primera :+1:

**Comment by arnaldos** [comment]
ok perfecto !!!
