### ISSUE TITLE
Create a logo to chat community 

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#734]

**Comment by adryx83** [comment]
Buenos días, aqui dejo la primera propuesta del logo, trate de vincularlo con el logo del chat, siendo esta como una aplicación paralela y como el diseño es bastante parecido al chat trate de no salirme del estilo. Nose que opinas tu @arnaldos 

![logo cummunity](https://cloud.githubusercontent.com/assets/17273349/14111610/253428f2-f595-11e5-9e22-cf01cf4b8f62.jpg)

**Comment by arnaldos** [comment]
@adryx83  prueba 3 personitas dentro del globito

**Comment by adryx83** [comment]
Propuesta #2 y #3 @arnaldos 

![logo cummunity2](https://cloud.githubusercontent.com/assets/17273349/14119032/11bf2710-f5b6-11e5-9ec3-3c43dd0587dc.jpg)

**Comment by arnaldos** [comment]
@adryx83 usa el mismo globo del logo de fermat chat y aplica las personas internamente dentro del globo

**Comment by adryx83** [comment]
Feliz Tarde Propuesta #4 @arnaldos 

![logo cummunity3](https://cloud.githubusercontent.com/assets/17273349/14154825/7042df84-f688-11e5-9da3-3a6bb9a4a2e2.jpg)

**Comment by arnaldos** [comment]
perfecto !! aprobado el icono usa este para el banner :+1: sube los archivos al repo plz

**Comment by adryx83** [comment]
Ok! entendido @arnaldos
