### ISSUE TITLE
logo for the head bitdubai.com

### ISSUE THREAD

**Issue by ivonnesantos** [bitDubai/fermat-graphic-design#735]
create logo for the head in blue tones, the full width.
crear logo para el cabezal en tonos azul, el ancho completo.

**Comment by ivonnesantos** [comment]
![fermat_3d_retina_1600](https://cloud.githubusercontent.com/assets/15238660/14085812/ce27ac40-f4eb-11e5-8d00-50b6acf5f0ff.png)
@Luis-Fernando-Molina

**Comment by arnaldos** [comment]
esto ya esta aplicado cierro el caso
