### ISSUE TITLE
Create a logo to chat Identiy

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#736]

**Comment by isahq23** [comment]
Here are my proposals.

![logo_chat_identity_issue736_proposal](https://cloud.githubusercontent.com/assets/15214774/14119404/d4fb9bea-f5b7-11e5-82a7-a882bc52cc09.png)

**Comment by arnaldos** [comment]
@isahq23 use version 2 upload all files to repo.

**Comment by isahq23** [comment]
I just did the export of the files in the sizes you told me so, I´ll refresh the repo right now.

**Comment by arnaldos** [comment]
nice !!!! i close thit issue we finish with this
