### ISSUE TITLE
Create Logos for P2P Services / Long term job search	

### ISSUE THREAD

**Issue by emmysm** [bitDubai/fermat-graphic-design#737]
A company or employer is looking to hire a person for a specific position and creates a job search. The other person is looking for a job opportunity, completes a profile and applies to the searched that are most appealing. 
It comes from the case #708

**Comment by proseuz** [comment]
@emmysm  @arnaldos @Luis-Fernando-Molina 
Propuesta 1
![pantalla search job 2](https://cloud.githubusercontent.com/assets/17308060/14100456/74fa04b2-f557-11e5-8bce-1f6c74e72326.png)
Propuesta 2
![pantalla search job 3](https://cloud.githubusercontent.com/assets/17308060/14100457/7512b138-f557-11e5-9756-7ea41d9e5fc6.png)
Propuesta 3
![pantalla search job 4](https://cloud.githubusercontent.com/assets/17308060/14100458/752d7644-f557-11e5-9ab4-d373d890d694.png)
Propuesta 4
![pantalla search job 5](https://cloud.githubusercontent.com/assets/17308060/14100459/753ee7da-f557-11e5-919c-b4f603cd5138.png)
Propuesta 5
![pantalla search job 1](https://cloud.githubusercontent.com/assets/17308060/14100460/75525a04-f557-11e5-81d4-ede6db4c0143.png)

**Comment by emmysm** [comment]
@arnaldos cómo vamos con este caso?

**Comment by arnaldos** [comment]
propuesta 4 con la persona del 3 adentro del circulo

**Comment by proseuz** [comment]
@arnaldos 

Proposal 1
![pantalla search job 6](https://cloud.githubusercontent.com/assets/17308060/14368726/709a6c9c-fce9-11e5-8588-b649c0111b56.png)

**Comment by emmysm** [comment]
@jhonmarquez92  @arnaldos en mi opinión se ve mejor sin el circulo, o en su defecto que el stroke sea más delgado.

**Comment by arnaldos** [comment]
@jhonmarquez92 prueba esas dos versiones que te comenta emmy 
1- sin el circulo
2- el espesor del aro mas delgado 
3- prueba haciendo uno colocando una sombra a 45 como los flat icons a ver que tal

**Comment by proseuz** [comment]
@arnaldos 
1
![pantalla search job 8](https://cloud.githubusercontent.com/assets/17308060/14399258/aa75d660-fdb4-11e5-93f9-dfa49716637c.png)
2
![pantalla search job 9](https://cloud.githubusercontent.com/assets/17308060/14399187/09d7c894-fdb4-11e5-8207-e4e8272f137f.png)
3
![pantalla search job 10](https://cloud.githubusercontent.com/assets/17308060/14399189/0a1c2020-fdb4-11e5-943a-d262c895dc6e.png)
4
![pantalla search job 11](https://cloud.githubusercontent.com/assets/17308060/14399190/0a335c4a-fdb4-11e5-828b-d9e4c0274a6e.png)

**Comment by arnaldos** [comment]
@jhonmarquez92 version 1 se ve mejor sin el aro como decía emmy
