### ISSUE TITLE
Create Logo for P2P Services / Freelance jobs / Gigs	

### ISSUE THREAD

**Issue by emmysm** [bitDubai/fermat-graphic-design#738]
A company or independent worker is looking for a person to do a specific task without any contract or long term relationship.   

it comes from the case #708

**Comment by proseuz** [comment]
@Luis-Fernando-Molina @emmysm @arnaldos
El colibrí por su característico rápido aleteo representa muy bien este modelo de negocios sin contratos a largo plazo, además simboliza la libertad que permite trabajar de manera freelance. 
Propuesta 1
![pantalla freelance 2](https://cloud.githubusercontent.com/assets/17308060/14100711/47759aea-f559-11e5-903a-abc6f9af6bb5.png)
Propuesta 2
![pantalla freelance 3](https://cloud.githubusercontent.com/assets/17308060/14100712/4787e16e-f559-11e5-82d9-c363e41b533f.png)
Propuesta 3
![pantalla freelance 4](https://cloud.githubusercontent.com/assets/17308060/14100713/47a0f000-f559-11e5-8af4-eca3a960240a.png)
Propuesta 4
![pantalla freelance 1](https://cloud.githubusercontent.com/assets/17308060/14100714/47b41022-f559-11e5-88d9-3149d1d5c81c.png)

**Comment by emmysm** [comment]
A mí me gustó la primera opción, pienso que puede andar. Qué dicen ustedes @arnaldos @Luis-Fernando-Molina

**Comment by emmysm** [comment]
@arnaldos cómo vamos con este caso?

**Comment by arnaldos** [comment]
esta muy similar a freelancer replantea la sintesis del ave, o genera otra version

**Comment by proseuz** [comment]
@arnaldos @emmysm 
Propuesta 1
![pantalla freelance 13](https://cloud.githubusercontent.com/assets/17308060/14448359/d9b9e234-0031-11e6-9c97-689ce7d64655.png)
Propuesta 2
![pantalla freelance 12](https://cloud.githubusercontent.com/assets/17308060/14448368/dc1378e2-0031-11e6-87d2-f0ac3b31b60a.png)

Propuesta 3
![pantalla freelance 5](https://cloud.githubusercontent.com/assets/17308060/14448361/da4fc858-0031-11e6-9aff-68e7ce53f6f4.png)
Propuesta 4
![pantalla freelance 6](https://cloud.githubusercontent.com/assets/17308060/14448362/da6fadee-0031-11e6-9071-0e46386bfc01.png)
Propuesta 5
![pantalla freelance 11](https://cloud.githubusercontent.com/assets/17308060/14448367/db949982-0031-11e6-9039-2ca4a98dc23f.png)
Propuesta 6
![pantalla freelance 8](https://cloud.githubusercontent.com/assets/17308060/14448364/db000010-0031-11e6-8b9f-bdd46c8a8c02.png)
Propuesta 7
![pantalla freelance 9](https://cloud.githubusercontent.com/assets/17308060/14448365/db1aa294-0031-11e6-8841-81a3a2f760c3.png)
Propuesta 8
![pantalla freelance 10](https://cloud.githubusercontent.com/assets/17308060/14448366/db71e0f4-0031-11e6-9e3c-d34e897fa234.png)
Propuesta 9
![pantalla freelance 14](https://cloud.githubusercontent.com/assets/17308060/14448360/da40e770-0031-11e6-8a8d-e6182b4d1367.png)

**Comment by proseuz** [comment]
correciones sugeridas a partir de la propuesta 9 y 6 @arnaldos 

Versión 1
![pantalla freelance 16](https://cloud.githubusercontent.com/assets/17308060/14655625/eb592628-064c-11e6-9ffd-109596590db3.png)

Versión 2
![pantalla freelance 15](https://cloud.githubusercontent.com/assets/17308060/14655293/6a66995c-064b-11e6-95d4-10d942810909.png)

**Comment by arnaldos** [comment]
@jhonmarquez92  versión 1 :+1:  sube los archivos
