### ISSUE TITLE
Create Logo for P2P Services / Household services	

### ISSUE THREAD

**Issue by emmysm** [bitDubai/fermat-graphic-design#739]
A home owner is looking for a person to take care of a manual task. A service provider is looking to find more opportunities.   

It comes from the case #708

**Comment by proseuz** [comment]
@arnaldos @emmysm @Luis-Fernando-Molina 

Propuesta 1
![pantalla household 2](https://cloud.githubusercontent.com/assets/17308060/14100267/06674c36-f556-11e5-8d03-7d64ce15f383.png)
Propuesta 2
![pantalla household 3](https://cloud.githubusercontent.com/assets/17308060/14100269/066b464c-f556-11e5-8f72-530dfce5d083.png)
Propuesta 3
![pantalla household 4](https://cloud.githubusercontent.com/assets/17308060/14100268/066af9f8-f556-11e5-8472-a41b99996b52.png)
Propuesta 4
![pantalla household 5](https://cloud.githubusercontent.com/assets/17308060/14100270/06701a14-f556-11e5-8714-81304ae2c450.png)
Propuesta 5
![pantalla household 1](https://cloud.githubusercontent.com/assets/17308060/14100271/0679bfa6-f556-11e5-8d92-9b2a586c25f6.png)

**Comment by arnaldos** [comment]
@jhonmarquez92 partiendo de la versión 4 genera otras propuestas plz, plantea otros colores combinaciones etc

**Comment by proseuz** [comment]
@arnaldos @emmysm  
Propuesta 1
![householdp 3](https://cloud.githubusercontent.com/assets/17308060/14319043/726bffb0-fbd9-11e5-8e4e-a51a9eb57084.png)
Propuesta 2
![householdp 4](https://cloud.githubusercontent.com/assets/17308060/14319044/727ee116-fbd9-11e5-86b6-c74acbeceb11.png)
Propuesta 3
![householdp 5](https://cloud.githubusercontent.com/assets/17308060/14319045/728fd1ba-fbd9-11e5-867f-625e0e99606f.png)
Propuesta 4
![householdp 6](https://cloud.githubusercontent.com/assets/17308060/14319046/72a279c8-fbd9-11e5-83f5-a41717bef1a4.png)
Propuesta 5
![householdp 7](https://cloud.githubusercontent.com/assets/17308060/14319048/72b55d0e-fbd9-11e5-8b7c-d2c19156b683.png)
Propuesta 6
![householdp 8](https://cloud.githubusercontent.com/assets/17308060/14319049/72cc37d6-fbd9-11e5-8a65-1dd30d83b7fc.png)
Propuesta 7
![householdp 2](https://cloud.githubusercontent.com/assets/17308060/14319859/a00b83d4-fbdc-11e5-82e3-1abc5f329b11.png)
Propuesta 8
![householdp 1](https://cloud.githubusercontent.com/assets/17308060/14319860/a01cf952-fbdc-11e5-97ed-18ee45d66873.png)

**Comment by arnaldos** [comment]
propuesta 2 :+1:
