### ISSUE TITLE
Crear un footer para los emails de bitDubai

### ISSUE THREAD

**Issue by Luis-Fernando-Molina** [bitDubai/fermat-graphic-design#74]
El **Footer** o firma digital debe llevar los siguientes requisitos:
- Nombre de la persona 
- Cargo de la persona 
- Foto de la persona 
- Teléfono de la persona 
- Logo de la empresa **(bitDubai)**

**Comment by m471c4** [comment]
@Luis-Fernando-Molina ¿podrías decirme si tienes algún tamaño (o ejemplo) de cómo te gustaría que se viera?

**Comment by Luis-Fernando-Molina** [comment]
Mmmmm,  no tengo,  pero me gustaría que incluya una foto de la persona.

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina Primeras versiones para el footer de los E-mail, inclui un QR Code que te direcciona al Website de bitDubai. se puede escanear con cualquier dispositivo.

Versión 1
![firma-digital](https://cloud.githubusercontent.com/assets/13594347/10922670/9ac9bb50-824e-11e5-89d6-2e576294bd06.png)

Versión 2
![firma-digital2](https://cloud.githubusercontent.com/assets/13594347/10922671/9b4bb61e-824e-11e5-91f7-e3910e7951da.png)

**Comment by Luis-Fernando-Molina** [comment]
Me gusta la version con foto y la diagramacion , que este doblada etc. (Vrsion 2)
Mostrala mas grande para ver los detalles.

Me imagino que se puede mejorar la tipografia y algunos detalles.

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina  si las tipografías las podemos mejorar, yo coloque iconos de las redes sociales. Se van a manejar las redes sociales en el footer ?

**Comment by Luis-Fernando-Molina** [comment]
No estoy seguro que se pueda poner un icono clickeable... fijate si lo logras ahi hablamos

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina  perfecto !!! voy a ver como lo integro en la pieza

**Comment by Neoperol** [comment]
@arnaldos 
@Luis-Fernando-Molina 

Si se puede colocar los iconos clickeable para la firma. Lo que hay que revisar es el ancho máximo. Son unos 580px. 
Lo que hay que cuadrar ahí es que elementos son Imágenes y que elementos son editables. Para lograr la tipografía con el nombre de Luis y la sombra hay que colocar eso en imagen porque ese tipo de tipografías no se puede ingresar en la firma.

**Comment by arnaldos** [comment]
@Neoperol Cuando hablas de las tipografías, te refieres a que use tipografías web tipo roboto algo asi ?

**Comment by Neoperol** [comment]
@arnaldos 
Si, la firma se renderiza con las fuentes que tiene instalada la computadora, no se pueden usar fuentes externas como se hace en las paginas webs. Por lo que la fuente que estas usando para el nombre del usuario que esta al lado de la foto hay que expotar todo eso como imagen. 
Lo que se deben colocar en html son la de la información del usuario, como por ejemplo; los teléfonos , el correo y el sitio web.

Decidan los cambios y me pasas el PSD para hacerla en HTML.

**Comment by arnaldos** [comment]
@Neoperol  vale perfecto !!!
