### ISSUE TITLE
Create Logo for P2P Services / Connections

### ISSUE THREAD

**Issue by emmysm** [bitDubai/fermat-graphic-design#740]
Professionals want to connect and create a work network that can help them learn, get jobs or recruit others.   

It comes from the case #708

**Comment by proseuz** [comment]
@Luis-Fernando-Molina  @emmysm @arnaldos 
Propuesta 1
![pantalla connetion1](https://cloud.githubusercontent.com/assets/17308060/14100805/db5fa962-f559-11e5-9bbd-05a9d1db4352.png)
Propuesta 2
![pantalla connetion 2](https://cloud.githubusercontent.com/assets/17308060/14100806/db7709ea-f559-11e5-9fb7-7b21c27977df.png)
Propuesta 3
![pantalla connetion 3](https://cloud.githubusercontent.com/assets/17308060/14100807/db8d1d34-f559-11e5-89dc-304e06ace564.png)
Propuesta 4
![pantalla connetion 4](https://cloud.githubusercontent.com/assets/17308060/14100808/dba76dce-f559-11e5-831e-f9cffe0ae32e.png)

**Comment by arnaldos** [comment]
@jhonmarquez92 prueba colocar el tipito principal solo sobre un cuadro llevando los brazos hacia las esquinas el cuadrado puede tener las esquinas redondas prueba como se ve mejor, si  tienes que ajustar los vectores para que se adapte mejor a la forma hazlo o si quieres incluir algún elemento eres libre.

**Comment by proseuz** [comment]
Propuesta 1
![connectionp 1](https://cloud.githubusercontent.com/assets/17308060/14305862/b52e1ecc-fb8a-11e5-915a-6b441b16bd46.png)
Propuesta 2
![connectionp 2](https://cloud.githubusercontent.com/assets/17308060/14305863/b5424532-fb8a-11e5-85f0-d462f7212650.png)
Propuesta 3
![connectionp 3](https://cloud.githubusercontent.com/assets/17308060/14305963/e2505cfc-fb8b-11e5-821c-96d5d9e0ac20.png)
Propuesta 4
![connectionp 4](https://cloud.githubusercontent.com/assets/17308060/14305860/b4e05ec6-fb8a-11e5-8d2f-f038134a5076.png)
Propuesta 5
![connectionp 5](https://cloud.githubusercontent.com/assets/17308060/14305861/b4f3a184-fb8a-11e5-9cbd-bd2a29c2bd69.png)

**Comment by arnaldos** [comment]
va mas por la propuesta 1 con tonos azules aun no me convence del todo siento le falta mas color, la sintesis si esta bien

**Comment by proseuz** [comment]
@arnaldos 
Color proposals
Proposal 1
![connectionp 12](https://cloud.githubusercontent.com/assets/17308060/14368238/5a6b88fa-fce6-11e5-895e-a648dfeebcdd.png)
Proposal 2
![connectionp 6](https://cloud.githubusercontent.com/assets/17308060/14368231/59f225c8-fce6-11e5-83f5-fd7a6abac9a7.png)
Proposal 3
![connectionp 7](https://cloud.githubusercontent.com/assets/17308060/14368233/5a0a0cb0-fce6-11e5-8aeb-7fd36bac8219.png)
Proposal 4
![connectionp 8](https://cloud.githubusercontent.com/assets/17308060/14368234/5a1b3a30-fce6-11e5-9bc8-62e03425a4ea.png)
Proposal 5
![connectionp 9](https://cloud.githubusercontent.com/assets/17308060/14368235/5a305438-fce6-11e5-83c4-24df5ba35e8e.png)
Proposal 6
![connectionp 10](https://cloud.githubusercontent.com/assets/17308060/14368236/5a45716a-fce6-11e5-8b0c-f37da2acb1cc.png)
Proposal 7
![connectionp 11](https://cloud.githubusercontent.com/assets/17308060/14368237/5a56fb1a-fce6-11e5-8376-235dbbf20e4c.png)
Proposal 8

![connectionp 13](https://cloud.githubusercontent.com/assets/17308060/14368230/59d25cfc-fce6-11e5-9d7c-78c8cd45f296.png)

**Comment by arnaldos** [comment]
@jhonmarquez92 propuesta 6 elimina la sombra del personaje, y prueba lo siguiente:
1- Aplica un "drop shadow" por debajo del personaje.
2- Aplica una sombra unicamente por debajo de los brazos a nivel del borde, solo hacia al lado de los morados.

**Comment by proseuz** [comment]
@arnaldos 
1
![connectionp 14](https://cloud.githubusercontent.com/assets/17308060/14398428/ec4c84a0-fdad-11e5-829b-5048b217fe95.png)

2
![connectionp 15](https://cloud.githubusercontent.com/assets/17308060/14398427/ec38b2ea-fdad-11e5-922e-2ff67329b755.png)

**Comment by arnaldos** [comment]
@jhonmarquez92  Versión 2 solo probemos darle un poco de espacio de al circulo y creo que con eso ya estaríamos

**Comment by proseuz** [comment]
@arnaldos 
![connectionp 15](https://cloud.githubusercontent.com/assets/17308060/14404139/54a9876a-fe39-11e5-8d5c-9ce0086db99e.png)

**Comment by emmysm** [comment]
@arnaldos ready?

**Comment by arnaldos** [comment]
@jhonmarquez92 @emmysm listo esto !! 
sube los archivos correspondientes al repo :+1:
