### ISSUE TITLE
Generate a  Banner for Fan Community to Music Player App

### ISSUE THREAD

**Issue by proseuz** [bitDubai/fermat-graphic-design#742]

**Comment by isahq23** [comment]
@arnaldos first proposals for Fan Community

![banner_fan_community_m1](https://cloud.githubusercontent.com/assets/15214774/14646077/f97a0482-0621-11e6-930d-fbe672aa9de9.jpg)

**Comment by darkestpriest** [comment]
Al igual como lo comenté en #744, me gustan las propuestas, pero le podemos quitar las palabras _Music Player_

**Comment by GaboHub** [comment]
Me gusta la propuesta número 2, sin las palabras músic player.

**Comment by isahq23** [comment]
@arnaldos @darkestpriest @GaboHub 

![banner_fan_community_m2](https://cloud.githubusercontent.com/assets/15214774/14650914/6e19de24-0637-11e6-864f-5d6115464060.jpg)

**Comment by arnaldos** [comment]
solo revisa los bordes del lado izquierdo y la parte superior se ve un borde negro revisa eso plz del resto todo bien

**Comment by isahq23** [comment]
@arnaldos ya vi el detalle, aquí está la corrección
Hazme saber si hay que guardarlo en algún otro sitio para ser utilizado, ya conozco las medidas.

![banner_fan_community_m2](https://cloud.githubusercontent.com/assets/15214774/14651771/1fe2502a-063b-11e6-93c0-7bfdd1ef6025.jpg)

**Comment by arnaldos** [comment]
listo !! subelo en fermat apps

**Comment by darkestpriest** [comment]
¡Genial!

**Comment by arnaldos** [comment]
@darkestpriest como vamos con esto puedo cerra el caso ?

**Comment by arnaldos** [comment]
puedo cerrar este caso @darkestpriest @lostwood

**Comment by lostwood** [comment]
Si ya esta implementado @arnaldos

**Comment by arnaldos** [comment]
perfecto !!! ya cierro el caso entonces gracias @lostwood
