### ISSUE TITLE
Generate a icon (logo) for Artist Community to Music Player App

### ISSUE THREAD

**Issue by proseuz** [bitDubai/fermat-graphic-design#743]

**Comment by Carelsy** [comment]
@emmysm @arnaldos @Luis-Fernando-Molina ![propuesta](https://cloud.githubusercontent.com/assets/17755307/14925594/feb5e0fe-0e11-11e6-81c0-37098f55feff.png)

**Comment by arnaldos** [comment]
esto es lo mismo que en este caso  #776 deben tener similitud mas ni ser el mismo

**Comment by Carelsy** [comment]
@arnaldos @emmysm me pueden decir cuál es la ubicación de este icono, para hacerlo más sencillo y con menos elementos. Si tienen alguna otra sugerencia me avisas.

**Comment by Carelsy** [comment]
@arnaldos @emmysm @Luis-Fernando-Molina ![propuesta-2](https://cloud.githubusercontent.com/assets/17755307/15048049/7bfcc3ea-12b1-11e6-815b-77acc547ec37.png)

**Comment by emmysm** [comment]
Más propuestas, @Carelsy :smile_cat:

**Comment by arnaldos** [comment]
si pienso debemos hacer otra propuesta donde se entienda que es una comunidad

**Comment by emmysm** [comment]
@karentvillegas encargate de este caso, porfa.

**Comment by darkestpriest** [comment]
Por favor @lostwood sigue este caso también.

**Comment by karentvillegas** [comment]
@arnaldos @emmysm @jhonmarquez92 @lostwood  Propuestas:
1
![propuesta1](https://cloud.githubusercontent.com/assets/19273211/15297571/a821cad6-1b64-11e6-8234-32e347b08446.png)
2
![propuesta2](https://cloud.githubusercontent.com/assets/19273211/15297582/ae5a65fc-1b64-11e6-9388-6e51cd6512ee.png)
3
![propuesta3](https://cloud.githubusercontent.com/assets/19273211/15297590/bb041c76-1b64-11e6-9ad9-eb071c7128fb.png)
4
![propuesta4](https://cloud.githubusercontent.com/assets/19273211/15297595/c1ba01b6-1b64-11e6-9da5-2752e4e92c64.png)
5
![propuesta5](https://cloud.githubusercontent.com/assets/19273211/15297612/cec9ecb8-1b64-11e6-96b2-f9e91b3c6a6f.png)
6
![propuesta6](https://cloud.githubusercontent.com/assets/19273211/15297614/d417d5a4-1b64-11e6-86bb-f6c110c6a0e2.png)
7
![propuesta7](https://cloud.githubusercontent.com/assets/19273211/15297617/d872c596-1b64-11e6-9115-100b524651d2.png)

**Comment by darkestpriest** [comment]
Version 5 for me, what do you think @Fermat-ORG/mordor-team ?

**Comment by GaboHub** [comment]
Logo 5

**Comment by proseuz** [comment]
a mi me gusta mucho la versión 3

**Comment by arnaldos** [comment]
@jhonmarquez92 @darkestpriest @karentvillegas  sinceramente podríamos usar la síntesis de la versión 7 y la base del icono la , no me apunto por la versión 5 ya que es un poco confusa la forma en que se representan las notas musicales de primera instancia parecen unos banderines.

**Comment by proseuz** [comment]
estoy de acuerdo con @arnaldos  aunque me gusta más la  versión 3 porque tiene más pinta de logo @karentvillegas

**Comment by lostwood** [comment]
Estoy de acuerdo con jhon la version 3

**Comment by arnaldos** [comment]
siendo así podemos eliminar los ojos ya que en la reducción se perderán, @karentvillegas genera las dos versiones y decidimos !

**Comment by karentvillegas** [comment]
@arnaldos @emmysm @jhonmarquez92 @lostwood En base a sus comentarios se han generado las siguientes propuestas:

1
![propuesta_1](https://cloud.githubusercontent.com/assets/19273211/15556493/f196e3d8-2297-11e6-86ac-9f7fa9d36bd6.png)
2
![propuesta_2](https://cloud.githubusercontent.com/assets/19273211/15556898/0de4256c-229a-11e6-9c66-e44c873d2e69.png)

3
![propuesta_3](https://cloud.githubusercontent.com/assets/19273211/15556511/fd4d25b6-2297-11e6-8b3c-03b1a20301de.png)

**Comment by arnaldos** [comment]
@karentvillegas  versión 2 sube los archivos !

**Comment by lostwood** [comment]
me gustaba mas la propuesta uno

**Comment by karentvillegas** [comment]
Listo @arnaldos  los archivos ya están en el repositorio.
