### ISSUE TITLE
Generate a Banner for Artist Community to Music Player App

### ISSUE THREAD

**Issue by proseuz** [bitDubai/fermat-graphic-design#744]

**Comment by isahq23** [comment]
@arnaldos first proposals for Artist Community in Music Player

![banner_artist_community_m1](https://cloud.githubusercontent.com/assets/15214774/14644531/3329dc94-061c-11e6-8564-d3c0e1d2509b.jpg)

**Comment by darkestpriest** [comment]
Hola, se ven geniales las propuestas, pero, podemos quitarle las palabras Music Player

**Comment by lostwood** [comment]
que tal, me gusta el 3 con la observacion de @darkestpriest

**Comment by arnaldos** [comment]
@isahq23 si la 3 esta buena has eso cambios según la sugerencia de @darkestpriest  plz

**Comment by isahq23** [comment]
@arnaldos @darkestpriest @lostwood 

![banner_artist_community_m2](https://cloud.githubusercontent.com/assets/15214774/14650837/205f1848-0637-11e6-8ba3-a480a5cf2df9.jpg)

**Comment by darkestpriest** [comment]
I liked it!!

**Comment by lostwood** [comment]
i like it too, congrat , what do you think @macuare @alexanderejm

**Comment by arnaldos** [comment]
avísenme cuando apliquen esto para cerrar el caso

**Comment by isahq23** [comment]
@arnaldos estoy archivos ya están en el repo, no sé si debas cerrar ya el caso

**Comment by arnaldos** [comment]
envíale la ruta  a @lostwood para que los aplique
