### ISSUE TITLE
Generate a icon for Identity Fan to Music Player App

### ISSUE THREAD

**Issue by proseuz** [bitDubai/fermat-graphic-design#745]

**Comment by proseuz** [comment]
@emmysm @Luis-Fernando-Molina @Miguelcldn 
Propuesta 1
![iconos fan identities](https://cloud.githubusercontent.com/assets/17308060/14329358/d42b6094-fc04-11e5-8f9c-b8a2c0d44155.png)

Propuesta 2
![iconos fan identities 2](https://cloud.githubusercontent.com/assets/17308060/14329362/d98b0670-fc04-11e5-83d4-73bbb72f922e.png)

**Comment by isahq23** [comment]
@arnaldos 
Following the style from the logo and keeping the vendetta mask this is what I got.

![icon_fan_mp_issues_745_m1](https://cloud.githubusercontent.com/assets/15214774/14756100/c6fcdc82-08b0-11e6-9c55-c23d5fd106d7.jpg)

**Comment by arnaldos** [comment]
@isahq23  el de la derecha !! :+1:  sube los archivos

**Comment by arnaldos** [comment]
@isahq23 como vamos aquí ? subiste los archivos ??

**Comment by isahq23** [comment]
@arnaldos cierra este caso, ya lo archivos están en el repo

**Comment by arnaldos** [comment]
:+1:
