### ISSUE TITLE
Generate a icon for the Fan Wallet 

### ISSUE THREAD

**Issue by proseuz** [bitDubai/fermat-graphic-design#746]
- Fan Wallet ( is a wallet where people go to see
  the websites of your favorite artists and see a list of
  songs you bought those artists )

**Comment by proseuz** [comment]
_The stars represent the artists
_The circles behind the stars represent the websites
_The horizontal bars with musical notes represent the list of song
 @emmysm @Luis-Fernando-Molina @Miguelcldn @darkestpriest 
Proposal 1
![fan wallet 1](https://cloud.githubusercontent.com/assets/17308060/14338952/bc67f040-fc44-11e5-8d66-c9ca977b7549.png)
Proposal 2
![fan wallet 2](https://cloud.githubusercontent.com/assets/17308060/14338953/bc89146e-fc44-11e5-931b-4ad2b92a20f8.png)
Proposal 3
![fan wallet](https://cloud.githubusercontent.com/assets/17308060/14338954/bca25cf8-fc44-11e5-908d-edf6c6047225.png)

**Comment by emmysm** [comment]
@Luis-Fernando-Molina  cómo vamos por aca?

**Comment by darkestpriest** [comment]
La wallet va a poder administrar canciones y ver los sitios de los artistas, la propuesta 2 es la que puedo observar que más se acerca a ese concepto, pero, me parece que le falta algo. ¿que opinas @lostwood ?

**Comment by lostwood** [comment]
tambien me parece que la 2 , en el caso anterior luis hizo incapie en deberia tener la  nota y el microfono

**Comment by Luis-Fernando-Molina** [comment]
Hola, este tipo de iconos son para las plataformas no para la apps. Fijense lo que hemos hecho antes para apps. saludos

**Comment by darkestpriest** [comment]
@emmysm @jhonmarquez92 es cierto lo que dice @Luis-Fernando-Molina, en la actualidad estamos usando este icono para la fan wallet provisionalmente:
![banner_tky](https://cloud.githubusercontent.com/assets/10060413/14457613/7903da28-0075-11e6-9317-f4168d27e246.png)
Podemos tomar este como inspiración y darle el toque Fermat.

**Comment by proseuz** [comment]
@emmysm  @Luis-Fernando-Molina  @darkestpriest  @arnaldos @lostwood  
Proposal 1
![fan_wallet 1](https://cloud.githubusercontent.com/assets/17308060/14480328/a8a4b38e-00f1-11e6-9fb7-857c8c39c5f0.png)
Proposal 2
![fan_wallet 6](https://cloud.githubusercontent.com/assets/17308060/14480334/a936b392-00f1-11e6-85b5-929b647a8628.png)
Proposal 3
![fan_wallet 2](https://cloud.githubusercontent.com/assets/17308060/14480329/a8c7f60a-00f1-11e6-8be5-cccd45027951.png)
Proposal 4
![fan_wallet 3](https://cloud.githubusercontent.com/assets/17308060/14480330/a8e18e6c-00f1-11e6-81a6-a22010d4956c.png)
Proposal 5
![fan_wallet 4](https://cloud.githubusercontent.com/assets/17308060/14480332/a903d1ac-00f1-11e6-9468-eaffbaa121d6.png)
Proposal 6
![fan_wallet 5](https://cloud.githubusercontent.com/assets/17308060/14480333/a917583a-00f1-11e6-9b90-eeb143ff4110.png)

**Comment by lostwood** [comment]
Me inclino mas por el que esta originalmente me parece que capta mejor la esencia de la app, apoyo lo que dice @darkestpriest

**Comment by darkestpriest** [comment]
Proposal 5, demasiado genial para mi :+1: 
La que tu mencionas @lostwood no es posible colocarla como icono, ya que ese estilo es solo para las plataformas que se muestran, por ejemplo, en dev.fermat.org

**Comment by lostwood** [comment]
No me referia a los 3 primeros sino al que esta actualmente en desktop de las wallet @darkestpriest
https://cloud.githubusercontent.com/assets/10060413/14457613/7903da28-0075-11e6-9317-f4168d27e246.png

**Comment by arnaldos** [comment]
@jhonmarquez92  conceptualmente esta bueno pero plz genera otra propuesta partiendo de la 5ta propuesta prueba que su máxima reducción no se pierdan los elementos ya que en este momento se pierden los elementos. por otro lado se ve muy plano. busca resaltar el elemento principal que no sea únicamente por el contraste de color.

**Comment by proseuz** [comment]
proposals with changes @arnaldos 
 Proposal 1
![fan_wallet 10](https://cloud.githubusercontent.com/assets/17308060/14498039/d43d43a0-0162-11e6-97e4-93641c969dec.png)
Proposal 2
![fan_wallet 11](https://cloud.githubusercontent.com/assets/17308060/14498040/d44563dc-0162-11e6-84c6-9eb999c48a31.png)
Proposal 3
![fan_wallet 12](https://cloud.githubusercontent.com/assets/17308060/14498041/d46ebc32-0162-11e6-98cf-685fb6db399d.png)
Proposal 4
![fan_wallet 7](https://cloud.githubusercontent.com/assets/17308060/14498042/d487fa8a-0162-11e6-9698-13f56af11659.png)
Proposal 5
![fan_wallet 8](https://cloud.githubusercontent.com/assets/17308060/14498043/d48b5216-0162-11e6-8ade-d7f7e8419bc0.png)
Proposal 6
![fan_wallet 9](https://cloud.githubusercontent.com/assets/17308060/14498045/d49c8f18-0162-11e6-9841-35fc7abdf10d.png)

**Comment by darkestpriest** [comment]
Me gusta la proposal 3

**Comment by emmysm** [comment]
@jhonmarquez92 propuestas de color a partir de la opción número dos, porfa.

**Comment by arnaldos** [comment]
@jhonmarquez92 me gusta el numero 2 pero hay algo que no me termina de cuadrar y creo que se debe al espacio que se genera en la esquina superior izquierda y la inferior derecha. prueba hacer las esquinas del cuadrado mas redondas para ver que resultado tenemos. tal ves eso puede funcionar

**Comment by proseuz** [comment]
Proposal colors
@arnaldos @emmysm 
1
![fan_wallet 13](https://cloud.githubusercontent.com/assets/17308060/14549679/d09c785e-028b-11e6-85a1-bed5525163c1.png)
2
![fan_wallet 16](https://cloud.githubusercontent.com/assets/17308060/14549677/d0205bb6-028b-11e6-987c-8b97d940bc07.png)
3
![fan_wallet 17](https://cloud.githubusercontent.com/assets/17308060/14549678/d07775c2-028b-11e6-9142-f7749435a387.png)
4
![fan_wallet 15](https://cloud.githubusercontent.com/assets/17308060/14549672/cfa06f64-028b-11e6-86bd-a71cdb76f1a0.png)

5
![fan_wallet 14](https://cloud.githubusercontent.com/assets/17308060/14549680/d0abac34-028b-11e6-9aa9-b950b7b86117.png)

**Comment by emmysm** [comment]
@jhonmarquez92  A mí me gusta la propuesta número 5. Qué opinas @arnaldos ?

**Comment by arnaldos** [comment]
@emmysm Totalmente de acuerdo propuesta 5. @jhonmarquez92  solo esta modificación al icono que te dejo de ejemplo. tal ves se ve pixelada la imagen por que la monte en photoshop.

puse el ejemplo porque no sabia como explicarte.

![icono-fan](https://cloud.githubusercontent.com/assets/13594347/14576396/8aebbd2c-0332-11e6-8dcf-2cdf7b8523c6.jpg)

**Comment by darkestpriest** [comment]
Me gustaba más la tres (por pertenecer al equipo Mordor) pero la 5 está genial :+1:

**Comment by arnaldos** [comment]
@jhonmarquez92 aplica esto también para la versión  3 solo que en la 3 el fondo un poco mas oscuro. muestranos las dos y decidimos junto a @darkestpriest  :+1:

**Comment by emmysm** [comment]
Opino lo mismo que @arnaldos . Se puede aplicar la 3, pero un fondo negro estaría mejor @jhonmarquez92 @darkestpriest

**Comment by darkestpriest** [comment]
No, tranquilos, la 5 es perfecta para todos, la tres es solo para metaleros ;)

**Comment by proseuz** [comment]
@arnaldos  se ve genial así, ya genero los cambios

**Comment by proseuz** [comment]
@arnaldos @emmysm @darkestpriest 
1
![fan_wallet 20](https://cloud.githubusercontent.com/assets/17308060/14577798/b1a06aca-0342-11e6-82e1-6fd9191c1c83.png)
2
![fan_wallet 21](https://cloud.githubusercontent.com/assets/17308060/14577799/b1b86d3c-0342-11e6-95c3-77d319488f7f.png)
3
![fan_wallet 18](https://cloud.githubusercontent.com/assets/17308060/14577800/b1e79bac-0342-11e6-875f-dc3f0b10080f.png)
4
![fan_wallet 19](https://cloud.githubusercontent.com/assets/17308060/14577801/b200f566-0342-11e6-98e3-d7b859b67947.png)

**Comment by darkestpriest** [comment]
Para mi, la propuesta 2

**Comment by arnaldos** [comment]
@jhonmarquez92 totalmente propuesta 2, sube los archivos !! :+1:

**Comment by lostwood** [comment]
excellent, what do you think @macuare @alexanderejm

**Comment by arnaldos** [comment]
como vamos con esto puedo cerra el caso ? ya esta aplicado en la app ??

**Comment by lostwood** [comment]
Si ya esta aplicado, por fa cuando puedan los otros recursos gracias

**Comment by arnaldos** [comment]
seguro !!  gracias a ti !!
