### ISSUE TITLE
Generate a icon for the Fan Community to the Artistic Platform ART

### ISSUE THREAD

**Issue by proseuz** [bitDubai/fermat-graphic-design#747]

**Comment by Carelsy** [comment]
Propuesta 1 para la comunidad de fan de la plataforma de artistas @arnaldos @emmysm @Luis-Fernando-Molina  ![propuesta-1](https://cloud.githubusercontent.com/assets/17755307/14371740/6db0a31e-fd04-11e5-8a5e-b762ab7bcf9c.png)

**Comment by arnaldos** [comment]
@Carelsy me gustaría ver otras propuestas. de esta corrige el globito de chat y colócalo en posición horizontal como el resto.

**Comment by Carelsy** [comment]
@arnaldos @emmys @Luis-Fernando-Molina aquí les muestro la propuesta con la corrección del globobito de chat.
![propuesta-2](https://cloud.githubusercontent.com/assets/17755307/14447282/eaab0730-0027-11e6-80fb-518442b449f2.png)

**Comment by arnaldos** [comment]
@emmysm revisa esto plz

**Comment by emmysm** [comment]
@arnaldos estoy a la espera de nuevas propuestas.

**Comment by Carelsy** [comment]
Propuesta 2 para la comunidad de fan de la plataforma de artistas @arnaldos @emmysm @Luis-Fernando-Molina
![propuesta-3](https://cloud.githubusercontent.com/assets/17755307/14624280/16e0e2f4-05a3-11e6-9f64-4ab45bb2a50d.png)

**Comment by Carelsy** [comment]
Propuesta 3 para la comunidad de fan de la plataforma de artistas @arnaldos @emmysm @Luis-Fernando-Molina
![propuesta-4](https://cloud.githubusercontent.com/assets/17755307/14624423/57d06ea0-05a4-11e6-91c4-2acd8b38b707.png)

**Comment by arnaldos** [comment]
@emmysm  como vamos con esto ?

**Comment by emmysm** [comment]
@Joseangel2v encárgate de este caso, porfa.

**Comment by Joseangel2v** [comment]
![sin titulo-4-01-01](https://cloud.githubusercontent.com/assets/17457499/15203619/5a79779a-17cf-11e6-963b-2f3f9809ee40.png)

**Comment by Joseangel2v** [comment]
![art c-01-01](https://cloud.githubusercontent.com/assets/17457499/15203641/7413ca16-17cf-11e6-9976-b71a379f064e.png)

**Comment by darkestpriest** [comment]
¿Podríamos lograr un icono que siga el estandar de los iconos de las communities que están en las otras plataformas? Este icono tiene el estilo de dev.fermat.org

**Comment by arnaldos** [comment]
@darkestpriest este icono sino me equivoco es para representar la plataforma en  dev.fermat.org @emmysm revisa esto plz!

**Comment by saraguerrerot** [comment]
![image](https://cloud.githubusercontent.com/assets/19808868/16319851/d9fdc318-3962-11e6-8023-8b1b8f494356.png)

@emmysm  @arnaldos

**Comment by emmysm** [comment]
Presenta dos propuestas más, @saraguerrerot, por favor. :)

**Comment by arnaldos** [comment]
@emmysm esto donde se mostrara ?

**Comment by arnaldos** [comment]
@emmysm

**Comment by saraguerrerot** [comment]
![image](https://cloud.githubusercontent.com/assets/19808868/16452074/99f89e02-3dd4-11e6-9357-db261d667f16.png)

@emmysm @arnaldos

**Comment by saraguerrerot** [comment]
![image](https://cloud.githubusercontent.com/assets/19808868/16452219/5f53742e-3dd5-11e6-983c-a28a10d44b23.png)

@emmysm @arnaldos

**Comment by saraguerrerot** [comment]
![image](https://cloud.githubusercontent.com/assets/19808868/16452250/78dfb4de-3dd5-11e6-9909-64d1e423a287.png)

@emmysm @arnaldos

**Comment by emmysm** [comment]
Caso en espera.
