### ISSUE TITLE
Logo para Fermat Wallet Production & Distribution

### ISSUE THREAD

**Issue by Luis-Fernando-Molina** [bitDubai/fermat-graphic-design#75]
Diseñar un logo para este concepto y colocarlo en la presentación.

![screenshot from 2015-08-17 12 39 45](https://cloud.githubusercontent.com/assets/9479367/9303318/6acd86f6-44dd-11e5-8d35-88b3b2e81c54.png)

**Comment by m471c4** [comment]
@Luis-Fernando-Molina este es el primer boceto para Fermat WPD

![fermatwpd](https://cloud.githubusercontent.com/assets/13468350/9569598/abc3b9f8-4f39-11e5-93fb-36ccae1fcbce.png)

**Comment by Luis-Fernando-Molina** [comment]
lo de  la factory bien, la otra parte no tanto. Fijate si podés representar la wallet store junto a la factory, como la bolsa de carton con 3 billeteras arriba quizás como el logo de fermat

**Comment by m471c4** [comment]
Muy bien, en un momento los subo.

**Comment by m471c4** [comment]
@Luis-Fernando-Molina ¿qué te parece así?

![fermatwpd4](https://cloud.githubusercontent.com/assets/13468350/9570276/5f8c9746-4f50-11e5-908a-38ed262fd3fe.png)
![fermatwpd2](https://cloud.githubusercontent.com/assets/13468350/9570235/f87df5aa-4f4e-11e5-9d18-7ca643931c45.png)
![fermatwpd3](https://cloud.githubusercontent.com/assets/13468350/9570244/34e50b0a-4f4f-11e5-9145-256f5ef31205.png)

**Comment by Luis-Fernando-Molina** [comment]
Hasta ahora el primero, podés probar poner la fabrica al lado de la bolsa please?

**Comment by m471c4** [comment]
Seguro, dame un momento y lo arreglo.

**Comment by m471c4** [comment]
@Luis-Fernando-Molina acá con las correcciones:

![fermatwpd5](https://cloud.githubusercontent.com/assets/13468350/9586181/15308578-4fe5-11e5-93f9-e0a26b6ebfbe.png)
![fermatwpd6](https://cloud.githubusercontent.com/assets/13468350/9586183/1543f676-4fe5-11e5-897a-2e4ff66489cf.png)

**Comment by Luis-Fernando-Molina** [comment]
al primero conecta la fabrica con la bolsa y listo (usa lo que de manera estandard se use para conectar)

**Comment by m471c4** [comment]
@Luis-Fernando-Molina con los cambios solicitados. Ya @Miguelcldn lo tiene en svg.

![fermatwpd7](https://cloud.githubusercontent.com/assets/13468350/9598084/d1bc81ee-5051-11e5-986e-71a947d300e5.png)

**Comment by Luis-Fernando-Molina** [comment]
ok, esto puede quedar asi :+1:
