### ISSUE TITLE
Crear un logo para la Identity Artist de la Fan Wallet App

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#750]
Es una sub app que permite al usuario artista crear una identidad para la Fan Wallet.

**Comment by JefersonBorgesS** [comment]
Propuestas para fan wallet @arnaldos  
1°
![1](https://cloud.githubusercontent.com/assets/17457984/14394707/6ef5f7b8-fd97-11e5-9e66-ef5d11f9ca94.png)

2°
![2](https://cloud.githubusercontent.com/assets/17457984/14394719/7a6b2eec-fd97-11e5-9e2c-53ed77775e9c.png)

**Comment by arnaldos** [comment]
creo que no es camino, trata de representar la coneccion entre los fanáticos y artistas, toma en cuenta en un futuro el fan podran chatear con ese artista. directamente

**Comment by arnaldos** [comment]
@jayborges como vamos con esto ??

**Comment by JefersonBorgesS** [comment]
1
![fan wallet 23-02-02](https://cloud.githubusercontent.com/assets/17457984/14499341/baeb237c-0167-11e6-8d23-1471f92e78f6.png)

2 - Con los personajes creados hace un tiempo.
![fan wallet 2-02](https://cloud.githubusercontent.com/assets/17457984/14499344/bd18bdb2-0167-11e6-9efc-8d2aecf4435a.png)

**Comment by JefersonBorgesS** [comment]
![3](https://cloud.githubusercontent.com/assets/17457984/14499999/1a424ccc-016a-11e6-9402-93da27ac5d16.png)

![4](https://cloud.githubusercontent.com/assets/17457984/14500003/1c65a058-016a-11e6-8e48-38cc754e9248.png)

**Comment by arnaldos** [comment]
otras propuestas plz

**Comment by JefersonBorgesS** [comment]
![5](https://cloud.githubusercontent.com/assets/17457984/14505064/53c9f104-0181-11e6-8e66-d35350722112.png)

**Comment by arnaldos** [comment]
me gusta, ajusta plz la sombra ponla a 45° y proyectala desde la punta de arriba, el tono de la sombra mas clara. verifica que la base del icono sea totalmente cuadrada aunque tenga las esquinas redonda, se ve medio rectangular verifica eso plz

**Comment by JefersonBorgesS** [comment]
![6](https://cloud.githubusercontent.com/assets/17457984/14548083/8b8c7ee8-027d-11e6-8abb-69b5708237fc.png)

**Comment by darkestpriest** [comment]
Saludos, la última propuesta la veo ideal para la sub app **Artist identity**

**Comment by arnaldos** [comment]
@darkestpriest perfecto siendo asi debe quedar como community porque las identities llevan la mascara de anonimous

**Comment by darkestpriest** [comment]
Pero, no tenemos communities en Tokenly @arnaldos

**Comment by arnaldos** [comment]
ahh ok ok !! perfecto !!

**Comment by proseuz** [comment]
My  proposal for the  identity Artist @arnaldos 
Proposal 1
![identity_artist 1](https://cloud.githubusercontent.com/assets/17308060/14658545/58fce9ce-065e-11e6-9e86-d2c0f669c45b.png)
Proposal 2
![identity_artist 2](https://cloud.githubusercontent.com/assets/17308060/14658546/5913f074-065e-11e6-9e4d-072d97b5d2bf.png)

**Comment by arnaldos** [comment]
@jhonmarquez92 versión 2 solo despega las puntas de la estrella del borde blanco. (achica la estrella)

**Comment by proseuz** [comment]
@arnaldos aquí las correcciones de la *_versión 2 *_
![artistic communityt logo-01-01](https://cloud.githubusercontent.com/assets/17308060/14725679/4fc8e58a-07e7-11e6-9d83-54114b8a7968.png)

**Comment by arnaldos** [comment]
aumenta el tamaño de la mascara y has la estrella con puntas mas anchas para que no se corte con la mascara

**Comment by proseuz** [comment]
@arnaldos 
1, 2 y 3
![artistic communityt logotamno-01](https://cloud.githubusercontent.com/assets/17308060/14900820/320618a4-0d5c-11e6-9217-604a42ed9717.png)

**Comment by proseuz** [comment]
@arnaldos qué opinas de las últimas propuestas?

**Comment by arnaldos** [comment]
usa la 3

**Comment by arnaldos** [comment]
@darkestpriest  esto esta implementado ?
