### ISSUE TITLE
Crear logo para Music Player app

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#751]
App reproductor de música, permite reproducir la música encryptada adquirida en la Fan wallet

**Comment by isahq23** [comment]
Here are my proposals.
I´m gonna clear some things first:
1. The only thing that keeps the graphic made by 3D team, was the ticket figure.
2. There are no samples of how to represent the idea of a token.
3. Since this was a "music" platform, I chose music elements.
4. The bear with the glasses: I wanted to create something to remember, something fun, something that shows how easy and awesome this APP can be.

![tokens_artist_app_issue751_muestra](https://cloud.githubusercontent.com/assets/15214774/14332990/143138a6-fc16-11e5-95e1-2e5195a7587f.png)

**Comment by arnaldos** [comment]
@isahq23 Remenber the name is tokenly artist. is not only tokenly. make a proposal similar like napster, itunes, drezzer or other app same. the icon i like the first and second version. create a new version for this. 
1-the shape of the ticket is ok.
2-the color to ticket, version 4

**Comment by isahq23** [comment]
Here are the modifications with some new proposals. I guided myself with the samples you gave me.

![tokens_artist_app_issue751_muestra2](https://cloud.githubusercontent.com/assets/15214774/14361092/1c236f9a-fcc3-11e5-838d-ed7a3d051b7f.png)

**Comment by arnaldos** [comment]
version 5 proves one thing, put color on headphones plz.

**Comment by isahq23** [comment]
Here you have.

![tokens_artist_app_issue751_muestra3](https://cloud.githubusercontent.com/assets/15214774/14391997/ff246d42-fd88-11e5-942c-009b5178a928.png)

**Comment by arnaldos** [comment]
@isahq23 place it on a screen, try other colors. of the two version ... left version

**Comment by isahq23** [comment]
What do you think?

![tokens_artist_app_issue751_muestra4](https://cloud.githubusercontent.com/assets/15214774/14397366/bb295ec2-fda6-11e5-9431-8768b2d1e6dd.jpg)

**Comment by arnaldos** [comment]
@isahq23 me gusta pero siento le falta algo, no se si combinarlo con un 3er color. en cuanto a la síntesis esta bien nose si un color.

**Comment by isahq23** [comment]
@arnaldos  experimentaré un poco más :P

**Comment by isahq23** [comment]
I played the most I could the colors.

![tokens_artist_app_issue751_muestra5](https://cloud.githubusercontent.com/assets/15214774/14430067/e7828d70-ffc9-11e5-8ba9-bd841e67d726.jpg)

**Comment by isahq23** [comment]
In this sample the colors used are the same used in deezer.

![tokens_artist_app_issue751_muestra6](https://cloud.githubusercontent.com/assets/15214774/14471792/0102ccf6-00ba-11e6-9074-c4022e54342f.jpg)

**Comment by arnaldos** [comment]
@isahq23  prueba en la version 4 seguir los colores en los audifonos para ver como se comporta

**Comment by isahq23** [comment]
así?

![tokens_artist_app_issue751_muestra7](https://cloud.githubusercontent.com/assets/15214774/14475656/ea771d30-00cc-11e6-9751-ba2116184e49.jpg)

**Comment by arnaldos** [comment]
@isahq23 la ultima sube los archivos plz :+1:

**Comment by darkestpriest** [comment]
¿Estos son banners para las communities? @arnaldos

**Comment by arnaldos** [comment]
@darkestpriest partiendo de aquí podemos hacer el banner, en este caso trabajamos el icono enfocados a una app similar a itunes como me comentaste cuando conversamos.  
Esto fue lo que aprobamos para esta app.
![a1](https://cloud.githubusercontent.com/assets/13594347/14576029/a756edd6-032f-11e6-99a8-e0845530847f.jpg)

**Comment by darkestpriest** [comment]
Me gusta mucho para el music player que está desarrollando @lostwood
@arnaldos sería excelente partir de esta idea para las dos communities que tenemos en la plataforma ART, una de Fans y otra de artistas.

**Comment by arnaldos** [comment]
@darkestpriest vale perfecto !!! el music player es una app aparte o esta interno a fan o artist ?

**Comment by darkestpriest** [comment]
Es una sub app, como lo es chat o el asset issuer

**Comment by arnaldos** [comment]
ahh vale perfecto !!!! siendo asi lo dejamos para music player va mas con eso.

**Comment by arnaldos** [comment]
@isahq23 el icono sigue aprobado pero lo vamos a usar para music player. ya le camio el nombre al issue asi no nos confundimos después. genera los archivos

**Comment by isahq23** [comment]
@arnaldos  vale ya le cambio el nombre a la carpeta del draft y la paso a 2D Design

**Comment by proseuz** [comment]
entonces este caso no va? https://github.com/Fermat-ORG/fermat-graphic-design/issues/749

**Comment by darkestpriest** [comment]
@jhonmarquez92 el icono mostrado en #749 tiene el estilo usado para los iconos de las plataformas, mas no para icono de sub app, mi propuesta sería, usar el de este issue para generar los banners para las communities de ART, las cuales son dos, de Fan y Artists, y tomar la de #749 y adaptarla al estilo de ico usado en el desktop de Fermat

**Comment by emmysm** [comment]
Generate a icon (logo) for Artist Community to Music Player App #743

**Comment by lostwood** [comment]
muy bueno que piensan muchachos @macuare @alexanderejm

**Comment by arnaldos** [comment]
como vamos con esto ?

**Comment by isahq23** [comment]
@arnaldos ya el repo está actualizado con todo del music player, creo que puedes cerrar este caso

**Comment by arnaldos** [comment]
perfecto isa gracias !!
