### ISSUE TITLE
Crear logo para Identity Fan de la Fan Wallet App

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#752]
Es una sub app que permite al usuario fanático crear una identidad para la Fan Wallet.

**Comment by adryx83** [comment]
Buenas Tardes aquí dejo la primera propuesta del logo de Tokenly. 

![logo tokens](https://cloud.githubusercontent.com/assets/17273349/14443790/34b899a4-000b-11e6-84b6-788ebee65356.jpg)

**Comment by adryx83** [comment]
Buenas tarde 3 propuestas mas para el logo tokently 

![logo tokens2](https://cloud.githubusercontent.com/assets/17273349/14504471/c53aebfc-017e-11e6-925b-a2d7f96e0dfd.jpg)

**Comment by emmysm** [comment]
@adryx83 genera más propuestas, porfa.

**Comment by arnaldos** [comment]
@adryx83 me gusta el concepto utilicemos esto ultimo como base, pudiésemos trabajar una imagen de un usuario tal como propones aquí, imagina un icono cuya base puede ser (cuadrada, circular, cuadrada con esquinas redondas, etc) coloca al usuario donde se aprecie cabeza y cuerpo unidos, el fondo puede ser blanco o gris por ahi los tonos, los audífonos los de la primera propuesta, el cintillo de los audífonos picalo en varias secciones e incluye varios colores neones o los que veas coerente de esta manera representas la diversidad de música que obtendrá el usuario el user mantelo oscuro de esta manera se entiende que el usuario puede ser cualquiera.

**Comment by adryx83** [comment]
@arnaldos aca estan una propuestas segun lo que entendi de tus comentarios...

![logo tokenly3](https://cloud.githubusercontent.com/assets/17273349/14542301/194a079e-0258-11e6-81bb-30b1a27aecba.jpg)

**Comment by arnaldos** [comment]
va encaminado pero aun le falta refinar el icono

**Comment by darkestpriest** [comment]
Saludos, este icono podría ser usado para la sub app Fan Identity

**Comment by adryx83** [comment]
Aca dejo unos iconos en los que trabaje que pueden servir para el logo
![icons tokenly4](https://cloud.githubusercontent.com/assets/17273349/14607897/61979ef6-054d-11e6-80ef-15db06248045.jpg)

**Comment by arnaldos** [comment]
@adryx83 identificalos plz va hacer mas fácil para poder comentarte

**Comment by adryx83** [comment]
@arnaldos Adjunto cambios sugeridos...

![fan identity logo](https://cloud.githubusercontent.com/assets/17273349/14621527/57c04c62-058d-11e6-9082-89dd94c87f64.jpg)

**Comment by arnaldos** [comment]
@adryx83 nos quedamos la versión redonda pero has que sea un circulo. los audífonos que lleven los colores del logo de fan wallet https://cloud.githubusercontent.com/assets/13594347/14576396/8aebbd2c-0332-11e6-8dcf-2cdf7b8523c6.jpg has la mascara mas pequeña, elimina el stroke de los audífonos. los elementos no tan a los bordes del circulo

**Comment by adryx83** [comment]
@arnaldos 

![fan identity](https://cloud.githubusercontent.com/assets/17273349/14622953/afc644ca-0597-11e6-9a5c-036888b08d3c.jpg)

**Comment by darkestpriest** [comment]
Me gusta este icono @arnaldos @adryx83 voy a pedirle opinión a @GaboHub él fue el desarrollador de esa sub app

**Comment by adryx83** [comment]
@arnaldos 

![fan identity2](https://cloud.githubusercontent.com/assets/17273349/14623143/2fcbf7d6-0599-11e6-85a3-7988c18a0fdd.jpg)

**Comment by adryx83** [comment]
@arnaldos 

![logo fan identity3](https://cloud.githubusercontent.com/assets/17273349/14639292/b54d23a0-0605-11e6-9e46-e5e98043f8ba.jpg)

**Comment by arnaldos** [comment]
@adryx83 Ajusta la sombra a 45 ° y que parta de la parte superior de los audífonos.

**Comment by arnaldos** [comment]
las divisiones del cintillo de los audífonos has que tengan el mismo espacio, si al momento de dividir loe elementos has que tengan el mismo angulo. busca un balance en eso. la división del centro da para la izquierda debería ser en el centro el resto de los ángulos deben ser simétricos

**Comment by arnaldos** [comment]
@adryx83 como vamos con esto ??

**Comment by adryx83** [comment]
Disculpa @arnaldos pense que habia posteado esto desde ayer...

![logo fan identity4](https://cloud.githubusercontent.com/assets/17273349/14694352/5c6ff67c-0731-11e6-9680-1aae0fbcec23.jpg)

**Comment by arnaldos** [comment]
este es el icono aprobado cierro el caso.
![fan_indetity](https://cloud.githubusercontent.com/assets/13594347/14898217/840aaabe-0d4f-11e6-91bf-0023b2852b6f.png)
