### ISSUE TITLE
Create Logo for Yayo Team

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#753]
Debido a que el equipo nació Thunder Team, se piensa trabajar algo relacionando a un cachorrito del logo de Thunder o algo por el stilo.

Dejo referencia logo thunder team
https://github.com/Fermat-ORG/fermat-graphic-design/issues/179

**Comment by JefersonBorgesS** [comment]
@arnaldos 
![yayo_team](https://cloud.githubusercontent.com/assets/17457984/14399182/f72eb14e-fdb3-11e5-96ff-2c0ac6e76c4c.png)

**Comment by arnaldos** [comment]
gracias @jayborges dejemos que decidan los del yayo team @Yayotron danos tu opinión ?

**Comment by Yayotron** [comment]
Buenos días! Me gusta la idea de los dos cachorritos. Pero el estilo de fuente no me gusta, y los colores no me convencen, en especial el color del rayo. Un color más "vivo" estaría bien.

**Comment by JefersonBorgesS** [comment]
@Yayotron Buenas, que estilo de fuente mas o menos buscas y que colores exactamente para ser mas puntual en las correciones, gracias.

**Comment by Yayotron** [comment]
Un color más vivo, un rojo/naranja por ejemplo. El estilo de fuente cualquiera que te guste, pero que sea más legible y se entienda mejor el nombre.

**Comment by JefersonBorgesS** [comment]
@arnaldos @Yayotron Aca dos propuestas nuevas con diferentes tipografias y colores calidos. (Me agrado mas la propuesta 2).

Propuesta 1
![yayo_team2-02](https://cloud.githubusercontent.com/assets/17457984/14463326/65881436-0094-11e6-87c6-ad57c946d037.png)

Propuesta 2
![yayo_team3-03](https://cloud.githubusercontent.com/assets/17457984/14463335/6984f252-0094-11e6-97f7-2b2e952158ba.png)

**Comment by Yayotron** [comment]
Hola. La Fuente y el color del primero me gusta más. Podrías dejar los perritos en el azul que me habías mostrado primero, y el círculo, rayito y la fuente en naranja? Creo que eso sería todo :+1:

**Comment by JefersonBorgesS** [comment]
Ok ya hago las correciones

**Comment by JefersonBorgesS** [comment]
@Yayotron 

1- Con los ajustes.
![yayo_team4](https://cloud.githubusercontent.com/assets/17457984/14468534/e20c69a2-00a9-11e6-9989-940c518ffee7.png)

2- Con los ajustes pero el azul en gradiente.
![yayo_team5](https://cloud.githubusercontent.com/assets/17457984/14468533/e207d91e-00a9-11e6-91c3-0f5757c4592b.png)

**Comment by Yayotron** [comment]
Me gusta más la primera opción. ¿Podés ponerle las letras en azul también? Ahora que las veo así, se ven extrañas. Lo demás todo bien!

**Comment by JefersonBorgesS** [comment]
![yayo_team6](https://cloud.githubusercontent.com/assets/17457984/14468888/c09e3366-00ab-11e6-9fd9-88962cf9af35.png)

**Comment by Yayotron** [comment]
Me gusta! Me quedo con ésta,
@arnaldos necesito este logo sobre una moneda para que sea mostrado en la página de bitdubai (http://bitdubai.com/wp/fermat-about-us/developers/devs-teams/). Y de ser posible para mañana, porque va a salir pronto.

**Comment by arnaldos** [comment]
@Yayotron vale perfecto siendo así @jayborges sube los archivos al repo para que @jonathanborges3d realice los 3Ds.

**Comment by jonathanborges3d** [comment]
@arnaldos Enterado! 
@jayborges Primo avísame cuando estén en el repo por favor. Saludos.

**Comment by jonathanborges3d** [comment]
Hice una versión con la disponible acá. ![yayo](https://raw.githubusercontent.com/Fermat-ORG/media-kit/68a3f95bbdd2e3366280dc1751bb24b962b48a8a/Logotype/FermatTeams/YAYO_1.jpg)

**Comment by Yayotron** [comment]
Qué hermoso se ve. Graciass!
¿Agregan ustedes el logo al README o lo hago yo?
Creo que ya pueden cerrar el issue

**Comment by jonathanborges3d** [comment]
Yo puedo hacerlo, pero haciendo un pull porque no tengo acceso de escritura al repo de fermat, todavía debo modificar el nombre del archivo, para que siga una misma nomenclatura.

**Comment by Yayotron** [comment]
Hazlo tú, por favor. Yo apruebo el PR.

**Comment by jonathanborges3d** [comment]
Listo, ya está creado el PR.
