### ISSUE TITLE
Create Welcome screen tutorial.

### ISSUE THREAD

**Issue by emmysm** [bitDubai/fermat-graphic-design#757]

**Comment by emmysm** [comment]
![welcome dialog](https://cloud.githubusercontent.com/assets/15143489/14361622/8d258b7c-fcc5-11e5-9521-478b7c6db762.png)

@Luis-Fernando-Molina @furszy el texto de cada una de las pantallas es totalmente provisional.

**Comment by furszy** [comment]
@gustl-arg please check this. We need text in each frame.

**Comment by furszy** [comment]
@Luis-Fernando-Molina  check this. I do not want to do it twice.

**Comment by furszy** [comment]
@gustl-arg you too check this, We need to adjust the real text space on each screen.
thanks to both of you

**Comment by arnaldos** [comment]
@furszy @emmysm I think we can apply the modal to full screen, after the splash. What do you think ?

**Comment by Luis-Fernando-Molina** [comment]
en general esta bien

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina Te comparto una versión de pantalla completa. Creo puede funcionar algo así para el welcome.

#### Secuencia

![secuencia](https://cloud.githubusercontent.com/assets/13594347/14398518/9480228a-fdae-11e5-9567-7fe2d355c56a.jpg)

#### Funcion animada

![welcome_animate](https://cloud.githubusercontent.com/assets/13594347/14398574/03d9bd08-fdaf-11e5-8e4f-5fc57e4604d1.gif)

**Comment by emmysm** [comment]
![sin titulo-3](https://cloud.githubusercontent.com/assets/15143489/14555011/f402160e-02b9-11e6-9118-53f569d6416a.png)

Solo faltarían los iconos que no se han aprobado todavía @Luis-Fernando-Molina @furszy

**Comment by furszy** [comment]
@emmysm , recien hablé con luis. Los muñequitos tienen que ser personas reales. El checkbox al final solamente, al igual que la pantalla de las apps y los bullet points alinealos a la izquierda, no los hagas centrados.

**Comment by arnaldos** [comment]
@furszy pero en ese caso los bullet points se mantienen en una linea horizontal ??? se va ver raro eso no crees ? no se va a ver desorganizados ?

**Comment by emmysm** [comment]
Lo mismo pensé @arnaldos @furszy

**Comment by furszy** [comment]
Es pedido de @Luis-Fernando-Molina, ël va a poder explicarlo mejor.

**Comment by Luis-Fernando-Molina** [comment]
correcto, los bullet points justificados a la iz.

El icono de ALpha under construction no se entiende.  Van a tener que agregar Alpha Version supongo ademas de una imagen

**Comment by furszy** [comment]
completado.
