### ISSUE TITLE
Logo para Fermat Shop

### ISSUE THREAD

**Issue by Luis-Fernando-Molina** [bitDubai/fermat-graphic-design#76]
Diseñar un logo para este concepto y colocarlo en la presentación.

![screenshot from 2015-08-17 12 39 45](https://cloud.githubusercontent.com/assets/9479367/9303318/6acd86f6-44dd-11e5-8d35-88b3b2e81c54.png)

**Comment by m471c4** [comment]
Primera propuesta para Fermat Shop.`

![fermat shop](https://cloud.githubusercontent.com/assets/13468350/9435679/7c8c20f6-4a13-11e5-8f1a-8f16d13b2a90.png)

**Comment by Luis-Fernando-Molina** [comment]
@m471c4 Perfcto! :+1:  Aprobado! Pregunta el tipo de ltra de SHP y Shop es el mismo que Fermat?

**Comment by Luis-Fernando-Molina** [comment]
Otra cosa, debiera decir "Shopping Platform" en vez de "Shop"

**Comment by m471c4** [comment]
Perfecto. Si @Luis-Fernando-Molina, es el mismo tipo de letra (Canaro). Igual consultaré con @arnaldos. Corregiré la parte de Shopping Platform, creo que queda mejor además.

**Comment by Luis-Fernando-Molina** [comment]
Otra cosa, ya necesito todos estos logos para poder ponerlos en el sitio Fermat.org. Aegurate de que estén todos los casos de los logos avanzando de alguna manera.

**Comment by m471c4** [comment]
Subo acá la versión final.

![fermatshop](https://cloud.githubusercontent.com/assets/13468350/9454790/9146fd7e-4a8e-11e5-8338-282483d073a3.png)

**Comment by arnaldos** [comment]
@m471c4 para estas versiones de logos use canaro para la palabra fermat y para las iniciales use Aqua Grotesque. ya as subo al repo para que la des cargues.

**Comment by Luis-Fernando-Molina** [comment]
@arnaldos la frase "Shopping Platform" que acá esta con la misma tipografia que Fermat, en todos los otros logos está igual, no???  Así como está esta es que me gusta, incluyendo el tampaño, color y tipo de letra.

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina si en los otros logos también mantienen la tipografia canaro, la unica variacion de tipografia seria en las iniciales que le coloque "Aqua Grotesque"

**Comment by Luis-Fernando-Molina** [comment]
@bitDubai/graphic-design-team ok este caso se puede cerrar, pero, a quien estaba asignado?  Por favor repartanse todos los casos que hay ya creados para que cada uno sepa de antemano que es lo que le queda pendiente. Gracias.

**Comment by m471c4** [comment]
@Luis-Fernando-Molina pensé que me lo había asignado ya. @arnaldos podemos asignarnos los que quedan para ir cerrándolos.

**Comment by arnaldos** [comment]
@m471c4 dale perfecto !!!
