### ISSUE TITLE
Refresh Fermat Logotype

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#762]
It will design a new logo for fermat to Replace current wallets.
The logo should be an armed planet with pieces very similar to wikipedia puzzle, we will leave the colors we already have

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina  I'll show you some options to new logo

#### Version 1

![nuevo logo fermat-01](https://cloud.githubusercontent.com/assets/13594347/14451293/c2996b4c-004f-11e6-88ce-45d2e5e180ac.jpg)

#### Version 2

![nuevo logo fermat-02](https://cloud.githubusercontent.com/assets/13594347/14451294/c29de50a-004f-11e6-9544-fc4f119ec224.jpg)

#### Version 3

![nuevo logo fermat-03](https://cloud.githubusercontent.com/assets/13594347/14451295/c2a2f464-004f-11e6-8c55-11885d280e77.jpg)

#### Version 4

![nuevo logo fermat-04](https://cloud.githubusercontent.com/assets/13594347/14451296/c2a69808-004f-11e6-9ad0-e269af79e992.jpg)

#### Version 5

![nuevo logo fermat-05](https://cloud.githubusercontent.com/assets/13594347/14451297/c2ab215c-004f-11e6-8c3e-925af32926ab.jpg)

**Comment by Luis-Fernando-Molina** [comment]
1. change the scale of the pieces please to look smaller please
2. also try the kind of pieces Jonathan used in 3d

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina I'll show you some options to the changes, In the version 6 I focused on the concept of the illuminati eye that sees everything . Overall, the all-seeing eye is a symbol of an omniscient entity , usually a deity who can see everything . like the eye of the end user if we take it to everyday life, it symbolizes the different puzzle pieces needed for fermat work completely perfectly and give the user the different tools that you can see on your screen. this being the all-seeing eye, the eye of Fermat, the eye of the end user.

#### Version 6

![nuevo logo fermat-06](https://cloud.githubusercontent.com/assets/13594347/14474688/23afc318-00c8-11e6-9835-e1a166911e69.jpg)

#### Version 7 (chages puzzles)

![nuevo logo fermat-07](https://cloud.githubusercontent.com/assets/13594347/14474685/2379e75c-00c8-11e6-93dd-5213bf499f0e.jpg)

#### Version 8 (chages puzzles)

![nuevo logo fermat-08](https://cloud.githubusercontent.com/assets/13594347/14474686/239d5a0c-00c8-11e6-8646-c2e9e87dac61.jpg)

#### Version 9 (chages puzzles)

![nuevo logo fermat-09](https://cloud.githubusercontent.com/assets/13594347/14474687/23aed0c0-00c8-11e6-9435-65ab8316ce06.jpg)

**Comment by Luis-Fernando-Molina** [comment]
please we need more options here @Fermat-ORG/2d-graphic-design-team 

Also:
- do the  logo bigger, we will find a way later to have a smaller version
- the logo mus represent at the same time:

1- Internet of People
2- P2P Economy
3- Application Framework built with components

The current idea reflects #3 somehow, but not the others. 

More suggestions needed, at least a few pero each designer please.

**Comment by Luis-Fernando-Molina** [comment]
@arnaldos some feedback from Perry:

> Logo development looks good - version 3 (https://cloud.githubusercontent.com/assets/13594347/14451295/c2a2f464-004f-11e6-8c55-11885d280e77.jpg) and 4 (https://cloud.githubusercontent.com/assets/13594347/14451296/c2a69808-004f-11e6-9ad0-e269af79e992.jpg) being the most promising so far.
> 
> The handshake/exchange element itself should be part of the modularity. The idea should be to convey that Fermat is building a modular framework that enables the "handshake." When the modules come together, both the world becomes complete and the handshake becomes possible. That's the idea that should be conveyed visually. The handshake icon should be integrated into the modular globe rather than drawn as a separate element that wraps around it. This is a very crude, partial example of what I mean:
> http://comps.canstockphoto.com/can-stock-photo_csp4249278.jpg
> Haven't yet found a more elegant example.

**Comment by Luis-Fernando-Molina** [comment]
Try to see if somehow the pieces could be hands that when used to form the globe they could be giving handshakes between them.

**Comment by arnaldos** [comment]
I will work under the last comments that you requesting me to achieve result.

**Comment by Luis-Fernando-Molina** [comment]
@arnaldos call the other designers to make proposals please (as soon as possible)

**Comment by arnaldos** [comment]
ok perfect !!!

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina  new logo variations taking your comments and the perry too.

##### Version 10

![nuevo logo fermat-11](https://cloud.githubusercontent.com/assets/13594347/14520130/a097b546-01ec-11e6-830f-06520def01c2.jpg)

##### Version 11

![nuevo logo fermat-12](https://cloud.githubusercontent.com/assets/13594347/14520131/a09c1d34-01ec-11e6-85a1-2e5722535ef1.jpg)

##### Version 12

![nuevo logo fermat-13](https://cloud.githubusercontent.com/assets/13594347/14520132/a09ffb34-01ec-11e6-9451-e6f12472856b.jpg)

##### Version 13

![nuevo logo fermat-14](https://cloud.githubusercontent.com/assets/13594347/14520133/a0a471a0-01ec-11e6-9146-0e627fd439fc.jpg)

##### Version 14

![nuevo logo fermat-15](https://cloud.githubusercontent.com/assets/13594347/14520134/a0a8848e-01ec-11e6-8cea-959958bacebc.jpg)

**Comment by Luis-Fernando-Molina** [comment]
> Try to see if somehow the pieces could be hands that when used to form the globe they could be giving handshakes between them.

please try to do what it says above

**Comment by proseuz** [comment]
@arnaldos @Luis-Fernando-Molina  Here are my proposals
I take my idea from suggestions Perry: **"The idea should be to convey that Fermat is building a modular framework that enables the "handshake." When the modules come together, both the world becomes complete and the handshake becomes possible. That's the idea that should be conveyed visually".**

puzzle pieces represent the people who join the network fermat

*\* Proposal 1**
![new logo fermat 1](https://cloud.githubusercontent.com/assets/17308060/14535928/ef336536-0239-11e6-8558-3bfb8556b54c.png)
![new logo fermat 4](https://cloud.githubusercontent.com/assets/17308060/14535911/e09a76e0-0239-11e6-9f6c-162f60c5344b.png)

**Proposal 2**
![new logo fermat 2](https://cloud.githubusercontent.com/assets/17308060/14535948/061822dc-023a-11e6-8357-c9a9bb927bd1.png)
![new logo fermat 3](https://cloud.githubusercontent.com/assets/17308060/14535896/d1976374-0239-11e6-9175-fce639d22dc2.png)

**Comment by Luis-Fernando-Molina** [comment]
@pqdeep your thoughts ?

**Comment by Luis-Fernando-Molina** [comment]
@jhonmarquez92 please continue from your proposal 2 giving more alternatives and ideas. Looks promising.

**Comment by Luis-Fernando-Molina** [comment]
Try changing the scale making the pieces smaller please.

**Comment by arnaldos** [comment]
@jhonmarquez92 excelent work !!! I like your proposal, very good.

**Comment by adryx83** [comment]
Good afternoon this is my Fermat Logo proposal...

![logo fermat propuestas](https://cloud.githubusercontent.com/assets/17273349/14543515/4e07aef4-025e-11e6-8c95-000a36a82397.jpg)

**Comment by proseuz** [comment]
@arnaldos @Luis-Fernando-Molina 
**here changes for my proposal.**
- I made the smallest pieces
- Gradation of the pieces to simulate that are building the world of fermat
  **Proposal 1**
  ![new logo fermat 7](https://cloud.githubusercontent.com/assets/17308060/14547090/31b92082-0274-11e6-8628-bce658cd30e1.png)
- Change the color of the component to highlight

**Proposal 2**
![new logo fermat 8](https://cloud.githubusercontent.com/assets/17308060/14547091/31f338ee-0274-11e6-9d94-013204c654f1.png)
**Proposal3**
![new logo fermat 6](https://cloud.githubusercontent.com/assets/17308060/14547094/3246a4ca-0274-11e6-861b-938306993f7a.png)

**Comment by arnaldos** [comment]
@jhonmarquez92 I like version 1 because it has more color green. since inside the launcher it is one of the most predominant colors . so we can not leave unnoticed

**Comment by proseuz** [comment]
@arnaldos you're right. I also like proposal 1. @Luis-Fernando-Molina what do you think?

**Comment by Luis-Fernando-Molina** [comment]
Hi guys, very good job. Lets continue refining Proposal 1 of @jhonmarquez92 only, the rest of the ideas we can pause them.

I would like to see options combining the following:
1. Even smaller pieces
2. A color ballance in the same proportions than the wallet of the current logo. Notice that black is not there. 
3. A 3d version in contrast to this 2d flat one. (think of the wikipedia world logo)

**Comment by proseuz** [comment]
@Luis-Fernando-Molina 
3D version with the changes suggested

![new logo fermat 9](https://cloud.githubusercontent.com/assets/17308060/14575427/8df01790-032b-11e6-9542-bf04e574e75d.png)

**Comment by Luis-Fernando-Molina** [comment]
Hi very good, we are almost there.

Try this: the flying people there are now 3 rows with two of them people are upside down and one is not. Try to invert that so most of the people is not up side down.

**Comment by Luis-Fernando-Molina** [comment]
Another trick:

Right now the sphere vertical axis is straight up. Put the north pole closer and the south farther by inclining the axis. Also  incline the top of the axis a little bit to the right.

Once done set missing pieces to be the one of the north pole, that would prevent to show the distorted pieces of the north pole (because they are missing) and the south pole (because they are behind).

Also make the pieces fly to the right instead of to the left as it is now. (most of the people should be up and not up side down)

**Comment by proseuz** [comment]
ok I'll corrections

**Comment by proseuz** [comment]
@Luis-Fernando-Molina 
![new logo fermat 10](https://cloud.githubusercontent.com/assets/17308060/14577567/91a1c474-033f-11e6-8f20-3d346f66ece2.png)

**Comment by proseuz** [comment]
@Luis-Fernando-Molina 
![new logo fermat 11](https://cloud.githubusercontent.com/assets/17308060/14577922/314e92e0-0345-11e6-8699-57b35e27df11.png)

**Comment by Luis-Fernando-Molina** [comment]
And this?

> Right now the sphere vertical axis is straight up. Put the north pole closer and the south farther by inclining the axis. Also incline the top of the axis a little bit to the right.
> 
> Once done set missing pieces to be the one of the north pole, that would prevent to show the distorted pieces of the north pole (because they are missing) and the south pole (because they are behind).

Al parecer no me entendiste en ingles, te lo digo en español:

Gira la esfera de manera que el polo norte (donde estan la fichas rojas, la parte de arriba), quede hacia adelante, mas cerca del observador, y al mismo tiempo el polo sur (donde estan las fichas verdes) quede oculto.

Al girarlo la distorición de las piezas que se ve en los polos quedaria oculta en el caso del polo sur, y seria mas evidente en el polo norete que quedaria mas de frente. El truco esta en que las piezas del polo norte sea en gan medida las que faltan.

Adicional a eso te pedia que girel el eje un poco en el sentido de las agujas del reloj.

**Comment by pqdeep** [comment]
hello everyone - 

@jhonmarquez92 - great work on the logo designs. 

https://cloud.githubusercontent.com/assets/17308060/14577567/91a1c474-033f-11e6-8f20-3d346f66ece2.png - looks good. I'd restore the axis tilt as @Luis-Fernando-Molina suggested.

But I think it might be best to have most of the people/components upside down, otherwise some might confuse the image as an illustration of components breaking apart/away from the globe rather than being assembled into a globe

**Comment by Luis-Fernando-Molina** [comment]
> But I think it might be best to have most of the people/components upside down, otherwise some might confuse the image as an illustration of components breaking apart/away from the globe rather than being assembled into a globe

ok @jhonmarquez92 plese draw it both way to see how they work as what @pqdeep says makes sense.

**Comment by proseuz** [comment]
@Luis-Fernando-Molina  @pqdeep @arnaldos 
good afternoon everyone.
I made the changes . I turned the axis line , but the red parts deform
**Version 1**
![new logo fermat 12](https://cloud.githubusercontent.com/assets/17308060/14583085/0d2efbc4-03e1-11e6-98d7-897597e30b67.png)

**Version 2**
I changed the direction of the flying people
![new logo fermat 14](https://cloud.githubusercontent.com/assets/17308060/14583087/0d83e698-03e1-11e6-962c-7cb80de1ea9b.png)

**Comment by proseuz** [comment]
I like the version 2.

**Comment by Luis-Fernando-Molina** [comment]
Ok, @jhonmarquez92 lets continue with version #2 
1. Try tilting more the globe so as the north pole is even more visible
2. As far as I can see you havent tilted to the right
3. Take the pieces away more from the north pole than from below

@jonathanborges3d @DexybelVillanueva we need your help here to produce a 3d version of verson 2 (the last version 2). 

Please read the comments below.

@jonathanborges3d you can complete the sphere from the behind with the same pieces on greyscale

@jhonmarquez92 please do your 2d version also.

thanks.

**Comment by pqdeep** [comment]
@jhonmarquez92 there's something odd about the curvature near the north pole - seems distorted.

Tilt, orientation and colors are good, but looking back on all of the designs, this earlier flat style with fewer components:
https://cloud.githubusercontent.com/assets/17308060/14547094/3246a4ca-0274-11e6-861b-938306993f7a.png
seemed "cleaner," simpler (good for small logo / favicon size), less distorted

**Comment by pqdeep** [comment]
@jhonmarquez92 Could you post transparent png versions (regular size and small) of 

https://cloud.githubusercontent.com/assets/17308060/14577922/314e92e0-0345-11e6-8699-57b35e27df11.png    

and

https://cloud.githubusercontent.com/assets/17308060/14583087/0d83e698-03e1-11e6-962c-7cb80de1ea9b.png

**Comment by Luis-Fernando-Molina** [comment]
> Tilt, orientation and colors are good, but looking back on all of the designs, this earlier flat style with fewer components:

Yes @pqdeep what I am looking for is the final version in terms of look and feel, orientation, etc, then from there we will take the collection of version to be used on every size, including small logo and favicon which most probably will be flat.

**Comment by jonathanborges3d** [comment]
![new_logo_3d_1](https://cloud.githubusercontent.com/assets/13649739/14621252/48e8f074-058b-11e6-8f01-dcff486e342c.jpg)

First version 3D

**Comment by victoralfonzohd** [comment]
Que tal @Luis-Fernando-Molina , vi el caso para la nueva imagen de Fermat y tengo una propuesta.

La nueva visión de lo que es Fermat le da un alcance sin fronteras y algo tan grande debería ser simple, sobrio y funcional, pienso que esto se logra con el uso de un Logotipo. 

Un símbolo o un icono en un logo siempre debe ser representativo de lo que es la empresa, y algo tan amplio como Fermat no puede encerrarse tan fácilmente en un icono ya que su constante crecimiento siempre va a necesitar una adaptación del icono que se tenga hasta el momento, que es justo lo que está pasando ahora.

La implementación de tipografía como imagen es lo que hacen las grandes corporaciones, cuando lo que ofrecen tiene tantos conceptos y cada concepto crece y no deja de hacerlo, el mejor ejemplo es google. 

Presento mi propuesta:

![fermat1](https://cloud.githubusercontent.com/assets/15219855/14621941/3f084adc-0590-11e6-800a-6f5a73b24638.png)

Tipografía Base: Chalet New York 1970

Personalidad versátil con una profunda modulación y contraste entre los trazos por la combinación de curvas y rectas 

La forma particular de la “e” y la “a” están pensadas en la interacción de las personas, parte del concepto “peer to peer economy” 

La “e” representa a la persona o usuario

La forma interna de la “a” tiene la forma sutil de una burbuja de dialogo representado la conexión y comunicación entre personas o usuarios

**Comment by Luis-Fernando-Molina** [comment]
@jonathanborges3d it is very good, lets refine it a little bit so we can get from there the different versions: 3d, 2d, large icon, medium, small, etc. Before that lets refine it:
1. There is one orange piece invading the green area. Please turn it green.
2. Also an orange invading the red at the bottom, please turn it red.
3. I like the pattern light / dark, please follow that rule everywhere for consistency.
4. Apply some curvature to the people flying, the closest to the sphere the more curvature get the illusion they are ready to fit there. 
5. Follow the dark / light pattern on the flying people.
6. Pieces seems to be separated by a white space, please close the gap.
7. Add more flying people at the end of the tale.
8. Add the pieces behind the visible ones, the back of the pieces should look grey.

Please don't change anything else except what is mentioned since everything else looks fine.

**Comment by Luis-Fernando-Molina** [comment]
@victoralfonzohd thanks but we are having too many open fronts by now to deal with a change on the fonts. As soon as we finish with this Fermat logo, we will design one logo for the "Internet of People" and the "Peer to Peer Economy" based in part on the results of this one. @arnaldos can you please create the issues so we start that discussion there?

**Comment by pqdeep** [comment]
@jonathanborges3d 
still lean toward simpler, flat (no 3D effect) version of logo, but
https://cloud.githubusercontent.com/assets/13649739/14621252/48e8f074-058b-11e6-8f01-dcff486e342c.jpg
looks good with no apparent distortions in the curvature. Only concern is how a small/favicon version might look, hence the preference the simpler, flat version with fewer components. Logos ideally should look good/clear in all sizes, color and B&W.

**Comment by pqdeep** [comment]
dont see any reason to change font at this point.

**Comment by jonathanborges3d** [comment]
![new_logo_3d_3](https://cloud.githubusercontent.com/assets/13649739/14691562/b39442f2-071b-11e6-9e2b-1b87182a2f58.jpg)

**Comment by arnaldos** [comment]
@jonathanborges3d  this is the final logo ??

**Comment by jonathanborges3d** [comment]
Yes, you can use it as base for 2D version.

**Comment by arnaldos** [comment]
perfect !!!! I'll start to work for this.

**Comment by Luis-Fernando-Molina** [comment]
@jonathanborges3d we need your version on the media kit on PNG different sizes

**Comment by jonathanborges3d** [comment]
@Luis-Fernando-Molina Here is the commit: https://github.com/Fermat-ORG/media-kit/commit/9b7ea3c82f7b397beeced12b269ab3207713dac0

**Comment by pqdeep** [comment]
Last logo version looks good - minor point: there's a piece (circled in red) that looks like it doesn't properly fit. Should either be modified or removed. Everything else looks smooth/distortion-free.

![1](https://cloud.githubusercontent.com/assets/13311619/14777880/2dd579fc-0ad0-11e6-87da-64c3b14cadd8.jpg)

**Comment by Luis-Fernando-Molina** [comment]
> Last logo version looks good - minor point: there's a piece (circled in red) that looks like it doesn't properly fit. Should either be modified or removed. Everything else looks smooth/distortion-free.

@jonathanborges3d please fix

@arnaldos please re-apply

**Comment by arnaldos** [comment]
ok I re-apply this !
