### ISSUE TITLE
Fermat network settings

### ISSUE THREAD

**Issue by furszy** [bitDubai/fermat-graphic-design#763]
Se debe crear una pantalla de settings que se lanzará desde el desktop, la misma debe tener:
Tipo de red (regtest,testnet,mainNet) en la parte superior, la cual hará de filtro para todo el contenido del cuerpo del fragmento.
Luego, en el cuerpo se pondrán el estado de los bloques descargados de la red, los nodos conectados, la latencia de cada nodo.
@acostarodrigo avisame si falta algo.
@arnaldos un diseño sencillo para esto necesitamos.

**Comment by acostarodrigo** [comment]
El estado de los bloques descargados de intenet debe ser a modo de tipo progress bar, que se irá completando hasta llegar al 100%.

La info se obtiene de 

``` /**
     * Gets the download progress from the specified network
     * @param blockchainNetworkType The network type we want to know the download progress
     * @return the BlockchainDownloadProgress class which includes information about pending blocks, total blocks, etc.
     * @throws CantGetBlockchainDownloadProgress
     */
    BlockchainDownloadProgress getBlockchainDownloadProgress(BlockchainNetworkType blockchainNetworkType) throws CantGetBlockchainDownloadProgress;
```

y

``` /**
     * Will get the BlockchainConnectionStatus for the specified network.
     * @param blockchainNetworkType the Network type we won't to get info from. If the passed network is not currently activated,
     * then we will receive null.
     * @return BlockchainConnectionStatus with information of amount of peers currently connected, etc.
     * @exception CantGetBlockchainConnectionStatusException
     */
    BlockchainConnectionStatus getBlockchainConnectionStatus(BlockchainNetworkType blockchainNetworkType)  throws CantGetBlockchainConnectionStatusException;
```

de la cryptoNetwork

**Comment by arnaldos** [comment]
@acostarodrigo perfecto !! @furszy me comenta que para representar el estado de los bloques descargados puede ser Una barra de progreso quizás con los bloques o algo que te diga que faltan desgargar @isahq23 plz ayúdame con este caso los mockups del desktop launcher están en el repo. cualquier duda me avisas

**Comment by furszy** [comment]
@arnaldos @isahq23 es una pantalla simple de settings, no se la compliquen y usen de base lo que se encuentra en material design de android please.

**Comment by arnaldos** [comment]
@furszy ok perfecto !!!

**Comment by arnaldos** [comment]
@isahq23 en el repo en 2D design vas a encontrar otra carpeta llamada toolbox ahi hay unos editables de una propuesta de settings pudieses usarla como base

**Comment by isahq23** [comment]
Algo así? A ver si entendí bien @arnaldos 

![network_settings_issue763_m1](https://cloud.githubusercontent.com/assets/15214774/14514938/102bd12c-01bf-11e6-9ee1-90104c9b08d7.jpg)

**Comment by arnaldos** [comment]
@isahq23 yo lo entendi de la misma manera, solo los iconos de la equis, el check, etc se ven un poco grande no se si al verlos en un teléfono físico el tamaño sea el correcto. @furszy @acostarodrigo cuando puedan para que nos den el feedback

**Comment by furszy** [comment]
Debería estar la selección del tipo de red visible, no es un expandible eso, queda mejor como popup sin botones, después es una barra de progreso sola, y abajo van los datos que @acostarodrigo les diga con respecto a los nodos.

**Comment by arnaldos** [comment]
El pop-up puede ser similar al que esta en el launcher de la app cuando seleccionas el filter ? de esa manera lo entiendo es asi como lo visualizas?

**Comment by furszy** [comment]
Yes, ese mismo

**Comment by acostarodrigo** [comment]
Mi primer comentario es que esto es para mostrar la configuracion de las redes activas en el telefono.
Por lo tanto, no es correcto mostrar un selector de redes, sino que se van a mostrar las redes que ya esten activas.

Y por cada red activa, deben mostrar la misma configuracion:
- La barra del download de 0 a 100%
- Los nodos a los que estamos conectados (que generalmente van a ser 8 o 12), siendo para cada uno:
  - Node IP: 192.168.0.1:1900 
  - Latency: 340 ms
  - Version: Satoshi 12.03

Esto lo tienen que acomodar para las redes activas. Generalmente será una sola, por ejemplo TestNet, pero pueden ser tres, MainNet, TestNet y RegTest

Cada red con su barra de progreso y sus nodos.

Me avisan si quedan dudas.

**Comment by acostarodrigo** [comment]
Agrego que la barra de downloads es para mostrar el progreso de bloques que se estan bajando para la red activa en cuestión.

Cada 10 minutos se genera un bloque, por lo tanto el celu está todo el tiempo pendiente de bajar estos bloques. Si el celular está apagado un tiempo, luego baja todos los que se generaron durante ese tiempo. Los bloques son importantes para poder notificar las transacciones de bitcoins.

Informacion del download que les proveo es:
- Cantidad total de bloques a bajar
- Cantidad de bloques pendientes
- Cantidad de bloques bajados
- y Progreso en %

Fijensé si pueden acomodar algo de esto info en algun lado.

**Comment by furszy** [comment]
Se deberia programar mañana esto, Por favor cierren las ideas que @acostarodrigo resumió.

**Comment by arnaldos** [comment]
@isahq23 estaba trabajando en eso

**Comment by isahq23** [comment]
De hecho @acostarodrigo tengo varias dudas sobre tus comentarios. 
Esta área de la app es más técnica y realmente he trabajado muy poco con este tipo de aspectos.
Principalmente, ¿Por qué cada red tiene una barra de progreso y qué papel juegan los nodos?
¿Esto indica que habrán descargas por cada tipo de red seleccionado?

**Comment by isahq23** [comment]
@arnaldos @acostarodrigo 

![network_settings_issue763_m2](https://cloud.githubusercontent.com/assets/15214774/14573072/78d7bbce-031c-11e6-8fce-3c75e6c228d7.jpg)

**Comment by arnaldos** [comment]
@isahq23  la primera propuesta me gusta mas. @acostarodrigo y @furszy que nos den su opinión

**Comment by acostarodrigo** [comment]
Tengan en cuenta que lo que más importa es el progreso del download.
y que luego se mostraran 8 nodos con su informacion. Y eso se puede repetir para 3 redes distintas.

Para que no sea demasiado extensa la informacion a mostrar....yo mostraria Tabs para cada red activa.
![image](https://cloud.githubusercontent.com/assets/9518556/14575060/c8d8fe3a-0335-11e6-8290-ae040301f1dd.png)

Y luego primero iria el progreso del download
y abajo la info de los 8 nodos

**Comment by isahq23** [comment]
@acostarodrigo algo así? @arnaldos 

![network_settings_issue763_m3](https://cloud.githubusercontent.com/assets/15214774/14576790/37d5a6a8-0336-11e6-891e-0f227b3fd32d.jpg)

**Comment by furszy** [comment]
@isahq23 sin tabs arriba, poné un texto con el nombre de la red que al presionarlo abra un popup para cambiar de red y por lo tanto cambiar el cuerpo de la pantalla, los tabs no se usan para este tipo de vistas.

**Comment by isahq23** [comment]
@furszy así?

![network_settings_issue763_m4](https://cloud.githubusercontent.com/assets/15214774/14617960/25f45cc2-057a-11e6-877b-f4ed707e1927.jpg)

**Comment by furszy** [comment]
Si material design dice que el popup es así, así lo haré. Tiene que seguir todo una misma linea.

**Comment by isahq23** [comment]
@furszy esperemos a ver qué dice @arnaldos

**Comment by arnaldos** [comment]
@isahq23  @furszy esto como va a ser mostrado en fermat app. alinea el color del action bar colo lo que se esta trabajando, seria lo unico. 

![settings app 6-14](https://cloud.githubusercontent.com/assets/13594347/14689685/3773da92-0712-11e6-9198-42cafd9a0a36.jpg)

**Comment by furszy** [comment]
@arnaldos  no entendí eso que mandaste con este issue.

**Comment by arnaldos** [comment]
@furszy es para que tome referencia de color para el action bar es lo único para que se apegue con lo que se viene trabajando. si esto no aplica lo dejamos como se planteo inicialmente.

**Comment by isahq23** [comment]
@arnaldos @furszy aquí está

![network_settings_issue763_m5](https://cloud.githubusercontent.com/assets/15214774/14718254/745c71be-07bf-11e6-922b-3b7de11a8992.jpg)

**Comment by arnaldos** [comment]
perfecto, que opinas @furszy ?? creo que asi esta bien !

**Comment by furszy** [comment]
@arnaldos necesito el doc con colores, tamaños, etc

**Comment by isahq23** [comment]
@furszy voy con eso mati

**Comment by furszy** [comment]
dale gracias, y una consulta. Para que son las tres progress bar? que hace cada uno desde su punto de vista?. porque no tenia eso en la cabeza.

**Comment by isahq23** [comment]
@furszy pues hablé con @acostarodrigo y me aclaró que dependiendo de la app existirá una red conectada y por supuesto cada una tiene como descargas propias... algo así como cuando descargas de distintos servidores: la dirección es distinta. Así lo entendí yo.

**Comment by furszy** [comment]
@isahq23 la red posee solo un progress bar y puede tener varios nodos conectados. por favor podrias hacer una pantalla con un progress bar arriba y la información de los nodos conectados abajo.

**Comment by acostarodrigo** [comment]
el orden de las cosas seria algo asi:

El progress bar, y luego los nodos conectados abajo. Los nodos conectados pueden llegar a ser ocho y uno solo, (el primero) debe tener la marca. Eso indicaria que es el nodo principal al que estamos conectados y de donde estamos haciendo el download en ese momento.

![image](https://cloud.githubusercontent.com/assets/9518556/14819586/2f7c2656-0b99-11e6-8f38-f3a3f6e24af7.png)

![image](https://cloud.githubusercontent.com/assets/9518556/14819564/1135939e-0b99-11e6-9023-21b6288c5e45.png)
![image](https://cloud.githubusercontent.com/assets/9518556/14819575/1efb7c82-0b99-11e6-9fde-396c0e1a43db.png)
![image](https://cloud.githubusercontent.com/assets/9518556/14819577/1f5a0be4-0b99-11e6-904e-7121d2827625.png)

**Comment by isahq23** [comment]
@acostarodrigo @furszy @arnaldos 
Entonces se vería así.

![network_settings_m1](https://cloud.githubusercontent.com/assets/15214774/14828502/035841b4-0bb1-11e6-8e2b-29eebd441c28.jpg)

**Comment by arnaldos** [comment]
por mi esta bien ! que dices @furszy ?

**Comment by furszy** [comment]
ok

**Comment by arnaldos** [comment]
@isahq23 pasale los recursos a @furszy

**Comment by isahq23** [comment]
@arnaldos está listo, ya le pasé ayer todo lo necesario a Marías

**Comment by arnaldos** [comment]
perfect cierro el caso !!
