### ISSUE TITLE
Create UI for all views of groups creation

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#764]
Issue base https://github.com/Fermat-ORG/fermat/issues/5662

**Comment by arnaldos** [comment]
@franklinmarcano1970 @josejcb I share the sequence of mockups.

![fermat_chat_group](https://cloud.githubusercontent.com/assets/13594347/14513248/95160480-01af-11e6-9dcb-2cfe86f7f5a3.png)

**Comment by franklinmarcano1970** [comment]
@Lozadaa

**Comment by arnaldos** [comment]
@franklinmarcano1970 @Lozadaa @josejcb this mockups is more complete 

![fermat_chat_group_2](https://cloud.githubusercontent.com/assets/13594347/14552503/f0cf1394-02a8-11e6-960b-927a7de6cc87.png)

**Comment by josejcb** [comment]
Excellent, maybe the words Done and Create do not fit here if you see the apps that we have in our phones. Most of them just have the image, and the user understand it. @franklinmarcano1970 @Lozadaa  @Fermat-ORG/kabuto-team  what do you think about the red font color for names in the messages list? Gray as Wapp or Red? I like just like here.

**Comment by arnaldos** [comment]
@josejcb ok I delete the words and just leave the check icon, do you agree?

**Comment by josejcb** [comment]
Yes, I do.

**Comment by arnaldos** [comment]
@josejcb here the view whith the change of buttom. I´m creating the resources. in a short time i upload this.
![fermat_chat_app_views_7](https://cloud.githubusercontent.com/assets/13594347/14596848/e9b1e462-0512-11e6-9b74-88da2c2309cc.png)
