### ISSUE TITLE
Create UI for all views of broadcasting

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#765]
Issue base https://github.com/Fermat-ORG/fermat/issues/5662

**Comment by arnaldos** [comment]
@franklinmarcano1970 @josejcb I share the sequence of mockups.

![fermat_chat_broadcast](https://cloud.githubusercontent.com/assets/13594347/14513238/7f3f418a-01af-11e6-82db-1face8697c08.png)

**Comment by franklinmarcano1970** [comment]
@Lozadaa

**Comment by Lozadaa** [comment]
Please review these mockups . It is missing the scheduled message sending ..

**Comment by arnaldos** [comment]
@franklinmarcano1970 @Lozadaa @josejcb New mockups, include Scheduled Broadcast and Simple Broadcast. if this needs other component just tell me and i make this.

##### Broadcast Scheduled

![fermat_chat_broadcast_1](https://cloud.githubusercontent.com/assets/13594347/14514855/29db173c-01be-11e6-9b96-27d2a8ae8f84.png)

##### Simple Broadcast

![fermat_chat_broadcast_2](https://cloud.githubusercontent.com/assets/13594347/14514856/29dfdb32-01be-11e6-94f5-376e173f8472.png)

**Comment by josejcb** [comment]
Agrega en la segunda pantalla la posibilidad de colocarle nombre a la difusion.

**Comment by arnaldos** [comment]
@franklinmarcano1970 @Lozadaa @josejcb New mockups, I change the wheel selector for a dialog pop-up if you want make this more simple and the buttom cancel and other buttom of the action bar is more simple too.

##### Broadcast Scheduled 2

![fermat_chat_broadcast_3](https://cloud.githubusercontent.com/assets/13594347/14552424/286e3592-02a8-11e6-8f66-2434751cc11b.png)

##### Simple Broadcast 2

![fermat_chat_broadcast_4](https://cloud.githubusercontent.com/assets/13594347/14552425/2871c0cc-02a8-11e6-9721-92b3d1829a39.png)

**Comment by josejcb** [comment]
Nice
