### ISSUE TITLE
Loader for print old messages in the current chat

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#766]
Issue base Fermat-ORG/fermat#5662

**Comment by arnaldos** [comment]
@franklinmarcano1970 @Lozadaa @josejcb here load message buttom 

![fermat_chat_load_message_buttom](https://cloud.githubusercontent.com/assets/13594347/14552413/f31b1b26-02a7-11e6-8253-4d3ca6383045.png)

**Comment by josejcb** [comment]
Nice, for this one we do not need resources because we can code this button. Just need the color code, I think.

**Comment by arnaldos** [comment]
@josejcb the code of buttom is #292929

**Comment by arnaldos** [comment]
@josejcb @franklinmarcano1970 podemos cerrar este caso ???

**Comment by josejcb** [comment]
Si.
