### ISSUE TITLE
DAP__stats_Asset_Wallet_Issuer

### ISSUE THREAD

**Issue by ivonnesantos** [bitDubai/fermat-graphic-design#767]

**Comment by ivonnesantos** [comment]
desarrollar concepto visual tomando en cuenta los bocetos de @javafrank 
![screenshot from 2016-04-11 19 29 12](https://cloud.githubusercontent.com/assets/13275281/14446088/fb5d32da-001b-11e6-85f9-8fa2504cbbaa.png)

**Comment by ivonnesantos** [comment]
![stats_desing-01](https://cloud.githubusercontent.com/assets/15238660/14730096/61868432-080d-11e6-9a0b-c582390284ff.png)
@javafrank @nindriago

**Comment by javafrank** [comment]
excelente!

cada estatus va a tener un color distinto, tal como lo tenemos actualmente, actualmente lo tenemos asi pero se pueden cambiar:

unused: E7212C
appropriated: E7212C
redeemed: 013572
selled: no tiene

me parece que está muy bien así la pantalla.

**Comment by ivonnesantos** [comment]
Colores de los status se manejaran entre dos variables activo (redimir, apropiar, vender) o inactivo (no utilizado) esto es aplicable para status futuros 
![stats_desing-01](https://cloud.githubusercontent.com/assets/15238660/14753879/d90dd21e-08a1-11e6-83d1-565ea4092324.png)
@javafrank @nindriago

**Comment by arnaldos** [comment]
@ivonnesantos @javafrank @nindriago esto esta implementado para cerrar el caso ?
