### ISSUE TITLE
Crear los diferentes Tamaños Requeridos en World Press & Favicon

### ISSUE THREAD

**Issue by Luis-Fernando-Molina** [bitDubai/fermat-graphic-design#77]
Viene de https://github.com/bitDubai/fermat-graphic-design/issues/22#issuecomment-133097726

Es necesario disponer de las dierentes tamaños del logo de bitDubai para reemplazar los logos en el sitio web.

Adicional a esto es necesario crear un favicon para bitdubai que no sea el logo de Fermat.

Cada logo debe estar en cada uno de estos tamaños en el repositorio de fuentes.

**Comment by Luis-Fernando-Molina** [comment]
![wp1](https://cloud.githubusercontent.com/assets/9479367/9405994/eac9fb7e-47fc-11e5-8e61-e5cee1f32b8e.png)
![wp2](https://cloud.githubusercontent.com/assets/9479367/9405996/ed069db6-47fc-11e5-8a0b-a854b048253c.png)
![wp3](https://cloud.githubusercontent.com/assets/9479367/9406000/f057cbac-47fc-11e5-8827-f239e77f5c64.png)
![wp4](https://cloud.githubusercontent.com/assets/9479367/9406003/f2559196-47fc-11e5-9e78-4607a6814742.png)

**Comment by m471c4** [comment]
Puedo armar la carpeta con los diferentes tamaños hoy, solo necesitaría ayuda para subirlos al repositorio.

**Comment by Luis-Fernando-Molina** [comment]
Pedile a Jorge o Matias please

**Comment by m471c4** [comment]
@Luis-Fernando-Molina,@lnacosta me dará la mano con eso. ¿Podríamos usar el logo cuadrado como favcon? veo que las dimensiones son diferentes; para ajustar las imágenes ¿debo guiarme por el alto o el ancho?

Otra cosa ¿las subo en png? Si es así ¿deben llevar el fondo blanco o transparente?

**Comment by Luis-Fernando-Molina** [comment]
imposible , el favon mas chico es de 16 x 16, jamas se pudiera leer el logo cuadrado ahi. Hay que inventar algo.

**Comment by m471c4** [comment]
En ese caso sería necesaria una imagen con mucha síntesis para lograr que se distinga, pero manteniendo la identidad de bitDubai. ¿Tal vez jugando con los colores, eliminando la palabra árabe y dejando solo las inciales (bD)?

**Comment by m471c4** [comment]
@Luis-Fernando-Molina es muy muy pequeño, pero creo que esto logra asociarse bastante a la imagen. Espero tu opinión.

![favicon-16x16](https://cloud.githubusercontent.com/assets/13468350/9416055/31e0a3f4-480d-11e5-959d-5e935943b932.png)
![favicon-60x60](https://cloud.githubusercontent.com/assets/13468350/9416056/32041b36-480d-11e5-8cf6-365bd5696448.png)

**Comment by Luis-Fernando-Molina** [comment]
quizas lo que haya que buscar sea un objeto que represente bitDubai y que pueda iconizarse

**Comment by m471c4** [comment]
¿Alguna sugerencia? @arnaldos, en cuanto puedas me gustaría tener tu opinión al respecto.
