### ISSUE TITLE
Create Logo for P2P Bussines

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#771]

**Comment by JefersonBorgesS** [comment]
Propuesta 1
![business](https://cloud.githubusercontent.com/assets/17457984/14648323/8b08bd7c-062b-11e6-899f-bf9e60f4ce12.png)

2
![business2](https://cloud.githubusercontent.com/assets/17457984/14648331/91b6939c-062b-11e6-84a6-46b1c47dc178.png)

3
![business3](https://cloud.githubusercontent.com/assets/17457984/14648334/96a438c8-062b-11e6-9bd8-7836662c29a1.png)

**Comment by arnaldos** [comment]
@jayborges puede andar por la versión 2 genera otras propuestas partiendo de ahi

**Comment by JefersonBorgesS** [comment]
@arnaldos 
1
![business4](https://cloud.githubusercontent.com/assets/17457984/14650690/97d0e8da-0636-11e6-9e32-aeb9e71f0486.png)

2
![business5](https://cloud.githubusercontent.com/assets/17457984/14650696/a31d852c-0636-11e6-9f20-5970ab1b131e.png)

3
![business6](https://cloud.githubusercontent.com/assets/17457984/14650699/a35490a8-0636-11e6-8072-f10e2c47983d.png)

**Comment by arnaldos** [comment]
replantealo plz el icono picado a la mitad no funciona

**Comment by JefersonBorgesS** [comment]
@arnaldos ok como me habias dicho que hiciera propuestas a partir de ese...

**Comment by JefersonBorgesS** [comment]
@arnaldos Esta con el icono completo
![business9](https://cloud.githubusercontent.com/assets/17457984/14825445/da518d46-0ba3-11e6-94f1-56cdc67265a2.png)

y esta nuevas

![business8](https://cloud.githubusercontent.com/assets/17457984/14825469/ea115d1a-0ba3-11e6-940c-eac65809e008.png)

![business7](https://cloud.githubusercontent.com/assets/17457984/14825476/edabee4a-0ba3-11e6-8de6-738277c3bb7e.png)

**Comment by arnaldos** [comment]
@gabymado este modelo de negocios se definirá para mas adelante ?
