### ISSUE TITLE
Create Logo for P2P Micro Payment

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#772]

**Comment by JefersonBorgesS** [comment]
Propuesta 1
![mircopayments](https://cloud.githubusercontent.com/assets/17457984/14573631/ff1720be-031f-11e6-83ad-ca5fd97e96ab.png)

Propuesta 2
![mircopayments2](https://cloud.githubusercontent.com/assets/17457984/14573632/076fe25a-0320-11e6-9d96-2d649bac04e5.png)

**Comment by arnaldos** [comment]
@jayborges usa solo las 3 torres de monedas, cambia los colores para que no se vean que son descargados de una pagina de vectores, modifica también la sombra. elimina el símbolo del dollar para no hacer énfasis a un solo tipo de divisa.

**Comment by arnaldos** [comment]
replantealo plz

**Comment by JefersonBorgesS** [comment]
1
![mircopayments6](https://cloud.githubusercontent.com/assets/17457984/14680529/73007bd6-06e7-11e6-9582-53dcdc2e8989.png)
2
![mircopayments7](https://cloud.githubusercontent.com/assets/17457984/14680530/7303ad60-06e7-11e6-8613-8ae113eabcba.png)
3
![mircopayments8](https://cloud.githubusercontent.com/assets/17457984/14680531/730aafca-06e7-11e6-9441-bf96a090f15c.png)
4
![mircopayments9](https://cloud.githubusercontent.com/assets/17457984/14680532/730c56a4-06e7-11e6-96e6-bd282d594fc8.png)

**Comment by arnaldos** [comment]
@jayborges genera un logo que represente micro pagos, esto que planteas no se ve como un logo, hay demasiados elementos para un logo.

**Comment by JefersonBorgesS** [comment]
@arnaldos ok

**Comment by JefersonBorgesS** [comment]
Propuestas Nuevas
1
![mircopayments10](https://cloud.githubusercontent.com/assets/17457984/14794468/1dba74f0-0aee-11e6-9473-6e1dbe73dc09.png)
2
![mircopayments11](https://cloud.githubusercontent.com/assets/17457984/14794828/8a6935a4-0aef-11e6-9fb1-a0f99833b40c.png)
3
![mircopayments12](https://cloud.githubusercontent.com/assets/17457984/14794839/955bad16-0aef-11e6-9cdf-8d2d58865009.png)

**Comment by arnaldos** [comment]
@jayborges Cual es la diferencia de ambos ? de verdad no puedo creer que desde mi ultimo comentario que fue hace 7 días y hace 2 días posteaste, lo que significa pasaste 5 días para mostrarme esto, de verdad esto lo hace cualquiera en 5 min. 

![captura de pantalla 4](https://cloud.githubusercontent.com/assets/13594347/14874445/ea67b51c-0cc9-11e6-93a0-dde0465ab514.png)

enlace de la imagen
https://www.google.co.ve/search?sa=G&hl=es-VE&q=condiciones+de+pago&tbm=isch&imgil=uI62-m0Mkg3wdM%253A%253B6b9fj9Ifi4buqM%253Bhttps%25253A%25252F%25252Felectrojaponesa.com%25252Finterna%25252Fterrminos-condiciones-de-uso-3&source=iu&pf=m&tbs=simg:CAESqAEJSxE1aZEv_1z0anAELEKjU2AQaBAgACAMMCxCwjKcIGmIKYAgDEii-AtESgQmRAdcG0BKDCaIUmgqyAZA06DajNI40_1zPnNrco_1jPXNp80GjAey_1bLczfriEsaMzl32o6FSNshQSv7q3Fkx6XixFUHTI2DWiKFEmpUjX0bbXqGiQcgAwwLEI6u_1ggaCgoICAESBGvC7KAMCxCd7cEJGggKBgoEaWNvbgw&fir=uI62-m0Mkg3wdM%253A%252C6b9fj9Ifi4buqM%252C_&usg=__YaYV3jZrOmnTovG-kH9juNHjYzM%3D&biw=1366&bih=599&ved=0ahUKEwj6w9b7rbDMAhUDGR4KHdHQCiAQyjcIPw&ei=OH8hV_rHBYOyeNGhq4AC#imgrc=uI62-m0Mkg3wdM%3A

**Comment by arnaldos** [comment]
@arismendi227 plz encárgate de este caso

**Comment by arismendi227** [comment]
@jhonmarquez92 @arnaldos @emmysm 
propuestas para Micro Payment
1
![1](https://cloud.githubusercontent.com/assets/19276382/15576380/668b604a-2321-11e6-8e4f-eaed04307dce.png)

2
![2](https://cloud.githubusercontent.com/assets/19276382/15577056/b395a406-2324-11e6-9d64-5bd7416d875e.png)

3
![3](https://cloud.githubusercontent.com/assets/19276382/15577064/b9624bb4-2324-11e6-85da-1213ef9bb2d4.png)

4
![4](https://cloud.githubusercontent.com/assets/19276382/15577070/bf7590d8-2324-11e6-8e3f-8fc8c59623de.png)

5
![5](https://cloud.githubusercontent.com/assets/19276382/15577076/c3f2dd3c-2324-11e6-8ada-f330c5197ad9.png)

6
![6](https://cloud.githubusercontent.com/assets/19276382/15577083/cae71130-2324-11e6-93a7-3643d8be40f1.png)

7
![7](https://cloud.githubusercontent.com/assets/19276382/15577088/cfb3511a-2324-11e6-9923-4f27e63b6268.png)

8
![8](https://cloud.githubusercontent.com/assets/19276382/15577094/d7ba1768-2324-11e6-9584-ba4347568d3b.png)

9
![9](https://cloud.githubusercontent.com/assets/19276382/15577101/dd1736fa-2324-11e6-8bba-3901382538a3.png)

10
![10](https://cloud.githubusercontent.com/assets/19276382/15577130/f0e9af96-2324-11e6-829d-ef083cf77d67.png)

**Comment by proseuz** [comment]
mejorale lo siguiente a la propuesta 7

ponle la base del 9
reduce la paleta de colores a 3 (crea varias propuestas)
el engranaje déjalo en negativo
quitale el símbolo de dolar ( trata de ponerle un borde o un bisel para que parezca moneda)
revisa que las figuras del fondo tengan la misma separación

que opinan? @emmysm @arnaldos

**Comment by arnaldos** [comment]
@arismendi227 para este yo eliminaria el engranje ya que el engranaje no me indica que este relacionado a micro payments mas bien lo veo como para un setting algo asi por eso eliminemos el engranaje, al igual que @jhonmarquez92 la propuesta 7 me gusta busca la manera de que el elemento se vea como una moneda en ves de la S del dollar coloca un M haciendo referencia a los micro pagos. y no quedas limitado a un tipo de monedas.

**Comment by arismendi227** [comment]
@jhonmarquez92 @arnaldos @emmysm 
correcciones 

1
![1](https://cloud.githubusercontent.com/assets/19276382/15658094/0b7dc30a-2682-11e6-8f57-07509426389d.png)
2
![2](https://cloud.githubusercontent.com/assets/19276382/15658100/12130fc2-2682-11e6-82f9-c65a79229225.png)
3
![3](https://cloud.githubusercontent.com/assets/19276382/15658101/17d45600-2682-11e6-912f-dd760b37cec0.png)
4
![4](https://cloud.githubusercontent.com/assets/19276382/15658102/1d057b22-2682-11e6-9e5f-a0da2d2a1b4b.png)
5
![5](https://cloud.githubusercontent.com/assets/19276382/15658103/211c0f28-2682-11e6-9040-ae0119d26179.png)
6
![6](https://cloud.githubusercontent.com/assets/19276382/15658106/258d3168-2682-11e6-8e6a-d580e38d819f.png)
7
![7](https://cloud.githubusercontent.com/assets/19276382/15658108/2afb85d2-2682-11e6-9d35-9065dd1a9f23.png)
8
![8](https://cloud.githubusercontent.com/assets/19276382/15658110/2f80dff8-2682-11e6-8ba4-a86b95dee3d4.png)

**Comment by arnaldos** [comment]
Evaluando las propuestas creo que debemos replantear el concepto y apoyarnos con elementos tipográfico. algo similar a payonner, paypal algo así por el estilo.

**Comment by arismendi227** [comment]
@jhonmarquez92 @arnaldos @emmysm 
nuevas propuestas tipográficas con la M   1,2,3,4,5,6,7,8,9,10,11,12 Y 13

![m1](https://cloud.githubusercontent.com/assets/19276382/15782668/fd11c2e4-2974-11e6-88b5-d0b722b4d521.png)

![m2](https://cloud.githubusercontent.com/assets/19276382/15782679/07e7e2b6-2975-11e6-9f2e-afdd502bee85.png)

![m3](https://cloud.githubusercontent.com/assets/19276382/15782693/1a85546c-2975-11e6-93ad-924c77a3c946.png)

![m4](https://cloud.githubusercontent.com/assets/19276382/15782701/1e796a22-2975-11e6-8ef2-bf41bdb8f486.png)

![m5](https://cloud.githubusercontent.com/assets/19276382/15782721/2e630f92-2975-11e6-8ff5-2c93ee7d7665.png)

![m6](https://cloud.githubusercontent.com/assets/19276382/15782725/326830cc-2975-11e6-9597-1c87ea6451fd.png)

![m7](https://cloud.githubusercontent.com/assets/19276382/15782731/37dd6f7c-2975-11e6-9c44-60f43b7f4449.png)

![m8](https://cloud.githubusercontent.com/assets/19276382/15782739/3e1b0dae-2975-11e6-9f93-2b15e937a75d.png)

![m9](https://cloud.githubusercontent.com/assets/19276382/15782750/45916790-2975-11e6-9491-4b2db1690efd.png)

![m10](https://cloud.githubusercontent.com/assets/19276382/15782757/4b5d594a-2975-11e6-8fd0-b0bbfd99c7c1.png)

![m11](https://cloud.githubusercontent.com/assets/19276382/15782762/50996f16-2975-11e6-9af2-ec2d0b7baadf.png)

![m12](https://cloud.githubusercontent.com/assets/19276382/15782770/54bd4b1c-2975-11e6-9339-ba6077a29101.png)

![m13](https://cloud.githubusercontent.com/assets/19276382/15782776/59d5e348-2975-11e6-87ca-114df8ddd04a.png)

**Comment by proseuz** [comment]
Porfa enumera las propuestas individualmente. Creo otras propuestas con  una M más "convencional" puedes incluir la P  (de MicroPayment) también. @arismendi227

**Comment by arnaldos** [comment]
totalmente de acuerdo con @jhonmarquez92

**Comment by arismendi227** [comment]
@ jhonmarquez92 @arnaldos @emmysm 
propuestas 

1
![1](https://cloud.githubusercontent.com/assets/19276382/15880696/9aacd34a-2cf9-11e6-8d5f-80592f16a7c3.jpg)

2
![2](https://cloud.githubusercontent.com/assets/19276382/15880707/ac4f54d8-2cf9-11e6-8a72-a0516e0d3148.jpg)

3
![3](https://cloud.githubusercontent.com/assets/19276382/15880712/b28960fa-2cf9-11e6-8ce3-e971235fbecd.jpg)

4
![4](https://cloud.githubusercontent.com/assets/19276382/15880720/c6b3e71c-2cf9-11e6-9a02-be1426d3eac7.jpg)

5
![5](https://cloud.githubusercontent.com/assets/19276382/15880722/cc4b88ce-2cf9-11e6-9d85-39c08c2fb288.jpg)

6
![6](https://cloud.githubusercontent.com/assets/19276382/15880734/dcf19ede-2cf9-11e6-8b9c-c33f4f3e1169.jpg)

7
![7](https://cloud.githubusercontent.com/assets/19276382/15880736/e523dee6-2cf9-11e6-8eb8-2780c1acaedb.jpg)

8
![8](https://cloud.githubusercontent.com/assets/19276382/15880743/edd90d54-2cf9-11e6-873a-25a7583fb0d9.jpg)

9
![9](https://cloud.githubusercontent.com/assets/19276382/15880755/0945df86-2cfa-11e6-99d9-6881d3fa9da6.jpg)

**Comment by proseuz** [comment]
yo creo que el 2do tiene potencial y se puede mejorar. que opinas @arnaldos

**Comment by arismendi227** [comment]
@jhonmarquez92 @arnaldos
propuestas 

1
![1](https://cloud.githubusercontent.com/assets/19276382/16065091/3a8f6bd0-3271-11e6-8f0c-f318e68e4949.jpg)

2
![2](https://cloud.githubusercontent.com/assets/19276382/16065098/4117db5e-3271-11e6-9c69-49b55c25c00d.jpg)

3
![3](https://cloud.githubusercontent.com/assets/19276382/16065103/4606a9ce-3271-11e6-9ceb-b3636c3a7bf4.jpg)

4
![4](https://cloud.githubusercontent.com/assets/19276382/16065105/4fb774b2-3271-11e6-8541-fbd407ea2f0d.jpg)

5
![5](https://cloud.githubusercontent.com/assets/19276382/16065107/5425b7ca-3271-11e6-9c4b-75a01732b623.jpg)

**Comment by proseuz** [comment]
@arismendi227 
**intenta  lo siguiente con la propuesta 4:**
- Prueba con otra tipografía, trata de buscar una tipografía con una modulación más fluida, quizá una itálica (no se si funcione pero puedes probar) 
- Refina los detalles y acabos del logotipo. debes tratar de que la tipografía luzca original, para eso debes modificarla un poco.
- Trata de que sea más compacto, me parece que se alarga mucho
- haz otras propuestas de colores, intenta con azules, amarillos, naranjas combinándolos con gris quizás, igual puedes proponer otra paleta

**Comment by arismendi227** [comment]
@jhonmarquez92 @arnaldos 
modificaciones y propuestas de color
(de la propuesta 1 a la 3 tipografia 1)
(de la 4 la 6 tipografia 2)

1
![1](https://cloud.githubusercontent.com/assets/19276382/16138775/d15afd14-340a-11e6-9079-254765f1f0e1.jpg)

2
![2](https://cloud.githubusercontent.com/assets/19276382/16138776/d589b416-340a-11e6-89db-c43f40630a95.jpg)

3
![3](https://cloud.githubusercontent.com/assets/19276382/16138780/daf07138-340a-11e6-886f-00c0d89d12f4.jpg)

4
![4](https://cloud.githubusercontent.com/assets/19276382/16138781/df2aad18-340a-11e6-8f14-3b1a145f4fc9.jpg)

5
![5](https://cloud.githubusercontent.com/assets/19276382/16138783/e4a45460-340a-11e6-8c61-68748997c952.jpg)

6
![6](https://cloud.githubusercontent.com/assets/19276382/16138786/e7f91830-340a-11e6-9239-7b00f34fcf5a.jpg)

**Comment by proseuz** [comment]
la propuesta 4, solo reduce un poco el tamaño de los círculos, cuida que último circulo no se acerque tanto a la t. @arismendi227 @arnaldos

**Comment by arismendi227** [comment]
@jhonmarquez92 @arnaldos 

aplicando las modificaciones de la propuesta 4

![7](https://cloud.githubusercontent.com/assets/19276382/16139309/befebe76-340f-11e6-8712-6357453ed013.jpg)

**Comment by proseuz** [comment]
Genial! se ve muy bien! qué opinas @arnaldos ?

**Comment by arnaldos** [comment]
muy bien la ultima version

**Comment by arnaldos** [comment]
esto ya esta en el repo ?

**Comment by arnaldos** [comment]
@arismendi227  esto esta en el repo ?
