### ISSUE TITLE
Generate a icon (logo) for Fan Community to Music Player App 

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#776]

**Comment by Carelsy** [comment]
Proposals for Fan Community to Music Player App @arnaldos @emmysm @Luis-Fernando-Molina ![propuesta-7](https://cloud.githubusercontent.com/assets/17755307/14626578/85d1bca2-05b6-11e6-9d71-6656a41d6b3a.png)
![propuesta-6](https://cloud.githubusercontent.com/assets/17755307/14626579/85d5ef7a-05b6-11e6-8775-d4080c92ac1b.png)

**Comment by arnaldos** [comment]
@Carelsy alinea el icono de acuerdo al de la app https://cloud.githubusercontent.com/assets/13594347/14576029/a756edd6-032f-11e6-99a8-e0845530847f.jpg

**Comment by Carelsy** [comment]
aquí esta la petición @arnaldos @emmysm @Luis-Fernando-Molina ![propuesta-4](https://cloud.githubusercontent.com/assets/17755307/14694085/e00a8dba-072e-11e6-9576-c91b3ec72037.png)

**Comment by arnaldos** [comment]
@Carelsy pudieses probar la diagramación que tienen los audífonos fijate esta uno mas arriba que el otro.

**Comment by Carelsy** [comment]
@arnaldos la idea era que las dos personas formaran el corazón con la mano. si bajo a una persona pierde el sentido del corazón, se ven los elementos flotando.
![propuesta-5](https://cloud.githubusercontent.com/assets/17755307/14694572/5d43fe5c-0733-11e6-9d9d-7e740160c4ea.png)

**Comment by arismendi227** [comment]
Proposals for Fan Community to Music Player App @jhonmarquez92 @arnaldos @emmysm
1
![m1](https://cloud.githubusercontent.com/assets/19276382/15262056/d661ce56-1929-11e6-87ac-f6cccef1b07a.png)
2
![m2](https://cloud.githubusercontent.com/assets/19276382/15262062/ddf2422c-1929-11e6-9d97-a75733cf6d71.png)
3
![m3](https://cloud.githubusercontent.com/assets/19276382/15262064/e56497b2-1929-11e6-9b2d-8e258a2ae6c7.png)
4
![m4](https://cloud.githubusercontent.com/assets/19276382/15262073/ef75a462-1929-11e6-9106-d4e74f490419.png)
5
![m5](https://cloud.githubusercontent.com/assets/19276382/15262077/f6030a5e-1929-11e6-8fc1-b4b5e49dd2ee.png)
6
![m7](https://cloud.githubusercontent.com/assets/19276382/15262090/04fee8c0-192a-11e6-94a3-d382d1dcec7b.png)

**Comment by darkestpriest** [comment]
I like the version 5, what do you think @Fermat-ORG/mordor-team ?

**Comment by lostwood** [comment]
I like the 6, but maybe in a circle, an the disc less shiny

**Comment by emmysm** [comment]
Me gusta mucho la versión 5 @arismendi227  
- Cuida que las cabezas y los cuerpos de los usuarios tengan la misma separación. 
- El  usuario del centro puede ser más grande y los dos muñequitos de los lados más pequeños pero del mismo tamaño ambos.
-  El botón de Play que sea plano.

**Comment by proseuz** [comment]
@arismendi227 también me gusta mucho la 5 con las sugerencias de @emmysm ¿qué opinas @arnaldos ?

**Comment by arismendi227** [comment]
@jhonmarquez92 @arnaldos @emmysm
modificados
![m8](https://cloud.githubusercontent.com/assets/19276382/15309724/25310fde-1bb3-11e6-8138-dbd12d8b51cf.png)
2
![m9](https://cloud.githubusercontent.com/assets/19276382/15309732/301a690e-1bb3-11e6-9691-237cc7207673.png)

**Comment by proseuz** [comment]
@arismendi227 considero que la última **versión 1** puede funcionar, peron conservando los personajes de acabados redondeados de la versión 2 para que exista coherencia total entre los elementos. @emmysm qué opinas?

**Comment by arismendi227** [comment]
@jhonmarquez92 @arnaldos @emmysm
![m9](https://cloud.githubusercontent.com/assets/19276382/15322001/e184ab6e-1c03-11e6-9f32-ccdfd1e8e774.png)

**Comment by darkestpriest** [comment]
Me gusta esta versión

**Comment by lostwood** [comment]
Se muy bien esta versión pienso que es la que deberia quedar

**Comment by arnaldos** [comment]
esta buena solo una acotación, el espesor de los bordes deben estar estandarizados con el icono principal de la app. en este caso los tipitos deben ser mas grandes ya que este icono va a reducirse y es posible que puedan perderse. @arismendi227 ajusta eso plz

**Comment by arismendi227** [comment]
@jhonmarquez92 @arnaldos @emmysm
modificación
![m10](https://cloud.githubusercontent.com/assets/19276382/15342899/877ffe8e-1c62-11e6-97bb-72cd82fe7e37.png)

**Comment by proseuz** [comment]
para mi está listo. @arnaldos

**Comment by arismendi227** [comment]
@jhonmarquez92 @arnaldos @emmysm 
corrección: los personajes mas grande para que no se pierdan en reducción y mas integración con los otros elementos. 
![f1](https://cloud.githubusercontent.com/assets/19276382/15557133/2d3de366-229b-11e6-8df3-0bcb05fd4e9e.png)

**Comment by proseuz** [comment]
@emmysm qué opinas Emmy?

**Comment by emmysm** [comment]
Por mi parte está listo @arismendi227 @jhonmarquez92

**Comment by proseuz** [comment]
subelo al repo!  @arismendi227

**Comment by darkestpriest** [comment]
Pendiente para que lo apliques @lostwood

**Comment by arismendi227** [comment]
@jhonmarquez92 @arnaldos @emmysm 
nuevas modificaciones 1,2,3,4 y 5

![1](https://cloud.githubusercontent.com/assets/19276382/15594101/40b9a45c-237c-11e6-8ff1-dd61dd3cec32.png)

![2](https://cloud.githubusercontent.com/assets/19276382/15594104/46f133ee-237c-11e6-9673-3e0528e12b3f.png)

![3](https://cloud.githubusercontent.com/assets/19276382/15594110/4c16778a-237c-11e6-98e9-ab3c8e13b784.png)

![4](https://cloud.githubusercontent.com/assets/19276382/15594113/54fe3158-237c-11e6-97dc-a43a1a4805a5.png)

![5](https://cloud.githubusercontent.com/assets/19276382/15594115/5bd397c0-237c-11e6-98a1-0b090717bc45.png)

**Comment by proseuz** [comment]
ponle a la segunda  el símbolo de play, los personajes secunadarios pueden ir un poco más grandes @arismendi227  @arnaldos

**Comment by arnaldos** [comment]
de este nueva serie la versión 2 que opinan @darkestpriest @emmysm @lostwood ?

**Comment by arismendi227** [comment]
@jhonmarquez92 @arnaldos @emmysm 
correcciones de la versión 2
![f1](https://cloud.githubusercontent.com/assets/19276382/15658135/94fa1bba-2682-11e6-8687-9082853f98e0.png)

**Comment by emmysm** [comment]
Opino lo mismo que @arnaldos, me gusta la 2da versión @jhonmarquez92 @darkestpriest @lostwood @arismendi227

**Comment by lostwood** [comment]
Si la version 2 me parece la indicada

**Comment by proseuz** [comment]
i liked

**Comment by arnaldos** [comment]
usemos esta versión provisional sin el play, pero creo debemos seguir trabajando en ello, realmente evaluando la perspectiva del los users referente a los audífonos se ven muy diferentes. Deja un solo aro de color.

**Comment by arismendi227** [comment]
@jhonmarquez92 @arnaldos @emmysm @darkestpriest @lostwood 
nuevas modificaciones 1,2,3 y 4 los personajes se ajustan a circulo y todo se maneja en una sola perspectiva {personajes y audífonos}
la 1 y 2 hay mas espacio entre los personajes  la 4 doble anillo 

![1](https://cloud.githubusercontent.com/assets/19276382/15782997/31506d48-2976-11e6-9b62-91c7a0f371c3.png)

![2](https://cloud.githubusercontent.com/assets/19276382/15783009/3928a1de-2976-11e6-8253-d00ff4efcdec.png)

![3](https://cloud.githubusercontent.com/assets/19276382/15783015/3fef574c-2976-11e6-9748-972faa43ae92.png)

![4](https://cloud.githubusercontent.com/assets/19276382/15783031/491b8d68-2976-11e6-9c40-3e87a1ed5210.png)

**Comment by emmysm** [comment]
@arismendi227 me voy por la versión tres de estas propuestas. Asegúrate que todos los elementos estén centrados, los usuarios de los lados no están alineados, al igual que la cabeza con el cuerpo del usuario del centro.

**Comment by proseuz** [comment]
Me inclino por la 3 también. qué opinas @arnaldos ?

**Comment by arnaldos** [comment]
propuesta 1

**Comment by arismendi227** [comment]
@jhonmarquez92 @arnaldos @emmysm
generando los recursos de la propuesta 1
