### ISSUE TITLE
DAP - Reference Wallet - Asset Redeem Point - Redeem Point Home - Android New GUI DAP

### ISSUE THREAD

**Issue by jinmyjbv** [bitDubai/fermat-graphic-design#777]
New UI for the Asset Redeem Point Wallet

@nindriago  Please assign this to me

**Comment by arnaldos** [comment]
@jinmyjbv @emmysm @ivonnesantos  this was resolved ?

**Comment by arnaldos** [comment]
@jinmyjbv @nindriago  plz what is this?  you talk about improved all redempoint? I don´t understand this issue
