### ISSUE TITLE
Welcome Wizzard Last Screen

### ISSUE THREAD

**Issue by furszy** [bitDubai/fermat-graphic-design#778]
We need to finish the wizzard. This is how the screen looks now:
![seleccion_138](https://cloud.githubusercontent.com/assets/5377650/14644388/487cacdc-0628-11e6-8dae-acc53f2112d6.png)

**Comment by furszy** [comment]
@arnaldos @emmysm @Luis-Fernando-Molina

**Comment by arnaldos** [comment]
perfecto !! ya mandamos propuestas para definir esto

**Comment by Luis-Fernando-Molina** [comment]
me parece que esto se puede mejorar.
1. los textos alineados a la izquierda.
2. la comunity tiene un banner en vez de un icono

@arnaldos trata de que los diseños sea realmente lo mejor que se puede hacer.

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina eso fue lo mejor que pude hacer en el xml no soy muy bueno trabajando con los xml @emmysm se va a encargar de hacer una propuesta visual para que @furszy nos ayude con eso

**Comment by furszy** [comment]
@arnaldos armemos el wireframe de esta pantalla, que se apruebe y yo armo la estructura como hicimos acá. Después todas las mejoras en el xml las podes armar vos tranquilamente.

**Comment by emmysm** [comment]
![pop up new-07](https://cloud.githubusercontent.com/assets/15143489/14654134/08adaaac-0646-11e6-813d-558d7c2d32d5.jpg)
![pop up new 2-07](https://cloud.githubusercontent.com/assets/15143489/14654481/b96f51e6-0647-11e6-9def-a52563caaf54.jpg)

![pop up new-05](https://cloud.githubusercontent.com/assets/15143489/14654449/862c76a6-0647-11e6-8947-8dd76f82c72c.jpg)

@arnaldos @Luis-Fernando-Molina @furszy

**Comment by Luis-Fernando-Molina** [comment]
la segunda version :+1: 

@franklinmarcano1970 que posibilidad hay de que pongamos a andar los actores de chat y comunidad de chat como para que esta pantalla de ayuda diga algo que realmente existe?

En cuantos dias a partir de ahora pudiera estar eso andando @franklinmarcano1970 ?

**Comment by franklinmarcano1970** [comment]
@Luis-Fernando-Molina La identidad esta funcional con diseno y todo, la community es la que estamos sacando ahora el BackEnd esta casi a un 70%,  pero estamos probandolo que se esta realizando, a nivel de android nos faltan algunos detalles de diseno y de funcionalidad, en 6 dias podemos tenerla funcional a nivel de diseno, para poder comenzar a probar a nivel de intengracion...

**Comment by furszy** [comment]
cierro este issue, welcome wizard completado e implementado.
