### ISSUE TITLE
 Create a brochure to sell Fermat Bounty Program similar in quality to the Dubai competition one.

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#779]
Here the issue #486 to the broshure of Dubai competition only reference
# Software Bounty Program

We are running a bounty program to complete the projected functionality as soon as possible. Currently bounties are not paid in cash, but in Fermat tokens. This is one of the ways we use to distribute ownership of the project with whoever adds value to it. 
## Sign-up - License Agreement - (READ FIRST)

Anyone who adds value to the Project in any form needs to sign up a Contribution License Agreement as the first step to become part of the project. To do that, please follow the steps described [here](https://github.com/bitDubai/contribution-program/tree/master/license-agreements/README.md) 

Now, after signing up,  you can follow the Bounty program procedure below.
## Software Release Life Cycle

A software release life cycle is the sum of the stages of development and maturity for a piece of computer software: ranging from its design and initial development to its eventual release, and including updated versions of the released version to help improve software or fix bugs still present in the software.

We adhere to the following definitions:
- [Architecture Design](https://en.wikipedia.org/wiki/Software_architecture)
- [Implementation](https://en.wikipedia.org/wiki/Software_release_life_cycle#Pre-alpha)
- [Alpha](https://en.wikipedia.org/wiki/Software_release_life_cycle#Alpha)
- [Beta](https://en.wikipedia.org/wiki/Software_release_life_cycle#Beta)
- [Release Candidate](https://en.wikipedia.org/wiki/Software_release_life_cycle#Release_candidatee)
- [Release](https://en.wikipedia.org/wiki/Software_release_life_cycle#Release)
## Procedure
1. Grab a Team and apply for one of the projects listed whose status reads as Not Assigned. You need to create an Issue in this REPO tagging the @bounty-program-team and attaching an agreement proposal based on this [template](https://github.com/Fermat-ORG/software-bounty-program/blob/master/Agreement.md).
2. Someone on this team will evaluate your skills and proposal and may or may not assign the project to your team. In any case a complete explanation of the reasons why they do or don't assign it will be given to you. Everything will happen in the discussion on the issue created.
3. If the project is finally assigned to your team, the @bounty-program-team will add the final agreement to the bounty folder in this repo and write your name in the table.
4. The same agreement document will be updated once the bounty is won with a distribution table where all beneficiaries will be listed together with the percentage that they will receive.
## Rules
1. The @bounty-program-team will evaluate the project completion according to the bounty agreement added to the bounty folder.
2. The distribution of the bounty between the team members is free. It is up to the team to decide how to distribute the bounty between them or other people from other teams that helped.
3. Team leaders can make agreements for tokens of the possible bounty with other team leaders to help them with the project. In fact this is expected to happend with graphic designers, UX designers, copywriters and others, in order to secure their commitment to the project for certain dates.
4. Reaching production phase means passing all controls, checks and approvals that might be in place by the time the code is implemented. Those approval procedures might or might not be in place at present time.
5. The conditions of bounties that are not yet _Assigned_ might be changed at anytime by the @bounty-program-team. Once assigned, the conditions will stay fixed.
6. If the @bounty-program-team sees a lack of commitment of a team with the project assigned or a the progress is too slow, it might cancel the assigment and return the project to the pool of _Not Assigned_ bounties.
7. For implementation projects, at a DEMO-DAY the team showcases the functionality that has developed. Previously a project manager will check the deliverables to see if they comply with the acceptance guidelines stated at the bounty agreement.
8. The payment of the bounty will be done when the project is released to general public (production). The amount of Tokens to receive will be calculated at the Tokens price at the date the project is released to the public.

**Comment by adryx83** [comment]
@arnaldos aca la propuesta, siento que es mucho texto se que hay que resumir, nose si me puedas ayudar a ver que se puede colocar para que no se vea tan recargado.

![broshure bounty program](https://cloud.githubusercontent.com/assets/17273349/14652614/dff0fdb4-063e-11e6-9b10-153f35241021.jpg)

**Comment by gustl-arg** [comment]
@arnaldos unfortunately it is not clear for me where and how this brochure will be used!
To sell the bounty program, this is definitely NOT  the appropiated text.
To set the rules for the program, it is the right text, but I do not understand the need to put it on a single image....
please refer to the person that originated this issue for more details!

**Comment by gustl-arg** [comment]
@arnaldos Attention! the text mentions many times "here" meaning the repository, and in this image it is not clear if this applies! Becasue, HERE means, the place where the image will be placed! ( unclear for me from reading this issue)

**Comment by Luis-Fernando-Molina** [comment]
Text must be provided by @katherine because she will use the brochure first on a meet up

**Comment by Luis-Fernando-Molina** [comment]
@Arnaldos that is not the last version of the logo

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina no, is not last version, i´m making it now. when i finish it I give it to @adryx83  to place it in the broshure

**Comment by adryx83** [comment]
@arnaldos el broshure con el texto sugerido...

![broshure bounty program2](https://cloud.githubusercontent.com/assets/17273349/14895982/4a71aea6-0d45-11e6-8461-ead9ba2b2378.jpg)

**Comment by Joseangel2v** [comment]
Propuesta 1
![d1-01](https://cloud.githubusercontent.com/assets/17457499/15048035/6c27436e-12b1-11e6-8d6a-b13fbabbf36a.png)

**Comment by emmysm** [comment]
More proposal @Joseangel2v. I think the colors should change. Colors that create contrast with the logo.

**Comment by arnaldos** [comment]
make this brochure like this #486

**Comment by Joseangel2v** [comment]
![flyers fermat](https://cloud.githubusercontent.com/assets/17457499/15086390/4ca085ce-13aa-11e6-9049-75e45e0454fb.png)

**Comment by Joseangel2v** [comment]
![flyers 3](https://cloud.githubusercontent.com/assets/17457499/15086954/7cf8d2f4-13ae-11e6-9b7a-b6bded065cc4.png)

**Comment by arnaldos** [comment]
@Joseangel2v I like this the second proporsal .. @Luis-Fernando-Molina what do you think about ??

**Comment by emmysm** [comment]
I like  :smiley:  @Joseangel2v

**Comment by Kate99** [comment]
The second one looks good!

**Comment by arnaldos** [comment]
@Joseangel2v plz uploads the files of the second proposal to the repository and give me the link to download the files to send to production
