### ISSUE TITLE
Help views for Loss Protected Wallet

### ISSUE THREAD

**Issue by m471c4** [bitDubai/fermat-graphic-design#781]
We need to design the help dialogs for the Loss Protected Wallet. This includes welcome dialog, default identity selector dialog and "add new contact" help dialog.

**Comment by m471c4** [comment]
@nattyco this are the help dialogs I designed for this wallet:

Welcome dialog:
![help_welcome](https://cloud.githubusercontent.com/assets/13468350/14667017/9de63390-06a6-11e6-9369-be87e74141fd.png)

Default Identity selector dialog:
![help_identity](https://cloud.githubusercontent.com/assets/13468350/14667019/a33bae60-06a6-11e6-8172-d95c63f1ed3d.png)

Add new contact help dialog:
![help_addcontact](https://cloud.githubusercontent.com/assets/13468350/14667025/a8a10076-06a6-11e6-93bd-5973d5bfe31b.png)

@arnaldos I used the Loss Protected color palette, could you please confirm me if this is correct? Also, I'm not sure if I can change the Caviar Dreams font in the title.

**Comment by arnaldos** [comment]
@m471c4 I think this is fine as you make the design of this app colors are good. typography I have been working with Helvetica neue test this and see it

**Comment by nattyco** [comment]
@m471c4 I like the combination of colors is this good for me

**Comment by Exilum** [comment]
Yeep it is quite good guys ! I actually like the combination of colors way more than the original wallet ! XD

**Comment by m471c4** [comment]
@Exilum @nattyco @arnaldos excellent! I also changed the fermat and external user icon, so it matches the color palette. This are the final views:

![help_views](https://cloud.githubusercontent.com/assets/13468350/14735759/c00c7b0e-083c-11e6-83ad-56ffe4fcdbd5.png)

**Comment by arnaldos** [comment]
@m471c4 this icons are fine !!

**Comment by arnaldos** [comment]
@m471c4 @nattyco  this is ready ?
