### ISSUE TITLE
Profiles Picker Improvement

### ISSUE THREAD

**Issue by furszy** [bitDubai/fermat-graphic-design#783]
La propuesta de @arnaldos para esta pantalla.
Deberia ir sin los dos radio buttons de abajo, que se pueda deslizar hacia abajo me parece mejor.
![imgpsh_fullsize](https://cloud.githubusercontent.com/assets/5377650/14698458/6729abb0-0765-11e6-927f-377cc0d37175.jpg)

**Comment by furszy** [comment]
@Luis-Fernando-Molina

**Comment by arnaldos** [comment]
Esta es una propuesta inicial, @emmysm esta encargada de generar otras propuestas.

**Comment by emmysm** [comment]
![mockup](https://cloud.githubusercontent.com/assets/15143489/14765526/6476eea4-09af-11e6-8af1-e14c68313702.png)

@Luis-Fernando-Molina

**Comment by Luis-Fernando-Molina** [comment]
Vamos a hacer lo siguiente:
1. La pantalla no se llama identity sino Profiles.
2. Te debe mostrar los profiles que ya tenes creados de manera similar al nuevo HELP que hicimos. 
3. Debajo de la fotito el alias que se uso y debajo del alias el tipo de profile. EJ Luis Molina / Chat Profile
4. Al final de la lista de profiles existentes debe comenzar una lista de iconos para agregar un nuevo tipo de perfil de cada tipo.
5. Tocando en un profile existente entras a la sub app que lo maneja en modo de edicion.
6. Tocando en el icono de un profile nuevo para un tipo en particular entras a la sub app que lo maneja en modo agregar un profile. 
7. Solo deben aparecer los profiles del tipo que la persona tiene habilitado de acuerdo al filtro (beta, release, alpha) y posteriormente de acuerdo a las aplicaciones que tiene instalada (cuando este el app store).

Vamos a inicialmente pintar las pantallas que acabo de describir.

**Comment by emmysm** [comment]
![create-profile](https://cloud.githubusercontent.com/assets/15143489/14774408/b1c45b4e-0a7f-11e6-8adf-214e31a00107.jpg)

@Luis-Fernando-Molina @arnaldos @furszy

**Comment by Luis-Fernando-Molina** [comment]
Puede ser.

En el label que dice "add or edit profile" debiera decir solamente "create a new profile:"

**Comment by Luis-Fernando-Molina** [comment]
el resto puede andar. 

@furszy hagamos la modificacion sin entrar a modificar las app de identity por ahora, solo la parte de afuera.

**Comment by emmysm** [comment]
Propuesta 1
![add_edit_profile1](https://cloud.githubusercontent.com/assets/15143489/14774734/f072e024-0a82-11e6-9436-6293e4b7dce4.jpg)

Propuesta 2
![add_edit_profile](https://cloud.githubusercontent.com/assets/15143489/14774735/f075dc5c-0a82-11e6-9ddd-323b847fec3f.jpg)

@Luis-Fernando-Molina

**Comment by Luis-Fernando-Molina** [comment]
propuesta 1

**Comment by arnaldos** [comment]
@emmysm de la propuesta elegida solo una acotación las flechas que te permiten cambiar las identidades  bájalas a nivel del texto (nombre del usuario), porque donde están actualmente, están muy al borde y puede ser algo incomodo al momento de pisar el boton.

**Comment by arnaldos** [comment]
@emmysm en "create a new profile:" dale mayor protagonismo (aumentar el tamaño pudiese ser) . se ve escondido y no se entiende como titulo de las distintas identidades que se pueden crear según la plataforma. el texto puede funcionar mejor centrado

**Comment by arnaldos** [comment]
@emmysm como quedo esto ??

**Comment by emmysm** [comment]
@arnaldos acá hay que subir propuestas con los nuevos colores, cierto?

**Comment by arnaldos** [comment]
@emmysm si es aqui!

**Comment by emmysm** [comment]
![profile-01](https://cloud.githubusercontent.com/assets/15143489/15265891/3aa5f004-195c-11e6-8c37-adc0e1b65a66.png)

@arnaldos @Luis-Fernando-Molina @furszy

**Comment by arnaldos** [comment]
@emmysm preséntalo usando los otros tonos también, para evaluar como se ve una versión con cada color.

**Comment by emmysm** [comment]
Perfecto, @arnaldos
