### ISSUE TITLE
Create a new divider/separator content for the web

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#784]
I show reference image

![referencia](https://cloud.githubusercontent.com/assets/13594347/14722344/efa5a43e-07d4-11e6-97d9-f17693b0e0e3.jpg)

Currently is using the logo must improve that. Here the link to the web http://fermat.org/

**Comment by isahq23** [comment]
@arnaldos 
This is what I think would work in this case. This parts of the website are TITLES AND SUBTITLES.
They emphasize each part of the information, we have: Fermat is the new internet, the fermat system is a P2P network, fermat is a digital money platform, The Fermat Movement Is a Global Community, videos and team. 
They are all titles of sections, they should be accompanied with icons of something related to each subject. Also that's why I didn't used any shadow (a lot of banners and images already have those)

![fermat_divider_issues784_m1](https://cloud.githubusercontent.com/assets/15214774/14724028/b55c25ba-07dd-11e6-82ef-1e443c0aac21.jpg)

**Comment by adryx83** [comment]
@arnaldos Here is my proposal of the web divider

![web divider fermat](https://cloud.githubusercontent.com/assets/17273349/14763037/c7906f26-0953-11e6-97e4-bd8e1fab6e78.jpg)

![web divider fermat2](https://cloud.githubusercontent.com/assets/17273349/14763038/c9764004-0953-11e6-984b-a3c4c30f39df.jpg)

**Comment by arnaldos** [comment]
@isahq23 @isahq23 not necessarily must replace the logo with an icon we can work another proposal that allows us to separate content from another can be an element, a pattern. @Luis-Fernando-Molina  what do you think about it ?

**Comment by Luis-Fernando-Molina** [comment]
What we need is a separator from one secccion to the other of the web site, not an icon.

**Comment by isahq23** [comment]
@Luis-Fernando-Molina the icon works to emphasize the section, to guide the user into "where is he and what is he reading"

**Comment by arnaldos** [comment]
@adryx83 @isahq23 @jayborges @jhonmarquez92 @Carelsy @Joseangel2v  plz we need resolve this right now.

**Comment by arnaldos** [comment]
more proposal plz

**Comment by m471c4** [comment]
@arnaldos @Luis-Fernando-Molina 

![divider1](https://cloud.githubusercontent.com/assets/13468350/14804153/8a7e68f8-0b2a-11e6-85b9-336d7cad1ce5.png)

**Comment by isahq23** [comment]
Texture + Colored Line
![fermat_divider_issues784_m2](https://cloud.githubusercontent.com/assets/15214774/14804470/8146352e-0b2d-11e6-89b5-3220f2850a1f.jpg)

![fermat_divider_issues784_m3](https://cloud.githubusercontent.com/assets/15214774/14804472/886ae944-0b2d-11e6-9e0e-09a2ba69c9df.jpg)

**Comment by Joseangel2v** [comment]
![1](https://cloud.githubusercontent.com/assets/17457499/14804789/226fec04-0b30-11e6-9151-bb61377b7b0d.png)

**Comment by Joseangel2v** [comment]
![2](https://cloud.githubusercontent.com/assets/17457499/14804797/419668c4-0b30-11e6-9aad-50272a5c364e.png)

**Comment by Carelsy** [comment]
@arnaldos @emmysm @Luis-Fernando-Molina
This is my proposal, the idea is to give importance to the text and logo often appears on the website and I think it should not be within the separator. ![propuesta-1](https://cloud.githubusercontent.com/assets/17755307/14804841/6a7f733e-0b30-11e6-9593-cad4fee6c48b.png)

**Comment by ivonnesantos** [comment]
N1
![separator-04](https://cloud.githubusercontent.com/assets/15238660/14806642/96162304-0b3e-11e6-8f44-3956aec216a8.jpg)

N2
![separator-05](https://cloud.githubusercontent.com/assets/15238660/14806644/9fbbccba-0b3e-11e6-88bc-0778ab980e62.jpg)

N3
![separator-06](https://cloud.githubusercontent.com/assets/15238660/14806648/a77ced58-0b3e-11e6-9633-4857c6ca59d8.jpg)

@Luis-Fernando-Molina

**Comment by proseuz** [comment]
@arnaldos @Luis-Fernando-Molina 
Proposal 1
basing on the new logo fermat 
I realize this bar is composed of pieces
![new divider-separator content for the web1-01](https://cloud.githubusercontent.com/assets/17308060/14807547/45653c70-0b47-11e6-855e-712dae998689.png)
Proposal 2
This minimalist , elegant and functional bar
the bar may be changing color (fermat colors) according to information containing 
![new divider-separator content for the web-012](https://cloud.githubusercontent.com/assets/17308060/14807548/45ba6baa-0b47-11e6-84eb-d562ce7153a0.png)

**Comment by Joseangel2v** [comment]
@arnaldos @Luis-Fernando-Molina 
![fermat1](https://cloud.githubusercontent.com/assets/17457499/14827250/4986d23c-0bab-11e6-8fa7-d525a238ea39.png)

**Comment by Joseangel2v** [comment]
![fermat 2](https://cloud.githubusercontent.com/assets/17457499/14827281/67fab7e2-0bab-11e6-84d6-b0f3815d660b.png)

**Comment by Joseangel2v** [comment]
![fermat 3](https://cloud.githubusercontent.com/assets/17457499/14827321/9475a9b2-0bab-11e6-89a5-39c8da99ac5a.png)

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina plz take a view when you have time, i like the version N3 paterm, maybe with other colors. what do you think about that ?

**Comment by Luis-Fernando-Molina** [comment]
A ver si nos entendemos. No se pidio que se rediseñe esa pantalla, si se cambie las letras ni el estilo de lo que hay.

Solo un separador que vaya de punta a punta en el espacio que hoy la pagina tiene en blanco entre cada parte de la misma (en general arriba del logo)

Deberia haber una separador por seccion que diria:
1. Welcome everybody
2. Welcome developers
3. Welcome bitcoiners
4. Welcome to the Fermat community
5. Separador solo sin frase 
6. idem
   7.idem

**Comment by ivonnesantos** [comment]
N1
![separator-01](https://cloud.githubusercontent.com/assets/15238660/14906576/a3bb980a-0d86-11e6-9978-28950e28a00f.png)

N2
![separator-02](https://cloud.githubusercontent.com/assets/15238660/14906579/a9eff37e-0d86-11e6-9126-d7823be9919e.png)

N3
![separator-03](https://cloud.githubusercontent.com/assets/15238660/14906584/b4761e86-0d86-11e6-878f-c0953894da18.png)

@Luis-Fernando-Molina @arnaldos

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina plz give me some feedback about ..
