### ISSUE TITLE
Create a banner for Fan Wallet Identity Art App

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#785]

**Comment by proseuz** [comment]
My proposal @arnaldos @emmysm 
1
![banner fan wallet-01-01-01](https://cloud.githubusercontent.com/assets/17308060/14759459/fc892ee0-08ed-11e6-952c-ba54588ad132.png)
2
![banner fan wallet-01-01-01-01](https://cloud.githubusercontent.com/assets/17308060/14759460/fca0e7a6-08ed-11e6-801f-d0a3a8208d3f.png)
3
![banner fan wallet-01-01-01-01-01](https://cloud.githubusercontent.com/assets/17308060/14759461/fcb3addc-08ed-11e6-92ff-2ddcef26fa7e.png)
4
![banner fan wallet-01-01](https://cloud.githubusercontent.com/assets/17308060/14759462/fccd4c1a-08ed-11e6-8df5-b96aa14db851.png)

**Comment by arnaldos** [comment]
@jhonmarquez92  la version 1 y la 4 coloca una para artist y otra para la fan.  que opinas @darkestpriest  ?

**Comment by darkestpriest** [comment]
A mi me gusta más la 3 ¿que opinan @GaboHub y @lostwood ?

**Comment by lostwood** [comment]
Si la 3 tambien, si pudieran presentarla en otra comvinacion de colores

**Comment by arnaldos** [comment]
@jhonmarquez92 deja la 3 para identity artist y la 4 para identity fan

**Comment by lostwood** [comment]
estos son los diseños muchachos  @macuare @alexanderejm

**Comment by arnaldos** [comment]
avísenme cuando los apliquen para cerrar los casos!

**Comment by arnaldos** [comment]
@darkestpriest @lostwood esta listo esto ?

**Comment by lostwood** [comment]
Si ya esta listo

**Comment by arnaldos** [comment]
perfecto!!
