### ISSUE TITLE
Create a banner for Fan Wallet Identity Fan App

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#786]

**Comment by proseuz** [comment]
@arnaldos  está fue la seleccionada para la fan identity 
![banner fanidentty wallet-01](https://cloud.githubusercontent.com/assets/17308060/14809209/476271c4-0b55-11e6-8449-e9211a69fdcf.png)

**Comment by arnaldos** [comment]
@lostwood @darkestpriest este esta listo ??

**Comment by lostwood** [comment]
Si listo

**Comment by arnaldos** [comment]
perfecto !!!
