### ISSUE TITLE
Create a ART_Artist identity UI/UX-App Design

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#787]
Actual View

![art_artist identity](https://cloud.githubusercontent.com/assets/13594347/14787825/007e7acc-0acf-11e6-9b87-7d1992092b0d.png)

**Comment by arnaldos** [comment]
@darkestpriest

**Comment by m471c4** [comment]
@arnaldos @darkestpriest first versions for Artist Identity. I think version 3 is better, there are better contrast and the rounded picture enhances the design:

Versión 1:
![identity1](https://cloud.githubusercontent.com/assets/13468350/14802604/14c2da94-0b1c-11e6-8ec6-1f1c7c05435a.png)

Versión 2:
![identity2](https://cloud.githubusercontent.com/assets/13468350/14802606/14d665e6-0b1c-11e6-8fc5-75e4bc9536aa.png)

Versión 3:
![identity3](https://cloud.githubusercontent.com/assets/13468350/14802605/14d098be-0b1c-11e6-972f-4bffb7f7e556.png)

Versión 4:
![identity4](https://cloud.githubusercontent.com/assets/13468350/14802607/14de9cca-0b1c-11e6-8a7b-e5d2867e70c8.png)

Versión 5:
![identity5](https://cloud.githubusercontent.com/assets/13468350/14802608/14ecc930-0b1c-11e6-9501-97810b863d87.png)

**Comment by darkestpriest** [comment]
Great work @m471c4 I like the version 3, what do you think @Fermat-ORG/mordor-team

**Comment by lostwood** [comment]
I like version 2

**Comment by darkestpriest** [comment]
Too white @lostwood, I like the version 3 contrast

**Comment by lostwood** [comment]
You are right, the version 3,  i would like to see the background with another colors examples

**Comment by GaboHub** [comment]
I like version 3, but I don't think that we should use so many colors in one screen, at least where it says "Artist Identity"

**Comment by m471c4** [comment]
@GaboHub I'm using only 2 colors (light blue and yellow), with a gradation, that's why it generates a green shade in the middle, but I can try a few monocolor versions and shortening the color spectre.

**Comment by m471c4** [comment]
@darkestpriest @lostwood @GaboHub @arnaldos two versions with the last suggestions you guys made, and two missing fields:

Versión 1:
![identity6](https://cloud.githubusercontent.com/assets/13468350/14837709/9959180e-0be4-11e6-9b65-eca8787d268e.png)

Versión 2:
![identity7](https://cloud.githubusercontent.com/assets/13468350/14837710/99e67730-0be4-11e6-9406-24aa30655637.png)

**Comment by darkestpriest** [comment]
I like version 1, the **darkest** one.

**Comment by arnaldos** [comment]
@m471c4 two things the save changes button to green color. the headset making a frame in the photo do not think it ideal plz try another element if you want to place something similar. I leave them alone with photo

**Comment by m471c4** [comment]
@darkestpriest @lostwood @GaboHub @arnaldos with your suggestions:

![identity8](https://cloud.githubusercontent.com/assets/13468350/14907246/984adb58-0d8f-11e6-986a-82d259304ad8.png)

**Comment by darkestpriest** [comment]
I like it!

**Comment by GaboHub** [comment]
I like the last one.

**Comment by lostwood** [comment]
Creo que hay Cuorum, de verdad excelente el color y el diseño

**Comment by m471c4** [comment]
Thank you guys! I'm glad you liked it. I'm working on the Community with the very same design standars, so it will look similar. Tomorrow I'll be posting the first versions.

**Comment by lostwood** [comment]
ok perfect what do you think @macuare @alexanderejm

**Comment by arnaldos** [comment]
@m471c4 excellent very good job !

**Comment by arnaldos** [comment]
just one thing the text of the action bar and the button could be lost with the background colors, checks that!

**Comment by juanaso** [comment]
i think its perfect.

**Comment by arnaldos** [comment]
this is implemented @lostwood ?

**Comment by lostwood** [comment]
It is almost done

**Comment by arnaldos** [comment]
nice !! so i close it
