### ISSUE TITLE
Create a ART_Artist Community UI/UX-App Design

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#788]
Actual View

![art_artist_community](https://cloud.githubusercontent.com/assets/13594347/14787882/33b8d2ac-0acf-11e6-9d09-0c88a0648940.png)

**Comment by arnaldos** [comment]
@darkestpriest

**Comment by m471c4** [comment]
@darkestpriest @arnaldos @Fermat-ORG/mordor-team here's the first version for the Artist Community. I tried to maintain the look and feeling of the same Identity (#787).

![community](https://cloud.githubusercontent.com/assets/13468350/15171104/d37ccf40-1719-11e6-801b-f481295a9e39.png)

**Comment by darkestpriest** [comment]
Cool! I like it!! Opinions? @Fermat-ORG/mordor-team

**Comment by lostwood** [comment]
I like it too, are you assign to design the artist identity icon?

**Comment by m471c4** [comment]
@lostwood no, I'm not assigned. Do you know if there's an issue for that?

**Comment by m471c4** [comment]
@darkestpriest @arnaldos @Fermat-ORG/mordor-team I missed the nav drawer in the last post. Here's the final version: 

![communitynew](https://cloud.githubusercontent.com/assets/13468350/15190902/4d6839c8-1780-11e6-9c0c-99f4283caa02.png)

**Comment by lostwood** [comment]
No, just asking

**Comment by lostwood** [comment]
Great a think it is ready, excellent work

**Comment by arnaldos** [comment]
nice job !!!!

**Comment by m471c4** [comment]
@darkestpriest @lostwood @arnaldos great! I'll generate the document and resources today :)

**Comment by lostwood** [comment]
perfect thank you

**Comment by arnaldos** [comment]
this is implemented @lostwood ?

**Comment by lostwood** [comment]
It is on the way to be implement

**Comment by arnaldos** [comment]
ok perfect!!
