### ISSUE TITLE
Create a ART_Fan identity UI/UX-App Design

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#789]
Actual View

![art_fan identity](https://cloud.githubusercontent.com/assets/13594347/14787914/60d6e2ce-0acf-11e6-9c9c-075e0678267a.png)

**Comment by arnaldos** [comment]
@darkestpriest

**Comment by isahq23** [comment]
@arnaldos @lostwood @darkestpriest 

![fan_identity_m1](https://cloud.githubusercontent.com/assets/15214774/15167137/217ffa02-16f0-11e6-9828-1c2f3227568f.jpg)

**Comment by isahq23** [comment]
@arnaldos recursos y archivos actualizados en el repo

fermat app / sub apps / identities / fan identity

**Comment by arnaldos** [comment]
perfect !!

**Comment by GaboHub** [comment]
I don't know if this is the final design but I would rather use a darker background, I've seen this design in the app and It's not user friendly to see.

@darkestpriest

**Comment by isahq23** [comment]
@GaboHub I made a dark version in the music player app (the principal), but, like we've been working with ligther versions they choose this one. I prefer the dark one too, but I think both works.

**Comment by arnaldos** [comment]
@darkestpriest how will progress this ?
