### ISSUE TITLE
Create a ART_Fan Community UI/UX-App Design

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#790]
Actual view

![art_fan_community](https://cloud.githubusercontent.com/assets/13594347/14787946/a02d3d6a-0acf-11e6-9ba5-39ec3f6496c0.png)

**Comment by arnaldos** [comment]
@darkestpriest

**Comment by isahq23** [comment]
@arnaldos @darkestpriest 
Still working on it

![fan_community_m1](https://cloud.githubusercontent.com/assets/15214774/15133158/41afecf4-162a-11e6-858c-74ea655ce1c5.jpg)

**Comment by isahq23** [comment]
@arnaldos @darkestpriest 
READY!

![fan_community_m2](https://cloud.githubusercontent.com/assets/15214774/15161714/009adf7c-16c9-11e6-9b58-8fa6971d1214.jpg)

**Comment by lostwood** [comment]
Excelente isa vamos a ver que opinan los muchachos @juanaso  @alexanderejm  @gaboslack  @macuare

**Comment by darkestpriest** [comment]
@lostwood si vas a invocar a Gabriel debes usar @GaboHub

**Comment by lostwood** [comment]
Cierto

**Comment by isahq23** [comment]
@arnaldos estoy actualizando el repo con los recursos e indicaciones de este issue, puedes cerrarlo

dirección: fermat-app / subapps / communities / fan community

**Comment by arnaldos** [comment]
@isahq23 gracias !!   @lostwood avísame cuando este implementado para cerrar el caso.
