### ISSUE TITLE
Create a ART_Music Player UI/UX-App Design

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#791]
Actual View

![art_music player](https://cloud.githubusercontent.com/assets/13594347/14787981/c9fb1e0a-0acf-11e6-8bfa-a8c04fb54b80.png)

**Comment by arnaldos** [comment]
@darkestpriest

**Comment by isahq23** [comment]
@arnaldos first part: playing song

![mp_app_1_playingsong](https://cloud.githubusercontent.com/assets/15214774/14873013/a7255e20-0cbb-11e6-9727-81c81b706293.jpg)

**Comment by arnaldos** [comment]
@isahq23 I like this. just one thing use the palet color have the logo/icon of this app. maybe in the elements buttoms or somethings that. just for make a link with the logo/icon. i'm waiting for the others views. :smile:

**Comment by isahq23** [comment]
@arnaldos check out!

![mp_app_aaps](https://cloud.githubusercontent.com/assets/15214774/14898467/b0b1ab20-0d50-11e6-8193-d07d75183cea.jpg)

**Comment by arnaldos** [comment]
@isahq23 I like it. but put in the action bar a color transparent  maybe black and the icons in white. so we avoid that if there is a picture in black background merge the icons buttoms with the image.

**Comment by arnaldos** [comment]
I prefer the version 1 is more fresh and youthful. @darkestpriest what do you think abiut that ?

**Comment by darkestpriest** [comment]
@arnaldos @isahq23 I like the _darkest one_, as always, what do you think @Fermat-ORG/mordor-team ?

**Comment by isahq23** [comment]
I'll keep designing in both styles then. All while you decide which one works best.

**Comment by isahq23** [comment]
Here we go.

New section: My Music
![mp_app_mm](https://cloud.githubusercontent.com/assets/15214774/14924349/da21565c-0e0b-11e6-90e9-0619c77e5d16.jpg)

New options in first proposal:
![mp_app_aaps](https://cloud.githubusercontent.com/assets/15214774/14924357/e5ef4ffc-0e0b-11e6-88fd-71cc4cd6eec7.jpg)

**Comment by isahq23** [comment]
My Music + Playlists

![mp_app_m p](https://cloud.githubusercontent.com/assets/15214774/14927018/336ab106-0e19-11e6-886d-b1a998e79736.jpg)

**Comment by darkestpriest** [comment]
I like the last one version, what do you think @Fermat-ORG/mordor-team ?

**Comment by isahq23** [comment]
Menu + Profile

![mp_app_menu profile](https://cloud.githubusercontent.com/assets/15214774/14969728/b30b9d96-108d-11e6-8397-8c0d5646bfef.jpg)

**Comment by lostwood** [comment]
I like the light design in both case, but for this version the music player is going to be basic in the functionality, because the due time

**Comment by isahq23** [comment]
@lostwood what do you mean with basic functionality? 
Which are those basic functions that I should focus on?
Please, name them.

**Comment by isahq23** [comment]
Entries + Filter by Entry 2

![mp_app_entries](https://cloud.githubusercontent.com/assets/15214774/14972894/186ba27c-10ab-11e6-897f-ae19b23ded61.jpg)

**Comment by lostwood** [comment]
Of course, the music player just has the buttons play, back and forward, and a list of song with and image, artist name and song name,in a next version playslist, repeat and those stuffs will be present, you can see the first imagen posted here

**Comment by isahq23** [comment]
@lostwood ok, so it won't have interactions like Spotify or Deezer, but still the user can find music inside of it. Perfect, that means the entry for the app will be "entry 1" Thank you!

**Comment by isahq23** [comment]
@arnaldos ya envié todo y estoy actualizando el repo, puedes cerrar el caso

**Comment by lostwood** [comment]
That's right thanks excellent work

**Comment by arnaldos** [comment]
done !! thanks isa
