### ISSUE TITLE
Create a TKY_Artist Identity UI/UX-App Design

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#792]
Actual View

![tky_artist identity](https://cloud.githubusercontent.com/assets/13594347/14788054/0c6af6a2-0ad0-11e6-9926-942254397a18.png)

**Comment by arnaldos** [comment]
@darkestpriest  @emmysm  @jhonmarquez92

**Comment by proseuz** [comment]
@arnaldos @emmysm @darkestpriest @Luis-Fernando-Molina 
Proposal 1
![identity artist-06](https://cloud.githubusercontent.com/assets/17308060/14844161/5bcf6692-0c1f-11e6-9c15-e43fd9afa04e.png)
Proposal 2
![identity artist-01](https://cloud.githubusercontent.com/assets/17308060/14844162/5be382f8-0c1f-11e6-9c15-d9995ebd62a2.png)
Proposal 3
![identity artist-02](https://cloud.githubusercontent.com/assets/17308060/14844163/5bee8482-0c1f-11e6-94a4-f6ac5c775653.png)
Proposal 4
![identity artist-03](https://cloud.githubusercontent.com/assets/17308060/14844166/5f0f0b00-0c1f-11e6-9dc2-b2a8cc026e00.png)
Proposal 5
![identity artist-04](https://cloud.githubusercontent.com/assets/17308060/14844165/5f03328a-0c1f-11e6-82d7-3901d0d37c34.png)
Proposal 6
![identity artist-05](https://cloud.githubusercontent.com/assets/17308060/14844164/5ef42b5a-0c1f-11e6-93e2-5eeb120f4761.png)

**Comment by emmysm** [comment]
Woow. Me gustan, me gustan las propuestas 4 y 5. Qué opinan chicos, @darkestpriest @arnaldos @lostwood @GaboHub ?

**Comment by emmysm** [comment]
Centra los box, @jhonmarquez92 veo que están más a la derecha que a la izquierda @jhonmarquez92

**Comment by darkestpriest** [comment]
Gran trabajo, para mi, la propuesta 2 ¿que opinan ustedes @Fermat-ORG/mordor-team ?

**Comment by lostwood** [comment]
Si esos serian los colores definitivos escojo la 2, sino me inclinaria mas al diseño de la 5

**Comment by arnaldos** [comment]
@emmysm @jhonmarquez92 

Definitivamente la 3

1-La versión 2 con el blanco brilla mucho lo que hace que sea algo molesto al ojo del usuario.
2-El selector de imagen de la 3 es consistente desde el momento en que esta el espacio vacio y cuando ya tiene la imagen del usuario. cosa que solo se mantiene también en la 2 menos en el resto. el resto cambia de un formato cuadrado a formato circular eso no esta bueno. **En el selector de imagen cambia el icono de la estrella por un tipito pero manten los colores**
3-A nivel cromático tiene mejor equilibrio.
4-La versión 5 también esta buena pero solo manteniendo el formato cuadrado plantea como se vera el espacio vació.

**Comment by proseuz** [comment]
ya genero los cambios

**Comment by proseuz** [comment]
@arnaldos @lostwood @darkestpriest @emmysm 
Propuesta 1
![identity artist 2da ronda-01](https://cloud.githubusercontent.com/assets/17308060/14903525/78f2002a-0d6b-11e6-87d0-31d366f88314.png)
Propuesta 2
![identity artist 2da ronda-02](https://cloud.githubusercontent.com/assets/17308060/14903536/8d09b8d2-0d6b-11e6-9187-3be53f028781.png)
Propuesta 3
![identity artist 2da ronda-03](https://cloud.githubusercontent.com/assets/17308060/14903537/8d1b53b2-0d6b-11e6-844e-4733127e994e.png)
Propuesta 4
![identity artist 2da ronda-04](https://cloud.githubusercontent.com/assets/17308060/14903538/8d2d493c-0d6b-11e6-8053-3204f9d43ff4.png)

**Comment by darkestpriest** [comment]
Para mi, la propuesta 1 ¿que opinan @GaboHub @lostwood ?

**Comment by GaboHub** [comment]
No me gustan mucho esos colores, pienso que brillan mucho y dificil de leer.

**Comment by lostwood** [comment]
Si pienso que la 1, y como he dicho en otros diseño de la parte de colores como comenta @GaboHub , pienso que una vez aprobado el diseño, deberia hacerse otra propuesta con colores alternativos

**Comment by emmysm** [comment]
@lostwood @GaboHub los colores no deberían verse tan brillantes en la pantalla del celular :smile:

**Comment by proseuz** [comment]
haré otras propuestas de combinación de colores. entonces la 1 esta bien? @emmysm @lostwood @GaboHub @darkestpriest @arnaldos

**Comment by emmysm** [comment]
Me gusta la propuesta 1, pero no me convence mucho los botones para editar la foto ahí @jhonmarquez92

**Comment by lostwood** [comment]
pueden comentar muchachos @macuare @alexanderejm

**Comment by darkestpriest** [comment]
Concuerdo con @emmysm la versión 1 sin el icono de editar en la foto.

**Comment by proseuz** [comment]
@arnaldos @darkestpriest @lostwood @emmysm  
versión 1
![identity artist 3ra ronda-02](https://cloud.githubusercontent.com/assets/17308060/14921299/5e3d9b82-0dfb-11e6-8b34-7aef0064637c.png)
versión 2
![identity artist 3ra ronda-01](https://cloud.githubusercontent.com/assets/17308060/14921300/5e5584cc-0dfb-11e6-859b-982110470588.png)

**Comment by lostwood** [comment]
A mi me gusta la version 1 @jhonmarquez92. Excelente

**Comment by darkestpriest** [comment]
Versión 1, gran trabajo @jhonmarquez92

**Comment by arnaldos** [comment]
@jhonmarquez92 para que realces los colores y no se vea tan plano usa un gradiente de fondo con 10% a 2% en gris asi el fondo no se ve tan blanco.
considero dejar los botones de edición, que tenias en la versión anterior.
el icono de cuando no hay foto, colocale un fondo que corte justo donde corta la imagen y luego el marco asi estandarizas esa area. porque actualmente el area del el icono se ve mas grande que el de la foto.

**Comment by proseuz** [comment]
@arnaldos propuestas con los cambios sugeridos
**1 gradiente de violeta **
![identity artist 4ta ronda-02](https://cloud.githubusercontent.com/assets/17308060/14996981/5a3aa1b2-1146-11e6-8eaf-078c22bc4b67.png)
**2 gradiente gris**
![identity artist 4ta ronda-01](https://cloud.githubusercontent.com/assets/17308060/14996982/5a4e7426-1146-11e6-8d34-1429e5519caa.png)

**Comment by lostwood** [comment]
Me gusta con el gradiente morado

**Comment by proseuz** [comment]
@arnaldos  cómo ves las últimas propuestas? yo prefiero el gradiente violeta

**Comment by darkestpriest** [comment]
Yo prefiero el gradiente gris.

**Comment by arnaldos** [comment]
si jhon el violeta igual las tonalidades son grises. pero no van hacia el negro. esa esta perfecta
