### ISSUE TITLE
Create a TKY_Fan Identity UI/UX-App Design

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#793]
Actual View

![tky_fan_identity](https://cloud.githubusercontent.com/assets/13594347/14788126/5a92251c-0ad0-11e6-93b6-077fe3190d8b.png)

**Comment by arnaldos** [comment]
@darkestpriest  @emmysm  @jhonmarquez92

**Comment by proseuz** [comment]
partiendo de la última propuesta de la identity artist,  hago estas propuestas de colores para la fan identity @darkestpriest @emmysm  @arnaldos @lostwood 
1
![fan identity-04](https://cloud.githubusercontent.com/assets/17308060/14982866/5bce9648-1103-11e6-9712-9d7959c735fb.png)
2
![fan identity-01](https://cloud.githubusercontent.com/assets/17308060/14982867/5bde8684-1103-11e6-9efa-f36179a11216.png)
3
![fan identity-02](https://cloud.githubusercontent.com/assets/17308060/14982868/5bf4ee06-1103-11e6-9d2b-579bdc116fef.png)
4
![fan identity-03](https://cloud.githubusercontent.com/assets/17308060/14982869/5c16c1c0-1103-11e6-8c85-1f691bb7bbb3.png)

**Comment by emmysm** [comment]
Me inclino por la propuesta 2. El botón de create sin gradiente. @jhonmarquez92 y las lineas que separan el username del status con menos opacidad.

**Comment by lostwood** [comment]
Me quedo con propuesta 2

**Comment by proseuz** [comment]
**Propuesta N°2** con los cambios sugeridos por @emmysm más algunos cambios sugeridos por @arnaldos  para la  artist identity que también pueden aplicar para la fan identity. ¿qué opinan? @lostwood @darkestpriest 
Versión 1
![fan identity 2da ronda-02](https://cloud.githubusercontent.com/assets/17308060/14998451/cbbddf96-114d-11e6-836b-81f6263c8681.png)
Versión 2
![fan identity 2da ronda-01](https://cloud.githubusercontent.com/assets/17308060/14998453/cbc93972-114d-11e6-9224-19ac661fd967.png)

**Comment by lostwood** [comment]
Se ve mucho mejor, esta nueva version y escojo la segunda propuesta

**Comment by arnaldos** [comment]
@jhonmarquez92 solo bájale un poco el al gris mas oscuro

**Comment by proseuz** [comment]
@arnaldos 
![fan identity 3ra ronda-01](https://cloud.githubusercontent.com/assets/17308060/15032299/34348274-1229-11e6-8385-cb740ee4498b.png)

**Comment by darkestpriest** [comment]
I like that!! @Fermat-ORG/mordor-team

**Comment by lostwood** [comment]
Congrat!!!! Super

**Comment by emmysm** [comment]
Implementado? @lostwood

**Comment by lostwood** [comment]
Si @emmysm
