### ISSUE TITLE
Create a TKY_Fan Wallet  following UI/UX-App Design

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#794]
Actual View

![tky_fan_wallet_following](https://cloud.githubusercontent.com/assets/13594347/14788167/8f50ba48-0ad0-11e6-8ea4-f82bc647f3b5.png)

**Comment by arnaldos** [comment]
@darkestpriest  @emmysm  @jhonmarquez92

**Comment by proseuz** [comment]
@arnaldos @emmysm @darkestpriest 
Propuesta 1
![fan_wallet_following-02](https://cloud.githubusercontent.com/assets/17308060/15004911/f27053e2-1186-11e6-912a-dcaf78a578f3.png)
Propuesta 2
![fan_wallet_following-01](https://cloud.githubusercontent.com/assets/17308060/15004912/f2840c66-1186-11e6-8c77-0a2d49f8429f.png)

**Comment by darkestpriest** [comment]
I prefer the proposal 2, what do you think @Fermat-ORG/mordor-team ?

**Comment by lostwood** [comment]
I think it is too much colorful

**Comment by arnaldos** [comment]
@jhonmarquez92 I think the same is too much color . put the default Android keyboard color, I think it is gray. look the chat app. for the drop down uses a simple color.

**Comment by proseuz** [comment]
@darkestpriest  @lostwood @arnaldos 
1
![fan_wallet_following 2da ronda-02](https://cloud.githubusercontent.com/assets/17308060/15031858/dd8682a4-1225-11e6-9bea-2e326a2c15da.png)
2
![fan_wallet_following 2da ronda-01](https://cloud.githubusercontent.com/assets/17308060/15031859/dd989458-1225-11e6-8d2e-d15c1ea238a8.png)
I prefer the proposal 1

**Comment by darkestpriest** [comment]
I like proposal 2, @Fermat-ORG/mordor-team ?

**Comment by lostwood** [comment]
The purple in the search background, it is the thing that i don't see right

**Comment by proseuz** [comment]
Do you think that maybe a color lighter or white work?@lostwood

**Comment by lostwood** [comment]
Maybe like the identity,  purple light gradient

**Comment by arnaldos** [comment]
is right version 2. just one thing the keyboard is very close to the dropdawn. 
put more space.

**Comment by proseuz** [comment]
@lostwood the search background is replaced with a white opacity of 80%
@arnaldos Is enough space between the keyboard and the window dropdawn? 
how much space you think that works?
![fan_wallet_following 3da ronda-01](https://cloud.githubusercontent.com/assets/17308060/15080468/2a42b654-1388-11e6-8e2a-d6021cfea9eb.png)

**Comment by arnaldos** [comment]
@jhonmarquez92 ready, for me is ok !!! good work !!!!! give @darkestpriest @lostwood  all resurces !!!

**Comment by darkestpriest** [comment]
Great job @jhonmarquez92

**Comment by emmysm** [comment]
Good!! :clap:
