### ISSUE TITLE
Create a TKY_Fan Wallet songs UI/UX-App Design

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#795]
Actual view

![tky_fan_wallet_song](https://cloud.githubusercontent.com/assets/13594347/14788240/e18b4940-0ad0-11e6-907b-67deedc4631f.png)

**Comment by arnaldos** [comment]
@darkestpriest  @emmysm  @jhonmarquez92

**Comment by proseuz** [comment]
@arnaldos @emmysm @darkestpriest 
Propuesta 1 y 2
![fan_wallet_song-01](https://cloud.githubusercontent.com/assets/17308060/14873207/ce670fea-0cbd-11e6-8b7a-23ad5bc58402.png)
Propuesta 3 y 4
![fan_wallet_song-02](https://cloud.githubusercontent.com/assets/17308060/14873204/ce32ee0e-0cbd-11e6-979e-39e9fcf61a82.png)
Propuesta 5 y 6
![fan_wallet_song-04](https://cloud.githubusercontent.com/assets/17308060/14873206/ce53e74e-0cbd-11e6-8e0b-e8788623596f.png)
Propuesta 7 y 8
![fan_wallet_song-03](https://cloud.githubusercontent.com/assets/17308060/14873205/ce416fc4-0cbd-11e6-8fbe-3c26076e74db.png)
Me inclino por la propuesta 1, 2, 7 y 8

**Comment by arnaldos** [comment]
@jhonmarquez92 yo diria la version lo que no estoy seguro es que tiene mucho negro y el logo casi no tiene. podemos dejar los tabs en color azul. para no salirnos tanto de la paleta de colores original.
 en caso tal tambien prueba el transparente negro cambiarlo por un tono azul casi negro pra tratar de mantener el la paleta pero muy bueno.!!

**Comment by proseuz** [comment]
Cuál versión @arnaldos ?

**Comment by arnaldos** [comment]
la 2 @jhonmarquez92

**Comment by emmysm** [comment]
geniaal! la propuesta 2 :D @jhonmarquez92

**Comment by darkestpriest** [comment]
La dos, pero con una foto de Amy Lee @jhonmarquez92 ;) ¿que opinan @Fermat-ORG/mordor-team ?

**Comment by lostwood** [comment]
La 2 me parece tambien, si colocaran otro color para la seleccion del tab seria excelente, primera vez que estoy tan de acuerdo con un diseño, los felicito

**Comment by proseuz** [comment]
@arnaldos @emmysm @lostwood 
Propuestas con los cambios sugeridos, más un pequeño cambio en el color de los nombres de las canciones para jerarquizar.
1                                                        y                              2
![fan_wallet_song2daronda-01](https://cloud.githubusercontent.com/assets/17308060/14904825/1fa02aa6-0d75-11e6-879d-56e6f87bd36f.png)
para conmplacer a @darkestpriest XD
![fan_wallet_song2daronda-02](https://cloud.githubusercontent.com/assets/17308060/14904826/1fb41908-0d75-11e6-8570-17563cab6987.png)

**Comment by darkestpriest** [comment]
Gran trabajo @jhonmarquez92 me quedo con la versión de **Amy Lee** :D ¿opiniones de @GaboHub @lostwood ?

**Comment by GaboHub** [comment]
Me gusta la tercera, pero no habría problemas por usar imagenes de artistas?

**Comment by darkestpriest** [comment]
@GaboHub  Las imagenes las cargaríamos desde swapbot, esas son públicas.

**Comment by lostwood** [comment]
Excelente la de amy lee, lo unico es el color del la linea de seleccion del tab, si pudiera ser otro color

**Comment by lostwood** [comment]
que opinan @macuare @alexanderejm

**Comment by proseuz** [comment]
@lostwood este es el 3er color de la fan wallet, con el azul violáceo no se ve bien porque no contrasta
![fan_wallet_song3raronda-02](https://cloud.githubusercontent.com/assets/17308060/14922563/147167fc-0e02-11e6-97cf-f8109745bd10.png)

**Comment by darkestpriest** [comment]
Me parece mejor la Amy Lee wallet original @jhonmarquez92

**Comment by lostwood** [comment]
Que opinas @juanaso

**Comment by arnaldos** [comment]
@jhonmarquez92 me gusta la ultima versión, con el selector del tab en amarillo así no predomina el color fucsia y se le da un equilibrio cromatico. yo lo dejaría así como esta. nose que mas le hace falta @darkestpriest @lostwood  ?

**Comment by lostwood** [comment]
Opino igual que @arnaldo el cambio del color en el selector era lo que falta excelente

**Comment by lostwood** [comment]
Existe un problema de implementación, por no contar a totalidad con todas las funcionalidades de android dentro del proyecto de fermat, estuve hablando con la gente del core y me suguirieron por los momentos, hacer el replanteo del diseño con referente a la división de la imagen entre el header y el fragmento

**Comment by proseuz** [comment]
Entiendo @lostwood  se me ocurre que podemos replantear el diseño, retomar y mejorar este:
![fan_wallet_song-03](https://cloud.githubusercontent.com/assets/17308060/15237271/32d86580-1896-11e6-9fef-004d3f0cd822.png)me parece que puede funcionar. Qué opinan? @arnaldos @emmysm

**Comment by lostwood** [comment]
the heroe of the day, a mi parecer pienso que el objetivo se cumple y lleva la escencia del anterior diseño

**Comment by emmysm** [comment]
Hola, @lostwood, se pueden hacer más propuestas de color? Pienso que se ve mejor un fondo oscuro y las portadas de los albumes sin drop shadow. Qué opinas @arnaldos?

**Comment by lostwood** [comment]
Que tal @emmysm si seria como comentastes en una de las propuestas anteriores, y de repente la parte del fondo colocar los puntos en un color que resalten un poco mas sin recargar el diseño claro

**Comment by darkestpriest** [comment]
Como dice @emmysm el fondo oscuro siempre se verá mejor, me gusta más esta versión del diseño.

**Comment by proseuz** [comment]
también creo que se ve mejor con fondo oscuro.
probé con los puntos en color magenta y amarillo.¿cuál les parece? yo me inclino por los puntos magenta porque en amarillo se interrumpe la lectura un poco.
![fan_wallet_cambio-06](https://cloud.githubusercontent.com/assets/17308060/15250479/c17b0b78-18ee-11e6-9a20-2660251adad9.jpg)
@arnaldos @emmysm @lostwood @darkestpriest

**Comment by lostwood** [comment]
Estoy de acuerdo con @jhonmarquez92

**Comment by arnaldos** [comment]
@jhonmarquez92 las siguientes recomendaciones:
- Los Tabs aumenta el alto una regla el alto de los tabs es de 48dp.
- El espacio entre los tabs y el inicio del listado debe ser de 8dp.
- Falta el tab de Artist (debe aparecer un listado de artistas donde salgan todos y tal ves agrega un icono con una estrellita o algo que permita marcar al artista como favorito y luego se pase al tab o filtro de following)
- El fondo de lo puntos no ayuda con la lectura del texto creo mejor eliminamos los puntos.
- Coloca el search del color del status bar y elimina el circulo a ver que tal se ve (prueba una con y sin el circulo colocando el color que te indico)

**Comment by proseuz** [comment]
El botón de search es de esa manera porque al presionarlo se convierte en esta barra de busqueda
@arnaldos 
![fan_wallet_following 3da ronda-01](https://cloud.githubusercontent.com/assets/17308060/15257650/26c1b3ca-1911-11e6-873c-4f7e1dca8c62.png)

**Comment by arnaldos** [comment]
@jhonmarquez92  te falto mejorar esto:

> Los Tabs aumenta el alto una regla el alto de los tabs es de 48dp.
> El espacio entre los tabs y el inicio del listado debe ser de 8dp.

Los Tabs son los que nos indican donde estamos ubicados en este caso, songs y following. plz ajusta el tamaño. si tienes alguna duda avísame.

**Comment by proseuz** [comment]
@arnaldos 
- amplié los tabs y le agregué la casilla Artist
- El espacio entre los tabs y el inicio del listado lo ajusté a 8dp.
- para seleccionar al artista como favorito creé un botón en forma de estrella.
- Creé la imagen que irá caso de que no haya foto de perfil o  imagen álbum del artista

![fan_wallet_son_artist_following-01](https://cloud.githubusercontent.com/assets/17308060/15377164/65b0df14-1d23-11e6-8950-5c541c000f42.png)

**Comment by arnaldos** [comment]
listo @jhonmarquez92 !!!! pasale los recursos a @lostwood @darkestpriest

**Comment by proseuz** [comment]
creé un banner para cuando no exista imagen del disco o foto de perfil @arnaldos @emmysm @lostwood @darkestpriest 
![6-02](https://cloud.githubusercontent.com/assets/17308060/15417201/0500ee0c-1e1d-11e6-9ba4-6ea4a7cfd5ac.png)

**Comment by emmysm** [comment]
Puedes probar colocando un stroke amarillo a la estrella? La notita está muy grande, @jhonmarquez92. Lo demás me gusta n.n

**Comment by proseuz** [comment]
1.  cuando no existen canciones ni artistas
2.  cuando no se han seleccionado canciones o artistas
3.  cuando se seleccionó una canción o un artista pero no existe foto
   ![8-02](https://cloud.githubusercontent.com/assets/17308060/15449042/7b070652-1f3c-11e6-91f6-8db5b60592be.png)
   No me gusta como se ve con el stroke
   ![7-02](https://cloud.githubusercontent.com/assets/17308060/15449045/7e0f926a-1f3c-11e6-8813-ce136494c037.png)
   @arnaldos @emmysm @lostwood

**Comment by lostwood** [comment]
Si el stroke no meparece que luce muy bien, y en el caso de que no haya canciones en el header se podria colocar la frase no songs found in tokenly o algo por el estilo

**Comment by darkestpriest** [comment]
Saludos, si no hay canciones el header podría ser mismo que en el caso que no se haya seleccionado alguna canción

**Comment by proseuz** [comment]
something like that? @darkestpriest @lostwood 

![9-02](https://cloud.githubusercontent.com/assets/17308060/15475463/0b7aca82-20d4-11e6-9cf6-be54b52ed0d3.png)

**Comment by lostwood** [comment]
yes i like it

**Comment by arnaldos** [comment]
:+1:

**Comment by proseuz** [comment]
- cuando no hay artistas en following

![10-03](https://cloud.githubusercontent.com/assets/17308060/15525769/7cfab1f4-21f6-11e6-83da-234a69bf5975.png)
@arnaldos @lostwood

**Comment by arnaldos** [comment]
:+1:

**Comment by lostwood** [comment]
excellent

**Comment by emmysm** [comment]
I like it!!

**Comment by emmysm** [comment]
Este caso se puede cerrar? @arnaldos @lostwood @darkestpriest

**Comment by lostwood** [comment]
si ya implementado

**Comment by emmysm** [comment]
Perfecto @lostwood
