### ISSUE TITLE
New splash screen with new logo.

### ISSUE THREAD

**Issue by furszy** [bitDubai/fermat-graphic-design#798]
@arnaldos @emmysm @ivonnesantos Vuelvo a armar el issue, hay que crear un splash nuevo para el inicio de Fermat con el nuevo logo.

**Comment by ivonnesantos** [comment]
Ya estoy haciendo esto mathias

**Comment by ivonnesantos** [comment]
Ya estoy haciendo esto mathias

**Comment by arnaldos** [comment]
@furszy esto es lo mismo que se aplico o se esta generando una propuesta nueva ?

**Comment by ivonnesantos** [comment]
@arnaldos este es una nueva propuesta con el nuevo logo

**Comment by arnaldos** [comment]
ok perfecto @ivonnesantos

**Comment by ivonnesantos** [comment]
@furszy le cambien solo el logo el resto de la pantalla la deje igual 
![mockups](https://cloud.githubusercontent.com/assets/15238660/15028954/31c4a91a-1215-11e6-9c6e-22021b89e093.gif)

**Comment by ivonnesantos** [comment]
Animacion para pantalla "Loading" para la aplicación de fermat general @mawisk puedes crear varias propuestas de esta animación para colocar en esta pantalla ten en consideración que esta animación se debe reproducir  en código cuando sea aprobada.

**Comment by mawisk** [comment]
![222](https://cloud.githubusercontent.com/assets/19206540/15095197/afdfca92-1485-11e6-9716-8131cf5e120e.gif) @ivonnesantos

**Comment by ivonnesantos** [comment]
@furszy aca esta mas o menos lo que nos pediste y se ve bien pero no parece un loading parece mas bien el intro de un video y eso se debe a que el logo es muy complicado tiene muchas piezas, a mi me parece que deberiamos hacer una propuestas mas sencilla como esto 
![image](https://cloud.githubusercontent.com/assets/15238660/15120592/43416dbc-15e0-11e6-841f-f93ff7195a8e.png)
pero con las piecitas de fermat o se puede mantener el logo armado pero que las tuercas tengan movimiento.

**Comment by emmysm** [comment]
![propuesta](https://cloud.githubusercontent.com/assets/15143489/15165604/e087b51c-16e0-11e6-8e03-97e49768e5bf.png)

Esto también puede ser una opción, @ivonnesantos @mawisk @furszy

**Comment by mawisk** [comment]
![rueda-gif](https://cloud.githubusercontent.com/assets/19206540/15185390/b95b9814-1762-11e6-8085-bd1a8b40596d.gif) @ivonnesantos

**Comment by ivonnesantos** [comment]
Se ve bien 
1- Vamos a ponerle a la tuerca los colores del logo (no se si son esos)
2- La tuerca un poco mas pequeña
3- la barra mas delgada

@arnaldo tu que piensas de esto, fijate que hicimos varias propuestas que involucran el logo pero no funcionan bien para loading porque es demasiado complejo como para armarlo.

**Comment by mawisk** [comment]
![rueda2-gif](https://cloud.githubusercontent.com/assets/19206540/15216902/e4bfbbe6-1822-11e6-9d6a-da1f94595fb5.gif)

1- Los colores son los mismos del logo desde un principio.
2 - La tuerca mas pequeña y la barra mas delgada.
@ivonnesantos

**Comment by furszy** [comment]
Esto es lo que quedó o se sigue desarrollando?

**Comment by ivonnesantos** [comment]
@furszy esas son varias propuestas y queremos saber tu opinion al respecto y la de @arnaldos tambien

**Comment by Luis-Fernando-Molina** [comment]
Va por el lado de @mawisk

**Comment by ivonnesantos** [comment]
@Luis-Fernando-Molina  la que tiene la tuerquita o la que es el logo armandose?

**Comment by arnaldos** [comment]
@ivonnesantos  a mi me gusta mas la versión del engranaje !

**Comment by arnaldos** [comment]
@ivonnesantos @mawisk @furszy esto como quedo ??

**Comment by arnaldos** [comment]
este caso queda detenido por ahora, se retomara cuando se solicite nuevamente
