### ISSUE TITLE
Logo para Fermat DAP - Digital Asset Platform

### ISSUE THREAD

**Issue by Luis-Fernando-Molina** [bitDubai/fermat-graphic-design#80]

**Comment by Luis-Fernando-Molina** [comment]
Preguntarme los detalles en reunión.

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina ok perfecto !!!

**Comment by m471c4** [comment]
@Luis-Fernando-Molina primero boceto para Fermat DAP:

![fermatdap](https://cloud.githubusercontent.com/assets/13468350/9574231/a7b09282-4f8e-11e5-9cd1-1f0be7232c12.png)

**Comment by Luis-Fernando-Molina** [comment]
El icono está bueno pero no aplica para este concepto.

Como un asset puede ser muchas cosas, no hay una forma clara de representarlos, yo usaría formas geométricas simples donde cada una representaría un asset.

Para denotar que son digitales yo usaría la pantalla de un monitor o un dispositivo movil y pondría las formitas adentro.

**Comment by m471c4** [comment]
Muy bien, lo subo en un momento.

**Comment by m471c4** [comment]
@Luis-Fernando-Molina ¿qué tal así?

![fermatdap2](https://cloud.githubusercontent.com/assets/13468350/9584969/de83190c-4fdd-11e5-8361-449d1146f5c8.png)

**Comment by Luis-Fernando-Molina** [comment]
puede ser, pero que no se superpongan las formas. Tambien estaria bueno que haya dos dispositivos, uno de cada lado, un telefno y un monitor, y un canal que los conecte, y lo siguiente:

El cuadrado en el de la iz
El triangulo en el de la derecha
A la iz el circulo pero en linea de puntos
A la derecha el circulo con linea de puntos 
Y en el medio del canal el circulo en linea de puntos pero pintado de rojo.

ok?

**Comment by m471c4** [comment]
@Luis-Fernando-Molina no estoy segura de si esto es lo que quieres, te paso a ver qué te parece:

![fermatdap3](https://cloud.githubusercontent.com/assets/13468350/9672924/bb7ed788-5268-11e5-8c42-3cfc6cb9997e.png)

**Comment by Luis-Fernando-Molina** [comment]
si, pero : 

1) Sin el circulo
2) los dispositivos en un tamaño mas un poco mas chico y mas parecidos a los que usamos en otros iconos.
3) Poné tres dispositivos, uno arriba y dos abajo como en un triangulo.

**Comment by Luis-Fernando-Molina** [comment]
la separación de DAP es la normal? La veo como muy espaciada

**Comment by m471c4** [comment]
@Luis-Fernando-Molina acá con los cambios. Estoy usando los mismos dispositivos que ha venido usando @arnaldos en sus diseños. La separación de DAP es la estandar, ¿quisieras que lo uniera más?

![fermatdap4](https://cloud.githubusercontent.com/assets/13468350/9711350/c7d6b040-550c-11e5-8d3f-64af13016786.png)
![fermatdap5](https://cloud.githubusercontent.com/assets/13468350/9711351/c7ef42fe-550c-11e5-82e2-41c0b871fb4e.png)

**Comment by Luis-Fernando-Molina** [comment]
El de arriba esta OK aunque los dispositivos están un poco grandes

**Comment by m471c4** [comment]
Muy bien, ¡los reduciré y lo subo!
