### ISSUE TITLE
Create a 3D coin for team Sierra

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#804]
the logotype was choose in this issue #293

**Comment by jonathanborges3d** [comment]
@jayborges Please upload the source files. Thanks!

**Comment by jonathanborges3d** [comment]
@jayborges Waiting for source files.

**Comment by jonathanborges3d** [comment]
Oh, sorry @jayborges , the designer for this logo was @adryx83.

**Comment by jonathanborges3d** [comment]
@Miguelcldn @arnaldos 

Primera versión 3D
![logo_sierra_team](https://cloud.githubusercontent.com/assets/13649739/15452128/05c26adc-1fad-11e6-8187-86d432e41419.jpg)

**Comment by Miguelcldn** [comment]
Good! :+1: approved
