### ISSUE TITLE
Create a 3D coin for team Charlie

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#805]
the logotype was choose in this issue #238

**Comment by jonathanborges3d** [comment]
@Miguelcldn @arnaldos Versión 3D
![charlie_1](https://cloud.githubusercontent.com/assets/13649739/15035151/60074c1e-1248-11e6-8b60-78d30635e6e8.jpg)

**Comment by Miguelcldn** [comment]
Nice! :heart_eyes: Could it be much of a trouble if I ask for the source files to play with it on Blender? >.<

**Comment by jonathanborges3d** [comment]
@Miguelcldn No problem! Sent via email :+1:
