### ISSUE TITLE
Create a new banner for Store App

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#806]
Currently this is the banner. It should be changed to one that is related to a store.

![wallet_store-03](https://cloud.githubusercontent.com/assets/13594347/15022851/7ec1bb9a-11f7-11e6-8da6-6ed7335f7860.jpg)

Size 1024x500 px

**Comment by Joseangel2v** [comment]
P-1
![bnn1](https://cloud.githubusercontent.com/assets/17457499/15204371/5c7978c2-17d6-11e6-860d-dc743ee3a544.png)

**Comment by Joseangel2v** [comment]
P-2
![bnn4](https://cloud.githubusercontent.com/assets/17457499/15204396/a1e0cb72-17d6-11e6-90e6-3a6db9eac858.png)

**Comment by Joseangel2v** [comment]
P-3
![bnn3](https://cloud.githubusercontent.com/assets/17457499/15204386/8a73fa5e-17d6-11e6-9549-805b5c738b80.png)

**Comment by Joseangel2v** [comment]
P-4
![bnn5](https://cloud.githubusercontent.com/assets/17457499/15204400/a854a212-17d6-11e6-97a2-d6cd69dcdfc8.png)

**Comment by Joseangel2v** [comment]
P-5
![bnn2](https://cloud.githubusercontent.com/assets/17457499/15204410/c80df3d8-17d6-11e6-928f-401016351548.png)

**Comment by Joseangel2v** [comment]
P-6
![bnn7](https://cloud.githubusercontent.com/assets/17457499/15204450/4e5d2f12-17d7-11e6-87d4-04ccaf97837d.png)

**Comment by Joseangel2v** [comment]
P-7
![bnn2](https://cloud.githubusercontent.com/assets/17457499/15204496/b1b7cc84-17d7-11e6-9d0e-c0019230513c.png)

**Comment by emmysm** [comment]
Me gustaría ver otras propuestas diferente al primer banner que se planteó. Puedes trabajar con otra paleta de colores, y proponer un concepto gráfico diferente  @Joseangel2v  :smile_cat:

**Comment by Joseangel2v** [comment]
P-8
![bnn1](https://cloud.githubusercontent.com/assets/17457499/15239148/dfb1374c-18a9-11e6-8f5e-fb46b5a8acb6.png)

**Comment by Joseangel2v** [comment]
P-9
![bnn2](https://cloud.githubusercontent.com/assets/17457499/15239156/f1349392-18a9-11e6-918b-31a5de028d10.png)

**Comment by Joseangel2v** [comment]
P-10
![bnn4](https://cloud.githubusercontent.com/assets/17457499/15239167/10a6a24c-18aa-11e6-9cd0-7755f8a01ca4.png)

**Comment by Joseangel2v** [comment]
P-11
![bnn7](https://cloud.githubusercontent.com/assets/17457499/15239189/3f5d0270-18aa-11e6-9bad-d240ac220688.png)

**Comment by Joseangel2v** [comment]
P-12
![bnn3](https://cloud.githubusercontent.com/assets/17457499/15239196/4d35a852-18aa-11e6-8022-5f3c190e6db7.png)

**Comment by Joseangel2v** [comment]
P-13
![bnn5](https://cloud.githubusercontent.com/assets/17457499/15239242/b13baa54-18aa-11e6-8552-a6e02a3028b2.png)

**Comment by arnaldos** [comment]
@Joseangel2v trabajemos partiendo de la versión P8 la idea de rediseñar el banner es buscar gráficamente el concepto de un store de apps. por eso en este momento no debemos mostrar nada relacionado a crypto currencies ni fiat currencies. tambien colocale el nombre de la app plz

**Comment by Joseangel2v** [comment]
P-14
![bnn1](https://cloud.githubusercontent.com/assets/17457499/15266284/e3e1b4e8-1969-11e6-974a-c260249f657b.png)

**Comment by Joseangel2v** [comment]
P-15
![bnn2](https://cloud.githubusercontent.com/assets/17457499/15266286/f675d35a-1969-11e6-8921-49363efcc03c.png)

**Comment by Joseangel2v** [comment]
P-16
![bnn3](https://cloud.githubusercontent.com/assets/17457499/15266287/fe79997e-1969-11e6-822e-d9eed3982eeb.png)

**Comment by Joseangel2v** [comment]
P-17
![bnn4](https://cloud.githubusercontent.com/assets/17457499/15266315/1b17fc96-196b-11e6-8d94-25e1f0aa6cef.png)

**Comment by Joseangel2v** [comment]
P-18
![bnn5](https://cloud.githubusercontent.com/assets/17457499/15266320/277614fa-196b-11e6-9875-f0da41ee7a5d.png)

**Comment by Joseangel2v** [comment]
P-19
![bnn7](https://cloud.githubusercontent.com/assets/17457499/15266321/30602920-196b-11e6-9406-be694f2dcaea.png)

**Comment by arnaldos** [comment]
@Joseangel2v usemos el P-17 asegurate de que los clores sean los mismos del icono

**Comment by Joseangel2v** [comment]
P- 20
![bnn1](https://cloud.githubusercontent.com/assets/17457499/15491153/a1c5e6ee-2137-11e6-8111-e91c6c3b0557.png)

**Comment by Joseangel2v** [comment]
P - 21
![bnn2](https://cloud.githubusercontent.com/assets/17457499/15491166/b3cd0462-2137-11e6-81b8-2e76f0adace1.png)

**Comment by Joseangel2v** [comment]
P-22
![bnn1](https://cloud.githubusercontent.com/assets/17457499/15515706/4e3023d2-21b9-11e6-8cc4-7461ea568dec.png)

**Comment by arnaldos** [comment]
@Joseangel2v solo una cosa el nombre del texto cámbialo de wallet store a app store y aumenta un poco el tamaño del icono y texto

**Comment by Joseangel2v** [comment]
P-23
![bnn2](https://cloud.githubusercontent.com/assets/17457499/15518153/369c4bcc-21c5-11e6-92ba-6aec42fe7dd6.png)

**Comment by arnaldos** [comment]
@Joseangel2v la A y la S en mayusculas

**Comment by arnaldos** [comment]
del resto esta bien sube eso apenas lo tengas

**Comment by Joseangel2v** [comment]
![bnn1](https://cloud.githubusercontent.com/assets/17457499/15537627/68fcedde-2241-11e6-9b6a-3350fb230ce6.png)

**Comment by emmysm** [comment]
Pienso que está muy pegado el texto al icono, yo le daría un poco de separación. Solo le cambiaría eso. @Joseangel2v

**Comment by arnaldos** [comment]
si @Joseangel2v  baja el texto comote comenta @emmysm

**Comment by arnaldos** [comment]
@Joseangel2v centra el texto !! tiene mas  peso del lado derecho

**Comment by Joseangel2v** [comment]
Ok, ok voy gracias @arnaldos no me habia fijado.

**Comment by Joseangel2v** [comment]
![bnn1](https://cloud.githubusercontent.com/assets/17457499/15557188/84f479c6-229b-11e6-8e27-01d6c4fb0045.png)

**Comment by arnaldos** [comment]
:+1:
