### ISSUE TITLE
View error report fermat Chat 

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#809]
current view

![error-report](https://cloud.githubusercontent.com/assets/13594347/15028255/bf7ed95a-1211-11e6-9db2-3f916b486dea.png)

**Comment by arnaldos** [comment]
@franklinmarcano1970 @josejcb improved screen to error report

![fermat_chat_error-report](https://cloud.githubusercontent.com/assets/13594347/15028272/d79b55f4-1211-11e6-81ef-a717e387d2af.png)

**Comment by josejcb** [comment]
This view will not be available anymore. In fact, Luis ask me for remove it.

**Comment by arnaldos** [comment]
so ..... just i close it !!
