### ISSUE TITLE
Logo para Fermat CBP Crypto Broker Platform

### ISSUE THREAD

**Issue by Luis-Fernando-Molina** [bitDubai/fermat-graphic-design#81]
Un crypto broker es una persona o empresa que se dedica a comprar y vender crypto currency (bitcoin por ejemplo) y ganar con la diferencia entre el precio de compra y el de venta.

Necesitamos un logo para esta parte de la plataforma.

**Comment by m471c4** [comment]
@Luis-Fernando-Molina primer boceto para Fermat CBP:

![fermatcbp](https://cloud.githubusercontent.com/assets/13468350/9515911/a644abcc-4c6e-11e5-86a8-9b044d681c49.png)

**Comment by m471c4** [comment]
Aun creo que se puede mejorar la forma de las manos, pero es una primera idea.

**Comment by Luis-Fernando-Molina** [comment]
ok, va bien, fijate de aplicar las mejoras que tengas en mente.

**Comment by m471c4** [comment]
@Luis-Fernando-Molina acá hay dos propuestas con las mejoras. Creo que la que tiene las flechas ayuda a reforzar la idea de intercambio comercial. Por favor dime qué te parecen.

![fermatcbp1](https://cloud.githubusercontent.com/assets/13468350/9542449/a8270ba2-4d3a-11e5-9420-934a11fa8a38.png)
![fermatcbp2](https://cloud.githubusercontent.com/assets/13468350/9542450/a829cae0-4d3a-11e5-929a-e493ca6fe139.png)

**Comment by Luis-Fernando-Molina** [comment]
:+1:  nos quedamos con la segunda. Listo este tema.

**Comment by Luis-Fernando-Molina** [comment]
El botoncito de la camisa por favor ponelo en blanco y tambien poneselo en la camisa del que no lo tiene.

**Comment by m471c4** [comment]
@Luis-Fernando-Molina con los cambios solicitados:

![fermatcbp3](https://cloud.githubusercontent.com/assets/13468350/9651431/6fdb6924-51da-11e5-93fc-08962ec81783.png)

**Comment by Luis-Fernando-Molina** [comment]
:+1:  pasaselo a Miguel (en general siempre que cambiemos un logo de Fermat.org, asegurate que se actualice ahí antes de cerrar tu caso por favor)

**Comment by m471c4** [comment]
Buenísimo. Lo subo y cierro el caso.
