### ISSUE TITLE
Generate design workflow steps 

### ISSUE THREAD

**Issue by emmysm** [bitDubai/fermat-graphic-design#810]

**Comment by emmysm** [comment]
![text3500 1](https://cloud.githubusercontent.com/assets/15143489/15047219/c7cb8b7a-12ad-11e6-97e9-36ce24e08b41.png)

**Comment by Joseangel2v** [comment]
![pro1](https://cloud.githubusercontent.com/assets/17457499/15130124/0c3efc00-1610-11e6-8173-5f4d868082da.png)

**Comment by Joseangel2v** [comment]
![pro2](https://cloud.githubusercontent.com/assets/17457499/15130136/18ebeb8e-1610-11e6-8c5f-9a4173c96e68.png)

**Comment by Joseangel2v** [comment]
![pro3](https://cloud.githubusercontent.com/assets/17457499/15130145/238f67fa-1610-11e6-92a1-b9140158147b.png)

**Comment by Joseangel2v** [comment]
![pro 4](https://cloud.githubusercontent.com/assets/17457499/15130150/2c331cd0-1610-11e6-8c81-1a953043186d.png)

**Comment by Joseangel2v** [comment]
![pro5](https://cloud.githubusercontent.com/assets/17457499/15130159/34b14cc4-1610-11e6-9009-73fa07f08c6e.png)

**Comment by Joseangel2v** [comment]
![pro7](https://cloud.githubusercontent.com/assets/17457499/15130171/434e6686-1610-11e6-8c42-23e190dae48f.png)

**Comment by emmysm** [comment]
@ricardo460

**Comment by emmysm** [comment]
@Joseangel2v hay que alinear a la izquierda las opciones. Y agregarle flechitas para los desplegable

**Comment by Joseangel2v** [comment]
![pro8](https://cloud.githubusercontent.com/assets/17457499/15132897/04337190-1628-11e6-9d20-2a89694d3c17.png)

**Comment by emmysm** [comment]
Issue does not apply to workFlow-Edit.
