### ISSUE TITLE
Generate logo for taxi platform

### ISSUE THREAD

**Issue by emmysm** [bitDubai/fermat-graphic-design#811]

**Comment by arismendi227** [comment]
@jhonmarquezm @arnaldos @emmysm Propuestas
1
![propuesta1](https://cloud.githubusercontent.com/assets/19276382/15190356/4440cff6-1779-11e6-86c8-ec6d2d9d3bb4.png)
2
![propuesta2](https://cloud.githubusercontent.com/assets/19276382/15190359/4922673c-1779-11e6-8696-213c6d2d4bba.png)
3
![propuesta3](https://cloud.githubusercontent.com/assets/19276382/15190366/51455c30-1779-11e6-8ea6-a1d8d5665e4c.png)

**Comment by proseuz** [comment]
@arismendi227  el **3** creo que puede funcionar, la sombra llévala desde la parte superior de la lupa hasta el borde inferior de la misma. qué opinas? @arnaldos

**Comment by arismendi227** [comment]
@jhonmarquez92  @arnaldos @emmysm
4
![propuesta4](https://cloud.githubusercontent.com/assets/19276382/15194486/e7cb9af8-178c-11e6-8cc1-14b93b453eff.png)
5
![propuesta5](https://cloud.githubusercontent.com/assets/19276382/15194496/f49ef4fa-178c-11e6-993b-984673f52eac.png)
6
![propuesta6](https://cloud.githubusercontent.com/assets/19276382/15194502/fc064298-178c-11e6-8716-63c75514e663.png)

**Comment by proseuz** [comment]
@arismendi227 centra todos los elementos pareciera que están levemente movidos fuera del centro (los faroles del carrito, el aviso, las ruedas)
intenta hacer lo siguiente:
1 prueba con otro dibujo del taxi desde otros ángulos, formas, ect.
2 quita la palabra taxi, pero mantén el casco que lo caracteriza 
2 trata de no poner tanto blanco, solo el contorno de los elementos deben llevarlo.
3 explora el elemento de cuadrados que utilizaste en la primera propuesta, trata de que no le quite protagonismo al taxi.
4 no uses el pin ni la lupa ya que se ha utilizado en otros logos

**Comment by arismendi227** [comment]
@jhonmarquez92 @arnaldos @emmysm
nuevas propuestas
7
![propuesta7](https://cloud.githubusercontent.com/assets/19276382/15234265/ab1f2686-1879-11e6-8414-4db3819bc83a.png)
8
![propuesta8](https://cloud.githubusercontent.com/assets/19276382/15234266/b1c6c674-1879-11e6-900d-85ca4e9a01d1.png)
9
![propuesta9](https://cloud.githubusercontent.com/assets/19276382/15234268/b78db784-1879-11e6-960e-8bfe3f4f3ec3.png)
10
![propuesta10](https://cloud.githubusercontent.com/assets/19276382/15234269/bfd56338-1879-11e6-8671-bd2483346722.png)

**Comment by arnaldos** [comment]
@arismendi227 el concepto de la 8 pero sustituye la libreta por una tablet u otro dispositovo mobile

**Comment by proseuz** [comment]
@arismendi227 utiliza el taxi de la 7 junto la sugerencia de @arnaldos . 

mejorale lo siguiente:
- los cuadritos dentro del taxi que no estén tan pegados al stroke de la rueda
- alinea las ventanas del carrito (que el espacio que hay en la parte superior sea parejo)
- Cuida que el grosor del stroke que se mantenga en todo el carro (fíjate en las ruedas y el casco)

**Comment by emmysm** [comment]
Añado a las correcciones de Jhon, que el carro tenga las ventanas en otro color, como lo planteaste en la propuesta 8.

**Comment by arismendi227** [comment]
@jhonmarquez92 @arnaldos @emmysm
modificaciones
1
![11](https://cloud.githubusercontent.com/assets/19276382/15260549/43f7ee86-1921-11e6-86bd-e5b77ccf9129.png)
2
![12](https://cloud.githubusercontent.com/assets/19276382/15260557/4e39d422-1921-11e6-9701-9cb077512ac8.png)

**Comment by proseuz** [comment]
Me gusta la propuesta 2. Solamente  mejora el símbolo de wifi, pon el stroke por fuera de la forma. ¿qué opinas @arnaldos ?

**Comment by arismendi227** [comment]
@jhonmarquez92 @arnaldos @emmysm
modifificado
![taxi-f](https://cloud.githubusercontent.com/assets/19276382/15308483/d00b5466-1ba7-11e6-9c44-c1404f8e516b.png)

**Comment by emmysm** [comment]
Genial @arismendi227  :smile:

**Comment by proseuz** [comment]
Excelente @arismendi227
