### ISSUE TITLE
Generate improvements views for the customer community

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#812]
Views

![custommer-community](https://cloud.githubusercontent.com/assets/13594347/15047953/0ae3f296-12b1-11e6-9652-15f1c4603be1.gif)

**Comment by arnaldos** [comment]
@abicelis here put the post of the customer community

**Comment by Carelsy** [comment]
@arnaldos @Luis-Fernando-Molina @emmysm @abicelis 
![propuesta-1](https://cloud.githubusercontent.com/assets/17755307/15060184/03b67c6e-12f2-11e6-9d34-46e27002a7b7.png)

**Comment by Carelsy** [comment]
@arnaldos @Luis-Fernando-Molina @emmysm @abicelis
![propuesta-2](https://cloud.githubusercontent.com/assets/17755307/15060232/483420c6-12f2-11e6-8d3c-7907445d8882.png)

**Comment by Carelsy** [comment]
@arnaldos @Luis-Fernando-Molina @emmysm @abicelis 
![propuesta-3](https://cloud.githubusercontent.com/assets/17755307/15060260/91c7cf9e-12f2-11e6-856d-321d31d79115.png)

**Comment by abicelis** [comment]
@Carelsy @arnaldos A @orlando711 le gusta el segundo diseno, a mi me gusta Ese y el tercero tambien se ve bueno.

Aqui esta el mock en el que esta trabajando orlando, Donde se ven sus ideas sobre la misma pantalla:
http://ninjamock.com/s/4V85S

Una cosa, en esta pantalla de home, deben diferenciarse los usuarios que estan conectados ya con uno, de los que no estan. Actualmente se diferencian superponiendole a la foto del usuario un iconito como se ve aca:

![screenshot from 2016-05-05 22-01-50](https://cloud.githubusercontent.com/assets/9850854/15062338/dafe61ee-1308-11e6-8c8e-eddbe51a6de2.png)

En el mock de orlando, el lo puso con un circulito al lado de cada user.

Otra cosa, arriba en el action bar, donde dice "Customer community", a la derecha de ese texto debe salir la foto de la identidad activa dentro del community. En el mock de orlando se ve!

**Comment by Carelsy** [comment]
@arnaldos @abicelis  aquí esta la propuesta basada en el mock de @orlando711 ![propuesta-4](https://cloud.githubusercontent.com/assets/17755307/15083865/8fbe7a8e-1399-11e6-91b7-894d61dbc651.png)

**Comment by abicelis** [comment]
@carelsy @arnaldos me parece bien el diseño.  Faltarían la pantalla del profile y los dialogs, no se si se me paso algo más.

**Comment by ivonnesantos** [comment]
@Carelsy me gusta tu propuesta solo una recomendación restale a la linea gris que lo separa un poco de grosor y a la linea de ubicación de los tabs tambien del resto me gusta esta muy linda.

**Comment by arnaldos** [comment]
@abicelis si esta bien el diseño solo faltan esas pantallas para revisar el resto de las pantallas. el diseño esta bueno. opino lo mismo que @ivonnesantos de hacer las lineas mas delgadas. me gusta la diagramacion en lista de la ultima propuesta esta muy bueno @Carelsy .

**Comment by Carelsy** [comment]
@arnaldos @abicelis @ivonnesantos @orlando711![propuesta-5](https://cloud.githubusercontent.com/assets/17755307/15088244/f0763e72-13ba-11e6-8ef4-65406244daca.png)

**Comment by Carelsy** [comment]
@arnaldos @abicelis @orlando711 @ivonnesantos estas son las observaciones que me hizo llegar @orlando711 ![propuesta-6](https://cloud.githubusercontent.com/assets/17755307/15088746/5554db04-13c1-11e6-9735-e87061b9a5bc.png)

**Comment by arnaldos** [comment]
@Carelsy En el tab la linea debe ser mas delgada también, que paso con las otras vistas ??

**Comment by Carelsy** [comment]
@arnaldos @abicelis @orlando711 @ivonnesantos Connections ![connections](https://cloud.githubusercontent.com/assets/17755307/15089327/834ab070-13ca-11e6-8fe8-04b51d00c132.png)

**Comment by Carelsy** [comment]
@arnaldos @abicelis @orlando711 @ivonnesantos Notifications 
![notifications](https://cloud.githubusercontent.com/assets/17755307/15089337/ed40ca78-13ca-11e6-95af-5c875f8a0673.png)

**Comment by Carelsy** [comment]
@arnaldos @abicelis @orlando711 @ivonnesantos @emmysm ![pantallas-1](https://cloud.githubusercontent.com/assets/17755307/15090002/1a0b57e0-13de-11e6-806a-c16a395c78a3.png)

**Comment by Carelsy** [comment]
@arnaldos @abicelis @orlando711 @ivonnesantos @emmysm ![pantallas-2](https://cloud.githubusercontent.com/assets/17755307/15090044/499138b6-13e0-11e6-8194-c5e6418024d7.png)

**Comment by Carelsy** [comment]
@arnaldos @abicelis @orlando711 @ivonnesantos @emmysm  
![pantalla-3](https://cloud.githubusercontent.com/assets/17755307/15093155/799d5194-1448-11e6-9239-4510373ed03c.png)

**Comment by abicelis** [comment]
@Carelsy @arnaldos @orlando711

Varios comentarios que vienen de @nelsonalfo:
- Eliminar la flecha <- en el appBar, no es necesaria pues la subApp solo tiene un fragmento.
- En el app, el tab que esta activo tiene una barrita que en los disenos tiene un degradado de azul a rosado, esa barrita solo puede ser de un solo color, no se pueden hacer degradados.
  - Falta este dialogo, en donde se selecciona cual identidad del dispositivo local se usara en la community:
    ![image](https://cloud.githubusercontent.com/assets/9850854/15164518/24c077d0-16d9-11e6-8738-986fc361d900.png)

**Comment by m471c4** [comment]
@abicelis here's the dialog. We can make it smaller, if the list of identities is going to be larger, using a scroll bar.

![community](https://cloud.githubusercontent.com/assets/13468350/15207265/f468e642-17f2-11e6-9a99-b437fd064bd0.png)

**Comment by abicelis** [comment]
It looks great @m471c4 , i'd only add the identity image next to each name, to make it easier for the user to find his/her identity.

**Comment by m471c4** [comment]
@abicelis what do you think?:

![community_2](https://cloud.githubusercontent.com/assets/13468350/15233232/1a763088-1875-11e6-819d-2d810b70d359.png)

**Comment by m471c4** [comment]
@abicelis without the radio buttons, highlighting the selected identity as you suggested. I made two color version:

![community_3](https://cloud.githubusercontent.com/assets/13468350/15233622/2ad0ee84-1878-11e6-9bda-b9a4d0ae064c.png)

**Comment by abicelis** [comment]
@m741c4 I like the blue one, I think it looks great!

**Comment by m471c4** [comment]
@abicelis great! I'll generate the document and resources :)

**Comment by arnaldos** [comment]
@m471c4 great job i like it. just one thing change de buttom names for icons, cancel for "X" Accept for a check. 

**Note:** @abicelis this change we need make in all app when this buttom show.

**Comment by m471c4** [comment]
@arnaldos thank you! Here's the proposal with the iconic buttons, @abicelis give me some feedback too, please:

![community_4](https://cloud.githubusercontent.com/assets/13468350/15256708/be25d2ec-1910-11e6-81f8-db102cc5f0d2.png)

**Comment by abicelis** [comment]
@m471c4 dont like those icons at all. Is this the new standard? really?
Me no like.

**Comment by m471c4** [comment]
@arnaldos @abicelis final views for this identity, with all the improvements. I also changed the buttons of the small dialogs. I'm already uploading this to the repo, with all the resources needed and the document.

![community_final](https://cloud.githubusercontent.com/assets/13468350/15266379/0862c332-1971-11e6-8c38-6011873ade77.png)

**Comment by arnaldos** [comment]
@m471c4 nice just send the resources to @abicelis

**Comment by arnaldos** [comment]
let me know when you apply this.

**Comment by abicelis** [comment]
@arnaldos I already have the resources, thanks @m471c4!

**Comment by arnaldos** [comment]
@abicelis  nice !! so I close this
