### ISSUE TITLE
Create a icon for Android App connection framework

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#815]
Reference issue https://github.com/Fermat-ORG/fermat/issues/6165

**Comment by m471c4** [comment]
@arnaldos here are my first proposals for this logo. I worked with typography and the connection concept.

![logo1](https://cloud.githubusercontent.com/assets/13468350/15600572/ca5db4b4-23b8-11e6-96e6-754ee34f59df.png)

**Comment by m471c4** [comment]
@arnaldos otra propuesta,con el nombre y otra propuesta de color:

![logo2](https://cloud.githubusercontent.com/assets/13468350/15602944/0aa71b84-23c6-11e6-9aa3-a902cf178940.png)

**Comment by m471c4** [comment]
@arnaldos otra propuesta más, usando los mismos elementos de la anterior:

![logo3](https://cloud.githubusercontent.com/assets/13468350/15725510/560c3688-281a-11e6-8e1e-24efbead92e5.png)

**Comment by furszy** [comment]
La primera app va a ser la de chat, sería bueno que sea el mismo logo de chat con la marca de Fermat en algún lado.
