### ISSUE TITLE
Change the colors of the app for the tones of the new logo

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#816]

**Comment by emmysm** [comment]
![desktop_launcher-01](https://cloud.githubusercontent.com/assets/15143489/15654592/47b5ace8-265f-11e6-8d0a-a4b9ba63e0e2.png)

@arnaldos

**Comment by arnaldos** [comment]
se ve bien el cambio, solo hay un ajuste, estandarizar los colores de las pestañas que filtran las identidades, y comunities

**Comment by emmysm** [comment]
Perfecto. Es la paleta de colores que me pareció más ideal para este caso, @arnaldos. Haré los ajustes.
