### ISSUE TITLE
Create a logo for Skull Ronin Team 

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#819]
@jonathanborges3d este seria el logo de mi team porfa para que me ayudes con lo del 3D. dime que te paso si necesitas los editables.

![skull-ronin](https://cloud.githubusercontent.com/assets/13594347/15218972/e6bf8f94-182b-11e6-8af3-27663d06e8a3.jpg)

**Comment by jonathanborges3d** [comment]
@arnaldos Ok, porfa sube el .ai y me avisas. Los logos de los equipos de GD tendrán el mismo tipo de moneda? qué sabes al respecto?

**Comment by arnaldos** [comment]
OK, ya subo el ai ... no se como se va a manejar eso, yo hice el logo con un formato circular pensando en las monedas como se han trabajado el resto.
