### ISSUE TITLE
Isologotipos de las SubApp para Fermat.org

### ISSUE THREAD

**Issue by m471c4** [bitDubai/fermat-graphic-design#82]
Este issue es para ir actualizando los isologos de las subaplicaciones. Por ahora se subirán las versiones finales de los que tengamos listos y versiones provisionales de los que no. Cada vez que se actualice alguno, se debe notificar a @Miguelcldn para que el se encargue de subirlo.

@arnaldos por favor sube a este issue en png (fondo transparente), en tamaño de 2060px de ancho los logos que ya tengas listos. Cuando lo hagas menciona a Miguel.

**Comment by m471c4** [comment]
@Miguelcldn acá está el de Fermat SHP.

![fermatshop](https://cloud.githubusercontent.com/assets/13468350/9454307/b52fac6c-4a8a-11e5-99e5-e26794702b44.png)

**Comment by m471c4** [comment]
@Miguel acá los logos provisionales para Fermat DAP y CBP.

![fermatcbp](https://cloud.githubusercontent.com/assets/13468350/9454672/a40794d8-4a8d-11e5-92d5-0c25420f69f8.png)
![fermatdap](https://cloud.githubusercontent.com/assets/13468350/9454673/a41bb990-4a8d-11e5-90a3-e2bdddeacd45.png)

**Comment by Miguelcldn** [comment]
Gracias, ordeno el orden de la página y los agrego

**Comment by Luis-Fernando-Molina** [comment]
@m471c4 bien Dayana, please dale prioridad a reemplazar los iconos repetidos.

**Comment by arnaldos** [comment]
@Miguelcldn  aquí agrego las imágenes para fermat.org
![fermat_pip_def_png](https://cloud.githubusercontent.com/assets/13594347/9527956/ebd43ed0-4cbb-11e5-964b-238dd633757f.png)
![fermat_p2p_def_png](https://cloud.githubusercontent.com/assets/13594347/9527959/f0b57d2e-4cbb-11e5-9f75-c3e3b2880cce.png)
![fermat_dmp_png](https://cloud.githubusercontent.com/assets/13594347/9527963/f73e1d2c-4cbb-11e5-92d1-a2da219f2259.png)

**Comment by Luis-Fernando-Molina** [comment]
@m471c4 @arnaldos hay una insconsistencia en el logo de DMP respecto a los otros, en particular con SHP y PIP.

En SHP y PIP claramente las billeteras tienen un borde blanco, en DMP rojo. Inclusive los bordes son de diferente visbilidad entre SHP y PIP (claro que son de distintos tamaños la billetras)

Como hacemos para que esto quede consistente?

**Comment by Luis-Fernando-Molina** [comment]
Por otro lado, la frace que va debao de P2P está claramente en un formato diferente a todo el resto. Inclusive algnasde las otras frases estan parecidas pero no iguales.

**Comment by Luis-Fernando-Molina** [comment]
El carrito en SHP tiene un borde blanco, cuyo equivalente en PIP (el elemento verde) no lo tiene; y el equivalente en P2P (la estrella) lo tiene de un ancho diferente.

**Comment by Luis-Fernando-Molina** [comment]
En otros logos que está bocentando @arnaldos también hay billeteras. Estas no pueden tener cualquier tamaño, por una cuestion de consistencia. Deberían haber dos o tres tamaños ya definidos como mucho y ser siempre los mismos. Cuando me hablaban de un manual de marca, yo me imaginaba exactamente esto, como se usan cada uno de los elementos, y cuales son los valores que pueden tomar, etc. QUizas me equivoco, no se.

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina ya voy a ponerme de acuerdo con @m471c4 para revisar los iconos y estandarizar-los.

**Comment by Luis-Fernando-Molina** [comment]
:+1:

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina @m471c4  no estaba seguro si crear un caso para subir y comparar todos los logos que estamos trabajando para Fermat.org, pero en esta oportunidad voy a subir aquí todos los logos que he trabajado en cada uno de los casos, para poder comparar que estén todos estandarizados.
![fermat_cdn](https://cloud.githubusercontent.com/assets/13594347/9556933/f55282aa-4da1-11e5-8815-811750b5f14c.png)
![fermat_cry](https://cloud.githubusercontent.com/assets/13594347/9556934/f5558e6e-4da1-11e5-947e-1de326a9447a.png)
![fermat_dmp](https://cloud.githubusercontent.com/assets/13594347/9556935/f55b3526-4da1-11e5-9f10-d5b82699545f.png)
![fermat_p2p](https://cloud.githubusercontent.com/assets/13594347/9556936/f56459ee-4da1-11e5-9a21-b7663573f92b.png)
![fermat_pip](https://cloud.githubusercontent.com/assets/13594347/9556937/f5668d9a-4da1-11e5-9720-7081e1a5220a.png)
![fermat-bnc](https://cloud.githubusercontent.com/assets/13594347/9556938/f57f8cc8-4da1-11e5-8827-e70ce96592f5.png)
![fermat-dpn](https://cloud.githubusercontent.com/assets/13594347/9556939/f58809c0-4da1-11e5-8964-3bb515731cd5.png)

**Comment by Miguelcldn** [comment]
Luego de su aprobación me gustaría que hicieras un comentario igual con las imágenes en formato png fondo transparente sin margen a 375x119 (o uno un poco mayor pero para web) para ponerlas en fermat.org como cabeceras de las filas y columnas (pasate por fermat.org si te parece).

:+1:

**Comment by arnaldos** [comment]
@Miguelcldn si perfecto una ves aprobado te genero los PNG que necesites, ya me paso por fermat.org

**Comment by Luis-Fernando-Molina** [comment]
@arnaldos te paso mis comentarios:

1) En P2P hay una billetera naranja que el cierre lo tiene verde, mientras que la misma en esta del color de la wallet.

2) En PIP todos los cierres estan en verde! Vamos a decir que no vamos a tener cierres en verde en ningún lado.

3) La separación de las letras en los códigos de 3 letras no puede ser variable. Debe se siempre el mismo.

4) La separacion de las letras en la frase debajo de los codigos no puede cambiar de logo a logo, debe ser siempre la misma. El tamaño de la letra tampoco puede variar. Entiendo que con esto no van a coincidir los anchos de los logos, pero aún así debe ser así. Debe usarse la separación estándard de las letras en todos los casos.

**Comment by arnaldos** [comment]
perfecto !!!

**Comment by m471c4** [comment]
@Luis-Fernando-Molina, @arnaldos acá los que tengo listos:

![fermatshp](https://cloud.githubusercontent.com/assets/13468350/9568298/25aef974-4f0f-11e5-914d-cf608515ba83.png)
![fermatmkt](https://cloud.githubusercontent.com/assets/13468350/9568301/3f437e8c-4f0f-11e5-8bf0-d25d5bd6fa40.png)
![fermatcbp2](https://cloud.githubusercontent.com/assets/13468350/9568302/552d4624-4f0f-11e5-9108-a7f3b716624f.png)

Versión PROVISIONAL para Fermat OSA:

![fermatosa](https://cloud.githubusercontent.com/assets/13468350/9568334/57465fd0-4f10-11e5-8131-51216d587aee.png)

**Comment by Luis-Fernando-Molina** [comment]
@m471c4 están en las dimesiones que pidió  @Miguelcldn ?

**Comment by Luis-Fernando-Molina** [comment]
@m471c4 otra cosa, tuvise en cuenta esto:

> 3) La separación de las letras en los códigos de 3 letras no puede ser variable. Debe se siempre el mismo.
> 
> 4) La separacion de las letras en la frase debajo de los codigos no puede cambiar de logo a logo, debe ser siempre la misma. El tamaño de la letra tampoco puede variar. Entiendo que con esto no van a coincidir los anchos de los logos, pero aún así debe ser así. Debe usarse la separación estándard de las letras en todos los casos.

**Comment by m471c4** [comment]
@Luis-Fernando-Molina tienen 2060 de ancho, el tamaño que me solicitó inicialmente, ya las subo a 375x119.

**Comment by m471c4** [comment]
@Luis-Fernando-Molina subiré una imagen para que me lo aclares mejor.

![fermatexpl](https://cloud.githubusercontent.com/assets/13468350/9568391/cb9a9b7a-4f11-11e5-98d7-7c8d008be8d3.png)

¿A cuáles de todas las separaciones te refieres? Yo he usado el mismo interletrado (áreas cian) en todos los códigos de 3 letras. La separación entre la Palabra Fermat y los códigos de 3 letras (área magenta) también ha sido la misma.

**Comment by Luis-Fernando-Molina** [comment]
me refiero al verde. quizás vos usaste el mismo pero Arnaldo no y ese mensaje original era para el. Lo que si veo es que "Marketing Platform" y "Crypto Broker Platform" no tienen el mismo tamaño de letras.

**Comment by m471c4** [comment]
Si, la variación que hice fue en los tamaños, porque la longitud de las palabras varían. Lo ideal es que esos subtítulos mantengan el mismo ancho de los códigos de tres letras. Si queda más largo o más corto haré mucho ruido. Lo que podría hacer es mantener el mismo tamaño y:

a. abrir o cerrar el espaciado entre letras según sea el caso (las áreas verdes variarían de un logo al otro)
b. abrir o cerrar el espaciado entre palabras según sea el caso (las áreas rojas variarían de un loco al otro)

**Comment by Luis-Fernando-Molina** [comment]
Por ahora vamos a hacerlo con el mismo espaciado para todos, el mismo tamaño de letra para todos mas allá de que quede mas corto o mas largo que el código de tres letras.

**Comment by m471c4** [comment]
Está bien. Entonces los subiré así, dame un momento.

**Comment by m471c4** [comment]
@Luis-Fernando-Molina @Miguelcldn @arnaldos adjunto las imagenes a 375 de ancho (los altos son variables, ya que no todos los logos tienen el mismo ancho) con los ajustes en la tipografía y sin bordes.

![osa_peqsb](https://cloud.githubusercontent.com/assets/13468350/9569149/6762c80c-4f2b-11e5-8c35-2e5e9438d71d.png)
![shp_peqsb](https://cloud.githubusercontent.com/assets/13468350/9569150/6804b86a-4f2b-11e5-8aca-9719673d947f.png)
![cbp_peqsb](https://cloud.githubusercontent.com/assets/13468350/9569151/69028152-4f2b-11e5-9eb8-50e39ca9a35b.png)
![mkt_peqsb](https://cloud.githubusercontent.com/assets/13468350/9569152/699d92e6-4f2b-11e5-9f2c-e4ad459da4ed.png)

**Comment by Luis-Fernando-Molina** [comment]
@Miguelcldn intuyo que vamos a tener muchos problemas si manejamos todo esto como bitmaps, sobre todo por la posibiidad de hacer zoom in y zoom out. Porque no lo manejamos directamente en vectores? 

Que necesitas para poder hacer eso asi?

**Comment by Luis-Fernando-Molina** [comment]
@m471c4 Hay un logo que no está planteado ni por vos no por @arnaldos que es el de WPD Wallet Production and Distribution. Sin ese el gráfico de @Miguelcldn va a quedar incompleto. 

Esa parte del sistema es la que se encarga de implementar la fabrica de wallets y la wallet store como puntos fuertes.

Quien lo toma?

**Comment by m471c4** [comment]
Faltaría ese y el de Fermat DAP, en el cual estoy trabajando. Lo puedo tomar yo también, ¿ya está creado el caso?

**Comment by Luis-Fernando-Molina** [comment]
> ¿ya está creado el caso?

ni idea.

**Comment by m471c4** [comment]
Ya está creado, es el #75. Hoy subo los bocetos.

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina comparto los Ajustes generales de las tipografías de cada uno de los logos, aquí podemos apreciar que todos poseen el mismo espacio en el interletrado. 
![fermat_bnk](https://cloud.githubusercontent.com/assets/13594347/9584524/4cc8522c-4fdb-11e5-9f2d-81efaab8279d.png)
![fermat_cdn](https://cloud.githubusercontent.com/assets/13594347/9584522/4cbf9880-4fdb-11e5-814d-fe749a9d53c9.png)
![fermat_cry](https://cloud.githubusercontent.com/assets/13594347/9584521/4cbd6e2a-4fdb-11e5-9fc5-7a2c9b15374c.png)
![fermat_dmp](https://cloud.githubusercontent.com/assets/13594347/9584523/4cc1a9a4-4fdb-11e5-8d33-5ab374e10c65.png)
![fermat_dnp](https://cloud.githubusercontent.com/assets/13594347/9584525/4cc8e520-4fdb-11e5-9b70-fd60e174e69b.png)
![fermat_p2p](https://cloud.githubusercontent.com/assets/13594347/9584526/4cccc0aa-4fdb-11e5-82a2-c9de215c7a00.png)
![fermat_pip](https://cloud.githubusercontent.com/assets/13594347/9584527/4ce7c2ce-4fdb-11e5-963d-17f070716238.png)

**Comment by arnaldos** [comment]
Subo Fermat DPN al tamaño correspondiente
![fermat_dnp](https://cloud.githubusercontent.com/assets/13594347/9584591/cc223f74-4fdb-11e5-9fec-8fb23b3b7271.png)

**Comment by Luis-Fernando-Molina** [comment]
ok, ahi vamos bien :+1:

**Comment by arnaldos** [comment]
buenisimo !!

**Comment by m471c4** [comment]
@Luis-Fernando-Molina, @arnaldos ya están todos los logos en los que yo trabajé actualizados y con la paleta de colores nueva en el repositorio. En sus versiones .ai y .svg.

@Miguelcldn por favor asegurate de actualizar los siguientes en Fermat.org: CBP, CCP, COR, DAP, MKT, OSA, SHP, WPD. ¡Gracias!

**Comment by Luis-Fernando-Molina** [comment]
Muy bien

**Comment by arnaldos** [comment]
@Miguelcldn  los siguientes BCH, BNK, BNP, CCM, CDN, DMP, DPN,P2P, PIP. también están en el repo en sus versiones finales, por favor asegúrate de actualizar en Fermat.org. 

gracias por el apoyo.

**Comment by Miguelcldn** [comment]
Excelente, ya subo todas las nuevas versiones
