### ISSUE TITLE
 Improve icon back to action bar of the Banking Wallet

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#820]
Reference

![banking wallet2-06](https://cloud.githubusercontent.com/assets/13594347/15221067/b296e4ee-1833-11e6-86a7-4db53ea933d9.jpg)

**Comment by isahq23** [comment]
@arnaldos Creo que el problema está en el triángulo como tal. Tal vez es muy pronunciado, fíjate que las 2 primeras propuestas que te paso las saqué de la flecha que ya tenía.

![arrow_m1](https://cloud.githubusercontent.com/assets/15214774/15225098/8ac9a272-1846-11e6-8452-bdd9aa2249ac.jpg)

**Comment by arnaldos** [comment]
versión 3 isa

**Comment by arnaldos** [comment]
@abicelis  esto esta listo ??

**Comment by abicelis** [comment]
Yes @arnaldos

**Comment by arnaldos** [comment]
ok cierro esto !
