### ISSUE TITLE
SUPER ISSUE: Design icons for map markers for every type

### ISSUE THREAD

**Issue by Miguelcldn** [bitDubai/fermat-graphic-design#822]
At lab.bitdubai.com/treant (alpha site) is being developed a map where users can see the actors, network nodes and network clients.

![Google Maps Anchor](https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/174-free-google-maps-pointer.png/286px-174-free-google-maps-pointer.png)

This is the default Google Maps marker. We want to develop a series of special markers for every type we want to show on it, including network nodes, network clients and different actor types.

Each marker will be referenced to this issue in order to close this super issue when the smaller ones are closed.

For all those markers we want a transparent background. The format (.svg or .png) will be decided later when some test are completed.

To clarify, an Actor is an account you create for using each platform, meaning that you could have a name for Chatting, and several names for Dating if you want.

**Comment by Miguelcldn** [comment]
The final product of the design will be a .svg format file.

All markers must be designed in the same size because they all will be scaled equally. @emmysm please comment here the dimension when all designer approve the dimensions.

**Comment by emmysm** [comment]
![markers](https://cloud.githubusercontent.com/assets/15143489/15605359/43b70a3e-23cf-11e6-8cd5-81865a85b4b6.png)

@Miguelcldn

**Comment by arnaldos** [comment]
@emmysm estan completas las apps ??

**Comment by Miguelcldn** [comment]
sólo falta una no tan importante https://github.com/Fermat-ORG/fermat-graphic-design/issues/835

**Comment by arnaldos** [comment]
@Miguelcldn perfecto !!
