### ISSUE TITLE
Network Node marker

### ISSUE THREAD

**Issue by Miguelcldn** [bitDubai/fermat-graphic-design#823]
Network nodes are devices that works as a server interconnecting clients between each other. So the marker should show a specie of server or another icon that share the idea of what's its function.

_Note:_ Its design should be similar to the Clients design #824

Part of #822

**Comment by arnaldos** [comment]
@Joseangel2v @Miguelcldn @emmysm Ver comentario #832

**Comment by GustavoDeMoura** [comment]
This is my version of the server marker with other colors!

@arnaldos @emmysm @Miguelcldn 

![servermarker-01](https://cloud.githubusercontent.com/assets/19398432/15597845/4efafc2a-23a2-11e6-8002-e6bedd01cb86.png)
