### ISSUE TITLE
Network Client marker

### ISSUE THREAD

**Issue by Miguelcldn** [bitDubai/fermat-graphic-design#824]
A Network Client is a user of the network, currently, Fermat is developer only for the Android platform, so a smartphone would be our best option for its design.

_Note:_ Its design should be similar to the Nodes design #823

Part of #822

**Comment by arnaldos** [comment]
@Joseangel2v @Miguelcldn @emmysm Ver comentario #832

**Comment by GustavoDeMoura** [comment]
This is my versions of the Phone marker with other colors!
I think the first version is more accurate!

Version 1
![phone2marker-01](https://cloud.githubusercontent.com/assets/19398432/15597914/0c4a9498-23a3-11e6-9dea-2d278eac2221.png)

Version2
![phocemarker-01](https://cloud.githubusercontent.com/assets/19398432/15597922/19d622e4-23a3-11e6-81ed-5ac62c5856d3.png)

@arnaldos @emmysm @Miguelcldn
