### ISSUE TITLE
Chat actor marker

### ISSUE THREAD

**Issue by Miguelcldn** [bitDubai/fermat-graphic-design#825]
Marker used to show Chat platform users

Part of #822

**Comment by Joseangel2v** [comment]
![propuesta 1](https://cloud.githubusercontent.com/assets/17457499/15414648/7951e0ca-1e06-11e6-95e6-b68c764f4217.png)

**Comment by Joseangel2v** [comment]
![propuesta 11](https://cloud.githubusercontent.com/assets/17457499/15444988/9c2708c6-1ec1-11e6-848f-1f0022ad3289.png)

**Comment by Joseangel2v** [comment]
@emmysm

**Comment by emmysm** [comment]
Propuesta 3 @Joseangel2v @Miguelcldn

**Comment by Miguelcldn** [comment]
De acuerdo con @emmysm

**Comment by arnaldos** [comment]
@Joseangel2v @Miguelcldn @emmysm Ver comentario #832
