### ISSUE TITLE
Redeem point actor marker

### ISSUE THREAD

**Issue by Miguelcldn** [bitDubai/fermat-graphic-design#826]
Marker used to show redeem point platform users

Part of #822

**Comment by Joseangel2v** [comment]
![r](https://cloud.githubusercontent.com/assets/17457499/15586238/19ed7c6a-234d-11e6-8ca5-536da7d4a9f1.png)

**Comment by Joseangel2v** [comment]
@emmysm

**Comment by emmysm** [comment]
Invierte los colores,  a ver qué tal queda, porfa @Joseangel2v

**Comment by Miguelcldn** [comment]
A mi me gusta la segunda

**Comment by emmysm** [comment]
A mí igual, pero me gustaría ver el otro color @Miguelcldn  :sweat_smile:

**Comment by Joseangel2v** [comment]
![r2](https://cloud.githubusercontent.com/assets/17457499/15586628/3e5d3188-234f-11e6-9291-892e0c9b3893.png)

**Comment by emmysm** [comment]
La segunda de las primeras propuestas @Joseangel2v

**Comment by arnaldos** [comment]
@Joseangel2v @Miguelcldn @emmysm Ver comentario #832
