### ISSUE TITLE
Crypto Broker actor marker

### ISSUE THREAD

**Issue by Miguelcldn** [bitDubai/fermat-graphic-design#827]
Marker used to show Crypto Brokers

Design should be related with #828

Part of #822

**Comment by Joseangel2v** [comment]
![propuesta 5](https://cloud.githubusercontent.com/assets/17457499/15415535/fecf2b08-1e0c-11e6-8b28-3be740dbe24c.png)

**Comment by Miguelcldn** [comment]
Podría ver el tamaño de la 3 en la silueta de la 4? para darle más protagonismo al logo, pero manteniendo la forma de la 4

**Comment by Joseangel2v** [comment]
![propuesta 7](https://cloud.githubusercontent.com/assets/17457499/15436271/d7cca250-1e8a-11e6-8ec3-3d95d277cc9c.png)

**Comment by Miguelcldn** [comment]
Me gusta la propuesta 2, @emmysm actualiza las que tu tienes a parecerse a esa y @Joseangel2v aplica ese diseño a las demás

**Comment by emmysm** [comment]
Perfecto @Miguelcldn n_n

**Comment by Joseangel2v** [comment]
![propuesta 8](https://cloud.githubusercontent.com/assets/17457499/15444864/952c7dc8-1ebf-11e6-9c6a-6e34126d10ae.png)

**Comment by Joseangel2v** [comment]
@emmysm

**Comment by emmysm** [comment]
Propuesta 3 @Miguelcldn @Joseangel2v

**Comment by Miguelcldn** [comment]
De acuerdo con @emmysm

**Comment by arnaldos** [comment]
@Joseangel2v @Miguelcldn @emmysm Ver comentario #832
