### ISSUE TITLE
Crypto Customer actor marker

### ISSUE THREAD

**Issue by Miguelcldn** [bitDubai/fermat-graphic-design#828]
Marker used to show Crypto Costumers

Design should be related with #827 

Part of #822

**Comment by emmysm** [comment]
![5-03](https://cloud.githubusercontent.com/assets/15143489/15410026/6b9b503a-1de1-11e6-906f-12cdf4e70e3d.png)

@Miguelcldn

**Comment by Miguelcldn** [comment]
Haz una versión como la propuesta 4 de aquí a ver cómo queda https://github.com/Fermat-ORG/fermat-graphic-design/issues/827#issuecomment-220503363

**Comment by Joseangel2v** [comment]
![sin titulo-3](https://cloud.githubusercontent.com/assets/17457499/15557454/de4d5618-229c-11e6-9bfb-38bd199454a8.jpg)

**Comment by emmysm** [comment]
Me gusta la propuesta 2 @Joseangel2v. Qué opinas, @Miguelcldn ?

**Comment by Miguelcldn** [comment]
Esas líneas blancas que están en estas propuestas y no en las anteriores.. son partes del logo? Para verlo sin esas líneas

**Comment by emmysm** [comment]
Sí, esas son las costuras de la wallet, son parte del icono @Miguelcldn. Pero si se pierden se las podemos quitar

**Comment by Miguelcldn** [comment]
Jajajaja ah ok, bueno, que se queden, me gusta la propuesta 2 :+1:

**Comment by arnaldos** [comment]
@Miguelcldn @emmysm Ver comentario #832.
Por favor revisar las costuras, ya que creo no son las del logo. 
No se les puede quitar las costuras porque son parte del logo, (se que al reducirse se van a perder pero tienen que estar en el)
