### ISSUE TITLE
Asset Issuer marker

### ISSUE THREAD

**Issue by Miguelcldn** [bitDubai/fermat-graphic-design#829]
Marker used to show Asset issuers

Design should be related to #830 

Part of #822

**Comment by emmysm** [comment]
![4-02](https://cloud.githubusercontent.com/assets/15143489/15381338/a35a6248-1d48-11e6-81e2-5379f8b57bef.png)

@Miguelcldn

**Comment by Miguelcldn** [comment]
Haz una versión como la propuesta 4 de aquí a ver cómo queda https://github.com/Fermat-ORG/fermat-graphic-design/issues/827#issuecomment-220503363

**Comment by Joseangel2v** [comment]
![sin titulo-2](https://cloud.githubusercontent.com/assets/17457499/15557451/d949171a-229c-11e6-98f9-e5faaee740c9.jpg)

**Comment by emmysm** [comment]
La propuesta 3 @Joseangel2v @Miguelcldn

**Comment by arnaldos** [comment]
@Miguelcldn @emmysm Ver comentario #832
