### ISSUE TITLE
Crear un Logo para Fermat COR (Core And Api)

### ISSUE THREAD

**Issue by m471c4** [bitDubai/fermat-graphic-design#83]
Este se puede asociar a la idea de un corazón, ya se trata del núcleo de la aplicación.

**Comment by Luis-Fernando-Molina** [comment]
CORE en algunos casos se lo asocia con el centro de la tierra o con el nucleo de un atomo.

**Comment by m471c4** [comment]
Muy bien, usaré ese concepto entonces.

**Comment by m471c4** [comment]
@Luis-Fernando-Molina primeros bocetos para Fermat COR

![fermatcor](https://cloud.githubusercontent.com/assets/13468350/9617514/08ffc290-50cc-11e5-8e3a-c4d1e7889355.png)
![fermatcor2](https://cloud.githubusercontent.com/assets/13468350/9617702/72308f92-50cc-11e5-8a2d-d3cca23341ee.png)

**Comment by Luis-Fernando-Molina** [comment]
1) vamos con el segundo
2) los electrones debieran estar igual que el rojo, en la parte mas exterior de cada elipse
3) probemos con dos electrones por elipse. 
4) hace una prueba donde los electrones sean las billeteras chiquitas con los 3 colores que tenemos
5) "Core & Api"

**Comment by m471c4** [comment]
@Luis-Fernando-Molina puse Core & API (todo en mayúscula) porque ya en OSA está así. Acá está con los cambios que me pediste:

![fermatcor3](https://cloud.githubusercontent.com/assets/13468350/9626704/45970594-5129-11e5-901f-d993ba209832.png)
![fermatcor4](https://cloud.githubusercontent.com/assets/13468350/9626705/45a255d4-5129-11e5-9b08-f0701880cd9c.png)

**Comment by Luis-Fernando-Molina** [comment]
ok, las billeteras quedan mejor, proba poner el cierre hacia adentro y fijate si pueden ser un poquito mas grandes (sin que toquen las orbitas vecinas)

El corazon pudiera ser mas chico, un poquito.

**Comment by leonacostaok** [comment]
Creo que queda muy cargado con tantas billeteras y más si son grandes.. Me pareció copada la idea de que sean impares, o sea, mientras este balanceado, no tiene que ser simétrico. ¿Qué te parece @Luis-Fernando-Molina ?

**Comment by m471c4** [comment]
@Luis-Fernando-Molina acá con los cambios que me pediste:

![fermatcor6](https://cloud.githubusercontent.com/assets/13468350/9651713/f83deeb0-51dd-11e5-9d50-36c552c77069.png)

Acá con la sugerencia de @lnacosta:

![fermatcor7](https://cloud.githubusercontent.com/assets/13468350/9651754/7a4fe8fe-51de-11e5-8573-9384f6021225.png)

**Comment by Luis-Fernando-Molina** [comment]
Proba cambiar el corazón por la billetera verde en uno de sus tamaños estandares

**Comment by m471c4** [comment]
@Luis-Fernando-Molina 

![fermatcor8](https://cloud.githubusercontent.com/assets/13468350/9653175/5b513810-51eb-11e5-99a1-70ef007847ca.png)

**Comment by Luis-Fernando-Molina** [comment]
Ok, va bien, ahora un poco de trigonometria:

fijate en esta imagen : http://www.iconshock.com/img_jpg/BRILLIANT/database/jpg/256/atom_icon.jpg

El angulo que hay entre las orbitas es constante, en el nuestro no. Inclusive podes hacer las elipses un poquito mas chatas, están muy gorditas.

**Comment by Luis-Fernando-Molina** [comment]
Muy buena la pagina de iconos :+1:

**Comment by m471c4** [comment]
@Luis-Fernando-Molina con los cambios que me pediste. Hice las elipses un poco más delgadas, peor no tanto como el referente que me pasaste, para que la cartera del centro pudiera estar un poco más grande. Dime qué te parecen.

Creo que queda mucho mejor.

![fermatcor9](https://cloud.githubusercontent.com/assets/13468350/9668396/11d5d9ce-524b-11e5-9372-2f0c23f991ad.png)

**Comment by Luis-Fernando-Molina** [comment]
@m471c4 ok las elipses estab bien, me gustaría probar rotando las billeteras chiquitas de nuevo para ver cual queda mejor, gracias.

**Comment by m471c4** [comment]
@Luis-Fernando-Molina ¿rotarlas cómo? ¿que los broches queden hace afuera?

**Comment by Luis-Fernando-Molina** [comment]
si

**Comment by m471c4** [comment]
@Luis-Fernando-Molina 

![fermatcor10](https://cloud.githubusercontent.com/assets/13468350/9672134/bca83980-5261-11e5-8ef7-fed3bedd658c.png)

**Comment by Luis-Fernando-Molina** [comment]
Ok, aprobado este :+1:  cuando se ponga en fermat.org cerra el caso.

**Comment by m471c4** [comment]
@Miguelcldn el logo de Fermat COR ya está en el repositorio. Puedes ponerlo en Fermat.org.
