### ISSUE TITLE
Asset User marker

### ISSUE THREAD

**Issue by Miguelcldn** [bitDubai/fermat-graphic-design#830]
Marker used to show Asset users

Design should be related with #829 

Part of #822

**Comment by Joseangel2v** [comment]
![propuesta 2](https://cloud.githubusercontent.com/assets/17457499/15415297/84ae260e-1e0b-11e6-8dad-e48c763c04eb.png)

**Comment by Joseangel2v** [comment]
![propuesta 10](https://cloud.githubusercontent.com/assets/17457499/15444984/9648b8aa-1ec1-11e6-8bb7-6677a531f941.png)

**Comment by Joseangel2v** [comment]
@emmysm

**Comment by emmysm** [comment]
Propuesta 1 @Joseangel2v

**Comment by Miguelcldn** [comment]
De acuerdo con @emmysm

**Comment by arnaldos** [comment]
@Miguelcldn @emmysm Ver comentario #832
