### ISSUE TITLE
Artist marker

### ISSUE THREAD

**Issue by Miguelcldn** [bitDubai/fermat-graphic-design#831]
Marker used to show Artists

Design should be related to #832 (but I'm not pretty sure, this one is not enforced)
Part of #822

**Comment by Joseangel2v** [comment]
![propuesta 3](https://cloud.githubusercontent.com/assets/17457499/15415501/d9d1b154-1e0c-11e6-8fb8-14cbc9fe5e03.png)

**Comment by Joseangel2v** [comment]
![propuesta 9](https://cloud.githubusercontent.com/assets/17457499/15444982/90ac9d62-1ec1-11e6-8bbb-b2e7e1225402.png)

**Comment by Joseangel2v** [comment]
@emmysm

**Comment by emmysm** [comment]
La primera propuesta @Joseangel2v 
@Miguelcldn

**Comment by Miguelcldn** [comment]
De acuerdo con @emmysm

**Comment by arnaldos** [comment]
@emmysm La primera propuesta de cual seria? Me gusta la primera versión de la segunda serie, 
Recuerda estandarizar los marker, para que todos, no tengan formas diferentes.

**Comment by Miguelcldn** [comment]
@arnaldos nos referimos a esa misma, la primera versión de la segunda serie, aunque tu comentario contradice lo comentado en https://github.com/Fermat-ORG/fermat-graphic-design/issues/832#issuecomment-221986715, por ser ese comentario más nuevo prevalece?
