### ISSUE TITLE
Fan marker

### ISSUE THREAD

**Issue by Miguelcldn** [bitDubai/fermat-graphic-design#832]
Marker used to show Fans

Design should be related to #831 (but I'm not pretty sure, this one is not enforced)

Part of #822

**Comment by emmysm** [comment]
![1-01](https://cloud.githubusercontent.com/assets/15143489/15381195/39298936-1d47-11e6-8bbc-d9da543bddab.png)

@Miguelcldn

**Comment by Miguelcldn** [comment]
Haz una versión como la propuesta 4 de aquí a ver cómo queda https://github.com/Fermat-ORG/fermat-graphic-design/issues/827#issuecomment-220503363

**Comment by Joseangel2v** [comment]
![sin titulo-1](https://cloud.githubusercontent.com/assets/17457499/15557499/2323ee3c-229d-11e6-83ab-d9c317358960.jpg)

**Comment by emmysm** [comment]
Me gusta la propuesta 1, @Joseangel2v  qué opinas @Miguelcldn?

**Comment by Miguelcldn** [comment]
Concuerdo contigo @emmysm

**Comment by Miguelcldn** [comment]
![image](https://cloud.githubusercontent.com/assets/5544266/15588477/1aeb8486-235c-11e6-85b0-71e979a99a08.png)

Este marcador tiene problemas con respecto a los colores de Google Maps, @emmysm puedes proveerme el de la propuesta 3?

**Comment by arnaldos** [comment]
@emmysm @Miguelcldn @Joseangel2v Este icono no es el de la Fan Wallet, es Music Player.

**Comment by arnaldos** [comment]
@emmysm @Joseangel2v Estandariza los market con la versión 3 de la primera serie, agregándole a cada uno los colores e iconos que los caracteriza.
