### ISSUE TITLE
Generic Marker

### ISSUE THREAD

**Issue by Miguelcldn** [bitDubai/fermat-graphic-design#835]
This marker is going to be used if the actor has no marker defined, its icon should be a person icon, as the ones we saw on Messenger back in our time [grabs hard his ID card].

Part of #822

**Comment by arnaldos** [comment]
@Joseangel2v @Miguelcldn @emmysm Ver comentario #832

**Comment by Miguelcldn** [comment]
Puede ser como el de client y node pero con una personita como logo

**Comment by Joseangel2v** [comment]
P-1
![m1](https://cloud.githubusercontent.com/assets/17457499/15688012/d34af91a-2741-11e6-95b0-d10208bfafcd.png)

**Comment by Joseangel2v** [comment]
P-2
![m2](https://cloud.githubusercontent.com/assets/17457499/15688023/da188a28-2741-11e6-8416-1e9d4d31ec3c.png)

**Comment by Joseangel2v** [comment]
P-3
![m3](https://cloud.githubusercontent.com/assets/17457499/15688029/e329f6c4-2741-11e6-871d-bee4865c883b.png)

**Comment by Joseangel2v** [comment]
P-4
![m6](https://cloud.githubusercontent.com/assets/17457499/15688033/ea18e756-2741-11e6-899b-ffd5890881a5.png)

**Comment by Joseangel2v** [comment]
P-5
![4m](https://cloud.githubusercontent.com/assets/17457499/15688044/f17ae210-2741-11e6-91c0-90abc1518609.png)

**Comment by Joseangel2v** [comment]
P-6
![5m](https://cloud.githubusercontent.com/assets/17457499/15688059/000a9f82-2742-11e6-9649-4b7db5bb5264.png)

**Comment by Joseangel2v** [comment]
P-7
![7m](https://cloud.githubusercontent.com/assets/17457499/15688068/0a9d4ef4-2742-11e6-8d01-69f6c0cf4ea3.png)

**Comment by Joseangel2v** [comment]
P-8
![8m](https://cloud.githubusercontent.com/assets/17457499/15688079/139af088-2742-11e6-8641-2ca4e287fadb.png)

**Comment by Joseangel2v** [comment]
@emmysm

**Comment by emmysm** [comment]
@Joseangel2v  me gustan las propuestas 6, 7 y 8. Qué opinas tú @Miguelcldn?

**Comment by Miguelcldn** [comment]
Yo digo **P-7**

**Comment by emmysm** [comment]
Envíame los recursos, @Joseangel2v, por favor :)
