### ISSUE TITLE
graphic-infographies_blockchain

### ISSUE THREAD

**Issue by ivonnesantos** [bitDubai/fermat-graphic-design#838]
Created a graph that represent the division cellular, focused on project fermat.

**Comment by ivonnesantos** [comment]
propuesta_1
![blockchain_1-01](https://cloud.githubusercontent.com/assets/15238660/15485953/2866c0d2-210c-11e6-8fcc-efd047c19f79.png)

Propuesta_2
![blockchain_1-02](https://cloud.githubusercontent.com/assets/15238660/15485958/2e0da122-210c-11e6-98f0-1c1cb131493d.png)

@Luis-Fernando-Molina @arnaldos

**Comment by Luis-Fernando-Molina** [comment]
Va por el lado de la propuesta 1
1. Titulo : Fermat Blockchain
2. Los puntitos azules hacelos mas chiquitos, separados a una distancia constante, y de vez en cuando ponele un puntito de otro color de los que usamos aca en estos graficos.
3. La primera cadena tiene que empezar desde donde las lineas se cruzan
4. el inicio de las otras cadenas puede quedar asi.
5. la tercera generacion que tiene 2 pares, hace que cada par comience en momentos diferentes.
6. Pone todo el grafico de manera horizontal en vez de vertical como esta ahora.

**Comment by ivonnesantos** [comment]
![blockchain_1-01](https://cloud.githubusercontent.com/assets/15238660/15505360/fb67cbe0-218c-11e6-9051-88cb548859fd.png)
hola @Luis-Fernando-Molina aca estan las correcciones espero haber entendido bien todas tus observaciones =)

**Comment by Luis-Fernando-Molina** [comment]
1. Mas puntos en las lineas
2. Tiene que ser mas larga, mas pega del titulo, mas eslabones por cadenas

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina adjunto los cambios solicitados 

Ajuste versión 1

![blockchain_2](https://cloud.githubusercontent.com/assets/13594347/15545072/d5cd5016-2264-11e6-970d-9ac5cf6d19f5.png)

**Comment by arnaldos** [comment]
Ajuste versión 2
![blockchain_3](https://cloud.githubusercontent.com/assets/13594347/15545514/5a393e54-2266-11e6-912c-20c635a8db27.jpg)

**Comment by ivonnesantos** [comment]
@Luis-Fernando-Molina Ajuste de version 3
![blockchain_1-01](https://cloud.githubusercontent.com/assets/15238660/15546496/f7dd6682-2269-11e6-8098-533c3d3bfb7a.png)

**Comment by Luis-Fernando-Molina** [comment]
Vamos con la ultima version de Ivonne

**Comment by Luis-Fernando-Molina** [comment]
Pero necesito que las bolitas esten en toda la linea no solo en los eslabones cerrados.

**Comment by ivonnesantos** [comment]
@Luis-Fernando-Molina 
![blockchain_1-01](https://cloud.githubusercontent.com/assets/15238660/15550838/1159e05a-227d-11e6-8692-f90047f53687.png)

**Comment by Luis-Fernando-Molina** [comment]
sacale  el ultimo nivel y hace cada cadena de mas eslabones por favor.

**Comment by ivonnesantos** [comment]
![blockchain_3-01](https://cloud.githubusercontent.com/assets/15238660/15557850/76135c70-229f-11e6-8c0e-819061a620b2.png)
@Luis-Fernando-Molina

**Comment by Luis-Fernando-Molina** [comment]
1. no me entendiste lo de que cada cadena tenga mas eslabones. Las cadenas no son verticales, son las horizontales.
2. En el ultimo nivel la duplicacion esta mal.

**Comment by ivonnesantos** [comment]
Volvi a la propuesta anterior e hice otra interpretacion de tus correcciones porque al parecer no lo entendi @Luis-Fernando-Molina 
![blockchain_4-01](https://cloud.githubusercontent.com/assets/15238660/15581481/52f6fe1c-2336-11e6-8355-7bc102c24267.png)

**Comment by Luis-Fernando-Molina** [comment]
El último nivel de abajo a la derecha no está bien porque se crea una línea de la nada. 

El ultimo nivel también parece que hay dos cadenas que se fusionan eso no esta bien

**Comment by ivonnesantos** [comment]
Alternativa_1
![blockchain_5-01](https://cloud.githubusercontent.com/assets/15238660/15619704/b6a1483e-241f-11e6-9b88-3501be1b17c8.png)
Alternativa_2
![blockchain_6-01](https://cloud.githubusercontent.com/assets/15238660/15619708/b932053e-241f-11e6-9432-e96eed6fe588.png)

@Luis-Fernando-Molina

**Comment by Luis-Fernando-Molina** [comment]
Los puntitos rojos dejalos solo para el momento que se separan.

**Comment by Luis-Fernando-Molina** [comment]
Alternative 2

**Comment by ivonnesantos** [comment]
![blockchain_6-01](https://cloud.githubusercontent.com/assets/15238660/15628094/44d45748-24c2-11e6-9eb5-8051dd31ebba.png)

@Luis-Fernando-Molina

**Comment by Luis-Fernando-Molina** [comment]
Perdon me equivoque, quice decir alternativa 1

**Comment by ivonnesantos** [comment]
![blockchain_5-01](https://cloud.githubusercontent.com/assets/15238660/15636065/1978a30a-25bd-11e6-96ed-6ffcc04939dd.png)

@Luis-Fernando-Molina

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina los ajustes solicitados 

Version 11
![blockchain_ar](https://cloud.githubusercontent.com/assets/13594347/15636712/c563587c-25d1-11e6-971f-cbfc8d527b72.png)

**Comment by Luis-Fernando-Molina** [comment]
Perfecto ahi quedo bien. Gracias!
