### ISSUE TITLE
Crear un Logo para Fermat CCP (Crypto Currency Platform)

### ISSUE THREAD

**Issue by m471c4** [bitDubai/fermat-graphic-design#84]
Es la parte de la plataforma que se encarga de manejar dinero en crypto currency. Se puede asociar a la idea de una crypto moneda genérica.

**Comment by m471c4** [comment]
@Miguelcldn en el repositorio hay una versión provisional para este logo. Por ffavor súbela y luego lo actualizamos. Gracias.

**Comment by Miguelcldn** [comment]
Ok, chévere :+1:

**Comment by m471c4** [comment]
@Luis-Fernando-Molina primer boceto para Fermat CCP:

![fermatccp](https://cloud.githubusercontent.com/assets/13468350/9678096/3eb4c9cc-52ab-11e5-9712-52b3d0ebee06.png)

**Comment by Luis-Fernando-Molina** [comment]
Proba con la billetera verde en grande (como la locomotora de un tren) y las chiquitas como vagones , pero unidas por la cadena que usamos en otros logos.

**Comment by m471c4** [comment]
@Luis-Fernando-Molina ¿algo así?

![fermatccp2](https://cloud.githubusercontent.com/assets/13468350/9711339/adda8af4-550c-11e5-8e61-006ddb60e8b8.png)

**Comment by Luis-Fernando-Molina** [comment]
Bien,  en vez de las ruedas pone una cadena continúa por favor

**Comment by m471c4** [comment]
@Luis-Fernando-Molina pondré la cadena entonces. Entre los vagones, ¿quieres que mantenga esos eslabones o pongo una línea recta?

**Comment by Luis-Fernando-Molina** [comment]
Probemos las dos formas

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina acá con los cambios sugeridos. No puse la cadena completa ya que queda demasiado cargada y hace mucho peso. mensaje de @m471c4 

![img-20150908-wa0002](https://cloud.githubusercontent.com/assets/13594347/9745487/fdd998c6-563b-11e5-894c-a95d55ef29d1.jpg)

**Comment by Luis-Fernando-Molina** [comment]
OK lo dejemos así.

**Comment by arnaldos** [comment]
esta si es la versión  ![img-20150908-wa0005](https://cloud.githubusercontent.com/assets/13594347/9746535/48709942-5642-11e5-8658-e7bac267c564.jpg)
