### ISSUE TITLE
Create Logo for P2P Classifieds App

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#840]
A person wants to sell a tangible object and publishes it in a portal. Another person is looking for a product, finds it and buys it online. The product need to be delivered.

**Comment by GustavoDeMoura** [comment]
These are the two proposal for the Classifieds app! one for dark interface and one for light color interface. I took the liberty to put a name to the app "CLASSIFINDER" i dont know if you have already a name but either way i give you this name to use. 

The images are 2 for the logos and 2 for the APP icon also for the different option, dark or ligh color

Let me know  if you have anything to say or change about this

![logo1classifinder](https://cloud.githubusercontent.com/assets/19398432/15517987/a4dabb8e-21c8-11e6-8eb0-ef673fd1bf8d.png)
![logo2classifinder](https://cloud.githubusercontent.com/assets/19398432/15517989/a4dd2b94-21c8-11e6-8b64-0b11259e8214.png)
![logo2classifinderapp](https://cloud.githubusercontent.com/assets/19398432/15517988/a4dc2424-21c8-11e6-8c20-32dc77b2b056.png)
![logoclassifinderapp](https://cloud.githubusercontent.com/assets/19398432/15517990/a4e0c65a-21c8-11e6-821a-10e72e4af649.png)

**Comment by arnaldos** [comment]
@gabymado look this !!! I like the icon because it is like a look, and it works when people want to find some object.

**Comment by gabymado** [comment]
@GustavoDeMoura @arnaldos Hi! And sorry for the late reply. I find it a bit agressive, it reminds me of war and weapons :/ Maybe you could take it a different way but remaining with the approach of "finding" what you need. Maybe using something similar to a magnifying glass?

Another way to go could be a more social approach, like the Mercado Libre logo, for example.

Hope this helps!

**Comment by GustavoDeMoura** [comment]
Here's another logo for the App of Classifieds, going more to the approach previously said!
3 propousal of the logo! all with the same base! Finding stuff's. the color is my idea! dont have to be that color.

![propunuevaclassifieds](https://cloud.githubusercontent.com/assets/19398432/15661779/443f2b4a-26c1-11e6-926a-c5ef23b16343.jpg)

Let me know if this is what we looking for, i'll keep working in the other things fot the apps to be deliver tomorrow @arnaldos @gabymado

**Comment by arnaldos** [comment]
most better i like it, the concept is realy good, that´s works. I prefer proposal 1 or 3. @GustavoDeMoura plz put the text "Classifieds" with the icon.

@gabymado What doyou think about?

**Comment by emmysm** [comment]
![sin titulo-2](https://cloud.githubusercontent.com/assets/15143489/15662920/f9e012d2-26be-11e6-867c-f826aa7c8c52.png)

proposal @arnaldos @gabymado

**Comment by GustavoDeMoura** [comment]
All three with the word Classified, i like de logo 1 and 3 also! @arnaldos @gabymado 

![propunuevaclassifieds2-01](https://cloud.githubusercontent.com/assets/19398432/15662946/d501334e-26cb-11e6-858f-b58ddb6f5d4f.jpg)

**Comment by gabymado** [comment]
They're much better. I really liked @emmysm proposal as it is a little bit more abstract and the C letter really works there. I would work on that direction. @GustavoDeMoura's designs look more modern so I would play with that also, combining the proposals that way. What do you think @arnaldos? 

Also, do all logos have to have the app's name included? If so, make sure to add it in a coherent way @emmysm (I mean matching the "C" of the image).

**Comment by GustavoDeMoura** [comment]
Propuesta 3 Vs2    @arnaldos @gabymado @emmysm 
is this a last minute version.

![propu3classifieds-01](https://cloud.githubusercontent.com/assets/19398432/15663601/1db18420-26d3-11e6-8291-20ac550db47e.jpg)

**Comment by arnaldos** [comment]
@gabymado I talk with @GustavoDeMoura and I talk to him to work with the eyes and form the synthesis of an owl , but I like the idea of ​​unifying the two proposals.

**Comment by arnaldos** [comment]
what do you think about ?

**Comment by gabymado** [comment]
Yes, as I said in my previous comment, I think I see @emmysm's proposal more clear, but maybe adapting what she did to a more modern look, like @GustavoDeMoura's design could work.

**Comment by GustavoDeMoura** [comment]
See this, and tell me what you think @arnaldos @gabymado @emmysm 

A mix between Emmy's logo and mine! 
Ps: the "classified" typography is in that space only for identification purpose only!

![propu3classifieds-02-01](https://cloud.githubusercontent.com/assets/19398432/15696965/e3c85a4a-278b-11e6-8002-a7ae776d1b2f.jpg)

**Comment by gabymado** [comment]
I like it. I'm not sure about the external lines. Maybe a proposal with a different background? A list of products? Always keeping it abstract.

Also, I'd review the font of "CLASSIFIEDS", it's still kind of aggressive and hard.

I think the whole logo should feel friendlier. @arnaldos @GustavoDeMoura @emmysm

**Comment by arnaldos** [comment]
I agree that such a change lines you see , in this case the base icon can work something different, and include within the magnifying glass when it is carried to the desktop app leave no element outside the reticle, with the typography maybe Futura, Avangarde, Neptune.

**Comment by emmysm** [comment]
![classifieds-02](https://cloud.githubusercontent.com/assets/15143489/15726273/be43151a-2819-11e6-9cae-9ede1b926081.png)

@arnaldos @gabymado

**Comment by GustavoDeMoura** [comment]
This are the new version i made for the logo, i think Emmy and I agree in one thing on the aplication of the logo!

i prefer the firt logo, with the magnified glass complete. works better to recognize at first sight.
the font is Futura. 

You decide @arnaldos @gabymado 

![propunuevaclassifieds2-01](https://cloud.githubusercontent.com/assets/19398432/15727055/a59e403c-282a-11e6-9f4a-40538260321e.jpg)

![propunuevaclassifieds3-01](https://cloud.githubusercontent.com/assets/19398432/15727059/acc873aa-282a-11e6-9554-f3d0f7f3a863.jpg)

![propunuevaclassifieds32-01-01](https://cloud.githubusercontent.com/assets/19398432/15727075/c32a1914-282a-11e6-8b16-138255796c44.jpg)

**Comment by gabymado** [comment]
@emmysm me gusta la opción con fondo gris, pero la haría de modo que quede bien en un fondo blanco y que el fondo gris sea simplemente una variante. Qué tal probar incorporando colores cómo el naranja y el amarillo? Para parecerse un poco más a amazon, ebay o mercado libre.

**Comment by emmysm** [comment]
Perfecto @gabymado , ya trabajo en eso

**Comment by emmysm** [comment]
![variacion de colores](https://cloud.githubusercontent.com/assets/15143489/15761760/c6fddfe4-28e3-11e6-8dbd-f2089a0b5299.png)

@arnaldos @gabymado

**Comment by gabymado** [comment]
@emmysm I really like 3c and 2c. @arnaldos?
