### ISSUE TITLE
Create Logo for P2P (Services / Work) Conections App

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#841]
Professionals want to connect and create a work network that can help them learn, get jobs or recruit others.

**Comment by Jessicafp** [comment]
![work connections-03](https://cloud.githubusercontent.com/assets/19536846/15513224/9f14960e-21ad-11e6-93dc-099c30b5c2b0.png)
![work connections-04](https://cloud.githubusercontent.com/assets/19536846/15513225/9f1e5b80-21ad-11e6-8c34-b0fb74cfc0e4.png)
![work connections-05](https://cloud.githubusercontent.com/assets/19536846/15513226/9f211938-21ad-11e6-8eb8-f66fedebc0a9.png)
![work connections-06](https://cloud.githubusercontent.com/assets/19536846/15513227/9f26d620-21ad-11e6-9e84-72a6ca897542.png)
![work connections-07](https://cloud.githubusercontent.com/assets/19536846/15513228/9f2c32b4-21ad-11e6-9215-6eb730895ff6.png)
![work connections-08](https://cloud.githubusercontent.com/assets/19536846/15513229/9f31a046-21ad-11e6-868c-3b51b66bebb5.png)
![work connections-09](https://cloud.githubusercontent.com/assets/19536846/15513231/9f4146ae-21ad-11e6-934e-e2f1b31b8e77.png)
![work connections-10](https://cloud.githubusercontent.com/assets/19536846/15513232/9f4a9592-21ad-11e6-9e74-5a8f0ad85ead.png)
![work connections-11](https://cloud.githubusercontent.com/assets/19536846/15513233/9f4e9070-21ad-11e6-8090-5d153f574ea0.png)
![work connections-12](https://cloud.githubusercontent.com/assets/19536846/15513234/9f54e650-21ad-11e6-88e4-fef44abdc468.png)
![work connections-14](https://cloud.githubusercontent.com/assets/19536846/15513235/9f629548-21ad-11e6-9a5c-e9acf158fabe.png)
![work connections-15](https://cloud.githubusercontent.com/assets/19536846/15513236/9f7cee0c-21ad-11e6-8c52-ee8b5519a108.png)

**Comment by arnaldos** [comment]
@Jessicafp me gusta la versión 4-A, pero genera una propuesta nueva y prueba usar un elemento o síntesis que nos describa que esta enfocado a work.

**Comment by Jessicafp** [comment]
![logos work connections-01](https://cloud.githubusercontent.com/assets/19536846/15520398/f56380ca-21cf-11e6-90e2-edccd929a9d7.png)
![logos work connections-02](https://cloud.githubusercontent.com/assets/19536846/15520399/f5683b6a-21cf-11e6-96be-0a97a9a4294e.png)
![logos work connections-03](https://cloud.githubusercontent.com/assets/19536846/15520400/f56d6838-21cf-11e6-982e-45fc7d973f3b.png)
![logos work connections-04](https://cloud.githubusercontent.com/assets/19536846/15520401/f574d096-21cf-11e6-9efb-0575a67448bf.png)
![logos work connections-05](https://cloud.githubusercontent.com/assets/19536846/15520402/f57a4850-21cf-11e6-84bf-9a01f5a210d0.png)
![logos work connections-06](https://cloud.githubusercontent.com/assets/19536846/15520403/f57f8dec-21cf-11e6-8b1b-655a52d33b49.png)

**Comment by arnaldos** [comment]
nos quedamos con la version 4_ de la primera serie sube los archivos al repo

**Comment by arnaldos** [comment]
subiste los archivos al repo?
