### ISSUE TITLE
graphic-infographies_Android Apps-Fermat Apps

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#842]
Actual proposal by rosana

![fermat app infography propuesta 4-01](https://cloud.githubusercontent.com/assets/13594347/15493504/30be63e2-214e-11e6-8c30-59f865c7cb60.png)

**Comment by arnaldos** [comment]
@jhonmarquez92 Aquí los comentarios para la infografia.

1- El texto del info graphic debe ser en la linea de abajo
Android Apps    Fermat Apps
2- Los colores no pueden salirse de los colores que ya hemos usado
3- Los palitos de android apps hacelos cada uno de un color, sin la cabecita de otro color
4- Las figuras de fermat apps sin el dibujito de las rueditas
5- En android apps hace que todo el espacio este lleno menos un espacio que se va a llanar con la ficha que viene bajando

**Comment by rosanacoronado** [comment]
@arnaldos @jhonmarquez92 @Luis-Fernando-Molina  

Propuesta_1
![new fermat app infography 4-03](https://cloud.githubusercontent.com/assets/19508456/15506679/571d167a-2192-11e6-8b51-8168033b6993.png)

Propuesta_2
![new fermat app infography 5-03](https://cloud.githubusercontent.com/assets/19508456/15506680/57229550-2192-11e6-9856-1cd06d69d907.png)

Propuesta_3
![new fermat app infography 3-03](https://cloud.githubusercontent.com/assets/19508456/15506681/57298a04-2192-11e6-9de1-aad70da800f2.png)

Acá están las nuevas propuestas. Espero haber entendido cada una de las correcciones :)

**Comment by proseuz** [comment]
yo creo que la propuesta 3 se adapta más al estilo que tienen las infografías @arnaldos

**Comment by rosanacoronado** [comment]
@arnaldos @jhonmarquez92 @Luis-Fernando-Molina En base a la propuesta 3 realice nuevas propuestas

Propuesta_1
![fermat app infography nueva 4](https://cloud.githubusercontent.com/assets/19508456/15543252/f7234b6e-225d-11e6-818a-5896c17d2ebd.png)

Propuesta_2
![fermat app infography nueva 1](https://cloud.githubusercontent.com/assets/19508456/15543253/f726b600-225d-11e6-9420-62e4c0d59518.png)

Propuesta_3
![fermat app infography nueva 2](https://cloud.githubusercontent.com/assets/19508456/15543254/f72ce9c6-225d-11e6-99d4-157b47609827.png)

Propuesta_4
![fermat app infography nueva 3](https://cloud.githubusercontent.com/assets/19508456/15543255/f732b310-225d-11e6-98ec-9a0ab856b97c.png)

**Comment by Luis-Fernando-Molina** [comment]
Ok propuesta 4 solo modifica que no sea el primer elemento el que falta en android, sino uno de mas al medio.

**Comment by rosanacoronado** [comment]
@arnaldos @Luis-Fernando-Molina En base a la modificación solicitada esta es la nueva propuesta
![fermat app infography final 2](https://cloud.githubusercontent.com/assets/19508456/15549404/2d3d4264-2276-11e6-95cb-55559911870c.png)

**Comment by Luis-Fernando-Molina** [comment]
ok gracias se puede quedar asi

**Comment by arnaldos** [comment]
esta en el repo !!
