### ISSUE TITLE
Create Interface Fermat Wallet 

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#843]

**Comment by arnaldos** [comment]
@nattyco here the fermat wallet interface, tell me if we need and other funtions 

![wireframe-fermat-wallet2](https://cloud.githubusercontent.com/assets/13594347/15493709/98ea98b8-214f-11e6-8655-a725c8739a94.jpg)

**Comment by furszy** [comment]
@arnaldos sacá la rozca por favor.

**Comment by nattyco** [comment]
@arnaldos La rosca del home donde se muestra al balance

**Comment by arnaldos** [comment]
@nattyco  @furszy  les comparto las propuestas para el balance 
![wireframe-fermat-wallet3](https://cloud.githubusercontent.com/assets/13594347/15525880/6fc5eaca-21f7-11e6-8ea8-d87a0986cd8d.png)

**Comment by arnaldos** [comment]
en la versión 2 el indicador rojo indica un saldo negativo (ultimo retiro) y el verde indica un saldo positivo  (ultimo ingreso)

**Comment by arnaldos** [comment]
hola @nattyco esto esta implementad?  podemos cerrar el caso ?

**Comment by arnaldos** [comment]
o falta algo por definir ?
