### ISSUE TITLE
Create a icon for a Valut for a Fermat Settings 

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#845]
The vault is where you keep the crypto currencie.

Here the view settings

![settings app 8 1-14](https://cloud.githubusercontent.com/assets/13594347/15529369/9bf8cdb4-2216-11e6-8a40-d7a2f792222c.jpg)

**Comment by GustavoDeMoura** [comment]
The vault icons propousal for fermat setting is this! @arnaldos 

![iconovault2](https://cloud.githubusercontent.com/assets/19398432/15555615/7dad9e94-2297-11e6-8ce1-187830246b42.jpg)

![iconovault](https://cloud.githubusercontent.com/assets/19398432/15552682/8585b420-2289-11e6-8854-c8203f800ac2.jpg)

An icon more plane and minimalistic with the color of the interface included in it! I hope this only icon is where you looking for or at list close to that.

Any change let me know

**Comment by arnaldos** [comment]
@GustavoDeMoura I like de second just one thing put the icon in the settngs view

**Comment by GustavoDeMoura** [comment]
Done @arnaldos 

the icon in the setting view look like this.

![interfaceconicono](https://cloud.githubusercontent.com/assets/19398432/15558018/ea4dfc94-22a4-11e6-8ea2-043b0d468022.jpg)

**Comment by GustavoDeMoura** [comment]
Changes to the icon! adapting more the app style.

Let me know which one of this two probably can go to the setting @arnaldos 

![iconovault3](https://cloud.githubusercontent.com/assets/19398432/15580772/d5ab3dfe-2337-11e6-9270-d301571ab2e5.jpg)

![iconovault3-2](https://cloud.githubusercontent.com/assets/19398432/15580773/d5ad1520-2337-11e6-8591-be6e413a6185.jpg)

**Comment by arnaldos** [comment]
@GustavoDeMoura Please present them where the button is currently in the private network setting

**Comment by GustavoDeMoura** [comment]
![interfaceconicono2](https://cloud.githubusercontent.com/assets/19398432/15590905/1b5940aa-2368-11e6-9dfa-61b386ef7d8a.jpg)

I put the two versions one next to the other, i think is more accurate the first to look in the phone @arnaldos

**Comment by arnaldos** [comment]
@GustavoDeMoura ok right vesion just the center element put a litter more dark

**Comment by GustavoDeMoura** [comment]
The version you choose with the changes in the settin view @arnaldos 

![settingpreview](https://cloud.githubusercontent.com/assets/19398432/15598280/781b12bc-23a6-11e6-869d-65164a321a4c.jpg)

**Comment by arnaldos** [comment]
@GustavoDeMoura  plz send me this icon
