### ISSUE TITLE
Create a Fermat Wallet Logotype

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#847]
Here I leave the logo of the Fermat App  , to have as a reference for the logo of the Wallet App. the logo of the Wallet App should keep the "F" Fermat

![fermat_logo_v2_256x256](https://cloud.githubusercontent.com/assets/13594347/15529448/3054a6c2-2217-11e6-977f-fd4104c5ac8c.png)

**Comment by proseuz** [comment]
@arnaldos 
![fermatwallet-01](https://cloud.githubusercontent.com/assets/17308060/15592985/d37de09c-2371-11e6-8e95-492350bffccc.png)
![fermatwallet-04](https://cloud.githubusercontent.com/assets/17308060/15592984/d36d8b02-2371-11e6-8b72-d0cf2fe94546.png)
![fermatwallet-02](https://cloud.githubusercontent.com/assets/17308060/15592981/d359da1c-2371-11e6-93bb-7a104c3d4925.png)
![fermatwallet-03](https://cloud.githubusercontent.com/assets/17308060/15592983/d36281bc-2371-11e6-9ca1-ac9787da983c.png)

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina version 7 

![logo-fermat-wallet2](https://cloud.githubusercontent.com/assets/13594347/15616477/cbdb4a72-240d-11e6-905b-9497e9dd6a90.png)

**Comment by isahq23** [comment]
Versión 8 - still working, bit hard...

![fermat_logo](https://cloud.githubusercontent.com/assets/15214774/15619395/daec891c-241d-11e6-9070-9d639406a082.png)

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina el banner de esta versión en el issue #848

Versión 9
![icono](https://cloud.githubusercontent.com/assets/13594347/15626268/def1f052-248a-11e6-9fb3-bdbfdfcdf2cb.png)

View

![logo-fermat-wallet-view](https://cloud.githubusercontent.com/assets/13594347/15626309/d365a7d2-248b-11e6-8b19-0daa0b4b02b2.png)

**Comment by Luis-Fernando-Molina** [comment]
FIjate si podes hacer la billetera con la textura del planeta fermat, osea un planeta que no sea con forma de esfera sino con forma de billetera.

**Comment by arnaldos** [comment]
perfecto !! ya me pongo a trabajar en eso a ver que resultados logro

**Comment by m471c4** [comment]
@Luis-Fernando-Molina @arnaldos acá la primera versión de la billetera con la textura del planeta:

![version1](https://cloud.githubusercontent.com/assets/13468350/15661278/16a653d2-26b4-11e6-9fa5-badf66240c93.png)

**Comment by m471c4** [comment]
@Luis-Fernando-Molina @arnaldos versión con el módulo inclinado:

![version2](https://cloud.githubusercontent.com/assets/13468350/15688683/38e41106-2749-11e6-848e-a96690d3ef39.png)

![version2_screen](https://cloud.githubusercontent.com/assets/13468350/15688686/3dd3e006-2749-11e6-8739-2d43bdef3e9d.png)

**Comment by arnaldos** [comment]
Final Version

![logo_fermat_wallet](https://cloud.githubusercontent.com/assets/13594347/15950197/6ca7d11a-2e76-11e6-902c-532e032911c8.png)
