### ISSUE TITLE
Create a new image for the website in dating secction

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#849]
Image Size 436x270

Reference image

![captura de pantalla 465](https://cloud.githubusercontent.com/assets/13594347/15529667/b68b25c6-2218-11e6-9b20-e9a8c8e55f9a.png)

**Comment by isahq23** [comment]
@rennyx7 yours

**Comment by rennyx7** [comment]
Aquí van 
![propuesta1 dating](https://cloud.githubusercontent.com/assets/20045567/16315932/015397f4-394e-11e6-9cb1-07912b438891.png)

**Comment by rennyx7** [comment]
![propuesta 2 dating](https://cloud.githubusercontent.com/assets/20045567/16315972/2a3036fa-394e-11e6-98ff-03ba8d738740.png)

**Comment by rennyx7** [comment]
![propuesta 3 dating](https://cloud.githubusercontent.com/assets/20045567/16315988/35ea9a1c-394e-11e6-96ed-196bbcb4a7a7.png)

**Comment by isahq23** [comment]
@arnaldos @gabymado what you think guys?

**Comment by arnaldos** [comment]
I think we need use the colors of the app. currently have support for mobile devices. no tv, no pc, no tablets. ( soon we made support for this device)

**Comment by arnaldos** [comment]
@isahq23 @rennyx7 plz we need the change for today

**Comment by rennyx7** [comment]
@arnaldos absolutely, but i need to know what colors are those

**Comment by rennyx7** [comment]
here we go
![propuesta1 2 dating](https://cloud.githubusercontent.com/assets/20045567/16387277/2cc1ac84-3c62-11e6-82f4-c2a9e1f16249.png)
![propuesta2 1_dating](https://cloud.githubusercontent.com/assets/20045567/16387284/32da3d16-3c62-11e6-8bf6-bd6520df1023.png)
![propuesta3 1_dating](https://cloud.githubusercontent.com/assets/20045567/16387290/3809e4bc-3c62-11e6-8d54-9608d4bcdba7.png)

**Comment by isahq23** [comment]
@rennyx7  Can you try the second image with the smart phone of the first image? 
And maybe use a black and white theme too.
I'd like to see those options.

**Comment by rennyx7** [comment]
@isahq23 
![propuesta2 3_ dating](https://cloud.githubusercontent.com/assets/20045567/16390717/2c020ce8-3c72-11e6-91bf-9c5224e6a98f.png)

**Comment by rennyx7** [comment]
@isahq23 
![propuesta2 3_dating](https://cloud.githubusercontent.com/assets/20045567/16395039/0c62cc60-3c86-11e6-9b2a-4bfde7cc33cc.png)

**Comment by arnaldos** [comment]
@isahq23 @rennyx7 Can you try create a other version with out phone, maybe using a vectors or something elements. the logo is ok.

**Comment by rennyx7** [comment]
Some alternative @isahq23 @arnaldos 
![propuesta2 4 dating](https://cloud.githubusercontent.com/assets/20045567/16423959/238debee-3d2c-11e6-9fd0-2c95b5b64004.png)
![propuesta2 6_ dating](https://cloud.githubusercontent.com/assets/20045567/16423960/23a5e316-3d2c-11e6-8b81-5467a33f8ea6.png)

**Comment by isahq23** [comment]
I like this. More accurate to the theme.

**Comment by arnaldos** [comment]
I like, I think the version 2 is more consistent , not sure text think we can get out of you think there @isahq23

**Comment by isahq23** [comment]
@rennyx7 remove the text, leave the red band with the dating logo... and remove the red background in it. The white line it suppose to be only that, a line.

**Comment by rennyx7** [comment]
![propuesta2 7_ dating](https://cloud.githubusercontent.com/assets/20045567/16468411/baf8be8a-3e19-11e6-801f-707ab3c82742.png)

**Comment by isahq23** [comment]
Great! I think it's ready.

**Comment by arnaldos** [comment]
fine !!

**Comment by arnaldos** [comment]
I´ll be update to website
