### ISSUE TITLE
Crear un Logo para Fermat CCM (Crypto Commodity Money)

### ISSUE THREAD

**Issue by m471c4** [bitDubai/fermat-graphic-design#85]
Se debe entender el concepto de commodity money, el cual es dinero que se encuentra respaldado (usualmente por oro o plata). En este caso específico estamos hablando de dinero respaldado por crypto currency.

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina @m471c4 logo Fermat CCM
![fermat_ccm-2](https://cloud.githubusercontent.com/assets/13594347/9625387/8aeb7b66-511f-11e5-9a41-5e36caa42480.png)
![fermat_ccm](https://cloud.githubusercontent.com/assets/13594347/9625388/8af1c76e-511f-11e5-934b-497f1bc2fdd0.png)

**Comment by Luis-Fernando-Molina** [comment]
para reresentar que está sobre crypto usa una cadena y el dinero usa $ o E . Fijate que podes hacer con eso.

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina que tal así
![fermat_ccm](https://cloud.githubusercontent.com/assets/13594347/9647109/7f0608fa-51a3-11e5-93d3-80b7411e8569.png)
 ?

**Comment by Luis-Fernando-Molina** [comment]
siento que el logo se aleja respecto a lo que veniamos haciendo

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina en esta versión le estoy dando el mismo enfoque gráfico que tiene el BCH para estandarizar el concepto de crypto
![fermat_ccm2](https://cloud.githubusercontent.com/assets/13594347/9671360/28b5862e-525c-11e5-9791-243656a953ee.png)

**Comment by Luis-Fernando-Molina** [comment]
Mas alla del significado este logo no tiene el colorido que tienen los otros

Las barras de oro no aplican.

La representación de fiat currency de esa forma no me convence.

Miralo con @m471c4 a ver que se le ocurre por favor.

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina ok perfecto voy a restructurar

**Comment by arnaldos** [comment]
el logo con @m471c4

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina  Coloque una sintesis de una candado que internamente lleva una moneda para entender que esta encriptado ya que para esta versión el uso de la cadena no es favorable, por eso trabaje con un elemento gráfico similar que se adapta  para el uso de las monedas no se que opinas al usar este elemento ?
![fermat_ccm3](https://cloud.githubusercontent.com/assets/13594347/9678171/e34dd474-52ab-11e5-99da-b6dea9d52da7.png)

**Comment by Luis-Fernando-Molina** [comment]
En este caso no es que esté encriptado, sino que se basan en una crypto currency , que a su vez dependen de una blockchain, por eso la cadena.

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina ok perfecto voy a darle la vuelta a para darle un mejor enfoque al caso y  todos los elemento tengan una armonía sin  perderse del resto de los iconos

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina  en esta versión trabaje con los billetes y la cadenita que hemos empleados en otros iconos de fermat 
![fermat_ccm2](https://cloud.githubusercontent.com/assets/13594347/9720706/ad973648-555a-11e5-85c3-ec1741d5be2e.png)
![fermat-ccm](https://cloud.githubusercontent.com/assets/13594347/9720707/ad9ad924-555a-11e5-9bdd-2be46f0e59b3.png)

**Comment by Luis-Fernando-Molina** [comment]
OK el primero 

Están los tres colores de las billeteras, incluyendo el rojo?

**Comment by arnaldos** [comment]
ya genero una versión con el color rojo

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina versión de billetes en rojo
![fermat_ccm3](https://cloud.githubusercontent.com/assets/13594347/9721922/e13cd062-556d-11e5-9ae6-13c8288f35a6.png)

**Comment by Luis-Fernando-Molina** [comment]
OK usemos este logo x ahora

**Comment by arnaldos** [comment]
ok perfecto !!! ya lo paso a formato svg y lo subo a repo para que miguel lo actualice
