### ISSUE TITLE
Create Logo for P2P Sharing Vehicles App

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#850]
A person has a vehicle and is willing to share/rent it to another person who needs it for a brief period of time

**Comment by rosanacoronado** [comment]
@arnaldos @jhonmarquez92 
These are three proposal for the P2P Sharing Vehicles App. 

The proposals represents the idea of sharing with another person by interlacing the figures, which together form the image of a car.  I made 4 changes to the first proposal, playing with the blue color in two variants, as well as in the rest of the proposals. I proposed as a name for the application: VSHARE or VRENT to reduce the title, meaning the letter "V" as a vehicle. I dont know if you have already a name but either way I give you this name to use.

The images are 1 for the logos and 1 for the APP icon. 

Propuesta_1

![propuesta 1_1-01](https://cloud.githubusercontent.com/assets/19508456/15584958/b9561bba-2346-11e6-9124-8f02903ee90a.png)
![propuesta 1_2-01](https://cloud.githubusercontent.com/assets/19508456/15584909/9136ffbe-2346-11e6-8739-79391cd48f2d.png)
![propuesta 1_3-01](https://cloud.githubusercontent.com/assets/19508456/15584910/91371cc4-2346-11e6-8939-d80feb62a375.png)
![propuesta 1_4-01](https://cloud.githubusercontent.com/assets/19508456/15584911/9143382e-2346-11e6-88d0-761b736b8695.png)

Propuesta_2
![propuesta 2-01](https://cloud.githubusercontent.com/assets/19508456/15584912/9145d2b4-2346-11e6-866e-d240572ca020.png)

Propuesta_3
![propuesta 3-01](https://cloud.githubusercontent.com/assets/19508456/15584913/914cf102-2346-11e6-8377-963951cf11dd.png)

**Comment by proseuz** [comment]
I really like the proposal 1, but I would like to see more color tests. What do u think? @arnaldos

**Comment by arnaldos** [comment]
@jhonmarquez92 I don´t realy shure about proposal 1, but i like how you put the text in second proposal. plase another icon and we´ll see

**Comment by rosanacoronado** [comment]
@arnaldos @jhonmarquez92 here are new proposals for icons and color tests

Propuesta_1
![all work logos 2 2-01](https://cloud.githubusercontent.com/assets/19508456/15649682/305bcc66-263d-11e6-840e-01f216670697.png)

Propuesta_2
![all work logos 2-01](https://cloud.githubusercontent.com/assets/19508456/15649683/3061943e-263d-11e6-8e37-c8e76d410d50.png)

Propuesta_3
![all work logos 3-01](https://cloud.githubusercontent.com/assets/19508456/15649684/306bd458-263d-11e6-955d-9bcae1ec304b.png)

Propuesat_4
![all work logos 4-01](https://cloud.githubusercontent.com/assets/19508456/15649685/306d1d0e-263d-11e6-9ba1-0a8e322f4ddf.png)

Propuesta_5
![all work logos 5-01](https://cloud.githubusercontent.com/assets/19508456/15649686/30778aa0-263d-11e6-9238-8599734b2b23.png)

Propuesta_6
![all work logos 6-01](https://cloud.githubusercontent.com/assets/19508456/15649687/30791064-263d-11e6-8690-261e7d8e5eb3.png)

Propuesta_7
![all work logos 7-01](https://cloud.githubusercontent.com/assets/19508456/15652920/59d65956-2653-11e6-9d10-301fa112c680.png)

Variacion propuesta_7
![all work logos 8-01](https://cloud.githubusercontent.com/assets/19508456/15653210/4e77abda-2655-11e6-8419-0153675559f1.png)

**Comment by proseuz** [comment]
i realy like the proposal 1,2 and 7. What do you think? @arnaldos @emmysm

**Comment by arnaldos** [comment]
@rosanacoronado @jhonmarquez92 
the proposal 4 works most better, I realy think we work about this. just proof this.

Errase the users side, just i wanna see how is work.

**Comment by rosanacoronado** [comment]
@arnaldos @jhonmarquez92 

Proposal 4 without users sides

![logo_sharingvehicle_oneuser-01](https://cloud.githubusercontent.com/assets/19508456/15663842/da8a1b08-26c8-11e6-9c5b-e60ea2ec4868.png)

**Comment by arnaldos** [comment]
works with the original version

**Comment by proseuz** [comment]
creates color tests with the original version @rosanacoronado

**Comment by rosanacoronado** [comment]
@arnaldos @jhonmarquez92 new proposals with limited colors.

Proposal_1
![3-01](https://cloud.githubusercontent.com/assets/19508456/15751910/b3fdad3a-28b5-11e6-8967-de695ae12d07.png)

Proposal_2
![4-01](https://cloud.githubusercontent.com/assets/19508456/15751911/b401a98a-28b5-11e6-9c69-de8923e886b1.png)

Proposal_3
![5-01](https://cloud.githubusercontent.com/assets/19508456/15751912/b40c22ac-28b5-11e6-80c0-f68766dad14d.png)

Proposal_4
![6-01](https://cloud.githubusercontent.com/assets/19508456/15751913/b4105174-28b5-11e6-9991-211c88d2d50b.png)

Proposal_5
![1-01](https://cloud.githubusercontent.com/assets/19508456/15751914/b417fcbc-28b5-11e6-9b39-45b8b7579873.png)

Proposal_6
![2-01](https://cloud.githubusercontent.com/assets/19508456/15751915/b41b5f9c-28b5-11e6-909b-d9edb7c5826e.png)

**Comment by proseuz** [comment]
the proposal 2 can work. the colors make look so elegant @arnaldos what do u think?

**Comment by arnaldos** [comment]
@jhonmarquez92  I feel is too grey, maybe the 4 or 2. are work most better. I like more proposal 2 colors because transmits confidence and security. @rosanacoronado tries to convey it look fresher as in version 4.

**Comment by rosanacoronado** [comment]
@arnaldos @jhonmarquez92 

Proposal_7
![v4-08](https://cloud.githubusercontent.com/assets/19508456/16047247/33197d26-3219-11e6-9522-0559c34443ce.png)

Proposal_8
![v5-07](https://cloud.githubusercontent.com/assets/19508456/16047250/332cde2a-3219-11e6-9a03-c215eb932722.png)

Proposal_9
![v9-09](https://cloud.githubusercontent.com/assets/19508456/16047248/33248cca-3219-11e6-86c7-dd67480610db.png)

Proposal_10
![v11-09](https://cloud.githubusercontent.com/assets/19508456/16047249/3329fd9a-3219-11e6-92df-f2c8b225f346.png)

Proposal_11
![v2-04](https://cloud.githubusercontent.com/assets/19508456/16047253/3338839c-3219-11e6-9f9d-c9759aab0f77.png)

Proposal_12
![v3-05](https://cloud.githubusercontent.com/assets/19508456/16047252/33356f5e-3219-11e6-9fa1-c556d920862b.png)

**Comment by proseuz** [comment]
i like the proposal 7. what do u think @arnaldos

**Comment by arnaldos** [comment]
:+1: proposal 7

**Comment by arnaldos** [comment]
@rosanacoronado esto esta en el repo ? avisame para cerrar el caso :smile_cat:
