### ISSUE TITLE
Create Logo for P2P Fund raising App

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#851]
Backers pledge money to join creators in bringing non for profit projects to life, or to help NGO grow or increase awareness.

**Comment by Jessicafp** [comment]
![fund raising-01](https://cloud.githubusercontent.com/assets/19536846/15563792/fa9fd92e-22d5-11e6-8349-b9eda86459b2.png)
![fund raising-02](https://cloud.githubusercontent.com/assets/19536846/15563793/fac48a08-22d5-11e6-9cac-3ea5045ca9a3.png)
![fund raising-03](https://cloud.githubusercontent.com/assets/19536846/15563794/fad10e2c-22d5-11e6-9e45-5bc594598363.png)
![fund raising-04](https://cloud.githubusercontent.com/assets/19536846/15563795/fad8124e-22d5-11e6-90d5-4ec2cdd97f2c.png)

**Comment by arnaldos** [comment]
Trabajemos con la versión de la mano, solo que la moneda puede ser a un tono en blanco y aumenta un poco el tamaño de la moneda

**Comment by Jessicafp** [comment]
![fund raising-04](https://cloud.githubusercontent.com/assets/19536846/15578506/858d8924-232a-11e6-9c17-65ee1f00b4f5.png)

**Comment by arnaldos** [comment]
@Jessicafp Vamos a probar usar dos manos, como si están tomando la moneda. Evaluando bien esta mano parece que esta dando una señal de Stop.

**Comment by Jessicafp** [comment]
![fund raising-04](https://cloud.githubusercontent.com/assets/19536846/15589824/45c0fe96-235e-11e6-90d1-07cfb239c67f.png)

**Comment by Jessicafp** [comment]
![fund raising-05](https://cloud.githubusercontent.com/assets/19536846/15590008/3a8c05ce-235f-11e6-8f29-7c57dc90e13d.png)

**Comment by arnaldos** [comment]
@Jessicafp como seria el icono de la versión 2 ?

**Comment by arnaldos** [comment]
identifica las versiones plz :smile_cat:

**Comment by Jessicafp** [comment]
jaja cierto cierto sorry, ya te los paso

**Comment by Jessicafp** [comment]
![fund raising-05](https://cloud.githubusercontent.com/assets/19536846/15592600/d61953fc-236e-11e6-82ee-937a54c20268.png)

**Comment by Jessicafp** [comment]
![fund raising-06](https://cloud.githubusercontent.com/assets/19536846/16219599/51beec7e-3751-11e6-8c40-ffac99b67d2d.png)

**Comment by arnaldos** [comment]
otras propuestas plz

**Comment by Jessicafp** [comment]
![fund raising-07](https://cloud.githubusercontent.com/assets/19536846/16235400/93a6685e-379e-11e6-9c87-2b710001cd00.png)

**Comment by Jessicafp** [comment]
![fund raising-08](https://cloud.githubusercontent.com/assets/19536846/16241366/1bb48dc6-37b7-11e6-8919-2fb3780bdcb1.png)

**Comment by arnaldos** [comment]
replantea este logo creo lo que se viene trabajando no esta funcionando

**Comment by Jessicafp** [comment]
![fund raising-09](https://cloud.githubusercontent.com/assets/19536846/16352540/0b1dc412-3a39-11e6-9756-6141658dedd7.png)
![fund raising-10](https://cloud.githubusercontent.com/assets/19536846/16352541/0b2491fc-3a39-11e6-9d89-8bdc5389f11e.png)
![fund raising-11](https://cloud.githubusercontent.com/assets/19536846/16352539/0b1a9242-3a39-11e6-88ec-91fc2577ec81.png)

**Comment by arnaldos** [comment]
algo nuevo plz

**Comment by arnaldos** [comment]
@gustavo plz genera propuestas aquí también

**Comment by Jessicafp** [comment]
![fund raising-12](https://cloud.githubusercontent.com/assets/19536846/16399805/8fa0c76c-3c9f-11e6-8890-d07ed223a93e.png)
![fund raising-13](https://cloud.githubusercontent.com/assets/19536846/16399806/8fb0db8e-3c9f-11e6-95a3-e729c9c34496.png)
![fund raising-14](https://cloud.githubusercontent.com/assets/19536846/16399807/8fb2969a-3c9f-11e6-979f-35799fff901a.png)
![fund raising-15](https://cloud.githubusercontent.com/assets/19536846/16399808/8fbe1e98-3c9f-11e6-8ee9-c8297b664273.png)
![fund raising-16](https://cloud.githubusercontent.com/assets/19536846/16399810/8fc630e2-3c9f-11e6-8f09-edfdd2a2660d.png)

**Comment by GustavoDeMoura** [comment]
4 Versiones siguiendo un poco la misma linea grafica pero mas minimalista y gerencial de lo que se habia trabajado aca @arnaldos 

![fundraisingv1](https://cloud.githubusercontent.com/assets/19398432/16427785/64b9c750-3d45-11e6-8520-25fd2a7f7624.jpg)
![fundraisingv2](https://cloud.githubusercontent.com/assets/19398432/16427786/64c478c6-3d45-11e6-88fe-5a389c6ffbfa.jpg)
![fundraisingv3](https://cloud.githubusercontent.com/assets/19398432/16427787/65325378-3d45-11e6-9994-9d56ed6923f3.jpg)
![fundraisingv4](https://cloud.githubusercontent.com/assets/19398432/16427788/6535ef74-3d45-11e6-83bc-954dfbba879b.jpg)

**Comment by arnaldos** [comment]
puede andar por la versión de @GustavoDeMoura pero se puede mejorar actualmente se ve como 2 bloques. planten una propuesta nueva en usando como base la idea.

**Comment by GustavoDeMoura** [comment]
Las otras propuestas nuevas que te debia @arnaldos sorry la tardanza.

![fundvs2-1](https://cloud.githubusercontent.com/assets/19398432/16567905/4ce30e70-41fa-11e6-8397-47a58106a59a.jpg)

![fundvs2-2](https://cloud.githubusercontent.com/assets/19398432/16567904/4ce183de-41fa-11e6-8156-618162729f2d.jpg)

**Comment by arnaldos** [comment]
@GustavoDeMoura me gusta la idea de usar un elemento para hacer la separación de los textos pero no entiendo lo de la flecha. cromaticamente me gusta como se ve

**Comment by GustavoDeMoura** [comment]
Lo de la flecha es por el Raising, ya que la app es para recabar y aumentar fondos y da a entender, ya que apunta hacia arriba, la superacion  y el logro de las funciones para lo que fue hecha la app @arnaldos igual seguire trabajando en ella

**Comment by arnaldos** [comment]
se postpone pora hora
