### ISSUE TITLE
Create a circular button for components. Bounty program

### ISSUE THREAD

**Issue by emmysm** [bitDubai/fermat-graphic-design#852]
![pasted image at 2016_05_25 06_39 pm](https://cloud.githubusercontent.com/assets/15143489/15656108/a69dd7e0-266d-11e6-9f52-db1387627243.png)

@Joseangel2v

**Comment by Joseangel2v** [comment]
P-1
![b1](https://cloud.githubusercontent.com/assets/17457499/15660266/b930d0b6-26a3-11e6-8ce2-dafedad907aa.png)

**Comment by Joseangel2v** [comment]
P-2
![b2](https://cloud.githubusercontent.com/assets/17457499/15660269/ce3dce64-26a3-11e6-8c80-2cff695a4731.png)

**Comment by Joseangel2v** [comment]
P-3
![b3](https://cloud.githubusercontent.com/assets/17457499/15660279/f86c9c6a-26a3-11e6-91e4-2c231fc2a950.png)

**Comment by Joseangel2v** [comment]
P-4
![b4](https://cloud.githubusercontent.com/assets/17457499/15660289/0b2f322c-26a4-11e6-909c-f18ae8eac105.png)

**Comment by Joseangel2v** [comment]
P-5
![b5](https://cloud.githubusercontent.com/assets/17457499/15660292/156b6224-26a4-11e6-9530-563b6949a474.png)

**Comment by Joseangel2v** [comment]
P-6
![b7](https://cloud.githubusercontent.com/assets/17457499/15660297/265f6896-26a4-11e6-9dca-26580f20834f.png)

**Comment by Joseangel2v** [comment]
P-7
![b8](https://cloud.githubusercontent.com/assets/17457499/15660300/437d9d44-26a4-11e6-8046-d11d5e49ce7f.png)

**Comment by emmysm** [comment]
@ricardo460 qué tal?

**Comment by emmysm** [comment]
@Joseangel2v también va un indicador como el botón anaranjado que se muestra en el ejemplo. Tiene que formar parte del workflow. Me van gustando las propuestas 5 y 7

**Comment by ricardo460** [comment]
@emmysm @Joseangel2v se ven bien, me gusta la P5.

 Oscurece un poco el borde, porque el fondo de la pagina es blanco entonces no se notara. y pon la sombra en posición vertical como la P4.

**Comment by ricardo460** [comment]
@Joseangel2v me gustaria un color unico que combine con todos los tipos de componentes que tenemos. 

Aquí te dejo los tipos de componentes.

![concept](https://cloud.githubusercontent.com/assets/13169767/15661401/28d9b44e-26b5-11e6-8ac7-f16714221635.png)
![development](https://cloud.githubusercontent.com/assets/13169767/15661403/28fc1e30-26b5-11e6-9b62-3e8dd42bbfdc.png)
![production](https://cloud.githubusercontent.com/assets/13169767/15661404/29156f66-26b5-11e6-8393-03905444d205.png)
![qa](https://cloud.githubusercontent.com/assets/13169767/15661405/291b52c8-26b5-11e6-8fa4-90fccb7ac481.png)

**Comment by Joseangel2v** [comment]
P-8
![bo1](https://cloud.githubusercontent.com/assets/17457499/15708384/24cb7df6-27c8-11e6-8eb1-651d5213123b.png)

**Comment by Joseangel2v** [comment]
P-9
![bo2](https://cloud.githubusercontent.com/assets/17457499/15708404/378f79c4-27c8-11e6-890c-7e8281e528c8.png)

**Comment by Joseangel2v** [comment]
P-10
![bo3](https://cloud.githubusercontent.com/assets/17457499/15708544/d71a5f36-27c8-11e6-815a-e536ee391461.png)

**Comment by Joseangel2v** [comment]
P-11
![bo4](https://cloud.githubusercontent.com/assets/17457499/15708520/af8227b0-27c8-11e6-818d-e12da19f3ad2.png)

**Comment by Joseangel2v** [comment]
@emmysm

**Comment by emmysm** [comment]
i like it, @Joseangel2v. What do you thing @ricardo460 ?

you can begin to make other proposals to the other buttons

**Comment by Joseangel2v** [comment]
P-12
![1w](https://cloud.githubusercontent.com/assets/17457499/15730614/fd2ed908-2837-11e6-957f-52d6de9d1069.png)

**Comment by Joseangel2v** [comment]
P-13
![2w](https://cloud.githubusercontent.com/assets/17457499/15730621/095a46ea-2838-11e6-8873-b51a86df49cf.png)

**Comment by Joseangel2v** [comment]
P-14
![3w](https://cloud.githubusercontent.com/assets/17457499/15730633/13717dc4-2838-11e6-865a-73593670af21.png)

**Comment by Joseangel2v** [comment]
P-15
![4w](https://cloud.githubusercontent.com/assets/17457499/15730638/1be17a9a-2838-11e6-82c5-dafefdd6fdd6.png)

**Comment by Joseangel2v** [comment]
P-16
![5w](https://cloud.githubusercontent.com/assets/17457499/15730645/26f4e2fa-2838-11e6-80f4-5ca3715c635c.png)

**Comment by Joseangel2v** [comment]
P-17
![6w](https://cloud.githubusercontent.com/assets/17457499/15730651/33b1fb36-2838-11e6-88af-91f0af030fa6.png)

**Comment by Joseangel2v** [comment]
P-18
![7w](https://cloud.githubusercontent.com/assets/17457499/15730655/3e2cdfea-2838-11e6-9ffa-f9fe17cbaa2c.png)

**Comment by Joseangel2v** [comment]
P-19
![8w](https://cloud.githubusercontent.com/assets/17457499/15730659/4b12e240-2838-11e6-9c9b-104d37c357c4.png)

**Comment by Joseangel2v** [comment]
P-20
![9w](https://cloud.githubusercontent.com/assets/17457499/15730663/5705e610-2838-11e6-8a21-19e489e800a1.png)

**Comment by Joseangel2v** [comment]
P-21
![10w](https://cloud.githubusercontent.com/assets/17457499/15730772/6909f3c8-2839-11e6-869f-3b22ef1af0e4.png)

**Comment by Joseangel2v** [comment]
P-22
![11w](https://cloud.githubusercontent.com/assets/17457499/15730672/6b80fc56-2838-11e6-85f3-9e69d915a61e.png)

**Comment by Joseangel2v** [comment]
P-23
![12w](https://cloud.githubusercontent.com/assets/17457499/15730757/450a2c04-2839-11e6-8741-a2424ae6aa80.png)

**Comment by Joseangel2v** [comment]
P-24
![13w](https://cloud.githubusercontent.com/assets/17457499/15730925/931fd438-283a-11e6-9ed2-55d478cd2d93.png)

**Comment by ricardo460** [comment]
@Joseangel2v @emmysm  

Para el botón con el Id, se necesita que parezca como una extensión del componente o acoplado en un costado, no circular. seria ideal que fuera un rectángulo con el borde izquierdo redondeado o como se vea mejor. 

Y con respecto al color seria magnifico que combinara con los 4 tipos de componentes, asi poder utilizarlos en todos.

**Comment by Joseangel2v** [comment]
P-25
![1b](https://cloud.githubusercontent.com/assets/17457499/15905917/90e8ae1a-2d80-11e6-9a59-b9420d511588.png)

**Comment by Joseangel2v** [comment]
P-26
![2b](https://cloud.githubusercontent.com/assets/17457499/15905923/9d4a0dac-2d80-11e6-8255-e955fcb69524.png)

**Comment by Joseangel2v** [comment]
P-27
![3b](https://cloud.githubusercontent.com/assets/17457499/15905929/a691862e-2d80-11e6-8910-2598a772d936.png)

**Comment by Joseangel2v** [comment]
P-28
![4b](https://cloud.githubusercontent.com/assets/17457499/15905941/b26ea896-2d80-11e6-942f-6ebcce4efbf6.png)

**Comment by Joseangel2v** [comment]
P-29
![5b](https://cloud.githubusercontent.com/assets/17457499/15905947/ba5ae722-2d80-11e6-9570-dcb08fa59687.png)

**Comment by Joseangel2v** [comment]
P-30
![6b](https://cloud.githubusercontent.com/assets/17457499/15905951/c2439f1a-2d80-11e6-9137-85902097d056.png)

**Comment by Joseangel2v** [comment]
P-31
![7b](https://cloud.githubusercontent.com/assets/17457499/15906054/13035670-2d81-11e6-8fe3-c84855c301dd.png)

**Comment by Joseangel2v** [comment]
P-32
![8b](https://cloud.githubusercontent.com/assets/17457499/15906066/1cf8b74c-2d81-11e6-9d0d-c141cdb6f381.png)

**Comment by Joseangel2v** [comment]
![botones](https://cloud.githubusercontent.com/assets/17457499/15911927/ad54988c-2d9b-11e6-8274-21b5b3d28d98.png)

**Comment by ricardo460** [comment]
@Joseangel2v  me parece bien la P-28, pero puedes cambiarle el color, por uno que sea neutral para todos los tipo de componentes. y añadirle un botón como la P-30.

**Comment by Joseangel2v** [comment]
![btprueba](https://cloud.githubusercontent.com/assets/17457499/16065642/664b183c-3276-11e6-9f09-65918a66967c.png)

**Comment by Joseangel2v** [comment]
P-33
![1bt](https://cloud.githubusercontent.com/assets/17457499/16065656/85e66642-3276-11e6-9084-0ef838045221.png)

**Comment by Joseangel2v** [comment]
P-34
![2bt](https://cloud.githubusercontent.com/assets/17457499/16065660/8fcb6f5e-3276-11e6-87ce-e4a5e6393d3c.png)

**Comment by Joseangel2v** [comment]
P-35
![3bt](https://cloud.githubusercontent.com/assets/17457499/16065670/99b78a02-3276-11e6-9299-bbc2b6331cee.png)

**Comment by Joseangel2v** [comment]
P-36
![4bt](https://cloud.githubusercontent.com/assets/17457499/16065676/a3e84fa2-3276-11e6-8182-831f0c1c97fb.png)

**Comment by Joseangel2v** [comment]
P-36
![5bt](https://cloud.githubusercontent.com/assets/17457499/16065690/c35c9cee-3276-11e6-9142-fde76ce84053.png)

**Comment by Joseangel2v** [comment]
P-37
![7bt](https://cloud.githubusercontent.com/assets/17457499/16065734/1d36666e-3277-11e6-9db6-ac77a5fa7df5.png)

**Comment by emmysm** [comment]
@Joseangel2v recuerda colocarle un color que haga buen contraste con todas las fichas. Asegurate de acomodar los vectores de las esquinas, están desprolijos

**Comment by ricardo460** [comment]
@Joseangel2v me parece bien la propuesta P-37.

**Comment by arnaldos** [comment]
@Joseangel2v revisa los nodos de los vectores están estirados en las esquinas deberían ser redonda.

**Comment by Joseangel2v** [comment]
P-38
![1bt](https://cloud.githubusercontent.com/assets/17457499/16101316/5df1849c-332e-11e6-8f97-270d43b0ebc7.png)

**Comment by Joseangel2v** [comment]
P-39
![2bt](https://cloud.githubusercontent.com/assets/17457499/16101324/718abf6e-332e-11e6-8108-de0089e3d90a.png)

**Comment by Joseangel2v** [comment]
P-40
![3bt](https://cloud.githubusercontent.com/assets/17457499/16101330/7bf6fd78-332e-11e6-80c6-c02045844ad0.png)

**Comment by Joseangel2v** [comment]
P-41
![4bt](https://cloud.githubusercontent.com/assets/17457499/16101341/97d5f2f6-332e-11e6-8712-76a30d413792.png)

**Comment by Joseangel2v** [comment]
P-42
![5bt](https://cloud.githubusercontent.com/assets/17457499/16101345/a19554c6-332e-11e6-8920-91eebd8d70a5.png)

**Comment by Joseangel2v** [comment]
P-43
![7bt](https://cloud.githubusercontent.com/assets/17457499/16101361/b08cf4d4-332e-11e6-80dc-33374684cdc3.png)

**Comment by Joseangel2v** [comment]
P-44
![btprueba](https://cloud.githubusercontent.com/assets/17457499/16101375/d831cdb6-332e-11e6-8c78-5af9f971fe50.png)

**Comment by ricardo460** [comment]
@Joseangel2v creo que la P-39 va mejor con el nuevo diseño de fermat-org. pero estoy entre esa y la P-44.
@emmysm que opinas?

También necesito una versión con la forma del botón derecho como la propuesta P-33.

**Comment by arnaldos** [comment]
@Joseangel2v  plz reevisa los vectores las esquinas no están redondeadas, el boton lo veo muy grande, @emmysm @Joseangel2v presenten la propuesta donde se debe ver y probar como se comportan los elementos juntos.

**Comment by Joseangel2v** [comment]
P-45
![boton](https://cloud.githubusercontent.com/assets/17457499/16212621/de9c33f2-3712-11e6-86e6-e4928a0d3f6d.png)

**Comment by Joseangel2v** [comment]
![propuesta boton](https://cloud.githubusercontent.com/assets/17457499/16212637/f827fe8c-3712-11e6-8634-528decc494f4.png)

**Comment by ricardo460** [comment]
@Joseangel2v  puedes subir esta versión,.Y también una versión como la P-33, igual que esta propuesta pero con la diferencia del segundo botón. 

Otra cosa, necesito que la versión con el botón rojo, sea transparente que solo se vea lo rojo. Es para sobreponer esa imagen con la otra y así cambiarle el color al botón.

**Comment by Joseangel2v** [comment]
P-46
![301](https://cloud.githubusercontent.com/assets/17457499/16216255/1dc5224e-3733-11e6-896c-c040c09ccee9.png)

**Comment by Joseangel2v** [comment]
![propuesta boton](https://cloud.githubusercontent.com/assets/17457499/16215024/158a523a-3728-11e6-9459-235963752d5d.png)

**Comment by emmysm** [comment]
genial @Joseangel2v @ricardo460
