### ISSUE TITLE
Create the interface of dating app  

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#853]

**Comment by isahq23** [comment]
@arnaldos first view - I still have to develope the settings/preferences

![dating_m1](https://cloud.githubusercontent.com/assets/15214774/15589252/d004b6ae-235b-11e6-9c38-7ae0499ef47b.png)

**Comment by arnaldos** [comment]
@isahq23 I like this but let katherine bring her opinion about

**Comment by Kate99** [comment]
@gabymado

**Comment by isahq23** [comment]
Advance - SING UP FULL - 2 VERSIONS

![sing_up_prop](https://cloud.githubusercontent.com/assets/15214774/16060200/63aaa8a2-3250-11e6-9d19-8301a7181cf4.jpg)

**Comment by isahq23** [comment]
![dating_part2](https://cloud.githubusercontent.com/assets/15214774/16128596/25604b2a-33cb-11e6-9396-c8760731aa03.jpg)

**Comment by isahq23** [comment]
![dating_community](https://cloud.githubusercontent.com/assets/15214774/16128604/2cd334d0-33cb-11e6-98f6-dc0436247939.jpg)
