### ISSUE TITLE
Create improvements  of element gray on actionbar to Banking Wallet

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#855]
Here actual view

![banking wallet-05](https://cloud.githubusercontent.com/assets/13594347/15591735/9426ae96-2368-11e6-8d43-cee28d24c64b.jpg)

**Comment by Jessicafp** [comment]
![Uploading banking wallet views-01.jpg…]()

**Comment by Jessicafp** [comment]
![banking wallet views-01](https://cloud.githubusercontent.com/assets/19536846/15615338/84063a96-2407-11e6-8848-e8cd444acc0c.jpg)

**Comment by arnaldos** [comment]
@Jessicafp genera otras propuestas plz

**Comment by Jessicafp** [comment]
![banking wallet-01](https://cloud.githubusercontent.com/assets/19536846/16119348/e03d0f2c-33a4-11e6-9abd-f70f9f7b35d0.png)

**Comment by Jessicafp** [comment]
![banking wallet views-04](https://cloud.githubusercontent.com/assets/19536846/16219583/37306428-3751-11e6-9ab1-577a4805f85f.png)
![banking wallet views-05](https://cloud.githubusercontent.com/assets/19536846/16219584/37385c46-3751-11e6-96eb-9ade2449d85d.png)
![banking wallet views-06](https://cloud.githubusercontent.com/assets/19536846/16219585/373e6884-3751-11e6-8a58-af718c54a7df.png)
