### ISSUE TITLE
Crear un Logo para Fermat BNP (Bank Notes Platform)

### ISSUE THREAD

**Issue by m471c4** [bitDubai/fermat-graphic-design#86]
Los bank notes son billetes, en este caso se puede usar ese concepto para representarlo.

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina  @m471c4  logo Fermat BNP 
![fermat_bnp](https://cloud.githubusercontent.com/assets/13594347/9625406/abaf4a3a-511f-11e5-994e-90f556ce21a0.png)

**Comment by Luis-Fernando-Molina** [comment]
no uses el banco. "Bank Notes" es como una sola palabra que significa "billete" . Esto se trata de wallets que en vez de mostrarte el dinero en numero te lo muestra en billetes.

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina Ajustes Fermat BNP
![fermat_bnp](https://cloud.githubusercontent.com/assets/13594347/9647095/645dc47a-51a3-11e5-8c40-3c6f2c858725.png)

**Comment by Luis-Fernando-Molina** [comment]
en este caso, los billetes van a ser de fiat currency, con lo cual no debiera tener la referencia a bitcoin.

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina  Ok, ya reviso eso.

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina subo los Fermat BNP 
![fermat_bnp2](https://cloud.githubusercontent.com/assets/13594347/9670483/9a0eb364-5256-11e5-8302-3fcc23b66737.png)

**Comment by Luis-Fernando-Molina** [comment]
no me convence. Proba poner la billetera del logo de fermat y en vez de poner las billeterias , ponele 3 billetitos de diferentes monedas.

**Comment by arnaldos** [comment]
ok perfecto !!

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina te comparto los ajustes de Fermat BNP
![fermat_bnp2](https://cloud.githubusercontent.com/assets/13594347/9677920/4c0b8928-52a9-11e5-8c5f-67ae4186f4e9.png)

**Comment by Luis-Fernando-Molina** [comment]
proba los billetes ponerle el color de las billeteras chiquitas, uno cada color.

Hacete una segunda version con los billetes en escalerita por favor.

Revisa los bordes blancos que sean estandares.

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina perfecto ya realizo los cambios !!

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina ajustes de fermat BNP
![fermat_bnp3](https://cloud.githubusercontent.com/assets/13594347/9691482/8658fd00-530c-11e5-8d7a-527eb7370ebd.png)
![fermat_bnp4](https://cloud.githubusercontent.com/assets/13594347/9691483/865dfd28-530c-11e5-8f6c-f1f9b933d130.png)
![fermat_bnp5](https://cloud.githubusercontent.com/assets/13594347/9691484/86635066-530c-11e5-85db-3cdd2e7c5369.png)

**Comment by Luis-Fernando-Molina** [comment]
No me entediste , ibamos bien con lo ultimo que me mostraste.

La escalarita era sin sacar la billetera grande.

El color probalo adentro del billete no en el borde por favor.

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina ok corrígeme si estoy equivocado, mantengo el color verde de los billetes y lo que le cambio el color seria  lo que en este momento esta en tono beige del centro del billete ? 

mantener la billetera entendido !

**Comment by Luis-Fernando-Molina** [comment]
> ok corrígeme si estoy equivocado, mantengo el color verde de los billetes y lo que le cambio el color seria lo que en este momento esta en tono beige del centro del billete ? 

Correcto

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina ajustes de Fermat BNP
![fermat-bnp](https://cloud.githubusercontent.com/assets/13594347/9720712/b7ab91c4-555a-11e5-9303-3a3174462b09.png)
![fermat-bnp2](https://cloud.githubusercontent.com/assets/13594347/9720711/b7a53fc2-555a-11e5-9739-0481177ba1e3.png)
![fermat-bnp3](https://cloud.githubusercontent.com/assets/13594347/9720713/b7b336fe-555a-11e5-9a1a-ab9d155d9b5b.png)

**Comment by Luis-Fernando-Molina** [comment]
Están los tres colores de las billeteras del logotipo fermat? 

No falta el rojo?

**Comment by arnaldos** [comment]
si falta el rojo ! ya lo subo

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina versión de billetes en rojo
![fermat-bnp4](https://cloud.githubusercontent.com/assets/13594347/9721913/90926776-556d-11e5-8c99-e0854c2b3142.png)
![fermat-bnp5](https://cloud.githubusercontent.com/assets/13594347/9721914/909759c0-556d-11e5-9d4e-3cf2a97dc668.png)
![fermat-bnp6](https://cloud.githubusercontent.com/assets/13594347/9721915/912cab10-556d-11e5-9400-4abd828562f5.png)

**Comment by Luis-Fernando-Molina** [comment]
OK vamos a usar la tercera. Asegúrate de que se actualice en fermat org por favor.

**Comment by arnaldos** [comment]
ok perfecto !!!
