### ISSUE TITLE
Create Improvements Chat Profile and Community

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#861]

**Comment by arnaldos** [comment]
@franklinmarcano1970 @josejcb @Luis-Fernando-Molina 

version 1
![community](https://cloud.githubusercontent.com/assets/13594347/15621597/cf2bfb4a-242b-11e6-9e5f-d9e77494cf81.jpg)

Version 2 and version 3
![2](https://cloud.githubusercontent.com/assets/13594347/15621598/cf2da6a2-242b-11e6-85c5-467a667e6d4e.jpg)

**Comment by Luis-Fernando-Molina** [comment]
La versión dos va mejor pero no debe tener los dibujitos

**Comment by arnaldos** [comment]
perfecto !!

**Comment by Luis-Fernando-Molina** [comment]
Por otro lado dijimos que este Chat debe ser igual a whatsup y whatsup no tiene navigation drawer,  con lo cual desde el vamos esta mal. Debe ser igual a whatsup.

**Comment by Luis-Fernando-Molina** [comment]
El tono de verde es diferente

**Comment by arnaldos** [comment]
El tono de verde lo exigió joaquin hace varios meses y es el que hemos venido trabajando desde el entonces

**Comment by franklinmarcano1970** [comment]
Claro es orientado a ws, pero tomamos como referencia mantener un estandar dentro de fermat y lo vimos de esa manera!!!...

**Comment by franklinmarcano1970** [comment]
Todos esos colores y diseños fueron aprobados en su momento hace unos meses por joaquin..

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina Disculpa a continuación te dejo el issue #525 donde se discutió los colores, fondos, y estilos que manejaba whatsapp para esa fecha y el proyecto actual fue trabajado en base a esos diseños. Si debemos ajustarnos a la nueva versión de whatsapp no hay problema. De igual manera ya estoy trabajando en ello.

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina @franklinmarcano1970 @josejcb  Les comparto el paquete de chat, community y profile. Enfocado a la ultima actualización de Whatsapp.

### Comunity Notifications

![chat_community_notifications](https://cloud.githubusercontent.com/assets/13594347/15625592/a692423e-2476-11e6-8888-09feb6fbf8ba.jpg)

### Comunity Users

![chat_community_users_fermat](https://cloud.githubusercontent.com/assets/13594347/15625597/d5a5aff2-2476-11e6-970c-fcef6813eb06.jpg)

### Comunity Contacts

#### Version 1

![chat_community_contacts](https://cloud.githubusercontent.com/assets/13594347/15625601/f254ec94-2476-11e6-9d5e-ba0c252da12d.jpg)

#### Version 2

![chat_community_contacts_2](https://cloud.githubusercontent.com/assets/13594347/15625603/00dc861e-2477-11e6-9175-93ae867a1475.jpg)

### Profile

![chat_profile](https://cloud.githubusercontent.com/assets/13594347/15625606/17113e84-2477-11e6-9fd5-52fe49ef2b31.jpg)

### Chat App

![chat](https://cloud.githubusercontent.com/assets/13594347/15625608/2aaad0b8-2477-11e6-82bd-dbf069e895f0.jpg)

**Comment by Luis-Fernando-Molina** [comment]
Esta mas parecida pero no esta igual. Fijate en los detalles.

El nombre en el title bar debe ser P2P Chat

**Comment by arnaldos** [comment]
ok perfecto !!

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina @franklinmarcano1970 @josejcb  Ajustes de chat, community y profile. 

### Comunity Notifications

![chat_community_notification](https://cloud.githubusercontent.com/assets/13594347/15628724/4a86b75c-24d2-11e6-87cc-323313ef5fa7.jpg)

### Comunity Users

![chat_community_users](https://cloud.githubusercontent.com/assets/13594347/15628727/5325535a-24d2-11e6-9a1a-aa4fa8a28c1d.jpg)

### Comunity Contacts

#### Version 1

![chat_community_contacts_1](https://cloud.githubusercontent.com/assets/13594347/15628729/5e63ed26-24d2-11e6-93ad-a65f1f0e1ff0.jpg)

#### Version 2

![chat_community_contacts_2](https://cloud.githubusercontent.com/assets/13594347/15628731/6692325a-24d2-11e6-8ded-c65018750d56.jpg)

### Profile

![chat_profile](https://cloud.githubusercontent.com/assets/13594347/15628733/733f5816-24d2-11e6-9932-7ad09959d079.jpg)

### Chat App

![chat](https://cloud.githubusercontent.com/assets/13594347/15628736/7abd5c6e-24d2-11e6-819e-2375fc5ae310.jpg)

**Comment by arnaldos** [comment]
Cambie el selector del tab en blanco como lo tiene whasapp, pero realmente me gusta verde, resalta mas el selector. los fondos en estos ajuste son mas simples sin gradientes, visualmente se ve mas atractivo, y seguramente la app la haría menos pesada.

Espero sus comentarios para iniciar a generar los recursos

**Comment by franklinmarcano1970** [comment]
Pienso como dice Arnaldo en verde se vera mejor y da algo mas de originalidad, pero bueno por otra cosa por mi caso todo se ve muy bien!!!!.

**Comment by Luis-Fernando-Molina** [comment]
1. Es P2P Chat,  no al revés 
2. El iconito de help no debiera estar ahí. Sino en algún menú,  siguiendo whatsup.

**Comment by Luis-Fernando-Molina** [comment]
Identity : qué es eso de You are pay useruser?

**Comment by Luis-Fernando-Molina** [comment]
Es P2P Chat community. Hace revisar tus textos por alguien que sepa inglés por favor.

**Comment by Luis-Fernando-Molina** [comment]
Community más tirando a versión 1

**Comment by franklinmarcano1970** [comment]
Identity : qué es eso de You are pay useruser?, era para saber si era una identidad que iba a cobrar por chatear con el, pero que actualmente no existe, de hecho eso no no esta en lo que esta actual, por tal motivo no va, ya que fueron las propuestas originales, y mas adelante veremos como es la mejor forma de manejar el poder manejar Chat de pago...

**Comment by franklinmarcano1970** [comment]
Es P2P Chat community. Hace revisar tus textos por alguien que sepa inglés por favor, acá tenemos a alguien que evalúa esos casos y se le da la mejor traducción.

**Comment by arnaldos** [comment]
ok ya modifico los ajustes solicitados.

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina @franklinmarcano1970 @josejcb  @Lozadaa les comparto los últimos ajustes

## Propuesta 3

### Community

#### Comunity Notifications

![chat_community_notifications](https://cloud.githubusercontent.com/assets/13594347/15636104/96d4528a-25be-11e6-9bed-1f7915b204bd.jpg)

#### Comunity General (users fermat)

![chat_community_users](https://cloud.githubusercontent.com/assets/13594347/15636105/9bd56904-25be-11e6-8621-ff8e02ed3b66.jpg)

#### Comunity Contacts

![chat_community_contacts](https://cloud.githubusercontent.com/assets/13594347/15636109/b2e6b63e-25be-11e6-8ddb-f52defe90084.jpg)

### Profile

![chat_profile](https://cloud.githubusercontent.com/assets/13594347/15636112/c14d4094-25be-11e6-8c51-f440c38a3bb7.jpg)

### Chat App

![chat](https://cloud.githubusercontent.com/assets/13594347/15636113/c595b168-25be-11e6-91dc-2c250b866483.jpg)

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina @franklinmarcano1970 @josejcb  @Lozadaa 

## Propuesta 4

### Community

#### Comunity Notifications

![notifications](https://cloud.githubusercontent.com/assets/13594347/15642044/86c832c6-260e-11e6-8b44-b19288b89cbf.jpg)

#### Comunity Browser

![browser](https://cloud.githubusercontent.com/assets/13594347/15642049/90f7a236-260e-11e6-8bfb-3e9c9e57012f.jpg)

#### Comunity Conections

![conections](https://cloud.githubusercontent.com/assets/13594347/15642056/9a159d8c-260e-11e6-9140-1e67608fa98c.jpg)

### Profile

![profile](https://cloud.githubusercontent.com/assets/13594347/15642061/a4250042-260e-11e6-9721-c9fb72368f6e.jpg)

### Chat App

![chat](https://cloud.githubusercontent.com/assets/13594347/15642114/10201980-260f-11e6-9c4f-ce4b71b92178.jpg)

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina @franklinmarcano1970 @josejcb  @Lozadaa Les comparto las ultima versión incluye la opción de geolocalizacion

## Propuesta 5

### Community

#### Comunity Notifications

![notifications](https://cloud.githubusercontent.com/assets/13594347/15800731/2f6d1b86-2a4b-11e6-889c-3a4cfe4259d7.jpg)

#### Comunity Browser

![browser](https://cloud.githubusercontent.com/assets/13594347/15800733/39853d7e-2a4b-11e6-95c4-7736726fd904.jpg)

#### Comunity Conections

![conections](https://cloud.githubusercontent.com/assets/13594347/15800735/3f6e7aac-2a4b-11e6-8e62-529051c1d5a3.jpg)

### Profile

![profile](https://cloud.githubusercontent.com/assets/13594347/15800747/aa9f5c4c-2a4b-11e6-9768-94730f41d167.jpg)

### Chat App

![chat](https://cloud.githubusercontent.com/assets/13594347/15800748/b1e4d450-2a4b-11e6-9374-392cede27eb3.jpg)

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina @franklinmarcano1970 @josejcb @Lozadaa Les comparto las ultima versión genere unos ajustes el el filtro de geolocalizacion y ajuste unos detalles 

## Propuesta 6

### Community

#### Comunity Notifications

![chat_notification](https://cloud.githubusercontent.com/assets/13594347/15884975/b0ff0ed2-2d1d-11e6-8bf4-55adec88bcb4.jpg)

#### Comunity Browser

![chat_browser](https://cloud.githubusercontent.com/assets/13594347/15884981/b63884d2-2d1d-11e6-921d-118014e3894d.jpg)

#### Comunity Conections

![chat_connections](https://cloud.githubusercontent.com/assets/13594347/15884987/bda61ef0-2d1d-11e6-8627-0cb3c2b59b77.jpg)

### Profile

![chat_profile](https://cloud.githubusercontent.com/assets/13594347/15884989/c22059e6-2d1d-11e6-96ee-e4968ad9c23f.jpg)

### Chat App

![chat_app](https://cloud.githubusercontent.com/assets/13594347/15884993/c8e539ea-2d1d-11e6-8c44-490c6c73eef6.jpg)

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina @franklinmarcano1970 les comparto algunos ajustes conversado con @josejcb 

## Propuesta 7

### Community

#### Comunity Notifications

![chat_notification](https://cloud.githubusercontent.com/assets/13594347/15932121/466b1054-2e24-11e6-82ca-15b85e508e82.jpg)

#### Comunity Browser

![chat_browser](https://cloud.githubusercontent.com/assets/13594347/15932126/4c379214-2e24-11e6-9d97-62211922568c.jpg)

#### Comunity Conections

![chat_connections](https://cloud.githubusercontent.com/assets/13594347/15932169/76ba15ac-2e24-11e6-9069-388aaf92b063.jpg)

### Profile

![chat_profile](https://cloud.githubusercontent.com/assets/13594347/15932173/7d55000c-2e24-11e6-9eda-4d5bfdeb41b7.jpg)

### Chat App

![chat_app](https://cloud.githubusercontent.com/assets/13594347/15932178/82949ba4-2e24-11e6-9edb-789ff38acf05.jpg)

**Comment by arnaldos** [comment]
@franklinmarcano1970 Últimos ajustes aplicados

## Propuesta 8

### Community

#### Comunity Notifications

![chat_version_12-22](https://cloud.githubusercontent.com/assets/13594347/16289149/80d8eb92-38bc-11e6-8ec7-6e7f1997a77b.jpg)

#### Comunity Browser

![chat_version_12-23](https://cloud.githubusercontent.com/assets/13594347/16289150/895ff788-38bc-11e6-9f2d-8ded3554f203.jpg)

#### Comunity Conections

![chat_version_12-24](https://cloud.githubusercontent.com/assets/13594347/16289157/93d19ed8-38bc-11e6-9952-f7b01be5ba88.jpg)

### Profile

![chat_version_12-20](https://cloud.githubusercontent.com/assets/13594347/16289166/a9332698-38bc-11e6-8599-8da8572aac47.jpg)

### Chat App

![chat_version_12-21](https://cloud.githubusercontent.com/assets/13594347/16289170/b000acc0-38bc-11e6-9bfa-07882fcee507.jpg)
