### ISSUE TITLE
Infographics Global Cyberspaces

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#862]

**Comment by Jessicafp** [comment]
![1 device private network-01 3](https://cloud.githubusercontent.com/assets/19536846/15622078/7c2fa4a6-242f-11e6-8522-91eef2b0e6db.png)
![2 device private network-04](https://cloud.githubusercontent.com/assets/19536846/15622079/7c3138d4-242f-11e6-9fcd-d96c030e39ba.png)
![3 device private network-02](https://cloud.githubusercontent.com/assets/19536846/15622080/7c40d46a-242f-11e6-932c-a2e586c81a83.png)

**Comment by Luis-Fernando-Molina** [comment]
Opción dos pero le falta un título

**Comment by Jessicafp** [comment]
Si disculpe, la elimine sin querer y no me di cuenta, disculpe, ya le paso el correcto

**Comment by Jessicafp** [comment]
![device private network-04](https://cloud.githubusercontent.com/assets/19536846/15623916/687f4360-2445-11e6-9187-c2ab28f69458.png)

**Comment by Luis-Fernando-Molina** [comment]
OK ahí esta,  ponelo en media kit please

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina ya este en media kit
