### ISSUE TITLE
Create a Banner to Jobs P2P App

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#863]
Issue Reference  #857

Image size 922x201
Image reference

![captura de pantalla 50](https://cloud.githubusercontent.com/assets/13594347/15610996/0d755b6a-23f2-11e6-8523-96b2c5bd441b.png)

**Comment by rosanacoronado** [comment]
@arnaldos @jhonmarquez92 here are some proposals for banners, some of them have text and other variations without the text. I will continue working on other proposals

Propuesta_1
![p2p jobs 8-02](https://cloud.githubusercontent.com/assets/19508456/15710882/b9549cfc-27d5-11e6-95ad-da3842d8dbad.png)

Propuesta_2
![p2p jobs 10-01](https://cloud.githubusercontent.com/assets/19508456/15710883/b9620ab8-27d5-11e6-9f44-df5ebfd3c53b.png)

Propuesta_3
![p2p job 5-03](https://cloud.githubusercontent.com/assets/19508456/15710920/dd99bfe8-27d5-11e6-8253-b453a4a0bf1f.png)
![p2p job 6-03](https://cloud.githubusercontent.com/assets/19508456/15710921/dd9c69a0-27d5-11e6-8a53-99ff1ae9210f.png)

Propuesta_4
![p2p job 7-01](https://cloud.githubusercontent.com/assets/19508456/15710922/dda43734-27d5-11e6-932e-af79da79ecd8.png)

Propuesta_5
![p2p job 4-02](https://cloud.githubusercontent.com/assets/19508456/15710943/eeaf697c-27d5-11e6-939c-f12cbf00c569.png)

Propuesta_6
![p2p job 2-01](https://cloud.githubusercontent.com/assets/19508456/15710983/f7369be2-27d5-11e6-9137-ec4f34ee6c8f.png)
![p2p job 1-01](https://cloud.githubusercontent.com/assets/19508456/15710984/f74500ce-27d5-11e6-9697-62e3ce809f94.png)

Propuesta_7
![p2p job 11-01](https://cloud.githubusercontent.com/assets/19508456/15710985/f748bef8-27d5-11e6-90f8-e14180757ebe.png)

**Comment by proseuz** [comment]
Proposal 4 can work but including the character of the proposal 3 @rosanacoronado  what do u think? @arnaldos

**Comment by rosanacoronado** [comment]
@arnaldos @jhonmarquez92 new proposals including the caracter

Proposal_1
![p2p jobs banner-01](https://cloud.githubusercontent.com/assets/19508456/15792260/f0707612-29a5-11e6-86ab-966b6138ddc3.png)

Proposal_2
![p2p jobs banner 3-01](https://cloud.githubusercontent.com/assets/19508456/15792261/f0788c26-29a5-11e6-85e4-4a52a45efa64.png)

Proposal_3
![p2p jobs banner 6-01](https://cloud.githubusercontent.com/assets/19508456/15792262/f07c48c0-29a5-11e6-87e8-00deecb2162b.png)

**Comment by proseuz** [comment]
the proposal 3 looks great @arnaldos

**Comment by emmysm** [comment]
i like the proposal 3 :)

**Comment by arnaldos** [comment]
@rosanacoronado the name is  P2P JOBS, and proposal 3 is good :+1:

**Comment by rosanacoronado** [comment]
@arnaldos @jhonmarquez92 @emmysm here is the correction of the name. What do you guys think?

![p2p jobs banner correcion-01](https://cloud.githubusercontent.com/assets/19508456/15822995/8c255640-2bc2-11e6-956a-84476e2ab0a6.png)

**Comment by arnaldos** [comment]
@rosanacoronado nice! upload it to the repo

**Comment by proseuz** [comment]
@arnaldos @gabymado 
1
![banner_p2p_jobs jhon-03](https://cloud.githubusercontent.com/assets/17308060/15918455/bc5adbb8-2dd0-11e6-968b-f38c70aaa9d7.jpg)
2
![banner_p2p_jobs jhon-01](https://cloud.githubusercontent.com/assets/17308060/15918456/bc6f52c8-2dd0-11e6-92aa-64b0d29fd56d.jpg)

**Comment by gabymado** [comment]
I like proposal 1 better, but I think it's still kind of stiff. I think the straight lines makes it kind of corporate. Maybe take them out. Also, the name will be replaced by the logo, right? @jhonmarquez92 @arnaldos

**Comment by proseuz** [comment]
yes, the name will be replaced but must define the logo for that.@gabymado

**Comment by arnaldos** [comment]
@rosanacoronado @jhonmarquez92 @gabymado here in this banner maybe can use the sketch element, that was used in clasified banner. maybe can try use a young people to this and can look more fresh and not so stiff.

**Comment by rosanacoronado** [comment]
@arnaldos @jhonmarquez92 @gabymado these are new proposals with images of younger people. I'm using a tentative logo as an example. I will continue working on more proposals.

Proposal_3
![banner_p2p_jobs_2-01](https://cloud.githubusercontent.com/assets/19508456/15925161/e0a5f424-2dff-11e6-8c3e-1ef050146ec0.png)

Proposal_3_variation
![banner_p2p_jobs_1-01](https://cloud.githubusercontent.com/assets/19508456/15925163/e0addf72-2dff-11e6-8a10-938c5ab1e750.png)

Proposal_4
![banner_p2p_jobs_3-01](https://cloud.githubusercontent.com/assets/19508456/15925162/e0a87f00-2dff-11e6-812c-c16039146bc5.png)

**Comment by arnaldos** [comment]
@gabymado I like the proposal 3 because it transmits confidence and security when seeking a job solution.  what do you think ?

**Comment by proseuz** [comment]
i like the proposal 3 too. and this logo work so good

**Comment by gabymado** [comment]
I like 3 also. Let's leave it that way and adapt it to social media covers. And focus on finishing the logo please. I need to upload everything by your 2 pm today.

**Comment by arnaldos** [comment]
so @rosanacoronado @jhonmarquez92  please create all sizes to social media and send to @gabymado ones repleace the final logo in to banner . please resolve that after 12:00pm today

**Comment by rosanacoronado** [comment]
@arnaldos @jhonmarquez92 
Proposal_5
![banner_webpage_p2p_jobs_-01](https://cloud.githubusercontent.com/assets/19508456/15940176/9dbad6f8-2e44-11e6-83d9-bf824c49669c.png)

**Comment by rosanacoronado** [comment]
@arnaldos @gabymado @jhonmarquez92 

Proposal_6 with color variations
![banner_webpage_p2p_jobs_ejemplos1-01](https://cloud.githubusercontent.com/assets/19508456/15945293/7a3c8a98-2e5b-11e6-9e49-bdfc7412feab.png)

![banner_webpage_p2p_jobs_ejemplos2-01](https://cloud.githubusercontent.com/assets/19508456/15945294/7a3d4230-2e5b-11e6-8e0d-b90f09d820da.png)

![banner_webpage_p2p_jobs_ejemplos3-01](https://cloud.githubusercontent.com/assets/19508456/15945295/7a434e8c-2e5b-11e6-8aa2-d6cac6396436.png)

Proposal_7 with color variations
![banner_webpage_p2p_jobs_ejemplos4-01](https://cloud.githubusercontent.com/assets/19508456/15945296/7a4d21dc-2e5b-11e6-9c5c-212abf50f7a4.png)

![banner_webpage_p2p_jobs_ejemplos5-01](https://cloud.githubusercontent.com/assets/19508456/15945297/7a4d6c14-2e5b-11e6-8cfc-b27b386c8647.png)

Proposal_8
![banner_webpage_p2p_jobs_ejemplos6-01](https://cloud.githubusercontent.com/assets/19508456/15945292/7a31588a-2e5b-11e6-9444-4b9f3b5af6e9.png)

Proposal_9
![banner_webpage_p2p_jobs_ejemplos7-01](https://cloud.githubusercontent.com/assets/19508456/15945811/ed4bcaa6-2e5d-11e6-8b92-f91a6596ec18.png)

**Comment by gabymado** [comment]
Nice! I like proposal 8. @arnaldos @rosanacoronado

**Comment by arnaldos** [comment]
yeah les´t work with proposal 8.  @rosanacoronado

**Comment by rosanacoronado** [comment]
ok, I will work on it
