### ISSUE TITLE
Create a Banner to Classifieds P2P App

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#864]
Issue Reference  #857

Image size 922x201
Image reference

![captura de pantalla 50](https://cloud.githubusercontent.com/assets/13594347/15610996/0d755b6a-23f2-11e6-8523-96b2c5bd441b.png)

**Comment by GustavoDeMoura** [comment]
Muchachos aqui la propuesta para el Banner de Facebook. Mismo linea grafica que lo de lo demas pero con mas . Pronto subo otras versiones. En esta y los otros elementos les falta la incrustacion del logo que no se ah concretado cual es.

![webbanner](https://cloud.githubusercontent.com/assets/19398432/15797195/5dfbca16-29e6-11e6-9831-1477d852cf98.jpg)

**Comment by emmysm** [comment]
No me convence mucho la lupa ahí. Me gustan los colores, y optaría porque los vectores que están de fondo en el background fueran un poco más visible @GustavoDeMoura. Me gustaría ver otras propuestas.

**Comment by Joseangel2v** [comment]
![922x201](https://cloud.githubusercontent.com/assets/17457499/15883348/3759b3c2-2d11-11e6-9062-d1cb28afe38a.png)

**Comment by Joseangel2v** [comment]
@gabymado @emmysm @arnaldos

**Comment by arnaldos** [comment]
listo !!
