### ISSUE TITLE
Create a Generic Profile Image to DAP Platform

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#865]
Profile Image Unisex, to put in default profile

**Comment by emmysm** [comment]
Propuesta 1
![profile-02](https://cloud.githubusercontent.com/assets/15143489/15691023/4ab73c1c-2750-11e6-9429-c4610bc8fd5f.png)

@nindriago

**Comment by ivonnesantos** [comment]
@emmysm me gusta mas el dos pero puedes hacer una opcion sin gradient y creo que esto debe quedar bien con todas las aplicaciones de la DAP el azul no parece una buena opcion al menos que se haga una version para cada una de las aplicaciones que no desentone no que opinan @nindriago @arnaldos

**Comment by emmysm** [comment]
Sí, pensé que podía ser un color para cada app. A @nindriago le gustó esta opción por ser unisex. @arnaldos @ivonnesantos

**Comment by ivonnesantos** [comment]
@emmysm a mi me gusta el patron la linea circular el icono de arriba es menos distintivo del sexo asi que puede que funcione mejor que el dos pero el gradient no me gusta; en la user no se va a ver bien, por ejemplo porque el navigation drawer de la user ya tiene un gradient en el menu hecho de una forma distinta asi que por eso no me gusta solo eso de resto si me gusta y se hacen varias versiones en los colores adecuados.

**Comment by emmysm** [comment]
![profile](https://cloud.githubusercontent.com/assets/15143489/15697689/5884d6c0-2786-11e6-9870-7af0a2288505.png)
