### ISSUE TITLE
Create a banner to Asset Factory 

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#866]
1025x500 pixeles
Fecha de entrega: 06/07/2016
Diseñador: @Joseangel2v 
Desarrollador encargado: @nindriago 
Diseñadora encargada: @emmysm

**Comment by emmysm** [comment]
@Joseangel2v encargate de este caso, porfa.

**Comment by Joseangel2v** [comment]
P-1 
![b8](https://cloud.githubusercontent.com/assets/17457499/16634541/43b0ecb6-439c-11e6-9502-adb3feabe8ae.png)

**Comment by Joseangel2v** [comment]
P-2
![b7](https://cloud.githubusercontent.com/assets/17457499/16634558/52feb6ee-439c-11e6-93f3-89fe4ed516bf.png)

**Comment by Joseangel2v** [comment]
P-3
![b2](https://cloud.githubusercontent.com/assets/17457499/16634596/75466314-439c-11e6-9090-68b24e443976.png)

**Comment by Joseangel2v** [comment]
P-4
![b6](https://cloud.githubusercontent.com/assets/17457499/16655988/d3ef9e7e-442a-11e6-90bc-b0e6d1f8110e.png)

**Comment by Joseangel2v** [comment]
P-5
![b5](https://cloud.githubusercontent.com/assets/17457499/16634654/9c0277d6-439c-11e6-962d-e05c8ae76be8.png)

**Comment by Joseangel2v** [comment]
P-6
![b1](https://cloud.githubusercontent.com/assets/17457499/16634668/aa45dd56-439c-11e6-9b08-3bdb42bbbead.png)

**Comment by Joseangel2v** [comment]
P-7
![b3](https://cloud.githubusercontent.com/assets/17457499/16634685/c48e7e84-439c-11e6-8a25-3b8c2555a25d.png)

**Comment by Joseangel2v** [comment]
P-8
![b4](https://cloud.githubusercontent.com/assets/17457499/16634699/d723ded6-439c-11e6-9af2-d9bfe6a2cce5.png)

**Comment by emmysm** [comment]
@Joseangel2v haz otras propuestas partiendo de la p-7

**Comment by Joseangel2v** [comment]
P-9
![1b](https://cloud.githubusercontent.com/assets/17457499/16668445/fd597882-445e-11e6-8af7-2b33a52d74a6.png)

**Comment by Joseangel2v** [comment]
P-10
![2b](https://cloud.githubusercontent.com/assets/17457499/16668463/106ad54c-445f-11e6-81f1-eaba3bbd0d0f.png)

**Comment by Joseangel2v** [comment]
P-11
![3b](https://cloud.githubusercontent.com/assets/17457499/16668469/20544bc8-445f-11e6-9ea8-2465e8861507.png)

**Comment by Joseangel2v** [comment]
P-12
![4b](https://cloud.githubusercontent.com/assets/17457499/16668480/2ad8f4cc-445f-11e6-8281-185ae752a875.png)

**Comment by Joseangel2v** [comment]
P-13
![5b](https://cloud.githubusercontent.com/assets/17457499/16668500/3c8dd50c-445f-11e6-89af-c8c633b7d84e.png)

**Comment by Joseangel2v** [comment]
P-14
![6b](https://cloud.githubusercontent.com/assets/17457499/16668513/4a3f1666-445f-11e6-994c-d14011a5d87a.png)

**Comment by Joseangel2v** [comment]
P-15
![7b](https://cloud.githubusercontent.com/assets/17457499/16668548/7207ba54-445f-11e6-8c0f-4f192876b400.png)

**Comment by Joseangel2v** [comment]
P-16
![8b](https://cloud.githubusercontent.com/assets/17457499/16668559/8170b1f8-445f-11e6-8f44-78e730022a19.png)

**Comment by emmysm** [comment]
Me gusta la primera. 
-Baje el nombre de la wallet
- Reducir el tamaño del icono
- Dar más separación al icono del Texto
- Agregale sombra al icono y al texto a ver qué tal queda
- Asset Factory.

**Comment by Joseangel2v** [comment]
P-17
![9b](https://cloud.githubusercontent.com/assets/17457499/16672744/0a7b4678-4476-11e6-9a97-bab466114960.png)

**Comment by arnaldos** [comment]
@Joseangel2v @emmysm prueba una versión usando elementos que representen los asset

**Comment by Joseangel2v** [comment]
P-18
![1b](https://cloud.githubusercontent.com/assets/17457499/16810267/4b2f1468-48f1-11e6-8a7b-638e04c8795a.png)

**Comment by Joseangel2v** [comment]
P-19
![2b](https://cloud.githubusercontent.com/assets/17457499/16810283/56c535fa-48f1-11e6-9612-ade8b8c16be0.png)

**Comment by Joseangel2v** [comment]
P-20
![3b](https://cloud.githubusercontent.com/assets/17457499/16810298/5f64de72-48f1-11e6-8c29-afd72c04b314.png)

**Comment by Joseangel2v** [comment]
P-21
![4b](https://cloud.githubusercontent.com/assets/17457499/16810311/6d103e5e-48f1-11e6-80b3-8470606d3b9b.png)

**Comment by Joseangel2v** [comment]
P-22
![5b](https://cloud.githubusercontent.com/assets/17457499/16810325/7e812edc-48f1-11e6-880b-2b3280b7b499.png)

**Comment by Joseangel2v** [comment]
P-23
![6b](https://cloud.githubusercontent.com/assets/17457499/16810797/655f7556-48f3-11e6-8b5b-e13449614a25.png)

**Comment by Joseangel2v** [comment]
P-24
![7b](https://cloud.githubusercontent.com/assets/17457499/16810368/9cd9a774-48f1-11e6-899a-26751829d083.png)

**Comment by Joseangel2v** [comment]
P-25
![8b](https://cloud.githubusercontent.com/assets/17457499/16810388/ac5c41e8-48f1-11e6-9f1b-417fbc9046f4.png)

**Comment by Joseangel2v** [comment]
P-26
![9b](https://cloud.githubusercontent.com/assets/17457499/16810414/c0194550-48f1-11e6-8281-70c998eca244.png)

**Comment by emmysm** [comment]
Incluye los Assets en las propuestas, me gustaría que fuera un diseño plano para este banner. @Joseangel2v

**Comment by arnaldos** [comment]
@emmysm @Joseangel2v  puede andar por la onda del P-24 pero obviamente me gustaría ver algo de los asset. centra los elementos se ven mas a la derecha.

**Comment by Joseangel2v** [comment]
P-27
![5b](https://cloud.githubusercontent.com/assets/17457499/16858590/022b5848-49f6-11e6-8f12-d41060ed9b75.png)

**Comment by Joseangel2v** [comment]
P-28
![2b](https://cloud.githubusercontent.com/assets/17457499/16858609/23fac30a-49f6-11e6-9ba7-62beec0c170b.png)

**Comment by Joseangel2v** [comment]
P-29
![3b](https://cloud.githubusercontent.com/assets/17457499/16858613/2cc7610a-49f6-11e6-87e3-0188db968301.png)

**Comment by Joseangel2v** [comment]
P-30
![4b](https://cloud.githubusercontent.com/assets/17457499/16858631/45cdaef2-49f6-11e6-9e6a-ff4ae2201db6.png)

**Comment by Joseangel2v** [comment]
P-31
![7b](https://cloud.githubusercontent.com/assets/17457499/16858647/5d1f8530-49f6-11e6-861e-5c24428638e5.png)

**Comment by Joseangel2v** [comment]
P-32
![8b](https://cloud.githubusercontent.com/assets/17457499/16858656/6a376602-49f6-11e6-8b00-e540c4b6362c.png)

**Comment by Joseangel2v** [comment]
P-33
![1b](https://cloud.githubusercontent.com/assets/17457499/16858668/825ae7a4-49f6-11e6-932e-66e8f8ae7918.png)
@emmysm @arnaldos Correciones Finales

**Comment by emmysm** [comment]
P33 =D @Joseangel2v
