### ISSUE TITLE
Create Webpage Image Banner for P2P Classifieds App

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#867]
Image size 922x201
Image reference

![captura de pantalla 50](https://cloud.githubusercontent.com/assets/13594347/15610996/0d755b6a-23f2-11e6-8523-96b2c5bd441b.png)

Date deliver 3 proponsal 31/06/2016

**Comment by Joseangel2v** [comment]
![922x201](https://cloud.githubusercontent.com/assets/17457499/15883435/f4da23e6-2d11-11e6-8c6d-0c37d6afcf9a.png)

**Comment by arnaldos** [comment]
:+1:  listo
