### ISSUE TITLE
Create Facebook Image Banner for P2P Classifieds App

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#868]
Image size 982x364
Date deliver 3 proponsal 31/06/2016

**Comment by GustavoDeMoura** [comment]
@arnaldos @emmysm 

Muchachos aqui la propuesta para el Banner de Facebook. Mismo lineamiento que la del avatar pero con mas trabajo e informacio. Pronto subo otras versiones.

En esta y los otros elementos les falta la incrustacion del logo que no se ah concretado cual es.

![portadafaceapp](https://cloud.githubusercontent.com/assets/19398432/15797184/1cbcb2fe-29e6-11e6-82e1-2c22592fcf81.jpg)

**Comment by Joseangel2v** [comment]
P-1
![banners 1](https://cloud.githubusercontent.com/assets/17457499/15830903/83891afe-2be4-11e6-81ab-dd948ea7d5b6.png)

**Comment by Joseangel2v** [comment]
P-2
![banners 2](https://cloud.githubusercontent.com/assets/17457499/15830917/92cb0216-2be4-11e6-80b5-f0baaa69b10d.png)

**Comment by Joseangel2v** [comment]
P-3
![banners 3](https://cloud.githubusercontent.com/assets/17457499/15831013/266d75a8-2be5-11e6-8095-7ab37fd9123b.png)

**Comment by Joseangel2v** [comment]
P-4
![banners 4](https://cloud.githubusercontent.com/assets/17457499/15831074/7df34d3e-2be5-11e6-8f2d-ebfa21cc5176.png)

**Comment by emmysm** [comment]
i like proposal 3. but, Can you mix @GustavoDeMoura proposals? @Joseangel2v

**Comment by GustavoDeMoura** [comment]
I will mix the proposals to!! like we talk @emmysm

**Comment by GustavoDeMoura** [comment]
Lo prometido es deuda. Version 1 y 2 respectivamente de la mezclaa de propuestas para el banner de la web @emmysm @arnaldos Creo que funciona mejor la Segunda version, es mas limpia y entendible.

PD: ya ire montando lo otro poco a poco! mi inter no ayuda pero ahi voy.

![webbanner2](https://cloud.githubusercontent.com/assets/19398432/15877285/6a05f218-2ce9-11e6-8d60-8a0f2ede24d8.jpg)
![webbanner3](https://cloud.githubusercontent.com/assets/19398432/15877284/6a05b1fe-2ce9-11e6-8b3b-ee9e87dfe8a3.jpg)

**Comment by Joseangel2v** [comment]
P-5
![banners 5t](https://cloud.githubusercontent.com/assets/17457499/15878859/571b83da-2ce8-11e6-9596-f56ed1732e93.png)

**Comment by Joseangel2v** [comment]
![banners facebook](https://cloud.githubusercontent.com/assets/17457499/15883316/e4d9387a-2d10-11e6-8c33-17b7d19c4f41.png)

**Comment by Joseangel2v** [comment]
@gabymado @emmysm @arnaldos

**Comment by emmysm** [comment]
Genial! @Joseangel2v

**Comment by arnaldos** [comment]
listo !!
