### ISSUE TITLE
Create Facebook Image Profile for P2P Classifieds App 

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#869]
Image size 180x180

Date deliver 3 proponsal 31/06/2016

**Comment by GustavoDeMoura** [comment]
@arnaldos  @emmysm 

Muchachos aqui esta una propuesta para el avatar de Face, lo subi en baja calidad y otra cosa fue que no le pude poner stroke blanco al logo porque no es un png es una imagen que recorte de la que subio Emmy

![avatar1](https://cloud.githubusercontent.com/assets/19398432/15797119/1268574c-29e4-11e6-9d3e-16ea5c4ecd5b.jpg)

PD: Pronto subire mas.

**Comment by Joseangel2v** [comment]
P-1
![p1](https://cloud.githubusercontent.com/assets/17457499/15831083/8bcc79a8-2be5-11e6-9492-8d7f61648c43.png)

**Comment by Joseangel2v** [comment]
P-2
![p2](https://cloud.githubusercontent.com/assets/17457499/15831145/f0a82458-2be5-11e6-8441-85ac639127f7.png)

**Comment by Joseangel2v** [comment]
P-3
![p3](https://cloud.githubusercontent.com/assets/17457499/15831168/1911df6a-2be6-11e6-861b-0660e4de4429.png)

**Comment by Joseangel2v** [comment]
P-4
![p4](https://cloud.githubusercontent.com/assets/17457499/15831175/202874a8-2be6-11e6-811b-2a1089219a2b.png)

**Comment by Joseangel2v** [comment]
P-5
![p6](https://cloud.githubusercontent.com/assets/17457499/15831196/304bcf88-2be6-11e6-8340-27c2dd8f5f62.png)

**Comment by Joseangel2v** [comment]
P-6
![p7](https://cloud.githubusercontent.com/assets/17457499/15831208/5434b860-2be6-11e6-9a6e-2e10f56b590b.png)

**Comment by Joseangel2v** [comment]
P-7
![p8](https://cloud.githubusercontent.com/assets/17457499/15831219/5cc3d66e-2be6-11e6-8b58-922af1f57aad.png)

**Comment by Joseangel2v** [comment]
P-8
![p5](https://cloud.githubusercontent.com/assets/17457499/15831230/6a8926be-2be6-11e6-9112-86d3b5c2a3dd.png)

**Comment by emmysm** [comment]
![profile-180-x-180](https://cloud.githubusercontent.com/assets/15143489/15876604/15c0be7e-2cd8-11e6-8a1a-04f4a05b58fa.png)

@arnaldos @gabymado

**Comment by GustavoDeMoura** [comment]
Lo prometido es deuda. Version 1 y 2 respectivamente de la mezclaa de propuestas @emmysm @arnaldos  personalmente creo que funciona mejor la segunda.

PD: ya ire montando lo otro poco a poco! mi inter no ayuda pero ahi voy.

![avatarclassiified](https://cloud.githubusercontent.com/assets/19398432/15877231/1d0e3600-2ce9-11e6-872e-b61c0b5be401.jpg)
![avatarclassiified2](https://cloud.githubusercontent.com/assets/19398432/15877230/1ce7c768-2ce9-11e6-9f07-b90b8ca6ba08.jpg)
