### ISSUE TITLE
Fiat currency Dollar/Fermat Moneda 3d

### ISSUE THREAD

**Issue by jonathanborges3d** [bitDubai/fermat-graphic-design#87]
Tomé como referencia ésta moneda para el diseño inicial

![1-dollar-george-washington-1789-1797](https://cloud.githubusercontent.com/assets/13649739/9644800/d7dc6f9e-5191-11e5-9298-4f2e977a7e36.jpg)

Primeros bocetos:
![fiat_dollar_4](https://cloud.githubusercontent.com/assets/13649739/9644680/4f523c76-5191-11e5-8434-a7d97a2b2ee6.png)
![fiat_dollar_1](https://cloud.githubusercontent.com/assets/13649739/9644681/4f6d72ca-5191-11e5-9298-85993bbeeb00.png)
![fiat_dollar_2](https://cloud.githubusercontent.com/assets/13649739/9644682/4f85785c-5191-11e5-9423-935ec4f10534.png)
![fiat_dollar_3](https://cloud.githubusercontent.com/assets/13649739/9644683/4fbf5e1e-5191-11e5-9069-bdb67e74084f.png)

Detrás del logo de fermat puede haber otro elemento como el puente Golden Gate o un águila, sinó puede extenderse un poco para que quede ajustado a la circunferencia interior.

Se puede hacer toda en oro u otro material o combinado como se hizo con el bitcoin. 

@Luis-Fernando-Molina

**Comment by Luis-Fernando-Molina** [comment]
Segui avanzando por favor. Recordá que no buscamos que sea la moneda anterior con otro loguito con lo cual debiera tener distinto tamaño, quizas material, grosor, borde, estilo, etc.

**Comment by jonathanborges3d** [comment]
Ok @Luis-Fernando-Molina , nuevas propuestas ya en modelado poligonal.

Aquí retiré el anillo exterior y coloqué el texto en el cuadrante superior izquierdo. 

Hice dos versiones, la segunda tiene la silueta de la bandera ondeante detrás de la estatua.

La palabra Fermat está en bajo relieve alrededor del borde exterior, donde iba el calado en la otra moneda.

![fiat_dollar_5](https://cloud.githubusercontent.com/assets/13649739/9669819/3c3f1ea2-5253-11e5-9563-59016e80d48d.png)

![fiat_dollar_6](https://cloud.githubusercontent.com/assets/13649739/9669873/793ab97e-5253-11e5-806b-6522add70637.jpg)

![fiat_dollar_7](https://cloud.githubusercontent.com/assets/13649739/9669887/8bf2a6ee-5253-11e5-852a-e03da951fd11.jpg)

![fiat_dollar_8](https://cloud.githubusercontent.com/assets/13649739/9671732/cb66f590-525e-11e5-8281-68233c8065b9.jpg)

![fiat_dollar_9](https://cloud.githubusercontent.com/assets/13649739/9671743/e1c202a8-525e-11e5-9c68-2f9d51229bf8.jpg)

![fiat_dollar_10](https://cloud.githubusercontent.com/assets/13649739/9671805/518dcf22-525f-11e5-9262-2f6be08ea42f.jpg)

**Comment by Luis-Fernando-Molina** [comment]
Va bien la que tiene la bandera y la estatua dorada, segui avanzando please

**Comment by jonathanborges3d** [comment]
@Luis-Fernando-Molina Versión con el anillo exterior dorado.

![fiat_dollar_11](https://cloud.githubusercontent.com/assets/13649739/9702167/e91468d4-541b-11e5-8142-cfab370c9585.jpg)

![fiat_dollar_12](https://cloud.githubusercontent.com/assets/13649739/9702175/1f20eeca-541c-11e5-9c81-f1f76144dbc8.jpg)

Comparación de la escala con respecto a la moneda Bitcoin-Fermat:

![fiat_dollar_13](https://cloud.githubusercontent.com/assets/13649739/9702181/57cc677c-541c-11e5-9d13-62c237d37fab.jpg)

**Comment by jonathanborges3d** [comment]
@Luis-Fernando-Molina Primera versión del reverso de la moneda:

![fiat_dollar_14](https://cloud.githubusercontent.com/assets/13649739/9820069/5313d18a-587b-11e5-8830-ce55593f9acd.jpg)

![fiat_dollar_15](https://cloud.githubusercontent.com/assets/13649739/9820070/533140e4-587b-11e5-9ce2-581b5e5c579e.jpg)

**Comment by Luis-Fernando-Molina** [comment]
esta bien me gustaria que el fondo no sea la misma bandera que esta del otro lado

**Comment by jonathanborges3d** [comment]
@Luis-Fernando-Molina Probé con el puente Golden Gate en dos versiones:

![fiat_dollar_16](https://cloud.githubusercontent.com/assets/13649739/9838052/332a6c00-5a1d-11e5-96f1-181f7f131990.jpg)

![fiat_dollar_17](https://cloud.githubusercontent.com/assets/13649739/9838053/333d54dc-5a1d-11e5-9fba-227abe300963.jpg)

![fiat_dollar_18](https://cloud.githubusercontent.com/assets/13649739/9838054/3373aaaa-5a1d-11e5-9b6b-65e1d3f86c0a.jpg)

![fiat_dollar_19](https://cloud.githubusercontent.com/assets/13649739/9838055/33ace536-5a1d-11e5-97c4-f0576308ed5c.jpg)

**Comment by Luis-Fernando-Molina** [comment]
la idea del puente esta bien, pero el logo no puede estar desplazado. El puente debe ser un fondo y aun asi notarse cual es.

**Comment by jonathanborges3d** [comment]
@Luis-Fernando-Molina Versión con el puente en bajo relieve y con un material metálico más oscuro, tal vez así se note mejor.

![fiat_dollar_20](https://cloud.githubusercontent.com/assets/13649739/9890062/8488d0b8-5bc7-11e5-98e5-d28b5ee9e11b.jpg)

**Comment by Luis-Fernando-Molina** [comment]
si, esta bien, proba ponerle alguna textura a todo lo que no es puente, alguna rugosidad

**Comment by jonathanborges3d** [comment]
@Luis-Fernando-Molina Hice una prueba con un patrón de puntos. Qué opinas?

![fiat_dollar_21](https://cloud.githubusercontent.com/assets/13649739/9917705/e9426d5a-5c8c-11e5-88f3-e661ce692ee4.jpg)

**Comment by Luis-Fernando-Molina** [comment]
puede ser

**Comment by jonathanborges3d** [comment]
@Luis-Fernando-Molina Tienes alguna otra sugerencia para ésta moneda o puede quedar así? Es para ir reuniéndolas en una sola escena con las versiones finales de cada una.

**Comment by jonathanborges3d** [comment]
@Luis-Fernando-Molina Cuando puedas me dices si tienes otras sugerencias para ésta moneda antes de reunirlas en una sola escena.

**Comment by Luis-Fernando-Molina** [comment]
no tengo, puede quedar asi.
