### ISSUE TITLE
 Create an icon to identify the contact if are an Artist or a Fan in the Community

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#870]
Acual Referece

Star icon 

![star](https://cloud.githubusercontent.com/assets/13594347/15657723/64247c9c-267d-11e6-957c-10bacefa0bc0.png)

User icon (FAN)

![people](https://cloud.githubusercontent.com/assets/13594347/15657730/85321750-267d-11e6-9276-3ffe8d8d4f8b.png)

View

![conns](https://cloud.githubusercontent.com/assets/13594347/15657679/ce974bdc-267c-11e6-875e-db1d2bbc8810.png)

**Comment by proseuz** [comment]
1 
![connections-01](https://cloud.githubusercontent.com/assets/17308060/15709225/62e4c91c-27cd-11e6-87b7-135a16b1de1a.png)
@arnaldos

**Comment by arnaldos** [comment]
@jhonmarquez92  That works !! what do you think about @darkestpriest @lostwood ?

**Comment by arnaldos** [comment]
for me is fine this icon

**Comment by lostwood** [comment]
I think this is it, goob job

**Comment by proseuz** [comment]
Great! I will create resources

**Comment by darkestpriest** [comment]
I like it!!

**Comment by proseuz** [comment]
Resources sent

**Comment by arnaldos** [comment]
nice !!! so i close it
