### ISSUE TITLE
Create a component that allows the user to control their own location

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#872]
It is a component that helps the user to set the update frequency and accuracy will be the location of User Profile

**Comment by arnaldos** [comment]
@furszy 

![geolocalization](https://cloud.githubusercontent.com/assets/13594347/15800467/820d6384-2a44-11e6-857f-65fb3e021a1a.jpg)

**Comment by furszy** [comment]
Ok, I think that is better show a dialog with the options. The fragment to build this kind of screens is already build it.
