### ISSUE TITLE
Create a Geolacation Filter Component

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#875]

**Comment by arnaldos** [comment]
@franklinmarcano1970 @furszy @nattyco @nelsonalfo @darkestpriest @nindriago 

Actual colors are like chat community, but this can be customized according to app.

![geolocation-filter](https://cloud.githubusercontent.com/assets/13594347/15800782/c128dd66-2a4c-11e6-8d4e-75b0b2a87a06.jpg)

**Comment by furszy** [comment]
No le veo necesidad a tener 4 pantallas para la selección de la ubicación, debería ser un texto autocompletable parecido o igual el de google maps

**Comment by arnaldos** [comment]
dejame revisar google maps para ver de que me hablas

**Comment by arnaldos** [comment]
@furszyy @darkestpriest Aqui podemos ver una secuencia de búsqueda, con el filtro de geo localización aplicada en chat 

![chat_browser](https://cloud.githubusercontent.com/assets/13594347/15932372/3fe256a6-2e25-11e6-81b4-e6caa1712bf9.jpg)

**Comment by darkestpriest** [comment]
Yo lo veo bien, me imagino que cada community tendrá algo parecido en su diseño.
