### ISSUE TITLE
 Change the color of the logos of the platforms to the new color palette logo fermat

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#876]
Date of delivery 06 Jun-16  

Reference Logo

![fermat_cer](https://cloud.githubusercontent.com/assets/13594347/15811314/4c5aa502-2b71-11e6-9fb3-87718762eee0.png)
#### RGB  Colors

![colorcode_logo_rgb](https://cloud.githubusercontent.com/assets/13594347/15811355/a4817d78-2b71-11e6-892d-febbb9c63b79.png)
#### Web Colors

![colorcode_logo_web](https://cloud.githubusercontent.com/assets/13594347/15811345/835c2daa-2b71-11e6-87e3-8cebfa105112.png)

**Comment by saraguerrerot** [comment]
![fermat_logo_muestra-01](https://cloud.githubusercontent.com/assets/19808868/15979494/1190e02e-2f2e-11e6-981d-5205684cfdf8.jpg)  @arnaldos @emmysm @Luis-Fernando-Molina

**Comment by emmysm** [comment]
En la COR platform me gustaría que las billeteras fuesen de otro color, no se distinguen mucho. Y de tokenly platform también quisiera ver otros colores @saraguerrerot  n.n

**Comment by arnaldos** [comment]
@emmysm @saraguerrerot revisen estén todas las plataformas creo falta CHT, CER, de las que veo de todas manera les dejo en link del web Dev http://dev.fermat.org/ en linea general esta bien :smile:

**Comment by emmysm** [comment]
Sí, estás en lo correcto @arnaldos, faltan 12 plataformas. Los archivos tenían errores y no abrían. Pero ya se solucionó y se está trabajando en eso :D

**Comment by emmysm** [comment]
En general me parece que se ven bien. Qué opinas? @arnaldos

**Comment by arnaldos** [comment]
comparto la misma opinion !

**Comment by saraguerrerot** [comment]
![fermat_logo_muestra](https://cloud.githubusercontent.com/assets/19808868/16021244/5e79a0b6-317b-11e6-8950-43920659cb0e.jpg)
@arnaldos @emmysm @Luis-Fernando-Molina

**Comment by emmysm** [comment]
@saraguerrerot, faltan dos plataformas por colocar el nombre. Fermat DTG (daiting platform) que es la 3 era de la 3era columna. y Fermat WRD ( world platform) la segunda de la cuarta columna. Fermat TKR tiene un nodito suelto, puedes corregir eso, porfa. De resto va muy bien @saraguerrerot

**Comment by saraguerrerot** [comment]
![fermat_logo_muestra](https://cloud.githubusercontent.com/assets/19808868/16024316/ee76c342-318a-11e6-9adb-b12a25a21644.jpg)
listo! @arnaldos @emmysm

**Comment by emmysm** [comment]
Genial, @saraguerrerot! Qué opinas, @arnaldos ?

**Comment by arnaldos** [comment]
me gustaria ver un poco del verde, de la paleta del logo.

**Comment by saraguerrerot** [comment]
![fermat_logo_muestra-01](https://cloud.githubusercontent.com/assets/19808868/16057237/244ecd54-3247-11e6-8d32-4efad56e9269.jpg)
@arnaldos @emmysm

**Comment by emmysm** [comment]
Este caso vamos a dejarlo en espera.
