### ISSUE TITLE
Improve the design of the profile of Bitcoin Wallet App

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#877]
This profile will also be used in Bitcoin Wallet, Loss Protected Wallet and Fermat Wallet

Actual View Profile

![profile](https://cloud.githubusercontent.com/assets/13594347/15811757/37809ce0-2b76-11e6-83d0-f38a8bbaa926.png)

take reference profile of the chat wallet

![profile](https://cloud.githubusercontent.com/assets/13594347/15811798/fb970010-2b76-11e6-8bcb-bf80bc5695fa.jpg)

**Comment by Jessicafp** [comment]
![profile-13](https://cloud.githubusercontent.com/assets/19536846/15939043/d42535f8-2e3f-11e6-83f5-3616b4407e54.png)

**Comment by arnaldos** [comment]
@Jessicafp por favor replantea las propuestas, las pantallas no pueden ser tan coloridas debes mantener standarizar la paleta usada en la app principal.

**Comment by Jessicafp** [comment]
![profile-13](https://cloud.githubusercontent.com/assets/19536846/15969310/4d403744-2ef9-11e6-9843-74b7bdd4f612.png)

**Comment by arnaldos** [comment]
para el background cro no me explique bien, deben ser mas simples ya que si hay muchos elementos puedan interrumpir en la lectura del usuario. puede andar por la version 6. coloca el elemento que te indica que no hay user en el espacio de la foto. y genere el resto de la secuencia de la pantallas que acompañan las acciones que tiene un profile

**Comment by Jessicafp** [comment]
![profile-16](https://cloud.githubusercontent.com/assets/19536846/15987698/159f4934-2ffc-11e6-8326-e5faf6139672.png)

**Comment by Jessicafp** [comment]
![profile-28](https://cloud.githubusercontent.com/assets/19536846/16050542/e47d287c-3225-11e6-9eb4-a1fac327f687.png)

**Comment by arnaldos** [comment]
@Jessicafp 
- El boton de Accept circular :white_check_mark: 
  (Botones en gradientes no funcionan colocalos en tonos planos)
- Para el perfil ese plano que divide la pantalla en dos usalo de esta forma con colores planos. no gradientes.
  ![12](https://cloud.githubusercontent.com/assets/13594347/16052401/ef4a4124-322d-11e6-9f66-90db17dec06f.jpg)
- El background del settings puede ser una color claro u oscuro.

**Comment by Jessicafp** [comment]
![profile-28](https://cloud.githubusercontent.com/assets/19536846/16056511/9ef1b704-323f-11e6-8c18-337ed1660455.png)

**Comment by Jessicafp** [comment]
![profile-25](https://cloud.githubusercontent.com/assets/19536846/16219558/01b3e4fa-3751-11e6-9e9f-76987bd99b0f.png)

**Comment by arnaldos** [comment]
@Jessicafp las ultimas 2 pantallas están alineadas, las anteriores no lo están plz alinea el resto a las ultimas dos

**Comment by Jessicafp** [comment]
![profile-24](https://cloud.githubusercontent.com/assets/19536846/16237853/f0b131d8-37a7-11e6-9dcf-ae14472a019d.png)

**Comment by arnaldos** [comment]
no debe verse hueco el icono cuando esta vacio

**Comment by arnaldos** [comment]
fondo blanco

**Comment by Jessicafp** [comment]
![profile-24-24](https://cloud.githubusercontent.com/assets/19536846/16241088/f29b117c-37b5-11e6-9b3a-fde5f0917a59.png)

**Comment by arnaldos** [comment]
versión 2 :+1:

**Comment by Jessicafp** [comment]
![final-22](https://cloud.githubusercontent.com/assets/19536846/16245247/be7a78ce-37c9-11e6-8294-dd70c749018d.png)

**Comment by arnaldos** [comment]
@Jessicafp para este caso busca el estilo gráfico que se definió en el caso #883. para estandarizar ya que ambos van de la mano

**Comment by m471c4** [comment]
@Jessicafp te comparto los códigos de color del caso #883 :

Color principal (action bar) # 21386D 
Accent color (subtitles, etc) # 7DD5CA

**Comment by Jessicafp** [comment]
![profile-22](https://cloud.githubusercontent.com/assets/19536846/16493482/6d9e1234-3eaf-11e6-9d01-1ae4527cd340.png)

**Comment by arnaldos** [comment]
@Jessicafp estas trabajando en RBG los colores se ven lavados

**Comment by arnaldos** [comment]
revisa eso plz

**Comment by Jessicafp** [comment]
![profile-22](https://cloud.githubusercontent.com/assets/19536846/16500924/a5927dc6-3ed0-11e6-8608-31bd0ac47032.png)

**Comment by arnaldos** [comment]
@Jessicafp Debajo del actionbar, colocaste un plano azul claro yo buscaria de revisar eso no creo se vea del todo bien como lo estas usando, replantea eso plz. en el settings los selectores en gris.
