### ISSUE TITLE
Improve the design of the profile of Asset Issuer App

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#878]
Standardize the design with the app

Actual View Profile

![profile_issuer](https://cloud.githubusercontent.com/assets/13594347/15811822/2eb961fe-2b77-11e6-8244-4da634969aa7.png)

take reference profile of the chat wallet

![profile](https://cloud.githubusercontent.com/assets/13594347/15811798/fb970010-2b76-11e6-8bcb-bf80bc5695fa.jpg)

**Comment by karentvillegas** [comment]
@arnaldos @jhonmarquez92 

Propuestas:
1
![propuesta1](https://cloud.githubusercontent.com/assets/19273211/16354052/fac33260-3a50-11e6-97af-146f15e86d60.png)
2
![propuesta2](https://cloud.githubusercontent.com/assets/19273211/16354053/ffb02ecc-3a50-11e6-8e10-16b77bd2f1f4.png)
3
![propuesta3](https://cloud.githubusercontent.com/assets/19273211/16354054/04136380-3a51-11e6-9371-30324ce07a2b.png)
4
![propuesta4](https://cloud.githubusercontent.com/assets/19273211/16354058/0c10c640-3a51-11e6-9666-d9d7ab56d7db.png)
5
![propuesta5](https://cloud.githubusercontent.com/assets/19273211/16354059/106142d8-3a51-11e6-9a06-e4ac6c66f038.png)
6
![propuesta6](https://cloud.githubusercontent.com/assets/19273211/16354060/1678add2-3a51-11e6-88d0-aa9cc9256498.png)

**Comment by proseuz** [comment]
el título sería: Asset Ussuer Profile.
Le falta el espacio para el status
Crea las pantallas que faltan cómo las del ejemplo, es necesario ver la pantalla antes de rellenarla (ponle un icono de profile dentro del circulo)
va mas por la propuesta 2 @karentvillegas

**Comment by arnaldos** [comment]
@karentvillegas @jhonmarquez92 Para este caso la versión que mas se apega a la App es la versión 3, ya que el color rojo en esta app se usa muy sutil. no debe predominar mucho. 
por otro lado se deben aplicar los botones siguiendo el estilo grafico manejado dentro de la app, el icono de help debería de usarse uno diferente y mas pequeño. Los iconos del actionbar deben medir 24x24 el pading y 18x18 el icono en si. revisen eso.

cualquier otra duda también puede preguntar @nindriago que es el developer encargado de DAP

**Comment by karentvillegas** [comment]
@arnaldos @jhonmarquez92  A partir de la propuesta 3 y con los cambios sugeridos

![propuesta7](https://cloud.githubusercontent.com/assets/19273211/16438828/9413ce6a-3d7c-11e6-9883-b223a9500257.png)

**Comment by proseuz** [comment]
qué opinas @arnaldos ?

**Comment by nindriago** [comment]
bonitos, les avisare a los demas para que los revisen :+1:

**Comment by arnaldos** [comment]
@jhonmarquez92 @karentvillegas revisaron que los botones sean el mismo estilo de la app ?

**Comment by arnaldos** [comment]
mira aqui un ejemplo que me envio @ivonnesantos  ![pasted image at 2016_06_27 12_54 pm](https://cloud.githubusercontent.com/assets/13594347/16456705/9c270bf6-3de2-11e6-8c1f-24e9d44ab640.png)

**Comment by arnaldos** [comment]
@karentvillegas  por fa esto lo necesitamos con urgencia.

**Comment by karentvillegas** [comment]
@arnaldos @ivonnesantos @jhonmarquez92 ¿Qué tal va?

![propuesta9](https://cloud.githubusercontent.com/assets/19273211/16472818/52eda7d4-3e31-11e6-935b-2d4000fe6a39.png)

**Comment by arnaldos** [comment]
@karentvillegas pudieses colocar el aro de la foto del perfil en rojo creo que con eso ya estariamos, que opinan al respecto @ivonnesantos

**Comment by proseuz** [comment]
Muy de acuerdo con @arnaldos

**Comment by karentvillegas** [comment]
@arnaldos @ivonnesantos @jhonmarquez92 

![propuesta10](https://cloud.githubusercontent.com/assets/19273211/16475105/b63d6cd4-3e45-11e6-9640-b04108fca893.png)

**Comment by proseuz** [comment]
Looks great!

**Comment by proseuz** [comment]
esto está listo? para generar los recursos. @nindriago @arnaldos @ivonnesantos

**Comment by proseuz** [comment]
Recursos listos y enviados a  @nindriago

**Comment by nindriago** [comment]
@Fermat-ORG/skynet-team

**Comment by arnaldos** [comment]
perfecto !! buen trabajo chicos !! @nindriago  avisanos cuando cuando este implementado para cerrar el caso
