### ISSUE TITLE
Improve the design of the profile of Asset User App

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#879]
Standardize the design with the app

Actual View Profile

![profile_user](https://cloud.githubusercontent.com/assets/13594347/15811838/6ba9255e-2b77-11e6-9241-905a12dac002.png)

take reference profile of the chat wallet

![profile](https://cloud.githubusercontent.com/assets/13594347/15811798/fb970010-2b76-11e6-8bcb-bf80bc5695fa.jpg)

**Comment by arismendi227** [comment]
@jhonmarquez92  @arnaldos 
 propuestas 

1
![user1](https://cloud.githubusercontent.com/assets/19276382/16386669/4f12a466-3c5b-11e6-990a-6dc763d0169d.png)

2
![user2](https://cloud.githubusercontent.com/assets/19276382/16386672/52d28e40-3c5b-11e6-8d13-b16c12688f63.png)

3
![user3](https://cloud.githubusercontent.com/assets/19276382/16386677/5809e5ca-3c5b-11e6-8ded-0aabdca73f00.png)

4
![user4](https://cloud.githubusercontent.com/assets/19276382/16386680/5b6820ba-3c5b-11e6-9009-deefccb484cd.png)

5
![user5](https://cloud.githubusercontent.com/assets/19276382/16386687/5f08ca76-3c5b-11e6-9497-eea01e1cac2a.png)

6
![user6](https://cloud.githubusercontent.com/assets/19276382/16386700/6c14ac58-3c5b-11e6-819a-2c293997279b.png)

7
![user7](https://cloud.githubusercontent.com/assets/19276382/16386701/6eec6876-3c5b-11e6-8a7c-deab5a78a677.png)

**Comment by proseuz** [comment]
el título sería Asset User Profile.
Le falta el espacio para el status
Crea las pantallas que faltan cómo las del ejemplo, es necesario ver la pantalla antes de rellenarla 
va mas por la propuesta 5 incluye el verde de la paleta de esta app puedes ponerlo en los títulos de los espacios a rellenar @arismendi227

**Comment by arnaldos** [comment]
@arismendi227  @jhonmarquez92  
- Usa un fondo sutil que no afecte la lectura de los elementos.
- Revisar los botones siguiendo el estilo grafico manejado dentro de la App.
- El icono de help debería de usarse uno diferente y mas pequeño. Los iconos del actionbar deben medir 24x24 el pading y 18x18 el icono en si. revisen eso.

cualquier otra duda también puede preguntar @nindriago que es el developer encargado de DAP

**Comment by arismendi227** [comment]
@jhonmarquez92 @arnaldos 

propuesta

![user8](https://cloud.githubusercontent.com/assets/19276382/16436908/d544c10c-3d6b-11e6-9272-3a9a7e194508.png)

**Comment by proseuz** [comment]
qué opinas @arnaldos ?

**Comment by nindriago** [comment]
bonitos, les avisare a los demas para que los revisen :+1:

**Comment by arismendi227** [comment]
@jhonmarquez92 @arnaldos
cambios 

![user9](https://cloud.githubusercontent.com/assets/19276382/16474591/d027a0e6-3e41-11e6-8016-5ae3f80303c2.png)

**Comment by proseuz** [comment]
el action bar va azul @arismendi227

**Comment by proseuz** [comment]
@arnaldos @emmysm @nindriago  qué opinan?

**Comment by arismendi227** [comment]
@jhonmarquez92 @arnaldos @emmysm @nindriago

1
![user10](https://cloud.githubusercontent.com/assets/19276382/16475554/2efbe9fe-3e49-11e6-98b9-a458e0034567.png)

2
![user11](https://cloud.githubusercontent.com/assets/19276382/16475557/3a744c4a-3e49-11e6-8008-3a184d43b175.png)

**Comment by proseuz** [comment]
me gusta la 2 @arnaldos

**Comment by arnaldos** [comment]
@jhonmarquez92 generen los recursos y envíen con nerio plz !

**Comment by arismendi227** [comment]
@jhonmarquez92 @arnaldos
recursos listos y enviandos a @nindriago

**Comment by arnaldos** [comment]
perfecto !!!
