### ISSUE TITLE
Improve the design of the profile of Redem Point App

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#880]
Standardize the design with the app

Actual View Profile

![profile_rp](https://cloud.githubusercontent.com/assets/13594347/15811871/d83e6558-2b77-11e6-9759-1cb8dbb5bb90.png)

take reference profile of the chat wallet

![profile](https://cloud.githubusercontent.com/assets/13594347/15811798/fb970010-2b76-11e6-8bcb-bf80bc5695fa.jpg)

**Comment by ivonnesantos** [comment]
@mawisk elabora las mejoras de esta identity basandote en el diseño de la aplicacion reedem point #612 esta es la app tambien la puedes encontrar en el repositorio para que tomes los colores en esta ruta UIUX Design\APPs\Plataforma_DAP\APP_Redeem_point

Fecha de entrega primera propuesta Jueves 09/06/2016 en la tarde
Fecha entrega final 13/06/2016

**Comment by mawisk** [comment]
Propuesta 

![completo-01](https://cloud.githubusercontent.com/assets/19206540/15943297/2c5a788e-2e52-11e6-8dd3-185a612ce966.jpg)

@ivonnesantos

**Comment by ivonnesantos** [comment]
@mawisk Me gusta lo que no estoy segura es sobre el color del app bar dejame confirmarte si puede ser distinto te digo de aqui a la noche. La pantalla 3 no sabria decirte si es posible hacerla porque eso puede que ya tenga algo predeterminado esa duda nos la pueden aclarar @nindriago @pennyxz @javafrank

**Comment by arnaldos** [comment]
En el texto cámbiale titulo a Redeem Point Profile. la tercera vista sino me equivoco podría variar según el teléfono son componentes standar de android según su api. @nindriago @pennyxz @javafrank díganme si estoy errado o en lo correcto.

**Comment by mawisk** [comment]
Modificaciones 

![completo-01](https://cloud.githubusercontent.com/assets/19206540/16117135/623e72d2-339a-11e6-827c-1cae1a55e755.jpg)

@ivonnesantos

**Comment by ivonnesantos** [comment]
@mawisk  listo ahora si quedo bien genera los recursos y archivo de indicaciones.

**Comment by arnaldos** [comment]
@ivonnesantos @mawisk  como va esto ?

**Comment by ivonnesantos** [comment]
Bien ya lo aprobe mauricio me paso los recursos el viernes y hoy los subo

**Comment by arnaldos** [comment]
vale perfecto !

**Comment by arnaldos** [comment]
@ivonnesantos plz enviale esto a @nindriago

**Comment by mawisk** [comment]
En estas pantallas está algunas modificaciones que se le hicieron a los iconos de los botones.

![completo-01-01](https://cloud.githubusercontent.com/assets/19206540/16392936/3e512b26-3c78-11e6-9247-9e678eb01c56.jpg)

@ivonnesantos
