### ISSUE TITLE
Improve the design of the profile of Crypto Customer App

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#881]
##### The user can create multiple profiles

Standardize the design with the app

Actual View Profile

![profile_customer](https://cloud.githubusercontent.com/assets/13594347/15811969/081f71e4-2b79-11e6-88d4-8bcd62486d02.png)

![profile_customer_2](https://cloud.githubusercontent.com/assets/13594347/15811970/0821b77e-2b79-11e6-9774-154fc8aabdeb.png)

take reference profile of the chat wallet

![profile](https://cloud.githubusercontent.com/assets/13594347/15811798/fb970010-2b76-11e6-8bcb-bf80bc5695fa.jpg)

**Comment by GustavoDeMoura** [comment]
This is the new proposal interface for Crypto Profile App i tried to make it more modern and minimalist. @arnaldos 

I dont change the color because i dont know if is allowed.

![newinterface1](https://cloud.githubusercontent.com/assets/19398432/15896512/0c6a8fc8-2d67-11e6-83a3-2b577244725b.jpg) ![newinterface2](https://cloud.githubusercontent.com/assets/19398432/15896513/0c83f800-2d67-11e6-9884-cae63aea1d8d.jpg)
![newinterface3](https://cloud.githubusercontent.com/assets/19398432/15896515/0ca90e6a-2d67-11e6-94be-2f2f90196064.jpg) ![newinterface4](https://cloud.githubusercontent.com/assets/19398432/15896516/0cb4d272-2d67-11e6-9e0b-b101145495e9.jpg)
![newinterface5](https://cloud.githubusercontent.com/assets/19398432/15896514/0ca8ec00-2d67-11e6-8fdd-d494ab24cb78.jpg)

**Comment by emmysm** [comment]
@GustavoDeMoura, la tipografía está muy grande. Prueba usando Helvetica neue o Roboto. Yo no le agregaría stroke a los botones, y a los iconos puedes reducirle el tamaño.

**Comment by GustavoDeMoura** [comment]
Aqui estan los cambios aplicados solo a dos imagenes para ver si estan correctos y  de ser asi y notificados a mi persona seran cambiados en todos los demas, ya estan en tamaño y medidas exactas, solo falta que den luz verde y pongo el texto igual en todos los demas, ya acomode todo en tamaño y dpi correctos para mejor manejo 

@arnaldos @emmysm 

![newinterface5](https://cloud.githubusercontent.com/assets/19398432/15975542/50991822-2f24-11e6-8c73-7d22ce764654.jpg)

![newinterface1](https://cloud.githubusercontent.com/assets/19398432/15975737/68c2d496-2f25-11e6-90af-a5c9a6adf8d9.jpg)

**Comment by emmysm** [comment]
Coloca los textos en minúsculas, los sigo viendo bastante grandes. Centra en el action bar "customer identity"  Usa el mismo ícono de help que en las propuestas de Arnaldo, ya que es algo predeterminado para todas las apps @GustavoDeMoura. Coloca el stroke de la foto de perfil más fino, porfa. El botón de color plano.

**Comment by GustavoDeMoura** [comment]
Textos e Iconos arreglados, estan en medida. Centrar el "Customer identity" a mi criterio hace que pierda consistencia en el diseño con las demas faces de la app y deja menos espacio a los iconos de "add" y "help". Aparte hice otra propuesta con un color de fondo casi blanco que mejora la visibilidad y lectura y no es tan fuerte como el degrade de la primera version.

Igual cualquier cambio que consideren haganmelo saber y lo realizo al instante, @arnaldos  @emmysm 

![cryptoview](https://cloud.githubusercontent.com/assets/19398432/16028816/5ab5428a-31b9-11e6-91bd-f875e739e0ba.jpg)

**Comment by arnaldos** [comment]
Version 2 

Correcciones:
- Tipografia Helvetica Neue
- Revisa los colores estén en RGB se ven algo opacos.
- Cambia la posición de los colores del actionbar.
- Revisa los botones estandariza los según lo que hemos trabajado 
  adjunto imagen

![crypto-customers-08](https://cloud.githubusercontent.com/assets/13594347/16051148/545b2d72-3228-11e6-8831-773c04b13854.jpg)

![crypto-customers-06](https://cloud.githubusercontent.com/assets/13594347/16051149/545e849a-3228-11e6-88a0-289a707b4ae6.jpg)

Este profile te permite crear varias identidades debes mostrar una pantalla de como se veran cuando tienes una identidad y cuando tienes varias.

**Comment by GustavoDeMoura** [comment]
@arnaldos 
Aqui estan los views de como seria la app! elegi esta version dado que es la mas acorde con lo que ya me habias mostrado. en cuanto a colores y diseño. Ya esta tiene implementadas las correciones pedidas, tipografias, botones entre otros,

Lo otro que me pediste referente a como se veria las multiples identidades es lo que esta bajo creacion ahorita ya que estoy buscando la manera que no se salga del diseño y que sea minimalista, pero que muestre toda la informacion.

![cryptoview](https://cloud.githubusercontent.com/assets/19398432/16125081/54629278-33c8-11e6-93b4-ed17873226ce.jpg)

**Comment by arnaldos** [comment]
@GustavoDeMoura ok por aqui estamos bien solo agrégale la opcion de administrar varios perfiles como se trabajo en la broker en el issue #882

**Comment by GustavoDeMoura** [comment]
Correcion lista. 

Vista de perfiles como se trabajo en la Broker. @arnaldos 

![newinterface8a](https://cloud.githubusercontent.com/assets/19398432/16342430/7e5240c4-3a08-11e6-804b-87e99677ca67.jpg)

**Comment by arnaldos** [comment]
ok cambia el botton del check en fucia

**Comment by arnaldos** [comment]
tambien pon la secuencia para que se pueda apreciar completa

**Comment by GustavoDeMoura** [comment]
Color de boton fucsia y la secuencia completa del proceso. @arnaldos 

![cryptoview](https://cloud.githubusercontent.com/assets/19398432/16344452/0025d75a-3a13-11e6-915d-df82f9f8fdbe.jpg)

**Comment by arnaldos** [comment]
perfecto !! :+1:
