### ISSUE TITLE
Improve the design of the profile of Crypto Broker App

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#882]
##### The user can create multiple profiles

Standardize the design with the app

Actual View Profile
## ![profile_broker](https://cloud.githubusercontent.com/assets/13594347/15812030/d1a12274-2b79-11e6-8981-0132016061a4.png)

![screenshot_7](https://cloud.githubusercontent.com/assets/13594347/15812039/e1577e7a-2b79-11e6-9fd4-c51c2065bed0.png)

take reference profile of the chat wallet

![profile](https://cloud.githubusercontent.com/assets/13594347/15811798/fb970010-2b76-11e6-8bcb-bf80bc5695fa.jpg)

**Comment by m471c4** [comment]
@arnaldos improvements for the Crypto Broker Profile:

![profile](https://cloud.githubusercontent.com/assets/13468350/16142684/724161f8-3435-11e6-93c4-a25d971d9d5d.png)

**Comment by arnaldos** [comment]
@m471c4 is fine this just need it an element to say visible and not visible, try to incluyed that on mockups.

**Comment by m471c4** [comment]
@arnaldos yes! sorry, I forgot to put that element. I also added some improvements for the last version.

![profile_new](https://cloud.githubusercontent.com/assets/13468350/16166453/5fd1fe90-34b9-11e6-8b96-b3e179a4f146.png)

**Comment by m471c4** [comment]
@arnaldos @abicelis final version for this profile, with the "new profile" feature:

![profile_final](https://cloud.githubusercontent.com/assets/13468350/16168867/036deec0-34e6-11e6-8eb0-4e561260c119.png)

**Comment by arnaldos** [comment]
@m471c4 pasale los recursos a nelson plz

**Comment by m471c4** [comment]
@arnaldos done! @nelsonalfo you can find the resources, document and views here [https://github.com/arnaldos/fermat-graphic-design/tree/master/2D%20Design/Fermat_App/Sub-apps/Identities/Crypto_broker_identity/GUI-UX](url) . Let me know if you need anything else.

**Comment by m471c4** [comment]
@arnaldos we can close this issue! :)
