### ISSUE TITLE
Improve the design of the Community of Bitcoin Wallet App

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#883]
This Community will also be used in Bitcoin Wallet, Loss Protected Wallet and Fermat Wallet

Actual View Community

![community](https://cloud.githubusercontent.com/assets/13594347/15812130/ebeb1f62-2b7a-11e6-86cf-5a0611dea405.png)

take reference Community of the chat wallet
## ![conections](https://cloud.githubusercontent.com/assets/13594347/15812126/e3419daa-2b7a-11e6-8129-3a76495b4ee8.jpg)

![notifications](https://cloud.githubusercontent.com/assets/13594347/15812127/e345abb6-2b7a-11e6-91ab-b027142d5255.jpg)

**Comment by m471c4** [comment]
@arnaldos here's the first version for this community (please open the image to see the details). I'm not sure about the title.

![community](https://cloud.githubusercontent.com/assets/13468350/16448480/b17c31c0-3dbf-11e6-9634-caf8c94f62f2.png)

**Comment by arnaldos** [comment]
@m471c4 
- El tag del filter colocalo en la parte superior para evitar tapar el nombre del user

**Comment by m471c4** [comment]
@arnaldos apliqué la corrección y mejoré algunos detalles. Lo subo por partes para que lo puedas ver mejor:

Browser:
![community_browser](https://cloud.githubusercontent.com/assets/13468350/16478416/93fca6ae-3e67-11e6-9cd8-4cee1ffe4723.png)

Connections:
![community_connections](https://cloud.githubusercontent.com/assets/13468350/16478422/9daa7848-3e67-11e6-8412-6c3835b370ef.png)

Notifications:
![community_notifications](https://cloud.githubusercontent.com/assets/13468350/16478428/a8ab6cf2-3e67-11e6-84da-dc851507a329.png)

Si todo está en orden puedo proceder a generar los recursos :)

**Comment by m471c4** [comment]
@arnaldos ya podemos cerrar este caso. El diseño se está implementando.
