### ISSUE TITLE
Improve the design of the Community of Asset Usser App

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#884]
Actual View Community

![issuer comunity](https://cloud.githubusercontent.com/assets/13594347/15812211/a69cfdbc-2b7b-11e6-8ce7-29d625a40fe4.png)

Take reference Community of the chat wallet
## ![conections](https://cloud.githubusercontent.com/assets/13594347/15812126/e3419daa-2b7a-11e6-8129-3a76495b4ee8.jpg)

![notifications](https://cloud.githubusercontent.com/assets/13594347/15812127/e345abb6-2b7a-11e6-91ab-b027142d5255.jpg)

**Comment by emmysm** [comment]
Perfect @arnaldos

**Comment by Joseangel2v** [comment]
![chat_nuevol](https://cloud.githubusercontent.com/assets/17457499/16438087/67c85dea-3d76-11e6-853b-3ceb00955500.png)

**Comment by emmysm** [comment]
Me gustan @Joseangel2v. Solo bájale el grosor a 2 o 1 pt de las fotos de perfiles

**Comment by arnaldos** [comment]
@Joseangel2v @emmysm @nindriago 
- Los iconos de Add y el del check deben ser del mismo tamaño.
- El Tag del filtro puede ponerse en a parte superior de esta manera evitar tapar el nombre del user
- Los iconos de search debe ir antes que el de geolocalizacion en algunos mockups se muestran al contrario revisa eso.

**Comment by Joseangel2v** [comment]
![chat_nuevol](https://cloud.githubusercontent.com/assets/17457499/16508993/54d0a02a-3f02-11e6-99bd-40bd06272f16.png)

**Comment by emmysm** [comment]
Hola @Joseangel2v, recuerda hacer la correción del tag del filtro. Puede ir en la parte superior. Sigue estando en el mismo lugar.

**Comment by arnaldos** [comment]
@Joseangel2v como vamos con esto ?

**Comment by Joseangel2v** [comment]
![chat_nuevol](https://cloud.githubusercontent.com/assets/17457499/16537111/69a7648a-3fc9-11e6-8b8b-ed194dd62859.png)

**Comment by arnaldos** [comment]
@nindriago  que opinas al respecto ?

**Comment by ivonnesantos** [comment]
@emmysm @Joseangel2v se necesitan estos recursos el editable esta en el repo?

**Comment by ivonnesantos** [comment]
@emmysm @arnaldos le cambie el nombre a este caso porque estos son los colores de la user pero para no perder el trabajo le cambie solo el nombre
