### ISSUE TITLE
Improve the design of the Community of Asset User App

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#885]
Actual View Community

![user community](https://cloud.githubusercontent.com/assets/13594347/15812236/f8fae22c-2b7b-11e6-96c3-d18377648ace.png)

Take reference Community of the chat wallet
## ![conections](https://cloud.githubusercontent.com/assets/13594347/15812126/e3419daa-2b7a-11e6-8129-3a76495b4ee8.jpg)

![notifications](https://cloud.githubusercontent.com/assets/13594347/15812127/e345abb6-2b7a-11e6-91ab-b027142d5255.jpg)

**Comment by isahq23** [comment]
@Vivialexandra your case

**Comment by Vivialexandra** [comment]
![community](https://cloud.githubusercontent.com/assets/19909065/16131907/956e17ee-33da-11e6-8416-d4e9903c2484.jpg)

**Comment by Vivialexandra** [comment]
![community](https://cloud.githubusercontent.com/assets/19909065/16151088/ca06c9e4-3464-11e6-9209-241d3fd5745b.jpg)

**Comment by arnaldos** [comment]
@Vivialexandra   plz change the funtions filter to geolocation for this right now this is the filter correct

![chat_browser](https://cloud.githubusercontent.com/assets/13594347/16155269/58e6e46a-3478-11e6-9592-751b0380e481.jpg)

this are the funtion that need apply to all communities.

The design in general are fine @emmysm check this plz

**Comment by arnaldos** [comment]
@emmysm @isahq23 the resources, colors will be the same stile to asset user. :smile:

**Comment by isahq23** [comment]
Corrections:
1. Header - delete the drop shadow, the white-line that comes from the result of chosen a tab should integrate with the background color. The words browser, connections + notifications are too small, make them bigger and place them closer to the line. - The gradient line upside the header its part of it, when you go to the browser search it won't appear, so you have to decide if you use a gradient or a flat color.
2. Search engine - go-back arrow should be the same in the hole app. You have two different, pick one.
3.Search engine results - the green line are too heavy but I like it, maybe if you put a bit more space between each option could look better. And the icon, I can't see the "+", remember: an icon is simple, so use the "+" or the little people.
4. Location screen - works perfect! But remove the little arrow besides the choose word.
5. Location options - white squares: you use a color to indicate the selection or you use the check mark icon. Gradients in this case are not recommended.
6. Contacts to add - let go the green squares, please try to do something more like the samples in this case.
7. Pop-ups messages - you are missing the color hierarchy. If the line button is green the word inside is green, if you make the pop-up tittle purple don't make anything else purple. Also, green lines at the sides of the square must go, it's too complex, remember to keep simple.
8. Connections screen - icons: the minus "-" icon make it grey, to show the non-active signal.
9. Deleting a contact - again, green lines and color hierarchy in buttons, change it. Icons of checked and "x" in the contact options pop-up: make them circle.
10. Notifications screen - the "bells" must have the same color, I would use the first green in that list. And the line that rounds the notification must be a flat color, gradients are not recommended.  

ADVICE
Icons - if you make them in circles, all the icon inside the app must be in circles.
Color - No more than 2 colors, the rest I recomend something neutral like shades of grey or darker versions of the principal color.

**Comment by emmysm** [comment]
Here are one of the screens of the asset user:
- Color header: # 1371A7
- Font: Roboto light and regular, 14/12 pt
- Without gradient
- Font color: # 545454

![sell asset-03](https://cloud.githubusercontent.com/assets/15143489/16165738/814970ee-34af-11e6-91ae-c0a2734504bf.png)

@isahq23 @Vivialexandra

**Comment by isahq23** [comment]
@Vivialexandra use the info that emmy's giving you to build the design for the community of this app.

**Comment by arnaldos** [comment]
@Vivialexandra we need this plz

**Comment by Vivialexandra** [comment]
![community3](https://cloud.githubusercontent.com/assets/19909065/16202790/0e664410-36e1-11e6-96bf-819829c0cab3.jpg)

**Comment by isahq23** [comment]
@Vivialexandra now we go with the resources and indications

**Comment by arnaldos** [comment]
@isahq23 @emmysm if this are ready plz send all resources to @nindriago

**Comment by isahq23** [comment]
@arnaldos on the way

**Comment by nindriago** [comment]
@Fermat-ORG/skynet-team

**Comment by javafrank** [comment]
@Vivialexandra I like the proposed colors, design is fine too, but I think that there should not be much difference between the initial design (chat) and this, just change colors and text content should be enough. The Communities Apps are almost always very similar, I think that the reuse of good design save a lot of work to design team.

**Comment by jinmyjbv** [comment]
@Vivialexandra, i agree with @javafrank

**Comment by isahq23** [comment]
Vivi is no longer with us, I'll be working on the changes for this part.

**Comment by arnaldos** [comment]
@isahq23 this issue is ready to close ?? or this needs something else ?

**Comment by isahq23** [comment]
@arnaldos you can close it

**Comment by ivonnesantos** [comment]
![asset user community-03](https://cloud.githubusercontent.com/assets/15238660/17792576/87161586-656f-11e6-82a8-af21e7730dfc.png)
@nindriago lo que me comentaste de los grupos tuve que reabrir el caso porque parece que eso se paso por alto
