### ISSUE TITLE
Improve the design of the Community of Redeem Point App

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#886]
Actual View Community

![rp community](https://cloud.githubusercontent.com/assets/13594347/15812252/3f923de8-2b7c-11e6-9094-7b305d271708.png)

Take reference Community of the chat wallet
## ![conections](https://cloud.githubusercontent.com/assets/13594347/15812126/e3419daa-2b7a-11e6-8129-3a76495b4ee8.jpg)

![notifications](https://cloud.githubusercontent.com/assets/13594347/15812127/e345abb6-2b7a-11e6-91ab-b027142d5255.jpg)

**Comment by mawisk** [comment]
Les pido disculpas por la tardanza pero tuve un problema con mi laptop y estaba resolviendo.
Aquí les dejo una propuesta de la tarea asignada.

![completo-01](https://cloud.githubusercontent.com/assets/19206540/17183809/3453491a-53f7-11e6-8253-9602be7db4e2.jpg)

@ivonnesantos

**Comment by arnaldos** [comment]
@mawisk @ivonnesantos me gusta pero el filtro de geolocation va a ser implementado de esta manera
![com_4](https://cloud.githubusercontent.com/assets/13594347/17238976/603bcaec-552e-11e6-9215-c19ceb83db93.png)

**Comment by arnaldos** [comment]
@nindriago @ivonnesantos que opinan de esto ?

**Comment by ivonnesantos** [comment]
@mawisk se ve bien pero tiene unos detalles que no estan acorde a lo que se hizo entonces vamos adaptarlo 
1 las fotos de lo usuarios la pones asi con esa sombra y la linea blanca este recurso lo puedes tomar de esta ruta UIUX Design\APPs\Plataforma_DAP
2 la parte de arriba que tiene la hora por favor colocala del mismo color que esta el la otra 
![captura de pantalla 241](https://cloud.githubusercontent.com/assets/15238660/17248398/4a3661a0-5568-11e6-98f6-6e63118aa8e3.png)

**Comment by ivonnesantos** [comment]
@mawisk y si coloca el filtro como te dice arnaldo

**Comment by mawisk** [comment]
Sería algo como estO?

![completo-02](https://cloud.githubusercontent.com/assets/19206540/17371879/994f61f0-596f-11e6-95fc-1717015a67fe.jpg)

@ivonnesantos

**Comment by ivonnesantos** [comment]
Si esta bien @mawisk genera los recursos y subelos el boton de agragar contacto colocaclo mas grande y crea una version con el boton ya pulsado

**Comment by mawisk** [comment]
Aquí están los cambios acordados.

![completo-01](https://cloud.githubusercontent.com/assets/19206540/17744194/ab5e0f80-6474-11e6-8c3b-39ea91c58994.jpg)

@ivonnesantos

**Comment by ivonnesantos** [comment]
@mawisk en la primera pantalla te faltan las pestañas browser/connection/notification. Te faltan don pantallas la de "no conection" y "no notification" yo ya hice esos dos iconos tomalos como base y aplicale el estilo del primero quw hiciste. Despues de esos detalles ya estariamos listos.

**Comment by mawisk** [comment]
Aquí están los detalles acordados.

![completo-01](https://cloud.githubusercontent.com/assets/19206540/17870437/91cd63b2-6885-11e6-9b20-e5f9089cbd70.jpg)

@ivonnesantos

**Comment by ivonnesantos** [comment]
ahora si quedo genera los iconos y el archivo de indicaciones subelo al repo y me avisas @mawisk

**Comment by arnaldos** [comment]
@ivonnesantos podemos cerrar el caso ??
