### ISSUE TITLE
Improve the design of the Community of Crypto Customer App

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#887]
Actual View Community
## ![community_community2](https://cloud.githubusercontent.com/assets/13594347/15812267/9dc3295e-2b7c-11e6-9354-68609b668492.png)

![community_community](https://cloud.githubusercontent.com/assets/13594347/15812268/9dc505da-2b7c-11e6-8bb0-31137a6354f3.png)

Take reference Community of the chat wallet
## ![conections](https://cloud.githubusercontent.com/assets/13594347/15812126/e3419daa-2b7a-11e6-8129-3a76495b4ee8.jpg)

![notifications](https://cloud.githubusercontent.com/assets/13594347/15812127/e345abb6-2b7a-11e6-91ab-b027142d5255.jpg)

**Comment by Magdy27** [comment]
![crypto-customer](https://cloud.githubusercontent.com/assets/19651834/15895549/ac879fa8-2d55-11e6-8c9f-e032f0ef44cf.png)

Hola, adjunto avances de la APP. @arnaldos @isahq23

**Comment by isahq23** [comment]
@Magdy27 
Correcciones: 
Header - ampliar, cambiar colores (intenta con los degradados que presenta el logo), elimina la sombra
Tabs - centrar las palabras respecto al espacio, acomodar línea blanca
Search - acomodar visualmente
Textos (cajas de confirmación) - aumenta un poco el puntaje
Espaciado - todo lo que esté enlistado debe tener más espacio entre los elementos
Definición de Colores - trabaja con la paleta del logo de la app y si es necesario agrega colores para ciertas funciones
Iconos - trabaja sobre ellos, puedes hacer propios o personalizar los existentes

**Comment by Magdy27** [comment]
![crypto-customer---correcion-1](https://cloud.githubusercontent.com/assets/19651834/15913546/65618676-2da4-11e6-93c4-d0b40aba89ad.png)

@arnaldos @isahq23

**Comment by arnaldos** [comment]
@Magdy27  make a review to search element. I show you an example 

![search](https://cloud.githubusercontent.com/assets/13594347/15919237/1ffe576e-2dd9-11e6-9cd6-97f7573c748c.png)

 About icon back is too big reduce size and make more small

**Comment by isahq23** [comment]
@arnaldos I agree. We should keep the search engine with the same apperance and the icons from empty screen please make them smaller, they're to big.

Other corrections:
1. the icons in the header should be ALL in the same size - and the three that are together, please make some space between them.
2. the text in below of some users like "request send" or "is now conections" make them a bit bigger and a bit darker.
3. the icons about "connected or not" should be different in color, remember to use the color psicology to make the app visually easier to the user.
4. try to use more the purple and the grey, I think the pink makes it look too girly.

Last: please do  another samples with the other colors in the logo, use gradients and spot colors (colores planos)
You can propose  only 2 screen (first and third), so we can see more options.

**Comment by Magdy27** [comment]
![crypto-customer---correcion-2](https://cloud.githubusercontent.com/assets/19651834/15944782/f4b4bf32-2e58-11e6-8190-7dce39b11536.png)

@arnaldos @isahq23 

Hola chicos, aquí están las correcciones hechas. En algunos casos coloque varias propuestas de color, de tamaño de los iconos, la separación entre ellos etc. Espero sus comentarios.

**Comment by isahq23** [comment]
1. Search Engine - Option 1 - I think it's the best one, only one change: the "search box" should be a bit smaller than the header.
2. Browser - Icons from option 1 and text from option 3 - use a lighter font for the names
3. Connections - "checked" icons from option 1, negative icon and text from option 3 - again, use a lighter font for the names.
4. The "location search" looks great.

Please make one more proposal with the icons in blue as your first proposal. I would like to see it with these new colors.

**Comment by Magdy27** [comment]
![crypto-customer---correcion-3](https://cloud.githubusercontent.com/assets/19651834/15978316/0f0ec2dc-2f27-11e6-98ac-27fff752d1a1.png)

@arnaldos @isahq23

**Comment by isahq23** [comment]
Final Corrections:
1. the "-" icon in connections creen should be the same grey from the "+" icon in browser.
2. the dark screen with "pop-ups" boxes shouldn't be too dark and it should cover the tabs, so the user can't do anything more after answering the question.
3. I think we should keep the purple icons, thanks for doing the blue samples but it's not working.
4. the icon on empty screens: make them smaller (no users - no contacts - no notifications)
5. notifications - the time of the notifications, make them grey.

Search engine, great.
After these corrections you can make the rest of the screens.

@arnaldos what do you think?

**Comment by Magdy27** [comment]
![crypto-customer---correcion-4](https://cloud.githubusercontent.com/assets/19651834/16025030/d6710394-318e-11e6-94a8-5bc3b2f912be.png)

@arnaldos @isahq23

**Comment by isahq23** [comment]
Looks pretty awesome!

Corrections: 
1. "Ubication" Screen - the correct word is "location" (there is no such thing as ubication, not your mistake but we should be aware of this things). I think the square theme it's not the right one, you've been working with corner-rounded squares so you should keep working with that. Something I didn't told is that the best way to place functions when you design an app is placing them in the center, makes easier to pick them for the user. And please, make the spaces and text bigger, you have a lot of wasted space there.
2. Countries + Cities Pop-ups - polish those pop-ups, they can look better.
3."Error Connection" pop-up - place de "ok" button below the text, looks tight.
4. Connections Screen - the "-" button looks too dark make it lighter and also the "delete conctact" pop-up

About the color tests I think we could use the 4th version, it shows that it is an option/step in the app but also separate from the header, and it's doesn't look girly. Use the 4th color version for locations.

**Comment by Magdy27** [comment]
![crypto-customer---correcion-5](https://cloud.githubusercontent.com/assets/19651834/16084899/2a521650-32e4-11e6-8a8b-339b7d4af4fd.png)

@arnaldos @isahq23  Espero sus comentarios.

**Comment by isahq23** [comment]
The pop-ups messages should all look similar, the "error connection" looks different.
I'm still not sure about the "location" design screen, can you please do another proposal? (not talking about color)
Finally, the "countries", "states" and "cities" pop-ups somehow still look wrong for me. Try to make the lines reach the square edges and the titles centered in their space.

**Comment by Magdy27** [comment]
![crypto-customer---correcion-6](https://cloud.githubusercontent.com/assets/19651834/16095166/36ac5586-330d-11e6-8f0e-1bc67a08c5ae.png)

@arnaldos @isahq23

**Comment by isahq23** [comment]
Last part - pop-ups - perfect
Location screen - I would go with the 4th version
Countries, states and citites pop-ups - I think the last one works best, but remember the title "all-distrito capital" must be centered in its space.

@arnaldos what do you think?

**Comment by Magdy27** [comment]
![crypto-customer---correcion-7](https://cloud.githubusercontent.com/assets/19651834/16100053/8a215992-3325-11e6-8b06-f4a05d7497e2.png)

@arnaldos @isahq23

**Comment by arnaldos** [comment]
@Magdy27 plz change the funtions filter to geolocation for this right now this is the filter correct

![chat_browser](https://cloud.githubusercontent.com/assets/13594347/16155269/58e6e46a-3478-11e6-9592-751b0380e481.jpg)

we need it for today, all design are fine just change the funtion filter

**Comment by Magdy27** [comment]
![crypto-customer---browser](https://cloud.githubusercontent.com/assets/19651834/16164751/b9694f2c-34a9-11e6-81ef-5356488174d8.png)
![crypto-customer---conections](https://cloud.githubusercontent.com/assets/19651834/16164752/b97172b0-34a9-11e6-8795-4a1ce6ef7a7c.png)
![crypto-customer---notifications](https://cloud.githubusercontent.com/assets/19651834/16164753/b97ccebc-34a9-11e6-939d-9ffaf8656058.png)

@arnaldos @isahq23

**Comment by isahq23** [comment]
go ahead! :D

**Comment by arnaldos** [comment]
@Magdy27 @isahq23 plz we need the resources to give @nelsonalfo

**Comment by nelsonalfo** [comment]
Hi guys when I'm gonna get the resources?

**Comment by arnaldos** [comment]
Hi @nelsonalfo we are waiting for this !

**Comment by nelsonalfo** [comment]
I have the resources now, thanks

**Comment by arnaldos** [comment]
fine

**Comment by Magdy27** [comment]
![crypto-customer---pantallas-separadas](https://cloud.githubusercontent.com/assets/19651834/16349109/9cbd8448-3a20-11e6-9b21-d9b9a9070af4.png)

@arnaldos @isahq23

**Comment by nelsonalfo** [comment]
Les adjunto capturas de pantalla de la implementación del nuevo diseño en vivo (todavía falta implementar el filtro por alias y el nuevo color de los tabs que me pasó @isahq23 , cuando lo tenga se los adjunto también):

![captura de pantalla de 2016-06-30 10 53 41](https://cloud.githubusercontent.com/assets/1823627/16494707/19f28c8c-3eb4-11e6-83b7-a4b883f05baf.png)

![captura de pantalla de 2016-06-30 10 53 26](https://cloud.githubusercontent.com/assets/1823627/16494706/19e2f650-3eb4-11e6-89ff-997770c3bd3e.png)

![captura de pantalla de 2016-06-30 10 52 16](https://cloud.githubusercontent.com/assets/1823627/16494709/1a009da4-3eb4-11e6-99bd-0b9e21054f87.png)

![captura de pantalla de 2016-06-30 10 52 11](https://cloud.githubusercontent.com/assets/1823627/16494710/1a035800-3eb4-11e6-8c04-79d0549d1b3b.png)

![captura de pantalla de 2016-06-30 10 51 59](https://cloud.githubusercontent.com/assets/1823627/16494705/19c0edb2-3eb4-11e6-8396-0a421ea0c924.png)

![captura de pantalla de 2016-06-30 10 51 55](https://cloud.githubusercontent.com/assets/1823627/16494711/1a0defb8-3eb4-11e6-91b6-29097e924a5d.png)

![captura de pantalla de 2016-06-30 10 51 48](https://cloud.githubusercontent.com/assets/1823627/16494708/19fb8152-3eb4-11e6-9d2c-39beea8f4f00.png)

**Comment by arnaldos** [comment]
@nelsonalfo que recurso, función falta por el lado de diseño ?

**Comment by isahq23** [comment]
@nelsonalfo  tienes una sombra debajo de los tabs igual que en el otro community. 
Remuevela por favor.
