### ISSUE TITLE
Improve the design of the Community of Crypto Broker App

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#888]
Actual View Community
## ![community_broker](https://cloud.githubusercontent.com/assets/13594347/15812279/c9546560-2b7c-11e6-8a20-eb60fe8a8ae8.png)

![community_broker2](https://cloud.githubusercontent.com/assets/13594347/15812280/c959ea9e-2b7c-11e6-8300-2e5987827860.png)

Take reference Community of the chat wallet
## ![conections](https://cloud.githubusercontent.com/assets/13594347/15812126/e3419daa-2b7a-11e6-8129-3a76495b4ee8.jpg)

![notifications](https://cloud.githubusercontent.com/assets/13594347/15812127/e345abb6-2b7a-11e6-91ab-b027142d5255.jpg)

**Comment by Magdy27** [comment]
![crypto-broquer-1](https://cloud.githubusercontent.com/assets/19651834/16087090/9287871c-32eb-11e6-8097-d03e17ad8578.png)

@arnaldos @isahq23

**Comment by isahq23** [comment]
Keep going!

Only detail: the "arrow" icon, in the results, works for other kind of function. It's more for links or going to a different website. You can use an eye or the same "+" like in the customer.

**Comment by arnaldos** [comment]
@Magdy27 plz change the funtions filter to geolocation for this right now this is the filter correct

![chat_browser](https://cloud.githubusercontent.com/assets/13594347/16155269/58e6e46a-3478-11e6-9592-751b0380e481.jpg)

we need it for today, all design are fine just change the funtion filter

**Comment by Magdy27** [comment]
![crypto-broquer---browser](https://cloud.githubusercontent.com/assets/19651834/16164859/403f1db0-34aa-11e6-9548-d9629242ea90.png)
![crypto-broquer---conections](https://cloud.githubusercontent.com/assets/19651834/16164860/4045d5ba-34aa-11e6-9c06-ac06bdb45efd.png)
![crypto-broquer---notifications](https://cloud.githubusercontent.com/assets/19651834/16164861/404c2f14-34aa-11e6-95cf-719373680197.png)

@arnaldos @isahq23

**Comment by isahq23** [comment]
go ahead! :D

**Comment by arnaldos** [comment]
@Magdy27 @isahq23 plz we need the resources to give @nelsonalfo

**Comment by nelsonalfo** [comment]
Hi guys when I'm gonna get the resources?

**Comment by arnaldos** [comment]
Hi @nelsonalfo we are waiting for this !

**Comment by nelsonalfo** [comment]
pregunta: que significan los colores de los tildes (:ballot_box_with_check:) en los items del Tab **Browser**? y como seria la interacción para agregar un usuario? solo le das clic al usuario y te aparecería un dialogo para enviar una nuevo solicitud de conexión?

**Comment by isahq23** [comment]
@nelsonalfo en este caso, sí. Solo con seleccionar el usuario se enviaría una solicitud de conexión.
El verde y el gris en el browser diferencian entre los usuarios ya agregados y los no agregados.

**Comment by nelsonalfo** [comment]
lo digo porque no veo el dialogo que pregunte si deseas enviar la solicitud de conexión solo el de que alguien se quiere conectar contigo. Pero igual creo que ese dialogo que te indica si alguien desea conectar contigo es innecesario porque para eso ya tienes el tab de **Notifications**

**Comment by isahq23** [comment]
en la penúltima pantalla puedes observar el pop-up de "connection request"

**Comment by arnaldos** [comment]
faltan los cambios que se le pidió a @Magdy27

**Comment by nelsonalfo** [comment]
hola @isahq23 para cuando van a tener listas las modificaciones en el tab de Notifications que me habias dicho?

**Comment by arnaldos** [comment]
@Magdy27 @isahq23  necesitamos eso con urgencia

**Comment by nelsonalfo** [comment]
Les adjunto capturas de pantalla de la implementación del nuevo diseño en vivo (todavía falta implementar el filtro por alias, cuando lo tenga se los adjunto también):

![captura de pantalla de 2016-06-30 10 53 58](https://cloud.githubusercontent.com/assets/1823627/16493243/92b2fa2c-3eae-11e6-89e2-bf4ef6a8df98.png)

![captura de pantalla de 2016-06-30 10 54 01](https://cloud.githubusercontent.com/assets/1823627/16493244/92d91d6a-3eae-11e6-9a86-29bf0c87d2b5.png)

![captura de pantalla de 2016-06-30 10 54 27](https://cloud.githubusercontent.com/assets/1823627/16493242/92a571ea-3eae-11e6-91cd-428b47972e20.png)

![captura de pantalla de 2016-06-30 10 54 35](https://cloud.githubusercontent.com/assets/1823627/16493240/929b49cc-3eae-11e6-9354-2224084c0998.png)

![captura de pantalla de 2016-06-30 10 54 46](https://cloud.githubusercontent.com/assets/1823627/16493239/9293979a-3eae-11e6-99c8-86d203abf8f4.png)

**Comment by nelsonalfo** [comment]
![captura de pantalla de 2016-06-30 11 10 45](https://cloud.githubusercontent.com/assets/1823627/16493425/37641e7a-3eaf-11e6-803e-9a6167047929.png)

**Comment by isahq23** [comment]
@nelsonalfo tienes una sombra en los tabs que no debería existir, el diseño es plano.
