### ISSUE TITLE
Create a Image for Facebook Profile to Dating P2P App

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#889]
Banner size 981x363 px

Profile size 180x180 px

**Comment by isahq23** [comment]
Profile
![dating_fb_profpic](https://cloud.githubusercontent.com/assets/15214774/15842089/d86acb9a-2c1f-11e6-9b09-a71583c0e55f.jpg)

Cover
![dating_fb_cover](https://cloud.githubusercontent.com/assets/15214774/15842095/dd4c07e6-2c1f-11e6-8f89-ae6fa0ebff5b.jpg)

**Comment by isahq23** [comment]
@rennyx7 
Could you please do some proposals for this?

It has to be "generic". Don't use a couple as image..
You can place one person by itself laughing, or a phone with th launch app view (from the .ai I sent you on slack). Remember this is an app for EVERYONE, does not matter the race, country, language and even age...

**Comment by rennyx7** [comment]
hello people @arnaldos @isahq23 
![fotoperfil1](https://cloud.githubusercontent.com/assets/20045567/16466216/49f53c8a-3e10-11e6-818e-df931fd81ac9.png)
![fotoperfil2](https://cloud.githubusercontent.com/assets/20045567/16466217/49f80b5e-3e10-11e6-8b43-4c804c8df359.png)
![bannerdating1-01](https://cloud.githubusercontent.com/assets/20045567/16466218/4a0a58a4-3e10-11e6-8376-f1f874e7f4b1.png)
![bannerdating2](https://cloud.githubusercontent.com/assets/20045567/16466266/6e34483e-3e10-11e6-83c1-116a789f3329.png)
![bannerdating3](https://cloud.githubusercontent.com/assets/20045567/16466268/6e43011c-3e10-11e6-9099-7487145a7c44.png)
![bannerdating4](https://cloud.githubusercontent.com/assets/20045567/16466267/6e42866a-3e10-11e6-9f65-f18b75528a1f.png)

**Comment by isahq23** [comment]
@gabymado what do you think?

**Comment by gabymado** [comment]
I don't see it @isahq23 I was imagining more like 2 pictures. One like the one I'm attaching and other, the person who could be holding the phone, smiling or laughing. 

Also I like this kind of image. Look at the cover. https://www.facebook.com/Fermat-P2P-Taxi-Platform-Project-992451414166615/

![https- 2f 2fblueprint-api-production s3 amazonaws com 2fuploads 2fstory 2fthumbnail 2f7227 2ftinder](https://cloud.githubusercontent.com/assets/17648218/16469799/3d1bea68-3e29-11e6-818e-8267bc5141fb.jpg)

**Comment by rennyx7** [comment]
@gabymado @isahq23 
![bannerdating5](https://cloud.githubusercontent.com/assets/20045567/16499419/6a719954-3ece-11e6-82e9-265287fecf1f.png)
![bannerdating](https://cloud.githubusercontent.com/assets/20045567/16499480/b830144a-3ece-11e6-87eb-dacde8dec3c5.png)

**Comment by arnaldos** [comment]
@rennyx7 check the mockups plz. I think this are old mockups. @isahq23  waht do you think ?

**Comment by rennyx7** [comment]
can i get the new one ? @arnalos @isahq23

**Comment by isahq23** [comment]
I like the last ones, I think it's more what Gaby is looking. 
I already send to renny 2 screens from the correct design

**Comment by rennyx7** [comment]
![bannerdating](https://cloud.githubusercontent.com/assets/20045567/16547166/3194525a-4132-11e6-924e-fa016cecfcc2.png)
![bannerdating2](https://cloud.githubusercontent.com/assets/20045567/16547174/67e4652a-4132-11e6-944b-356bf2538489.png)

**Comment by isahq23** [comment]
@rennyx7 if you place the app screen backwards, I mean, the launch in the above imagen and the match in the below image, it'll make the appreciation easier.

**Comment by rennyx7** [comment]
Mejor vista 
![bannerdating2](https://cloud.githubusercontent.com/assets/20045567/16567535/bdfcfb8c-41ed-11e6-932e-b91bd08c6986.png)
![bannerdating](https://cloud.githubusercontent.com/assets/20045567/16567534/bdfc8580-41ed-11e6-98f1-e41ec9075aff.png)

**Comment by isahq23** [comment]
Awesome! 
@gabymado check this!

**Comment by arnaldos** [comment]
Be care with details. 
- the mockup is stretched,
- the phone is invert.
- The mockup is like a sticker, put screen glare and shadows that are normally generated in a phone.

**Comment by rennyx7** [comment]
yep, So i need approbation to made the final art

**Comment by rennyx7** [comment]
![bannerdating](https://cloud.githubusercontent.com/assets/20045567/16596076/3fbc452e-42c0-11e6-8f2b-fe3d107ed5af.png)
![bannerdating2](https://cloud.githubusercontent.com/assets/20045567/16596119/74f55ad2-42c0-11e6-9d70-68bf3f46c7fd.png)

**Comment by isahq23** [comment]
@rennyx7 it's too obvious, you can make them more lighter.

**Comment by gabymado** [comment]
I like them better than the old ones but, I still imagine something more "relaxed" like the taxi cover. These ones look too posed, specially the hand. I like the picture of the guy, though, and that it is him in the real world. Maybe the hand could be holding a phone with the match or the chat of that guy (I'm sure you don't have it but if it was a small picture in a circle, with a guy in a suite and glasses, it would be hard to notice he's not the same. So the hand is the girl's hand holding the phone and she's chatting with his match. Something like that. Also, it would be good if the hand was "posing" so much.

@isahq23 @rennyx7

**Comment by rennyx7** [comment]
@isahq23 @arnaldos @gabymado 
![bannerdating2](https://cloud.githubusercontent.com/assets/20045567/16624669/a143d87a-436f-11e6-8df3-c49a9696d66d.png)

**Comment by isahq23** [comment]
I like it, but I don't know if the hands and phone are too dark. 
Can you add some light? To make it similar to the image.

**Comment by rennyx7** [comment]
@gabymado 
![bannerdating1](https://cloud.githubusercontent.com/assets/20045567/16631172/c7e226b4-438b-11e6-8ca2-4a4441e25a54.png)

**Comment by isahq23** [comment]
@arnaldos this case can be close.
The files are in the repo

**Comment by isahq23** [comment]
@arnaldos the same image will be use in twitter and youtube profile
so I think you could close the cases #890 and #891

**Comment by arnaldos** [comment]
@isahq23 @rennyx7 is fine but, to social media, I like an image that involved a different sexes Actors.

**Comment by rennyx7** [comment]
Hi, I made this new options 
![propueta_nueva1](https://cloud.githubusercontent.com/assets/20045567/17520475/dd4dfb3e-5e1d-11e6-85a4-5b6d182ba93a.jpg)

![propueta_nueva2](https://cloud.githubusercontent.com/assets/20045567/17520428/bab8499e-5e1d-11e6-99ce-b83c5ba41a53.jpg)
