### ISSUE TITLE
Realizar el diseño de la base para las fichas descriptivas de fermat.org

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#89]
Viene del #88 

Se recomienda realizar un diseño nuevo para la base de la estructura de la ficha.
estandarizando el estilo gráfico que llevan los iconos de fermat.org en cuanto a forma, color y tipografía.

**Comment by m471c4** [comment]
@Luis-Fernando-Molina @arnaldos @Miguelcldn ¿debemos mantener la misma proporción y tamaño?

**Comment by Luis-Fernando-Molina** [comment]
En lo posible si.

**Comment by m471c4** [comment]
@Miguelcldn ¿podrías por favor darnos las dimensiones de la ficha para trabajar en función de eso?

**Comment by Miguelcldn** [comment]
Cada ficha individual tiene:
- width: 120px
- height: 160px

En la tabla, tienen una separación de 20px para todas las direcciones

**Comment by m471c4** [comment]
@Miguelcldn muchas gracias.

**Comment by Miguelcldn** [comment]
**Nota:** Para que consideren en el diseño base, he recolectado los nombres más largos para el nombre del elemento (texto en blanco debajo de la dificultad) y el nombre de la capa (texto a color debajo del nombre), los cuales son los siguientes:

Capa mas larga: "Digital Money Transaction"
Nombre mas largo: "Top Up Point Cash Out Point Crypto Purchase"

Con el diseño actual, el nombre de la capa ha llegado a ser hasta 2 líneas mientras que el nombre del elemento ha llegado hasta 3.

**Comment by arnaldos** [comment]
@Miguelcldn ok perfecto voy a tomarlo en cuenta !!

**Comment by arnaldos** [comment]
@Miguelcldn para este trabajo es necesario usar tipografías para web cierto ?  de ser así voy a trabajar con la tipografía roboto. aparte de esa tengo "source sans pro" y "open sans" si es recomendado usar una diferente avísame para ubicar las fuentes y compartir con @m471c4

**Comment by Miguelcldn** [comment]
Si me pueden dar el archivo de las fuentes entonces pueden usarlas sin problemas, lo instalaría en el servidor de manera que los clientes puedan verlo con dicha tipografía, claro, no estaría de más tener una estándar como "fallback" por si algo falla, mostrar la estándar

**Comment by arnaldos** [comment]
ok perfecto de momento voy a trabajar con roboto, mientras consigo "fallback" y de esta manera evitar que fallos mas adelante te parece ?

**Comment by Miguelcldn** [comment]
"fallback" no es una tipografía, fallback significa que el navegador, si por alguna razón no puede usar la tipografía dada, buscara la siguiente en la lista

**Comment by arnaldos** [comment]
ahh ok ok !! jajajaja con razón no la conseguía :smiley:

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina @m471c4  comparto varias propuestas para la ficha 

versión 1
![ficha_descriptiva_fermat_org-01](https://cloud.githubusercontent.com/assets/13594347/9778433/f4b06a64-5739-11e5-81bb-5060a05b9109.jpg)

versión 2
![ficha_descriptiva_fermat_org-02](https://cloud.githubusercontent.com/assets/13594347/9778434/f4b10e92-5739-11e5-8ecf-68688728311c.jpg)

versión 3
![ficha_descriptiva_fermat_org-03](https://cloud.githubusercontent.com/assets/13594347/9778435/f4b5bd3e-5739-11e5-8262-4c69d2e803cc.jpg)

versión 4
![ficha_descriptiva_fermat_org-04](https://cloud.githubusercontent.com/assets/13594347/9778436/f4bc9c08-5739-11e5-80e3-8621d780f998.jpg)
![ficha_descriptiva_fermat_org-05](https://cloud.githubusercontent.com/assets/13594347/9778437/f4be647a-5739-11e5-9ccc-6fbd4af66df8.jpg)

versión 5
![ficha_descriptiva_fermat_org-06](https://cloud.githubusercontent.com/assets/13594347/9778438/f4c313bc-5739-11e5-9c4a-763daf6914f4.jpg)

versión 6
![ficha_descriptiva_fermat_org-07](https://cloud.githubusercontent.com/assets/13594347/9778439/f4df64ae-5739-11e5-8d44-0905b3d024f9.jpg)

**Comment by m471c4** [comment]
@Luis-Fernando-Molina, @arnaldos acá cuatro propuestas adicionales para las fichas. Yo usé Helvetica para los textos. @Miguelcldn ¿eso iría como texto o como imágenes fijas?

Versión 1:
![ficha1](https://cloud.githubusercontent.com/assets/13468350/9782437/e24321e6-5766-11e5-898a-5b0e1ed8a982.png)

Versión2:
![ficha2](https://cloud.githubusercontent.com/assets/13468350/9782439/e256250c-5766-11e5-91ea-7f1e79083498.png)

Versión 3:
![ficha3](https://cloud.githubusercontent.com/assets/13468350/9782438/e255f37a-5766-11e5-9395-9e8f4f1de180.png)

Versión 4:
![ficha4](https://cloud.githubusercontent.com/assets/13468350/9782440/e27e9816-5766-11e5-9eb6-b2cc377536fe.png)

**Comment by Luis-Fernando-Molina** [comment]
Hablando de las versiones de Dayana:

1) Puede ir por el lado de la version 4
2) pero debe usar las billeteras chiquitas en sus colores que ya usamos: verde , rojo, y los otros.
3) las billeteras pueden ir al rededor de la foto de manera circlar, como rayos de sol. Tambien pudieran estar en otros lados pero debieran ser esas billeteras.
4) La ficha roja en realidad debe ser del naranja fermat, el verde debe ser del de fermat, etc.
5) La tipografia no puede estar estirada hacia arriba
6) El codigo no puede estar vertical. Pudiera ser como la version 3
7) debiera tener un borde blanco la ficha entera como los iconos de las plataformas
8 ) La version 2 no está mal.

Hablando de las versiones de Arnaldo:

Hay varias versiones que se ven bien en ambos casos, me pregunto si no sería bueno tener versiones diferentes para los diferentes estados: Concepto, Desarrollo, Qa, Produccion, y que la distinción no sea solo el color. Creemos un caso para cada estado, asi diseñamos una ficha para cada caso.

Yo acá indico con cual propuesta arrancamos la discución de cada caso.

@Miguelcldn debería ir actualizando en lab.fermat.com de vez en cuando las fichas para ver como quedan todas juntas y mezcladas.

A) La version 4 de arnaldo pudiera ser la base del estado CONCEPTO, en vez de rojo debiera haber gris.
B) La version 3 de Dayana para DESARROLLO, la barra de abajo se pudiera reutilizar luego para mostrar el avance.
C) para QA habria que hacer alguna en amarilla.
D) La version 5 de arnaldo puderas ser la base del estado PRODUCCION

**Comment by Miguelcldn** [comment]
@m471c4 No entiendo muy bien la pregunta, ahorita hay 2 versiones para hacer las fichas, la primera 2D es usando HTML con CSS para dibujar los textos e imagenes, la ficha termina siendo un /<div>. La segunda 3D es usando /<canvas> que un algoritmo dibuja el texto y todo termina convirtiéndose en una imagen a dibujar en la pantalla.

Yo opino que se debería tomar un solo diseño y en base al avance del estado del complemento agregar más detalles de este, como por ejemplo empezar en la versión 4 de @arnaldos y terminar en su versión 5. Pasar de la version 4 de Arnaldo y luego a la version 3 de Dayana es mucha diferencia con respecto a la ubicación de la foto y afectaría su armonía con las demás fichas a la vista. Para implementar dichos diseños en la página necesitaría el CSS correspondiente

**Comment by Luis-Fernando-Molina** [comment]
La idea no es tomar exactamene las versiones propuetas , pueden estandarizarse ciertas cosas también. Pero no veo mal que la ficha sea diferente mas allá del color. De alguna manera pudiera motivar a su dueño a lograr alcanzar cierto tipo de ficha. Primero hagamos los diseños y cuando los terminemos que se involucre @Miguelcldn asi no le robamos tiempo. Ver las fichas una al lado de la otra lo puede hacer @arnaldos  o @m471c4  con un programa de diseño gráfico.

**Comment by m471c4** [comment]
@Luis-Fernando-Molina muy bien, haré los cambios que me pides y los subo. La tipografía no estña estirada, es la Helvetica Narrow que tiene esa forma, ¡pero la puedo cambiar! Pondré las fichas una al lado de la otra para que las puedan ver y comparar, aunque estoy de acuerdo con @Miguelcldn, podríamos trabajar en base a un solo diseño, tal vez combinar los elementos de la que más te haya gustado de @arnaldos y mía.

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina les comparto todas las fichas en una sola fila y con un fondo gris para que se aprecien los bordes que antes no se veían reflejados.
![ficha_descriptiva_fermat_org-08](https://cloud.githubusercontent.com/assets/13594347/9794689/5baea79a-57b6-11e5-81f1-8a9b30f285d9.jpg)

**Comment by Luis-Fernando-Molina** [comment]
No está mal que sean distintas. Si son muy parecidas entonces los elementos como las fotos debiran estar en el mismo lugar, pero si son bien diferentes quizas no. Acordate que el fondo de fermat.org es blanco, con lo cual deberías mostrarlo asi.

**Comment by m471c4** [comment]
@Luis-Fernando-Molina acá las que hice para que pueda compararlas, aun no he aplicado los cambios sugeridos.

![fichas_fermat](https://cloud.githubusercontent.com/assets/13468350/9795417/501b3f66-57ba-11e5-9c6b-8fed80e67511.png)
