### ISSUE TITLE
Create a Image for Twitter Profile to Dating P2P App

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#890]
Banner size 1500x500 px

Profile size 500x500 px

**Comment by isahq23** [comment]
Profile
![dating_tw_profpic](https://cloud.githubusercontent.com/assets/15214774/15842077/bdd1a8e4-2c1f-11e6-84c0-d2b8cbfea6db.jpg)

Cover
![dating_tw_cover](https://cloud.githubusercontent.com/assets/15214774/15842084/c459842a-2c1f-11e6-9fee-b3f64549dd33.jpg)

**Comment by isahq23** [comment]
@Magdy27 
Please do some proposals for this.

It has to be "generic". Don't use a couple as image..
You can place one person by itself laughing, or a phone with th launch app view (from the .ai I sent you on slack). Remember this is an app for EVERYONE, does not matter the race, country, language and even age...

Gaby said:
I was imagining more like 2 pictures. One like the one I'm attaching and other, the person who could be holding the phone, smiling or laughing.
See the samples in this FB profile
https://www.facebook.com/Fermat-P2P-Taxi-Platform-Project-992451414166615/

**Comment by Magdy27** [comment]
![cover twitter 2](https://cloud.githubusercontent.com/assets/19651834/16501028/2d8108b0-3ed1-11e6-9a64-e12d686df95b.jpg)
![cover twitter](https://cloud.githubusercontent.com/assets/19651834/16501029/2da18766-3ed1-11e6-886a-f25f5c609500.jpg)

@isahq23

**Comment by isahq23** [comment]
@gabymado check this

**Comment by arnaldos** [comment]
@isahq23 @Magdy27 that image are examples ¿ right ? be carefull with copyrights

**Comment by Magdy27** [comment]
Si claro de boceto.

2016-06-30 15:57 GMT-04:30 Arnaldo Santamaria notifications@github.com:

**Comment by Magdy27** [comment]
![dating_ui-ux-02](https://cloud.githubusercontent.com/assets/19651834/16528253/8af8e184-3f85-11e6-8954-61035820a989.jpg)

@isahq23 @arnaldos

**Comment by arnaldos** [comment]
I don´t understand, this isues is to defined the profile image to twitter. why is this mockups here ?

**Comment by isahq23** [comment]
@Magdy27 those images suppose to go on the dating channel in slack haha

**Comment by Magdy27** [comment]
![cover twitter 3](https://cloud.githubusercontent.com/assets/19651834/16657748/930bf90a-4431-11e6-8340-5c6602a03a24.jpg)
![cover twitter 4](https://cloud.githubusercontent.com/assets/19651834/16657750/935b681e-4431-11e6-94a9-756da2b30d42.jpg)

@isahq23 @arnaldos

**Comment by isahq23** [comment]
@gabymado check this ones for twitter

**Comment by Magdy27** [comment]
![cover twitter 5](https://cloud.githubusercontent.com/assets/19651834/16659421/f0aabfbe-4437-11e6-9f67-5867406ab6dc.jpg)
![cover twitter 6](https://cloud.githubusercontent.com/assets/19651834/16659422/f0ccb7cc-4437-11e6-839e-631926158458.jpg)

@arnaldos @isahq23
