### ISSUE TITLE
Create a Image for Youtube Profile to Dating P2P App 

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#891]
Banner size 2560x423 px

Profile size 250x250 px

**Comment by isahq23** [comment]
Profile
![dating_yt_profpic](https://cloud.githubusercontent.com/assets/15214774/15842049/898126be-2c1f-11e6-8135-6d1c4f677f36.jpg)

Cover
![dating_yt_cover](https://cloud.githubusercontent.com/assets/15214774/15842058/96d27430-2c1f-11e6-95e7-8d0fdd234bf9.jpg)

**Comment by arnaldos** [comment]
@isahq23  plz show this to @Kate99 to change all brand on social media.
