### ISSUE TITLE
Create a Image for Twitter Profile to Classifieds P2P App

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#892]
Banner size 1500x500 px

Profile size 500x500 px

**Comment by emmysm** [comment]
![profile-500-x-500](https://cloud.githubusercontent.com/assets/15143489/15876587/005ebdec-2cd8-11e6-8119-01adcabe2500.png)

@arnaldos @gabymado

**Comment by Joseangel2v** [comment]
![banners twitter](https://cloud.githubusercontent.com/assets/17457499/15883444/025b8faa-2d12-11e6-9473-79bd07fe4ff7.png)

**Comment by Joseangel2v** [comment]
@gabymado @emmysm @arnaldos

**Comment by arnaldos** [comment]
@emmysm  postea el logo definitivo

**Comment by arnaldos** [comment]
banner listo

**Comment by emmysm** [comment]
![classifieds logo-02](https://cloud.githubusercontent.com/assets/15143489/15894799/c172e656-2d51-11e6-9689-31a4777881f5.png)
@arnaldos @gabymado

**Comment by arnaldos** [comment]
nice job!! upload file and give @gabymado
