### ISSUE TITLE
Create a Image for Facebook Profile to Jobs P2P App

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#893]
Banner size 981x363 px

Profile size 180x180 px

**Comment by rosanacoronado** [comment]
@arnaldos @jhonmarquez92 

Proposal_1
![banner_facebook_p2p_jobs_-01](https://cloud.githubusercontent.com/assets/19508456/15939849/7017de0e-2e43-11e6-909b-83db8524ccd1.png)

**Comment by rosanacoronado** [comment]
@arnaldos @gabymado @jhonmarquez92 new proposals on screenshots to better visualize
Proposal_2
![fb_mp_1](https://cloud.githubusercontent.com/assets/19508456/15951645/fd886e6c-2e83-11e6-98d0-b3ec3526c8fd.jpg)

Proposal_3
![fb_mp_2](https://cloud.githubusercontent.com/assets/19508456/15951652/0585c240-2e84-11e6-9890-4c8c5a2f513b.jpg)

Proposal_4
![fb_mp_3](https://cloud.githubusercontent.com/assets/19508456/15951653/05b50118-2e84-11e6-8a31-9b43b6eebe23.jpg)

Proposal_5
![fb_mp_4](https://cloud.githubusercontent.com/assets/19508456/15951654/05f1aca8-2e84-11e6-9990-7375a4ed9811.jpg)

Proposal_6
![fb_mp_5](https://cloud.githubusercontent.com/assets/19508456/15951655/05f65622-2e84-11e6-9ce0-43cec7779fa2.jpg)

**Comment by arnaldos** [comment]
@rosanacoronado @gabymado  proposal 6 is good use that.

**Comment by gabymado** [comment]
Agreed @arnaldos @rosanacoronado

**Comment by rosanacoronado** [comment]
ok, good :+1:
