### ISSUE TITLE
Create a Image for Youtube Profile to Classifieds P2P App

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#894]
Banner size 2560x423 px

Profile size 250x250 px

**Comment by emmysm** [comment]
![youtube-profile](https://cloud.githubusercontent.com/assets/15143489/15876004/a20bb70c-2cd4-11e6-9350-c4ba6a88b56b.png)

@arnaldos @gabymado

**Comment by Joseangel2v** [comment]
![banners youtube](https://cloud.githubusercontent.com/assets/17457499/15883402/bb5d6bfa-2d11-11e6-9a6f-6a0481f30f4e.png)

**Comment by Joseangel2v** [comment]
@gabymado @emmysm @arnaldos

**Comment by arnaldos** [comment]
@emmysm postea el logo definitivo para el perfil

**Comment by arnaldos** [comment]
@Joseangel2v banner listo

**Comment by emmysm** [comment]
![250-x-250-profime-image](https://cloud.githubusercontent.com/assets/15143489/15893752/8a31f94e-2d4b-11e6-8c27-0767d17b2666.png)}

@arnaldos @gabymado

**Comment by arnaldos** [comment]
@emmysm @Joseangel2v please give to @gaby all image to refresh the social media pages

**Comment by arnaldos** [comment]
and web page
