### ISSUE TITLE
Create a Image for Twitter Profile to Jobs P2P App

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#895]
Banner size 1500x500 px

Profile size 500x500 px

**Comment by rosanacoronado** [comment]
@arnaldos @jhonmarquez92 
Proposal_1
![banner_twitter_p2p_jobs_-01](https://cloud.githubusercontent.com/assets/19508456/15939949/cbc82d44-2e43-11e6-9441-0cefbd20ced5.png)

**Comment by rosanacoronado** [comment]
@arnaldos
Proposal_2
![banner_twitter_p2p_jobs-1-01](https://cloud.githubusercontent.com/assets/19508456/15952397/4718c1a2-2e8a-11e6-843b-9c9a62830e9d.png)

Profile
![profile_twitter_p2p_jobs-01](https://cloud.githubusercontent.com/assets/19508456/15952398/471dbacc-2e8a-11e6-93c3-0faa1dc30f87.png)
