### ISSUE TITLE
Create a Image for Youtube Profile to Jobs P2P App

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#896]
Banner size 2560x423 px

Profile size 250x250 px

**Comment by rosanacoronado** [comment]
@arnaldos @jhonmarquez92 
Proposal_1
![banner_youtube_p2p_jobs-01](https://cloud.githubusercontent.com/assets/19508456/15940050/17333b52-2e44-11e6-84ec-32599458d495.png)

**Comment by rosanacoronado** [comment]
@arnaldos 
Banner_proposal_2
![banner_youtube_p2p_jobs-1-01](https://cloud.githubusercontent.com/assets/19508456/15952203/b0e6a60a-2e88-11e6-8d7f-1c7682ea0ec2.png)

Profile
![profile_youtube_p2p_jobs-01](https://cloud.githubusercontent.com/assets/19508456/15952208/b67f47c0-2e88-11e6-92aa-0d900270444b.png)
