### ISSUE TITLE
Create Logo for new Platform - Home Node Platform

### ISSUE THREAD

**Issue by acostarodrigo** [bitDubai/fermat-graphic-design#897]
We are creating a new platform called Home Node Platform.
I need the logo that will be used in the dev.fermat.org architecture diagrams.

![image](https://cloud.githubusercontent.com/assets/9518556/15838493/ada66eec-2c14-11e6-814d-c9dec7c1b288.png)

Name to display: FermatHNP
                            Home Node Platform

Logo:
This platform will hold functionality of the "Home Node", which is a Fermat Network Node the device is connecting to and is paying the fee for services. It is related to Fermat Communication Servers, payment and exchange of services.

The Home Node is a server (a PC or desktop computer) running Fermat code that allows the mobile device be visible to the entire worldwide Fermat network.

**Comment by proseuz** [comment]
My proposals
1
![home node platform-02](https://cloud.githubusercontent.com/assets/17308060/18066208/56d2a18e-6e05-11e6-8632-052860467f1a.jpg)
2
![home node platform-01](https://cloud.githubusercontent.com/assets/17308060/18066209/56f32f3a-6e05-11e6-96da-ec2ab62ab03a.jpg)

**Comment by arnaldos** [comment]
@jhonmarquez92  This logo is need to be the same graphics style like this http://dev.fermat.org/

**Comment by proseuz** [comment]
My proposal (again) 
1
![fermat_hnp-02](https://cloud.githubusercontent.com/assets/17308060/18076046/5ebeeee6-6e48-11e6-9c6b-dcf1be14c10a.jpg)
![fermat_hnp-01](https://cloud.githubusercontent.com/assets/17308060/18076047/5ecdbfd4-6e48-11e6-8e8e-1ecb808b2f5c.jpg)

**Comment by Magdy27** [comment]
![fermat-hnp](https://cloud.githubusercontent.com/assets/19651834/18091636/50e752aa-6e97-11e6-9803-441c4a062525.png)
![fermat-hnp2](https://cloud.githubusercontent.com/assets/19651834/18091637/50f1b934-6e97-11e6-8374-36bf83fe30d6.png)
![fermat-hnp3](https://cloud.githubusercontent.com/assets/19651834/18091638/50f254ca-6e97-11e6-9eba-2a3b8d4799cf.png)

@arnaldos

**Comment by ivonnesantos** [comment]
Me gusta el de John

**Comment by m471c4** [comment]
@Magdy27 please read the previous comments made about this issue. The graphic style for this has to be the same used for the other platform logos. Please, addapt your proposals to that and present them again.

**Comment by saraguerrerot** [comment]
los nodos del 1 con el dise;o base de las plataformas :smile: @Magdy27

**Comment by Magdy27** [comment]
![fermat-hnp2](https://cloud.githubusercontent.com/assets/19651834/18094288/f315ee3e-6ea0-11e6-9f53-a8bfd88ac987.png)

 @arnaldos @m471c4

**Comment by m471c4** [comment]
@Magdy27 the font for the platform name must be Aqua Groteske. Also, use the two shades of green and try to copy the stroke value. You can search the other platform logos on the repo for examples.

**Comment by m471c4** [comment]
@Magdy27 please present a version of the second proposal you posted at first, but addapted to the correct graphic style.

**Comment by saraguerrerot** [comment]
![image](https://cloud.githubusercontent.com/assets/19808868/18095143/01547a94-6ea4-11e6-8f1f-8987e056a043.png)

@arnaldos

**Comment by Jessicafp** [comment]
![fermat-home-node-platform1](https://cloud.githubusercontent.com/assets/19536846/18096697/20ebf9ae-6ea9-11e6-907d-5463a1375ee3.png)
![fermat-home-node-platform2](https://cloud.githubusercontent.com/assets/19536846/18096700/210b6cd0-6ea9-11e6-9cd7-7314a97610ee.png)
![fermat-home-node-platform3](https://cloud.githubusercontent.com/assets/19536846/18096701/2115b294-6ea9-11e6-810b-707e9da152d8.png)

**Comment by rosanacoronado** [comment]
@arnaldos @jhonmarquez92 
Proposal_1

![fermat_hnplogotipo-01](https://cloud.githubusercontent.com/assets/19508456/18099300/d98bbe90-6eb3-11e6-9d6a-d05067548c5e.png)
![fermat_hnpicono-02](https://cloud.githubusercontent.com/assets/19508456/18099413/6a1487ee-6eb4-11e6-8d29-76197ab14250.png)

**Comment by proseuz** [comment]
@Jessicafp 
- ningún elemento puede salir del primer circulo 
- no puede haber transparencias
- el stroke debe ser parejo y estar en todas las formas
- la sombra debe ir a 45°
- cuida que los elementos estén centrados
- no puedes superponer las formas como en tu propuesta 2

**Comment by Magdy27** [comment]
![1](https://cloud.githubusercontent.com/assets/19651834/18097988/4e66c242-6eae-11e6-815a-682441f175bc.png)
![2](https://cloud.githubusercontent.com/assets/19651834/18097989/4ebb0212-6eae-11e6-9b0c-1d71f287a625.png)
![3](https://cloud.githubusercontent.com/assets/19651834/18097990/4f2734b4-6eae-11e6-8e35-c8bd29c45cad.png)

@arnaldos @m471c4

**Comment by saraguerrerot** [comment]
![image](https://cloud.githubusercontent.com/assets/19808868/18100470/1fa8eb46-6eb9-11e6-84a9-75a8f82e359a.png)

@arnaldos

**Comment by Jessicafp** [comment]
![1](https://cloud.githubusercontent.com/assets/19536846/18104003/1810aa82-6ec7-11e6-94bf-111d282571c6.png)
![2](https://cloud.githubusercontent.com/assets/19536846/18104008/1e76f656-6ec7-11e6-8100-e82879772526.png)

**Comment by lisamarmolina** [comment]
Proposal 1
![1](https://cloud.githubusercontent.com/assets/19942022/18105647/2969a458-6ece-11e6-9320-2d0f1b5f0bdd.png)
![1_1](https://cloud.githubusercontent.com/assets/19942022/18105787/cf12cc4a-6ece-11e6-9e83-ebf0ddb999ae.png)

Proposal 2
![2](https://cloud.githubusercontent.com/assets/19942022/18105799/d765e742-6ece-11e6-9090-ce1750fb5745.png)
![2_2](https://cloud.githubusercontent.com/assets/19942022/18105804/dc59a9c8-6ece-11e6-85a3-5d23f28f4557.png)
@m471c4 @arnaldos

**Comment by rennyx7** [comment]
![hnp1](https://cloud.githubusercontent.com/assets/20045567/18106971/deda55da-6ed3-11e6-8732-332e448d7aa3.png)
![hnp2](https://cloud.githubusercontent.com/assets/20045567/18106973/def4318a-6ed3-11e6-9d01-0b7eb464bd2b.png)
@arnaldos

**Comment by saraguerrerot** [comment]
![image](https://cloud.githubusercontent.com/assets/19808868/18108813/1140fcc4-6edc-11e6-807a-0af2bd75d620.png)

@arnaldos

**Comment by proseuz** [comment]
@arnaldos @acostarodrigo  ¿Cuál funciona mejor?

**Comment by acostarodrigo** [comment]
para mi, sacando el tema del diseño en sí, el que es tecnicamente correcto es 
![image](https://cloud.githubusercontent.com/assets/9518556/18207697/98b457aa-7102-11e6-84b3-5e06de805c6e.png)

El Home Node es la "conexión" hacia otros dispositivos y otros home nodes. Es la puerta de acceso a la red P2P de IoP, es lo que permite que el dispositivo de uno sea visible a otros dispositivos.

**Comment by arnaldos** [comment]
vale perfecto ! siguiendo el comentario de @acostarodrigo  esta versión es la tuya @Jessicafp 

#### Comentarios:
- Sombras a 45°
- Reducir el tamaño de los elementos para que no estén pegados a los bordes.
- Centrar la composición de los nodos
- El nodo verde que esta a la derecha en la parte inferior que este a la misma distancia de del que esta arriba y el mismo tamaño.
- Las lineas blancas estandarizalas según el tamaño que se ha manejado en el resto de los logos de las plataformas

**Comment by Jessicafp** [comment]
![fermat-home-node-platform](https://cloud.githubusercontent.com/assets/19536846/18251174/87f0b846-7355-11e6-8372-9e6a8f373c7e.png)

@arnaldos

**Comment by proseuz** [comment]
@Jessicafp  el rectángulo rosa también debe llevar sombra. Aumenta el stroke, trata de que tenga un tamaño parecido a los logos que están en la pág  http://dev.fermat.org/

**Comment by Jessicafp** [comment]
![muestra-2](https://cloud.githubusercontent.com/assets/19536846/18259226/bad8953a-73af-11e6-91b6-69a6c6c803cc.png)

@jhonmarquez92 @arnaldos

**Comment by arnaldos** [comment]
aumenta el stroke de los circulos

**Comment by Jessicafp** [comment]
![nuevo](https://cloud.githubusercontent.com/assets/19536846/18280971/12b0407c-7429-11e6-9d53-e63c01d6b26a.png)

**Comment by proseuz** [comment]
@arnaldos  ¿crees que los círculos que están dentro de los círculos verdes deban ir?

**Comment by m471c4** [comment]
@jhonmarquez92 @Jessicafp los círculos más claros que están dentro de los círculos verdes no deben ir, los colores para cada sección son planos. Por lo demás lo veo bien. Asegúrate de que el stroke se mantenga igual cuando la imagen se reduzca.

Sube una versión final con el texto lateral para ver cómo queda, por favor..

**Comment by m471c4** [comment]
@Jessicafp hay una sombra que se mete un poco en una de las esquinas del rectángulo. Por favor acomódalo. Si es un rectángulo, nada debe atravesarlo, debe ser una sección de color plana del color rosado más claro. Si son líneas, ellas también "generan sombra", por lo que el área debe ser de color rosado oscuro.

Por favor, corríjelo cuanto antes porque esto se necesita rápido.

**Comment by Jessicafp** [comment]
![nuevo](https://cloud.githubusercontent.com/assets/19536846/18321304/5fe4f1da-74fb-11e6-9009-e62fb225dea1.png)

@jhonmarquez92 @arnaldos @m471c4 Ya solucione el problema del rectangulo, y ya elimine los circulos mas claros que estaban dentro, aqui el presento el final con el texto.

**Comment by m471c4** [comment]
@Jessicafp mucho mejor. Por favor pon la sombra de las líneas que unen los nodos pequeños con el nodo grande. Lo demás lo veo perfecto, Si @arnaldos no tiene ninguna otra corrección, puedes subir los editables.

**Comment by Jessicafp** [comment]
![nuevo](https://cloud.githubusercontent.com/assets/19536846/18334025/327d324c-7542-11e6-9bcf-6e679d2a1914.png)

**Comment by arnaldos** [comment]
@m471c4 @jhonmarquez92 @Jessicafp perfecto subelos  !!
