### ISSUE TITLE
CREATE A NEW LOGO FOR JOBS APP P2P

### ISSUE THREAD

**Issue by proseuz** [bitDubai/fermat-graphic-design#899]

**Comment by proseuz** [comment]
Rosana's proposals @rosanacoronado @gabymado @arnaldos 
1
![proposals logo-07](https://cloud.githubusercontent.com/assets/17308060/15909049/6742c4c0-2d8e-11e6-8bdc-825ccf39f997.png)
2
![proposals logo-01](https://cloud.githubusercontent.com/assets/17308060/15909050/679cf544-2d8e-11e6-8507-771a38f2e250.png)
3
![proposals logo-02](https://cloud.githubusercontent.com/assets/17308060/15909051/67c17702-2d8e-11e6-935f-49a9d192088c.png)
4
![proposals logo-04](https://cloud.githubusercontent.com/assets/17308060/15909052/67d8aa4e-2d8e-11e6-85a0-15d6aa097b74.png)
5
![proposals logo-05](https://cloud.githubusercontent.com/assets/17308060/15909054/67ef6090-2d8e-11e6-9fc6-412bed03f138.png)
6
![proposals logo-06](https://cloud.githubusercontent.com/assets/17308060/15909055/68016056-2d8e-11e6-814d-ab017b390806.png)
7 This proposal is based when underline the title of work on newspaper
![proposals logo-03](https://cloud.githubusercontent.com/assets/17308060/15909057/681cbe14-2d8e-11e6-8513-ac7af978a870.png)

**Comment by proseuz** [comment]
my proposals. @arnaldos @gabymado 
1 the concept of this proposal is based the _Jobs App_ open the door to the excelent works
![jobs logo-04](https://cloud.githubusercontent.com/assets/17308060/15909328/9912f96a-2d8f-11e6-90d6-38361f36e2fa.jpg)
2 handshake of characters representing the contract and opportunities![jobs logo-03](https://cloud.githubusercontent.com/assets/17308060/15909329/991ba6f0-2d8f-11e6-9b3f-661005313967.jpg)

**Comment by lostwood** [comment]
i like the first logo with the handshake

**Comment by arismendi227** [comment]
@jhonmarquez92 @arnaldos @gabymado 
proposals

1
![1](https://cloud.githubusercontent.com/assets/19276382/15912536/cfea5a5a-2d9e-11e6-8b3b-1c93d8a82e14.jpg)

2
![2](https://cloud.githubusercontent.com/assets/19276382/15912540/d5c9fbe2-2d9e-11e6-9858-d377b49e3e9e.jpg)

3
![3](https://cloud.githubusercontent.com/assets/19276382/15912545/dbc91aa0-2d9e-11e6-9e8b-256894eeef70.jpg)

4
![4](https://cloud.githubusercontent.com/assets/19276382/15912551/e0f44aae-2d9e-11e6-850a-f0a49fae765e.jpg)

5
![5](https://cloud.githubusercontent.com/assets/19276382/15912552/e511cd96-2d9e-11e6-900b-ecc5382fed71.jpg)

6
![6](https://cloud.githubusercontent.com/assets/19276382/15912558/ea1ee774-2d9e-11e6-9c3e-f88f2d407737.jpg)

**Comment by karentvillegas** [comment]
@gabymado @jhonmarquez92 @arnaldos 

Other proposals

1
![propuesta1](https://cloud.githubusercontent.com/assets/19273211/15913626/fd193414-2da4-11e6-95cd-b2d0dfe239d9.jpg)
2
![propuesta2](https://cloud.githubusercontent.com/assets/19273211/15913631/021c1684-2da5-11e6-8bd7-9fc5068157ac.jpg)
3
![propuesta3](https://cloud.githubusercontent.com/assets/19273211/15913642/07b419f2-2da5-11e6-840a-9a9de162323d.jpg)

**Comment by gabymado** [comment]
The one I like most is @arismendi227 proposal nr 4. I'd still work on it: friendlier and with a different font. @arnaldos? Let's define this ASAP!

**Comment by arnaldos** [comment]
@gabymado @jhonmarquez92  I think the same the proposal nr 4 to @arismendi227 is good. but just one thing. maybe delete the down element of the circle left and leave just check.

**Comment by proseuz** [comment]
I made changes to the proposed Carlos. @arnaldos @gabymado 
4.1
![jobs2-03](https://cloud.githubusercontent.com/assets/17308060/15933235/c8f7065a-2e28-11e6-962f-0363ad00e32a.jpg)
4.2
![jobs2-02](https://cloud.githubusercontent.com/assets/17308060/15933236/c90c5104-2e28-11e6-85d4-ca86b5f9e9a7.jpg)
4.3
![jobs22-03](https://cloud.githubusercontent.com/assets/17308060/15933538/e53ab004-2e29-11e6-8136-ac172c22f4e6.jpg)
4.4
![jobs22-04](https://cloud.githubusercontent.com/assets/17308060/15933539/e55054c2-2e29-11e6-8211-1b7522748539.jpg)

**Comment by proseuz** [comment]
4.5 I modified the check to make it more like j @arnaldos 
![jobs2-02](https://cloud.githubusercontent.com/assets/17308060/15935444/0fa00946-2e31-11e6-84bd-68649def6698.png)

**Comment by arnaldos** [comment]
aproved 4.5 !! :+1:
