### ISSUE TITLE
Create a Redesign Broshue for Java Developers 

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#902]
Day Delivery  Today 09-06-2016

Actual broshure

![java dev](https://cloud.githubusercontent.com/assets/13594347/15928663/17962d5c-2e12-11e6-89cc-0424d21f7e26.jpg)

Email Adress: d.csendes@fermat.org

This broshure is to hungry

Reference broshure in this #427

**Comment by solemiliia** [comment]
use Roboto y lo hice 1080x1080px
![redesign broushes-4](https://cloud.githubusercontent.com/assets/19818549/15936077/6eb3f40e-2e33-11e6-8066-04e9bdb86252.jpg)
![redesign broushes-1](https://cloud.githubusercontent.com/assets/19818549/15936170/cdd2b5c4-2e33-11e6-8fa2-9e03d03e1c66.jpg)
![redesign broushes-2](https://cloud.githubusercontent.com/assets/19818549/15936171/cdd9ff78-2e33-11e6-9bce-bb1c85099336.jpg)
![redesign broushes-3](https://cloud.githubusercontent.com/assets/19818549/15936172/cdde40e2-2e33-11e6-99a1-ca243fb943ce.jpg)

**Comment by solemiliia** [comment]
![1](https://cloud.githubusercontent.com/assets/19818549/15951444/06bcc066-2e82-11e6-8c21-6b8719115e5e.jpg)

**Comment by solemiliia** [comment]
![2](https://cloud.githubusercontent.com/assets/19818549/15951694/4e81c9ee-2e84-11e6-857a-70ea2e1c1918.jpg)

**Comment by solemiliia** [comment]
1
![1](https://cloud.githubusercontent.com/assets/19818549/15952344/b965e40c-2e89-11e6-953c-d031f9d72682.jpg)
2
![3](https://cloud.githubusercontent.com/assets/19818549/15952359/f87beaa6-2e89-11e6-9804-e45f95238a88.jpg)

**Comment by solemiliia** [comment]
3
![4](https://cloud.githubusercontent.com/assets/19818549/15952670/c9290ede-2e8c-11e6-8e61-5527ae03d8e9.jpg)
4
![5](https://cloud.githubusercontent.com/assets/19818549/15952679/dfe14e20-2e8c-11e6-99d0-1d432b4e0f5e.jpg)

**Comment by solemiliia** [comment]
5
![1](https://cloud.githubusercontent.com/assets/19818549/15961335/fd30ca50-2ecd-11e6-9c45-6fa3c694a17a.jpg)
6
![2](https://cloud.githubusercontent.com/assets/19818549/15961340/0bc02d4a-2ece-11e6-8c8d-d7ca894e06f9.jpg)
![2](https://cloud.githubusercontent.com/assets/19818549/15961368/2fc76b4a-2ece-11e6-8d19-0d4e00d99d6d.jpg)

**Comment by solemiliia** [comment]
la cargue dos veces, disculpa

**Comment by arnaldos** [comment]
@solemiliia 

#### Correcciones:
- Personaje del lado derecho 
- Texto a la izquierda
- Background mas claro
- Logo a la izquierda 
- Baja el vector azul para que entre el logo del lado izquierdo sin reducir el tamaño.
- Aumenta un poco el tamaño de personaje que este por encima del vector de arriba pero interno al de abajo asi generaremos profundidad.
- Los iconos no estoy seguro muestra una versión con asteriscos o algo por el estilo para marcar cada punto.

**Comment by solemiliia** [comment]
7 
![3](https://cloud.githubusercontent.com/assets/19818549/15979980/76d1c1b2-2f31-11e6-9f6e-851d6564b920.jpg)
