### ISSUE TITLE
P2P Jobs App UX/UI

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#904]

**Comment by arnaldos** [comment]
@gabymado @darkestpriest @lostwood The App First look 

![jobs](https://cloud.githubusercontent.com/assets/13594347/15957683/79614f14-2eba-11e6-9800-6b7ab76bd907.png)

**Comment by lostwood** [comment]
Excellent work @arnaldos , 

I think the login could be in the identity maybe like this

![selection_002](https://cloud.githubusercontent.com/assets/16200298/15968012/274f8ec8-2ef8-11e6-9a19-b28726eaa9b6.png)

-The community

![selection_001](https://cloud.githubusercontent.com/assets/16200298/15968041/4a0628c8-2ef8-11e6-99d5-c36d3cb5f32e.png)

-The Selection of country , city and filters in another view

![selection_020](https://cloud.githubusercontent.com/assets/16200298/15968162/d2f1d056-2ef8-11e6-8fe7-26c5bc2a5636.png)

-The search

![selection_012](https://cloud.githubusercontent.com/assets/16200298/15968211/0032220a-2ef9-11e6-8261-3cd6fc0b83ff.png)

I believe this way, with a better design, could improve the user experience

**Comment by darkestpriest** [comment]
I think that design can work, but, I don't see if we need a password field in the identity @lostwood @arnaldos

**Comment by arnaldos** [comment]
@darkestpriest Maybe you have right, we can change some funtions, tonight i send you others views more complete.

**Comment by arnaldos** [comment]
@lostwood @darkestpriest here I share the mockups to profiles and search jobs. @jhonmarquez92  are making the communities.

![jobs2](https://cloud.githubusercontent.com/assets/13594347/16108075/9a5a164c-336a-11e6-81bf-28fb257c8fad.png)

**Comment by darkestpriest** [comment]
Muy buen trabajo @arnaldos y @jhonmarquez92 pero, en la primera versión no existirá "Search jobs", se necesita una community en la cual se pueden buscar candidatos, de igual forma, deja las pantallas de search jobs para la versión 2.

**Comment by arnaldos** [comment]
@darkestpriest perfecto !! en este caso las communities @jhonmarquez92 nos esta dando un mano con eso.
