### ISSUE TITLE
Create a banner for P2P Artist Platform

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#905]
Dimensions for this banner: 922x201

Artist Platform

Is the platform allows artists interaction with users of the app . allowing the sale of his art. ( music, pictures , etc. depending on the performance of the artist).

we need a banner image for web page.

**Comment by arnaldos** [comment]
@GustavoDeMoura plz encárgate de esto, cualquier duda avísame.

**Comment by GustavoDeMoura** [comment]
@arnaldos aqui estan las 3 propuestas base para el banner de la app, necesito que me pases el logo y un screen de la app para presentarlo mas completo y pulido todavia. 

Hazme saber si hay alguna correccion o cambio que hacer.

PD: El primero es el mas viable personalmente hablando.

![bannerv3](https://cloud.githubusercontent.com/assets/19398432/16360177/c06a5020-3b28-11e6-95e2-6318015c54b2.jpg)
![bannerv2](https://cloud.githubusercontent.com/assets/19398432/16360178/c5630f22-3b28-11e6-95d0-fdc12a0d9875.jpg)
![bannerv1](https://cloud.githubusercontent.com/assets/19398432/16360179/c79e9d06-3b28-11e6-869f-ce8c272945b9.jpg)

**Comment by arnaldos** [comment]
ok creo el concepto no se entendió, la plataforma artist permite que los artistas en sus multiples ramas (musicos, artistas plasticos entre otros puedan vender su arte atraves de la app ) actualmente solo ha sido enfocado a la musica contamos con una plataforma que permite comprar y administrar las cansiones del artista y a su ves cuenta con un reproductor para las canciones encriptadas

**Comment by GustavoDeMoura** [comment]
Nuevo diseño para la propusta del banner. Esta vez mas acorde con el tema de la App en si, que es el de compartir todo tipo de arte en especial (y por ahora) el musical. Cualquier duda sobre lo que se presenta preguntame o si hay que cambiar algo tambien @arnaldos ,  El espacio en blanco entre las dos barras es donde iria el logo, que pido por favor para colocarlo, asi como tambien una captura de la App para colocar en la Tablet

![banner2v1](https://cloud.githubusercontent.com/assets/19398432/16402749/2be4f7c2-3cc5-11e6-84f4-d352991b8ec7.jpg)
![banner2v2](https://cloud.githubusercontent.com/assets/19398432/16402750/2bf22a82-3cc5-11e6-84ee-271980aadc79.jpg)

**Comment by arnaldos** [comment]
@GustavoDeMoura  usa algo mas a una persona o varias, escuchando música a través del dispositivo ( un telefono ). revisa los colores usados en la app. busca los mockups en el repo para que veas el stilo grafico manejado. Fan wallet - artist wallet

**Comment by GustavoDeMoura** [comment]
Iconos cambiados a unos mas acorde con la tematica de la app, los colores propuestos son los utilizados en la app y la imagen fue cambiada igual por algo mas acorde al tema. @arnaldos 

![banner3v2](https://cloud.githubusercontent.com/assets/19398432/16526918/13222eb8-3f8a-11e6-8344-64d72cbc7a26.jpg)

![banner3v1](https://cloud.githubusercontent.com/assets/19398432/16526916/12e07694-3f8a-11e6-8950-c6dcc125d45c.jpg)

**Comment by arnaldos** [comment]
usa algo mas plane, mas minimalista como lo estan trabajando en datting, pero usando los colores de la app fijate en esta imagen de muestra 
![image](https://cloud.githubusercontent.com/assets/13594347/16569789/9f351b74-4208-11e6-96a6-bcb5f7f24ede.png)

**Comment by GustavoDeMoura** [comment]
Esta es la manera mas minimalista que puedo dejar este banner para que no que no quede tan vacio. Igual transmite la esencia de la App @arnaldos 

![banner4v1](https://cloud.githubusercontent.com/assets/19398432/16596847/1fa2e8ae-42cc-11e6-80b9-8a5fcb2ea067.jpg)

**Comment by arnaldos** [comment]
replanteala plz

**Comment by GustavoDeMoura** [comment]
Banners Nuevas Propuestas @arnaldos 

![banner5](https://cloud.githubusercontent.com/assets/19398432/16777767/4d7443a2-4841-11e6-9c3a-e5302c23c1ca.jpg)

![banner6](https://cloud.githubusercontent.com/assets/19398432/16777768/4d79815a-4841-11e6-998a-a05c1fccf833.jpg)

**Comment by arnaldos** [comment]
@GustavoDeMoura Aun no me parece que transmita te dejo unos ejemplos para que te sirva de guia del concepto que queremos manejar, usa la paleta de colores usada en la identidad.

## ![screenshot_4](https://cloud.githubusercontent.com/assets/13594347/16787356/a95e289a-4869-11e6-888c-0d91b96c6da4.png)

## ![screenshot_5](https://cloud.githubusercontent.com/assets/13594347/16787357/a960b25e-4869-11e6-908e-12d768f7901d.png)

## ![screenshot_1](https://cloud.githubusercontent.com/assets/13594347/16787358/a9623dcc-4869-11e6-936d-492cc695a2f1.png)

## ![screenshot_2](https://cloud.githubusercontent.com/assets/13594347/16787359/a963386c-4869-11e6-82da-eea99a9ad67d.png)

![screenshot_3](https://cloud.githubusercontent.com/assets/13594347/16787360/a965f700-4869-11e6-9276-c537d69edd87.png)

**Comment by arnaldos** [comment]
@GustavoDeMoura necesitamos esto con urgencia plz dale prioridad

**Comment by GustavoDeMoura** [comment]
@arnaldos 

![8](https://cloud.githubusercontent.com/assets/19398432/16886144/7f7c0504-4aa0-11e6-8d1c-181be4da03ac.jpg)

**Comment by arnaldos** [comment]
@GustavoDeMoura excelente !! solo una cosa, genera una variación de esta versión donde se incluyan ambas apps fan wallet y music player.
- Del lado izquierdo fan wallet y el derecho music player. 
- Manten las lineas de la izquierda cambiando solo a los colores de la fan wallet.
- Revisa la proporción del ultimo mockup del la derecha. se ve estirado pero no se si es algo visual confirmarme esto plz.

**Comment by GustavoDeMoura** [comment]
variacion con el logo de la Fan Wallet manteniendo el diseño previo..
solo me falta los mock ups de la fan wallet para ponerlo con en la music player. si puedes mandarmelos seria genial. @arnaldos 

![8-1](https://cloud.githubusercontent.com/assets/19398432/16955978/093f7384-4dad-11e6-81a3-cd29ae23ac20.jpg)

**Comment by arnaldos** [comment]
@GustavoDeMoura Ya te pase los mockups por slack las lineas de la fan inviertelas que vallan hacia el centro de la imagen,
porfa termina esto hoy lo necesitamos con urgencia

**Comment by GustavoDeMoura** [comment]
@arnaldos 

![8-1](https://cloud.githubusercontent.com/assets/19398432/17010470/a6c1ceb2-4eda-11e6-9126-e0e8ddac3354.jpg)

**Comment by arnaldos** [comment]
@GustavoDeMoura Del lado de la fan invierte la ubicacion del tlf y los mockups dejando el telefono hacia el centro.

**Comment by GustavoDeMoura** [comment]
asi no? @arnaldos 

![8-2](https://cloud.githubusercontent.com/assets/19398432/17012478/5d7d6ea0-4eee-11e6-9515-2903ffdad95a.jpg)

**Comment by GustavoDeMoura** [comment]
@arnaldos 

![8-1 escalera](https://cloud.githubusercontent.com/assets/19398432/17108995/67dff134-526c-11e6-86c2-dfcf085813aa.jpg)

**Comment by arnaldos** [comment]
:+1:
