### ISSUE TITLE
P2P Jobs Community  UX 

### ISSUE THREAD

**Issue by proseuz** [bitDubai/fermat-graphic-design#907]

**Comment by proseuz** [comment]
@gabymado @arnaldos @lostwood @darkestpriest 
![community jobs](https://cloud.githubusercontent.com/assets/17308060/16063564/eb89df32-3263-11e6-859e-1487a587d29a.png)

**Comment by proseuz** [comment]
Here is the last mockup to the Jobs Community,  with the changes suggested for @arnaldos  and @lostwood  in the meeting todays @gabymado @Luis-Fernando-Molina @darkestpriest 
![community jobs employer version 1-01](https://cloud.githubusercontent.com/assets/17308060/16137659/5d111336-33ff-11e6-9a89-343e4f9b0656.png)

**Comment by darkestpriest** [comment]
I like the screens @jhonmarquez92

**Comment by lostwood** [comment]
I like too, great work
