### ISSUE TITLE
Create a graphics to Network

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#908]
Networks 

![pasted image at 2016_06_14 08_08 pm](https://cloud.githubusercontent.com/assets/13594347/16068604/fa57f27e-3290-11e6-9468-3312e1b771a1.png)

**Comment by solemiliia** [comment]
![centralizado](https://cloud.githubusercontent.com/assets/19818549/16090417/25531e82-32f9-11e6-9a45-ca150704ca65.jpg)
![descentralizado](https://cloud.githubusercontent.com/assets/19818549/16090418/25613940-32f9-11e6-8294-e8d53b44c970.jpg)
![Uploading distribuida.jpg…]()

**Comment by solemiliia** [comment]
![distribuida](https://cloud.githubusercontent.com/assets/19818549/16090846/f194c27e-32fa-11e6-9552-cacda78cb84c.jpg)

**Comment by arnaldos** [comment]
@solemiliia los cambios 
- Quita el texto que dice Fermat P2P Network en todos los gráficos 
- Coloca un nodo central para la red centralizada 
- Las otras dos no deben tener nodos en el centro

@Rart3001 estas son mis observaciones no se si hay algo mas en que nos puedas orientar ?

**Comment by Rart3001** [comment]
@solemiliia @arnaldos: Solo necesito la imagen de la red centraliza y la descentralizada. En la primera solo existe un nodo central (Servidor), y en la segunda hay múltiples nodos (Servidores) interconectados entre si, a mi parecer las imágenes que ustedes crearon son las misma y solo le cambiaron el titulo, y por favor poner los títulos en ingles.   "Centralized Network" y  "Decentralised Network" si no me equivoco.

**Comment by solemiliia** [comment]
![centralizado](https://cloud.githubusercontent.com/assets/19818549/16095851/44b048d8-3310-11e6-9201-5a500886d2bc.jpg)
![descentralizado 2](https://cloud.githubusercontent.com/assets/19818549/16095909/88ff327e-3310-11e6-99ad-46ca2b903912.jpg)

**Comment by solemiliia** [comment]
![centralizado](https://cloud.githubusercontent.com/assets/19818549/16104914/3752593a-334f-11e6-8ce5-8111210191f6.jpg)
![descentralizado](https://cloud.githubusercontent.com/assets/19818549/16104924/597677c6-334f-11e6-85b4-c0ea3bf443b5.jpg)

**Comment by Rart3001** [comment]
@solemiliia  Gracias quedo muy bien :+1:, gracias a ti también @arnaldos

**Comment by arnaldos** [comment]
no fue nada @Rart3001 buen trabajo @solemiliia

**Comment by solemiliia** [comment]
Gracias a ustedes @Rart3001 @Rart3001
