### ISSUE TITLE
Create a banner for P2P CHAT Platform

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#909]
Dimensions for this banner: 922x201

Reference
![image](https://cloud.githubusercontent.com/assets/13594347/16141642/ab0c9b5a-3427-11e6-8b30-1cec5687657c.png)

**Comment by andiechan** [comment]
![banner_01](https://cloud.githubusercontent.com/assets/19866300/16232996/94566f5e-3796-11e6-82b1-e1e96f8fe027.JPG)

**Comment by andiechan** [comment]
![banner_02](https://cloud.githubusercontent.com/assets/19866300/16233001/9b5fa5f4-3796-11e6-9dc6-0dff5bdd568a.JPG)

**Comment by arnaldos** [comment]
@andiechan 

Cambia el texto de fermat chat por P2P chat 
Trabajemos con la version 1 
Si vas a mostrar la pantalla que sea la que ya esta establecida en para la app
los iconos de fondo ya tenemos unos establecido en el banner de bienvenida revisalos e incluye esos en este banner.

**Comment by solemiliia** [comment]
@andiechan  creo que también si inviertes los colores del degradado, para que el icono del chat haga un poco de contraste con el fondo

Ambas debemos trabajar el mismo?

**Comment by arnaldos** [comment]
sol esta actividad es de andrea

**Comment by andiechan** [comment]
![chatapp_banner_03](https://cloud.githubusercontent.com/assets/19866300/16244007/bfa12ec4-37c3-11e6-84b4-69f4946500f2.jpg)

**Comment by andiechan** [comment]
Estoy probando otras opciones a ver que tal se ven

**Comment by arnaldos** [comment]
Prueba una versión con los vectores que hacen de fondo en color negro similar al banner de bienvenida

**Comment by andiechan** [comment]
![banner_06](https://cloud.githubusercontent.com/assets/19866300/16268293/a20c4f3a-3857-11e6-86d7-7d5a6ed14011.png)
![banner_07](https://cloud.githubusercontent.com/assets/19866300/16268295/a22a24f6-3857-11e6-94ac-f9ac0f235da0.png)
![banner_08](https://cloud.githubusercontent.com/assets/19866300/16268296/a2395b06-3857-11e6-9e3f-89013914bb07.png)

**Comment by arnaldos** [comment]
la tercera subela al repo ! estandariza el resto de los banners delas redes con esto

**Comment by andiechan** [comment]
vale
