### ISSUE TITLE
Create a banner Fermat P2P Network

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#910]
Dimensions for this banner: 922x201

Reference 

![image](https://cloud.githubusercontent.com/assets/13594347/16141760/b7035452-3428-11e6-8c41-48920417df8b.png)

**Comment by rosanacoronado** [comment]
@arnaldos @jhonmarquez92 Here are my proposals, based on the graph found on the website
Proposal_1.1
![banner 2_2-01](https://cloud.githubusercontent.com/assets/19508456/16281640/1f9a88ae-388f-11e6-82e7-9e45e8fe8bb0.png)
Porposal_1.2
![banner 2_3-01](https://cloud.githubusercontent.com/assets/19508456/16281651/2bff271c-388f-11e6-98eb-6beb5d06c597.png)

Proposal_2
![banner 2_6-01](https://cloud.githubusercontent.com/assets/19508456/16281670/40a0379c-388f-11e6-9351-7ff26a2e4856.png)

Proposal_3
![banner 3_3-01](https://cloud.githubusercontent.com/assets/19508456/16281687/54fb20b2-388f-11e6-96ed-f897e31aa711.png)

Proposal_4
![p2p network banner 2-01](https://cloud.githubusercontent.com/assets/19508456/16281727/79372c64-388f-11e6-8768-b71fda6f3f5e.png)

Proposal_5.1
![banner 3_4-01](https://cloud.githubusercontent.com/assets/19508456/16281736/80573732-388f-11e6-88a2-edc9d65fd67a.png)

Porposal_5.2
![banner 3_1-01](https://cloud.githubusercontent.com/assets/19508456/16281737/807793e2-388f-11e6-8c27-2b06b3d2d8ac.png)

**Comment by arnaldos** [comment]
version 5.1

**Comment by proseuz** [comment]
Estoy de acuerdo @rosanacoronado
