### ISSUE TITLE
Create a banner Crypto Broker Platform

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#911]
Dimensions for this banner: 922x201

Reference

![image](https://cloud.githubusercontent.com/assets/13594347/16141739/8cbd49fa-3428-11e6-9b14-e947eeaf4cac.png)

**Comment by solemiliia** [comment]
1 
![banner crypto 1](https://cloud.githubusercontent.com/assets/19818549/16306370/47c51568-3927-11e6-85fb-d3f8f4cdb943.jpg)
2
![banner crypto 2](https://cloud.githubusercontent.com/assets/19818549/16306476/a9708ebe-3927-11e6-987d-0490b6085987.jpg)
3
![banner crypto 3](https://cloud.githubusercontent.com/assets/19818549/16306538/da83987a-3927-11e6-9525-5a5f307f642f.jpg)
4
![banner crypto 4](https://cloud.githubusercontent.com/assets/19818549/16307015/9620131e-3929-11e6-9d31-7fcdadb5566e.jpg)

**Comment by arnaldos** [comment]
hola @solemiliia  trabajemos con la versión 4, cambios:
- Usa las monedad Btc que trabajo @jonathanborges3d 
- Genera una propuesta con los vectores apegados a los colores del logo.

Aquí puedes conseguir las imágenes https://github.com/Fermat-ORG/media-kit

**Comment by solemiliia** [comment]
1
![banner crpto 2](https://cloud.githubusercontent.com/assets/19818549/16326261/c0719d30-398e-11e6-9f92-3e4acf076e9d.jpg)
2
![banner crypto 1](https://cloud.githubusercontent.com/assets/19818549/16326262/c0c874c0-398e-11e6-8e66-c2fa58882596.jpg)

**Comment by arnaldos** [comment]
@solemiliia una version con los vectores naranja en tonos verdes y azules

**Comment by solemiliia** [comment]
1
![banner crypto6](https://cloud.githubusercontent.com/assets/19818549/16340138/406cb84c-39f0-11e6-92b4-aa09757218d2.jpg)
2
![banner crypto 7](https://cloud.githubusercontent.com/assets/19818549/16340278/0dc636f6-39f1-11e6-9776-e872756ad02b.jpg)

**Comment by arnaldos** [comment]
Ok version 1

**Comment by solemiliia** [comment]
el degradado y todo de los vectores en esa dirección?

**Comment by arnaldos** [comment]
ok que propones ?

**Comment by solemiliia** [comment]
Solo era una pregunta @arnaldos  le hice unos ajustes mínimos en el degradado, la dirección del degradado y la opacidad de la imagen de fondo 
![banner crypto broker](https://cloud.githubusercontent.com/assets/19818549/16343529/57d55dd4-3a01-11e6-98a3-a4ef2214ae9d.jpg)

**Comment by arnaldos** [comment]
lo dejamos asi !!

**Comment by arnaldos** [comment]
@solemiliia un cambio debemos incluir el logo de la customer también, sorry!!

**Comment by solemiliia** [comment]
1
![banner crypto 8](https://cloud.githubusercontent.com/assets/19818549/16360328/f8396c7c-3b26-11e6-98fd-4b7e0c1c4671.jpg)
2
![banner crypto 9](https://cloud.githubusercontent.com/assets/19818549/16360354/72d559ae-3b28-11e6-90cc-3e80b99c055e.jpg)

**Comment by arnaldos** [comment]
Hola @solemiliia ese no es el logo de la crypto customer, por otro lado como ambos deben tener la misma importancia deberían ir en la misma linea.

Imagen de Referencia logo Crypto Customer

![image](https://cloud.githubusercontent.com/assets/13594347/16382329/29a9f532-3c4a-11e6-8ce5-4fa02027de27.png)

**Comment by solemiliia** [comment]
1
![banner crypto 1](https://cloud.githubusercontent.com/assets/19818549/16401410/0ff94336-3cae-11e6-9ddc-9f290fe8ab4b.jpg)
2
![banner crypto 2](https://cloud.githubusercontent.com/assets/19818549/16401456/81679e46-3cae-11e6-9190-f404bcb92903.jpg)

**Comment by arnaldos** [comment]
@solemiliia  lleva este banner, al concepto que se maneja en esta imagen en el sentido que se incluyen las 4 apps de CBP 

https://cloud.githubusercontent.com/assets/19942022/17110208/da374a3c-5269-11e6-88db-e025f999635d.png

**Comment by solemiliia** [comment]
pero sigo trabajando solo las dos que tengo no?

**Comment by m471c4** [comment]
@lisamarmolina apoya a Sol con este caso, por favor. Sigue un lineamiento gráfico similar al que estabas manejando para las imagenes del slider.

**Comment by lisamarmolina** [comment]
@m471c4 @arnaldos 
1
![cbpbanner](https://cloud.githubusercontent.com/assets/19942022/17423462/d2ef9e1a-5a88-11e6-84aa-dd2cfbee9d16.png)

2
![cbpbanner2](https://cloud.githubusercontent.com/assets/19942022/17423477/debe2b44-5a88-11e6-8bb6-20dc33db2a57.png)

3
![cbpbanner3](https://cloud.githubusercontent.com/assets/19942022/17423480/e40c252e-5a88-11e6-8aa5-82d76111e796.png)

**Comment by arnaldos** [comment]
@lisamarmolina sube el 2ro plz!!!

**Comment by lisamarmolina** [comment]
Vale, perfecto, lo subo ya al repo @arnaldos
