### ISSUE TITLE
Create a Image for Youtube Profile to Chat P2P App

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#913]
Banner size 2560x423 px

Profile size 250x250 px

**Comment by andiechan** [comment]
¡Buen día Arnaldo!.
En este caso, ¿se busca crear el mismo estilo para todas las redes?
Quedo atenta

**Comment by andiechan** [comment]
![youtube-banner_02](https://cloud.githubusercontent.com/assets/19866300/16315720/41761452-394d-11e6-82cb-571c64e70e4e.png)
![youtube_banner](https://cloud.githubusercontent.com/assets/19866300/16315721/419a7a0e-394d-11e6-8973-cff2352ed3ec.png)
![youtube_profile](https://cloud.githubusercontent.com/assets/19866300/16315722/41b3039e-394d-11e6-9675-7f3378df6cd5.png)

**Comment by arnaldos** [comment]
Version 1 del banner elimina el icono ya que se mostrara en la imagen de perfil, para el perfil en el icono elimina los 3 puntos de abajo y los elementos de fondo

**Comment by andiechan** [comment]
![youtube_profile](https://cloud.githubusercontent.com/assets/19866300/16343359/8a7278e0-3a00-11e6-8e2a-b37a10c1c3d8.png)

**Comment by andiechan** [comment]
![youtube_banner](https://cloud.githubusercontent.com/assets/19866300/16543061/ec1bdb40-4090-11e6-9d7f-992792d2f9a6.jpg)
![youtube_mock up-03](https://cloud.githubusercontent.com/assets/19866300/16543062/ec1e884a-4090-11e6-8593-8ed16c020b07.jpg)

**Comment by andiechan** [comment]
![youtube_04](https://cloud.githubusercontent.com/assets/19866300/16704933/20f89adc-454c-11e6-8ed9-9198ffb8af43.jpg)
![Uploading Youtube_Mock up_02.jpg…]()

**Comment by andiechan** [comment]
![youtube_04](https://cloud.githubusercontent.com/assets/19866300/16704933/20f89adc-454c-11e6-8ed9-9198ffb8af43.jpg)
![youtube_mock up_02](https://cloud.githubusercontent.com/assets/19866300/16704934/20fa6a6a-454c-11e6-873e-4f36f7bd5664.jpg)

**Comment by arnaldos** [comment]
@andiechan subiste esto al repo ?

**Comment by andiechan** [comment]
@arnaldos aun no, estoy esperando la aprobación de los 3 diseños para subirlos al repo.

**Comment by arnaldos** [comment]
si subelos !!

**Comment by arnaldos** [comment]
@andiechan esto esta en el repo ?
