### ISSUE TITLE
Create a Image for Twitter Profile to Chat App

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#914]
Banner size 1500x500 px

Profile size 500x500 px

**Comment by andiechan** [comment]
¡Buen día Arnaldo!.
2 cositas, el logo de Fermat en formato PNG si me lo puedes facilitar por favor.
¿y que tipo de estilo se requiere para esta cuenta?, ¿Lleva algún texto?.
Quedo atenta

**Comment by arnaldos** [comment]
@andiechan Los recursos los puedes encontrar en el repo, para esta oportunidad debemos trabajar con el logo de chat. cualquier duda escribeme al slack

**Comment by andiechan** [comment]
![twitter_01](https://cloud.githubusercontent.com/assets/19866300/16247612/5890d098-37d4-11e6-829f-639ad2f3412c.JPG)
![twitter_02](https://cloud.githubusercontent.com/assets/19866300/16247609/586faa9e-37d4-11e6-8923-b18063631e68.JPG)
![twitter_03](https://cloud.githubusercontent.com/assets/19866300/16247611/588fb6ea-37d4-11e6-9403-b162e35151be.JPG)

**Comment by andiechan** [comment]
![twitter_05](https://cloud.githubusercontent.com/assets/19866300/16250959/b177a436-37eb-11e6-8d18-0c8ff209cfec.JPG)
![twitter_06](https://cloud.githubusercontent.com/assets/19866300/16250960/b22e10ea-37eb-11e6-9676-0bdd67d36499.JPG)

**Comment by andiechan** [comment]
Twitter Banner y profile: 

![banner-twitter_01](https://cloud.githubusercontent.com/assets/19866300/16313807/b1147dd4-3944-11e6-92e2-d7880461304d.png)
![twitter-profile_01](https://cloud.githubusercontent.com/assets/19866300/16313808/b152b932-3944-11e6-9e66-d1a1234d873c.png)

**Comment by arnaldos** [comment]
el aviable on eliminalo, elimina el icono ya que se mostrara en la imagen de perfil, para el perfil en el icono elimina los 3 puntos de abajo y los elementos de fondo

**Comment by andiechan** [comment]
![twitter](https://cloud.githubusercontent.com/assets/19866300/16343574/ac71760c-3a01-11e6-811c-0da006e9010c.png)
![twitter_profile](https://cloud.githubusercontent.com/assets/19866300/16343575/ac72910e-3a01-11e6-9dbf-e6b2c580a68a.png)

**Comment by andiechan** [comment]
¿Como subo los archivos al repositorio?

**Comment by arnaldos** [comment]
mediante la herramienta del github, a incluir los archivos dentro de la carpeta. avisame cualquier cosa y te ayudo

**Comment by andiechan** [comment]
![twitter](https://cloud.githubusercontent.com/assets/19866300/16437785/6593cbb6-3d73-11e6-9a09-4deae46238c3.jpg)
![twitter_mock up-02](https://cloud.githubusercontent.com/assets/19866300/16437786/65b1ccd8-3d73-11e6-9ba6-eb63892ad7b7.jpg)
![twitter_mock up-05](https://cloud.githubusercontent.com/assets/19866300/16437787/65bcc7d2-3d73-11e6-9f7f-8783f6809950.jpg)
![01](https://cloud.githubusercontent.com/assets/19866300/16437788/65c1a23e-3d73-11e6-96f5-080940ccf46a.jpg)

**Comment by arnaldos** [comment]
@andiechan Me gusta la versión del teléfono, pero ese telefono sino me equivoco es un iphone actualmente fermat tiene soporte únicamente en android 
- los iconos del backgound se pueden reducir un poco 
- prueba colocar dos dispositivos uno en cada lado / o dos personas.
- el grafico de la burbuja hecha a mano esta bien se queda.

**Comment by andiechan** [comment]
Te paso otras propuestas con dispositivos samsung y las sugerencias que me comentaste:
![muestra02_twitter](https://cloud.githubusercontent.com/assets/19866300/16526177/b3a3961c-3f79-11e6-856a-d28a9a0b6469.jpg)
![muestra01_twitter](https://cloud.githubusercontent.com/assets/19866300/16526178/b3aaca72-3f79-11e6-8e1a-7fb35b0e9348.jpg)

Estoy armando más versiones para ver si damos con las finales y de esa forma arrancar con otros proyectos.

**Comment by andiechan** [comment]
ah y cuando tengas un chance para que me me enseñes rapidito a subir las cosas al repo, sol se ofreció también, ahorita le digo.

**Comment by andiechan** [comment]
![twitter_banner_02](https://cloud.githubusercontent.com/assets/19866300/16543092/f28a4cda-4092-11e6-979a-2ffeca097e14.JPG)

**Comment by andiechan** [comment]
![twitter _otro banner](https://cloud.githubusercontent.com/assets/19866300/16565459/4c7a97e2-41db-11e6-9791-567a842624d5.JPG)

**Comment by arnaldos** [comment]
@andiechan plz enumera las versiones para poder, evaluar mas fácil.

pero esta seria la version 

![image](https://cloud.githubusercontent.com/assets/13594347/16569515/5f1ca83e-4205-11e6-98c5-4edef59ca744.png)

montala en un perfil para ver como se comporta

**Comment by andiechan** [comment]
![twitter_mock ups_03](https://cloud.githubusercontent.com/assets/19866300/16573555/43f67178-4243-11e6-94bc-648b5e97f261.jpg)

**Comment by arnaldos** [comment]
Ajusta el texto para que no se tape con la foto.

**Comment by andiechan** [comment]
![twitter_mock ups_05](https://cloud.githubusercontent.com/assets/19866300/16592023/bb4e7a4a-42ac-11e6-9f91-bf99fd7f2774.jpg)

![Uploading TWITTER_15.JPG…]()
![Uploading TWITTER_Mock ups_05.jpg…]()

**Comment by arnaldos** [comment]
nice !! make others social media images like this.
