### ISSUE TITLE
Create a Image for Facebook Profile to Chat P2P App

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#915]
Banner size 981x363 px

Profile size 180x180 px

**Comment by andiechan** [comment]
![facebook-banner_01](https://cloud.githubusercontent.com/assets/19866300/16314532/1e1f5964-3948-11e6-997f-64c178b17ebc.png)
![facebook_profile](https://cloud.githubusercontent.com/assets/19866300/16314533/1e56278c-3948-11e6-8a0b-7da74c19a03b.png)

**Comment by arnaldos** [comment]
Version 1 del banner elimina el icono ya que se mostrara en la imagen de perfil, el texto bajalo un poco para que que de al centro, para el perfil en el icono elimina los elementos de fondo

**Comment by andiechan** [comment]
![youtube_profile](https://cloud.githubusercontent.com/assets/19866300/16343484/338c81a0-3a01-11e6-8422-c1aa690a2477.png)
![facebook](https://cloud.githubusercontent.com/assets/19866300/16343485/33ae7d8c-3a01-11e6-8d54-1e8fc2a8b89a.png)

**Comment by arnaldos** [comment]
presentalos en un perfil de face para ver como se comporta, lo mismo para las otras redes

**Comment by andiechan** [comment]
![facebook-01](https://cloud.githubusercontent.com/assets/19866300/16381121/c47b20d2-3c44-11e6-91d0-9b8dd6207560.jpg)

**Comment by arnaldos** [comment]
@andiechan plz entra en este enlace y fijate como se ve  https://www.facebook.com/Fermat-P2P-Taxi-Platform-Project-992451414166615/?fref=ts replantea la imagen para que la del perfil no cubra la acción que realiza la persona

**Comment by andiechan** [comment]
Esta seria la versión para el antiguo Facebook
![facebook_antiguo](https://cloud.githubusercontent.com/assets/19866300/16397899/c823710c-3c90-11e6-9f94-7f882e0c49e8.png)
![mock ups facebook viejo-04](https://cloud.githubusercontent.com/assets/19866300/16397901/c863c752-3c90-11e6-8135-c862953a5ee9.jpg)

**Comment by andiechan** [comment]
y este para el nuevo: 
![facebook_nuevo](https://cloud.githubusercontent.com/assets/19866300/16397961/4107ec2e-3c91-11e6-8291-2c60a53763e9.png)
![facebook mock up-01](https://cloud.githubusercontent.com/assets/19866300/16397962/41091cfc-3c91-11e6-864b-aac53ba4b4d3.jpg)

**Comment by andiechan** [comment]
![facebook_otro banner](https://cloud.githubusercontent.com/assets/19866300/16565929/af43aef6-41de-11e6-8f6d-2d30b41ce204.JPG)

**Comment by andiechan** [comment]
![facebook_06](https://cloud.githubusercontent.com/assets/19866300/16704972/79e9636a-454c-11e6-9014-5023d1278006.JPG)
- FACEBOOK NUEVO:
  ![facebook nuevo_mock up_03](https://cloud.githubusercontent.com/assets/19866300/16704982/93402d9e-454c-11e6-879c-546314e87fa2.jpg)
- FACEBOOK VIEJO:
  ![facebook viejo_mock up_03](https://cloud.githubusercontent.com/assets/19866300/16704983/934a970c-454c-11e6-92f6-cb5f842e96b2.jpg)

**Comment by arnaldos** [comment]
@andiechan subiste esto al repo ?
