### ISSUE TITLE
Create a welcome Banner to Classifieds App

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#916]
1080x500 px

**Comment by saraguerrerot** [comment]
![image](https://cloud.githubusercontent.com/assets/19808868/16808371/419c6a1a-48ea-11e6-9884-2f1fdd93af27.png)

![image](https://cloud.githubusercontent.com/assets/19808868/16808387/5381e34a-48ea-11e6-9dc5-375fcb44b291.png)

![image](https://cloud.githubusercontent.com/assets/19808868/16808403/601a563c-48ea-11e6-9a86-82299f0542d1.png)

@emmysm @arnaldos

**Comment by emmysm** [comment]
Más propuestas, @saraguerrerot , porfa :sweat_smile:

**Comment by saraguerrerot** [comment]
![image](https://cloud.githubusercontent.com/assets/19808868/16811584/0df5d31a-48f7-11e6-99c5-7ddaa2d76a36.png)

@emmysm @arnaldos

**Comment by emmysm** [comment]
Pudiera andar por ahí, puedes hacer 3 propuesta partiendo de esa? @saraguerrerot

**Comment by saraguerrerot** [comment]
oki @emmysm

**Comment by saraguerrerot** [comment]
![image](https://cloud.githubusercontent.com/assets/19808868/16814240/f20c21f2-4902-11e6-938d-6d8bf31cdecc.png)

![image](https://cloud.githubusercontent.com/assets/19808868/16814247/fb1bd3b4-4902-11e6-856c-1e02b8491bac.png)

![image](https://cloud.githubusercontent.com/assets/19808868/16814265/0782f682-4903-11e6-8ae8-dde5a60145db.png)

@emmysm @arnaldos

**Comment by emmysm** [comment]
@saraguerrerot  Me gusta la segunda propuesta. Qué opinas @arnaldos ?

**Comment by arnaldos** [comment]
@saraguerrerot @emmysm del primer seriado me gusta la 1ra versión y del segundo seriado la 2da.

plz enumeren las versiones es mas facil evaluar :smile:

**Comment by emmysm** [comment]
Me quedo con la 2da. Me gustó bastante esa @saraguerrerot
