### ISSUE TITLE
Storyboard - Introduccion al CBP

### ISSUE THREAD

**Issue by victoralfonzohd** [bitDubai/fermat-graphic-design#917]
@jonathanborges3d @Yinellydesign @AnaPietrosanti 

En esta plataforma los actores involucrados son los Crypto Brokers y sus clientes (Crypto Customers) 

Un Crypto Broker es una persona u organización pequeña cuya lógica de negocio es comprar o vender monedas digitales y en papel en su mercado local. Su mercancía es el stock inicial de cada divisa y su ganancia la obtiene vendiéndola a un precio mayor en cada operación.  

El Crypto Customer es el comprador de la mercancía ofrecida por el Crypto Broker, acordando los términos de la transacción hasta finalizar la operación.

El objetivo principal de esta plataforma es agilizar todos los procesos involucrados en la gestión del negocio, facilitando el software adecuado para completar todo el circuito transaccional. Siempre evitando la pérdida de dinero en cada transacción.

**Comment by victoralfonzohd** [comment]
## Storyboard seccion 01

---

![introduccion_cbp_seccion01](https://cloud.githubusercontent.com/assets/15219855/16121572/991348ec-33ad-11e6-9991-b6ee7c1f2727.jpg)

@Yinellydesign @jonathanborges3d @AnaPietrosanti @MaviDavsa

**Comment by Yinellydesign** [comment]
![storyboard el crypto customer el crypto broker](https://cloud.githubusercontent.com/assets/17091674/16133221/81eacdce-33e0-11e6-8556-b9c0b0eb4caa.png)

@jonathanborges3d @AnaPietrosanti @MaviDavsa @victoralfonzohd

**Comment by jonathanborges3d** [comment]
@victoralfonzohd @Yinellydesign Me gustaría ver personajes nuevos para éste video, tal vez en el mismo estilo, pero otros que no se relacionen con ediciones anteriores. También es válido probar otras opciones de estilo. 

Para las escenas podemos trabajar un plano más cercano, medio cuerpo pudiese ser, para que se noten las pantallas de las apps en cada dispositivo de los personajes

En los celulares deben ir las capturas de las aplicaciones que actúan en el proceso de compra y venta de la CBP: Crypto Broker Wallet, Cypto Customer Wallet, Se deberían tomar las capturas desde el emulador, configurando los perfiles de cada actor con una imagen a modo de foto carnet o parecida (que no salga el personaje Jhon Doe por defecto), luego se debe procurar iniciar una negociación tal como hemos visto en las pruebas Beta.

**Comment by victoralfonzohd** [comment]
## Storyboard Seccion 01 / Version 2

@jonathanborges3d  aqui puedes ver los nuevos personajes que hizo @Yinellydesign 

![introduccion_cbp_seccion01-v2](https://cloud.githubusercontent.com/assets/15219855/16196704/da0aaa66-36c8-11e6-8a10-05b79ffa9374.jpg)

**Comment by jonathanborges3d** [comment]
@Yinellydesign @victoralfonzohd Me gusta el estilo de los personajes pero de primera impresión me parecieron niños, tal vez sea por las proporciones de la cabeza con respecto al cuerpo, pero el estilo me gusta. @AnaPietrosanti pudiese darnos su opinión al respecto.

Ambos personajes deberían tener dispositivos en las manos, recuerden que es importante hacer referencia a que se hace desde la comodidad de tu android X.

Propongo colocar varios customers, diferentes personajes, vaiantes del mismo estilo pero que se vea que no sólo uno es el cliente. No sé, Uds. me dicen si conviene o no.

Comparto la idea de que aparezca la Crypto Broker Wallet con una tranzacción en proceso, pero también funcionaría hacer la animación de que navega por la app, abre la bitcoinwallet y luego la CBW, así se da una idea de que utiliza varias apps detro del sistema.

El logo de las monedas digitales debe ser de bitcoin, ethereum y ¿por qué no?: Fermats, y en los billetes podemos poner $ € etc..

**Comment by arnaldos** [comment]
@victoralfonzohd @AnaPietrosanti @jonathanborges3d les recomiendo usar de teléfono un samsung s6 es uno de los standares que se usa para el momento de hacer enfasis de un dispositivo.

**Comment by Yinellydesign** [comment]
![story el crypto customer el crypto broker](https://cloud.githubusercontent.com/assets/17091674/16210456/df28254a-3705-11e6-83cb-93ef183f1a47.png)

**Comment by AnaPietrosanti** [comment]
De acuerdo con Jonathan, la proporción exagerada de la cabeza en relación con el cuerpo se utiliza comúnmente para representar niños. Podemos usar la referencia de los personajes usados en el video anterior. También en cómo diferenciarlos aunque sean hombres los dos, que no cambie solo la vestimenta y el color de pelo. 
En la escena donde aparecen los dos agregaría cerca del dispositivo una flecha hacia arriba y otra hacia abajo que simbolice quién envía y quién recibe. (Si pueden probar a ver cómo funciona) 
También como dice J, dejar ver toda la transacción desde que entra en la wallet estaría más instructivo. 

A evaluar: Con el nuevo logo y sus colores vamos a hacer una paleta un poco menos pastel. He visto que los últimos diseños para la App los colores son más vivos. V qué dice al respecto?

Ana P.

**Comment by victoralfonzohd** [comment]
@arnaldos Gracias por el dato!

@Yinellydesign @AnaPietrosanti @jonathanborges3d 

Propongo este estilo para los nuevos personajes.. 

Este seria el Customer

![personaje-customer](https://cloud.githubusercontent.com/assets/15219855/16213836/470edf94-371c-11e6-964e-57af6c0fc627.jpg)

El broker

![personaje-customer](https://cloud.githubusercontent.com/assets/15219855/16214073/7754e1e2-371e-11e6-871e-684af77d87e7.jpg)

Que les parece?

**Comment by jonathanborges3d** [comment]
@victoralfonzohd mejoraron las proporciones pero el rostro es de un chico aún. Por favor, intenta modificar las proporciones sobre la base del developer y ponerle una barba o bigotes que lo haga ver un poco más adulto y vemos. Todavía me gustaría ver los de @Yinellydesign con las proporciones adecuadas.

**Comment by victoralfonzohd** [comment]
@Yinellydesign @jonathanborges3d @AnaPietrosanti 

Correcciones:

Broker:

![personaje-broker2](https://cloud.githubusercontent.com/assets/15219855/16232302/c7da81d8-3793-11e6-966d-550fe2dc321c.jpg)

Customer:

![personaje-customer2](https://cloud.githubusercontent.com/assets/15219855/16232303/c7dcb692-3793-11e6-82f2-4f96f55865f5.jpg)

**Comment by jonathanborges3d** [comment]
@victoralfonzohd Creo que mejoró mucho la apariencia en cuanto a la edad, se logra inferir que el broker tiene sus 40 y el customer unos 25-30. Por favor genera dos imágenes de los personajes como para los perfiles de la crypto broker wallet y las crypto customer, desde otro ángulo puede ser, o mirando de frente. y veamos como se ven en la app, así sustituimos la imagen por defecto con cada una según sea el caso.

**Comment by victoralfonzohd** [comment]
Que te parecen @jonathanborges3d ?

---

## Vistas de la app:

### Home Broker

![home-broker](https://cloud.githubusercontent.com/assets/15219855/16286282/41e9b630-38a5-11e6-9544-0c940a0c16fe.png)

### Home Customer

![home-customer](https://cloud.githubusercontent.com/assets/15219855/16286281/41c7c8a4-38a5-11e6-8752-47515d8601f4.png)

### Profile Broker

![profile-broker](https://cloud.githubusercontent.com/assets/15219855/16286431/162de0ec-38a6-11e6-8ade-fe8118b677d1.png)

### Profile Customer

![profile-customer](https://cloud.githubusercontent.com/assets/15219855/16286437/1cb38b10-38a6-11e6-986c-8d87169e8881.png)

**Comment by Yinellydesign** [comment]
@jonathanborges3d @AnaPietrosanti @victoralfonzohd 

Broker:

![personaje2](https://cloud.githubusercontent.com/assets/17091674/16378433/badcfbe0-3c35-11e6-9a80-635c9f2564e5.jpg)

Customer:

![personaje1](https://cloud.githubusercontent.com/assets/17091674/16378448/cd704744-3c35-11e6-91ef-db4cb48eb1b5.jpg)

**Comment by jonathanborges3d** [comment]
@Yinellydesign Se ven mucho mejor así, por favor genera unas vistas similares a las que hizo @victoralfonzohd de los personajes en los perfiles de las wallets, Luego decidimos con cual propuesta nos quedamos y procedemos a animarlos.

**Comment by victoralfonzohd** [comment]
@Yinellydesign Tenemos que usar las vistas actuales de las comunities, aun no tengo acceso a ellas D:

**Comment by victoralfonzohd** [comment]
Propuesta para el Personaje Broker Femenino 

![personaje-brokerfemale](https://cloud.githubusercontent.com/assets/15219855/16500192/6de20bd8-3ecd-11e6-8ed6-6fa0ed687e47.jpg)

@jonathanborges3d @Yinellydesign @AnaPietrosanti @MaviDavsa

**Comment by Yinellydesign** [comment]
Propuesta para el Personaje Broker Femenino
![personajes_mujer](https://cloud.githubusercontent.com/assets/17091674/16498783/3512dd60-3ec7-11e6-8ec4-cabe923b6a67.png)

@jonathanborges3d @victoralfonzohd  @AnaPietrosanti @MaviDavsa

**Comment by jonathanborges3d** [comment]
@Yinellydesign Perfecto. Vamos a Ir cerrando con ésto, solo faltan las modificaciones que te comentamos (el color de la camisa del customer y el detalle con el cuello de la broker) y hacer las primeras animaciones

Por otro lado ya debemos ir trabajando en la actualización del storyboard con el texto del script. Te lo pongo por acá:

> Fermat Crypto Broker Platform es una de las funcionalidades del sistema en la que han sido agrupadas diversas aplicaciones internas que forman las herramientas básicas para generar un mercado de compra-venta de monedas digitales.
> 
> En esta plataforma los actores involucrados son los Crypto Brokers y sus clientes, los Crypto Customers . 
> 
> Un Crypto Broker es una persona u organización pequeña cuya lógica de negocio es comprar o vender criptomonedas y monedas de uso común. Su mercancía es el stock inicial de cada divisa y su ganancia la obtiene vendiéndola a un precio mayor en cada operación.  
> 
> El Crypto Customer es el comprador de la mercancía ofrecida por el Crypto Broker, acordando los términos de la transacción a través de la aplicación hasta finalizar la operación.
> 
> El objetivo principal de esta plataforma es agilizar todos los procesos involucrados en la gestión del negocio, facilitando el software adecuado para completar todo el circuito transaccional. Siempre evitando la pérdida de dinero en cada transacción.
