### ISSUE TITLE
Create banners for CCP social media accounts

### ISSUE THREAD

**Issue by m471c4** [bitDubai/fermat-graphic-design#918]
Reference issue #857

We need to adapt the CCP banner made here #860 for the facebook, twitter and youtube accounts. I highly recomend to consider the place where the profile image is going to show, so it doesn't cover any information. Sizes are:

Facebook: 851x315px
Twitter: 1500x500px
Youtube: 2560x1224px (visible in all devices: 1280x350px)

This is the reference banner:

![ccp_banner](https://cloud.githubusercontent.com/assets/13468350/16133914/5c369088-33e8-11e6-8ea1-b3446441ecb2.png)

**Comment by m471c4** [comment]
@lisamarmolina please take this issue. We need this as soon as possible.

**Comment by lisamarmolina** [comment]
Facebook: 851x315px
![ccp_banner_facebook](https://cloud.githubusercontent.com/assets/19942022/16143458/b7271e9c-3436-11e6-932f-278233215353.png)

Twitter: 1500x500px
![ccp_banner_twitter](https://cloud.githubusercontent.com/assets/19942022/16143498/eb622cc4-3436-11e6-8389-ecfed3dc6a98.png)

Youtube: 2560x1224px (visible in all devices: 1280x350px)
![ccp_banner_youtube](https://cloud.githubusercontent.com/assets/19942022/16143521/09579b24-3437-11e6-94ab-879875009122.png)

Example: 
![youtube](https://cloud.githubusercontent.com/assets/19942022/16143536/2fa0bf68-3437-11e6-830a-f44ad78dc3a1.PNG)

**Comment by m471c4** [comment]
@lisamarmolina the youtube one is perfect. We need to adjust the other two. Please center the elements, and distribute them better, considering the place where the profile image is going to show. Also, please make the map in the background bigger :)

**Comment by lisamarmolina** [comment]
I have made the corrections...

Twitter 1500x500px:
![ccp_banner_twitter](https://cloud.githubusercontent.com/assets/19942022/16166935/8e4c59b4-34b9-11e6-9af6-4080a4c7a2c6.png)

Examples:
![1](https://cloud.githubusercontent.com/assets/19942022/16167072/e124d066-34ba-11e6-8b83-51d9770d8a8c.PNG)
![2](https://cloud.githubusercontent.com/assets/19942022/16167073/e12d7efa-34ba-11e6-98c6-8d9fdc79dda7.PNG)

Facebook 851x315px:
![ccp_banner_facebook_c](https://cloud.githubusercontent.com/assets/19942022/16167129/5510a3d8-34bb-11e6-9d6e-22f42618b978.png)

Example:

![3](https://cloud.githubusercontent.com/assets/19942022/16167312/41c54354-34bd-11e6-9323-198f191c71d0.PNG)

**Comment by m471c4** [comment]
@lisamarmolina those are perfect! Good job! Please upload the files! :)
