### ISSUE TITLE
Create a Graphics to Represent the connections between Clients and Customers

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#919]
Reference Issue Info https://github.com/Fermat-ORG/fermat/issues/6316

**Comment by solemiliia** [comment]
Necesito Saber que nombre va a llevar 
Caso 1
![caso1](https://cloud.githubusercontent.com/assets/19818549/16155865/209f92a2-347b-11e6-841d-fc0657cbaef6.jpg)
Caso 2
![caso 2](https://cloud.githubusercontent.com/assets/19818549/16156019/f3a77f84-347b-11e6-8d71-b5e27e079b52.jpg)

**Comment by Rart3001** [comment]
Caso 1
Communication Between Devices Connected to The Same Node

Caso 2
Communication Between Devices Connected to Different Nodes

**Comment by solemiliia** [comment]
![caso 1](https://cloud.githubusercontent.com/assets/19818549/16165243/a3639b76-34ac-11e6-80b6-0b8d0844af8b.jpg)
![caso 2](https://cloud.githubusercontent.com/assets/19818549/16165244/a368e4fa-34ac-11e6-841a-0dc4b3def3df.jpg)

**Comment by solemiliia** [comment]
![caso 1](https://cloud.githubusercontent.com/assets/19818549/16167286/fd36c3de-34bc-11e6-9216-2ff67f3c4994.jpg)
![caso 2](https://cloud.githubusercontent.com/assets/19818549/16167287/fd3fa0da-34bc-11e6-9f5b-4778aae05ea8.jpg)

**Comment by Rart3001** [comment]
@solemiliia muchas gracias muy buen trabajo
