### ISSUE TITLE
Create a Web page Image slide to Chat Platform

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#920]
Sizes 364x225

Create 2 Image

![image](https://cloud.githubusercontent.com/assets/13594347/16141687/278e121c-3428-11e6-809e-29263d885efc.png)

**Comment by Jessicafp** [comment]
![1](https://cloud.githubusercontent.com/assets/19536846/16157403/37a7a6f4-3482-11e6-97b5-6e4940faf521.png)
![2](https://cloud.githubusercontent.com/assets/19536846/16157404/37b20d74-3482-11e6-8dba-81e371a06957.png)
![3](https://cloud.githubusercontent.com/assets/19536846/16157405/37b4019c-3482-11e6-969c-7d205d00e2f3.png)

**Comment by Jessicafp** [comment]
![1](https://cloud.githubusercontent.com/assets/19536846/16160104/12692c4c-3490-11e6-83e0-9a2d82191cb2.png)
![2](https://cloud.githubusercontent.com/assets/19536846/16160105/12715d90-3490-11e6-84e3-f96e731ef0bd.png)
![3](https://cloud.githubusercontent.com/assets/19536846/16160106/12752e84-3490-11e6-8250-b26706408d67.png)
![Uploading 4.png…]()

**Comment by Jessicafp** [comment]
![4](https://cloud.githubusercontent.com/assets/19536846/16160127/361bb7cc-3490-11e6-89e8-d064d43fa34b.png)

**Comment by arnaldos** [comment]
las ultimas versiones no están funcionando los elemento de las infografia no las mezcles con las imágenes. tal ve spueda funcionar una imagen de dos personas chateando

**Comment by arnaldos** [comment]
Trata de que los elementos estén bien distribuidos sus pesos, siento están muy recargados.

**Comment by Jessicafp** [comment]
![sin titulo-3](https://cloud.githubusercontent.com/assets/19536846/16162188/b5d10f16-349b-11e6-915d-f837d1dbc209.png)
![muestra-01](https://cloud.githubusercontent.com/assets/19536846/16162189/b5d88f52-349b-11e6-8fb0-63be0c7c441e.png)

**Comment by arnaldos** [comment]
@Jessicafp genera otras propuestas plz

**Comment by Jessicafp** [comment]
![1](https://cloud.githubusercontent.com/assets/19536846/16341388/90107d4c-39f6-11e6-8c2c-0dbb960d8669.png)
![2](https://cloud.githubusercontent.com/assets/19536846/16341389/9013db54-39f6-11e6-8d48-094dd88fa737.png)

**Comment by arnaldos** [comment]
ok de las ultimas dos la de arriba

**Comment by Jessicafp** [comment]
![1](https://cloud.githubusercontent.com/assets/19536846/16342417/d42e92ca-39fb-11e6-8d30-6f06efa60f52.png)

**Comment by Jessicafp** [comment]
listo

**Comment by arnaldos** [comment]
subelo al repo
