### ISSUE TITLE
 Improve the choice of key export settings Fermat App

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#921]
Reference

![image](https://cloud.githubusercontent.com/assets/13594347/16212858/aac4ea9a-3714-11e6-8a20-4872d3eb43a9.png)

**Comment by solemiliia** [comment]
1 ![1](https://cloud.githubusercontent.com/assets/19818549/16327572/57db249c-399a-11e6-9aa6-d99d6765a0cb.jpg)
2 ![2](https://cloud.githubusercontent.com/assets/19818549/16327575/59b5b50c-399a-11e6-9cba-796a90bddb96.jpg)
3 ![3](https://cloud.githubusercontent.com/assets/19818549/16327576/59be9e24-399a-11e6-86ef-dddce141d5dc.jpg)
4 ![4](https://cloud.githubusercontent.com/assets/19818549/16327577/59c87840-399a-11e6-9ea9-792da09bded4.jpg)

**Comment by arnaldos** [comment]
@solemiliia Me gusta como se ve. Que opinas @furszy ?

**Comment by solemiliia** [comment]
Acomode un poco el icono de la llave, cambie el color del texto a uno mas oscuro y al boton de "Press to see the mnemonic code" lo pase a bold para que no se pierda con el fondo 
1
![1](https://cloud.githubusercontent.com/assets/19818549/16343881/7a5ccaca-3a03-11e6-991e-4ab856adeb92.jpg)
2
![2](https://cloud.githubusercontent.com/assets/19818549/16343882/7a5f3788-3a03-11e6-9339-356359134883.jpg)
3
![3](https://cloud.githubusercontent.com/assets/19818549/16343883/7a665c7a-3a03-11e6-8e8a-957b4f34bba3.jpg)
4
![4](https://cloud.githubusercontent.com/assets/19818549/16343884/7a6a09e2-3a03-11e6-8324-4f1c6d4d9171.jpg)

**Comment by solemiliia** [comment]
1
![1](https://cloud.githubusercontent.com/assets/19818549/16534922/6fe25020-3fb1-11e6-9e70-e32703393905.jpg)
2
![2](https://cloud.githubusercontent.com/assets/19818549/16534946/92ced9aa-3fb1-11e6-8eb7-f05dbf0e7b08.jpg)

**Comment by arnaldos** [comment]
@furszy que opinas de esto ?

**Comment by furszy** [comment]
El mnemonic code más grande, son 12 palabras que tienen que entrar. Y con ese texto va a alargar y va a desaparecer.

**Comment by solemiliia** [comment]
Hola @furszy dices que deben ser 12 caracteres, o literal 12 palabras?  y a que te refieres con que va a alargar y luego desaparecer? que acción se supone que se genera? dices que son como esos códigos de seguridad que salen varios en modo de recuperación o algo así, cuando te refieres a las 12 palabras?
