### ISSUE TITLE
Create new Fermat icons for Fermat Core

### ISSUE THREAD

**Issue by acostarodrigo** [bitDubai/fermat-graphic-design#922]
Please, replace bitcoin core icons with our own fermat icons from https://github.com/Fermat-ORG/fermat-blockchain/tree/0.9/src/qt/res

The fermat core app is the fermat client that generates the fermat blockchain. It is a clone from bitcoin so we need to use our own icons.

The repository is private, so let me know who will access it so I can give him/her access.

**Comment by acostarodrigo** [comment]
Can you please give me the correct version of fermat.ico?
You need to give me a Fermat icon

@m471c4 @lisamarmolina @arnaldos

**Comment by acostarodrigo** [comment]
This is the new Fermat App. But it is showing a Bitcoin icon.

![image](https://cloud.githubusercontent.com/assets/9518556/16426052/d9180d8a-3d3d-11e6-833e-8792eeea07be.png)

**Comment by furszy** [comment]
@arnaldos give him the Fermat launcher icon in .ico format.

**Comment by arnaldos** [comment]
@furszy I send icon to rodrigo

**Comment by acostarodrigo** [comment]
please, upload icon to issue

**Comment by arnaldos** [comment]
![fermat_logo_v2_square_256x256](https://cloud.githubusercontent.com/assets/13594347/16503993/771acdcc-3edf-11e6-9ea2-26f8732b932b.png)
