### ISSUE TITLE
Create combo app mockups to Bitcoin Wallet

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#925]
The combined application contains unified profile , comunity and app . into one. you need to create a function that no intregre the 3 apps

**Comment by m471c4** [comment]
@arnaldos I've added a floating button which morphs into a bottom sheet where you have access to all 3 CCP wallets. What do you think?

![community_combo1](https://cloud.githubusercontent.com/assets/13468350/16506359/dda5b70e-3eef-11e6-8f15-fa69b5d29f32.png)

**Comment by arnaldos** [comment]
@m471c4 it´s fine but I would use the bottom sheet when the user has to return the comunity to one of these apps without using the floating botton.
