### ISSUE TITLE
Create a Welcome Banner for P2P Jobs app

### ISSUE THREAD

**Issue by proseuz** [bitDubai/fermat-graphic-design#929]
this is a document of this app https://docs.google.com/document/d/1TJEX9QcWA5ZaWM6vYzDT4T9MVtpyVPqlG-U4kHMNENU/edit

Size 1024x500

**Comment by rosanacoronado** [comment]
Here are the proposals @arnaldos @jhonmarquez92 

Proposal_1
![welcome banner-02](https://cloud.githubusercontent.com/assets/19508456/16501881/86bf4118-3ed5-11e6-9ac9-5bb4c22e7087.jpg)

Porposal_2
![welcome banner-03](https://cloud.githubusercontent.com/assets/19508456/16501882/86c79a52-3ed5-11e6-9a58-25f694a8b412.jpg)

Proposal_3
![welcome banner-05](https://cloud.githubusercontent.com/assets/19508456/16501883/86e83a82-3ed5-11e6-9548-720cb39e5112.jpg)

Proposal_4
![welcome banner-06](https://cloud.githubusercontent.com/assets/19508456/16501884/86ffebdc-3ed5-11e6-8037-5111caec5eba.jpg)

Proposal_5
![welcome banner_2-02](https://cloud.githubusercontent.com/assets/19508456/16501885/8717d396-3ed5-11e6-95fb-1c25ec55f3f7.jpg)

Proposal_6
![welcome banner_2-03](https://cloud.githubusercontent.com/assets/19508456/16501886/87264c1e-3ed5-11e6-9472-ba36ad5ff616.jpg)

Proposal_7
![welcome banner-01](https://cloud.githubusercontent.com/assets/19508456/16501887/873c8844-3ed5-11e6-96ac-a9b68ea69cf6.jpg)

**Comment by arnaldos** [comment]
@rosanacoronado  para estos banners es mas con vectores es para dar la bienvenida a la app una ves entres en ella te dejo una muestra de otra app. pudiese andar por la 3 y la 7

![wallet_store](https://cloud.githubusercontent.com/assets/13594347/16503032/ea8ebb74-3eda-11e6-98cf-eb950bf65d18.png)

**Comment by rosanacoronado** [comment]
@jhonmarquez92 @arnaldos adjunto nuevas propuestas siguiendo las sugerencias, jugando un poco con la linea gráfica utilizada en la app. Espero haber captado la idea :grinning: 

Propuesta_8
![welcome banner 2_4-02](https://cloud.githubusercontent.com/assets/19508456/16535441/3ac4daee-3fb5-11e6-910f-c1a40d004ceb.jpg)

Propuesta_9
![welcome banner 2-06](https://cloud.githubusercontent.com/assets/19508456/16535444/3af98870-3fb5-11e6-905c-17e3afe3733f.jpg)

Propuesta_10
![welcome banner 2_2-04](https://cloud.githubusercontent.com/assets/19508456/16535445/3b0b0b5e-3fb5-11e6-8d6d-c8120d6f8262.jpg)

Propuesta_11
![welcome banner 2_5-03](https://cloud.githubusercontent.com/assets/19508456/16535442/3ace344a-3fb5-11e6-8c82-6d57748693ee.jpg)

Propuesta_12
![welcome banner 2-01](https://cloud.githubusercontent.com/assets/19508456/16535443/3ae2f70e-3fb5-11e6-9a34-503a4117f539.jpg)

**Comment by proseuz** [comment]
Intenta con la propuesta 12, ponle las figuras del fondo de la propuesta 11, pon el logo un poco más pequeño y porfa crea una propuesta distinta a ver qué tal. @rosanacoronado @arnaldos

**Comment by rosanacoronado** [comment]
@arnaldos @jhonmarquez92 nuevas propuestas incluyendoel texto de P2P APP, no se si deba o no deba incluirse 

Propuesta_13
![welcome banner 3-01](https://cloud.githubusercontent.com/assets/19508456/16563848/528d4a34-41d2-11e6-8145-26e35acad3a7.jpg)

Propuesta_14.1
![welcome banner 3_5-06](https://cloud.githubusercontent.com/assets/19508456/16563855/5bf6f3c2-41d2-11e6-96a2-51266b79bfe1.jpg)

Propuesta_14.2
![welcome banner 3_3-06](https://cloud.githubusercontent.com/assets/19508456/16563856/5bff4ee6-41d2-11e6-9ee8-b07b696db732.jpg)

Propuesta_15
![welcome banner-04](https://cloud.githubusercontent.com/assets/19508456/16563867/6ef06512-41d2-11e6-9abc-20a957dba526.jpg)

**Comment by proseuz** [comment]
@rosanacoronado  probemos  con el logo en negativo sobre un fondo azul como el de los elementos de la 14.2. No sé si en negativo funcione que opinas @arnaldos ? ( chequea los vectores del logo, no sé si es idea mía pero creo que la "o"  está deforme)

**Comment by arnaldos** [comment]
si la O esta rara, revisa eso. Pero de acuerdo la versión 14.2. aunque me parece así esta bien. pero realiza lo que pide @jhonmarquez92 y luego comparamos

**Comment by rosanacoronado** [comment]
nuevos cambios sugeridos @arnaldos @jhonmarquez92, en base a la propuesta 14.2, una de ellas deje el logo totalmente en negativo, y la otra solo deje en negativo la "J" de Jobs.

Propuesta_16.1
![welcome banner 4_2-06](https://cloud.githubusercontent.com/assets/19508456/16571937/21a43446-4231-11e6-8543-2532c863f679.jpg)

Propuesta_16.2
![welcome banner 4_3-06](https://cloud.githubusercontent.com/assets/19508456/16571938/21c00d60-4231-11e6-875d-ba7ac687f4d6.jpg)

**Comment by rosanacoronado** [comment]
corrijo, esta si es la versión en negativo, otra propuesta @arnaldos @jhonmarquez92. Este no es el logo final, luego sera reemplazado.

Propuesta_17.1
![welcome banner 5_1-06](https://cloud.githubusercontent.com/assets/19508456/16572139/29446b24-4233-11e6-8fab-ec6e7123dfb4.jpg)

Propuesta_17.2
![welcome banner 5-06](https://cloud.githubusercontent.com/assets/19508456/16572160/71e8d496-4233-11e6-9a29-8948a93515b0.jpg)

**Comment by proseuz** [comment]
La 16,2 y la 17,1 me gustan @arnaldos

**Comment by arnaldos** [comment]
@jhonmarquez92 coincido contigo la 16.2. rosana sube el banner al repo plz
