### ISSUE TITLE
Crear un logo para representar plugins

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#93]
Viene del #88

Crear logo para representar plugins (seran ubicados en la esquina superior izquierda de la ficha) este logo servirá para indicar los componentes que tiene el cada modulo.

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina  @m471c4  este icono puede funcionar para representar los plugins 

![fermat_plugins](https://cloud.githubusercontent.com/assets/13594347/9891796/edac8ed0-5bd2-11e5-8682-df44bdc7460d.png)

**Comment by Luis-Fernando-Molina** [comment]
@arnaldos :+1:

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina :+1:

**Comment by m471c4** [comment]
@Luis-Fernando-Molina @arnaldos acá el ícono estandarizado, cerré el círculo blanco y utilicé la cartera con el grosor de borde de los últimos logos.

![iconplugin](https://cloud.githubusercontent.com/assets/13468350/9908734/c8eb7f0c-5c5e-11e5-852e-8df2f7c7f26c.png)

**Comment by Luis-Fernando-Molina** [comment]
:+1: este puede quedar asi
