### ISSUE TITLE
Change Crypto Customer Wallet mockups from Ps to Ai

### ISSUE THREAD

**Issue by m471c4** [bitDubai/fermat-graphic-design#931]
We need this mockups to be updated in Adobe Illustrator so the video team can use them as soon as possible.

**Comment by m471c4** [comment]
@lisamarmolina please take this issue. Comment here when you've finished and the files are in the repo.

**Comment by lisamarmolina** [comment]
I've finished, ready to upload to the repo.

**Comment by arnaldos** [comment]
nice !! thanks @lisamarmolina
