### ISSUE TITLE
Change Crypto Broker Wallet mockups from Ps to Ai

### ISSUE THREAD

**Issue by m471c4** [bitDubai/fermat-graphic-design#932]
We need this mockups to be updated in Adobe Illustrator so the video team can use them as soon as possible.

**Comment by m471c4** [comment]
@arnaldos todavía no puedo ver a Martín, su user es @teniasrosales pero no aparece así que supongo que sigue sin tener los permisos necesarios. Ya le asigné el caso para que vaya trabajando en él, pero necesitamos solventar esta situación lo más pronto posible.

**Comment by arnaldos** [comment]
que raro ya pido ayuda con esto

**Comment by arnaldos** [comment]
esto como quedo @m471c4 ?

**Comment by m471c4** [comment]
@arnaldos de esto se encargó @lisamarmolina y ya está listo, los archivos están en el repositorio.
