### ISSUE TITLE
Create a Web page Image slide to Jobs P2P App

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#934]
2 images for slide 

Image Sizes 436x180

![image](https://cloud.githubusercontent.com/assets/13594347/16504533/4e857d1e-3ee2-11e6-9061-8409142e6bac.png)

Job Platform

It is the platform that allows a job seeker find a job and the employers finds talents for future employment.

**Comment by rosanacoronado** [comment]
@arnaldos @jhonmarquez92 These are the proposals for the webpage image slide, let me know your opinion and suggestions :relaxed:  I will continue working on more proposals

Proposal_1
![image slide jobs-01](https://cloud.githubusercontent.com/assets/19508456/16661027/fb3d703c-443e-11e6-97f8-2f9bcf6191e5.jpg)

Proposal_2
![image slide jobs4-01](https://cloud.githubusercontent.com/assets/19508456/16661028/fb3f47a4-443e-11e6-99e1-b848595efb5c.jpg)

Proposal_3.1
![image slide jobs8-01](https://cloud.githubusercontent.com/assets/19508456/16661052/11f6fca8-443f-11e6-97fd-1887f4fccc52.jpg)

Proposal_3.2
![image slide jobs_5-01](https://cloud.githubusercontent.com/assets/19508456/16661053/1205dab6-443f-11e6-8a7d-9df0eaad578d.jpg)

**Comment by arnaldos** [comment]
@rosanacoronado the image sizes is 436x180 check this plz proposal 3.1 with propposal 1 look

**Comment by rosanacoronado** [comment]
@arnaldos @jhonmarquez92 I reviewed the measures of the previous images and are the right size :flushed: But seeing the reference image appears the size required in the case is not correct, which leads me doubts :worried: here I leave the new proposals with suggested changes and then we can verify it is the correct size and change proposals if necessary :relaxed:

Proposal_4
![image slide jobs 1-01](https://cloud.githubusercontent.com/assets/19508456/16815111/a10014a4-4906-11e6-8964-6991deb06dee.png)

Proposal_5
![image slide jobs 2-01](https://cloud.githubusercontent.com/assets/19508456/16815137/b65e23ea-4906-11e6-9c0d-b2b618389abe.png)

**Comment by proseuz** [comment]
@rosanacoronado I think the proposal 4 looks good. But the telephone center should not be cut by the diagonal lines @arnaldos

**Comment by rosanacoronado** [comment]
new proposal with suggested changes. What do you think @arnaldos @jhonmarquez92?

Proposal_4.1
![image slide jobs 5-01](https://cloud.githubusercontent.com/assets/19508456/16820768/c10a584e-4920-11e6-94f6-3a37f73d3216.png)

**Comment by arnaldos** [comment]
@rosanacoronado nice, but the real size is 436x270px. I apologize for this :disappointed:

**Comment by rosanacoronado** [comment]
Don't worry hehe. Here are new proposals adjusting the size as well as playing with other images, keeping the graphic style of the previous proposals. @arnaldos @jhonmarquez92 

Proposal 4.2
![slides resizes6-01](https://cloud.githubusercontent.com/assets/19508456/16857547/6c31598e-49ee-11e6-8447-f90bf727b12f.png)

Proposal_4.3
![slides resizes 3-01](https://cloud.githubusercontent.com/assets/19508456/16857763/ee3a6a00-49ef-11e6-96b5-957e996d1e7d.png)

Proposal_4.4
![slides resizes 4-01](https://cloud.githubusercontent.com/assets/19508456/16857263/c485380a-49ec-11e6-8424-575c8f037b73.png)

Proposal_4.5
![slides resizes 2-01](https://cloud.githubusercontent.com/assets/19508456/16857590/c52dff92-49ee-11e6-8d81-fbe2437e363c.png)

**Comment by proseuz** [comment]
qué opinas @arnaldos creo que la última

**Comment by rosanacoronado** [comment]
@jhonmarquez92 @arnaldos  acá otra propuesta de la versión 4.5 con el fondo en blanco, de manera que realce mucho mas el celular, que opinan? 

Propuesta_4.6
![slides resizes7-01](https://cloud.githubusercontent.com/assets/19508456/17338817/fec9273c-58b6-11e6-861c-fbc2880cbf23.png)
