### ISSUE TITLE
Workflow edit. Design app form and buttons

### ISSUE THREAD

**Issue by emmysm** [bitDubai/fermat-graphic-design#936]
Rediseñar formulario y botones para la workflow edit

Desarrollador responsable: @ricardo460 
Diseñador: @saraguerrerot 
Diseñador responsable @emmysm

**Comment by saraguerrerot** [comment]
![image](https://cloud.githubusercontent.com/assets/19808868/16528120/c8d93d2a-3f88-11e6-897b-274807092669.png)

me parece que los dos de abajo, que están mas a la derecha podrian ser, activo e inactivo 

@emmysm @ricardo460

**Comment by saraguerrerot** [comment]
![image](https://cloud.githubusercontent.com/assets/19808868/16528277/f0dacc84-3f89-11e6-90c7-b5491757bde6.png)

![image](https://cloud.githubusercontent.com/assets/19808868/16528290/07c4c580-3f8a-11e6-8e82-ca939ce6bb7d.png)

![image](https://cloud.githubusercontent.com/assets/19808868/16528298/1a16f38e-3f8a-11e6-9746-1a7be067c9ee.png)

los campos que estan mas ocuros o con un resplandor exterior es cuando el cambi esta activa, para mostrar la diferencia 

@emmysm @ricardo460

**Comment by emmysm** [comment]
Más propuesta de botones. Pudiera ser fondo blanco con stroke azul @saraguerrerot

**Comment by saraguerrerot** [comment]
![image](https://cloud.githubusercontent.com/assets/19808868/16529874/382d7092-3f93-11e6-832f-c3ad0a080c19.png)

@emmysm

**Comment by ricardo460** [comment]
@emmysm @saraguerrerot 
![image](https://cloud.githubusercontent.com/assets/13169767/16542809/b4ac0de2-4086-11e6-896f-b66a8fceff3a.png)
Me gusta este boton.

y el primer formulario.

**Comment by arnaldos** [comment]
esto debe ir en que parte ??

**Comment by emmysm** [comment]
@saraguerrerot más propuesta de botones, porfa, pero que sean planos.

**Comment by emmysm** [comment]
La parte de edición de la página de desarrolladores @arnaldos

**Comment by arnaldos** [comment]
ok en que parte presentalo para ver como se comporta con el resto de los elementos

**Comment by saraguerrerot** [comment]
![captura de pantalla 49 1](https://cloud.githubusercontent.com/assets/19808868/16600582/c3aeb794-42d5-11e6-8422-ea5c9703fd08.jpg)

@emmysm @arnaldos @ricardo460

**Comment by emmysm** [comment]
Otras propuestas de botones, @saraguerrerot porfa. El stroke de los campos de texto puede ir un poco más grueso

**Comment by saraguerrerot** [comment]
![captura de pantalla 49 1](https://cloud.githubusercontent.com/assets/19808868/16628335/585e0c92-437f-11e6-9f0b-4cfa089dea5f.jpg)

asi? o es muy grueso? @emmysm

**Comment by emmysm** [comment]
Así está bien. Recuerda los botones @saraguerrerot

**Comment by saraguerrerot** [comment]
![image](https://cloud.githubusercontent.com/assets/19808868/16629406/89d70e46-4383-11e6-9a20-98249835aa7c.png)
 botones @emmysm @arnaldos @ricardo460

**Comment by emmysm** [comment]
Me gusta la segunda propuesta de izquierda a derecha. Centra los elementos y colocalos en el mockup  @saraguerrerot

**Comment by saraguerrerot** [comment]
![captura de pantalla 49 1](https://cloud.githubusercontent.com/assets/19808868/16631873/65ad9efc-438f-11e6-9be9-281f06068e3e.jpg)

@emmysm
