### ISSUE TITLE
Create ADD (Fermat Addons) logo

### ISSUE THREAD

**Issue by Miguelcldn** [bitDubai/fermat-graphic-design#937]
An add-on is a Fermat component that adds to the framework new functionalities, we need to group them on a platform. So we need a logo for it. Currently, we put to add-ons this stamp to mark them as "add-on":
![image](https://cloud.githubusercontent.com/assets/5544266/16527112/e0172ba6-3f82-11e6-8b2b-837605e95cd0.png)

So this can be a starting point of the logo, but can be anything that resembles the idea of an add-on.

@emmysm put the corresponding labels

Responsible developer @Miguelcldn 
Designer: @saraguerrerot 
Responsible designer: @emmysm

**Comment by saraguerrerot** [comment]
![image](https://cloud.githubusercontent.com/assets/19808868/16532991/acaaee6c-3fa3-11e6-8ca0-e0c27ba7b7c5.png)

![image](https://cloud.githubusercontent.com/assets/19808868/16533169/d1c94814-3fa4-11e6-9e29-7e09e7db8a8c.png)

![image](https://cloud.githubusercontent.com/assets/19808868/16533182/dee01b72-3fa4-11e6-8b02-f3327491c2b1.png)

@emmysm

**Comment by Miguelcldn** [comment]
Pueden mostrarse de alguna manera 3 piezas ya juntas y una nueva agregándose? (o más facil dos juntas y una nueva agregándose)

**Comment by emmysm** [comment]
Me gusta la última versión. Precisamente te iba a preguntar si era necesario que todas las piezas estuvieran armadas o algunas de ellas. @saraguerrerot añade las indicaciones de @Miguelcldn a la última propuesta, porfa :)

**Comment by saraguerrerot** [comment]
![image](https://cloud.githubusercontent.com/assets/19808868/16534114/5fce5496-3fab-11e6-9005-cf079b9ad178.png)

@emmysm @Miguelcldn

**Comment by emmysm** [comment]
Coloca más fino el stroke. Fijate que los círculos estén centrados, veo el lado derecho más fino que el izquierdo @saraguerrerot

**Comment by saraguerrerot** [comment]
![image](https://cloud.githubusercontent.com/assets/19808868/16534572/c0885f9a-3fae-11e6-881d-786b1767a2b4.png)

@emmysm @Miguelcldn

**Comment by Miguelcldn** [comment]
Bien, esa última me gusta, quisiera verlo como quedaría el final, con los textos

**Comment by saraguerrerot** [comment]
![image](https://cloud.githubusercontent.com/assets/19808868/16535695/70293c00-3fb7-11e6-830a-0d2c273d4ff0.png)

@emmysm @Miguelcldn

**Comment by Miguelcldn** [comment]
Que abajo diga sólo "Add ons" (puesto que conceptualmente no es un platform propiamente dicho)

**Comment by saraguerrerot** [comment]
![image](https://cloud.githubusercontent.com/assets/19808868/16535741/db2d0be4-3fb7-11e6-9810-bd00afc83c7c.png)

@Miguelcldn 

es adds on? o add ons? o.o

**Comment by emmysm** [comment]
@saraguerrerot  Las piezas que están armadas colocalas pegaditas. Y así quedaría bien. @Miguelcldn se trabajaría con estos nuevos colores o con los anteriores?

**Comment by Miguelcldn** [comment]
@saraguerrerot ponlo "Add-ons" en plural, ya que su función es encapsular varios add-ons. @emmysm si aún no están listos todos los platforms, entonces necesitaré que me den una versión con los colores viejos, para que este no esté distinto

**Comment by saraguerrerot** [comment]
![image](https://cloud.githubusercontent.com/assets/19808868/16536017/b83bacb4-3fba-11e6-95ab-cf0d2842378d.png)

@Miguelcldn @emmysm

**Comment by Miguelcldn** [comment]
Esta quedando bien, quisiera ver cómo se ve llenando las separaciones entre las piezas unidas de blanco

**Comment by Miguelcldn** [comment]
Mejor llenar el espacio de blanco, moviéndolas desordena el centro de las piezas. Y quisiera es verlo con el texto :sweat_smile: sorry por no ser claro.
![image](https://cloud.githubusercontent.com/assets/5544266/16536405/0a10a310-3fbf-11e6-9d4d-08d48cc9c138.png)

**Comment by emmysm** [comment]
Jajajaajajaj, está muy bien, @Miguelcldn  xD

**Comment by saraguerrerot** [comment]
no me bare slack @emmysm 

![image](https://cloud.githubusercontent.com/assets/19808868/16568836/ff44af54-41fc-11e6-8468-d074766f4a3d.png)

**Comment by arnaldos** [comment]
@saraguerrerot revisa la linea horizontal que se forma en el centro de las piezas están desfasadas. alinealas plz

**Comment by saraguerrerot** [comment]
que tal @arnaldos @emmysm 

![image](https://cloud.githubusercontent.com/assets/19808868/16569876/f95e4868-4209-11e6-8260-bd62193115b0.png)

**Comment by saraguerrerot** [comment]
![image](https://cloud.githubusercontent.com/assets/19808868/16594135/e2ae9994-42b6-11e6-9199-77b34c60fd15.png)

@emmysm @arnaldos
