### ISSUE TITLE
Banking Wallet - Refresh Mockups to actual funtions

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#938]
Entrega hoy 05-07-2016

**Comment by solemiliia** [comment]
1
![1](https://cloud.githubusercontent.com/assets/19818549/16602958/51688a8c-42e6-11e6-9096-a819e3480e38.jpg)
1-2
![1-2](https://cloud.githubusercontent.com/assets/19818549/16603038/d69dee5e-42e6-11e6-9814-d83947f8fdef.jpg)
1-3
![1-3](https://cloud.githubusercontent.com/assets/19818549/16603051/f6d88314-42e6-11e6-8dd8-df28e3f27dde.jpg)
2
![2](https://cloud.githubusercontent.com/assets/19818549/16603066/12bfd14a-42e7-11e6-81a7-cfa80257f846.jpg)
3
![3](https://cloud.githubusercontent.com/assets/19818549/16603080/43acbf5c-42e7-11e6-8935-4cb4a30e0b6e.jpg)
4
![4](https://cloud.githubusercontent.com/assets/19818549/16603116/a81f61b0-42e7-11e6-8282-8436d31af4c5.jpg)
5
![5](https://cloud.githubusercontent.com/assets/19818549/16603131/c76e4e82-42e7-11e6-9cbd-2a3cc2658d7b.jpg)
6
![6](https://cloud.githubusercontent.com/assets/19818549/16603150/ef5df2b2-42e7-11e6-8bbb-f11f9b10863c.jpg)
7
![7](https://cloud.githubusercontent.com/assets/19818549/16603179/21263174-42e8-11e6-8842-99f2c53b782a.jpg)
8
![8](https://cloud.githubusercontent.com/assets/19818549/16603203/44edbf78-42e8-11e6-95e6-22f5b03c6722.jpg)

**Comment by solemiliia** [comment]
le agregue la flecha de regresar como sale en el repo, y agregue el icnono de la alcancia de cochinito como esta en la app en vez del signo exclamacion que tenia en el repo
![bank wallet refresh mockup-4](https://cloud.githubusercontent.com/assets/19818549/16624337/4358a308-436f-11e6-9390-40d1a6847e75.jpg)

**Comment by arnaldos** [comment]
perfect !
