### ISSUE TITLE
Crear un logo para representar add-ons

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#94]
Viene del #88

Crear logo para representar add-ons (seran ubicados en la esquina superior izquierda de la ficha) este logo servirá para indicar los componentes que tiene el cada modulo.

**Comment by m471c4** [comment]
@Luis-Fernando-Molina @arnaldos acá el primero boceto para el ícono de add-on:

![iconaddon](https://cloud.githubusercontent.com/assets/13468350/9908692/98e01c14-5c5e-11e5-970c-349a6209c7e8.png)

**Comment by Luis-Fernando-Molina** [comment]
:+1: perfecto, listo. El de android va a quedar descolorido en relacion a los otros, quizas lo puedas poner en verde al muñequito.
