### ISSUE TITLE
New look to Images Playstore to Fermat App

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#944]
## Actual image 

![fermat-wallet-home](https://cloud.githubusercontent.com/assets/13594347/16787689/1d31d936-486c-11e6-83eb-5cd783cb49b9.png)
## Suggestion look image, but with fermat colors to background 

![screenshot_2016-07-10-22-16-40](https://cloud.githubusercontent.com/assets/13594347/16787591/534a6052-486b-11e6-9f4b-30c73747d35c.png)

Image size 720 px x 1280 px 

Image Link Folders fermat-graphic-design/2D Design/Playstore/Views

Deliver date 15-07-2016

**Comment by rennyx7** [comment]
![untitled-1](https://cloud.githubusercontent.com/assets/20045567/16858211/4ba542b6-49f3-11e6-959a-a3047ce50118.png)
![untitled-2](https://cloud.githubusercontent.com/assets/20045567/16858212/4bc6b45a-49f3-11e6-9795-6195afe84ab0.png)
![untitled-3](https://cloud.githubusercontent.com/assets/20045567/16858213/4bc98d42-49f3-11e6-8de2-4d2fccdd187a.png)

**Comment by rennyx7** [comment]
@arnaldos 
![fermat_playstore6](https://cloud.githubusercontent.com/assets/20045567/16859854/6f5a55ea-4a00-11e6-8e07-d12f0fbc786e.jpg)
![fermat_playstore7](https://cloud.githubusercontent.com/assets/20045567/16859852/6f585cb8-4a00-11e6-960f-5bacbd2655fc.jpg)
![fermat_playstore8](https://cloud.githubusercontent.com/assets/20045567/16859853/6f59c562-4a00-11e6-81ad-bf48497aa76c.jpg)
![fermat_playstore9](https://cloud.githubusercontent.com/assets/20045567/16859855/6f5bc43e-4a00-11e6-9617-3b453db086d5.jpg)
![fermat_playstore10](https://cloud.githubusercontent.com/assets/20045567/16859857/6f5ea744-4a00-11e6-9e4a-a97be1f07b77.jpg)
![fermat_playstore11](https://cloud.githubusercontent.com/assets/20045567/16859856/6f5dfbfa-4a00-11e6-9122-5e02b6de69f9.jpg)
![fermat_plastore2](https://cloud.githubusercontent.com/assets/20045567/16859858/6f6d95e2-4a00-11e6-94ab-31df7bc94a76.jpg)
![fermat_playstore3](https://cloud.githubusercontent.com/assets/20045567/16859860/6f724d58-4a00-11e6-8214-f79b69bfa558.jpg)
![fermat_playstore1](https://cloud.githubusercontent.com/assets/20045567/16859859/6f6f3a82-4a00-11e6-8d8e-1e84889b11e7.jpg)
![fermat_playstore4](https://cloud.githubusercontent.com/assets/20045567/16859861/6f72a9ce-4a00-11e6-86d5-30142617f4d9.jpg)
![fermat_playstore5](https://cloud.githubusercontent.com/assets/20045567/16859862/6f7b5aba-4a00-11e6-8f32-ff240b3d5ab9.jpg)

**Comment by arnaldos** [comment]
muy bien solo unas correcciones que te deje por slack

**Comment by arnaldos** [comment]
revisa que este en RGB los colores se ven muy oscuros
