### ISSUE TITLE
Broshure to Meetups to social media 

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#945]
Image size 1024x1024px

Info: 
- Location
- Date
- Address Location
- Time

Deliver date 14-07-2016

**Comment by solemiliia** [comment]
no lo habia revisado antes, aun asi te pasare este como un boceto a ver si debo hacer algun cambio grande aparte del tamaño 
![fermat meetup](https://cloud.githubusercontent.com/assets/19818549/16822186/c38982f4-4928-11e6-814f-97e2360e128e.jpg)

**Comment by arnaldos** [comment]
ya fue solucionado este caso genere las fechas para el resto delos meetups

**Comment by arnaldos** [comment]
te comparto como quedaron maneje 3 versiones diferentes 

![meet-up_caracas-04](https://cloud.githubusercontent.com/assets/13594347/16848682/f0a6fdec-49c4-11e6-897b-277616f8cbc8.jpg)
