### ISSUE TITLE
Create a Image to Artist Platform for web site

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#946]
Image 436x270px

Image reference

![image](https://cloud.githubusercontent.com/assets/13594347/16792803/0b2b1fd0-489a-11e6-98aa-4de4b90b4b56.png)

**Comment by Jessicafp** [comment]
![artist platform 2](https://cloud.githubusercontent.com/assets/19536846/16858267/c0f59732-49f3-11e6-87c5-dceaf9c8f949.png)
![artist platform 3](https://cloud.githubusercontent.com/assets/19536846/16858268/c0fca9c8-49f3-11e6-9069-2483d718e8c9.png)
![artist platform](https://cloud.githubusercontent.com/assets/19536846/16858269/c11544ba-49f3-11e6-9b3f-249f91ab2401.png)

**Comment by arnaldos** [comment]
@Jessicafp  mis comentarios:
- plz revisa la paleta de colores de esto. 
- Usa fotos con color
- La versión del concierto descartala no funciona.
- Enumera las versiones
- El texto encapsulado a dentro del triangulo de la primera versión no es la mejor ubicación.
- Realiza una versión mas limpia.

Artist Platform permite al usuario compra de canciones a cambio de tokens (fermats), también puede administrar las canciones adquiridas. reproducir, eliminar,.

**Comment by m471c4** [comment]
@Jessicafp por favor, ten cuidado con el uso de las imágenes. En la primera y la tercera versión usaste una fotografía de una persona sosteniendo un Iphone, pero Fermat está desarrollada únicamente para Android por ahora.

**Comment by Jessicafp** [comment]
![1 platform artist-01](https://cloud.githubusercontent.com/assets/19536846/16886794/429d8488-4aa4-11e6-81ba-68a901a72e18.png)
![2 artist platform](https://cloud.githubusercontent.com/assets/19536846/16886795/42a55348-4aa4-11e6-98c8-ba907ed8d1d0.png)
![3 artist platform 3](https://cloud.githubusercontent.com/assets/19536846/16886796/42ad6d4e-4aa4-11e6-9369-9b6d97aa26bd.png)

**Comment by arnaldos** [comment]
@Jessicafp versión 3 pero aplica las lineas diagonales, que uso gustavo en este caso #905

**Comment by Jessicafp** [comment]
![artist platform 3](https://cloud.githubusercontent.com/assets/19536846/16891430/58b22530-4ac7-11e6-9db8-6972f753e4bb.png)

**Comment by Jessicafp** [comment]
![fan wallet 2](https://cloud.githubusercontent.com/assets/19536846/16970540/d1acd874-4dea-11e6-90dc-2bc5c36d525d.png)
![fan wallet 3](https://cloud.githubusercontent.com/assets/19536846/16970542/d1b3eb00-4dea-11e6-8ac0-0bffbc808075.png)
![fan wallet](https://cloud.githubusercontent.com/assets/19536846/16970543/d1c5b6f0-4dea-11e6-83db-55c51012e14c.png)

**Comment by arnaldos** [comment]
@Jessicafp ese telefono no es un Iphone s6 ? recuerda que la app actualmente tiene soporte para android

**Comment by Jessicafp** [comment]
![fan wallet 2](https://cloud.githubusercontent.com/assets/19536846/17030680/9a1962ce-4f3e-11e6-80f8-d6aea37fdd8e.png)
![fan wallet 3](https://cloud.githubusercontent.com/assets/19536846/17030681/9a1f6598-4f3e-11e6-8320-cc72daf36b90.png)
![fan wallet](https://cloud.githubusercontent.com/assets/19536846/17030682/9a2502be-4f3e-11e6-9ba2-54ecf801df85.png)

**Comment by arnaldos** [comment]
@Jessicafp Cambios:
- El texto se dificulta la lectura 
- A nivel visual no tiene el mismo impacto que el otro replantea lo plz

**Comment by Jessicafp** [comment]
![fan wallet 2](https://cloud.githubusercontent.com/assets/19536846/17116547/3d95a15c-5286-11e6-8c33-4d56e8534409.png)

**Comment by Jessicafp** [comment]
![sin titulo-2](https://cloud.githubusercontent.com/assets/19536846/17118728/fefa72d8-528f-11e6-8676-18c6732048c4.png)

**Comment by arnaldos** [comment]
@Jessicafp sustituye el texto por el logo para ambas apps manteniendo el estilo que planteo gustavo

**Comment by Jessicafp** [comment]
![1](https://cloud.githubusercontent.com/assets/19536846/17262713/158a6846-55ab-11e6-9094-e836bb1ee334.png)
![2](https://cloud.githubusercontent.com/assets/19536846/17262715/159aba8e-55ab-11e6-9831-587c72f5dbe8.png)
![3](https://cloud.githubusercontent.com/assets/19536846/17262714/1598f690-55ab-11e6-99a7-339b6c793318.png)

**Comment by Jessicafp** [comment]
![222](https://cloud.githubusercontent.com/assets/19536846/17349633/9dcedee0-58ed-11e6-9cc2-78a82da5e22a.png)

**Comment by Jessicafp** [comment]
@jhonmarquez92

**Comment by proseuz** [comment]
@arnaldos  qué te parece la última versión?

**Comment by Jessicafp** [comment]
![ms](https://cloud.githubusercontent.com/assets/19536846/17425569/b36ad8fc-5a9c-11e6-8d17-31b3ebdf94ba.png)
![222](https://cloud.githubusercontent.com/assets/19536846/17425572/b4295976-5a9c-11e6-9965-85950d90473b.png)
![22](https://cloud.githubusercontent.com/assets/19536846/17425570/b375b2ae-5a9c-11e6-996e-81718518bde2.png)
![mms](https://cloud.githubusercontent.com/assets/19536846/17425571/b37eb296-5a9c-11e6-90b5-1fbae12c8394.png)

**Comment by Jessicafp** [comment]
@jhonmarquez92 Aca estas los 4 modelos :D

**Comment by proseuz** [comment]
Yo creo que la 3 tiene coherencia con lo que se ha venido trabajando, además el teléfono con los audífonos te ponen en contexto. qué opinas @arnaldos ?

**Comment by arnaldos** [comment]
@jhonmarquez92 @Jessicafp la 3 y la 4 son las mismas por lo que veo en esta oportunidad creo que la 4 con el color de fondo hace resaltar el telf por eso usaría esa. un aspecto a corregir seria el corte en la parte inferior del teléfono esta generando ruido. por lo tanto incluye el teléfono dentro de la imagen si es necesario reduzcan el tamaño un poco.

**Comment by proseuz** [comment]
@arnaldos de acuerdo contigo, además el color violeta va más con la fan wallet. Decía la 4 porque se parece más al banner que se hizo para la music y la fan.

**Comment by Jessicafp** [comment]
![fan wallet final](https://cloud.githubusercontent.com/assets/19536846/17439867/f06d6fe8-5af7-11e6-8657-84d84d1e01cf.png)

**Comment by Jessicafp** [comment]
@arnaldos @jhonmarquez92

**Comment by proseuz** [comment]
Puedes tratar de que el espacio que está entre el telfono y el borde superior sea el mismo del borde inferior. alinea el icono con el tlf y mantén los margenes al mismo tamaño @Jessicafp

**Comment by Jessicafp** [comment]
![artist platform 2](https://cloud.githubusercontent.com/assets/19536846/17483521/6306aed0-5d54-11e6-85fc-fa133a478211.png)

**Comment by Jessicafp** [comment]
@arnaldos @jhonmarquez92 Aqui esta con los arreglos que me acotaste jhon

**Comment by arnaldos** [comment]
ok ready con este :+1:
