### ISSUE TITLE
Create a Image to Dating P2P App for web site

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#947]
Image sizes 436x270px

Image reference

![image](https://cloud.githubusercontent.com/assets/13594347/16792952/3794acfc-489b-11e6-9394-b5f84d486fdb.png)

**Comment by rennyx7** [comment]
prueba 1
![prueba1](https://cloud.githubusercontent.com/assets/20045567/16989419/2f0cfdce-4e62-11e6-97ba-2736c74e4ca9.jpg)

**Comment by arnaldos** [comment]
@rennyx7 plz revisa el teléfono se ve estirado

**Comment by rennyx7** [comment]
est[a tal cual como los otros del playstore

**Comment by rennyx7** [comment]
![prueba1 2](https://cloud.githubusercontent.com/assets/20045567/17108081/0796e41a-5260-11e6-93b7-a0718783a049.jpg)

**Comment by arnaldos** [comment]
perfecto !! :+1:

**Comment by rennyx7** [comment]
la subo?

**Comment by arnaldos** [comment]
si si

**Comment by isahq23** [comment]
@arnaldos creo que este caso podemos cerrarlo
