### ISSUE TITLE
Create a Image to Jobs P2P App for web site

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#948]
Image sizes 436x270px

Image reference

![image](https://cloud.githubusercontent.com/assets/13594347/16792983/7ddb0c88-489b-11e6-8c5c-25aa9c511a41.png)

**Comment by rosanacoronado** [comment]
@arnaldos @jhonmarquez92 

Proposal_1
![image web jobs1-01](https://cloud.githubusercontent.com/assets/19508456/16892779/4da86b1a-4b1f-11e6-9df2-ab5b41d55354.jpg)

Proposal_2.1
![image web jobs3-04](https://cloud.githubusercontent.com/assets/19508456/16892780/4db4612c-4b1f-11e6-944c-76f92279fd52.jpg)

Proposal_2.2
![image web jobs6-04](https://cloud.githubusercontent.com/assets/19508456/16892786/5d3e1d72-4b1f-11e6-818b-2faefc3e8e93.jpg)

Proposal_3
![image web jobs4-05](https://cloud.githubusercontent.com/assets/19508456/16892781/4db9e99e-4b1f-11e6-8b85-c50a3f831a8e.jpg)

Proposal_4
![image web jobs5-06](https://cloud.githubusercontent.com/assets/19508456/16892782/4dbec14e-4b1f-11e6-9a29-d3fdb10645c3.jpg)

Proposal_5.1
![image web jobs9-02](https://cloud.githubusercontent.com/assets/19508456/16892789/7290e9c0-4b1f-11e6-97e9-7d096c8c2aaa.jpg)

Proposal_5.2
![image web jobs8-02](https://cloud.githubusercontent.com/assets/19508456/16892790/7294bdfc-4b1f-11e6-8316-8e9c72804422.jpg)

**Comment by arnaldos** [comment]
proposal 1
