### ISSUE TITLE
Create a Image to Crypto Broker Platform for web site

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#949]
it´s need tow image
Image size 436x270px

Image reference

![image](https://cloud.githubusercontent.com/assets/13594347/16793026/caf13506-489b-11e6-94f3-4462bf4e3fca.png)

**Comment by lisamarmolina** [comment]
Proposal 1

Crypto Broker Platform
![cbp](https://cloud.githubusercontent.com/assets/19942022/16888288/13d7003a-4aad-11e6-8fe9-0f0279646093.png)

Crypto Broker
![cb](https://cloud.githubusercontent.com/assets/19942022/16888293/1e749d90-4aad-11e6-9b8b-a47566ca783b.png)

Crypto Customer
![cc](https://cloud.githubusercontent.com/assets/19942022/16888295/26377d40-4aad-11e6-8a8a-d4b17d98a80e.png)

**Comment by m471c4** [comment]
@lisamarmolina buen trabajo, vas bien. Me gusta la propuesta de las personas, especialmente la de la Broker, creo que se puede explorar esa idea porque finalmente esa es la esencia de esta plataforma. Con respecto a la diagramación: pon los nombres más grandes en ambos casos (un tamaño similar al que tiene la primera versión). Los iconos no deberían tocar el plano de color que tienes para el nombre.

Algo que también puedes usar para el que tiene ambos iconos es un primer plano de unas manos estrechándose, como cerrando un contrato. Si encuentras una foto así sería bueno verlo.

¿Qué opas tú @arnaldos? por otro lado, ¿se debe trabajar en torno a una imagen para ambas wallets o por separado? Si se debe hacer una por cada wallet, ¿debería incluír la cash y la banking?

**Comment by lisamarmolina** [comment]
Propuesta 1 (correcciones)

Crypto Broker Platform
![cbp2](https://cloud.githubusercontent.com/assets/19942022/16892215/e62f7e8c-4ad9-11e6-83a2-62b9f0366947.png)

Crypto Broker
![cb2](https://cloud.githubusercontent.com/assets/19942022/16892256/2e10135a-4adb-11e6-9bd5-e66c02ed79f0.png)

Crypto Customer
![cc2](https://cloud.githubusercontent.com/assets/19942022/16892257/3422a9e2-4adb-11e6-8ac3-a1c2443f43d2.png)

Propuesta 2 (más simple)

Crypto Broker Platform
![cbp2](https://cloud.githubusercontent.com/assets/19942022/16892308/c0eccdac-4adc-11e6-9dff-35f12e87d24b.png)

Crypto Broker
![cb2](https://cloud.githubusercontent.com/assets/19942022/16892310/c8319a7a-4adc-11e6-9fd2-152bfeff76a7.png)

Crypto Customer
![cc2](https://cloud.githubusercontent.com/assets/19942022/16892313/cf799a76-4adc-11e6-840b-7537035c0049.png)

**Comment by arnaldos** [comment]
@m471c4 @lisamarmolina el seriado de la propuesta 1

**Comment by arnaldos** [comment]
@lisamarmolina @m471c4  tambien nos falta para la cash y banking wallet y en la imagen general deberiamos incluir tambien esas dos a la imagen

**Comment by lisamarmolina** [comment]
Crypto Broker Platform
![cryptobrokerplatform](https://cloud.githubusercontent.com/assets/19942022/17011177/dbaed496-4ed8-11e6-8b6d-d7ae18642d69.png)

Cash Wallet
![cashwallet](https://cloud.githubusercontent.com/assets/19942022/17011181/e3a9de98-4ed8-11e6-8cc4-af13fe4f9dc3.png)

Banking Wallet
![bankingwallet](https://cloud.githubusercontent.com/assets/19942022/17011182/e6563b50-4ed8-11e6-8165-caf2203c7910.png)

**Comment by lisamarmolina** [comment]
![cryptobrokerplatform2](https://cloud.githubusercontent.com/assets/19942022/17011309/9e5c85b4-4eda-11e6-8f67-4eb27e3fa441.png)
Creo que más pequeño queda mejor, ¿alguna propuesta? @arnaldos @m471c4

**Comment by m471c4** [comment]
@lisamarmolina vas bien, me gustan las propuestas para Cash y Banking; solo cambiaría la capa que tiene logos de bitcoin repetidos como una textura en el fondo. Recuerda que estas wallets solo manejan dinero real, cámbialos por logos de monedas fiat (como $, €, £, etc) o elimínalos. 

La que tiene los logos de todas las wallets no termina de convencerme. Trata poniendo los logos un poco más pequeños, que todos tengan el mismo tamaño y queden alineados. ¿Qué opinas tú @arnaldos?

**Comment by lisamarmolina** [comment]
Crypto Broker Plarform, ¿qué opinan? @m471c4 @arnaldos 
![cryptobrokerplatform3](https://cloud.githubusercontent.com/assets/19942022/17031869/5c920aa4-4f44-11e6-8799-d19e5f1a9b4a.png)

Cash Wallet
![cashwallet](https://cloud.githubusercontent.com/assets/19942022/17031899/7ab97314-4f44-11e6-9e0b-48f419083e06.png)

Banking Wallet
![bankingwallet](https://cloud.githubusercontent.com/assets/19942022/17031906/82fb2e8c-4f44-11e6-974c-406901e36feb.png)

**Comment by arnaldos** [comment]
@lisamarmolina  revisa el icono de la cash, los efectos están raros, parecen no estar al tamaño adecuado. cun la customer parece estar pasando algo similar respecto a la costura.

**Comment by arnaldos** [comment]
del resto lo veo bien que opinas @m471c4 ?

**Comment by m471c4** [comment]
@arnaldos tienes razón, @lisamarmolina lo que pasa es que tienes que activar la opción "escalar trazos y efectos" (en las preferencias generales del Illustrator) antes de reducir el tamaño de los iconos, por eso se ven así (las costuras de la Customer y la Cash se ven muy grandes y las sombras muy oscuras). Arregla eso y quedarían listas.

**Comment by lisamarmolina** [comment]
Con las correcciones finales, ¿qué opinan? @arnaldos @m471c4 

![cryptobrokerplatform](https://cloud.githubusercontent.com/assets/19942022/17110208/da374a3c-5269-11e6-88db-e025f999635d.png)

![cryptobroker](https://cloud.githubusercontent.com/assets/19942022/17110211/dfc3b8dc-5269-11e6-93a4-b7f82fbe727b.png)

![cryptocustomer](https://cloud.githubusercontent.com/assets/19942022/17110216/e53d4814-5269-11e6-91fa-7fef22e43901.png)

![bankingwallet](https://cloud.githubusercontent.com/assets/19942022/17110222/ebbf0236-5269-11e6-856a-5717f02bcbab.png)

![cashwallet](https://cloud.githubusercontent.com/assets/19942022/17110228/eeb775e0-5269-11e6-8ee2-622baf7b12f9.png)
