### ISSUE TITLE
Crear un logo para representar los componentes de android

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#95]
Viene del #88

Crear logo para representar los componentes de android (seran ubicados en la esquina superior izquierda de la ficha) este logo servirá para indicar los componentes que tiene el cada modulo.

**Comment by m471c4** [comment]
@Luis-Fernando-Molina @arnaldos acá la propuesta para android.

![iconandroid](https://cloud.githubusercontent.com/assets/13468350/9908714/af38948c-5c5e-11e5-81aa-4dad856635ed.png)
:

**Comment by Luis-Fernando-Molina** [comment]
El de android va a quedar descolorido en relacion a los otros, quizas lo puedas poner en verde al muñequito. (con bordes blancos como la wallet y una costura como la waleltt)

**Comment by m471c4** [comment]
@Luis-Fernando-Molina muy bien, lo haré y lo subo en un momento.

**Comment by m471c4** [comment]
@Luis-Fernando-Molina acá con el robot en color verde y la costura:

![iconandroid2](https://cloud.githubusercontent.com/assets/13468350/9913516/03fdf49a-5c77-11e5-8193-c9df5687dac0.png)

**Comment by Luis-Fernando-Molina** [comment]
:+1:
