### ISSUE TITLE
Create a Image for Youtube Profile to Crypto Broker Platform

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#950]
Banner size 2560x423 px

Profile size 250x250 px

**Comment by arismendi227** [comment]
@jhonmarquez92 @arnaldos 
propuestas 

1
![cb1](https://cloud.githubusercontent.com/assets/19276382/16932615/75cc4c9a-4d15-11e6-9c32-58380cb9d43e.jpg)
2
![cb2](https://cloud.githubusercontent.com/assets/19276382/16932618/7bb2b5cc-4d15-11e6-8173-c45622600755.jpg)
3
![cb3](https://cloud.githubusercontent.com/assets/19276382/16933055/983481b4-4d18-11e6-8650-1987afdc16ea.jpg)

**Comment by proseuz** [comment]
Creo que puede ir por la propuesta 1 pero con el logo más grande en el banner. qué opinas       @arnaldos ?

**Comment by arnaldos** [comment]
fíjate como se esta trabajando en el caso #949

**Comment by arismendi227** [comment]
@jhonmarquez92 @arnaldos 
correcciones según las sugerencias 
![cb4](https://cloud.githubusercontent.com/assets/19276382/16956909/32f1040e-4da8-11e6-9d54-7d12e85ea5d2.png)

**Comment by proseuz** [comment]
Looks great! The logo could be more bigger? @arnaldos

**Comment by arnaldos** [comment]
@arismendi227 @jhonmarquez92 
Change the logo of the crypto broker app that was left by the broker plattform crypto is in the 3D folder. Also includes some customer on the big picture for the banner profile also , the two identities should appear.

**Comment by arnaldos** [comment]
Les dejo el comentario en español:
- Colocar las logos de las identidades de las apps (cash, banking, broker, customer)
- Remplazar el logo donde va la imagen cuadrada, colocar la de CBP que esta en la carpeta de 3D.

**Comment by arismendi227** [comment]
@jhonmarquez92 @arnaldos 
Correcciones
1
![cb5](https://cloud.githubusercontent.com/assets/19276382/16995195/0efc230e-4e79-11e6-9c69-f3bcecf3c4f3.jpg)

2
![cb6](https://cloud.githubusercontent.com/assets/19276382/16995199/139bb186-4e79-11e6-8abd-51f296693e1a.jpg)

3
![cb7](https://cloud.githubusercontent.com/assets/19276382/16995205/1734a5b4-4e79-11e6-8ea3-b5a345de7ff9.jpg)

**Comment by proseuz** [comment]
deberían estar más  separados los logos @arnaldos

**Comment by arismendi227** [comment]
@jhonmarquez92 @arnaldos
Ajustando los logos
1
![cb8](https://cloud.githubusercontent.com/assets/19276382/16996409/32b8ce40-4e7f-11e6-9304-2543bc2eee27.jpg)

2
![cb9](https://cloud.githubusercontent.com/assets/19276382/16996415/3784c820-4e7f-11e6-96cf-a59fecfc4c9e.jpg)

3
![cb10](https://cloud.githubusercontent.com/assets/19276382/16996421/3c7c42b8-4e7f-11e6-9b28-e03fab41c87b.jpg)

**Comment by proseuz** [comment]
@arnaldos que opinas?

**Comment by arnaldos** [comment]
@arismendi227 @jhonmarquez92 la moneda de CBP en la version frontal

**Comment by arismendi227** [comment]
@jhonmarquez92 @arnaldos
corrección: moneda frontal para el perfil 
1
![cb1](https://cloud.githubusercontent.com/assets/19276382/17198393/da9604f2-5442-11e6-8383-b5db18033006.jpg)

2
![cb2](https://cloud.githubusercontent.com/assets/19276382/17198395/deef34ec-5442-11e6-85ef-d7817898b0b1.jpg)

3
![cb3](https://cloud.githubusercontent.com/assets/19276382/17198399/e602c5d2-5442-11e6-9d4a-888d4eef2061.jpg)

**Comment by arnaldos** [comment]
@arismendi227 Incluye el texto de CBP platform o crypto currency platform, definitivo la moneda en perspectiva

**Comment by arismendi227** [comment]
@jhonmarquez92 @arnaldos
con el texto CBP
1
![cb4](https://cloud.githubusercontent.com/assets/19276382/17302129/bfeef84e-57e8-11e6-9e52-4b1ee94270b0.jpg)

2
![cb5](https://cloud.githubusercontent.com/assets/19276382/17302133/c9546aa4-57e8-11e6-929e-1d31265724ae.jpg)

3
![cb6](https://cloud.githubusercontent.com/assets/19276382/17302135/cd741bd4-57e8-11e6-9d66-650662f9f023.jpg)

**Comment by arnaldos** [comment]
@arismendi227  versión 3 sube al repo los archivos
