### ISSUE TITLE
Create a Image for Twitter Profile to Crypto Broker Platform

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#951]
Banner size 1500x500 px

Profile size 500x500 px

**Comment by karentvillegas** [comment]
@arnaldos @jhonmarquez92 
La siguiente propuesta es la seleccionada para perfil de twitter de CBP previamente aprobada en el issue #952 

![cbp_twitter](https://cloud.githubusercontent.com/assets/19273211/17348469/4faed110-58e4-11e6-9539-4ee9a180318f.png)

**Comment by proseuz** [comment]
se ve muy bien @arnaldos

**Comment by arnaldos** [comment]
perfecto !!!

**Comment by arnaldos** [comment]
@karentvillegas plz prepara los archivos en una carpeta para el repo y asi actualizamos en las redes
