### ISSUE TITLE
Create a Image for Facebook Profile to Crypto Broker Platform

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#952]
Banner size 981x363 px

Profile size 180x180 px

**Comment by karentvillegas** [comment]
@arnaldos @jhonmarquez92 
Propuestas:
1
![1](https://cloud.githubusercontent.com/assets/19273211/17004428/e8d4db92-4ea2-11e6-89da-c4af375ca5c8.png)
2
![2](https://cloud.githubusercontent.com/assets/19273211/17004386/afa13c44-4ea2-11e6-806b-b464566ea30e.png)
3
![3](https://cloud.githubusercontent.com/assets/19273211/17004392/b72cf1f6-4ea2-11e6-8463-71a5d509958a.png)
4
![4](https://cloud.githubusercontent.com/assets/19273211/17004394/bba0b420-4ea2-11e6-8fad-7333e0c5d0e6.png)
5
![5](https://cloud.githubusercontent.com/assets/19273211/17004401/c2119554-4ea2-11e6-8fb8-b03ebb0a5a92.png)

**Comment by proseuz** [comment]
la 2, qué te parece @arnaldos

**Comment by arnaldos** [comment]
@jhonmarquez92 @karentvillegas La 2da esta buena pero usaría las monedas que ha realizado jonathan. las versiones frontales.
incluso aqui 
![image](https://cloud.githubusercontent.com/assets/13594347/17105200/40c572ee-5254-11e6-91c4-e42918324513.png)

**Comment by karentvillegas** [comment]
@arnaldos @jhonmarquez92 Usando la moneda de la CBP en versión frontal
![2_1](https://cloud.githubusercontent.com/assets/19273211/17160049/0c27fa4e-5370-11e6-834c-486a63ac333b.png)

**Comment by arnaldos** [comment]
@karentvillegas @arismendi227 definitivo la moneda en perspectiva, prueben la primera versión 1 y 2 del primer seriado de propuestas colocando crypto broker platform eliminando la palabra fermat y las iniciales CBP

**Comment by karentvillegas** [comment]
@arnaldos @jhonmarquez92 
A partir de las versiones 1 y 2 se generaron las siguientes propuestas:

7
![1_1](https://cloud.githubusercontent.com/assets/19273211/17266817/fb9143b8-55ca-11e6-899f-2448e625ee32.png)
8
![1_2](https://cloud.githubusercontent.com/assets/19273211/17266820/088ab5a4-55cb-11e6-912e-4844896802ec.png)
9
![2_2](https://cloud.githubusercontent.com/assets/19273211/17266827/1635669a-55cb-11e6-96ab-d5358a61d9f8.png)
10
![2_3](https://cloud.githubusercontent.com/assets/19273211/17266828/200ebd06-55cb-11e6-8cc5-812401b0e9b8.png)

**Comment by arnaldos** [comment]
@karentvillegas versión 10 :+1:
