### ISSUE TITLE
Create a Infography to P2P Taxi Transactions

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#953]
You must show the user step by step

1 - sends a request taxi driver.
2- connection with the profiles of drivers displaying a list of CONDUTORES ordered by the most economical
3- the user chooses the most economical
4- one you see the user is in the right place . proceeds to the cancellation the driver meaning through the app using crypto currency

**Comment by ivonnesantos** [comment]
![infographie_taxi-01](https://cloud.githubusercontent.com/assets/15238660/16892033/c464bbb0-4ad3-11e6-8b64-c2ff4c7c77d4.png)
@arnaldos

**Comment by arismendi227** [comment]
@ivonnesantos @arnaldos 
propuesta
![infografia_taxi](https://cloud.githubusercontent.com/assets/19276382/17452315/34f04b38-5b3c-11e6-8ce4-3d7aa3a51c41.png)

**Comment by ivonnesantos** [comment]
@arismendi227 vamos a crear una mezcla entre el taxi y el mapa  y lo colocas donde esta el mapa y le quitamos el icono de wifi, los telefonos subelos un poco y creo que se vera todo mas ciclico la linea exterior ponla de otro color por ahi en la otras infografias creo que hay una manera de representar las plataformas busca entre esos archivos a ver.

**Comment by arismendi227** [comment]
@ivonnesantos @arnaldos 
correciones
![info_taxi](https://cloud.githubusercontent.com/assets/19276382/17524234/c1ea5604-5e2b-11e6-8e9c-0e2fbeec1ba3.png)

**Comment by ivonnesantos** [comment]
@arnaldos que te parece esto

**Comment by isahq23** [comment]
@ivonnesantos yo no entiendo bien el flujo en estas infografías, de hecho pienso que en el medio debería ir el logo de la app que es el "mediador" entre usuario/cliente y usuario/chofer

**Comment by arismendi227** [comment]
@ivonnesantos @arnaldos @isahq23 
correcciones 
![infografia_taxi1](https://cloud.githubusercontent.com/assets/19276382/17827009/70cf0654-6644-11e6-8d68-96bae2fceb95.png)

**Comment by ivonnesantos** [comment]
Este me gusta mas se parece a lo que arnaldo me pidio en un principio
