### ISSUE TITLE
Create Flayers to meet-up

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#954]
Date Delivery Today 14-07-2016

Size 10x13 cm

Reference Image, this image are to social media.
## ![meet-up_maracay-03](https://cloud.githubusercontent.com/assets/13594347/16846373/2f64648a-49ba-11e6-9c2e-d36d4aaf50ec.jpg)

![meet-up_maracaibo-01](https://cloud.githubusercontent.com/assets/13594347/16846416/5b2c8cd2-49ba-11e6-926a-f7a7711e6e22.jpg)

**Comment by isahq23** [comment]
![meetup_flyer](https://cloud.githubusercontent.com/assets/15214774/16850756/97541ad6-49ce-11e6-900c-a52a3c0519bf.jpg)

**Comment by proseuz** [comment]
Propuesta de @arismendi227 @karentvillegas  y mía XD
Manteniendo el concepto gráfico de referencia
![flayer_meet_up_merida-01-01-01](https://cloud.githubusercontent.com/assets/17308060/16851667/8ba6c69e-49d2-11e6-9e4e-36259291a15a.jpg)
@arnaldos

**Comment by Magdy27** [comment]
![flayer-fermat3](https://cloud.githubusercontent.com/assets/19651834/16852994/78f5a6cc-49d8-11e6-919e-4976a461c1b6.png)
![flayer-fermat4](https://cloud.githubusercontent.com/assets/19651834/16852992/786e2382-49d8-11e6-8809-221fdf45148f.png)

@arnaldos

**Comment by arnaldos** [comment]
@jhonmarquez92 @Magdy27 una acotación el texto esta errado, ya que estos flayers tienen que ser netamente informativo algo general de fermat. Mas no debe ser alucivo al meetup sino algo mas informativo.
- Que es fermat? cual es el su objetivo ? (algo breve un extracto que se pueda sacar de la web)
- Un QR code que diseccione a la pagina web.

**Comment by proseuz** [comment]
La última versión del Flayer con los ajustes acordados. 
![flayer_meet_up_merida-01](https://cloud.githubusercontent.com/assets/17308060/16927077/b8df9a6c-4cf9-11e6-8262-9482fc7cf881.jpg) @arnaldos

**Comment by arnaldos** [comment]
POr ahora hay que eliminar toda info aluciva los brokers

**Comment by arnaldos** [comment]
y solo se dejara ala pagina web

**Comment by Magdy27** [comment]
![flayer-fermat](https://cloud.githubusercontent.com/assets/19651834/16967094/76a2df60-4dd5-11e6-94ee-70ed3f958b87.png)
![flayer-fermat-2](https://cloud.githubusercontent.com/assets/19651834/16967102/887f63b6-4dd5-11e6-99da-6742ed47f55a.png)

@arnaldos Estos son los ajustes solicitados.

**Comment by arnaldos** [comment]
@Magdy27  los ajustes conversados por tlf :smile_cat:
