### ISSUE TITLE
Create 6 Image Gallery to silde show to web

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#958]
Picture galery (JPEG, PNG, TIFF, size exactly 1520x600 or 760x300)

Reflect the image and personality of your company: work environment, atmosphere, team, etc

Deliver Date 19-07-16

**Comment by rennyx7** [comment]
Here we go 
![atmosphere](https://cloud.githubusercontent.com/assets/20045567/16917685/a6d3efa4-4cd0-11e6-9fd2-a813786e15f8.jpg)
![international](https://cloud.githubusercontent.com/assets/20045567/16917683/a6d30710-4cd0-11e6-8d63-1a608dc777e7.jpg)
![passion](https://cloud.githubusercontent.com/assets/20045567/16917686/a6d436e4-4cd0-11e6-8a69-c55948d0642c.jpg)
![passion2](https://cloud.githubusercontent.com/assets/20045567/16917688/a6d81dfe-4cd0-11e6-9c49-540db672bc7b.jpg)
![team_work](https://cloud.githubusercontent.com/assets/20045567/16917684/a6d3a15c-4cd0-11e6-9a29-a0f14cbc7a35.jpg)
![work_environment](https://cloud.githubusercontent.com/assets/20045567/16917687/a6d47df2-4cd0-11e6-8afa-9915a2018e80.jpg)
![workmates](https://cloud.githubusercontent.com/assets/20045567/16917689/a6e2f292-4cd0-11e6-8551-8d24d485ce69.jpg)

**Comment by arnaldos** [comment]
@rennyx7 Include some elements or colors to help make emphasis on Fermat

**Comment by rosanacoronado** [comment]
here I leave some images if necessary complement those previously published by Renny :smiley: I keep looking more images :grinning: 

1
![1-01](https://cloud.githubusercontent.com/assets/19508456/16921827/7a116396-4d13-11e6-9f23-1d2d69e37e31.jpg)

2
![3-01](https://cloud.githubusercontent.com/assets/19508456/16921826/7a0eac82-4d13-11e6-8bbb-ce91eef22f0a.jpg)

3
![5-01](https://cloud.githubusercontent.com/assets/19508456/16921828/7a175f62-4d13-11e6-8d83-31543efac676.jpg)

4
![6-01](https://cloud.githubusercontent.com/assets/19508456/16921829/7a1d8b08-4d13-11e6-8fff-1cb94547d329.jpg)

5
![7-01](https://cloud.githubusercontent.com/assets/19508456/16921832/7a2cdfa4-4d13-11e6-9d29-acd1386777bf.jpg)

6
![8-01](https://cloud.githubusercontent.com/assets/19508456/16921831/7a2a4438-4d13-11e6-8412-c96d4d384fc0.jpg)

**Comment by arnaldos** [comment]
@rosanacoronado see if you can put the logo on the glass shown in picture 6.

**Comment by rennyx7** [comment]
![team_work](https://cloud.githubusercontent.com/assets/20045567/16925817/f8608c7e-4cf3-11e6-813b-9db2c3d7ea37.jpg)
![atmosphere](https://cloud.githubusercontent.com/assets/20045567/16925816/f85ef864-4cf3-11e6-94d4-1ed30238f8fe.jpg)
![passion](https://cloud.githubusercontent.com/assets/20045567/16925818/f8685850-4cf3-11e6-9ad5-be1dae5b2bf5.jpg)
![passion2](https://cloud.githubusercontent.com/assets/20045567/16925819/f86e6c68-4cf3-11e6-89ce-1b92db91a94b.jpg)

**Comment by rosanacoronado** [comment]
@arnaldos acá esta la nueva imagen añadiéndole el logo de fermat, una tiene el logotipo repetido en forma de patrón,  la segunda opción solo muestro el isotipo de la organización, y en la tercera una versión en positivo del logo.

6.1
![6-3](https://cloud.githubusercontent.com/assets/19508456/16930105/1d42e112-4d3b-11e6-87d5-2fb300b0fe8a.jpg)

6.2
![6-4](https://cloud.githubusercontent.com/assets/19508456/16930107/1d47fd64-4d3b-11e6-8c3b-77cded2fbbac.jpg)

6.3
![6-5-01](https://cloud.githubusercontent.com/assets/19508456/16931272/6437774a-4d40-11e6-9383-d5ec3920863c.jpg)

**Comment by rosanacoronado** [comment]
@arnaldos tambien adjunto propuestas con una linea grafica :smile: 
7.1
![8-2-01](https://cloud.githubusercontent.com/assets/19508456/16933317/a1bcae08-4d4c-11e6-8d5c-328f406e6594.jpg)

7.2
![8-3-01](https://cloud.githubusercontent.com/assets/19508456/16933318/a1c26a8c-4d4c-11e6-8f5d-a87a639c4ffd.jpg)

**Comment by arnaldos** [comment]
Este es un extracto de donde van a ir las imágenes, @rosanacoronado la 6.1 como te estoy como te muestro, el vidrio mas claro. y la foto en general mas claro también.
monten las imágenes en esta sección para ver como se muestran @rosanacoronado 
@rennyx7 
![image](https://cloud.githubusercontent.com/assets/13594347/16935065/0e0065a0-4d2a-11e6-9624-5015c45f197e.png)

**Comment by rosanacoronado** [comment]
@arnaldos Acá están los mockups con 2 propuestas gráficas y con la sugerencia del logo en cada una de las imágenes, espero cualquier acotación :smiley: 

Propuesta_1
![0e0065a0-4d2a-11e6-9624-5015c45f197e1-1-01](https://cloud.githubusercontent.com/assets/19508456/16938256/1da64e42-4d76-11e6-924a-00f476876e8c.jpg)
![0e0065a0-4d2a-11e6-9624-5015c45f197e1-2-01](https://cloud.githubusercontent.com/assets/19508456/16938257/1dc15110-4d76-11e6-8697-c03277d0a31c.jpg)
![0e0065a0-4d2a-11e6-9624-5015c45f197e1-3-01](https://cloud.githubusercontent.com/assets/19508456/16938258/1dc7a1c8-4d76-11e6-9d87-f5ef8304f6f0.jpg)
![0e0065a0-4d2a-11e6-9624-5015c45f197e1-4-01](https://cloud.githubusercontent.com/assets/19508456/16938259/1dcba386-4d76-11e6-824f-0bcc925fde4c.jpg)
![0e0065a0-4d2a-11e6-9624-5015c45f197e1-5-01](https://cloud.githubusercontent.com/assets/19508456/16938260/1dd11c9e-4d76-11e6-9270-e739f3c1bc55.jpg)
![0e0065a0-4d2a-11e6-9624-5015c45f197e1-6-01](https://cloud.githubusercontent.com/assets/19508456/16938432/3d9edc80-4d78-11e6-9305-b49c746929c1.jpg)

Propuesta_2
![0e0065a0-4d2a-11e6-9624-5015c45f197e2-1-01](https://cloud.githubusercontent.com/assets/19508456/16938262/1ddeb52a-4d76-11e6-837c-3b43f97c45f4.jpg)
![0e0065a0-4d2a-11e6-9624-5015c45f197e2-2-01](https://cloud.githubusercontent.com/assets/19508456/16938263/1de37f38-4d76-11e6-912c-c4aba8ee11c1.jpg)
![0e0065a0-4d2a-11e6-9624-5015c45f197e2-3-01](https://cloud.githubusercontent.com/assets/19508456/16938264/1de98d4c-4d76-11e6-8a49-56dabfc0fa04.jpg)
![0e0065a0-4d2a-11e6-9624-5015c45f197e2-4-01](https://cloud.githubusercontent.com/assets/19508456/16938265/1def158c-4d76-11e6-9f28-d0374410a939.jpg)
![0e0065a0-4d2a-11e6-9624-5015c45f197e2-5-01](https://cloud.githubusercontent.com/assets/19508456/16938266/1df50bcc-4d76-11e6-80be-e403c7cde603.jpg)
![0e0065a0-4d2a-11e6-9624-5015c45f197e2-6-01](https://cloud.githubusercontent.com/assets/19508456/16938411/e63bbdfa-4d77-11e6-9a3f-e1b20b2a30a3.jpg)

**Comment by arnaldos** [comment]
@rosanacoronado el seriado de la propuesta 2 subelas al repo plz

**Comment by rennyx7** [comment]
Aprove?

![imagegallery_fermat_webpage6-01](https://cloud.githubusercontent.com/assets/20045567/16958965/d712044a-4db0-11e6-95ff-554a9acfae8c.jpg)
![imagegallery_fermat_webpage-01](https://cloud.githubusercontent.com/assets/20045567/16958966/d72ce06c-4db0-11e6-8ae8-087a6825cb9a.jpg)
![imagegallery_fermat_webpage2-01](https://cloud.githubusercontent.com/assets/20045567/16958968/d768c14a-4db0-11e6-88d1-c84832f3d2f3.jpg)
![imagegallery_fermat_webpage3-01](https://cloud.githubusercontent.com/assets/20045567/16958967/d74d0310-4db0-11e6-91ed-37289e4e6c49.jpg)
![imagegallery_fermat_webpage4-01](https://cloud.githubusercontent.com/assets/20045567/16958969/d7892c28-4db0-11e6-9b7d-87ddd8bd0edd.jpg)
![imagegallery_fermat_webpage5-01](https://cloud.githubusercontent.com/assets/20045567/16958970/d78e188c-4db0-11e6-88fb-617a375f7d53.jpg)

**Comment by arnaldos** [comment]
for a moment yes !! upload to repo plz !! and send me de link

**Comment by arnaldos** [comment]
@rennyx7  @rosanacoronado upload to repo plz
