### ISSUE TITLE
Create a icon On/Off to data mobile (consumos de la red de datos) setings to Fermat App

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#959]
Actual view setings apps

![apps-icon](https://cloud.githubusercontent.com/assets/13594347/16916462/ef972630-4cca-11e6-8396-1d092fa79e2b.png)

**Comment by solemiliia** [comment]
![icono](https://cloud.githubusercontent.com/assets/19818549/16929250/d1e000d2-4d04-11e6-8abd-d2638b54bc6d.jpg)

**Comment by arnaldos** [comment]
@solemiliia ese verde tiene mucho brillo, que otra sugerencia para esa funcion ? recuerda mostrar ambos estados On / Off

**Comment by solemiliia** [comment]
no se porque se esta viendo en ese color, realmente es un azul rey @arnaldos

**Comment by arnaldos** [comment]
@solemiliia pudieses trabajar algo asi https://www.devicemagic.com/wordpress/wp-content/uploads/2014/06/feature-offline1.png en dos colores para identificar los dos estados On/Off

**Comment by solemiliia** [comment]
![iconos](https://cloud.githubusercontent.com/assets/19818549/16959151/97d9c05a-4db1-11e6-9032-961eb9bf935b.jpg)

**Comment by solemiliia** [comment]
![icono](https://cloud.githubusercontent.com/assets/19818549/17114852/c9070940-527e-11e6-9228-039313c7ba21.jpg)

**Comment by m471c4** [comment]
@Magdy27 por favor, haz algunas propuestas para este caso.

**Comment by Magdy27** [comment]
![iconos](https://cloud.githubusercontent.com/assets/19651834/17420536/4509ecde-5a71-11e6-9108-ac8faee5d1ef.png)
![iconos2](https://cloud.githubusercontent.com/assets/19651834/17420533/443a9a2e-5a71-11e6-9ff6-2b29a7adac91.png)
![iconos3](https://cloud.githubusercontent.com/assets/19651834/17420534/44942440-5a71-11e6-9c39-d167b8fb1836.png)
![iconos---propuestas](https://cloud.githubusercontent.com/assets/19651834/17420593/b7c164c8-5a71-11e6-9001-7d5383b81e16.png)

**Comment by Magdy27** [comment]
@m471c4  @arnaldos

**Comment by arnaldos** [comment]
@Magdy27 disculpa deben mantener este mismo estilo gráfico 
![image](https://cloud.githubusercontent.com/assets/13594347/17423517/2f639872-5a89-11e6-927a-6c39cebff10b.png)

solo es hacer uno que permita encender y apagar el consumo de datos

**Comment by Magdy27** [comment]
![5](https://cloud.githubusercontent.com/assets/19651834/17439643/0eb0a728-5af7-11e6-899f-0c0e613762d6.png)
![iconos4](https://cloud.githubusercontent.com/assets/19651834/17439645/0ecb7800-5af7-11e6-82ab-9d0db80cd845.png)
![iconos5](https://cloud.githubusercontent.com/assets/19651834/17439644/0ec7deca-5af7-11e6-9fab-29fffe28cf0c.png)
![iconos6](https://cloud.githubusercontent.com/assets/19651834/17439642/0e966994-5af7-11e6-8af1-f380d37568d5.png)
![iconos---propuestas2](https://cloud.githubusercontent.com/assets/19651834/17439646/0f51e52a-5af7-11e6-93ec-6c7ed0d9df98.png)
@arnaldos @m471c4

**Comment by m471c4** [comment]
@Magdy27 me parece que podemos descartar la versión de las flechas porque rompe el esquema que se ha manejado para los otros iconos, donde los elementos distintivos están dentro de círculos.

Con respecto a las 3 propuestas con gráficos circulares: van bien, pero recuerda que estás trabajando con iconos, que son elementos muy pequeños, por lo que las líneas muy delgadas y los detalles pequeños o excesivos se van a perder en tamaño real. Trata de sintetizar un poco más los símbolos y prueba engrosando un poco las líneas. La señal de wifi, por ejemplo, no tiene que tener tantas líneas, puedes poner 3 y se va a seguir entendiendo. Lo mismo para la última propuesta.

Otra cosa, por favor enumera las propuestas y úbelas ordenadas.

@arnaldos cuando puedas dime ¿qué te parece?

**Comment by Magdy27** [comment]
![icono-1](https://cloud.githubusercontent.com/assets/19651834/17442522/26dc40de-5b04-11e6-87eb-75e27fcef513.png)
![iconos-2](https://cloud.githubusercontent.com/assets/19651834/17442523/272396f0-5b04-11e6-9d33-32697afe60f3.png)
![iconos-3](https://cloud.githubusercontent.com/assets/19651834/17442524/27712618-5b04-11e6-8a1d-cb0b0b83a209.png)

@arnaldos @m471c4

**Comment by m471c4** [comment]
@Magdy27 yo me iría por la primera porpuesta, pero eliminando la línea que une los 3 arcos del wifi; porque genera un efecto de valorización de la línea que hace un poco de ruido. También probaría con otro color, tal vez el azul que usaste para propuestas anteriores. Pero a menos de que @arnaldos tenga otra observación, creo que puede quedar así.

Me parece que la versión "Off" de los iconos es como se ve la opción "Private Network", en el mockup. Arnaldo, ¿nos puedes confirmar esto?

**Comment by m471c4** [comment]
@Magdy27 los colores se ven lavados en estas últimas propuestas. Revisa que estés usando la opción Guardar para web y que tu configuración de color sea RGB.

**Comment by Magdy27** [comment]
![icono-1](https://cloud.githubusercontent.com/assets/19651834/17452398/fc85eb08-5b3c-11e6-822c-744495e0e4d0.png)
@m471c4 @arnaldos

**Comment by Magdy27** [comment]
![icono-1](https://cloud.githubusercontent.com/assets/19651834/17452609/ae1baeba-5b3e-11e6-9b4b-5299b4e6ae49.png)
@arnaldos @m471c4

**Comment by arnaldos** [comment]
deberíamos buscar un icono que no sea el de wifi ya que no es ese el que queremos administrar. seria una icono de datos. fijate como lo manejan aqui no digo sea el mismo http://www.johnoneilldesign.com/wp-content/uploads/2013/11/mobile_icon.png

**Comment by arnaldos** [comment]
o así también 
http://www.istockphoto.com/fi/vector/mobile-data-and-payment-processing-prime-series-gm165943934-22204513

**Comment by arnaldos** [comment]
![image](https://cloud.githubusercontent.com/assets/13594347/17490505/21266fb0-5d71-11e6-9f86-2e86b9722555.png)

**Comment by Magdy27** [comment]
![1](https://cloud.githubusercontent.com/assets/19651834/17492163/9ac98d96-5d78-11e6-8160-31a04de76967.png)
![2](https://cloud.githubusercontent.com/assets/19651834/17492164/9aed9e20-5d78-11e6-91b8-345ee6e3e8ca.png)
![3](https://cloud.githubusercontent.com/assets/19651834/17492162/9aadb5c6-5d78-11e6-96fc-333723be4934.png)
@arnaldos @m471c4

**Comment by arnaldos** [comment]
@Magdy27 para este icono podemos probar sustituir el icono de la red por la de data mobiel y donde esta el circulo mas pequeño usar on - off

**Comment by Magdy27** [comment]
![1](https://cloud.githubusercontent.com/assets/19651834/17519091/742e7f34-5e18-11e6-8ce9-f60d929185b3.png)
@arnaldos @m471c4

**Comment by solemiliia** [comment]
![iconos](https://cloud.githubusercontent.com/assets/19818549/17567477/8493ced8-5f0d-11e6-9ab1-e9e6c74a29e4.jpg)

**Comment by arnaldos** [comment]
@Magdy27 De las ultimas dos versiones dejaría la primera, cambiando el off en gris y el on en verde o azul

**Comment by Magdy27** [comment]
![1](https://cloud.githubusercontent.com/assets/19651834/17588566/01d20e38-5f9e-11e6-8691-8ac07bd79165.png)
@arnaldos  @m471c4

**Comment by arnaldos** [comment]
@Magdy27 perfecto la ultima versión genera los recursos plz . un ves los tengas enviale a @furszy
