### ISSUE TITLE
Versión 3D del logo de Fermat COR

### ISSUE THREAD

**Issue by jonathanborges3d** [bitDubai/fermat-graphic-design#96]
Viene del #139 

Versión plana actual:

![](https://cloud.githubusercontent.com/assets/13468350/9672134/bca83980-5261-11e5-8ef7-fed3bedd658c.png)

Primer boceto 3D:

![f_cor_1](https://cloud.githubusercontent.com/assets/13649739/9718579/f054c36a-5546-11e5-92af-98a43c9a71f4.jpg)

![f_cor_2](https://cloud.githubusercontent.com/assets/13649739/9718594/16cc970c-5547-11e5-8d67-e332d2de8307.jpg)

![f_cor_3](https://cloud.githubusercontent.com/assets/13649739/9718627/40b47ae4-5547-11e5-9c27-fd018944b1a1.jpg)

Espero sus opiniones

@m471c4 @Luis-Fernando-Molina @arnaldos

**Comment by m471c4** [comment]
@jonathanborges3d ¡se ve muy bien! Yo no veo detalle alguno, no se qué opine @Luis-Fernando-Molina

**Comment by Luis-Fernando-Molina** [comment]
Esta muy bueno. No veo la sombra,  aunque que quizás en este caso no corresponda. 

Habla con Miguel para que lo ponga en fermat. Org y veamos como queda antes de hacer los otros por favor

**Comment by jonathanborges3d** [comment]
Ok, @Luis-Fernando-Molina, me pondré de acuerdo con @Miguelcldn para ver en qué formato lo necesita.

**Comment by Miguelcldn** [comment]
Me lo puedes dejar en .obj para probar.

O dependiendo de la herramienta que usaste podrías instalarle el exportador correspondiente de https://github.com/mrdoob/three.js/tree/master/utils/exporters para que lo pase a json

**Comment by jonathanborges3d** [comment]
@Miguelcldn, yo puedo exportarlo en json directamente, Primero lo paso a blender y despues uso el exporter. Lo que no sé es si necesita una proyección específica para los materiales y si necesita un mapa de oclusión para las sombras, Por favor dame detalles del json que usarías. Gracias.

**Comment by Miguelcldn** [comment]
Es la librería la que cargará el modelo leyendo la estructura estándar de objetos 3D en json. No encuentro documentación respecto al mapa de oclusión de sombras pero si puedes añádelo a ver si three.js es capaz de aplicarlo

**Comment by jonathanborges3d** [comment]
@Miguelcldn Ya está la primera versión del logo en formato .json en el repositorio. Lo probé con el editor de Three y lo carga bien, incluso con los materiales.

https://github.com/bitDubai/fermat-graphic-design/blob/f03da5b1c9ad815b23bbff6cd940332fa90fb0fb/Dise%C3%B1o%203D/Logos%203D/Fermat_COR.json

**Comment by Miguelcldn** [comment]
Excelente, dale, gracias por hacer la prueba :+1:

**Comment by jonathanborges3d** [comment]
Tranquilo, Avísame si hay que modificar algo.

**Comment by Miguelcldn** [comment]
Ok dale, tomará un tiempo porque preveo una dificultad técnica, yo te aviso cuando lo haya probado

**Comment by jonathanborges3d** [comment]
Modificación: con la fuente correcta en las siglas "COR"

![f_cor_4](https://cloud.githubusercontent.com/assets/13649739/9724099/e2e94390-559b-11e5-9cfd-2c283843da32.jpg)

**Comment by jonathanborges3d** [comment]
@Luis-Fernando-Molina Primer boceto del logo 3D de Fermat COR, versión moneda.

![f_cor_5](https://cloud.githubusercontent.com/assets/13649739/9749232/e4a832cc-5654-11e5-8f0e-b635f81839ae.jpg)

![f_cor_6](https://cloud.githubusercontent.com/assets/13649739/9749265/3d41a328-5655-11e5-9dd9-76457e85084c.jpg)

**Comment by m471c4** [comment]
@jonathanborges3d hubo un cambio en los colores de los logos (incluyendo este). Ya están actualizados en el repositorio.

**Comment by Luis-Fernando-Molina** [comment]
Muy bien!  Seguí avanzando...

**Comment by Luis-Fernando-Molina** [comment]
Estaría muy bueno si la sorbetes estuvieran inclinadas de manera que pasen una vez por arriba de las otra se otra por abajo

**Comment by Miguelcldn** [comment]
@jonathanborges3d Aquí la versión en desarrollo de la página http://3d.fermat.org la rotación está deshabilidata por ahora para que se pueda ver desde móviles, a @Luis-Fernando-Molina le parece que se ve plano, ¿qué opinas tu? la escala actual es (75, 75, 75), tiene una luz ambiental blanca. Ahorita estoy probando con distintas iluminaciones a ver qué tal

**Comment by Miguelcldn** [comment]
No veo que esté aplicando oclusión ambiental en la página, estoy trabajando en ello para que three.js aplique el SSAO.

**Comment by jonathanborges3d** [comment]
@Miguelcldn Que bueno verlo allí, me gusta pero noto algunas cosas:

1) La profundidad del modelo es mayor a la original, creo que si pruebas una escala de 30 en el valor correspondiente mejoraría la relación de aspecto

2) El color está algo opaco, creo que la iluminación de la escena en three debería ser un poco más intensa para poder apreciar el color  correctamente.

3) La oclusión ambiental se exporta como un mapa de bits que aplicas sobre un mapa difuso o la textura del modelo, eso le dice a Three.js cuáles partes van oscuras y cuales van iluminadas, incluyendo las sombras arrojadas; no sé si podemos trabajar con ello, puedo hacer un nuevo .json que utilice texturas y oclusión en una misma proyección. ¿Qué opinas?

**Comment by Miguelcldn** [comment]
1) Si, la profundidad la exageré para que se viera el relieve que @Luis-Fernando-Molina no podía notar, pero al tener oclusión no sería necesario porque ya se vería relieve.

2) La iluminación la disminuí un poco para ponerle otras luces pero no funcionó, sí puedo aumentar la intensidad sin problemas.

3) Estaría bueno tener la oclusión de una vez en la textura porque en la escena no hay luces dinámicas que vayan a cambiar eso y facilitaría el trabajo, porque hay poco avance con three.js para aplicar oclusión ambiental, lo único que encontre fue que con el shader darle el mapa de oclusión, pero en el json no lo veo.

**Comment by jonathanborges3d** [comment]
Ok, voy a preparar un nuevo archivo y a generar el mapa de oclusión, en cuanto lo tenga te aviso.

**Comment by jonathanborges3d** [comment]
@Miguelcldn Ya subí los archivos al repositorio:

https://github.com/bitDubai/fermat-graphic-design/commit/cf54a00e7e73a1b03dca4b4ed7f35cd31e42bb9b

**Comment by Miguelcldn** [comment]
En la página está subido con el mapa aplicado, pero el mapa se ve muy pixelado, la siguiente imagen es como se ve, la escala es (1, 1, 1), solo se trasladó más cerca de la cámara.

![dirty](https://cloud.githubusercontent.com/assets/5544266/9780836/79ffc8e6-5757-11e5-803e-25eb098fb1d3.png)

Si bien me parece que sería muy pesado duplicar la resolución del mapa de OA igual podríamos hacer la prueba. De todas maneras yo se usar blender, si quieres pásame el archivo exportado .blend o todo lo que necesite y así modifico las opciones de exportación a json hasta que me quede, por ahí vi que puedo usar el light map para ese efecto

**Comment by jonathanborges3d** [comment]
@Miguelcldn @Luis-Fernando-Molina  Hice una prueba con una escena de Three.js que tengo en archivos. El resultado es éste:

![f_cor_7](https://cloud.githubusercontent.com/assets/13649739/9837295/2934fb70-5a04-11e5-8f73-1c9168ba5d72.jpg)

Se puede apreciar un sombreado determinado por el color ambiental, eso ayuda a marcar el relieve.

Noto que los colores del logo están alterados, a pesar de que para cada uno utilicé un material distinto con una textura del color correspondiente, tomados del logo que está en .ai en el repositorio:

![f_cor_9](https://cloud.githubusercontent.com/assets/13649739/9837317/98770b0e-5a04-11e5-8af9-15728c8df449.jpg)

En el editor 3D se ve así:

![f_cor_8](https://cloud.githubusercontent.com/assets/13649739/9837316/9596a41c-5a04-11e5-8dc8-88cd3616780e.jpg)

No sé que estará causando el cambio de color en la escena pero al menos se puede apreciar el sombreado del objeto utilizando una luz básica en la escena.

**Comment by Luis-Fernando-Molina** [comment]
@jonathanborges3d  me gustaria ver como se ve de frente

**Comment by jonathanborges3d** [comment]
@Luis-Fernando-Molina Aquí está de frente, todavía no doy con la causa del cambio de color porque estoy usando mapas de bits separados para cada color del logo, parece que Three.js está aumentando la saturación de alguna manera.

![f_cor_10](https://cloud.githubusercontent.com/assets/13649739/9864523/5a38524c-5b14-11e5-8b99-b34e43d5a631.jpg)

**Comment by Miguelcldn** [comment]
Ciertamente la iluminación es un tema particular en lo que respecta a WebGL

Extracto de MDN (https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API/Tutorial/Lighting_in_WebGL):

> The first thing to understand about WebGL is that unlike the broader OpenGL standard, WebGL does not have inherent support for lighting. You have to do it yourself.

Aquí encontré una discusión con respecto a los materiales difusos y materiales de ambiente (los cuales en Blender nunca los he visto) en 3DS Max

https://github.com/mrdoob/three.js/ issues/6501 (Espacio a propósito para no referenciar el issue)

No se si aplique a la manera en la que estás tratando los materiales, pero por si acaso.

**Comment by Luis-Fernando-Molina** [comment]
@jonathanborges3d  Y si te generas un input menos saturado, no podés lograr luego que quede como el original?

**Comment by jonathanborges3d** [comment]
@Miguelcldn Podemos hacer una prueba en 3d.fermat.org agregando una luz direccional (sol u otra) y un ambiente un poco gris con éste .json? a ver si tendrías un mejor resultado. Gracias.

6eeec3ce3a1f292cbf974b8c771271122eee7608

**Comment by Miguelcldn** [comment]
Sí, no hay problema, cuando yo estaba probando con el modelo anterior puse una luz direccional que viniera desde la cámara. Ahora lo pruebo y paso una captura

**Comment by jonathanborges3d** [comment]
@Luis-Fernando-Molina He estado haciendo pruebas con los mapas de bits que le dan el color al logo en la escena de Three.js, aumenté la claridad de cada textura entre 90 y 100% y éste es el resultado:

![f_cor_11](https://cloud.githubusercontent.com/assets/13649739/10050047/270503a8-61e4-11e5-93b6-999f4cfa5362.jpg)

![f_cor_12](https://cloud.githubusercontent.com/assets/13649739/10050049/2d6e0456-61e4-11e5-8b74-7076512c101b.jpg)

![f_cor_13](https://cloud.githubusercontent.com/assets/13649739/10050058/349408c0-61e4-11e5-9b63-3f3261ccdd47.jpg)

![f_cor_14](https://cloud.githubusercontent.com/assets/13649739/10050165/cbaa6dc6-61e4-11e5-9b0e-cd00d12beb97.jpg)

No sé si se aleja mucho de la paleta original pero a mi me parece que puede funcionar así, debido a lo complicado de la iluminación.

Aquí una comparación del logo disponible en Fermat.org y la escena 3D de Three.js:

![f_cor_15](https://cloud.githubusercontent.com/assets/13649739/10050190/f01efa14-61e4-11e5-8760-902bbc8ef725.jpg)

**Comment by Luis-Fernando-Molina** [comment]
Yo lo veo aceptable, porqué no se lo pasas a @Miguelcldn asi lo pone en 3D.fermat.org . Yo creo que puede andar bien.

**Comment by jonathanborges3d** [comment]
@Luis-Fernando-Molina @Miguelcldn Listo, ya subí las nuevas imágenes al repositorio, sólo hay que sustituir las anteriores:

3ad369a6cdb6118bc6dec835914472b313fbbed1

**Comment by jonathanborges3d** [comment]
Actualización de la versión en moneda:

![f_cor_26](https://cloud.githubusercontent.com/assets/13649739/10472391/bd2891e6-71e9-11e5-8481-4d0e967d1250.jpg)

![f_cor_27](https://cloud.githubusercontent.com/assets/13649739/10472399/cf272e2a-71e9-11e5-806e-5d1d8a1af961.jpg)

**Comment by Luis-Fernando-Molina** [comment]
:+1:

**Comment by jonathanborges3d** [comment]
Actualización del render de la moneda para los covers de hangouts:

![cor_5](https://github-cloud.s3.amazonaws.com/assets/13649739/10566274/a485cf20-75ac-11e5-9f67-b5adde024bd5.jpg)

**Comment by Luis-Fernando-Molina** [comment]
:+1:
