### ISSUE TITLE
Create a banner to Dating webside 

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#960]
Image size 922x201 px

Actual banner 

![image](https://cloud.githubusercontent.com/assets/13594347/16968839/47b7b978-4ddf-11e6-9b4d-296d2d75a6f6.png)

**Comment by rennyx7** [comment]
![banner_webside](https://cloud.githubusercontent.com/assets/20045567/17114203/e5d4e0a4-527b-11e6-8937-fa383a56c689.jpg)

**Comment by rennyx7** [comment]
![banner_webside2](https://cloud.githubusercontent.com/assets/20045567/17117272/7026984e-5289-11e6-8b2a-98fbf6b671db.jpg)

**Comment by arnaldos** [comment]
@rennyx7 versión 2 pero el teléfono mas al centro lo ve mas hacia la derecha, agrégale mas símbolos gráficos plz.   no se si puedes incluir otra persona en la misma posición

**Comment by rennyx7** [comment]
![untitled-2](https://cloud.githubusercontent.com/assets/20045567/17257399/e9523cb0-558f-11e6-8b03-8c556a7ed5b9.jpg)

**Comment by rennyx7** [comment]
![2 2](https://cloud.githubusercontent.com/assets/20045567/17259991/e7944a92-559b-11e6-8024-8ddb1c2cba41.jpg)

**Comment by arnaldos** [comment]
genera una imagen donde se aprecien 2 personas intentando chatear entre si

**Comment by rennyx7** [comment]
Pero usando los celulares o en la vida real?

**Comment by rennyx7** [comment]
![image_internter](https://cloud.githubusercontent.com/assets/20045567/17378353/9e8a4c18-598b-11e6-9484-c31b100de8d8.jpg)

**Comment by arnaldos** [comment]
@rennyx7 esta es la imagen actual esta gusto mucho el concepto, trata de representar el mismo concepto con lo nuevo que se esta trabajando 

![image](https://cloud.githubusercontent.com/assets/13594347/17409027/6e6546e0-5a3b-11e6-9ba0-90573b7ae15c.png)

**Comment by rennyx7** [comment]
ok, tienes esa imagen disponible para trabajar con ella?

**Comment by arnaldos** [comment]
ya la ubico y te paso

**Comment by rennyx7** [comment]
![dating_banner_922x201](https://cloud.githubusercontent.com/assets/20045567/17447524/e0200cde-5b1c-11e6-933d-7f61b90247c1.png)

**Comment by arnaldos** [comment]
@rennyx7 trabaja los corazones pero con este estilo y color, los icono si los usas que sean mas tipo sketch.

**Comment by rennyx7** [comment]
cual estilo y color? como los viejos?

**Comment by arnaldos** [comment]
el color actual y los iconos llevalos tipo sketch.

**Comment by rennyx7** [comment]
![dating_banner_922x201_nueva1](https://cloud.githubusercontent.com/assets/20045567/17603150/e293bf4a-5fdd-11e6-98ce-0006b5315b45.png)

**Comment by rennyx7** [comment]
![dating_banner_922x201_nueva2](https://cloud.githubusercontent.com/assets/20045567/17603292/64fe3d3e-5fde-11e6-85e6-e176fd2c4512.png)
