### ISSUE TITLE
Create a new welcome dialog stile to Apps

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#962]
Actual dialog
![image](https://cloud.githubusercontent.com/assets/13594347/17112226/34288bd8-5273-11e6-80f6-035041cc07cf.png)

**Comment by saraguerrerot** [comment]
@arnaldos @emmysm @andiechan propuesta no.1

![image](https://cloud.githubusercontent.com/assets/19808868/17144980/a8bfe1fe-5326-11e6-9024-7fd83fec88cd.png)

**Comment by emmysm** [comment]
Me gusta la idea del wizard, pero creo que puede abarcar toda la pantalla. Por otra parte se pudiera dejar el banner también que estaba antes implementado @saraguerrerot . Qué opinas @arnaldos ?

**Comment by saraguerrerot** [comment]
01-a 

![image](https://cloud.githubusercontent.com/assets/19808868/17157237/1ac085ee-535c-11e6-8e57-61ac11391d59.png)

01-b

![image](https://cloud.githubusercontent.com/assets/19808868/17157254/303568ea-535c-11e6-9239-10b340e729d6.png)

**Comment by saraguerrerot** [comment]
01-c
![image](https://cloud.githubusercontent.com/assets/19808868/17157450/5b20fb86-535d-11e6-96b4-e54ac1ea2af8.png)

**Comment by emmysm** [comment]
No me convence mucho, @saraguerrerot. No me termina de parecer la moneda. Prueba con otras propuestas, porfa. Esa wallet usa de tipografía Roboto, si más no me equivoco.

**Comment by andiechan** [comment]
Propuesta No.2
![crypto customer_02](https://cloud.githubusercontent.com/assets/19866300/17187193/41b9f324-5406-11e6-8d33-564a01b08ecb.png)

Propuesta No. 3 
![crypto customer_03](https://cloud.githubusercontent.com/assets/19866300/17187194/41e1d2ae-5406-11e6-95db-2d35ccdc7d48.png)

**Comment by arnaldos** [comment]
@saraguerrerot @andiechan lo que debemos cambiar aquí es el dialog si quieren modificar os banners deben usar el logo de la app en cuestión. planteen otras propuestas plz

**Comment by saraguerrerot** [comment]
propuesta 2 ![image](https://cloud.githubusercontent.com/assets/19808868/17340866/06e522fa-58c0-11e6-8c9c-cf167f694b4b.png)

**Comment by saraguerrerot** [comment]
ah ok, perfecto @arnaldos

**Comment by saraguerrerot** [comment]
propuesta no. 3 @arnaldos @emmysm ![image](https://cloud.githubusercontent.com/assets/19808868/17341798/4e649b8e-58c4-11e6-9955-2b2cc91f5842.png)

**Comment by saraguerrerot** [comment]
propuesta 3.1 @arnaldos @emmysm 

![image](https://cloud.githubusercontent.com/assets/19808868/17341866/9ea5ff7a-58c4-11e6-823b-f1262fd8e039.png)

**Comment by andiechan** [comment]
![crypto customer_03-01](https://cloud.githubusercontent.com/assets/19866300/17346865/b8d5e980-58da-11e6-88bd-0815f60c498f.png)
![crypto customer_03-02](https://cloud.githubusercontent.com/assets/19866300/17346867/b8f22528-58da-11e6-9bcf-a0e75d739e8d.png)
![crypto customer_03-03](https://cloud.githubusercontent.com/assets/19866300/17346868/b9002cf4-58da-11e6-8662-0d62304b7a12.png)

**Comment by arnaldos** [comment]
@saraguerrerot @andiechan pudiesen colocar el welcome como un modal de pantalla completa usando una imagen referente a los brockers, incluyendo la informacion y logo de la app. les dejo unos ejemplos 

## ![image](https://cloud.githubusercontent.com/assets/13594347/17411621/024706a4-5a47-11e6-806a-dd0745f8b1ae.png)

## ![image](https://cloud.githubusercontent.com/assets/13594347/17411643/1423689a-5a47-11e6-89b0-f1e93f26d65a.png)

## ![image](https://cloud.githubusercontent.com/assets/13594347/17411725/76a91082-5a47-11e6-80d2-e6359009dd8e.png)

## ![image](https://cloud.githubusercontent.com/assets/13594347/17411743/87649450-5a47-11e6-81c5-a542e94c15e0.png)

![image](https://cloud.githubusercontent.com/assets/13594347/17411779/9d71bb42-5a47-11e6-9a53-b76dc9f054ee.png)

**Comment by arnaldos** [comment]
@andiechan trabaja con el dialog de la broker y @saraguerrerot con customer

**Comment by saraguerrerot** [comment]
propuesta crypto customer no. 4

![image](https://cloud.githubusercontent.com/assets/19808868/17446957/df17639e-5b19-11e6-9012-02818ee5a869.png)

prop 4.1

![image](https://cloud.githubusercontent.com/assets/19808868/17447017/313245c2-5b1a-11e6-87b8-9501e2e19943.png)

prop 4.2
![image](https://cloud.githubusercontent.com/assets/19808868/17446957/df17639e-5b19-11e6-9012-02818ee5a869.png)

prop 4.3 

![image](https://cloud.githubusercontent.com/assets/19808868/17447178/0b21751e-5b1b-11e6-936b-8c4daca07aab.png)

prop 4.4

prop 5 
![image](https://cloud.githubusercontent.com/assets/19808868/17447226/4616a07c-5b1b-11e6-8dfa-e621714cac40.png)

prop 5.1 

![image](https://cloud.githubusercontent.com/assets/19808868/17447255/6aa13010-5b1b-11e6-93a9-8a0cebe5654c.png)

prop 6
![image](https://cloud.githubusercontent.com/assets/19808868/17447591/479b59c2-5b1d-11e6-962a-f4b2aaf8e8e9.png)

@arnaldos

**Comment by andiechan** [comment]
Broker Propuesta .01
![cryptobroker_04-01](https://cloud.githubusercontent.com/assets/19866300/17452889/0ea32210-5b42-11e6-9e2a-5648a881c8b6.jpg)

Broker Propuesta .02
![cryptobroker_06-01](https://cloud.githubusercontent.com/assets/19866300/17452890/0ebb06dc-5b42-11e6-80bd-86da0d63f4cc.jpg)

Broker Propuesta .03
![cryptobroker_07-01](https://cloud.githubusercontent.com/assets/19866300/17452891/0ec28eb6-5b42-11e6-9902-5d7e54e2300d.jpg)

Broker Propuesta .04
![cryptobroker_02-01](https://cloud.githubusercontent.com/assets/19866300/17452892/0ed7f79c-5b42-11e6-9689-6e4c4c0bc119.jpg)

Broker Propuesta .05
![crypto_broker_01-01](https://cloud.githubusercontent.com/assets/19866300/17452893/0edbe866-5b42-11e6-9c09-cb854b315df0.jpg)

Broker Propuesta .06
![cryptobroker_03-01](https://cloud.githubusercontent.com/assets/19866300/17452894/0ee3e3b8-5b42-11e6-8fc3-1d8cdd8a18ac.jpg)

**Comment by emmysm** [comment]
Pienso que las pantallas de inicio que estás proponiendo les hace falta un poco más de brillo. La veo muy oscuras, se debe jugar con otro color que haga buen contraste con la paleta de colores del logo de la app @saraguerrerot

**Comment by saraguerrerot** [comment]
a. 
![image](https://cloud.githubusercontent.com/assets/19808868/17571309/b31bd542-5f1d-11e6-86b2-c44a7734ab5f.png)

b. 
![image](https://cloud.githubusercontent.com/assets/19808868/17571498/6bb0be9c-5f1e-11e6-91ce-a683a84ac0bc.png)

c.
![image](https://cloud.githubusercontent.com/assets/19808868/17571512/791f602e-5f1e-11e6-8d98-f830877d6396.png)

d.
![image](https://cloud.githubusercontent.com/assets/19808868/17571528/8b91daf2-5f1e-11e6-8518-125569c8a3e7.png)

e.
![image](https://cloud.githubusercontent.com/assets/19808868/17571530/9047316e-5f1e-11e6-8eb2-8c9744bba401.png)

@arnaldos @emmysm

**Comment by saraguerrerot** [comment]
f. 
![image](https://cloud.githubusercontent.com/assets/19808868/17574932/260fa7b2-5f33-11e6-8bda-3d196ff3c598.png)
 g.

![image](https://cloud.githubusercontent.com/assets/19808868/17574937/2f2a3916-5f33-11e6-8265-537f93f3a00a.png)

@arnaldos @emmysm

**Comment by saraguerrerot** [comment]
h.
![image](https://cloud.githubusercontent.com/assets/19808868/17575108/7fc23012-5f34-11e6-87ab-d3a0714f0076.png)

**Comment by arnaldos** [comment]
colocale un filtro mas oscuro como se muestra en esta imagen
https://cloud.githubusercontent.com/assets/13594347/17411725/76a91082-5a47-11e6-80d2-e6359009dd8e.png

**Comment by saraguerrerot** [comment]
a.1
 ![image](https://cloud.githubusercontent.com/assets/19808868/17753854/c4689b28-649f-11e6-91f0-a010523a268f.png)

b.1
![image](https://cloud.githubusercontent.com/assets/19808868/17753884/e25c6722-649f-11e6-821b-a954268ae832.png)

c.1
![image](https://cloud.githubusercontent.com/assets/19808868/17753905/05ca1470-64a0-11e6-841c-8da32c8bfcbf.png)

d.1
![image](https://cloud.githubusercontent.com/assets/19808868/17753918/120a7de2-64a0-11e6-903d-cf6368a0537d.png)

e.1
![image](https://cloud.githubusercontent.com/assets/19808868/17753932/22dfd9dc-64a0-11e6-85bf-a071c9edca9d.png)

@arnaldos

**Comment by isahq23** [comment]
@arnaldos el detalle con las imágenes es su límite de descargas de acuerdo a sus licencias. Por más gratuitas que sean todas las imágenes poseen códigos con los que se les sigue. 

Cuando descargas e instalas una app, todos los elementos se hacen copia en cada telf donde sea descargado e instalado. Esto puede ocasionar que la imagen en algún punto desaparezca porque se "sobrepasó su uso", algo asi como superar el límite de la tarjeta de crédito.

Pienso que debemos continuar con el trabajo de elementos puramente gráficos. Así nos evitamos problemas como ese.

**Comment by arnaldos** [comment]
entiendo bueno en este caso @saraguerrerot sigue con el consejo de isa 

Te dejo algunas referencias

## ![image](https://cloud.githubusercontent.com/assets/13594347/17791805/4f430654-656b-11e6-9f1f-6ad0414f0faf.png)

## ![image](https://cloud.githubusercontent.com/assets/13594347/17791819/68406638-656b-11e6-987a-5c5c2846dd3f.png)

## ![image](https://cloud.githubusercontent.com/assets/13594347/17791824/71ff323a-656b-11e6-84c5-c8d66115082a.png)

## ![image](https://cloud.githubusercontent.com/assets/13594347/17791858/a42f11bc-656b-11e6-8da2-ba028e2f323a.png)

![image](https://cloud.githubusercontent.com/assets/13594347/17791879/c54ff44c-656b-11e6-81fd-b249108f1fa1.png)

**Comment by saraguerrerot** [comment]
1
![image](https://cloud.githubusercontent.com/assets/19808868/17793162/5c27f052-6573-11e6-82dc-21cd73026ef8.png)

2
![image](https://cloud.githubusercontent.com/assets/19808868/17793165/699024a8-6573-11e6-8dd7-6bafdb41ef97.png)

3
![image](https://cloud.githubusercontent.com/assets/19808868/17793177/7355eeb4-6573-11e6-841d-ce5066d9317f.png)

4
![image](https://cloud.githubusercontent.com/assets/19808868/17793181/7deeec54-6573-11e6-879a-bc8b3b01bc23.png)

5
![image](https://cloud.githubusercontent.com/assets/19808868/17793190/8fec3344-6573-11e6-9ee2-1169c39d0fa6.png)

6
![image](https://cloud.githubusercontent.com/assets/19808868/17793229/b963f6b2-6573-11e6-8cad-c4a46cb7d952.png)

@arnaldos

**Comment by arnaldos** [comment]
coloca el logo en diapo ya que tiene colores similares con el fondo

**Comment by saraguerrerot** [comment]
![image](https://cloud.githubusercontent.com/assets/19808868/17820882/ed183db6-661c-11e6-9274-b7a92e4e4129.png)
 @arnaldos

**Comment by isahq23** [comment]
@arnaldos @saraguerrerot me gusta mucho la última, con el fondo temático.
Porque es un elemento gráfico pero le da profundidad.

**Comment by arnaldos** [comment]
@saraguerrerot @isahq23 si de acuerdo solo que aquí trabajaría los tonos de la customer , la diagramacion de los textos y boton como la version 2 o 4 que se muestra con mayor espacio.

**Comment by isahq23** [comment]
Totalmente de acuerdo, hay que darle espacio al texto de lectura como también al cuadro de selección.
Recuerda que esto se maneja con los dedos, debe existir un buen espacio.

@saraguerrerot 
Revisa esto https://material.google.com/layout/metrics-keylines.html#metrics-keylines-keylines-spacing

**Comment by saraguerrerot** [comment]
![image](https://cloud.githubusercontent.com/assets/19808868/17874656/23ca8974-689b-11e6-8e3a-c7fba387376c.png)

@arnaldos @isahq23

**Comment by isahq23** [comment]
@saraguerrerot qué diferencia en pixeles hay entre el check-box y el botón de close?

**Comment by saraguerrerot** [comment]
65px @isahq23
