### ISSUE TITLE
Update Crypto Broker Wallet UI/UX

### ISSUE THREAD

**Issue by isahq23** [bitDubai/fermat-graphic-design#964]
Convert screenshots from Crypto Broker Wallet to vectors so files inside the repo match with the actual view of the app.

Drive URL with files
https://drive.google.com/drive/u/0/folders/0B-ykaWmX3h6UNmhTNmhMd2RIZG8

**PLEASE**
1. Update in comments all the views vectorized
2. Update .ai file with vectorized screens inside the Drive folder so it can be checked

**Comment by isahq23** [comment]
@karentvillegas this case is yours

**Comment by karentvillegas** [comment]
@isahq23 

![cbw_1](https://cloud.githubusercontent.com/assets/19273211/17382926/5fa9983a-59a1-11e6-87fe-56f589fbb4f0.jpg)
![cbw_2](https://cloud.githubusercontent.com/assets/19273211/17382932/67c62bbe-59a1-11e6-91dd-14e868e65a26.jpg)
![cbw_3](https://cloud.githubusercontent.com/assets/19273211/17382935/6b551010-59a1-11e6-9d42-c645b09be891.jpg)
![cbw_4](https://cloud.githubusercontent.com/assets/19273211/17382942/6f8da2aa-59a1-11e6-9dcc-afd10fb219ae.jpg)
![cbw_5](https://cloud.githubusercontent.com/assets/19273211/17382946/73fcb72c-59a1-11e6-98fc-8d87def9cc2d.jpg)
![cbw_6](https://cloud.githubusercontent.com/assets/19273211/17382948/7a21aebe-59a1-11e6-9fa1-fdef2163a81c.jpg)

**Comment by arnaldos** [comment]
nice !!

**Comment by isahq23** [comment]
@karentvillegas perfect, the file is also complete!
Thank you!
