### ISSUE TITLE
Translate Workflows inside CBP Document

### ISSUE THREAD

**Issue by isahq23** [bitDubai/fermat-graphic-design#965]
Follow the comments leaved by Angel Veloz to the untranslated content inside the CBP document and translate every word and sentenced written in spanish.

https://docs.google.com/document/d/1SGR4LSyAGu6_E5pGoTZADASNiGcmNRavJrV0knHjqu8/edit

_PS: you already have edit permission_

**PLEASE** publish the URL doc with adjustments as a comment after translated to be reviewed and accepted

**Comment by isahq23** [comment]
@rennyx7 this case is yours

**Comment by rennyx7** [comment]
ready 
https://docs.google.com/document/d/1SGR4LSyAGu6_E5pGoTZADASNiGcmNRavJrV0knHjqu8/edit#

**Comment by isahq23** [comment]
@rennyx7 great thanks, now organize everything you translate please.

**Comment by rennyx7** [comment]
Ready to go 
https://docs.google.com/document/d/1SGR4LSyAGu6_E5pGoTZADASNiGcmNRavJrV0knHjqu8/edit#heading=h.8j8mhlqxowyj

**Comment by isahq23** [comment]
@rennyx7 great job! thank you!
