### ISSUE TITLE
Convert screenshots from Crypto Costumer  to vectors UX/UI

### ISSUE THREAD

**Issue by proseuz** [bitDubai/fermat-graphic-design#966]
Convert screenshots from Crypto Costumer  to vectors.

**Comment by proseuz** [comment]
this are the screenshots @rosanacoronado  this case is your
![screenshot_2016-07-29-23-28-28](https://cloud.githubusercontent.com/assets/17308060/17370659/dc9783ac-596a-11e6-9050-4df93d761776.png)
![screenshot_2016-07-29-23-27-58](https://cloud.githubusercontent.com/assets/17308060/17370660/dca47d32-596a-11e6-9a50-516a034cf99d.png)
![screenshot_2016-07-29-23-31-19](https://cloud.githubusercontent.com/assets/17308060/17370682/f556a1ca-596a-11e6-98d5-606b7fec2803.png)
![screenshot_2016-07-29-23-31-26](https://cloud.githubusercontent.com/assets/17308060/17370683/f5652006-596a-11e6-9aac-a730c3d28636.png)
![screenshot_2016-07-29-23-31-05](https://cloud.githubusercontent.com/assets/17308060/17370684/f58c8a74-596a-11e6-95f4-58db59d395ba.png)
![1](https://cloud.githubusercontent.com/assets/17308060/17370698/047e2254-596b-11e6-97d0-1237d9c8a88d.png)
![screenshot_2016-07-28-16-37-21](https://cloud.githubusercontent.com/assets/17308060/17370709/14d9615e-596b-11e6-965d-963caf16323c.png)
![screenshot_2016-07-28-16-37-16](https://cloud.githubusercontent.com/assets/17308060/17370710/151b724c-596b-11e6-8d92-e9a641506d3d.png)
![screenshot_2016-07-28-16-38-38](https://cloud.githubusercontent.com/assets/17308060/17370732/2bbc328e-596b-11e6-8ff0-0e6f703bef15.png)
![screenshot_2016-07-28-16-37-42](https://cloud.githubusercontent.com/assets/17308060/17370733/2bd4a314-596b-11e6-9823-39cd583a5adb.png)
![screenshot_2016-07-28-16-38-21](https://cloud.githubusercontent.com/assets/17308060/17370734/2be78f2e-596b-11e6-9163-fc742115af2c.png)

**Comment by arnaldos** [comment]
@jhonmarquez92 the browser list are wrong , check the container image. has a square Queser or circilar but not both. this should be clarified with development. some views are raady in previous mockups  right ?.

**Comment by proseuz** [comment]
@arnaldos These are sreenshot of the current app, I think the container images must be circular to ensure consistency with other views. I do not understand because the name is red if no part of the color palette of the app, I think we should rethink the design.

Yes, the other views are ready, you can review the document.

**Comment by arnaldos** [comment]
@jhonmarquez92 Agreement with you the container images must be circular. About the text I was not sure a change of developers . segurament quienren transmitr currently not understand something , ask @nelsonalfo

**Comment by proseuz** [comment]
@arnaldos  I also believe that the background should be white. When Nelson connect I talk to him

**Comment by arnaldos** [comment]
perfect !!

**Comment by rosanacoronado** [comment]
@jhonmarquez92 @arnaldos here are all the screenshots with suggested changes 

![crypto customer 1-01](https://cloud.githubusercontent.com/assets/19508456/17504225/fe76f0c6-5dc4-11e6-9dd2-a2ba48144f03.png)
![crypto customer screens 2-01](https://cloud.githubusercontent.com/assets/19508456/17504226/fe8626f4-5dc4-11e6-82e0-afce6261d84f.png)
![crypto customer screens 3-01](https://cloud.githubusercontent.com/assets/19508456/17504227/fe97f49c-5dc4-11e6-92b7-371775fb15a3.png)
![crypto customer screens 4-01](https://cloud.githubusercontent.com/assets/19508456/17504228/feab6de2-5dc4-11e6-82e3-588f1953b3bf.png)
![crypto customer screens 5-01](https://cloud.githubusercontent.com/assets/19508456/17504230/febc46bc-5dc4-11e6-88dd-1962eeb27db2.png)
![crypto customer screens 6-01](https://cloud.githubusercontent.com/assets/19508456/17504231/fece1266-5dc4-11e6-83fd-38818f5841f6.png)
![crypto customer screens 7-01](https://cloud.githubusercontent.com/assets/19508456/17504232/fede8e70-5dc4-11e6-832c-b34c8f9a9950.png)
![crypto customer screens 8-01](https://cloud.githubusercontent.com/assets/19508456/17504233/fef52806-5dc4-11e6-9ecd-97be7e2c6552.png)
![crypto customer screens 9-01](https://cloud.githubusercontent.com/assets/19508456/17504234/ff0592ae-5dc4-11e6-98d5-190c474eb3be.png)
![crypto customer screens 10-01](https://cloud.githubusercontent.com/assets/19508456/17504235/ff1a953c-5dc4-11e6-9c8f-eeb95ba8b55a.png)
![crypto customer screens 11-01](https://cloud.githubusercontent.com/assets/19508456/17504236/ff2abb60-5dc4-11e6-8b61-fc0f1d840d84.png)
![crypto customer screens 12-01](https://cloud.githubusercontent.com/assets/19508456/17504237/ff40abbe-5dc4-11e6-8df3-454add089528.png)

**Comment by proseuz** [comment]
cool @arnaldos  you can close this case

**Comment by rosanacoronado** [comment]
I think this is the correct visualization of these screenshots guys @jhonmarquez92 @arnaldos 

![crypto customer screens 2-01](https://cloud.githubusercontent.com/assets/19508456/17528095/e5126bfc-5e3b-11e6-9aed-2fcbc8020ba2.png)
![crypto customer screens 1-01](https://cloud.githubusercontent.com/assets/19508456/17528096/e5326ab0-5e3b-11e6-8b65-c2398167a1fe.png)

**Comment by proseuz** [comment]
yes, what size have the image? @rosanacoronado

**Comment by rosanacoronado** [comment]
360 x 640 @jhonmarquez92 I worked with the document sizes

**Comment by arnaldos** [comment]
I see it is fine.
