### ISSUE TITLE
Organize and Add the Missing Screenshots

### ISSUE THREAD

**Issue by isahq23** [bitDubai/fermat-graphic-design#967]
Organize the vectorized screenshots inside the final file for Crypto Broker Wallet and add the new vectorized screens.

Also, erase any extra vector or image inside the file and modify each table for each screen to the right size - 360x640

Drive Files
https://drive.google.com/drive/u/0/folders/0B-ykaWmX3h6UNmhTNmhMd2RIZG8

**PLEASE** 
Upload a full view of the finished work to be reviewed

**Comment by isahq23** [comment]
@karentvillegas this case is yours, please until file is upload into drive

**Comment by arnaldos** [comment]
@isahq23 when is the date delivery ?

**Comment by isahq23** [comment]
@arnaldos I can only put title and description for new issues, I don't have option to place a top finish date.

But it's for this friday 05/08/2016

**Comment by karentvillegas** [comment]
@arnaldos @isahq23 
Full view of the finished work

![crypto_broker_wallet](https://cloud.githubusercontent.com/assets/19273211/17447439/625a84dc-5b1c-11e6-9926-1689e915500e.jpg)

**Comment by isahq23** [comment]
@karentvillegas great job, I think that's all.
@arnaldos @AdryCanonico can you guys check this? Please

**Comment by arnaldos** [comment]
@isahq23 @karentvillegas 
the image of the user is very close to the edge of the status bar this should be smaller and be focused on actionbar. The text in one line plz.

![image](https://cloud.githubusercontent.com/assets/13594347/17490067/12ebb2c2-5d6f-11e6-9445-0d90c5225ee5.png)

**Comment by karentvillegas** [comment]
@arnaldos @isahq23 
Corrected views
![crypto_broker_wallet1](https://cloud.githubusercontent.com/assets/19273211/17497741/6c4407f8-5d91-11e6-9a0b-b87159fa1502.jpg)

**Comment by arnaldos** [comment]
@karentvillegas perfect !! :+1:

**Comment by isahq23** [comment]
@karentvillegas please send the file to @rennyx7 so he can upload it in the repo.
Of course, let him know where.
