### ISSUE TITLE
Create a Image for Youtube Profile to Artist Platform

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#968]
Banner size 2560x423 px

Profile size 250x250 px

Date Delivery 04-08-2016

**Comment by Jessicafp** [comment]
@arnaldos @jhonmarquez92 Cuando subo la imagen para probarla en mi perfil de youtube me dice que es muy pequeña, no me acepta que mida 423 px

**Comment by arnaldos** [comment]
revisa bien la medida  es 2560x423

**Comment by Jessicafp** [comment]
![banner youtube](https://cloud.githubusercontent.com/assets/19536846/17564024/eaee1a66-5eff-11e6-8e21-ae28d705cb45.png)

**Comment by Jessicafp** [comment]
@arnaldos @jhonmarquez92 Asi se veria el banner con esas medidas, pero no me permite probarlo en el perfil de youtube, me dice que es muy pequeño el tamaño, no se si quieran probarlo ustedes, puede ser mi pc que este fallando

**Comment by proseuz** [comment]
y la foto de profile? @Jessicafp

**Comment by Jessicafp** [comment]
@jhonmarquez92 Seria la misma de las otras redes, pero estoy en espera de la aprobacion de arnaldo a ver cual es la opcion que mas le gusta

**Comment by arnaldos** [comment]
@Jessicafp ok para los profles recuerda que las medidas son distintas a pesar que son cuadras

**Comment by arnaldos** [comment]
si intente pero fijte que cambio ahi en el mensaje te dice la nueva medida que es de 2048x1152

**Comment by arnaldos** [comment]
minimo 2048x1152 y recomendado 2560 x1440

**Comment by arnaldos** [comment]
Adjunto imagen
![image](https://cloud.githubusercontent.com/assets/13594347/17568285/19a5c032-5f11-11e6-941c-abedbc1f4c3f.png)

**Comment by arnaldos** [comment]
revisa que lo que se va a visualizar este dentro de 2560x423 centrado.

**Comment by arnaldos** [comment]
fijate como se muestra
![image](https://cloud.githubusercontent.com/assets/13594347/17570677/66c17f96-5f1b-11e6-95b8-16f1b1c728cc.png)

**Comment by Jessicafp** [comment]
![youtube 1](https://cloud.githubusercontent.com/assets/19536846/17577228/2b5d59ba-5f49-11e6-9c4b-27b093645cb6.png)
![youtube 2](https://cloud.githubusercontent.com/assets/19536846/17577229/2be1ea68-5f49-11e6-9fd4-48f5286d188f.png)

**Comment by Jessicafp** [comment]
@arnaldos @jhonmarquez92 Aqui se presenta la vista del perfil y abajo las vistas en los demas dispositivos

**Comment by arnaldos** [comment]
@Jessicafp pon la imagen completa para ver el detalle sino me equivoco veo a la mujer picada se raro

**Comment by Jessicafp** [comment]
![muestraa](https://cloud.githubusercontent.com/assets/19536846/17613492/000f1bac-602c-11e6-9559-ea81e24e29df.png)
![muestraaa](https://cloud.githubusercontent.com/assets/19536846/17613493/00167f00-602c-11e6-86a2-5c28e4dac219.png)

**Comment by proseuz** [comment]
la segunda funciona @arnaldos qué crees?

**Comment by arnaldos** [comment]
@Jessicafp @jhonmarquez92 no esta mal pero probaria pasar las lineas en todo el espacio y no queden cortadas el unico momento que se corte sea cuando se suba al youtube el mismo croper marque el area a mostrarse

**Comment by Jessicafp** [comment]
![1](https://cloud.githubusercontent.com/assets/19536846/17788282/ea7b3df0-655a-11e6-9012-ff2cd5fcb23c.png)
![2](https://cloud.githubusercontent.com/assets/19536846/17788283/ea7d7c46-655a-11e6-860d-f88d8b9824d2.png)

**Comment by proseuz** [comment]
@arnaldos  que opinas?

**Comment by arnaldos** [comment]
@jhonmarquez92 @Jessicafp ok prueba algo elimina algunas lineas de abajo y que se mantengan en el cuadrante de arriba como en el de abajo sin sangrar las lineas. pon unas mas arriba y evaluemos los resultados

**Comment by Jessicafp** [comment]
![prueba 1](https://cloud.githubusercontent.com/assets/19536846/17827503/fa87d888-664b-11e6-8380-267d555b9060.png)
![prueba 2](https://cloud.githubusercontent.com/assets/19536846/17827502/fa8e4df8-664b-11e6-9f0c-bfce0005d4f9.png)

**Comment by arnaldos** [comment]
version 1
