### ISSUE TITLE
Create a Image for Twitter Profile to Artist Platform

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#969]
Banner size 1500x500 px

Profile size 500x500 px

Date Delivery 04-08-2016

**Comment by Jessicafp** [comment]
![banner platform artist 2](https://cloud.githubusercontent.com/assets/19536846/17454064/e5843160-5b57-11e6-86df-529859ab5e1a.png)
![banner platform artist 3](https://cloud.githubusercontent.com/assets/19536846/17454066/e5909a40-5b57-11e6-9448-f93fb1340607.png)
![banner platform artist 4](https://cloud.githubusercontent.com/assets/19536846/17454065/e58aeb54-5b57-11e6-88b4-28dba37769f8.png)
![banner platform artist](https://cloud.githubusercontent.com/assets/19536846/17454063/e51135ac-5b57-11e6-8bbd-4ba63384e432.png)

**Comment by Jessicafp** [comment]
@arnaldos @jhonmarquez92

**Comment by proseuz** [comment]
@arnaldos cuál te parece? @Jessicafp  falta la imagen del profile

**Comment by proseuz** [comment]
Tienes que probar que la imagen del profile no tape el logo de la plataforma @Jessicafp

**Comment by arnaldos** [comment]
@jhonmarquez92 @Jessicafp Estaria entre la 4 y la 1 pero hay que ver como se comporta cuando tiene la imagen del perfil montada. @Jessicafp montala en un perfil y verificamos realiza esto con las otras redes también

**Comment by Jessicafp** [comment]
![1](https://cloud.githubusercontent.com/assets/19536846/17501697/5eed319c-5daf-11e6-91be-f73ca06b88c7.png)
![2](https://cloud.githubusercontent.com/assets/19536846/17501698/5fe060a6-5daf-11e6-914b-b3c2edd027c9.png)

**Comment by Jessicafp** [comment]
@arnaldos @jhonmarquez92 Aca estan las 2 artes que le gustaron a arnaldo, presentadas como en la red social

**Comment by proseuz** [comment]
Lo que no me gusta de la propuesta 2 es que es muy colorida @arnaldos qué opinas tú?

**Comment by proseuz** [comment]
creo que la foto del profile podría estar sin los logos de la fan y la music @arnaldos

**Comment by arnaldos** [comment]
@Jessicafp @jhonmarquez92 en el perfil debe aparecer el logo de la art platform

**Comment by Jessicafp** [comment]
![muestra 1](https://cloud.githubusercontent.com/assets/19536846/17505497/7fed4ec0-5dcf-11e6-912f-7f21f56243aa.png)
![muestra 2](https://cloud.githubusercontent.com/assets/19536846/17505498/7ff46e94-5dcf-11e6-96fd-27e6ecf2ca9a.png)

**Comment by proseuz** [comment]
@arnaldos  que te parece la foto del profile?

**Comment by arnaldos** [comment]
aplica lo mismo que en este issue #970

**Comment by Jessicafp** [comment]
![face](https://cloud.githubusercontent.com/assets/19536846/17577268/9c2cec6e-5f49-11e6-8841-884262ea550d.png)

Esta seria la elección final

**Comment by proseuz** [comment]
yo creo que está listo @arnaldos

**Comment by arnaldos** [comment]
perfecto una ves listo subelo todo el pack para enviarlo a sustituirlo
