### ISSUE TITLE
Versión 3D del logo de Fermat PIP

### ISSUE THREAD

**Issue by jonathanborges3d** [bitDubai/fermat-graphic-design#97]
Viene del #139 

Versión plana actual:

![fermat_pip_2](https://cloud.githubusercontent.com/assets/13649739/9723964/6f94b8dc-5598-11e5-993e-d02f186b4657.png)

Primer boceto 3D

![f_pip_1](https://cloud.githubusercontent.com/assets/13649739/9724021/c0f039b2-5599-11e5-9cfc-53a3a0709e3a.jpg)

![f_pip_2](https://cloud.githubusercontent.com/assets/13649739/9724024/14ff0e34-559a-11e5-9174-f64d23f68a80.jpg)

![f_pip_3](https://cloud.githubusercontent.com/assets/13649739/9724028/2e6105f8-559a-11e5-99f5-adec1ee540de.jpg)

@Luis-Fernando-Molina Posteo éste porque ya lo tenía adelantado cuando terminé el de Fermat COR, de todos modos esperaré los resultados de las pruebas de Miguel para continuar con los otros.

@m471c4 Aquí si utilicé la fuente correcta para las tres siglas en mayúscula, un detalle que se me pasó en el de Fermat COR.

**Comment by Luis-Fernando-Molina** [comment]
OK esta muy bueno este también

**Comment by jonathanborges3d** [comment]
@Luis-Fernando-Molina Actualización a la paleta de colores aprobada, versión en moneda y versión en modelo para 3d.fermat.org:

En el editor:
![f_pip_4](https://cloud.githubusercontent.com/assets/13649739/10090580/f7952356-62fa-11e5-989f-0a796388058b.jpg)

Versión en moneda:

![f_pip_5](https://cloud.githubusercontent.com/assets/13649739/10090598/2e971b70-62fb-11e5-85ea-e5ca58b35641.jpg)

![f_pip_6](https://cloud.githubusercontent.com/assets/13649739/10090636/92f88a04-62fb-11e5-8253-0a32916289a4.jpg)

Versión .json para 3d.fermat.org:

![f_pip_7](https://cloud.githubusercontent.com/assets/13649739/10091655/f17219fe-6307-11e5-9271-51561b046bde.jpg)

![f_pip_8](https://cloud.githubusercontent.com/assets/13649739/10091656/fb1ed758-6307-11e5-93d0-bc3d57b9095b.jpg)

**Comment by Luis-Fernando-Molina** [comment]
Excelente @jonathanborges3d  !!! Sigamos avanzando con los otros logos ahora que se destrabó el uso 3D y que estan en una version mas estable. Me gustaria que @Miguelcldn lo ponga en 3d.fermat.org pronto!

Avancemos tambien la moneda que asi como va, ya va muy bien.

**Comment by Luis-Fernando-Molina** [comment]
Hay que encontrar un formato para estas monedas que representan plataformas y luego aplicarselo a todas. En este caso no vamos a hacer un diseño completamente distinto por cada una como en las monedas de los paises.

**Comment by jonathanborges3d** [comment]
@Luis-Fernando-Molina Con respecto al formato de las monedas de los logos de las plataformas, pienso que podríamos seguir con materiales plateados para todas y colocar en la parte superior en todos los casos "Fermat ###" y en la parte inferior la descripción que tienen en el logo, en algunos casos como COR y ésta la descripción es corta y pude colocarla en los laterales, pero en WPD y CCP (y otros que estuve viendo) la descripción es más extensa por lo que no podría colocarla en igual posición.

Aquí están todas las que llevo hasta ahora:

![f_cor_5](https://cloud.githubusercontent.com/assets/13649739/9749232/e4a832cc-5654-11e5-8f0e-b635f81839ae.jpg)
![f_pip_5](https://cloud.githubusercontent.com/assets/13649739/10090598/2e971b70-62fb-11e5-85ea-e5ca58b35641.jpg)
![f_wpd_1](https://cloud.githubusercontent.com/assets/13649739/10263456/763a0bf8-69b9-11e5-8508-a0ac65ab6bc0.jpg)
![f_ccp_5](https://cloud.githubusercontent.com/assets/13649739/10265628/209e154c-6a02-11e5-87f8-925c9be6a4c2.jpg)

Los espacios sobrantes entre el nombre de la plataforma y la descripción pudiesen tener estrellas como en la moneda de CCP.

¿Qué piensas al respecto?

**Comment by Luis-Fernando-Molina** [comment]
Prefiero el formato de las 2 primeras, pero si no entra la frase por ser mas larga puede que sté bien como la planteaste con la salvedad de que la frase en ambas debe tener el mismo tamaño de letra. 

Es mejor que rellenes los espacios con estrellas a que queden vacios.

**Comment by Luis-Fernando-Molina** [comment]
Todas estas monedas estan muy lindas pero me parece que le falta un poco para terminarlas. Proba con alguna de ella ponerle un poco mas de detalles o terminaciones, que luego de aprobadas se pueda trasladar al resto.

**Comment by jonathanborges3d** [comment]
@Luis-Fernando-Molina Ok. Comencé por añadirle un dentado al borde exterior, ubiqué la descripción en la parte inferior y rellené el espacio entre los textos con estrellas:

![f_cor_16](https://cloud.githubusercontent.com/assets/13649739/10299145/74e2de08-6bb0-11e5-8995-ec57dbe0350e.jpg)

![f_cor_17](https://cloud.githubusercontent.com/assets/13649739/10299150/87a15aec-6bb0-11e5-9c8e-e09f0bb07862.jpg)

Aquí una prueba incluyendo un fondo en un material cobrizo:

![f_cor_18](https://cloud.githubusercontent.com/assets/13649739/10299297/2bd6996e-6bb2-11e5-90a9-3bdf8772e507.jpg)

Tal vez ayude a mejorar la apariencia si se emplean dos materiales.

**Comment by Luis-Fernando-Molina** [comment]
Proba que el material nuevo solo sea en la parte interna, noen el aro. Fijate si podes simular cobre para eso.

El dentado queda bien pero es igual al otro, se podrá usar algun otro patron ahí?

**Comment by jonathanborges3d** [comment]
@Luis-Fernando-Molina Qué tal éste borde y el material de cobre?

![f_cor_19](https://cloud.githubusercontent.com/assets/13649739/10329001/b3c1aa94-6c84-11e5-8581-a4735efc6989.jpg)

**Comment by Luis-Fernando-Molina** [comment]
Me gusto el borde. El cobre puede ser. no se ve metalico pero puede ser por la iluminación. Realmente usaste un material de cobre o uno de color cobre?

**Comment by jonathanborges3d** [comment]
@Luis-Fernando-Molina Si, usé un material de cobre, no el preset, lo edité un poco en el color porque era muy claro:

![cobre_1](https://cloud.githubusercontent.com/assets/13649739/10349326/c0b7d556-6d07-11e5-96cf-ddebb0f46611.jpg)

Hice otros renders con variantes de iluminación, de pronto puede mejorar:

![f_cor_20](https://cloud.githubusercontent.com/assets/13649739/10349281/86d8ede8-6d07-11e5-8f3e-437462d26630.jpg)

![f_cor_21](https://cloud.githubusercontent.com/assets/13649739/10349339/daa9f250-6d07-11e5-82ba-dbcf5d678682.jpg)

Otra versión del material:

![cobre_2](https://cloud.githubusercontent.com/assets/13649739/10354156/43ba451e-6d27-11e5-891f-f4a52e2b500d.jpg)

![f_cor_23](https://cloud.githubusercontent.com/assets/13649739/10354160/49c028ac-6d27-11e5-8bb9-2f8e79668eec.jpg)

![f_cor_24](https://cloud.githubusercontent.com/assets/13649739/10354169/5fbc901e-6d27-11e5-99de-ad8fea363a56.jpg)

**Comment by Luis-Fernando-Molina** [comment]
Ok, con la primera version esta OK.

Quizas pudiera quedar asi la moneda, probemos como quedaria con las letras y estrellas en oro.

**Comment by jonathanborges3d** [comment]
@Luis-Fernando-Molina Versión con las letras y estrellas doradas:

![f_cor_25](https://cloud.githubusercontent.com/assets/13649739/10383409/57daebee-6df8-11e5-96f7-de87ff22cc39.jpg)

**Comment by Luis-Fernando-Molina** [comment]
ok puede quedar asi. Fijate que las billeteras no estén levemente en el aire por favor.

**Comment by jonathanborges3d** [comment]
@Luis-Fernando-Molina Ok, revisé el modelo, las billeteras tienen parte del modelo por debajo del nivel del fondo de cobre, parece que estuviesen en el aire por la reflexión del metal.

Hice la versión correspondiente al logo de éste issue:

![f_pip_9](https://cloud.githubusercontent.com/assets/13649739/10399191/f349fbba-6e7a-11e5-9edc-2f3cf70e6369.jpg)

![f_pip_10](https://cloud.githubusercontent.com/assets/13649739/10399203/078d9172-6e7b-11e5-899f-c27db10c6fd0.jpg)

Pensé en colocar en el otro lado un logo común a todas las monedas:

![f_dmp_1](https://cloud.githubusercontent.com/assets/13649739/10399363/06b478be-6e7c-11e5-9a26-7082d70fdc11.jpg)

![f_dmp_2](https://cloud.githubusercontent.com/assets/13649739/10399371/161aae7c-6e7c-11e5-936f-4670be4a5b2e.jpg)

Dame tu opinión para aplicar los cambios a todas las monedas de los logos por favor.

**Comment by Luis-Fernando-Molina** [comment]
todavia me parece que le falta algo

Quizas una textura a la parte en cobre? podes probar con algunas diferentes?

**Comment by jonathanborges3d** [comment]
@Luis-Fernando-Molina Ok, aquí hice algunas pruebas con diversos mapas de relieve:
![f_dmp_3](https://cloud.githubusercontent.com/assets/13649739/10402176/9da7e0d8-6e8d-11e5-8331-0e40b62776a8.jpg)

![f_dmp_4](https://cloud.githubusercontent.com/assets/13649739/10403078/1f13292a-6e93-11e5-88af-87b02d35fe29.jpg)

![f_dmp_5](https://cloud.githubusercontent.com/assets/13649739/10403130/62503318-6e93-11e5-917f-69bd85d4b385.jpg)

**Comment by Luis-Fernando-Molina** [comment]
ok, la ultima :+1:  y del otro lado como hacemos?

**Comment by jonathanborges3d** [comment]
@Luis-Fernando-Molina Había pensado que éste fuese el anverso de todas las monedas de éste tipo y por el reverso el de la plataforma o supercapa. ¿Qué te parece?

**Comment by Luis-Fernando-Molina** [comment]
Mostrame como quedaria del otro lado con el mismo patron, o quizas otra cosa.

**Comment by jonathanborges3d** [comment]
@Luis-Fernando-Molina Aquí está el logo de PIP en las tres versiones de la textura del cobre:

![f_pip_11](https://cloud.githubusercontent.com/assets/13649739/10407493/22ca3f5a-6eb5-11e5-893f-3b27da1c4963.jpg)

![f_pip_12](https://cloud.githubusercontent.com/assets/13649739/10407508/533d206c-6eb5-11e5-8435-730f63d968da.jpg)

![f_pip_13](https://cloud.githubusercontent.com/assets/13649739/10407545/5bc255b2-6eb6-11e5-8de9-897c936f65d6.jpg)

**Comment by Luis-Fernando-Molina** [comment]
ok lo dejemos tambien con el pattern de Fermat
:+1: 

Ya lo podes aplicar al resto de las monedas del mismo tipo.

**Comment by jonathanborges3d** [comment]
Actualización del render de la moneda para los covers de hangouts

![cover_pip](https://github-cloud.s3.amazonaws.com/assets/13649739/10566314/d3b33390-75ad-11e5-806a-7464c2ca4e4e.jpg)
