### ISSUE TITLE
Create a Image for Facebook Profile to Artist Platform

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#970]
Banner size 981x363 px

Profile size 180x180 px

Date Delivery 04-08-2016

**Comment by Jessicafp** [comment]
![banner facebook 2](https://cloud.githubusercontent.com/assets/19536846/17521414/431b2e84-5e21-11e6-8cba-cab6b04c5587.png)
![banner facebook](https://cloud.githubusercontent.com/assets/19536846/17521416/43d13580-5e21-11e6-83af-a50440288777.png)

**Comment by Jessicafp** [comment]
@arnaldos @jhonmarquez92

**Comment by arnaldos** [comment]
montala en un screen de face

**Comment by Jessicafp** [comment]
![face](https://cloud.githubusercontent.com/assets/19536846/17564792/b017c006-5f02-11e6-80df-5bc148974f18.png)

**Comment by proseuz** [comment]
Yo creo que esta será la foto de profile @Jessicafp  por ahora puedes aplicarla en todas
