### ISSUE TITLE
Create mockups to brokers website 

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#971]
This website is to attract brokers. example of the style you want to manage, interaction and usability.

http://demo.udthemes.com/encore/wordpress/app/

http://burst.mikado-themes.com/landing/

Contact to @robertggovias and @AdryCanonico to more info.  

First review of mockups 05-08-2016 6pm

**Comment by robertggovias** [comment]
Everyone can follow the development of this web pages, on this [document](https://docs.google.com/document/d/1OCS4XfyEm8ue2BEY_huLXT9mH-mmy10Aehzq21f4LC8/edit).

Also others collaborative platforms are available
[Contact form](https://docs.google.com/forms/d/1hMtJkP6m04Zfiq5-T88yIIrRI-IR0c38BNn7CIQrxnY/edit?usp=sharing)
![cryptobroker form - google forms](https://cloud.githubusercontent.com/assets/13140486/17457331/f6bd4622-5bc2-11e6-82a0-51a40edfb82a.jpg)

[Site map](https://cacoo.com/diagrams/lFRF83PpFfkCxai3/edit?sid=D7340)
![sitemaps 1](https://cloud.githubusercontent.com/assets/13140486/17457313/8bcc8148-5bc2-11e6-9e73-bb151ea4e2f8.png)

[Wireframe Mokcup](https://wireframe.cc/whJr7l)
![mockup](https://cloud.githubusercontent.com/assets/13140486/17457339/370762f8-5bc3-11e6-954c-d8b87c2cf084.jpg)

[Visual-Web elemental Mockup](https://ninjamock.com/s/626XD)
![screen](https://cloud.githubusercontent.com/assets/13140486/17457293/09efd7a6-5bc2-11e6-81b9-f574c7736ac0.jpg)

You can access and vote for your favourite
@lisamarmolina 
[Slides](https://docs.google.com/presentation/d/1T2EtKnEwPDD6Zt8JcvC5QL3wFlraDG-03PoyLx5a6OM/edit#slide=id.p)
![4 slides cryptobrokers net](https://cloud.githubusercontent.com/assets/13140486/17457637/dfec30a8-5bcb-11e6-8c65-3240e6def38b.png)
@rosanacoronado 
[Left  Nav Bar Icons](https://docs.google.com/presentation/d/1JABvQ-fQUb7jMLJJYnXwJ2IJyGazP0jorJx9ns5BEBo/edit#slide=id.p)
![iconos cryptobrokers net]
![iconos cryptobrokers net](https://cloud.githubusercontent.com/assets/13140486/17457600/a8b4008a-5bca-11e6-9995-7277dd8a2cf4.png)

[Colour palette](https://color.adobe.com/library/1c6c1b1a-715c-4e63-9aa4-fa51c7f7e171/theme/24411e13-1c39-440c-8eb6-24b3f48a0c61/)
![image](https://cloud.githubusercontent.com/assets/13140486/17457691/3d1bea7e-5bcd-11e6-9abc-af1a21d5e0ee.png)

[And this Folder in Google Drive](https://drive.google.com/folderview?id=0B84NnTtLDRPHdzIyMTdMcHMyZ3c&usp=sharing)
![image](https://cloud.githubusercontent.com/assets/13140486/17457693/4d35cb50-5bcd-11e6-87c9-495ad78e69ed.png)

**Comment by arnaldos** [comment]
según lo definido el día de hoy trabajaremos este concepto gráfico

![brokers](https://cloud.githubusercontent.com/assets/13594347/17503562/d40dfcfe-5dbe-11e6-8be8-4fec1d110df8.png)

**Comment by rosanacoronado** [comment]
nuevas propuestas segun lo que se ha definido, aplicando diagramación, iconos seleccionados y paleta de color

![all 4-2-04](https://cloud.githubusercontent.com/assets/19508456/17543528/3c86f606-5e9f-11e6-9f73-f3ad085019ec.png)

![all 3-03](https://cloud.githubusercontent.com/assets/19508456/17543544/5e2e97a0-5e9f-11e6-8a74-d88fdad91bd3.png)

![all 2-01](https://cloud.githubusercontent.com/assets/19508456/17543546/5f9b83b4-5e9f-11e6-9977-748eaa2fb59f.png)

![all 2-02](https://cloud.githubusercontent.com/assets/19508456/17543707/8b51f24e-5ea0-11e6-80bf-700dfe8f4e06.png)

**Comment by arnaldos** [comment]
@rosanacoronado @lisamarmolina 
- La ultima version me gusta solo oscureciera un poco el area del texto (un plano oscuro transparente), ya que por los colore de las imagene en algunos sitios se dificulta la lectura. 
  dejo un ejemplo no se si sea la forma mas idonea 
  Ejemplo : 
  ![imagen-1](https://cloud.githubusercontent.com/assets/13594347/17561283/533629e0-5ef3-11e6-8093-f28e81fc0d09.png)
- En el paso 5 la imagen tiene un telefono, aqui usaria un screen propiamente de la app.

**Comment by rosanacoronado** [comment]
nuevas propuestas incluyendo los slides del home y el navbar

Propuesta_ 1
![items-01](https://cloud.githubusercontent.com/assets/19508456/17582114/d7d39db6-5f77-11e6-9173-07eb00ce70f5.png)
![home all-01](https://cloud.githubusercontent.com/assets/19508456/17582115/d7d93712-5f77-11e6-9408-ce8c255a7cb2.png)

**Comment by arnaldos** [comment]
reduce un poco el tamaño del logo que esta en el header

**Comment by arnaldos** [comment]
@rosanacoronado prueba usar los colores de la broker en el header

**Comment by arnaldos** [comment]
coloca plz una de las imágenes pequeñas en grande plz para ver los detalles creo esa versión se ve mejor

**Comment by rosanacoronado** [comment]
Por ahora propuestas finales para el home y la pagina de pasos @arnaldos @robertggovias @lisamarmolina 
Home / Slides

![sb8-01](https://cloud.githubusercontent.com/assets/19508456/17610130/f7b5c726-6008-11e6-86e8-b921984e4be8.png)
![sb9-01](https://cloud.githubusercontent.com/assets/19508456/17610131/f7c1d322-6008-11e6-80f7-d96d977d122d.png)
![sb10-01](https://cloud.githubusercontent.com/assets/19508456/17610132/f7e1bc64-6008-11e6-97ed-b5cc67de935b.png)
![sb11-01](https://cloud.githubusercontent.com/assets/19508456/17610133/f7ec1ef2-6008-11e6-8143-9a193b10c141.png)

Pasos a seguir
![sb-01](https://cloud.githubusercontent.com/assets/19508456/17609931/4b29e722-6007-11e6-9405-7067a8dcdcb8.png)
![sb-02](https://cloud.githubusercontent.com/assets/19508456/17609932/4b38d6b0-6007-11e6-84ab-04b91cd1face.png)
![sb-03](https://cloud.githubusercontent.com/assets/19508456/17609933/4b4e22a4-6007-11e6-9522-f2e94446bca9.png)
![sb-04](https://cloud.githubusercontent.com/assets/19508456/17609934/4b6e11f4-6007-11e6-8ffc-ff0583cf42ef.png)
![sb-05](https://cloud.githubusercontent.com/assets/19508456/17609935/4b872ae0-6007-11e6-94a1-4f81b913c852.png)
![sb-06](https://cloud.githubusercontent.com/assets/19508456/17609936/4b929fba-6007-11e6-91ff-40f06fea7622.png)
![sb-07](https://cloud.githubusercontent.com/assets/19508456/17609937/4baf3f62-6007-11e6-9f39-6eed5cbadf70.png)

**Comment by robertggovias** [comment]
Excelente, se ve mucho más espacioso, el único desafío lo presenta el paso 4 por la falta de legibilidad en el Main Nav Bar, que se deriva de la falta de contraste entre la palabra home y el fondo oscuro del cabello en la foto, justo detrás del texto.

**Comment by rosanacoronado** [comment]
@robertggovias acá la corrección, haciendo la imagen un poco mas clara para que la palabra HOME pueda visualizarse

![2-02](https://cloud.githubusercontent.com/assets/19508456/17635319/a9462878-60a4-11e6-9e9e-9865ec5617ed.png)

**Comment by robertggovias** [comment]
Gracias @rosanacoronado, ahora, es posible, que alguien pueda leerlo.

**Comment by robertggovias** [comment]
#971 Después de haber definido el mockup, solo nos falta adaptarlo a la proporción de ancho y alto de un celular y también al de una tablet

**Comment by rosanacoronado** [comment]
@robertggovias @arnaldos Version 1.0 de la plataforma adaptado a un celular

![view2-01](https://cloud.githubusercontent.com/assets/19508456/17741623/e08eff16-646a-11e6-965d-03a9e720fa87.png)
![view3-01](https://cloud.githubusercontent.com/assets/19508456/17741625/e099c554-646a-11e6-9881-286cb479c25e.png)
![view4-01](https://cloud.githubusercontent.com/assets/19508456/17741626/e0a922ec-646a-11e6-8a28-f83cbaf91bc0.png)
![view5-01](https://cloud.githubusercontent.com/assets/19508456/17741627/e0b9aab8-646a-11e6-9794-57e6db3d2875.png)
![view6-01](https://cloud.githubusercontent.com/assets/19508456/17741629/e0d7cc28-646a-11e6-9991-16e105e69bf1.png)
![view8-01](https://cloud.githubusercontent.com/assets/19508456/17741628/e0d5066e-646a-11e6-977a-d0acbe1740de.png)
![view9-01](https://cloud.githubusercontent.com/assets/19508456/17741630/e1827542-646a-11e6-83b5-b791e6db4e2e.png)
![view10-01](https://cloud.githubusercontent.com/assets/19508456/17741631/e1891dde-646a-11e6-9c04-beb04b969ba8.png)
![view11-01](https://cloud.githubusercontent.com/assets/19508456/17741632/e19f7a48-646a-11e6-8bc9-405c55fdf38c.png)
![view12-01](https://cloud.githubusercontent.com/assets/19508456/17741633/e1ae7db8-646a-11e6-9373-017efa6bb61b.png)
![view13-01](https://cloud.githubusercontent.com/assets/19508456/17741634/e1c5c784-646a-11e6-9518-a3d0bab05c77.png)
![view1-01](https://cloud.githubusercontent.com/assets/19508456/17741635/e1d3fd0e-646a-11e6-8e5d-4c705a28f553.png)

**Comment by rosanacoronado** [comment]
@arnaldos @robertggovias Version 1.0 adaptado a una tablet - HOME

![tview1-01](https://cloud.githubusercontent.com/assets/19508456/17745220/090cdbda-6479-11e6-8457-2a9c4aad63b9.png)
![tview2-01](https://cloud.githubusercontent.com/assets/19508456/17744783/36715fb2-6477-11e6-8211-04c8775bfe90.png)
![tview3-01](https://cloud.githubusercontent.com/assets/19508456/17744784/36789a98-6477-11e6-869c-806752d0f0e0.png)
![tview4-01](https://cloud.githubusercontent.com/assets/19508456/17744785/3686a99e-6477-11e6-944d-62ea0cfa642d.png)

**Comment by rosanacoronado** [comment]
@arnaldos @robertggovias Version 1.0 para tablet - Pasos a seguir 

![tview8-01](https://cloud.githubusercontent.com/assets/19508456/17745363/8a03bfd8-6479-11e6-972f-b8e017529d35.png)
![tview9-01](https://cloud.githubusercontent.com/assets/19508456/17745364/8a0d49fe-6479-11e6-83bb-c67de658f5c0.png)
![tview10-01](https://cloud.githubusercontent.com/assets/19508456/17745365/8a263f68-6479-11e6-8a5d-420c531e84da.png)
![tview11-01](https://cloud.githubusercontent.com/assets/19508456/17745367/8a3ba4f2-6479-11e6-8da3-356194769143.png)
![tview12-01](https://cloud.githubusercontent.com/assets/19508456/17745368/8a42946a-6479-11e6-9404-b479c9bd4dfe.png)
![tview5-01](https://cloud.githubusercontent.com/assets/19508456/17745369/8a58ef94-6479-11e6-803b-feeb41938baa.png)
![tview6-01](https://cloud.githubusercontent.com/assets/19508456/17745371/8a6d25fe-6479-11e6-89f3-65bd394f8e0c.png)
![tview7-01](https://cloud.githubusercontent.com/assets/19508456/17745372/8a7bcd52-6479-11e6-812c-076167843bef.png)

**Comment by isahq23** [comment]
De acuerdo a permisos sobre uso de logos/iconos de redes sociales no están siendo utilizados de la forma adecuada, sé que nos guiamos por estética, pero también debemos respetar la imagen de empresas ajenas.

Acá dejo los links:
https://www.facebookbrand.com/
https://brand.twitter.com/es.html
https://www.youtube.com/yt/brand/downloads.html

**Comment by arnaldos** [comment]
@robertggovias @lisamarmolina @rosanacoronado  totalmente de acurdo con la recomendación dada por @isahq23 de revisen de que manera se pueden aplicar los logos de lar redes y respetar su uso establecido por cada uno de estas empresas descarguen el pack de iconos y úsenlos según la recomendación dada por cada una de ellas.

**Comment by robertggovias** [comment]
Ok, Gracias
