### ISSUE TITLE
Create a Corporate Branding

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#973]
It´s need 
- Business Card
- Corporate Folder
- Letterhead Sheet

Date Delivery 04-08-2016

**Comment by Magdy27** [comment]
![973---papeleria1](https://cloud.githubusercontent.com/assets/19651834/17447917/459fa6bc-5b1f-11e6-97e8-05575f022900.png)
![973---papeleria2](https://cloud.githubusercontent.com/assets/19651834/17447918/45c84e78-5b1f-11e6-8720-d4d3bf7cc7d4.png)
![973---papeleria3](https://cloud.githubusercontent.com/assets/19651834/17447919/45c8a508-5b1f-11e6-8e4c-c9f4ed98cf15.png)
@arnaldos

**Comment by m471c4** [comment]
@Magdy27 la business card es una tarjeta de presentación, no un identificador. Corrige eso por favor. Yo me iría por la primera versión, que usa la paleta de azules y líneas curvas que aportan dinamismo al diseño. Igual haz algunas propuestas más variando el estilo usado en estas 3 vresiones, que es muy similar.

Otra observación, trata en lo posible de no poner el logo sobre planos de color, pues el gris de Fermat se pierde (como pasa en tu última versión). Mantenlo sobre fondo blanco mientras sea posible.

**Comment by Magdy27** [comment]
![973---papeleria1](https://cloud.githubusercontent.com/assets/19651834/17452335/57964a48-5b3c-11e6-95a6-2fd2dd783918.png)
![973---papeleria2](https://cloud.githubusercontent.com/assets/19651834/17452336/57bd97a6-5b3c-11e6-9eac-4a3937827cbd.png)
@m471c4 @

**Comment by andiechan** [comment]
![papeleria_01-02](https://cloud.githubusercontent.com/assets/19866300/17488996/ea4286de-5d69-11e6-9d63-155c31120b88.jpg)

![papeleria_02](https://cloud.githubusercontent.com/assets/19866300/17490325/5fdd8bae-5d70-11e6-9d2d-89ee48765bad.jpg)

**Comment by arnaldos** [comment]
@Magdy27 @andiechan 

#### Carpeta

Version 1 de andrea intenta probar el logo en marca de agua como hiciste en la versión 2

#### Hoja membrete

Version 2 andrea solo que aquí usaría la versión del logo landscape
de encabezado  puedes conseguirlo en el Media kit
![fermat_logo_v2_horizontal_256x103](https://cloud.githubusercontent.com/assets/13594347/17503383/77911f0c-5dbd-11e6-8850-ab176934ae32.png)

#### Identificadores

la versión 1 de magdy pero revisa la tarjeta existente que esta en el repo y estandariza la con esa tarjeta

**Comment by Magdy27** [comment]
![973---bussines-card](https://cloud.githubusercontent.com/assets/19651834/17518601/94ae1212-5e16-11e6-8ac2-c8a79f996ab1.png)
![973---bussines-card2](https://cloud.githubusercontent.com/assets/19651834/17518602/9526ed40-5e16-11e6-9414-2cc2650c5895.png)
@arnaldos @m471c4

**Comment by andiechan** [comment]
-Carpeta:
![carpeta_ fermat-04](https://cloud.githubusercontent.com/assets/19866300/17523876/2cb0c650-5e2a-11e6-9811-f5d8a9546dbf.png)

-Hoja Carta:
![hoja carta_fermat-05](https://cloud.githubusercontent.com/assets/19866300/17523878/2df00f58-5e2a-11e6-8f71-384ab9065ce4.png)

**Comment by Magdy27** [comment]
![973---bussines-card](https://cloud.githubusercontent.com/assets/19651834/17554622/c2680618-5ed9-11e6-8817-ada521768c40.png)
@arnaldos @m471c4
