### ISSUE TITLE
New Icons for Internet of People

### ISSUE THREAD

**Issue by acostarodrigo** [bitDubai/fermat-graphic-design#976]
# Icon replacement for Internet of People:

For the new Internet of People blockchain I need to replace the files attached below,
They need to maintain the same:
- size
- resolution
- extension

but instead of Bitcoin, it must reference Internet of People

![about](https://cloud.githubusercontent.com/assets/9518556/17531787/d373d490-5e53-11e6-93d7-426635c4adad.png)

![fermat](https://cloud.githubusercontent.com/assets/9518556/17531785/d3546434-5e53-11e6-979f-55cef9f76939.png)

@arnaldos some other files I need to replace are not supported to be uploaded here. Contact me and I will pass them on Slack.

Ask @Luis-Fernando-Molina if you have doubts on what the IoP icon should be.

**Comment by Luis-Fernando-Molina** [comment]
I sent it by email.

**Comment by acostarodrigo** [comment]
@arnaldos please complete the request ASAP. attached are the IoP reference images.
Let me know if you have doubts. 

![internet_of_people_logo_500x500](https://cloud.githubusercontent.com/assets/9518556/17607470/514df414-5ffc-11e6-9dd0-a1225d544894.png)
![internet_of_people_logo_500x500_sin_texto](https://cloud.githubusercontent.com/assets/9518556/17607471/51709906-5ffc-11e6-8106-44939df07bb8.png)
![internet_of_people_logo_1280x1280](https://cloud.githubusercontent.com/assets/9518556/17607472/51894834-5ffc-11e6-8069-313d92dd5e1f.png)

**Comment by acostarodrigo** [comment]
I need:
- an icon of 48x48 with just the logo
- the same icon as before but with a different background color
- a .png file of 256x256 with the logo and the Internet of People text
- the same .png but with a different background color 
- a .png file that will be used as a splash image with a partial view of the logo and the text in 480 x 320
- the same image as before but with a different background color
- the logo in a .svg file of 1024 x 1024

**Comment by acostarodrigo** [comment]
@arnaldos any update on this?

**Comment by arnaldos** [comment]
@acostarodrigo I send you to slack
