### ISSUE TITLE
DAP_community_asset_issuer

### ISSUE THREAD

**Issue by ivonnesantos** [bitDubai/fermat-graphic-design#977]

**Comment by ivonnesantos** [comment]
![community-08](https://cloud.githubusercontent.com/assets/15238660/17576516/ba80e2d6-5f41-11e6-9f03-8ed7b1ec52c3.png)
@nindriago @arnaldos tengo algunas dudas el la lista de "connetions" aparecen las personas que ya estan agregadas? y los estatus que representan? yo lo hice algo asi como ausente, conectado pero no lo tengo claro.

**Comment by arnaldos** [comment]
@ivonnesantos en conections solo las personas que  contactos, los estatus un es para indicar que la solicitud ha sido enviada y el otro cuando ya fue aceptada la solicitud pero ese estatus se mostrara en el browser ... no en conections ya que los que aparecen en el listado son las pensonas con las que tienes coneccion

**Comment by ivonnesantos** [comment]
Ok pero si se coloca un estatus en browser de solicitud enviada y en espera el boton de agregar deberia eliminarse o suatituirse por dicho estatus o me equivocó? @arnaldos

**Comment by ivonnesantos** [comment]
@arnaldos 
![community-08](https://cloud.githubusercontent.com/assets/15238660/17638072/b60198ca-60b5-11e6-98e2-2daf6f924a45.png)

**Comment by ivonnesantos** [comment]
Recursos parasados a @javafrank
