### ISSUE TITLE
Revisar Paletas de colores para estandarizar en los logos de Fermat.org 

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#98]
Revisaremos la paleta de colores de los logos que se están trabajando para Fermat.org y de esta manera estandarizar los colores.

**Comment by arnaldos** [comment]
Paleta de color A

![fermat_pip_paleta_1](https://cloud.githubusercontent.com/assets/13594347/9744668/0b189f32-5637-11e5-8625-fbd88343a228.png)

Paleta de color B

![fermat_pip_paleta_2](https://cloud.githubusercontent.com/assets/13594347/9744693/2579d350-5637-11e5-9820-0fe2347275c9.png)

**Comment by Luis-Fernando-Molina** [comment]
Opción B

**Comment by arnaldos** [comment]
ok perfecto !!! ya subo al repo !!

**Comment by m471c4** [comment]
@Luis-Fernando-Molina, @arnaldos ya están todos los logos en los que yo trabajé actualizados y con la paleta de colores nueva en el repositorio. En sus versiones .ai y .svg.
