### ISSUE TITLE
Create 2  Wallpapers to Fermat 

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#980]
### Wallpapers

1- Bright and light background with fermat logo 
2- Darker with fermat logo in dark backgrund

Size qhd (960x540) and fullhd (1920x1080)

Delivery Date Today 3:30 pm

**Comment by rennyx7** [comment]
here we go 

![brightandlight_960x540](https://cloud.githubusercontent.com/assets/20045567/17865409/77bfb1d8-6870-11e6-8598-8ea95017f6a7.jpg)
![brightandlight_1920x1080](https://cloud.githubusercontent.com/assets/20045567/17865410/77cbddaa-6870-11e6-9f30-31b2a783c15d.jpg)
![dark_1920x1080](https://cloud.githubusercontent.com/assets/20045567/17865412/77cef6d4-6870-11e6-8af7-d05205626b58.jpg)
![dark_960x540](https://cloud.githubusercontent.com/assets/20045567/17865411/77ccd156-6870-11e6-834e-8446e10ab8d6.jpg)

**Comment by rosanacoronado** [comment]
@arnaldos @rennyx7 working with graphic elements in the background. What do you think guys?

 Proposal_1
![1-01](https://cloud.githubusercontent.com/assets/19508456/17866950/7ac86824-6876-11e6-8bbf-5caf80dd90e9.png)
![2-01](https://cloud.githubusercontent.com/assets/19508456/17866939/79f39ef0-6876-11e6-8148-5fb4f84fbc1a.png)
![3-01](https://cloud.githubusercontent.com/assets/19508456/17866940/7a05efc4-6876-11e6-9fcc-c5b4abf7bab3.png)
![4-01](https://cloud.githubusercontent.com/assets/19508456/17866941/7a1530ba-6876-11e6-99ee-298ee618e45f.png)

Proposal_2
![5-01](https://cloud.githubusercontent.com/assets/19508456/17866942/7a2a7484-6876-11e6-814d-eba34b9c5712.png)
![6-01](https://cloud.githubusercontent.com/assets/19508456/17866943/7a4af4a2-6876-11e6-9e0b-1855b0e3ef92.png)
![7-01](https://cloud.githubusercontent.com/assets/19508456/17866944/7a4ee652-6876-11e6-8c9d-615e42beaedb.png)
![8-01](https://cloud.githubusercontent.com/assets/19508456/17866945/7a5afd52-6876-11e6-88ae-dd4b9a511625.png)

Proposal_3
![9-01](https://cloud.githubusercontent.com/assets/19508456/17866946/7a733746-6876-11e6-9e45-db3515b1a522.png)
![10-01](https://cloud.githubusercontent.com/assets/19508456/17866947/7a8834de-6876-11e6-9e6a-42e28f02fb04.png)
![11-01](https://cloud.githubusercontent.com/assets/19508456/17866948/7aa708be-6876-11e6-8314-6d9c620e8040.png)
![12-01](https://cloud.githubusercontent.com/assets/19508456/17866949/7ab18848-6876-11e6-8536-d9db1c051db9.png)

**Comment by arnaldos** [comment]
@rosanacoronado @rennyx7 
- Text Missing Logo
- The way of the latest versions
- Increase the resolution to not pixelate
- Use some more texture to prove

**Comment by rosanacoronado** [comment]
@arnaldos

Proposal_1
![1-01](https://cloud.githubusercontent.com/assets/19508456/17870521/e19c5b1e-6885-11e6-926b-14edf7d25c76.png)
![2-01](https://cloud.githubusercontent.com/assets/19508456/17870522/e1a57410-6885-11e6-9a37-97ae8f615650.png)
![3-01](https://cloud.githubusercontent.com/assets/19508456/17870523/e1b42118-6885-11e6-97be-9d57a93a2747.png)
![4-01](https://cloud.githubusercontent.com/assets/19508456/17870524/e1c9b0e6-6885-11e6-8092-d848b6e1f9eb.png)

Proposal_2
![5-01](https://cloud.githubusercontent.com/assets/19508456/17870525/e1d950fa-6885-11e6-961b-7af84606af04.png)
![6-01](https://cloud.githubusercontent.com/assets/19508456/17870527/e1f48f82-6885-11e6-8640-c9ca42403f89.png)
![7-01](https://cloud.githubusercontent.com/assets/19508456/17870528/e201e3f8-6885-11e6-9bec-47be2faa450c.png)
![8-01](https://cloud.githubusercontent.com/assets/19508456/17870529/e21be38e-6885-11e6-8ef7-618968c2adb3.png)

**Comment by arnaldos** [comment]
los colores se ven pixelados cuanto tienen de resolución

**Comment by rennyx7** [comment]
Los mios?

**Comment by rennyx7** [comment]
![dark2_960x540](https://cloud.githubusercontent.com/assets/20045567/17873960/847d5be8-6896-11e6-8ba6-991d95fa7bf4.jpg)
![brightandlight2_960x540](https://cloud.githubusercontent.com/assets/20045567/17873961/848df2be-6896-11e6-9bb1-40bdc9edece1.jpg)
![brightandlight2_1920x1080](https://cloud.githubusercontent.com/assets/20045567/17873962/84b0ec60-6896-11e6-8b4d-ec5603c368f8.jpg)

**Comment by arnaldos** [comment]
Ya envié esto para aprobación estamos esperando respuesta
