### ISSUE TITLE
Crear imagen general para representar el IOP

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#985]
Tamaño: 1920x1080 px

Ejemplo:
Generar una imagen con foto real que incluya personas reales y una ciudad donde se vea una red en el aire como en la nube (serían círculos de colores que representan los nodos). Se debe mostrar que el operador de los nodos pueda correr en cualquiera de esto 5 nodos y algunos que corra en los 5 nodos. Puede ser una línea vertical que salga de una casa o edificio y se conecte con alguno de los nodos pelotitas arribas de colores distintos para representar que se están corriendo distintos nodos.

**Comment by arnaldos** [comment]
### Version 1

![image-1](https://cloud.githubusercontent.com/assets/13594347/18588565/062f135e-7bf5-11e6-896d-1046d9e10eaa.jpg)

**Comment by victoralfonzohd** [comment]
@arnaldos 

Aqui va mi primera propuesta! 

![sin-titulo-1](https://cloud.githubusercontent.com/assets/15219855/18598301/1b7a061c-7c20-11e6-9d35-041f3cfeceb7.jpg)

**Comment by Luis-Fernando-Molina** [comment]
Va bien pero no se representa el enunciado de manera completa

**Comment by victoralfonzohd** [comment]
Comparto otra Version

@arnaldos @Luis-Fernando-Molina 

![imageniop2](https://cloud.githubusercontent.com/assets/15219855/18609725/6042bb6a-7cd7-11e6-8cc0-3e8061f085b7.jpg)

**Comment by arnaldos** [comment]
@magdy donde esta tu propuesta ??

**Comment by arnaldos** [comment]
### Version 4

![image-3](https://cloud.githubusercontent.com/assets/13594347/18621128/0953f474-7ded-11e6-80f1-085e52131526.jpg)

**Comment by arnaldos** [comment]
### Version 5

![image-3 1](https://cloud.githubusercontent.com/assets/13594347/18621284/e639dcea-7dee-11e6-8118-ae31269f85a0.jpg)

**Comment by Luis-Fernando-Molina** [comment]
La versión 5 tiene los mejores nodos. Le falta la inicial de cada nodo. B, H, P, R, M.  

Ahora, en la versión 5 no está bien representado el enunciado,  porque no  esta la conexión con las casas como dije sino con gente.

**Comment by arnaldos** [comment]
Entiendo lo que dices pero lo que nos ha frenado ha sido conseguir la foto que tenga todo y muchas veces al hacer el foto montaje no quedan bien los elementos ya que hacer la composición aveces tiene iluminación distinta. aun sigo trabajando en ello para obtener el resultado.

**Comment by arnaldos** [comment]
### Version 6

## ![image-4](https://cloud.githubusercontent.com/assets/13594347/18658926/e56b8138-7ed4-11e6-9188-0393fb0bb8c7.jpg)

### Version 7

![image-4 1](https://cloud.githubusercontent.com/assets/13594347/18658929/ea280fc0-7ed4-11e6-8f96-f1473c9c3b00.jpg)

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina

**Comment by Magdy27** [comment]
![nodos 2](https://cloud.githubusercontent.com/assets/19651834/18673184/d8196ac4-7f18-11e6-9e9c-9e51af327928.jpg)

@arnaldos @Luis-Fernando-Molina

**Comment by victoralfonzohd** [comment]
Version 3

![imageniop2](https://cloud.githubusercontent.com/assets/15219855/18687847/e5ec0738-7f4f-11e6-8150-c28a492953c1.jpg)

**Comment by arnaldos** [comment]
### Version 10

![image-5](https://cloud.githubusercontent.com/assets/13594347/18692514/c87daf3a-7f68-11e6-9a14-4d2cbf21decd.jpg)

**Comment by victoralfonzohd** [comment]
@arnaldos @Luis-Fernando-Molina 

# ### Version 5

### 

Version 5.1

![iopv6](https://cloud.githubusercontent.com/assets/15219855/18693868/464271bc-7f73-11e6-8252-fd75e9b48447.jpg)

### Version 5.2

![iopv5](https://cloud.githubusercontent.com/assets/15219855/18693540/6975dda2-7f70-11e6-89ff-20093af036c8.jpg)

### Version 5.3

![imageniop7](https://cloud.githubusercontent.com/assets/15219855/18694357/4bfe7cb4-7f77-11e6-8bd6-0a2f847b31f5.jpg)

**Comment by Luis-Fernando-Molina** [comment]
Arreglen la versión 10 de Arnaldo y 5.3 de victor

Sigue el problema que representan la conexión entre nodos igual a la conexión entre App y nodo y no debe ser. Ver mis comentarios en otros casos.

**Comment by Luis-Fernando-Molina** [comment]
Victor a su columnas de nodos debiera ponerle la misma perspectiva de los edificios para que quede bien.  

Esta poniendo conexiones a personas que no es la idea de gráficas en esta imagen. 

No se ven las distintas conexiones entre nodos de las distintas redes que te explique ayer Arnaldo.

**Comment by victoralfonzohd** [comment]
Mejoras Version 5.3

![imageniop8](https://cloud.githubusercontent.com/assets/15219855/18720095/3de5de3e-7ff8-11e6-8aa3-f7891292c258.jpg)

Version 5.4 

![imageniop8](https://cloud.githubusercontent.com/assets/15219855/18727384/57329b8e-8016-11e6-8044-015cafbd3d7f.jpg)

**Comment by arnaldos** [comment]
Ajustes a a version 10

### Version 13

En esta versión incluí la conexión entre usuarios dentro de la imagen con algunos señaladores de los usuarios.

![image-5 1](https://cloud.githubusercontent.com/assets/13594347/18733695/40f24930-803b-11e6-9bc0-2f1825fec649.jpg)

### Verison 14

Ajustes solicitados sin usuarios

![image-5 2](https://cloud.githubusercontent.com/assets/13594347/18733694/40eefac8-803b-11e6-8c0f-270bc666e897.jpg)

**Comment by Luis-Fernando-Molina** [comment]
El estilo grafico va por el lado de la version 5.4, pero la foto no me convence. 

El concepto de las redes esta mejor representado por la version 14.

Busquen imagenes de dia.

**Comment by victoralfonzohd** [comment]
Propuesta 6:

![imageniop10](https://cloud.githubusercontent.com/assets/15219855/18767158/9cde8c80-80eb-11e6-8b27-59d72e2e5cb9.jpg)

**Comment by arnaldos** [comment]
victor para la imagen de este caso pon las lineas mas delgadas y has que peguen de nodo a nodo, y si el color del nodo es naranja le linea de conexion debe ser naranja no de otro color

**Comment by victoralfonzohd** [comment]
### Propuesta 6.1: Cambios

![imageniop10](https://cloud.githubusercontent.com/assets/15219855/18769037/ad95d55e-80f7-11e6-8205-d71a76015677.jpg)

### Propuesta 7:

![imageniop7](https://cloud.githubusercontent.com/assets/15219855/18769001/6018c516-80f7-11e6-9ac1-8ea3fcfbf61e.jpg)

**Comment by arnaldos** [comment]
@victoralfonzohd para la propuesta 7 es muy oscura y rojiza busca una imagen mas clara como se solicita en los comentarios de arriba.

**Comment by arnaldos** [comment]
### Version 18

![image-5 3](https://cloud.githubusercontent.com/assets/13594347/18776517/b865c512-8137-11e6-82b1-bab4d1a7fae8.jpg)

**Comment by Luis-Fernando-Molina** [comment]
La 7 y 18 estan mas o menos bien. Faltaria que los haces de las conexiones pasaran por dentras de los edificios, o que los esquiven si pasan por delante. Se sigue viendo como que esta superpuesto, no hay integración.

**Comment by arnaldos** [comment]
Ok ya generamos los cambios !!

**Comment by arnaldos** [comment]
### Version 19

![image-5 4](https://cloud.githubusercontent.com/assets/13594347/18805340/cfe47570-81d8-11e6-9639-c89ef779aa85.jpg)

**Comment by Luis-Fernando-Molina** [comment]
No logro que me entiendan el concepto de que debe verse como Augmented Reality, donde los haces de luces deben esquivar los edificios y algunas torres de nodos o parte de ellas deben estar por detras y no siempre por delante. 

Por otro lado el estilo grafico de las conexiones entre nodos se ve bastante diferente entre Victor y Arnaldo. Cual es el estadard?

**Comment by Luis-Fernando-Molina** [comment]
AHora veo que los pusiste por atras pero los hiciste rectos. No habia que cambiar el estilo.

**Comment by arnaldos** [comment]
### Version 20

ya genere los ajustes manteniendo el estilo de las lineas anterior

![image-5 5](https://cloud.githubusercontent.com/assets/13594347/18857847/3941b6dc-8435-11e6-81cf-2ff6da409b54.jpg)

**Comment by Luis-Fernando-Molina** [comment]
NO estas teniendo en cuenta mi comentario anterior. Ya no se como explicartelo.

**Comment by victoralfonzohd** [comment]
Corrección en la propuesta 20 hecha por @arnaldos , las lineas estan mas integradas a la ciudad, al superponerse con los edificios en su trayectoria de conexion, creo que esto es lo que @Luis-Fernando-Molina pide en su comentario anterior. 

![image-5](https://cloud.githubusercontent.com/assets/15219855/18887035/823d56ee-84c0-11e6-83bc-c45018f41fb9.jpg)

**Comment by Luis-Fernando-Molina** [comment]
si bravo Victor! al fin alguien lo entendio! Listo este caso.

**Comment by arnaldos** [comment]
ya lo subo al media kit
