### ISSUE TITLE
Crear imagen general para representar conexión de los nodos del IOP

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#986]
Tamaño: 1920x1080 px

Ejemplo:

Imagen de una ciudad que muestre a las pelotitas o nodos conectados entre sí, los nodos de un color conectados con los del mismo color formando una red. Y las otras se conectan como redes separadas.

**Comment by arnaldos** [comment]
que ha pasado con la imagen ?

**Comment by solemiliia** [comment]
1 ![imageniop](https://cloud.githubusercontent.com/assets/19818549/18646648/7cf8b502-7e80-11e6-90e9-f0f6ffca0af2.jpg)

**Comment by solemiliia** [comment]
2 ![imagen iop2](https://cloud.githubusercontent.com/assets/19818549/18647807/cf3e36ac-7e85-11e6-9d54-210430dcfbfe.jpg)

**Comment by m471c4** [comment]
![city](https://cloud.githubusercontent.com/assets/13468350/18650029/ddde9fe8-7e90-11e6-85df-caf396f3dbdc.png)

**Comment by arnaldos** [comment]
las esferas parecen van por un lado y la foto por otra, integren los elementos con la foto, busquen fotos de ciudades que tengan profundidad para que les permita ajustar los elementos de acuerdo a la perspectiva.

**Comment by ivonnesantos** [comment]
@m471c4 Las lineas tampoco ayudan porque estan rectas y eso le quita perpectiva se supone que si hay perpectiva las lineas deben empezar mas ancha en lo nodos que estan mas cerca y mas angosta en los nodos lejos independientemente que sean rectas o curvas, tambien el orden de los nodos hay que corregirlo como dijo luis todos deben tener la misma distancia al suelo te estas guiando por la altura de los edificios pero no tomas en cuenta la distancia y que todos los edificios son de distinta altura busca una rejilla o algo creo que ilustrator tiene una vista de perspectiva donde puedes armar una rejilla de guia ya que tu imagen es dificil de trabajar porque los edificios no te ayudan con la guia. @arnaldos por ahi lei en un comentario que debemos trabajar las conexiones igual si es cierto pero tenemos que definirlo primero todo lo estamos haciendo distinto porque estamo trabajando todos a la vez de igual forma paso con los nodos al final una sola persona trabajo el nodo y nosotros lo tomamos cuando estuvo definido pasa lo mismo con las conexiones pero para subir las propuestas tenemos que conectarlo provisionalmente con las conexiones que a cada uno se le ocurra.

**Comment by solemiliia** [comment]
1 aquí deje los nodos conectados unos con otros 
![imagen iop 3](https://cloud.githubusercontent.com/assets/19818549/18688938/8a0ca486-7f54-11e6-86e4-1c6780555039.jpg)

2 aquí use los nodos como redes separadas como dice el enunciado 
![imagen iop 3-1](https://cloud.githubusercontent.com/assets/19818549/18689027/0a0fdac2-7f55-11e6-8967-0f5b36eb9e09.jpg)

**Comment by m471c4** [comment]
@arnaldos ¿qué tal así? Hay una perspectiva que aun se ve rara para mi, pero te lo dejo acá:

![imagenweb2](https://cloud.githubusercontent.com/assets/13468350/18697156/9fc98810-7f8c-11e6-820a-4cbe8bee3874.png)

**Comment by solemiliia** [comment]
3
![iop33](https://cloud.githubusercontent.com/assets/19818549/18698938/e40c8e14-7f9b-11e6-97f6-7031da3f52f8.jpg)

**Comment by m471c4** [comment]
@arnaldos acá la versión con los nuevos nodos alargados:

![city_new2](https://cloud.githubusercontent.com/assets/13468350/18700386/f8da0228-7fa4-11e6-8257-a9285201e1ec.png)

**Comment by m471c4** [comment]
@Luis-Fernando-Molina cuando puedas por favor revisa este caso.

**Comment by m471c4** [comment]
@arnaldos @Luis-Fernando-Molina con las líneas de los colores que corresponde:

![city_new3](https://cloud.githubusercontent.com/assets/13468350/18733572/19803bce-803a-11e6-8c50-d0763ed37c0c.png)

**Comment by solemiliia** [comment]
4 
![iop-4](https://cloud.githubusercontent.com/assets/19818549/18737093/897f6898-805b-11e6-91e8-e56bed5bdc28.jpg)

**Comment by m471c4** [comment]
@arnaldos @Luis-Fernando-Molina otra versión más:

![city_new4](https://cloud.githubusercontent.com/assets/13468350/18738038/d7c7c82e-8065-11e6-9094-a55fa9ed345c.png)

**Comment by Luis-Fernando-Molina** [comment]
Aca ninguna foto se acerca a lo que se busca. Se ven todas muy irreales.

Los nodos tienen que parecer torres, o antenas de celulares pero mucho mas altas que los edificios, tienen que respetar la perspectiva. Debe verse como si fuera la pantalla capturada de un programa de realidad aumentada, no un dibujo sobre una foto.

Eso es valido para las conexiones entre los nodos que deben pasar por detras de los obstaculos.

**Comment by solemiliia** [comment]
5 ![iop 5](https://cloud.githubusercontent.com/assets/19818549/18772680/03cd3e52-8117-11e6-9a05-b565a1f102d9.jpg)

**Comment by arnaldos** [comment]
@solemiliia 

La foto no me parece mal pero veo varias cosas a tomar en cuenta:
- La perspectiva de los nodos respecto a la imagen.
- Nodos estirados
- Nodos muy grandes rompen la armonía de la foto 
- Mayor transparencia al punto blanco base del modulo de nodos esto es con la intención de que no tape la ventana

**Comment by andiechan** [comment]
Dejo otra versión por acá, estaba pensando anexarle algunos iconos de las apps acorde a la conexión de cada nodo pero no creo que aplique en este caso.  

![conexion_iop_01](https://cloud.githubusercontent.com/assets/19866300/18774511/e77919d6-8127-11e6-9006-dbfce66959ab.jpg)

**Comment by solemiliia** [comment]
@arnaldos  corrección de la 5 
![iop51](https://cloud.githubusercontent.com/assets/19818549/18788678/d3ced01c-8175-11e6-92ef-367efb19fed3.jpg)
