### ISSUE TITLE
Crear imagen que represente el Home Node para IOP

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#987]
Tamaño: 1920x1080 px

Home Node (cada persona tiene varios perfiles pero cada perfil tiene un home node) es el nodo más cercano de donde la persona más reside o vive.

Conexión de las personas a su home node, no necesariamente al lugar más cercano al que está. Sino en el área donde se encuentra su zona. Ejemplo la persona está en la ciudad y el home node se ubica en su residencia.

**Comment by lisamarmolina** [comment]
Propuesta 1
![1](https://cloud.githubusercontent.com/assets/19942022/18603267/08bbba70-7c3e-11e6-9551-34243ddca1c5.png)
@arnaldos

**Comment by proseuz** [comment]
Propuesta 2
![home node-04](https://cloud.githubusercontent.com/assets/17308060/18605359/f89ba414-7c5d-11e6-9d47-749433bec6a5.jpg)
@arnaldos

**Comment by lisamarmolina** [comment]
Propuesta 3 
![2](https://cloud.githubusercontent.com/assets/19942022/18611604/76fc3478-7d0c-11e6-8416-417ac1b3520b.png)
@arnaldos

**Comment by arnaldos** [comment]
va mas por la propuesta de @jhonmarquez92 porque muestra las calles y trayectoria de los nodos ... pero tambien deb mostrar al usuario y de cierta manera hacer referencia al home node

**Comment by proseuz** [comment]
Propuesta 4
![home node2-02](https://cloud.githubusercontent.com/assets/17308060/18644281/c0ce8dec-7e76-11e6-9947-de22e17444a4.jpg)
Propuesta 5
![home node2-01](https://cloud.githubusercontent.com/assets/17308060/18644282/c19496c2-7e76-11e6-9bf3-04e3c29f1cfa.jpg)
@Luis-Fernando-Molina  @arnaldos

**Comment by arnaldos** [comment]
@jhonmarquez92   aparte de la imagen pudises incluir una especie de radar tal como lo unas en GTA te dejo ejemplo.  de esta manera creo que se puede contar la historia del home node. aun falta ver que el usuario esta lejos de su zona y el home node. http://vignette2.wikia.nocookie.net/gtawiki/images/b/bc/Radar-GTA4-wanted.png/revision/latest?cb=20100204183515

**Comment by proseuz** [comment]
Propuesta 6
![hnp-04](https://cloud.githubusercontent.com/assets/17308060/18657844/0bab7c8a-7ecc-11e6-89ab-7a2c705d4ac2.jpg)
Propuesta 7
![hnp-01](https://cloud.githubusercontent.com/assets/17308060/18657845/0babce56-7ecc-11e6-8177-9f839ec90f91.jpg)
Propuesta 8
![hnp-02](https://cloud.githubusercontent.com/assets/17308060/18657846/0c0a34d2-7ecc-11e6-9ba4-95a54bda204e.jpg)
@arnaldos @Luis-Fernando-Molina

**Comment by lisamarmolina** [comment]
Propuesta 9
![homenodepicture](https://cloud.githubusercontent.com/assets/19942022/18658527/dd65d400-7ed1-11e6-9392-84cda046abe8.png)

De igual forma dejo la imagen que se encuentra en la tablet:
![gpsnode](https://cloud.githubusercontent.com/assets/19942022/18658612/95e88d60-7ed2-11e6-9e2e-e270250c7127.png)

@Luis-Fernando-Molina @arnaldos

**Comment by lisamarmolina** [comment]
Propuesta 10
![10](https://cloud.githubusercontent.com/assets/19942022/18695455/e6f66b8e-7f7f-11e6-8927-e0ae80ce123c.png)

10.1
![10_1](https://cloud.githubusercontent.com/assets/19942022/18697448/42a47764-7f8f-11e6-9d6a-e40b69291ff9.png)

Sigo trabajando en otras propuestas, pero esta es la que está lista por el momento.
@arnaldos @Luis-Fernando-Molina

**Comment by proseuz** [comment]
Propuesta 11
![hnp-04-01](https://cloud.githubusercontent.com/assets/17308060/18696142/be61880c-7f84-11e6-9033-acdbe304db99.jpg)
Propuesta 12
![hnp-04-02](https://cloud.githubusercontent.com/assets/17308060/18696143/bea30804-7f84-11e6-9c2c-63eb78220b51.jpg)

**Comment by proseuz** [comment]
Propuesta 13
![hnp-04-02-02](https://cloud.githubusercontent.com/assets/17308060/18696459/54bd172e-7f87-11e6-838f-af0e8ba525c8.jpg)

**Comment by arnaldos** [comment]
conceptualmente va por la propuesta la propuesta 12 no se que opines @Luis-Fernando-Molina ?

@jhonmarquez92 cambia en el mapa el indicador del usuario debería ser diferente del nodo.

**Comment by proseuz** [comment]
Propuesta 14
![hnp-04-02-05](https://cloud.githubusercontent.com/assets/17308060/18698855/6fbbe83e-7f9b-11e6-8e7e-5140f1a597ef.jpg)
@arnaldos @Luis-Fernando-Molina

**Comment by Luis-Fernando-Molina** [comment]
Conceptualmente esta mejor la 11, donde un grupo de gente cada una esta conectada a su Home node que so  diferentes entre sí porque viven en diferentes lugares. 

Ver comentarios en otros casos para arreglar todo.

**Comment by proseuz** [comment]
Propuesta_15
![hnp-04-02-01](https://cloud.githubusercontent.com/assets/17308060/18727486/d62c05b0-8016-11e6-85f0-d3515bb49319.jpg)
@Luis-Fernando-Molina @arnaldos

**Comment by proseuz** [comment]
Propuesta 15, con las modificaciones sugeridas @arnaldos 
![1-01-01](https://cloud.githubusercontent.com/assets/17308060/18773161/8bc83d54-811a-11e6-8cc5-9b97501570cd.jpg)

**Comment by arnaldos** [comment]
@jhonmarquez92 perfecto !! esperemos los comentarios de luis pero yo creo ya esta esta lista !

**Comment by Luis-Fernando-Molina** [comment]
La curvatura de las lineas que une a la gente con los nodos ignora completamente los obstaculos en la foto. Debiera esquivar los edificios. Los nodos debieran tener alguno de los otros nodos tambien, es raro que solo haya home nodes.

**Comment by proseuz** [comment]
![1-01-01-01](https://cloud.githubusercontent.com/assets/17308060/18796873/37f2a17c-8199-11e6-8e03-d97dbe752fcd.jpg)  @Luis-Fernando-Molina

**Comment by proseuz** [comment]
![1-01-01-01-01](https://cloud.githubusercontent.com/assets/17308060/18797332/8033b988-819b-11e6-8392-388496c80cdf.jpg) @arnaldos @Luis-Fernando-Molina

**Comment by Luis-Fernando-Molina** [comment]
Hace por favor que la persona del medio, el haz pase por dentras de los 2 edificios que ahora pasa por el frente, y poniendo la curva mas pronunciada.

**Comment by proseuz** [comment]
**15.3**
En esta primera prueba el haz que sale desde el personaje del centro pasa por detrás de los 2 edificios
![1-01-01-01-01-01-01](https://cloud.githubusercontent.com/assets/17308060/18854123/39601e88-8417-11e6-9dbb-cd313e9b47b7.jpg)
**15.4**
En esta versión el haz solo pasa por detrás de un edificio
![1-01-01-01-01-01](https://cloud.githubusercontent.com/assets/17308060/18854124/39a3b242-8417-11e6-8cfd-9dc5b0a0dec4.jpg)
@arnaldos @Luis-Fernando-Molina

**Comment by Luis-Fernando-Molina** [comment]
Esta mal. Debe pasar por detras de 2 edificios no de uno. Los edificios son el de 15.4 y el de la izquierda de ese.

**Comment by proseuz** [comment]
15.5
@Luis-Fernando-Molina 
![1-01-01-01-01-01-01-01](https://cloud.githubusercontent.com/assets/17308060/18879523/9848f5c4-84a2-11e6-819d-51a59d462414.jpg)

**Comment by Luis-Fernando-Molina** [comment]
Ok, listo caso cerrado.
