### ISSUE TITLE
Diseñar la identidad para la Bitcoin Wallet 

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#99]
1- Crear icono para la Bitcoin Wallet .
2- Crear Banner de presentación para la Bitcoin Wallet.

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina te comparto una serie nueva de versiones de Sreenshot para que visualices el conjunto de los elementos 
![sreenshot-bitcoin-wallet6](https://cloud.githubusercontent.com/assets/13594347/10037802/f931d852-6184-11e5-8737-318fdea1b149.png)
![sreenshot-bitcoin-wallet7](https://cloud.githubusercontent.com/assets/13594347/10037803/f936d1c2-6184-11e5-8a4d-aa395d300236.png)
![sreenshot-bitcoin-wallet8](https://cloud.githubusercontent.com/assets/13594347/10037804/f9392bca-6184-11e5-98d5-3160a567430e.png)
![sreenshot-bitcoin-wallet9](https://cloud.githubusercontent.com/assets/13594347/10037805/f9412c12-6184-11e5-8d26-274a2345a5ca.png)

**Comment by Luis-Fernando-Molina** [comment]
@arnaldos perfecto, como te imaginaras nos vamos con la 3ra. Por favor ponete en contacto con @furszy y @Neoperol a ver si le podes ir aplicando el estilo este a las imágenes que se están definiendo para la Bitcoin Wallet.

**Comment by arnaldos** [comment]
@Luis-Fernando-Molina perfecto !! ya me pongo en contacto con ellos !!
