### ISSUE TITLE
Crear imagenes representar la Interoperabilidad de IOP

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#991]
Tamaño: 1920x1080 px

Interoperabilidad mostrar que las personas pueden chatear por apps distintas una persona inicia una chat por whatsapp y la otra responde por telegram.

**Comment by isahq23** [comment]
Cover 1
![interoperabilidad_cover_1](https://cloud.githubusercontent.com/assets/15214774/18600200/e060a78a-7c32-11e6-8160-c392fe1566b3.jpg)

Cover 2
![interoperabilidad_cover_2](https://cloud.githubusercontent.com/assets/15214774/18600219/e8af4db0-7c32-11e6-8643-2591e51b7e3a.jpg)

Cover 3
![interoperabilidad_cover_3](https://cloud.githubusercontent.com/assets/15214774/18600235/f8fa1f38-7c32-11e6-9096-2299cf271bcf.jpg)

**Comment by arnaldos** [comment]
aqui de alguna form debe mostrarse el nodo, a que el nodo permite la conexion entre usuarios trabajaria un elemento tipo geotag que salga de la persona haciendo enfasis en cada app que esta usando pero el nodo es quien hace de intermediario

**Comment by andiechan** [comment]
01-
![06-01](https://cloud.githubusercontent.com/assets/19866300/18604193/8e12fcc0-7c47-11e6-8997-7a0e7c493f1f.png)

**Comment by arnaldos** [comment]
@andiechan @isahq23 En la imagen debe mostrarse la conexión del usuario1 al nodo y del nodo al usuario 2. en ninguna version se logra el objetivo.

**Comment by andiechan** [comment]
Bueno ahora si versión 1 
![1_iop](https://cloud.githubusercontent.com/assets/19866300/18650967/4ebe6d9c-7e96-11e6-8e25-ab9c302bfbef.PNG)

**Comment by arnaldos** [comment]
falta representar el hecho que se puede interactuar con apps diferentes del misma categoria

**Comment by andiechan** [comment]
Versión 02
![2_iop](https://cloud.githubusercontent.com/assets/19866300/18653319/17a5b3a4-7ea7-11e6-8450-ce37ae39387b.PNG)

Bueno le anexe los iconos de ambas Apps en forma de geotags, no se si anexarle las pantallas
a un costado como hizo Isa anteriormente. Cualquier cosa me comentas.

**Comment by isahq23** [comment]
Cover 4
![interoperabilidad_cover_4](https://cloud.githubusercontent.com/assets/15214774/18655576/720a44e0-7ec0-11e6-8517-89cb9fbc2e5d.jpg)

Algo más así?

**Comment by arnaldos** [comment]
@andiechan Incluye las pantallas tal como sugieres a ver que tal se ven.
- También anexa la letra del nodo que corresponde. 
- El nodo mas grande pudieses reducirlo un poco para que se vea mas aereo.
- Al tipo de la maleta podrías remplazarlo por alguno que este como si estuviese escribiendo o incluye a otra persona cerca en posición como si esta escribiendo y cambias el indicador hacia esa persona.

---

@isahq23 revisa la resolución de las imágenes, esa imagen no tiene sentido, plz busca imágenes que tengan coherencia de la acción que de lo que se quiere mostrar.

**Comment by isahq23** [comment]
Cover 5
![interoperabilidad_cover_05](https://cloud.githubusercontent.com/assets/15214774/18675560/2016dfa4-7f29-11e6-8064-c8060a6b44cd.jpg)

**Comment by andiechan** [comment]
**ICONOS PNG**

![telegram_element_iop-02](https://cloud.githubusercontent.com/assets/19866300/18685536/781122f6-7f46-11e6-974f-87ba26db681c.png)
![whatsapp_element_iop-02](https://cloud.githubusercontent.com/assets/19866300/18685537/7815e84a-7f46-11e6-859a-033711071739.png)

**Comment by isahq23** [comment]
Cover 6
![interoperabilidad_cover_06](https://cloud.githubusercontent.com/assets/15214774/18689847/a3a95cf6-7f61-11e6-9a8c-89d0ae509ab3.jpg)

**Comment by arnaldos** [comment]
### Version 9

![image-6](https://cloud.githubusercontent.com/assets/13594347/18695012/c6ef2d7e-7f7c-11e6-8620-2d3089dca678.jpg)

**Comment by andiechan** [comment]
Versión 10
![10_iop](https://cloud.githubusercontent.com/assets/19866300/18697275/a93ef8f2-7f8d-11e6-9357-63a0270ff556.png)

**Comment by andiechan** [comment]
Versión 11
![11_iop](https://cloud.githubusercontent.com/assets/19866300/18697585/9a5d82f6-7f90-11e6-8ee8-71ea233a62c5.png)

**Comment by Luis-Fernando-Molina** [comment]
Ver mis comentarios en el otro caso sobre el palito 3 veces más largo y la conexión entre nodos.

**Comment by Luis-Fernando-Molina** [comment]
La interoperability se da entre Home Nodes,  no nodos de proximidad.

**Comment by Luis-Fernando-Molina** [comment]
Los iconos de WhatsApp, telegram,  etc pueden ir pero deben decir p2p,  porque no es realmente WhatsApp,  sino la versión p2p..

**Comment by Luis-Fernando-Molina** [comment]
Arnaldo tu versión no se ve que sean diferentes App de chat. Parecen iguales. Falta la de Facebook.  En todos las imágenes debieran estar las 3 más populares. WhatsApp,  Facebook y viber. 

Los nombres  y diálogos en perfecto inglés.

**Comment by isahq23** [comment]
Cover 7
![interoperabilidad_cover_07](https://cloud.githubusercontent.com/assets/15214774/18716236/657f22a8-7ff2-11e6-8bc2-d863df87377b.jpg)

**Comment by arnaldos** [comment]
### Version 12

Luis en la app de facebook cuando se trabaja con grupos el dialogo es naranja, cuando es un chat simmple es azul. aclaro esto antes que me comentes que los colores no son igual de facebook. los dialogos me los paso David.

![image-6](https://cloud.githubusercontent.com/assets/13594347/18733872/a84e4d62-803c-11e6-9b5f-814bf611d21e.jpg)

**Comment by arnaldos** [comment]
@isahq23 coloca los diálogos que pase por el canal ya esta el archivo en illustrator para que extraigas las maquetas. Revisa los comentarios que se están haciendo en el canal. y los que ha hecho luis en el resto de los casos. para que te alinees con los elementos.

**Comment by isahq23** [comment]
Cover 7.1
![interoperabilidad_cover_7 1](https://cloud.githubusercontent.com/assets/15214774/18734119/8972b0ee-8047-11e6-9240-72eb449f792d.jpg)

**Comment by Luis-Fernando-Molina** [comment]
@arnaldos , tu version 12 esta casi perfecta. Yo solo le cambiaria donde dice p2p APP, por "IoP Chat App". El resto dejalo tal cual y el mismo estilo debiera usarse en el resto de la imagenes.

**Comment by Luis-Fernando-Molina** [comment]
Esa imagen, version 12 con eso arreglado es el modelo para todo el resto. Las demas debieran usar los mismos recursos de la misma forma.

**Comment by arnaldos** [comment]
perfecto luis, ya genero el cambio.

**Comment by arnaldos** [comment]
listo !!

![image-6](https://cloud.githubusercontent.com/assets/13594347/18762410/a5fd33a8-80d6-11e6-94da-901123f2bc2c.jpg)

**Comment by Luis-Fernando-Molina** [comment]
Esto casi está. Volvé a asegurarte que el ingles esta ok. Verificalo con Markus o alguien que sepa bien ingles.

**Comment by arnaldos** [comment]
perfecto ya me aseguro de esto !

**Comment by arnaldos** [comment]
Listo !! ya corregido el dialogo. Daniel Scendes me ayudo con esto

![image-6](https://cloud.githubusercontent.com/assets/13594347/18794362/2eb495b8-818d-11e6-8c2c-a084055f5f72.jpg)

**Comment by Luis-Fernando-Molina** [comment]
Sigue mal el ingles.

**Comment by arnaldos** [comment]
Corrección 

![image-6](https://cloud.githubusercontent.com/assets/13594347/18819525/36549190-8360-11e6-97b6-0e0da51dac84.jpg)
