### ISSUE TITLE
Crear imagenes para representar la base de datos de  IOP

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#992]
Tamaño: 1920x1080 px

Ejemplo

Base de usuarios es una base común en IOP ejemplo: si se crea una app de taxi1 y en esta se registran 100 choferes y luego se crea otra app de taxi2 con 100 choferes la base de datos reflejara 200 choferes ya que muestra la cantidad total como si se creara una comunidad de choferes. Esto sucede en cualquier modelo de negocio.

**Comment by Jessicafp** [comment]
Propuesta 1
![propuesta 1](https://cloud.githubusercontent.com/assets/19536846/18605204/7dd27a2c-7c59-11e6-8aad-de2670ec1710.png)

**Comment by arnaldos** [comment]
@Jessicafp esta imagen no representa el concepto, esto va mas con el issue #985

necesitamos ver propuestas para esta imagen

**Comment by emmysm** [comment]
Propuesta 1

![propuesta 2](https://cloud.githubusercontent.com/assets/15143489/18648980/148e429c-7e8b-11e6-9e96-13073aa707f9.png)

Propuesta 2

@arnaldos  @Luis-Fernando-Molina 

![propuesta](https://cloud.githubusercontent.com/assets/15143489/18649146/e16b9396-7e8b-11e6-9453-1af387e002f8.png)

Propuesta 3

![propuesta 3](https://cloud.githubusercontent.com/assets/15143489/18649212/4597515c-7e8c-11e6-8129-4cde14e129e5.png)

**Comment by Jessicafp** [comment]
@arnaldos @Luis-Fernando-Molina 
![propuesta-2](https://cloud.githubusercontent.com/assets/19536846/18649612/6316a50a-7e8e-11e6-815e-aa77294dae00.png)
![propuesta-3](https://cloud.githubusercontent.com/assets/19536846/18649613/63487152-7e8e-11e6-8ee9-6807e443bce6.jpg)

**Comment by arnaldos** [comment]
No se entienden @emmysm los nodos usados no tiene que ver con esa imagen. 
el usario no va a tener un contador de personas. la idea de una vista área podría funcionar. 

@Jessicafp el concepto no se entiende si usas personas trata de que estén interactuando con un dispositivo esta imagen no transmite. 

Este es el concepto que debe transmitir, pero en una imagen en un ambiente real.

![image](https://cloud.githubusercontent.com/assets/13594347/18650459/2a217220-7e93-11e6-9cbf-ae64162d9ff1.png)

**Comment by emmysm** [comment]
![propuesta 4](https://cloud.githubusercontent.com/assets/15143489/18683949/626443ee-7f40-11e6-9be8-67570d7ac380.png)

@arnaldos

**Comment by emmysm** [comment]
Propuesta 5
![propuesta 5](https://cloud.githubusercontent.com/assets/15143489/18684347/d6d8fd4a-7f41-11e6-889d-556acf7dad13.png)

**Comment by arismendi227** [comment]
Propuesta @arnaldos 
![base_de_datosiop](https://cloud.githubusercontent.com/assets/19276382/18687053/51c01e30-7f4c-11e6-9ff1-e9eafa73b8cb.jpg)

**Comment by Jessicafp** [comment]
Propuesta 4 
![nueva-edicion](https://cloud.githubusercontent.com/assets/19536846/18690464/33ed0a48-7f5c-11e6-8ec9-a47d15c23b7a.jpg)

@arnaldos

**Comment by Jessicafp** [comment]
Propuesta 5
![propuesta-5](https://cloud.githubusercontent.com/assets/19536846/18695844/963794cc-7f82-11e6-8bd4-80138ea1bde9.jpg)
@arnaldos

**Comment by arnaldos** [comment]
@Jessicafp para esta propuesta usa los iconos de las apps propias de fermat pera este caso podrias usar el de bitcoin wallet y la fermat wallet oo crypto customer y broker.

**Comment by Jessicafp** [comment]
Propuesta 6
![propuesta-6](https://cloud.githubusercontent.com/assets/19536846/18716571/53687738-7feb-11e6-8f3b-1b454cda760b.jpg)
@arnaldos

**Comment by Jessicafp** [comment]
Propuesta 7
![propuesta-7](https://cloud.githubusercontent.com/assets/19536846/18731746/e07fb29a-802b-11e6-8f3d-77ce451a94d1.jpg)
@arnaldos

**Comment by Jessicafp** [comment]
Propuesta 8
![propuesta-8](https://cloud.githubusercontent.com/assets/19536846/18732690/4e9ada82-8033-11e6-9815-eb45c5b8caae.jpg)
@arnaldos

**Comment by arnaldos** [comment]
@Jessicafp Aca esta mal empleado los iconos que describen que app usa cada usuario. ya que ambas son la misma app uno es de la propia app de chat y la otra identifica la comunity de chat dentro de la app de Fermat todas las comunities permiten encontrar a las personas que usan Fermat según cda categoría. 

En esta imagen se busca representar que 2 o mas apps dentro de Fermat de la misma categoria comparten la misma base de datos, es decir los usuarios pueden interactuar entre si asi usen distintas apps de la misma categoría ya sea de chat, empleo, financiera, etc. @Luis-Fernando-Molina  por favor corrígeme si estoy errado.

**Comment by Jessicafp** [comment]
Propuesta 9
![propuesta-9](https://cloud.githubusercontent.com/assets/19536846/18737177/4c551c3c-805c-11e6-8c15-f777ded4dc7f.jpg)

Propuesta 10
![propuesta-10](https://cloud.githubusercontent.com/assets/19536846/18737178/4c611028-805c-11e6-8e19-67f3bc45ffa8.jpg)

@arnaldos

**Comment by Luis-Fernando-Molina** [comment]
Aca no veo porque usar fotos. Es imposible explicar esto con una foto de fondo.

La cosa viene mas por un grafico o infografico.

**Comment by Jessicafp** [comment]
Propuesta 11
![grafico-fermat](https://cloud.githubusercontent.com/assets/19536846/18758515/6050cc58-80c6-11e6-8a20-2cbb6f2c3ea6.jpg)

propuesta 12
![grafico-fermat-2](https://cloud.githubusercontent.com/assets/19536846/18758516/605a535e-80c6-11e6-9015-50ea8effaaa6.jpg)

propuesta 13
![propuesta-nueva](https://cloud.githubusercontent.com/assets/19536846/18758517/60620180-80c6-11e6-8544-b629ac94c09a.jpg)

@arnaldos @Luis-Fernando-Molina

**Comment by arnaldos** [comment]
@Jessicafp  esto no transmite ! busca otra alternativa para representar el concepto, ve el comentario de luis donde indica no uses foto, has una infografia plz

**Comment by ivonnesantos** [comment]
Propuesta13
![infografia-01](https://cloud.githubusercontent.com/assets/15238660/18843988/53ab211c-83e9-11e6-8efe-324655440942.jpg)
@arnaldos

**Comment by Luis-Fernando-Molina** [comment]
Esto esta mal desde el titulo, no se busca representar la "base de datos de IoP" , IoP no tiene ninguna base de datos. Tiene perfiles de usuarios. Los perfiles son de diferentes tipos. Por cada tipo de perfil puede haber n applicaciones: ejemplo tipo de perfil "Chat User", applicationes: IoP Whatsapp, IoP Messanger, IoP Viber, etc.

Cada app cuando alguien la desarrolla, trae una nueva masa de usuarios a la red.

Lo que quiero mostrar con este slide es que la base de usuarios es compartida. Osea lo que dije antes, que cada IoP app trae nuevos usuarios de un cierto tipo y esto aumenta el total de usuarios de chat. 

Ya no se como explicarlo, fuera de esto me costará dibujarlo yo mismo.

**Comment by emmysm** [comment]
Propuesta 14

![basededatos](https://cloud.githubusercontent.com/assets/15143489/18850233/938ff7ce-8404-11e6-98af-e55bd3e4d500.png)
@arnaldos @Luis-Fernando-Molina

**Comment by victoralfonzohd** [comment]
Propuesta 15
Yo lo veo reflejado de esta manera: @arnaldos @Luis-Fernando-Molina 

![iop-users](https://cloud.githubusercontent.com/assets/15219855/18852004/7685dc72-840c-11e6-8918-fbc395ecaca1.jpg)

**Comment by isahq23** [comment]
Propuesta 16
![iop_01](https://cloud.githubusercontent.com/assets/15214774/18852985/6827776e-8419-11e6-87d0-7d7c08d1b570.jpg)

@arnaldos @Luis-Fernando-Molina

**Comment by ivonnesantos** [comment]
Propuesta 17
![infografia-02](https://cloud.githubusercontent.com/assets/15238660/18853283/567ca5ea-8412-11e6-97c8-bffb1f22eda3.jpg)
@Luis-Fernando-Molina  @arnaldos

**Comment by ivonnesantos** [comment]
Propuesta 18
![infografia-03](https://cloud.githubusercontent.com/assets/15238660/18855227/2d46dc4c-841f-11e6-8b80-1e45a1ecb775.jpg)
Propuesta 19
![infografia-04](https://cloud.githubusercontent.com/assets/15238660/18855233/3118cf7e-841f-11e6-8ca9-14668e7a93ce.jpg)
@Luis-Fernando-Molina @arnaldos

**Comment by victoralfonzohd** [comment]
Propuesta ## 20

![iop](https://cloud.githubusercontent.com/assets/15219855/18855666/91209af2-8422-11e6-99e5-6767bb230088.jpg)

**Comment by rosanacoronado** [comment]
## Propuesta_21

![data base iop chat-01](https://cloud.githubusercontent.com/assets/19508456/18857263/7aa59e18-8430-11e6-9a27-778043430a69.png)

@arnaldos @Luis-Fernando-Molina

**Comment by isahq23** [comment]
Propuesta 22
![iop_02](https://cloud.githubusercontent.com/assets/15214774/18858066/c45aed56-843f-11e6-87a8-3784893967d6.jpg)

@Luis-Fernando-Molina @arnaldos

**Comment by Jessicafp** [comment]
Propuesta 23
![propuesta-23](https://cloud.githubusercontent.com/assets/19536846/18858123/cdeafd50-8437-11e6-9ce6-14c69cd057c4.jpg)

Propuesta 24
![propuesta-24](https://cloud.githubusercontent.com/assets/19536846/18858120/cc34e0b6-8437-11e6-97c6-d35f708e4024.jpg)

Propuesta 25
![propuesta-26](https://cloud.githubusercontent.com/assets/19536846/18858122/cc40138c-8437-11e6-8d8b-9e22441d56ec.jpg)

@arnaldos @Luis-Fernando-Molina

**Comment by rosanacoronado** [comment]
## Propuesta_27

![iop chat users_2-01](https://cloud.githubusercontent.com/assets/19508456/18859527/e27e570c-8442-11e6-9100-3e2881dbf3e9.png)

@arnaldos @Luis-Fernando-Molina

**Comment by arnaldos** [comment]
hola rosana me gusta tu propuesta 27 lo unico que cambiaría seria el icono del chat de fermat por el de otra app conocida como line u otra y le pondria la etiqueta de IOP CHat sobre los iconos.

Jesica para tu version 24 puede me gusta los elementos que usas pero no usaria el fondo del website busca una similar al que uso rosana algo mas por ese estilo.

A nivel general explique el concepto, nose si usando dentro de la misma infografia usar otro ejemplo con otro seriado de apps que se muestren uno a la derecha y otro a la izquierda. tal ves creo de esta manera puede explicarse el data users

**Comment by m471c4** [comment]
Propuesta 28:

![iop1](https://cloud.githubusercontent.com/assets/13468350/18863485/84dc9772-845f-11e6-8914-19729078eada.png)

**Comment by Luis-Fernando-Molina** [comment]
1. Los usuarios se miden en millones. 350 M  por ejemplo
2. Una mezcla de la propuesta 16 con la 21 es lo que se necesita.

Los usuarios de cada app (16) deben verse con un conjunto (en matematicas) que se intersecta con usuarios de otras apps.

La union de todos los conjuntos son los usuarios de IoP Chat Apps

**Comment by isahq23** [comment]
Propuesta 29
![iop_04](https://cloud.githubusercontent.com/assets/15214774/18880953/08d6aefa-84b0-11e6-8517-b60f81bd0f96.jpg)

Propuesta 30
![iop_03](https://cloud.githubusercontent.com/assets/15214774/18881331/40766ce6-84b1-11e6-9fc0-716b6b89b0d9.jpg)

@Luis-Fernando-Molina @arnaldos

**Comment by Luis-Fernando-Molina** [comment]
La verdad que esperaba ver una docena de propuestas con mi ultimo comentario y solo veo una. Que pasa con el resto?

"Los usuarios de cada app (16) deben verse con un conjunto (en matematicas) que se intersecta con usuarios de otras apps." esta parte fue ignorada.

Los guio un poco mas:

Hacer una "bolsa" por cada tipo de APP de las que estan en la ultima imagen. En cada bolsa poner hombrecitos del color de la app. Las bolsas deben solaparse y donde lo hacen deben tener hombrecitos de los colores de las apps de las bolsas que se solapan.

**Comment by arnaldos** [comment]
> La verdad que esperaba ver una docena de propuestas con mi ultimo comentario y solo veo una. Que pasa con el resto?

Entiendo quieras mas propuestas pero mientras se resuelven los últimos comentario, el resto esta trabajando en propuestas para las otras imágenes, a veces se complica ya que se tienen que que buscar muchas imágenes que siendo gratis es muy complicado conseguir algo muy especifico a la idea que se busca representar.

**Comment by isahq23** [comment]
@Luis-Fernando-Molina en ambas propuestas los que cambia en sí es el fondo, tienen patrones distintos. Fusioné ambas propuestas con lo que supuse eran los elementos que esperabas de cada una.

Ahora, tengo unas preguntas:
1. A qué te refieres con un conjunto en matemáticas? Si puedes darme un ejemplo sería genial.
2. Las "bolsas" representarían círculos que contienen "hombrecitos"? A eso te refieres?

**Comment by victoralfonzohd** [comment]
Cuando Luis habla de un conjunto matemático, se refiere al concepto base de las funciones..

Una App IoP va a estar relacionada con un numero o cantidad de usuarios.. X - (0). Entonces:

Tenemos tres funciones donde cada una representa una App IoP de tipo Chat:

 App IoP A - (1,2,3)

App IoP B - (1,2,3)

App IoP C - (1,2,3)

 Entonces la función Base de Datos IoP es: BD - ( A,B,C ).

Cada cunjunto o funcion seria una bolsita, y cada bolsa va estar dentro de una bolsa mas grande, esta seria la bolsa "Base de Datos"

**Comment by Jessicafp** [comment]
Propuesta 31
![propuesta-31](https://cloud.githubusercontent.com/assets/19536846/18922109/65c4e72e-8575-11e6-95de-16474cf6e7c0.jpg)

@arnaldos @Luis-Fernando-Molina

**Comment by victoralfonzohd** [comment]
### Propuesta 32

![iopchat_user](https://cloud.githubusercontent.com/assets/15219855/18924646/f65ccece-857e-11e6-83fe-6290fea28ae6.jpg)

### Propuesta 33

![iop-infografia](https://cloud.githubusercontent.com/assets/15219855/18924666/0977edcc-857f-11e6-8e8d-87263ceacb5d.jpg)

**Comment by Jessicafp** [comment]
Propuesta 34
![propuesta-34](https://cloud.githubusercontent.com/assets/19536846/18925549/5f4412b4-8582-11e6-8d8d-5a1019e1fe2d.jpg)

@arnaldos @Luis-Fernando-Molina

**Comment by isahq23** [comment]
Propuesta 35
![iop_05](https://cloud.githubusercontent.com/assets/15214774/18927397/19c704a2-8592-11e6-9b4e-6a8db67a8a9d.jpg)

@Luis-Fernando-Molina

**Comment by Luis-Fernando-Molina** [comment]
La 35 es la que mas se aproxima. 
1. Por favor quita las personas blancas por fuera de las bolsas de otras apps. 
2. IoP chat users , la cantidad debe ser igual a la suma de todas las otras cantidades.
3. Mostra mas solapamiento entre los conjuntos. En la parte solapada el muñequito debe tener ambos colores de las dos aplicaciones que comparten usuarios.
4. En el centro pone el logo de IoP
5. Los tipitos por fuera de todo conjunto, reemplazarlos con algun pattern que no sean tipitos. 
6. Pudiera ser con el fondo de la propuesta 34

**Comment by victoralfonzohd** [comment]
@Luis-Fernando-Molina @arnaldos 

### Propuesta 36

![iopchat_user](https://cloud.githubusercontent.com/assets/15219855/18969531/8b3098fa-865b-11e6-8750-2ec04f04786f.jpg)

**Comment by isahq23** [comment]
Propuesta 37
![iop_06](https://cloud.githubusercontent.com/assets/15214774/18970343/4a02d4cc-8667-11e6-9b86-a280cb24c490.jpg)

@Luis-Fernando-Molina listo, revisé la suma final y está correcta.

**Comment by arnaldos** [comment]
me gusta la propuesta 36

**Comment by arnaldos** [comment]
no se que opines @Luis-Fernando-Molina

**Comment by Luis-Fernando-Molina** [comment]
Isa por favor pone el tipo de letra que usaste para los usuarios de IoP en el resto. 

El nro con formato de coma en los miles. 

Los tipos que están en la intersección de los conjuntos,  a cada tipo dividido con una línea diagonal así / y la mitad ponelo de un color y la otra mitad del otro color de la otra App,  para que represente que la misma persona usa dos apps. 

Sigue solo Isa acá.

**Comment by isahq23** [comment]
Propuesta 38
n°1 - misma fuente (OCR A Std), mezcla de colores de users y menos users (se veía muy lleno)
![iop_07-1](https://cloud.githubusercontent.com/assets/15214774/18998061/6e23cc2a-870d-11e6-8907-2dd201db98e3.jpg)

n°2 - misma fuente (Ubuntu), mezcla de colores en users y misma cantidad de users que en la propuesta 37
![iop_07-2](https://cloud.githubusercontent.com/assets/15214774/18998132/a57ed5d4-870d-11e6-9539-b28c59274f1a.jpg)

@Luis-Fernando-Molina  por favor dime cuál de ambas te parece mejor en cuanto a fuente (no estaba muy segura de a cuál fuente te referías) y cantidad de users

**Comment by Luis-Fernando-Molina** [comment]
Arnaldo cerra el caso con la 38.1. Gracias

**Comment by arnaldos** [comment]
ok perfecto !!

**Comment by Luis-Fernando-Molina** [comment]
no me subiste este al media kit
