### ISSUE TITLE
Crear imagen para representar Reputation Node

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#994]
La Red La reputación es una red p2p independiente de los nodos de reputación . Su objetivo principal es almacenar y gestionar la información de la reputación de las personas. Al ser una red agnóstica aplicación, esto permite a la gente para demostrar su reputación a través de varias aplicaciones , casos de uso e incluso industrias . Identidades utilizando el IoP podrían tener entradas en la Red de la reputación .
entradas de reputación son manejados por la identidad . A medida que la gente podría tener varias identidades diferentes que pueden construir reputación de cada uno de ellos por separado . Las personas también pueden vincular las identidades de combinar su reputación. La vinculación se realiza fuera de la red para preservar la privacidad .

Idea de ejemplo:
Crear una imagen con un tipo donde se muestre con un teléfono y la pantalla con tres identidades, a la ves en escena otro usuarios con el mismo patrón y estos se conectan al nodo rojo.  Se podría mostrar una esfera o indicador con el record de la reputación de la persona tipo los likes de Facebook.

**Comment by isahq23** [comment]
Cover 01
![reputation_01](https://cloud.githubusercontent.com/assets/15214774/18797197/2e923822-81a3-11e6-8914-4c87af39f15b.jpg)

algo asi?

**Comment by ivonnesantos** [comment]
Cover 02
![reputacion_nodos_1](https://cloud.githubusercontent.com/assets/15238660/18801322/1063a1a8-81b0-11e6-87c7-dd0d941fa808.jpg)
@arnaldos lo hice con este tipo de pantalla porque es el estilo que se esta llevando

**Comment by solemiliia** [comment]
cover 3 ![reputation](https://cloud.githubusercontent.com/assets/19818549/18805934/188ec7c0-81e9-11e6-86b4-e43d9853a4dd.jpg)

**Comment by ivonnesantos** [comment]
![reputacion_nodos_2](https://cloud.githubusercontent.com/assets/15238660/18811507/a7d280a2-827f-11e6-92ba-3cb2e2c64273.jpg)
@arnaldos

**Comment by Luis-Fernando-Molina** [comment]
1. El nodo de reputacion es el que tiene la R, no la M
2. Lo que tengo que explicar aca es lo siguiente:

En la red de reputación la gente va acumulando RATINGS y REVIEWS que otros hacen de ellos. Estos ratings se acumulan independientemente para cada uno de los perfiles que una misma persona pueda tener. 

Eso quiere decir que las APPs que manejan un tipo de perfil pueden leer la reputacion de una persona para ese tipo de perfil. 

A su vez, como el usuario tiene el control de todos sus perfiles en su telefono, si necesita probar en un determinado momento a alguien que tiene mucha reputacion, el puede combinar la reputacion de varios de sus perfiles y mostrarle a otro esa combinación. 

Necesito una imagen que me sirva como base para explicar lo anterior. No tiene que ser una foto, puede ser un esquema, de hecho sería mejor.

**Comment by isahq23** [comment]
Cover 2
@Luis-Fernando-Molina replanteé un poco la relación entre los elementos, algo más personal.
![reputation_02](https://cloud.githubusercontent.com/assets/15214774/18846768/e1e07e46-83fd-11e6-8c56-87700d86b3b6.jpg)

**Comment by arnaldos** [comment]
### Version 6

En esta versión trato de mostrar que el usuario puede tener 3 identidades distintas y cada una de ellas trabaja de manera independiente al igual que su record o reputación.

![image-10](https://cloud.githubusercontent.com/assets/13594347/18853078/6c2327f8-8411-11e6-9f00-c8128aff1c38.jpg)

**Comment by Luis-Fernando-Molina** [comment]
Los distintos perfiles no se ejemplifican con un texto Profile 1 , 2 y 3. Sino con fotos de la misma persona actuando diferentes roles. Esto ya lo habiamos hecho una vez para el help introductorio de la APP de Fermat. 

Los ratings no se ejemplifican con LIKES, sino con ratings, con hasta 5 estrellas. Los reviews son textos. Por favor informate de estas cosas.

**Comment by arnaldos** [comment]
esta imagen fue cambiada por este caso #1001
