### ISSUE TITLE
Crear imagen que represente como iteractua el IOP Ejemplo 4

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#995]
Un grupo de 3 o 4 mujeres sentadas en un bar o lounge,  bebiendo y charlando. La imagen debe mostrar distintos perfiles de cada una (osea la foto de perfil que cada una pondría en distintas apps) ,  incluyendo el icono de las apps. Una de las persona debe ser de profesión médica,  y una de las apps debe ser de médicos. 

Para este caso,  sacar del perfil de médica una extensión y mostrár una red de pacientes que han puesto un rating sobre ella,  y una serie de reviews pero con un texto tan chico que no se pueda leer.

**Comment by rennyx7** [comment]
Propuesta 1: es solo el primer borrardor para ir haciendo las correcciones e ir entendiendo que es lo q se quiere.

![propuesta1](https://cloud.githubusercontent.com/assets/20045567/18898011/c34e6ca4-84fc-11e6-958a-1185304f045e.jpg)

**Comment by Luis-Fernando-Molina** [comment]
Mas o menos.

1- No estan en un lugar publico como un bar o lounge
2- Se debe mostrar un icono por cada perfil como los que teniamos en los infograficos de Fermat, en el caso de un dentista, un diente, de un doctor un estetoscopio, si juega un deporte, lo que sea que lo represente. 

Releer las instrucciones originales.

**Comment by arnaldos** [comment]
infografia que se refiere luis anexo imagen https://github.com/Fermat-ORG/media-kit/blob/master/MediaKit/Infographies/Graphic_internet_of_people/Graphics_Internet-of-people.png

**Comment by m471c4** [comment]
Propuesta 2:

![new_reputation2](https://cloud.githubusercontent.com/assets/13468350/18934918/9cffd3f4-85aa-11e6-8c07-62cdbf426cd2.png)

@Luis-Fernando-Molina @arnaldos

**Comment by Luis-Fernando-Molina** [comment]
1. Los iconos deben idicar de alguna manera a que persona pertenece. 
2. Ademas del icono debe salir las fotos de perfil. como medica, como odontoloca o como peluquera.
3. No solo deben ser profesiones y no solo un icono por persona, sino media docena como minimo por cada una.
4. La parte del perfil con nombre , que hace y reviews esta bien.
5. el logo de dode trabaja debe estar conectado al icono de medica. Lo mismo el perfil en texto debe estar conectado.
6. Lo de instagram y facebook esta de mas, no se que hace ahi.

**Comment by emmysm** [comment]
![propuesta 4](https://cloud.githubusercontent.com/assets/15143489/18960806/f96409d8-8638-11e6-9b58-d79bfcd6cdc9.png)
propuesta 3

**Comment by m471c4** [comment]
Propuesta 4:

![new_reputation3](https://cloud.githubusercontent.com/assets/13468350/18971476/2d667a66-8663-11e6-8586-0da6838ba83d.png)

@Luis-Fernando-Molina @arnaldos

**Comment by victoralfonzohd** [comment]
Propuestas realizadas por @emmysm.

@Luis-Fernando-Molina  @arnaldos 

### Propuesta 5

![img-20160929-wa0011](https://cloud.githubusercontent.com/assets/15219855/18975863/520a404c-867b-11e6-81de-3bdf72fe6c16.jpg)

### Propuesta 6

![img-20160929-wa0007](https://cloud.githubusercontent.com/assets/15219855/18975858/4247b16c-867b-11e6-9a28-6e037b8fc44b.jpg)

**Comment by Luis-Fernando-Molina** [comment]
Solo sigue propuesta 4.

En general esta bien. No se entiende como una peluquera además puede ser médica como algo secundario. 

El icono principal ponelo dentro del círculo con los otros,  así más grande como esta. 

El icono de la empresa conectalo con el de médica,  no con los audífonos como esta ahora. 

Tampoco la dentista como puede ser médica. 

Corregí eso por favor.

**Comment by ivonnesantos** [comment]
@Luis-Fernando-Molina yo entiendo que su amiga la que esta junto a ella es peluquera y la chica de pelo rojo es medico

**Comment by m471c4** [comment]
@Luis-Fernando-Molina @arnaldos mejoré el icono del estetoscopio y apliqué las correcciones de las profesiones:

![new_reputation4](https://cloud.githubusercontent.com/assets/13468350/19011795/a7e61da2-876f-11e6-81b7-d18de916ca1d.png)

**Comment by Luis-Fernando-Molina** [comment]
Entonces la médica también es mecánica? 

Y tiene 22 años de experiencia como médica una persona que por la foto tiene menos de 30?

**Comment by m471c4** [comment]
@Luis-Fernando-Molina @arnaldos correcciones aplicadas, cambié los años de esperiencia y el año de graduación de la médico.

![new_reputation_final](https://cloud.githubusercontent.com/assets/13468350/19082808/b33488d6-8a2d-11e6-98b9-5ebe71a1c9fd.png)

**Comment by Luis-Fernando-Molina** [comment]
Listo, subilo al media kit por favor.

**Comment by Luis-Fernando-Molina** [comment]
Perdon, recien me doy cuenta, debajo de la foto de cada una debe salir su nombre y apellido de manera que quede bien.

**Comment by Luis-Fernando-Molina** [comment]
En el mismo formato en el que sale en el caso del auto.

**Comment by m471c4** [comment]
@Luis-Fernando-Molina @arnaldos ¡listo! Puse un poco girada la etiqueta del nombre para que no chocara con las profesiones. 

![reputation_final](https://cloud.githubusercontent.com/assets/13468350/19086489/63c7b1b0-8a3c-11e6-979b-ec83f6182812.png)

**Comment by Luis-Fernando-Molina** [comment]
ok, ahora si subilo al media kit por favor

**Comment by arnaldos** [comment]
ya esta en el media kit
