### ISSUE TITLE
Crear imagen que represente como interactua el IOP ejemplo 1

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#996]
Escena de noche,  un tipo manejando parado en un semáforo,  mirando por la ventana del acompañante que esta cerrada,  al lado un auto parado donde van un grupo de chicas,  arregladas como saliendo un sábado a la noche. También con el vidrio bajo. El tipo las apunta con su celular como para sacarles una
foto pero sobre la foto se ven los perfiles al menos de la que conduce el otro auto.

Si no consiguen una foto así,  componer una en photoshop con imagenes de otras.

**Comment by saraguerrerot** [comment]
ese perfil debe ser de alguna interfaz conocida? o? .. @arnaldos

**Comment by victoralfonzohd** [comment]
### Propuesta 1

@arnaldos  @Luis-Fernando-Molina 

![nearby-node-caso-4](https://cloud.githubusercontent.com/assets/15219855/18895270/5cf800ca-84e6-11e6-946a-67f65485b518.jpg)

**Comment by proseuz** [comment]
## **Propuesta 2**

@arnaldos @Luis-Fernando-Molina
![caso 4-01](https://cloud.githubusercontent.com/assets/17308060/18901424/c541288c-8518-11e6-8da1-5a85d2122aaa.jpg)

**Comment by Luis-Fernando-Molina** [comment]
Se estan poniendo cosas de otros casos que aca no se han pedido. Leer las instrucciones y poner lo que se describe ahi.

**Comment by Luis-Fernando-Molina** [comment]
Los autos deben estar uno al lado del otro parados en el mismo semaforo. La imagen es una captura del telefono del conductor (que no se ve el) de realidad aumentada de lo que el telefono le muestra a esta persona cuando con la camara apunta al auto del lado. Esto incluye los perfiles de las personas que estan ahi y la posibilidad de llamar a algunas de ellas.

**Comment by victoralfonzohd** [comment]
### Propuesta 3

 @arnaldos  @Luis-Fernando-Molina 

![iop-4](https://cloud.githubusercontent.com/assets/15219855/18933232/d7552ff8-85a1-11e6-81a2-a377442109af.jpg)

**Comment by karentvillegas** [comment]
### Propuesta 4

@arnaldos @Luis-Fernando-Molina 
![propuesta1](https://cloud.githubusercontent.com/assets/19273211/18933818/935a05fa-85a4-11e6-9a50-dd4bda546cd5.jpg)

**Comment by proseuz** [comment]
## Propuesta 5

![caso 4-02](https://cloud.githubusercontent.com/assets/17308060/18944159/e26b8194-85f1-11e6-9a0a-ed7fc15c4ddb.jpg)
@Luis-Fernando-Molina  @arnaldos

**Comment by Luis-Fernando-Molina** [comment]
Nadie entendio que la imagen es desde la perspectiva del conductor de un auto? porque me muestran las fotos desde afuera del auto? Por favor releer todo lo que escribi.

**Comment by proseuz** [comment]
## Propuesta 6

![caso 4-03](https://cloud.githubusercontent.com/assets/17308060/18962416/c3a9557c-863e-11e6-9d1d-606fc429e04a.jpg)
@Luis-Fernando-Molina

**Comment by karentvillegas** [comment]
### Propuesta 7

@arnaldos @Luis-Fernando-Molina 
![propuesta2](https://cloud.githubusercontent.com/assets/19273211/18976577/cd1a20ea-8680-11e6-9f55-826db28c98d2.jpg)

**Comment by Luis-Fernando-Molina** [comment]
Seguir con la imagen de fondo de la propuesta 7 y entre todos mejorar el resto (el teléfono,  los gráficos,  como se muestran,  etc). 

Debería aparecer de manera similar al gráfico del caso de las 3 chicas, pero con la opción grande de llamar,  o chatear.

**Comment by victoralfonzohd** [comment]
@arnaldos  @Luis-Fernando-Molina 

### Propuesta 8

![propuesta8](https://cloud.githubusercontent.com/assets/15219855/19004115/3ca2e644-8722-11e6-9aee-3abeb27b5214.jpg)

**Comment by ivonnesantos** [comment]
propuesta 9
![scan](https://cloud.githubusercontent.com/assets/15238660/19010072/d8ac0482-8748-11e6-8db0-2b44910f7801.jpg)
@Luis-Fernando-Molina @arnaldos

**Comment by karentvillegas** [comment]
### Propuesta 10

![propuesta3](https://cloud.githubusercontent.com/assets/19273211/19010809/1db9652c-8755-11e6-93cd-371f8ecda521.jpg)

### Propuesta 11

![propuesta4](https://cloud.githubusercontent.com/assets/19273211/19010813/27873674-8755-11e6-8093-7fc54f54050e.jpg)

@arnaldos @Luis-Fernando-Molina

**Comment by proseuz** [comment]
## Propuesta 12

![caso 4-04](https://cloud.githubusercontent.com/assets/17308060/19011073/05b146a2-875a-11e6-8caa-357f4db1c1f8.jpg)
@Luis-Fernando-Molina @arnaldos

**Comment by Luis-Fernando-Molina** [comment]
La mejor es la 12. 

Solo faltaria agregarle unos iconitos mas chicos que representen los distintos sub perfiles que estas personas tendrian (profesion, hobbies, lo que sea), estos iconos, mas chicos pudieran estar del lado derecho de la burbuja.

Por favor ponele nombres ingleses reales a las personas, en correcto ingles.

**Comment by proseuz** [comment]
## Propuesta 12.1

![caso 4-04-04](https://cloud.githubusercontent.com/assets/17308060/19058347/7fde82ea-89a4-11e6-99cd-b5c5d5a71794.jpg)
@Luis-Fernando-Molina

**Comment by arnaldos** [comment]
@jhonmarquez92  coloca el texto del usuario que siga la forma de l circulo

**Comment by proseuz** [comment]
## Propuesta 12.2

![caso 4-04-04-04](https://cloud.githubusercontent.com/assets/17308060/19062653/e5366d9a-89c9-11e6-9891-e8c36ed225fc.jpg)
@arnaldos @Luis-Fernando-Molina

**Comment by arnaldos** [comment]
creo podemos cerrar el caso con la propuesta 12.2 que opinas @Luis-Fernando-Molina  ?

**Comment by Luis-Fernando-Molina** [comment]
El nombre de una no coincide con lo que se ven en el teléfono 

El icono de la profesión es un poco más grande que el resto.

**Comment by proseuz** [comment]
## Propuesta 12.3

![caso 4-04-04-04-04](https://cloud.githubusercontent.com/assets/17308060/19085519/9169df84-8a38-11e6-9281-7fb7f18918a3.jpg)
@Luis-Fernando-Molina @arnaldos

**Comment by Luis-Fernando-Molina** [comment]
Listo pasalo a media kit
