### ISSUE TITLE
Crear imagen que represente como iteractua el IOP Ejemplo 3

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#997]
Un joven mira desde el balcón de su departamento que en el edificio del frente hay una fiesta. La imagen debe mostrar que con una App IoP de party el tipo se conecta al grupo donde los de la fiesta están conectados,  y dice go así:

Hey neighbors! It's Josh from the 8A at the building in front of you.

Hi Josh,  it's Julia's birthday,  hope we are not disturbing with the music. Want to join us?

**Comment by andiechan** [comment]
**Propuesta 01**
![01](https://cloud.githubusercontent.com/assets/19866300/18892179/8654169e-84d6-11e6-9215-d0a77983e9b9.jpg)

**Comment by andiechan** [comment]
**Propuesta 2**
![02](https://cloud.githubusercontent.com/assets/19866300/18895278/6a79055a-84e6-11e6-8214-a4ef90a9b136.jpg)

**Comment by arnaldos** [comment]
el texto de la etiueta IOP party app en color oscuro

**Comment by Luis-Fernando-Molina** [comment]
De donde sacaste Arnaldo que este caso tiene que ver con la red de proximidad?

La imagen es desde el balcon donde esta el personaje, no desde donde esta la fiesta. Debe ser de noche. Leer el texto original.

**Comment by arnaldos** [comment]
que representan este tipo de imágenes si no es el nodo?

**Comment by ivonnesantos** [comment]
Propuesta 3
Hice lo posible por mezclar varios elementos en un fotomontaje para que se acercara a la imagen que se describe solo no encontre un edificio en el angulo de frente al otro edificio 
![party_propuesta](https://cloud.githubusercontent.com/assets/15238660/18931101/c23821ec-8598-11e6-85ab-5bb7afed8bd0.jpg)
 @arnaldos @Luis-Fernando-Molina

**Comment by ivonnesantos** [comment]
Propuesta 4
![party_propuesta_3](https://cloud.githubusercontent.com/assets/15238660/18969585/be84cac8-865b-11e6-95c2-c11dae986b66.jpg)
@Luis-Fernando-Molina @arnaldos en este caso puse al personaje sin ver directamente a la fiesta para que no se vea tan sugestivo.

**Comment by Jessicafp** [comment]
Propuesta 5
![propuesta 4](https://cloud.githubusercontent.com/assets/19536846/18970322/d128c488-865e-11e6-9b98-503e8d562e3e.jpg)
@arnaldos @Luis-Fernando-Molina

**Comment by arnaldos** [comment]
propuesta 5

**Comment by arnaldos** [comment]
solo cambiaría en el zoom del apartamento si es posible colocar a la otra persona escribiendo en el con su telefono en medio de la fiesta

**Comment by Jessicafp** [comment]
Propuesta 6
![propuesta-6](https://cloud.githubusercontent.com/assets/19536846/18978313/2352eece-8690-11e6-8313-6814ff6f6ec9.jpg)
@arnaldos @Luis-Fernando-Molina

**Comment by arnaldos** [comment]
versión 6

**Comment by arnaldos** [comment]
pero ajusta el chat de la chica, la del teléfono esta bien. pero el que simula el de la chica las burbujas de los mensajes van invertidos.

**Comment by Jessicafp** [comment]
Propuesta 7
![propuesta-7](https://cloud.githubusercontent.com/assets/19536846/18981642/4c383a38-86ae-11e6-816d-0082f48b79ad.jpg)
@arnaldos @Luis-Fernando-Molina

**Comment by Luis-Fernando-Molina** [comment]
Seguimos con Jessica propuesta 7. 

Saca por favor la última burbuja del diálogo. 

Falta el icono de la App. 

No puede decir contacs,  sino Neighbors.

**Comment by Jessicafp** [comment]
Propuesta 8
![propuesta-8](https://cloud.githubusercontent.com/assets/19536846/19012043/50da5b6a-8777-11e6-8adf-74d22e890200.jpg)
@arnaldos @Luis-Fernando-Molina

**Comment by arnaldos** [comment]
creo que podemos cerrar este caso

**Comment by Luis-Fernando-Molina** [comment]
Desapareció la frase "Want to join us?" 

Y hay un signo de pregunta en la primera oración que la verdad que no entiendo para que esta.

**Comment by arnaldos** [comment]
usa este icono plz 
![image](https://cloud.githubusercontent.com/assets/13594347/19090721/12de8b74-8a56-11e6-92c1-aac80e45db64.png)

**Comment by Jessicafp** [comment]
Propuesta 9
![propuesta-9](https://cloud.githubusercontent.com/assets/19536846/19091399/70a3f998-8a50-11e6-8422-b12a292b7cde.jpg)

@arnaldos @Luis-Fernando-Molina

**Comment by Luis-Fernando-Molina** [comment]
Pasala a media kit

**Comment by arnaldos** [comment]
perfecto !
