### ISSUE TITLE
Crear imagen que represente como iteractua el IOP ejemplo 2

### ISSUE THREAD

**Issue by arnaldos** [bitDubai/fermat-graphic-design#998]
Un tipo en un parque muy lindo mirando su celular,  parado como decidiendo que va a hacer. Pasando unos árboles,  atrás a 300 m no se ve en la imagen un grupo de gente tocando la guitarra (se ve por una serie de imágenes que postearon en un grupo de un evento que este tipo esta viendo).  

En otra dirección a 550 m un grupo de gente jugando al voleibol por ejemplo (puede ser otro juego en equipos que se juegue en un parque) ,  esto el lo ve por otra App de voleibol que esta gente usa y que indica que hay dos lugares disponibles para participar.

**Comment by isahq23** [comment]
Propuesta 1
@arnaldos 
![nearby_1](https://cloud.githubusercontent.com/assets/15214774/18897490/3e036248-8501-11e6-8ffa-a9404a3a099a.jpg)

**Comment by rosanacoronado** [comment]
@arnaldos 

## Propuesta 2.1

![nearbynode_case6_3-01](https://cloud.githubusercontent.com/assets/19508456/18906989/d2ea54ee-8537-11e6-996b-467e07420574.png)

## Propuesta 2.2

![nearbynode_case6_4-01](https://cloud.githubusercontent.com/assets/19508456/18907412/8b32fd70-8539-11e6-9d47-c720bccb5f99.png)

**Comment by Luis-Fernando-Molina** [comment]
No se de donde sacaste el titulo de poner nodos de proximidad.

Las propuestas de Rosana se aproximan, pero le falta. La 2.2 va mejor.

**Comment by Luis-Fernando-Molina** [comment]
El tipo se debe ver mejor de atras, y la imagen debe parece una screen shot de su propio celular con augmented reality donde la persona esta viendo las opciones de lo que se puede hacer en ese parque  mientras mueve la camara del telefono.

Quizas la persona no deba aparecer y que la imagen represente la realidad aumentada que el telefono le muestra mientras escanea que se puede hacer con la camara. Asi que no van las imagenes de las app, sino otra forma de mostrarlo, imaginense una realidad aumentada ahi.

**Comment by isahq23** [comment]
Propuesta 3
![nearby_2](https://cloud.githubusercontent.com/assets/15214774/18928445/82e889c0-8596-11e6-81e5-fe05f4c4ece7.jpg)

Tomando en cuenta elementos que @rosanacoronado realizó (app's screens) para mantener el mismo estilo de trabajo, pero con el fondo y el personaje de mi propuesta.
@Luis-Fernando-Molina

**Comment by rosanacoronado** [comment]
@arnaldos @Luis-Fernando-Molina 

## Propuesta 4.1

![case6_3-01](https://cloud.githubusercontent.com/assets/19508456/18930092/bda4dca0-8594-11e6-9ad5-bc487cb8d1f3.png)

## Propuesta 4.2

![case6_4-01](https://cloud.githubusercontent.com/assets/19508456/18930261/5ac7783a-8595-11e6-9e57-31e5d99f06d3.png)

## Propuesta_4.3

![case6_5-01](https://cloud.githubusercontent.com/assets/19508456/18930342/abb1334e-8595-11e6-8ed4-3cbb2863b62a.png)

**Comment by solemiliia** [comment]
5  
![623](https://cloud.githubusercontent.com/assets/19818549/18930272/66741bc0-8595-11e6-8f20-6337fe1744ba.jpg)

**Comment by isahq23** [comment]
Propuesta 6
![nearby_3](https://cloud.githubusercontent.com/assets/15214774/18933994/c4808150-85ad-11e6-8adb-cced11eb95ba.jpg)

**Comment by rosanacoronado** [comment]
@arnaldos @Luis-Fernando-Molina propuestas añadiendo al personaje

Propuesta_7.1
![nearbyn_case6_1-01](https://cloud.githubusercontent.com/assets/19508456/18942036/e7eb6656-85e3-11e6-984d-0c96adb685e4.png)

Propuesta_7.2
![nearbyn_case6_2-01](https://cloud.githubusercontent.com/assets/19508456/18942042/ef1520e8-85e3-11e6-8036-b760aab06528.png)

**Comment by Luis-Fernando-Molina** [comment]
Lo mas parecido es la propuesta 7.1 pero:
1. La foto del parque no tiene la calidad apropiada
2. La persona no debiera aparecer, ni su telefono tampoco
3. La imagen debiera mostrar el radar de la 4.1
4. Los eventos se ven mas o menos bien, faltaria que en el de volley se diga que falta 1 jugador y que tocando un botoncito ahi (si el tipo le hiciera zoom), aplica para ingresar al juego.
5. Los dos eventos estan a simple vista en la foto, uno de ello debiera estar detras de los arboles 
6. Reemplza guitar concert por Guitar with Friends .
7. Poné mas eventos mas lejanos, en la ciudad, que se distingan poco que son pero que se vean que existen. 
8. Quita las burbujas y conexiones, eso es otro tema, no este.

**Comment by rosanacoronado** [comment]
@arnaldos @Luis-Fernando-Molina 

Propuesta 8
![nearbyn_case6_3-01](https://cloud.githubusercontent.com/assets/19508456/18980740/59088b86-86a5-11e6-9a7d-16543502b739.png)

Propuesta 9
![nearbyn_case6_4-01](https://cloud.githubusercontent.com/assets/19508456/18980723/20fd4c5e-86a5-11e6-8bb8-6237e6c8392d.png)

**Comment by solemiliia** [comment]
10 
![10](https://cloud.githubusercontent.com/assets/19818549/18991474/bdb1c098-86e6-11e6-9ff2-74eec50ad846.jpg)

**Comment by Luis-Fernando-Molina** [comment]
1. no se de donde sacaron la idea de introducir una maquina de foto y una camara a la imagen. Quitenla por favor.
2. La propuesta 10 es la que mejor interpreta la perspectiva para la información desplegada. 

a) Las personas ahi hablando se ve muy falsa su integracion en la imagen. 
b) Tendrian que verse otros eventos mas lejanos, ya afuera del parque, atras de los arboles, incluso atras de los edificios.
c) El formato grafico no me parece bien. Dentro del evento (de la tarjeta) debieran estar un par de fotos asociadas a los que esta pasando, al evento. Fuera de la tarjeta, como globos, las personas que estan participando.

d) Fan Club o Reading Club no suenan como eventos , sino como asociaciones.

**Comment by arnaldos** [comment]
la imagen de la propuesta 10 no podremos usarla ya que es una imagen paga https://thumb7.shutterstock.com/display_pic_with_logo/1030336/207050221/stock-photo-new-york-june-people-enjoying-relaxing-outdoors-in-central-park-on-june-in-new-york-207050221.jpg

Nota: chicos hay que tener mucho cuidado de usar imágenes pagas ya que nos pueden perjudicar, la única forma de usar imágenes pagas es tener una cuenta en algún stock de imágenes que actualmente no disponemos.

Usemos una imagen similar a la que uso sol en la propuesta 10

**Comment by rosanacoronado** [comment]
@arnaldos @Luis-Fernando-Molina 

Propuesta 11
![iop2](https://cloud.githubusercontent.com/assets/19508456/19067902/36939888-89ee-11e6-81fc-9a0bdb0d8459.png)

**Comment by rosanacoronado** [comment]
Propuesta_12
![iop3](https://cloud.githubusercontent.com/assets/19508456/19068899/7569fe68-89f2-11e6-91e5-f170ab681e88.png)

**Comment by rosanacoronado** [comment]
Cambiando un poco los gráficos @arnaldos @Luis-Fernando-Molina 

## Propuesta_11.2

![nearbyn_case6_5_1](https://cloud.githubusercontent.com/assets/19508456/19084906/47daff26-8a36-11e6-9a47-749bb824d3b6.png)

## Propuesta_12.2

![nearbyn_case6_5_2](https://cloud.githubusercontent.com/assets/19508456/19084913/4bb4f610-8a36-11e6-9494-8e8b21dc6490.png)

**Comment by Luis-Fernando-Molina** [comment]
Voley : no se dice get in,  sino Request to Join

Las imágenes de la gente tienen que estar alrededor del cartel del evento 

Seguimos solo con la 11.2

**Comment by rosanacoronado** [comment]
@arnaldos @Luis-Fernando-Molina 

## Propuesta_11.3

![interaccion iop_ejemplo2](https://cloud.githubusercontent.com/assets/19508456/19092874/cad9c54a-8a56-11e6-83c0-d57e883bbfdd.png)

**Comment by arnaldos** [comment]
Según los comentarios este esta listo !!

**Comment by Luis-Fernando-Molina** [comment]
El tamaño del evento depende de la cercanía y de la cantidad de gente participando. La carrera en la ciudad ponele unas 100 personas y hacela más grande,  manteniendo la posición del evento. Crea otro evento,  un concierto de música mucho más lejano pero con muchaas gente y por eso es visible.

**Comment by Luis-Fernando-Molina** [comment]
- mucha más gente

**Comment by rosanacoronado** [comment]
@arnaldos @Luis-Fernando-Molina para no hacer 100 burbujas con personas y que la visualización sea muy pesada, decidi que se podía colocar en un icono la cantidad de personas que están presentes en el evento, de manera que identifique que existe un gran numero de personas participando, esto seria en casos cuando es una cantidad muy elevada de usuarios

## Propuesta_11.4

![interaccion_iop_ejemplo2](https://cloud.githubusercontent.com/assets/19508456/19122286/c4197074-8af7-11e6-8f99-dd4f821a2e8e.png)

**Comment by rosanacoronado** [comment]
## Propuesta_11.5

los eventos mas lejanos solo muestran la cantidad de usuarios presentes en el evento, sin burbujas de usuarios

![ejemplo2](https://cloud.githubusercontent.com/assets/19508456/19123458/be92f3b4-8afc-11e6-8d48-e039cdac3a14.png)

**Comment by Luis-Fernando-Molina** [comment]
no es lo que pedi

**Comment by rosanacoronado** [comment]
@arnaldos @Luis-Fernando-Molina 

## Propuesta_11.6

![ejemplo2_iopinteraccion](https://cloud.githubusercontent.com/assets/19508456/19140903/078cf4f4-8b5f-11e6-89c4-855a6b6d2da8.png)

**Comment by Luis-Fernando-Molina** [comment]
ahi esta bien, pasalo a media kit por favor

**Comment by arnaldos** [comment]
perfecto !!
