### ISSUE TITLE
Imagen general para representar conexión de los nodos del IOP-londres to website

### ISSUE THREAD

**Issue by ivonnesantos** [bitDubai/fermat-graphic-design#999]
Make a picture with city london. Used as reference #986

**Comment by ivonnesantos** [comment]
Proponsal_1
![london_2](https://cloud.githubusercontent.com/assets/15238660/19057847/f4e0f0fe-89a0-11e6-89a7-89f191c10ad4.jpg)
Proponsal_2
![london_3](https://cloud.githubusercontent.com/assets/15238660/19057848/f4eded72-89a0-11e6-8b20-d3c299ea23e7.jpg)

**Comment by emmysm** [comment]
Proposal 3
![propuesta 1 london](https://cloud.githubusercontent.com/assets/15143489/19060360/89aad5ec-89b5-11e6-91bb-01acb05bd4a5.png)

@arnaldos  @Luis-Fernando-Molina

**Comment by emmysm** [comment]
Propuesta 3.1
![propuesta 2 london](https://cloud.githubusercontent.com/assets/15143489/19060570/41a89c46-89b7-11e6-9af9-e7bbf4225d94.png)

**Comment by Jessicafp** [comment]
Propuesta 5
![propuesta-1-londres](https://cloud.githubusercontent.com/assets/19536846/19062699/49819f36-89ca-11e6-89ee-d5486d3f1ada.jpg)

Propuesta 6
![propuesta-2-londres](https://cloud.githubusercontent.com/assets/19536846/19062700/4a54c168-89ca-11e6-8894-ae114bc281a9.jpg)

@arnaldos @Luis-Fernando-Molina

**Comment by victoralfonzohd** [comment]
@Luis-Fernando-Molina @arnaldos 

### Propuesta 4

![londres-1](https://cloud.githubusercontent.com/assets/15219855/19074389/f24d3150-8a0d-11e6-9944-eb76234848fd.jpg)

### Propuesta 5

![londres-2](https://cloud.githubusercontent.com/assets/15219855/19078026/b91c5104-8a1c-11e6-8b02-6881f6b6644f.jpg)

**Comment by isahq23** [comment]
Propuesta 6
![iop_london_1](https://cloud.githubusercontent.com/assets/15214774/19096230/2d4d8bc0-8a71-11e6-9b22-c1c3513c625d.jpg)
